- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/NodePalette/Model/NodePaletteSortFilterProxyModel.cpp
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/NodePalette/Model/NodePaletteSortFilterProxyModel.h
NodePaletteAutoCompleteModel didn't have a proper parent set up so it
was left dangling after NodePaletteSFPM was destroyed.
Completer model didn't have parent set so it leaked.
This was found when I started using GraphCanvas in EMotionFX (#10963) and ran the test suite. After applying the patch, no more leaks were reported by tests.
> Fix memory leak in NodePaletteSortFilterProxyModel

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Logging/LogPanel_Panel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Logging/StyledLogPanel.cpp
The Logs window in the Asset Processor was showing the incorrect "X" icon for closing tabs. This change applies the secondary TabWidget style in order to get the correct icon.
Before:
After:
Material Editor:
Closes #8607
> Applied secondary style to LogPanel, fixes tab close icon in AP & ME

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
Fixes the following compile error on Mac:
```
In file included from /Users/spham/github/o3de/build/mac/Code/Framework/AzToolsFramework/CMakeFiles/AzToolsFramework.dir/Unity/unity_34_cxx.cxx:13:
/Users/spham/github/o3de/Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp:382:44: error: no viable conversion from 'optional<reference_wrapper<AzToolsFramework::Prefab::Instance>>' to 'optional<reference_wrapper<const AzToolsFramework::Prefab::Instance>>'
InstanceOptionalConstReference instance = owningInstance;
^          ~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/optional:689:41: note: candidate constructor not viable: no known conversion from …
```
> Fix mac compile error related to assigning a non-const to a const reference

- Gems/EditorPythonBindings/Code/Source/ActionManager/PythonActionManagerHandler.cpp
- Gems/EditorPythonBindings/Code/Source/ActionManager/PythonActionManagerHandler.h
- Gems/EditorPythonBindings/Code/Source/ActionManager/ToolBarManagerBus.h
- Gems/EditorPythonBindings/Code/editorpythonbindings_common_files.cmake
Exposed the `ToolBarManagerInterface` APIs from the `ActionManager` to python.
Tested the APIs via test scripts to verify they worked. Here is a simple example of it in action:
```
from azlmbr.action import ToolBarManagerPythonRequestBus
toolbar_id = "o3de.toolbar.editor.tools"
ToolBarManagerPythonRequestBus(bus.Broadcast, 'AddSeparatorToToolBar', toolbar_id, 700)
ToolBarManagerPythonRequestBus(bus.Broadcast, 'AddActionToToolBar', toolbar_id, "o3de.action.edit.undo", 701)
ToolBarManagerPythonRequestBus(bus.Broadcast, 'AddActionToToolBar', toolbar_id, "o3de.action.edit.snap.toggleGridSnapping", 702)
ToolBarManagerPythonRequestBus(bus.Broadcast, 'AddActionToToolBar', toolbar_id, "o3de.action.edit.snap.toggleAngleSnapping", 703)
```
This adds existing actions that …
> Exposed ToolBar ActionManager APIs to Python

- Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
Problem is closing scriptcanvas editor with a non-existing file, the default behavior is to save in place.
The fix is to check whether asset is valid, if not, then we have to save as new file.
To fix https://github.com/o3de/o3de/issues/11479
Tested in editor, there will be save as dialogue popup in this case.
> Fix close editor with an invalid graph file

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
Try to fix #11452 and related #11489
This PR puts up a fix for the save issue happening after create-entity. It updates the cache for the new entity and its parent entity. So, the DOMs in undo cache are correct.
**Next Step (long-term fix):**
Remove DOM cache in Prefab Undo Cache as the previous state can be retrieved from template DOM. It helps avoid more similar issues that might occur other public workflows (e.g. delete, instantiate).
> Prefab | Fix prefab save issue in create entity

- Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/Artifact/Static/TestImpactTargetDescriptor.h
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/BuildTarget/Common/TestImpactBuildGraph.h
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/BuildTarget/Common/TestImpactBuildTarget.h
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/Dependency/TestImpactTestSelectorAndPrioritizer.h
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/Target/Common/TestImpactTarget.h
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/Target/Common/TestImpactTargetList.h
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Source/Artifact/Factory/TestImpactTargetDescriptorFactory.cpp
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Source/Target/Common/TestImpactTarget.cpp
- Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/Target/Native/TestImpactNativeTargetListCompiler.cpp
- Code/Tools/TestImpactFramework/Runtime/Python/Code/Source/Target/Python/TestImpactPythonTargetListCompiler.cpp
- cmake/LYTestWrappers.cmake
- cmake/TestImpactFramework/LYTestImpactFramework.cmake
- cmake/TestImpactFramework/SourceToTargetMapping.in
This PR adds two notable changes:
1. The build type is now identified at build generation time and thus has been moved to the `Target` class from the `BuildTarget` class.
2. The build graph now has 4 walking functions to walk the build and runtime dependencies and dependers of a given target.
> TIAF: Add build graph visitor.

- AutomatedTesting/Gem/PythonTests/editor_test_testing/CMakeLists.txt
EditorTest's self testing modules have become unstable, likely as a side effect of the Python 3.10 update: https://github.com/o3de/o3de/issues/11528
This appears to not affect tests using EditorTest, which do not use the same pytest-within-a-pytest trickery. Disabling these tests while investigation is pending, to help prevent wasting build resources in Automated Review.
Signed-off-by: Kadino <sweeneys@amazon.com>
> Disable unstable self-tests of EditorTest

- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/ComponentModeDelegate.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/ComponentModeDelegate.h
- Gems/GradientSignal/Code/Include/GradientSignal/Components/ImageGradientComponent.h
- Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
- Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.cpp
- Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.h
- Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponentMode.cpp
- Gems/GradientSignal/Code/Source/Editor/EditorImageGradientRequestBus.h
The configuration parameters impact the underlying image data that's being painted, so they shouldn't be editable while in the midst of painting. Without this change, changing the parameters causes errors / asserts to be triggered and leaves things in a generally bad state.
Manually edited images in the Editor and verified that the fields became read-only and writeable as expected.
https://user-images.githubusercontent.com/82224783/186509082-52f4d8c7-6ed6-4b39-96f4-4715e3d1f8c1.mp4
> [Terrain] Make Image Gradient configuration read-only while painting

- Code/Tools/ProjectManager/Source/NewProjectSettingsScreen.cpp
- Code/Tools/ProjectManager/Source/ProjectTemplateInfo.h
- Code/Tools/ProjectManager/Source/PythonBindings.cpp
- Code/Tools/ProjectManager/Source/PythonBindings.h
- Code/Tools/ProjectManager/Source/PythonBindingsInterface.h
- Code/Tools/ProjectManager/Source/TemplateButtonWidget.cpp
- Code/Tools/ProjectManager/Source/TemplateButtonWidget.h
- scripts/o3de/o3de/manifest.py
Making remote templates appear in the templates list and adding status icons and progress bars for downloading. The functionality for using this will be covered in a follow up PR once the PR for the refactor of the download controller has been merged.
> Making remote templates visible

- Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_TransformFunctions_FromRotationScaleAndTranslation.names
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Math/Transform.ScriptCanvasFunction.xml
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Math/Transform.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Math/Transform.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Translation/GraphToLuaUtility.cpp
- Gems/ScriptCanvas/Code/Tests/Libraries/Math/ScriptCanvasUnitTest_Transform.cpp
1. Fix the error when passing default quaternion value, as core math quaternion class doesn't implement default constructor. Instead of using default constructor, we should pass specific identity value like Quaternion(0, 0, 0, 1)
2. Add support to create transform from rotation, scale and translation
Unit test, and tested through Editor
Get following output
```
(Script) - (x=1.0000000,y=0.0000000,z=0.0000000),(x=0.0000000,y=1.0000000,z=0.0000000),(x=0.0000000,y=0.0000000,z=1.0000000),(x=0.0000000,y=0.0000000,z=0.0000000)
(Script) - (x=1.0000000,y=0.0000000,z=0.0000000),(x=0.0000000,y=1.0000000,z=0.0000000),(x=0.0000000,y=0.0000000,z=1.0000000),(x=0.0000000,y=0.0000000,z=0.0000000)
(Script) - …
```
> Fix quaternion default value error

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Window/AtomToolsMainWindow.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowser.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowser.qrc
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/Icons/menu.svg
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/Icons/view.svg
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp
- Changed the default window layout to hide the mini map, bookmarks, and dock the viewport to the bottom of the window.
- Implemented support for saving custom window layouts in the tool’s layouts menu, mirroring what’s available in the main editor. This will be available in materializer and shader management console as well.
- Hiding menu options for unnamed, tabbed dock widgets.
- Replaced asset browser menu icon.
https://github.com/o3de/o3de/issues/3386
https://github.com/o3de/sig-graphics-audio/issues/51
Manual testing in material editor and material canvas, saving and reloading different layouts
> Material Canvas: Support for saving custom window layouts

- Code/Legacy/CrySystem/AZCoreLogSink.h
The CryOutputToCallback function is compiled out in Release builds.
> Adding `[[maybe_unused]]` to fix unused variable warning.

- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
Prior to this PR, the `ReflectionAdapter` tree was not being refreshed when invoking `ChangeNotify` callbacks. This was due to the `ReflectionAdapter` not adding a message handler to `PropertyEditor` nodes, causing the `RequestTreeUpdate` invocation to fail.
This PR adds a message handler for nodes that have `OnChanged` callbacks which covers context elements that expose a `ChangeNotify` attribute.
Example of a combo box value change resulting in a dependent combo box values being refreshed:
**Testing**
- Verified that dependent combo box values are updated now when the contingent dropdown's value changes.
> DPE: Add RequestTreeUpdate callback to relevant nodes in ReflectionAdapter

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentInspector.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentMainWindow.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentInspector.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.h
- Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorMainWindow.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorMainWindow.h
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.cpp
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.h
- Fix this problem in material editor, material canvas, shader management console causing inspector properties to disappear if multiple documents are open then closed. The properties would come back if reselecting the same document.
- Exposed a virtual function from the base main window class for tools to override if they want to override the file save workflow. By default, it opens a save dialog. Shader management console needs to restrict saving files to specific folders.
- Updated material canvas to export material input group names as material type property group display names and descriptions.
- Updated material editor to use a default group display name if one was not specified.
https://github.com/o3de/sig-graphics-audio/issues/51
https://github.com/o3de/o3de/issues/11380 …
> Atom Tools: Fixed issue with properties disappearing from inspector if multiple documents are open and closed

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
This PR enables override authoring for prefabs behind a flag(/O3DE/Preferences/Prefabs/EnableOverridesUx)
Tested manually that overrides authoring works. Will run existing tests before merging that when overrides ux is disabled, everything stays the same.
> Enable prefab override authoring behind a flag

- Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/Artifact/Factory/TestImpactTestEnumerationSuiteFactory.h
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/Dependency/TestImpactDynamicDependencyMap.h
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/Dependency/TestImpactTestSelectorAndPrioritizer.h
- Code/Tools/TestImpactFramework/Runtime/Python/Code/Include/TestImpactFramework/Python/TestImpactPythonRuntime.h
- Code/Tools/TestImpactFramework/Runtime/Python/Code/Source/Dependency/TestImpactPythonTestSelectorAndPrioritizer.h
- Code/Tools/TestImpactFramework/Runtime/Python/Code/Source/TestImpactPythonRuntime.cpp
- Code/Tools/TestImpactFramework/Runtime/Python/Code/testimpactframework_runtime_python_files.cmake
This PR adds the Python test selector. Currently, there is no test coverage as this selector has yet to be integrated into the runtime.
Note: the `continue` statements map to an internal rule rubric that will eventually be part of the dev docs, hence why these noops are left there.
> TIAF: Python Test Selector

- Code/Framework/AzCore/CMakeLists.txt
- Code/Framework/AzCore/Tests/Asset/AssetManagerLoadingTests.cpp
Sandbox 3 flaky AssetManager tests
Ran CTEST command locally:
```
3: Note: Google Test filter = *SUITE_sandbox*
3: [==========] Running 3 tests from 2 test cases.
3: [----------] Global test environment set-up.
3: [----------] 2 tests from AssetManagerClearAssetReferenceTests
3: [ RUN      ] AssetManagerClearAssetReferenceTests.ReloadTest_SUITE_sandbox
3: Waiting for initial asset load to complete
3: Starting reload of asset
3: Waiting for reload to complete
3: Starting another reload of asset
3: Waiting for 2nd reload to complete
3: Test conditions complete, beginning shutdown
3: [       OK ] AssetManagerClearAssetReferenceTests.ReloadTest_SUITE_sandbox (5 ms)
3: [ RUN      ] AssetManagerClearAssetReferenceTests.ReleaseOldReferenceWhileLoadingNewReference_DoesNotDeleteContainer_SUITE_sand …
```
> Sandbox 3 flaky AssetManager tests

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Window/AtomToolsMainWindow.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowserInteractions.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/AtomToolsFrameworkSystemComponent.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
- Gems/Atom/Tools/ShaderManagementConsole/Registry/scripts.shadermanagementconsole.setreg
Shader management console requires a generic method for registering applications specific scripts with the file menu and asset browser context menu. This allows those scripts to be added using the settings registry. The settings can be registered in application specific settings registry files or at runtime, by specifying a category and a list of script paths. If the category name is empty, the script will be added to the top-level menu. When executed from the asset browser context menu, the first selected file is passed in as an argument.
https://github.com/o3de/o3de/issues/11380
Verified that the generate shader varian list script appears in the asset browser context menu and runs when collected. The script currently produces errors but that …
> Atom Tools: Support for registering dedicated Python scripts with SMC, ME, MC

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabUiHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabUiHandler.h
Fix the issue https://github.com/o3de/o3de/issues/11332
1. Display the icon if the prefab has no children (previous condition would only check if the item was collapsed)
2. Handle click on the icon when item has no children (as OnOutlinerItemCollapse will not be called in this disposition)
3. Move 2 local variables into constants to prevent future mismatch
4. Auto format the files with the o3de clang format
Can be seen as a follow-up to 52112be1acaa4c10c5dbc3e7e2a0f5d87ea34148
Used the same repro steps as the issue.
> Show prefab's button "Exit Focus Mode" even when prefab is empty

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
Prior to this PR, there were a couple of places in the DPE where strings could potentially be corrupted when passed to `QString::fromUtf8` as `string_view`s.
This PR makes use of the `QString::fromUtf8` overload which takes an optional str buffer size parameter in order to fix the issue.
After change and before change example:
**Testing**
- Verify strings such as container names (with the "(N elements)" text) are no longer corrupted when adding new elements to the container.
> DPE: Prevent strings from being garbled by fromUtf8

- Code/Framework/AzCore/AzCore/Component/ComponentApplication.cpp
- Code/Framework/AzCore/AzCore/Serialization/Json/StackedString.cpp
- Code/Framework/AzCore/AzCore/Serialization/Json/StackedString.h
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistry.h
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.cpp
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.h
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.cpp
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.h
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryVisitorUtils.cpp
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryVisitorUtils.h
- Code/Framework/AzCore/Platform/Windows/AzCore/IO/Streamer/StreamerConfiguration_Windows.cpp
- Code/Framework/AzCore/Tests/Settings/SettingsRegistryMergeUtilsTests.cpp
- Code/Framework/AzCore/Tests/Settings/SettingsRegistryTests.cpp
- Code/Framework/AzCore/Tests/Settings/SettingsRegistryVisitorUtilsTests.cpp
- Code/Framework/AzFramework/AzFramework/Application/Application.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/SettingsRegistryAdapter.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/SettingsRegistryAdapter.h
- Code/Framework/AzFramework/AzFramework/Gem/GemInfo.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Asset/AssetUtils.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/LocalViewBookmarkLoader.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/LocalViewBookmarkLoader.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewBookmarkLoaderInterface.h
- Code/Framework/AzToolsFramework/Tests/Viewport/ViewBookmarkTests.cpp
- Code/Tools/AssetProcessor/native/InternalBuilders/SettingsRegistryBuilder.cpp
- Code/Tools/AssetProcessor/native/InternalBuilders/SettingsRegistryBuilder.h
- Code/Tools/AssetProcessor/native/tests/InternalBuilders/SettingsRegistryBuilderTests.cpp
- Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp
- Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.h
[[Breaking Change]] The Visit functions on the Settings Registry now supply a struct with the arguments about the field being visited.
This allows future updates to Visit API without changing the API in the future.
The new struct now supplies the `SettingsType` value for the field type, instead of `Type` allowing for querying the signedness of an integer type.
The struct also supplies a reference to the Settings Registry being visited, alliviating the need to bind the SettingsRegistry to the visitor or functor, supplied to visit.
Greatly simplified the PlatformConfiguration parsing of the settings registry for AssetProcessor settings, the LocalBookmarkLoader for the editor bookrmark settings and the StreamerConfiguration for determining if a drive is in use by O3DE
Signed-off-by: …
> Settings Registry Visitor API Updates

- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/AngularManipulatorCircleViewFeedback.cpp
Signed-off-by: guillaume-haerinck <guillaume.haerinck@outlook.com>
Fix for https://github.com/o3de/o3de/issues/11308
1. Limit rotation circle drawing to 2Pi to prevent overlap (else the alpha of the color is increased)
2. Draw start and end radius segments for better feedback
Note : In blender 2.8+, colors overlaps with further rotation. It stays visible as the radius segments have a bigger width, might be a good future change.
Checked with all angles of the gizmo
> No overlap when drawing rotate gizmo and draw start / end segments

- Code/Legacy/CryCommon/IAudioSystem.h
- Code/Legacy/CrySystem/System.cpp
- Code/Legacy/CrySystem/System.h
- Code/Legacy/CrySystem/SystemInit.cpp
- Gems/AudioEngineWwise/Code/Source/AudioEngineWwiseGemSystemComponent.cpp
- Gems/AudioEngineWwise/Code/Source/AudioEngineWwiseGemSystemComponent.h
- Gems/AudioEngineWwise/Code/Source/Engine/AudioSystemImpl_wwise.cpp
- Gems/AudioSystem/Code/Source/AudioSystemGemSystemComponent.cpp
- Gems/AudioSystem/Code/Source/AudioSystemGemSystemComponent.h
- Gems/AudioSystem/Code/Source/Engine/ATL.cpp
- Gems/AudioSystem/Code/Source/Engine/ATLComponents.cpp
- Gems/AudioSystem/Code/Source/Engine/AudioSystem.cpp
- Gems/AudioSystem/Code/Source/Engine/AudioSystem.h
- Gems/AudioSystem/Code/Source/Engine/SoundCVars.cpp
- Gems/AudioSystem/Code/Source/Engine/SoundCVars.h
This addresses a couple instances of shutdown crashes in GameLauncher related to audio Gems.
One fixes how a container of objects was being destructed.
The other changes the lifetime of the `IAudioSystem` interface, so that it's constructed earlier and destructed later. This prevents nullptr dereference.
fixes #11554 
fixes #11557
Run GameLaunchers for projects with and without audio setups.
Quit from levels with and without audio playing.
Ran Editor and exit.
> AudioSystem Gem Shutdown Fixes

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Framebuffer.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Framebuffer.h
The resolution for the Vulkan Framebuffer object is currently taken directly from the original image of the rendertarget - ImageView, even if the ImageView only points to a single mip-level of the image.
This leads to the Vulkan Validation error that the bound rendertarget has a size mismatch with the framebuffer, an eventually causes a device lost.
'manually' fill the mip-levels of a texture with separate Renderpasses. 
Currently only tested on Windows with Vulkan, i did not tested with DirectX.
> Fix rendering to a single mip-level of a texture with vulkan

- Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/Dependency/TestImpactTestSelectorAndPrioritizer.h
This PR implements support for the "Dependency Locality" TestPrioritization policy. This involves exploring the build graph of each of our test targets, calculating the distance to the closest production target in that graph, and ordering our test targets by distance to their closest production target in their build graph.
Previously reviewed and approved in https://github.com/aws-lumberyard-dev/o3de/pull/446
Manual testing, with tests forthcoming.
> TIF Test Prioritizer - Dependency Locality Policy

- Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/MaterialComponentBus.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.h
- Gems/Blast/Code/Source/Editor/EditorBlastMeshDataComponent.cpp
- Gems/EMotionFX/Code/Source/Integration/Components/ActorComponent.h
Renamed the material receiver related buses to material consumer and updated comments.
This did not result in any behavioral changes
> Material Component: Renamed MaterialReceiver* to MaterialConsumer* plus comments

- Code/Tools/LuaIDE/Source/LUA/LUAEditorView.cpp
- Code/Tools/LuaIDE/Source/LUA/LUAEditorView.hxx
ref: https://github.com/o3de/o3de/issues/11586
this correctly handles marking the update state of the document. this is a visual change so this does not change how the lua editor works. 
when creating a new file the document shouldn't be marked with a '*'
> bugfix(Lua Editor): correctly handle marking when creating a new file

- Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
To fix https://github.com/o3de/o3de/issues/11547
For above case, source handle won't get information about the relative path of the graph (which loaded when opening graph). So instead of using source handle to check whether graph is new, we can use tab metadata information to check whether graph is new.
Tested through Editor to confirm the corner case has been fixed.
> Minor fix for close window save corner case

- Code/Tools/LuaIDE/Source/LUA/LUAEditorFindDialog.cpp
this just update the usage with the method pointer variants of signal and slot. I would like to do some improve on the lua editor but I think updating these first would help catch these problems at compile time.
verify that it compiles.
> chore: update usage of signal and slot for LUAEditorFindDialog

- Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.cpp
This commit fixes a bug on Ubuntu 22.04.1 (X display server - XCB input).
When launching "Play Game" using top menu the cursor disappears and does not appear again when changing window
(for example Alt-Tabbing) or after exiting "Play Game" mode. In order for cursor to show up again the Editor should close.
Launching game using hotkey "Ctrl+G" doesn't face this problem.
XCB input implementation tries to keep cursor behavior for itself. This is why when Focus Out (`XCB_FOCUS_OUT`) event 
happens system default cursor behavior is set while when Focus In (`XCB_FOCUS_IN`) the needed behavior is set. However an Focus In event can arrive without an Focus Out just before (I don't know exactly why this happen, my knowledge on XCB is not great). As a result windows in which cursor Hide option is …
> XCB: Reset cursor state if Focus-In is not paired with Focus-Out (Fix hidden cursor bug when "Play Game")

- Code/Framework/AzCore/AzCore/Math/Quaternion.h
- Code/Framework/AzCore/Tests/Math/QuaternionTests.cpp
just noticed these method are the same as Quaternion::CreateFromEulerRadiansXYZ. not too hard to also deprecate these as well and use the methods already in Quaternion.
should be covered by the unit test.
> chore: deprecate both ConvertEulerRadiansToQuaternion and ConvertEulerDegreesToQuaternion

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Operators/Math/OperatorDiv.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Operators/Math/OperatorDiv.h
- Gems/ScriptCanvasTesting/Assets/ScriptCanvas/UnitTests/LY_SC_UnitTest_OperatorDiv.scriptcanvas
ref: https://github.com/o3de/o3de/issues/10232
adds support to vector2/3/4 for the divide node
> feat(ScriptCanvas): add vector2/3/4 to divide node

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceDomGenerator.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabInstanceUtils.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabInstanceUtils.h
This PR fixes the issue of implicit conversion from `InstanceOptionalReference` to `InstanceOptionalConstReference`. It was reported that on macOS the conversion yields error.
```
/o3de/Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp:378:40: 
No viable conversion from ‘optional<reference_wrapper<AzToolsFramework::Prefab::Instance>>’ to ‘optional<reference_wrapper<const AzToolsFramework::Prefab::Instance>>’
```
Fix:
- Use `InstanceOptionalReference` explicitly as what the code in other places is doing.
Minor Changes:
- Use `const Instance*` instead of `InstanceOptionalConstReference` in m_climbedInstances.
Reference:
- Might be related to this: https://stackoverflow.com/questions/65992868/cannot-convert-stdrefere …
> Prefab | Fix prefab instance reference conversion issue

- Code/Framework/AzCore/AzCore/DOM/DomPath.h
- Code/Framework/AzCore/AzCore/Serialization/AZStdContainers.inl
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/KeyQueryDPE.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/KeyQueryDPE.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/KeyQueryDPE.ui
- Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
Adds a mechanism for the DPE to query keys from the user, whenever a new entry is added to an associative container
Note: Although this is functional, it has some rough edges to address in a future PR, possibly by someone other than me:
1) Adapter shows a superfluous root node in the DPE embedded in the key query dialog. This should be suppressed using the same mechanism as AZ::Edit::PropertyVisibility::ShowChildrenOnly.
2) When creating integral types (likesay, an integer) the container does not zero construct the key, so the key query dialog will suggest something like, "-2556236", which isn't a great experience.
3) When triggering the key query, the container reserves a new entry before passing it via the adapter to the DPE. If the …
> added user query for keys when adding to an associative container

- Code/Tools/LuaIDE/Source/LUA/LUAEditorBreakpointWidget.cpp
- Code/Tools/LuaIDE/Source/LUA/LUAEditorBreakpointWidget.hxx
- Code/Tools/LuaIDE/Source/LUA/LUAEditorView.cpp
- Code/Tools/LuaIDE/Source/LUA/LUAEditorView.hxx
this is a refactor of the LuaEditorView and replaces the SIGNAL SLOT with method pointers. I also replaced OnToggleBreakpoint, 
OnBreakpointLineMoved, and OnBreakpointLineDeleted with signals from LUAEditorBreakpointWidget.
opened a lua document verified that breakpoints can be set and closing and opening documents works correctly.
> refactor: minor refactor or LUAViewWidget

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_GPU.py
- AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Sandbox.py
- AutomatedTesting/Gem/PythonTests/PythonAssetBuilder/TestSuite_Periodic.py
- AutomatedTesting/Gem/PythonTests/editor/TestSuite_Main.py
- AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/TestSuite_Main.py
- Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
- Tools/LyTestTools/ly_test_tools/o3de/material_editor_test.py
- Tools/LyTestTools/ly_test_tools/o3de/multi_test_framework.py
Simplifies writing integration tests which use EditorSingleTest and MaterialEditorSingleTest by removing unused boilerplate from their overridable callbacks:
- launcher_platform is already user-parameterized, and tests should not need to access it
- Setup should never need to interact with results
Removes usage from existing tests, which demonstrate the boilerplate-ness of these args.
Tested locally on Windows by executing `ctest -C profile -L "(SUITE_smoke|SUITE_main)" --output-on-failure -j 6`
> Remove boilerplate args from multitest framework

- Code/Legacy/CrySystem/Log.cpp
Examined Editor.log to make sure newlines appeared between messages that didn't end with newline
> Add back newline append when writing to log files

- Code/Framework/AzCore/AzCore/Settings/CommandLine.cpp
- Code/Framework/AzCore/AzCore/Settings/CommandLine.h
- Code/Framework/AzCore/Tests/Settings/CommandLineTests.cpp
The new GetSwitchValue overload which doesn't accept an index returns the last occurance of a command line option.
This helps to prevent user from coding to retrieve the first instance of a switch on a command.
Ex. `commandLine.GetSwitchValue("<switchName>", 0)`.
CLI argument parsing uses the last instance of the parameter as the value.
i.e `command -s 10 -s 20`, for the option for 's', if only one value is used, it should be the last one of 20
Added a unit test for the new GetSwitchValue overload.
> Added a no-index GetSwitchValue overload to AZ::CommandLine

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/Workspace.cpp
Fix the problem that create double actor instance when loading workspace.
Manuel verified. 
This CL will stop saving the createActorInstance command in the workspace file. The actorInstance will be created in the actor component already, so createActorInstance command is not needed anymore.
> Fix the problem that create double actor instances when open workspaces

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsAnyDocument.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsAnyDocumentNotificationBus.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsAnyDocumentRequestBus.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentMainWindow.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowserInteractions.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsAnyDocument.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocument.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentInspector.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystem.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/CreateDocumentDialog.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeConfig.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeSlotConfig.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_files.cmake
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Textures/sample_texture_2d.materialcanvasnode
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.h
- Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.h
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.cpp
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.h
- Created AtomToolsAnyDocument to wrap any serialize and edit context reflected classes to the document system and expose them to the document inspector. 
- Used AtomToolsAnyDocument to register shader source data and dynamic node config as editable document types within material canvas.
- Updated class with construction parameters and different code paths to support loading and saving JSON objects with and without type info and class data because some atom types use nonstandard serializers that don’t include the class the class data.
- Fixed a bug with passing arguments from the asset browser into Python scripts using string views. Script execution was deferred which caused the string view arguments to be invalid by the time the script executed.
- Removed checks for open document state …
> Material Canvas: Initial support for creating and editing shader config and dynamic node config files plus other fixes

- .github/workflows/validation.yaml
- scripts/build/Jenkins/Jenkinsfile
- scripts/build/Platform/Linux/build_config.json
This PR adds a GitHub action workflow to run the validation step and removes the step from the Jenkins AR Pipeline. Validation will still be required to pass in order merge the PR. Also there is no increase in the runtime for the validation workflow (3-4min).
- Maintainers will have visibility into whether validation passes or fails prior to running AR. Checks will run when the PR is created and updated with new commits.
- This will reduce costs a bit since GitHub action usage is free for public repos.
- Validation can still be executed in branch builds by adding `validation` as an override.
This is how the check will appear on a PR:
Tested the new workflow on our fork and created a test PR here: https://github.com/aws-lumberyard-dev/o3de/pull/451
> Move validation step to GtiHub actions

- Gems/Atom/RHI/Code/Include/Atom/RHI/DrawFilterTagRegistry.h
- Gems/Atom/RHI/Code/Include/Atom/RHI/DrawListTagRegistry.h
- Gems/Atom/RHI/Code/Include/Atom/RHI/TagBitRegistry.h
- Gems/Atom/RHI/Code/Include/Atom/RHI/TagRegistry.h
- Gems/Atom/RHI/Code/Tests/TagRegistryTests.cpp
- Gems/Atom/RHI/Code/atom_rhi_public_files.cmake
- Gems/Atom/RHI/Code/atom_rhi_tests_files.cmake
- Adds unit tests for TagRegistry. 
- Enforces Handle usage in TagRegistry instead of just expect users to use a Handle template type.
- Adds a new variant of TagRegistry that allocates bit flags per tag, which is implemented as a thin wrapper of TagRegistry. This could be used to accelerate draw list mask usage in the future, or by other systems that want the ability to reserve bit flags dynamically, without needing to do bit shifting logic themselves.
This doesn't change any existing functionality. The new unit tests were run. ASV and the editor were also run to ensure there weren't any unexpected side effects from the change to the TagRegistry template type.
> Adding unit tests for TagRegistry and a variant of TagRegistry for bit flags

- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/RotationManipulators.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/RotationManipulators.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
- Gems/PhysX/Code/Editor/ColliderRotationMode.cpp
Signed-off-by: guillaume-haerinck <guillaume.haerinck@outlook.com>
When editing a PhysX collider, show the rotation feedback (as done when rotating object).
Suggested by @hultonha on https://github.com/o3de/o3de/pull/11550.
**Changes**
1. Call `DisplayFeedback` in the `ColliderRotationFeedback`
2. CircleViewFeedback is no longer a public member of `RotationManipulators`. Its updates are now handled inside the class by adding hook into the inputs callbacks
3. Subscribe to input callback in the `RotationManipulators` constructor, as when one is missing there can be visual glitches in the rotation feedback
4. Move `RotationManipulators::m_viewAngularManipulator` init in the class initialization list because we can
**In action**
Before : …
> Show rotation feedback when editing PhysX collider

- AutomatedTesting/Gem/PythonTests/largeworlds/landscape_canvas/EditorScripts/TerrainExtenderNodes_ComponentEntitySync.py
- AutomatedTesting/Gem/PythonTests/largeworlds/landscape_canvas/EditorScripts/TerrainNodes_DependentComponentsAdded.py
- AutomatedTesting/Gem/PythonTests/largeworlds/landscape_canvas/EditorScripts/TerrainNodes_EntityCreatedOnNodeAdd.py
- Gems/GraphModel/Code/Include/GraphModel/GraphModelBus.h
- Gems/GraphModel/Code/Include/GraphModel/Integration/GraphController.h
- Gems/GraphModel/Code/Include/GraphModel/Model/Graph.h
- Gems/GraphModel/Code/Source/Integration/GraphController.cpp
- Gems/GraphModel/Code/Source/Model/Graph.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Terrain/TerrainMacroMaterialNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Terrain/TerrainMacroMaterialNode.h
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Terrain/TerrainSurfaceMaterialsListNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Terrain/TerrainSurfaceMaterialsListNode.h
- Gems/LandscapeCanvas/Code/Source/LandscapeCanvasSystemComponent.cpp
- Gems/LandscapeCanvas/Code/landscapecanvas_editor_static_files.cmake
Added Landscape Canvas support for Terrain Macro Material and Surface Materials List nodes. These are the first nodes that can be either wrapped (on a Terrain Layer Spawner) or can be standalone on their own Entity, so Landscape Canvas needed some minor changes to be able to handle both cases (previously assumptions were made that a node could only ever be wrapped or not). Also made sure we never show the Entity Name property on wrapped nodes since it's already shown on the wrapper node.
Updated the automated tests with the new nodes and verified all automated tests still pass. Also did manual testing creating nodes from node palette, wrapper action, right-click menu, and by manually adding components from the Entity Inspector.
> Added Landscape Canvas support for Terrain Macro Material and Surface Materials List nodes

- Gems/Atom/RHI/Code/Source/RHI.Reflect/AttachmentEnums.cpp
Added it to ToString and AdjustAccessBasedOnUsage to avoid the error
"Unkown ScopeAttachmentUsage: 7" when Indirect is used.
Signed-off-by: Joerg H. Mueller <joerg.mueller@huawei.com>
Fixes above mentioned error.
Using a custom data driven pass/pipeline (i.e. json) that included a slot with `Indirect` as `ScopeAttachmentUsage`.
> Adding ScopeAttachmentUsage::Indirect to work.

- Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowserInteractions.cpp
https://github.com/o3de/o3de/issues/10944 reported that duplicating materials from the asset browser could not be opened or used. The duplicate action allowed the user to select a new file name and location before copying the file. Moving material files can break file associations that prevent the material from opening.
This change removes the save dialog and just duplicates in the same folder with a unique numeric suffix. The user can then take explicit action to rename or move the file and update any references.
Manually verified duplicated file is automatically added to the same folder with a unique numeric suffix and no user prompt
> Material Editor: Change asset browser duplicate action to save in the same folder

- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
Signed-off-by: Joerg H. Mueller <joerg.mueller@huawei.com>
Atom does not compile without this fix when `AZ_RPI_ENABLE_PASS_DEBUGGING` is set to 1.
I set `AZ_RPI_ENABLE_PASS_DEBUGGING` to 1, compiled and ran a test project.
> Compile fix for enabled AZ_RPI_ENABLE_PASS_DEBUGGING.

- Gems/ScriptCanvas/Code/Editor/Assets/ScriptCanvasFileHandling.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/GraphSerialization.cpp
This PR is to add extra improved error messages while opening an old SC graph with old spawnable nodes in it.
Tested with the files: [OldSCdata.zip](https://github.com/o3de/o3de/files/9462753/OldSCdata.zip)
Test Result:
- Before the fix:
- After the fix (the dialog content is slightly different):
> Improve error messaging when users need to update scripts to new spawnable APIs

- Code/Framework/AzCore/AzCore/Debug/ITrace.cpp
- Code/Framework/AzCore/AzCore/Debug/Trace.h
- Code/Framework/AzCore/AzCore/o3dekernel_files.cmake
The whole ITrace class needs to be exported for the symbols to resolve
correctly on Android. The `static ITrace*` that keeps the ITrace
instance must come only from the O3DEKernel library, and exporting the
whole class seems to be required to get this to work for Android. Methods
that must be in the O3DEKernel library are now defined in a separate
implementation file.
Fixes #11443.
> Fix the symbol visibility of the ITrace methods for Android

- Gems/LmbrCentral/Code/Source/Shape/EditorAxisAlignedBoxShapeComponent.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorAxisAlignedBoxShapeComponentMode.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorAxisAlignedBoxShapeComponentMode.h
- Gems/LmbrCentral/Code/lmbrcentral_editor_files.cmake
Signed-off-by: guillaume-haerinck <guillaume.haerinck@outlook.com>
Fix https://github.com/o3de/o3de/issues/10937
Created a new class which inherit the base behavior, the only override is for the name
Added an axis-aligned box component in an entity and enter subedit
> Use new class AxisAlignedBoxShapeComponentMode to have the correct display name in subedit

- Gems/MotionMatching/Code/Source/BlendTreeMotionMatchNode.cpp
- Gems/MotionMatching/Code/Source/BlendTreeMotionMatchNode.h
- Gems/MotionMatching/Code/Source/FeatureMatrixStandardScaler.cpp
- Gems/MotionMatching/Code/Source/FeatureMatrixStandardScaler.h
- Gems/MotionMatching/Code/Source/FeatureMatrixTransformer.h
- Gems/MotionMatching/Code/Source/MotionMatchingData.cpp
- Gems/MotionMatching/Code/Source/MotionMatchingData.h
- Gems/MotionMatching/Code/Tests/MinMaxScalerTests.cpp
- Gems/MotionMatching/Code/Tests/StandardScalerTests.cpp
- Gems/MotionMatching/Code/motionmatching_files.cmake
- Gems/MotionMatching/Code/motionmatching_tests_files.cmake
The standard scaler can be used to normalize the feature matrix, the query vector and other data. It standardizes features by removing the mean and scaling to the unit variance. This implementation is mimicing the behavior of the standard scaler from scikit-learn (sklearn.preprocessing.StandardScaler). As we use floats by default, our errors are a bigger, especially if the variance is small as this leads to a division by a small value. In case the calculated standard deviation for a given feature is smaller than the given s_epsilon value, the standard deviation gets force-set to 1.0 to avoid divisions by infinity and preserve the value when doing the transform -> inverse-transform roundtrip.
If the standard deviation is small and basically a feature hardly changes (but does change a …
> Motion Matching: Added standard scaler

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_GPU.py
Skipping gpu tests that fail in nightly build. They are remnants of AtomTest tests which are deprecated. Kept for reference.
> Skipped screenshot gpu tests currently failing.

- AutomatedTesting/Gem/PythonTests/Atom/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Smoke_GPU.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/rhi_validation/RHIValidation_Vulkan_DefaultLevel.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/rhi_validation/vulkan_skip_errors.py
- AutomatedTesting/Levels/DefaultLevel/DefaultLevel.prefab
Added smoke test suite to Atom tests. it includes 2 tests:
1. Run editor with vulkan and validation enabled and fail if vulkan validation tests were detected.
2. Same but running editor with low end pipeline, useful to detect errors when using the low render pipeline (used by mobile devices).
There is a list to add vulkan errors that for some reason we will like to ignore (maybe to fix later if they are harmless).
The smoke gpu tests will run as part of "test_gpu_profile" job in aws nightly build.
Run test locally on nVidia GPU: tests passed
Run test locally with vulkan errors present, it failed correctly and tested adding the error to the ignore list to make it pass.
Run job "test_gpu_profile" on jenkins: smoke tests added passed
```
[2022-08-23T13:26:04.137Z]     Start 168: …
```
> Added Vulkan Validation Smoke Test (run on nightly build)

- Assets/Editor/Prefabs/Default_Level.prefab
Removes console warnings about the usage of deprecated selection component on new levels.
Manually. Will run automated tests before merging.
> Remove deprecated selection component from default level template

- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
Attempt to make error message clearer to users to fix https://github.com/o3de/o3de/issues/8405
Set `editorsv_enabled` to true, deleted ServerLauncher binaries and attempted to play in editor with AutomatedTesting base project.
Logs now state:
```
Disable Accelerators
(MultiplayerEditor) - Editor is listening for the editor-server...
[Error] (MultiplayerEditor) - The ServerLauncher binary is missing! Attempted to find ServerLauncher in the editorsv_process path:"", relative to editor:"E:\dev\o3de\o3de\build\windows_vs2019\bin\profile\AutomatedTesting.ServerLauncher.exe" and relative to the current project:"E:\dev\o3de\o3de\build\windows_vs2019\bin\profile\AutomatedTesting.ServerLauncher.exe". Please build ServerLauncher …
```
> Update Server launcher play-in-editor error message to be more explicit about paths examined.

- Code/Editor/EditorPreferencesPageViewportGeneral.cpp
- Code/Editor/EditorViewportSettings.cpp
- Code/Editor/EditorViewportSettings.h
- Code/Editor/EditorViewportWidget.cpp
- Code/Editor/EditorViewportWidget.h
- Code/Editor/Settings.cpp
- Code/Editor/Settings.h
- Code/Editor/ViewPane.cpp
- Code/Editor/Viewport.cpp
- Code/Editor/ViewportTitleDlg.cpp
ref: https://github.com/o3de/o3de/issues/11253
I made the fov apart of the default preferences and correctly handle updating the fov in the ui and updating the fov for the viewport. Changing the fov in the global prefrences also updates the fov value when viewing the fov in the dropdown for the camera in the viewport. 
- update the fov in the global preferences
- verify fov value when selecting the camera icon in the viewport
- do the reverse operation to compare the values.
- verify the fov correctly applies to the viewport
> bugfix(Editor): correctly handle update fov settings from Global Preferences

- Code/Framework/AzCore/AzCore/JSON/rapidjson.h
- Code/Framework/AzCore/AzCore/Serialization/Json/UnorderedSetSerializer.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.cpp
* turns on SIMD where available
* (Used to enable the map feature, but this is no longer the case).
* Garbage collects after prefab operations so that memory stays
flat.
RapidJSON has config options for using SIMD operations as well as for optimizing lookups using a map, which we were simply not using.
Benchmarks, manual testing, and unit tests.
Benchmarks show a slight improvement in loading RapidJSON from text due to SIMD operations in the text parser.
It also shows the garbage collection resulting in memory being freed after large operations.
> Optimize engine usage of RapidJSON

- Templates/PrebuiltGem/template.json
Fix a typo in the display name of the Prebuilt Gem Template
> Fix prebuilt gem template name

- cmake/Platform/Linux/PAL_linux.cmake
- cmake/Platform/Linux/Packaging/prerm.in
Fixes an issue with the installation debian package where the ```OpenSSL_linux.cmake``` file was included multiple times.
The root cause was the original logic to use the system openssl was in BuiltinPackages.cmake, which is not copied from the source installation but rather generated, so there was logic to append the openssl include. But with commit [d3760da](https://github.com/o3de/o3de/commit/d3760da0ab375a21d67a3be5ecefbedad2440d27) the include was moved to the PAL_Linux system cmake which always gets included. The ```O3DE_BUILTIN_PACKAGES_INSTALL_CODE``` string no longer needs this custom code to be injected.
Fixes https://github.com/o3de/o3de/issues/11743 
Built the installer on Ubuntu 20.04 and followed the repro steps
> Fix ubuntu 20.04 installation issues related to duplicate 3rdParty::OpenSSL duplication

- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/ContextMenuActions/ConstructMenuActions/ConstructPresetMenuActions.cpp
use the same icon for both hover and normal state of color icon for script canvas.
https://user-images.githubusercontent.com/854359/188545833-7eb7adc9-305d-4bd2-8631-37d48f2e3c6b.mp4
follow steps listed in issue ticket
https://github.com/o3de/o3de/issues/11740
> bugfix(Script Canvas): use same icon for both normal and hover for preview color

- Code/Tools/LuaIDE/Source/LUA/LUAEditorDebuggerMessages.h
- Code/Tools/LuaIDE/Source/LUA/LUAWatchesDebuggerMessages.h
- Code/Tools/LuaIDE/Source/LUA/WatchesPanel.cpp
- Code/Tools/LuaIDE/Source/LUA/WatchesPanel.hxx
this is a refactor of the DHWatchesWidget for the watcher panel and replaces the SIGNAL SLOT with method pointers. Also updated the use of the EBus signals with something more standard. 
opened a lua document verify watching variables and local variables.
> refactor: minor refactor of DHWatchesWidget

- Code/Tools/AssetProcessor/native/InternalBuilders/SettingsRegistryBuilder.cpp
The Settings Registry builder uses a filename prefix of
`bootstrap.game.` as a prefix for generating the launchers settings
registry file and the final '.' was incorrectly removed in this
[commit](https://github.com/o3de/o3de/commit/139e535cb8f494d43e6689a8b19ed1905db784f3#diff-8709932f0f3f12cb1ef4041a9245713e5ac46ba615a4b5f3d01b3b83abad7b58R170)
> Added back missing '.' character that was incorrectly removed

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicInterface.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
* Disable parenting an entity from one instance to a parent in another instance
Cherry-pick https://github.com/o3de/o3de/pull/11659 from development branch.
> Disable parenting an entity to another instance (#11659)

- AutomatedTesting/Gem/Code/enabled_gems.cmake
Signed-off-by: Jack Curtis <jcurtisk@amazon.com>
Enables the previously tested PythonCoverage gem in the AutomatedTesting project. This is necessary to enable TIAF to generate coverage of Python tests.
> Enable PythonCoverage gem in automated testing

- Code/Framework/AzCore/AzCore/Math/Frustum.cpp
- Code/Framework/AzCore/AzCore/Math/Frustum.h
- Code/Framework/AzCore/AzCore/Math/Frustum.inl
- Code/Framework/AzCore/Tests/Math/FrustumTests.cpp
- Gems/Atom/Feature/Common/Code/Source/AuxGeom/AuxGeomDrawQueue.cpp
- Gems/Atom/Feature/Common/Code/Source/AuxGeom/AuxGeomDrawQueue.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/AuxGeom/AuxGeomDraw.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
This PR adds support for AZ::Frustum in AuxGeom using code originally written for culling. The original code has been cleaned up an corrected a little but remains largely the same.
As part of this work, the ability to retrieve the corners of a frustum was moved into the AZ::Frustum class itself, along with unit tests to validate the new functionality.
Core math tests were run to ensure new unit test passed. Tested culling debugging in ASV to ensure the frustum draws correctly using the new function.
> Support frustum shape in AuxGeom

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusInterface.h
- Gems/Camera/Code/Source/CameraEditorSystemComponent.cpp
Introduces checks to prevent the creation of camera entities inside a procedural prefab.
Manual testing
> Procedural Prefabs | Disable the ability to create a camera entity inside read-only procedural prefab instance

- Code/Framework/AzCore/AzCore/Math/Crc.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyCRCCtrl.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyCRCCtrl.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI.h
ref: https://github.com/o3de/o3de/issues/9823
Fixes configure setting the tag property in the property window for script canvas. Couple of notes with this widget.
- Its very hard to set a value the cursor is reset so you have to set a single value one by one
- CRC tags are associated with strings would be convenient to let the user pass in a string to set the crc value. not sure how this would work maybe ux would have an opinion. 
https://user-images.githubusercontent.com/854359/188374443-22ffd8b7-d5f5-4853-9509-a430c53d863f.mp4
follow steps in the linked issue ticket.
> bugfix(Script Canvas): Unable to edit Tag in property field

- cmake/TestImpactFramework/ConsoleFrontendConfig.in
- scripts/build/TestImpactAnalysis/Testing/conftest.py
- scripts/build/TestImpactAnalysis/persistent_storage/tiaf_persistent_storage.py
- scripts/build/TestImpactAnalysis/test_impact/base_test_impact.py
Signed-off-by: Jack Curtis <jcurtisk@amazon.com>
Creates explicit path ways for Reports and Changelists, and updates tests to match. Also includes a bugfix where in some cases if a parent folder did not exist our coverage data would not get written.
Manual testing + suite of automated tests
> TIF/ Explicit path ways for reports and Changelists

- Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.cpp
- Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.h
Fixes #11720 
This hides the `Create New Image` option in the `Image Gradient` if the `/O3DE/Preferences/ImageGradient/PaintFeature` feature isn't enabled. Without the paint feature, the user is unable to edit the newly created image, which makes the workflow confusing.
Once the paint feature is complete and enabled by default, this flag will be removed and the `Create New Image` option will be enabled by default as well.
Tested the `Image Gradient` component with the paint feature enabled and disabled and verified the `Create New Image` option is shown/hidden, respectively.
> Hide the create new image option if paint feature isn't enabled

- Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/Link/SingleInstanceMultiplePatchesBenchmarks.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/Link/SingleInstanceMultiplePatchesBenchmarks.h
- Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
This PR adds benchmarks for GetLinkDom and SetLinkDom functions in AzToolsFramework::Prefab::Link class. These benchmarks will be useful if and when the storage format or logic changes to get and set link doms.
Here are the benchmark numbers. The times taken are almost negligible because the current logic simply gets and sets a member variable in the object without doing any additional operations.
```
----------------------------------------------------------------------------------------------------------------
Benchmark                                                                      Time             CPU   Iterations
---------------------------------------------------------------------------------------------------------------- …
```
> Add GetLinkDom and SetLinkDom benchmarks

- Code/Framework/AzFramework/AzFramework/Components/CameraBus.h
- Gems/Atom/Component/DebugCamera/Code/Include/Atom/Component/DebugCamera/CameraComponent.h
- Gems/Atom/Component/DebugCamera/Code/Include/Atom/Component/DebugCamera/NoClipControllerBus.h
- Gems/Atom/Component/DebugCamera/Code/Include/Atom/Component/DebugCamera/NoClipControllerComponent.h
- Gems/Atom/Component/DebugCamera/Code/Source/CameraComponent.cpp
- Gems/Atom/Component/DebugCamera/Code/Source/NoClipControllerComponent.cpp
- Gems/Atom/Feature/Common/Assets/Passes/LowEndPipelineXRLeft.pass
- Gems/Atom/Feature/Common/Assets/Passes/LowEndPipelineXRRight.pass
- Gems/Atom/Feature/Common/Assets/Passes/PassTemplates.azasset
- Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/ViewSrg.azsli
- Gems/Atom/RHI/Vulkan/Code/Source/RHI.Builders/ShaderPlatformInterface.cpp
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RenderPipeline.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/View.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/ViewProviderBus.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/XR/XRRenderingInterface.h
- Gems/Atom/RPI/Code/Source/RPI.Public/RenderPipeline.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/View.cpp
- Gems/Camera/Code/Source/CameraComponent.cpp
- Gems/Camera/Code/Source/CameraComponentController.cpp
- Gems/Camera/Code/Source/CameraComponentController.h
- Extend XR interface API to support XR device data related to controller, headset tracking. 
- Views changes to help support Stereoscopic projections
- Fixes for LinearDepth pass and Shadowmap pass to work with stereoscopic views
- Camera changes to help support multiple views. In the case the ASV sample has 3 views - One for PC and 2 for XR
- Enable debug shader symbols for spirv
- Added a XR multi-view pipelines for left and the right eye. At the moment it supports Blendshapes, Skinning, DepthPrepass, LightCulling, Shadows, ForwardPass, SkyBox, TransparentPass, LightAdaptions, AuxGeom, UI, CopyToSwapChain. There is a lot of room for perf improvements like not doing ShadowPass twice or skipping DepthPrepass given that the device will be used tile deferred architecture but for now this …
> Next set of core engine VR support work for a function AtomSampleViewer VR sample. 

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicInterface.h
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabDeleteTests.cpp
This PR removes the deprecated delete API in public prefab handler. The API was already marked as DEPRECATED since last release 2205.
All tests passed.
> Prefab | Remove deprecated delete API in public interface

- Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp
Necessary to fix #10213
Exposed the `IsLevelDocumentOpen` and `GetLevelName` requests from the `EditorRequestsBus` to python.
Tested via the following script in python and verified the APIs work.
```
import azlmbr.editor as editor
level_open = editor.EditorRequestBus(bus.Broadcast, 'IsLevelDocumentOpen')
level_name = editor.EditorRequestBus(bus.Broadcast, 'GetLevelName')
```
> Exposed level requests to python

- Gems/Terrain/Assets/Shaders/Terrain/TerrainMacroHelpers.azsli
This PR ensures that the modulus operation is always done with positive numbers to make sure the platform specific shaders have consistent behavior.
Tested terrain macro materials with several scenes in dx12 and vulkan.
> Fixing issue where hlsl and spi-rv handle modulus math differently with negative numbers.

- Gems/AWSMetrics/cdk/README.md
- Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/DCC/Substance/readme.md
- Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/DCC/Launch_Maya_2022.bat
- Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Env_O3DE_Python.bat
- Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Solutions/.idea/DccScriptingInterface.iml
- Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/IDE/Wing/readme.md
- scripts/build/build_node/Platform/Linux/install-ubuntu-build-tools.sh
- scripts/build/build_node/Platform/Windows/install_python.ps1
House-keeping updates for references to the previous version of Python (3.7)
* Update references to Python 3.7(.12) to 3.10(.5) in scripts, comments, etc
* Also Remove unnecessary libffi installation for ubuntu 20.04
Most of the changes are in comments, messages only, not any direct code. The only scripting code that is affected is used to configure new build nodes.
> Final Python 3.7 -> 3.10 updates

- Code/Framework/AzCore/AzCore/Serialization/ObjectStream.cpp
This cleans up the error log for the Object Stream when class version mismatches are encountered.
View the AP logs and output to see the new error log.
> {lyn13148} Updated logging for Object Stream

- Code/Editor/EditorPreferencesPageGeneral.h
- Code/Editor/MainWindow.cpp
- Code/Editor/Settings.cpp
- Code/Editor/Settings.h
Addresses issue with P4 being enabled by default on new installs despite the setting being marked as disabled by default. That was likely due to the previous code relying on both settings registry and windows registry to determine the activation status; new code streamlines the setting to be in line with other settings relying on the settings registry (namely the viewport ones).
Note that this change may result in the Source Control setting being disabled for users that have it enabled on their local installation and rebuild with this commit, since the source of the setting has changed. The solution is just to re-enable P4 manually, no data loss is introduced (P4 settings will not be lost).
Closes #8408
> P4 | Change SourceControl settings to only rely on SettingsRegistry instead of Windows Registry

- Code/Framework/AzNetworking/AzNetworking/Utilities/QuantizedValues.inl
Fixes unit test failure on Ubuntu 22.04, related to order of operation precedence differences and overflow of doubles and floats.
Root cause not positively identified (clang version? compiler flag? linux distro?), but the behavior of the following line
```
static_cast<float>(minimumFloat + quantized * convertToFloat);
```
acts differently on Ubuntu 22.04 w/ clang-12 than the other platforms that support this unit test. This could either be caused by some precision differences or overflow optimization, but there is a difference down casting from (quantized * convertToFloat) vs (minimumFloat + quantized * convertToFloat) in one operation. 
The update does not change the behavior of the intended function, but will at least make the behavior consistent
More specifically:
```
[ RUN      ] …
```
> Fix AzNetworking unit test failures on Ubuntu 22.04

- Gems/Terrain/Assets/Shaders/Terrain/TerrainMacroHelpers.azsli
Fixing issue where hlsl and spi-rv handle modulus math differently with negative numbers. This change ensures that the modulus operation is always done with positive numbers to make sure the platform specific shaders have the same behavior.
(cherry picked from commit f73f81bff77a3ea77c720c5786a45df7ade17025)
> Fixing issue where hlsl and spi-rv handle modulus math differently with negative numbers. (#11833)

- scripts/ctest/CMakeLists.txt
Disables a test which verifies PyTest suite filtering, due to intermittent XML error seen in https://github.com/o3de/o3de/issues/11667 which has only ever appeared for this one test.
Executed suite locally without failure, however the underlying issue is intermittent with a ~1/100 failure rate. Hopefully the race condition is somehow specific to this file.
> Disable intermittent test for investigation

- cmake/Platform/Android/CMakePresets.json
- cmake/Platform/Common/CMakePresets.json
- cmake/Platform/Linux/CMakePresets.json
- cmake/Platform/Mac/CMakePresets.json
- cmake/Platform/Windows/CMakePresets.json
- cmake/Platform/iOS/CMakePresets.json
Updated the generator for VS2022 and VS2019 to use the name of "Visual Studio 17 2022" and "Visual Studio 16 2019"
Apparently there is a bug where if the generator of "Visual Studio 17" or "Visual Studio 16" is specified as the "generator" value in the preset, it doesn't show up in the --list-presets command(though it is usable).
Fixed the naming of the windows-test-profile test preset
Verified that the VS2019 and VS2022 configure presets appear
```
C:\code\o3de>cmake --list-presets
Available configure presets:
"windows-automated-testing"        - Windows + Automated Testing project
"windows-automated-testing-vs2019" - Windows + Automated Testing project + VS2019
"android-automated-testing" …
```
> Extracted out the host OS conditions for presets to their own presets

- Code/Editor/Plugins/ComponentEntityEditorPlugin/ContextMenuHandlers.cpp
- Code/Editor/Plugins/ComponentEntityEditorPlugin/ContextMenuHandlers.h
- Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
- Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.h
- Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/Outliner/OutlinerWidget.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Editor/EditorContextMenuBus.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/EditorContextMenu.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.h
- Gems/Camera/Code/Source/CameraEditorSystemComponent.cpp
- Gems/Camera/Code/Source/CameraEditorSystemComponent.h
- Gems/PhysX/Code/Editor/Source/Components/EditorSystemComponent.cpp
- Gems/PhysX/Code/Editor/Source/Components/EditorSystemComponent.h
When creating an entity from the Entity Inspector, the entity is no longer created in the center of the viewport, instead the entity will be created at the origin (0, 0, 0), or if created as a child of another entity, have a local translation of (0, 0, 0) and exist at the same world space position as the parent.
Resolves #9754 
Currently this test has just been tested manually in the viewport. I would love to add tests for this and am inclined to create a follow-up task to do this as I know this fix is important to get in to the stabilization branch for the 22.10 release.
https://user-images.githubusercontent.com/82228511/189088219-c3544e06-da89-4f89-9d3c-8099b89953e7.mp4 …
> Ensure entity is created at local (0, 0, 0) if created from the Entity Outliner

- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/ComponentModeCollection.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/ComponentModeSwitcher.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/EditorBaseComponentMode.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/EditorComponentModeBus.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorDefaultSelection.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorDefaultSelection.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiDisplay.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiDisplay.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiManager.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiManager.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiRequestBus.h
When the user changes component mode via the switcher, the border flickered on the change, with this PR, the border no longer flickers.
This PR has been approved (https://github.com/o3de/o3de/pull/11436) and merged into development.
Before:
https://user-images.githubusercontent.com/105638312/185807369-bb841254-eb94-4722-9d7f-f134c99814e0.mp4
After:
https://user-images.githubusercontent.com/105638312/185807390-3c4b0670-fc34-4632-8ba2-5925c6724bf3.mp4
> Fix Component mode border flicker - PR11585

- Code/Framework/AzFramework/AzFramework/Application/Application.cpp
This PR turns on the Editor Mode Feedback System by default. Previously, it was turned off by default unless explicitly turned on by the customer.
> Turn on EMVF by default.

- Gems/LmbrCentral/Code/Source/Builders/LuaBuilder/LuaBuilderComponent.cpp
- Gems/LmbrCentral/Code/Source/Builders/LuaBuilder/LuaBuilderWorker.cpp
For non-lua files, the error message is more descriptive to let people know that files should not be referenced directly from lua code but should instead go through the Property slots system using AssetIds
Manually
> Updated lua builder error message for files which do not look like lua references

- Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
On initialization, terrain wasn't correctly updating zmin and zmax. This caused terrain to not render when settings changed because zmin and zmax initialize to 0.
Fixes: #11824
Tested terrain levels to make sure updating terrain settings were reflected immediately and terrain continued to render as expected.
> Fix for #11824. On initialization, terrain wasn't correctly updating zmin and zmax.

- Gems/Multiplayer/Code/Source/NetworkEntity/EntityReplication/EntityReplicationManager.cpp
- Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp
HandleEntityDeleteMessage treats a duplicate MarkForRemoval of an entity as a failure resulting in a disconnection. This change updates to treat this as a no-op non failure.
Addresses https://github.com/o3de/o3de/issues/11695. 
Ran units and tested in MultiplayerSample.
> Treat duplicate MarkForRemoval as acceptable

- Code/Framework/AzFramework/AzFramework/Archive/Archive.cpp
- Code/Framework/AzFramework/AzFramework/Archive/Archive.h
- Code/Framework/AzFramework/AzFramework/Archive/IArchive.h
- Code/Framework/AzFramework/AzFramework/Archive/ZipDirCache.cpp
- Code/Framework/AzFramework/AzFramework/Archive/ZipDirCache.h
- Code/Framework/AzFramework/AzFramework/Archive/ZipDirCacheFactory.cpp
- Code/Framework/AzFramework/AzFramework/Archive/ZipDirList.cpp
- Code/Framework/AzFramework/AzFramework/Archive/ZipDirList.h
- Code/Framework/AzFramework/AzFramework/Archive/ZipDirStructures.cpp
- Code/Legacy/CryCommon/Mocks/ICryPakMock.h
The IArchive::MemoryBlock now uses the SystemAllocator for its allocations now.
The MemoryBlock AddressPtr byte array now just uses azmalloc and azfree
Simplified the FileDataRecord class to inherit from AZStd::intrusive_base and use the SystemAllocator. The FileDataRecord also now in it's constructor allocates a byte array for it's data payload.
Use the Asset Cache Server feature to create zip files of products assets
> Remove use of the OSAllocator in the Legacy AZ::IO::Archive

- AutomatedTesting/Gem/PythonTests/editor/EditorScripts/ComponentCRUD_Add_Delete_Components.py
Fixes the addition of the Mesh component to the entity via Entity Inspector. New Mesh category in Entity Inspector was being selected instead of the actual component.
Ran updated test locally which now passes. Test will remain in Sandbox due to intermittent timeout issues.
> Updating Mesh component addition via PySide utils in ComponentCRUD test

- Gems/LyShine/Code/Editor/AssetTreeEntry.cpp
This PR is for fixing GHI https://github.com/o3de/o3de/issues/11724
In UI editor, users was unable to instantiate a UI element from the slice library context menu since Slice Library context menu entry (Right-click on the canvas area, and hover over New > Element from Slice Library) doesn't expand.
Follow repro steps from https://github.com/o3de/o3de/issues/11724 and see expected result after this fix:
> Fix Slice Library context menu entry not expanding issue

- Code/Editor/Controls/ConsoleSCB.cpp
- Code/Editor/Controls/ConsoleSCB.h
- Code/Editor/Controls/ConsoleSCB.ui
- Code/Framework/AzToolsFramework/AzToolsFramework/PythonTerminal/ScriptTermDialog.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/PythonTerminal/ScriptTermDialog.ui
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/UICore/ConsoleTextEdit.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/UICore/ConsoleTextEdit.hxx
- Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
ref: https://github.com/o3de/o3de/issues/11478
This reuses the ConsoleTextEdit for default console and the python console. having the option to delete lines from the console is kind of a strange option? don't think I've seen that in anything I've used recently?
The styling could do with some tweaks since the color of the console seems to be coming from the same setting but through different means. python console is using an EBus and the standard console is getting set through the same global variable. Setting.cpp from my understanding is suppose to be replaced. I think I would like to explore this separately then add this to the current PR. 
verified with both console and python console. …
> feat(Python Console): add clear option to python console

- cmake/Tools/Platform/Android/android_deployment.py
- cmake/Tools/Platform/Android/android_support.py
- cmake/Tools/Platform/Android/generate_android_project.py
- cmake/Tools/Platform/Android/unit_test_android_deployment.py
- cmake/Tools/Platform/Android/unit_test_generate_android_project.py
- cmake/Tools/common.py
* Updates the android unit tests to reflect recent changes to the android deployment scripts 
* Updated ```generate_android_project.py``` to default the argument of ```--third-party-path``` to the O3DE default
* Resolved the following deprecation warning
```
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
```
Note, the changes were made to reflect the updated expect values, mocks, etc. They assume that the updates to the android deployment scripts were tested properly.
Run unit test against the android python scripts (on windows)
```
cd cmake\Tools\Platform\Android
..\..\..\..\python\python.cmd -m pytest
```
> Android script updates

- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h
Fix for Eliding Labels not taking up enough space within a DPE shared column.
Launched the editor and the debug view standalone to ensure that Eliding labels are taking the appropriate amount of space.
Before:
After:
> Fix for Eliding Label spacing in shared columns

- Gems/Terrain/Code/Source/Components/TerrainWorldDebuggerComponent.cpp
- Gems/Terrain/Code/Source/TerrainRaycast/TerrainRaycastContext.cpp
This fixes some "invalid AABB" asserts that can occur when running in debug. The asserts themselves were warning about harmless cases, but these changes prevent the asserts from happening at all.
Ran a debug build and verified that the asserts no longer occurred.
> [Terrain] Fix invalid AABB asserts in debug builds.

- Gems/Atom/Component/DebugCamera/Code/Source/CameraComponent.cpp
Fix a crash when the camera component entity is activated/de-activated multiple times
Tested Metarial Editor and ASV
> Fix crash within Material Editor

- Gems/EMotionFX/Code/EMotionFX/Source/Node.h
- Gems/EMotionFX/Code/Source/Editor/ColliderHelpers.cpp
- Gems/EMotionFX/Code/Source/Editor/Plugins/Cloth/ClothJointInspectorPlugin.cpp
- Gems/EMotionFX/Code/Source/Editor/Plugins/HitDetection/HitDetectionJointInspectorPlugin.cpp
- Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeInspectorPlugin.cpp
- Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeWidget.cpp
- Gems/EMotionFX/Code/Source/Editor/Plugins/SkeletonOutliner/SkeletonOutlinerPlugin.cpp
- Gems/EMotionFX/Code/Source/Editor/SimulatedObjectHelpers.cpp
- Gems/EMotionFX/Code/Source/Editor/SkeletonModel.cpp
- Gems/EMotionFX/Code/Source/Editor/SkeletonModel.h
- Gems/EMotionFX/Code/Source/Editor/SkeletonModelJointWidget.cpp
- Gems/EMotionFX/Code/Tests/ProvidesUI/Ragdoll/CanCopyPasteColliders.cpp
- Gems/EMotionFX/Code/Tests/ProvidesUI/Ragdoll/CanCopyPasteJointLimits.cpp
- Gems/EMotionFX/Code/Tests/UI/CanAddJointAndChildren.cpp
- Gems/EMotionFX/Code/Tests/UI/CanAddSimulatedObject.cpp
- Gems/EMotionFX/Code/Tests/UI/CanAddToSimulatedObject.cpp
- Gems/EMotionFX/Code/Tests/UI/CanChangeParametersInSimulatedObject.cpp
- Gems/EMotionFX/Code/Tests/UI/ClothColliderTests.cpp
- Gems/EMotionFX/Code/Tests/UI/RagdollEditTests.cpp
- Adds a new "Character" root node to skeleton outliner treeview.
- Adds special behaviour for that node: no context menu on right click, and special handling when that node is part of a multiple selection
Manually interacted with the treeview making sure that the model was consistent (selection/hover/etc. behave as expected).
Checked that the items in the context menu were behaving as expected.
Checked that changing selection on the treeview triggered changes on the details dockwidgets as expected.
Succesfully run autotests (EMotionFX.Editor.Tests).
> Add 'Character' root node to skeleton outliner treeview (#10962)

- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/ComponentModeDelegate.cpp
This PR fixes a potential editor hang when pressing escape immediately before attempting to enter component mode. The current entity is deselected but the information hasn't yet reached the component mode system, so all the editor ends up disabled.
Issue: https://github.com/o3de/o3de/issues/11309
The duplication instructions were followed multiple times with no issues. Debugging text was added so I could see the times when the added code prevented the issue from happening.
> 11309 Fix for editor lock when entering component mode.

- Gems/Atom/RPI/Code/Source/RPI.Edit/Common/AssetUtils.cpp
- Gems/Atom/RPI/Code/Tests/Material/MaterialSourceDataTests.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Tests/AtomToolsFrameworkTest.cpp
Updated functions that create and resolve references to use relative paths by default if both files are contained in the same scan folder. 
If the files are in different scan folders or the relative path cannot be created then the function falls back to using an aliased path.
Replaced calls to ResolvePath with ReplaceAlias. ResolvePath has some implicit functionality that automatically resolves non aliased paths to the product assets folder. In the usage within the tools, we just want to convert paths between aliased and non aliased.
https://github.com/o3de/o3de/issues/9445
https://github.com/o3de/o3de/issues/2841
Updated and ran unit tests.
Resaved many existing materials to see their paths maintained or correctly updated with relative …
> Fixing bugs constructing and reconciling paths to referenced assets in materials and material types

- Code/Framework/AzCore/AzCore/Serialization/AZStdContainers.inl
- Code/Framework/AzCore/Tests/Serialization.cpp
- Gems/GradientSignal/Code/CMakeLists.txt
- Gems/NvCloth/Code/Source/Pipeline/SceneAPIExt/ClothRule.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/ClientTransceiver.cpp
1. Fixes a few 'unused-but-set-variable' gcc errors, such as
```               from /home/github/o3de/Code/Framework/AzCore/./AzCore/Component/EntityUtils.h:12,
from /home/github/o3de/Code/Framework/AzCore/AzCore/Component/EntityUtils.cpp:9:
/home/github/o3de/Code/Framework/AzCore/./AzCore/Serialization/AZStdContainers.inl: In instantiation of ‘bool AZ::Internal::AZStdBasicContainer<T, IsStableIterators>::RemoveElement(void*, const void*, AZ::SerializeContext*) [with T = AZStd::vector<AZ::Entity*>; bool IsStableIterators = false]’:
/home/github/o3de/Code/Framework/AzCore/./AzCore/Serialization/AZStdContainers.inl:294:21:   required from here
/home/github/o3de/Code/Framework/AzCore/./AzCore/Serialization/AZStdContainers.inl:299:38: error: variable ‘prevIter’ set but not used …
```
> Fixes for Linux/GCC build errors

- Code/Tools/ProjectManager/Source/AddRemoteProjectDialog.cpp
- Code/Tools/ProjectManager/Source/AddRemoteProjectDialog.h
- Code/Tools/ProjectManager/Source/DownloadController.cpp
- Code/Tools/ProjectManager/Source/DownloadController.h
- Code/Tools/ProjectManager/Source/DownloadWorker.cpp
- Code/Tools/ProjectManager/Source/DownloadWorker.h
- Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
- Code/Tools/ProjectManager/Source/NewProjectSettingsScreen.cpp
- Code/Tools/ProjectManager/Source/NewProjectSettingsScreen.h
- Code/Tools/ProjectManager/Source/ProjectButtonWidget.cpp
- Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
- Code/Tools/ProjectManager/Source/ProjectsScreen.h
- Code/Tools/ProjectManager/Source/PythonBindings.cpp
- Code/Tools/ProjectManager/Source/PythonBindings.h
- Code/Tools/ProjectManager/Source/PythonBindingsInterface.h
- Code/Tools/ProjectManager/tests/MockPythonBindings.h
- scripts/o3de/o3de/github_utils.py
Fix objects not being downloaded to the chosen path.
Fix remote projects not being shown if there are no local projects.
Adding placeholder text and warning icon in add remote project dialog, 
Fix exception using logger in github_utils.py
> Remote project fixes

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
When a material preview is done rendering, it sends a callback from the thread that finished rendering. However, code that listens and handles this notification is not thread safe. This PR queues the callback to be sent on the main thread.
Fixes issue #11757. The UI Editor's Properties Pane listens to ToolsApplicationEvents::InvalidatePropertyDisplay to update script component properties when a script changes. This was being called on a thread other than the main thread via the material preview callback and left the property pane's Qtimer in a bad state thinking that it was still active but having a time remaining of -1.
Tested repro steps in GHI.
> Call material preview ready notification on main thread

- Code/Editor/Settings.h
- Code/Editor/ViewportTitleDlg.cpp
- Code/Editor/ViewportTitleDlg.h
- Code/Editor/ViewportTitleDlg.ui
- Code/Framework/AzToolsFramework/AzToolsFramework/Editor/EditorSettingsAPIBus.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportSettings.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportSettings.h
- Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/FocusedEntityState.cpp
This PR adds the persistent registry setting to the prefab edit mode effect setting in the viewport.
Manual testing in Editor.
> Add prefab edit mode setting persistence to registry.

- Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialSourceData.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeManager.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
- Gems/Atom/Tools/MaterialEditor/Scripts/UpgradeAllMaterials.py
This change resolves an issue with the material editor loading and creating child materials. Material source data asset references were being resolved relative to the final child material instead of the parent materials containing the reference.
In addition to resolving the issue, functions were registered with the behavior context to support a Python script for loading and resaving all materials in a project and its active gems. This script is useful for testing material editor serialization as well as upgrading materials to the latest material type version. Upgrading to the latest material type version will eradicate warning message box spam for older materials, reorganize, and rename material properties to the latest version so it does not have to be done at runtime.   
Resaved …
> Material Editor: Fixing bug creating and loading child materials from source data + upgrade material Python script

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
Fix: #11756 (multiple-save issue in instantiate-prefab)
This PR is a temp fix to add prefab undo cache update in instantiate-prefab workflow. After this change, it will no longer put in-memory DOMs in weird states and not generate unexpected patches which lead to multiple-save issue.
**Follow-Up:** As we are removing DOM cache in prefab undo cache in development, a follow-up of this change would be add parent DOM update in the instantiate-prefab workflow. This is needed in the case where DOM cache is removed; otherwise the same issue will still occur.
> Prefab | Add prefab undo cache update in instantiate-prefab workflow

- Code/Framework/AzFramework/AzFramework/Input/Channels/InputChannelDigitalWithSharedModifierKeyStates.h
- Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp
- Code/Framework/AzFramework/Tests/CameraInputTests.cpp
This PR fixes a really annoying bug that would cause the camera to move to the origin when pressing `Alt-Tab` and moving the mouse at the same time (see attached videos for before/after).
This was tested in the Editor manually. An integration test for the camera was also created to mimic the issue and show that the new code fixes it.
```
[----------] 1 test from CameraInputFixture
[ RUN      ] CameraInputFixture.OrbitRotateCameraInputDoesNotResetPositionWithInconsitentEventAndUpdate
D:/o3de-2/Code/Framework/AzFramework/Tests/CameraInputTests.cpp(621): error: Value of: m_camera.Translation()
Expected: is close tolerance ((X: 0, Y: -20, Z: 0), 0.01)
Actual: (X: 0, Y: -10, Z: 0) (of type class …
```
> Fix alt-tab issue with mouse move causing camera reset

- Code/Editor/StartupLogoDialog.cpp
Fixes a drop shadow artifact on the About Us dialog in the Editor.
Cherry-picks https://github.com/o3de/o3de/pull/11800 to stabilization/2210
Fixes https://github.com/o3de/o3de/issues/11684
> Editor | Fix shadow artifact on About Us dialog

- Code/Framework/AzCore/Platform/Mac/AzCore/Platform_Mac.cpp
Fix for the following compile error on Mac
```
In file included from /Users/github/o3de/build/mac_xcode/Code/Framework/AzCore/CMakeFiles/AzCore.dir/Unity/unity_30_cxx.cxx:9: /Users/github/o3de/Code/Framework/AzCore/Platform/Mac/AzCore/Platform_Mac.cpp:39:22: error: no matching member function for call to
'ProcessBytes'
hash.ProcessBytes(&hostId, sizeof(hostId));
~~~~~^~~~~~~~~~~~
In file included from /Users/github/o3de/build/mac_xcode/Code/Framework/AzCore/CMakeFiles/AzCore.dir/Unity/unity_30_cxx.cxx:5: In file included from /Users/github/o3de/Code/Framework/AzCore/Platform/Common/Apple/AzCore/Module/DynamicModuleHandle_Apple.cpp:9: In file included from /Users/github/o3de/Code/Framework/AzCore/AzCore/std/string/osstring.h:11: In file included from …
```
> Fix compile error on Mac

- scripts/ctest/CMakeLists.txt
Disables tests encountering test framework-level failures with a ~1/50 rate, which no other tests are encountering. The tests themselves are consistently passing, but the framework fails on teardown. The underlying failure may have started appearing after the Python interpreter upgrade, and needs further investigation in https://github.com/o3de/o3de/issues/11667
This applies https://github.com/o3de/o3de/pull/11871 to stabilization. If this change is not performed, automated test runs in Stabilization will continue to intermittently error at around a 1/50 rate. However this will not impact the stability of the actual O3DE production code.
Verified locally and in development.
> Disable intermittent XML failures in Stabilization

- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Components/SceneBus.h
- Gems/GraphModel/Code/Include/GraphModel/Integration/GraphController.h
- Gems/GraphModel/Code/Source/Integration/GraphController.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.h
Fixes #11987 
When you delete nodes in Landscape Canvas, it will automatically delete the corresponding component (and Entity if applicable) for you. For wrapped nodes, it only deletes the component, since the wrapper node corresponds to a separate component so the Entity should remain. The Macro Material and Surface Material nodes are the first nodes that are able to be wrapped but also standalone. The logic for when to delete the whole entity vs. just the component was only doing a type check, not looking if the node was actually wrapped, so updated the logic to be more generic/future proof.
- Removed the `PreOnNodeRemoved` that was no longer in-use by GraphCanvas
- Updated the `GraphController` to properly trigger the pre-node removal event
- Updated logic to actually check if a node …
> Improved handling of action after deleting wrapped nodes

- Code/Editor/TrackView/AtomOutputFrameCapture.cpp
- Gems/Atom/Feature/Common/Code/Source/FrameCaptureSystemComponent.cpp
- Gems/Atom/Feature/Common/Code/Source/FrameCaptureSystemComponent.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRenderer.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRenderer.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/ColorGrading/EditorHDRColorGradingComponent.cpp
Found some places still using uint32 when working on other PRs. Replaced them with FrameCaptureId.
> [Atom] Change uint32 to FrameCaptureId

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorWidget.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorWidget.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditorSettings.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditorSettings.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/IPropertyEditor.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/SettingsRegistrar.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/SettingsRegistrar.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyManagerComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ReflectedPropertyEditor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ReflectedPropertyEditor.hxx
- Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
This PR adds support for saving expanded element states in property editors which use the DocumentPropertyEditor (DPE).
Notable changes include:
- Settings files for the DPE are stored in the active project's `user/Registry` dir:
- `[projectRoot]/user/Registry/DocumentPropertyEditor/[propertyEditor]_settings.setreg`
- Expansion state is saved when closing a property editor or when switching files, and only for user activated expansions/collapses
- Shift+click will now expand/collapse a node and all of its children
- Also fixes expansion state saving with the RPE in the AssetEditor which was not functional
Saving state when switching files and recursive shift+click expansion from a node:
Settings file structure:
**Testing**
- Expanded/collapsed nodes in a document and …
> DPE: Enable expansion state saving

- Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/ComboBoxNodePropertyDisplay.cpp
While testing, find out annoying warning message while switching focus of combo box across graphs.
The issue is related to ViewNotificationBus, as it doesn't support multi handler, so we should disconnect it from previous one
Warning message example
```
(System) - Connecting to a different id on this bus without disconnecting first! Please ensure you call BusDisconnect before calling BusConnect again, or if multiple connections are desired you must use a MultiHandler instead.
(System) - ------------------------------------------------
(System) - D:\Lumberyard\o3de\Gems\GraphCanvas\Code\Source\Components\NodePropertyDisplays\ComboBoxNodePropertyDisplay.cpp (346) : GraphCanvas::ComboBoxNodePropertyDisplay::SetupProxyWidget
(System) - …
```
> Fix combo box warning message while switching focus across graphs

- AutomatedTesting/Assets/TestAnim/scene_export_actor.py
- AutomatedTesting/Assets/TestAnim/scene_export_motion.py
- AutomatedTesting/Assets/ap_test_assets/script_reinsert.py
- AutomatedTesting/Editor/Scripts/auto_lod.py
- AutomatedTesting/Editor/Scripts/scene_mesh_to_prefab.py
- AutomatedTesting/Gem/PythonTests/PythonAssetBuilder/export_chunks_builder.py
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoSceneFiles_OneWithPythonOneWithout_PythonOnlyRunsOnFirstScene/python_builder.py
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/script_basics/base_example.py
- AutomatedTesting/TestAssets/test_chunks_builder.py
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.cpp
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.h
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiManager.cpp
- Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingResourceList.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRenderer.cpp
- Gems/Blast/Editor/Scripts/blast_chunk_processor.py
From stabilization to development.
Fixes several memory/heap corruption bugs
These would eventually cause random crashes.  They were detected by turning AzCore SystemAllocator to use the OS malloc and free (That change is not included in this change), and then using the Microsoft Debug CRT allocators with heap corruption detection features enabled.
The specific errors are as follows:
- Python files:  Deleting an event handler while inside the event handler invalidates the 'this' pointer which is then subsequently used.
- Settings Registry:  Mutating the settings registry while iterating over it in a visitor pattern.  The iterators are invalidated as the document changes out from onder them and will cause random crashes depending on memory reuse.  Added automatic detection for this problem …
> Cherry-picks https://github.com/o3de/o3de/pull/11992

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetSelectionModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.hxx
- Gems/GradientSignal/Code/Source/Editor/EditorStreamingImageAssetCtrl.cpp
- Gems/ScriptCanvas/Code/Editor/GraphCanvas/DataInterfaces/ScriptCanvasAssetIdDataInterface.h
- Gems/ScriptCanvas/Code/Editor/View/Widgets/SourceHandlePropertyAssetCtrl.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Translation/GraphToLuaUtility.cpp
This change updates script canvas to support picking, assigning, and generating code for asset IDs. This should resolve issues with the material component, decal component, image-based lighting, gradients, and any other component that requires assets to be assigned from script canvas. While users can now select assets, the script canvas asset picker is now completely unfiltered instead of filtered exclusively to dynamic slices. Additional work will be required to provide script canvas with the necessary asset type info in order to properly filter the asset picker.
https://github.com/o3de/o3de/issues/11307
verify that assets can be assigned to the material component from script canvas hand at the materials are applied when scripts are run in …
> Script Canvas: Support for selecting asset IDs from nodes

- Code/Editor/Controls/ConsoleSCB.cpp
- Code/Editor/Plugins/ComponentEntityEditorPlugin/ComponentEntityEditorPlugin.cpp
- Code/Editor/QtViewPaneManager.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/API/ViewPaneOptions.h
This removes the hard-coded special behaviors for keeping the Entity Inspector, Pinned Entity Inspector, Entity Outliner, and Console windows active during Component Mode, and instead turns it into a generalized ViewPaneOption, with the option enabled for those four windows.
The behavior in the Editor remains the same, but by moving this to the ViewPaneOptions, we can now add this functionality to new view panes without needing to hardcode the view pane name in QtViewPaneManager. This will be used by the Paint Brush Settings view pane in an upcoming PR.
Note that of the four, only the Console window remains completely active. The Entity Inspector / Pinned Entity Inspector need the view panes to remain active so that they can disable all components except the one(s) being edited. It's not …
> Generalized the view pane options for enable/disable during Component Mode

- Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/LodRule.cpp
> [GHI-11704] Number of selected joints in Skeleton LOD rule in FBX settings is incorrect

- CMakeLists.txt
- cmake/GeneralSettings.cmake
- cmake/Subdirectories.cmake
This is to fix a limitation with external_subdirectories recurse logic when gathering the list of external_subdirectories to visit for any gems referenced indirectly in the project.json/engine.json via the "gem_names" field.
The limitation was that only the gem paths of the referenced "gem_names" had cmake `add_subdirectory` command called on them. If thoses gems contained additional external subdirectories referenced in the "external_subdirectories" field in the gem.json, those subdirectories were NOT added to CMake via `add_subdirectory`
The change here is to create a mapping of <gem-name> (via the `O3DE_EXTERNAL_SUBDIRS_GEM_<gem_name>` property) to all external subdirectories that are descendents for all gems.
Then when a gem is referenced by "gem_name", not only is the gem path …
> CMake referenced Gems external_subdirectories fixes

- Code/Editor/Style/Editor.qss
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h
Horizontal rules which show in the AssetEditor for top level container elements were not showing up when the DocumentPropertyEditor (DPE) was enabled in place of the ReflectedPropertyEditor.
This PR enables those horizontal rules in the AssetEditor when using the DPE.
DPE in AssetEditor with horizontal rules:
**Testing**
- Verified that assets which normally have horizontal rules in the AssetEditor using the RPE also have them with the DPE
> DPE: Support horizontal rules in AssetEditor similar to the RPE

- Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableEntitiesInterface.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasNodeable_Source.jinja
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/CreateSpawnTicketNodeable.ScriptCanvasNodeable.xml
Asset type is not fully supported through node input slot assignment.
To clear confusion, hide the assignment through node inspector for CreateSpawningTicket node.
Confirmed the fix in Editor. User could use graph variable instead at current phase.
> Hide prefab reference assignment in node inspector

- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/BaseNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/BaseNode.h
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Terrain/TerrainSurfaceGradientListNode.cpp
Fixes #11917 
This fixes an issue where connections made in Landscape Canvas with the Terrain Height Gradient List and Terrain Surface Gradient List extender nodes were being removed when the graph was re-opened. This was due to the properties for these components not being properly parsed on graph open, so the connections were being removed because it thought they weren't valid connections anymore.
Before this change, running the scenario in the gif below would result in no connections being present on the graph when re-opened.
Tested the steps in #11917 as well as manual testing + running the Landscape Canvas automated tests.
> Fixed node connections disappearing from terrain extenders

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ViewportInputBehaviorController/ViewportInputBehavior.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ViewportInputBehaviorController/ViewportInputBehaviorController.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ViewportInputBehaviorController/ViewportInputBehaviorControllerInterface.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportContent.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ViewportInputBehaviorController/DollyCameraBehavior.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ViewportInputBehaviorController/OrbitCameraBehavior.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ViewportInputBehaviorController/PanCameraBehavior.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ViewportInputBehaviorController/RotateCameraBehavior.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ViewportInputBehaviorController/ViewportInputBehavior.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ViewportInputBehaviorController/ViewportInputBehaviorController.cpp
This change fixes an issue with the material canvas and material editor viewport turning red momentarily on startup and anytime the viewport model is invalid or deleted. This is caused because requesting the object entity local and world bounds returns an invalid bounding box if no model is loaded.
This change also renames a handful of variables and functions.
https://github.com/o3de/o3de/issues/10879
Verified that using both material editor and material canvas, starting both tools, moving the camera in different modes, deleting and switching between different models
> Material Canvas: Fixing screen turning red from invalid entity bounds

- Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialTypeSourceData.cpp
Improved an error message that was a bit misleading.
Addresses https://github.com/o3de/o3de/issues/11893.
Made a local change to a .shader file to reproduce the Issue. Noted the improved error message.
> Improved an error message about missing shader assets.

- scripts/build/Platform/Linux/pipeline.json
- scripts/build/Platform/Windows/pipeline.json
This change adds default version parameters to the installer pipeline, as well as utilizing the last known parameter values
Resolves https://github.com/o3de/o3de/issues/12011
Tested in the sandbox Jenkins
> Add installer parameters

- Code/Framework/AzToolsFramework/AzToolsFramework/PropertyTreeEditor/PropertyTreeEditor.cpp
Fixes an issue with PhysX components that would see a crash when the `BuildPathsListWithTypes` function of the `PropertyTreeEditor` class is called on them.
This function returns a list of component properties as follows:
```
[
"Standard Joint Parameters|Lead-Follower Collide (bool,Visible)",
"Angular Limit|Standard limit configuration|Damping (float,NotVisible)",
"Standard Joint Parameters|Local Position (Vector3,Visible)",
"Standard Joint Parameters|Local Rotation (Vector3,Visible)",
"Standard Joint Parameters|Maximum Torque (float,NotVisible)",
"Standard Joint Parameters|Display Setup in Viewport (unsigned char,Visible,ReadOnly)",
"Standard Joint Parameters|Breakable (bool,Visible)",
"Angular Limit …
```
> PropertyTreeEditor | Fix crash when the ReadOnly attribute is set by a member function.

- Gems/LyShine/Code/Editor/Animation/UiAnimViewCurveEditor.ui
- Gems/LyShine/Code/Editor/Animation/UiAnimViewKeyPropertiesDlg.cpp
- Gems/LyShine/Code/Editor/Animation/UiAnimViewNodes.ui
Decrease minimum size of the UI Editor's animation panes so the editor has a better chance of fitting on displays configured to have a smaller width footprint, such as setting orientation to portrait mode.
Fixes #11773, #11761
Tested manually using provided steps in GHI issue.
> Set smaller minimum sizes for UI animation panes

- Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/FocusedEntityState.cpp
This PR changes the behavior of Prefab Edit Mode visual effect such that it is only disengaged when prefab editing mode is exited. This allows for other modes such as Component Mode visual effect to be nested within the Prefab Edit Mode visual effect.
See https://github.com/o3de/o3de/issues/11444 for more details.
This PR was tested manually within the editor.
> Change prefab edit mode behavior to overlap with component mode.

- AutomatedTesting/Assets/Prefabs/BushFlowerBlender.prefab
- AutomatedTesting/Gem/PythonTests/largeworlds/landscape_canvas/EditorScripts/ComponentUpdates_UpdateGraph.py
- AutomatedTesting/Levels/Base/Base.prefab
1. Test was passing when it should have been failing due to a few issues:
* Calling GetValue() on an unsuccessful Outcome returned by GetComponentOfType()
* The usage of GetNodeMatchingEntityComponentInGraph whose result can't be validated against None
2. To fix this, the test now:
* Uses editor_entity_utils.py to ensure IsSuccess() is validated before GetValue() so garbage values aren't returned
* Uses GetAllNodesMatchingEntityComponent whose result is a list that can be validated against using len()
3. This PR also updates several prefabs used in the test to remove the deprecated SelectionComponent warnings.
Ran updated test several times without issue.
> Updating ComponentUpdates_UpdateGraph test

- Code/Tools/Android/ProjectBuilder/AndroidManifest.xml
- Code/Tools/Android/ProjectBuilder/build.gradle.in
This allows APKs that larger than 4K to be used.
Added the android:exported attribute to the AndroidManifest.xml to allow API level >30 to build successfully when using the intent-filter(which O3DE does.
https://developer.android.com/guide/topics/manifest/activity-element#exported
resolves #11972
> Updating the gradle build script to produce APKs that use Zip64.

- Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
- Code/Tools/AssetProcessor/native/ui/MainWindow.h
- Code/Tools/AssetProcessor/native/ui/MainWindow.ui
- Code/Tools/AssetProcessor/native/ui/style/AssetProcessorConfig.ini
- Code/Tools/AssetProcessor/native/ui/style/AssetsTab.qss
Update the Event Log Line Details table in AP to display/hide automatically based on the log line context:
- Show the table when the log line contains context details. Adjust the table height automatically based on the number of rows (The maximum number of rows is configurable)
- Hide the table if the log line doesn't contain any context details.
Tested the AP GUI automatically.
_Before this PR:_
_After this PR:_
> Update the content details table to display/hide automatically

- Code/Tools/AssetProcessor/AssetBuilder/TraceMessageHook.cpp
- Move trace information and message type to context details and display them under the Event Log Line Details table
- Simplify the error/warning messages in the job log file
Tested manually in AP GUI and validated the log messages in the job log file.
_Before these changes:_
Log file: [test.fbx-old.log](https://github.com/o3de/o3de/files/9611607/test.fbx-old.log)
_After these changes:_
Log file: [test.fbx-new.log](https://github.com/o3de/o3de/files/9611609/test.fbx-new.log)
> New error log line in AP Jobs pane

- Code/Framework/AzCore/AzCore/DOM/DomComparison.cpp
- Code/Framework/AzCore/AzCore/DOM/DomComparison.h
- Code/Framework/AzCore/AzCore/DOM/DomPatch.cpp
- Code/Framework/AzCore/AzCore/DOM/DomPatch.h
- Code/Framework/AzCore/AzCore/DOM/DomPath.cpp
- Code/Framework/AzCore/AzCore/DOM/DomPath.h
- Code/Framework/AzCore/Tests/DOM/DomPatchTests.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.cpp
I received some API feedback about patch handling within the Document Property Editor, namely that the prevalent use of `EndOfArray` entries in our `GenerateHierarchicalDeltaPatch` algorithm (and the validity of its prevalence) led to significant friction for consumers handling patches downstream, as to fully resolve an `EndOfArray` path requires a denormalization operation via a lookup in a provided `Dom::Value`, which is both cumbersome and potentially expensive. While there still remains a valid and open architectural question as to whether JSON patch is the right abstraction for the DPE, this patch attempts to address some of this friction in the short term.
To that end:
1. Our `EndOfArray` usage has been audited and restricted to only the one place where it's called out (and indeed …
> Tweak DPE patch path normalization behavior

- Code/Tools/SceneAPI/SceneBuilder/SceneSystem.cpp
Currently, all non-FBX model files are imported with invalid scale.
This is because `SceneSystem` is tailored around FBX meshes and assumes a centimeter as a default unit for every imported mesh. This PR checks if the imported mesh "looks like" FBX. If it is, then centimeter -> meter conversion is applied. On the other hand, no conversion is applied for non-FBX meshes.
I exported a single mesh from Blender in 3 different formats: FBX, DAE, and STL (with default settings). Then imported each mesh into O3DE scene.
Before:
After:
> Mesh scale fix for non FBX files

- Code/Legacy/CryCommon/IMovieSystem.h
- Gems/Maestro/Code/Source/Cinematics/AnimSplineTrack_Vec2Specialization.h
- Gems/Maestro/Code/Source/Cinematics/AnimTrack.h
Using the VS2022 17.4.0 Preview the `EAnimCurveType` type implicitly changed to a `unsigned int`, due to having an enum option with a value of `0xFFFFFFFF`.
This causes an unsigned/signed mismatch while comparing an `int` to an `EnimCurveType` in AnimTrack.h
Built the Editor and AssetProcessorBatch using VS2022 version 17.4.0 Preview 2.1
> VS2022 17.4.x build fixes

- Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.h
Trying to assign a UUID to a non-asset file and look up the file by UUID failed because non-asset files cannot be looked up by UUID. Switched to storing results from db as they are so lookups can be done separately for UUID vs path.
Note that the PathOrUuid class is placed in-line temporarily.  There is another, larger PR that further reworks dependencies which already includes this class.  That PR will be updated to include this fix and remove the PathOrUuid class.
Manually + added and ran unit test
> [LYN-15573] Asset Processor - Fix dependencies on non-asset files being ignored

- Code/Tools/ProjectManager/Resources/DefaultProjectImage.png
- Code/Tools/ProjectManager/Resources/DefaultTemplate.png
A couple of images (for project and template) used by project manager (in the case that a project or template did not have an overriding image) were not updated to use the current logo. This changes these images to use the current logo. Attached new images in case the diff does not show these files:
> Updating images that were missed containing the old logo

- Gems/Atom/Feature/Common/Code/Source/ImGui/ImGuiPass.cpp
Code was checking for existing default pass with same pipeline
However during hot reload, we create new passes and initialize them to validate the hot reload
This creates a new ImGui pass, but it doesn't get assigned to default because it's the same pipeline as the current default
Then the reload succeeds, the old ImGui pass is removed and ImGui isn't pointing to any pass, so it doesn't render.
Upon inspection of the code, ImGui can have multiple pass pointers in it's stack of default passes (it already does for multiple pipelines) and these passes can be from the same pipeline, so the check preventing the addition of the new pass wasn't necessary. Tested and works after hot reload.
> Fixed ImGui pass issue on pass hot reload

- Gems/AudioEngineWwise/Code/Source/Engine/FileIOHandler_wwise.cpp
Fixed compile issue with Wwise enabled on latest development:
```
19>------ Build started: Project: EditorLib, Configuration: profile x64 ------
9>D:/github/o3de/Gems/AudioEngineWwise/Code/Source/Engine/FileIOHandler_wwise.cpp(302,114): error C2440: 'initializing': cannot convert from 'std::chrono::duration<float,std::milli>' to 'std::chrono::duration<__int64,std::micro>'
9>        AZStd::chrono::microseconds deadline = AZStd::chrono::duration<float, AZStd::milli>(heuristics.fDeadline);
9>                                                                                                                 ^
9>D:/github/o3de/Gems/AudioEngineWwise/Code/Source/Engine/FileIOHandler_wwise.cpp(302,46): note: No user-defined-conversion operator available that can perform this conversion, or the …
```
> Fixed Wwise compile error

- Gems/GraphModel/Code/Include/GraphModel/GraphModelBus.h
- Gems/GraphModel/Code/Include/GraphModel/Integration/GraphController.h
- Gems/GraphModel/Code/Source/GraphModelSystemComponent.cpp
- Gems/GraphModel/Code/Source/Integration/GraphController.cpp
Fixes #12155 
Added API to query if specified source and target slots are connected in a graph.
Tested with the following script that creates two nodes and connects their slots and verifies before/after if they are connected using the new API. After executing the script I also manually disconnected them in the graph and then queried the API again to verify they are disconnected.
```
import azlmbr
import azlmbr.editor as editor
import azlmbr.editor.graph as graph
import azlmbr.landscapecanvas as landscapecanvas
import azlmbr.math as math
editor_id = azlmbr.globals.property.LANDSCAPE_CANVAS_EDITOR_ID
new_graph_id = graph.AssetEditorRequestBus(bus.Event, 'CreateNewGraph', editor_id)
new_graph = graph.GraphManagerRequestBus(bus.Broadcast, 'GetGraph', new_graph_id) …
```
> Added AreSlotsConnected API to GraphModel

- Code/Tools/ProjectManager/Resources/ProjectManager.qss
- Code/Tools/ProjectManager/Source/AddRemoteProjectDialog.cpp
- Code/Tools/ProjectManager/Source/AddRemoteTemplateDialog.cpp
- Code/Tools/ProjectManager/Source/CreateProjectCtrl.cpp
- Code/Tools/ProjectManager/Source/NewProjectSettingsScreen.cpp
- Code/Tools/ProjectManager/Source/NewProjectSettingsScreen.h
- Code/Tools/ProjectManager/Source/ProjectSettingsScreen.cpp
- Code/Tools/ProjectManager/Source/ProjectSettingsScreen.h
- Code/Tools/ProjectManager/Source/PythonBindings.cpp
- Code/Tools/ProjectManager/Source/PythonBindings.h
- Code/Tools/ProjectManager/Source/PythonBindingsInterface.h
- Code/Tools/ProjectManager/Source/UpdateProjectSettingsScreen.cpp
- Code/Tools/ProjectManager/Source/UpdateProjectSettingsScreen.h
- Code/Tools/ProjectManager/tests/MockPythonBindings.h
- scripts/o3de/o3de/github_utils.py
- scripts/o3de/o3de/repo.py
Fixs for remote template and repo script issues:
Add remote template dialog has the failed/successful validation feedback icons mirroring those in the add remote project dialog.
Newly added templates are added to the layout immediately
Error message when trying to create a project when attempting to use a template that has not been downloaded.
Fix for scripts assuming that all object types will be available in the repo.json
Fix incorrectly attempting to using git to download files by direct links on github (for example files from releases)
> Remote templates and repo script fixes

- Code/Tools/ProjectManager/Source/ProjectButtonWidget.cpp
Cancel button was hidden while building, re-adding the button for this state.
> Fix cancel button not showing while building

- scripts/build/Platform/Linux/build_config.json
Creates a Ubuntu 22.04 nightly non-unity profile job with a generic node label. We'll be moving the node configs to utilize a hashed label after we solidified the node config
> Add Ubuntu 22.04 nightly job

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNodeConfig.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNodeManager.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNodeManagerRequestBus.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNodeSlotConfig.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNodeUtil.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/AtomToolsFrameworkSystemComponent.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentApplication.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeConfig.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeManager.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodePaletteItem.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeSlotConfig.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeUtil.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportSettingsInspector.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Inspector/PropertyWidgets/PropertyStringBrowseEditCtrl.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Inspector/PropertyWidgets/PropertyStringBrowseEditCtrl.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_files.cmake
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.h
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocumentRequestBus.h
- Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.cpp
- This change addresses issues with the node configuration editor and edit contexts.
- The included property controls prevent files outside of scan folders and invalid files and values from being selected within the editor.
- This fixes problems with editing shader code snippets that were previously limited to confined space in the inspector. Properties with large text blocks like shader code snippets and descriptions can now be opened and edited in a model, resizable dialog.
- Default values will be cleared if incompatible type selections are made.
- Fixed other bugs related to create a new, untitled documents and saving them without a file name. Instead, if no file name has been specified the user will be prompted to select a path, defaulting to an untitled path with the first supported …
> Material Canvas: Fixing issues with node configuration editor and saving untitled documents

- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Components/SceneBus.h
- Gems/GraphModel/Code/Include/GraphModel/GraphModelBus.h
- Gems/GraphModel/Code/Include/GraphModel/Integration/GraphController.h
- Gems/GraphModel/Code/Include/GraphModel/Model/Graph.h
- Gems/GraphModel/Code/Source/Integration/GraphController.cpp
- Gems/GraphModel/Code/Source/Model/Graph.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.h
Fixes #7909
This PR fixes undo/redo support in Landscape Canvas.
- Keep track of entities that need to be refreshed during prefab propagation
- After prefab propagation ends, refresh those queued entities (they might've been deleted or re-created after undo/redo)
- Cherry-pick of two commits from `development` related to fixing the `PreOnNodeRemoved` no longer working, which had broken the feature of restoring previously deleted nodes to their past positions
(NOTE: The shortcuts for Delete and Undo/Redo are functional, I just triggered the menu items explicitly so that the gif showed what was happening)
Ran Landscape Canvas automated tests and all passed. Also did some manual testing of undo/redo scenarios.
> Fixed Landscape Canvas Undo/Redo

- Gems/PhysX/Code/Editor/Source/ComponentModes/Joints/JointsComponentModeCommon.cpp
- Gems/PhysX/Code/Editor/Source/ComponentModes/Joints/JointsComponentModeCommon.h
- Gems/PhysX/Code/Source/EditorHingeJointComponent.cpp
- Gems/PhysX/Code/Source/EditorPrismaticJointComponent.cpp
Signed-off-by: Michał Pełka <michalpelka@gmail.com>
This PR is needed by a Gem that we are currently developing.  The API for manipulating joint limits lacks a way to activate and deactivate it by communicating with PhysX `EditorHingeJointComponent` and `EditorPrismaticJointComponent` via `EditorJointRequestBus`. Here is a snippet for sample usage:
````
PhysX::EditorJointRequestBus::Event(
AZ::EntityComponentIdPair(followColliderEntityId, jointComponent->GetId()),
&PhysX::EditorJointRequests::SetBoolValue,
PhysX::JointsComponentModeCommon::ParamaterNames::EnableSoftLimits,false);
````
It allows to turn off Limits and Soft Limits for  `EditorHingeJointComponent` and `EditorPrismaticJointComponent`
It was manually tested against the developed codebase of our Gem.
> Added possibility to turn on and off PhysX joints' limits

- AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Main.py
- AutomatedTesting/Gem/PythonTests/Prefab/tests/overrides/EditEntity_UnderImmediateInstance.py
- AutomatedTesting/Gem/PythonTests/Prefab/tests/overrides/EditEntity_UnderNestedInstance.py
This PR adds two automated tests for verifying prefab instance overrides. It creates two instances from the same prefab, edits an entity in one of the instances and verifies that after propagation, only one of the two entities of the two instances was modified, and the other remained the same.
- Editing entity of an instance that's owned by the level
- Editing an entity of a nested instance
Ran Prefab automated tests and checked that they passed.
> Add tests for entity edit overrides

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
The code for moving an asset in the Asset Browser had a non-functioning cancel button in the Folder selection dialog. It always assumed that OK had been pressed. It also didn't move non-conflicting assets correctly.
Tested dialog box to make sure cancel really cancelled.
> Fixes Folder Dialog bug

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
Try to fix: #11748 (warning: entity id has no registered owning instance)
This PR fixes the warning "Entity Id has no registered owning instance". The root cause is described in the issue. It happens in instance object serialization where child entity object is detached but their parent container entity object still links to the child.
This can be fixed by breaking the relation before getting into serialization. To do that, we also need to move transform calculation forward before breaking.
A follow-up PR is replace UpdatePrefabInstance with RemoveEntities and UpdateEntity undo nodes, which is based on some changes in this PR.
> Prefab Fix | Set parent of direct entities to null in create-prefab

- Gems/GraphCanvas/Code/Source/Components/SceneComponent.cpp
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/GraphicsItems/GraphicsEffect.h
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/GraphicsItems/GraphicsEffectBus.h
fixes a crash when highlighting a component and clicking away in the graph canvas. 
follow the referenced issue. its pretty hard to reproduce.
ref: https://github.com/o3de/o3de/issues/11639
> bugfix(Script Canvas): fix crash when highlighting a variable

- Gems/GraphCanvas/Code/Source/Widgets/GraphCanvasComboBox.cpp
This is a tweak where the dialog finished is used to determine when the the control loses focus. observed in the linked ticket that the control does not correctly lose focus. we don't hide the dialog/set the visibility to false so finished should be handled when the dialog is closed.
I did observe that it was possible to still get the control in a stuck state where the menu dialog does not correctly open. I don't think this change would cause that problem. 
If this fix does work I think it would be kind of temporary. I think I would like to rework this control a bit but this should be good enough to just address the problem. I think some of the logic to handle focus/unfocus could be simplified not sure how at the moment would need to …
> bugfix(Script Canvas): better handle focus for ComboBox

- AutomatedTesting/Gem/PythonTests/Atom/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Periodic_Null_Render_01.py
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Sandbox.py
Re-adds the shader asset builder test to the periodic suite out from the sandbox suite (it passes now).
Tested using command `C:\git\o3de\python\runtime\python-3.10.5-rev1-windows\python\python.exe -m pytest -vv -s --build-directory="C:\git\o3de\build\bin\profile" C:\git\o3de\AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Periodic_Null_Render_01.py`
Results:
```
PASSED
AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Periodic_Null_Render_01.py::TestAtomPeriodic::ShaderAssetBuilder_RecompilesShaderAsChainOfDependenciesChanges[windows-windows_editor-AutomatedTesting] <- tools\lytesttools\ly_test_tools\o3de\multi_test_framework.py Checking for tmp path C:\Users\jromnoa\AppData\Local\Temp\tmptzylh3ko
Found existing tmp path, deleting
Creating tmp path
Configuring Artifact Manager with path …
```
> Move shader asset builder tests to periodic suite from sandbox suite.

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp
Disables the ability to drop assets into the Entity Inspector when a read-only entity is part of the selection. This prevents the ability to edit procedural prefabs this way.
> Procedural Prefabs | Disable dropping assets in the Entity Inspector

- Gems/LmbrCentral/Code/Source/Shape/EditorBaseShapeComponent.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorBaseShapeComponent.h
- Gems/LmbrCentral/Code/include/LmbrCentral/Shape/EditorShapeComponentBus.h
Signed-off-by: Michał Pełka <michalpelka@gmail.com>
This PR is needed by the Gem we are developing. API does not allow current to modify this property of `EditorShapeComponent`.
After merging this PR we will be able to set visibility of `EditorShapeComponent` added to an entity with the request.
Manually tested against developed Gem.
> Add SetVisibleInGame request to EditorShapeComponentRequests

- Gems/Atom/Feature/Common/Code/Source/Debug/RenderDebugFeatureProcessor.cpp
Added check for the ReflectiveCubeMap view usage flag
Tested baking ReflectionProbes in the Editor
Tested AtomSampleViewer
> Fix for RenderDebug disabling direct lighting in CubeMap captures

- Code/Editor/TrackView/TrackViewSequenceManager.cpp
Fixes issue that would prevent sequences to be created correctly in TrackView.
Fixes #12209 
The issue was related to this line
```
AzToolsFramework::EntityCompositionRequestBus::Broadcast(
&AzToolsFramework::EntityCompositionRequests::AddComponentsToEntities, 
AzToolsFramework::EntityIdList{ newEntityId }, 
AZ::ComponentTypeList{ "{C02DC0E2-D0F3-488B-B9EE-98E28077EC56}" }
);
```
While this used to work correctly, the implicit conversion from string to AZ::Uuid/AZ::TypeId in `AZ::ComponentTypeList{ "{C02DC0E2-D0F3-488B-B9EE-98E28077EC56}" })` no longer works and `AddComponentsToEntities` would receive an empty vector, causing it to early out with a success (hence the lack of errors).
While I didn't pinpoint the …
> TrackView | Fix issue on sequence creation

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.h
Fixes a warning related to using new instead of aznew with AtomRenderPlugin. Partial fix for #11408 (fixes warning but not assert).
Manually opened and closed animation editor and verified warning did not appear in console.
> use aznew with AtomRenderPlugin

- Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.h
- Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/AssetIdNodePropertyDisplay.cpp
- Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/ComboBoxNodePropertyDisplay.cpp
- Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/EntityIdNodePropertyDisplay.cpp
- Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/NumericNodePropertyDisplay.cpp
- Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/StringNodePropertyDisplay.cpp
- Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/StringNodePropertyDisplay.h
- Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/VectorNodePropertyDisplay.cpp
- Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/VectorNodePropertyDisplay.h
- Gems/GraphModel/Code/Include/GraphModel/GraphModelBus.h
- Gems/GraphModel/Code/Include/GraphModel/Integration/GraphController.h
- Gems/GraphModel/Code/Include/GraphModel/Integration/VectorDataInterface.inl
- Gems/GraphModel/Code/Source/Integration/BooleanDataInterface.cpp
- Gems/GraphModel/Code/Source/Integration/FloatDataInterface.cpp
- Gems/GraphModel/Code/Source/Integration/GraphController.cpp
- Gems/GraphModel/Code/Source/Integration/IntegerDataInterface.cpp
- Gems/GraphModel/Code/Source/Integration/ReadOnlyDataInterface.cpp
- Gems/GraphModel/Code/Source/Integration/StringDataInterface.cpp
This change allows material canvas to consistently receive and process slot data changes whenever the user is done editing. Changes will be sent whenever the user is done editing, whenever focus changes, and other widget specific conditions. Material canvas will now correctly trigger regeneration of shaders, materials, material types after slot values are modified.
Currently testing changes in material canvas, modifying vector, numeric, and asset properties. Will continue to test changes in landscape canvas and script canvas to make sure those update as expected.
> Material Canvas: Fixing graph canvas and graph model data interfaces to send notifications after values are edited

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp
- Gems/WhiteBox/Code/Source/Rendering/Atom/WhiteBoxAtomRenderMesh.cpp
This PR fixes the crashing issue between `WhiteBox` and Editor Mode Visual Feedback by having the `WhiteBox` component correctly unregister its mesh handle when it goes out of scope.
Additionally, this PR adds the mesh handle registration to the Actor component for completeness (this was previously being obtained implicitly when the `DrawableMeshEntity` components connect to the `MeshHandleStateNotificationBus`, now the handles are registered explicitly by the `Actor` component).
Manually in the editor.
> Fix for GHI12221: WhiteBox component crashes with Editor Mode Visual Feedback

- Code/Framework/AzCore/AzCore/Memory/Memory.h
Adds the name of the relevant class to the warning displayed when new is used instead of aznew, to make it easier to locate problems.
Used to track down a hard to locate usage of new.
> add class names to warnings about using not using aznew

- Code/Framework/AzCore/AzCore/std/ranges/ranges_algorithm.h
- Code/Framework/AzCore/Tests/AZStd/RangesAlgorithmTests.cpp
Fixed the `ranges::contains_subrange` unit test to expect true to be returned for an empty subrange(https://en.cppreference.com/w/cpp/algorithm/ranges/contains#Return_value).
> Corrected ranges::contain_subrange to return true for an empty subrange

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_03.py
Disabling ReflectionProbeAdded null render test which is failing intermittently on linux
hydra_AtomEditorComponents_ReflectionProbeAdded test is marked pytest skip pending further investigation of https://github.com/o3de/o3de/issues/12253
on ubuntu 20.04 test suite was executed 10 times with no failure
```
Test stability summary:
All tests were executed 10 times and passed 100% of the time.
new_user@ip-172-31-35-155:~/github/o3de$ ./scripts/ctest/ctest_entrypoint.sh --build-path ./build/linux --suite main --ctest-executable /usr/bin/ctest --config profile --tests-regex "AutomatedTesting::Atom_Main_Null_Render_03" --generate-xml --repeat 10
```
> Disabling ReflectionProbeAdded null render test

- Code/Tools/ProjectManager/Resources/ProjectManager.qss
- Code/Tools/ProjectManager/Source/CreateAGemScreen.cpp
- Code/Tools/ProjectManager/Source/CreateAGemScreen.h
- Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
- Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.h
- Code/Tools/ProjectManager/Source/ProjectManagerWindow.cpp
- Code/Tools/ProjectManager/Source/UpdateProjectCtrl.cpp
- Code/Tools/ProjectManager/Source/UpdateProjectCtrl.h
- scripts/o3de/o3de/engine_template.py
Set of fixes for Create Gem:
- Allow creating a gem from a template to use a folder that already exists if it is empty
- Error message in Project Manager UI if a folder is chosen that is not empty
- Allow commas as well as spaces for tag separation in engine_template.py
- Align form error messages to the left of the fields
- Do not allow spaces in user tag field (these would generate new tags and given instructions are to use commas)
- Fix the entry points to Create Gem, and reducing code duplication. This also fixes the back button to go back to an expected page.
> Multiple "Create Gem" fixes

- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/SpinBox.cpp
This fixes a problem where the user is unable to drag the the scale for a property in the scriptcanvas using the spinbox. another widget in the chain is consuming the mouse move event so this change will grab the mouse so events are handled exclusively for the active spinbox. I added some more logic to work on the screen where the mouse started to the wrapping logic. found that it only worked on the first screen in my multi-monitor setup.
https://user-images.githubusercontent.com/854359/192167997-dfc94c1c-c67e-47ad-8594-84315337e660.mp4
- open script canvas and create a heartbeat node.
> bugfix(Script Canvas): improve dragging behavior for spinbox for script canvas

- Gems/EMotionFX/Code/EMotionFX/Source/DualQuatSkinDeformer.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/DualQuatSkinDeformer.h
Switch to the job system instead of the task graph for CPU skinning. There are two deadlocks caused by using the taskgraph improperly that this fixes.
Tested in the editor using vertex-based bounding box calculations and loading a level with an actor in it - the two scenarios that were leading to a deadlock.
> Use job system instead of task graph for CPU skinning.

- AutomatedTesting/Gem/PythonTests/largeworlds/landscape_canvas/TestSuite_Main.py
- Gems/LandscapeCanvas/Code/Include/LandscapeCanvas/LandscapeCanvasBus.h
- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.h
- Gems/LandscapeCanvas/Code/Source/LandscapeCanvasSystemComponent.cpp
- Gems/LandscapeCanvas/Code/Source/LandscapeCanvasSystemComponent.h
Fixes #10746, #8207, #3922 and #10126
Added proper support for duplicating nodes in Landscape Canvas. The root of this change is that when duplicating nodes in Landscape Canvas, this means under the hood we need to duplicate their corresponding entities/components. When Landscape Canvas was originally written, we were still using slices, so the duplicate logic revolved around cloning an `AZ::Entity` and then serializing/deserializing the cloned entity (or entities). This needed to be completely replaced to work with prefabs instead.
- Updated to use the prefab duplicate API directly, rather than trying to clone the entities ourselves
- Removed all slice/cloning specific logic that is now unneeded
- Hid Cut/Copy/Paste actions. This is consistent with the currently supported prefab workflow …
> Fixed Landscape Canvas duplicate support

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_01.py
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_03.py
disables postfx shapeweight modifier and diffuse probe which are also causing failures
> disabling atom tests which add axis aligned box shape

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_01.py
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_03.py
disables tests which add axis aligned box then undo it. this has failed in at least two of these frequently.
> disabling tests which add axis aligned box

- AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/__init__.py
- AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/auto_test_fbx.fbx
- AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/scene_settings_tests.py
- AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/tests/__init__.py
- AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/tests/scene_settings_tests_in_editor.py
- Code/Editor/Plugins/EditorAssetImporter/AssetImporterPlugin.cpp
- Code/Editor/Plugins/EditorAssetImporter/AssetImporterPlugin.h
- Code/Tools/SceneAPI/SceneUI/CommonWidgets/SceneSettingsCard.cpp
1. Copies a temp FBX to the AutomatedTesting project
2. Opens the scene settings UI to that file
3. Verifies the initial status card exists + closes it
4. Perfoms a simple operation to mark the scene settings as dirty (toggles a field on/off)
5. Saves the scene settings to the scene manifest
6. Waits for this operation to finish
7. Verifies the status card was created and is interactable after the operation finishes
8. Verifies the scene manifest file was actually created on disk
This required two C++ changes:
1. A bus to allow the behavior context to open the scene settings menu to a file.
2. A change to how scene settings status cards are dismissed. DeleteLater was not working within the test.
Performs an …
> First automated test for scene settings UI:

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/ClientTransceiver.cpp
Signed-off-by: guillaume-haerinck <guillaume.haerinck@outlook.com>
fix https://github.com/o3de/o3de/issues/11584 by checking that RemoteToolsInterface is not nullptr.
It is the case if the "Remote Tools Connection" gem is not enabled.
The check is done with a syntax similar to the rest of the file.
Simply run the script canvas debugger and exit it
> Check for nullptr in ClientTransceiver::DisconnectFromTarget()

- Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
Manually adding a local gem then getting GemInfo was not setting the downloaded flag as it would when getting all gem infos, this was causing a gem added manually to report as not being downloaded causing issues creating a project using that gem.
> Fix manually adding a local gem

- Code/Tools/ProjectManager/Source/ProjectBuilderWorker.cpp
The split command of the progress dialog causes an out of bounds access when the build output does not have a newline yet.
Used Project Manager on MacOS
> Apply patch to fix crash in ProjectBuilderWorker on MacOS

- Code/Tools/ProjectManager/Source/DownloadRemoteTemplateDialog.cpp
- Code/Tools/ProjectManager/Source/ProjectUtils.cpp
- Code/Tools/ProjectManager/Source/ProjectUtils.h
Change to use the default template location for downloading templates.
Fixes indentation on GetDefaultProjectPath
> Use default templates folder for starting path for template location

- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/ColorPicker.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/ColorPicker.h
- Code/Framework/AzQtComponents/AzQtComponents/Utilities/ColorUtilities.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Utilities/ColorUtilities.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyColorCtrl.cpp
- Gems/Atom/Feature/Common/Code/Source/Utils/EditorLightingPreset.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicProperty/DynamicProperty.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorAreaLightComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorDirectionalLightComponent.cpp
Since the Color Picker operates in sRGB and the property being edited is Linear sRGB, the numbers do not match between Color Picker and the Property Inspector. This is intentional, but admittedly confusing as seen in these issues: 
- https://github.com/o3de/o3de/issues/4210
- https://github.com/o3de/o3de/issues/2980
- https://github.com/o3de/o3de/issues/3736
So I'm adding some alternate read-only fields to the Color Picker that will display the final output value in the destination color space. These values will match the value shown in the Property Inspector.
In the screenshot below...
- Most importantly, the "Linear sRGB Int" output **(3)** exactly matches the value shown in the Property Inspector **(5)**.
- The float edit fields **(1)** are moved up above the Quick Palette, closer to …
> Improved Color Picker Clarity

- Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.cpp
Cherry-pick linux mouse fix from dev to stabilization.
Fixed a bug on linux where the system mouse cursor would be permanently hidden.
See https://github.com/o3de/o3de-atom-sampleviewer/issues/509
>  Cherry-pick linux mouse fix

- Gems/Atom/Feature/Common/Code/Source/Utils/EditorLightingPreset.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicProperty/DynamicProperty.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorAreaLightComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorDirectionalLightComponent.cpp
Originally the color picker was set to be in sRGB, and configure a Linear sRGB property. This PR https://github.com/o3de/o3de/pull/6812 changed that so the color picker and the property were both treated as sRGB, to make the numbers match. It's understandable that the developer thought this was an improvement, but this change was not actually the correct thing to do. The most common and natural workflow is for artists to work in a sRGB color space, while the material and lighting systems store color values as Linear sRGB. That is why the color picker needs to be configured as it was originally. This should address https://github.com/o3de/o3de/issues/12227 and https://github.com/o3de/o3de/issues/11166
In the long term, we would like to expand the color picker to allow users to select what …
> Fixed the Color Picker color space for materials and lights.

- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
Fixes #12301
Fixes issue with the preview bounds not being parsed properly in Landscape Canvas due to the field property name changing. This resulted in connections to the preview bounds being lost anytime the nodes connections were refreshed.
Tested steps from the linked issue.
BEFORE:
AFTER:
> Fixed LC preview bounds not being parsed properly

- Gems/NvCloth/Code/Source/Pipeline/SceneAPIExt/ClothRule.cpp
Remove unnecessary include from SceneData in NvCloth, causing undefined references in debug/clang builds
Fixes the following
```
Code && /usr/bin/cmake -P /home/github/o3de/cmake/Platform/Linux/ProcessDebugSymbols.cmake /usr/bin/strip /usr/bin/objcopy /home/github/o3de/build/linux/bin/debug/libNvCloth.Editor.Gem.so dbg MODULE_LIBRARY DETACH /usr/bin/ld: lib/debug/libNvCloth.Editor.Static.a(ClothRule.cpp.o):
(.data.rel.ro._ZTVN2AZ8SceneAPI9SceneData22SceneNodeSelectionListE[_ZTVN2AZ8SceneAPI9SceneData22SceneNodeSelectionListE]+0x50): undefined reference to `AZ::SceneAPI::SceneData::SceneNodeSelectionList::GetSelectedNodeCount() const' /usr/bin/ld: lib/debug/libNvCloth.Editor.Static.a(ClothRule.cpp.o):
(.data.rel.ro._ZTVN2AZ8SceneAPI9SceneData22SceneNodeSelectionListE[_ZTVN2AZ8SceneAPI9Scene …
```
> Fix linux/debug linker errors in Linux/clang

- Gems/LyShine/Code/Source/LyShinePass.cpp
- Gems/LyShine/Code/Source/LyShinePass.h
When render pipelines are rebuilt the old pass hierarchy will stick around while the new one is being built. This means that for a brief moment, there will be two instances of the same pass on the same render pipeline. The LyShinePass connects to a single handler / multi address bus. This means when a new LyShinePass is created on render pipeline rebuild, it fails to connect to the bus because the old pass hasn't yet disconnected. The old pass then disconnects, and LyShine is left in a permanent zombie state where the pass bus isn't connected to anything.
#11749 refers to a specific case of this problem where adding a terrain world renderer component will break LyShine. This is because it adds a feature processor under the hood when the component activates, causing the pipeline to refresh …
> Fix for #11749 - LyShinePass ebus fix

- Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp
- Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.h
Fixing an issue where the DiffuseProbeGrid passes were getting removed because we were seting MSAA state after adding the pipeline to the scene
Ran Editor and ensured that DiffuseProbeGrid passes are still present
> Fixing an issue where the DiffuseProbeGrid passes were not available

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabViewportFocusPathHandler.cpp
Refreshes the Prefab Focus Path widget on initialization. This fixes issues where the widget would look empty if initialized after the level has already been loaded, for example when restoring the default Editor layout.
Fixes #12090
> Prefabs | Refresh Prefab Focus Path widget on init

- Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeAccumTransformNode.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeTwoLinkIKNode.cpp
- Gems/EMotionFX/Code/MCore/Source/AzCoreConversions.h
just replaces MCore::CreateFromAxisAndAngle with the equivalent method from AZ::Quaternion::CreateFromAxisAngle. both implements are basically the same the only main difference is MCore version normalizes the vector. not sure about the comment about this version being left handed and the AZCore version being right handed. I ended up writing a test to convince myself that both are equivalent after also comparing both implementations and seeing that they are the same with some subtle changes. There is also a small advantage with using simd operations with this change. 
```
class AngleTestFixture
: public UnitTest::ScopedAllocatorSetupFixture {
};
TEST_F(AngleTestFixture, ToAngleTest)
{
std::uniform_real_distribution<float> unif; …
```
> chore(EmotionFX): replace MCore::CreateFromAxisAndAngle with AZ::Quaternion::CreateFromAxisAngle

- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/ManipulatorManager.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/MultiLinearManipulator.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/MultiLinearManipulator.h
- Gems/WhiteBox/Code/Source/Viewport/WhiteBoxVertexTranslationModifier.cpp
- Gems/WhiteBox/Code/Tests/WhiteBoxComponentTest.cpp
ref: https://github.com/o3de/o3de/issues/10543
the active manipulator is getting called while the defaultMode is freed when switching mode. The active manipulator has just been freed causing a crash when the user releases the mouse button which causes MouseUpCallback to be called into freed memory.  This change will clear the active manipulator and adds logic to restore the mesh to the last serialized state so this should just clear the action that the user was just starting.  
follow the steps with the referenced ticket.
> bugfix(Whitebox): fix crash when switching modes while dragging manipulator

- Templates/AssetGem/Template/CMakeLists.txt
- Templates/CppToolGem/Template/CMakeLists.txt
- Templates/CppToolGem/Template/Code/CMakeLists.txt
- Templates/DefaultGem/Template/CMakeLists.txt
- Templates/DefaultGem/Template/Code/CMakeLists.txt
- Templates/DefaultProject/Template/Gem/CMakeLists.txt
- Templates/MinimalProject/Template/Gem/CMakeLists.txt
- Templates/PrebuiltGem/Template/CMakeLists.txt
- Templates/PrebuiltGem/Template/Code/CMakeLists.txt
- Templates/PythonToolGem/Template/CMakeLists.txt
- Templates/PythonToolGem/Template/Code/CMakeLists.txt
- cmake/Gems.cmake
- cmake/SettingsRegistry.cmake
- scripts/o3de/o3de/get_registration.py
- scripts/o3de/o3de/manifest.py
- scripts/o3de/o3de/print_registration.py
- scripts/o3de/tests/test_print_registration.py
Updated to Gem CMake targets templates to reference the "gem_name" from the gem.json
This changes makes it easier to rename a gem via updating it's
"gem_name" field in the gem.json file.
Previously users would also need to update the CMakeLists.txt to update
the target names to match the gem name in order for CMake to find the
`<gem-name>.<variant>` target that it checks before adding the gem module
filename to the generated `cmake_dependencies.<target>.setreg` which
indicates that the gem is active.
closes https://github.com/o3de/o3de/issues/12309
Added missing print_project_engine_name function to print_registration.py
The register-show command `--print-engine-name` command would attempt to
invoke a method to print the "engine" field from a `project.json` file,
but that function was …
> Reduce manual steps required to rename a gem

- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/SpinBox.cpp
This is just a cleanup pass on the spinboxWatcher, mainly removing the additional nested method call and consolidating things into a single method. A lot of the extra notes between the two methods means they are coupled pretty tightly to each other so It makes sense to consolidate and simplify. 
- verified spinbox in property widget and script canvas
> refactor(AZQtComponents): refactor SpinBox watcher

- Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp
- Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.h
ModelAssets are set to not auto-reload and when used by Actor assets, they are assigned a unique ID which means the custom reloading system does not handle autoreload either. This fix unloads the actor first to remove all old references, requests a reload of the ModelAsset, and then loads the actor again when that is complete
This fixes https://github.com/o3de/o3de/issues/9764
Manually following repro steps at the end of here: https://github.com/o3de/o3de/issues/9764
> Fix issue with actor reloading using old ModelAsset

- Code/Framework/AzCore/AzCore/std/azstd_files.cmake
- Code/Framework/AzCore/AzCore/std/utility/charconv.h
- Code/Framework/AzCore/Tests/AZStd/Charconv.cpp
- Code/Framework/AzCore/Tests/azcoretests_files.cmake
Added a UnitTest to test out the integer versions of to_chars/from_chars. 
Not all compilers current implement the floating point overloads
> Adding alias of the C++17 std::to_chars and std::from_chars functions

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.h
- Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.cpp
- Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.h
- Code/Tools/AssetProcessor/native/tests/AssetProcessorMessagesTests.cpp
- Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
- Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.h
- scripts/build/Platform/Android/build_config.json
- scripts/build/Platform/Linux/build_config.json
- scripts/build/Platform/Mac/build_config.json
- scripts/build/Platform/Windows/build_config.json
- scripts/build/Platform/iOS/build_config.json
If the command line flag is not set, the Asset Processor will emit an error if the Asset Database on disk is a future version, and then shut down, to preserve the database.
If the command flag is set, the Asset Processor will instead print a message that this event occured, and then create a new Asset Database.
Integration from Development.
Fixes the issue where branch Jenkins jobs would fail due to future asset database versions, by having the job create a new database in that situation.
Tested locally by making asset databases with future versions and running AP.
> Asset Database Future version check can now be downgraded from an error, via a command line flag + set this flag on Jenkins.

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
Fix: #11741
This PR fixes the crash when escaping prefab edit mode. See the issue for more details.
The changes were originally introduced from prefab overrides UX prototype #10943. The related two lines should be put under the overrides UX flag.
**Note: The flag is OFF by default and the two lines were added after the above PR. So the risk of merging this PR should be minimal.**
> Prefab | Fix crash on escaping prefab edit mode

- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/MaterialGraphName_ForwardPass.azsl.template
Updated material canvas experimental shader templates referencing include paths that have changed since the shader refactor.
Materials and shaders generated from the experimental template were failing in the asset processor. After this change, the generated code and assets compiled successfully and appeared in the report.
> Material Canvas: Fix include paths broken after shader refactor

- Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Draw/EditorStateMaskRenderer.cpp
- Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Draw/EditorStateMaskRenderer.h
- Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/EditorModeFeedbackFeatureProcessor.cpp
- Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/EditorModeFeedbackFeatureProcessor.h
This PR defers the usage of the EMVF mask material until the asset is successfully loaded. Previously, the attempt to load this asset occurred only once when the EMVF system component was activated. Under certain conditions, this asset was not ready and thus the attempt would fail, causing consumers of that material to dereference a null pointer.
Fixes https://github.com/o3de/o3de/issues/12221
Manual testing in the editor by myself and Lionbridge testers.
> Fix crash when EMVF mask asset is not ready.

- Gems/PhysX/Code/Source/Scene/PhysXScene.cpp
Fixed active actors to handle transform sync events outside of the scene lock
There are active actors and transform sync handlers that may lock the scene for write. We need to make sure we signal the events outside of the scene read lock
Unit tests. Manual tests in a test level reproducing the issue
> Fixed active actors to handle transform sync events outside of the scene lock

- AutomatedTesting/Gem/Code/enabled_gems.cmake
This is important to be able to debug Lua scripts
with Lua Editor (aka LuaIDE.exe).
Enabled the RemoteTools Gem in AutomatedTesting. Without this, you can not debug Lua scripts.
Made sure the LuaIDE can connect to the Editor and was able to debug lua code.  
This picture shows that the Editor Target appears in the LuaIDE.
> Enabled the RemoteTools Gem in AutomatedTesting.

- Code/Framework/AzCore/AzCore/RTTI/TypeInfo.h
- Code/Framework/AzCore/AzCore/std/chrono/chrono.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.cpp
- Code/Tools/LuaIDE/Source/LUA/LUAEditorSyntaxHighlighter.cpp
- Code/Tools/LuaIDE/Source/LUA/WatchesPanel.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/ReflectionProbe/ReflectionProbeComponentController.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Core/Core.h
Removed unneeded `s_nullTypeId_v` constant. This was triggering the following error
```
[2022-09-28T05:14:53.562Z] /data/workspace/o3de/Code/Framework/AzCore/./AzCore/RTTI/TypeInfo.h:520:44: error: 'constexpr static data member 's_nullTypeId_v' must have an initializer
[2022-09-28T05:14:53.562Z]   520 |         inline static constexpr AZ::TypeId s_nullTypeId_v;
```
Updated the chrono.h header to explicitly use the chrono namespace to distinguish between type names and function names. This was triggering errors such as
```
[2022-09-28T05:14:53.563Z] /data/workspace/o3de/Code/Framework/AzCore/./AzCore/std/chrono/chrono.h:2349:35: error: declaration of 'constexpr std::chrono::seconds AZStd::chrono::hh_mm_ss<Duration>::seconds() const' changes meaning of 'seconds' [-fpermissive] …
```
> AzCore and AzCore.Tests GCC build fixes

- Code/Framework/AzCore/AzCore/std/ranges/ranges_algorithm.h
- Code/Framework/AzCore/Tests/AZStd/RangesAlgorithmBenchmarks.cpp
- Code/Framework/AzCore/Tests/azcoretests_files.cmake
The `ranges::copy` and `ranges::copy_n` functions will use memcpy if the output type is trivially copyable and both iterators are contiguous.
The `ranges::copy_backward` function will use memmove if the output iterator value type is trivially copyable and both iterators are contiguous.
Also added memcpy/memmove to `ranges::move` and `ranges::move_backward` as well.
Verified that the existing [ranges copy](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/Tests/AZStd/RangesAlgorithmTests.cpp#L367) test succeed.
Added Benchmark Test to verify the optimizations
```
OKAY Library loaded: D:/o3de/o3de/build/windows/bin/profile/AzCore.Tests.dll
OKAY Symbol found: AzRunBenchmarks …
```
> Added optimization to ranges::copy/copy_n/copy_backward

- Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/IntermediateAssetTests.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/JobDependencySubIdTests.cpp
Updated APM to use a 0 ms single shot timer for ScheduleNextUpdate.  This puts the message in the queue to run on the next update reliably without any time component being required. 
Updated unit tests to remove now unnecessary sleep.
Fixed IntermedateAssetTest which was accidentally relying on the previous 1ms delay to avoid a process step.
Fixes https://github.com/o3de/o3de/issues/12313
Ran unit tests
> [LYN-15735] Asset Processor - Fixed sporadically failing AP unit test

- Code/Framework/AzCore/AzCore/EBus/EventSchedulerSystemComponent.cpp
- Code/Framework/AzCore/AzCore/EBus/ScheduledEvent.cpp
- Code/Framework/AzCore/AzCore/EBus/ScheduledEventHandle.cpp
- Code/Framework/AzCore/AzCore/EBus/ScheduledEventHandle.h
Fix for the warning we see from AZ::Events about handler mismatches during multiplayer matches
Signed-off-by: kberg-amzn <karlberg@amazon.com>
> Fix for the warning we see from AZ::Events about handler mismatches during multiplayer

- Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
Every modification made in material canvas was reporting warnings with the shadow catcher and other meshes that do not have irradiance properties in their materials. The changes early return from the function if the main property is not present.
Warnings no longer appear in material canvas console
> Material Canvas: Fix warnings with mesh feature processor setting irradiance properties on shadow catcher

- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/Translation/materialcanvas_en_us.ts
- Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp
Creating a placeholder Qt translation file to silence startup warnings and eventually update with proper translations unless it is possible to use the graph canvas translation system generically.
Launched material canvas to see that warning no longer appears on startup
> Material Canvas: Fix warnings caused by missing translation files

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Application/AtomToolsApplication.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
Registering crash function with behavior context to create failure cases. Some of the duplicate bindings should be moved to a common, lower-level location to be shared between the editor and other tools.
Resolves https://github.com/o3de/o3de/issues/12396
Duplicated from main editor and compiling to facilitate other tests that are being written separately.
> Material Canvas: Register crash function Python binding for automated testing failure cases

- Gems/AWSCore/Code/Source/AWSCoreInternalBus.h
- Gems/AWSCore/Code/Source/Configuration/AWSCoreConfiguration.cpp
- Gems/AWSCore/Code/Source/Configuration/AWSCoreConfiguration.h
- Gems/AWSCore/Code/Source/Credential/AWSDefaultCredentialHandler.cpp
- Gems/AWSCore/Code/Source/Credential/AWSDefaultCredentialHandler.h
- Gems/AWSCore/Code/Tests/Configuration/AWSCoreConfigurationTest.cpp
- Gems/AWSCore/Code/Tests/Credential/AWSDefaultCredentialHandlerTest.cpp
- Gems/AWSCore/Code/Tests/ResourceMapping/AWSResourceMappingManagerTest.cpp
Implements https://github.com/o3de/o3de/issues/10452
> Add to AWSCore support for retrieving AWS creds from EC2 instance profile

- Gems/AWSCore/Code/Tests/Credential/AWSDefaultCredentialHandlerTest.cpp
Signed-off-by: allisaurus <34254888+allisaurus@users.noreply.github.com>
Fixes https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/development/3224/pipeline/   
unit tests pass (and the reverse of this change, initialize to `true`, causes it to fail like above CI error)
> Fix uninitialized member variable in AWSCore test

- Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystem.cpp
- Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystemUtils.cpp
This PR adds checks to ensure that an already created pass template for EMVF is not created and attempted to register more than once. Although his shouldn't functionally change any behavior as the warning emitted by the Atom pass system early exits if it detects a duplicate creation for a given template, this fix will unclutter the editor logs with this warning and reduce misdirection when debugging viewport render related behavior.
This fix was tested manually in the editor.
> Check if EMVF passs templates are already created before creating. 

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphWidget.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphWidget.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp
Add colored icons next to items EMotionFX context menu. These icons correspond to the colors of the nodes they create when selected.
Fixes https://github.com/o3de/o3de/issues/11689
manually
> Add colored icons next to items in EMotionFX context menu

- Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/ImageBuilder.settings
Adds naming convention support for _linear and _splatmaps to the image builder profiles.
Locally created images using conventions, cooked and then utilized in the engine.
> adding new naming conventions for splatmaps

- Code/Framework/AzCore/AzCore/Serialization/Json/JsonImporter.cpp
- Code/Framework/AzFramework/AzFramework/IO/LocalFileIO.cpp
- Code/Framework/AzFramework/Tests/FileIO.cpp
Also added support to the JSONImporter to replace any aliases in the import path before appending it to the import path stack
This allows the `ResolveImports` function to be used with a path that
starts with a path that has the form of
`@gemroot:<gem-name>@/rest/of/path` and smartly update the import path
based on whether it the import filepath resolves to an absolute path in
which case it replaces the path importAbsPath value. Or if the import
path doesn't contain a fileio alias and is relative, it is appended to
the importAbsPath value.
Added Unittest to validate inplace replacement of a FileIO alias at the beginning of a path
> Updated the `LocalFileIO::ReplaceAlias` to substitute inplace

- Gems/Atom/RHI/Code/Include/Atom/RHI/ValidationLayer.h
- Gems/Atom/RHI/Code/Source/RHI.Private/FactoryManagerSystemComponent.cpp
- Gems/Atom/RHI/Code/Source/RHI/ValidationLayer.cpp
Now it's possible to specify the rhi device validation by both command line and setting registry by having this in a .setget file.
````
{
"O3DE": {
"Atom": {
"rhi-device-validation": "enable"
}
}
}
````
This is very useful for android platform since it's not possible at the moment to pass the validation by command line.
Also unified the logic into one function so it's simpler to read and follow.
Tested setting the validation using cvar, command line and setting registry.
> Added option to set rhi-device-validation in settings registry

- Code/Framework/AzCore/AzCore/Interface/Interface.h
- Code/Framework/AzCore/Tests/Interface.cpp
The AZ::Interface `Register` and `Unregister` functions no longer assert within them, but instead return an outcome with the error message should registration or unregistration fails.
Updated the AZ Interface UnitTest to check the Register/Unregister return outcome
> Updated the AZ::Interface Register function to return an Outcome

- Code/Framework/AzCore/AzCore/Utils/Utils.cpp
- Code/Framework/AzCore/AzCore/Utils/Utils.h
The GetProjectUserPath function queries the Settings Registry the `/O3DE/Runtime/FilePaths/SourceProjectUserPath` setting which stores the path the project user path which defaults to `<project-root>/user`
> Adding GetProjectUserPath utility function

- scripts/ctest/CMakeLists.txt
Re-enables the pytest sanity tests to run in serial to prevent xml race condition.
https://github.com/o3de/o3de/issues/11667 
Ran tests locally. By running in serial, this adds slightly under 9 seconds of additional test time.
> re-enables pytest sanity tests to run in serial

- .github/CODEOWNERS
Expand sig-content ownership for AzFramework Asset folders and include reviewers group
No testing done
> Expand sig-content ownership for AzFramework Asset folders

- Code/Framework/AzFramework/AzFramework/Asset/AssetRegistry.cpp
- Code/Framework/AzFramework/AzFramework/Asset/AssetRegistry.h
- Code/Framework/AzFramework/Tests/AssetRegistry.cpp
- Code/Framework/AzFramework/Tests/frameworktests_files.cmake
This greatly speeds up the GetLegacyMappingSubsetFromRealIds call which was previously looping over every entry to find the subset of legacy ids that belong to the provided real id.
This will address the performance impact from https://github.com/o3de/o3de/pull/12445, reducing time taken from about 4000ms to about 150ms.
Tested with above PR for speed improvement.
Added and ran unit test
> Asset Processor - Add registry reverse lookup for real id -> legacy id

- Gems/LyShine/Code/Editor/Animation/Controls/UiSplineCtrlEx.cpp
Fix a crash caused by double clicking on a key in the curve editor to delete the key. The issue was that the undo system wasn't in the correct state when the delete command was added.
Fixes #12219.
Manual testing by repeating steps in ticket multiple times, and also doing undo/redo.
> Fix crash in curve editor on double click

- Gems/LyShine/Code/Editor/Animation/UiAnimViewDialog.cpp
- Gems/LyShine/Code/Editor/Animation/UiAnimViewDialog.h
- Gems/LyShine/Code/Editor/EditorWindow.cpp
- Fixes curve editor icons not being found
- The curve editor docking widget does not draw when the layout is saved/restored when the curve editor is undocked. This issue seems to be related to UI Editor not using the fancy docking system, so a longer term fix would be to convert UI Editor to use fancy docking. The current workaround in this PR is to dock the sub-panes back up before saving the layout.
The new ViewMode related code was taken from TrackView.
Fixes #11616
Manual testing closing and re-opening curve widget, UI editor, main editor.
https://user-images.githubusercontent.com/82236305/194137274-78b76731-584a-415a-9158-ac96a8f1b8b0.mp4
https://user-images.githubusercontent.com/82236305/194137294-20bc9b29-d8b8-4369-97d9-176453c945b2.mp4
> Fix UI anim curve editor issues

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
This PR fixes a potential memory issue in create-entity workflow. The issue was observed when turning on CRT allocation for RapidJSON usage. PrefabUndoHelpers::AddEntity modifies the DOM that UpdateEntity relies on.
Change:
- Moved PrefabUndoHelpers::UpdateEntity call before AddEntity call
- Put DOM value pointers under limited scope
It was tested that it could resolve the memory issue in the branch in this PR https://github.com/o3de/o3de/pull/11860.
> Prefab - Fix memory issue in create entity operation

- Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayer.h
- Gems/Multiplayer/Code/Source/Components/MultiplayerComponentRegistry.cpp
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
- Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp
- Gems/Multiplayer/Code/Source/ReplicationWindows/ServerToClientReplicationWindow.cpp
Allow using the default sv_port value when hosting through the IMultiplayer interface, adds some safety guards to the component registry and some asserts to the mark always relevent methods to guarantee we don't create replicators in a bad state, and validate that all replicators marked relevent are in the correct role for replication
Signed-off-by: kberg-amzn <karlberg@amazon.com>
> Allow using the default sv_port value when hosting through the IMultiplayer interface, and adds some safety guards

- cmake/Tools/Platform/Android/android_deployment.py
Second attempt to deploy assets to an android device was failing because `mkdir` command fails since the folder already exists. Added function to create a path on device that checks if it exists first.
Deployed assets to android device from scratch, made a change to one asset and deployed again. Both deploys work now.
> Fixed error deploying assets to android after the first deploy

- Code/Editor/Plugins/ProjectSettingsTool/ProjectSettingsContainer.cpp
- Code/Editor/Plugins/ProjectSettingsTool/ProjectSettingsContainer.h
- Code/Framework/AzCore/AzCore/JSON/rapidjson.h
This mainly affects memory usage when large levels are loaded, not tiny ones.  It has to do with the storage of JSON DOM trees in memory.
This change makes RapidJSON no longer pool its allocations itself.  Instead it directly asks the AzCore SystemAllocator for memory.  The AzCore SystemAllocator already pools memory in 64k blocks itself for small allocations and reuses the memory in those blocks when they are returned.
The memory savings are roughly 2x for any time JSON is involved. They come from the fact that RapidJSON would ask for 64K bytes PLUS 32 extra bytes for a chunk header.  This would cause the AzCore SystemAllocator to have to ask for extra chunks since the
data would not fit in 1x 64 chunk.   What makes it worse is that
this would get doubled again by the fact that AzCore …
> Significantly reduces memory usage of Editor

- AutomatedTesting/Gem/PythonTests/editor_test_testing/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/editor_test_testing/TestSuite_Main.py
This re-enables the EditorTestTesting module and updates one of the pytest legacy methods.
Tested by locally running 1000 attempts without reproduction. Further investigated original bug logs and found errors not related to the test that caused the failures.
> reenables EditorTestTesting module

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasNodeable_Header.jinja
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvas_Nodeable_Macros.jinja
- Gems/StartingPointInput/Code/Source/InputHandlerNodeable.h
I noticed some gems & features (StartingPointInput, spawnables) were providing a default copy ctor to get around some issues compiling when using Script Canvas nodes. I added a memberwise copy ctor for nodeables for any properties that become member variables.
One concern I have is what if a user adds custom non-serialized members may want to add their own copy ctor, I'll add a tag to opt out of this behavior in an upcoming commit
> AutoGen a valid copy constructor for SC nodes

- Code/Tools/AssetProcessor/assetprocessor_test_files.cmake
- Code/Tools/AssetProcessor/native/tests/ApplicationManagerTests.cpp
- Code/Tools/AssetProcessor/native/tests/ApplicationManagerTests.h
- Code/Tools/AssetProcessor/native/tests/AssetCatalog/AssetCatalogUnitTests.cpp
- Code/Tools/AssetProcessor/native/tests/AssetProcessorMessagesTests.cpp
- Code/Tools/AssetProcessor/native/tests/AssetProcessorTest.cpp
- Code/Tools/AssetProcessor/native/tests/FileProcessor/FileProcessorTests.cpp
- Code/Tools/AssetProcessor/native/tests/FileProcessor/FileProcessorTests.h
- Code/Tools/AssetProcessor/native/tests/MissingDependencyScannerTests.cpp
- Code/Tools/AssetProcessor/native/tests/MockAssetDatabaseRequestsHandler.h
- Code/Tools/AssetProcessor/native/tests/PathDependencyManagerTests.cpp
- Code/Tools/AssetProcessor/native/tests/assetdatabase/AssetDatabaseTest.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.h
- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.h
- Code/Tools/AssetProcessor/native/tests/assetmanager/IntermediateAssetTests.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/JobDependencySubIdTests.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/ModtimeScanningTests.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/Validators/LfsPointerFileValidatorTests.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/Validators/LfsPointerFileValidatorTests.h
- Code/Tools/AssetProcessor/native/tests/utilities/JobModelTest.cpp
- Code/Tools/AssetProcessor/native/tests/utilities/JobModelTest.h
- Code/Tools/AssetProcessor/native/tests/utilities/StatsCaptureTest.cpp
- Code/Tools/AssetProcessor/native/unittests/AssetProcessingStateDataUnitTests.cpp
- Code/Tools/AssetProcessor/native/utilities/StatsCapture.cpp
Currently, the failed tests read database.sqlite from the current working directory and create one if the file doesn't exist. However, the tests don't clean up the database file during the tear down process. This becomes a problem when the current asset database version doesn't match the database version on disk/Jenkins since the tests keep reading the outdated database information on disk/Jenkins.
PR changes:
- Make sure that database.sqlite is only written to a temp folder and cleaned each time after the tests finish. 
- Refactor test code to remove the duplicate AzToolsFramework::AssetDatabase::AssetDatabaseRequests::Bus::Handler implementations. 
- Fix an issue in …
> Fix Asset Processor test failures caused by the future database version

- Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
Check LFS pointer files for autofail jobs, so that files which failed at the CreateJobs phase will also be validated.
Tested manually in AP and unit tests passed.
```
[ RUN      ] AssetProcessorManagerTest.SourceFileProcessFailure_AutoFailedLfsPointerFile_ReceiveLFSPointerFileError
[       OK ] AssetProcessorManagerTest.SourceFileProcessFailure_AutoFailedLfsPointerFile_ReceiveLFSPointerFileError (134 ms)
```
> Update the LFS pointer checking for autofail jobs

- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
Fix the issue for building AP automation tests. This is caused by the following two conflict PRs merged into dev together:
- https://github.com/o3de/o3de/pull/12446
- https://github.com/o3de/o3de/pull/12401
Built and ran the test locally.
> Fix test build failures caused by the AP LFS pointer tests

- Gems/PhysX/Code/Source/EditorColliderComponent.cpp
- Gems/PhysX/Code/Tests/RigidBodyComponentTests.cpp
Fixes a crash when either radius or height of the cylinder collider is set to zero.
Issue #12147
Unit tests, manual testing in the Editor
> #12147 Fixed crash when cylinder sizes are set to zero

- Code/Editor/EditorPreferencesPageViewportGeneral.cpp
- Code/Editor/EditorPreferencesPageViewportGeneral.h
- Code/Editor/EditorViewportWidget.cpp
- Code/Editor/EditorViewportWidget.h
- Code/Editor/Settings.cpp
- Code/Editor/Settings.h
ref: https://github.com/o3de/o3de/issues/12347
This removes the safe frame logic from the viewport. this is planning to get handled through LyShine. 
@hultonha  do we want to hold off until a replacement is made?
> chore: remove legacy safe frame

- Gems/Prefab/PrefabBuilder/PrefabGroup/DefaultProceduralPrefab.cpp
- Gems/Prefab/PrefabBuilder/PrefabGroup/tests/PrefabBehaviorTests.cpp
The prefab builder was ignoring transform nodes that were children of a mesh node. This PR fixes that by creating unique entities for transform nodes that are not associated with a mesh but are direct children of a mesh node.
More context on scene graph:
The first child transform of a mesh node in a graph contains the transform data associated with that mesh. All other child transform nodes of the mesh are considered actual children when preserving the parent/child hierarchy.
Fixes #12021 
Manual testing with the asset provided in the GHI #12021. Updated unit test to include this scenario and checked that it passed.
> Fix hierarchy for child transform nodes of a parent mesh node

- Code/Tools/ProjectManager/Source/PythonBindings.cpp
There was a weird issue discovered where shortly after a gem is created via Create a Gem workflow, trying to "View Directory" of said gem in the catalog produced a malformed directory link, leaving us unable to access the folder unless you close the program and restart.
This is the issue before the proposed fix:
After the fix:
The main issue was shown in the first gif. The rendered URL in the View Directory dialog uses %5C as the separator. This is an URL encoding for backward slash, which means the links were being rendered as windows paths instead of unix paths (which are compatible with URL links). The main fix was to update the CreateGem function in the PythonBindings to make sure to replace '\\' with '/' in the directory link field of the output `GemInfo` before returning the result.
> Fix View Directory Label Link with proper directory link after gem creation

- Code/Framework/AzCore/AzCore/Serialization/EditContext.h
- Code/Framework/AzCore/AzCore/Serialization/Utils.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
- Code/Framework/AzQtComponents/AzQtComponents/DPEDebugViewStandalone/main.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEnumComboBoxCtrl.hxx
- Gems/LyShine/Code/Editor/PropertyHandlerEntityIdComboBox.cpp
Adds support for the `EnumValues` attribute from `EditContext` to the DPE.
This is accomplished by way of ensuring the vector `EnumConstant`s contained by reflected `EnumValues` is guaranteed 64-bit, then adding an attribute handler to marshal the vector to and from the DOM.
There seems to be an issue in which `EnumValue` entries can be read and added when `EnumValues` is present, but I believe it to be unrelated to the attribute logic introduced here and I expect it should be straightforward to track down.
Created in response to discussion in https://github.com/o3de/o3de/pull/12306
Manually tested in the standalone DPE (with above noted issue). Unit testing would be wise, but I don't presently have the bandwidth to spec out a set of reflection adapter unit tests - happy to help anyone …
> Add support for reading `EnumValues` to the DPE.

- Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityContextBus.h
Fixes https://github.com/o3de/o3de/issues/12414
It was discovered that making call to EditorEntityContextRequests is not thread safe. Not sure why it would only be triggered in the repro steps in 12414, but I think it's a reasonable request to add the mutex type to EditorEntityContextRequests Bus.
> Add MutexType to EditorEntityContextRequests

- Code/Framework/AzCore/AzCore/Date/DateFormat.cpp
The function was incorrectly named
`GetFilenameCompatibleBasicFormatNowWithMicroseconds`
> Fixed misnamed `GetFilenameCompatibleFormatNowWithMicroseconds`

- Code/Framework/AzFramework/AzFramework/Entity/GameEntityContextComponent.cpp
In the function that destroys an entity and its descendants, it loops through all entities to be deleted. If an entity has a valid spawn ticket, it queues up a command to get the spawn ticket, and then returns. (Later when the spawn ticket is retrieved, a command to despawn the entity is queued, which ends up calling the same DestroyGameEntityInternal function, but this time the spawn ticket will be 0 and the entity will be deleted.)
This PR changes the "return" to a "continue" so that it can go through all entities to be deleted.
Fixes #12003
Tested using repro steps in the ticket. Also tested with nested children to make sure those get deleted as well.
> Fix early return when destroying entity and descendants

- Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
- Code/Tools/AssetProcessor/native/ui/MainWindow.ui
* added tab stops for each input field for the asset cache server
* added tool tips for the input fields
Manually used the Asset Processor GUI tool in the Shared Cache tool.
> {lyn15599} updating asset cache server tab ordering

- Gems/Atom/RHI/Vulkan/Code/Include/Atom/RHI.Reflect/Vulkan/XRVkDescriptors.h
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Instance.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp
ASV RHI and RPI samples crashed when running on Quest2 with GPU detailed profiling mode enabled (`'adb shell ovrgpuprofiler -e`), which allows the use of `GPU systrace` and `ovrgpuprofiler` tools.
There were 2 crashes when GPU detailed profiling mode is enabled:
1. XR pipeline calling `LoadProcAddresses` passing the physical device leads to vulkan extensions enabled when they are not supported in an XR environment. To fix this issue the RHI::Device just uses the glad context returned from XR, that way only XR's device is responsible to do `LoadProcAddresses`.
2. With an XR pipeline it crashes when creating the default swapchain. Since the default swapchain isn't used anyway in non-host platforms when there is an xr system, now it's not created, …
> Fix crash when running on Quest 2 with GPU detailed profiling mode enabled

- Code/Framework/AzCore/AzCore/Debug/PerformanceCollector.cpp
- Code/Framework/AzCore/AzCore/Debug/PerformanceCollector.h
- Code/Framework/AzCore/AzCore/Metrics/JsonTraceEventLogger.cpp
- Code/Framework/AzCore/AzCore/azcore_files.cmake
- Code/Framework/AzCore/Tests/Debug/PerformanceCollectorTests.cpp
- Code/Framework/AzCore/Tests/azcoretests_files.cmake
- Gems/Atom/RPI/Code/Source/RPI.Private/PerformanceCVarManager.cpp
- Gems/Atom/RPI/Code/Source/RPI.Private/PerformanceCVarManager.h
- Gems/Atom/RPI/Code/Source/RPI.Private/RPISystemComponent.cpp
- Gems/Atom/RPI/Code/Source/RPI.Private/RPISystemComponent.h
- Gems/Atom/RPI/Code/atom_rpi_private_files.cmake
Added a new class to AzCore/Debug called `PerformanceCollector`. It is a general purpose class that helps measure and record performance data. The output data is generated using AzCore/Metrics/JsonTraceEventLogger which produces JSON files in the Google Trace data format.
For details on how to use take a look at the file `AzCore/Tests/Debug/PerformanceCollectorTests`, but here is the gist of it:  
PerformanceCollector provides two mechanisms to measure code performance in `microseconds`:
1. Scope based:
Use the companion AZ::Debug::ScopeDuration class.  Let's say you want to measure the duration of a particular function:  
```cpp
void MyClass::MyFunction()
{
...  Some Code ...
}
```
Then you can do (Assuming MyClass owns or has access to a PerformanceCollector object.  
```cpp
void …
```
> The new AzCore/Debug/PerformanceCollector

- cmake/Gems.cmake
The `get_property` command doesn't update the output variable if the property name that is supplied is an empty string. This was causing the `o3de_find_ancestor_gem_root` function to be stuck in an infinite loop
fixes #12593
Configured the AtomSampleViewer project using an SDK engine
> Fix for cmake configure loop when using SDK

- Code/Framework/AzCore/AzCore/Task/TaskExecutor.cpp
- Code/Framework/AzCore/AzCore/Task/TaskExecutor.h
- Code/Framework/AzCore/AzCore/Task/TaskGraph.cpp
- Code/Framework/AzCore/Tests/TaskTests.cpp
Race condition was reading from the this ptr to a compiled task graph (CTG) after another thread had deleted the memory. On deletion some values (e.g. m_parent) would be filled with random data and move the CTG from the detached path to the retained path, which would cause a 2nd attempt to signal any wait event.
Debugging aid change
TaskGraph system can now keep a list of recent CompiledTaskGraph events to aid debugging issues.
https://github.com/o3de/o3de/issues/12015
tested by running locally
> Fix TaskGraph race condition in CompiledTaskGraph::Release

- Code/Editor/EditorViewportWidget.cpp
- Code/Editor/EditorViewportWidget.h
- Code/Framework/AzCore/AzCore/Task/TaskGraphSystemComponent.cpp
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/ViewportContext.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/ViewportContextBus.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassSystem.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RasterPass.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/RenderPipeline.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/ViewportContext.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRenderer.cpp
- Gems/AtomLyIntegration/ImguiAtom/Code/Source/ImguiAtomSystemComponent.cpp
- Gems/AtomLyIntegration/ImguiAtom/Code/Source/ImguiAtomSystemComponent.h
- Gems/ImGui/Code/Include/ImGuiBus.h
- Gems/ImGui/Code/Source/ImGuiManager.cpp
- Gems/ImGui/Code/Source/ImGuiManager.h
Improved CPU performance with the following optimizations:
- Removed a redundant call to UpdateVisibility at the end of the frame (~3ms)
- Switched culling to use jobs instead of task graph (~2.5ms)
- Switch the tools render pipeline to be off when created since it gets manually turned on and then off when it needs to do a capture (~0.5ms)
- Switch ImGui update to be multithreaded (up to 5ms when CPU profiler is running)
Those were the big ones if I'm not forgetting any. Other changes here are small things like removing perf markers that are too small to show up in profiling, adding perf markers for tasks that are definitely big enough to profile,
> Improved CPU performance by almost 13ms (37.48ms -> 24.74ms) on the RosCon level

- Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponentMode.cpp
Should fix issue #12486 . For some reason, these compile warnings are only showing up on periodic builds, not locally or on AR, but since this is the only source file showing up with problems, I think I've got them all.
Verified that the casts compile and work locally in a build.
> Fixed more potential compile warnings.

- Code/Tools/AssetProcessor/native/tests/AssetProcessorMessagesTests.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.h
Clean up AP tests to make sure that database connection is closed before destroy the temp testing folder.
Run AP tests locally and don't see the error related to QTempFolder any more.
> Clean up AP tests to make sure that database connection is closed before destroy the temp testing folder

- .gitignore
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
This PR is related to issue: https://github.com/o3de/o3de/issues/12290. According to the issue, I have deprecated `sv_isTransient` CVAR and added `sv_terminateOnPlayerExit` CVAR with it's description.
It isn't fully tested as it's a really small fix.
> added sv_terminateOnPlayerExit and deprecated sv_isTransient

- Code/Editor/CryEdit.cpp
- Code/Editor/MainWindow.cpp
- Code/Editor/WelcomeScreen/WelcomeScreenDialog.cpp
- Code/Framework/AzCore/AzCore/Utils/Utils.cpp
- Code/Framework/AzCore/AzCore/Utils/Utils.h
- Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp
The Editor Welcome Screen dialog and the GameLauncher window were also updated to use the Project Display Name.
Added a Utility function to read the project's display name from the Settings Registry.
Renamed the "display_name" in the AutomatedTesting project to "Automated Renamed Testing"
> Updated the Editor TitleBar to use the Project Display Name

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_01.py
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_03.py
This PR re-enables the tests that were disabled as part of GHI#12253: https://github.com/o3de/o3de/issues/12253 
The disabled test PRs are here:
- https://github.com/o3de/o3de/pull/12295 
- https://github.com/o3de/o3de/pull/12254
This ended up being the fix: https://github.com/o3de/o3de/pull/12367  
Tests were run on Linux and passed without issue.
> Re-enable disabled Atom Editor tests since GHI#12253 is fixed

- .github/ISSUE_TEMPLATE/deprecation_template.md
Add a template for deprecation notice. This template is used for create a github issue which is mentioned [here ](https://github.com/o3de/community/blob/main/guides/o3de-deprecation-guidelines.md#api-deprecation---initial-steps)
md file viewer
> Add a template for deprecation notice

- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/ImageBasedLights/EditorImageBasedLightComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/ImageBasedLights/EditorImageBasedLightComponent.h
This change will automatically set the matching Diffuse or Specular IBL image in the EditorImageBasedLightComponent.
> Automatically set the matching Diffuse or Specular IBL image in the Editor

- Code/Tools/AssetProcessor/native/unittests/AssetRequestHandlerUnitTests.cpp
- Code/Tools/AssetProcessor/native/unittests/AssetRequestHandlerUnitTests.h
Migrated the legacy AssetRequestHandlerUnitTests and broke it into multiple tests
```
[==========] Running 5 tests from 1 test case.
[----------] 5 tests from AssetRequestHandlerUnitTests
[ RUN      ] AssetRequestHandlerUnitTests.RequestToProcessAssetNotExistInDatabaseOrQueue_RequestSent_RequestHandled
[       OK ] AssetRequestHandlerUnitTests.RequestToProcessAssetNotExistInDatabaseOrQueue_RequestSent_RequestHandled (720 ms)
[ RUN      ] AssetRequestHandlerUnitTests.RequestToCreateCompileGroup_RequestSent_RequestHandled
[       OK ] AssetRequestHandlerUnitTests.RequestToCreateCompileGroup_RequestSent_RequestHandled (303 ms)
[ RUN      ] …
```
> Migrate the legacy AssetRequestHandlerUnitTests

- Code/Tools/AssetProcessor/native/unittests/FileWatcherUnitTests.cpp
- Code/Tools/AssetProcessor/native/unittests/FileWatcherUnitTests.h
Migrate the legacy FileWatcherUnitTests to the modern test framework.
The test has lots of hardcoded timeout. I'll create a separate task to investigate and get rid of them if possible.
```
[----------] 4 tests from FileWatcherUnitTest
[ RUN      ] FileWatcherUnitTest.WatchFileCreation_CreateSingleFile_FileChangeFound
[       OK ] FileWatcherUnitTest.WatchFileCreation_CreateSingleFile_FileChangeFound (405 ms)
[ RUN      ] FileWatcherUnitTest.WatchFileCreation_CreateMultipleFiles_FileChangesFound
[       OK ] FileWatcherUnitTest.WatchFileCreation_CreateMultipleFiles_FileChangesFound (1077 ms)
[ RUN      ] FileWatcherUnitTest.WatchFileDeletion_RemoveTestAsset_FileChangeFound
[       OK ] …
```
> Migrate the legacy FileWatcherUnitTests

- Gems/PhysX/Code/Source/EditorColliderComponent.cpp
- Gems/PhysX/Code/Tests/RigidBodyComponentTests.cpp
Fixes crash when setting cylinder collider subdivision count to invalid value (fixes #12608)
Unit test plus manual testing in editor.
> fix for crash on invalid cylinder collider subdivision count

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/AnimGraphPlugin.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphWidget.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphWidget.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/NodePaletteModelUpdater.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/NodePaletteModelUpdater.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/NodePaletteWidget.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/NodePaletteWidget.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/standardplugins_files.cmake
- Gems/EMotionFX/Code/Tests/ProvidesUI/AnimGraph/AnimGraphNodeTests.cpp
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/NodePalette/Model/NodePaletteSortFilterProxyModel.cpp
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/NodePalette/NodePaletteWidget.cpp
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/NodePalette/NodePaletteWidget.h
This PR migrates node palette dock (`EMStudio::NodePaletteWidget`) from custom solution to `GraphCanvas::NodePaletteWidget`.
Also, common code for building the tree model for the node palette in EMFX context menu and dock was extracted to a common helper class.
A bugfix for `GraphCanvas::NodePaletteAutoCompleteModel` also was discovered and fixed.
I encourage reviewing commit by commit.
Here's how it looks:
https://user-images.githubusercontent.com/104767/195676131-92acd1ab-137f-4fc2-bd71-50156a27e4f5.mp4
Note that my screen recorder didn't grab the nice pixmap that is following the cursor during the drag.
~~I'm putting this PR as a draft because I don't know how to fix memory allocation errors related to the new code:~~
The tests are fixed now
```
[ RUN      ] …
```
> GraphCanvas node palette in EMotionFX node palette dock

- Code/Tools/AssetProcessor/native/unittests/RCcontrollerUnitTests.cpp
- Code/Tools/AssetProcessor/native/unittests/RCcontrollerUnitTests.h
Migrated the legacy RCcontrollerUnitTests and broke it into multiple tests
```
[==========] Running 12 tests from 1 test case.
[----------] 12 tests from RCcontrollerUnitTests
[ RUN      ] RCcontrollerUnitTests.TestRCJobListModel_AddJobEntries_Succeeds
[       OK ] RCcontrollerUnitTests.TestRCJobListModel_AddJobEntries_Succeeds (322 ms)
[ RUN      ] RCcontrollerUnitTests.TestCompileGroup_RequestExactMatchCompileGroup_Succeeds
[       OK ] RCcontrollerUnitTests.TestCompileGroup_RequestExactMatchCompileGroup_Succeeds (305 ms)
[ RUN      ] RCcontrollerUnitTests.TestCompileGroup_RequestNoMatchCompileGroup_Succeeds
[       OK ] …
```
> Migrate the legacy RCcontrollerUnitTests

- Gems/Atom/RPI/Code/Source/RPI.Private/PerformanceCVarManager.cpp
- Gems/Atom/RPI/Code/Source/RPI.Private/RPISystemComponent.cpp
- Gems/Atom/RPI/Code/Source/RPI.Private/RPISystemComponent.h
Added new CVAR named `r_metricsQuitUponCompletion`, defaults to false. When true the application will quit when all frame batches have been measured for performance.
Added OS name and RHI name to the Log Category name: `Graphics-<OS>-<RHI>`. It will make it easy to keep vulkan and dx12 results side by side and easy to identify.
This is a cosmetic change but I made sure the GameLauncher  quits when all frames have been measured for performance.
Also made sure the output json file has the new name format: "Performance_Graphics-OS-RHI_DATE.json".
> Added quit option for performance collection.

- Gems/EMotionFX/Code/EMotionFX/Pipeline/RCExt/Actor/ActorGroupExporter.cpp
Many asset are failing now due to the EMotionFX: Ambigious mesh for actor asset. More than one mesh group found. Defaulting to the first one.
EMotionFX had this as AZ_Error because atom should only ever produce one true mesh group. Now that Procedural Prefab system also creates mesh group, it is only making sense to downgrade to a AZ_Warning.
P.S this PR related to https://github.com/o3de/o3de/issues/9309 
P.S.2 Is there a pattern of when Procedural Prefab create additional mesh group and when not? This seems to happen on certain assets, but not all of them.
> EMFX: Downgrade the AZ_Error to warnings when multiple mesh group is detected. 

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyRowWidget.cpp
- Code/Tools/SceneAPI/SceneUI/RowWidgets/TransformRowWidget.cpp
- Code/Tools/SceneAPI/SceneUI/RowWidgets/TransformRowWidget.h
ref: https://github.com/o3de/o3de/issues/12602
this just makes sure that the modifications that are introduced with the TransformwWidget is cleaned up with the component is deleted.  this is because PropertyRowWidget is recycled and reused so any change to the component will need to be undone when the widget is return to the pool
follow step in the referenced issue
> bugfix(ToolsFramework): ensure TransformRowWidget widget deletes additional components 

- Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/IntermediateAssetTests.cpp
AP was detecting the loop case but the override system was causing AP to reprocess the source again, causing an infinite loop.
Manual testing plus updated the existing unit test to verify it catches this issue
> Fix intermediate asset infinite loop

- Gems/Terrain/Assets/Shaders/Terrain/TerrainCommon.azsli
- Gems/Terrain/Assets/Shaders/Terrain/TerrainMaterialSrg.azsli
Removed unnecessary #include lines from terrain shader code.
These paths were not resolving to the intended files and were being reported as missing, but the compilation still passed because nothing in the shader code actually depended on these files. So I just deleted the offending #included statements. The errors were like D:/o3de/Gems/Terrain/Assets/Shaders/Terrain/TerrainCommon.azsli:11: error: Can't open include file "../Materials/Types/MaterialInputs/MetallicInput.azsli"
The shader files reprocessed in the AP with no errors reported.
> Removed unnecessary #include lines from terrain shader code.

- Code/Framework/AzCore/AzCore/std/azstd_files.cmake
- Code/Framework/AzCore/AzCore/std/string/fixed_string.cpp
- Code/Framework/AzCore/AzCore/std/string/fixed_string.h
- Code/Framework/AzCore/AzCore/std/string/fixed_string.inl
This reduces the number of template instantiations down to 1.
Externing the fixed_string<1024> class exposed a compiler error in the insert function, which is the other change
Built the and ran the AzCore.Tests
> Extern the AZStd::fixed_string<1024> template instantiation

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphWidget.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/NodeGraphWidget.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/NodeGraphWidget.h
Since the cellSize parameter was not used anyway, let's get rid of it.
It's a small code cleanup.
EMotionFX unit tests were executed and snapping in node graph was tested manually for regressions.
> EMotionFX: Don't use magic numbers for snapping

- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/ComponentModeCollection.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/ComponentModeCollection.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/ComponentModeSwitcher.cpp
The Image Gradient Component Mode wasn't defaulting back to Transform on exit. This was happening because in its exit code, it ran multiple event ticks while showing a progress bar during image asset saving, and the component switcher was using a timer to defer some logic to switch to Transform after the Component Mode ended. Since the mode hadn't fully ended at the point the timer triggered, the switch never occurred.
This change adds more information to make it clear that the component mode has begun ending, so the switcher no longer needs to defer its logic and it can handle things immediately.
Manually switched between Tube, Spline, Image Gradient, and Transform multiple times successfully.
> Bugfix for switcher defaulting back to Transform.

- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Culling.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/RenderPipeline.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/View.cpp
Changes:
**Culling.cpp**: changed WorkListCapacity from 5 to 9. This increases performance quite a bit as it increases the size of the array of visibility nodes we fill before we spawn a job to process that list (so less job spawning, longer jobs, better performance)
The rest of Culling.cpp is just cosmetic changes
**RenderPipeline.cpp**: Removed unnecessary call to reset views. Resetting the view resets the DrawListContext, which kills all the array and so the array capacity during the next draw list context gather will be 0, resulting in array growing and memory allocations. This changes lets the arrays keep their capacity for better draw item insertion.
**View.cpp**: Don't reset the DrawListContext if the mask is the same (for the same reason as just stated)
Update:
Added a commit with …
> Improved culling performance by 2.5ms (roughly 50%)

- scripts/build/build_failure_rca/rca_patterns/Asset-Processing.json
Added optional whitespace capture at end of regex to deal with a space at the end of the message
Untested since this runs on Jenkins
> Add optional whitespace capture to AP regex in root cause analysis config

- Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
Before this change:
With this change:
Editor with o3de-multiplayersample
> Editor names for archetype and network properties are more human readable

- Gems/LyShine/Code/Source/Sprite.cpp
Fixes a debugger assert/crash when closing a game launcher with LyShine assets on the level.
Game launcher under a debugger with o3de-multiplayersample
> LyShine shutdown assert/crash fix

- Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorDisabledCompositionComponent.cpp
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/BuilderSettingManager.cpp
The Atom Image Builder uses a set of user-definable file name suffixes to select the correct image settings for processing the image. These suffixes take the form “_albedo”, “_gsi”, etc. See https://www.o3de.org/docs/user-guide/assets/texture-settings/texture-presets/ for more details. The change that’s being made is that an additional condition is being added to the suffix check so they will only compare the filename between the last underscore and the first period. For example, the name “image_gsi.0000.tif” used to try comparing “_gsi.0000” to the image suffixes. Now it will compare “_gsi” and ignore the “.0000”.
There's also a small mostly-unrelated null crash fix in this PR that I found while debugging the builder code in the Asset Processor. I wasn't making it to the image builder …
> Image suffix support

- Code/Framework/AzFramework/AzFramework/API/ApplicationAPI.h
- Code/Legacy/CryCommon/ILevelSystem.h
- Code/Legacy/CrySystem/LevelSystem/LevelSystem.cpp
- Code/Legacy/CrySystem/LevelSystem/LevelSystem.h
- Code/Legacy/CrySystem/LevelSystem/SpawnableLevelSystem.cpp
- Code/Legacy/CrySystem/LevelSystem/SpawnableLevelSystem.h
- Gems/ImGui/Code/Source/LYCommonMenu/ImGuiLYCommonMenu.cpp
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
- Adding GetCurrentLevelName() method to AzFramework LevelSystem in order to remove Cry dependency. 
- Multiplayer will need to use this value in an upcoming PR
- Rename level blocking with its own EBus
A piece of #9666 
Making sure the updated code that was using the old GetLevelName is still working.
> Removing Cry Dependency for Getting the Current Level Name

- Code/Editor/Controls/FolderTreeCtrl.cpp
- Code/Editor/Controls/FolderTreeCtrl.h
- Code/Editor/Dialogs/PythonScriptsDialog.cpp
- Code/Editor/Dialogs/PythonScriptsDialog.h
ref: https://github.com/o3de/o3de/issues/12270
this resolves the ownership problems with CFolderTreeCtrl. This should resolve the crash problem observed in the referenced ticket. I also migrated the logic from the standard library and removed a lot of additional methods. I think the logic should be more clear with these changes. 
follow the steps in the referenced ticket.
> refactor: fix crash for CFolderTreeCtrl and cleanup logic

- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Client interpolation of objects was occasionally broken, when re-connecting from the same client or re-entering game mode in the Editor.
Fixes https://github.com/o3de/o3de/issues/12771 
In o3de-multiplayersample
> Fixes interpolation when re-connecting or re-entering game mode

- Gems/GraphModel/Code/Source/Integration/GraphController.cpp
- Gems/GraphModel/Code/Source/Model/DataType.cpp
- Gems/GraphModel/Code/Source/Model/Node.cpp
The flag to hide slots was only being respected when initially creating node UI. This change also adds handling for node configurations being rearranged, changing input slots to property slots and vice versa.
Before the change, duplicating and pasting nodes displayed slots that were hidden on the node UI when they were originally created.
After the change, the hidden slots remain hidden but appear in the inspector in material canvas.
Rearranging note configuration data to move property slots into the input slot list correctly updated the configuration and area where the slots are displayed.
> GraphModel: Fix bug where hidden graph model slots reappear after copy paste duplicate

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicProperty/DynamicProperty.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicProperty/DynamicProperty.cpp
Attempting to eliminate warnings, errors, or spam that might cause test failures.
Changes dynamic property class to only register soft or hard limits if there is an explicit type match instead of forcing limits to the standard ranges for the value type. This stops warning messages if there is a type mismatch or the type does not support limits.
Verified that dynamic properties continue to work for material editor, material canvas, and the settings dialog in atom tools.
> Fixed warning caused by dynamic property edit context range attributes being out of bounds for some types

- Gems/Atom/Tools/MaterialCanvas/Registry/gem_autoload.materialcanvas.setreg
- Gems/Atom/Tools/MaterialEditor/Registry/gem_autoload.materialeditor.setreg
- Gems/Atom/Tools/ShaderManagementConsole/Registry/gem_autoload.shadermanagementconsole.setreg
Python automated tests were just restored for material editor and material canvas. Test suites for both tools are just starting to be written. The test coverage gem has not been tested with those tools. It seems like it just needs to be configured correctly. It's currently triggering warnings on startup, which this change disables until that can get sorted out.
Confirmed corresponding warnings no longer appear after changes.
> Atom Tools: disable python test coverage gem in material canvas to stop warnings until it can be configured

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnailRenderer.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnailRenderer.h
Replace this hard coded product path references with asset IDs copied from asset processor.
Only attempts to queue the assets for load after the asset Catalog has been loaded just stop warnings about assets that can't be resolved.
Cleared asset cache and launched main editor and material editor before and after changes to see that messages no longer show
> Fix spam caused by preview and thumbnail render request before the asset catalog was loaded

- Code/Framework/AzCore/AzCore/Serialization/Json/AnySerializer.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
This change is only registering the data types needed to represent floating point matrix slots on material canvas nodes. Nodes and other test data that uses these new types will be submitted in a subsequent PR.
Using arrays of vectors because they map directly to the corresponding AZSL types, can easily be converted, and are reflected with edit context bindings that automatically work in the inspector without additional attributes for special container handling.
This PR also includes minor simplification to the JSON Any Serializer, removing redundant type checks and code paths.
Minor optimizations were also made for generating the inspector properties in the material canvas document class. Reserving space in containers. Moving data types.
Code …
> Material Canvas: Registering matrix slot data types

- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Exits the server application once all clients have disconnected if `sv_terminateOnPlayerExit `is true.
Addresses https://github.com/o3de/o3de/issues/12198
Opened a server and connected a client and then terminated the client. Observed the server correctly terminating.
> Terminate server on player exit if configured for it

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentSystem.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentSystemRequestBus.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentApplication.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystem.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
- Gems/Atom/Tools/MaterialCanvas/Scripts/TestOpenClose.py
- Gems/Atom/Tools/MaterialEditor/Scripts/UpgradeAllMaterials.py
Problems were occurring when opening documents from shortcut and menu actions. Modal message boxes can be displayed for documents that log warning and error messages. Opening a document triggers notifications that could subsequently cause the actions that triggered them to be deleted as part of menus refreshing. By deferring the open document commands to use a timer or tick bus, they will be invoked as part of the regular system tick instead of nested inside of the action callback with the potential warning or error message boxes.
Replaced all QTimers that could not be connected to a parent object for lifetime management with system tick bus.
The callbacks bound to most timers and the tick bus were updated to not capture the this pointer.
Some direct function calls were converted to bus …
> Atom Tools: Deferring open document actions to the system tick bus and fixing other timer usage

- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Material/MaterialAssignmentBus.h
- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h
- Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignment.cpp
- Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
The MeshFeatureProcessor was unaware of changes to the material instance, which required reloading the entity to update the mesh RayTracing data.
Added a MaterialAssignmentNotificationBus and handled the notification to update the mesh RayTracing data.
Tested Editot DX12/Vulkan
> Update RayTracing data when the material instance is changed

- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp
Makes sure the initial value of vsync_interval
CVar is used when initializing the swapchain.
Fixes the 2nd problem mentioned here: https://github.com/o3de/o3de/issues/12748
On windows set the `--vsync_interval=0` in the command line when starting Editor.exe. The FPS started almost at 200fps.
On windows set the `--vsync_interval=1` in the command line when starting Editor.exe. The FPS started almost at 60fps.
> Makes sure the initial value of vsync_interval

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterCreateEditWidget.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterCreateEditWidget.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterWindow.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterWindow.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/standardplugins_files.cmake
- Gems/EMotionFX/Code/Tests/ProvidesUI/AnimGraph/Parameters/AddParameter.cpp
- Gems/EMotionFX/Code/Tests/ProvidesUI/AnimGraph/Parameters/ParameterGroupEdit.cpp
- Gems/EMotionFX/Code/Tests/UI/CanEditParameters.cpp
- Gems/EMotionFX/Code/Tests/UI/CanOpenWorkspace.cpp
- Gems/EMotionFX/Code/Tests/UI/UIFixture.cpp
This moves the parameter properties edit/creation window into the inspector.
I's a re-submission of PR [!11702](https://github.com/o3de/o3de/pull/11702) that I had to take over. See that PR for technical discussion. I only added two commits that fixed minor issues and rebased the commit on top of the `development` branch tip because otherwise, the PR was accepted.
https://user-images.githubusercontent.com/104767/196743764-10518a2a-2058-45d2-91f1-c063b144edf3.mp4
Manually according to requirements. Also EMotionFX unit test suite was updated to test the functionality.
Fixes #10965
> 10965 move animgraph parameter props to inspector

- Gems/Atom/Feature/Common/Code/Source/SkyAtmosphere/SkyAtmosphereFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/SkyAtmosphere/SkyAtmosphereFeatureProcessor.h
- Gems/Atom/Feature/Common/Code/Source/SkyAtmosphere/SkyAtmospherePass.cpp
- Gems/Atom/Feature/Common/Code/Source/SkyAtmosphere/SkyAtmospherePass.h
Fixes issue where the SRG changed and the sky parent pass did not update the new SRG.
Moves the addition of new passes to the `AddRenderPasses` function instead of in RenderPipelineChanged.
Verified the bug existed before the change using the steps:
1. Create a level with a skyatmosphere component.
1. save the level and close the editor
2. open the editor and open the level
The sky loads but disappears - verified SRG values are zeroed in RenderDoc capture
After fix, the issue no longer repros in the Editor following the steps above
> Fix sky using wrong SRG and use AddRenderPasses

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentMainWindow.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/GraphView/GraphView.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/GraphView/GraphView.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasGraphView.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.h
• Ensures that all menus and actions in atom tools, material canvas, and graph view have the correct parents and shortcut contexts so that they clean up correctly and shortcuts are processed in the correct context depending on the focused widget. 
• Changed atom tools graph view to recycle actions instead of recreating every time the main menu is populated. 
• Reimplement a bug fix that might have been lost during an integration that made sure the main menu is populated with the correct set of graph view menu actions when tabbing between and closing documents.
Running material canvas script to open and close all of the test documents repeatedly.
Manually opening, closing, and rotating through open material canvas and material editor document …
> Material Canvas: Menu parenting and recycling fixes

- Gems/WhiteBox/Code/Source/WhiteBoxToolApiReflection.cpp
Added two methods from the `WhiteBoxToolApi` class for Python reflection: `MeshVertexCount` and `FaceVertexHandles`.
These two provide minimal support for accessing mesh data from whitebox components, like in the following code excerpt:
```
vertlist = []
facelist = []
vertexCount = mesh.MeshVertexCount()
for i in range(vertexCount):
vertHandle = azlmbr.object.construct('VertexHandle', i)
new_vert = mesh.VertexPosition(vertHandle)
vertlist.append([new_vert.x, new_vert.y, new_vert.z])
faceCount = mesh.MeshFaceCount()
for i in range(faceCount):
faceHandle = azlmbr.object.construct('FaceHandle', i)
new_face = mesh.FaceVertexHandles(faceHandle)
new_list = []
for f in new_face:
new_list.append(f.Index()) …
```
> added methods MeshVertexCount and FaceVertexHandles for accessing mesh data from Python

- Code/Framework/AzCore/AzCore/std/utility/expected.h
- Code/Framework/AzCore/AzCore/std/utility/expected.inl
- Code/Framework/AzCore/Tests/AZStd/RangesViewTests.cpp
Visual Studio 2022 17.4.0 Preview fix for the RangesViewTests.cpp
Apparently Visual Studio reverse_iterator implementation was changed to check for an `operator->` in the major release.
Built the AzCore.Tests project using both VS2019 and VS2022 17.4.0 Preview 4
> Visual Studio 2019 build fixes for expected changes.

- Templates/DefaultProject/Template/Registry/assetprocessor_settings.setreg
- Templates/MinimalProject/Template/Registry/assetprocessor_settings.setreg
The @PROJECTROOT@/Shaders folder wasn't added as a recursive scan folder due to the typo.
> Fixed typo in `recursive` option in the Project Template asset processor settings

- Code/Framework/AzCore/Tests/StatisticalProfilerTests.cpp
- Gems/Atom/Asset/ImageProcessingAtom/Code/Tests/ImageProcessing_Test.cpp
- Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
There are some compiling errors with clang-15 in regards to unused variables on linux. I'm currently using ubuntu 22.10 with a newer version of clang. 
verified that this is able to compile in clang-15
> chore: remove unused variables to compile for clang-15

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/EntryDelegate.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/EntryDelegate.h
tried to reproduce this crash but found trying to select an asset to edit in the asset browser would cause a crash: https://github.com/o3de/o3de/issues/12044. Don't think this is related to the linked ticket.
What i'm guessing is happening is AssetBrowserTreeView is deleted so m_assetBrowserSortFilterProxyModel goes out of scope and crashes when it tries to access the shared pointer when GetSelectedAssets is called. This changes the logic to using a signal and slot so this avoids having to share the raw pointer to the delegate. 
```
* thread #1, name = 'Editor', stop reason = signal SIGSEGV: invalid address (fault address: 0x95)
* frame #0: 0x00007fffec1deecf libEditorLib.so`int QAtomicOps<int>::loadRelaxed<int>(std::atomic<int> const&) …
```
> bugfix(Editor): crash with searching/renaming fields in the AssetBrowser

- Gems/GradientSignal/Code/Include/GradientSignal/Components/ImageGradientComponent.h
- Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
- Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.cpp
This PR adds bicubic filtering support for image gradients. While this could be useful in any application that needs to sample an image gradient at a higher resolution than the source image, this change was made mostly with the intention of improving terrain quality and allowing low resolution heightmaps to be used to make highly detailed terrain.
Here's an example of a 512x512 heightmap being spread over 4 kilometers with 0.5 meter query resolution. This means that each pixel in the source heightmap is spread over 8x8 meters, and makes up 16x16 geometry quads at the highest LOD
Image gradients already have bilinear filtering, and while this can help with small magnifications (less than 2x) it falls apart with large magnifications.
Bicubuc filtering solves this problem by considering not …
> [Terrain] Adding support for bicubic filtering to image gradients.

- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/Button.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ButtonGroup.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ButtonGroup.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiCluster.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiManager.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiManager.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiRequestBus.h
- Code/Framework/AzToolsFramework/Tests/Viewport/ViewportUiManagerTests.cpp
ref: https://github.com/o3de/o3de/pull/12833
This add a disable option for buttons for the switcher and cluster. The linked PR should have a video of this working in whitebox. 
example usage found here: https://github.com/o3de/o3de/pull/12833
> feat: add disable option for switcher and cluster

- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiManager.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiManager.h
ref: https://github.com/o3de/o3de/issues/12813
Looks like the ID's when you register a cluster are not unique so the overlapping id's will delete the wrong cluster when the transform mode icon is selected multiple times
Create Cluster --> 1 [1]
Create Cluster --> 2 [1,2]
Delete Cluster --> 1 [2]
Create Cluster --> 2 [2,2]
repeat steps in the linked ticket: https://github.com/o3de/o3de/issues/12813
> bugfix(Whitebox, AZToolsFramework): correctly generate unique ids for new Cluster, Switcher, TextField

- Gems/LyShine/Code/Editor/ViewportInteraction.cpp
OnTick is paused when the window loses focus so the viewport does not correctly handle the change. 
this is the call that would need to happen: `UpdateCanvasInEditorViewport`
follow steps listed from issue: https://github.com/o3de/o3de/issues/12365
> bugfix(UI Editor): prevent zoom when canvas window loses focus

- Code/Editor/Core/EditorActionsHandler.cpp
- Code/Editor/Core/EditorActionsHandler.h
Introduces fixes to the `Open Recent...` menu with the new Action Manager enabled.
- In the previous implementation, the full level path would be displayed instead of the display version;
- Fixed the list generation to skip levels that do not belong to the current project;
- Fixed index number to show the correct count (bug that is still in the legacy implementation).
Verified that the menu items open the correct files (had to refactor the code since now there is no longer 1:1 correspondence between the indices).
Legacy menu (new action manager flag off)
New menu (new action manager flag on)
(Note, the ordering of the levels is different due to testing, but the behavior is correct).
> Action Manager | Fixes to Open Recent menu displaying invalid levels

- Code/Editor/MainWindow.cpp
Fixes #12562
Removes the "Customize Toolbars..." menu item from the right click context menu of toolbars in the Main Window.
This functionality won't be available in the MVP for the new Action Manager but will be added as follow-up work. This prevents a crash when selecting that menu item when the new action manager is enabled.
> Disable toolbar customization menu item

- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.ui
A middle stack widget is added that contains placeholders for thumbnail and list view.
Buttons for switching between these views are added.
There's a new cvar for turning this placeholder design on and off. By default it's off.
To turn it on, do these steps:
1. Write the following in the console:
`ed_useWIPAssetBrowserDesign 1`
2. Close the the asset browser tab
3. Reopen it through Tools -> Asset Browser
https://user-images.githubusercontent.com/104767/198565557-51eab01e-4486-415d-b7a3-e0d37bb09e88.mp4
Manually tested
> Asset Browser: add placeholders for new design

- Code/Tools/AssetProcessor/native/unittests/AssetProcessorManagerUnitTests.cpp
- Code/Tools/AssetProcessor/native/unittests/AssetProcessorManagerUnitTests.h
- Code/Tools/AssetProcessor/native/unittests/MockApplicationManager.cpp
- Code/Tools/AssetProcessor/native/unittests/MockApplicationManager.h
- Code/Tools/AssetProcessor/native/unittests/MockConnectionHandler.h
Migrated the legacy asset processor manager unit tests to the modern test framework. The tests have no logic changes but I broke the huge tests into more than 10 smaller ones.
This PR depends on https://github.com/o3de/o3de/pull/12544.
```
[==========] Running 12 tests from 1 test case.
[----------] 12 tests from AssetProcessorManagerUnitTests
[ RUN      ] AssetProcessorManagerUnitTests.SkipProcessing_FeedFilesToIgnore_NoTasksGenerated
[       OK ] AssetProcessorManagerUnitTests.SkipProcessing_FeedFilesToIgnore_NoTasksGenerated (453 ms)
[ RUN      ] AssetProcessorManagerUnitTests.ProcessFile_FeedFileToProcess_TasksGenerated
[       OK ] …
```
> Migrate asset processor manager unit tests to the modern test framework

- scripts/build/Platform/Linux/build_config.json
- scripts/build/Platform/Windows/build_config.json
Resolves https://github.com/o3de/o3de/issues/12487#issuecomment-1297526928 
1. Reproduced issue with `CDK_VERSION` set to 1.154.0
2. Set `CDK_VERSION` to 1.179.0
3. Deployment now succeeds
4. Destroy also succeeds
> Update CDK version to 1.179.0 for AWSI periodic tests

- Gems/PhysX/Code/NumericalMethods/Source/DoublePrecisionMath/Quaternion.cpp
- Gems/PhysX/Code/NumericalMethods/Tests/DoublePrecisionMath/QuaternionTest.cpp
Fixes an error where the implementation of GetConjugate for double precision quaternions was returning the negative of the conjugate. The negative of a quaternion is in some senses an equivalent rotation, so I don't think this would have had a big impact, and doesn't seem to have affected the automatic joint fitting (which is the only feature using the double precision quaternion), but it was technically incorrect.
Ran unit tests. Tested automatic joint limit fitting in the animation editor.
> fix mistake in double precision quaternion conjugate

- Code/Framework/AzCore/AzCore/Math/Geometry3DUtils.cpp
- Code/Framework/AzCore/Tests/Math/Geometry3DUtilsTests.cpp
- Code/Framework/AzCore/Tests/azcoretests_files.cmake
Fixes an issue where some vertices from GenerateIcoSphere were not normalized to unit radius.
Added a unit test to check that all vertices in the icosphere have unit radius.
> fix issue with not all vertices in icosphere getting normalized

- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/PaintBrushManipulator.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/PaintBrushManipulator.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/PaintBrushNotificationBus.h
- Code/Framework/AzToolsFramework/AzToolsFramework/PaintBrushSettings/PaintBrushSettings.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/PaintBrushSettings/PaintBrushSettings.h
- Code/Framework/AzToolsFramework/AzToolsFramework/PaintBrushSettings/PaintBrushSettingsNotificationBus.h
- Code/Framework/AzToolsFramework/AzToolsFramework/PaintBrushSettings/PaintBrushSettingsRequestBus.h
- Code/Framework/AzToolsFramework/AzToolsFramework/PaintBrushSettings/PaintBrushSettingsSystemComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/PaintBrushSettings/PaintBrushSettingsSystemComponent.h
- Code/Framework/AzToolsFramework/AzToolsFramework/PaintBrushSettings/PaintBrushSettingsWindow.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/PaintBrushSettings/PaintBrushSettingsWindow_Internals.h
- Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponentMode.cpp
- Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponentMode.h
This replaces intensity/opacity in the paintbrush APIs with a single AZ::Color value, and adds a paintbrush color mode so that each component mode can specify whether they want linear color, SRGB, or greyscale. 
The paintbrush settings themselves will show either a color picker or an intensity slider depending on whether color or greyscale is selected. The opacity slider remains as well for better UX usability, even though the opacity value just gets merged into the AZ::Color from an API perspective.
The Image Gradient painting code only uses the greyscale mode, nothing currently uses the color mode.
The color mode was tested in a local branch in which the Terrain Macro Material supports color painting. I was able to use this to verify that the color picking works for component modes that …
> [Terrain] Change underlying paint brush settings code to support color.

- Code/Tools/AssetProcessor/native/unittests/AssetProcessingStateDataUnitTests.cpp
Refactor and break the AP state data unit tests. Test all the existing functionalities in the current test. 
**Suggest to treat these as new unit tests for review due to the huge refactor.**
```
[==========] Running 37 tests from 1 test case.
[----------] 37 tests from AssetProcessingStateDataUnitTest
[ RUN      ] AssetProcessingStateDataUnitTest.TestScanFolder_AddScanFolder_Succeeds
[       OK ] AssetProcessingStateDataUnitTest.TestScanFolder_AddScanFolder_Succeeds (339 ms)
[ RUN      ] AssetProcessingStateDataUnitTest.TestScanFolder_AddDuplicateScanFolder_GetsSameId
[       OK ] AssetProcessingStateDataUnitTest.TestScanFolder_AddDuplicateScanFolder_GetsSameId (306 ms)
[ …
```
> Refactor and break the AP state data unit tests

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/PhysicalDevice.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/PhysicalDevice.h
This PR enables the Vulkan device extensions
* `VK_KHR_ray_query`
* `VK_KHR_SHADER_ATOMIC_INT64`
* `VK_EXT_SHADER_IMAGE_ATOMIC_INT64`
and enables the following device features if they are supported:
* `rayQuery`
* `shaderInt64`
* `shaderImageInt64Atomics`
* `sparseImageInt64Atomics`
* `shaderBufferInt64Atomics`
* `shaderSharedInt64Atomics`
* `shaderBufferInt64Atomics`
I ran the AtomSampleViewer with Vulkan RHI and almost all tests pass (the hot-reload tests fail, which they also did before changing anything; and three other tests fail for being slightly above the error threshold, but this is very unlikely to be caused by these changed)
> Enable ray query and shader int64 atomics Vulkan device features

- AutomatedTesting/Levels/Multiplayer/AutoComponent_NetworkInput/AutoComponent_NetworkInput.scriptcanvas
Replace the outdated node in the SC graph to fix the AP processing failure. Graph looks like below after the change:
Process the file locally without errors.
> Replace the outdated Extract Properties node in the AutoComponent_NetworkInput graph

- Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerStats.h
- Gems/Multiplayer/Code/Source/MultiplayerStats.cpp
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Instruments a metric for `clientConnectionCount` within MultiplayerStats.
* unit tests pass
* running _o3de-multiplayersample_ with this change results in client count being output to the "args" object of network metrics objects:
```json
// test on localhost with 2 clients running
{"name":"Stats","cat":"Networking","ph":"C","ts":1667341975203292,"pid":27960,"tid":27744,"args":{"NumEntities":274.0,"FrameTimeUs":1881.234375,"ClientConnections":2.0}},
{"name":"Stats","cat":"Networking","ph":"C","ts":1667341976201165,"pid":27960,"tid":27744,"args":{"NumEntities":274.0,"FrameTimeUs":1972.5546875,"ClientConnections":2.0}},
{"name":"Stats","cat":"Networking","ph":"C","ts":1667341977218809,"pid":27960,"tid":27744,"args":{"NumEntities":274.0,"FrameTimeUs":1938.296875,"ClientConnections":2.0}},
```
> Add clientConnectionCount perf metric to Multiplayer gem

- CMakeLists.txt
- cmake/3rdParty/FetchRGA.cmake
(this makes this file work on versions of cmake earlier than 3.23)
Hashes were added (SHA256) to ensure that the files downloaded were exactly the expected ones at the time of snapshot (security).
Timestamp option was removed - its not necessary for this package and is a brand new feature only in a very new version of cmake.
> Makes FetchRGA older-cmake-version compatible and adds hashes

- Gems/WhiteBox/Code/Source/WhiteBoxToolApiReflection.cpp
- Gems/WhiteBox/Editor/Scripts/default_shapes.py
ref: https://github.com/o3de/o3de/issues/8263
add null checking to avoid a crash in whitebox when running from python. 
run this is the command line window
```
PyRunFile <project>/o3de/Gems/WhiteBox/Editor/Scripts/default_shapes.py 1 1 1
```
> bugfix(Whitebox): fix crash where default_shapes.py is run with invalid arguments

- AutomatedTesting/Gem/PythonTests/Atom/tests/MaterialEditor_Atom_BasicTests.py
- This PR adds more test material checks to the existing Material Editor basic tests.
- The other tests that were part of the source ticket involved mouse movements and functionality with the mouse, which is something we avoid automating in our null renderer tests. This reduced the complexity of the parts of the test to add and that's why it appears like a small change.
- I also updated the language regarding material documents to be more clear (it made a lot of confusing references previously such as "material asset file" - they are just material documents).
Ran test command: ` C:\git\o3de\python\runtime\python-3.10.5-rev1-windows\python\python.exe -m pytest -vv -s --build-directory="C:\git\o3de\build\bin\profile" C:\git\o3de\AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Main_Null_Rende …
> Adds some extra material document file checks to the MaterialEditor basic tests.

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_MaterialEditor_01.py
- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_tools_utils.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/MaterialEditor_Atom_ExpectsCrashFailure.py
Adds a test to verify crashing is a failing result and that the `azlmbr.atomtools.general.crash` binding works as expected.
Test command used: `C:\git\o3de\python\runtime\python-3.10.5-rev1-windows\python\python.exe -m pytest -vv -s --build-directory="C:\git\o3de\build\bin\profile" C:\git\o3de\AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Main_Null_Render_MaterialEditor_01.py`
Results: `=== 4 passed, 3 xfailed in 44.19s ===`
> MaterialEditor crash test.

- Gems/LyShine/Code/Editor/ViewportInteraction.cpp
- Gems/LyShine/Code/Editor/ViewportInteraction.h
simplify and remove usage of legacy Vec2i. 
- verify zooming and moving around UI canvas
> refactor(UI Canvas): remove crylegacy Vec2i and simplify pivot logic for SetCanvasToViewportScale

- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ButtonGroup.cpp
- Gems/WhiteBox/Code/Source/SubComponentModes/EditorWhiteBoxTransformMode.cpp
ref: https://github.com/o3de/o3de/issues/12818
This adds a disabled state when a single vertex is selected in whitebox. when a single vertex is selected I disable both the rotation and scale options and switch to translate mode. not sure if this is better since this will switch the mode for the user seems to be just as good to allow this.
for usability I use the user selection as the staged mode so when the user clicks to a face/edge I restore their selection. 
[Screencast from 2022-10-26 20-26-30.webm](https://user-images.githubusercontent.com/854359/198184363-132695a7-a9f5-441c-9d76-ed3acc651aeb.webm)
details described in: https://github.com/o3de/o3de/issues/12818
> bugfix(Whitebox): add disable state for button cluster

- Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
Fix missing qRegisterMetaType call for SourceAssetReference
Manually verified Qt-Warning message about missing metatype no longer appears when processing assets
> Asset Processor - Fix missing qRegisterMetaType call for SourceAssetReference

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphCompiler.h
ref: https://github.com/o3de/o3de/issues/11225
The last attempt at this introduced a breaking change where this would fail with the vulkan validation layer: https://github.com/o3de/o3de/pull/11381
after reviewing the specification it seems just enough to add the stage to mark a transfer. should be able to then set the access for a write transfer. 
need to repeat the steps here: https://github.com/o3de/o3de/pull/10876
> bugfix(RHI): set VK_PIPELINE_STAGE_TRANSFER_BIT when pipeline has an explicit clear

- Gems/Multiplayer/Code/Source/Components/NetworkHitVolumesComponent.cpp
Fixes a bug where Network Hit Volumes were registered for pre-render updates
Tested in o3de-multiplayersample
> Pre-render fix for network hit volumes

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorApi.cpp
just adding null pointer checks and early returns
Before changes, material canvas dynamic node config property editor would crash, trying to retrieve a display name while adding elements to an empty map from the property editor.
After changes, the crash no longer occurs.
> Fix reflected property editor crash adding new elements to container types

- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUndoAddEntityTests.cpp
Fix a crash from unit test PrefabUndoAddEntityTests:: PrefabUndoAddEntity_AddEntityUnderUnfocusedInstance by using instance after propagation for validation instead of before.
Ran all unit tests in AzToolsFramework.Tests and passed.
> Fix PrefabUndoAddEntityTests crash

- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.ui
- Code/Editor/Style/Editor.qss
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/Internal/RectangleWidget.h
This is a preliminary work for two-column layout.
* Some paddings are gone.
* When a category is selected in the filtered search field, the remaining buttons in the asset browser still align to the top. Before they got centered and looked weird
* Search area is separated from the views area with a 1px line of the same color as the splitters
* Splitter between the tree view and asset preview now stretches all the way up and down forming nice line
* Unnecessary padding (due to window margin and scroll area frame) in the Asset Browser window were reduced to 0
Drive-by: Add a missing Q_PROPERTY macro to
AzQtComponents::Internal::RectangleWidget.
Task-Id: o3de/o3de#12855
Asset Browser is made to look more like on the current Figma designs. …
> Improve Asset Browser design

- scripts/build/Platform/Linux/build_config.json
Add Linux profile_nounity to daily metrics job. 
> Add Linux profile_nounity to daily metrics job

- Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialSourceData.h
- Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialTypeBuilder.cpp
- Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialSourceData.cpp
AP dependencies are case sensitive and the case of the shader file references were wrong. So the intermediate .materialtype file was not being reprocessed as needed. Also improved error reporting in MaterialSrouceData where the original source file path was not being included.
Ran the AP on linux before and after. Touched the .shader file and saw the .materialtype get reprocessed.
ASV full test suite on pc dx12, no changes.
ASV material screenshots test on linux vulkan. It seems ASV automated testing isn't supported yet on linux, it couldn't find any of the baseline images. But watching the materials screenshot tests, I could see that it was rendering things as expected. I also manually tested the material pipeline test …
> Fixed a case sensitivity bug in MaterialTypeBuilder on Linux.

- Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp
- Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Draw/DrawableMeshEntity.cpp
- Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Draw/EditorStateMeshDrawPacket.cpp
- Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystem.cpp
Fixes https://github.com/o3de/o3de/issues/12682
The pass of editor mode feedback was only added to the render pipeline once because it was doing an early return if the pass template was created. But when the pipelines are reinitialized (for example when setting the MSAA state) then it doesn't re-add the pass because the pass template was already created.
Updated the early return to check if the pass is in the render pipeline fixed the issue.
This PR includes other small improvements done while investigating the issue.
Now the editor mode feedback won't add null draw packets to the system and instead it will print an error if the draw packet generated was incorrect, this way it'll be easier in the future to identify the error since the message …
> Fix editor mode feedback, the pass was only added to the pipeline once.

- Code/Editor/CryEditDoc.cpp
It was possible to select "Exit" while in Component Mode, which could cause the work currently being done in Component Mode to get lost. This gives Component Mode a chance to save the work before exiting.
In particular, this improves two behaviors for the Image Gradient Component Mode:
1. Ensures that the user has a chance to save the image when Exiting the Editor.
2. Ensures that the Paint Brush Settings window closes cleanly and doesn't reappear on the next run of the Editor.
Exited the Editor while in Component Mode and verified that it ended Component Mode before exiting.
> Force Component Mode to close when exiting the Editor.

- Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
If an image reload happens (from the user editing and saving the image in a paint program for example) while still in image edit mode, instead of asserting and/or crashing, the Editor now replaces the painted data with the newly-reloaded data and lets the user keep painting. The one quirky part is that any existing undo/redo buffers will no longer directly match the modified image, so they can introduce unwanted artifacts if the user tries to undo/redo painted data into an image that has been reloaded this way. Not perfect, but it's a better experience than crashing. :)
This is just handling an edge case behavior, because the user really _shouldn't_ try to paint on the same image from two different programs at the same time and have any expectations about the chaos that might ensue.
Tried …
> [Terrain] Make editing during an image reload more stable.

- Code/Editor/AnimationContext.cpp
- Code/Editor/SelectLightAnimationDialog.cpp
- Code/Editor/SelectSequenceDialog.cpp
- Code/Editor/TrackView/SequenceBatchRenderDialog.cpp
- Code/Editor/TrackView/TrackViewDialog.cpp
- Code/Editor/TrackView/TrackViewPythonFuncs.cpp
- Code/Editor/TrackView/TrackViewSequenceManager.cpp
- Code/Legacy/CryCommon/IMovieSystem.h
- Code/Legacy/CrySystem/SystemInit.cpp
The MovieSystem is implemented by the Maestro gem, if this gem is not part of the project or built into the engine the engine would fail to run. Given that gems are optional components, I removed the strict dependency and safeguarded calls to retrieve the IMovieSystem. 
No longer show TrackView as an option if no MovieSystem is present.
Ran the editor, verified no crashes, then verified TrackView no longer shows in the tools menu
> Removed strict dependency of O3DE on the MovieSystem (which is a gem)

- Gems/WhiteBox/Code/Source/SubComponentModes/EditorWhiteBoxTransformMode.cpp
ref: https://github.com/o3de/o3de/issues/12816
for uniform scale only the Z axis is set. This adds logic to handle scaling uniformly. 
follow steps here: https://github.com/o3de/o3de/issues/12816
> bugfix(Whitebox): fix uniform scale for manipulator mode

- AutomatedTesting/Gem/PythonTests/Terrain/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/Terrain/TestSuite_Main.py
- AutomatedTesting/Gem/PythonTests/Terrain/TestSuite_Periodic.py
- AutomatedTesting/Levels/Terrain/TerrainPhysicsCollider_MaterialMapping_Works/TerrainPhysicsCollider_MaterialMapping_Works.prefab
- Moves test_TerrainPhysicsCollider_MaterialMapping_Works to Periodic suite for further investigation
- Updates level used in test_TerrainPhysicsCollider_MaterialMapping_Works to remove SelectionComponent deprecation warning
Ran new Periodic test suite locally.
> Moving intermittently failing test to Periodic suite

- Gems/Atom/Feature/Common/Code/Source/CubeMapCapture/CubeMapRenderer.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ParentPass.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
- Gems/LyShine/Code/Source/LyShineFeatureProcessor.cpp
- Gems/LyShine/Code/Source/LyShineFeatureProcessor.h
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
- Fixed issue with invalid pass cached in terrain FP when remove render pipeline
- Check reference pass before insert pass for LyShine FP and Terrain FP
Enable render pipeline modification for cubemap baking render pipeline
Fixed some errors reported by LyShine  feature processor and Terrain feature processor when enable them for cubemap baking
Open Sponza level in Editor. Add an entity with Cubemap Baker component. In level prefab, add Terrain Renderer and Terrain level components.
Press capture button and see the cubemap was baked successfully with GI baked in the cubemap texture. 
No errors in the editor error window. 
(There are warnings in the output, they will be addressed separately).
> Enable render pipeline modification for cubemap baking render pipeline

- scripts/o3de/o3de/gem_properties.py
- scripts/o3de/tests/test_gem_properties.py
This PR provides the ability to specify platforms for gems in `edit_gem_props` in `gem_properties.py` of the o3de CLI tooling.
Unit tests have been updated to test for platform changes. The tests are passing.
```
c:\workspace\o3de(Prism/PythonPlatformSupportEditGemProperties -> upstream)
λ python\python.cmd -m pytest scripts\o3de\tests\test_gem_properties.py
Pytest custom argument "--build-directory" was not provided, tests using LyTestTools will fail
Pytest custom argument "--output-path" was not provided, defaulting Test Results output to: c:\workspace\o3de\pytest_results\2022-11-07T16-21-13-491375
=================================================================== test session starts …
```
> adding platform support for editing gem properties in python CLI

- Code/Framework/AzCore/AzCore/Memory/AllocatorManager.h
- Code/Framework/AzCore/AzCore/Name/NameDictionary.h
- Code/Framework/AzCore/AzCore/std/createdestroy.h
VS2022
Built AzCore.Tests using VS2022
> Simplified `construct_at` SFINAE to avoid internal compiler error in

- Gems/Atom/RPI/Code/Tests.Builders/AnyAssetBuilderTest.cpp
- Gems/Atom/RPI/Code/Tests.Builders/PassBuilderTest.cpp
- Gems/Atom/RPI/Code/Tests.Builders/ResourcePoolBuilderTest.cpp
Update RPI builder unit tests which will clean up temporary files generated by the unit tests which unblocks the TIAF pipeline work. 
Run unittests in Atom_RPI.Builders.Tests and make sure the temporary files are deleted after tests end.
> Use ScopedAutoTempDirectory for files generated in RPI builder unit tests.

- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
- Code/Framework/AzQtComponents/AzQtComponents/DPEDebugViewStandalone/main.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h
This PR adds support to the DPE for the `AZ::Edit::Attributes::Readonly` attribute. Nodes with this attribute set will be disabled when their property handler widget is created in `DPERowWidget::CreateWidgetForHandler`.
Any existing ReadOnly attribute will be detected per node and its value stored in the node's disabled flag prior to caching attributes in the LegacyReflectionBridge. When caching attributes, we already check if the node should be disabled (as is the case with set data structures) hence we roll the legacy ReadOnly attribute into our DPE Disabled attribute. Also, child nodes of disabled parents will inherit the Disabled attribute and elements of ReadOnly containers will disable their container action buttons.
Box 1 in the image below shows that non-readonly …
> DPE: Add support for ReadOnly attributes

- Code/Framework/AzFramework/AzFramework/Components/TransformComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/SpawnableUtils.cpp
- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
- Gems/Multiplayer/Code/Source/NetworkEntity/EntityReplication/EntityReplicationManager.cpp
This change addresses the following minor to major issues:
Multiplayer warning whenever an entity is removed (properly with MarkForRemoval): https://github.com/o3de/o3de/issues/12847
- This changes the related WARN to an INFO. A timing issue on the server can cause multiple delete messages to be sent. This behavior is however innocuous. 
Entering game mode in a multiplayer level throws warnings: https://github.com/o3de/o3de/issues/12755
- This fixes an order of ops issue in the MP Editor Game Mode pipeline in which a Transform Component was operated on prior to being added to an entity. It also adds a safety check.
Assert after creating multiplayer entity from context menu of selected prefab: https://github.com/o3de/o3de/issues/12614
- This …
> Fix miscellaneous minor Multiplayer Gem issues

- Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp
Editor uses default render pipeline even when XR system is present, but when running launcher then the default render pipeline is suppose to reflect what's being rendered into XR device, so with the launcher the default render pipeline will use the low end render pipeline to match the XR's.
Checked XR pipeline on Editor and Launcher running through link cable to Quest 2. Only launcher used low end render pipeline.
> Editor uses default render pipeline even when XR system is present

- Gems/AWSCore/Code/Source/Editor/Attribution/AWSCoreAttributionManager.cpp
- Gems/AWSCore/Code/Source/Editor/Attribution/AWSCoreAttributionManager.h
- Gems/AWSCore/Code/Source/Editor/Attribution/AWSCoreAttributionMetric.h
- Gems/AWSCore/Code/Tests/Editor/Attribution/AWSCoreAttributionManagerTest.cpp
- Gems/AWSCore/Code/Tests/Editor/UI/AWSCoreResourceMappingToolActionTest.cpp
- Gems/AWSCore/Code/Tests/TestFramework/AWSCoreFixture.h
Fix AWSCore unit tests which were previously failing due to:
```
E:\dev\o3de\o3de\Code\Framework\AzCore\AzCore/UnitTest/UnitTest.h(175): error: Cannot set @gemroot@ alias for gem "AWSCore". It does not have a gem root folder path within the "/O3DE/Runtime/Manifest/Gems" section of the SettingsRegistry. Make the sure gem is registered in an o3de manifest (o3de_manifest.json, engine.json, project.json, gem.json) and that the manifest files have been merged to the SettingsRegistry. Invoke `AZ::SettingsRegistryMergeUtils::MergeSettingsToRegistry_ManifestGemsPaths` to explicitly merge the gem root folder paths from all manifest to the registry
```
Also fixes issues where the core platform identifier has changed from PC to …
> AWSCore: fix unit tests and handling of platform value

- Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp
Fixed the following error being spammed when using a render pipeline with MSAA state with 1 sample:
````
[Error] (ShaderResourceGroupData) - Image Input 'm_depth[0]': The image has multisample count 1 but the shader expected more than 1.
````
- Manually tested the conditions for the error to occur and check it was fixed. This is by default the application is set to 4x MSAA, create render pipeline whose data has 1x MSAA, and then later set MSAA 1x to the application.
- Checked Editor and Launcher running a default level.
- Checked XR pipeline on Editor and Launcher running through link cable to Quest 2.
- Checked XR pipeline on Launcher running natively on Quest 2.
- Tested adding a Diffuse Probe Grid component, enabled the probes, modified the …
> Fixed function setting MSAA to application

- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.h
- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.ui
I also renamed some widgets in the UI file to have consistent naming.
We now have:
- List View
- Thumbnail View
- Tree view
Fixes #12855
A new button is introduced that lets the user show/hide the middle stack view
https://user-images.githubusercontent.com/104767/200311019-961d2995-0cf9-439b-8ab5-3098919e9a59.mp4
Manual testing and running EditorLib unit tests.
> Asset browser: implement switching between layouts

- AutomatedTesting/Levels/Performance/10KEntityCpuPerfTest/10KEntityCpuPerfTest.prefab
Removes deprecated selection component from a couple of existing prefabs in AutomatedTesting project.
The 10kEntityCpuPerfTest level used to show selectioncomponent deprecation warnings before on load. Those warnings go away with this change.
> Remove selection component from entities of 10k perf level

- Code/Tools/AssetProcessor/native/tests/ApplicationManagerTests.cpp
- Code/Tools/AssetProcessor/native/tests/ApplicationManagerTests.h
- Code/Tools/AssetProcessor/native/tests/AssetProcessorMessagesTests.cpp
- Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.h
- Code/Tools/AssetProcessor/native/utilities/BatchApplicationManager.cpp
- Code/Tools/AssetProcessor/native/utilities/BatchApplicationManager.h
Disables the file state cache for APB.
The file state cache requires the file monitor to update its state but the file monitor is disabled in batch mode. Since intermediate assets are created while running, this meant the cache would be out of date.
This was causing a particular problem for atom systems which attempt to look up dependency files using the GetSourceInfo API before declaring a dependency.  The API was always returning that intermediate asset files did not exist, resulting in the atom builder reporting the dependency as a source dependency instead of a job dependency (this is common behavior for atom builders because they work with relative paths that can refer to multiple locations and don't want to spam job dependency errors by reporting dependencies on files that will …
> Asset Processor - Disable file state cache for asset processor batch

- Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerMetrics.h
- Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerStats.h
- Gems/Multiplayer/Code/Source/MultiplayerStats.cpp
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
- Gems/Multiplayer/Code/multiplayer_files.cmake
- Gems/Multiplayer/Code/multiplayerstats_api_files.cmake
- Adds application frame time to network metrics
- Some light refactoring as well to put metrics into their own header file.
Tested with o3de-multiplayersample
> Adds application frametime to multiplayer metrics

- Gems/PhysX/Code/Source/ForceRegion.cpp
- Gems/PhysX/Code/Source/Scene/PhysXScene.cpp
- Gems/PhysX/Code/Source/Scene/PhysXScene.h
- Gems/PhysX/Code/Source/System/PhysXSystem.cpp
- Gems/PhysX/Code/Tests/Benchmarks/PhysXBenchmarksCommon.cpp
- Gems/PhysX/Code/Tests/PhysXSpecificTest.cpp
- Gems/PhysX/Code/Tests/PhysXTestCommon.cpp
- Gems/PhysX/Code/Tests/RagdollTests.cpp
Added an option to batch rigid body transform syncs for the entire simulation pass
Disabled by default as needs documentation update and more real world testing
Gives up to 40% cut on physics simulation pass cost: 
Unit tests, manual testing various conditions: boxes, ragdolls, with & without interpolation
> Added an option to batch rigid body transform syncs for the entire simulation pass

- Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityHelpers.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorHelpers.cpp
Relates to https://github.com/o3de/o3de/issues/13014.
These changes do not fix the issue completely (this requires more refactoring/restructuring to accomplish) but this does reduce some of the noisy profile markers and should make future captures more informative.
This PR was tested locally and viewport tests have been run against the latest changes.
> Small improvements to `EditorHelpers::DisplayHelpers`

- Code/Tools/TestImpactFramework/Runtime/Python/Code/Source/TestEngine/Python/TestImpactPythonTestEngine.cpp
- scripts/build/Platform/Windows/build_config.json
This PR removes the `test_impact_analysis_profile_python` stage from `profile_pipe` and makes the Python test runner live for `profile_pipe_tiaf`.
This PR will be tested in AR as a PR build, and again in AR when the PR is merged.
> TIAF: Make the Python test runner live for profile_pipe_tiaf and disabled for profile_pipe

- scripts/build/Platform/Windows/build_config.json
This PR removes the `stdout` option from the TIAF Python scripts. This particular option is supported by the runtime but not yet supported by the scripts. A future PR will put this support back in.
Well... it passed AR the first time, how it passed is beyond me.
> Remove stdout from TIAF script

- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/GpuQuery/GpuPassProfiler.h
- Gems/Atom/RPI/Code/Source/RPI.Private/PerformanceCVarManager.cpp
- Gems/Atom/RPI/Code/Source/RPI.Private/PerformanceCVarManager.h
- Gems/Atom/RPI/Code/Source/RPI.Private/RPISystemComponent.cpp
- Gems/Atom/RPI/Code/Source/RPI.Private/RPISystemComponent.h
- Gems/Atom/RPI/Code/Source/RPI.Public/GpuQuery/GpuPassProfiler.cpp
- Gems/Atom/RPI/Code/atom_rpi_public_files.cmake
Added class GpuPassProfiler, that is based on the existing ImGuiGpuProfiler but did not make changes to ImGuiGpuProfiler at this time to simplify the size of the PR.
The core function is in
GpuPassProfiler::MeasureGpuTimeInNanoseconds(). Use judiciously, as MeasureGpuTimeInNanoseconds() can itself affect performance when called. For example, if a scene is running at 300fps, calling
MeasureGpuTimeInNanoseconds(), each frame, can reduce the FPS to ~290fps.
Added CVAR r_metricsMeasureGpuTime, which defaults to false, as it is the only parameter that can be expensive to measure.
Collected data around the new "Frame Gpu Time" metric on the Editor, AutomatedTesting.GameLauncher and LoftSample.GameLauncher.
> Added performance metric:Frame Gpu Time.

- Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
Fixes a crash when right clicking on a source asset "View Job" context menu item.  This was caused by a lambda capture of an out of scope pointer.  Fixed the crash by computing the SourceAssetReference outside of the lambda and capturing by copy.
Tested manually by right clicking on a source asset in the Assets view and clicking on a View job item
> Asset Processor - Fix crash due to referencing out of scope captured pointer

- Code/Tools/AssetProcessor/native/unittests/AssetProcessorManagerUnitTests.cpp
- Replaced the hardcoded sleep in the asset processor manager unit test which is used to set a different timestamp for each file.
- Replace the anonymous namespace in the test code
asset processor manager unit tests passed locally
> Remove the hardcoded sleep for setting the file creation timestamp

- Code/Editor/Plugins/EditorAssetImporter/AssetImporterDocument.cpp
- Code/Editor/Plugins/EditorAssetImporter/SceneSerializationHandler.cpp
- Code/Editor/Plugins/EditorAssetImporter/SceneSerializationHandler.h
- Code/Tools/SceneAPI/SceneCore/Events/AssetImportRequest.cpp
- Code/Tools/SceneAPI/SceneCore/Events/AssetImportRequest.h
- Code/Tools/SceneAPI/SceneCore/Events/SceneSerializationBus.h
- Code/Tools/SceneAPI/SceneCore/Tests/Events/AssetImporterRequestTests.cpp
- Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/MetaDataRule.inl
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/Commands.cpp
- Gems/SceneProcessing/Code/Source/SceneBuilder/SceneBuilderWorker.cpp
- Gems/SceneProcessing/Code/Source/SceneBuilder/SceneSerializationHandler.cpp
- Gems/SceneProcessing/Code/Source/SceneBuilder/SceneSerializationHandler.h
- Gems/SceneProcessing/Code/Tests/SceneBuilder/SceneBuilderPhasesTests.cpp
* this fixes the miss named product asset for the procedural prefab when the watch folder was blank
* the watch folder was attempted to be found with non-deterministic means from the asset database
* the fix pushes the watch folder down the Load Scene pipeline
Reprocessed all the source assets in Automated Testing.
> {ghi12844} fixing the product asset reference for procedural prefab

- scripts/build/Jenkins/Jenkinsfile
`defaultValue` is not a valid option for the choice parameter and will cause an error in the latest version of Jenkins.
This will not change the current behavior of the pipeline. The defaultValue option was ignored before, but the latest version of Jenkins now generates an error with invalid options. The pipeline will still default to the `development` snapshot for PR builds since it is the first entry on the list. 
Tested on my branch using a branch build on the sandbox with the latest version of Jenkins installed.
> Remove defaultValue from the choice parameter

- scripts/o3de/o3de/manifest.py
- scripts/o3de/tests/test_manifest.py
1. Fix an issue where template/gem discovery fails when no projects are registered which is the case when using the Installer.
2. Fixed a minor naming issue where gem/projects were misnamed.
3. Add a unit test for template discovery
Closes #13020 
This should fix our installer tests which failed to create a Project because the DefaultProject template could not be found.
Applied the fix in the installer SDK and verified the `create-project` now succeeds
- Unit test added, verified test failed before the change and succeeded after
> Fix template/gem missing without projects add test

- Code/Tools/TestImpactFramework/Frontend/Console/Common/Code/Source/TestImpactCommandLineOptions.cpp
- Code/Tools/TestImpactFramework/Frontend/Console/Common/Code/Source/TestImpactConsoleTestSequenceEventHandler.cpp
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Headers/TestImpactFramework/TestImpactClientTestRun.h
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/TestImpactRuntimeUtils.h
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Source/TestImpactClientSequenceReportSerializer.cpp
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Source/TestImpactClientTestRun.cpp
- Code/Tools/TestImpactFramework/Runtime/Python/Code/Source/TestEngine/Python/TestImpactPythonTestEngine.cpp
- Code/Tools/TestImpactFramework/Runtime/Python/Code/Source/TestEngine/Python/TestImpactPythonTestEngine.h
- scripts/build/Platform/Windows/build_config.json
- scripts/build/TestImpactAnalysis/test_impact/runtime_test_impact_args.py
- scripts/build/TestImpactAnalysis/tiaf_driver.py
This PR adds the functionality required to pipe std out/err from the test target's console output to the runtime's console output.
Related PRs: https://github.com/o3de/o3de/pull/13083, https://github.com/o3de/o3de/pull/13066
Manually and in AR.
> TIAF: Add test target console output routing.

- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/BuilderSettingManager.cpp
- Gems/GradientSignal/Code/Source/Editor/EditorGradientImageCreatorUtils.cpp
- Gems/GradientSignal/Code/Tests/EditorGradientSignalBakerTests.cpp
When painting or baking an image gradient, it was possible for the Asset Processor to start processing the asset before the image was fully written, which would result in an incorrect processed asset. Furthermore, the AP didn't know to reprocess the asset without a manual trigger.
This change uses special temp file naming to make the AP ignore the image while it's being written, then renames it _after_ it's done so that the AP processes the fully-written image.
Also fixed a tiny null dereference problem in the image builder that could happen occasionally if the source image couldn't be read in for some reason.
Tried painting on images that were 64x64 in size and saving them. Oddly enough, tiny images like these were triggering the problem 100% of the time for me. They now trigger it 0% of …
> [Terrain] Prevent AP from processing image until after it's done saving

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/ImageView.cpp
Signed-off-by: JLeclercq <99494374+CyaNinix@users.noreply.github.com>
When this assert triggers (which is does incorrectly with cubemaps and default image view because of this line:
```cpp
const uint16_t arrayLayers = AZStd::min(static_cast<uint16_t>(imgViewDesc.m_arraySliceMax - imgViewDesc.m_arraySliceMin), static_cast<uint16_t>(imgDesc.m_arraySize - 1)) + 1;
```), a crash follows because the format string is incorrect (single % have to be escaped as %%)
> RHI/Vulkan: Fix error message in ImageView.cpp

- Code/Framework/AzFramework/AzFramework/Asset/AssetCatalog.cpp
- Code/LauncherUnified/Launcher.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
The following fix https://github.com/o3de/o3de/pull/12509 caused Android to start crashing when running with VFS in AtomSampleViewer project.
This happens because as soon as the connection with Asset Processor is stablished it's sending a `BulkAssetNotificationMessage` with `AssetChanged` events for all the assets, but with VFS that's happening before the catalog is initialized (with VFS the initialization happens after connecting to AP and reads the catalog from the remote system). Skipping `AssetChanged` event for this scenario when the catalog is supposed to be initialized fixes the issue.
Also added `CriticalAssetsCompiled` printfs as it's useful to know when they happen in the log. The editor already has one, added the one for the launcher …
> Fixed Android running on VFS. 

- Gems/PhysX/Code/Source/EditorColliderComponent.cpp
- Gems/PhysX/Code/Source/EditorColliderComponent.h
- Gems/PhysX/Code/Source/EditorRigidBodyComponent.cpp
- Gems/PhysX/Code/Source/EditorRigidBodyComponent.h
Connects PhysX Collider and PhysX Rigid Body components to visibility bounds bus. Fixes #2466
Tested in editor, with variety of different collider geometries, position and rotation offsets, transform rotation, translation and scale, with and without non-uniform scale, single and multiple colliders, with and without rigid body component.
> connect collider and rigid body components to visibility bounds

- Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
Wrap IsCompileLoggingEnabled() with AZ_ENABLE_TRACING to match AZ_TracePrintf_IfTrue to fix a linux unused compile error
Built with AZ_ENABLE_TRACING not defined
> Fix for linux unused compile error on Linux

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetsWindowPlugin.cpp
Task-Id: #10960
Fixed header names in motion sets window as requested by @hultonha :
Manually
> Improve naming in Motion Sets window

- Code/Framework/AzNetworking/AzNetworking/Serialization/ISerializer.h
- Code/Framework/AzNetworking/AzNetworking/Serialization/ISerializer.inl
Allows AzNetworking to serialize AZ::s64 and AZ::u64.
AzNetworking ISerialize current supports int64_t and uint64_t, which (depending on the system) is sometimes long and sometimes long long. AZ types such as AZ::u64 are set up to always be defined as long long. This change makes it so that if int64_t is long (not long long), then we'll define a new method to support long long.
Fixes https://github.com/o3de/o3de/issues/13019
> AZ Networking ISerialize Support for AZ::s64 and AZ::u64

- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.ui
Some of them didn't use proper terminology. Placeholder texts also use proper naming
Fixes minor naming issues in .ui files
Compiled and ran the editor. Worked as expected
> Standardize widget names in Asset Browser window

- Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
fixes #13124
The file monitor is now destroyed up front during shutdown so that it can no longer generate extra events during shutdown.
Tested while the crash was active.  It no longer crashes.
> Fixes a crash on AP shutdown

- Code/Tools/ProjectManager/Source/GemCatalog/GemItemDelegate.cpp
- Code/Tools/ProjectManager/Source/GemCatalog/GemItemDelegate.h
This PR provides text rendering for gems to indicate their supported platforms. Please see the testing section for examples.
_Note on implementation:_ The original plan was to implement the text rendering using a QLabel and adjusting layout (i.e. implementing from scratch). However, rendering the text via QPainter was chosen, because the `GemItemDelegate` class uses QPainter to render everything. To go with the original plan would have meant overhauling the class, which is too drastic for this PR.
The rendering logic was visually tested for various scenarios. Note that at the time of writing this PR,  there is currently no logic for fetching the supported platforms from `GemModel`. That will be addressed in a future …
> Added supported platform text rendering for gem catalog cards.

- Gems/Atom/Feature/Common/Assets/Shaders/Materials/BasePBR/BasePBR_VertexData.azsli
- Gems/Atom/Feature/Common/Assets/Shaders/Materials/Eye/Eye_PixelGeometryEval.azsli
- Gems/Atom/Feature/Common/Assets/Shaders/Materials/Eye/Eye_VertexData.azsli
- Gems/Atom/Feature/Common/Assets/Shaders/Materials/Eye/Eye_VertexEval.azsli
The calculated bitangent seems to be inconsistent from the vertex stream. Bring the bitangent back before further investigation to determine the correctness of the bitangent.
The test should pass with little difference.
And for reference:
Before and after this change:
https://github.com/o3de/o3de/pull/12173
Calculated TBN in vertex shader:
Calculated TBN in pixel shader:
> Temporarily bring bitangent back in vertex shader to fix the screenshot test

- Code/Tools/AssetProcessor/native/AssetManager/SourceAssetReference.cpp
- Code/Tools/AssetProcessor/native/AssetManager/SourceAssetReference.h
- Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
Fixed issue where AP crashed when running after having processed with a scanfolder which no longer exists.  A few places in the code were assuming a 'find scanfolder' call would always have a return value.
Fixes https://github.com/o3de/o3de/issues/13114
Followed repro steps in https://github.com/o3de/o3de/issues/13114
> Asset Processor - Fix missing scanfolder crash

- Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.h
- Gems/ScriptCanvas/Code/Editor/View/Windows/ScriptEventMenu.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/ScriptEventMenu.h
- Gems/ScriptCanvas/Code/Editor/View/Windows/mainwindow.ui
Saving ScriptEvents in the SC editor is pretty much hacked in, it does not follow standard saving/loading operations and displays confusing dialogs to try and disambiguate between ScriptCanvas and ScriptEvent assets.
This change removes the conversion between ScriptCanvas and ScriptEvent assets, and removes unnecessary dialog while saving ScriptEvent assets.
Manually tested in Editor
> Improve ScriptEvent file open and save in Editor

- Gems/PhysX/Code/Source/EditorRigidBodyComponent.cpp
Makes the editor world body created by the editor rigid body component actually get added to the editor world, but made inactive so it doesn't move when the editor world updates.
Tested in the editor with physx_debug on.
> fix editor rigid body component editor world body creation

- Gems/PhysX/Code/Include/PhysX/MathConversion.h
- Gems/PhysX/Code/Tests/EditorTestUtilities.cpp
- Gems/PhysX/Code/Tests/EditorTestUtilities.h
- Gems/PhysX/Code/Tests/ShapeColliderComponentTests.cpp
Fixes some newly added tests which were reading from the PhysX scene without a lock. Also fixes the conversion code from PhysX to O3DE math types for AABBs in the case when PhysX returns an invalid AABB (thanks to @SergeyAMZN for finding).
Ran editor unit tests in debug.
> fixes for editor tests in debug

- Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
Fixes bug #13111 
This bug was caused by not checking the asset for being source not product before adding to the context menu.
Checked many items in the Asset Browser to see that the menu works correctly.
> Fixed by checking if source or product before showing the menu

- Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp
- Code/Framework/AzToolsFramework/Tests/ToolsComponents/EditorLayerComponentTests.cpp
This PR checks if there is a current undo batch in progress before adding an entity to the dirty entity list. This prevents entities being dirtied unintentionally such as during level load. An example of this is the TransformComponent calling SetDirty() from its Activate().
This manifested as a performance issue for large levels in the prefab system because the dirty entity list became bloated after level load causing the next user undo operation, such as entity selection, to take a long time since it was creating undo commands for all those dirty entities.
Tested common undo/redo operations in editor. Opened/closed/switched levels.
> Prevent entities being marked dirty outside of an undo batch

- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
- Code/Framework/AzQtComponents/AzQtComponents/DPEDebugViewStandalone/main.cpp
Before this PR, it was possible to encounter an assertion caused by the incorrect assumption that `ReadOnly` attributes were always `bool` values. In fact, `ReadOnly` attributes can be invocable values that reference member functions/data that will yield a `bool` value.
This PR adds support for those invocable `ReadOnly` values to the `LegacyReflectionBridge`.
**Testing**
- Verified opening the EntityInspector no longer throws an assertion for attempting to access a non-bool Value
- Added a test case to the standalone debug DPE app and verified that the property editor is enabled/disabled at runtime as appropriate
Signed-off-by: amzn-tmryan <104796591+amzn-tmryan@users.noreply.github.com>
> DPE: Support invocable ReadOnly attributes

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditorSettings.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditorSettings.h
Before this PR, only persistent expansion state storage existed in the DPE. This meant that editors needed to create and set a GUID state key if they wanted the DPE to remember expansion states and there was no way to activate it only for the time a document was open (transient in-memory storage only).
This PR makes the DPE's default expansion state saving behavior the non-persistent in-memory only (wiped after the document is closed) behavior. Setting a save state key will continue to work as before where settings are saved to disk when a document is closed.
**Testing**
- Tested in the AssetEditor by disabling the current save to disk behavior
- Tested in the standalone debug DPE app by collapsing and expanding rows in various configs as well as switching between the …
> DPE: Add default transient in-memory expansion state saving

- Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/GeneralCommonPropertyGroup.json
- Gems/Atom/Feature/Common/Assets/Passes/MainRenderPipeline.azasset
- Gems/Atom/TestData/TestData/Materials/StandardPbrTestCases/013_SpecularAA_Off.material
Changed MSAA to be 2x by default (better performance than 4x) with custom sample points (fix some artifacts, including this bug: https://github.com/o3de/o3de/issues/9882) and turned on specular AA by default for better image quality and less aliasing across the board
> Changed MSAA and SpecularAA

- AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Periodic.py
- AutomatedTesting/Levels/Prefab/SC_Spawnables_MultipleSpawnsFromSingleTicket/SC_Spawnables_MultipleSpawnsFromSingleTicket.prefab
- Adds necessary setreg flag for running test_AddEntity_UnderUnfocusedInstanceAsOverride - Fixes https://github.com/o3de/o3de/issues/13150
- Moves all tests to use EditorBatchedTest to avoid parallel Editor issues
- Combined separate test classes, and now utilize both -BatchMode and -autotest_mode for all tests
- Updates a test level to remove deprecated SelectionComponent warning
- Ran updated periodic suite several times with 0 failures
> Organizational updates and test fix for Prefab TestSuite_Periodic

- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/PaintBrushManipulator.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/PaintBrush/PaintBrush.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/PaintBrush/PaintBrush.h
- Code/Framework/AzToolsFramework/AzToolsFramework/PaintBrush/PaintBrushNotificationBus.h
- Code/Framework/AzToolsFramework/Tests/PaintBrush/MockPaintBrushNotificationHandler.h
- Code/Framework/AzToolsFramework/Tests/PaintBrush/PaintBrushBaseTests.cpp
- Code/Framework/AzToolsFramework/Tests/PaintBrush/PaintBrushPaintLocationTests.cpp
- Code/Framework/AzToolsFramework/Tests/PaintBrush/PaintBrushSmoothLocationTests.cpp
- Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
This adds a set of unit tests for PaintBrush that test most of the base functionality:
- Paint Mode begin/end
- Brush Stroke begin/end
- PaintToLocation, SmoothToLocation, ResetPaintBrushTracking all trivially work and handle locations correctly
The one functional change introduced here is that I realized the PaintBrush code was inconsistently converting things into 2D space for painting calculations. I've made this more explicit and consistent and (not really) conditional based on the constant "PaintIn2D". It's structured this way because we might eventually want to open this up as a runtime parameter so that we can have full 3D painting as well, but since we don't have any use cases for that yet I'd like to avoid adding extra parameters and unit tests before we have the need.
Ran the …
> [Terrain] First batch of unit tests for PaintBrush

- Code/Framework/AzCore/AzCore/DOM/DomPrefixTree.h
- Code/Framework/AzCore/AzCore/DOM/DomPrefixTree.inl
- Code/Framework/AzCore/Tests/DOM/DomPrefixTreeTests.cpp
This PR adds 2 new public functions to attach and detach sub trees within an AZ::Dom::PrefixTree. It also adds a few private helper functions and a constructor to achieve this.
These functions are required in order to support several override operations for Prefabs. Once these changes are in, they will be integrated immediately with the 'prefab revert overrides' feature. The draft PR for that can be found here along with a working video of the feature: https://github.com/aws-lumberyard-dev/o3de/pull/468
Tested manually to accomplish a prefab feature. Once this direction is agreed upon, I'll also add unit tests to this same PR.
> Add AttachSubTree and DetachSubTree functions for AZ::Dom::DomPrefixTree

- Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/DCC/Blender/Scripts/addons/SceneExporter/utils.py
Signed-off-by: shawstar <shawstar@amazon.com>
A fix for when a user could have a dead material that is a None in the selected materials and will have a key error.
Skips the '' material in the selected list.
Manually tested.
> Dead Material Fix @shawstar

- AutomatedTesting/Gem/PythonTests/Atom/CMakeLists.txt
Signed-off-by: NULL <jromnoa@amazon.com>
Temporarily disables the level loads test for Atom null render while the underlying crash is investigated.
Relates to latest build failure on https://github.com/o3de/o3de/issues/11238 which is build https://jenkins.build.o3de.org/job/O3DE/job/development/3468/ 
Ran the tests locally after removing the problematic tests from CMakeLists.txt registration.
> Disable Atom level loads test to investigate crash.

- Code/Framework/AzToolsFramework/AzToolsFramework/PaintBrush/PaintBrush.cpp
- Code/Framework/AzToolsFramework/Tests/PaintBrush/MockPaintBrushNotificationHandler.h
- Code/Framework/AzToolsFramework/Tests/PaintBrush/PaintBrushPaintLocationTests.cpp
- Code/Framework/AzToolsFramework/Tests/PaintBrush/PaintBrushPaintSettingsTests.cpp
- Code/Framework/AzToolsFramework/Tests/PaintBrush/PaintBrushSmoothLocationTests.cpp
- Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
Adds another round of unit tests for the PaintBrush code. This verifies that the following Paint Brush Settings correctly affect painting and smoothing:
* Brush opacity
* Brush size
* Hardness %
* Flow %
* Distance %
* Blend modes
* Smoothing radius
* Smoothing modes
Ran the unit tests and verified they passed.
> [Terrain] Second batch of Paint Brush unit tests - validates Paint Brush Settings

- Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
Avoid calling FindFirstMatchingFile on an absolute path as its unnecessary and doesn't really make sense.
Also switch out a call to ConvertToRelativePath to GetScanFolderForFile since the relative path was not used and made the code confusing.
Ran AP and unit tests
> Asset Processor - Avoid FindFirstMatchingFile on absolute path

- Gems/PhysX/Code/Source/Scene/PhysXScene.cpp
- Gems/PhysX/Code/Source/Scene/PhysXScene.h
- Gems/PhysX/Code/Source/System/PhysXSystem.cpp
Added parallel transform sync for rigid bodies when batched sync is enabled
Enables parallelized transform sync for rigid bodies using `AZ::TaskGraph`. 
Manual testing with 4320 rigid bodies, unit tests
> Added parallel transform sync for rigid bodies when batched sync is enabled

- scripts/build/build_node/Platform/Mac/install-jdk.sh
- scripts/build/build_node/Platform/Windows/install_utiltools.ps1
Updates the build node dependencies for JDK 11 for Windows and Mac (Linux is already on JDK 11). Also configures Windows nodes to use JDK 11 only for the Jenkins agent, while leaving JDK 8 for Android builds 
> Update build nodes to JDK 11

- Code/Tools/ProjectManager/Source/CreateAGemScreen.cpp
Updated `CreateGem::m_gemTemplateLocation` filepath widget so that at the start of the CreateGem workflow it is disable by default. Only if the appropriate radio button is selected will it be enabled for editing.
This PR is to address the following github issue: https://github.com/o3de/o3de/issues/13250
All testing was performed manually. Results are shown in the gif above.
> Fixed UX for Gem Template Location Filepath widget

- Code/Framework/AzCore/AzCore/UnitTest/TestTypes.h
- Code/Framework/AzCore/Tests/Memory.cpp
This disables ThreadPoolAllocator leak detection because of incorrect tracking data.
Fixes #13262 
> Disable ThreadPoolAllocator leak detection because of incorrect tracking data

- AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Periodic.py
- AutomatedTesting/Gem/PythonTests/Prefab/tests/PrefabTestUtils.py
- AutomatedTesting/Gem/PythonTests/Prefab/tests/overrides/DeleteEntity_UnderImmediateInstance.py
- AutomatedTesting/Gem/PythonTests/Prefab/tests/overrides/DeleteEntity_UnderNestedInstance.py
- AutomatedTesting/Gem/PythonTests/Prefab/tests/overrides/DeletePrefab_UnderImmediateInstance.py
- AutomatedTesting/Gem/PythonTests/Prefab/tests/overrides/DeletePrefab_UnderNestedInstance.py
This PR adds new automated tests under Prefab/TestSuite_Periodic for delete-entity and delete-prefab as overrides.
- DeleteEntity_UnderImmediateInstance
- DeleteEntity_UnderNestedInstance
- DeletePrefab_UnderImmediateInstance
- DeletePrefab_UnderNestedInstance
In addition, it adds two helper functions to validate count and child count for named editor entity:
1. validate_count_for_named_editor_entity
2. validate_child_count_for_named_editor_entity
It is a follow-up PR for the new feature introduced in https://github.com/o3de/o3de/pull/13171.
> New automated tests for delete entity or prefab as overrides

- Gems/Atom/Asset/Shader/Code/Source/Editor/AzslShaderBuilderSystemComponent.cpp
- Gems/Atom/Asset/Shader/Code/Source/Editor/PrecompiledShaderBuilder.cpp
Checked for a supported platform API before adding the azshadervariant to the product dependencies.
> Fix for precompiled shader asset serialization errors on Linux

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/AssetSelection/AssetSelectionComboBox.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/AssetSelection/AssetSelectionGrid.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportSettingsInspector.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportToolBar.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetSelection/AssetSelectionComboBox.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetSelection/AssetSelectionGrid.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystem.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/CreateDocumentDialog.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportSettingsInspector.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportToolBar.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Functions/acos.materialgraphnode
- Gems/Atom/Tools/MaterialCanvas/Registry/gem_autoload.materialcanvas.setreg
- Gems/Atom/Tools/MaterialEditor/Registry/gem_autoload.materialeditor.setreg
- Gems/Atom/Tools/ShaderManagementConsole/Registry/gem_autoload.shadermanagementconsole.setreg
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
Initializing lighting and model preset widget contents off the main thread. 
Removing auto population from asset selection control constructors. 
Disabling several modules unused in material editor and material canvas.
Confirmed that lighting and model preset dropdowns and dialogues populate correctly after asynchronous file enumeration is complete.
> Material Canvas: Improving startup time

- Gems/EMotionFX/Code/Source/Integration/System/SystemComponent.cpp
Fixes bug #13196
Tried opening .animgraph and .motionset and ensuring they open correctly.
> Fixes bug #13196 Opening .animgraph or .motionset assets via Asset Browser does not work

- Templates/CppToolGem/Template/Code/CMakeLists.txt
- Templates/DefaultGem/Template/Code/CMakeLists.txt
- Templates/PrebuiltGem/Template/Code/CMakeLists.txt
- Templates/PythonToolGem/Template/Code/CMakeLists.txt
The Project templates Gem target already properly check the PAL_TRAIT\_*_SUPPORTED option, so it was already possible to selectively disable building those modules on a per platform basis.
Validate that create a gem using the gem templates succeed and produce a compilable gem
```powershell
PS C:\code\o3de> .\scripts\o3de.bat create-gem -gp ..\TestGem2
PS C:\code\o3de> .\scripts\o3de.bat enable-gem -gp ..\TestGem2 -pp .\AutomatedTesting
PS C:\code\o3de> cmake --preset windows-automated-testing
PS C:\code\o3de> cmake …
```
> Fix Gem templates to respect the `PAL_TRAIT_<gem_name>_SUPPORTED` option

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoAddEntity.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoDelete.cpp
Fix: https://github.com/o3de/o3de/issues/13155
This PR addresses the issue of an unexpected patch for updating the parent container entity's transform in the source template. During add-entity operation, if the container entity is being focused and we fetch from focused template, the transform in the retrieved entity DOM will be empty. An unexpected patch will be generated to update the transform.
- Patch 1: Add new entity DOM
- Patch 2: Update parent's child entity order
- **Patch 3: Update parent entity's transform    <-- unexpected**
In this case, we need to change it to "fetch from root" such that the transform contains data and later patch generation would not generate an extra patch to update parent transform.
The recently added unit …
> Prefab Bug Fix - Remove unexpected transform update of container entity for add-entity

- scripts/build/build_node/Platform/Windows/install_vsbuildtools.ps1
Bumps Visual Studio 2022 to 17.4.1, including latest compiler
> Update VS2022 build node config to 17.4.1

- Code/Framework/AzCore/AzCore/Debug/Profiler.h
- Code/Framework/AzCore/AzCore/Debug/Profiler.inl
- Code/Framework/AzCore/AzCore/IO/Streamer/Statistics.cpp
- Code/Framework/AzCore/AzCore/IO/Streamer/Streamer.cpp
- Code/Framework/AzCore/Platform/Android/AzCore/Debug/Profiler_Android.inl
- Code/Framework/AzCore/Platform/Common/Unimplemented/AzCore/Debug/Profiler_Unimplemented.inl
- Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/Debug/Profiler_WinAPI.inl
- Gems/PhysX/Code/Source/Scene/PhysXScene.cpp
Adds PIX implementation for AZ_PROFILE_DATAPOINTs. 
Now we can plot data point metrics along with profiling information of the functions.
> Added PIX implementation for AZ_PROFILE_DATAPOINTs

- Code/Editor/Util/GuidUtil.cpp
- Code/Legacy/CrySystem/IDebugCallStack.cpp
- Code/Legacy/CrySystem/XConsole.cpp
- Gems/Atom/RPI/Code/Tests/Material/MaterialPropertyValueSourceDataTests.cpp
- Gems/Atom/RPI/Code/Tests/Material/MaterialTypeSourceDataTests.cpp
- Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugHierarchyReporter.cpp
- Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugPerEntityReporter.cpp
This fixes the macOS build, where `sprintf` is deprecated
> Prefer `snprintf` to `sprintf`, the former is deprecated on macOS

- Code/Editor/2DViewport.cpp
- Code/Editor/2DViewport.h
- Code/Editor/CryEdit.cpp
- Code/Editor/CryEditDoc.h
- Code/Editor/EditorViewportWidget.cpp
- Code/Editor/EditorViewportWidget.h
- Code/Editor/Export/ExportManager.cpp
- Code/Editor/GameEngine.cpp
- Code/Editor/GameEngine.h
- Code/Editor/GameExporter.cpp
- Code/Editor/GameExporter.h
- Code/Editor/IEditor.h
- Code/Editor/LyViewPaneNames.h
- Code/Editor/Resource.h
- Code/Editor/Settings.cpp
- Code/Editor/Settings.h
Removed a bunch of low-hanging fruit in the Editor that contained dead references to the legacy terrain system. 
There are more references that could still be removed, but they require more effort because they involve API changes or additional research to verify that the code is truly unused.
Removed the code, verified that everything still compiled and ran and seemed to function correctly. Since these changes were just removals that didn't require any code fixups, it's very unlikely that they have any hidden side effects.
> [Terrain] Redcode dead terrain code.

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetWindow.cpp
Before the change, the open in explorer action on the motion set window point to the cache folder. When user select the browser action, they almost always want to look at the source file, not the .motion file in the cache.
https://user-images.githubusercontent.com/69218254/202828442-937a46a7-d83d-4404-bd9d-feeef1fb83b1.mp4
> The browse action on the motion set window should point to the source folder

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
This PR changes DeleteEntity call to reset() in prefab delete operation.
Difference: [ComponentApplication::DeleteEntity](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Component/ComponentApplication.cpp#L1139) also signals "entity removed event".
Since not noticing any of this event handler being registered (i.e. empty), we discussed that we can try to switch to calling reset() to keep consistency with how it's deleting entities in nested instances `detachedInstance.reset()`.
**Note:** We can revert this commit later if we see new issue because of this change.
Before:
```cpp
AZ::ComponentApplicationBus::Broadcast(&AZ::ComponentApplicationRequests::DeleteEntity, entityId);
```
After:
```cpp …
```
> Switch to reset deleted entity in prefab delete-entity operation

- Gems/AtomLyIntegration/ImguiAtom/Code/Source/ImguiAtomSystemComponent.cpp
- Gems/AtomLyIntegration/ImguiAtom/Code/Source/ImguiAtomSystemComponent.h
- Gems/ImGui/Code/Include/ImGuiBus.h
- Gems/ImGui/Code/Source/ImGuiManager.cpp
- Gems/ImGui/Code/Source/ImGuiManager.h
Fixes https://github.com/o3de/o3de/issues/12932
The problem was introduced at https://github.com/o3de/o3de/pull/12609 which moved ImGuiManager rendering to a job thread, as an optimization. I simply reverted that part of the changes, as there isn't time for a thorough investigation and proper fix, and I'm concerned there might be more threading issues yet to be uncovered. If we really want ImGuiManager to render on a separate thread, someone else will have to do a deep dive.
The original change is reported to have saved 5ms, but only when the ImGui CPU profiler tool was open, and on a specific level. I checked the CPU profiler performance in Editor.exe before and after the change. When I tested using the default scene, the main thread took about 2.75 ms before my change and 3.25ms after. …
> Fixed IMGUI Unusable: Mouse Doesn't Work in Game Launcher

- Gems/LyShine/Code/Include/LyShine/Bus/UiCursorBus.h
- Gems/LyShine/Code/Source/LyShine.cpp
- Gems/LyShine/Code/Source/LyShine.h
- Gems/LyShine/Code/Source/LyShineSystemComponent.cpp
Exposes SetUiCursorPosition to scripting (Script Canvas / Lua)
Closes #11894 
Created a simple Script Canvas graph that set the mouse cursor to the center of the screen every frame
> Reflected SetUiCursorPosition to scripting

- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h
- Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
Added a list of material changeIds and checked for material changes before updating the Mesh ray tracing data.
> Check for material changes before updating Mesh ray tracing data

- AutomatedTesting/Gem/PythonTests/Atom/tests/MaterialEditor_Atom_BasicTests.py
Signed-off-by: NULL <jromnoa@amazon.com>
This part of the test needs to be temporarily disabled to not block the pipeline as the functionality is working and it appears to be failing on a pathing error (maybe from a recent update). 
1. Test command: `C:\git\o3de\python\runtime\python-3.10.5-rev1-windows\python\python.exe -m pytest -vv -s --build-directory="C:\git\o3de\build\bin\profile" C:\git\o3de\AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Main_Null_Render_MaterialEditor_01.py -k MaterialEditor_Atom_BasicTests`
2. Results:
```
Starting test MaterialEditor_BasicFunctionalityChecks_AllChecksPass...
Test MaterialEditor_BasicFunctionalityChecks_AllChecksPass finished.
Report:
[SUCCESS] Success: Existing material document opened successfully.
[SUCCESS] Success: Closed existing material …
```
> Temporarily disable the asset path check portions of the basic tests for MaterialEditor.

- cmake/install/Findo3de.cmake.in
If the Installer was built with the `LY_DISABLE_TEST_MODULES` cache variable set to TRUE, then it would not include the test modules in the SDK layout which is OK.
The issue however is that when the Installer SDK layout is used with a project and external gems, it doesn't have the PAL_TRAIT_BUILD_TEST_SUPPORTED trait set to FALSE.
Therefore when a project and external gems with test attempts to configure using the Installer SDK layout, configuration fails.
Built an SDK layout with the LY_DISABLE_TEST_MODULES cache variable set to TRUE and validated that configuring a new project with a external gem that includes test modules succeed.
> Fixed SDK Install layout issue

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_GPU.py
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_MaterialCanvas_01.py
- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_tools_utils.py
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportSettingsRequestBus.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportSettingsSystem.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportSettingsSystem.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/GraphView/GraphView.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
- Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/VectorNodePropertyDisplay.cpp
- Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/VectorNodePropertyDisplay.h
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/AssetEditorToolbar/AssetEditorToolbar.cpp
The first issue was improper widget cleanup in recently added code for the color picker button on the graph canvas vector property display class.
The second issue was caused by trying to access clipboard mime data before the application exits. In this case, I clear the clipboard when the application is destroyed. This prevents the crash from happening but the clipboard data should be managed by Qt.
Set up other widget parents to make sure they were cleaned up correctly while debugging the previously mentioned problems.
Resolves https://github.com/o3de/o3de/issues/12152
Manually and rapidly creating, destroying, cutting, copying, pasting, duplicating several notes, shutting down confirm exceptions or crashes no longer occur.
Being able to shut …
> Material Canvas: Fixing graph canvas crashes on shut down

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
Mainly just limited the size of the scale of the solid joints, and lower the alpha number down.
Before
After
> EMFX: Improve the solid skeleton render

- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/ComponentModeSwitcher.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/ComponentModeSwitcher.h
- Code/Framework/AzToolsFramework/Tests/ComponentModeSwitcherTests.cpp
Signed-off-by: amzn-ahmadkrm <105638312+amzn-ahmadkrm@users.noreply.github.com>
The Switcher has a difficult to notice flicker when switching between components, the text changes to "Transform" before changing to the new Components' name. This PR fixes this by ensuring that the Editor is not in Component Mode with TickBus::QueueFunction.
https://user-images.githubusercontent.com/105638312/202327349-cbf0babc-26e2-4b2f-963d-998b6665911f.mp4
Another bug was that the Switcher did not switch between the Component icons when cycling through Component Mode with Tab. i.e. Switching between Spline Component and Tube Shape Component. 
After:
https://user-images.githubusercontent.com/105638312/202327719-b67e10d4-ce59-4e33-adc4-a28f417353f0.mp4
Manual testing for the transform flicker and unit test …
> Fix name flicker on the Component Mode Switcher and update the Switcher when ActiveComponentMode changes

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/AnimGraphPlugin.cpp
All other graph-based tools call this element just the "Node Palette"
Fixes: #13375
Changes the menu entry name and window title of node palette tool in EMotionFX to be consistent with other canvas-based tools.
Manually
> EMotionFX: Apply consistent naming for node palette

- Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainSurfaceGradientListComponent.cpp
If a terrain had two surface types that were both image gradients, and the second image gradient didn't have an image connected to it, the code would hit a couple of edge cases where the weights from the first image gradient would get applied to both surface types. Specifically, the image gradient never filled in any output values in a GetValues() call if the image wasn't loaded, and the Terrain Surface Detail Materials component never cleared the output value list between calls.
This fixes both sides of the problem by adding clears to both. They're both necessary because gradients are expected to always return values so the Image Gradient was breaking its API contract, and the Terrain Surface Detail Materials could also hit the same edge case on its own if an invalid gradient entity had …
> [Terrain] Surface weights could be invalid in some edge cases

- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BreadCrumbs.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BreadCrumbs.h
BreadCrumbs::fillPath used a crude approximation for how much space will the path string take based on font metrics of a plain text string of the path. This patch fixes a bunch of issues with this:
The actual html that was put into the QLabel was very different. It used different spacing, could add icons, etc.
In some situations it could cause a crash because the html inserted into the label could be longer that the available space. This caused a resize that again, caused the re-calculation of the path. This time there was enough space so a path portion was added again. This led to infinite recursion and stack overflow.
Instead, the path label has the horizontal policy set to "Ignore". We ourselves make sure to use the available space in the best way.
The calculation of the path width was …
> Fix path width calculation in BreadCrumbs

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionEvents/EventDataEditor.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionEvents/EventDataEditor.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionEvents/MotionEventEditor.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionEvents/MotionEventEditor.h
Ensure event data editor refreshes when event data entry is added/removed
Fixes https://github.com/o3de/o3de/issues/12665
This PR ensures the MotionEventEditor refreshes correctly when MotionEvents are added/removed from a MotionEvent in the TimeView.
This is a follow-on from https://github.com/o3de/o3de/pull/12692 to address things at the Editor level.
The reproductions steps outlined in the original issue were followed to verify the fix was working as expected. Tested manually.
https://user-images.githubusercontent.com/82228511/203779444-f0bbc1d1-1e77-45bb-af55-7c1244ad35e0.mp4
Tagging @pollend for visibility
> Ensure event data editor refreshes correctly

- Gems/EMotionFX/Code/Source/Editor/SkeletonModel.cpp
- Gems/EMotionFX/Code/Source/Editor/SkeletonModel.h
On the skeleton outliner the root node used to have a joint icon, that has been changed to the character icon.
Fixes #13273 
Opening the skeleton outliner after adding an actor. The icon on the root node is now is the expected one.
> 13273 skeleton outliner update character node icon

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterCreateEditWidget.cpp
This change fixes a bug where the Inspector layout was shaking when a parameter name was being edited.
Fixes #13234 
The PR was tested by adding a new parameter and editing its name, the layout is not shaking anymore.
> 13234 fix shaking inspector layout

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/NodePaletteWidget.cpp
For some reason the Editor.qss stylesheet is not applied to the NodePaletteWidget when it's inserted into the dock widget in EMotionFX.
This widget is later reparented to the chain originating in the editor main window so in theory it should be applied and the palette for the tree view delegate should be proper.
As a workaround, we apply the style directly.
Fixes: #13235
Fixes the search highlight in Node Palette window in EMotionFX
Manually
> Fix style application in EMotionFX

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/NodeGraph.cpp
When multiple node groups existed, trying to edit the name of any of them would immediately disable editing the name because QLineEdit::hide triggers the QLineEdit::editingFinished signal.
Fixes https://github.com/o3de/o3de/issues/13279
manually
> EMotionFX: fix editing node group name when multiple groups exist

- Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphNodeGroup.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphNodeGroup.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphWidget.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp
Node groups can now be created in all levels, and every level only sees node groups created in that level.
Signed-off-by: Alessandro Ambrosano <1006222+aambrosano@users.noreply.github.com>
Fixes https://github.com/o3de/o3de/issues/13232
This PR prevents node groups to be mixed between different levels on an animation graph.
Every new node group is now bound to a level and can only be used in that level.
Manually navigating a multi-level animation graph, assigning and removing node groups.
Before:
After:
> AnimGraph: Fix node groups bleeding into different levels (#13232).

- Code/Framework/AzCore/AzCore/Name/Name.cpp
Signed-off-by: Ethan Chen <ethanchen1227@gmail.com>
Addressing a remaining issue in https://github.com/o3de/o3de/issues/13137
Add `__repr__` in `AZ::Name` Behavior Context to avoid the warning.
Test on my local PC
> Fix warning message for AZ::Name in python script

- Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp
- Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.h
- Code/Framework/AzFramework/Tests/CameraInputTests.cpp
Fixes an input issue where 'boost' for `TranslateCameraInput` could get stuck on when focus changed
Tested manually in the editor and also created a unit test to replicate the failure and show the fix worked
```
[ RUN      ] CameraInputFixture.TranslateCameraInputBoostDoesNotGetStuckOn
D:/o3de/Code/Framework/AzFramework/Tests/CameraInputTests.cpp(651): error: Value of: m_firstPersonTranslateCamera->Boosting()
Expected: is false
Actual: true (of type bool)
```
```
[ RUN      ] CameraInputFixture.TranslateCameraInputBoostDoesNotGetStuckOn
[       OK ] CameraInputFixture.TranslateCameraInputBoostDoesNotGetStuckOn (1 ms)
[----------] 1 test from CameraInputFixture (1 ms total)
```
> Fix for camera boost getting stuck on

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
By the time the semicolon is reached at the end of line where compareName is defined the QByteArray returned by toUtf8() is destroyed and the string_view points to a freed memory.
Fixes a dangling string reference
Manually, the editor seems to behave the same.
> Fix dangling string AssetBrowserTreeView

- Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
- Code/Tools/AssetProcessor/native/ui/SourceAssetDetailsPanel.cpp
Fixed QueryAbsolutePathDependenciesRecursive not handling absolute paths.
Fixed SourceAssetDetailsPanel having empty entries for dependencies with UUIDs that can't be resolved.
Updated and ran unit tests
> Asset Processor - Fix absolute path source dependency handling

- Code/Tools/AssetProcessor/native/unittests/FileWatcherUnitTests.cpp
Update the comment in FileWatcherUnitTest for the reason to disable the tests
No logic changes in the test
> Update the comment in FileWatcherUnitTest for the reason to disable the tests

- Code/Framework/AzToolsFramework/AzToolsFramework/Metadata/MetadataManager.cpp
Adds missing AZ::Component base class to the reflection call for MetadataManager
Ran editor and confirmed warning message no longer shows up
> Add missing reflection of AZ::Component base class for MetadataManager

- .github/ISSUE_TEMPLATE/config.yml
Remove duplicated security policy lines in new issue reporting. Github is now autogenerating one based on our `SECURITY.md`
Remove our explicit line to reduce duplication of effort
Before change:
> There are two 'security' policy links. User given two actions of "**report a security vulnerability**" or "**Security Vulnerability**"
After change:
Tested in private repro, confirmed that security policy link is in place.
> [Issue Template] Remove duplicated security policy lines

- .github/ISSUE_TEMPLATE/bug_template.md
Add the commit ID information to the GHI bug template which helps people to check whether the bug has been fixed in the latest for proper triage.
Cannot test the change locally. Will try to create a new GHI after the merge to verify it.
> Update the bug template to include commit ID

- Code/Framework/AzCore/Tests/Debug/PerformanceCollectorTests.cpp
Removes a Uint & Double comparison that was causing flaky test results.
Fixes https://github.com/o3de/o3de/issues/13419
Validated all AzCore.Tests still passed locally.
> Removed flaky comparison from PerformanceCollectorTest

- Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasGraphView.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasGraphView.h
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Types/ConstructPresets.cpp
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Types/ConstructPresets.h
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/ContextMenuActions/ConstructMenuActions/ConstructPresetMenuActions.cpp
- Gems/GraphModel/Code/Include/GraphModel/Integration/GraphCanvasMetadata.h
- Gems/GraphModel/Code/Source/Integration/GraphCanvasMetadata.cpp
- Gems/GraphModel/Code/Source/Integration/GraphController.cpp
- Gems/ScriptCanvas/Code/Editor/Settings.cpp
- Implemented construct presets for material canvas graph view. The toolbar actions for creating groups of nodes are only functional if presets are set up.
- Graph model controller was not sending all of the requests and notifications needed to fully initialize a new graph, update bookmarks, and allow groups to resolve and re add contained nodes.
- Graph model controller was serializing “other” redundant metadata and then attempts to capture information about comments and groups. The information is already captured as part of the scene metadata when it is serialized.
- Graph model controller does not currently clear metadata from nodes that have been deleted. This may be a requirement for landscape canvas and will need to be addressed so excess data is not retained or serialized between …
> Material Canvas: Fixing creation and serialization of node groups, bookmarks, comments

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphWidget.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphWidget.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp
Signed-off-by: Alessandro Ambrosano <1006222+aambrosano@users.noreply.github.com>
Fixes #13373
Nodes in an animation graph couldn't be assigned to any other node group once they were assigned the first time.
This PR makes it possible to let a node switch the groups to which it belongs.
Manually switching graph nodes from a group to another through the menu.
https://user-images.githubusercontent.com/1006222/204567271-669dd4ed-07ef-422f-8073-6b0d77c193e7.mp4
Fixes #13373
> AnimGraph: Make it possible for a node in a group to be assigned to another group (#13373)

- Code/Editor/EditorModularViewportCameraComposerBus.h
- Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp
- Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp
- Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportMessages.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ModularViewportCameraController.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ModularViewportCameraControllerRequestBus.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ModularViewportCameraController.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp
A bug was discovered where if moving the camera using the WASD (or ED) keys, if the user clicked outside of the viewport while this was happening (keys were held) the input would get 'stuck' on as the key up event would be missed as the viewport was no longer in focus.
To avoid this we now detect when the viewport for the camera receiving the input loses focus and reset all camera inputs to ensure nothing is still running.
Both manually in the Editor and also a new test was created (`CameraSystemStopsMovingWhenViewportLosesFocus`)
```
[ RUN      ] ModularViewportCameraControllerFixture.CameraSystemStopsMovingWhenViewportLosesFocus
D:/o3de/Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp(531): …
```
> Ensure camera inputs are cleared when the viewport loses focus

- Code/Editor/CryEditDoc.cpp
- Code/Editor/EditorPreferencesDialog.cpp
- Code/Editor/MainWindow.cpp
- Code/Editor/MainWindow.h
This PR fixes #5485. Previously the auto save timer would be killed after the first time it triggered, and never be restarted unless the interval was changed in the settings. Now the timer runs continuously, resetting if the interval is modified, and being restarted on a new scene load.
Tested manually.
> Ensure autosave timers are stopped and started correctly.

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicInterface.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
Deprecation Notice GHI: https://github.com/o3de/o3de/issues/12956
This PR renames an existing prefab public-facing function CreatePrefabInDisk to CreatePrefabAndSaveToDisk. See the issue for more information.
No logic changed.
> Prefab API | Rename CreatePrefabInDisk to CreatePrefabAndSaveToDisk

- Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.cpp
> Mac build fix for non-unity, missing header include

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.h
Before this PR, changes made internally to a prefab weren't being propagated to other instances of the same prefab in a scene when the DPE EntityInspector was being used.
This PR adds handler code to the DPEComponentAdapter similar to what is done in the RPE's EntityPropertyEditor for creation and tracking of undo nodes. This allows the necessary events to reach the prefab system interface, triggering the propagation of those changes to other instances of the same prefab.
**Testing**
- Verified behavior with the RPE enabled seems consistent with DPE-enabled behavior in the EntityInspector regarding prefab change propagation and undoing those changes
Signed-off-by: amzn-tmryan <104796591+amzn-tmryan@users.noreply.github.com>
> DPE: Handle entity change undo events in ComponentAdapter

- scripts/build/Jenkins/Jenkinsfile
- Add new behavior to the Jenkinsfile to allow for pulling the bootstrap scripts from o3de to the o3de-extras or project repos
- Some cleanup on LFS behavior
- Validates the workspace availability before the build
- Consolidating the script paths to a single variable
Tested in a sandbox Jenkins environment.
> Jenkinsfile fixes for external repos

- Code/Editor/AssetImporter/AssetImporterManager/AssetImporterManager.cpp
- Code/Editor/AssetImporter/AssetImporterManager/AssetImporterManager.h
- Code/Editor/AssetImporter/UI/FilesAlreadyExistDialog.ui
- Code/Editor/AssetImporter/UI/SelectDestinationDialog.cpp
- Code/Editor/AssetImporter/UI/SelectDestinationDialog.ui
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.h
Fixes changes requested by UX in #12865
Also fixed that dragged from explorer to Asset Browser was broken.
Tested by moving files back and forward in the Asset Browser.
> Changes required by UX

- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.h
- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.ui
These breadcrumbs show the relative path of a selected folder or, if an assets is selected, its folder.
Breadcrumbs are for now hidden behind the `ed_useWIPAssetBrowserDesign` cvar.
When the width of Asset Browser window falls below a certain threshold, it goes into "narrow" mode, breadcrumbs are then shown below the search bar, view switchers and the tools menu.
Fixes: #13236
Implements breadcrumbs in the Asset Browser:
https://user-images.githubusercontent.com/104767/204834768-c186df03-7619-4f4f-a36c-cfdf5ea87197.mp4
Note:
- It's not working right for Engine assets and Gems assets. We have to fix the Relative path of asset browser entries before it works properly
- Back and forth arrows are not implemented yet. To do in …
> Implement BreadCrumbs in AssetBrowser

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/NodeGraph.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ZoomableLineEdit.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ZoomableLineEdit.h
Partial fix for https://github.com/o3de/o3de/issues/13372 by fixing scaling of the font size of the QLineEdit used for editing a node group's name. This is not a complete fix for https://github.com/o3de/o3de/issues/13372 because the height of the line edit is still not set correctly.
manually
> NodeGraph: fix scaling of node group font size when editing it

- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/SearchWidget.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/SearchWidget.h
Adds a filter to only show folders in the leftmost tree view of the new two column views in the asset browser. 
Resolves #13309.
Locally under the new WIP asset browser.
> Add a folder filter for the Asset Browser two column mode

- Code/Tools/AssetProcessor/native/unittests/PlatformConfigurationUnitTests.cpp
- Code/Tools/AssetProcessor/native/unittests/RCcontrollerUnitTests.cpp
- Code/Tools/AssetProcessor/native/unittests/RCcontrollerUnitTests.h
- Code/Tools/AssetProcessor/native/unittests/UtilitiesUnitTests.cpp
Clean up the magic numbers in PlatformConfigurationUnitTests, RCcontrollerUnitTests and UtilitiesUnitTests.
All unit tests passed with the changes.
> Clean up the magic numbers in AP unit tests

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoRevertOverrides.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/Overrides/PrefabOverridePublicInterfaceTests.cpp
This PR adds the missing "move operation" in prefab override revert undo node. Without moving back, the subtree stored in the undo node will become empty in subsequent undo/redo operations.
Before this fix, issue occurs when hitting "revert", undo, redo, and undo. In redo, the override subtree is not populated correctly, then in the second undo, the override subtree is empty.
1. Verified in editor
2. Update existing unit test to cover this fix. Verified that it failed before the fix and passed after the fix.
> BugFix - Move back override subtree in prefab override revert redo

- Code/Framework/AzCore/AzCore/IO/CompressorZLib.cpp
- Code/Framework/AzCore/AzCore/IO/CompressorZStd.cpp
- Code/Framework/AzCore/AzCore/JSON/rapidjson.h
- Code/Framework/AzCore/AzCore/Memory/Memory.h
- Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.cpp
- Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.h
- Code/Framework/AzCore/AzCore/Serialization/SerializeContext.h
- Code/Framework/AzCore/Tests/Memory.cpp
- Code/Framework/AzCore/Tests/Script.cpp
- Code/Framework/AzCore/Tests/Serialization.cpp
- Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/AssetBuilderSDK.cpp
- Gems/AudioEngineWwise/Code/Source/Engine/AudioSystemImpl_wwise.cpp
- Gems/AudioSystem/Code/Source/Engine/ATL.cpp
- Gems/AudioSystem/Code/Source/Engine/ATLComponents.cpp
- Gems/AudioSystem/Code/Source/Engine/AudioSystem.cpp
- Gems/AudioSystem/Code/Source/Engine/FileCacheManager.cpp
- Gems/RemoteTools/Code/Source/RemoteToolsSystemComponent.cpp
The allocation records no longer fill in allocation names that are supplied by the user. In many cases these names would come from AZStd containers, and were not that useful. It is more informative to track the location that the allocation originated from, which is captured in the record's callstack.
> Remove redundant azmalloc, azcreate, and azcalloc overloads

- cmake/Subdirectories.cmake
- scripts/o3de/o3de/disable_gem.py
- scripts/o3de/o3de/enable_gem.py
- scripts/o3de/o3de/engine_properties.py
- scripts/o3de/o3de/project_manager_interface.py
- scripts/o3de/o3de/project_properties.py
- scripts/o3de/o3de/utils.py
- scripts/o3de/tests/test_project_manager_interface.py
- scripts/o3de/tests/test_utils.py
This allows for gems listed in `project.json`'s `"gem_names"` array to be marked as optional.  This change helps projects that might want to soft-enable external Gems.  You can list the Gems as optional, and if the optional gems aren't found by CMake, configuration will still succeed.  External Gems that are optional can also be listed permanently in the `enabled_gems.cmake` file in the project, they will still retain their optional property.
This is an example of how it might look in `project.json`:
```
...
"gem_names": [
{
"name": "MyExternalGem",
"optional": true
}
]
...
```
This was tested against a project (Atom Sample Viewer) with external Gems from o3de-extras repo.
- With the external gems NOT registered to my manifest, configuration succeeds and the project builds successfully, …
> Allow for Optional Gem annotations

- Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphNodeGroup.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/ObjectId.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/ObjectId.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ContextMenu.cpp
- Gems/EMotionFX/Code/Source/Integration/System/SystemComponent.cpp
AnimGraphNodeGroup::m_parentNodeId added in 337565f79a0c1d90ace2e5e29e2e14fd6d2f508d (https://github.com/o3de/o3de/pull/13395) was not being serialized/deserialized when saving/loading AnimGraphs to files, causing the context menu for assigning nodes to groups to be unable to assign nodes to groups that were created from the saved file.
Fixes https://github.com/o3de/o3de/issues/13426
manually, and confirming the new AZ_Assert failed before adding the new code
> EMotionFX: reload node group's parent node ID from file

- cmake/Platform/Common/RuntimeDependencies_common.cmake
- cmake/Platform/iOS/RuntimeDependencies_ios.cmake
If fixes configuring and running iOS when built non-monolithically.
There were 3 issues:
1. Target dependencies were not picked up correctly, using `O3DE_PROJECTS_NAME` property now uses the correct project name to query dependencies.
2. Configuration was failing due to not been able to find `IMPORTED` targets, which in iOS they shouldn't be included as dependencies of targets, but it will include the imported target's dependencies.
3. The app was crashing at runtime due to not having O3DEKernel. The issue was that when a static lib depended on a shared lib, that dependency was not transmitted when a target depended on that static lib. Fixed in `ly_get_runtime_dependencies` now including the shared lib as runtime dependencies (and not only its …
> Fixed iOS when built non-monolithically.

- Code/Tools/ProjectManager/Source/GemCatalog/GemFilterWidget.cpp
This PR re-enables platform based filtering for gems in the Gem Catalog screen. Implementation was simple: there already existed logic in the filter widget classes similar to what already exists for Type, Feature, and Origin filtering. I just re-enabled that in the main code path for resetting filters.
Testing was performed manually. Results can be found in this gif.
> re-enabled platform filters for gem catalog

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocument.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentRequestBus.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocument.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystem.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/GraphDocument.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialGraphCompiler.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialGraphCompiler.h
- Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.h
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.h
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.cpp
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.h
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.cpp
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.h
This change has material canvas start up with an empty, untitled graph document and view. Nodes can be dragged into the untitled graph and generated files will be saved to a default, generated materials folder in the user's project. Once the graph is saved, the shaders and materials will be generated in that folder instead.
Other changes were made throughout the document system to do more context sensitive checks to determine if a file could be saved without user prompting.
Disabled the “save as child” menu option by default and enabling it in the material editor.
> Material Canvas: Support for automatically opening blank graph on startup

- Gems/GradientSignal/Code/Include/GradientSignal/Components/ImageGradientComponent.h
- Gems/GradientSignal/Code/Include/GradientSignal/Components/ImageGradientModification.h
- Gems/GradientSignal/Code/Include/GradientSignal/Ebuses/ImageGradientModificationBus.h
- Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
- Gems/GradientSignal/Code/Source/Components/ImageGradientModification.cpp
- Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.cpp
- Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.h
- Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponentMode.cpp
- Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponentMode.h
- Gems/GradientSignal/Code/Source/Editor/EditorImageGradientRequestBus.h
- Gems/GradientSignal/Code/gradientsignal_files.cmake
This PR finishes the reorganization of the ImageGradient / PaintBrush logic so that ImageGradient painting can now occur through both the Editor via Component Mode and through the runtime via ScriptCanvas / Lua.
The code in ImageGradientModification is pretty much a direct move of the code that used to live in EditorImageGradientComponentMode. The only logical change is that it returns a pointer to the ImageTileBuffer instead of directly tracking the undo/redo buffer. This change allows for a separation in which the runtime code just uses the buffer for managing the paint stroke compositing, and the editor code can then additionally use the buffer for undo/redo after the paint stroke is complete.
Manually verified that painting in the Editor continues to function the same as before. Also …
> [Terrain] Move ImageGradient paint logic to the runtime and expose via API

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Graph/GraphDocument.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Graph/GraphUtil.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/GraphDocument.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/GraphUtil.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_files.cmake
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialGraphCompiler.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialGraphCompiler.h
Creating holding pin for useful utility functions not exclusive to material canvas
Just moving one function and removing another. Testing that graph document still displayed correctly in inspector And instructions were still generated in execution order.
> Material Canvas: Small change starting file for graph related utility functions

- Code/Framework/AzCore/AzCore/StringFunc/StringFunc.cpp
- Code/Framework/AzCore/AzCore/StringFunc/StringFunc.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
- Gems/EMotionFX/Code/Source/Integration/System/SystemComponent.cpp
Fixes critical bug #13486
Tried various previously failing filenames.
> Fixed: Duplicating a file with an appended filename can cause an Editor deadlock

- Code/Editor/MainWindow.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/InputDialog.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/InputDialog.h
- Code/Framework/AzQtComponents/AzQtComponents/azqtcomponents_files.cmake
This PR fixes #11688. It adds an AzQtComponents::InputDialog class which expands QInputDialog by allowing a text validator to be added to the text input. It then used this to prevent the user from adding illegal characters, e.g. '/' to layout filenames.
It also fixes a discrepancy between naming and renaming a layout, where naming forced the name to lower case, whereas renaming did not. Layout names are now always lower case.
Testing performed manually.
> add AzQtComponents::InputDialog to allow validator to be used.

- AutomatedTesting/Gem/PythonTests/assetpipeline/CMakeLists.txt
Period builds were failing due to Editor and AP not being defined there. https://jenkins.build.o3de.org/job/O3DE_periodic-incremental-daily/job/development/184/
Verified build failed locally with this command, without this change:
cmake .. -DLY_3RDPARTY_PATH=C:\3rdParty -DLY_UNITY_BUILD=ON -DLY_MONOLITHIC_GAME=TRUE -DLY_PROJECTS="AutomatedTesting"
Then verified the build succeeded with this change
> Disabled Editor / AP tests in monolithic builds - fixes periodic build failure

- Code/Framework/AzToolsFramework/AzToolsFramework/ContainerEntity/ContainerEntitySystemComponent.cpp
This PR fixes some of the entity selection logic for when prefab override UX is enabled. It was not allowing descendant entities to be selected in the viewport for entities whose owning instance is the root (level).
Fixes #13415.
Manual testing in Editor.
> Fix entity selection when parent instance is the root

- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
Adds server leave log message so its clearer to users why server closed. Addresses: https://github.com/o3de/o3de/issues/13463
* Fix some bad casts in code
* Ran unit tests
* Running client/server test to ensure log is written out
```
...
<21:19:26> (System) - Remotely disconnected from remote address 127.0.0.1:50720 due to TerminatedByUser
<21:19:48> (System) - Server exiting due to zero active connections (sv_terminateOnPlayerExit=true)
```
> Add server closing message when sv_terminateOnPlayerExit is active

- scripts/build/Platform/Linux/build_config.json
Fixes https://github.com/o3de/o3de/issues/12487 
Changes AWSI test param for `PYTHON_RUNTIME` to match what is [currently configured](https://github.com/o3de/o3de/blob/f524e0bdb68610bada6648890e1a773ddcf7f7a0/cmake/LYPython.cmake#L25) for Linux.
It hasn't been tested directly in CI yet, however the current Linux tests are failing to bootstrap with the error `line 32: python: command not found`, so we know its current value is wrong, while the new value matches what is used elsewhere in the engine.
> Fix python runtime in AWS linux params

- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/PBRMaterialConvertion/Nagamaki1.fbm/Nagamaki_AO.png
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/PBRMaterialConvertion/Nagamaki1.fbm/Nagamaki_Basecolor.png
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/PBRMaterialConvertion/Nagamaki1.fbm/Nagamaki_Metallic.png
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/PBRMaterialConvertion/Nagamaki1.fbm/Nagamaki_Normal.png
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/PBRMaterialConvertion/Nagamaki1.fbm/Nagamaki_Roughness.png
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/PBRMaterialConvertion/SceneDebug/Nagamaki1.dbgsg
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/PBRMaterialConvertion/SceneDebug/Nagamaki1.dbgsg.xml
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/PBRMaterialConvertion/nagamaki1.fbx
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/fbx_tests.py
Additional FBX test verifying PBR material conversion and automatic assignment of material textures' relative path.
Signed-off-by: Rosario Cox <lesaelr@amazon.com>
Adds an additional FBX test to the asset pipeline FBX test suite.
This test verifies Stingray PBR material conversions locate and assign material textures to their corresponding fields.
Locally tested by running the FBX suite and confirming passing test results.
> Additional FBX test verifying PBR material conversion

- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_batch_tests.py
- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/test_TwoAssetsWithSameProductName_ShouldProcessAfterRename/a.fbx
- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/test_TwoAssetsWithSameProductName_ShouldProcessAfterRename/a.fbx.assetinfo
- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/test_TwoAssetsWithSameProductName_ShouldProcessAfterRename/b.fbx
- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/test_TwoAssetsWithSameProductName_ShouldProcessAfterRename/b.fbx.assetinfo
- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/test_TwoAssetsWithSameProductName_ShouldProcessAfterRename/rename.txt
Added missing test assets and additional logging.
Signed-off-by: Rosario Cox <lesaelr@amazon.com>
This PR fixes the failing test "_test_TwoAssetsWithSameProductName_ShouldProcessAfterRename_" in asset_processor_batch_tests by adding the missing test assets.
This PR was tested locally.
> Fixed test_TwoAssetsWithSameProductName_ShouldProcessAfterRename in the Asset Pipeline FBX suite.

- Tools/LyTestTools/ly_test_tools/o3de/multi_test_framework.py
This improves gaps in logging for editor test framework failures. 
I threw exceptions from every method in core Editor Test files. I then made sure they either provided sufficient debugging information already, or I added logging until it did. I moved the logging up to the location that captured all of the uncovered locations.
> Added logging to clarify EditorTest framework failures.

- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.h
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BreadCrumbs.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntryUtils.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntryUtils.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
Adds back and forward buttons Next to the breadcrumbs in new Asset Browser Design.
I recommend reviewing commit by commit.
https://user-images.githubusercontent.com/104767/205650015-33b75ff7-ef08-40b9-b131-6997a78250f3.mp4
Fixes o3de/o3de#12859
Manually
> Asset Browser breadcrumbs navigation

- Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystem.cpp
Fixes the following compilation error in mac:
````
/Users/lybuilder/workspace/o3de/Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystem.cpp:198:33: error: loop variable 'entityId' of type 'const AZ::EntityId' creates a copy from type 'const AZ::EntityId' [-Werror,-Wrange-loop-analysis]
for (const auto entityId : entityIds)
^
/Users/lybuilder/workspace/o3de/Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystem.cpp:198:22: note: use reference type 'const AZ::EntityId &' to prevent copying
for (const auto entityId : entityIds)
^~~~~~~~~~~~~~~~~~~~~
&
````
> Fix warning error on Mac

- Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialTypeBuilder.cpp
I added more file references to the material type asset for new material pipeline data, but forgot to add these dependencies.
Checked the Asset Processor "Dependencies - Out" info before and after to confirm that the .shader files and .lua files are present.
> Fixed material type dependency build failures.

- Code/Framework/AzCore/Platform/Common/VisualStudio/AzCore/Natvis/azcore.natvis
The `m_storage->m_value` member isn't available when the value_type is void.
Validated the debugger watch window was able to properly visualize an `AZ::Outcome<void, fixed_string<256>`
> Fixing natvis for AZ::Outcome<void, *> overload

- Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
Signed-off-by: JLeclercq <99494374+CyaNinix@users.noreply.github.com>
Small optimization since computing the screen percentage of a sphere implies a sqrt for perspective cameras
> Atom/RPI: Don't compute screen coverage if lod is fixed

- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/FolderAssetBrowserEntry.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp
The Relative Path variable in the asset browser displays the path to the nearest scan folder, while the Full Path variable displays the entire path from the root of your computer. Therefore, the visible path displays only the path visible in the asset browser.
Resolves #13474 
Manually
> Add VisiblePath variable to the Asset Browser

- Gems/Microphone/Code/Source/Platform/iOS/MicrophoneSystemComponent_iOS.mm
- cmake/3rdParty/Platform/iOS/BuiltInPackages_ios.cmake
Fixes #12490
Updated O3DE to use rev3 of libpng package for iOS, which fixes neon linking issues. (https://github.com/o3de/3p-package-source/pull/169)
This PR also fixes a warning error of a variable set but not used discovered while building O3DE to run unit tests in iOS.
Built iOS successfully.
> Fix iOS linkage issues with libpng library.

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Results/ErrorText.h
Signed-off-by: Jarosław Gawęda-Ścibior <99716227+LB-JaroslawGaweda@users.noreply.github.com>
* Fixed a Graph Validation arithmetic error typo in Script Canvas.
This fixes #13432
> Fixed a typo in Graph Validation error

- AutomatedTesting/TestAssets/test_chunks_builder.py
- Gems/EditorPythonBindings/Code/Source/PythonProxyBus.cpp
connect needs to be called before add_callback, this change fixes that, and adds more context to the error message.
Tested locally.
New error message:
> Fixed out of order ebus connect/add_callback, added more context to error message

- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabDeleteAsOverrideTests.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabDeleteTests.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabTestFixture.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabTestFixture.h
- Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
Signed-off-by: Junhao Wang [wjunhao@amazon.com](mailto:wjunhao@amazon.com)
This PR improves unit tests for template editing and adds 4 new tests for override editing. All tests are related to the public delete API "DeleteEntitiesAndAllDescendantsInInstance".
**Improve PrefabDeleteTests:**
1. DeleteSingleEntitySucceeds
2. DeleteSinglePrefabSucceeds
3. DeletingEntityDeletesChildEntityToo
4. DeletingEntityDeletesChildPrefabToo
**Add PrefabDeleteAsOverrideTests:**
1. DeleteSingleEntitySucceeds
2. DeleteSinglePrefabSucceeds
3. DeletingEntityDeletesChildEntityToo
4. DeletingEntityDeletesChildPrefabToo
**Update PrefabTestFixture:**
1. Add helper function to rename an entity
Follow-up for: https://github.com/o3de/o3de/pull/13171
Passed all AzToolsFramework unit tests.
> Improve prefab delete API unit tests and add override tests

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.cpp
This PR fixes a few small issues discovered while using the Animation Editor Viewport.
- Fixes a FOV calculation problem when first opening the editor that would cause a jerky behavior
- Makes view changing instant
- Fixes a bug with Alt-Tab moving camera to origin when _not_ in camera follow mode
- Fixes distance calculation for default camera
This PR was tested manually but I do intend to add additional tests in a follow-up PR
https://user-images.githubusercontent.com/82228511/206740650-f159e664-3e96-4cb1-80da-d99f7e8086e6.mp4
https://user-images.githubusercontent.com/82228511/206740679-b8fd85c8-2c02-4c68-9653-08435d581044.mp4
> Improvements to the camera behavior in the EMFX editor

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
Fix https://github.com/o3de/o3de/issues/13434
```
[Warning] (Prefab) - Source template from link with id '4' shouldn't contains key 'LinkId'
```
The cause is described in the issue. This PR removes the invalid link id stored in source template DOM. The link id was created in prefab loader when the template is sanitized.
It is okay that we remove it as when comparing between source template DOM and linked instance DOM, we already make sure link id is removed.
Manually tested and the warning is gone. Passed all tests.
> Prefab | Remove link id in source template

- AutomatedTesting/Gem/PythonTests/Prefab/tests/PrefabTestUtils.py
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
This PR blocks override editing for some prefab-related operations as they are currently not supported. It will show an info dialog to users and direct them to perform a prefab edit instead. But the PR even hides the options in context menu so users won't be able to do so.
Related Workflows:
1. Instantiate Prefab (including Procedural Prefab)
2. Create Prefab
3. Detach Prefab
Current State: Users can perform the operations but they are essentially prefab-editing.
New State: Users cannot perform the operations in the very first place.
Manually tested in editor:
> Block override editing for instantiate, create and detach prefab

- Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphStateTransition.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/TimeView/TrackDataWidget.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/TimeView/TrackDataWidget.h
Fixed the wheelMouse event for time track widget.
Basically skip the wheel event when it is dragging/resizing. This avoid multiple mouse move event triggered at same time.
https://user-images.githubusercontent.com/69218254/206630767-399ccbe1-f7b0-4c87-bf01-5ad1ea0f9add.mp4
Fixes https://github.com/o3de/o3de/issues/13535
> EMFX: Fix the  time track widget mouse wheel event

- Code/Framework/AzCore/AzCore/std/string/fixed_string.h
- Code/Framework/AzCore/AzCore/std/string/fixed_string.inl
- Code/Framework/AzCore/AzCore/std/string/string.h
- Code/Framework/AzCore/Platform/Common/MSVC/AzCore/std/string/fixed_string_MSVC.inl
The static_assert validates that the format overload that is called with a `char*` argument is used with a string_type with a value_type that is `char`.
The format overload that accepts a `wchar_t*` is validated that the value_type that is `wchar_t`
Built the codebase
> Added static_assert to string/fixed_string format

- Code/Framework/AzCore/AzCore/Component/ComponentApplication.cpp
- Code/Framework/AzCore/AzCore/Metrics/EventLoggerReflectUtils.cpp
- Code/Framework/AzCore/AzCore/Metrics/EventLoggerReflectUtils.h
- Code/Framework/AzCore/AzCore/Metrics/IEventLogger.h
- Code/Framework/AzCore/AzCore/Metrics/JsonTraceEventLogger.cpp
- Code/Framework/AzCore/AzCore/Metrics/JsonTraceEventLogger.h
- Code/Framework/AzCore/AzCore/Preprocessor/EnumReflectUtils.h
- Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.cpp
- Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.h
- Code/Framework/AzCore/AzCore/RTTI/BehaviorContextEBusEventRawSignature.inl
- Code/Framework/AzCore/AzCore/RTTI/ChronoReflection.cpp
- Code/Framework/AzCore/AzCore/RTTI/ChronoReflection.h
- Code/Framework/AzCore/AzCore/RTTI/TypeInfo.h
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryScriptUtils.cpp
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryScriptUtils.h
- Code/Framework/AzCore/AzCore/azcore_files.cmake
- Code/Framework/AzCore/Tests/Metrics/EventLoggerReflectUtilsTests.cpp
- Code/Framework/AzCore/Tests/azcoretests_files.cmake
- Gems/Multiplayer/Code/Source/MultiplayerStatSystemComponent.cpp
- Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.cpp
- Gems/ScriptEvents/Code/Include/ScriptEvents/Internal/BehaviorContextBinding/BehaviorContextFactoryMethods.h
- Gems/ScriptEvents/Code/Include/ScriptEvents/Internal/BehaviorContextBinding/ScriptEventBroadcast.cpp
- Gems/ScriptEvents/Code/Include/ScriptEvents/Internal/BehaviorContextBinding/ScriptEventBroadcast.h
- Gems/ScriptEvents/Code/Include/ScriptEvents/Internal/BehaviorContextBinding/ScriptEventMethod.cpp
- Gems/ScriptEvents/Code/Include/ScriptEvents/Internal/BehaviorContextBinding/ScriptEventMethod.h
Adding BehaviorContext support for using the EventLogger API
The primary new functions are `CreateMetricsLogger`, `RecordEvent`
`IsEventLoggerRegistered` and `GetGlobalEventLoggerFactory`.
Several wrapper classes have been added to BehaviorContext to help with
recording event data.
The `EventLoggerId` class is used to specify an ID for an event logger.
In script it can be created as such
```
import azlmbr.metrics
eventLoggerId1 = azlmbr.metrics.CreateFromInt(1)
eventLoggerId2 = azlmbr.metrics.CreateFromString("foo")
```
The `EventPhase` class is used to specify the type of event to record
```
import azlmbr.metrics
durationEventPhase = azlmbr.metrics.EventPhase.DurationBegin
```
The `InstantEventScope` class is used to specify the scope values to an
InstantEvent.
```
import azlmbr.metrics …
```
> Event logger script support: Behavior Context reflection

- Code/Framework/AzCore/AzCore/Settings/ConfigParser.cpp
- Code/Framework/AzCore/AzCore/Settings/ConfigParser.h
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.cpp
- Code/Framework/AzCore/AzCore/azcore_files.cmake
- Code/Framework/AzCore/Tests/Settings/ConfigParserTests.cpp
- Code/Framework/AzCore/Tests/Settings/SettingsRegistryMergeUtilsTests.cpp
- Code/Framework/AzCore/Tests/azcoretests_files.cmake
- Code/Tools/SerializeContextTools/Converter.cpp
The `ParseConfigFile` function can parse a Windows style INI file without any dynamic memory allocations and is suitable to be used in early application startup before O3DE allocators are available.
The SettingsRegistryMergeUtils MergeSettingsToRegistry_ConfigFile function has been updated to use the ParseConfigFile function.
`ParseConfigFile` can can be used for example to parse .ini files containing VFS settings for connecting to the AssetProcessor on Android or allocator configuration settings
Added a fix to the Comment Prefix Filter functions. If a line contained multiple comment start characters such as `";#"` and a commented line of `# This is a comment; More text`, then the Comment Prefix Filter function would only remove up to the first comment start character that was found (in …
> Adding a `ParseConfigFile` function to AzCore

- Code/Framework/AzCore/AzCore/std/time.h
- Code/Framework/AzCore/Platform/Common/Apple/AzCore/std/time_Apple.cpp
- Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/std/time_UnixLike.cpp
- Code/Framework/AzCore/Platform/Windows/AzCore/std/time_Windows.cpp
- Code/Framework/AzCore/Tests/Time/TimeTests.cpp
Added a UnitTest to validate that the CpuThread time is non-zero after waiting 50 milliseconds after the first call
> Adding PAL functions for query CPUThreadTime

- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabTestDataUtils.cpp
Fixed the following Mac compilation error:
````
[2022-12-12T09:42:04.556Z] /Users/lybuilder/workspace/o3de/Code/Framework/AzToolsFramework/Tests/Prefab/PrefabTestDataUtils.cpp:86:42: error: no viable conversion from 'optional<reference_wrapper<GenericValue<...>>>' to 'optional<reference_wrapper<const GenericValue<...>>>'
[2022-12-12T09:42:04.556Z]             PrefabDomValueConstReference patchesReference = PrefabDomUtils::FindPrefabDomValue(linkDom, PrefabDomUtils::PatchesName);
[2022-12-12T09:42:04.556Z]                                          ^                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2022-12-12T09:42:04.556Z] In file included from /Users/lybuilder/workspace/o3de/build/mac/Code/Framework/AzTool …
```
> Fix Mac compilation issue

- AutomatedTesting/Gem/PythonTests/smoke/test_CLITool_PythonBindingsExample_Works.py
Disables `TestCLIToolPythonBindingsExampleWorks` which has been failing repeatedly on unrelated AR runs.
3/5 AR runs failed on this test for no reason, please see https://github.com/o3de/o3de/issues/13693 for more details and logs.
Ran AR
> Disable TestCLIToolPythonBindingsExampleWorkst that fails periodically

- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/BlockCompression.h
- Gems/Atom/RPI/Code/Source/RPI.Public/RPIUtils.cpp
This adds BC4_UNORM to the set of image formats that can get decoded at runtime.
The specific use case is that with this support, we can easily take material displacement maps that default to BC4_UNORM encoding and use them on an Image Gradient as a heightmap, and then take the material basecolor texture and use it as a terrain macro material. It's not expected to be a normal use case, especially since it only supports 256 different height values, but it's a novel thing to do that isn't hard to support.
Loaded a texture and displacement map onto the terrain. Also verified with low mips of the displacement map that the pixel values match the dds when loaded into Visual Studio.
> Added BC4_UNORM support to runtime-decodable formats.

- AutomatedTesting/Gem/PythonTests/Atom/CMakeLists.txt
1. This PR moves the AutomatedTesting::Atom_Main_Null_Render_02 test to periodic suite since it is intermittently failing in AR.
2. Some example builds demonstrating this failure below:
https://jenkins.build.o3de.org/blue/rest/organizations/jenkins/pipelines/O3DE/pipelines/development/runs/3600/nodes/876/log/
https://jenkins.build.o3de.org/blue/rest/organizations/jenkins/pipelines/O3DE/pipelines/development/runs/3630/nodes/1047/log/
https://jenkins.build.o3de.org/blue/rest/organizations/jenkins/pipelines/O3DE/pipelines/development/runs/3595/nodes/865/log/
There was no need to test this as it is simply moving suites from main suite to periodic suite plus the issue has a low repro rate (0% locally so far and 1/30 or so on the AR runs).
> Move AutomatedTesting::Atom_Main_Null_Render_02 test to periodic suite temporarily.

- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/PaintBrushManipulator.cpp
- Gems/GradientSignal/Code/CMakeLists.txt
- Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainLayerSpawnerComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainWorldDebuggerComponent.cpp
This fixes a few bugs that were found while testing terrain:
* Terrain debug drawing sometimes culled out because the AABBs weren't being updated with the visibility system when terrain spawners were dragged around the level. Now the AABBs update correctly. (closes #13654 )
* Terrain Layer Spawner was using Min instead of SoftMin for the lower bounds by mistake. Switched to the correct SoftMin constant.(closes #13656 )
* Image Gradient would propose potentially invalid file names if the Entity name has invalid characters in it (spaces, slashes, etc). It now sanitizes the entity name before using it as a default file name.
* Painting didn't work when the camera is pulled back more than 1000 meters from the surface. This is because the raycast was hardcoded to only go 1000 meters. The fix …
> [Terrain] Misc TQO Bugfixes

- Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/Link/SingleInstanceMultiplePatchesBenchmarks.cpp
- Gems/Atom/RHI/Code/Tests/TagRegistryTests.cpp
- cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
- cmake/Platform/Common/Configurations_common.cmake
- cmake/Platform/Windows/Configurations_windows.cmake
Fixes compilation errors with clang, and adds a feature mainly meant for clang tools like the clang build analyzer and others (which require adding flags to compiler).
It also fixes the OpenEXR package to no longer set "/EHsc" (a MSVC-only flag) on Windows, instead, it sets it only when in MSVC.
Building this with MSVC, as well as building it with clang on windows.
to build it on windows with clang, make sure llvm clang is installed and on the path, and set the CMAKE_C_COMPILER and CMAKE_CXX_COMPILER  variables in cmake to both be clang++
You need to be inside a visual studio command prompt to do this, since some tools still invoke 'link' from vs.
> Fix clang compile and add extra flags feature

- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.ui
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BreadCrumbs.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BreadCrumbs.h
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BreadCrumbs.qss
- Code/Framework/AzQtComponents/AzQtComponents/Gallery/BreadCrumbsPage.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.h
Implements editable breadcrumbs in the Asset Browser. Fixes #12854 
https://user-images.githubusercontent.com/104767/207630758-4e8bbb03-092d-45eb-a440-417d7dedb854.mp4
Some notes:
- If an incorrect url is pasted, nothing happens
- If an url to files is pasted, the folder in which the file is located is selected
- Esc or a focus change aborts the editing
- Enter confirms editing
Potential ideas for follow-up tasks:
- validator to show if the current url is incorrect
- completer that suggest folder names at the current level
Manually and by running the editor test suite in AutomatedTesting
> Editable breadcrumbs for asset browser

- Code/Editor/CMakeLists.txt
The 3P library `squish-ccr` is listed as a build dependency of `EditorLib`, which it is not. The package is only a dependency of `ImageProcessingAtom.Editor.Static`. This removes this unnecessary dependency.
The Editor for AutomatedTesting was built and ran on Windows and Ubuntu Linux
> Remove squish-ccr from the EditorLib BUILD_DEPENDENCIES

- Gems/AtomLyIntegration/CommonFeatures/Code/Tests/EditorAreaLightComponentTests.cpp
Adds tests for light bounds when using shapes with translation offsets
Ran tests.
> add tests for light bounds for shapes with translation offsets

- AutomatedTesting/Gem/PythonTests/editor_test_testing/TestSuite_Main.py
- Tools/LyTestTools/ly_test_tools/o3de/multi_test_framework.py
- Tools/LyTestTools/setup.py
- Tools/LyTestTools/tests/integ/__init__.py
- Tools/LyTestTools/tests/unit/test_o3de_multi_test_framework.py
- python/requirements.txt
Resolves https://github.com/o3de/o3de/issues/10588 and https://github.com/o3de/o3de/issues/12685 by updating to the latest version of PyTest. Also includes minor updates to make it easier to run tests locally.
Tests pass when running the following command with CWD in o3de/build:
`ctest -C profile -L "(SUITE_smoke|SUITE_main)" --no-tests=error --parallel 12 --output-on-failure`
> Update PyTyest, custom plugin, and remove unused dependency

- Code/Framework/AzToolsFramework/AzToolsFramework/Metadata/MetadataManager.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
Fix AR failure in development branch.
This PR restores a flag change introduced in https://github.com/o3de/o3de/pull/13629. It was reverted during rebase in https://github.com/o3de/o3de/pull/13151.
***Why did the prefab unit tests fail?***
Between the above 2 PRs, I updated existing unit tests to check link ids in prefab template DOM in https://github.com/o3de/o3de/pull/13662. So the tests failed because of a previous bugfix reverted.
Passed all unit tests, automated tests.
> Restore removal of 'SkipLinkIds' flag during template sanitization

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
When the focus changes, only propagate changes on the previous focused instance if it's not a descendant of the new focused instance. Otherwise, the propagation of the new focused instance will automatically handle the previous focused instance.
This solves an assert that occurred when the focus changes to the root instance from a nested instance that the root has deleted as an override (because the DOM for the deleted instance doesn't exist when seen from the root).
> Only propagate previous focused instance if necessary

- Gems/GradientSignal/Code/Include/GradientSignal/Components/ImageGradientModification.h
- Gems/GradientSignal/Code/Include/GradientSignal/GradientTransform.h
- Gems/GradientSignal/Code/Source/Components/ImageGradientModification.cpp
- Gems/GradientSignal/Code/Source/GradientTransform.cpp
When painting on an image gradient with non-standard gradient transforms or tiling values, the dirty region wasn't getting calculated correctly and the set of pixels to modify wasn't accounting for rotation and scale. This PR fixes all of the issues I could find:
- Tiled images now have dirty regions that account for all of the repeated pixels affected by painting.
- ClampToEdge now stretches the dirty region to infinity when a pixel that affects the edge is modified.
- Repeat/Mirror/Unbounded now always create an infinite dirty region for changes.
- The dirty regions for modifying pixels now account for the entire volume of the pixel, not just the corner.
- The dirty region takes rotation / translation / scale into account.
- Pixels are now walked through based on their centers, not …
> [Terrain] Painting fixes with non-standard gradient transforms

- Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasViewportContent.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorViewportContent.cpp
- Gems/Atom/Tools/PassCanvas/Code/Source/Window/PassCanvasViewportContent.cpp
This fixes a problem with VS2022 17.4.3 that gives a warning about converting double to float which in turn generates an error. Giving a specific float as an argument fixes this.
Compiles correctly.
> Fix Compile Bug

- Code/Framework/AzCore/Tests/Math/ShapeIntersectionTests.cpp
`MATH_ShapeIntersection.Test` passes on Android using NEON (which is enabled by default), so enabling the test.
This test will fail on Android using Scalars when AABB dimensions are -FLT_MAX, FLT_MAX due to the usage of --ffast-math where [this trick](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Math/ShapeIntersection.inl#L181-L184) doesn't work since it's optimized away.
After discussing some potential ways to address this it was concluded that it'd be better to not trying to workaround `--ffast-math` by doing some less performant solution without being absolutely necessary and since the default SIMD set in Android is NEON now and it passes, it will be left as is for the time being. If in the future this test …
> MATH_ShapeIntersection.Test passes on Android using NEON

- Gems/EMotionFX/Code/Source/Editor/Plugins/ColliderWidgets/SimulatedObjectColliderWidget.cpp
> Add a static_cast<int> to work around Mac not allowing transparent downcast of unsigned long (aka size_t) to int

- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/BoxManipulatorRequestBus.h
- Gems/LmbrCentral/Code/Source/Shape/EditorAxisAlignedBoxShapeComponent.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorAxisAlignedBoxShapeComponent.h
- Gems/LmbrCentral/Code/Source/Shape/EditorBoxShapeComponent.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorBoxShapeComponent.h
- Gems/PhysX/Code/Source/EditorColliderComponent.cpp
- Gems/PhysX/Code/Source/EditorColliderComponent.h
Removes deprecated functions from BoxManipulatorRequestBus (#7572). The functions were marked with O3DE_DEPRECATION_NOTICE in #7463, prior to the 2210 release. The bus has very light usage, so moving directly to deleting the functions rather than marking with AZ_DEPRECATED.
Ran LmbrCentral and PhysX tests and editor tests.
> remove deprecated functions from BoxManipulatorRequestBus

- Code/Tools/AssetProcessor/Platform/Linux/native/FileWatcher/FileWatcher_linux.cpp
The cycleCount variable is only read when the
ALLOW_FILEWATCHER_DEBUG_SPAM definition is 1, but it is 0 by default. Otherwise cycleCount is only assigned to, but never read.
```
o3de/Code/Tools/AssetProcessor/Platform/Linux/native/FileWatcher/FileWatcher_linux.cpp:319:9: error: variable 'cycleCount' set but not used [-Werror,-Wunused-but-set-variable]
int cycleCount = 0;
^
```
Signed-off-by: Be Wilson <be.wilson@kdab.com>
> fix build error in FileWatcher_linux.cpp

- Code/Framework/AzCore/AzCore/RTTI/AttributeReader.h
- Code/Framework/AzCore/AzCore/Serialization/SerializeContextEnum.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/Visitor.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/Visitor.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
- Code/Framework/AzQtComponents/AzQtComponents/DPEDebugViewStandalone/main.cpp
Before this PR, EnumValue attributes were not being converted to DPE node attributes correctly in the LegacyReflectionBridge.
That was partly due to the way that attributes are being identified by a CRC of their string name; there was an EnumValue attribute in the SerializeContext and another in the EditContext.
This PR does a few things in order to handle EnumValue attributes in the DPE:
- Changes the CRC of the SerializeContext's EnumValue attribute key
- Templatizes EnumValueAttributeDefinition so it can work with the enum's original type
- Registers AttributeDefinitions for those enum types supported by the combo box property controls
- Caches related EnumValue attributes in the LegacyReflectionBridge and puts them into an EnumValues DOM node for the DPE to use
- Adds …
> Add support for EnumValue attribute to DPE

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.cpp
Signed-off-by: Nikhil Raktale <raktalen@amazon.com>
Adds a reflect call that was missed in PR13797 so that the exposed methods can be available for testing.
This change was tested along with PR13797
> Adding a Reflect call that was missed in PR13797

- Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.cpp
Signed-off-by: Michał Pełka <michal.pelka@robotec.ai>
This PR prevents a crash on the allocation SingleColorDynamicSizeLineHelper constructor.
> Fix to prevent crash on drawing arc with negative sweep.

- Code/Framework/AzFramework/AzFramework/PaintBrush/PaintBrushSettings.cpp
- Code/Framework/AzFramework/AzFramework/PaintBrush/PaintBrushSettings.h
- Code/Framework/AzToolsFramework/AzToolsFramework/PaintBrush/GlobalPaintBrushSettings.cpp
This fixes two problems discovered while testing the Paint Brush Settings with color painting:
1. The lambda for setting the color space wasn't getting called due to the wrong function signature. (See #13830 ) This was causing the color field to display the colors in the wrong color space.
2. By setting the color field to readonly when using the eyedropper, the color is greyed out, making it hard to see the color the eyedropper is picking. There's no harm in leaving these fields writeable, so this removes the readonly flags on them.
I used these changes with local modifications for doing color painting and verified that the color picker is much more usable.
> [Terrain] Fix paint brush settings when used with a color.

- Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialTypeSourceData.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialUtils.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Material/MaterialTypeAsset.h
- Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilder.cpp
- Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialTypeBuilder.cpp
- Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialTypeBuilder.h
- Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialSourceData.cpp
- Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialUtils.cpp
- Gems/Atom/RPI/Code/Tests/Material/MaterialSourceDataTests.cpp
Materials reference the original material type even when intermediate material types are involved.
This allows Material Editor to create new materials based on the original .materialtype file and both Material Editor and Material Builder understand the indirect reference to the final MaterialTypeAsset.
Also fixed a bug where child materials weren't always reprocessed when they should be, if a .materialtype is changed. See https://github.com/o3de/o3de/issues/13766
AtomSampleViewer material screenshot test script
Created new materials in material editor, using both StandardPBR and the new pipeline based equivalent material type. Also a child material. These are processed successfully by the AP and opened successfully my …
> Materials reference the original material type

- Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiPassTree.inl
Updated ImGuiPassTree to use ScriptableImGui for the color range sliders. This allows the range to be adjusted in AtomSampleViewer test scripts.
Tested together with WIP changes to add a new test script that modifies this color range.
> Updated ImGuiPassTree to use ScriptableImGui for the color range sliders

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabUiHandler.cpp
This PR fixes a crash that occurs when the left arrow key is used to collapse a tree row in the outliner that represents a focused prefab container. The issue is that after Qt sends the "on collapsed" callback, it expects the tree rows to be unaltered as it continues to manipulate tree indices. When the focus changes to another prefab, rows can be added or removed from the tree, causing the old tree indices to become invalid.
The fix is to move the focus handling to the end of the message queue to allow Qt to finish its own "on collapsed" logic before we perform ours.
Fixes #13796.
> Fix crash on outliner tree collapse

- Gems/AWSCore/Code/Tools/ResourceMappingTool/.gitignore
- Gems/AWSCore/Code/Tools/ResourceMappingTool/README.md
- Gems/AWSCore/Code/Tools/ResourceMappingTool/requirements.txt
- Gems/AWSCore/Code/Tools/ResourceMappingTool/tests/unit/utils/test_environment_utils.py
- Gems/AWSCore/Code/Tools/ResourceMappingTool/utils/environment_utils.py
Fix for https://github.com/o3de/o3de/issues/13798 
* Python loading of DLLs has changed on windows, change will fix discovery of the QT libraries
* Linux loading requires further work to fix discovery of Shiboken2 
* Launched tool from Editor menu and command line, tool opens on Windoes
* Ran all unit tests via ```python -m pytest -vv .``` all passed
> [AWSCore] Fix loading of the resource mapping tool on Windows

- Code/Framework/AzCore/AzCore/Math/Matrix3x4.cpp
- Code/Framework/AzCore/Tests/Math/Matrix3x4Tests.cpp
- Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.cpp
Fixed Matrix3x4::GetInverseFull() and FBX processing.
This bug was introduced at https://github.com/o3de/o3de/pull/13739 It messed up the normal vectors on some models, which caused many AtomSampleViewer screenshot tests to fail. The tests are passing again.
AtomSampleViewer full test suite on vulkan.
> Fixed Matrix3x4::GetInverseFull() and FBX processing.

- AutomatedTesting/Gem/PythonTests/Atom/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_02.py
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Sandbox.py
1. Re-enables the component test previously disabled in https://github.com/o3de/o3de/pull/13679 
2. Moves the 2 components causing the test to intermittently fail into sandbox suite (Mesh & Hair components caused it).
3. GHI for Hair component failure: https://github.com/o3de/o3de/issues/13819 
4. GHI for Mesh component failure: https://github.com/o3de/o3de/issues/13818 
1. Ran this command many times (at least 200) with different permutations of disabled/enabled components in the test.
2. Only the Mesh and Hair components triggered asserts every 20 to 30 runs or so. Removing them made the test pass 100 times in a row.
5. Since I can't include all output, here's an example output from 1 run below:
```py
Starting test AtomEditorComponents_Material_AddedToEntity...
Test …
```
> Re-enable Atom_Main_Null_Render_02 test, move Mesh & Hair component portions of test to sandbox for fixing.

- Code/Tools/AssetProcessor/CMakeLists.txt
- Code/Tools/AssetProcessor/native/tests/ApplicationManagerTests.cpp
Move ApplicationManagerTest.FileWatcherEventsTriggered_ProperlySignalledOnCorrectThread to the sandbox since it fails intermittently. The issue is tracked at https://github.com/o3de/o3de/issues/12638.
```
D:\github\o3de>build\windows\bin\profile\AzTestRunner.exe build\windows\bin\profile\AssetProcessor.Tests.dll AzRunUnitTests --gtest_filter=*SUITE_sandbox*
cwd = D:\github\o3de
LIB: build\windows\bin\profile\AssetProcessor.Tests.dll
Loading: build\windows\bin\profile\AssetProcessor.Tests.dll
OKAY Library loaded: build\windows\bin\profile\AssetProcessor.Tests.dll
OKAY Symbol found: AzRunUnitTests
Note: Google Test filter = *SUITE_sandbox*
[----------] Global test environment …
```
> Sandbox the failed ApplicationManagerTest

- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.h
- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.ui
- Code/Editor/LyViewPaneNames.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserBus.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserComponent.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserEntityInspectorWidget.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserEntityInspectorWidget.h
- Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
Implement a new DockWidget which displays a preview and potentially more information about an asset which gets selected in the Asset Browser
Fixes: #12856
Signed-off-by: Alexander Busse <alex@busse.earth>
Implement a new DockWidget which displays a preview and potentially more information about an asset which gets selected in the Asset Browser
Basicly just drag the Preview into a dockwidget and remove it from the Asset Browser
Manually
> New detail panel for the Asset Browser

- Tools/LyTestTools/ly_test_tools/_internal/pytest_plugin/test_tools_fixtures.py
Attempts a new workaround to resolve a filesystem race condition in pytest https://github.com/o3de/o3de/issues/13720 . The race condition most frequently appears when running multiple instances of pytest in parallel, or when invoking pytest inside another instance of pytest.
The change copies existing pytest code from https://github.com/pytest-dev/pytest/blob/7.2.x/src/_pytest/junitxml.py#L646 and modifies a single line to include `exist_ok=True`. This notably does not work around another edge case where the user requests creating a file at `grandparent/parent/file.xml` but a non-directory file already exists at `grandparent/parent` . That case does not appear to be reproducing in O3DE, should be very uncommon, and would likely require …
> Monkeypatch pytest xml file race condition

- CMakeLists.txt
Signed-off-by: Chiang <evanchia@amazon.com>
Adds the include(CTest) option to the top level CMakeLists file to create the CTest DartConfiguration file. No actual config is being added, this change is merely to remove the "Cannot find file: ~/o3de/build/windows/DartConfiguration.tcl" warning.
Tested by configuring locally and running CTest
> Includes CTest in top level CMakeLists to create the CTest config file

- Code/Framework/AzCore/AzCore/DOM/DomValue.cpp
- Code/Framework/AzCore/AzCore/DOM/DomValue.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.h
Prior to this PR, it was possible for builds to fail on Linux systems when certain integral types were being passed to the `Dom::Value` constructor due to an explicit constructor for long, unsigned long, long long, and unsigned long long being missing. Linux systems do not have the same integral types specified for uint64_t and int64_t which resulted in intended constructor ambiguity.
This PR removes the uint64_t and int64_t and replaces them with explicit constructors for long, unsigned long, long long, and unsigned long long.
**Testing**
- Ran AzCore Dom::Value tests
- Verified editor builds without error on Windows
- Verified reflected enums correctly populate comboboxes in the standalone DPE app when using enums of underlying types affected by this PR
Signed-off-by: …
> Fix ambiguous Dom::Value ctor error for Linux

- Gems/PhysX/Code/Editor/ColliderComponentMode.cpp
- Gems/PhysX/Code/Editor/ColliderComponentMode.h
- Gems/PhysX/Code/Editor/ColliderComponentModeBus.h
- Gems/PhysX/Code/Editor/Source/Components/EditorSystemComponent.cpp
- Gems/PhysX/Code/Editor/Source/Components/EditorSystemComponent.h
Reflects the Collider Component Mode to Serialize Context:
This allows it to be picked up by the new setup that allows Component Modes to register actions and switch them correctly in the file menu of the Editor using the new Action Manager.
Manual testing
> Action Manager | Reflect Collider Component Mode to work correctly with the new setup

- Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentModes/BoxComponentMode.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentModes/BoxComponentMode.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorNonUniformScaleComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorNonUniformScaleComponentMode.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorNonUniformScaleComponentMode.h
- Gems/LmbrCentral/Code/Source/Shape/EditorPolygonPrismShapeComponent.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorPolygonPrismShapeComponentMode.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorPolygonPrismShapeComponentMode.h
Reflects these Component Modes to Serialize Context:
- Box Component Mode
- Non-Uniform Scale Component Mode
- Polygon Prism Shape Component Mode
This allows them to be picked up by the new setup that allows Component Modes to register actions and switch them correctly in the file menu of the Editor using the new Action Manager.
Tested locally, verified that switching to these Component Modes changes the menu items correctly.
> Action Manager | Reflect 3 more Component Modes to work correctly with the new setup

- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUndoDeleteTests.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/BufferMemoryAllocator.cpp
Signed-off-by: spham <82231385+spham-amzn@users.noreply.github.com>
Fixes the following mac compilation errors:
```
In file included from /Users/spham/github/o3de/build/mac/External/Metal-3248c6c3/Code/CMakeFiles/Atom_RHI_Metal.Private.Static.dir/Unity/unity_0_cxx.cxx:11:
/Users/spham/github/o3de/Gems/Atom/RHI/Metal/Code/Source/RHI/BufferMemoryAllocator.cpp:111:62: error: use of undeclared identifier 'bufferMemoryView'
heapMemoryUsage.m_usedResidentInBytes -= bufferMemoryView.GetSize();
```
and 
```
In file included from /Users/spham/github/o3de/build/mac/Code/Framework/AzToolsFramework/CMakeFiles/AzToolsFramework.Tests.dir/Unity/unity_10_cxx.cxx:15:
/Users/spham/github/o3de/Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUndoDeleteTests.cpp:208:38: error: no viable conversion from …
```
> Fixes for Mac compilation errors

- Code/Framework/AzFramework/AzFramework/Application/Application.cpp
- Code/Framework/AzFramework/AzFramework/AzFrameworkModule.cpp
- Code/Framework/AzFramework/AzFramework/PaintBrush/PaintBrush.cpp
- Code/Framework/AzFramework/AzFramework/PaintBrush/PaintBrushNotificationBus.h
- Code/Framework/AzFramework/AzFramework/PaintBrush/PaintBrushSessionBus.h
- Code/Framework/AzFramework/AzFramework/PaintBrush/PaintBrushSystemComponent.cpp
- Code/Framework/AzFramework/AzFramework/PaintBrush/PaintBrushSystemComponent.h
- Code/Framework/AzFramework/AzFramework/azframework_files.cmake
- Code/Framework/AzFramework/Tests/PaintBrush/MockPaintBrushNotificationHandler.h
- Code/Framework/AzFramework/Tests/PaintBrush/PaintBrushPaintLocationTests.cpp
- Code/Framework/AzFramework/Tests/PaintBrush/PaintBrushPaintSettingsTests.cpp
- Code/Framework/AzFramework/Tests/PaintBrush/PaintBrushSmoothLocationTests.cpp
- Gems/GradientSignal/Code/Include/GradientSignal/Components/ImageGradientComponent.h
- Gems/GradientSignal/Code/Include/GradientSignal/Components/ImageGradientModification.h
- Gems/GradientSignal/Code/Include/GradientSignal/Ebuses/ImageGradientModificationBus.h
- Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
- Gems/GradientSignal/Code/Source/Components/ImageGradientModification.cpp
- Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.cpp
- Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.h
This extracts the runtime API for painting on an Image Gradient and moves it to a generic PaintBrush runtime API. The generic API makes it possible to use the same Script Canvas script for painting onto Image Gradients and Terrain Macro Material Components, depending on which entity is targeted. It also adds API support for multiple simultaneous paint sessions, so that multiple painting script instances can run in parallel.
The changes consist of the following:
* Extracted the PaintBrush instance management, wrapper code, and EBus from Image Gradient and moves it to a new PaintBrushSystemComponent.
* Added multiple instances to PaintBrushSystemComponent by adding a sessionId to the API.
* Changed the PaintBrushNotificationBus to include the brush color on every call, not just …
> [Terrain] Support multiple generic runtime paint sessions

- Code/Framework/AzFramework/AzFramework/Terrain/TerrainDataRequestBus.h
- Gems/Terrain/Code/Source/Components/TerrainHeightGradientListComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainLayerSpawnerComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainSurfaceGradientListComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainWorldDebuggerComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainWorldDebuggerComponent.h
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp
- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.cpp
- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.h
While adding support for broadcasting dirty terrain color data and changing the terrain debug dirty region to support different colors based on which types of data are dirty, I also added the bit operators to the TerrainDataChangedMask enum and cleaned up the dirty data tracking in TerrainSystem to use the flags.
This PR doesn't include the changes for broadcasting the dirty terrain color data, it just includes the enum cleanup and the colorization of the terrain debug dirty region.
Ran the changes in the Editor and was surprised to discover that surface changes also cause a height data refresh. sigh. But that's exactly the sort of reason _why_ I wanted the debug colorization change. :)
> [Terrain] Change enum to use bit operators and added colorized debug dirty region.

- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/EditorCommon.cpp
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/ImageProcessingSystemComponent.cpp
https://github.com/o3de/o3de/issues/13771
The asset source id can be empty when the exr was just added to the asset folder. Change the code so it only adds context menu when the asset source id is valid.
Follow the repro steps mentioned in the [GHI](https://github.com/o3de/o3de/issues/13771)
> GHI-13371 Freshly imported .exr files can crash the Editor when attempting to Edit Texture Settings

- Tools/LyTestTools/tests/integ/test_o3de_codeowners.py
https://github.com/o3de/o3de/issues/13304
Fixes a test to make it not rely on "o3de" being in the file path unnecessarily.
Ran the test locally.
> Changed codeowners test to not fail if o3de text is not in path.

- Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp
- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.h
This adds a secondary asset browser, which is not shown in the Tools menu, that can be opened by right clicking assets in the asset browser.
This partially fixes https://github.com/o3de/o3de/issues/12870. Dragging and dropping between the two asset browsers is not implemented yet.
Signed-off-by: Be Wilson <be.wilson@kdab.com>
https://user-images.githubusercontent.com/9455094/210030961-69a04fe2-c962-41f6-889e-383f00c5f3bb.mp4
> show secondary asset browser from context menu

- Gems/Multiplayer/Multiplayer_ScriptCanvas/CMakeLists.txt
- Templates/DefaultGem/Template/CMakeLists.txt
- Templates/DefaultProject/Template/Gem/CMakeLists.txt
- Templates/MinimalProject/Template/Gem/CMakeLists.txt
- Templates/PrebuiltGem/Template/CMakeLists.txt
- Templates/PythonToolGem/Template/CMakeLists.txt
The `o3de_find_ancestor_gem_root` function in the Gem templates were storing the output gem path in a variable called "gempath", but were checking a variable called "gem_path".
Corrected the code to store the output gem path in the `gem_path` variable.
> Corrected output variable name used to contain gem root path.

- Code/Editor/Plugins/ProjectSettingsTool/ProjectSettingsContainer.cpp
- Code/Editor/Plugins/ProjectSettingsTool/ProjectSettingsContainer.h
- Code/Framework/AzCore/AzCore/JSON/RapidJsonAllocator.h
- Code/Framework/AzCore/AzCore/JSON/rapidjson.cpp
- Code/Framework/AzCore/AzCore/JSON/rapidjson.h
- Code/Framework/AzCore/AzCore/azcore_files.cmake
- Code/Framework/AzCore/Platform/Common/VisualStudio/AzCore/Natvis/rapidjson.natvis
- Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EntityUtilityComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Metadata/MetadataManager.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Metadata/MetadataManager.h
- Code/Framework/AzToolsFramework/Tests/MetadataManagerTests.cpp
- Gems/AWSCore/Code/Include/Framework/JsonWriter.h
- Gems/GraphCanvas/Code/Source/Translation/TranslationDatabase.h
- Gems/PhysX/Code/Editor/Source/Material/Conversion/LegacyPhysicsMaterialPrefabConversion.cpp
- Gems/SceneProcessing/Code/Source/SceneBuilder/SceneBuilderWorker.cpp
- Gems/ScriptCanvas/Code/Tools/TranslationGeneration.cpp
The fixes to the memory allocators in rapidjson caused crashes on linux which turned out to be from linker choosing symbols from the assimp static library which used a different version of the rapidjson library than the rest of the engine.
Because of those crashes, the changes were reverted.  
This PR reverts the revert, and then adds one additional change which fixes the problem, by putting o3de's rapidjson into a namespace (One which it used to be in, so as to retain backward compat).  This fixes the problem, as the linker will only use the o3de rapidjson symbols that come from that namespace instead of matching them with other versions of rapidjson embedded in other third party static libraries.
Tested manually on linux and windows by compiling all assets with it.
Note that it contains …
> Restore rapidjson fixes

- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/BlockCompression.h
BC1 compression has two modes - if color0 > color1, then the 4 colors are color0, color1, 1/3 lerp, 2/3 lerp. However, there's a second mode as well, where if color0 <= color1, then the 4 colors should be color0, color1, 1/2 lerp, and transparent black.
(See https://learn.microsoft.com/en-us/windows/win32/direct3d10/d3d10-graphics-programming-guide-resources-block-compression for documentation on the two modes)
This fix adds the second mode.
Loaded a BC1-compressed image that was using both modes into an image gradient and verified that the results looked much more correct.
> Add the second mode to BC1 runtime decompression.

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
- Gems/EMotionFX/Code/Source/Integration/System/SystemComponent.cpp
Fixes certain file types not prompting the user for a rename when they are created in the asset browser
Resolves #13717.
locally
> Fix create new not prompting user for rename

- Code/Tools/SceneAPI/SceneData/Behaviors/ScriptProcessorRuleBehavior.cpp
- Code/Tools/SceneAPI/SceneData/Behaviors/ScriptProcessorRuleBehavior.h
- Code/Tools/SceneAPI/SceneData/Tests/SceneManifest/SceneManifestRuleTests.cpp
This fixes the Python shutdown issues that the Asset Builder is seeing when the Script Rule behavior uses a stale interface pointer. This first checks to see if the script interface is valid before shutting down Python.
Added ScriptProcessorRule_EditorPythonEventsInterface_RunsWithWhenCleared to regress test that the Deactivate() does not use a stale pointer.
> {ghi13575} fixing the python life cycle in ScriptProcessorRule

- AutomatedTesting/Gem/PythonTests/Atom/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_02.py
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_03.py
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Level_Loads.py
1. This PR is to temporarily disable some Atom tests on Linux since they intermittent fail.
2. It also re-enables the level loads test on Windows since it now appears to be only failing on Linux.
3. The tests do not intermittently fail on Windows (thoroughly tested already and the problematic Windows tests have bugs now in https://github.com/o3de/o3de/issues/13818 + https://github.com/o3de/o3de/issues/13819).
1. No testing needed, this is just re-enabling the level loads test for Windows and disabling 3 different test files for Linux so the failure can be root caused.
2. See this main GHI tracking ticket for all updates on these tests for Linux: https://github.com/o3de/o3de/issues/13930
> Skip some failing Atom Linux tests while bug is investigated (Windows now passes).

- Code/Framework/AzFramework/AzFramework/Physics/Configuration/RigidBodyConfiguration.cpp
- Code/Framework/AzFramework/AzFramework/Physics/Configuration/RigidBodyConfiguration.h
- Gems/PhysX/Code/Source/EditorRigidBodyComponent.cpp
Signed-off-by: amzn-ahmadkrm <ahmadkrm@amazon.com>
This PR updates the UI to disallow the user to set a Rigid Body Component to Kinematic mode while CCD is enabled and vice versa, these are not compatible in PhysX and results in a warning. This PR makes it so it doesn't get to the point of the PhysX warning and informs the user that only one setting can be used at once.
> Make CCD read only when kinematic is enabled and vice versa

- Code/Framework/AzFramework/AzFramework/Spawnable/InMemorySpawnableAssetContainer.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.cpp
Signed-off-by: Nikhil Raktale <raktalen@amazon.com>
Fixes : https://github.com/o3de/o3de/issues/4934
- Adds better error messaging for assets that were deleted on disk after being referenced
- Adds better iconography and messaging for assets that are supposed to have valid defaults, but the defaults are missing
Tested in editor
> Added a new error message for Erroneous Assets 

- Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
- Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.h
- Code/Framework/AzCore/AzCore/RTTI/ReflectContext.h
- Code/Framework/AzToolsFramework/AzToolsFramework/API/ToolsApplicationAPI.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/ComponentModeSwitcher.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/ComponentModeSwitcher.h
Signed-off-by: amzn-ahmadkrm <ahmadkrm@amazon.com>
Fixes issue: https://github.com/o3de/o3de/issues/13873
The problem was that when a user hits Undo the component is destroyed and recreated but the pointer does not update. The crash happens when it was trying to access the pointer when another entity was added to the selection. This fix stops using a pointer for the component and uses FindComponent instead.
> Bug fix: Switcher crash on undo + select other component

- Code/Tools/SceneAPI/SDKWrapper/AssImpSceneWrapper.cpp
- Gems/SceneProcessing/Code/Source/SceneBuilder/SceneBuilderWorker.cpp
- Gems/SceneProcessing/Registry/AssetProcessorGemConfig.setreg
The Helios team has already updated the AssImp library to 5.2.5 so that the scene pipeline but we are now turning on loading the “skeleton” flag. This will require a version bump to reprocess all the source scene (e.g. FBX and GLTF) files. This means that the next time a user fetches/pulls code then all the source scene files will be processed again. This should not cause any problems other than a longer load time to get back into the Editor (to finish Asset Processor).
> {lyn16847} adding import skeleton logic into scene pipeline

- Code/Tools/SceneAPI/SceneCore/Tests/Utilities/SceneGraphSelectorTests.cpp
- Code/Tools/SceneAPI/SceneCore/Utilities/SceneGraphSelector.cpp
This PR changes the behavior for loading selected/unselected node lists from scene settings. It addresses a few existing issues:
- Issue 1: All the nodes are selected by default when the selected node list contains part of all nodes and the unselected node list is missing. 
- After this change, only the nodes included in the selected node list (and their children) will be selected by default.
- Issue 2: All the nodes are selected by default when both of the selected and unselected node lists are empty (e.g. by default, a new LOD slot will say "All lod meshes selected" even if nothing is selected).
- After this change, no nodes will be selected by default when add a new LOD.
- Behavior Update: If both of the selected …
> Fix the scene setting issue when selected or the unselected node list is not provided

- Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp
This function is one of the very hot-path functions when AP is doing its fast scan.
QStrings cache the length of the string - so we don't need to compare the watch folder unless they're exactly he same length.  This saves about 5 seconds (22 down to 17) in a full run on multiplayer sample.
> Small startup performance improvement for AssetProcessor

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoDeleteAsOverride.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoDeleteAsOverride.h
This PR changes to update cached instance DOM in owning instance rather than the focused instance for deletion overrides.
We should update the cached instance DOM that is stored in the owning instance. Otherwise, the Entity 1 container entity would be unnecessarily reloaded due to sort order update.
Passed all tests.
> Prefab - Fix cached instance DOM update in undo delete

- AutomatedTesting/Assets/ap_test_assets/script_reinsert.py
- Gems/SceneProcessing/Code/Source/SceneBuilder/SceneBuilderComponent.cpp
AutomatedTesting/Assets/ap_test_assets/script_reinsert.fbx fails to be processed after https://github.com/o3de/o3de/pull/13965 is merged since https://github.com/o3de/o3de/pull/13965 changes how the selected and unselected nodes from the scene settings are parsed. This PR updated the node list to match the previous selection for script_reinsert.fbx. 
This PR also bump up the scene builder version to trigger the reprocess of all the FBX files due to scene settings change.
Verified that script_reinsert.fbx could be processed successfully. All the other FBX files were reprocessed as well.
> Fix the processing failure for script_reinsert.fbx and bump up the scene builder version

- Gems/ScriptCanvas/Code/CMakeLists.txt
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasNodeable.xsd
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/CreateSpawnTicketNodeable.ScriptCanvasNodeable.xml
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/DespawnNodeable.ScriptCanvasNodeable.xml
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/SpawnNodeable.ScriptCanvasNodeable.xml
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Time/DelayNodeable.ScriptCanvasNodeable.xml
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Time/DurationNodeable.ScriptCanvasNodeable.xml
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Time/HeartBeatNodeable.ScriptCanvasNodeable.xml
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Time/RepeaterNodeable.ScriptCanvasNodeable.xml
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Time/TimeDelayNodeable.ScriptCanvasNodeable.xml
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Time/TimerNodeable.ScriptCanvasNodeable.xml
- Templates/ScriptCanvasNode/Template/${Name}_files.cmake
- Templates/ScriptCanvasNode/Template/Source/${Name}.ScriptCanvasNodeable.xml
- Templates/ScriptCanvasNode/Template/Source/AutoGen/ScriptCanvasNodeable.xsd
- Templates/ScriptCanvasNode/template.json
The .xsd schema provides autocompletion and validation capabilities in Visual Studio when authoring or editing ScriptCanvas nodeable XML files.
Also added the same .xsd for nodeable targets generated from the ScriptCanvasNode template
Verified that no errors or warnings were emitted in Visual Studio
> Added ScriptCanvas schema for nodeables and updated template

- Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/std/time_UnixLike.cpp
- Code/Framework/AzFramework/Tests/FileIO.cpp
- Gems/PhysX/Code/Source/HingeJointComponent.cpp
Fixes #13697 
Fixed the following compilation errors:
````
/Users/macpro15/o3de/Code/Framework/AzFramework/Tests/FileIO.cpp:179:23: error: implicit conversion loses integer precision: 'clock_t' (aka 'unsigned long') to 'unsigned int' [-Werror,-Wshorten-64-to-32]
srand(clock());
~~~~~ ^~~~~~~
````
````
/data/workspace/o3de/Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/std/time_UnixLike.cpp:62:13: error: unused variable 'result' [-Werror,-Wunused-variable]
int result = clock_gettime(CLOCK_THREAD_CPUTIME_ID , &ts);
^
````
````
/Users/lybuilder/workspace/o3de/Gems/PhysX/Code/Source/HingeJointComponent.cpp:115:20: error: unused variable 'type' [-Werror,-Wunused-variable]
const auto type = …
```
> Fix mac/linux compilation errors

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_02.py
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_03.py
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Level_Loads.py
This PR re-enables a bulk of tests that were disabled in https://github.com/o3de/o3de/issues/13930
1. It does not enable the test for `AtomEditorComponents_MaterialAdded` inside `TestSuite_Main_Null_Render_Component_02.py`: https://github.com/o3de/o3de/issues/14007 
2. It also does not enable the test for `AtomEditorComponents_ReflectionProbeAdded` inside `TestSuite_Main_Null_Render_Component_03.py`: https://github.com/o3de/o3de/issues/14008 
Each test was run hundreds of times on an g4dn.2xlarge EC2. The above caused crashes but I was unable to obtain crash logs due to the crash log issue mentioned in those tickets.
> Re-enables Linux tests except for a couple intermittent failures with certain components.

- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabInstanceDomGeneratorTestFixture.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabInstanceDomGeneratorTestFixture.h
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabInstanceDomGeneratorTests.cpp
- Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
Add unit tests for generating instance and entity DOMs based on the currently focused prefab and existing template DOMs.
Ran new unit tests and checked that they passed.
> Add unit tests for instance DOM generator

- Code/Framework/AzCore/Tests/AZStd/Bitset.cpp
- Code/Framework/AzCore/Tests/JSON.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/AzToolsFrameworkTestHelpers.h
- Code/Tools/AssetProcessor/native/unittests/FileWatcherUnitTests.cpp
- Gems/ScriptCanvasDeveloper/Code/Editor/Source/EditorAutomation/EditorAutomationActions/EditorKeyActions.cpp
- Gems/ScriptCanvasDeveloper/Code/Editor/Source/EditorAutomation/EditorAutomationActions/EditorMouseActions.cpp
Fixes #13697
Fixes for the following compilation errors:
````
/Users/macpro/Desktop/build/o3de/Code/Framework/AzCore/Tests/AZStd/Bitset.cpp:27:30: error: implicit conversion loses integer precision: 'const testing::WithParamInterface<unsigned long>::ParamType' (aka 'const unsigned long') to 'AZ::u32' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
m_unsignedLong = GetParam();
~ ^~~~~~~~~~
````
````
/Users/moraaar/Amazon/o3de/Code/Framework/AzCore/Tests/JSON.cpp:124:43: error: implicit conversion loses integer precision: 'size_t'
(aka 'unsigned long') to 'rapidjson_ly::SizeType' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
author.SetString(lbuffer, static_cast<size_t>(len), document.GetAllocator());
~~~~~~~~~ …
```
> Fix Mac warnings as errors

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorTab.cpp
This PR fixes a crash issue caused by creating an asset withing the asset editor whilst in DPE mode.
Created multiple assets in DPE and non DPE mode without any issues.
> Prevent crash when creating assets with DPE enabled.

- Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp
- Gems/Atom/RPI/Code/Source/RPI.Private/RPISystemComponent.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRendererSystemComponent.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRendererSystemComponent.h
Changes include:
- Move RPISystem::InitializeSystemAssets to after all system components are activated.
- Add initialize dependency of RPISystem to PrevewRendererSystemComponent.
- Move BootstrapSystemComponent's initalize function to after all system components are activated. 
The RPISystem initialization with assets was relying on "CriticalAssetsCompiled" event. If by any chance the event wasn't triggered, it may lead to the crash in the RHI. The changes in this commit remove that dependency. Instead, it adds the initialization all system components are activated and when the AZ::TickBus::ExecuteQueuedEvents() is called.
https://github.com/o3de/o3de/issues/13115
https://github.com/o3de/o3de/issues/6139
Tested with Editor (AutomatedTesting); AutomatedTesting.GameLauncher; ASV standalone; …
> GHI-13115 Atom: Editor can crash on startup in ShaderResourceGroupLayout.cpp

- AutomatedTesting/Gem/Code/CMakeLists.txt
- Gems/Multiplayer/Code/CMakeLists.txt
- Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugModule.cpp
- Gems/Multiplayer/Code/Source/MultiplayerGem.cpp
- Gems/Multiplayer/Multiplayer_ScriptCanvas/Code/Source/ScriptCanvasMultiplayerModule.cpp
This change addresses build issues in RELEASE builds introduced with the Multiplayer Client Server split change. The specific issue here is that `AZ_DECLARE_MODULE_CLASS` functions differently in RELEASE builds.
The issue here is for any Gem that specifies different targets for the Client, Server or Unified aliases. In this case, Multiplayer specifies `Multiplayer.Client`, `Multiplayer.Server` and `Multiplayer` respectively. In RELEASE, this requires module declarations for `Gem_Multiplayer_Client`, `Gem_Multiplayer_Server` and `Gem_Multiplayer`. This is not an issue outside of RELEASE builds.
There were two potential fixes here.
1. Modify build instructions so that the convention broadly used by split Gems would be honored by default. I did not want to go this route as I have concerns …
> Fix RELEASE build issues introduced by Client/Server split

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceDomGenerator.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceDomGenerator.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceDomGeneratorInterface.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceToTemplateInterface.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceToTemplatePropagator.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceToTemplatePropagator.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoAddEntity.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoAddEntityAsOverride.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoDelete.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoDeleteAsOverride.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoEntityOverrides.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/Link/SingleInstanceMultiplePatchesBenchmarks.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabEntityAliasTests.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabInstanceDomGeneratorTestFixture.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabInstanceToTemplatePropagatorTests.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUndoEditEntityTests.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUndoLinkTests.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUndoTests.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUpdateWithPatchesTests.cpp
- Code/Tools/SerializeContextTools/SliceConverter.cpp
This PR renames the prefab entity/instance DOM generator functions to reduce confusion.
Before:
```cpp
InstanceToTemplatePropagator::GenerateDomForInstance();
InstanceToTemplatePropagator::GenerateDomForEntity();
InstanceDomGenerator::GenerateInstanceDom();
InstanceDomGenerator::GenerateEntityDom();
```
After:
```cpp
InstanceToTemplatePropagator::GenerateInstanceDomBySerializing();
InstanceToTemplatePropagator::GenerateEntityDomBySerializing();
InstanceDomGenerator::GetInstanceDomFromTemplate();
InstanceDomGenerator::GetEntityDomFromTemplate();
```
Passed tests. The PR does not alter implementation logic.
> Prefab | Rename prefab DOM generator functions

- scripts/build/Jenkins/Jenkinsfile
Fixes https://github.com/o3de/o3de/issues/14052
This change fixes an issue introduced in the Jenkisfile that prevents users from testing build config changes in a branch. The bootstrap files are always loaded from the development branch since the check will fail on new branches. 
This change moves the checkout step to the original location. The bootstrap scripts will still be pulled from the O3DE development branch if they are missing. 
Performed the following tests in a branch:
- Updated one of the build config files (e.g. scripts/build/Platform/Windows/pipeline.json). Jenkins successfully picked up the change from the branch. 
- Ran a build with the scripts/build folder missing. Bootstrap files successfully loaded from the development branch.
> Update Jenkinsfile to checkout bootstrap scripts from current branch

- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
If the client wants to connect on startup, wait for all the system components to activate, and then call connect. Connecting too soon causes a 'version mismatch' because all of the system components haven't registered their multiplayer components.
Fixes #13868
1. Open server launcher
2. Open console: host > loadlevel SampleBase > sv_launch_local_client
3. Notice game opens and connects
> Multiplayer: Fix cl_connect_onstartup

- Gems/Atom/Feature/Common/Code/Source/Material/MaterialConverterSystemComponent.cpp
After the latest AssImp library upgrade (https://github.com/o3de/o3de/commit/fda9d48d3163006cf137fda4c514ae816006a734), roughness factor of a non-PBR material is detected/exported when users create content via Blender and export it as FBX. This is introduced by the latest AssImp change: https://github.com/assimp/assimp/pull/4466. 
However, this change breaks our existing logic in the material converter: The converter treats roughness factor as one of the PBR material properties and uses it to decide the material type. This causes that non-PBR materials are not processed properly. The screenshots below shows how the testing material look like before/after the recent AssImp upgrade.
This PR updated the material converter …
> Fix an issue where non-PBR materials with valid RoughnessFactor property are not processed properly

- Gems/LyShine/Code/Source/World/UiCanvasOnMeshComponent.cpp
This PR incorporates non-uniform scale values of an entity when calculating hit information for a canvas rendered in 3D.
Fixes #13856.
> Fix input for UI canvas on mesh when using non-uniform scale

- cmake/LyAutoGen.cmake
This fixes the issue with CMake not re-configuring when an `*.AutoComponent.xml`, `*.AutoComponent.json` or `*.AutoComponent*.jinja` file is modified or removed.
fixes #12973
> Adding AzAutoGen input files as CMake Configure dependencies

- cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake
- cmake/Platform/Linux/PAL_linux.cmake
- cmake/Platform/Linux/Packaging_linux.cmake
- cmake/Platform/Linux/libunwind_linux.cmake
- scripts/build/build_node/Platform/Linux/package-list.ubuntu-bionic.txt
- scripts/build/build_node/Platform/Linux/package-list.ubuntu-focal.txt
- scripts/build/build_node/Platform/Linux/package-list.ubuntu-jammy.txt
Previously, linux was using a mystery meat package for libunwind with unknown pedigree.
This changes it to use the official libunwind provided by your system.
Building and running AP on linux and android (android is unaffected by this change, but wanted to be sure).  Also ran all the AzCore tests on linux, to pass.
> linux now uses system libunwind instead of a o3de package

- Gems/Atom/RHI/Code/Include/Atom/RHI/ShaderResourceGroupData.h
Fixes a crash during validation when a texture in an array used for SetImageViewUnboundedArray() is a nullptr.
Windows & Vulkan, using an unbound ImageArray where single views are nullptrs.
> avoid a crash with texture arrays

- Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.cpp
- Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.h
Adds a check if the RayGeneration - Shader actually needs the RayTracingSceneSrg, instead of always providing it unchecked.
Windows & Vulkan, with a Fullscreen Raytracing pass that uses an entirely custom TLAS/BLAS to trace against
> check if the raytracing pass needs the RayTracingSceneSrg

- Gems/EditorPythonBindings/Code/Tests/CustomTypeBindingBusTests.cpp
- Gems/EditorPythonBindings/Code/Tests/PythonLogSymbolsComponentTests.cpp
There are a few instances where freed variables are read from in the EditorPythonBindings tests. This fixes them.
Ran the tests with the address sanitizer enabled in Linux
> Fix heap-use-after-free errors in the EditorPythonBindings tests

- AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py
- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
Increasing multiplayer editor connections attempts to 15 tries. That's 106 seconds total. 1+1+2+3+4...+14
Note that this change doesn't cause the test to actually take 10x longer. It will still proceed as soon as it receives a connection. It should just give it a bit more of a margin for when the machine is busy.
Fixes #11635
> Multiplayer Editor Test: Wait 100 Seconds for Server to Start

- Code/Editor/Controls/FolderTreeCtrl.cpp
Fixes #7876 
Fixed issue with the `Show in Explorer` option not working in the Python Scripts tool. The original logic wasn't meant to handle absolute paths being passed in, so updated it to handle an absolute path properly while keeping the relative path logic in place as well.
Tested the menu option on both files and folders in the Python Scripts tool.
> Fixed Python Scripts show in explorer

- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ComputePass.cpp
Signed-off-by: Martin Sattlecker <martin.sattlecker@huawei.com>
The Dispatch Arguments in the Compute Shader were overwritten when the Shader was reloaded. This was unexpected, as we use Indirect Dispatch, and only set the Dispatch Arguments in the `BuildInternal` function. Not every frame.
We now load the `PassData` Dispatch Arguments in the constructor. Only the data from the Shader is updated in the LoadShader function.
Windows & Vulkan. Tested with direct and indirect dispatch and hot reloading.
> Set the Dispatch args in the constructor instead of LoadShader.

- Code/Framework/AzCore/AzCore/Debug/PerformanceCollector.cpp
- Code/Framework/AzCore/AzCore/Debug/PerformanceCollector.h
- Code/Framework/AzCore/Tests/Debug/PerformanceCollectorTests.cpp
- Gems/PhysX/Code/Source/System/PhysXSystem.cpp
Adds an optional `fileExtension` parameter to _PerformanceCollector_ so logging systems can optionally set a custom extension (such as "physx.json") on the created log file. A custom file extension makes post-processing discovery of the created logs easier, e.g., upload the file to Amazon S3 and trigger a Lambda based on file suffix. 
Defaults to **"json"** if no value is provided.
Also updates the **PhysX** gem to use the extension **"physx.json"** when initializing _PerformanceCollector_.
* `AzCore.Tests` pass
* `PhysX.Tests` pass
* `Atom_RPI.Tests` pass (not modified, but another user of _PerformanceCollector_)
* Building & running [o3de-multiplayersample](https://github.com/o3de/o3de-multiplayersample) with this change and PhysX metrics turned on produces a log file named …
> Add optional fileExtension param to PerformanceCollector

- Code/Framework/AzCore/AzCore/Component/ComponentApplicationLifecycle.cpp
- Code/Framework/AzCore/AzCore/Component/ComponentApplicationLifecycle.h
- Code/Framework/AzFramework/AzFramework/Archive/Archive.cpp
Updated the Archive system handling of OnSystemActivated lifecycle event to ONLY prune the list of archive files with asset bundle catalogs to load, if the files were opened as an archive successfully.
Updated the Component Application Lifecycle event to signal, using a different section of the Settings Registry which is never loaded from a file and is transient in memory.
See the [setregbuilder](https://github.com/o3de/o3de/blob/development/Registry/setregbuilder.assetprocessor.setreg#L17-L30) settings registry file.
fixes #13473
Built and Launched the Windows GameLauncher Monolithic build.
> Monolithic Asset Bundle Runtime fixes

- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserFilterModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserFilterModel.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserThumbnailViewProxyModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserThumbnailViewProxyModel.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.h
Refactor a bit the underlying model to derive from QIdentityProxyModel and using roles for special functions such as visibility of single  items when filtering with a search string.
After the refactoring also #14002 is fixed.
Add a context menu when showing search results, to allow navigating to the parent folder of a result item.
Signed-off-by: Alessandro Ambrosano <1006222+aambrosano@users.noreply.github.com>
Implements showing search results on the thumbnail view, and adds a context menu for navigating to the parent folder of a search result.
It also refactors the model behind the thumbnail view to make it more robust and appropriate for the search results use case.
Also fixes a crash sometimes happening when expanding source assets (#14002).
Fixes #14002 #14003.
Manual testing …
> Show search results in Asset Browser Thumbnail View (#14003)

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorTab.cpp
This PR fixes a warning when building on linux caused by including the wrong moc file.
Built withoug issues.
> Fix incorrect moc include.

- cmake/LYPython.cmake
- python/get_python.bat
- python/get_python.sh
This adds checks to the get_python and lypython.cmake files which will cause cmake or the command prompt to fail immediately and return a non zero exit code.
Continuing while the python package configuration is bad causes hard-to-attribute failures.
Windows and linux testing.
Tested the following cases on each
* No python installed
* Python installed but no packages
* Python and packages installed
Tested the above 3 against the matrix of
* Via CMake
* Via get_python
* Via CMake + an invaild package -> error
* Via get_python + an invalid package -> error
> Errors in python packages will now be a build failure

- Code/Framework/AzCore/AzCore/Serialization/EditContext.h
Adding shim to EditContext Attribute to add a GenericValueList attribute whenever an EnumValues attribute is reflected.
It does this by wrapping the data value or function that is used to obtain a `vector<EnumConstants<EnumType>>` to return a 
`vector<pair<EnumType, string>`
From @amzn-tmryan Added a shim to the `EnumAttribute` method to make a `GenericValue` value attribute for each legacy `EnumValue` attribute, so that enum value attributes can be read using the same API reading GenericValues.
Tested it as part of the PropertyEditor DPE attribute work by @amzn-tmryan
> EditContext EnumValue -> GenericValue wrapper

- AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py
Pushing multiplayer test times up to 10x the time it normally takes to help eliminate flaky fails due to extra slow Jenkin machines.
Note, this will not cause tests to run longer, success conditions will still be captured as soon as they occur, this just gives a buffer for slower machines to still pass AR.
Note: Hoping to resolve a flaky test: https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-14070/4/pipeline/898/
This test fail is actually the same fail @mcphedar was seeing [here](https://github.com/o3de/o3de/issues/13988), but only for a particular level. Maybe there is a real issue, and his level reproduces it 100%.
> Multiplayer Editor Test: Increasing More Test Wait Times

- Gems/Atom/Feature/Common/Code/Source/FrameCaptureSystemComponent.cpp
1- Avoid constant spam message:
"No callback or image path is set. No result will be generated."  
2- Allows the MaterialEditor render thumbnails.
> Fixes two bugs from FrameCaptureSystemComponent:

- Gems/Atom/Feature/Common/Assets/Passes/ReflectionScreenSpaceBlur.pass
- Gems/Atom/Feature/Common/Assets/Passes/ReflectionScreenSpaceBlurVertical.pass
- Gems/Atom/Feature/Common/Assets/Passes/ReflectionScreenSpaceComposite.pass
Fix Vulkan related validation errors which stems from the fact that we were not providing aspect plane information when trying read from a depth stencil resource.
Tested ASV SSR sample on PC vulkan
> Fix Vulkan related validation errors for SSR ASV sample

- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
The new asset browser inspector panel was not being displayed in the tools menu, this change fixes it.
Tested to make sure it works with source assets in the thumbnail view and the tree view.
Resolves #14137 
Tested locally
> Display Asset Browser Inspector in Tools

- Gems/SceneProcessing/Code/Source/SceneBuilder/SceneBuilderComponent.cpp
We had a recent fix for non-PBR material processing due to the latest assimp library upgrade (https://github.com/o3de/o3de/pull/14036). Even though the change is not in SceneAPI or Scene Builder, we should still bump up the builder version to make sure that FBX files can be reprocessed after the fix. 
Verified that all the FBX files were reprocessed
> Bump up the scene builder version to reprocess FBX files after the non-PBR material fix (#14036)

- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h
- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h
- Gems/Atom/Feature/Common/Code/Mocks/MockMeshFeatureProcessor.h
- Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Mesh/MeshComponentBus.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.h
- Gems/Vegetation/Code/Tests/VegetationMocks.h
This PR updates `AtomActorInstance` so that the meshes it uses aren't reflected in cubemaps (since they are dynamic) . This change also moves `m_excludeFromReflectionCubemaps` from the `ModelDataInstance` to the `MeshHandleDescriptor` so it can be set on `AcquireMesh()`.
Fixes #14106
This change also exposes `SetExcludeFromReflectionCubeMaps()` and `GetExcludeFromReflectionCubeMaps()` to the `MeshComponentBus` (thanks @CyaNinix for the idea)
Tested in Editor to ensure a generated cubmap no longer shows an actor in the reflection
> Removing actors from reflection cubemap images.

- Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.h
- Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.cpp
If an srg was not provided by RPI we would trigger a bindless srg assert which is incorrect. Now it only goes into the bindless srg section when the slot is for that srg. 
Tested ASV
> Fix incorrect triggering of an assert for Bindless SRG.

- Gems/Atom/RHI/Code/Include/Atom/RHI/BufferView.h
- Gems/Atom/RHI/Code/Include/Atom/RHI/ImageView.h
- Gems/Atom/RHI/DX12/Code/Source/RHI/DescriptorContext.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/BindlessArgumentBuffer.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/BindlessArgumentBuffer.h
- Gems/Atom/RHI/Metal/Code/Source/RHI/BufferView.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/BufferView.h
- Gems/Atom/RHI/Metal/Code/Source/RHI/ImageView.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/ImageView.h
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/BindlessDescriptorPool.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/BufferView.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/BufferView.h
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/ImageView.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/ImageView.h
Previously, when an ImageView or BufferView was invalidated, the old location on the bindless array was deallocated and a new one was created. This meant that it was possible for the bindless ID of the view to change under the hood, which could cause crashes in anything using that view in a bindless way. This updates DirectX, Vulkan, and Metal to replace the old location instead of allocating a new location when a view is being invalidated and reinitialized.
This also fixes BufferView invalidation in Vulkan which was previously just shutting down the BufferView instead of reinitializing it. Making it reinitialize keeps the behavior consistent with the way both ImageView on Vulkan and BufferView on Dx12 work.
The root issue this PR is attempting to address is from #13660 where as mips …
> Fixing ImageView and BufferView to have consistent bindless IDs after invalidation.

- Code/Framework/AzCore/AzCore/Settings/SettingsRegistry.h
- Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp
- Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.h
- Registry/AssetProcessorPlatformConfig.setreg
It may be desirable to have the scan folders of any project-relative Gems (Gems that reside within the project folder) be prioritized before the main Project scan folder.  By default, the project scan folder is priority 0, and all Gem scan folders start incrementing from starting value of 100, so Gem scan folders are always at a lower priority than the project.
This introduces two settings registry keys that can be used to tweak relative priorities:
`"/Amazon/AssetProcessor/Settings/GemScanFolderStartingPriorityOrder": 100`
This setting will define the starting priority order for all Gems.  The first Gem scan folder will be assigned 101 and increase value from there.
`"/Amazon/AssetProcessor/Settings/ProjectRelativeGemsScanFolderPriority": "none"`
This setting determines how you want …
> Allow adjusting scan folder priority for project-relative Gems

- Gems/EMotionFX/Code/Include/Integration/ActorComponentBus.h
- Gems/EMotionFX/Code/Source/Integration/Components/ActorComponent.cpp
- Gems/EMotionFX/Code/Source/Integration/Components/ActorComponent.h
- Gems/EMotionFX/Code/Source/Integration/Components/AnimGraphComponent.cpp
- Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp
- Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.h
Add an ebus to actor request bus to allow enable/disable actor instance update.
This is done so the end user can directly control that without having to go through create a snapshot.
> EMotionFX: Allow changing the actor instance update enable or disable through ebus

- Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
The RayTracingFeatureProcessor will now set one RayTracingAccelerationStructurePass active and disable any others when there are multiple pipelines rendering on the scene.  This avoids redundant updates of the acceleration structure which reduce performance and cause a failure on Linux when there are 3+ pipelines.
> Execute the RayTracingAccelerationStructurePass in only one pipeline per scene

- Code/Legacy/CrySystem/CmdLine.cpp
This fixes an assert that can occur with command lines that end in a single digit, such as "enableProfiling 1".
Verified that the command line ending in a single digit no longer asserts.
> Fix out-of-bounds reference that occurs when the command line ends with an argument containing a single digit.

- cmake/Platform/Android/CMakePresets.json
- cmake/Platform/Linux/CMakePresets.json
- cmake/Platform/Mac/CMakePresets.json
- cmake/Platform/Windows/CMakePresets.json
- cmake/Platform/iOS/CMakePresets.json
Presets.
Previously these presets did not specify a binary directory, therefore using these presets would default to using the binary directory of the first inherited preset.
For example windows this would result in the monolithic build being placed in the same folder as non-monolithic builds(`build/windows`), because the windows_unity target has a binary directory set to `build/windows`. his makes it so that by default the monolithic binary directory is a different directory than the non-monolithic binary directory. This can overridden via the `-B <binary-dir>` option when cmake configuring.
For more information see the
[configure_preset](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html?highlight=presets#configure-preset) inherits entry documentation for inheritance of …
> Added an explicit binary directory to the mono-default configure CMake

- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/ModifiedFBXFile_ConsistentProductOutput/SceneDebug/modifiedfbxfile.dbgsg
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/ModifiedFBXFile_ConsistentProductOutput/SceneDebug/modifiedfbxfile.dbgsg.xml
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/OneMeshMultipleMaterials/SceneDebug/single_mesh_multiple_materials.dbgsg
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/OneMeshMultipleMaterials/SceneDebug/single_mesh_multiple_materials.dbgsg.xml
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/OneMeshOneMaterial/SceneDebug/onemeshonematerial.dbgsg
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/OneMeshOneMaterial/SceneDebug/onemeshonematerial.dbgsg.xml
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/Override_ModifiedFBXFile_ConsistentProductOutput/SceneDebug/modifiedfbxfile.dbgsg
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/Override_ModifiedFBXFile_ConsistentProductOutput/SceneDebug/modifiedfbxfile.dbgsg.xml
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/ShaderBall/SceneDebug/shaderball.dbgsg
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/ShaderBall/SceneDebug/shaderball.dbgsg.xml
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/SoftNamingPhysics/SceneDebug/physicstest.dbgsg
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/SoftNamingPhysics/SceneDebug/physicstest.dbgsg.xml
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoMeshLinkedMaterials/SceneDebug/multiple_mesh_linked_materials.dbgsg
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoMeshLinkedMaterials/SceneDebug/multiple_mesh_linked_materials.dbgsg.xml
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoMeshOneMaterial/SceneDebug/multiple_mesh_one_material.dbgsg
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoMeshOneMaterial/SceneDebug/multiple_mesh_one_material.dbgsg.xml
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoMeshTwoMaterial/SceneDebug/multiple_mesh_multiple_material.dbgsg
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoMeshTwoMaterial/SceneDebug/multiple_mesh_multiple_material.dbgsg.xml
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoMeshTwoMaterial/SceneDebug/multiple_mesh_multiple_material_override.dbgsg
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoMeshTwoMaterial/SceneDebug/multiple_mesh_multiple_material_override.dbgsg.xml
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/VertexColor/SceneDebug/vertexcolor.dbgsg
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/VertexColor/SceneDebug/vertexcolor.dbgsg.xml
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/cubewithline/SceneDebug/cubewithline.dbgsg
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/cubewithline/SceneDebug/cubewithline.dbgsg.xml
- AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/OneMeshOneMaterial/SceneDebug/onemeshonematerial.dbgsg
- AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/OneMeshOneMaterial/SceneDebug/onemeshonematerial.dbgsg.xml
- AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/TwoMeshTwoMaterial/SceneDebug/multiple_mesh_multiple_material.dbgsg
- AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/TwoMeshTwoMaterial/SceneDebug/multiple_mesh_multiple_material.dbgsg.xml
- AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/TwoMeshTwoMaterial/SceneDebug/multiple_mesh_multiple_material_override.dbgsg
- AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/TwoMeshTwoMaterial/SceneDebug/multiple_mesh_multiple_material_override.dbgsg.xml
Regenerated the debug files for the FBX/scene automation testing since the latest assimp library exports RoughnessFactor for non-PBR materials. Check https://github.com/o3de/o3de/pull/14036 for more details.
Ran the FBX and scene automation tests. All the tests passed except MorphTargetOneMaterial_RunAP_SuccessWithMatchingProducts and MorphTargetTwoMaterials_RunAP_SuccessWithMatchingProducts. Those two failed tests are because of some missing product assets that are not related to the RoughnessFactor property update. We should address them in a separate PR.
It's easier to review the .dbgsg files since the changes are more obvious. The XML version of debug files contain the exact same content as .dbgsg files. Some node …
> Update the fbx/scene testing assets because of the latest assimp upgrade

- Code/Framework/AzCore/Tests/EBus.cpp
The `EBus.ConnectionPolicy_WaitOnSecondHandlerWhileStillLocked_CantComplete` test checked that a connection to the `BusWithConnectionPolicyUnlocksBus` EBus occured within 100 milliseconds which is a bit to low on the Jenkins Windows server machine running CI/CD.
The test failed previously due to it taking 100.133100 milliseconds for the `connectHandler` to connect to the `BusWithConnectionPolicyUnlocksBus` EBus.
Therefore the connection check time has been updated to 1 second.
Made sure the code compiled.
> Up the connection check time for the EBus Connection Policy test

- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_Common.azsli
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_Depth.azsl
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_DepthPass.shader
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_Forward.azsl
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_ForwardPass.shader
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_LowEndForward.shader
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_MeshMotionVector.azsl
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_MultiViewForward.shader
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_Shadowmap.shader
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_VertexEval.azsli
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_Common.azsli
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_Depth.azsl
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_DepthPass.shader
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_DepthPass_WithPS.shader
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_Forward.azsl
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_LowEndForward.shader
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_LowEndForward_EDS.shader
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_MeshMotionVector.azsl
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_MultiViewForward.shader
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_MultiViewForward_EDS.shader
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_MultiViewTransparentForward_EDS.shader
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_Shadowmap.shader
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_Shadowmap_WithPS.shader
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_SurfaceEval.azsli
This change fixes and cleans up all of the shaders provided with the current material canvas templates. When they were last submitted with support for transparency, everything appeared to work correctly on the tested pipelines but the depth shader was spamming warnings and asserts about requiring an SRG that was not bound. This turned out to be the pass SRG, which is not used in the depth shader code but was referenced in the included, common lighting code. The resulting log spam eventually caused a significant frame rate drop and potential crash.
Resolves https://github.com/o3de/o3de/issues/14121 and similar issues
Created material graphs using both templates.
Configured inputs upon created graphs to test transparency options and alpha.
Tested …
> Material Canvas: Fixing base and standard PBR material templates

- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/SearchWidget.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/SearchWidget.h
Resolves #14136.
The filter in place was only allowing source assets to be displayed,
fixes folder creation by changing the filter to an inverse product filter, allowing empty folders to be displayed.
Locally, tested that folders can now be created
> Fix folder creation in WIP Asset Browser

- Gems/Atom/Feature/Common/Code/Source/CoreLights/ProjectedShadowmapsPass.cpp
- Gems/Atom/Feature/Common/Code/Source/CoreLights/ProjectedShadowmapsPass.h
Previously, `ProjectedShadowmapsPass` expected that `FrameBeginInternal()` will always be called before `BuildInternal()` however this is not always true. That caused `m_clearShadowDrawPacket` to sometimes not be initialized when it was needed. This PR changes it so that we no longer rely on `FrameBeginInternal()` and simply make sure the draw packet is built if needed right before its used.
In addition, there seem to be circumstances where `BuildInternal()` can be called and the children should update even if `m_updateChildren` isn't set to true. This PR changes it so the children always rebuild if `BuildInternal()` is called, which forces cached shadows to re-draw.
There is still a bug where it's possible for cached shadows to become corrupted, at least in editor mode. It seems to be …
> Fixing potential crash that can happen with cached shadows

- Gems/GraphCanvas/Code/Source/Components/StylingComponent.cpp
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Styling/PseudoElement.cpp
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Styling/SelectorImplementations.cpp
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Styling/StyleManager.cpp
- Gems/GraphModel/Code/Include/GraphModel/Model/Graph.h
- Gems/GraphModel/Code/Include/GraphModel/Model/Node.h
- Gems/GraphModel/Code/Include/GraphModel/Model/Slot.h
- Gems/GraphModel/Code/Source/Model/Graph.cpp
- Gems/GraphModel/Code/Source/Model/Node.cpp
- Gems/GraphModel/Code/Source/Model/Slot.cpp
Material canvas does extensive traversing and sorting of nodes for populating the inspector and ordering instructions to generate code. Most accessor functions require looking up data on the graph object, which contains all of the node and connection data, which can be expensive.
This PR reimplements caching that saves parent nodes, connections, and data for some other recursive functions needed during sorting. The data is also protected using mutexes because a subsequent change makes material canvas sort and generate data asynchronously.
There are also minor changes to graph canvas to reserve space and avoid copying data in some places. During a stress test that loads a large graph of hundreds of nodes, it looks like most of the time is going to looking up and applying styles to graph …
> Material Canvas: Restoring graph model caching and minor graph canvas optimizations

- scripts/build/Jenkins/Jenkinsfile
Add improvements to the recent external repo AR changes: https://github.com/o3de/o3de/pull/13780
- When AR is run within a project repo, pulls any build, pipeline, and o3de configs/scripts from a `scripts/Build` folder and uses it for the AR build. (this currently overrides the o3de AR configs)
- Uses `CMAKE_LY_PROJECTS` within the project based `build_config.json` for registration
- Adds a check for a key called `DEFAULT_PROJECT` in `pipeline.json` or `o3de.json`, which sets the engine default project for registration
Tested in a sandbox with o3de-multiplayersample changes from https://github.com/o3de/o3de-multiplayersample/pull/214 and a build of O3DE development
> AR project build config

- Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
- Code/Tools/AssetProcessor/native/ui/MainWindow.ui
Improve the UX of the AP Tools tab:
- Move from checkbox to toggle
- Minor changes to the layout
- Verified AP UX manually
- AP currently doesn't have any automation tests on the GUI. I've cut an internal ticket for tracking the automation tests.
> [Disabled Startup Scan Mode] Move from checkbox to toggle and UX improvements

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndo.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndo.h
This PR updates some prefab nodes to use undo utility functions that we introduced earlier.
- PrefabUndoEntityUpdate
- PrefabUndoRemoveEntities (renamed to PrefabUndoRemoveEntityDoms)
Passed tests.
> Update prefab undo nodes to use utility functions

- Code/Tools/SceneAPI/SceneData/Groups/AnimationGroup.cpp
- Code/Tools/SceneAPI/SceneData/Groups/MeshGroup.cpp
- Code/Tools/SceneAPI/SceneUI/SceneWidgets/ManifestWidgetPage.cpp
- Code/Tools/SceneAPI/SceneUI/SceneWidgets/ManifestWidgetPage.h
- Code/Tools/SceneAPI/SceneUI/SceneWidgets/ManifestWidgetPage.ui
- Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Groups/ActorGroup.cpp
- Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Groups/MotionGroup.cpp
- Gems/PhysX/Code/Source/Pipeline/MeshGroup.cpp
- Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroup.cpp
Adds a help button to the scene manifest widget page, that links to documentation about the group associated with that page.
Manually tested so far. I'm investigating what our options are for capturing the URL open command in an automated test. That automated test will be a separate PR.
> Scene settings help button

- Code/Framework/AzCore/AzCore/Preprocessor/Enum.h
Expands the comments in Enum.h to include info about using AZ_TYPE_INFO_SPECIALIZE as well. This just helps make it more explicit that using the AZ_ENUM* macros make the enums serializable and provides helpers for counting and printing, but doesn't give them unique UUIDs. To get unique UUIDs, you also need to use AZ_TYPE_INFO_SPECIALIZE.
Recompiled and ran. It's just comment changes, so there's nothing really to test.
> Add more comments to Enum.h to provide extra usage hints.

- scripts/o3de/o3de/compatibility.py
- scripts/o3de/o3de/enable_gem.py
- scripts/o3de/tests/test_enable_gem.py
1. Fixes #14154 (enable-gem functionality does not automatically add dependencies and fails)
2. Fixes bad logic in `get_gem_project_incompatible_objects` that was causing unit tests to pass when they shouldn't
3. Adds 2 unit tests that check implicit dependencies
4. Adds infinite recursion protection to `get_incompatible_gem_version_specifiers` and makes it check dependencies recursively
- Updated unit tests, new unit tests
- Tested adding implicit dependencies (existing, missing and recursive) to misc gem.json files and used --dry-run to see if enable_gem returned correct output.
> Enable gems with found implicit gem dependencies

- Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
- Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
- Code/Tools/AssetProcessor/native/ui/MainWindow.h
- Code/Tools/AssetProcessor/native/ui/MainWindow.ui
- Code/Tools/AssetProcessor/native/ui/ProductAssetTreeModel.h
- Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
- Code/Tools/AssetProcessor/native/utilities/GUIApplicationManager.h
Will consider splitting into seperate PRs
1. Fixes new startup scan mode so AP correct signals that its Idle.  Ensures that `m_isAssetProcessorReady` flag is correctly set when entering Idle after skipping startup scan.
3. Update UX for startup scan mode to new language discussed with sig/ui-ux
4. Rename Tools tab -> settings
5. Fix missing or incorrect virtuals noticed in code
* Ran all unit tests
* Ran AP with new startup scan and ensured that once AP goes Idle, Editor gets a correct response from `RequestAssetProcessorStatus`
> AssetProcessor: Fix new startup scan skip mode, update UX and rename tools to settings

- Code/Framework/AzCore/AzCore/RTTI/AttributeReader.h
- Code/Framework/AzCore/AzCore/RTTI/ReflectContext.cpp
- Code/Framework/AzCore/AzCore/RTTI/ReflectContext.h
- Code/Framework/AzCore/AzCore/Serialization/EditContext.h
- Code/Framework/AzCore/Tests/Serialization.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEnumComboBoxCtrl.hxx
- Gems/EMotionFX/Code/Source/Editor/PropertyWidgets/AnimGraphNodeNameHandler.cpp
- Gems/EMotionFX/Code/Source/Editor/PropertyWidgets/AnimGraphParameterMaskHandler.cpp
- Gems/EMotionFX/Code/Source/Editor/PropertyWidgets/AnimGraphTransitionHandler.cpp
- Gems/EMotionFX/Code/Source/Editor/PropertyWidgets/BlendNParamWeightsHandler.cpp
- Gems/EMotionFX/Code/Source/Editor/PropertyWidgets/BlendSpaceMotionContainerHandler.cpp
- Gems/EMotionFX/Code/Source/Editor/PropertyWidgets/BlendSpaceMotionHandler.cpp
Added the GetVoidInstanceAttributeInvocable function which returns a smart pointer that either wraps the existing attribute instance in a deleter that is a no-op or if the Attribute is of type `AttributeInvocable` wrap that wraps a functor stored inside of it with another function that can call the original with the first argument replaced with a void*.
It is the responsibility of the caller to verify that correct instance type is passed supplied when using the wrapped attribute with an AttributeReader. This is due to needing to perform static_cast from a `void*` instance to the original first argument type in order to make the function call.
fixes #13830
Fixed the creation of the GenericValueList attribute in the EditContext whenever an EnumValues attribute is reflected.
It now properly …
> AttributeInvocable non-void instance call wrapper

- Gems/Atom/Feature/Common/Assets/Passes/ProjectedShadowmaps.pass
- Gems/Atom/Feature/Common/Code/Source/CoreLights/ProjectedShadowmapsPass.cpp
Cached shadows were implemented with the expectation that the shadow maps were persistent resources, however they were not. The fact that they've mostly worked thus far is surprising, but it _is_ possible for the cached shadows to be overwritten by other passes since they're transient resources. This PR updates the resource to be persistent so that the memory won't be stomped on by some other pass.
Tested using a test level with multiple cameras. Also tested in loft which uses many cached shadows.
> Switch to using a persistent resource for the projected shadow map atlas

- Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
Removed the AZ_Warning on unsupported irradiance color blend mode, which causes excessive output in the Editor.
Tested Editor and AtomSampleViewer.
> Remove warning on irradiance color blend mode

- Gems/LmbrCentral/Code/Source/Audio/AudioAreaEnvironmentComponent.cpp
- Gems/LmbrCentral/Code/Source/Audio/AudioAreaEnvironmentComponent.h
- Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkRigidBodyComponent.h
- Gems/Multiplayer/Code/Source/Components/NetworkRigidBodyComponent.cpp
- Gems/PhysX/Code/Source/EditorBallJointComponent.cpp
- Gems/PhysX/Code/Source/EditorFixedJointComponent.cpp
- Gems/PhysX/Code/Source/EditorHingeJointComponent.cpp
- Gems/PhysX/Code/Source/EditorPrismaticJointComponent.cpp
- Gems/PhysX/Code/Source/ForceRegionComponent.cpp
- Gems/PhysX/Code/Source/ForceRegionComponent.h
- Gems/PhysX/Code/Source/JointComponent.cpp
- Gems/PhysX/Code/Source/JointComponent.h
**Note**
This work has been divided into multiple PRs to make it easier to review. Merging each PR into the staging branch `PhysX_StaticRigidBody_Staging_o3de`.
This change is part of the following PR https://github.com/o3de/o3de/pull/14261
This PR adapts Joints, ForceRegion, NetworkRigidBody and AudioAreaEnvironment components to query for simulated bodies after the rigid body (static or dynamic) has created them by listening to `RigidBodyNotificationBus` notifications.
Joints initialization improved to only be enabled when all the rigid bodies involved in the joint are enabled.
**Components initialization order when colliders and rigid bodies are involved:**
1. Entity calls Component::Activate
1. Rigid Body components connect to `EntityBus` to …
> Adapt components that query simulated bodies

- Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
- Gems/PhysX/Code/Source/HeightfieldColliderComponent.cpp
- Gems/PhysX/Code/Source/HeightfieldColliderComponent.h
- Gems/WhiteBox/Code/Source/Components/EditorWhiteBoxColliderComponent.cpp
- Gems/WhiteBox/Code/Source/Components/WhiteBoxColliderComponent.cpp
- Gems/WhiteBox/Code/Source/Components/WhiteBoxColliderComponent.h
**Note**
This work has been divided into multiple PRs to make it easier to review. Merging each PR into the staging branch `PhysX_StaticRigidBody_Staging_o3de`.
This change is part of the following PR https://github.com/o3de/o3de/pull/14261
Whitebox and Heightfield colliders handle their own collision and rigid body, so they have been explicitly made incompatible with other rigid bodies.
**Out of Scope**
- Now that there is a Static Rigid Body component, refactor Whitebox and Heightfield code so they don't have to handle their own rigid body, they user could instead add a rigid body component.
PhysX unit tests pass.
Passed AR in local branch `PhysX_StaticRigidBody` which has all the PRs combined.
> Update Whitebox and Heightfield components' dependencies

- AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_PxMeshConvexMeshCollides.py
- AutomatedTesting/Gem/PythonTests/Physics/tests/tick/Tick_InterpolatedRigidBodyMotionIsSmooth.py
- AutomatedTesting/Gem/PythonTests/Terrain/EditorScripts/Terrain_SupportsPhysics.py
- AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/PhysXColliderSurfaceTagEmitter_E2E_Editor.py
- Gems/PhysX/Code/Tests/ColliderScalingTests.cpp
- Gems/PhysX/Code/Tests/DebugDrawTests.cpp
- Gems/PhysX/Code/Tests/EditorTestUtilities.cpp
- Gems/PhysX/Code/Tests/PhysXColliderComponentModeTests.cpp
- Gems/PhysX/Code/Tests/ShapeColliderComponentTests.cpp
- Gems/PhysX/Code/Tests/StaticRigidBodyComponentTests.cpp
**Note**
This work has been divided into multiple PRs to make it easier to review. Merging each PR into the staging branch `PhysX_StaticRigidBody_Staging_o3de`.
This change is part of the following PR https://github.com/o3de/o3de/pull/14261
- Adapt PhysX unit tests to count for the colliders requiring a rigid body (static or dynamic).
- Fixed dyn_veg PhysXColliderSurfaceTagEmitter python test.
PhysX unit tests pass.
Passed AR in local branch `PhysX_StaticRigidBody` which has all the PRs combined.
> Adapt PhysX unit tests using the new static rigid body component

- Gems/PhysX/Code/Editor/Source/Components/Conversion/CollidersPrefabConversion.cpp
- Gems/PhysX/Code/Editor/Source/Components/Conversion/PrefabConversionUtils.cpp
- Gems/PhysX/Code/Editor/Source/Components/Conversion/PrefabConversionUtils.h
- Gems/PhysX/Code/physx_editor_files.cmake
**Note**
This work has been divided into multiple PRs to make it easier to review. Merging each PR into the staging branch `PhysX_StaticRigidBody_Staging_o3de`.
This change is part of the following PR https://github.com/o3de/o3de/pull/14261
Added console command `ed_physxUpdatePrefabsWithColliderComponents` that finds prefabs containing entities with collider components and no rigid bodies and fixes them by adding a static rigid body component.
Run `ed_physxUpdatePrefabsWithColliderComponents` console command and checked the prefabs were modified correctly and processed successfully by Asset Processor.
PR with o3de prefabs updated: https://github.com/o3de/o3de/pull/14295
> Added console command that updates prefabs containing colliders with no rigid bodies

- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BreadCrumbs.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BreadCrumbs.h
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BreadCrumbsConfig.ini
- Code/Framework/AzToolsFramework/AzToolsFramework/Editor/ActionManagerIdentifiers/EditorActionUpdaterIdentifiers.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabViewportFocusPathHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabViewportFocusPathHandler.h
Fixes https://github.com/o3de/o3de/issues/8231
Disables the Prefab Focus Breadcrumbs during Component Mode.
This prevents the user from being able to change prefab focus and with it the entity selection while using Component Mode and editing a nested prefab.
Also adds some code to the Breadcrumbs component so that it paints the 
Manual testing. Verified the behavior is now correct and Breadcrumbs links are not clickable while in Component Mode.
> Component Mode | Disable prefab focus breadcrumb on component mode

- Gems/Atom/Feature/Common/Code/Source/PostProcessing/TaaPass.cpp
- Gems/Atom/Feature/Common/Code/Source/PostProcessing/TaaPass.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/ComputePass.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ComputePass.cpp
Previously, the TAA pass would swap between two images to manage its history buffer. The current frame's output would become the next frame's history, and the current frame's history would be overwritten on the next frame. This avoids needing to copy the image to the history buffer every frame. However, this method had a problem due to the way the pass system currently works.
The pass system has no way to mark textures as read-only, which means when a pass's output is used as the input for another pass, that pass may overwrite the same image with its own modifications. This was causing TAA's output buffer to be overwritten by all the postfx passes that came after it - bloom, dof, etc. So unfortunately, a copy needs to be added for now to avoid this problem.
I implemented this change in a …
> Update TAA to make a copy of its output for next frame's history.

- Code/Framework/AzFramework/AzFramework/Physics/RigidBodyBus.h
- Gems/PhysX/Code/Source/EditorStaticRigidBodyComponent.cpp
- Gems/PhysX/Code/Source/HingeJointComponent.cpp
- Gems/PhysX/Code/Source/HingeJointComponent.h
- Gems/PhysX/Code/Source/JointComponent.cpp
- Gems/PhysX/Code/Source/JointComponent.h
- Gems/PhysX/Code/Source/PhysXCharacters/Components/CharacterControllerComponent.cpp
- Gems/PhysX/Code/Source/PrismaticJointComponent.cpp
- Gems/PhysX/Code/Source/PrismaticJointComponent.h
- Gems/PhysX/Code/Source/RigidBodyComponent.cpp
- Gems/PhysX/Code/Source/StaticRigidBodyComponent.cpp
Before this change the Hinge & Prismatic joints were connecting to the JointRequest bus too early, when their native joint wasn't created yet, so potentially JointRequest calls could arrive before the native joint is created.
PhysX unit tests passed.
> Improve how Hinge/Prismatic joints handle the connection to JointRequest bus

- .github/CODEOWNERS
Signed-off-by: amzn-phist <52085794+amzn-phist@users.noreply.github.com>
Add sig graphics audio to audio-related paths in the CODEOWNERS file.
None
> Adds sig-graphics-audio reviewers to Audio Gems

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabCreateInMemoryTests.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabCreateTests.cpp
- Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
Rearrange the "Create prefab" logic a bit so the original entity order remains intact when a prefab is created out of those entities. Before this PR, top-level container entities always appeared before regular entities.
Fixes #12603
Tested different hierarchies with a mix of entities and nested instances in Editor.
> Preserve entity order in newly created prefab

- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.h
Connects the functionality of the product asset filter to the new asset browser thumbnail view
Locally
> Connect product filter to Asset Browser thumbnail view

- scripts/build/Jenkins/Jenkinsfile
Add an option to use S3SIS to upload build artifacts after the build is done.
Use Jenkins build parameter "S3SIS_UPLOAD_PARAMS" or add "S3SIS_UPLOAD_PARAMS" in pipeline environment override in build_config.json to specify s3sis upload parameters. No upload if S3SIS_UPLOAD_PARAMS is not specified.
This allows people to upload build artifacts to S3 from branch builds and periodic builds.
Tested by uploading MultipleSample build artifacts.
> Add an option to upload build artifacts after the build is done

- Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp
Currently there is a bug in dev that causes actor to be hidden when the level first loaded. This change address it.
https://user-images.githubusercontent.com/69218254/215905502-180d82b6-ca54-49c7-a41b-6b3b970b8633.mp4
> EMFX: Fix a bug that causes actor to disappear when loading level.

- AutomatedTesting/Gem/PythonTests/Atom/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Periodic_Null_Render_MaterialEditor_01.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/MaterialEditor_Atom_PeriodicTests.py
Re-adds the deleted tests from https://github.com/o3de/o3de/pull/12583/files that deal with saving materials after updating them. These tests had to be moved to the periodic suite because they deal with saving files to disk and we try to avoid that as much as possible in the main suite (causes intermittent failures).
1. Test command used: `C:\git\o3de\python\runtime\python-3.10.5-rev1-windows\python\python.exe -m pytest -vv -s --build-directory="C:\git\o3de\build\bin\profile" C:\git\o3de\AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Periodic_Null_Render_MaterialEditor_01.py`
2. Test output:
```py
Starting test MaterialEditor_FileSaveChecks_AllChecksPass...
Test MaterialEditor_FileSaveChecks_AllChecksPass finished.
Report:
[SUCCESS] Success: original_material_document opened successfully …
```
> MaterialEditor starting periodic suite test for saving materials.

- Code/Tools/AssetProcessor/native/tests/ApplicationManagerTests.cpp
Sandboxing a flaky test again. It's been sandboxed before: https://github.com/o3de/o3de/pull/13866/files and it looks like it's still flaky https://jenkins.build.o3de.org/blue/rest/organizations/jenkins/pipelines/O3DE/branches/development/runs/3864/nodes/88/steps/792/log/?start=0
https://github.com/o3de/o3de/issues/12638
It's a sandbox so nothing direct. This is moving a test out of the main suite to the sandbox suite to avoid disrupting others.
> Sandboxing flaky test again

- Gems/StartingPointInput/Code/Source/InputHandlerNodeable.h
Fixes #14165 
This fixes an issue where any Script Canvas script with an `InputHandler` node fails to compile in the Asset Processor.
Verified scripts that use `InputHandler` now compile in the Asset Processor and handle user inputs as expected.
> Fixed InputHandler node allocator

- AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Periodic.py
- AutomatedTesting/Gem/PythonTests/Prefab/tests/create_prefab/CreatePrefab_CreationFailsWithDifferentRootEntities.py
- Adds a new test for verifying prefab creation fails when attempted with entities that do not share a common root
- Ran updated test suite with 0 failures
> Adding new CreatePrefab test for expected prefab creation failure

- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Surfaces/StandardSurface.azsli
- Gems/Atom/Feature/Common/Code/Source/FrameCaptureSystemComponent.cpp
1. Fix screenshot capture for secondary windows.
2. Fix issue that was exposed by multiscene sample
The multiscene sample started to fail from this commit:
https://github.com/o3de/o3de/pull/11016/commits/b0d199ad67aa50b798f23504dd77d9e4d6838341
It didn't introduce bug, but in fact exposed an older bug where there were different behavior after calculating specularAA, which is whether to set back linear roughness after calculating specular AA.
Check
[Gems/Atom/Feature/Common/Assets/Shaders/Materials/BasePBR/BasePBR_SurfaceData.azsli](https://github.com/o3de/o3de/pull/11016/files#diff-d7a09bf799d2de8986dda7232c78614abe97385120b888c75c0535df8780f78e) line 49 - 82 …
> Fix ASV screenshot

- .github/ISSUE_TEMPLATE/deprecation_template.md
The Deprecation Notice now adds the `needs-triage` and `needs-sig` labels by default
> Add `needs-*` labels to Deprecation Notice Issue Template

- Code/Tools/AssetProcessor/native/tests/ApplicationManagerTests.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/TestEventSignal.cpp
Fixes #12638
Increases the timeout a test is waiting for a cross-thread signal so that it if it doesn't get it we are very confident that its never going to get it.
When I measured this locally on a machine that was idle, it was something near 100ms to perform this test (total) and ~1ms to check the condition.
However, when I added a stress load to the machine, the time it takes was anywhere between 100ms and 8 seconds, which easily explains the flakyness on our test boxes.  
Also fixes a rare crash in Qt if the thread is deleted before it stops, this occurs very rarely as I tested this on repeat 10000.
I tested this on repeat 10000 with and without a load.
Signed-off-by: Nicholas Lawson <70027408+lawsonamzn@users.noreply.github.com>
> Fix flaky test - increase timeout

- Code/Tools/ProjectManager/Source/ProjectGemCatalogScreen.cpp
- When saving, need to refresh and update the cart so that Project Manager knows it's got a clean slate for the next operation.
- Without this, you can't seem to toggle gem activations back and forth.
fixes #12328 
fixes #14222 
Run Project Manager, enable some Gems, and Save.  Check `enabled_gems.cmake` that the changes are reflected there.  The Gem Cart now shows `0`.  Reverse the operations and Save again.  The changes are correct and the Gem Cart also goes to `0`.
> Fix an issue updating the Gem Cart in Project Manager

- Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignment.cpp
- Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
This PR updates the material component to handle missing assets and asset failures. If materials in the component configuration are missing or have errors, warnings will be reported and those materials will be ignored while waiting for all materials to load and setting up material instances.
Tested by loading a level with entities referencing materials to confirm that it looked correct. Then closed the level, deleted the referenced material assets, and reopen the level. Warnings were printed in the console window with information about which materials were missing and which entities were affected.
Tested restoring the missing materials. The restored materials are hot loaded and appear on the model because the asset bus is connected and listens …
> Material Component: Error handling for missing assets

- Gems/LyShine/Code/Editor/EditorWindow.cpp
- Gems/LyShine/Code/Editor/LyShineEditorSystemComponent.cpp
Fix Editor closing issues due to a Linux workaround for UI Editor. The workaround was added because the UI Editor hangs if it's destroyed and recreated on Linux (which appears to be a graphics related issue). The workaround was to have the UI Editor ignore the close event and just hide its window when asked to close, but that prevented the Editor from closing.
Now instead of special casing the UI Editor's close event, the UI Editor's view pane sets its "isDeletable" flag to false on Linux which hides/shows the UI Editor window instead of destroying/recreating it.
The root issue that warranted this workaround will be addressed in a separate ticket.
Fixes #12739.
Manual testing on Linux.
> Move Linux workaround for UI Editor

- Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderVariantAssetBuilder.cpp
- Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Common/AssetUtils.h
- Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilderUtils.cpp
- Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialTypeBuilder.cpp
- Gems/Atom/RPI/Code/Source/RPI.Edit/Common/AssetUtils.cpp
ShaderVariantAssetBuilder which help for cases
when the .shadervariantlist file references a .shader file that will eventually appear under the "Cache/Intermediate Assets/" folder.
Fixed typo in function name inside AssetUtils.h/.cpp and other files that were referencing the old function name.
> Improve asset dependency discovery for

- Code/Editor/Core/EditorActionsHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManager.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManager.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManagerInterface.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManagerInternalInterface.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/EditorAction.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/EditorAction.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/EditorActionContext.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/EditorActionUtils.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/EditorMenu.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/MenuManager.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ToolBar/EditorToolBar.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ToolBar/ToolBarManager.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/ComponentModeActionHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Editor/ActionManagerIdentifiers/EditorActionUpdaterIdentifiers.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/EditorVertexSelection.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/EditorVertexSelection.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/EditorVertexSelectionBus.h
- Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
- Code/Framework/AzToolsFramework/Tests/ActionManager/ActionManagerTests.cpp
- Code/Framework/AzToolsFramework/Tests/ActionManager/MenuManagerTests.cpp
- Code/Framework/AzToolsFramework/Tests/ActionManager/ToolBarManagerTests.cpp
- Gems/LmbrCentral/Code/Source/LmbrCentralEditor.cpp
- Gems/LmbrCentral/Code/Source/LmbrCentralEditor.h
- Gems/LmbrCentral/Code/Source/Shape/EditorSplineComponentMode.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorSplineComponentMode.h
Refactors a couple Action Manager systems to give clients more versatility and allow for better UX.
- Allow multiple Enabled State Callbacks to be installed on an Action. The enabled state of the Action will be determined by chaining the results with an AND (so if any of the callbacks returns false, the Action will be disabled).
- Refactor the Action Visibility properties to allow for actions to be shown as greyed out when disabled while in an Action Context Mode where they are active, but be hidden otherwise. The bool values have been replaced with an enum so that more granularity can be provided.
This allowed to refactor the Spline Component Mode so that the End Component Mode (`Done`) action can be disabled when any of the Spline Vertices is selected. This way, pressing `Esc` when a …
> Action Manager | Allow multiple Enabled State Callbacks, refactor Action Visibility properties

- AutomatedTesting/Gem/PythonTests/editor/EditorScripts/BasicEditorWorkflows_LevelEntityComponentCRUD.py
- AutomatedTesting/Gem/PythonTests/editor/EditorScripts/Menus_EditMenuOptions.py
- AutomatedTesting/Gem/PythonTests/editor/EditorScripts/Menus_ViewMenuOptions.py
Fixes #13349 
This fixes a few automated tests that were executing before the new action manager had fully initialized. This occurred because the new action manager doesn't add the menus until the following system tick. I added logic in the tests to wait until the menus had been added. Also removed some menu checks for items that aren't shared by both the new and old action managers.
Ran the `editor/TestSuite_Main.py` with both the new action manager enabled and disabled and verified all the automated tests passed.
> Fixed automated tests failing with new action manager enabled

- Code/Framework/AzFramework/AzFramework/Physics/Common/PhysicsSceneQueries.h
- Code/Framework/AzFramework/AzFramework/Physics/Configuration/SystemConfiguration.h
- Gems/PhysX/Code/Source/Scene/PhysXScene.cpp
- Gems/PhysX/Code/Source/Scene/PhysXScene.h
- Gems/PhysX/Code/Tests/Benchmarks/PhysXJointBenchmarks.cpp
Improves performance of scene queries in PhysX gem by replacing expensive AZ_RTTI mechanism with storing request type in the base class. 
Unit tests
> Optimized scene queries by replacing RTTI with request type

- Code/Editor/Core/EditorActionsHandler.cpp
- Code/Editor/Core/EditorActionsHandler.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/ComponentModeActionHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Editor/ActionManagerIdentifiers/EditorActionUpdaterIdentifiers.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/EditorVertexSelection.cpp
Adds an Enabled State CallBack to the "End Component Mode" action so that it is disabled when the Editor is in Entity Pick mode.
This allows the usage of the `Esc` shortcut in a nested fashion: when entering Entity Pick mode inside a Component Mode, pressing `Esc` a first time will just end the Entity Pick mode, while pressing it a second time will close the Component Mode.
Took the chance to verify that multiple Enabled State Callbacks on a single action work as intended in a real environment (unit tests already exist).
Before this PR
After this PR
> Action Manager | Disable "End Component Mode" action when Editor is in Entity Pick mode

- cmake/Platform/Android/Configurations_android.cmake
Fixing linker error  by not linking libraries from ${LY_NDK_ABI_ROOT}/usr/lib since LY_NDK_ABI_ROOT is never set.
`'ld: error: --fix-cortex-a53-843419 is only supported on AArch64 targets' ` 
Android build on linux ran succesfully.
> Fix linker error in Android builds on Linux 

- Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
- Code/Framework/AzFramework/AzFramework/Visibility/BoundsBus.h
Stop LyShine editor crash which was caused by the editor attempting to access a null transform component.
Adding null checks, but also stopping the editor before it even gets to that point by stopping the Editor from trying to view ui entities in the viewport
Fixes #14344 
Selected entity references in Ui Canvas as well as the normal Editor and made sure everything still worked. Ui entities were selected without crashing, and normal editor would still point to look at the entity
> Fix LyShine Entity Reference Crash

- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_batch_tests_2.py
This is a flaky test - it passes most of the time, but it failed on Linux in a recent development branch build https://jenkins.build.o3de.org/job/O3DE/job/development/3881/
> 107/129 Test #143: APTests.Batch_2_Main.main::TEST_RUN .....................................***Failed   39.47 sec
> 
> /data/workspace/o3de/python/python.sh -m pytest -v --tb=short --show-capture=stdout -c /data/workspace/o3de/pytest.ini --build-directory /data/workspace/o3de/build/linux/bin/profile --output-path /data/workspace/o3de/build/linux/Testing/LyTestTools/APTests.Batch_2_Main --junitxml=/data/workspace/o3de/build/linux/Testing/Pytest/APTests.Batch_2_Main.xml -m not SUITE_sandbox …
> Sandboxing a flaky test
