Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
This fixes an issue where non-svg component icons weren't being loaded. Almost all component icons have been converted to `.svg`, but some are still in the previous default format (`.png`). Because the `.svg` files aren't picked up by the Asset Processor, there is an API being used to query the full source path given a relative path that doesn't work on the `.png` files because that API expects the product extension to be on the path.
Launched the UI Editor and verified that the component icons show up on the component cards, whereas previously they were empty and warning messages were printed in the Editor log.
=> Fix non-svg component icons not being loaded

Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/GraphCanvasEditor/GraphCanvasAssetEditorMainWindow.cpp, Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp, Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp, Gems/ScriptCanvas/Code/Editor/View/Windows/mainwindow.ui
Fix some additional ambiguous shortcuts in Script Canvas and Landscape Canvas when the new action manager is enabled. These are necessary since we are currently allowing a mix of actions registered with the new action manager + registered explicitly through Qt.
Tested shortcuts in Script Canvas and Landscape Canvas with the new action manager enabled and disabled and verified they worked as expected.
=> Fixed some ambiguous shortcuts with new action manager

Gems/Terrain/Assets/seedList.seed
Adds more files to the default seed list in the Terrain Gem, so that asset bundles will contain the necessary material and shader files for rendering terrain.
Ran a release build of MultiplayerSample and verified that the terrain appeared. (Prior to this PR, the terrain did not appear)
=> Added missing terrain seed files.

AutomatedTesting/Gem/PythonTests/Terrain/CMakeLists.txt, AutomatedTesting/Gem/PythonTests/largeworlds/CMakeLists.txt
This PR opts-in the Terrain and Large Worlds Python tests in the `main` and `smoke` suites to TIAF Python.
This PR will be tested in AR.
=> Opt-in terrain and Large Worlds to TIAF Python.

Gems/Atom/Feature/Common/Assets/seedList.seed
Adds some diffuse probe grid assets that were missing from the Atom seed list, which caused errors when trying to run release pak builds.
Ran a MultiplayerSample build in profile with the AP disconnected and verified that the missing asset errors I was seeing from this no longer happen. There are still some asset load errors related to shader variants, but a GHI has been filed for that.
=> Add missing diffuse probe grid assets to seed list.

Code/Framework/AzCore/AzCore/Console/Console.cpp, Code/Framework/AzCore/AzCore/Console/Console.h, Code/Framework/AzCore/AzCore/Console/IConsole.h, Code/Framework/AzCore/Tests/Console/ConsoleTests.cpp, Code/Legacy/CrySystem/SystemCFG.cpp
Ensure AZ::Console::PerformCommand() will defer commands to be executed at a later time if the command isn't yet registered
Fixes #14449 
Call PerformCommand on a cvar before the gem module owning that cvar was registered. Later checked the cvar and noticed the cvar is now properly set.
=> Ensure All AZ::Console Commands Eventually Get Called 

Code/Framework/AzCore/AzCore/RTTI/TypeInfo.h, Code/Framework/AzCore/AzCore/RTTI/TypeInfoSimple.h, Code/Framework/AzCore/Tests/RTTI/IsTypeofBenchmarks.cpp, Code/Framework/AzCore/Tests/azcoretests_files.cmake, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.h, Gems/Atom/RHI/Code/Include/Atom/RHI/IndirectBufferSignature.h
This yields a 13.5x speed increase to the `TYPEINFO_Uuid()` method for classes, without adding any new symbols. It does this by forcing the calculation of a class's uuid at compile time, avoiding the expensive call to `AZ::Uuid::CreateStringSkipWarnings` at runtime.
Because the class's `TYPEINFO_Uuid_v` static variable is never ODR-used, no symbol is emitted for it into the generated binary.
The speed was measured with this benchmark:
```cpp
class Base
{
public:
virtual ~Base() = default;
AZ_RTTI(Base, "{4699b4b3-2a44-4a02-9f70-cd9889b4b36d}")
};
class Derived
: public Base
{
public:
AZ_RTTI(Derived, "{c89b7eac-26a0-4b37-a14e-cec20fcad7a8}", Base)
};
static void BenchmarkIsTypeof(benchmark::State& state)
{
auto derived = std::make_unique<Derived>();
Base* base = derived.get();
for (auto _ …
```
=> Use a `constexpr` static variable to force evaluation of typeid strings at compile time

Code/Framework/AzFramework/AzFramework/Physics/Material/PhysicsMaterialManager.cpp, Gems/PhysX/Code/Include/PhysX/Material/PhysXMaterial.h, Gems/PhysX/Code/Source/BaseColliderComponent.cpp, Gems/PhysX/Code/Source/EditorColliderComponent.cpp, Gems/PhysX/Code/Source/EditorRigidBodyComponent.cpp, Gems/PhysX/Code/Source/Material/PhysXMaterial.cpp, Gems/PhysX/Code/Source/Utils.cpp, Gems/PhysX/Code/Source/Utils.h
Fixes a bug that causes a crash when while waiting for a physics material asset to load the asset manager dispatches events for other assets. These events can cause `OnAssetReady` of other assets to be called and if those end up trying to create the same physics material then it leads to the crash.
Solved by creating the material first, then block until loaded.
Also renamed the utility function `GetShapesFromAsset` to `CreateShapesFromAsset` since that reflects better what it does.
Run PhysX unit tests.
Tested using a local level that was crashing while loading due to the issue described above. After this fix the level loads correctly. Also debugged the loading of colliders and rigid bodies to verify it works correctly.
=> Fixed error while loading PhysX materials.

Assets/Editor/Scripts/dump_lua_symbols.py, Gems/EditorPythonBindings/Editor/Scripts/dump_lua_symbols.py
of the APIs available for Lua scripting.
It makes use of the EBus: LuaSymbolsReporterBus.
The easiest way to run this script in O3DE
is to run it via the "Python Scripts" window in the Editor: Tools -> Other -> Python Scripts.
Press the `Execute` button after selecting the script located at:  
o3de -> Assets -> Editor ->Scripts -> dump_lua_symbols
Will produce the file <game_project>\lua_symbols.txt
Alternatively from the Editor console:
`pyRunFile C:\GIT\o3de\Assets\Editor\Scripts\dump_lua_symbols.py`   
Will produce the file <game_project>\lua_symbols.txt  
or if you need to customize the name of the output file `pyRunFile C:\GIT\o3de\Assets\Editor\Scripts\dump_lua_symbols.py -o my_lua_name.txt`   
Will produce the file <game_project>\my_lua_name.txt  
Signed-off-by: galibzon …
=> Added helper script that facilitates discovery

AutomatedTesting/Gem/PythonTests/largeworlds/large_worlds_utils/editor_dynveg_test_helper.py
- Adds a PhysX Static Rigid Body component that is now required to activate the PhysX Collider component to test helper
- Ran updated periodic suite without failure
=> Updating utility to add new dependent component

Code/Framework/AzFramework/AzFramework/Physics/CharacterBus.h, Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkCharacterComponent.h, Gems/Multiplayer/Code/Source/Components/NetworkCharacterComponent.cpp, Gems/PhysX/Code/Source/PhysXCharacters/Components/CharacterControllerComponent.cpp, Gems/PhysX/Code/Source/PhysXCharacters/Components/CharacterControllerComponent.h, Gems/PhysX/Code/Source/RigidBodyComponent.cpp, Gems/PhysX/Code/Source/RigidBodyComponent.h, Gems/PhysX/Code/Source/StaticRigidBodyComponent.cpp, Gems/PhysX/Code/Source/StaticRigidBodyComponent.h
The recent change to Static Rigid Bodies changed the timing of the Character Controller initialization. It used to occur during the component's Activate(), which meant that other components on the entity could be guaranteed that they could fetch a pointer to the component during their Activate() calls, as long as they had the service dependencies set up correctly.
However, the Character Controller now activates during OnEntityActivated(), which means that other components can no longer rely on the service dependencies to know when the Character Controller is available.
To fix this, the Character Controller now has a new notification bus that it uses to signal when the character is activated and deactivated. Dependent components can listen for these notifications to know when it is safe to …
=> Provide a CharacterNotifications bus to drive association of active PhysX character and Network Character Controllers

Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialTypeSourceData.h, Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialTypeSourceData.cpp, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test_propertysorting.materialgraph, Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialGraphCompiler.cpp
This change implements automatic sorting of material type groups and properties emitted from material canvas.
Material input nodes are used to expose material properties on the generated material type. These nodes have fields that allow the user to configure the material type property names, groups, and descriptions. The material type groups and properties will be registered in the order nodes are traversed. That order is not deterministic. There is currently no variable manager or other mechanism to explicitly dictate the organization of groups and properties. In lieu of that, the groups and properties will be sorted alphabetically.
Resolves https://github.com/o3de/o3de/issues/14263
Created included test graph with multiple texture material …
=> Material Canvas: Sorting generated material type groups and properties

Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/AreaLightComponentConfig.cpp
Signed-off-by: Zhang-Baochong <zhangbaochong@huawei.com>
Some parameters can be modified even if disabled shadow.
Manually tested in editor.
1.Open Editor.
2.Create a new Entity.
3.Add Light Component.
4.Close `Enable shadow`
5.Test if all parameters of shaodw cannot be modified.
=> Forbid to modify shadow parameters if disabled shadow.

Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkCharacterComponent.h, Gems/Multiplayer/Code/Source/Components/NetworkCharacterComponent.cpp
This addresses the feedback that appeared in #14484 .
1. Added OnCharacterDeactivated() which sets m_physicsCharacter back to null.
2. Moved the network connect / disconnect code into Activate() / Deactivate() instead of OnCharacterActivated() / OnCharacterDeactivated().
Ran MultiplayerSample and verified the character still moved around successfully.
=> NetworkCharacterComponent cleanup from previous PR feedback

Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserBus.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserComponent.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Script/LuaEditorSystemComponent.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialBrowserInteractions.cpp, Gems/EMotionFX/Code/Source/Integration/System/SystemComponent.cpp, Gems/ScriptCanvas/Code/Editor/SystemComponent.cpp
- Adds a parameter to the ebus call for notifying the editor that an asset has been created, which allows users to have their asset use custom creation logic (such as material and material graphs) and still notify the editor that an asset has been created
- Adds a signal to refresh the refresh the thumbnail view when a new asset has been created
- Partially Fixes #14394  asset renaming still needs to be implemented, will happen in a separate PR
Locally
=> Fix for create new asset in thumbnail view

scripts/o3de/o3de/compatibility.py, scripts/o3de/o3de/enable_gem.py, scripts/o3de/o3de/manifest.py, scripts/o3de/o3de/register.py, scripts/o3de/tests/test_enable_gem.py, scripts/o3de/tests/test_manifest.py, scripts/o3de/tests/test_register.py
1. Fixes a false compatibility error when a user adds a gem that has multiple nested gems inside it.  The compatibility checks are now updated to consider those gems (found in 'external_subdirectories' in the gem.json).
1. adds `--dry-run` and `--force` support for `--all-projects-path` and `--all-gems-path`
2. unit test updates and new tests for the nested gem compatibility check
3. removed unneeded call to `get_gems_json_data_by_name` and `get_enabled_gems` (unused) in `enable_gem.py`
- ran existing and new unit tests
- manually tested (and stepped thru the code) registering and unregistering the `o3de-multiplayersample-assets/Gems` path with and without the `--all-gems-path`, `-espp`,  and `--dry-run`
=> Fix nested gem dependency checking

Code/Editor/WelcomeScreen/WelcomeScreenDialog.cpp, Code/Editor/WelcomeScreen/WelcomeScreenDialog.ui
When opening an existing project, the prompt information in the level selection dialog box is misleading.
Fix the misleading prompt in the level selection dialog box.
Click `Open`
Click `Open an existing level`
=> Fix the misleading prompt in the level selection dialog box.

Code/Editor/LevelFileDialog.ui
Click `File` -> `Open Level`.
The dialog can lost focus.
Set `Open a Level` dialog to be `model`.
=> Set `Open a Level` dialog to be `model`.

Code/LauncherUnified/Launcher.cpp
Fix memory leak for system object, which is not freed when `AZ_MONOLITHIC_BUILD` is enabled.
=> Fix memory leak for system object

Gems/LyShine/Code/Editor/Animation/UiAVSequenceProps.cpp
1. Set `Time Unit` as `Frames`, and `EndTime` as `90.0`, Click `OK`.
2. Edit sequence again, as follows.
The `EndTime` is totally wrong.
=> bugfix for calculation error caused by time unit error.

Gems/LyShine/Code/Editor/EditorWindow.cpp
When saving the UI canvas file with an existed filename, UI editor will directly overwrite the existing file without prompting.
1. Create a1.uicanvas, and save to disk.
2. Create another uicanvas file, using filename as `a1.uicanvas`, and Click Save.
3. UI Editor will prompt if user want to overwrite the existing file.
=> add prompt when overwriting existing files.

Gems/UiBasics/Assets/UI/Slices/Library/Button.slice
The color label of `Text` is incorrect, as follows:
=> bugfix for text color.

Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp
Added the world bounds minHeight to the height calculation when creating the RayTracing terrain mesh, which matches the calculation used in the terrain shader.
=> Fix for RayTracing terrain mesh height

Code/Editor/CryEdit.cpp
1. Set LuaIDE as Scripts Editor.
2. Open to see log files of Editor.
3. LuaIDE starts and gives a misleading prompt.
Follow the same repo steps, and see.
=> Using default editor to open log files.

Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp, Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.h
Fix memory leak from `TrajectoryTracePath` object.
Objects of `TrajectoryTracePath` are created but no code to delete them.
Using `AZStd::unique_ptr` to track the memory allocated with `TrajectoryTracePath`.
=> Fix memory leak from TrajectoryTracePath object.

Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp, Code/Framework/AzToolsFramework/Tests/Prefab/PrefabDetachPrefabTests.cpp
This PR fixes a bug that was introduced by the detach-prefab improvement PR https://github.com/o3de/o3de/pull/14282.
**Bug:** In detached prefab, nested prefab that is not under top level entity would be reparented beyond level. Nested entity is fine.
**Cause:** The issue happens in `CreateLink` for nested prefab. It creates a reparent patch pointing to a parent entity that is in a state before detach. Moving `DetachEntities` call before `DetachNestedInstances` call can resolve the bug.
https://user-images.githubusercontent.com/11157226/217672566-e32bf27c-096c-454a-8d4d-fb6397ecb9fc.mp4
```
[==========] 7 tests from 1 test case ran. (1508 ms total)
[  PASSED  ] 5 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] PrefabDetachPrefabTests.DetachPrefabWithNestedPrefabUnderTopLevelEntityS …
```
=> Fix nested prefab bug in detach prefab operation

Code/Legacy/CrySystem/System.cpp, Gems/ImGui/Code/Source/LYCommonMenu/ImGuiLYCommonMenu.cpp
bugfix for issue #9212
1. Open sponza level.
2. Check value of `sys_MaxFPS`.
3. Check value of `vsync_interval`.
4. Modify value of `sys_MaxFPS` to `30`, value of `vsync_interval` to `0`.
The AVG FPS value equals to `30`.
5. Modify value of `vsync_interval` to `1`.
The AVG FPS value equals to `60`.
=> bugfix #9212

Gems/LyShine/Code/Source/UiParticleEmitterComponent.cpp, Gems/LyShine/Code/Source/UiParticleEmitterComponent.h
with #14552, using sprite edior to set index for each part of image, but cannot list the indices correctly.
=> bugfix for sprite sheet index.

AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_02.py
This test is intermittently failing and is going to be temporarily disabled. The root cause will be determined after https://github.com/o3de/o3de/issues/14580 is complete.
PR was not tested as this is a simple change to temporarily disable it.
=> Temporarily skip AtomEditorComponents_GlobalSkylightIBLAdded test due to intermittent failure.

Gems/Terrain/Assets/seedList.seed
With the recent material pipeline changes, the "terraindetailmaterial.azmaterialtype" is now "terraindetailmaterial_generated.azmaterialtype".
Generated a PAK file and verified the new material type file was added to it.
=> Fix terrain seed list based on recent material pipeline change.

Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/MemoryUsage.h, Gems/Atom/RHI/Code/Source/RHI.Reflect/MemoryUsage.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/BufferMemoryAllocator.cpp, Gems/Atom/RHI/Metal/Code/Source/RHI/BufferMemoryAllocator.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/MemoryTypeAllocator.h, Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiGpuProfiler.h, Gems/Atom/Utils/Code/Source/ImGuiGpuProfiler.cpp
GPU Profiler memory tracking page now shows how much of a BufferPools allocated memory has gone to unique (non-paged) allocations.
Also added Collapsing sections for the 2 tables in the memory view, Allocations can take a lot of time to render just based on sheer number of entries.
=> Add BufferPool unique allocation bytes tracking

Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/AzToolsFrameworkTestHelpers.h, Code/Framework/AzToolsFramework/Tests/EditorTransformComponentSelectionTests.cpp
Fixed several `EditorTransformComponentSelection` unit tests that fail when the new action manager is enabled by default, which was uncovered in this PR (https://github.com/o3de/o3de/pull/14581). These tests failed because they trigger operations by injecting key presses into a dummy widget that gets constructed as part of the test fixture, but these actions are registered in a different workflow when the new action manager is enabled. This required the test fixture to be updated to construct a similar dummy widget for the new action manager to register its default action context with.
Ran all unit tests with and without the new action manager enabled and verified they all pass.
=> Fixed EditorTransformComponentSelection tests with new action manager enabled

Code/Editor/Core/EditorActionsHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Editor/ActionManagerIdentifiers/EditorContextIdentifiers.h
Fixes #14442 
Added an action context for the Asset Browser with the new action manager so their shortcuts are handled properly.
Tested Asset Browser shortcuts and verified they work as expected with the new action manager both enabled and disabled.
=> Fixed asset browser shortcuts with new action manager

Code/Framework/AzNetworking/AzNetworking/Serialization/StringifySerializer.cpp, Gems/Multiplayer/Code/Include/Multiplayer/Components/MultiplayerComponent.h
The array and vector network serialization helpers were using "Element" as the base name for every entry in the array/vector. This could lead to inconsistent serialized state like the following:
Note that the ActiveShots.Size is 0, but there is an entry for an element in ActiveShots. This occurs when multiple weapons states in an array are serialized, where the first one has a size of 1, and the second has a size of 0. The second size overwrites the first, but the rest of the previous entry is left as-is.
The fix changes the helpers to generate unique names like "00", "01", etc for each array entry instead of "Element" for every entry. The assert in StringifySerializer is there to provide more visibility in case something else ends up creating non-unique names in the future.
Ran …
=> Fix array/vector network serialization to have unique names.

Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
The default value of `Expand by` is `25%`, as follows:
When set it to a new value, like `100%`, as follows, but no changes.
When my bugfix patch applied, changing "Expand by" takes effect, as follows:
=> bugfix: Changing "Expand by" doesn't take effect.

Code/Framework/AzQtComponents/AzQtComponents/Components/DockBarButton.cpp
Buttons of Editor are lack of tooltips.
=> bugfix: Editor buttons is lack of tooltips, such as Max/Min/Restore.

Code/Framework/AzCore/AzCore/Memory/PoolAllocator.cpp, Code/Framework/AzCore/AzCore/Memory/PoolAllocator.h, Code/Framework/AzCore/CMakeLists.txt
CMake contains a cache variable called `O3DE_STACK_CAPTURE_DEPTH` which determines the amount of stack frames to capture when a memory leak occurs in the C++ UnitTest.
When that cache variable is changed, it modified the public COMPILE_DEFINITION of `O3DE_STACK_CAPTURE_DEPTH` on the `O3DEKernel` library target.
As the `O3DEKernel` is a dependency of AzCore and AzCore is a dependency on all the other libraries within the code base, this required the entire code base to recompile when the option is changed.
To reduce the time needed to recompile, the `O3DE_STACK_CAPTURE_DEPTH` CMake cache variable will only change the COMPILE_DEFINITION for the `OSAllocator.cpp`, `PoolAllocator.cpp` and `SystemAllocator.cpp`.
Therefore only those 3 files need to recompile.
There is still a cost to relinking …
=> Reduced recompile time when changing O3DE_STACK_CAPTURE_DEPTH

AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py, AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_BasicConnectivity_Connects_ClientServer.py, Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Update Multiplayer System Component to wait for level load if no spawner is found; if the spawner isn't a system component and instead lives in the level, then the level wont be ready when a client-server player starts hosting.
Fixes #14635 
New Automated Test Added: _Multiplayer_BasicConnectivity_Connects_ClientServer.py_
Open Editor > open a multiplayer level using a Simple Network Player Spawner > Enable client-server mode (editorsv_clientserver) > CTRL+G. Make sure player is spawned into the game.
=> Multiplayer Waits For Level Load if No Spawner is Found

Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/AzToolsFrameworkTestHelpers.h, Code/Tools/AssetBundler/tests/tests_main.cpp, Code/Tools/DeltaCataloger/CMakeLists.txt, Code/Tools/DeltaCataloger/Tests/tests_main.cpp, Code/Tools/PythonBindingsExample/tests/TestMain.cpp, Code/Tools/SerializeContextTools/CMakeLists.txt, Code/Tools/SerializeContextTools/Tests/test_main.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Tests/Main.cpp, Gems/LyShine/Code/CMakeLists.txt, Gems/LyShine/Code/Tests/LyShineEditorTest.cpp, Gems/NvCloth/Code/Tests/NvClothEditorTestEnvironment.cpp, Gems/PhysX/Code/Tests/PhysXEditorTest.cpp, Gems/Prefab/PrefabBuilder/CMakeLists.txt, Gems/Prefab/PrefabBuilder/PrefabBuilderTests.cpp, Gems/SceneProcessing/Code/CMakeLists.txt, Gems/SceneProcessing/Code/Tests/SceneProcessingConfigEditorTest.cpp, Gems/SceneProcessing/Code/Tests/SceneProcessingConfigTest.cpp, Gems/SceneProcessing/Code/sceneprocessing_editor_tests_files.cmake
This change adds a `AZ_TOOLS_UNIT_TEST_HOOK_ENV` macro that defines a `QApplication` before constructing the test environment and running the tests, which is required if any portion of the unit tests construct a `QWidget`.
This came up in some AR failures for https://github.com/o3de/o3de/pull/14581, which enables the new Action Manager that constructs a `QWidget` internally, and so any tests that use the default tools system component end started hitting this failure since it adds the action manager system component as a required component.
I noticed that several tests had manually defined their own main hook in order to construct this `QApplication`, so I'd like to update those to use this new hook as well if this pattern is accepted.
Ran all unit tests locally with the new action …
=> Added helper for unit test hook with QApplication

Gems/GradientSignal/Code/Include/GradientSignal/Components/GradientTransformComponent.h, Gems/GradientSignal/Code/Include/GradientSignal/Ebuses/GradientTransformModifierRequestBus.h, Gems/GradientSignal/Code/Source/Components/GradientTransformComponent.cpp, Gems/GradientSignal/Code/Tests/GradientSignalImageTests.cpp
Allows gradient transforms to handle shapes which are not symmetrical about their centre e.g. shapes with translation offsets, polygon prisms. Related to #13398.
Manual testing in editor and running unit tests.
=> allow gradient transform to handle asymmetrical shapes

Gems/PhysX/Code/Editor/Source/Components/Conversion/CollidersPrefabConversion.cpp
Fixes #14656
Run the command with and without a level opened in the editor.
=> Check level is not opened when running 'ed_physxUpdatePrefabsWithColliderComponents' command

Code/Editor/TrackView/TrackViewDopeSheetBase.cpp
fix color change rule from editor to track.
1. Open Editor, create a level, create an entity with Light Component, named as `light1`.
2. Open Track View.
4. Add `light1` to sequence, add Color track.
5. Set color value as `255, 0, 0`.
6. Create a key frame at color track, set color value as `0, 255, 0`.
7. Click the key frame, open the color picker dialog, don't make any change, just click `Cancel`, then color value is changed.
=> bugfix: light color on track is inconsistent.

Code/Editor/TrackView/TVEventsDialog.cpp
4. Right click the sequence to open menus, and click `Edit Events`.
5. Add some events.
=> bugfix: edit event name with its old name.

Code/Editor/TrackView/TVEventsDialog.cpp
Remove the unnecessary prompt when deleting unused events.
4. Right click the sequence to open menus, and click Edit Events.
5. Add some events.
6. Remove one of them, as follows:
=> bugfix: remove the unnecessary prompt when deleting unused events.

Code/Legacy/CrySystem/XML/xml.cpp
Currently, due to serialize/deserialize problems, we cannot copy a node between sequences.
3. Create two sequence, and add some nodes, as follows:
4. Right click a node of sequence 1, copy it.
5. Change to sequence 2.
6. Right click, and paste.
7. The node of sequence 1 fails to copy to sequence 2.
=> fix uint64 value serialize/deserialize by CXmlNode.

Code/Editor/TrackView/TrackViewDialog.cpp
4. Add some nodes to the sequence.
5. Check the default option of `Auto Recording`, `1 sec`, which means 1 frame per 1 second.
6. Click `Auto Recording` to start recording using default option.
7. Check recording result as follows. It takes `0.5` second between two frames, not `1` second.
=> fix auto recording rate inconsistent problem.

Code/Editor/TrackView/TVSequenceProps.cpp, Code/Legacy/CryCommon/IMovieSystem.h
Save Frames options in `Edit Sequence`.
4. Click `Edit Sequence Properties`.
5. Change `Seconds` to `Frames`, and press `OK`.
6. Click `Edit Sequence Properties` again.
=> Save Frames options in Edit Sequence.

Code/Editor/TrackView/TrackViewFindDlg.cpp, Code/Editor/TrackView/TrackViewFindDlg.h
Fix `Find` function of Track View.
4. Add some nodes to the sequence.
5. Click `Find` in the toolbar of Track View.
6. Input keyword to filter items.
7. Double click an item, check whether the related item is selected.
8. Choose an item, click `Find`, check whether the related item is selected.
=> bugfix Find Node of Track View.

Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
Prior to this PR it was possible for widgets to sometimes not show after being recycled. These changes make it so all widgets are shown after being re-acquired from the widget pools.
**Testing**
- Verified DPE based components in the entity inspector stay shown after being recycled.
- Verified that other editors using the DPE function correctly after the change.
=> DPE: Show all widgets after recycling

Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/MultiSparseVector.h, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/SparseVector.h
This fixes a bug in SparseVector and MultiSparseVector where random memory could be treated as a valid object in a copy assignment.
These containers use a vector or multiple vectors to store data in cases where you want a stable index, and don't care about there being holes in the data. The holes have a linked list embedded in them so that the container can just point to the first free slot if it exists, and that slot will point to the next etc. When acquiring a new slot on the list, previously it was initialized with a copy assignment, but this treats the existing memory as a valid object, which can cause problems on any objects with complicated destruction behavior. The fix is to do a placement new to the memory location to avoid any kind of copy or possible calls to a destructor.
This …
=> Fixes for creating a new entry in an existing spot on a sparse vector.

Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/PolygonLightFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshCommon.h, Gems/Atom/Feature/Common/Code/Source/CoreLights/PolygonLightFeatureProcessor.cpp
This PR fixes a few small issues with the polygon light.
- Depending on the order of initialization, it was possible for AZ::Hemisphere to complain about a non-normalized direction. This happened when the polygon tried updating its bounds before having any points.
- The polygon light would still create a "valid" default initialized sphere when it was invalid
- When the polygon's points are removed and lowered to below 3, it wouldn't update to not render, instead it would retain a brighter version of the last valid point configuration.
Tested the Polygon light in various configurations.
=> Polygon light bounds fix

Code/Framework/AzToolsFramework/AzToolsFramework/UI/Notifications/ToastNotificationsView.cpp
Sets the maximum width and height of the widget blocking access to the `File` and `Edit` menus in the main editor window's menu bar to 0,0.
Verified that this doesn't preclude the correct behavior of the toast notification system as the same visual feedback shown in the change that introduced the issue ([14197](https://github.com/o3de/o3de/pull/14197)) could be reproduced.
Closes #14471
Manual testing as per gif above.
=> Fix issue with File and Edit menus of the main editor window being unresponsive.

Code/Framework/AzFramework/AzFramework/Physics/Common/PhysicsSceneQueries.h, Code/Framework/AzFramework/AzFramework/Physics/PhysicsScene.cpp, Code/Framework/AzFramework/AzFramework/Physics/PhysicsScene.h, Code/Framework/AzFramework/AzFramework/Physics/Shape.h, Gems/EMotionFX/Code/Tests/Mocks/PhysicsSystem.h, Gems/Multiplayer/Code/Tests/NetworkRigidBodyTests.cpp, Gems/PhysX/Code/Mocks/PhysX/MockPhysicsShape.h, Gems/PhysX/Code/Mocks/PhysX/MockSceneInterface.h, Gems/PhysX/Code/Source/Common/PhysXSceneQueryHelpers.cpp, Gems/PhysX/Code/Source/Common/PhysXSceneQueryHelpers.h, Gems/PhysX/Code/Source/Scene/PhysXScene.cpp, Gems/PhysX/Code/Source/Scene/PhysXScene.h, Gems/PhysX/Code/Source/Scene/PhysXSceneInterface.cpp, Gems/PhysX/Code/Source/Scene/PhysXSceneInterface.h, Gems/PhysX/Code/Source/Shape.cpp, Gems/PhysX/Code/Source/Shape.h, Gems/PhysX/Code/Tests/Benchmarks/PhysXSceneQueryBenchmarks.cpp, Gems/ScriptCanvasPhysics/Code/Tests/ScriptCanvasPhysicsTest.cpp
Scene queries optimization: Exposed `QueryScene` function doing no allocations + exposed Shape::GetMaterialId to prevent using `shared_ptr` in a performance critical code. 
Benchmark creating 32 threads running 1 million raycasts against 128 boxes, measuring overall execution time:
Before: 48583 ms 
After: 456 ms
CPU: AMD Ryzen Threadripper 3970X (32 cores)
Unit tests, benchmarks.
=> Scene queries optimization: Exposed QueryScene function doing no allocations

Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/GenericComboBoxCtrl.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/GenericComboBoxCtrl.inl, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyStringComboBoxCtrl.cpp, Gems/NvCloth/Code/Source/Editor/MeshNodeHandler.cpp, Gems/PhysX/Code/Editor/CollisionGroupWidget.cpp, Gems/PhysX/Code/Editor/CollisionLayerWidget.cpp
The custom widgets `CollisionLayerWidget`, `CollisionGroupWidget` and `MeshNodeHandler` were recently changed to indirectly inherit from `GenericComboBoxCtrl`. This created a bug where the widgets were trying to clear and re-add elements to the ComboBox but the values were not being re-added because they weren't being cleared from the values stored in the `GenericComboBoxCtrl`.
When the component changed the fields were cleared and not repopulated, this PR corrects the behavior of the elements being removed so that it can work as intended.
=> Bug Fix: Empty combo box on Component change

Gems/LmbrCentral/Code/include/LmbrCentral/Shape/ShapeComponentBus.h
Sets the shape translation offset feature to be on by default.
Extensive testing in the editor and addition of unit tests during feature development. 2 QA passes.
=> set shape translation offset feature flag to be on by default

cmake/Platform/Windows/Packaging/BootstrapperTheme.wxl.in
Display CPACK_PACKAGE_VERSION in the installer in all locations to be consistent, since this variable will be in the format that we want.
=> Make version numbers in Windows installer consistent

Code/Framework/AzCore/AzCore/Script/ScriptTimePoint.cpp
Fix the bug that method `ToString` of `ScriptTimePoint` cannot be used in scripts.
Test if method `ToString` of `ScriptTimePoint` can be used in scripts.
=> Fix bug of ScriptTimePoint ToString method.

Code/Editor/TrackView/SequenceBatchRenderDialog.cpp
4. Click Tools -> Render Output, and modify `File prefix`, such as `xxx1`.
5. Press `Start`, and wait for its ending.
The value of `File prefix` does not take effect as expected.
Follow the same steps, and check the filenames, as follows:
=> bugfix Render Output File name prefix is not usable.

Code/Legacy/CryCommon/Cry_Quat.h, Gems/Maestro/Code/Source/Cinematics/CompoundSplineTrack.cpp
5. Record a key frame, modify the rotation of the entity.
=> bugfix for inconsistent rotation calculation order.

Code/Editor/TrackView/TrackViewDialog.cpp
4. Add a director node, and some others.
5. Record two key frames at the director track, give camera to 1st frame, give none to 2nd frame.
6. Play.
1. Before the 1st key frame.
2. Between the two key frames.
3. After the 2nd key frame.
=> bugfix Active Camera doesn't take effect when playing.

Code/Framework/AzCore/AzCore/IO/Path/Path.cpp, Code/Framework/AzCore/AzCore/IO/Path/Path.h, Code/Framework/AzCore/AzCore/IO/Path/Path.inl, Code/Framework/AzCore/AzCore/IO/Path/PathParser.inl, Code/Framework/AzCore/AzCore/IO/Path/PathReflect.cpp, Code/Framework/AzCore/AzCore/RTTI/AzStdOnDemandReflection.inl, Code/Framework/AzCore/AzCore/RTTI/AzStdOnDemandReflectionLuaFunctions.inl, Code/Framework/AzCore/AzCore/RTTI/AzStdOnDemandReflectionSpecializations.cpp, Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.cpp, Code/Framework/AzCore/AzCore/Utils/Utils.cpp, Code/Framework/AzCore/AzCore/Utils/Utils.h, Code/Framework/AzCore/Tests/BehaviorContext.cpp, Code/Framework/AzCore/Tests/IO/Path/PathReflectTests.cpp, Code/Framework/AzCore/Tests/IO/Path/PathTests.cpp, Code/Framework/AzCore/Tests/Serialization.cpp, Code/Framework/AzCore/Tests/azcoretests_files.cmake, Gems/EditorPythonBindings/Code/Source/PythonMarshalComponent.cpp, Gems/EditorPythonBindings/Code/Source/PythonReflectionComponent.cpp
The AZ::IO::Path reflected functions model the python Pathlib API and use the same method names.
Added AsUri function and (StringAsUri/FixedAstringAsUri) functions to `AZ::IO::Path*` classes to allow a path to be encoded as a uri using the `file://` protocol
Other Changes:
* Moved the reflection for AZStd::string and AZStd::string_view to the AzStdOnDemandReflectionSpecializations.cpp file to reduce compilation time
* Added fixed_string<1024> BehaviorContext reflection also inside of the AzStdOnDemandReflectionSpecializations.cpp file
* Added a utility function for retriving a project's product folder for a platform and the project's log folder
Added UnitTest that validates the reflected AZ IO Path Scripting functions as well as the `AsUri` function
=> Adding proper BehaviorContext reflection of AZ Path

Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
Scripts canvas will report an error if file name start with a number，so need verification when saving scripts canvas file.
Test whether the file name start with number can be verified.
=> Add verification that script canvas filename cannot start with a number.

Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
According to the documentation, AutoComponent.xml files should use "Description" as the name of the field to use for descriptions:
https://www.o3de.org/docs/user-guide/networking/multiplayer/autocomponents/
However, the jinja file was looking for "Desc" instead, causing correctly-formatted AutoComponent.xml files to fail to generate descriptions in the generated components.
This changes the jinja file to look for "Description" so the descriptions show up.
Regenerated the files in MultiplayerSample and verified that the Description fields are now populated for the components. Spot-checked both the code and some of the tooltips in the Editor.
=> Fix descriptions on generated components.

AutomatedTesting/Gem/PythonTests/assetpipeline/TestSuite_Periodic.py, AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_batch_tests.py, AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_cache_server.py, AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_gui_tests.py, AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_gui_tests_2.py, AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_relocator_tests.py
- Updates conditional skips for several inaccurately skipped tests in the Asset Pipeline team's test suite
- Addresses feedback from https://github.com/o3de/o3de/pull/14569
- Running Periodic test suite on internal Jenkins
=> Updating conditional skips for several Asset Pipeline tests

Tools/LyTestTools/ly_test_tools/_internal/managers/artifact_manager.py, Tools/LyTestTools/tests/unit/test_artifact_manager.py
Adds exist_ok params to LTT artifact manager mkdir calls and also adds extra debug text when errors are caught.
Ran unit tests locally.
=> Fixes FileExistsError in LTT artifact manager

AutomatedTesting/Gem/PythonTests/editor/TestSuite_Main.py
- Adds "-NullRenderer" arg to specific test that intermittently crashes using "-rhi=Null"
- Ran updated test without issue
=> Updating commandline args for EntityOrdering test

Code/Editor/Core/LevelEditorMenuHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ActionBus.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.h
Migrated the Material Canvas & Material Editor main menu bar items to use the Action Manager
Built the editor, launched both tools with the menu option and with the key shortcut
=> Implemented MaterialEditor & Canvas menu items with ActionManager

AutomatedTesting/Levels/Physics/Collider_PxMeshErrorIfNoMesh/Collider_PxMeshErrorIfNoMesh.prefab, AutomatedTesting/Levels/Physics/ForceRegion_ImpulsesPxMeshShapedRigidBody/ForceRegion_ImpulsesPxMeshShapedRigidBody.prefab, AutomatedTesting/Levels/Physics/ForceRegion_PxMeshShapedForce/ForceRegion_PxMeshShapedForce.prefab, AutomatedTesting/Levels/Physics/Joints_Ball2BodiesConstrained/Joints_Ball2BodiesConstrained.prefab, AutomatedTesting/Levels/Physics/Joints_BallBreakable/Joints_BallBreakable.prefab, AutomatedTesting/Levels/Physics/Joints_BallNoLimitsConstrained/Joints_BallNoLimitsConstrained.prefab, AutomatedTesting/Levels/Physics/Joints_Fixed2BodiesConstrained/Joints_Fixed2BodiesConstrained.prefab, AutomatedTesting/Levels/Physics/Joints_FixedBreakable/Joints_FixedBreakable.prefab, AutomatedTesting/Levels/Physics/Joints_Hinge2BodiesConstrained/Joints_Hinge2BodiesConstrained.prefab, AutomatedTesting/Levels/Physics/Joints_HingeBreakable/Joints_HingeBreakable.prefab, AutomatedTesting/Levels/Physics/Material_NoEffectIfNoColliderShape/Material_NoEffectIfNoColliderShape.prefab, AutomatedTesting/Levels/Physics/Material_PerFaceMaterialGetsCorrectMaterial/Material_PerFaceMaterialGetsCorrectMaterial.prefab, AutomatedTesting/Levels/Physics/Physics_WorldBodyBusWorksOnEditorComponents/Physics_WorldBodyBusWorksOnEditorComponents.prefab, AutomatedTesting/Levels/Physics/RigidBody_COM_ComputingWorks/RigidBody_COM_ComputingWorks.prefab, AutomatedTesting/Levels/Prefab/PrefabLevel_OpensLevelWithEntities/PrefabLevel_OpensLevelWithEntities.prefab
**Note**
This is part of the work to separate PhysX Collider into 2 components: https://github.com/o3de/o3de/pull/14725. Merging into the staging branch `MeshColliderComponent_Staging`.
=> Updated prefabs in AutomatedTesting by running 'ed_physxUpdatePrefabsWithColliderComponents' command

Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BreadCrumbs.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BreadCrumbs.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
- Allows users to paste full file paths from file explorer and have the asset browser navigate to the correct directory
- Display the full file path when editing the URL, allowing users to copy the full file path
- Fixes #14431.
Locally
=> Allow editable breadcrumbs to use and display full file paths

Gems/Atom/Feature/Common/Assets/Materials/Pipelines/Common/TransparentPassVertexAndPixel.azsli, Gems/Atom/Feature/Common/Assets/Materials/Pipelines/MainPipeline/ForwardPassVertexAndPixel.azsli, Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/EmissivePropertyGroup.json, Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lighting/LightingData.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Surfaces/StandardSurface.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/EnhancedPBR/EnhancedPBR_SurfaceEval.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/EmissiveInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/StandardPBR/StandardPBR_SurfaceEval.azsli
Moved the emissive contribution out of LightingData and into the individual VertexAndPixel shaders (its usage was inconsistent before). Emissive is now added onto diffuse instead of specular. 
Added a new slider to the emissive section of materials to control how much the alpha should affect the emissive contribution.
Tested with atom sample viewer (in progess) and custom materials in the material editor.
=> Fixing emissive to work with alpha. 

Gems/Atom/Feature/Common/Assets/seedList.seed
Another diffuse raytracing shader was discovered to be missing from the seed list. Added.
Built MPS with pak files and verified that it ran without asserting and crashing from missing shaders.
=> Add missing shader to seed list

AutomatedTesting/Gem/PythonTests/Prefab/CMakeLists.txt, AutomatedTesting/Gem/PythonTests/Prefab/LauncherTestSuite_Periodic.py, AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_DPEOverrides.py, AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Main.py
- Duplicates non-override related tests to also run in the Periodic Pipeline with DPE/Inspector Overrides enabled
- Ran new suite without issue
=> Enabling set of tests to also run against DPE/Inspector Overrides in Periodic Pipeline

Code/Editor/TrackView/SequenceBatchRenderDialog.cpp
* Save `image format` and `debuginfo` to batch files.
* Load `image format` and `debuginfo` from batch files. 
5. Click Tools -> Render Output, Add a batch.
6. Click `Save Batch...`, and check the batch file.
=> bugfix image format and debuginfo cannot save and load from batch files.

Code/Framework/AzQtComponents/AzQtComponents/Components/ToastNotificationConfiguration.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/Notifications/ToastNotificationsView.cpp, Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/GraphCanvasGraphicsView/GraphCanvasGraphicsView.cpp
This PR adds a toast notification when a user screenshots using the screenshot button. This addresses https://github.com/o3de/o3de/issues/14722. The issue also mentioned a window that would display for a tick, but this change seems to stop that aswell.
https://user-images.githubusercontent.com/105638312/220892649-639ba050-09bb-475f-9ef7-b6ee8a89ddd0.mp4
The toast notifications were tested in script and material canvas.
=> Add a toast notification for Script and Material canvas

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
Increases the number of maximum used pass-slots of the same type (Input/InputOutput/Output) from 16 to 32.
The total limit of slots per pass stays unchanged.
Used with a pass with ~20 input/output slots.
=> increase the number of max Input/InputOutput/Output - Bindings to 32

Code/Editor/Core/EditorActionsHandler.cpp
Refactors EditorActionsHandler::UpdateRecentFileActions to only check a file's validity when the index is in bounds, preventing a crash.
Verified the crash no longer occurs locally.
=> Action Manager | Refactor EditorActionsHandler::UpdateRecentFileActions to prevent crash.

Gems/AWSGameLift/Code/AWSGameLiftClient/Source/AWSGameLiftClientSystemComponent.cpp, Gems/AWSGameLift/Code/AWSGameLiftClient/Source/AWSGameLiftClientSystemComponent.h
Moved some includes from the source file to header to fix some compile issues with `unique_ptr` expecting the complete type instead of just a forward declaration.
=> Moved includes to fix unique_ptr compile issue

Gems/Atom/Feature/Common/Code/Source/CoreLights/PolygonLightFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/CoreLights/PolygonLightFeatureProcessor.h
Adds an interface to get the polygon point buffer of a polygon light. This is useful for some custom Gems that needs the polygon light point information.
Using a custom gem calling this function to get the buffer, and set to another shader resource group, and access it in the shader.
=> Introduce an interface to get the polygon point buffer of polygon light.

Gems/Atom/Feature/Common/Code/Source/PostProcessing/TaaPass.cpp, Gems/Atom/Feature/Common/Code/Source/PostProcessing/TaaPass.h
Changes the checks if the Attachments of the TAA - pass are valid. Currently wrong attachments lead to a crash, which makes debugging the actual cause somewhat difficult.
Used with a custom render-pipeline, where the SizeSource - Slot for the TAA - images was connected, but had no actual attachment.
=> avoid a crash if the input-image for the TAA pass has no attachment

Gems/Atom/Feature/Common/Assets/Passes/BloomDownsample.pass, Gems/Atom/Feature/Common/Assets/Passes/KawaseShadowBlur.pass, Gems/Atom/Feature/Common/Assets/Passes/SubsurfaceScattering.pass, Gems/Atom/Feature/Common/Assets/Passes/Taa.pass, Gems/Atom/Feature/Common/Assets/Passes/UIParent.pass
Changes a few values in the json templates so they are somewhat more future proof, and stick to the case convention as in the Reflect - functions. Mostly this makes parsing the templates by an external script a bit easier.
Display a basic scene. The PR didn't introduce any functional difference.
=> make hand-written pass-templates more consistent with json serialization

AutomatedTesting/Gem/Code/Source/AutomatedTestingSystemComponent.cpp, Gems/AWSClientAuth/Code/Source/AWSClientAuthEditorSystemComponent.cpp, Gems/AWSGameLift/Code/AWSGameLiftClient/Source/AWSGameLiftClientEditorSystemComponent.cpp, Gems/AWSMetrics/Code/Source/AWSMetricsEditorSystemComponent.cpp, Gems/AudioEngineWwise/Code/Source/AudioEngineWwiseGemSystemComponent.cpp, Gems/Meshlets/Code/Source/MeshletsSystemComponent.cpp, Templates/CppToolGem/Template/Code/Source/Clients/${Name}SystemComponent.cpp, Templates/DefaultGem/Template/Code/Source/Clients/${Name}SystemComponent.cpp, Templates/DefaultProject/Template/Gem/Source/${Name}SystemComponent.cpp, Templates/MinimalProject/Template/Gem/Source/${Name}SystemComponent.cpp, Templates/UnifiedMultiplayerGem/Template/Code/Source/Unified/${Name}SystemComponent.cpp
This attribute is deprecated
Removes more instances of "system" component attrib
https://github.com/o3de/o3de/pull/14791/
configured and built
=> remove additional uses of "system" attrib

Gems/PhysX/Code/Editor/Source/Components/Conversion/CollidersPrefabConversion.cpp
**Note**
This is part of the work to separate PhysX Collider into 2 components: https://github.com/o3de/o3de/pull/14725. Merging into the staging branch `MeshColliderComponent_Staging`.
Command 'ed_physxUpdatePrefabsWithColliderComponents' now also updates all prefabs in a project by detecting PhysX Colliders using physics assets and converting them into PhysX Mesh Colliders.
Deprecation GHI (https://github.com/o3de/o3de/issues/14718)
Used the command to update all the prefabs in AutomatedTesting project and it worked as expected: https://github.com/o3de/o3de/pull/14730
=> Command 'ed_physxUpdatePrefabsWithColliderComponents' update

Gems/PhysX/Code/Source/PhysXCharacters/Components/CharacterGameplayComponent.cpp, Gems/PhysX/Code/Source/PhysXCharacters/Components/CharacterGameplayComponent.h
Removes the caching behaviour for IsOnGround queries on the character gameplay controller component. The caching was intended to avoid the expense of scene queries, but can lead to incorrect results if the controller or other physics bodies move outside the physics update.
Unit tests and manual testing in the editor.
=> remove caching for IsOnGround result

scripts/o3de/o3de/register.py
Reverts some code changed in https://github.com/o3de/o3de/pull/14270 that required each engine to be registered in `o3de_manifest.json` in an `engines_path` dictionary.
Older projects rely on this key to find the engine, so users were confused when they installed o3de from dev but their project's failed to find the engine.
This change:
1. registers the engine in the `engines_path` dictionary in the `o3de_manifest.json` if no entry exists
2. prints a warning instead of an error if a different engine is already registered with the engine name in `engines_path` 
Example:
```
$ scripts/o3de.bat register --this-engine
[INFO] o3de.register: Engine successfully registered.
[WARNING] o3de.register: Important notice regarding older projects created with engine version 22.10 or earlier:
An engine …
```
=> Register sets engines_path for older projects

Code/Legacy/CrySystem/CMakeLists.txt, Code/Legacy/CrySystem/XML/XmlUtils.cpp, Gems/Atom/RHI/Code/CMakeLists.txt, Gems/Atom/RHI/Code/Include/Atom/RHI.Edit/Utils.h, Gems/Atom/RHI/Code/Source/RHI.Edit/Utils.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI.Builders/ShaderPlatformInterface.cpp, cmake/3rdParty/Platform/Android/BuiltInPackages_android.cmake, cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake, cmake/3rdParty/Platform/Mac/BuiltInPackages_mac.cmake, cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake, cmake/3rdParty/Platform/iOS/BuiltInPackages_ios.cmake
Removes dependency on the MD5 3rd Party package and replaces the only usage of MD5 to use SHA1 as a digest algorithm instead.
Built and ran AP on Linux and WIndows
Ran internal jenkins validation jobs
=> Remove dependencies on md5

Gems/AWSClientAuth/Code/Source/AWSClientAuthEditorSystemComponent.cpp, Gems/AWSClientAuth/Code/Source/AWSClientAuthEditorSystemComponent.h, Gems/AWSGameLift/Code/AWSGameLiftClient/Source/AWSGameLiftClientEditorSystemComponent.cpp, Gems/AWSGameLift/Code/AWSGameLiftClient/Source/AWSGameLiftClientEditorSystemComponent.h, Gems/AWSMetrics/Code/Source/AWSMetricsEditorSystemComponent.cpp, Gems/AWSMetrics/Code/Source/AWSMetricsEditorSystemComponent.h
Fixed issue with the new AWS gem editor system components deriving from their base editor system components, which was causing asserts due to the base system components getting registered twice, and activated twice (that was causing internal buses from being connected to twice).
Built/ran all AWS unit tests and verified they pass. Built/ran the Editor and verified there are no asserts and the AWS gem menus still appear/work as expected.
=> Fixed AWS editor system components to not register the base components twice

Code/Editor/Core/EditorActionsHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManager.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManager.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManagerInterface.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.h
Restore the `Lua Editor` menu item in the Tools menu.
Took the chance to apply some minor refactorings:
- Split action and menu binding definitions for the Material Editor into separate hooks;
- Added an API call to generate a sort key for an action given its identifier, which can be used to sort alphabetically.
I preferred introducing an API call for this purpose as it makes the call opaque, giving us the chance to change it down the line if we need more granularity, and it makes it easier to expose to Python or other purposes.
Tested locally, menu item now appears in the menu.
Before
After
=> Action Manager | Restore Lua Editor as an item in the Tools Menu (+ minor refactoring)

AutomatedTesting/Editor/Scripts/scene_mesh_to_prefab.py, AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/editor_component/editor_physx_mesh_collider.py, AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_MultipleSurfaceSlots.py, AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_PxMeshAutoAssignedWhenAddingRenderMeshComponent.py, AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_PxMeshAutoAssignedWhenModifyingRenderMeshComponent.py, AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_PxMeshConvexMeshCollides.py, AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_PxMeshNotAutoAssignedWhenNoPhysicsFbx.py, AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/PhysXColliderSurfaceTagEmitter_E2E_Editor.py, AutomatedTesting/Gem/PythonTests/largeworlds/large_worlds_utils/editor_dynveg_test_helper.py, Gems/PhysX/Code/Editor/DebugDraw.cpp, Gems/PhysX/Code/Editor/DebugDraw.h, Gems/PhysX/Code/Editor/Source/Components/Conversion/CollidersPrefabConversion.cpp, Gems/PhysX/Code/Source/EditorColliderComponent.cpp, Gems/PhysX/Code/Source/EditorColliderComponent.h, Gems/PhysX/Code/Source/EditorMeshColliderComponent.cpp, Gems/PhysX/Code/Source/EditorMeshColliderComponent.h, Gems/PhysX/Code/Source/EditorRigidBodyComponent.cpp
This is to simplify the transition from old PhysX Colliders and not having to update the property paths on prefabs' patches or python scripts.
Reverted the property paths to PhysX Mesh Collider's properties on python scripts since now it matches the same as before (one less change to do to adapt to PhysX Mesh Colliders).
Exposed collider debug draw display flag so it can be queried when converting from PhysX Collider to PhysX Mesh Collider.
Tested converting prefabs on complex levels (like MultiplayerSample and loft scene) with `ed_physxUpdatePrefabsWithColliderComponents` and no prefab patching warnings appear anymore after the conversion.
=> Change Physics Asset serialization in Editor Mesh Collider to match the same property paths than previously.

Gems/Atom/RPI/Code/Source/RPI.Public/Image/StreamingImageController.cpp
If the set of loaded images have varying numbers of mipmaps, the previous logic wouldn't evict as many mipmaps as it could, because it would stop at the first failure case. For example, if 10 textures have 1 mipmap and 2 textures have 5 mipmaps, it will evict one mipmap from each of those 2 textures, put them at the front of the list, and then stop evicting because it will check a texture with 1 mipmap. With this change, it will keep searching and evict 4 mipmaps from those 2 textures, freeing more memory before failing.
Ran MultiplayerSample (which uses ~2.5 GB of streaming images) with a budget of 1 GB.
Before (multiple allocation failure warnings and texture corruption):
After (no allocation failure warnings, no texture corruption):
=> Improves mipmap eviction for streaming images

Code/Framework/AzCore/AzCore/Preprocessor/Enum.h
Previously a trailing comma used in the AZ_ENUM macro was treated as another enum entry resulting in preprocessor macro expansion errors.
Successfully built a cpp file using the following AZ_ENUM_CLASS macro with a trailing comma.
```c++
AZ_ENUM_CLASS(
SoundEffect,
// Player Sounds
PlayerFootSteps,
PlayerExertion,
PlayerKnockedDown,
ArmorBreaking,
ArmorMend,
PlayerOuch,
LadderClimb,
ShutDown,
// Game Event Sounds
CountDown,
GemPickup,
VictoryFanfare,
LosingFanfare,
RoundStart,
RoundEnd,
GameEnd,
// Laser Pistol
LaserPistolMuzzleFlash,
LaserPistolImpact,
// Bubble Gun
BubbleGunBuildup,
BubbleGunMuzzleFlash,
BubbleGunProjectile,
BubbleGunImpact,
// Jump Pad
JumpPadLaunch,
// Energy Ball Trap
EnergyBallTrapRisingOutOfTheGround,
EnergyBallTrapBuildup, // followed by muzzle flash …
```
=> Added support to the AZ_ENUM* macros to support a trailing comma

Code/Framework/AzCore/AzCore/RTTI/AzStdOnDemandReflection.inl, Code/Framework/AzCore/AzCore/RTTI/BehaviorClassBuilder.cpp, Code/Framework/AzCore/AzCore/RTTI/BehaviorClassBuilder.inl, Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.cpp, Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.h, Code/Framework/AzCore/AzCore/RTTI/BehaviorEBusBuilder.cpp, Code/Framework/AzCore/AzCore/RTTI/BehaviorEBusBuilder.inl, Code/Framework/AzCore/AzCore/RTTI/BehaviorEBusEvent.cpp, Code/Framework/AzCore/AzCore/RTTI/BehaviorEBusEvent.inl, Code/Framework/AzCore/AzCore/RTTI/BehaviorEBusHandler.cpp, Code/Framework/AzCore/AzCore/RTTI/BehaviorEBusHandler.inl, Code/Framework/AzCore/AzCore/RTTI/BehaviorMethodImpl.cpp, Code/Framework/AzCore/AzCore/RTTI/BehaviorMethodImpl.inl, Code/Framework/AzCore/AzCore/RTTI/BehaviorObjectSignals.h, Code/Framework/AzCore/AzCore/Script/ScriptContext.cpp, Code/Framework/AzCore/AzCore/azcore_files.cmake, Code/Framework/AzCore/AzCore/std/typetraits/function_traits.h, Gems/Achievements/Code/Source/AchievementsSystemComponent.cpp, Gems/EditorPythonBindings/Code/Source/PythonProxyObject.cpp, Gems/Presence/Code/Source/PresenceSystemComponent.cpp, Gems/ScriptEvents/Code/Include/ScriptEvents/Internal/BehaviorContextBinding/BehaviorContextFactoryMethods.h, Gems/ScriptEvents/Code/Include/ScriptEvents/Internal/BehaviorContextBinding/ScriptEventBroadcast.cpp, Gems/ScriptEvents/Code/Include/ScriptEvents/Internal/BehaviorContextBinding/ScriptEventBroadcast.h, Gems/ScriptEvents/Code/Include/ScriptEvents/Internal/BehaviorContextBinding/ScriptEventMethod.cpp, Gems/ScriptEvents/Code/Include/ScriptEvents/Internal/BehaviorContextBinding/ScriptEventMethod.h
Any inline functions or classes that didn't need to be templated in the BehaviorContext were moved to a cpp file. The BehaviorArgument and BehaviorObject inline functions have been moved to the BehaviorContext.cpp file
The BehaviorMethodImpl class is no longer templated and it's member functions have been moved to a new BehaviorMethodImpl.cpp file The constructor functions are still templated as they need to access the function signature of the method being wrapped. These functions have been moved to the BehaviorMethod.inl file
The BehaviorEBusEvent class is also no longer templated and has undergone the same transformation as the BehaviorMethodImpl. Its non-templated functions have been moved to the BehaviorEBusEvent.cpp file, while it's constructors have been relocated to the …
=> BehaviorContext compile time improvements refactor

Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipService.cpp
When exiting game mode, spawned entities are queued to despawn, but the spawnable queue is processed on the next tick. This caused some batched automated tests to fail because game entities remained active for a frame while the next test ran.
Tested entering and exiting game mode in Editor. Also ran the tests that were previously failing to make sure they don't fail anymore. Since this is an intermittent failure, I originally ran the tests 100x and saw the failure after about 30 tries. After the fix, the test passed 100x.
Command used for testing:
<project path>\build\windows_vs2019>ctest -C profile -R AutomatedTesting::PrefabTests_Periodic --output-on-failure --repeat until-fail:100
=> Despawn entities right away when exiting game mode

Code/Framework/AzCore/AzCore/Script/ScriptProperty.cpp, Code/Framework/AzCore/AzCore/Script/ScriptProperty.h
The ScriptPropertyBoolean, ScriptPropertyNumber and ScriptPropertyGenericClass types are serialized with type name of "AzFramework::ScriptPropertyBoolean",
"AzFramework::ScriptPropertyNumber" and
"AzFramework::ScriptPropertyGenericClass" in *.prefab and *.scriptcanvas JSON serialized files.
fixes #14910
Validated a prefab file that contained an "AzFramework::ScriptPropertyBoolean" deserialized correctly.
=> Fixed the loading of ScriptProperty types that were serialized using an older typename in JSON Serialization files.

Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/HandleCastShadows.lua, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/HandleCastShadows.lua, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/HandleOpacityDoubleSided.lua, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/HandleOpacityMode.lua, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/HandleShaderEnable.lua
Updated base PBR and standard PBR lua scripts that come with material canvas to handle missing shader options. This should only occur when opening the material graph template materials and material types directly, since the options are only added to materials generated from them. The lua functor API should be updated to have default values passed in as a second parameter when reading options and properties.
Resolves https://github.com/o3de/o3de/issues/14800
Opened base and standard PBR material graph template materials in the material editor without errors.
Created new materials from material canvas and opened those without errors.
Confirmed that options still behave correctly when toggling them on generated materials.
=> Material Canvas: Updated lua scripts to check for missing options before reading them

Code/Tools/TestImpactFramework/Runtime/Common/Code/Source/Process/JobRunner/TestImpactProcessJobMeta.cpp, Code/Tools/TestImpactFramework/Runtime/Common/Code/Source/TestRunner/Common/Job/TestImpactTestJobInfoUtils.cpp, Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/Target/Native/TestImpactNativeTargetListCompiler.cpp, Code/Tools/TestImpactFramework/Runtime/Python/Code/Source/Target/Python/TestImpactPythonTargetListCompiler.cpp, Code/Tools/TestImpactFramework/Runtime/Python/Code/Source/TestRunner/Python/TestImpactPythonInstrumentedNullTestRunner.cpp, Code/Tools/TestImpactFramework/Runtime/Python/Code/Source/TestRunner/Python/TestImpactPythonInstrumentedTestRunnerBase.cpp, Code/Tools/TestImpactFramework/Runtime/Python/Code/Source/TestRunner/Python/TestImpactPythonRegularNullTestRunner.cpp, Code/Tools/TestImpactFramework/Runtime/Python/Code/Source/TestRunner/Python/TestImpactPythonRegularTestRunnerBase.cpp, Gems/Meshlets/Code/Source/Meshlets/MeshletsAssets.cpp
The TestImpactAnalysisFramework files contains `#pragma once` directives resulting in an error
```
D:/o3de/o3de/Code/Tools/TestImpactFramework/Runtime/Common/Code/Source/TestRunner/Common/Job/TestImpactTestJobInfoUtils.cpp:9:9:
error: #pragma once in main file [-Werror,-Wpragma-once-outside-header]
```
=> Windows clang non-unity fix

Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/Debug/Trace_UnixLike.cpp, Code/Framework/AzToolsFramework/Tests/EntityOwnershipService/SliceEntityOwnershipTests.cpp
This fixes an issue on linux where the detection of a debugger being attached is always reporting 'true' whether or not one is attached at all. The original logic relied on only checking for the space character, but on ubuntu, it was a tab character before the pid.
Added temporary trace logs to show results for `IsDebuggerPresent` with and without a debugger (lldb) attached.
=> Fix parsing of 'TracerPid' ID to account for spaces AND tabs before the number

Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp, Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h, Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
Update AP Gui settings logic to take command line arguments into account instead of overriding them.
Previously AP gui settings would only follow what is set in the registry and override any setting specified on the command line.  This change allows command line settings to enable a setting and override previous GUI settings
Manually ran AP with various combinations of GUI and command line settings
=> Asset Processor - AP Gui settings take command line into account

Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/Debug/Trace_UnixLike.cpp
Fixes a unity-build related issue on android
Built on Linux with non-unity
=> Add missing #include for std::isspace

Gems/Atom/RHI/Metal/Code/Source/RHI/Memory.h
Fixed the type name in the MetalResource class to supply its type to its AZ_RTTI macro call
Built Editor target successfully on MacOS
=> Corrected typename for MetalResource typename for Metal RHI

Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp, Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp
Because StopEntity() was only getting called in the RemoveEntities() flow, it was possible for it to skip getting called when destroying entities in other ways, such as through `AzFramework::SpawnableEntitiesInterface::Get()->DespawnAllEntities(ticket);` .
By moving the call into the NetBindComponent::OnDeactivate(), we can ensure that it is always called as a part of entity destruction. Also, by moving the call, the cvar is no longer necessary for detecting that we've forgotten to call StopEntity().
Addresses #7462 .
Ran the Multiplayer Sample and verified that gem despawning worked correctly.
=> Move StopEntity() into the NetBindComponent Deactivate()

Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Specific/DownsampleSinglePassLuminancePass.cpp
Fixes a release compilation error due to a variable being unused because it is only used during an `AZ_Assert`.
N/A
Confirmed I could successfully compile on Linux: `cmake --build build/linux_mono --target install --config release`
=> Fix release compilation due to unused variable

Code/Framework/AzFramework/AzFramework/Physics/Configuration/RigidBodyConfiguration.cpp
Fix the following warning when building with clang-cl shipped with VS2022.
```
error : parameter 'flags' set but not used [-Werror,-Wunused-but-set-parameter]
```
The I found that the whole function is not used.
Rebuild o3de using VS2022 cl and clang-cl.
=> Remove unused function SetPropertyVisibility.

Gems/Atom/RHI/Code/Include/Atom/RHI/AliasedAttachmentAllocator.h, Gems/Atom/RHI/Code/Source/RHI/ResourcePool.cpp, Gems/Atom/RHI/Code/Source/RHI/StreamingImagePool.cpp, Gems/Atom/RHI/Code/Source/RHI/SwapChain.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Buffer/BufferPool.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/GpuQuery/QueryPool.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Image/AttachmentImagePool.cpp, Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiGpuProfiler.h, Gems/Atom/Utils/Code/Source/ImGuiGpuProfiler.cpp, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.cpp
Change the gpu memory profiler data save format to JSON. Existing CSV data can still be loaded.
This allows us to store the exact pool data rather than approximating it from the allocated buffers.
Additionally all current pools should be named.
=> imgui gpu memory profiler improvements

Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ComponentEditor.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ComponentEditor.hxx, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp
Move the "ed_enableDPE" registry flag check from ComponentEditor to EntityPropertyEditor because not all tools that use the ComponentEditor class are compatible with the DocumentPropertyEditor.
Also set up a way to hook up a custom component adapter to the ComponentEditor to accompany PR https://github.com/o3de/o3de/pull/14917 which creates a custom prefab component adapter.
Tested the Editor's inspector and the UI Editor's properties pane to ensure functionality is as expected. Tested with DPE enabled and disabled.
=> Add constructor params to customize component editor with dpe/adapter

Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Graph/GraphDocumentView.h, Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Window/AtomToolsMainWindow.h, Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/GraphDocumentView.cpp, Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp, Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp, Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp, Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.h, Gems/Atom/Tools/PassCanvas/Code/Source/PassCanvasApplication.cpp, Gems/Atom/Tools/PassCanvas/Code/Source/Window/PassCanvasMainWindow.cpp, Gems/Atom/Tools/PassCanvas/Code/Source/Window/PassCanvasMainWindow.h
This change adds handlers and notifications for graph view settings changes that cause the graph to refresh.
Resolves https://github.com/o3de/o3de/issues/13559
Confirmed graph view visibly updates after curve type settings changes
=> Material Canvas: Refresh graph view after settings change

Gems/PhysX/Code/Source/EditorMeshColliderComponent.cpp, Gems/PhysX/Code/Source/EditorMeshColliderComponent.h
Show in the Asset property of PhysX Mesh Collider the type of shape the asset contains.
No Asset:
Primitive:
Convex:
Triangle Mesh:
Manually tested in the editor assigning all the different types of PhysX Assets.
=> Show in the Asset property of PhysX Mesh Collider the type of shape the asset contains

Code/Framework/AzFramework/AzFramework/Physics/ShapeConfiguration.h, Gems/PhysX/Code/Source/EditorColliderComponent.h, Gems/PhysX/Code/Tests/ColliderScalingTests.cpp, Gems/PhysX/Code/Tests/DebugDrawTests.cpp, Gems/PhysX/Code/Tests/EditorColliderComponentTests.cpp, Gems/PhysX/Code/Tests/EditorMeshColliderComponentTests.cpp, Gems/PhysX/Code/Tests/EditorShapeColliderComponentTests.cpp, Gems/PhysX/Code/Tests/EditorTestUtilities.cpp, Gems/PhysX/Code/Tests/EditorTestUtilities.h, Gems/PhysX/Code/Tests/TestColliderComponent.h
Also unified arguments of helper functions that create editor colliders (primitive, mesh, shape).
PhysX gem unit tests pass.
=> Added unit tests to cover non-uniform scale in mesh colliders.

Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ActionManagerSystemComponent.cpp
When the ActionManagerSystemComponent is loaded in an Application that hasn't create a QGUIApplication, it asserts when a QWidget is created with the message
> QWidget: Must construct a QApplication before a QWidget
The fix is to avoid creating the QWidget if there is no QApplication.
Side Note: We should investigate why the ActionManagerSystemComponent is creating a QWidget. It is the only SystemComponent that creates a QT GUI Object.
Successfully loaded activated all the active AutomatedTesting SystemComponents when using loading the Editor gem modules in `SerializeContextTools` application.
The command used were as follows
```
<build-dir>/bin/debug/SerializeContextTools.exe convert --project-path=<engine-root>/AutomatedTesting --specializations=editor …
```
=> Fixed assert in the ActionManagerSystemComponent::Init

Gems/PhysX/Code/Include/PhysX/EditorColliderComponentRequestBus.h, Gems/PhysX/Code/Source/EditorColliderComponent.cpp, Gems/PhysX/Code/Source/EditorColliderComponent.h, Gems/PhysX/Code/Tests/EditorColliderComponentTests.cpp, Gems/PhysX/Code/Tests/EditorTestUtilities.cpp, Gems/PhysX/Code/Tests/TestColliderComponent.h
`EditorPrimitiveColliderComponentRequests` had functions to set the parameters of all the shapes except for box. Before code was using `BoxManipulatorRequestBus` to get/set the box dimensions, which is more appropriate to handle as manipulator rather to set the shape dimentions.
Changed the test code of Editor Primitive Collider component to use the new functions in `EditorPrimitiveColliderComponentRequests` bus.
Run the Editor PhysX tests and it passes.
=> Add box dimensions setter/getter to EditorPrimitiveColliderComponentRequests

Gems/Multiplayer/Code/Include/Multiplayer/NetworkEntity/INetworkEntityManager.h, Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp, Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp, Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.h, Gems/Multiplayer/Code/Tests/CommonBenchmarkSetup.h, Gems/Multiplayer/Code/Tests/MockInterfaces.h
A previous recent change to the NetBind component made it so that networked prefabs could be despawned just by calling DespawnAllEntities. However, by going through that API instead of the NetworkEntityManager API, this caused a tracking leak where the networked entities still had entries in a network entity table.
This PR fixes the leak by having the NetBind component remove its entity from the tracking table.
Ran MPS and printed out the tracked network entity counts to verify they no longer kept growing on every round. No other obvious errors or warnings from the change showed up as a result either.
=> NetBind component now removes its entity from network tracking on Deactivate

Gems/PhysX/Code/Source/EditorBallJointComponent.cpp, Gems/PhysX/Code/Source/EditorHingeJointComponent.cpp, Gems/PhysX/Code/Source/EditorPrismaticJointComponent.cpp
Previously, if you zoom in far enough the physics joint visuals would cover the entire screen unlike the rest of the gizmos and visualizations.
This change causes the visualizers to remain the same size on screen regardless of your zoom.
This also adds a different visualizer for the revolving joint (the hinge joint with no limits).  I made sure that adding rotation in the positive direction caused the body to rotate in the direction the arrows indicate.
Manually, by viewing the gizmos at various scales.
Hinge Joint with no limit
Hinge joint with limit
The rest are unchanged, except that they remain a constant size on screen regardless of whether you zoom in or out.
=> Makes the visuals of physics joint scale as you zoom

scripts/commit_validation/commit_validation/validators/generated_files_validator.py
Removes the `.meta` extension from the generated files validator. This generally only is created within the build folder by Visual Studio, which is already in `.gitignore`. This extension is being used by the metadata manager in AzToolsFramework here: https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/Metadata/MetadataManager.h#L81
This is preventing commits of its files for tests: https://github.com/o3de/o3de/pull/14931
Alternatively, we can have instructions to move test assets to an exclusion list, found here: https://github.com/o3de/o3de/blob/development/scripts/commit_validation/commit_validation/commit_validation.py#L171
Run in a sandbox Jenkins
=> Remove .meta extension from the validator list

Code/Framework/AzFramework/AzFramework/Physics/Shape.cpp, Code/Framework/AzFramework/AzFramework/Physics/Shape.h
Show the 'Is Simulated' option as disabled when the collider is acting as a trigger,  this way it'll be clear that when the collider is a trigger it won't be simulated.
Checked 'Is Simulated' appears disabled when 'Is Trigger' is enabled in Primitive, Mesh and Shape collider components.
=> Show the 'Is Simulated' option as disabled when the collider is acting as a trigger.

Gems/AtomLyIntegration/CommonFeatures/Code/Tests/EditorAreaLightComponentTests.cpp, Gems/LmbrCentral/Code/Source/LmbrCentralEditor.cpp, Gems/LmbrCentral/Code/Source/Shape/BoxShape.cpp, Gems/LmbrCentral/Code/Source/Shape/BoxShapeComponent.cpp, Gems/LmbrCentral/Code/Source/Shape/CapsuleShape.cpp, Gems/LmbrCentral/Code/Source/Shape/CapsuleShapeComponent.cpp, Gems/LmbrCentral/Code/Source/Shape/EditorAxisAlignedBoxShapeComponent.cpp, Gems/LmbrCentral/Code/Source/Shape/EditorBoxShapeComponent.cpp, Gems/LmbrCentral/Code/Source/Shape/EditorCapsuleShapeComponent.cpp, Gems/LmbrCentral/Code/Source/Shape/EditorSphereShapeComponent.cpp, Gems/LmbrCentral/Code/Source/Shape/SphereShape.cpp, Gems/LmbrCentral/Code/Source/Shape/SphereShapeComponent.cpp, Gems/LmbrCentral/Code/Tests/AxisAlignedBoxShapeTest.cpp, Gems/LmbrCentral/Code/Tests/BoxShapeTest.cpp, Gems/LmbrCentral/Code/Tests/CapsuleShapeTest.cpp, Gems/LmbrCentral/Code/Tests/EditorAxisAlignedBoxShapeComponentTests.cpp, Gems/LmbrCentral/Code/Tests/EditorBoxShapeComponentTests.cpp, Gems/LmbrCentral/Code/Tests/EditorCapsuleShapeComponentTests.cpp, Gems/LmbrCentral/Code/Tests/EditorSphereShapeComponentTests.cpp, Gems/LmbrCentral/Code/Tests/SphereShapeTest.cpp, Gems/LmbrCentral/Code/include/LmbrCentral/Shape/ShapeComponentBus.h, Gems/PhysX/Code/Tests/EditorTestUtilities.cpp, Gems/PhysX/Code/Tests/EditorTestUtilities.h
Removes the feature flag for the shape translation offset feature. The flag was set to on by default on 21st February, and no new issues have surfaced since then, so now the flag is being removed altogether.
Built editor, ran relevant unit tests.
=> remove feature flag for shape component translation offset

AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_02.py, AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Sandbox.py
This PR moves the AtomEditorComponents_GlobalSkylightIBLAdded test to the sandbox suite as we cannot reproduce the error identified in https://github.com/o3de/o3de/issues/14580 locally so believe it may be a local issue with the AR machines.
For this reason, we are going to move it to the sandbox suite and monitor for intermittent failures there instead of try to reproduce locally.
Tests are only being moved between suites, so no new testing is required to verify the changes.
=> Move AtomEditorComponents_GlobalSkylightIBLAdded test to sandbox suite.

Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetSelection/AssetSelectionComboBox.cpp, Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetSelection/AssetSelectionGrid.cpp
Updating asset selection combo box and grid classes to append a unique suffix on to entries with the same display name. In addition to that, tooltips were also added showing the absolute path to the file being referenced.
Resolves https://github.com/o3de/o3de/issues/13507
Confirmed asset selection drop down and grid operate as before, with the addition of the unique suffix four files with the same display name and the tooltip.
=> Atom Tools: Adding unique suffixes and tooltips to asset selection entries

Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.h, Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h, Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowser.cpp, Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
Now that intermediate assets are being used to generate material types and shader permutations, the files are showing up in the asset browser and asset selection controls, adding a lot of noise and confusion because of the extra options.
This PR hides them from the asset browser and asset selection controls in material editor, material canvas, and other tools based on atom tools framework.
A custom, general purpose asset browser entry filter was also added that allows using the standard function instead of creating complex combinations of other filter types.
Confirmed that cache folder assets don't appear in material editor or material canvas browsers/pickers.
=> Atom Tools: Updating asset browser, selectors, and enumeration to ignore the cache and intermediate asset folders

Code/Framework/AzToolsFramework/AzToolsFramework/ContainerEntity/ContainerEntitySystemComponent.cpp
Prevents an infinite loop in the case where a parent entity is invalid.
This can cause the editor to freeze up even if the situation is just temporary and will be 'fixed up' the moment the current undo is complete.
The old behavior was that if you were messing with entity hierarchy and deleting parent entities, or loading old data or dealing with prefabs with overrides that applied to missing entities, then there could be a case where the parent entity is _temporarily_ invalid.
In that case, if this code triggered, what would occur is it would 
* set the entityId up to be the parent entity Id
* while loop until the entityId was valid
* set the entityId to the parent entity Id using the ebus …
=> Prevent an infinite loop when a parent entity is invalid

Gems/Atom/Feature/Common/Assets/Passes/CameraPipeline.pass, Gems/Atom/Feature/Common/Assets/Passes/PassTemplates.azasset, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RenderPipeline.h, Gems/Atom/RPI/Code/Source/RPI.Public/RenderPipeline.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/View.cpp, Gems/AtomTressFX/Assets/Passes/HairShortCutResolveColor.pass, Gems/Camera/Code/Source/CameraComponentController.cpp, Gems/Camera/Code/Source/CameraComponentController.h, Gems/Camera/gem.json
The camera component can specify an AttachmentImageAsset which it renders to.
The camera component can specify the root pass template it may use for its render pipeline.
To test this feature, we may create a UICanvas which uses this AttachmentImageAsset for its image component. Then add this UICanvas to an entity inside the level via UICanvas Ref component. When enter the game mode in Editor, it should show the render target image on screen in UI. 
Tested in Editor for AutomatedTesting project. 
Tested with AutomatedTesting.GameLauncher. 
Test steps in Editor:
1. Create a new level
2. Add an entity with camera component and set it as the activate camera for the level
3. Add another entity with camera, set the camera1.attimage (from the following package) to its Render Texture. 
4. Create …
=> Add RenderToTexture function to camera component

Gems/PhysX/Code/Source/BaseColliderComponent.cpp, Gems/PhysX/Code/Source/EditorMeshColliderComponent.cpp, Gems/PhysX/Code/Source/EditorMeshColliderComponent.h, Gems/PhysX/Code/Source/EditorRigidBodyComponent.cpp, Gems/PhysX/Code/Tests/EditorMeshColliderComponentTests.cpp, Gems/PhysX/Code/Tests/EditorTestUtilities.cpp
Fixed asset scale when Mesh Collider has primitive shapes. (https://github.com/o3de/o3de/issues/14907)
Subdivision level property now shows when there are primitive shapes.
The tests were checking only the runtime components created from the editor component (which is good to test), but it was missing to check the editor component itself. Refactored the tests to check results in both editor and runtime components.
Fixed bug when creating an `EditorMeshColliderComponent` via its constructor passing physics asset configuration, it was missing to set the proxy's `m_pxAsset` variable from the configuration, which caused the editor on activation to assume there was no asset.
Run PhysX gem unit tests and passed.
Checked the Asset Scale property inside Mesh Collider Component works properly with …
=> Fixed asset scale when Mesh Collider has primitive shapes and improved unit tests.

Code/Framework/AzFramework/Platform/Windows/AzFramework/Process/ProcessUtils_Win.cpp
Built the AzFramework target for Windows successfully with `LY_UNITY_BUILD=0`
=> Adding missing includes to ProcessUtils_Win.cpp to fix Windows non-unity builds

Gems/PhysX/Code/Source/EditorRigidBodyComponent.cpp, Gems/PhysX/Code/Source/RigidBodyComponent.cpp
Also improved warning message in dynamic rigid body component.
Fixes #14972
Fixes #14973
Warning message is as follows now:
`[Warning] (RigidBodyComponent) - It is not valid to have a PhysX Dynamic Rigid Body Component when the Transform Component is marked static.  Entity "Ball Follower" will behave as a static rigid body.`
=> Replace 'Dynamic' with 'Simulated' to match the property type

Code/Tools/ProjectManager/tests/GemCatalogTests.cpp
Expanding coverage to `GemSortProxyModel` based of latest coverage test results.
Tests added to touch the following areas:
- `GetGemSelected()`
- `GetGemActive()` 
- `GetGemOrigins()` 
- `GetPlatforms()` 
- `GetTypes()`
- `GetFeatures()`
- `ResetFilters()`
Verified that gtests initially failed, then passed after correcting the conditions for passing.
Verified that gtests passed in isolation of the `GemCatalogFilters` as well as passing the entire `ProjectManager.Tests` suite.
```
[       OK ] ProjectManagerApplicationTests.Application_Init_Succeeds (4109 ms)
[----------] 1 test from ProjectManagerApplicationTests (4110 ms total)
[----------] 1 test from GemCatalogTests
[ RUN      ] GemCatalogTests.GemCatalog_GemWithDependencies_DisplaysButDoesNotAdd …
```
=> Expand coverage to GemSortProxyModel

Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.h, Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
AssetProcessor would erronously spam warnings with the text "asset name was replaced with a new, but different file."
This fixes that asset spam.
The reason this started happening a while ago is that the flags and hash field were added to the product database, and thus added to the operator==.  
However, theres a blob of code that starts with all the previous assets from the last session, and _subtracts_ the ones from this session, resulting in the assets that used to be there (last time) that are are no longer there (this time) since everything that is here this time has been removed from the list.    It wants to use this list of "stuff that was here, but is no longer here" to delete products …
=> Fixes asset processor warning spam

AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_03.py, AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py, AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_StarsAdded.py
Adds some basic null rhi tests for instantiation and property modification of Stars component.
in editor `pyRunFile ../../Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_StarsAdded.py`
```
Report:
[SUCCESS] Success: Stars Entity successfully created
[SUCCESS] Success: Entity has a Stars component
[SUCCESS] Success: Stars component successfully removed
[SUCCESS] Success: UNDO Stars component removal success
[SUCCESS] Success: Stars component enabled
[SUCCESS] Success: Stars Asset property set
[SUCCESS] Success: Exposure property set
[SUCCESS] Success: Exposure property set
[SUCCESS] Success: Twinkle rate property set
[SUCCESS] Success: Twinkle rate property set
[SUCCESS] Success: Radius factor property set
[SUCCESS] Success: Radius factor property set
[SUCCESS] Success: Entered game …
```
=> Stars component null rhi test automation

Code/Framework/AzFramework/AzFramework/Physics/Material/PhysicsMaterialSlots.cpp, Code/Framework/AzFramework/AzFramework/Physics/Material/PhysicsMaterialSlots.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.cpp, Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h, Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.cpp
Physics material reflection to edit context does not need an asset assigned, the components handle that if there is no asset it uses the default material. In order to show the text "(default)" when there is no asset assigned Physics materials were passing an null asset to the DefaultAsset property. This was ok before, but after [this change](https://github.com/o3de/o3de/pull/13959) this is reported as an error.
- Fixed by passing the default physics material from the material manager, which is an in-memory asset. 
- This was still reported as error because the asset property handler expected an asset job for the default asset, but since it's an in-memory asset there is no job for it and it was reported it as missing asset. Fixed by only reporting as missing asset if it is not found in …
=> Fix Physics Material Asset property from showing invalid asset in components

Gems/PhysX/Code/Source/Pipeline/MeshBehavior.cpp, Gems/PhysX/Code/Source/Pipeline/MeshBehavior.h, Gems/PhysX/Code/Source/Pipeline/MeshExporter.cpp
Added support for "Coordinate system change" modifier to PhysX tab so the users can add the transformation to the PhysX collider to match the transformation applied to the Mesh.
Fixes #14649
Fixes #11330
Fixes #2426
Modifier in Scene settings PhysX tab:
Before:
After:
Manually tested in a level using a Mesh Collider with a mesh exported as:
- primitive
- primitive with decomposition
- convex
- convex with decomposition
- triangle mesh
Tested with "Coordinate system change" modifier simple and advance modes.
=> Add support for 'Coordinate system change' modifier to PhysX tab in Scene Settings

scripts/o3de/o3de/register.py, scripts/o3de/tests/__init__.py, scripts/o3de/tests/test_register.py
If the `-esgp`, `-espp`, `-esep` is not supplied when registering a gem path, then the nearest ancestor directory containing a gem.json is used as the location to register the sub gem to it's "external_subdirectories" array.
If there is no ancestor gem path, then the nearest project path is
located.
If there is no nearest project path, then the nearest engine path is
located.
Finally if there is no nearest engine path, the
`~/.o3de/o3de_manifest.json` is where the gem will be registered.
Fixed the test package name discovery for the o3de python package by removing the `__init__.py` script
Added an additional external subdirectory option that is mutually exclusive with `--external-subdirectory-gem-path`, `--external-subdirectory-project-path` and `--external-subdirectory-engine-path`, that …
=> Add support to register sub gem to nearest ancestor gem automatically

cmake/AzAutoGen.py, cmake/LyAutoGen.cmake
The prune option will remove any files from the generated output directories that were NOT produced by the current run of AzAutoGen.
This can be used to clean up state generated files that are still being tracked by CMake.
Commented out AutoGen generation for the [RpcTesterComponent.AutoComponent.xml](https://github.com/o3de/o3de-multiplayersample/blob/development/Gem/Code/multiplayersample_files.cmake#L11) and performed two iterative builds of the the MultiplayerSample.Client.Static target
Verified that the **first** iterative build re-ran CMake and removed the `RpcTesterComponent.AutoComponent.h` and `RpcTesterComponent.AutoComponent.cpp` files
Verified that the **second** iterative did not re-run CMake
=> Add `--prune` option to AzAutoGen

Gems/DebugDraw/Code/CMakeLists.txt
Enables debug draw gem functionality for Unified launchers.
Tested with o3de-multiplayersample in Unified launcher.
=> DebugDraw fix for Unified launchers

cmake/Subdirectories.cmake
Fix an issue where CMake would not configure if an object had no gem_names, like in the Loft Sample
- verified the the Loft Sample configured succesffully
=> fix error when project has no gem_names

Code/Tools/AssetProcessor/native/AssetManager/SourceFileRelocator.cpp, Code/Tools/AssetProcessor/native/AssetManager/SourceFileRelocator.h, Code/Tools/AssetProcessor/native/tests/SourceFileRelocatorTests.cpp
Updated the legacy find-and-replace asset relocator to ignore dependencies for metadata-enabled types.
Also fixed a bug that prevented metadata files from being properly renamed with the source file.
Manually running editor and using the rename command
Added and ran unit test
=> Asset Processor - Update Legacy Relocator to handle meta types

Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/CoreLights/DirectionalLightComponentConfig.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DirectionalLightComponentConfig.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorDirectionalLightComponent.cpp
Signed-off-by: Zhang-Baochong <zhangbaochong@huawei.com>
Update DirectionalLight `Far depth cascade` if `Shadow far clip` is modified.
Fix the bug that the value of tooltip is not same with edit box if `Shadow far clip` is modified.
Before：
After:
Manually tested in editor.
1.Open Editor.
2.Modify `Shadow far clip`  parameter of Diectional Light Component 
3.Test if the `Far depth cascade` can be updated correctly.
4.Test if the vaule of tooltip is same with edit box.
=> Update Far depth cascade if Shadow far clip is modified.

Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/GraphView.cpp, Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/ConstructPresetDialog/ConstructPresetDialog.cpp
Changes the selection behavior of the graph canvas preset editor table view so that clicking any cell in the table selects the entire row instead of an individual cell. This way, if a user selects the name column or the enable column, they will still be able to remove the entire row.
Also performed research and replace to update references to the dialogue that use consistent naming.
Resolves https://github.com/o3de/o3de/issues/15006 
Resolves https://github.com/o3de/o3de/issues/15004
Confirmed that selecting any cell in the table selected the entire row.
Confirm that clicking the column with the checkbox still allowed the entire road to be deleted.
Confirmed that the material canvas menu entry displayed the same name as other references.
=> Change graph canvas presets dialog selection behavior to entire row and update naming

Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialGraphCompiler.cpp, Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialGraphCompiler.h
Material canvas currently supports multiple output nodes on the same graph. While it’s not typical, this allows generating multiple materials, strategies, or other types of content from the same graph. To keep the generated data of one element node from stopping over the other, a unique suffix will be added onto graph name substitutions for each output node after the first one.
If other issues are encountered, this can be changed to return after the first output is processed and ignore the others.
Resolves https://github.com/o3de/o3de/issues/14903
Confirmed that having multiple output nodes on the same graph will generate data for both nodes with the new suffix.
=> Material Canvas: Use a unique suffix for substitution names if a graph has multiple output nodes

AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_03.py, AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py, AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_SkyAtmosphereAdded.py
Sky Atmosphere component tests with `-rhi=null`. Testing component property limits and basic instantiation of component.
in editor `pyRunFile ../../Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_SkyAtmosphereAdded.py`
```
Report:
[SUCCESS] Success: Sky AtmosphereEntity successfully created
[SUCCESS] Success: Entity has a Sky Atmosphere component
[SUCCESS] Success: Sky Atmosphere component successfully removed
[SUCCESS] Success: UNDO Sky Atmosphere component removal success
[SUCCESS] Success: Sky Atmosphere component enabled
[SUCCESS] Success: Ground albedo property set
[SUCCESS] Success: Ground radius property set
[SUCCESS] Success: Origin property set to GroundAtWorldOrigin
[SUCCESS] Success: Origin property set to GroundAtLocalOrigin
[SUCCESS] Success: Origin property set to …
```
=> Sky Atmosphere rhi null test automation

Code/Framework/AzCore/AzCore/EBus/BusImpl.h
It resolves a (soon-to-be) broken documentation link to the EBus docs. 
The PR that changes the link is located here: https://github.com/o3de/o3de.org/pull/2209
=> Fix broken link to EBus docs

Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
On a server with a camera, even with -rhi=null, only the entities within the camera frustum would tick. This results in an incorrect root transform for the players and their animation actors. In turns, this breaks bones' positions, and the firing ends up broken as well, since the server disagrees with the client on the origin of the shot based on the shooting bone.
in o3de-multiplayer with a dedicated server with camera looking away from players
=> Fix server entities not ticking when outside of a camera frustum view

Gems/Atom/Feature/Common/Assets/seedList.seed
A recent PR added a new hard-coded "clearshadow.azshader". This PR adds that shader to the Atom seed list, so that it will end up in generated Asset Bundles.
Generated Asset Bundles for MPS and verified that the shader now loads correctly instead of giving an asset not found error.
=> Add new hard-coded clearshadow shader.

Gems/AWSGameLift/Code/AWSGameLiftServer/Source/AWSGameLiftServerSystemComponent.cpp
Addresses https://github.com/o3de/o3de/issues/14848
Some questions I'd like feedback on:
1. what's the best way to _enable_ GameLift for local play, add `sv_useGameLiftServer=true` in the `server.cfg`? Will this work for playing in the Editor?
2. should we have a corresponding CVAR for the client, i.e., `cl_useGameLift`? This would mostly prevent the client from connecting to the various GameLift request buses, which may help performance, but not sure its worth complicating things with an additional setting to flip.
* Using [o3de-multiplayersample](https://github.com/o3de/o3de-multiplayersample) with AWSGameLift gem enabled, can run `ctrl` + `g` in Editor w/o running GameLiftLocal.
* setting `"sv_useGameLiftServer": "true"` in _commands.multiplayersample_serverlauncher.setreg_ and running …
=> Add sv_useGameLiftServer CVAR to allow local play without GameLift

AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py, AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_SkyAtmosphereAdded.py, Gems/AtomLyIntegration/CommonFeatures/Code/Source/SkyAtmosphere/EditorSkyAtmosphereComponent.cpp
fix title casing in sky atmo tests and component that was causing the pytests to fail
Ran the tests on Windows and verified they passed:
```
$ python/python.cmd -m pytest --build-directory build/windows_vs2019/bin/profile  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_03.py
Pytest custom argument "--output-path" was not provided, defaulting Test Results output to: build/windows_vs2019/bin/profile\Testing\LyTestTools\pytest_results\2023-03-14T11-53-07-207054
================================================================= test session starts ==================================================================
platform win32 -- Python 3.10.5, pytest-7.2.0, pluggy-0.13.1
rootdir: D:\git\o3de-dev, configfile: pytest.ini
plugins: mock-3.8.2, timeout-2.1.0, …
```
=> fix title casing in sky atmo tests and component

AutomatedTesting/Registry/editorpreferences.setreg, Registry/prefab.editor.setreg
This PR enables the new prefab override feature in Entity Outliner by default.
Once enabled, prefab containers can be manually expanded or collapsed. Any override edits would be stored in the _prefab that is being edited_ (highlighted with blue capsule). The level prefab is in edit mode by default.
(Blue "o" icon indicates there is an override edit; Blue "+" icon indicates the entity is added as an override)
See more in [prefab override user guide](https://development--o3deorg.netlify.app/docs/learning-guide/tutorials/entities-and-prefabs/override-a-prefab/).
See RFC: https://github.com/o3de/sig-content/issues/75
See the [known issue list](https://github.com/o3de/o3de/issues?q=is%3Aopen+is%3Aissue+label%3Afeature%2Fprefabs+%22prefab+overrides%22) for prefab override.
If it causes any …
=> Prefab Override | Enable override in Entity Outliner by default

Gems/GraphModel/Code/Include/GraphModel/Integration/FloatDataInterface.h, Gems/GraphModel/Code/Include/GraphModel/Integration/IntegerDataInterface.h, Gems/GraphModel/Code/Source/Integration/FloatDataInterface.cpp
Resolves https://github.com/o3de/o3de/issues/14258
Created and edited multiple floating point and integer nodes in material canvas.
Confirmed that integer based nodes do not allow entering digits after the decimal point.
Confirmed that integer based nodes only display scientific notation for numbers >= 10000.
=> Fix graph model integer slot precision to only show scientific notation for large numbers

Gems/Atom/Feature/Common/Code/Source/Utils/EditorLightingPreset.cpp, Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportSettingsInspector.cpp
The viewport settings panel was refreshing after selection and property changes but not rebuilding itself or the embedded property editors after changes that affected container sizes. This led to displaying and manipulating corrupt lighting data.
Resolves https://github.com/o3de/o3de/issues/12237
Tested creating and cycling through multiple lighting presets, adding and removing directional lights from the configuration.
=> Fix material editor/canvas viewport settings inspector data corruption

Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp, Gems/Atom/Tools/MaterialCanvas/Registry/gem_autoload.materialcanvas.setreg, Gems/Atom/Tools/MaterialEditor/Registry/gem_autoload.materialeditor.setreg, Gems/Atom/Tools/PassCanvas/Registry/gem_autoload.passcanvas.setreg, Gems/Atom/Tools/ShaderManagementConsole/Registry/gem_autoload.shadermanagementconsole.setreg
Also initializing action manager to prevent crash if gems that require it are enabled
Resolves https://github.com/o3de/o3de/issues/7113 for the existing gem combinations but need to add UI to disable the disable gem feature and documentation
Enabled all gems that could be enabled for the automated testing project.
Launched material editor and saw errors indicating that motion matching system component could not be initialized.
Updated settings files to disable motion matching which allowed material editor to launch.
Deleted settings files to see material editor crashing because action manager was not initialized.
Initialized action manager and restarted material editor successfully.
=> Fix material editor not launching when motion matching is enabled

Gems/Atom/Feature/Common/Code/Source/CoreLights/ShadowmapPass.cpp, Gems/Atom/Feature/Common/Code/Source/CoreLights/ShadowmapPass.h
Cached shadows weren't correctly handling the case of multithreaded draw submits with regards to their first render when cached shadows were initially turned on. Depending on the order things were called, it was possible for `m_forceRenderNextFrame` to be set to false before the clear draw packet was actually submitted since `SubmitDrawItems()` can be called multiple times per frame on different threads. This fixes it so `m_forceRenderNextFrame` isn't set to false until `FrameEndInternal()` which will be called only once per frame.
Tested in warehouse scene with 108 light views and a fair number of draws.
=> Fixing cached shadows not clearing properly for their initial render.

AutomatedTesting/Gem/PythonTests/editor/EditorScripts/EditorWorkflow_EditorCameraInBeThisCameraReturnsToOriginalPositionWhenLeavingGameMode.py, AutomatedTesting/Gem/PythonTests/editor/EditorScripts/EditorWorkflow_EditorCameraReturnsToOriginalPositionWhenLeavingFullscreenGameMode.py, AutomatedTesting/Gem/PythonTests/editor/TestSuite_Main.py, Code/Editor/EditorViewportWidget.cpp, Code/Editor/PythonEditorFuncs.cpp
Fixes https://github.com/o3de/o3de/issues/14527
This PR restores the backed out code from https://github.com/o3de/o3de/pull/15115 and fixes game mode camera logic for both Ctrl-G and fullscreen.
_(Interestingly what broke the [previous change (#15051)](https://github.com/o3de/o3de/pull/15051) was this [unrelated change (#14889)](https://github.com/o3de/o3de/pull/14889))_
Automated tests locally, tested in editor and AR run
```bash
python\python.cmd -m pytest -v --build-directory build-3\vs2022\bin\profile .\AutomatedTesting\Gem\PythonTests\editor\TestSuite_Main.py
Pytest custom argument "--output-path" was not provided, defaulting Test Results output to: build-3\vs2022\bin\profile\Testing\LyTestTools\pytest_results\2023-03-15T13-28-44-268783 …
```
=> Camera fix again

Gems/RemoteTools/Code/Source/RemoteToolsSystemComponent.cpp
Fixes a Linux/Clang compile error:
```
In file included from /home/github/o3de/build/linux_aarch64/External/RemoteTools-bd846853/Code/CMakeFiles/RemoteTools.Private.Static.dir/Unity/unity_0_cxx.cxx:3:
/home/github/o3de/Gems/RemoteTools/Code/Source/RemoteToolsSystemComponent.cpp:568:14: error: variable 'hasActiveConnection' set but not used [-Werror,-Wunused-but-set-variable]
bool hasActiveConnection = false;
^
```
Built locally on Linux
=> Fix unused variable error by deleting unnecessary code

Code/Editor/Platform/Common/Clang/editor_lib_clang.cmake, Code/Tools/ProjectManager/Platform/Common/Clang/projectmanager_clang.cmake, Code/Tools/PythonBindingsExample/source/Platform/Common/Clang/pythonbindingsexample_clang.cmake, Code/Tools/TestImpactFramework/Frontend/Console/Common/Code/Source/Platform/Common/Clang/testimpactframework_clang.cmake, Code/Tools/TestImpactFramework/Frontend/Console/Native/Code/CMakeLists.txt, Code/Tools/TestImpactFramework/Frontend/Console/Native/Code/Source/Platform/Common/Clang/testimpactframework_clang.cmake, Code/Tools/TestImpactFramework/Frontend/Console/Native/Code/Source/Platform/Common/GCC/testimpactframework_gcc.cmake, Code/Tools/TestImpactFramework/Frontend/Console/Native/Code/Source/Platform/Common/MSVC/testimpactframework_msvc.cmake, Code/Tools/TestImpactFramework/Frontend/Console/Python/Code/CMakeLists.txt, Code/Tools/TestImpactFramework/Frontend/Console/Python/Code/Source/Platform/Common/Clang/testimpactframework_clang.cmake, Code/Tools/TestImpactFramework/Frontend/Console/Python/Code/Source/Platform/Common/GCC/testimpactframework_gcc.cmake, Code/Tools/TestImpactFramework/Frontend/Console/Python/Code/Source/Platform/Common/MSVC/testimpactframework_msvc.cmake, Code/Tools/TestImpactFramework/Runtime/Common/Code/Source/Platform/Common/Clang/testimpactframework_clang.cmake, Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/Platform/Common/Clang/testimpactframework_clang.cmake, Code/Tools/TestImpactFramework/Runtime/Python/Code/Source/Platform/Common/Clang/testimpactframework_clang.cmake, Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Platform/Common/Clang/imageprocessingatom_editor_static_clang.cmake, Gems/Atom/Asset/Shader/Code/Source/Platform/Common/Clang/atom_asset_shader_static_clang.cmake, Gems/Atom/RHI/DX12/Code/Source/RHI/QueryPoolResolver.cpp, Gems/EditorPythonBindings/Code/Source/Platform/Common/Clang/editorpythonbindings_static_clang.cmake, Gems/EditorPythonBindings/Code/Source/Platform/Common/Clang/editorpythonbindings_tests_clang.cmake, Gems/GradientSignal/Code/Source/Platform/Common/Clang/gradient_signal_editor_clang.cmake, Gems/Metastream/Code/Source/Platform/Common/Clang/metastream_clang.cmake, Gems/PythonAssetBuilder/Code/Source/Platform/Common/Clang/pythonassetbuilder_static_clang.cmake, Gems/PythonAssetBuilder/Code/Source/Platform/Common/Clang/pythonassetbuilder_tests_clang.cmake, Gems/QtForPython/Code/Source/Platform/Common/Clang/qtforpython_clang.cmake, cmake/Platform/Common/MSVC/Configurations_clang.cmake, cmake/Platform/Windows/CMakePresets.json, cmake/Platform/Windows/Configurations_windows.cmake, cmake/Platform/Windows/platform_windows_files.cmake
Build o3de with `clang-cl` shipped with VS2022.
Configure the engine source with the following commands:
```
set SRC_ROOT=E:\CODE\o3de
cmake -B %SRC_ROOT%\build\windows_clang ^
-S %SRC_ROOT% ^
-T ClangCl ^
-DLY_UNITY_BUILD=ON ^
-DLY_3RDPARTY_PATH=D:\CODE\o3de\3rd-packages ^
-DLY_PROJECTS=AutomatedTesting
```
Build the engine source using VS2022, using `O3DE.sln` located in `%SRC_ROOT%\build\windows_clang`
Build the source.
=> Build with MSVS2022 clang-cl.

Code/Framework/AzFramework/AzFramework/Physics/Material/PhysicsMaterialSystemComponent.cpp, Gems/PhysX/Code/Editor/Source/Components/EditorSystemComponent.cpp, Gems/PhysX/Code/Source/SystemComponent.cpp
Fixes #10825
`Physics::MaterialSystemComponent`, which is the system that registers the physics material asset handler, is already activated since it's part of `Application::GetRequiredSystemComponents()`, so it doesn't need to be tagged as `AssetBuilder`, which was causing to be activated again in the asset processor.
Run PhysX unit tests
Debugged Asset Builder and checked physics material asset handler is only registered once.
Run Asset Processor and checked the error doesn't appear anymore.
Rebuild all assets in AutomatedTesting and checked physics material assets are correctly generated.
Run Editor and tested different physics materials in a level.
Run Launcher and checked the level using different physics materials work.
=> Fix to avoid physics material asset handler to be registered twice when running Asset Processor

Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/PathOrUuid.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/PathOrUuid.h, Code/Tools/AssetProcessor/assetprocessor_test_files.cmake, Code/Tools/AssetProcessor/native/AssetManager/AssetCatalog.cpp, Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp, Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h, Code/Tools/AssetProcessor/native/tests/ApplicationManagerTests.cpp, Code/Tools/AssetProcessor/native/tests/BuilderManagerTests.cpp, Code/Tools/AssetProcessor/native/tests/PathDependencyManagerTests.cpp, Code/Tools/AssetProcessor/native/tests/UnitTestUtilities.h, Code/Tools/AssetProcessor/native/tests/UuidManagerTests.cpp, Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.cpp, Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.h, Code/Tools/AssetProcessor/native/tests/assetmanager/IntermediateAssetTests.cpp, Code/Tools/AssetProcessor/native/tests/assetmanager/SourceDependencyTests.cpp, Code/Tools/AssetProcessor/native/tests/assetmanager/SourceDependencyTests.h, Code/Tools/AssetProcessor/native/ui/SourceAssetDetailsPanel.cpp, Code/Tools/AssetProcessor/native/utilities/UuidManager.cpp, Code/Tools/AssetProcessor/native/utilities/UuidManager.h
Updates UuidManager to track and provide APIs for looking up legacy UUIDs.
Updates asset catalog to convert legacy UUIDs in source and product dependencies to the current canonical UUID on startup.
Updates asset processor manager to convert newly created source/product dependencies that reference legacy UUIDs into canonical UUIDs before saving to the database.
Updates some of the exposed APIs which lookup sources by UUID to attempt to lookup an asset using a legacy UUID.
Manual testing + added and ran unit tests
=> Asset Processor - Improve handling of legacy UUIDs

Gems/Atom/Feature/Common/Assets/seedList.seed
Atom changes to the diffuse probe grid code from the past few days have caused a new set of Atom files to be missing from the Atom seed list. This adds the files.
Built and ran MultiplayerSample with bundles and verified that I no longer got missing asset errors due to Diffuse Probe Grid shaders and passes.
=> Add missing atom files to the seed list

Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp
Related PR - https://github.com/o3de/o3de-extras/pull/219
Tested OpenXrTest project on Quest 2
=> Moved xr pipeline names to cvars so they can be overridden easily

Code/Framework/AzCore/Tests/AZStd/Parallel.cpp
This is being done to better debug failures in the future that occurs on Linux
Fixed the AZStd::thread creation calls to properly supply the thread descriptor argument as the first argument to `AZStd::thread`
Fixed intermittent memory leak in Parallel thread unit test due to the thread swap unit test detaching the thread and not joining.
This created a race condition where a thread can still be running at the end of the Parallel_Thread.Test when the memory leak 
checker is checking for existing allocations.
Most of the changes involve spliting up the singular`run()` function into discrete methods that test more fine grained pieces of the `AZStd::thread` API
fixes #14536
Ran all `Parallel_Thread.*` test 1000 times successfully on Windows and Linux
=> Split the `Parallel_Thread.Test` unit test into smaller UnitTest

Gems/WhiteBox/Assets/materials/WhiteBoxDefault.material, Gems/WhiteBox/Assets/materials/checker_material.mtl, Gems/WhiteBox/Assets/materials/default_material.mtl, Gems/WhiteBox/Assets/materials/solid_material.mtl, Gems/WhiteBox/Assets/seedList.seed, Gems/WhiteBox/Assets/textures/default/_dev_Middle_Gray_Checker.tif, Gems/WhiteBox/Assets/textures/default/_dev_Middle_Gray_Checker_ddn.tif, Gems/WhiteBox/Assets/textures/default/_dev_Middle_Gray_Checker_spec.tif, Gems/WhiteBox/Assets/textures/default/_dev_Solid_Fill.tif, Gems/WhiteBox/Code/Source/Rendering/Atom/WhiteBoxAtomRenderMesh.h
This fix the issue https://github.com/o3de/o3de/issues/15116
The changes include:
- Added missing material used for whitebox.
- Renamed the material from DefaultPBR.material to WhiteBoxDefault.material.
- Deleted some unused mtl files (old ly material files) and unused texture files.
- Added a seed file to include the white box material asset.
Cleaned cache and tested in Editor with AutomatedTesting project.
=> white box material fix

AutomatedTesting/Gem/PythonTests/editor/TestSuite_Main.py, Code/Framework/AzCore/AzCore/Task/TaskGraph.h, Gems/RemoteTools/Code/Source/RemoteToolsSystemComponent.cpp
Fixes Linux and android on release configurations. `TaskGraphEvent::m_label` is only used inside `AZ_Assert` statements, so it was warning as not used in release, causing build to fail.
Marking as well `test_BasicEditorWorkflows_LevelEntityComponentCRUD` as xfail since it's regularly failing affecting the speed to submit bug fixes to stabilization branch. (#15172)
Fixed also the following error introduced in #15112 (tagging @galibzon)
````
/data/workspace/o3de/Gems/RemoteTools/Code/Source/RemoteToolsSystemComponent.cpp:568:14: error: variable 'hasActiveConnection' set but not used [-Werror,-Wunused-but-set-variable]
bool hasActiveConnection = false;
^
````
Built Linux and android on release successfully.
=> Fix build linux/android in release

Gems/EMotionFX/Code/EMotionFX/Source/ActorInstance.cpp
EMotionFX and NvCloth unit tests fail when running on debug due to the following math assert in Aabb (that is only reported on debug).
````
D:\workspace\o3de\Code\Framework\AzCore\AzCore/Math/Aabb.inl(36): error: Min must be less than Max
````
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE_periodic-incremental-daily/detail/stabilization%2F2305/2/pipeline/2217/
The issue is that there are edge cases where `ActorInstance` can be left with an invalid aabb, for example when the actor doesn't have any nodes, which is a case tested by unit tests and therefore failing because it's doing operation with the aabb when it's invalid.
To fix it now the code is protected so it doesn't do operations on invalid aabb and `ActorInstance` now guarantees to have a valid aabb when it's …
=> Fix EMotionFX and NvCloth unit tests by making sure ActorInstance has a valid aabb

Gems/DiffuseProbeGrid/Assets/Passes/DiffuseProbeGridPreparePassRequest.azasset, Gems/DiffuseProbeGrid/Assets/Passes/DiffuseProbeGridUpdate.pass, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.cpp
Moved the DiffuseProbeGridPreparePass out of the DiffuseProbeGridUpdatePass since it is needed for the DiffuseProbeGridRenderPass on non-RT capable devices.
=> Fix for Baked DiffuseProbeGrids on non-RT capable devices

Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
Fixes https://github.com/o3de/o3de/issues/14998
Disables the `Delete` action when the Entity Picker mode is enabled. This prevents edge cases where users can try and delete the currently selected entity while picking an entity for a property of one of its components, causing a crash.
=> Action Manager | Prevent entity deletion while in Entity Picker mode

Code/Framework/AtomCore/AtomCore/Instance/InstanceDatabase.h, Code/Framework/AzCore/AzCore/Math/Sfmt.cpp, Code/Framework/AzCore/AzCore/Math/Sfmt.h, Code/Framework/AzCore/AzCore/Math/Uuid.cpp, Code/Framework/AzCore/Tests/Math/SfmtTests.cpp
The Sfmt code had some subtle (and some not-so-subtle) bugs that led to race conditions which led to O3DE producing the same "random" UUIDs far more often than the odds would predict. This manifested as an intermittent assert ("Instance creation for asset id X resulted in a recursive creation of that asset, which was unexpected. This asset might be erroneously referencing itself as a dependent asset.") from Atom in the Instance database, since it is the most frequent consumer of parallel random UUID generation.
Thanks to @amzn-tommy for providing the unit test that made this bug nearly 100% reproducible!
The heart of the problem was some bad overly-clever threading logic that attempted to remain lockless as much as possible, but introduced bugs that were thread-unsafe and logically …
=> Fix sfmt value repetition bugs

AutomatedTesting/Gem/PythonTests/Atom/tests/MaterialCanvas_Atom_BasicTests.py, Gems/GraphModel/Code/Include/GraphModel/Model/Common.h, Gems/GraphModel/Code/Include/GraphModel/Model/GraphContext.h, Gems/GraphModel/Code/Source/GraphModelSystemComponent.cpp, Gems/GraphModel/Code/Source/Model/Connection.cpp, Gems/GraphModel/Code/Source/Model/DataType.cpp, Gems/GraphModel/Code/Source/Model/Graph.cpp, Gems/GraphModel/Code/Source/Model/GraphContext.cpp, Gems/GraphModel/Code/Source/Model/GraphElement.cpp, Gems/GraphModel/Code/Source/Model/Node.cpp, Gems/GraphModel/Code/Source/Model/Slot.cpp
This change reorders reflection calls and removes a behavior context binding for a graph model graph controller function that was causing asserts in the AP.
Resolves https://github.com/o3de/o3de/issues/15121
Confirmed that asserts no longer appear in the AP log after changes.
=> Updating graph model reflection and unbinding function causing AP asserts

Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp, Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp, Gems/Atom/Tools/MaterialCanvas/Registry/gem_autoload.materialcanvas.setreg, Gems/Atom/Tools/MaterialEditor/Registry/gem_autoload.materialeditor.setreg, Gems/Atom/Tools/PassCanvas/Registry/gem_autoload.passcanvas.setreg, Gems/Atom/Tools/ShaderManagementConsole/Registry/gem_autoload.shadermanagementconsole.setreg, Gems/RemoteTools/Code/Source/RemoteToolsSystemComponent.cpp
Disabling additional modules that should have no direct impact on material editor, material canvas, etc. Some AWS game lift modules were missed in the last iteration. All of the tools launched successfully with those exhaustively disabled. Would be great if the auto load feature supported wild cards.
Resolves https://github.com/o3de/o3de/issues/7113
More exhaustive testing between all atom tools, changing the settings for one tool to do A/B comparison against another before updating settings for the remaining tools. Confirmed that all load with game lift and the other AWS modules enabled.
=> Updating atom tools auto load registry settings to disable AWS modules

Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.cpp
This change fixes a potential crash if a material component config has slots referencing bad material assets or no material w/ model UV overrides
Compiled code successfully
=> Add material instance null pointer check in editor material component

AutomatedTesting/cmake/EngineFinder.cmake, Templates/DefaultProject/Template/cmake/EngineFinder.cmake, Templates/MinimalProject/Template/cmake/EngineFinder.cmake
Fixes an issue where Findo3de.cmake would throw this error:
```
-- Selecting engine 'D:/git/o3de-stab-worktree'
CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
This engine was not found to be compatible with your project, or no
compatibility checks were done.  For more information, run the command
again with '--log-level VERBOSE'.  (missing: PACKAGE_VERSION_COMPATIBLE)
```
Cmake finds and selects a compatible engine, but there is a case where PACKAGE_VERSION_COMPATIBLE isn't set - this happens when the last engine checked is incompatible.  This fix sets PACKAGE_VERSION_COMPATIBLE when a compatible engine is found.
Configured, built and ran AutomatedTesting from a build folder inside AutomatedTesting
```
cd …
```
=> fix PACKAGE_VERSION_COMPATIBLE not set

Gems/DiffuseProbeGrid/Code/Source/EditorComponents/EditorDiffuseProbeGridComponent.cpp
Restore the selected Editor DiffuseProbeGrid mode (RealTime or Baked) when exiting Game mode and returning to the Editor.
=> Fix for DiffuseProbeGrid mode when exiting Play Game

Gems/PhysX/Code/Tests/Benchmarks/PhysXBenchmarksUtilities.cpp, Gems/PhysX/Code/Tests/Benchmarks/PhysXBenchmarksUtilities.h, Gems/PhysX/Code/Tests/Benchmarks/PhysXRigidBodyBenchmarks.cpp
Added benchmark `BM_RigidBody_Activation` to PhysX Gem. This test will create 100, 1K, 10K and 100K entities with rigid bodies, colliders and mock components that depend on the rigid bodies, and it measures the time it takes to activate them. It will do 10 iterations of each and calculate the mean, standard deviation, P50, P90, P99, Fastest and Slowest times.
````
---------------------------------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                                         Time             CPU   Iterations UserCounters...
----------------------------------------------------------------------------------------------------------------------------------------- …
```
=> Added benchmark to measure the activation time of PhysX Rigid Bodies.

AutomatedTesting/Gem/PythonTests/Prefab/CMakeLists.txt, AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Main.py, AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Periodic.py
- Moves spawnables tests back into the main suite
- Resolves https://github.com/o3de/o3de/issues/9789
Ran spawnables tests 100x locally without failure.
Ran updated main test suite without failure.
Ran updated periodic suite to ensure dummy test does not cause a failure.
=> Moving spawnables tests into main suite

Gems/EMotionFX/Code/EMotionFX/Source/BlendSpaceNode.cpp, Gems/EMotionFX/Code/EMotionFX/Source/BlendSpaceNode.h
Bringing over Chris's fix for crashes when adding motion events to graphs containing blend nodes
Original fix: https://github.com/o3de/o3de/pull/15195/
=> Fix for crashing when adding motion events

Code/Editor/Core/EditorActionsHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Editor/ActionManagerIdentifiers/EditorMenuIdentifiers.h, Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp, Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.h
- Introduces a "Create" sub-menu to the Outliner and Viewport context menus. This can be used to provide entity presets to streamline entity creation.
- Restores the "Create multiplayer entity" menu item that was present before the migration to the new Action Manager system. This is now included in the "Create" sub-menu described above.
Verified a multiplayer entity is created correctly.
In verifying this change, I realized that in both the new Action Manager and the legacy system the behavior for creating entities by right-clicking in the viewport is inconsistent. I'm working on a follow-up PR to standardize the behavior and possibly provide helper functions to simplify adding new menu items to the "Create" menu down the line with consistent behavior.
=> Action Manager | Introduce "Create" context sub-menu, restore "Create multiplayer entity" menu item.

Gems/EditorPythonBindings/Code/Source/ActionManager/MenuManagerBus.h, Gems/EditorPythonBindings/Code/Source/ActionManager/PythonActionManagerHandler.cpp, Gems/EditorPythonBindings/Code/Source/ActionManager/PythonActionManagerHandler.h
Exposes the following functionality to be used in Python:
- `AddWidgetToMenu` in `MenuManagerPythonRequestBus`
- `AddMenuToMenuBar` in `MenuManagerPythonRequestBus`
- `MenuProperties`
- `ToolBarProperties`
Verified via the following script
```
import azlmbr.action as action
actionProperties = action.ActionProperties()
actionProperties.name = "Custom Action"
actionProperties.description = "A custom action defined via Python"
actionProperties.category = "Python"
def someCustomAction():
print("Hello")
action.ActionManagerPythonRequestBus(bus.Broadcast, "RegisterAction", "o3de.context.editor.mainwindow", "o3de.action.python.test", actionProperties, someCustomAction)
menuProperties = action.MenuProperties()
menuProperties.name = "Python Menu" …
```
=> Action Manager | Expose additional Menu and ToolBar functionality to Python

Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
Fixes #15212
Correctly refreshes the Outliner and Viewport menu items after duplicating an entity.
To address this, I added action updates after entity propagation since that may introduce changes to the selection.
Tested locally and verified it addresses the issue.
=> Action Manager | Correctly refresh the Outliner/Viewport context menus on Duplicate.

scripts/build/Jenkins/Jenkinsfile
- Add stabilization/2305 to the snapshot tags in Jenkins
- Fixes an issue with the snapshot flag being called during the mount action
=> Add stabilization/2305 snapshot tag (Stabilization branch)

Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserViewUtils.cpp
It is very easy to delete files that are not being referenced to in the asset browser, so this adds a confirmation dialog for those files.
Fixes #13488 
Locally
=> Confirmation dialog for file deletions

Code/Tools/AssetProcessor/native/resourcecompiler/rcjob.cpp, Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp, Code/Tools/AssetProcessor/native/tests/assetmanager/IntermediateAssetTests.cpp, Code/Tools/AssetProcessor/native/utilities/ProductOutputUtil.cpp, Code/Tools/AssetProcessor/native/utilities/ProductOutputUtil.h, Code/Tools/AssetProcessor/native/utilities/UuidManager.cpp
Fixes an edge case where asset products could be overwritten if they used the same naming scheme as is used for override prefixing.
When files are copied to the cache they now are given a temporary but longer prefix that shouldn't accidentally conflict with an asset naming scheme.
Added and ran unit test
=> Asset Processor - Handle edge case of product prefix conflict

Code/Framework/AzToolsFramework/AzToolsFramework/API/EditorPythonRunnerRequestsBus.h, Code/Tools/SceneAPI/SceneData/Tests/SceneManifest/SceneManifestRuleTests.cpp, Gems/EditorPythonBindings/Code/Source/PythonSystemComponent.cpp, Gems/EditorPythonBindings/Code/Source/PythonSystemComponent.h
While debugging a separate issue, I realized that our execution of python bootstrap scripts continues even if the script(s) failed, which was masking a problem, so I've changed them to assert on failure so we can catch issues sooner.
Executing scripts manually or through the scripts tool will not trigger the assert.
Inserted issue into a bootstrap script and verified the Editor now asserts on bootstrap. Tested executing other scripts while running the Editor and verified they do not trigger the assert.
=> Make bootstrap scripts execution assert on failure

Code/Editor/CryEdit.cpp, Code/Editor/CryEdit.h, Code/Editor/Util/FileUtil.cpp, Code/Editor/Util/Platform/Linux/FileUtil_Linux.cpp, Code/Editor/Util/Platform/Mac/FileUtil_Mac.cpp, Code/Editor/Util/Platform/Windows/FileUtil_Windows.cpp, Code/Framework/AzCore/AzCore/Script/ScriptContextDebug.cpp, Code/Framework/AzFramework/AzFramework/Script/ScriptRemoteDebugging.cpp, Code/Framework/AzFramework/Platform/Linux/AzFramework/AzFramework_Traits_Linux.h, Code/Framework/AzFramework/Platform/Mac/AzFramework/AzFramework_Traits_Mac.h, Code/Framework/AzFramework/Platform/Windows/AzFramework/AzFramework_Traits_Windows.h
This is the final PR to merge https://github.com/o3de/o3de/pull/15189
into stabilization/2305, which fixes a critical bug that was not allowing to debug Lua scripts on Linux.
Fixes two bugs that occur when debugging Lua scripts. The bug occur with both LuaIDE and VSCode Dbg extension. In other words these two bugs occur regardless of the type of debugger that the Editor.exe is connected to.
The first bug is minor and occurs on all platforms and it is related with the StepOut event when
debugging (Both, with LuaIDE and VSCode Debugger extension). When at the top of the callstack, in ScriptContextDebug.cpp set `m_stepStackLevel = -1;` instead of 0 for properly exiting the current function.
Without this minor fix, the StepOut behaved just like StepOver.
The second bug was major and it …
=> Merging BugFix https://github.com/o3de/o3de/pull/15189

Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbNativeWindow.cpp
Run GameLauncher process on Euler or Ubuntu System. This process can encode video and streaming. If I change resolution during the process is running, the image of encoding and streaming will stop. This PR can fix this issue.
1. Strat a virtual window using "Startx";
2. Export virtual window and run GameLauncher process on Euler or Ubuntu System;
3. Change resolution using code below
EBUS_EVENT(AzFramework::WindowRequestBus, ResizeClientArea, AzFramework::WindowSize(width, height));
4. Check whether streaming of GameLauncher process if normal;
=> Fix streaming issue when changing resolution on Linux

Code/Editor/Controls/ConsoleSCB.cpp, Code/Editor/Core/EditorActionsHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManagerInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManagerInternalInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/HotKey/HotKeyManagerInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/HotKey/HotKeyManagerInternalInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/MenuManagerInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/MenuManagerInternalInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ToolBar/ToolBarManagerInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ToolBar/ToolBarManagerInternalInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/Editor/ActionManagerIdentifiers/EditorContextIdentifiers.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/UICore/ConsoleTextEdit.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/UICore/ConsoleTextEdit.hxx
Fixes the shortcut dispatching for the Console widget in the Editor.
For example, pressing Ctrl+A while focusing on the Console in the current editor leads to all entities being selected instead.
After this fix, the test is selected as expected again.
The same applies to all other shortcuts in the Console's context menu.
=> Action Manager | Fix shortcut dispatching in the Console Widget

Code/Tools/AssetProcessor/native/utilities/GUIApplicationServer.cpp
Updated error message about bootstrap.cfg to refer to bootstrap.setreg and point out the registry path that can be used as well
Fixes https://github.com/o3de/o3de/issues/13449
Manually ran 2 copies of AP
=> Asset Processor - Update error message to refer to setreg path instead of bootstrap.cfg

Gems/Atom/Feature/Common/Assets/seedList.seed
Adding splash screen render pass to seedlist. This is required because the shader pass is referenced in code (not a dependency of any other seed asset) and injected into the render pipeline
Stops a crash from occurring in _Gems\Atom\Feature\Common\Code\Source\SplashScreen\SplashScreenFeatureProcessor.cpp_
`AddPassRequestToRenderPipeline(renderPipeline, "Passes/SplashScreenPassRequest.azasset", "CopyToSwapChain", true);
`
Generated engine_pc.pak and see that PAK build no longer crashes
_.\MultiplayerSample.GameLauncher.exe -bg_ConnectToAssetProcessor=0 -sys_PakPriority=2_
=> Add Splash Screen Render Pass to Seed List

Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Graph/GraphDocument.h, Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/GraphDocument.cpp, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/StyleSheet/materialcanvas_style.json, Gems/Atom/Tools/PassCanvas/Assets/PassCanvas/StyleSheet/passcanvas_style.json
Material canvas primarily uses graph model and dynamic nodes that hide most of the graph canvas implementation. Graph model does not implement wrapper nodes for common, utility types like groups, comments, and bookmarks. This change adds support for editing those types as well as a style sheet entry so they don’t have a blank icon in the node palette.
Resolves https://github.com/o3de/o3de/issues/12494
Tested dragging, dropping, configuring, undo, and redo with comments, groups, and bookmarks.
=> Material Canvas: Fixing utility nodes to be editable in the inspector and have a title palette color

Gems/EMotionFX/Code/EMotionFX/Source/Importer/Importer.cpp
Fix crash seen on Linux when EMFX data cannot be loaded
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  EMotionFX::MotionSet::SetIsOwnedByRuntime (this=0x0, isOwnedByRuntime=true) at /data/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Source/MotionSet.cpp:604
b#1  0x00007f05e715cd1a in EMotionFX::Importer::LoadMotionSet (this=<optimized out>, memoryStart=<optimized out>, lengthInBytes=130, settings=0x7f0532d765c8)
at /data/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Source/Importer/Importer.cpp:549
#2  0x00007f05e74bd77a in EMotionFX::Integration::MotionSetAssetHandler::OnInitAsset (this=<optimized out>, asset=...)
at /data/workspace/o3de/Gems/EMotionFX/Code/Source/Integration/Assets/MotionSetAsset.cpp:143
#3  0x00007f05e6aecd13 in …
```
=> EMFX: Fix crash caused by non-loading MotionSets

Gems/Camera/Code/Source/ViewportCameraSelectorWindow.cpp
Fixes #14925 
The Viewport Camera Selector has logic to change the selection in the list view with the arrow keys, but wasn't ensuring the selection was visible. This change will ensure the selection remains visible by scrolling to the currently selected index, if it isn't already visible in the list view.
Created many camera entities and resized the Viewport Camera Selector widget so that only a few of them were visible. Then used the arrow keys to change the selection and verified the list will scroll to the new selection if it is hidden. Also testing wrapping around the front/end of the list.
=> Scroll to the selected index when changing the selection in the Viewport Camera Selector

Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/Handle.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Shader/ShaderVariantListSourceData.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderOptionGroupLayout.h, Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/ShaderCollection.cpp, Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderOptionGroupLayout.cpp, Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.cpp, Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.h, Gems/Atom/Tools/ShaderManagementConsole/Scripts/GenerateShaderVariantListForAllShaders.py, Gems/Atom/Tools/ShaderManagementConsole/Scripts/GenerateShaderVariantListForMaterials.py, Gems/Atom/Tools/ShaderManagementConsole/Scripts/GenerateShaderVariantListUtil.py
Add the functionality to process user-provided system option setting files, extension ".systemoptions", live in the same path as the ",shader" file. 
The setting file is a json looks like this
```
{
"o_option1": "true",
"o_option2": "2",
"o_option3": "Modulate::None"
"o_option4": ""     // value unset
}
``` 
Users can generate ShaderVariantList with `GenerateShaderVariantListForMaterials.py` as they used to, only now the script will try to read ".systemoptions" and process the value.
If the value is set, it will replace the value set in `GenerateShaderVariantListForMaterials.py`, if the value is unset,
it will be automatically expanded with all the possible combination
Note there is duplicate functionality in c++ and python, because we can't get the `ShaderOptionDescriptor` in the script …
=> [ShaderManagementConsole] Add functionality for system option handling

Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderAssetBuilder.cpp, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Material/Material.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Material/MaterialAsset.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Material/MaterialTypeAsset.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Material/ShaderCollection.h, Gems/Atom/RPI/Code/Source/RPI.Public/Material/Material.cpp, Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/MaterialAsset.cpp, Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/MaterialTypeAsset.cpp, Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/ShaderCollection.cpp
Fixes the dealock by removing the call to
`m_shaderAsset.BlockUntilLoadComplete()`
in ShaderVariantReferenceSerializationEvents::OnWriteEnd().
The idea is that higher layers of class like MaterialAsset and MaterialtypeAsset will cascade back into calling
ShaderCollection::Item::InitializeShaderOptionGroup() and/or ShaderCollection::Item::TryReplaceShaderAsset() which will initialize the m_shaderOptionGroup once the ShaderAssets are loaded asynchronously.
Tested with MultiplayerSampler, LoftSample, AutomatedTesting and AtomSampleViewer.
=> Fixes #15149

Gems/Multiplayer/Code/Source/Components/LocalPredictionPlayerInputComponent.cpp, Gems/Multiplayer/Code/Tests/ClientHierarchyTests.cpp, Gems/Multiplayer/Code/Tests/TestMultiplayerComponent.cpp, Gems/Multiplayer/Code/Tests/TestMultiplayerComponent.h
The ClientInputId is defined as a uint16 that is incremented every frame. At 60 fps, it takes ~18.2 minutes for this value to wrap around back to 0. However, the LocalPredictionPlayerInputComponent wasn't accounting for wraparound, so it had logic like this:
```
if (clientInputId <= m_lastClientInputId) { return; }
```
Once m_lastClientInputId reached 65535, the clientInputId would always be <= m_lastClientInputId, and no further inputs could get processed. This manifested as a bug in MultiplayerSample where the player could still move around locally and could still see other players moving around, but the server version of their player didn't move and nobody else saw them move. They also couldn't interact with the environment since the server version didn't move.
This changes the logic …
=> Fix movement issues when client input id wraps around.

Gems/DebugDraw/Code/CMakeLists.txt, Gems/DebugDraw/Code/debugdraw_api_files.cmake, Gems/RecastNavigation/Code/CMakeLists.txt
Provide a new cmake target to avoid linking when using DebugDraw gem.
Compiled the engine and tested against Recast Navigation gem use of DebugDraw interface.
=> Added DebugDraw.API target to avoid linking

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/Attribute.h, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
=> Prefab Overrides: Fix invalid string data in DPE reflection adapter

Gems/Atom/Feature/Common/Code/Source/SplashScreen/SplashScreenPass.cpp
Ensure splash screen disables itself if there's no image found.  Otherwise, there's just a black screen on game startup and it never goes away.
Assign an invalid value to /O3DE/Atom/Feature/SplashScreen/ImagePath and see that the game still loads up
=> Splash Screen Disables Itself When Invalid Texture is Used

Gems/Atom/RHI/Code/Include/Atom/RHI/Factory.h, Gems/Atom/RHI/Code/Include/Atom/RHI/RHISystem.h, Gems/Atom/RHI/Code/Include/Atom/RHI/RHISystemInterface.h, Gems/Atom/RHI/Code/Include/Atom/RHI/Scope.h, Gems/Atom/RHI/Code/Source/RHI/Factory.cpp, Gems/Atom/RHI/Code/Source/RHI/RHISystem.cpp, Gems/Atom/RHI/Code/Source/RHI/Scope.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.h, Gems/Atom/RHI/DX12/Code/Source/RHI/IndirectBufferSignature.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/PipelineState.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/PipelineState.h, Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingPipelineState.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/Scope.cpp, Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.cpp, Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineState.cpp, Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineState.h, Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuteGroup.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuteGroupHandler.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuteGroupMerged.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuteGroupMerged.h, Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuteGroupMergedHandler.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Scope.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/StreamingImagePoolResolver.cpp, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Scene.h, Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
- Cleans up GPU markers related verbosity and management.
- Adds support for flattened markers for dx12 and Vk related gpu captures. 
- Add support to add pipeline name to the gpu capture if more than one pipeline is active
- Add support to better manage parallel encoding related markers. 
- Add support for merged groups via a cvar (r_gpuMarkersMergeGroups) in case a graphics engineer want to track payload per command list
- Add support to skip Scene updates if they are not active. 
- Other minor fixes
Tested ASV and MPS on dx12 and vulkan backends
- Vulkan with one pipeline (contains parallel encoding related scopes)
- Vulkan with multiple pipelines
- Vulkan with merged group cvar enabled
- DX12 with one pipeline (contains parallel encoding related scopes)
=> Add support for better gpu marker labels amongst many other fixes.

Code/Editor/CryEdit.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ActionManagerSystemComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ActionManagerSystemComponent.h, Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/AzToolsFrameworkTestHelpers.h
Introduces changes to allow Gems to register Action Manager items in their `bootstrap.py` scripts via Python:
- Refactors the order of operations in the initialization of the Editor to ensure `bootstrap.py` scripts are run before the Action Manager Registration Hooks are triggered;
- Exposes the Action Manager Registration Notification Bus calls ("Hooks") to be usable in Python.
The following sample code now works as intended in `bootstrap.py` files:
```
import azlmbr.action as action
def someCustomAction():
print("Hello")
def OnActionRegistrationHook(parameters):
actionProperties = action.ActionProperties()
actionProperties.name = "Custom Action"
actionProperties.description = "A custom action defined via Python"
actionProperties.category = "Python" …
```
=> Action Manager | Allow action registration hooks usage for python scripts

Code/Editor/CryEdit.cpp
Fix issue when running the Editor while the new Action Manager system is disabled. Change in https://github.com/o3de/o3de/pull/15266 would trigger the Action Manager Registration Hooks even when the system is disabled, causing crashes in systems that would connect to that bus and assume the functions would only be triggered when the system is available.
=> Action Manager | Prevent Registration Hooks from being called if the system is disabled.

Code/Tools/ProjectManager/Source/ProjectManagerWindow.cpp
Updates the Project Manager to use the display version of `engine.json` if its value is not `00.00`.
Confirmed visually.
When the display version is `00.00`
When the display version is `23.05`
=> added fix for correctly displaying engine version in window title

Gems/Multiplayer/Code/Include/Multiplayer/Components/LocalPredictionPlayerInputComponent.h, Gems/Multiplayer/Code/Source/AutoGen/LocalPredictionPlayerInputComponent.AutoComponent.xml, Gems/Multiplayer/Code/Source/Components/LocalPredictionPlayerInputComponent.cpp, Gems/Multiplayer/Code/Tests/LocalPredictionPlayerInputTests.cpp
This adds unit tests for HandleSendClientInput and HandleSendClientInputCorrection to verify that they correctly handle the case where the ClientInputId wraps around to 0. 
In the process, also found and fixed another wraparound bug with HandleSendClientInputCorrection where the logic to ignore old corrections would fail if the corrections were sent more than 10 minutes apart because there's no way to reliably tell just from the input id which correction is older if one or more wraparounds occur. The fix is to also send the client input's host frame id with the correction and ensure that we're processing a later frame or an equal frame but a later input id.
Verified that the new unit tests failed when the fixes to the Handle* methods were reverted and succeeded when the fixes were …
=> Local prediction unit tests for client input id wraparound

Code/Tools/SerializeContextTools/Dumper.cpp, Code/Tools/SerializeContextTools/Dumper.h, Code/Tools/SerializeContextTools/Runner.cpp
The `createuuid` command outputs a uuid created from a string using the SHA1 hash algorithm that O3DE uses.
This is suitable for outputting Uuids used as part of AssetIds.
The command supports a `--quiet` option for suppressing output of the string used to generate the UUID.
The `--values=<string...>` option can be specified 1 or more times to specify strings to convert.
The `--with-curly-braces=<true|false>` option formats the Uuid with `{}` surrounding it
The `--with-dashes=<true|false>` option formats the Uuid with `-` after the 8th, 12th, 16th, 20th nibble in the Uuid
The `--output-file=<file>` option allows outputting the Uuid to a file instead of stdout.
Ran the `createuuid` command with the following arguments
`SerializeContextTools.exe createuuid …
=> Adding utility command of `createuuid` to SerializeContextTools

Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.h
This PR resolves #14427. Previously, the correct parent folder was selected, but would be overridden when the treeview was updated. This adds an additional selection to the update routine.
=> Select correct parent folder.

Code/Framework/AzFramework/AzFramework/Process/ProcessCommunicator.cpp, Code/Framework/AzFramework/AzFramework/Process/ProcessCommunicator.h, Code/Framework/AzFramework/Platform/Android/AzFramework/Process/ProcessCommunicator_Android.cpp, Code/Framework/AzFramework/Platform/Common/Default/AzFramework/Process/ProcessCommunicator_Default.cpp, Code/Framework/AzFramework/Platform/Linux/AzFramework/Process/ProcessCommon.h, Code/Framework/AzFramework/Platform/Linux/AzFramework/Process/ProcessCommunicator_Linux.cpp, Code/Framework/AzFramework/Platform/Mac/AzFramework/Process/ProcessCommunicator_Mac.cpp, Code/Framework/AzFramework/Platform/Windows/AzFramework/Process/ProcessCommunicator_Win.cpp, Code/Framework/AzFramework/Platform/iOS/AzFramework/Process/ProcessCommunicator_iOS.cpp, Code/Framework/AzFramework/Tests/ProcessLaunchMain.cpp, Code/Framework/AzFramework/Tests/ProcessLaunchParseTests.cpp, Code/Framework/AzFramework/Tests/ProcessLaunchTestTokens.h, Code/Framework/AzFramework/Tests/process_launch_test_files.cmake, Registry/Platform/Mac/streamer.editor.setreg, Registry/Platform/Windows/streamer.editor.setreg, Registry/Platform/Windows/streamer.game.debug.setreg, Registry/Platform/Windows/streamer.game.profile.setreg, Registry/Platform/Windows/streamer.test.setreg, Registry/streamer.editor.setreg, Registry/streamer.game.debug.setreg, Registry/streamer.game.profile.setreg, Registry/streamer.game.setreg, Registry/streamer.setreg, Registry/streamer.test.setreg
fixes #15332 and also fixes a deadlock discovered by fixing that fix, in windows.
The original bug was discovered here: https://github.com/o3de/o3de-extras/issues/118 and applies to o3de-extras, but the actual problem is in the o3de source code.
see the bug report above for a description of the problem.
For the windows deadlock, the same PR (this one) also fixes the windows deadlock which was always there, but the new test reveals.
Order that this happened in
1. discover the bug on linux and develop a fix using epoll, yay!
2. write a test to ensure its working correctly and that all the data is present and read regardless of flush/buffered
3. run the test all green on linux, push to branch!
4. …
=> Fix file handle starvation linux

Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArrayFeatureProcessor.cpp
Previously if a single decal material was missing, all decals would break. In addition to being a bug, it also made it difficult to track down which was the offending decal. With this change, it simply warns for the missing material's asset id, and all other decals continue to work.
Fixes #15193
Tested using repro steps from original bug.
=> All decals no longer break if a decal material is missing

Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManagerInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManagerInternalInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/HotKey/HotKeyManagerInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/HotKey/HotKeyManagerInternalInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/MenuManagerInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/MenuManagerInternalInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ToolBar/ToolBarManagerInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ToolBar/ToolBarManagerInternalInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/UICore/ConsoleTextEdit.cpp
Reverts a recent change that added includes to `AzCore/Interface/Interface.h` in Action Manager interfaces. The includes had been intentionally removed to improve build times. 
Verified call sites include the interface headers where needed, and the Editor builds correctly.
=> Action Manager | Revert interface includes change that impacted optimizations

Code/Framework/AzCore/AzCore/Memory/SystemAllocator.cpp
`SystemAllocator` compilation failed in monolithic release due to a "Warning as error" when AZ_ENABLE_TRACING is defined.
Compile a project in monolithic with release configuration.
=> Fix SystemAllocator compilation in monolithic release (vs 2022)

Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.h
This PR adds a check on component validity. If the component is not valid, then skip 'DoRefresh()' and 'NotifyResetDocument()' in `DPEComponentAdapter`.
Looks like it can fix a couple of delete-component crashes:
- https://github.com/o3de/o3de/issues/15184
- https://github.com/o3de/o3de/issues/15097 (still verifying)
- Delete AudioAnimation component
Manually tested in editor to delete different components which could cause crashes earlier.
=> Check component validity before DoRefresh() in DPE component adapter

Gems/Atom/RHI/Code/Source/RHI/ValidationLayer.cpp
Commit https://github.com/o3de/o3de/commit/d23949373490b39745e4b4314c1728631f0970cf disabled Vulkan validation on all build types. The change was probably commited accidentally (@jjjoness).
Vulkan device validation is now enabled in Debug builds by default again and the command line parameter "rhi-device-validation" is checked again.
Windows & Vulkan. Tested the command line parameter "rhi-device-validation"
=> Reenable checking for vulkan validation in non release builds

Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Mesh/MeshComponentBus.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h, Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp, Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.h
This PR adds an event to know when a new ObjectSrg is created for a mesh or an actor.
This allows to easily sets custom per-object data using only a few lines of code, usage example at the end.
The main issue is that when you acquire a mesh handle, ObjectSrg have not yet been created, and except waiting for the next tick there's not way to get them.
This PR adds a new MeshComponent event which allows us to be able to know when a new ObjectSrg has been created by the mesh feature processor. This way we can configure it using our already configured data, or query all object SRGs when data changes.
This PR was tested using a similar simple component as present at the end of this PR, adding the component, instancing a prefab containing a mesh/material and colored components and changing the …
=> Add OnObjectSrgCreated event

AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/TestSuite_Main.py
- Skips test_PhysXColliderSurfaceTagEmitter_E2E_Editor
- Ran updated Dynamic Vegetation test suite
=> Skipping test that is now failing due to an asset removal

scripts/o3de.py, scripts/o3de/o3de/export_project.py, scripts/o3de/o3de/utils.py, scripts/o3de/tests/CMakeLists.txt, scripts/o3de/tests/test_export_project.py, scripts/o3de/tests/test_utils.py
This PR addresses users running custom export scripts for processing various build tasks involved with releasing their projects to O3DE. This is the first step for the [Project Export CLI RFC](https://github.com/o3de/sig-content/blob/main/rfcs/rfc-123-project-export-cli.md).
There are two APIs: `process_command` and `execute_python_script`, which when combined with the new `O3DEScriptExportContext` provide high flexibility for users to design the workflows as they see fit, with the convenience of accessing existing APIs from O3DE CLI.
Typically export scripts are part of a user's project, but the CLI can also execute export scripts outside of the user's project if they include the project's path in the invocation.
With the PR, the following is possible:
```python
#test_export.py
import os …
```
=> Implementing Project Export CLI MVP, including ablity to execute user's python scripts and process any commands. Unit tests are also included

Code/Editor/EditorViewportCamera.cpp, Code/Editor/EditorViewportCamera.h, Code/Editor/Lib/Tests/Camera/test_EditorCamera.cpp, Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
Fixes https://github.com/o3de/o3de/issues/14894
Fixes https://github.com/o3de/o3de/issues/9151
Fixes https://github.com/o3de/o3de/issues/6243
The crux of the change is updating...
```c++
const AZ::Vector3 forward = (center - cameraTransform.GetTranslation()).GetNormalized();
```
to...
```c++
const AZ::Vector3 forward = [&center, &cameraTransform]
{
const AZ::Vector3 forward = (center - cameraTransform.GetTranslation()).GetNormalized();
// if the camera is looking directly up or down, pitch the camera down or up respectively to avoid
// a singularity when creating the lookat transformation below
if (const float forwardDot = forward.Dot(AZ::Vector3::CreateAxisZ()); AZ::IsCloseMag(AZ::Abs(forwardDot), 1.0f, 0.001f))
{
return AZ::Transform::CreateFromQuaternion( …
```
=> Fix for camera go-to-entity functionality when looking directly up or down

AutomatedTesting/Assets/Objects/PxMesh/test.fbx, AutomatedTesting/Assets/Objects/PxMesh/test.fbx.assetinfo, AutomatedTesting/Assets/Objects/PxMesh/test.mtl, AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/PhysXColliderSurfaceTagEmitter_E2E_Editor.py, AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/TestSuite_Main.py
- Re-adds an asset that was removed causing test_PhysXColliderSurfaceTagEmitter_E2E_Editor to fail
- Re-enables the skipped test
- Fixes https://github.com/o3de/o3de/issues/15456
- Ran updated Dynamic Vegetation suite
=> Re-adding removed asset and re-enabling skipped test

Gems/LmbrCentral/Code/Source/LmbrCentralEditor.cpp, Gems/LmbrCentral/Code/Source/Shape/EditorAxisAlignedBoxShapeComponent.cpp, Gems/LmbrCentral/Code/Source/Shape/EditorAxisAlignedBoxShapeComponentMode.cpp, Gems/LmbrCentral/Code/Source/Shape/EditorAxisAlignedBoxShapeComponentMode.h
Correctly registers the Axis Aligned Box Component Mode so that actions are updated correctly.
Fixes #15416
=> Action Manager | Fix Axis Aligned Box Component Mode

Gems/Atom/Feature/Common/Code/Mocks/MockMeshFeatureProcessor.h
The same function already exists in line 46.
=> Removed duplicated function SetExcludeFromReflectionCubeMaps in MockMeshFeatureProcessor

AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_tools_utils.py, AutomatedTesting/Gem/PythonTests/Atom/tests/MaterialCanvas_Atom_BasicTests.py, AutomatedTesting/Gem/PythonTests/Atom/tests/MaterialEditor_Atom_BasicTests.py, AutomatedTesting/Gem/PythonTests/Atom/tests/MaterialEditor_Atom_PeriodicTests.py
Changes atom tools document system registry settings from Python test scripts to disable warning and error message boxes that can potentially block test progression. All of the messages that would be displayed in the user facing message boxes will still be logged.
Tests continue to run successfully locally without error.
=> Disable warning and error message box UI in material editor and material canvas tests

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/FullscreenTrianglePass.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/FullscreenTrianglePass.cpp
Shader hot reload did not work for the `FullscreenTrianglePass`. The `ShaderReloadNotificationBus` overrides did not actually reload the shader, but only called `UpdateSrg` for the old shader. The new code actually reloads the shader.
I also made the `ShaderReloadNotificationBus` overrides protected (formerly they were private), so derived passes can react to reloaded shaders.
Windows and Vulkan. Tested hot reload on a custom compute pass.
=> Fixed Shader hot reload for FullscreenTrianglePass

Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/GraphDocument.cpp, Gems/GraphModel/Code/Include/GraphModel/Integration/BooleanDataInterface.h, Gems/GraphModel/Code/Include/GraphModel/Integration/FloatDataInterface.h, Gems/GraphModel/Code/Include/GraphModel/Integration/IntegerDataInterface.h, Gems/GraphModel/Code/Include/GraphModel/Integration/ReadOnlyDataInterface.h, Gems/GraphModel/Code/Include/GraphModel/Integration/StringDataInterface.h, Gems/GraphModel/Code/Include/GraphModel/Integration/VectorDataInterface.inl, Gems/GraphModel/Code/Source/Integration/BooleanDataInterface.cpp, Gems/GraphModel/Code/Source/Integration/FloatDataInterface.cpp, Gems/GraphModel/Code/Source/Integration/ReadOnlyDataInterface.cpp, Gems/GraphModel/Code/Source/Integration/StringDataInterface.cpp
Refresh the node property displays in the graph view whenever properties are edited using the inspector.
Resolves https://github.com/o3de/o3de/issues/13875
Tested setting checkbox and other properties in the inspector to see them update in the graph view.
=> Material Canvas: Fix checkbox and node property displays refreshing

Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/GraphView.cpp, Gems/GraphCanvas/Code/Source/Components/SceneComponent.cpp, Gems/GraphModel/Code/Include/GraphModel/Integration/GraphCanvasMetadata.h, Gems/GraphModel/Code/Include/GraphModel/Integration/GraphController.h, Gems/GraphModel/Code/Source/GraphModelSystemComponent.cpp, Gems/GraphModel/Code/Source/Integration/GraphCanvasMetadata.cpp, Gems/GraphModel/Code/Source/Integration/GraphController.cpp
This change implements graph model selection state serialization so that it can be saved and restored when graphs are loaded and after undo and redo operations. Prior to these changes, loading, undue, and reduce selected all nodes in the graph.
In order to accomplish this, rather than creating new components and injecting them into all of the graph canvas native types, graph controller creates a router for entity state save data to inject and retrieve selection and position data with the rest of the metadata.
Additionally, this change adds batching for drag and drop operations so that tracking multiple nodes from the node palette can be undone and redone as an atomic operation.
Resolves https://github.com/o3de/o3de/issues/13919
Tested by creating multiple combinations of nodes, dragging …
=> Material Canvas: Save and restore graph element selection on load, undo, and redo

AutomatedTesting/Registry/material_pipelines.setreg, Gems/Atom/Feature/Common/Assets/Textures/VRSTexture.attimage, Gems/Atom/RHI/Code/Source/RHI/ValidationLayer.cpp
- Enables MultiView pipeline for Automated Testing
- Enables Vk validation
- Setting VRS image to R8_Uint as by default dx12 only works with this format. For Vulkan if openxr is enabled we pick the correct format based on device requirement. For quest 2 it automatically switches to R8G8.
Tested Material canvas and openxrtest
=> Fixed material canvas crash when switching pipelines plus fixes mesh rendering

Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceToTemplateInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceToTemplatePropagator.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceToTemplatePropagator.h, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.h, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndo.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoAddEntity.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoAddEntityAsOverride.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoBase.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoBase.h, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoComponentPropertyEdit.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoComponentPropertyOverride.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoDelete.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoDeleteAsOverride.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoEntityOverrides.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoUtils.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoUtils.h, Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/Link/SingleInstanceMultiplePatchesBenchmarks.cpp, Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUndoLinkTests.cpp
This PR simplifies and improves utility functions in 'PrefabUndoUtils'. They are used to encapsulate repeated code to generate undo/redo patches and update value in cached instance DOM.
The purpose of this PR is to remove duplicate code and avoid confusion in usage.
**Change List:**
- Keep functions for entity-level or property-level updates. Entity-level would call property-level version.
- Replaced `GenerateUpdateEntityPatch` by `GenerateAndAppendPatch`.
- Changed to initialize undo/redo patch arrays in member initialization list, rather than calling `SetArray` before usage.
- For path helper function, use 'Append' to 'Prepend' in naming, and use assertions to check if the provided patches is array type.
Does not alter workflow logic. Passed existing unit tests.
=> Simplify and improve prefab undo utility functions

Code/Tools/SceneAPI/SceneBuilder/Importers/AssImpMaterialImporter.cpp, Gems/Atom/Feature/Common/Code/Source/Material/MaterialConverterSystemComponent.cpp
Signed-off-by: Zhang-Baochong <zhangbaochong@huawei.com>
Import model with transparent material, the material is opaque in o3de editor.
Import model with transparent material, check if it is transparent in editor.
=> Model import support transparent material.

Gems/DiffuseProbeGrid/Code/Source/EditorComponents/EditorDiffuseProbeGridComponent.cpp
Signed-off-by: Zhang-Baochong <zhangbaochong@huawei.com>
There is no progress bar when DDGI bakes the texture, so user cannot judge if the baking is running.
For this, add a progress bar when baking texture.
Manually tested in editor.
1.Open Editor.
2.Create a new Entity.
3.Add `Diffuse Probe Grid` Component.
4.Click `Bake Textures` Button
=> add progress bar for ddgi bake textures.

Gems/Atom/RHI/Vulkan/Code/Source/RHI/DescriptorSet.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/DescriptorSetLayout.cpp
Removes a Vulkan validation error when Raytracing acceleration structures are in the unbound array of an SRG.
Raytracing acceleration structures were wrongly bound as storage buffers, which led to the following validation error:
```
<09:32:53> [Error] (vkDebugMessage) - [ERROR][Validation] Validation Error: [ VUID-VkWriteDescriptorSet-descriptorType-00331 ] Object 0: handle = 0xe76bbd0000001fba, name = ..., type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0xde8c9ed7 | vkUpdateDescriptorSets() pDescriptorWrites[7] failed write update validation for VkDescriptorSet 0xe76bbd0000001fba[...] with error: Write update to VkDescriptorSet 0xe76bbd0000001fba[...] allocated with VkDescriptorSetLayout 0xc20bd20000000656[] binding #8 failed with error message: Attempted write update to buffer …
```
=> Fixed a Vulkan validation warning with Raytracing Acceleration structures

Gems/Multiplayer/Code/Source/Components/NetworkCharacterComponent.cpp, Gems/Multiplayer/Code/Source/Components/NetworkHitVolumesComponent.cpp, Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp, Gems/PhysX/Code/Source/PhysXCharacters/API/CharacterController.cpp, Gems/PhysX/Code/Source/PhysXCharacters/API/CharacterController.h, Gems/PhysX/Code/Tests/CharacterControllerTests.cpp
This fixes the hit volumes on networked characters. Previously, the character physics didn't support rotation of the character controller, so the attached hit volumes always stayed unrotated, regardless of the visual character's rotation. With this fix, the hit volumes rotate with the networked characters.
Changes:
* Changed the NetworkCharacterComponent to set the rotation on the physics character.
* Changed the CharacterController to store a copy of the rotation and correctly apply it to the shadow body, and added a unit test to trivially validate that this works.
* Changed the NetworkHitVolumes to destroy themselves when the physics character is destroyed, so that they'll recreate correctly when a new physics character is created. (This fixes a teleportation bug with the hit volumes …
=> Fix networked character physics hit volumes

Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/AmbientOcclusion.preset, Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/Emissive.preset
This changes the presets for Emissive and Ambient Occlusion textures to generate mipmaps by default. Previously, they weren't generating mipmaps. Mipmap generation allows these textures to work better with mip streaming and pool budgets.
Ran AP on MPS and verified that the emissive and AO textures were now generating mipmaps.
=> Emissive and AO presets now generate mips by default.

AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/TestSuite_Main.py
- Removes skip marker from fixed test (missed file add in https://github.com/o3de/o3de/pull/15464)
- Now with 100% more fix for https://github.com/o3de/o3de/issues/15456
- Ran updated test suite
=> Removing skip marker from fixed test

Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Image/ImageSystemDescriptor.h, Gems/Atom/RPI/Code/Source/RPI.Public/Image/ImageSystem.cpp, Gems/Atom/RPI/Code/Source/RPI.Reflect/Image/ImageSystemDescriptor.cpp, Gems/Atom/RPI/Registry/atom_rpi.setreg
Add streaming image mip bias setting to setting registry: "/O3DE/Atom/RPI/Initialization/ImageSystemDescriptor/SystemStreamingImagePoolMipBias"
Also add value syncing for image streaming cvars and settings. 
Now user can use following way to setup texture mip bias when start app:
1. setting registry  "/O3DE/Atom/RPI/Initialization/ImageSystemDescriptor/SystemStreamingImagePoolMipBias" 
2. use --r_streamingImageMipBias=x in application's command line
3. add the cvar to <project-root>/Cache/<platform>/user.cfg
Editor
=> Setting registry support for r_streamingImageMipBias

Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/ActionDispatcher.h, Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/ImmediateModeActionDispatcher.h, Code/Framework/AzManipulatorTestFramework/Source/ImmediateModeActionDispatcher.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/ManipulatorManager.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/ManipulatorManager.h, Code/Framework/AzToolsFramework/Tests/ManipulatorCoreTests.cpp
Fixes #5748
Fixes irritating issue with camera when pressing RMB while interacting with a manipulator after having pressed RMB.
> Note: The changes to `ImmediateModeActionDispatcher` were needed to bring the behavior of the test code more inline with the Editor code. The logic more closely matches `ViewportManipulatorController.cpp` (see line 160 in that file).
```
MouseInteraction mouseInteraction = m_mouseInteraction;
if (overrideButton)
{
mouseInteraction.m_mouseButtons.m_mouseButtons = static_cast<AZ::u32>(overrideButton.value());
}
```
1. Followed reproduction steps in #5748 and verified fix
2. Created an integration test to verify the behavior before/after
```bash
[----------] 1 test from …
```
=> Fix for camera look behavior getting stuck on

Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BreadCrumbs.cpp
Fixes the behavior of the Breadcrumbs widget so that it correctly collapses the path portions that don't fit the current size, and correctly populates the overflow menu.
Before:
After:
=> Fix Breadcrumbs widget handling of resizing

Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp, Code/Tools/AssetProcessor/native/resourcecompiler/rccontroller.cpp, Code/Tools/AssetProcessor/native/resourcecompiler/rcjoblistmodel.cpp
Fixed a crash when processing assets in a case with mixed failures.
FinishJob was called twice in some cases, causing this crash.
Cleaned up the assert **message.**
Tested with Multiplayer Sample project. Processing assets on an empty cache crashes without this fix, and does not crash with this fix.
=> Fixed a crash when processing assets in a case with mixed failures

Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/MaterialTypeAsset.cpp
Removed unnecessary assert when loading non-serialized data in MaterialTypeAsset::PostLoadInit().
Did the same steps as described in this bug: https://github.com/o3de/o3de/issues/15488, and the Editor doesn't crash anymore.
Also did the other related bug described by @amzn-tommy in the same GHI and the bug doesn't occur anymore (Using an MC generated material, saving the level, closing the Editor, reopening the Editor and the level).
=> Closes #15427

Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
Fixed an edge case that the m_isDrawMotion wasn't set correctly if the mesh asset was already loaded when creating the MeshHandle
ASV SkinemeshMotionVector test
=> Skinmesh motion vector fix

Code/Tools/TestImpactFramework/Frontend/Console/Common/Code/Source/TestImpactTestSequenceNotificationHandler.cpp, Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/Target/Native/TestImpactNativeTestTarget.cpp, Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/Target/Native/TestImpactNativeTestTarget.h, Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Job/TestImpactNativeShardedTestJobInfoGenerator.h, scripts/build/Platform/Windows/build_config.json
This PR fixes the accidental opting in of all test targets to the test sharding optimization.
This PR also adds test target stdout to the native TIAF runtime, but only outputs the stdout for test targets that fail in any way.
This PR will be tested in AR.
=> Fix accidental opt-in of all test targets to sharding.

Code/Editor/LevelFileDialog.cpp
Fixes #13445
Automatically expands the file tree for the "Open Level" dialog.
Before:
After:
=> Automatically expand file tree in "Open Level" dialog

Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportScene.cpp
Move check for invalid render pipeline asset ID so that it's handled on all code paths
I have been running with these changes locally for some time. 
Confirmed that code still compiles and render pipelines are updated when changed from the viewport drop down.
=> Material Canvas: Move check for invalid render pipeline asset ID so that it's handled on all code paths

Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/GraphCompiler.cpp, Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/GraphDocument.cpp
Resetting graph compiler data between state transitions and updating status messages
Confirmed that code still compiles.
Confirmed that state changes display the correct messages.
Confirmed that assets and data captured with the graph compiler and job are released with job completion, cancellation, and before exit.
=> Material Canvas: Resetting graph compiler data between state transitions

Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/StringNodePropertyDisplay.cpp, Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/VectorNodePropertyDisplay.cpp, Gems/GraphModel/Code/Include/GraphModel/Integration/GraphController.h, Gems/GraphModel/Code/Source/Integration/GraphController.cpp
- Changing the value of a string property display will now cause the node to grow with the length of the string and shrink to reclaim wasted space.
- Vector property displays now correctly set the container and proxy widget sizes together correctly. Both now also consider visibility of the optional button or icon. This eliminates the popping and displacement whenever hovering over a node containing a vector.
- The graph model graph controller now automatically adjusts the size of any affected nodes whenever connections are added or removed. This ensures that nodes always take up the minimum amount of space whenever all of their slots with properties have connections.
Resolves https://github.com/o3de/o3de/issues/13918
Resolves https://github.com/o3de/o3de/issues/13916
- Tested creating, …
=> Material Canvas: Fixed multiple issues with node resizing

Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManager.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManager.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/HotKey/HotKeyManager.cpp, Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
This PR addresses an issue where sometimes shortcuts weren't working properly in dock widgets depending on which widget the user had attempted to focus. The particular use-case that exposed this issue was when the user had first opened the Script Canvas tool, the `Ctrl+N` hot-key would trigger the Editor's main "New Level" dialog instead of creating a new graph in Script Canvas. This is because if the user had just opened Script Canvas (or had clicked somewhere in its drop area, menu bar or dock widget resize handles), the Script Canvas main widget wouldn't actually get focus because those areas don't accept focus, so instead the focus widget would become the `DockWidget` that owns the Script Canvas widget. So because the action context watcher was only listening for shortcut events on …
=> Fixed issue with shortcuts not working in a dock widget depending on focus

Gems/Atom/Asset/Shader/Code/Source/Editor/AzslShaderBuilderSystemComponent.cpp, Gems/Atom/Asset/Shader/Code/Source/Editor/HashedVariantListSourceData.h, Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderVariantAssetBuilder.cpp, Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderVariantAssetBuilder.h, Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderVariantListBuilder.cpp, Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderVariantListBuilder.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Shader/ShaderVariantAsyncLoader.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/IShaderVariantFinder.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderAsset.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderVariantTreeAsset.h, Gems/Atom/RPI/Code/Source/RPI.Public/Shader/ShaderVariantAsyncLoader.cpp, Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderAsset.cpp
This new version doesn't consume *.shadervariantlist files. Instead it consumes *.hashedvariantlist and *.hashedvariantinfo files.
As a reminder, the ShaderVariantListBuilder consumes *.shadervariantlist and produces Intermediate Assets: One *.hashedvarianlist + Several *.hashedvariantinfo
In turn, this new ShaderVariantAssetBuilder has two inputs:
- First Input: *.hashedvariantlist. Output: ShaderVariantTreeAsset (*.azshadervarianttree)
- Second Input: *.hashedvariantinfo. Ouputs: ShaderVariantAsset (*.azshadervariant) one for each combination of RHI+Supervariant+StableId.
**What's the benefit**:
The main benefit is that whenever the original *.shadervariantlist file changes, let's say because the user added a new variant, or because the user modified an existing variant, only the …
=> Updated the ShaderVariantAssetBuilder.

Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerEditorServerBus.h, Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp, Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.h, Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorAutomation.cpp, Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorAutomation.h, Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
When connecting from the Editor to a multiplayer server, we would see intermittent timeouts during the level send causing the Editor/server connection to fail, even though the level send would retry multiple times over 20 seconds. Upon further investigation, the root cause was that the output of the server was being piped back to the Editor process. If these pipes fill up, the entire server process locks up on outputting to the pipe until the pipe is free to send again. So if the server attempted to print too much to stdout during the connection process, and the client was in a tight loop attempting to retry level sends without processing the pipes, the connection would fail.
The solution is to add "m_serverProcessTracePrinter->Pump();" in the retry loop to ensure that the pipes continue …
=> Fixed the intermittent timeouts when connecting to editor server

Code/Tools/AssetProcessor/native/AssetManager/PathDependencyManager.cpp, Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp, Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.h
There are two code paths when resolving product path dependencies with wildcards.
1. The product with a dependency checks all existing files already resolved in the database.
2. Later jobs finish, and the existing previously emitted wildcard path dependencies are checked against the newly completed files.
Without this change, there was a difference in those code paths:
1. This did a database search with database style wildcard. This meant a wildcard matched against the whole string, and didn't stop at directory markers.
2. This did a path search with path style wildcards. This meant a wildcard stopped matching at directory change markers.
This meant that, if you re-processed a file with a wildcard dependency after the asset processor went idle, you could get new dependencies, due to the …
=> Standardized path resolution for wildcard product dependencies.

Code/Tools/AssetBundler/source/models/SeedListTableModel.cpp, Code/Tools/AssetBundler/source/models/SeedListTableModel.h
Without this change: When you view a seed list with a missing asset in the Asset Bundler GUI, it displays a blank line. There is an error message in the log output at the bottom of the screen, but it's still confusing having a blank line.
With this change: Instead a blank line, the asset hint and ID are displayed (if available), and an error icon is displayed to call attention to this row.
This change addresses this issue: https://github.com/o3de/o3de/issues/15271
This is what this change looks like:
Manual testing - we don't have automation for asset bundler GUI available yet.
=> When an asset in a seed file is no longer available, an error icon and error message is now displayed instead of a blank line.

Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
Temporary fix for "Basic search is broken in table view #15524" to allow release. Permanent fix is in progress. 
From the bug description:-
"If we are unable to fix this bug before the general release, Luis, Daniel and I spoke about a good back up plan being that we disable search in table view until we can get the feature working. We would also need to prevent a user from switching into table view IF a use started a search in a different view and then tried to switch into table view while a search is in process."
Checked that search is not available in Table View mode and TableView button is disabled if a search is in progress.
=> Temporary fix ready for release

Gems/SceneProcessing/Code/Source/Generation/Components/MeshOptimizer/MeshOptimizerComponent.cpp
Fixed a crash that occurred when a scene filename contained invalid characters.
Fixes https://github.com/o3de/o3de/issues/6083
Manually tested by putting a . in the filename of an FBX file
=> Scene Builder - Fix handling of invalid scene file names

Code/Framework/AzManipulatorTestFramework/CMakeLists.txt, Gems/ScriptCanvasTesting/Code/CMakeLists.txt
This PR opts out two test targets that seem to be dependent on state not available within the TIAF native pipeline stage. As these failures cannot be reproduced locally, they will be moved back to CTest.
Tested in AR.
=> Opt out failing tests that cannot be reproduced locally.

Gems/Atom/RPI/Code/Source/RPI.Public/MeshDrawPacket.cpp
Fixes https://github.com/o3de/o3de/issues/15531
The mesh draw packet wasn't properly setting the initial root constant data, leading to a vulkan validation error.
Tested in the editor and material canvas on the branch from https://github.com/o3de/o3de/pull/15491, which adds a root constant to the default draw srg.
=> Fix for GHI-15531: Vulkan Validation Error: Push Constants not set

Code/Tools/AssetProcessor/native/connection/connectionManager.cpp
Without this change: When you remove a user created connection in the asset processor, it wasn't properly saving that removal, because the connection wasn't removed from the map until later, when it was fully deleted. Now, the connection is immediately removed from the map, so that that when the settings are saved, the connection is properly deleted.
This addresses this issue https://github.com/o3de/o3de/issues/7673
1. Add new connection in the asset processor
2. Give it an obvious name
3. Close asset processor
4. Open asset processor again - verify the created connection is there
5. Remove the connection
6. Close asset processor
7. Open asset processor
8. View the connection tab
Without this change: The connection shows up again on step 8, because the settings were saved with the …
=> Asset processor now properly saves the removal of asset connections

Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/AssetBuilderSDK.cpp, Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/AssetBuilderSDK.h, Code/Tools/AssetProcessor/native/resourcecompiler/RCQueueSortModel.cpp, Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp, Code/Tools/AssetProcessor/native/tests/utilities/assetUtilsTest.cpp, Code/Tools/AssetProcessor/native/utilities/assetUtils.cpp, Gems/Atom/Asset/Shader/Code/Source/Editor/AzslShaderBuilderSystemComponent.cpp, Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderVariantAssetBuilder.cpp
Added `OrderOnly` job dependency.
This new job dependency is helpful when it is needed that **Asset A** completes before **Asset B** runs,
but don't re-run **Asset B** just because **Asset A** ran. In other words, **Asset A** does not modify the
fingerprint of **Asset B**.
The `ShaderVariantAssetBuilder` is the first builder that takes advantage of this new job dependency because it needs the `ShaderVariantTreeAsset` to complete before any `ShaderVariantAsset` job starts, But `ShaderVariantAsset`s do not rebuild simply because the `ShaderVariantTreeAsset` was rebuilt.
Solves #15428
1. Added two unit tests:
1.1. TEST_F(AssetProcessorManagerTest, JobDependencyOrderOnly_MultipleJobs_EmitOK), based on TEST_F(AssetProcessorManagerTest, JobDependencyOrderOnce_MultipleJobs_EmitOK) with proper …
=> Added "OrderOnly" job dependency.

AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
disables a test in the script canvas periodic test suite when run from linux. This test fails the incremental daily builds. Associated GHI to investigate and fix the failing test: https://github.com/o3de/o3de/issues/15553
Test suite run successfully through pytest runner in win10 environment
=> Disable NodeCategory_ExpandOnClick when running test suite in Linux

Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabComponentAdapter.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabComponentAdapter.h, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorDisabledCompositionBus.h, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorDisabledCompositionComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorDisabledCompositionComponent.h, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorPendingCompositionBus.h, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorPendingCompositionComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorPendingCompositionComponent.h, Code/Framework/AzToolsFramework/Tests/ComponentModeTestFixture.cpp, Code/Framework/AzToolsFramework/Tests/ComponentModeTestFixture.h
Fixes and unblocks https://github.com/o3de/o3de/issues/15509
This PR is a temp fix for crashes that happen when we add pending/disabled components to an entity because of empty component alias assertions in `PrefabComponentAdapter`. See the ticket for more details.
It is a temp fix that keeps the component alias empty for pending and disabled components, but instead in adapter it changes to assert only when the component is not disabled or pending.
I created another issue to address the empty component alias issue: https://github.com/o3de/o3de/issues/15546, which I feel like it might not be easily fixed.
Tested in editor. Crashes no longer happen for these operations:
- Add a pending component 'AudioAnimation' (or 'VegetationSurfaceMaskFilter') to an entity, disable and enable it.
- Add a …
=> Fix add-component crashes for disabled and pending components

Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceComposite.shader, Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceTrace.shader, Gems/Atom/Feature/Common/Code/Source/Shadows/ProjectedShadowFeatureProcessor.cpp
Add msaa super variant for reflection shaders since they are using msaa textures.
Remove cachePass in projected shadow feature processor since it's called from render pipeline change event when connect scene notification bus. (otherwise it may report error when it's called twice)
=> Fixes to support msaa count 1 and misc

Gems/AWSGameLift/cdk/aws_gamelift/gamelift_stack.py
Fixes `AttributeError: type object 'CfnBuild' has no attribute 'S3LocationProperty'` in AWSGameLift gem `gamelift_stack.
Currently, running `cdk deploy -c upload-with-support-stack=true` results in the following error:
```
Traceback (most recent call last):
File "C:\Users\USER\source\o3de\gems\AWSGameLift\cdk\app.py", line 43, in <module>
feature_struct = AWSGameLift(
File "C:\Users\USER\source\o3de\gems\AWSGameLift\cdk\.venv\lib\site-packages\jsii\_runtime.py", line 112, in __call__
inst = super().__call__(*args, **kwargs)
File "C:\Users\USER\source\o3de\gems\AWSGameLift\cdk\aws_gamelift\aws_gamelift_construct.py", line 50, in __init__
self._feature_stack = GameLiftStack(
File "C:\Users\USER\source\o3de\gems\AWSGameLift\cdk\.venv\lib\site-packages\jsii\_runtime.py", line 112, in __call__ …
```
=> Fix CfnBuild.StorageLocationProperty in gamelift_stack

Code/Framework/AzFramework/AzFramework/Process/ProcessCommunicator.h, Code/Framework/AzFramework/AzFramework/Process/ProcessCommunicatorTracePrinter.cpp, Code/Framework/AzFramework/AzFramework/Process/ProcessCommunicatorTracePrinter.h, Code/Tools/AssetProcessor/native/utilities/Builder.cpp, Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
This improves upon a previous PR by introducing threaded trace printing for the editor/server connection instead of relying on well-placed Pump() calls. Also fixed a tiny bug where the tick bus wouldn't get connected to if server logging wasn't enabled, so the detection of unexpected server disconnects also wouldn't happen in that case.
In adding this support, I also left the previous pump-based trace printing because the Asset Builders rely on it pretty deeply, since they expect the trace printing to occur on specific threads. The change was spiraling out too far to get the Asset Builders to use the threaded trace printing, so I left them working the same as before with a comment explaining the situation.
Rebuilt the entire cache in the AP to verify that builder logging still works.
Ran …
=> Switch trace processing to use threads for editor/server connection without impacting AP or asset builders

scripts/o3de/o3de/download.py
- Ensure SHA256 remote template checks are case insensitive.
[Powershell's Get-FileHash](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-filehash?view=powershell-7.3) method used for generating the zip SHA265 outputs uppercase, whereas the ProjectManager's python script using lowercase.
- Corrected a small fypo
Fixes #12443
Attempted to download the MultiplayerTemplate and see that it successfully matches its uppercase hash.
=> Project Manager: Remote Template SHA265 Compare Using Case Insensitive Hash Check

Gems/Atom/RHI/DX12/Code/CMakeLists.txt, Gems/Atom/RHI/DX12/Code/Source/Platform/Common/Clang/amd_dx12ma_clang.cmake, Gems/Atom/RHI/DX12/Code/Source/Platform/Common/msvc/amd_dx12ma_msvc.cmake, Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/Device_Windows.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/BufferD3D12MemoryAllocator.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/BufferD3D12MemoryAllocator.h, Gems/Atom/RHI/DX12/Code/Source/RHI/BufferMemoryAllocator.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/BufferMemoryAllocator.h, Gems/Atom/RHI/DX12/Code/Source/RHI/BufferPool.h, Gems/Atom/RHI/DX12/Code/Source/RHI/Conversions.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/Conversions.h, Gems/Atom/RHI/DX12/Code/Source/RHI/DX12.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/Device.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/Device.h, Gems/Atom/RHI/DX12/Code/Source/RHI/MemoryView.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/MemoryView.h, Gems/Atom/RHI/DX12/Code/Source/RHI/ReleaseQueue.h, Gems/Atom/RHI/DX12/Code/amd_dx12ma_files.cmake, Gems/Atom/RHI/DX12/Code/atom_rhi_dx12_private_common_files.cmake, Gems/Atom/RHI/DX12/External/AMD_D3D12MemoryAllocator/v2.0.1/dx12ma/D3D12MemAlloc.cpp, Gems/Atom/RHI/DX12/External/AMD_D3D12MemoryAllocator/v2.0.1/dx12ma/D3D12MemAlloc.h, Gems/Atom/RHI/DX12/External/AMD_D3D12MemoryAllocator/v2.0.1/dx12ma/D3D12MemAlloc.natvis, Gems/Atom/RHI/DX12/External/AMD_D3D12MemoryAllocator/v2.0.1/dx12ma/LICENSE.txt
This PR enables O3DE to use AMD's D3D12MemoryAllocation library as a replacement for our page sub-allocators for buffer pools.
This has the advantage that we are now using resource objects that the D3D12 api is aware of so the names of the buffers show up in debugging captures. The current sub-allocator is re-using a subsection of an existing buffer with all the complexity that comes along with that (can't state transition just 1 buffer, no visible debug name, needs internal tools to see where memory is spent, etc)
It also moves O3DE over to use an externally tested piece of code.
=> Add option to use AMD's D3D12MemoryAllocation library for buffer allocations

Gems/Atom/RPI/Code/Source/RPI.Public/MeshDrawPacket.cpp
Fixes https://github.com/o3de/o3de/issues/15561
Fix error message, which wasn't handling the case where the pipeline's rootConstantLayout was non-null, but its size was 0. The error message should not fire in that case.
Ran the editor on latest development, and the error no longer occurs.
=> Fix for GHI-15561 : MeshDrawPacket errors in console

Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.h
Fixes a bug that happened because the editor allowed a folder to be dropped on itself in the Asset Browser Treeview.
Tried dropping a folder on itself and it no longer does anything.
=> Fixes dropping a folder on itself in Asset Browser

Gems/Atom/RHI/DX12/Code/Source/RHI/BufferPool.h
BufferMemoryAllocator::Descriptor still needs to be defined for BufferD3D12MemoryAllocator path
Feature is already tested, this fixed non-unity build.
=> Fix non-unity build

Gems/Atom/RHI/DX12/Code/Source/RHI/CommandListBase.cpp
Fix for an asserting firing off in case hw/driver did not support msaa sample count. 
Tested on ASV
=> Move the msaa custom sample count check assert within the "if" branch.

Code/Framework/AzFramework/AzFramework/Process/ProcessCommunicatorTracePrinter.h, Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerEditorServerBus.h, Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp, Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.h, Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorAutomation.cpp, Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorAutomation.h, Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp, Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.h
Changed the Editor->server communication to send the level data packets over a series of frames instead of in a tight loop. For large levels, this will make it clear that the Editor isn't just frozen while sending it. Also added better status messages for successful and failed sends.
Ran the MPS sample, manually forced failure conditions to verify the fail message worked, slowed down the time cap to verify that the intermediate status updates worked, and ran with the code as-is to verify that success worked.
=> Change level send to be async and more gracefully handle errors.

cmake/Subdirectories.cmake, scripts/o3de/o3de/cmake.py, scripts/o3de/tests/test_cmake.py
The  O3DE_EXTERNAL_SUBDIRS` variable did not work properly for me, when I tried using it to specify a subdirectory that was not specified in the o3de manifest. This pull request fixes the issues I encountered.
This PR now allows me to build an engine, together with a project and an external gem that the project depends on  without having the engine and gem directories registered in the o3de manifest using the cmake variables  `O3DE_EXTERNAL_SUBDIRS` and `LY_PROJECTS`. This is useful, for example, when you want to build a project together with the engine in a CI setup since you can do it without setting up the o3de manifest. It also allows you to build multiple versions of a gem on one machine without running into issues, since registering both versions in the manifest leads to naming …
=> Use O3DE_EXTERNAL_SUBDIRS cmake variable correctly.

Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditorSettings.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/SettingsRegistrar.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/SettingsRegistrar.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ComponentEditor.cpp
A warning was being output to the console when trying to load a DPE inspector settings file or an entry in the settings file that didn't exist yet.
Testing in editor.
=> Fix warnings when loading component editor settings

Gems/Atom/Asset/Shader/Config/Platform/iOS/shader_build_options.json, Gems/Atom/RHI/DX12/Code/Source/RHI/Device.cpp
- Minor fix related to passing in incorrect enum to query DX12 drivers for msaa custom sample support.
- Another minor fix related ios shader not building due to passing in multiple name spaces on the same line
Tested on ASV
=> Fix querying DX12 for msaa custom sample support as well as fix ios shader build related crash

Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp
Now correctly populates the context menu when user is in search mode.
Fixed Show In Folder context menu action not working correctly for product assets
Fixes search widget not being re-enabled if view was switched to list view
Locally
=> Thumbnailview Context Menu Fixes

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp, Code/Framework/AzQtComponents/AzQtComponents/DPEDebugViewStandalone/main.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
Prior to this PR, there were some issues with containers in the DPE such as broken nested container action buttons and the inability to remove nested associative containers elements from their parent container.
This PR fixes those issues and makes some improvements to the `ReflectionAdapter`'s `BoundContainer` including:
- Fix for broken nested container action buttons which weren't working due to BoundContainer combining the state for root containers, nested containers, and non-container elements
- Fix for using the IDataContainer API with a nested container by storing its element instance override (from the LegacyReflectionBridge) separately from its container instance 
- Refactored BoundContainer's element responsibilities into struct ContainerElement
- A ContainerNode …
=> DPE: BoundContainer fixes and improvements

Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/ResourcePool/ResourcePoolSourceData.h
- Fix m_budgetInBytes to be 64 bits
Tested ASV
=> Minor fix related to lower bit variable type related to bytes associated with Pool budget

Gems/Atom/Asset/Shader/Code/Source/Editor/AzslShaderBuilderSystemComponent.cpp, Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderAssetBuilder.cpp, Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderVariantAssetBuilder.cpp, Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderVariantAssetBuilder.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Shader/Shader.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderAsset.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderAssetCreator.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderVariantAsset.h, Gems/Atom/RPI/Code/Source/RPI.Edit/Shader/ShaderVariantAssetCreator.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Shader/Shader.cpp, Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderAsset.cpp, Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderAssetCreator.cpp, Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderVariantAsset.cpp, Gems/Atom/RPI/Code/Tests/Common/ShaderAssetTestUtils.cpp, Gems/Atom/RPI/Code/Tests/Shader/ShaderTests.cpp
Remove m_buildTimeStamp from ShaderAsset and ShaderVariantAsset.
Having `m_buildTimeStamp` was necessary a few years ago, but with the recent improvements in the Asset System notifications it is not necessary anymore and removing it also adds stability to Asset Bundling. The main problem of having a build time stamp embedded in the asset is that the same shader built on different dates would appear as having different content, but now, regardless of the date of compilation the Shader assets will have the same binary content, assuming the code has not changed.
Tested empirically with AutomatedTesting (Editor) by manually changing *.shader assets and making sure the OnAssetReady and OnAssetReloaded events are processed accordingly. Also validated with AtomSampleViewer.
=> Remove m_buildTimeStamp from ShaderAsset and ShaderVariantAsset

Code/Framework/AzCore/AzCore/IO/SystemFile.cpp, Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/IO/SystemFile_UnixLike.cpp, Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/IO/SystemFile_WinAPI.cpp
Validated that running the [SystemFileTest.FileDescriptorCapturer_DoesNotDeadlock_WhenMoreThanPipeSizeContent_IsCaptured](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/Tests/SystemFileTest.cpp#L254) closes the epoll descriptor when running the UnitTest on Linux.
=> Adding missing `close()` call for FileDescriptorCapturer UnixLike pipe data

Tools/LyTestTools/ly_test_tools/__init__.py
Make LyTestTools be able to isolate tests that are specific to or disabled on Linux ARM64.
Example usage:
Skip a test on Linux arm64 machine:
@pytest.mark.skipif(ly_test_tools.LINUX, reason="Python based file locking does not function on Linux")
@pytest.mark.skipif(ly_test_tools.ARM64, reason="Python based file locking does not function on ARM64")
Skip a test on Linux non-arm64 machine:
@pytest.mark.skipif(ly_test_tools.LINUX, reason="Python based file locking does not function on Linux")
@pytest.mark.skipif(not ly_test_tools.ARM64, reason="Python based file locking does not function on ARM64")
=> Detect CPU architecture in LyTestTools

Code/Framework/AzCore/Tests/Asset/AssetManagerLoadingTests.cpp, Code/Framework/AzCore/Tests/Asset/BaseAssetManagerTest.cpp, Code/Framework/AzCore/Tests/Asset/BaseAssetManagerTest.h, Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/TestEngine/Common/TestImpactTestEngine.h, Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestEngine/Native/TestImpactNativeTestEngine.h
Removed unnecessary call to GetRemainingJobs that was causing tests to sometimes fail.
Fixed compile errors in the Test Impact Framework.
https://github.com/o3de/o3de/issues/15549
Ran this test locally on Windows a few thousand times with and without this change. It doesn't fail for me locally with and without this fix on Windows:
bin\debug\AzTestRunner.exe C:/git3/o3de/windows_vs2019/bin/debug/AzCore.Tests.dll AzRunUnitTests --gtest_output=xml:C:/git23/o3de/windows_vs2019/testing/Gtest/AZ_AzCore.Tests.xml --gtest_filter=*BasicDependencyManagement* --gtest_break_on_failure --gtest_repeat=5000
I'm building Linux now to test there as well.
My build fails without the Test Impact Analysis Framework changes, and builds with them.
=> Removed unnecessary call to GetRemainingJobs that was causing tests to sometimes fail.

Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h
Fixes https://github.com/o3de/o3de/issues/15097
This PR fixes issues that would occur if there are multiple DPE views are being used. In the Entity Inspector, there is one DPE view for each component. The pool manager is responsible for creating the pool and holds a weak pointer to it. Each DPE view co-owns the instance pool if it uses its handler.
- **Why it crashes?** - The single-shot delete would cause double deletion after DPE view widget deletes the prefab label handler.
- **Why it does deletion rather than recycling?** - Pool manager's GetPoot() returns nullptr during the deletion of second DPE view, which would lead to delete the handler rather then recycling it. It happens because the prefab label handler pool has already been destroyed in the first DPE view's deletion (upon …
=> Fix handler pool issues for multiple-DPE case

Code/Tools/AssetProcessor/native/AssetManager/SourceAssetReference.cpp, Code/Tools/AssetProcessor/native/AssetManager/SourceAssetReference.h
Profiling showed FixedMaxPath was resulting in high memory usage as part of QueueElementID in RCController's Cached Job list
Memory profiling on AutomatedTesting project.
Memory usage before: 460MB
Memory usage after: 348MB
=> Asset Processor - Replace FixedMaxPath with Path in SourceAssetReference

AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_batch_tests.py, Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.h, Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.cpp, Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.h, Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp, Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h, Code/Tools/AssetProcessor/native/assetprocessor.h
AP will now store the source and job fingerprint when a job is failed due to outputting the same product(s) as another job. Whenever a job completes it will now check if it is listed as a 'conflictor' for another job, and if its fingerprint has changed since last time, will re-queue the other source.
_Before this change:_ When 2 sources produced the same product(s) one of the jobs would be failed based on which ran last.  If the user chose to fix the problem by updating the source that succeeded, they would need to manually reprocess the source that failed OR restart AP.
_After this change:_ Next time the successful job is re-run, it will also re-run the failed job provided the fingerprint has changed.
Resolves https://github.com/o3de/o3de/issues/15248
Resolves …
=> Asset Processor - Add retry logic for jobs that conflicted due to same outputs

Gems/Atom/Feature/Common/Assets/Passes/PassTemplates.azasset, Gems/Atom/Feature/Common/Assets/Passes/PostProcessParent.pass, Gems/Atom/Feature/Common/Assets/Passes/TaaParent.pass, Gems/Atom/Feature/Common/Code/Source/PostProcessing/TaaPass.cpp, Gems/Atom/Feature/Common/Code/Source/PostProcessing/TaaPass.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/CopyPass.h
This PR fixes an issue where the TAA history buffer copy is done in the same scope as TAA itself, which isn't technically allowed. While these "works" it causes validation errors.
Fixes #15083 
Tested with TAA on/off in dx12/vulkan.
=> Separating TAA history buffer copy into its own scope.

Code/Tools/AssetProcessor/native/ui/ProductAssetDetailsPanel.cpp
Running the scanner on the entire output folder was previously locking up AP.  Profiling showed this was due to a thread per file being spawned. This change moves the work to the AZ Job system to prevent spawning an unlimited number of threads. This process is still essentially single-threaded due to the use of ebuses and a database connection that can't be shared across threads, but this at least improves the UI performance.
Manually opening the AP Asset Products tab and clicking Scan button when the "pc" folder is selected (top level asset folder)
=> Asset Processor - Updated missing dependency scanner to use the job system.

scripts/o3de/o3de/engine_template.py
When creating a template containing TypeIds declared in a TypeIds.h header, the Uuids were not replaced with a placeholder entry such as `{${Random_Uuid}}` which would cause instantiations of the that template to re-use the same TypeIds.
Validated that running the `create-template` command over the Compression gem in o3de replaced the Uuid values with template placeholders.
Tested using the command of
```powershell
C:\code\o3de>scripts\o3de.bat create-template -sp Gems\Compression -dp C:\TestTemplate
```
```c++
namespace ${SanitizedCppName}
{
// System Component TypeIds
inline constexpr const char* …
```
=> Fix `create-template` to add placeholder entries to the *TypeIds.h file

Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.h, Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.cpp, Code/Tools/AssetProcessor/native/ui/ProductAssetTreeModel.cpp, Code/Tools/AssetProcessor/native/ui/ProductAssetTreeModel.h
- Added missing index for the MissingProductDependencies table.
- This was causing a significant slowdown when a few hundred entries were present in the MissingProductDependencies table (which is empty by default until the Scan Missing Dependencies button is used)
- Replaced multiple query calls with a single QueryCombined call.
- This was causing a lesser slowdown amount of slowdown but was always present even if the MissingProductDependencies table was empty (around 400ms).
Manually started AP and profiled how long it took to open Assets tab the first time.
Before: 1412ms
After: 216ms
Speedup: 6.54x
(These times are for when there are MissingProductDependencies entries, without them, the speedup is closer to 2x)
=> Asset Processor - Improved performance loading assets tab the first time

Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
The DPE settings are loaded and saved during construction/destruction. This PR makes sure that settings are saved to disk before they're loaded from disk again.
Testing in Editor.
=> Save DPE inspector settings before loading

Code/Framework/AzCore/AzCore/IO/GenericStreams.cpp, Code/Framework/AzCore/AzCore/IO/GenericStreams.h, Code/Framework/AzCore/AzCore/IO/SystemFile.cpp, Code/Framework/AzCore/AzCore/IO/SystemFile.h, Code/Framework/AzCore/AzCore/Settings/CommandLine.cpp, Code/Framework/AzCore/AzCore/Settings/CommandLine.h, Code/Framework/AzCore/AzCore/Settings/ConfigParser.cpp, Code/Framework/AzCore/AzCore/Settings/ConfigParser.h, Code/Framework/AzCore/AzCore/Settings/TextParser.cpp, Code/Framework/AzCore/AzCore/Settings/TextParser.h, Code/Framework/AzCore/AzCore/azcore_files.cmake, Code/Framework/AzCore/Platform/Android/AzCore/IO/SystemFile_Android.cpp, Code/Framework/AzCore/Platform/Common/UnixLikeDefault/AzCore/IO/SystemFile_UnixLikeDefault.cpp, Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/IO/SystemFile_WinAPI.cpp, Code/Framework/AzCore/Tests/Platform/Android/Tests/IO/SystemFileTest_Android.cpp, Code/Framework/AzCore/Tests/Platform/Android/platform_android_files.cmake, Code/Framework/AzCore/Tests/Platform/Common/UnixLike/Tests/IO/SystemFileTest_UnixLike.cpp, Code/Framework/AzCore/Tests/Platform/Common/WinAPI/Tests/IO/SystemFileTest_WinAPI.cpp, Code/Framework/AzCore/Tests/Platform/Linux/platform_linux_files.cmake, Code/Framework/AzCore/Tests/Platform/Mac/platform_mac_files.cmake, Code/Framework/AzCore/Tests/Platform/Windows/platform_windows_files.cmake, Code/Framework/AzCore/Tests/Platform/iOS/platform_ios_files.cmake, Code/Framework/AzCore/Tests/Settings/CommandLineTests.cpp, Code/Framework/AzCore/Tests/Settings/TextParserTests.cpp, Code/Framework/AzCore/Tests/SystemFileTest.cpp, Code/Framework/AzCore/Tests/azcoretests_files.cmake, Code/Tools/SerializeContextTools/Dumper.cpp, Code/Tools/SerializeContextTools/Runner.cpp
Updated the createuuid options
Support has been added for a `--values-file` option which allows
specifying a text file which contains lines which should be converted to
Uuids using the SHA1 hash algorithm
With the support, was also added the ability to specify stdin as an
input file to the `--values-file` option using the `-` value.
The `--output-file` option for the createuuid, dumptypes, createtype
also supports using the value `-` to specify stdout as output file to
open
Adding support for SystemFile API to support wraping Std handles
The `stdin`, `stdout` and `stderr` file handles are wrapped by static
functions on the SystemFile class that allows using the SystemFile class
to read from stdin or write to stdout/stderr using its API.
The Std handles are setup to not close on …
=> Updated the SerializeContext `createuuid` options

Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabComponentAdapter.cpp, Code/Framework/AzToolsFramework/Tests/Prefab/Overrides/PrefabInspectorOverrideTests.cpp
Fixes https://github.com/o3de/o3de/issues/15661
This PR changes to set up the `RevertOverride` message handler by default in 'PrefabComponentAdapter::CreateLabel'.
Whether or not the context menu can be shown is still checked in [PrefabOverrideLabelHandler::ShowContextMenu](https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabOverrideLabelHandler.cpp#L58).
When a property value is edited as override, 'PrefabComponentAdapter::UpdateDomContents' will generate a patch to set `IsOverridden` to true and can notify to call 'PrefabOverrideLabelHandler::SetValueFrom' to update the cached node such that the context menu can be shown.
PR that adds revert support: https://github.com/o3de/o3de/pull/14917
Tested in editor …
=> Prefab/DPE: Set the RevertOverride message handler correctly

Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ActionManagerSystemComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ActionManagerSystemComponent.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/HotKey/HotKeyWidgetRegistrationHelper.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/HotKey/HotKeyWidgetRegistrationHelper.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/HotKey/HotKeyWidgetRegistrationInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Editor/ActionManagerUtils.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Editor/ActionManagerUtils.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/UICore/ConsoleTextEdit.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake, Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp
Fixes a regression due to changes in the order of operations during editor initialization - widgets were initialized before the action manager registration hooks were called, making it so that the assignment would fail when the editor layout is restored at startup.
Introduced a new helper function that correctly delays registration if the system has not been initialized when the widget is created.
=> Action Manager | Fix assigning widgets to action contexts at startup

Gems/Multiplayer/Code/Source/Components/SimplePlayerSpawnerComponent.cpp
If the Simple Player Spawner component had an empty entry in its list, the Respawn code would return an uninitialized transform. This fixes the logic so that invalid entity IDs will assert and return an Identity(), and missing entities will also return an Identity() instead of uninitialized data.
Tried spawning in MPS with an empty entry and verified that it asserted and spawned at the Identity() location.
=> Fix SimplePlayerSpawner to always return valid transform

Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h
Cherry picks the commit from PR https://github.com/o3de/o3de/pull/15662. It fixed https://github.com/o3de/o3de/issues/15097 in development.
It was reported that destructor of `ContainerActionButtonHandler` _sometimes_ crashes in stab due to double deletion, which is showing a similar call stack.
```
Qt5Widgets.dll!QWidget::~QWidget() Line 1442	C++
> EitorLib.dll!AzToolsFramework::ContainerActionButtonHandler::`scalar deleting destructor'(unsigned int)	C++
[Inline Frame] Qt5Core.dll!QtPrivate::QSlotObjectBase::call(QObject *) Line 398	C++
Qt5Core.dll!QMetaCallEvent::placeMetaCall(QObject * object) Line 622	C++
Qt5Core.dll!QObject::event(QEvent * e) Line 1314	C++
Qt5Widgets.dll!QApplicationPrivate::notify_helper(QObject * receiver, QEvent * e) Line 3632	C++ …
```
=> Cherry-Pick: Fix handler pool issues for multiple-DPE case

Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Multiplayer System can ignore doing special stuff on level loads if not in multiplayer mode.
Stops a wrong/confusing error log from occurring.
```"Attempting to spawn players on level load failed."```
Alternative solution is to only connect to RootSpawnableNotificationBus::Handler when we need to but OnRootSpawnableReady is rarely called and this logic seems easier to read instead of placing BusConnects and BusDisconnects outside of De/Activate().
Fixes #13431
Using Multiplayer game, before hosting or connecting attempt to load level in a launcher and make sure log error doesn't occur.
```"Attempting to spawn players on level load failed."```
Using Multiplayer game press CTRL+G in editor (with editorsv_enabled false) and ensure log error doesn't occur.
```"Attempting to spawn players on …
```
=> Multiplayer: Don't Attempt Player Spawn on Level Load if Not in Multiplayer Mode 

Gems/Atom/RHI/Code/Include/Atom/RHI/RayTracingAccelerationStructure.h, Gems/Atom/RHI/Code/Include/Atom/RHI/RayTracingShaderTable.h, Gems/Atom/RHI/Code/Source/RHI/RayTracingAccelerationStructure.cpp, Gems/Atom/RHI/Code/Source/RHI/RayTracingShaderTable.cpp
This PR only changes the signature of three methods to accept a `const` reference parameter instead of a reference, all three only make copies of that parameter internally and this change allows the usage of these descriptors in contexts where a `const` resource is present.
Built against the newest `o3de-atom-sampleviewer` state and does not change anything else, so should not affect run-time behaviour.
=> Allow usage of RT descriptors in const context

Code/Framework/AzToolsFramework/AzToolsFramework/UI/DPEDebugViewer/DPEDebugModel.cpp
Resolves https://github.com/o3de/o3de/issues/15157
This PR fixes a crash in the DPEDebugModel caused by paths that have path entries beyond their property. This meant that a particular `for` loop was continuing after finding the last keyed PathEntry and eventually returning nullptr.
**Testing**
- Verified no crash occurs when doing things that previously crashed in the DPEDebugViewStandalone app
- Verified that the for loop no longer continues after encountering the first keyed PathEntry
=> DPE: Prevent nullptr node crash in DPEDebugModel

Code/Tools/AssetProcessor/native/ui/BuilderListModel.cpp, Code/Tools/AssetProcessor/native/ui/BuilderListModel.h, Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
Right click job -> go to builder.
Fixed issue where "Show in Asset Browser" was enabled when the Editor wasn't connected.
Tested locally - UI automation for this tool is not yet available.
=> Right click job -> go to builder

Code/Tools/AssetProcessor/native/ui/ProductAssetDetailsPanel.cpp, Code/Tools/AssetProcessor/native/ui/ProductAssetDetailsPanel.h, Code/Tools/AssetProcessor/native/ui/ProductAssetDetailsPanel.ui
Last year, we switched to a new design for asset processor views, to use tabs to better organize data, visually. The product assets tab hadn't been updated to this new design yet. This pull request updates it to that design.
Tested locally, see screenshots
=> Product details page is now tabbed, like other views in the Asset Processor.

Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp
Previous terrain ray tracing meshes are were cleaned up after the sectors they relied on were already destroyed. This led to UB. It's kind of amazing it took several weeks to notice, possible that in many cases the memory hasn't actually been wiped and was in a good enough state to "work"
Fixes #15702 
Tested in a couple terrain levels. Verified that ray tracing meshes were being cleaned up while sectors still existed.
=> [Terrain] - Fixing terrain mesh manager cleanup

scripts/o3de/o3de/engine_template.py
By specifying the long option first (`--keep-license-text`), before the short option (`-kl`), the long option is shown in the usage text when an invalid argument is specified.
fixes #15720
Ran the create-gem command without an argument with before and after changes
Before:
After
=> Swapped the order of the license text option in the engine template cli

Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArrayFeatureProcessor.cpp
Fix decal crash #15190 
- Changed how the image asset is verified to correctly catch the missing image error
- Changed Assert to Error so console can report missing image and Editor can continue safely
Tested manually by doing the following steps: 
Setup: 
1. Created a new material with a base color texture
2. Added the Decal component to the default ShaderBall
3. Added the material to the Decal component
4. Deleted the base color texture
5. Saved and closed Editor.
6. Relaunched Editor. 
Before this fix, the Editor would crash after loading a level. After the fix, the level loads and the "missing image" error is output to the console.
=> Fix decal crash #15190

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
Prior to this PR, the wrong instance pointer was being used to invoke/access ReadOnly attributes from inside the LegacyReflectionBridge. This meant that the DPE was attempting to invoke functions, or otherwise access members, on the member of the class instead of the class itself.
This PR changes the instance ptr being used to the parent data's instance ptr, which is the class that owns the reflected member being accessed.
**Testing**
- Verified that component readonly issues recently found in the EntityInspector are fixed
- Verified that readonly functionality in the DPE debug standalone app is still intact and correct
=> DPE: Fix various readonly issues in the EntityInspector

Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/MemoryUsage.h, Gems/Atom/RHI/Code/Include/Atom/RHI/StreamingImagePool.h, Gems/Atom/RHI/DX12/Code/Source/RHI/StreamingImagePool.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/StreamingImagePool.cpp, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/StreamingImage.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/StreamingImageContext.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/StreamingImageController.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/StreamingImagePool.h, Gems/Atom/RPI/Code/Source/RPI.Public/Image/StreamingImage.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Image/StreamingImageContext.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Image/StreamingImageController.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Image/StreamingImagePool.cpp
Fixed a vulkan image streaming issue: https://github.com/o3de/o3de-atom-sampleviewer/issues/605
Improved image streaming control by using two separate sorted list for mip expand and evict.
Change the heap memory usage validation so the budget only limits the used memory
DX12/Vulkan
ASV RPI/StreamingImage sample
LoftScene level
=> Fixed a vulkan image streaming issue

Gems/Atom/RHI/Code/Include/Atom/RHI/RayTracingPipelineState.h, Gems/Atom/RHI/Code/Include/Atom/RHI/RayTracingShaderTable.h, Gems/Atom/RHI/Code/Source/RHI/RayTracingPipelineState.cpp, Gems/Atom/RHI/Code/Source/RHI/RayTracingShaderTable.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingShaderTable.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingShaderTable.h, Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingShaderTable.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingShaderTable.h
Added support for callable shaders to the RayTracing PipelineState and ShaderTable.
=> RayTracing Callable Shader support

Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
Fixes minor issues: https://github.com/o3de/o3de/issues/15087, https://github.com/o3de/o3de/issues/15606
This PR fixes the error messages that show up in console after various prefab operations. 
> [Error] (Prefab) - Failed to find an owning instance for entity with id 17089810523390950905.
The error message shows up when AM is turned on by default and 'Revert Override' action (in context menu) would then use that feature. There is a new 'Enabled State' callback in AM that checks an action's availability. For 'Revert Override' action, the callback gets invoked when entity selection changes or prefab propagation ends.
In some prefab editor operations, selection change might happen before the prefab propagation ends, then the callback invoked by the 'selection change' event would try to …
=> Prefab/ActionManager: Fix error message in various prefab operations

Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp
ref: https://github.com/o3de/o3de/issues/15759
when compiled on clang 16
compile on linux against clang-16
=> bugfix: address compiling issues for clang-16

Code/Tools/AssetProcessor/native/AssetManager/FileStateCache.cpp, Code/Tools/AssetProcessor/native/AssetManager/FileStateCache.h, Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp, Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h, Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp, Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp, Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.h
* Added a string path cache to the FileStateCache to avoid re-normalizing and lowercasing the same string many times.  Profiling showed this as a hot spot and it was being called over 5M times during startup.
* Added a dependency cache to QueryAbsolutePathDependenciesRecursive.  Profiling also showed this as a hotspot for several different items.  The cache only applies during startup and is cleared/disabled after reaching idle state.
* Switched from a queue to an unordered_set as the order doesn't actually matter and profiling showed unordered_set to be faster.
* Added an optional return of the scanfolder for FindFirstMatchingFile to optimize one of the SourceAssetReference calls during the above.
Manually ran AP, wrote some verification code to compare the old and new results to make …
=> Asset Processor - Optimize initial startup time

Code/Editor/Core/EditorActionsHandler.cpp, Code/Editor/GameEngine.cpp, Code/Editor/MainWindow.cpp, cmake/Platform/Windows/Packaging/Tests/conftest.py
When the 'quit' console command is used, the Editor crashes with a non-zero exit code.
`GetActionManager()` returns null when the new action manager is active, which is the default.
Other fixes:
- fix trying to connect signal to nullptr object
- fix inaccurate Exit menu text
- fix missing variable error in the installer test logging thread
- Ran tests that relied on the quit command and were failing (e.g. installer test)
- used the quit command in the Editor
=> Fix editor crash on quit

Gems/PhysX/Code/Editor/Source/Components/EditorSystemComponent.cpp, Gems/PhysX/Code/Source/Utils.cpp
This PR fixes a critical issue with all Hinge and Prismatic joint components in GameLauncher (not Editor / Game mode). The issue causes failure in components serialization (these components are not reflected).
Fixes #15798.
It was tested in both Editor (to confirm no regression) and GameLauncher. I looked whether there are critical errors (as before this PR) and whether the joints move as intended (confirmed that). I used [ROSConDemo](https://github.com/o3de/ROSConDemo) for testing.
=> Moved joint motor properties reflection to proper place

Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipService.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.h, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.cpp
The PR prevents recreation of an instantiated prefab by caching the instance DOM of the parent instance.
Also container entity was being set up twice.
Tested in Editor.
=> Cache parent instance DOM upon prefab instantiation

Gems/Camera/Code/Source/CameraComponentController.cpp, Gems/Camera/Code/Source/CameraComponentController.h
Remove EditorEntityId from being serialized. This property is not visible to the user and does not seem necessary to serialize. When serialized, it causes prefab override visualization to be displayed on the entity because the Camera component assigns the EditorEntityId property on activation which differs from the default.
Tested in Editor.
=> Remove EditorEntityId from serialized content

Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/SearchWidget.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/SearchWidget.h
Fixes Asset Browser's "Hide Engine Assets" toggleable filter to hide folders inside the o3de engine path, excluding the project folder, rather than hiding everything outside of the project.
Locally with AutomatedTesting. Testing with Asset Gems and a project-centric build to ensure everything works.
=> Fix Hide Engine Assets Filter

Gems/LyShine/Code/Source/UiTextComponent.cpp
Fix a couple of issues with UI text rendering.
- Move an assert to correct place
- Don't add draw batch to render graph if there are no vertices to draw. This can happen if there are characters to draw, but they are all clipped out of view
Fixes #15755.
Tested in UI Editor.
=> Fix for rendering UI text that is completely clipped

Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.cpp
The first time launch of a project with Diffuse Probe gem hits an assert as the required asset isn't ready yet. However it is already loaded in a deferred manner. So the assert here isn't necessary. Lowering the messaging down to a warning instead.
Testing locally with a brand new project with clean cache.
=> Fixes first time Editor startup assert in Diffuse Probe gem

Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h
Before this PR, it was possible for cached DOM attributes such as Disabled to be incorrect when a widget was pulled from the pool during a patch.
This PR refactors attribute caching in `DocumentPropertyEditor.cpp` so that we only remember layout relevant attributes and, unless default, always cache them the next time a widget is being configured here.
**Testing**
- Tested with an issue noticed in the DPE debug standalone app that caused certain controls to become enabled even though their DOM nodes contained the "Disabled" attribute
=> DPE: Fix unwanted disabling of widgets

cmake/Projects.cmake, cmake/Subdirectories.cmake
Fix a case where cmake configure fails because it uses the wrong engine in an 'engine-centric' workflow.
Fixes https://github.com/o3de/o3de/issues/15792
The solution is to always provide the engine path to the cmake.py dependency script so it always uses the engine CMake is using.
- configured a project in engine-centric and project-centric mode
- ran o3de pytests
=> fix cmake dependency resolution using wrong engine

Gems/WhiteBox/Code/Source/EditorWhiteBoxComponent.cpp
the file extension for wbm is not appended correctly if the file is missing the extension when saving a whitebox mesh.
this regex expression is what drives how the extension is appended: https://github.com/o3de/o3de/blob/development/Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/FileDialog.cpp#L113
documentation: https://doc.qt.io/qt-6/qfiledialog.html#getSaveFileName
follow the instruction in the issue below to reproduce. 
ref: https://github.com/o3de/o3de/issues/15788
=> bugfix(Whitebox): correctly save file with extension *.wbm

Code/Tools/ProjectManager/Source/ProjectButtonWidget.h, Code/Tools/ProjectManager/Source/ProjectsScreen.cpp, Code/Tools/ProjectManager/Source/ProjectsScreen.h
This is a single line fix to address the bug discovered in https://github.com/o3de/o3de/issues/13035.
In essence, auto-build did not occur because once the download happened, the current cache of projects did not account for the newly added repo. This requires updating the project information so that it is present before searching for projects to mark as needing to build.
Testing was done manually. Behavior was confirmed as shown in the following gif:
=> Prompt the user to build newly downloaded project

Code/Framework/AzCore/AzCore/Debug/Trace.cpp, Code/Framework/AzCore/AzCore/Serialization/ObjectStream.cpp, Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/LuaMaterialFunctor.cpp
This PR fixes a few violations found with the address sanitizer on Linux of the `BasicEditorWorkflows_LevelEntityComponentCRUD` test.
By running the test in a build with the address sanitizer enabled, and fixing the violations until the test passed.
=> Test fixes for the `BasicEditorWorkflows_LevelEntityComponentCRUD` test

scripts/build/Platform/Windows/build_config.json, scripts/build/Platform/Windows/pipeline.json
Fixes an issue where the installer test was hard coded to use the development installer.
The following change allows setting the path to the installer inside the bucket using a Jenkins job parameter `INSTALLER_S3_PATH`
Used a test Jenkins job to verify with these changes Jenkins uses the correct installer
https://jenkins.build.o3de.org/view/Tools/job/O3DE-test_nightly-installer/102/execution/node/229/log/?consoleFull
```
12:15:29  [ci_build] Executing "D:\workspace\o3de\scripts\build\Platform/Windows/pytest_windows.cmd"
12:15:29    cwd = D:\workspace\o3de
12:15:29    engine_dir = D:\workspace\o3de
12:15:29    parameters:
12:15:29      PYTEST_PATH = cmake\Platform\Windows\Packaging\Tests 
12:15:29      PYTEST_PARAMETERS = --capture=no 
--log-file=%WORKSPACE%\installer_test.log …
```
=> Allow selecting test installer path via Jenkins

Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/TestRunner/Common/TestImpactTestSuiteContainer.h, Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Job/TestImpactNativeShardedTestJobInfoGenerator.h
This PR fixes a bug where the number of sharded test fixtures was the minimum value of the number of cores or the number of enabled tests instead of the number of enabled test fixtures. This bug manifested on a user's local machine with `AzFramework.Tests` where the number of cores was greater than the number of test fixtures for this test target, causing some shards to have an empty gtest filter.
This PR was tested locally and will be tested in AR.
=> Tiaf fixture interleave bug fix

AutomatedTesting/AutomationScripts/ExpectedScreenshots/LowEndRenderPipeline/windows/dx12/Atom_DepthOfField/depth_of_field_screenshot1.png, AutomatedTesting/AutomationScripts/ExpectedScreenshots/LowEndRenderPipeline/windows/vulkan/Atom_DepthOfField/depth_of_field_screenshot1.png, AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Periodic_GPU.py
This PR updates the Atom screenshot testing suite to also test the LowEndRenderPipeline.
For testing I ran the AutomatedTesting/AutomationScripts/RunAtomScreenshotTests.bat and verified it produced the expected output.
=> Make the Atom screenshot tests parametrize the render pipeline

Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/Target/Native/TestImpactNativeTargetListCompiler.cpp, scripts/build/TestImpactAnalysis/git_utils.py
This PR fixes two bugs with TIAF:
1. When a test target has coverage in the historical data (either in an s3 bucket or using local persistent storage) and is subsequently removed or no longer a member of the suites being run (for which the coverage data exists for), it was mistakenly being treated as a production target which causes the test selector to try and retrieve the test target for said coverage data, only to draw a `nullptr` due to the mistaken categorization of being a production target. With this fix, test targets that are not in the `testTargetMetaMap` (due to either being removed or no longer being part of the suite's coverage data) are simply not included in the build target list used by the dynamic dependency map.
2. When creating the changelist, the TIAF python script …
=> TIAF: Test target and changelist bug fixes

Code/Framework/AzCore/AzCore/Utils/Utils.h, Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/Utils/Utils_UnixLike.cpp, Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/Utils/Utils_WinAPI.cpp, Code/Framework/AzCore/Tests/Platform/Common/Apple/Tests/UtilsTests_Apple.cpp, Code/Framework/AzCore/Tests/Platform/Common/UnixLike/Tests/UtilsTests_UnixLike.cpp, Code/Framework/AzCore/Tests/Platform/Common/WinAPI/Tests/UtilsTests_WinAPI.cpp
The Utils.h header now exposes a `GetEnv` and a `IsEnvSet` function that can query the value of an OS environmnent and whether it is set respectively.
Fixed the return value `SetEnv` function on Windows to return true when the environment variable is successfully set.
Added UnitTest to that validates the `GetEnv`, `IsEnvSet`, `SetEnv` and `UnsetEnv` functions.
=> Added PAL OS Environment Variable functions in AzCore

Code/Editor/Core/QtEditorApplication.cpp, Code/Framework/AzCore/AzCore/Component/ComponentApplication.cpp, Code/Framework/AzCore/AzCore/Component/ComponentApplicationLifecycle.cpp, Code/Framework/AzCore/AzCore/IO/FileReader.cpp, Code/Framework/AzCore/AzCore/IO/FileReader.h, Code/Framework/AzCore/AzCore/IO/SystemFile.cpp, Code/Framework/AzCore/AzCore/Settings/SettingsRegistry.cpp, Code/Framework/AzCore/AzCore/Settings/SettingsRegistry.h, Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.cpp, Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.h, Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.cpp, Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.h, Code/Framework/AzCore/AzCore/UnitTest/Mocks/MockSettingsRegistry.h, Code/Framework/AzCore/Tests/Settings/SettingsRegistryMergeUtilsTests.cpp, Code/Framework/AzCore/Tests/Settings/SettingsRegistryTests.cpp, Code/Framework/AzFramework/AzFramework/ProjectManager/ProjectManager.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/SettingsRegistrar.cpp, Code/Tools/AssetProcessor/native/InternalBuilders/SettingsRegistryBuilder.cpp, Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp, engine.json
Updated the AZ::IO::FileReader to support reading from stdin.
Fix the SystemFile move constructor/assignment to properly copy the `m_closeOnDestruction` bool.
Updated the Settings Registry Merge* functions to return a result structure with a message string containing user relevant merge messages.
Updated the Settings Registry Builder to output messages related to merging the Engine, Gems and Project registry folders at the info log level.
Updated MergeSettingsToRegistry_CommandLine argument parsing
The `MergeSettingsToRegistry_CommandLine` now accepts a struct instead of a boolean which indicates which command line settings registry arguments to parse.
Verified that specifying a --regset-file option with the `-` argument successfully merges the JSON blob to stdin correctly.
The command …
=> Settings Registry Builder log improvements

Code/Framework/AzCore/AzCore/Debug/Trace.cpp
In commit 4b655211 / #15834, the way that the stack lines were truncated were changed to fix a case in Linux where the whole buffer was used, causing `azstrcat` to fail. That implementation was off by 1, this fixes it.
=> Fix off-by-one error when truncating string when printing the stack

Code/Framework/AzCore/AzCore/IO/Streamer/FullFileDecompressor.cpp, Gems/Compression/Code/Source/Clients/CompressionModule.cpp, Gems/Compression/Code/Source/Clients/CompressionSystemComponent.cpp, Gems/Compression/Code/Source/Clients/Streamer/DecompressorStackEntry.cpp, Gems/Compression/Code/Source/Clients/Streamer/DecompressorStackEntry.h, Gems/Compression/Code/Source/CompressionModuleInterface.cpp, Gems/Compression/Code/Source/CompressionModuleInterface.h, Gems/Compression/Code/compression_private_files.cmake, Gems/Compression/Registry/decompressor_streamer.game.setreg
Streamer will process request from the DecompressionRegistrar before processing request from the FullFileDecompressor
Moved the creation of the DecompressorRegistrar from CompressionModule class to the CompressionModuleInterface class to allow it to be available in tooling application such as the Editor.
Also moved the registration of the Client CompressionSystemComponent to the CompressionModuleInterface to also allow it to be available with the Editor.
Enabled the Compression Gem and validated that the DecompressorRegistrar entry was created when running the AutomatedTesting.GameLauncher without issue.
=> Adding Decompression Registrar entry to the Streamer Stack

Gems/AWSGameLift/cdk/aws_gamelift/fleet_configurations.py
Amazon GameLift recently announced that Windows 2012 servers were EOL. Change default to be Windows 2016 servers.
```
cdk synth
cdk deploy using MPS build
```
Note: Will push doc update as the install.bat no longer requires VC_redistributables.
=> Update AWS GameLift gem to target Windows 2016 Server by default

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/InstanceDataHierarchy.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals_Impl.h, Gems/ScriptCanvas/Code/Editor/View/Widgets/SourceHandlePropertyAssetCtrl.cpp
Fixes https://github.com/o3de/o3de/issues/15558
This PR fixes a crash that happens when we add a ScriptCanvas component in the DPE Entity Inspector.
The crash happens at the time when RPE property handler wrapper is trying to configure data inside the widget. The 'SourceHandle' property wants to set the edit notify target to its parent instance (i.e. a 'Configuration' instance owned by 'EditorScriptCanvasComponent'), but the parent instance that can be retrieved from the 'InstanceDataNode' turns out to be missing. See [my reply](https://github.com/o3de/o3de/issues/15558#issuecomment-1516582040) in the issue for more details.
In this PR, I added a new `ParentValue` attribute for 'PropertyEditor' node and set it up in legacy reflection bridge, so code in the RPE property handler wrapper is …
=> DPE Inspector: Set up parent instance as node attribute for wrapped handler

Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp
Skip override visualization/interaction for container entities in the DPE inspector because they are not meant to be changed by the user. This prevents errors being output to the console.
Tested in Editor.
=> Don't expose overrides on container entities in the DPE inspector

cmake/Platform/Linux/Packaging_Snapcraft.cmake
The failure described https://github.com/o3de/o3de/issues/15856 the binaries that were copied into the bin folder (not compiled) were corrupted, most likely due to a conflict with the fixes to the package with manual rpath processing and snap-crafts own auto-rpath feature.
Removing the rpath manual work-around since the build nodes for the snap packaging is on a stable version of snap craft 7.3.1
Generated a test snap package and install locally, created a new project and new level
fixes https://github.com/o3de/o3de/issues/15856
=> Fix for corrupt binaries in a snap package

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.h, Code/Framework/AzQtComponents/AzQtComponents/DPEDebugViewStandalone/main.cpp
Fixes #15717, #15660
Added handling in `LegacyAttributeToDomValue` to check if the attribute is an invokable function as opposed to a value passed directly. This will fix several cases where attributes such as `Visibility` and `ButtonText` are supplied as a function.
Also added some additional properties to the DPE standalone view to exercise these paths.
Tested the properties in the DPE standalone, as well as the buttons in the Camera component and Landscape Canvas component.
=> Fix for a generic handling of invokable attributes

Code/Framework/AzCore/AzCore/Compression/zstd_compression.cpp
When the system ZStd version of 1.38 or above is used,, a compiler warning is triggered due to calling a deprecated zstd function
```
[47/2376] Building CXX object Code/Framework/AzCore/CMakeFiles/AzCore.dir/profile/Unity/unity_2_cxx.cxx.o
FAILED: Code/Framework/AzCore/CMakeFiles/AzCore.dir/profile/Unity/unity_2_cxx.cxx.o
/usr/sbin/clang++ -DAZ_BUILD_CONFIGURATION_TYPE=\"profile\" -DAZ_ENABLE_DEBUG_TOOLS -DAZ_ENABLE_TRACING -DAZ_PROFILE_BUILD -DLINUX -DLINUX64 -DNDEBUG -D_FORTIFY_SOURCE=2 -D_HAS_EXCEPTIONS=0 -D_PROFILE -D__linux__ -DCMAKE_INTDIR=\"profile\" -I/home/lumberyard-employee-dm/o3de/Code/Framework/AzCore/. -I/home/lumberyard-employee-dm/o3de/Code/Framework/AzCore/Platform/Linux -I/home/lumberyard-employee-dm/o3de/Code/Framework/AzCore/Platform/Common -isystem …
```
=> Fix compile error in zstd_compression.cpp when using system ZStd

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h, Code/Framework/AzQtComponents/AzQtComponents/DPEDebugViewStandalone/main.cpp
Fixes #15744 
The DPE wasn't parsing the `ValueText` attribute for the `Label` handler, so it wasn't being populated, so just had to add it. Also added example of the label UIElement to the DPE example view.
Tested `PhysX Static Rigid Body` component with DPE and verified the label text is now displayed. Also tested the example usage in the DPE example view.
=> Fixed DPE handling of the Label UIElement

Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityHelpers.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityHelpers.h, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
Fixes https://github.com/o3de/o3de/issues/15260 issue ([previous fix](https://github.com/o3de/o3de/pull/15726) did not fix all cases)
This PR blocks users from parenting an entity or a nested prefab to an entity owned by a different prefab in TransformComponent's parent field.
Previously, there was a PR https://github.com/o3de/o3de/pull/14411 blocking this, but it was only for drag-and-drop in Entity Outliner.
**Change List:**
- Add new check in editor's transform component
- Improve the existing check in EntityOutlinerListModel (remove `InstanceEntityMapperInterface` dependency)
https://user-images.githubusercontent.com/11157226/236561106-70ad77bb-ad3c-459e-b555-1524c473d8a7.mp4
=> No cross-prefab reparenting in editor transform component

Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h, Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportSettingsSystem.cpp, Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/DynamicNode/DynamicNodeManager.cpp, Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp, Gems/Atom/Tools/MaterialCanvas/Scripts/TestOpenClose.py, Gems/Atom/Tools/MaterialEditor/Scripts/UpgradeAllMaterials.py
This PR changes file enumeration functions to use a faster extension filter instead of a wild card filter. 
Logging was also added to record how long it takes to enumerate files in different systems.
Parallelization was removed from directory traversal.
This is all in an ever dude determine what might cause extended startup times on some machines.
The extended delay is usually on the first run after downloading the engine or setting up a new project where Python symbols and other data have not been saved yet.
Launched affected tools and ran included Python scripts
=> Atom Tools: Change file enumeration to add logging and use extension checks instead of wild cards

Code/Framework/AzToolsFramework/AzToolsFramework/Thumbnails/ThumbnailerComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Thumbnails/ThumbnailerComponent.h
There was a bug that in certain circumstances the AssetBrowser Thumbnail view could hang if too many concurrent loads occurred. This is now set to the number of hardware threads available.
Tested under circumstances that previously failed. All working now,
=> Changed the max number of concurrent thumbnail loads

cmake/Gems.cmake, scripts/o3de/o3de/download.py, scripts/o3de/tests/test_download.py
Fixes https://github.com/o3de/o3de/issues/15893
When a specific version of a gem is used in ProjectManager the `project.json` `gem_names` entry looks like `PopcornFX==2.16.2` but when CMake is looking for all the variants to load the `==2.16.2` part was not stripped and so none of the load targets were found.  This change removes the version specifiers so the gem name alone is used in the search for variants.
Fixes https://github.com/o3de/o3de/issues/15925
The default gem registration will not use the `o3de_manifest.json` in the case when the user downloads a version of a gem into a folder that has a `gem.json` in a parent folder - this can happen for downloaded gems that were previously downloaded without gem versions, and then a subsequent versioned gem is downloaded and ends up in a …
=> Fix PopcornFX loading and registration

Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/DiskLight.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/QuadLight.azsli
Straighten a nit point of code syntax in shaders
Ran the sample viewer and material editor to have the asset processor re-treat the change.
=> Syntax issue in shader: can't use a non-class enum as qualifier prefix.

Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabComponentAdapter.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyManagerComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyManagerComponent.h
This PR fixes one of the issues listed in https://github.com/o3de/o3de/issues/15918 where undoing a multi-edit action requires hitting undo 'n' times, where n is the number of entities being modified
This PR gives the responsibility of creating and ending undo batch to PropertyManagerComponent, which is the source for all DPE property edits.
This PR needs to go along with https://github.com/o3de/o3de/pull/15943 to fix the issue fully.
Another cool benefit we get with this approach is that we can do both direct template edits and overrides together using multi-edit. The prefab adapter takes care of doing the right calls. But the undo system doesn't need to know anything about it rightfully so.
Manually along with https://github.com/o3de/o3de/pull/15943
=> Give undo batch handling responsibility to PropertyManagerComponent

Gems/Atom/Feature/Common/Code/Source/SplashScreen/SplashScreenFeatureProcessor.cpp
Updates the splash screen feature processor to only be enabled in game.
Resolves https://github.com/o3de/o3de/issues/15897
Confirmed that splash screen no longer appears in material editor or material canvas
=> Only enable splash screen in game

Code/Framework/AzToolsFramework/Tests/Prefab/PrefabInstantiateTests.cpp
Fixes https://github.com/o3de/o3de/issues/3398
Link comparison should work as expected, so I enable the disabled prefab unit test that failed before.
Tested that it can pass now.
=> Re-enable one prefab instantiation unit test

Code/Framework/AzCore/AzCore/IO/AnsiTerminalUtils.cpp, Code/Framework/AzCore/AzCore/IO/AnsiTerminalUtils.h, Code/Framework/AzCore/AzCore/IO/SystemFile.h, Code/Framework/AzCore/AzCore/Utils/Utils.h, Code/Framework/AzCore/AzCore/azcore_files.cmake, Code/Framework/AzCore/Platform/Android/AzCore/Utils/Utils_Android.cpp, Code/Framework/AzCore/Platform/Android/platform_android_files.cmake, Code/Framework/AzCore/Platform/Common/Unimplemented/AzCore/Utils/Utils_Unimplemented.cpp, Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/IO/AnsiTerminalUtils_UnixLike.cpp, Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/IO/SystemFile_UnixLike.cpp, Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/IO/AnsiTerminalUtils_WinAPI.cpp, Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/IO/SystemFile_WinAPI.cpp, Code/Framework/AzCore/Platform/Linux/platform_linux_files.cmake, Code/Framework/AzCore/Platform/Mac/platform_mac_files.cmake, Code/Framework/AzCore/Platform/Windows/platform_windows_files.cmake, Code/Framework/AzCore/Platform/iOS/platform_ios_files.cmake, Code/Tools/TestImpactFramework/Frontend/Console/Common/Code/Source/TestImpactConsoleUtils.cpp, Code/Tools/TestImpactFramework/Frontend/Console/Common/Code/Source/TestImpactTestSequenceNotificationHandler.cpp
Fixed potential divide by zero in the Test Impact Analysis Framework when outputting which test were selected.
This was causing the Test Impact Analysis Framework run to crash with return code 0xc0000094 which is the return code for integer divide by zero on Windows
The error can be seen on Jenkins at https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/development/4331/pipeline/819
```
[2023-05-16T21:48:21.363Z] BuildTargetDependencyGraph: Trace::Warning
[2023-05-16T21:48:33.592Z]  D:\workspace\o3de\Code\Tools\TestImpactFramework\Runtime\Common\Code\Include\Static\BuildTarget/Common/TestImpactBuildGraph.h(156): 'auto __cdecl TestImpact::BuildGraph<class TestImpact::NativeProductionTarget,class TestImpact::NativeTestTarget>::{ctor}::<lambda_2>::operator ()(const class …
```
=> Test Impact Analysis Divide by zero fix

Code/Framework/AzCore/AzCore/Component/Component.cpp, Code/Framework/AzCore/AzCore/Component/Component.h, Code/Framework/AzCore/AzCore/Component/Entity.cpp, Code/Framework/AzCore/AzCore/Component/EntitySerializer.cpp, Code/Framework/AzCore/AzCore/Component/EntitySerializer.h, Code/Framework/AzCore/AzCore/Component/EntityUtils.cpp, Code/Framework/AzCore/AzCore/Component/EntityUtils.h, Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityActionComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorComponentBase.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorComponentBase.h, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorDisabledCompositionComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorDisabledCompositionComponent.h, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorPendingCompositionComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorPendingCompositionComponent.h, Code/Framework/AzToolsFramework/Tests/ComponentAddRemove.cpp
Fixes empty component alias issue: https://github.com/o3de/o3de/issues/15546
This PR aims to fix the empty component alias issue that happens to components stored in pending and disabled composition components. The issue started to occur after we changed to use component type names as component aliases in PR https://github.com/o3de/o3de/pull/15256.
A non-empty component alias for a component stored in the composition component is required for ensuring correctness of override patching because patches have paths that contain component aliases. They can't be empty. Note that before using component type name as aliases, there was no issue since we used component ids as the aliases. To learn more, see the attached GHI.
**Change List:**
1. Changed to use map (not vector) to store component …
=> Handle component aliases in editor composition components

Gems/Atom/Feature/Common/Code/Source/ImGui/ImGuiPass.cpp
Sometimes, on shutdown, during the level unload if there are any queued input events IMGUI will try to process them. However, IMGUI's pipeline might be null at this point, causing a crash. This fixes the crash.
Ran MPS ServerLauncher and shut it down multiple times without a crash.
=> Fix occasional shutdown crash

Code/Tools/TestImpactFramework/Runtime/Python/Code/testimpactframework_runtime_python_files.cmake
With VS 2019, some of us were seeing occasional compile errors when compiling the TestImpact.Runtime.Python.Static project that looked like this:
```
62>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\xlocinfo.h(18,17): error C5032: detected #pragma warning(push) with no corresponding #pragma warning(pop)
62>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\xlocinfo.h(18,17): error C5032: #pragma warning(push, _STL_WARNING_LEVEL)
62>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\xlocinfo.h(18,17): error C5032:                 ^
62>Done building project "TestImpact.Runtime.Python.Static.vcxproj" -- FAILED.
```
Further investigation …
=> Workaround for a presumed VS2019 compiler bug causing compile errors

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/FilterAdapter.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/FilterAdapter.h, Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/ElidingLabel.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/ElidingLabel.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ComponentEditor.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ComponentEditorHeader.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ComponentEditorHeader.hxx
Fixes #15504 
With the DPE enabled, any components that don't have fields (e.g. Audio Proxy, Network Test Player, etc...) weren't being shown in the Inspector. This is a common use-case for components that are meant to attach code/logic to an Entity but don't need any kind of data fields exposed to the Editor.
The components were being hidden because the RPE would still register at least one visible node (even though it wasn't actually shown) for any component, whereas the DPE queries the adapter which returns empty if there is nothing to display. It also thought it was empty even if a filter hadn't been specified yet.
The final issue uncovered for this scenario is that the RPE was able to match the filter based on the component name (because of the aforementioned invisible root node), …
=> DPE: Fixed missing components without data fields and filtering issues when DPE is enabled

cmake/Platform/Linux/Configurations_linux_x86_64.cmake, cmake/Platform/Linux/Packaging/snapcraft.yaml.in, cmake/Platform/Linux/PackagingPostBuild_linux.cmake, cmake/Platform/Linux/Packaging_Snapcraft.cmake, cmake/install/Findo3de.cmake.in
Rolls back some of the fixes for make snap packages work on Ubuntu 22.04, including:
- Removing paths to core22 in the Linux compiler and configurations in the CMake scripts
- Remove custom patchelf fixes and relying on the autopatch provided by Snapcraft 7.3
Re-sets the snap package dependencies for Ubuntu 20.04:
- Sets the base image to core20 (Ubuntu 20.04 container)
- Adds packages needed for Ubuntu 20.04 
Tested on a snap package built in a sandbox in Ubuntu 20.04 and 22.04
=> Snap package fixes for Ubuntu 20.04

AutomatedTesting/CMakePresets.json, Templates/MinimalProject/Template/CMakePresets.json, cmake/Projects.cmake, cmake/Subdirectories.cmake, scripts/o3de/o3de/cmake.py, scripts/o3de/o3de/register.py, scripts/o3de/tests/test_cmake.py
When a project is registered a
`<project-root>/user/cmake/engine/CMakePresets.json` will be added/updated which contains an "include" entry to the registered engine's ``CMakePresets.json` file
The Default and Minimal Project templates have had their `<project-root>/CMakePresets.json` file to include the generated `"user/cmake/engine/CMakePresets.json"` file.
This means that new projects will now opt-in to this functionality by default.
Added a CMakePresets.json file for the AutomatedTesting project that includes the file in the CMakePresets.json it's engine root directory.
Furthermore running cmake configfure will also update the `<project-root>/user/cmake/engine/CMakePresets.json` file to include the CMakePresets.json file using the path of the current engine being configured.
This does …
=> Updated o3de CLI register command to generate a CMakePresets file for project registration

Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Slot.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Variable/GraphVariableManagerComponent.cpp
Script Canvas nodes are _intended_ to support subclasses when hooking variables to input slots, but the subclass support was broken in a couple of spots:
1. The code was checking for "if slotType.is_a(variableType)" instead of "if variableType.is_a(slotType)", so the backwards check only worked if the slot type was a subclass of the variable. Instead, it should work if the variable is a subclass of the slot type.
2. When filling in the default variable choice after converting a slot to a reference, the code was only look for exact slot type matches from the list of variables. It now looks for subclasses as well.
Tested with an upcoming change that relies on using subclasses with the Spawning API in ScriptCanvas. Before the change, the dropdown only listed the "Spawnable" (type …
=> Fix subclass support on ScriptCanvas nodes.

Code/Framework/AzCore/AzCore/Serialization/EditContextConstants.inl, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/MultiLineTextEditHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyStringLineEditCtrl.cpp, Gems/AtomLyIntegration/AtomBridge/Code/Source/Editor/AssetCollectionAsyncLoaderTestComponent.cpp, Gems/LmbrCentral/Code/Source/Editor/EditorCommentComponent.cpp
Fixes #16065 
This fixes support for the `PlaceholderText` attribute in the DPE. Made several changes:
* Consolidated all usages of the attribute to a single constant instead of duplicating the crc throughout the code-base
* Registered the attribute with both the string line edit and multiline edit widgets
* Updated the string line edit handler to consume the attribute (This attribute was being passed in the `AssetCollectionAsyncLoaderTest` component for the json path field, but the handler for the string line edit never actually had support for this attribute, so it didn't work in the RPE either for this field)
BEFORE:
AFTER:
Tested both the `Comment` and `AssetCollectionAsyncLoaderTest` components that make use of this attribute on fields and verified they work as expected now.
=> Fixed PlaceholderText support in DPE

Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerTypes.h, Gems/Multiplayer/Code/Source/Components/SimplePlayerSpawnerComponent.cpp
1. Adds support for clearing the .network.spawnable asset again after it's been assigned on the Simple Player Spawner.
2. Adds error messages when trying to use the Simple Player Spawner with a prefab that has anything other than 1 networked entity in it.
Manually tested both cases above.
=> Simple Player Spawner error checking fixes

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
Fixes #16067 
Fixed an issue with the DPE handling of read-only attributes that was preventing them being handled for UIElements (e.g. buttons, groups). I moved the check to the generic `checkAttribute` location in the `LegacyReflectionBridge` so it gets all the same benefits of that method, but kept the special-case to ignore it if we'd already detected the ancestor node is disabled.
Here is a simple use-case in the `Transform` component where the `Add non-uniform scale` button should get disabled based on whether or not the  `Non-uniform Scale component` is present for this Entity. Before this change, the button is just always enabled.
BEFORE:
AFTER:
Tested according to repro steps listed in bug and above. Tested various other read-only usages on normal data elements (e.g. Mesh Stats in …
=> Fixed read-only handling in DPE to get applied to UIElements as well

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
Fixes #16075 and #16083
Added support for handling the `NameLabelOverride` attribute in the DPE. This was added to the `GetNodeDisplayLabel` that will continue to be extended in future PRs to handle additional name label overrides (e.g. child indexes).
BEFORE:
AFTER:
Tested the components mentioned in both issues and verified the expected labels now appear.
=> Added support for handling the NameLabelOverride attribute in the DPE

Templates/RemoteRepo/Template/repo.json, scripts/o3de/o3de/engine_template.py, scripts/o3de/o3de/register.py, scripts/o3de/tests/test_engine_template.py
This PR adds a new create-repo CLI function to engine_template.py, which supports creation of a remote repository that generates a repo.json template and registers it with the engine. This supports user to share their personal projects/Gems online.
I run the create-repo function from CLI and added the relevant variables and made sure the correct information was produced in the generated repo.json file and checks if the user provided repo_uri has been registered with the engine.
command used: ./o3de.bat create-repo -rp "C:\o3de_Projects\test1" -ru "https://github.com/VeryKaylin-player1/o3deRemoteRepo.git"
I also added a unit test name test_create_repo in test_engine_template.py and make sure the correct information was generated.
=> Add create-repo CLI and unit test for this function

Gems/DiffuseProbeGrid/Code/Source/EditorComponents/EditorDiffuseProbeGridComponent.cpp
Fixes #16077 
This fix actually isn't a DPE bug, but rather was an unnecessary placement of the "Bake Textures" button on the "Diffuse Probe Grid" component underneath a group with the same name. It appears the author wasn't aware of the ability to end the scope of a group (which is why I later added the `EndGroup` helper API), so this "Bake Textures" button was put underneath a group so that it wouldn't be grouped under the "Grid mode" group.
I came across this during DPE testing and it caught my eye as a potential DPE bug, but actually turned out to just be how it was reflected as it appeared the same in the RPE, but I went ahead and fixed it so that it wouldn't appear to others as a DPE bug.
BEFORE:
AFTER:
Tested on the "Diffuse Probe Grid" component and verified the "Bake Textures" …
=> Moved Bake Texture button out of group

Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
moves spammy "got patch for unimplemented PropertyHandler" warning behind ed_DebugDPE flag
Fixes #15924 
locally using the Editor project
=> move spammy propertyHandler warning behind ed_DebugDPE flag

Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasNodeable.xsd, Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasNodeable_Header.jinja, Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasNodeable_Source.jinja, Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvas_Nodeable_Macros.jinja
This PR adds additional styling options to Nodeables that users can take advantage of in a Nodeable's xml file. The following attributes were added:
HideName, which hides the name label of a data slot.
HideInputField, which hides the input field of a data slot.
Style, which sets the nodeable's style to the specified GraphCanvas substyle.
DisplayGroup, which sets the display group of a data or execution slot. Previously this only worked for execution slots.
Future PRs will utilize these new options for compact style small operator nodes.
Manual testing was preformed to test the effects of enabling these attributes. I created a new Nodeable node with these options:
To create this node:
I also created a simple script to test that the node worked as intended with these options enabled: …
=> Add additional attribute options to Nodeables

Gems/NvCloth/Code/Source/Components/ClothConfiguration.cpp, Gems/NvCloth/Code/Source/Components/ClothConfiguration.h, Gems/NvCloth/Code/Source/Components/EditorClothComponent.cpp, Gems/NvCloth/Code/Source/Components/EditorClothComponent.h
Fixes #16086 
This resolves a crash noticed when enabling the DPE and trying to inspect an Entity that has a Cloth component. The `ClothConfiguration` is owned by the `EditorClothComponent`, but is given callbacks that reference back to the `EditorClothComponent` because there are fields in the reflected data that are driven by querying a `Mesh` component that may or may not be on the same Entity. Instead of re-working the EditContext reflection for this, I opted to instead push pure data down to the `ClothConfiguration` instead of a callback for a safer flow of ownership.
Tested adding a Cloth component and verified the mesh node related fields are populated as expected when adding a Mesh component and assigning it a mesh with cloth capabilities.
=> Fixed crash in Cloth component

Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
now that the DPELayout has been fixed to consistently use DOM indices, we need to make sure that all children are in place in the DOM hierarchy before adding them to the layout. This fixes two cases where that ordering was incorrect.
locally in Editor project
=> Fix dom lookup by DPELaout

Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/PropertyEditorToolsSystem.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/PropertyEditorToolsSystem.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/PropertyEditorToolsSystemInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/PropertyHandlerWidget.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
Fixes #16057 
The initial fix to get asset property handlers to show (#15954) introduced a crash on certain enum/combo boxes. The first commit was to back out just the logic from that PR in `PropertyEditorAPI_Internals.h`. The new approach is similar in that we need to account for generic class info when searching for property handlers by type, but with two major differences:
1. No longer modify the `m_proxyClassData.m_typeId`, which led to crashes in other widgets (enum/combo boxes)
2. Instead of checking generic info in each handler every check, now we only fallback to looking at the generic info if the initial searches in the default and registered handlers fail to find a handler, which matches the logic flow for the RPE `PropertyManagerComponent::ResolvePropertyHandler`. 
Verified the …
=> DPE: Reworked finding generic property handlers

Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
Fixes #16127 
We need to disable the property handler recycling feature in the DPE in the short-term. The RPE creates a new property handler for each field that needs one, and because of this behavior many of our property handlers and the widgets they create store transient data about the field they are attached to. With the recycling feature in the DPE, this transient data never gets reset, and so bleeds over into unrelated fields causing random inconsistencies.
I've created a backlog item to revisit the property handler recycling in the future: #16135
There was a mechanism that was created to fix a specific issue with re-use of one handler's widget, but this same approach would need to be done for all of our supported handlers and widgets.
Tested with breakpoints in several property …
=> Disable property handler recycling in the DPE

Gems/ImGui/Code/Source/ImGuiManager.cpp
This is a temporary hotfix (may not be the ideal solution) for the current issue of not being able to exit the game mode in Linux after entering. Opening a PR for it to gather feedback.
Allow for exiting from game mode using ESC as intended.
#15958
Tested on Fedora 38, by checking to see if exiting game mode was possible by pressing ESC.
=> Linux game mode esc exit hotfix

Assets/Engine/SeedAssetList.seed, Code/Framework/AzCore/AzCore/Serialization/Json/JsonUtils.cpp, Code/Framework/AzCore/AzCore/Serialization/Json/JsonUtils.h, Code/Framework/AzCore/AzCore/Settings/SettingsRegistry.h, Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.cpp, Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.h, Code/Framework/AzCore/Platform/Windows/AzCore/IO/Streamer/StreamerConfiguration_Windows.cpp, Code/Framework/AzGameFramework/AzGameFramework/Application/GameApplication.cpp, Code/Framework/AzNetworking/Platform/Common/WinAPI/AzNetworking/Utilities/NetworkCommon_WinAPI.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Asset/AssetSeedManager.cpp, Code/LauncherUnified/Game.cpp, Code/LauncherUnified/Launcher.cpp, Code/LauncherUnified/Launcher.h, Code/LauncherUnified/Server.cpp, Code/LauncherUnified/Tests/Test.cpp, Code/LauncherUnified/Unified.cpp, Code/Tools/AssetBundler/CMakeLists.txt, Code/Tools/AssetBundler/source/ui/AssetBundlerTabWidget.cpp, Code/Tools/AssetBundler/tests/DummyProject/SeedAssetList.seed, Code/Tools/AssetBundler/tests/DummyProject/SeedAssetListObjectStreamXML.seed, Code/Tools/AssetBundler/tests/applicationManagerTests.cpp, Code/Tools/AssetBundler/tests/tests_main.cpp, Code/Tools/AssetProcessor/native/InternalBuilders/SettingsRegistryBuilder.cpp, Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp, cmake/Tools/layout_tool.py
The Setreg builder will now generate a `bootstrap.<launcher-type>.<config>.setreg` file.
There are now 9 setreg files that are generated
1. `bootstrap.client.debug.setreg` - loads in the `${project}.GameLauncher` (ClientLauncher) built in the debug configuration
1. `bootstrap.client.profile.setreg` - loads in the `${project}.GameLauncher` (ClientLauncher) built in the profile configuration
1. `bootstrap.client.release.setreg` - loads in the `${project}.GameLauncher` (ClientLauncher) built in the release configuration
1. `bootstrap.server.debug.setreg` - loads in the `${project}.ServerLauncher` (ServerLauncher) built in the debug configuration
1. `bootstrap.server.profile.setreg` - loads in the `${project}.ServerLauncher` (ServerLauncher) built in the profile configuration
1. …
=> Updated the SetregBuilder to generate per launcher aggregate setreg

Gems/AtomLyIntegration/AtomFont/Code/Source/FFont.cpp
When windows has a dpi setting such as 150%, the debug font in the Editor viewport are rendered with wrong size and layout. See the picture below:
This PR fixes the wrong font size. The screenshot after the change with dpi 200%:
This issue was brought in after the explicit render resolution change: https://github.com/o3de/o3de/pull/16027
o3de Editor
=> Fixed debug font size in Editor when windows has a DPI setting other than 100%

Assets/Engine/SeedAssetList.seed, Code/Tools/AssetProcessor/native/InternalBuilders/SettingsRegistryBuilder.cpp
The SubID calculation was taking into account the project name and project launcher executable name which would cause a different Asset SubID to be generated based on the active project.
That is not needed since each project has it's own Asset Cache and therefore the SubIDs values should be the same across all projects.
Currently building the AssetProcessor right now to validate that the SubIDs of the `bootstrap.<launcher-type>.<config>.setreg` files are the same when created across two different projects.
Update: Verified that both the AtomSampleViewer and AutomatedTesting project produces the same SubIds for the `bootstrap.<launcher-type>.<config>.setreg` files
=> Fixed calculation of `bootstrap.<launcher-type>.<config>.setreg` SubIDs

Code/Editor/StartupLogoDialog.cpp
The Editor startup dialog sometimes crashes, for me, when an information text is set.
This is because the text is, sometimes, set from a thread that is not the thread that the `QWidgets` are supposed to be updated from.
In Qt its not allowed to call the `setText` of the text widget in a thread that's not the Widget thread.
To solve this, the text is set through the `QMetaObject::invokeMethod` function (https://doc.qt.io/qt-6/qmetaobject.html#invokeMethod-8).
If the calling thread is not the widget thread, this function enqueues the function call. It is called when the `QEventLoop` of the widgets thread processes its events.+
If it is called from the widget thread, the passed function is called immediately ([Qt::AutoConnection](https://doc.qt.io/qt-6/qt.html#ConnectionType-enum))
This was …
=> Fix thread handling in Editor startup dialog

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.h, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
- adds ReflectionAdapter support for the "ContainerCanBeModified" flag for both container rows and container element rows
- fixes #16059 
- a few formatting and spelling fixes to adhere to O3DE's style guide
locally with the Editor project
=> Implement ContainerCanBeModified flag for DPE-based reflection

Gems/PhysX/Code/Include/PhysX/ArticulationJointBus.h, Gems/PhysX/Code/Source/ArticulationLinkComponent.cpp, Gems/PhysX/Code/Source/ArticulationLinkComponent.h
Modify `ArticulationLinkComponent` to implement extend ArticulationJointBus.
This PR is adding missing getters to `ArticulationJointBus`:
- `GetJointPosition`
- `GetJointVelocity`
Manual testing implementing, new features in ROS2 Gem.
=> Add missing getters to PhysX/ArticulationJointBus.

Gems/LyShine/Assets/Passes/RttChildPass.pass
Fix "Device Lost" error when creating a UI Canvas with a texture larger than the window size. 
The RTTChildPass was using the depth/stencil attachment from the ForwardPass. If the texture use by the UI Canvas was larger than the depth/stencil attachment of the ForwardPass, an error was generated when running on Vulkan. To fix it, the RTTChildPass now uses a transient attachment that matches the size of the texture used (the depth/stencil texture is cleared, so it wasn't using the depth information from the ForwardPass)
Fixes #13853
Run Editor with Vulkan and created a UI Canvas of size 1500x1000
=> Fix LyShine RTTChildPass depth attachment size issue

Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp, Gems/Atom/RHI/Metal/Code/Source/RHI/BindlessArgumentBuffer.cpp, Gems/Atom/RHI/Metal/Code/Source/RHI/BindlessArgumentBuffer.h, Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.cpp, Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.h, Gems/Atom/RHI/Metal/Code/Source/RHI/CommandQueueCommandBuffer.cpp, Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineState.cpp
Compile fixes for Ventura upgrade.
Tested ASV
=> Fixes for Compile errors related to macOS16 (Ventura)

.github/CODEOWNERS, Gems/Archive/Code/Source/Clients/ArchiveReader.cpp, Gems/Archive/Code/Source/Clients/ArchiveTOCView.h, Gems/Archive/Code/Source/Clients/ArchiveTOCView.inl, Gems/Archive/Code/Source/Tools/ArchiveWriter.cpp
Several integer values needed explicit static cast into smaller types
Built the Archive.Editor.Tests target successfully and verified that the Archive Unit Test also complete successfully as well.
=> Fixed Archive Gem build on MacOS

Code/Framework/AzFramework/AzFramework/Archive/Archive.cpp
Ensure game client pak-file settings aren't affected by the server's settings. 
This was causing MultiplayerSample to change how assets were loaded after connecting to servers.
Fixes https://github.com/o3de/o3de-multiplayersample/issues/396
=> Don't Replicate Server Asset Settings to Client

Gems/AWSCore/Code/Include/Framework/Util.h
Adding a new AWS Util for extracting data from an AWS ARN. 
Multiplayer Sample uses this to automatically find the AWS region in order to configure the client.
Helps fix: https://github.com/o3de/o3de-multiplayersample/pull/436
=> AWS Util to Extracting Data from an ARN

scripts/o3de.py, scripts/o3de/o3de/repo_properties.py, scripts/o3de/tests/test_repo_properties.py
Added a edit-repo-CLI function that edits the repo.json fields -> 
gems_data: add gems / remove gems / replace gems
template_data: add template / remove template / replace template
project_data: add project / remove project / replace project
the command to add a gem is: './o3de.bat edit-repo-properties -rp "C:\o3de_Projects\test1\repo.json" -ag "C:\o3de_Projects\o3de\Gems\Archive"'
I wrote unit test test_repo_properties.py file and tested through the command line argument to add, delete, and replace different objects.
=> Add edit-repo-properties CLI function and unit test

scripts/o3de/o3de/manifest.py
I'm running this in a neovim running from snap, I think a similar situation can be reproduced in vscode from snap. this is my terminal env SNAP_BUILD is not defined so o3de will fail to start.
=> bugfix: ignore SNAP_BUILD if not defined

AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Periodic_GPU.py, AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Smoke_GPU.py, Gems/Atom/Bootstrap/Code/Include/Atom/Bootstrap/BootstrapRequestBus.h, Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp, Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.h, Gems/AtomLyIntegration/AtomViewportDisplayInfo/Code/Source/AtomViewportDisplayInfoSystemComponent.cpp, Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystem.cpp, Gems/AtomTressFX/Code/Rendering/HairFeatureProcessor.cpp, Gems/ScriptAutomation/Code/Source/ScriptAutomationScriptBindings.cpp
User can set the pipeline's azasset file file to r_default_pipeline_name cvar at runtime to switch the render pipeline for Editor's 3d viewport or game launcher
The viewport debug info now has information of current render pipeline's name. Resolve the pass injections errors form hair FP and editorModeFeedback FP when switched to low end pipeline. Output warnings.
Tested with graphics/Stanza level and Graphics/PbrMaterialSheet level of AutomatedTesting project in Editor (dx12, Vulkan) and GameLauncher. 
Multiplayer Sample Project: works fine with dx12; got a device lost crash with vulkan when switch render pipeline.
=> User can switch render pipeline at runtime for Editor's main viewport and GameLauncher's viewport

Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/DirectionalLight.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/DiskLight.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/PointLight.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/DirectionalLightShadow.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/ProjectedShadow.azsli, Gems/Atom/RHI/Code/Source/RHI/PipelineState.cpp, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/RasterPass.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/RasterPassData.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RasterPass.cpp, Gems/Atom/RPI/Code/Source/RPI.Reflect/Pass/PassData.cpp, Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiPassTree.inl
Added ifdefs to disable shadow code when included in files that define ENABLE_SHADOWS to be 0, allowing such shaders to compile. Added option for RasterPass to set its viewport/scissor based on its output. Added RasterPass draw item count to ImGuiPassTree visualization to help debug how many draw items each RasterPass is receiving.
=> Misc Atom Improvements.

Gems/Atom/Feature/Common/Code/Source/Material/ConvertEmissiveUnitFunctor.cpp, Gems/Atom/Feature/Common/Code/Source/Material/ConvertEmissiveUnitFunctor.h, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
The light intensity in the StandardPBR material is defined in Ev100 in the Editor. However the shader expects Nits.
For the non-raytracing materials the intensity is converted using a Functor that is registered in the material (in `EmissivePropertyGroup.json`). This Functor is never called for the raytracing material.
My solution is to search for the specific Functor when creating the raytracing material, and convert the unit using this functor.
The solution is kind of dirty, but I can't think of another way, to convert the unit, with the current material system. The raytracing support, for materials, is quite limited currently.
Vulkan and Windows
=> MeshFeatureProcessor: Consider emissive intensity unit for raytracing materials

Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
This PR resolves #13990. Each AssetBrowser checks whether the focused widget is a descendant before entering the renaming functionality.
=> Check that AssetBrowser is focused before auto renaming.

Code/Tools/AssetProcessor/Platform/Mac/native/FileWatcher/FileWatcher_mac.h, Code/Tools/AssetProcessor/Platform/Mac/native/FileWatcher/FileWatcher_macos.cpp
Adds an async dispatch_queue_t to be used for the updated FSEventStreamSetDispatchQueue api as FSEventStreamScheduleWithRunLoop is deprecated
- Ran AP within ASV
- Ran AztestRunner with CL params **libAssetProcessor.Tests.dylib AzRunUnitTests --gtest_filter=FileWatcherUnitTest***
cwd = /Users/moudgils/GitHub/o3de-atom-sampleviewer/build/MacBuild/bin/profile
LIB: libAssetProcessor.Tests.dylib
Loading: libAssetProcessor.Tests.dylib
OKAY Library loaded: libAssetProcessor.Tests.dylib
OKAY Symbol found: AzRunUnitTests
Note: Google Test filter = FileWatcherUnitTest*
[==========] Running 17 tests from 3 test cases.
[----------] 13 tests from FileWatcherUnitTest
[ RUN      ] FileWatcherUnitTest.WatchFileCreation_CreateSingleFile_FileChangeFound …
=> Fix event stream related API deprecation

Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/Limits.h, Gems/Atom/RHI/Code/Include/Atom/RHI/RHISystem.h, Gems/Atom/RHI/Code/Source/RHI/Device.cpp, Gems/Atom/RHI/Code/Source/RHI/RHISystem.cpp, Gems/Atom/RHI/Code/Tests/Device.cpp, Gems/Atom/RHI/Code/Tests/Device.h, Gems/Atom/RHI/Code/Tests/Factory.cpp, Gems/Atom/RHI/Code/Tests/RHITestFixture.h, Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp
This PR is part of https://github.com/o3de/sig-graphics-audio/pull/137 (original proposal including discussion in https://github.com/o3de/sig-graphics-audio/issues/120, there referred to as (part of) commit 3 in the Planned git history sub-section) and lays the foundations for introducing multi-device versions of all relevant resource classes on the `RHI` level.
This MR holds all minor changes that affect the current code setup and is necessary as a first step for introducing multi-device resources as well as the ability to write tests that can utilize multiple devices.
The changes include:
- Moving multi-device command line parameter query to the `RPISystem`, which is more coherent and allows the test suite to instantiate the `RHISystem` in a multi-device fashion.
- Define `DeviceMask` …
=> Preparation for multi-device resources

scripts/o3de/o3de/engine_template.py
1. Checks if a folder already exists at the user provided path when user calls the create-repo cli command. Provides an error message telling user to use --force if they would want to override the current directory. 
2. If there is already a repo.json file in the directory, provided error message saying that a repo.json already exist and ask user if they want to edit the repo.json properties instead, if so, they should be using edit-repo-properties function.
3. fixes https://github.com/o3de/o3de/issues/16172 
I called create-repo function and pass in a path that already has a folder, and I now see an error message instead of a crash.  I choose --force to override that folder when prompted.
Here is the command I used when there was a already a folder existed at the path I provided: …
=> Repo Path Folder Exist Error Fix

scripts/o3de/o3de/repo_properties.py
If user use the --release-archive-path command without --download-prefix and error message would require user to pass in a --download-prefix along with an example of a github url
fix https://github.com/o3de/o3de/issues/16181
I used this command: ./o3de.bat edit-repo-properties -rp "C:\o3de_Projects\o3deRemoteRepo\repo.json" -ag "C:\o3de_Projects\o3deRemoteRepo\Gems\TestGem\" --release-archive-path "C:\o3de_Projects"
an error message would be: [ERROR] o3de.repo_properties: The -download-prefix must be provided. A url prefix for a file attached to a Github release might look like this: -dp https://github.com/o3de/o3de-extras/releases/download/2305.0
=> Add Check To Require Download-prefix To Be Provided With Usage Suggestion

Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp, Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorGraph.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasNodeable.xsd, Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasNodeable_Source.jinja, Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvas_Nodeable_Macros.jinja, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Slot.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Slot.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/SlotConfigurations.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/AbstractCodeModel.cpp
This PR allows execution slots to be given the attribute m_createsImplicitConnections. This makes it so the slot automatically connects itself to other nodes' execution slots behind the scenes when their data slots are connected. I do this by having implicit connections only create their entity in the Script Canvas gem without creating a corresponding visual connection entity in the Graph Canvas gem.
I also added a few more attributes to nodeables to allow for nodeable input execution slots to be given the m_createsImplicitConnections attribute, and for nodeble execution slots to be hidden.
Finally, I made a few changes in the AbstractCodeModel to ensure that execution out slots with multiple connections will always parse nodes with implicit connections first. I did this so people can …
=> Added functionality for implicit execution connections

Gems/PhysX/Code/Source/Pipeline/MeshAssetHandler.cpp, Gems/PhysX/Code/Source/Pipeline/MeshExporter.cpp
This adds the PhysX material dependencies to the PhysX mesh (pxmesh) assets. Without the dependencies, a rare Editor lockup could occur because when loading a pxmesh asset, the serialized material dependency would become a blocking asset load, which under the right circumstances could cause an unrecoverable deadlock. By adding the dependencies, the Asset Manager uses the dependencies to load all the assets in parallel with non-blocking loads, avoiding the deadlock situation.
The change to the call to LoadAssetStreamInPlace in the MeshAssetHandler is there to pass down the Asset Container filter callback which will assert if a dependent asset load is triggered without a proper dependency set up. This presumably was deliberately (and incorrectly) left off before to avoid the assert since …
=> Fix PhysX mesh material dependencies

Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Specific/EnvironmentCubeMapPass.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Specific/RenderToTexturePass.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Specific/SwapChainPass.cpp
This change fixed a crash when preview a pass tree attachment. 
Repro steps:
* Change windows DPI to 150%
* Run Editor with AutomatedTesting project with vulkan backend: add "-rhi=vulkan" to the command line when start Editor. 
* Open a level. For example, Graphics/Sponda
* Open PassTree tool via ImGui menu: press ` key to open the ImGui menu and PassTree tool is under Atom Tools menu.
* Enable show attachment and preview attachment
* Choose an image attachment in MainPipeline's pass tree
Tested with the repro steps.
ASV screenshot tests
=> Fixed pass attachment preview issue with vulkan in Editor when windows dpi is not 100%

Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.cpp
Indirect indexed draw did not work for the DX12 RHI, because the Index Buffer was never set.
The Index buffer is now set the same way as in the direct indexed draw case.
Windows and DX12, with a custom pass, that performs an indexed indirect draw.
=> DX12: Fixed indirect indexed draw

Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Job/TestImpactNativeShardedTestJobInfoGenerator.h
There is a scenario where the TestImpactNativeShardedTestJobInfoGenerator.h could attempt to perform a divide by zero operation where the number of test shards is 0.
Using Jenkins to run the TIAF job.
=> Add modulo by zero checks to the TIAF SharedTest JobInfo Generator

Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/Job/TestImpactNativeShardedTestJobInfoGenerator.h
The checks only check if the number of enabled test were greater than 1, but did not account for the number of enabled test fixtures being greater than 1 when the sharding configuration was for fixtures.
Successfully the TestImpact Analysis Frameworks targets successfully locally.
=> Hardended the NativeShardedTestRunJobInfoGeneratorBase sharding configuration checks

Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorTab.cpp
This PR resolves #15153. The expected vs saved path comparison was failing due to case differences.
Also fixes #14872.
Saved several asset types with correct results.
=> Fix saved asset name comparison

Code/Editor/AssetImporter/AssetImporterManager/AssetImporterDragAndDropHandler.cpp, Code/Editor/AssetImporter/AssetImporterManager/AssetImporterDragAndDropHandler.h, Code/Editor/AssetImporter/AssetImporterManager/AssetImporterManager.cpp, Code/Editor/AssetImporter/AssetImporterManager/AssetImporterManager.h
This PR resolves #14434. Formerly, a successful file copy/move operation would not clear up after itself, leading the drag/drop handler to assume the operation was still in progress, and trying to re-import the previously imported asset if the import menu option was subsequently used. 
Dragged multiple assets into the editor from explorer successfully.
=> Fix error when trying to import a second asset.

Code/Framework/AzCore/AzCore/RTTI/ReflectContext.h, Code/Framework/AzCore/AzCore/Serialization/SerializeContext.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
- Defines `SetTrueLabel` and `SetFalseLabel` attributes so that the `Type` property of the `PhysX Dynamic Rigid Body
` component is populated correctly.
- Also fixes minor issues in comments.
BEFORE:
AFTER:
=> DPE | Fix PhysX Dynamic Rigid Body type property labeling

Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/AbstractCodeModel.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/AbstractCodeModel.h
This PR allows for nodes with an execution in slot marked with the m_createsImplicitConnections attribute to be able to parse when it has more than one data in slot. This is accomplished during parsing, where implicit connections connected to nodes with implicit connections that have not been parsed yet will be ignored.
This PR also fixes a crash that happens when nodes that have implicit connections are deleted by refreshing selections before the deletion of nodes. This crash previously only happened on Linux and was fixed here: https://github.com/o3de/o3de/pull/9698.
Tests for ScriptCanvas and ScriptCanvas Editor were run locally. I also did manual testing by creating, deleting, undoing, and redoing connections. Three simple nodeables were created to test functionality, one that …
=> Parsing for implicit connections to nodes with multiple data slots

Templates/RemoteRepo/Template/Gems/README.md, Templates/RemoteRepo/Template/Projects/README.md, Templates/RemoteRepo/Template/Templates/README.md, Templates/RemoteRepo/template.json, scripts/o3de/o3de/repo_properties.py, scripts/o3de/tests/test_repo_properties.py
1. Auto Creates Gems/Projects/Templates folder when create-repo command is called, each with README.md inside of them that clarifies what should be placed in those folders. 
2. Allow repo.json to generate a backup file called repo.json.bak every time user made a change to their repo.json file
1. Auto generation of folders is tested by calling this command to create a remote repo:
> ./o3de.bat create-repo -rp "C:\o3de_Projects\RemoteRepoCheck\repo.json" -ru "https://github.com/VeryKaylin-player1/RemoteRepoCheck"
Result: Three folders would show up with appropriate README.md files inside them with appropriate message
- Rerun all unit test in test_repo_properties.py file to make sure adding this function won't affect the previous functions
2. To test repo.json.bak file call add command on …
=> Add README.md Files And Generate Repo.json.bak File When Change Is Made

Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorTab.cpp
Temporarily disable support for the DPE in the Asset Editor so that we can focus on the Entity Inspector for now. This will later be revisited to tackle the following issues that were found:
https://github.com/o3de/o3de/issues/16229
https://github.com/o3de/o3de/issues/16230
Tested the Asset Editor with the DPE enabled and verified the above issues no longer occur.
=> Disable DPE support in the Asset Editor

Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceObject.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceResource.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceResourcePool.h, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceObject.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceResource.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceResourcePool.cpp, Gems/Atom/RHI/Code/atom_rhi_public_files.cmake
This PR is part of https://github.com/o3de/sig-graphics-audio/pull/137 (original proposal including discussion in https://github.com/o3de/sig-graphics-audio/issues/120, there referred to as (part of) commit 3 in the Planned git history sub-section) and introduces the base resource classes from which most multi-device classes inherit, which includes
- `MultiDeviceObject`
- `MultiDeviceResource`
- `MultiDeviceResourcePool`
|--- | --- | --- |
|Preparation …
=> Multi-device base resources

Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/CreateDocumentDialog.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialBrowserInteractions.cpp
Fixes bug reported by @rainbj. Create in the AB context menu shouldn't show the filepath.
Tried to create a material and a material graph and watched the result.
=> Remove folder selection for move when location is selected by user already. #13759

Gems/Atom/Feature/Common/Assets/Passes/BloomDownsample.pass
This PR addresses a crash issue on Linux that occurs when the Bloom component is enabled. The fix resolves the problem, allowing the Bloom component to function properly.
The root cause of the crash was identified as the usage of strings for the WidthMultiplier and HeightMultiplier parameters in some pass templates. This resulted in zero-sized images being generated in the RHI::Size PassAttachmentSizeMultipliers::ApplyModifiers(const RHI::Size& size) const function.
It is worth noting that this issue may also be related to the following tickets:
#4812
#7400
Additionally, there are other template passes that utilize the same approach and may require similar fixes.
The changes in this PR were tested on Linux within the O3DE Editor environment to ensure its functionality and verify the …
=> [LINUX] Fix crash when enabling bloom component.

Gems/GraphCanvas/Code/Source/Components/Nodes/General/GeneralNodeLayoutComponent.cpp, Gems/GraphCanvas/Code/Source/Components/Slots/Data/DataSlotLayoutComponent.cpp, Gems/GraphCanvas/Code/Source/Components/Slots/Data/DataSlotLayoutComponent.h, Gems/GraphCanvas/Code/Source/Components/Slots/Execution/ExecutionSlotLayoutComponent.cpp, Gems/GraphCanvas/Code/Source/Components/Slots/Execution/ExecutionSlotLayoutComponent.h, Gems/GraphCanvas/Code/Source/Components/Slots/SlotComponent.cpp, Gems/GraphCanvas/Code/Source/Components/Slots/SlotComponent.h, Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Components/Slots/SlotBus.h, Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Styling/definitions.h, Gems/ScriptCanvas/Assets/ScriptCanvas/StyleSheet/graphcanvas_style.json, Gems/ScriptCanvas/Code/Editor/Nodes/NodeDisplayUtils.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasNodeable_Source.jinja, Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvas_Nodeable_Macros.jinja, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Slot.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Slot.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/SlotConfigurations.h
This PR adds some styling fixes for upcoming small operators:
- The compact substyle that small operators use has been more apropriately renamed from "small" to "compact". The unfinished small operators hidden behind the cvar "ed_showSmallOperators" also had their style updated to this name, and will be removed in a future PR
- Slots can now make use of a new "m_isNameHidden" attribute, which prevents the name of a slot from appearing in the graph. This was added because slots often use their name to identify themselves, so slots couldn't just be given an empty string for a name. Several small operators will take advantage of this attribute
- The Autogen HideName attribute now enables the m_isNameHidden attribute in the slot's SlotConfiguration
- Compact nodes' slots' names that are …
=> Style fixup for upcoming compact nodes

Gems/Atom/RPI/Code/Source/RPI.Public/Pass/FullscreenTrianglePass.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/CoreLights/DirectionalLightBus.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DirectionalLightComponentController.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DirectionalLightComponentController.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorDirectionalLightComponent.cpp
- Added AZ Event to notify config changes
in Directional Light component.
- Fixed crashed in FullscreenTrianglePass that occurred when the PassData comes from PassRequest defined insize an *.azasset. Unlike the PassBuilder, the AnyAssetBuilder doesn't record the shader AssetId, so we have to discover the asset id at runtime.
- Placed breakpoints in `EditorDirectionalLightComponent::OnConfigurationChanged()` and the event is signaled upon change any of the configuration parameters in the Inspector panel for the EditorDirectionalLightComponent.
- Validated in another project that requires this event and it worked too.
- Also in the other project I found the crash related with FullscreenTrianglePass and the crash doesn't occur anymore.
=> Added AZ Event to notify Directional Light component config changes

Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/IndirectRendering.azsli, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.cpp, Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/IndirectBufferLayout.h, Gems/Atom/RHI/Code/Include/Atom/RHI/DispatchRaysItem.h, Gems/Atom/RHI/Code/Source/RHI.Reflect/IndirectBufferLayout.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/IndirectBufferSignature.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI.Reflect/Conversion.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/IndirectBufferSignature.cpp, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridRayTracingPass.cpp, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridVisualizationRayTracingPass.cpp
This PR adds support for indirect ray tracing (similar do indirect draw commands) to the Vulkan and DX12 RHI.
The accompanying change to AtomSampleViewer can be found in https://github.com/o3de/o3de-atom-sampleviewer/pull/510
I tested the PR with the AtomSampleViewer using Samples->Features->SSAO and changeing to RTAO in the sidebar on the right, with both Vulkan and DX12. The results looked the same before and after the change.
=> [Atom] Add indirect raytracing command

Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.hxx, Gems/GradientSignal/Code/Source/Editor/EditorStreamingImageAssetCtrl.cpp, Gems/GradientSignal/Code/Source/Editor/EditorStreamingImageAssetCtrl.h
Fixes #16242 
The image gradient component uses a custom asset handler for its image asset field. This custom handler mostly copies from the default asset property handler and introduces some specific logic, but wasn't copying the default asset property handlers type logic, so it wasn't being found in the DPE.
BEFORE:
AFTER:
Tested the image gradient asset field and other asset fields (e.g. mesh, script canvas) and verified they work as expected with DPE both enabled and disabled.
=> Fixed the gradient image asset handler in DPE

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp, Code/Framework/AzToolsFramework/Tests/Prefab/Overrides/PrefabInspectorOverrideTests.cpp
Fixes the DPE logic that determined where UI Elements are placed in the Inspector Component Cards.
Code now correctly places buttons in groups.
BEFORE:
AFTER:
=> DPE | Fix UI Element grouping

Gems/Atom/RHI/Code/Include/Atom/RHI/DispatchRaysItem.h
Add a missing include and a forward declaration in the file `DispatchRaysItem.h`, which led to compile errors when using this class in an external gem with a non-unity-build configuration.
No testing other than checking if it compile successfully, since no functionality was changed.
=> Add missing include and forward declaration

Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
During shutdown of a GameLauncher we get a few crashes when using vulkan. 
Press the [x] in the game-launcher when running in the debugger, and observer fewer crashes.
=> reorder the shutdown sequence for vulkan to fix a few crashes

Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/Interpreted/ExecutionStateInterpretedPerActivation.cpp
This PR fixes a "no lightuserdata" assert that was hit in Gems\ScriptCanvas\Code\Include\ScriptCanvas\Execution\Interpreted\ExecutionStateInterpretedAPI.cpp whenever a graph with at least one node with a latent output was run in the intepreter, stopped, and then run again in the Script Canvas interpreter.
Manual testing was preformed by starting, stopping, and starting again various graphs in the interpreter. Local tests for ScriptCanvas and ScriptCanvas Editor were run as well.
=> Fix assert in Script Canvas interpreter

scripts/o3de/o3de/repo_properties.py, scripts/o3de/tests/test_repo_properties.py
Add the --auto-update CLI option to repo-properties.py and include the associated unit test. This CLI should be capable of automatically detecting any Gems/Projects/Templates present in the remote repository folder but not registered with the repo.json file, then update that object in the user's repo.json file.
- User can specify which type of object they want to auto-update. The command for using this CLI is:  `o3de.bat edit-repo-properties -rp "C:\o3de_Projects\test2\repo.json" -au gem`
- you can use the last argument parameter with other objects
For example : `-au gem`, `-au project`, `-au template`, or `-au gem project template`
1. I added unit tests that made sure the _auto_update function got called and mocked that function to make sue the correct object gets updated in the …
=> Add Auto Update CLI and Unit Test

Gems/AWSClientAuth/Code/Source/AWSClientAuthSystemComponent.cpp, Gems/AWSClientAuth/Code/Source/Authorization/AWSCognitoAuthorizationController.cpp, Gems/AWSClientAuth/Code/Tests/AWSClientAuthGemMock.h, Gems/AWSClientAuth/Code/Tests/AWSClientAuthSystemComponentTest.cpp, Gems/AWSCore/Code/Include/ResourceMapping/AWSResourceMappingBus.h, Gems/AWSCore/Code/Source/ResourceMapping/AWSResourceMappingManager.cpp, Gems/AWSCore/Code/Source/ResourceMapping/AWSResourceMappingManager.h, Gems/AWSCore/Code/Tests/Framework/ServiceClientJobConfigTest.cpp, Gems/AWSGameLift/Code/AWSGameLiftClient/Tests/AWSGameLiftClientManagerTest.cpp
- Adding HasResourceType to AWSResourceMappingManager, thus allowing users to check if a property exists instead of requesting the property and receiving a warning that it doesn't exist.
- Cleaning up AWS warning about undefined Cognito User Pools. User Pools aren't required, so the warning was giving developers a sense that something is wrong when it's fine.
=> Cognito User Pools Warning Cleanup

Gems/AtomLyIntegration/AtomBridge/Code/Source/FlyCameraInputComponent.cpp, Gems/AtomLyIntegration/AtomBridge/Code/Source/FlyCameraInputComponent.h
This pull request introduces an enhancement to the FlyCameraInputComponent by incorporating up/down navigation control using the keys 'Q' and 'E' for keyboard input, as well as utilizing the left and right triggers for controller input.
In certain instances, particularly while navigating in Game Mode, there is often a need to move vertically without adjusting the camera's pitch. Hence, the inclusion of this feature as an extension to the FlyCameraInputComponent would prove beneficial.
Validation of this pull request was conducted through testing within the Editor's Game Mode.
=> Allow navigation in up and down direction.

Code/Framework/AzToolsFramework/AzToolsFramework/Slice/SliceTransaction.cpp
… fix it by keeping the original path cases
Fix the error in https://github.com/o3de/o3de/issues/16309 which was caused by normalizing the save path with lower case letters. This pr  preserves the pull temp path and the full path in its original casing.
Compiled a fresh project as source build. Used UI editor to create and save new UI slices. Slices were now getting saved in the requested location without any error.
=> Fix slice save error

Gems/AWSClientAuth/Code/Source/Authorization/AWSClientAuthCognitoCachingAuthenticatedCredentialsProvider.cpp, Gems/AWSClientAuth/Code/Source/Authorization/AWSCognitoAuthorizationController.cpp, Gems/AWSClientAuth/Code/Tests/Authorization/AWSCognitoAuthorizationControllerTest.cpp
Reduces AWS Authorization spam. 
Avoid making AWS requests if the Cognito identity pool was never set in the first place.
Tested by opening Editor and GameLauncher with AWSAuthClient gem enabled.
Ensured authorization still works after game initializes AWS with a proper Cognito identity pool.
Old spam is gone...
```
[Warning] (AwsNativeSDK) - [AWS] AWSErrorMarshaller - Encountered AWSError 'ValidationException': 2 validation errors detected: Value '' at 'identityPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w-]:[0-9a-f-]; Value '' at 'identityPoolId' failed to satisfy constraint: Member must have length greater than or equal to 1
Exception name: ValidationException
Error message: 2 validation errors detected: Value '' at 'identityPoolId' failed to …
```
=> AWS ClientAuth Identity Pool Spam Reduction

Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp, Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorGraph.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Graph.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Graph.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Node.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Node.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/SlotExecutionMap.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/SlotExecutionMap.h
This PR makes the following changes:
- Implicit slots will now always connect to the proper execution slot, allowing upcoming compact or small operator style nodes to work properly with all nodes in ScriptCanvas, including those with multiple execution ins or outs.
- Fixed a typo by correcting "UpdateCorrospondingImplicitConnections" to "UpdateCorrespondingImplicitConnections".
- Added comments to SlotExecutionMap.h.
- Added methods to ScriptCanvas::Node for retrieving a slot's corresponding execution or data slots.
Testing was done manually by connecting, disconnecting, reconnecting, undoing, and redoing, and then running graphs in the interpreter. Local tests were also run. Here is an example graph that was tested to ensure that implicit connections were properly being made to latent …
=> Compact node compatibility with nodes that have multiple execution ins/outs

Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.cpp
Changes the LuaIDE editor's save dialog to use the project path by default.
Fixes #15934
Built profile and release on Linux with Clang 16.0.6
Launched LuaIDE with `./LuaIDE --project-path=/my/project/path and confirmed the new file dialog opens to the project root.
Launched LuaIDE without a project path and it behaves as normal (complains that the executable's path doesn't contain a project"
=> Change LuaIDE save dialog to use project path by default

Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasNodeable_Header.jinja
Fixes the generated code for ExtendConfigureSlots so that it compiles properly for nodes outside the ScriptCanvas namespace
=> Fixes the generated code for ExtendConfigureSlots

Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.hxx, Gems/LyShine/Code/Editor/LyShineEditorSystemComponent.cpp, Gems/LyShine/Code/Editor/PropertyHandlerCanvasAsset.cpp, Gems/LyShine/Code/Editor/PropertyHandlerCanvasAsset.h, Gems/LyShine/Code/Source/World/UiCanvasAssetRefComponent.cpp, Gems/LyShine/Code/lyshine_uicanvaseditor_files.cmake
Fixes #16084 
This fixes the issue with the canvas asset property on the `UI Canvas Asset Ref` component not showing up. The short answer is its using a simple reference asset type, which uses an underlying base-class handler that doesn't function properly in the DPE, so to resolve this I registered a custom handler for the explicit property type that makes uses of the default asset property handler.
BEFORE:
AFTER:
I've created a backlog item to potentially revisit the generic base class handler property type support, but I believe the proper workflow going forward is either registering the property handler with the expected type (which covers most of our properties), or use a templated data type like the asset property handlers: https://github.com/o3de/o3de/issues/16347
Tested the canvas …
=> Modified canvas asset to use custom property handler

Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasNodeable.xsd, Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasNodeable_Source.jinja, Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvas_Nodeable_Macros.jinja
This PR allows users to add a "Preset" attribute to AZAutogen nodes. Users can set this attribute to "compact" to automatically set default attributes for compact style nodes.
This PR also makes giving a description for slots optional. Slot descriptions for many compact nodes shouldn't be necessary, and for implicit slots that do not appear in the editor, descriptions are completely redundant.
This PR was tested manually by creating compact nodes using this preset with slots that do and do not have descriptions.
=> Add compact node preset to AZAutogen Nodeables

Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.cpp
Having multiple raytracing shaders (RayGen, Hit, Miss) in the same `.shader` file leads to errors in the DX12 debug layer. The errors look something like this:
`D3D12 ERROR: ID3D12Device::CreateStateObject: Export "RayGen" already defined. [ STATE_CREATION ERROR #1194: CREATE_STATE_OBJECT_ERROR]`
This is because the shader libraries, passed to the `RayTracingPipelineStateDescriptor` are duplicates of each other.
In this PR, we check for duplicates in the shader libraries, so each one is only attached once.
Windows and DX12/Vulkan. For DX12 it now works, Vulkan still works.
=> DX12: Raytracing: Support multiple shaders in one source file

AutomatedTesting/Gem/PythonTests/editor/EditorScripts/AssetBrowser_SearchFiltering.py, Code/Framework/AzQtComponents/AzQtComponents/Components/FilteredSearchWidget.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/FilteredSearchWidget.h
Fixes an issue where the Asset Browser's favorite system was being added to the` AzQtComponents::FlowLayout` and the interaction was causing a second scroll bar to appear. Whenever the favorite system is being used, the FlowLayout is no longer used. 
This means that there will no longer be overflow control if a user has too many filters set, but since the new asset browser is docked to the bottom this should not be a concern for the majority of users. If the window is resized too small, the names of each filter will resize to their minimum sizes. 
Fixes #16345
Previously:
Now:
Tested by using the asset browser, and by using material canvas which uses the FilteredSearchWidget without favorites.
=> Fix second scroll bar in AB

Gems/Camera/Code/Source/CameraComponentController.cpp
If a camera-Component has no other components that update the transform of the entity, the camera-transform initialized with the wrong position, and never updated.
Create a scene with a single, active camera that doesn't have a 'FlyCameraInputComponent', and start the GameLauncher using this scene. The camera position will be wrong without this fix.
=> Initialize the transform for static camera-components properly

Gems/Atom/Feature/Common/Assets/Passes/PassTemplates.azasset
Fixes runtime crash that was introduced by
PR https://github.com/o3de/o3de/pull/16326
It caused the AP to fail building
Gems/Atom/Feature/Common/Assets/Passes/PassTemplates.azasset
Which in turn caused the Editor to crash at startup in Debug mode
The AP doesn't complain anymore and The Editor doesn't crash anymore when loading.
=> Fixes runtime crash that was introduced by

Gems/PhysX/Code/Source/ArticulationLinkComponent.cpp, Gems/PhysX/Code/Source/EditorArticulationLinkComponent.cpp
Added ArticulationLinkService to list of services provided by ArticulationLinkComponent and EditorArticulationLinkComponent.
This is needed to resolve https://github.com/o3de/o3de-extras/issues/389, where JointsArticulationControllerComponent requires this component, but currently cannot list it as requirement.
https://github.com/o3de/o3de-extras/pull/393 relies on this PR to resolve https://github.com/o3de/o3de-extras/issues/389.
1. Add JointsArticulationControllerComponent to empty entity.
2. Component is not active. There is notification visible, informing of missing required component and suggesting to add PhysX Articulation Link.
=> Added ArticulationLink to services provided by ArticulationLinkComponent

Code/Legacy/CrySystem/LevelSystem/SpawnableLevelSystem.cpp, Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/Shadows/FullscreenShadowPass.h
- Crash when start loft scene game launcher: it was trying to build cullable before mesh was loaded.
- Lighting was wrong when load a new level while there is a level loaded: the new level entities were activated before entities from old level are deactivated. This leads to IBL fp reset its diffuse & specular maps to default.
Run game launcher for loft-arch-vis-sample project. 
Load Interior_03.prefab level.
Load Interior_03.prefab level again. 
Make sure the 3d rendering is same before and after load the Interior_03.prefab level the second time. 
Try switch to different levels then load Interior_03.prefab again. The rendering result should be the same.
=> Multiple fixes with game launcher for loft scene 

Gems/PhysX/Code/Source/ArticulationLinkComponent.cpp, Gems/PhysX/Code/Source/ArticulationLinkComponent.h
This PR adds a simple getter for all of the simulated body handles.
This will be used with the Vaccum gripper component https://github.com/o3de/o3de-extras/pull/369. It is used to further find the body handle for the gripper.
=> Add getter for all simulated body handles

Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp, Code/Framework/AzCore/Platform/Common/Apple/AzCore/std/parallel/internal/thread_Apple.cpp, Code/Framework/AzCore/Platform/iOS/AzCore/Module/DynamicModuleHandle_iOS.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h, Gems/Atom/Asset/Shader/Code/Source/Editor/AzslShaderBuilderSystemComponent.cpp, Gems/Atom/Asset/Shader/Config/Platform/iOS/shader_build_options.json, Gems/Atom/Feature/Common/Code/Source/ImGui/ImGuiPass.cpp, Gems/Atom/RHI/Code/Source/RHI/FrameScheduler.cpp, Gems/Atom/RHI/Metal/Code/Source/RHI/Conversions.cpp, Gems/Atom/RHI/Metal/Code/Source/RHI/Device.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/FullscreenTrianglePass.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/EditorCommonFeaturesSystemComponent.cpp
- Crash related to incorrect shader language. Explicitly setting it to metal shader language 2.2 as oppose to it picking one based not he operating system of the Mac where AP is running
- Crash related incorrect deployment target. Explicitly setting the OS version to iOS 14.0.
- Crash related to Imgui - Fixed Imgui's UV index stream to hold 4 byte integers as oppose to 1 byte as the drivers do not like that. Other option was to uncompress explicitly in the shader but it wasn't worth it to save 48 bytes. 
- Crash related to incorrect scissors when writing to non zero mip - Add support to clamp scissors based on the mip level of the render target
- Address Slow AP speeds by increasing thread priority - Increased thread priority for Apple to help AP processing.
- Address iOS compile/link …
=> Fix various issues related to iOS build and run on Iphone 8

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h, Gems/LmbrCentral/Code/Source/Audio/EditorAudioMultiPositionComponent.cpp, Gems/LmbrCentral/Code/Source/Audio/EditorAudioPreloadComponent.cpp, Gems/LmbrCentral/Code/Source/Audio/EditorAudioTriggerComponent.cpp, Gems/PhysX/Code/Editor/EditorJointConfiguration.cpp
Fixes #16063 and #16076 
This resolves two separate enum handling issues in the DPE. Cases that reflect the enum to the EditContext need to also have them reflected to the SerializeContext if they want to provide the values through EnumAttribute attributes. The other case is for specialized enum types that don't use u64 as the base type, they need special handling to make sure their value list gets passed on properly and that the changed value uses the proper proxy value.
Tested the repro cases in the listed issues and verified they now work as expected. Also tested various enum cases in the Editor.
=> Fixed issues with handling enums in DPE

Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/SlotConfigurationDefaults.h, Gems/ScriptCanvasTesting/Code/Source/Framework/ScriptCanvasTestFixture.h, Gems/ScriptCanvasTesting/Code/Source/Framework/ScriptCanvasTestNodes.cpp, Gems/ScriptCanvasTesting/Code/Source/Framework/ScriptCanvasTestNodes.h, Gems/ScriptCanvasTesting/Code/Tests/ScriptCanvas_Slots.cpp
This PR adds two integration tests to test nodes with slots that make implicit connections:
- SlotConnecting_ImplicitConnections, which tests if implicit connections are being made correctly between two nodes that do not have a Slot Execution Map
- SlotConnecting_ImplicitConnectionsSlotExecutionMap, which tests if implicit connections are being made correctly with a more complex node that does have a Slot Execution Map
Both tests make ConfigurableUnitTestNodes and configure one to have an execution input that makes implicit connections, and another to have execution output(s). Each node is given data slots that are connected and disconnected with checks to make sure implicit connections are being properly made/removed.
Manual testing was done to ensure that the tests passed and failed …
=> Add integration tests for implicitly connecting slots

Gems/PhysX/Code/Source/ArticulationLinkComponent.cpp, Gems/PhysX/Code/Source/ArticulationLinkComponent.h, scripts/o3de/o3de/engine_template.py, scripts/o3de/o3de/utils.py, scripts/o3de/tests/test_engine_template.py
When the replacement arg count is odd, one of the pairs will be missing a value  resulting in a script error.  This  PR checks for this case and provides better error messaging and a unit test.
Related documentation here: https://docs.o3de.org/docs/user-guide/programming/components/create-component/
Related command:
```cmd
scripts\o3de.bat create-from-template -dp MyCode -dn MyTest -tn DefaultComponent -kr -r ${GemName} MyGem
```
Also fixes #13644
Also fixes an issue where a file download would silently fail on Windows if a file URI was provided in an invalid format.
New unit tests were added and commands were testing in Windows terminal (bash and cmd).
Used the new remote repo functionality to generate a repo, add a gem with an archive to it and test downloading it using a `file:///` uri …
=> Fix invalid replace arg count error handling

Gems/ScriptCanvas/Code/Editor/Nodes/NodeCreateUtils.cpp, Gems/ScriptCanvas/Code/Editor/Nodes/NodeCreateUtils.h, Gems/ScriptCanvas/Code/Editor/ReflectComponent.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/GeneralNodePaletteTreeItemTypes.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/GeneralNodePaletteTreeItemTypes.h, Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.h, Gems/ScriptCanvas/Code/Editor/View/Widgets/ScriptCanvasNodePaletteDockWidget.cpp
This PR removes some unused code designed for creating data driven nodes, that was previously only used for the unfinished small operator nodes hidden behind a cvar. This code can be restored in the future if someone wanted to refactor how nodes in ScriptCanvas are created.
Local tests were run to make sure I wasn't breaking anything.
=> Remove old small operator / data driven node code

Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactCeilingNodeable.ScriptCanvasNodeable.xml, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactCeilingNodeable.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactCeilingNodeable.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactFloorNodeable.ScriptCanvasNodeable.xml, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactFloorNodeable.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactFloorNodeable.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactModuloNodeable.ScriptCanvasNodeable.xml, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactModuloNodeable.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactModuloNodeable.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactPowerNodeable.ScriptCanvasNodeable.xml, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactPowerNodeable.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactPowerNodeable.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactRoundNodeable.ScriptCanvasNodeable.xml, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactRoundNodeable.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactRoundNodeable.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactSquareNodeable.ScriptCanvasNodeable.xml, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactSquareNodeable.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactSquareNodeable.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactSquareRootNodeable.ScriptCanvasNodeable.xml, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactSquareRootNodeable.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Compact/MathematicalFunctions/CompactSquareRootNodeable.h, Gems/ScriptCanvas/Code/scriptcanvasgem_common_files.cmake, Gems/ScriptCanvas/Code/scriptcanvasgem_headers.cmake, Gems/ScriptCanvasTesting/Assets/ScriptCanvas/UnitTests/LY_SC_UnitTest_CompactNodeMathematicalFunctions.scriptcanvas, Gems/ScriptCanvasTesting/Code/Tests/ScriptCanvas_RuntimeInterpreted.cpp
This is the third PR of a series of 3 PRs for adding compact nodes to the node palette in Script Canvas. This PR adds nodes for common mathematical functions. More specifically, the following nodes were added:
- ceil
- floor
- mod
- pow
- round
- square
- sqrt
Link to first PR: https://github.com/o3de/o3de/pull/16382
Link to second PR: https://github.com/o3de/o3de/pull/16403
A unit test was created using the Script Canvas Testing framework to test that the nodes are producing their expected results:
=> Add mathematical function compact nodes

Code/Editor/Plugins/ProjectSettingsTool/ProjectSettingsToolWindow.cpp
In line 348, ResizeTabs is connected to the function currentChanged.
However, currentChanged returns -1 in case there is no new current widget:
https://doc.qt.io/qt-5/qtabwidget.html#currentChanged
This will cause a segfault, as the function ResizeTabs was not prepared to handle this case. This PR fixes that.
Issue:
resolves #16410
=> Fixed segfault caused by resizing a non-existent tab

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
Fixes components that don't have a parent invoke instance, such as Camera Rig and Fly Camera Input
fixes #16441 
Locally in the Editor app
=> fix for components like Fly Camera Input, that are their own reference

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/ContainerActionButtonHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/ContainerActionButtonHandler.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/GenericButtonHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/GenericButtonHandler.h
Fixes #16437 
This adds the feature for prompting the user when clearing a container in the DPE. I've added an improvement over the RPE, where previously this prompt was always displayed, but now in the DPE you can op-out of it for your container by setting the `PromptOnContainerClear` on your container element to `false`.
Tested all container buttons to make sure they all work as expected. Verified that the prompt only shows when attempting to clear at the container level, not just deleting a single element.
=> Added feature to prompt user on container clear for DPE

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp, Gems/Vegetation/Code/Source/Descriptor.cpp
Fixes #16337
Fixed crash when adding a `Vegetation Asset List` component due to the wrong instance pointer being used when evaluating `ElementAttribute`. The `ElementAttribute` are meant to be invoked against the actual element instances in the container, as opposed to normal `Attribute` which are (typically) invoked against the parent instance. The `ElementAttribute` sets the `m_describesChildren` on the attribute so we can check that flag to determine which instance pointer to use.
Another issue found once I fixed the crash was that all the advanced groups in the `Vegetation Asset List` were being shown but empty in the DPE (if the advanced toggle wasn't enabled). This is due to a limitation in the RPE where they don't process all attributes such as Visibility on groups, so you have to …
=> Fixed element attributes instance in DPE

Gems/Atom/Feature/Common/Assets/atom_feature_common_asset_files.cmake, Gems/Atom/RPI/Assets/atom_rpi_asset_files.cmake
Updated the cmake asset file lists, which adds .pass, .aszl, .shader and other files to the project list show they show up in Visual Studio. Updated them by running atom_rpi_asset_files.cmake and atom_feature_common_asset_files.cmake.
=> updating cmake asset file lists

Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp, Gems/AtomLyIntegration/AtomFont/Code/Source/FFont.cpp
Use actual pixel resolution for render resolution.
Apply DPI factor to debug font size and layout
This change fixed debug font size and layout issue when DPI is set to any value other than 100%
AutomatedTesting project, AutomatedTesting\Levels\Graphics\hermanubis_high level
Open the said level in both editor and game launcher with dpi 100 and dpi 150. Vulkan and DX12
Editor DPI 100% Vulkan
Editor DPI 150% Vulkan
Editor DPI 150% DX12
GameLauncher DPI 150% DX12
=> Fixed debug font size and layout issue with high DPI

Gems/Atom/Asset/ImageProcessingAtom/Code/Include/Atom/ImageProcessing/ImageObject.h, Gems/Atom/Asset/ImageProcessingAtom/Code/Source/ImageLoader/DdsLoader.cpp, Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageAssetProducer.cpp, Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvert.cpp, Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageObjectImpl.cpp, Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageObjectImpl.h, Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/PixelFormatInfo.cpp, Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/PixelFormatInfo.h
In addition to Width(x) and Height(y), the IImageObject interface now has awareness of Depth(z). This means the interface now supports Volume Textures, including mip levels. Consequently, relevant updates were made to CImageObject.
In terms of Asset Processing, only the `DdsLoader` was added the capability of loading Volume Textures.
Unlike Image2D, Volume Textures do not support
automatic generation of Mip Levels during asset processing. The Volume Texture is assumed to contain all the mips and the output streaming mip chain assets will contain the pixels for all Mip Levels.
The runtime can now load a StreaminImage from a dds.streamingimage asset that contains 3D Texture data.
First, it was validated that the existing 2D Image functionality is not broken. All ASV samples work as …
=> Added Volume(3D) Texture support to StreamingImage.

Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvas_Nodeable_Macros.jinja
Small PR that disables the use of references for compact style nodes, as compatibility between compact style nodes and references is still under development.
Manual testing was preformed by dragging and dropping variables from the variable browser.
=> Disable reference slots for compact nodes

Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayer.h, Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp, Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h, Gems/Multiplayer/Code/Tests/CommonBenchmarkSetup.h, Gems/Multiplayer/Code/Tests/MockInterfaces.h, Gems/Multiplayer/Code/Tests/MultiplayerSystemTests.cpp
- Adds AddNetworkInitHandler for dedicated servers and client-servers
- Adds sv_versionMismatch_check_enabled, allows disabling the server side checking the versions for debug purposes
- Fixes a case when a server level isn't correctly detected on a client joining
Locally with a multiplayer template project
=> Adds AddNetworkInitHandler and sv_versionMismatch_check_enabled

Code/Framework/AzFramework/AzFramework/Physics/RigidBodyBus.h
On Linux AZStd::mutex is non-recursive, however some use cases of physics require that mutex to be recursive.
Tested on Linux with a multiplayer template project.
=> Correcting physics mutex to be recursive

Tools/LyTestTools/ly_test_tools/_internal/managers/artifact_manager.py, Tools/LyTestTools/ly_test_tools/_internal/managers/workspace.py, Tools/LyTestTools/ly_test_tools/environment/file_system.py, Tools/LyTestTools/ly_test_tools/mobile/android.py, Tools/LyTestTools/ly_test_tools/o3de/asset_processor.py, Tools/LyTestTools/ly_test_tools/o3de/pipeline_utils.py, Tools/LyTestTools/tests/unit/test_workspace.py
Between the logic of checking whether a directory exist and making a call to create that directory in the ly_test_tools python script, a parallel execution of another test could create that directory
This would cause the directory creation in the current test to raise a python exception causing the test to fail.
Ran the `AutomatedTesting::EditorTestTesting` CTest Test successively which was exhibiting the race condition
```
[2023-07-18T13:52:49.321Z] ============================== warnings summary ===============================
[2023-07-18T13:52:49.321Z] test_parallel_1_pass_1_fail_1_crash.py::TestAutomation::run_parallel_tests[windows-AutomatedTesting-windows_editor]
[2023-07-18T13:52:49.321Z]   D:\workspace\o3de\python\runtime\python-3.10.5-rev1-windows\python\lib\site-packages\_pytest\ …
```
=> Fixed race condition in directory calls in ly_test_tools

Gems/Profiler/Code/Source/ProfilerSystemComponent.cpp
This is a spelling fix in a cpp file.
In [o3de/Gems/Profiler/Code/Source/ProfilerSystemComponent.cpp](https://github.com/o3de/o3de/blob/42e8f1f66373a0ea995a564b5ff7500df7fe9bab/Gems/Profiler/Code/Source/ProfilerSystemComponent.cpp), the struct name DeplayedFunction is corrected to DelayedFunction in all 4 instances of it in the file.
https://github.com/o3de/o3de/issues/16493
According to the testing page: https://www.docs.o3de.org/docs/user-guide/build/configure-and-build/#simulate-an-automated-review-run
Is this the test that I should run?:  python\python.cmd -u …
=> Fixed spelling: changed DeplayedFunction to DelayedFunction

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.h, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp, Code/Framework/AzQtComponents/AzQtComponents/DPEDebugViewStandalone/main.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
- Fixes NumericEditors of different types to use different Names, so that they can coexist in the PropertyEditorSystem and not overwrite each others' entries.
- Makes sure that the correctly typed reader/writer is used (no fallback), so that attributes of the wrong type are not skipped.
- fixes: #16453 #16455  #16476 #16477 #16488 #16489 #16490 #16475 
locally in both the Editor and DPEStandalone projects
=> NumericEditor attribute fix for better Min/Max support in the DPE Inspector

scripts/o3de/o3de/git_utils.py, scripts/o3de/o3de/github_utils.py, scripts/o3de/o3de/gitproviderinterface.py, scripts/o3de/o3de/repo_properties.py
This PR implements a --upload-github-release-tag CLI to use with the '--release-archive-path' CLI. It allows automatically uploading the release archive zip to Github with the required argument of tag_name. To use this feature, the user needs to provide their Github token with content read and write access. The CLI will detect if the current tag exists; if it does, it will upload the zip to the specified release. Otherwise, it will create a new release with the provided tag name and upload the zip to that release.
Additionally, this PR updates the current '--release-archive-path' CLI to still allow users to choose to provide '--download-prefix' if they are not using Github as their version control system.
Tested that the associated gem is created successfully on Github release and that …
=> Add Auto Upload Github Release CLI `--upload-github-release-tag`

Code/Editor/EditorViewportWidget.cpp, Code/Editor/Viewport.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportMessages.h, Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp
This PR is to fix this GHI: https://github.com/o3de/o3de/issues/16494
Change Windows DPI to 150%
Tested following functions in O3DE Editor:
- Use mouse to select entity
- Drag mouse to select multiple entities. 
- Drag an procprefab asset to viewport which creates a prefab entity at the position where the mouse was released
- Right click menu and choose Instantiate prefab to create a prefab entity. The entity was created at the center of the screen (expected behavior based on the code)
- Material editor: using mouse to control camera
- Animation editor: using mouse control camera.
=> Fix entity selection issue with high DPI setting

Gems/Atom/Feature/Common/Code/Source/CoreLights/CascadedShadowmapsPass.cpp, Gems/Atom/Feature/Common/Code/Source/CoreLights/CascadedShadowmapsPass.h, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.cpp, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h, Gems/Atom/RPI/gem.json
Follow-up to MR #16269:
- Fixed a few passes that used the `m_pipelineViewTag` variable directly, and may not get the right viewTag from the pipeline.
- Restored the function `HasPipelineViewTag()` and marked it as deprecated
- Increased the ATOM_RPI version from "0.0.0" to "0.0.1", as suggested by @AMZN-alexpete 
Make sure a default level still renders with the default renderpipeline
=> Pipelineviewtag from parent followup

Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
Fixes #16487 
This fixes a logic error that was preventing the `LOD Configuration` group from being shown on the `Mesh` component based on what the current LOD Type is set to. The reflection code used a `ShowLodConfig` method for the `Visibility` attribute on the group, but the RPE doesn't actually use the `Visibility` attribute for groups, and instead relies on the individual children elements to be shown/hidden, which is why this logic error was never caught.
The `LOD Configuration` group now shows up properly and shows the correct children based on the LOD Type as can be seen below:
Tested the `Mesh` component and verified the `LOD Configuration` group appears with the proper children based on the LOD Type with both DPE enabled and disabled.
=> Fixed logic error in visibility for LOD Configuration group

Code/Framework/AzCore/AzCore/RTTI/TypeInfoSimple.h, Code/Framework/AzFramework/AzFramework/Application/Application.cpp, Code/Framework/AzFramework/AzFramework/AzFrameworkModule.cpp, Code/Framework/AzFramework/AzFramework/Quality/QualityCVarGroup.cpp, Code/Framework/AzFramework/AzFramework/Quality/QualityCVarGroup.h, Code/Framework/AzFramework/AzFramework/Quality/QualitySystemBus.h, Code/Framework/AzFramework/AzFramework/Quality/QualitySystemComponent.cpp, Code/Framework/AzFramework/AzFramework/Quality/QualitySystemComponent.h, Code/Framework/AzFramework/AzFramework/azframework_files.cmake, Code/Framework/AzFramework/Tests/QualitySystemComponentTests.cpp, Code/Framework/AzFramework/Tests/frameworktests_files.cmake, Code/Legacy/CrySystem/SystemInit.cpp, Gems/Atom/Feature/Common/Registry/quality.setreg, Registry/quality.setreg
Adds initial quality system component, cvar groups and a `q_general`, `q_graphics`, and `q_shadows` quality groups setting registry files.
Quality group CVARs found in `/O3DE/Quality/Groups` are automatically created on application start and their quality level can be set from the console using the level name (e.g. "low" or "high") or the level index (e.g. 0 or 1).
If a default quality group is defined at `/O3DE/Quality/DefaultGroup` (currently `q_general`), the quality level for that group will be automatically loaded in `SystemInit.cpp` based on the default quality level for that group (currently "high") and eventually the level can be determined from device rules (future task).
Relevant RFC:  https://github.com/o3de/sig-core/issues/57
- Unit tests added for basic functionality
- …
=> Initial quality system component

cmake/Tools/common.py
When validating gradle, if an error occurs it was not sent to stderr, but instead stdout.
Therefore the error message would be loss.
With the fix all output is logged and errors are surfaced. For example one of the issues with validating gradle is that JAVA_HOME is not set correctly.
That kind of error message now outputs to the terminal
```
gradle cannot be resolved or there was a problem determining its version
number. Either make sure its in the system path environment or a valid
path is passed in through the --gradle-install-path argument.
ERROR: JAVA_HOME is set to an invalid directory: C:\Program
Files\Java\jdk1.8.0_311
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```
Verified that configuring Android using the …
=> Updated the verify_tool function to grab the error output from the exception output variable

Code/Framework/AzFramework/AzFramework/Application/Application.cpp, Code/Framework/AzFramework/AzFramework/Visibility/VisibleGeometryBus.cpp, Code/Framework/AzFramework/AzFramework/Visibility/VisibleGeometryBus.h, Code/Framework/AzFramework/AzFramework/azframework_files.cmake, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h
This change adds a bus and simple data structure to mine geometric data from visible or renderable components, like the mesh and shape components, without requiring access to or knowledge of the renderer or related assets. It has potential use cases for gathering and exporting scene geometry, occlusion culling, rendering debug information, and potential gameplay applications. The visible geometry data structure may be extended with additional members or flags that further described the type of geometry.
Added implementation for mesh component controller that builds and produces a dump of triangulated data.
Tests that compare against the expected geometry could be added for shapes and other components as implementations come online.
=> Initial visible geometry bus with mesh component controller bindings

Gems/Atom/RHI/Code/Source/RHI/FrameGraph.cpp, Gems/Atom/RHI/Code/Source/RHI/FrameGraphCompiler.cpp
Adds a few checks to avoid an exception when an attachment is unused. 
Add an image-attachment without any connections to the Parent-Pass in `MainPipeline.pass`. The result is now the message 
`[Error] (FrameGraph) - Invalid State: attachment 'Root.MainPipeline_0.TestImage' was added but never used!`, but no crash.
=> Don't crash if a framegraph attachment is unused

Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
Provide more information about which exact connection is actually causing an error.
Old:
`Pass::ProcessConnection - Pass [MainPipeline_0.SkinningPass] failed to find slot [SkinnedMeshOutputStreams].`
New:
`Pass::ProcessConnection MainPipeline_0.SkinningPass:SkinnedMeshOutputStreams -> MorphTargetPass:MorphTargetDeltaOutput: failed to find Local Slot.`
Introduce a faulty connection in the MainPipeline and watch the debug output.
=> Improve error-messages for Pass::ProcessConnection

Code/Legacy/CrySystem/XConsole.cpp
It is not valid to assert(this) and leads to a clang-15 error in warnings-as-error mode.
```XConsole.cpp:809:10: error: 'this' pointer cannot be null in
well-defined C++ code; pointer may be assumed to always convert to true
[-Werror,-Wundefined-bool-conversion]```
Compiling on linux clang-15.
=> Fixes a linux clang-15 compile error

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassAttachment.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassAttachment.cpp
When creating a pass request, e.g. the size of an attachment might depend on the size of another image/buffer. For this a size/format/multisampling/arraysize can be specified.
This does currently not work, if:
- The referenced image/buffer attachment, also has a size source
- The referenced attachment has a `Transient' lifetime
- The current attachment has an `Imported` lifetime
This happens e.g. when an images size is dependent on the input image size, which again is dependent on the PipelineOutput size.
This PR solves this issue, by recursively searching for the "original" size source, and use it.
The same is also true for the format/multipsampling/arraysize members.
Windows and DX12/Vulkan.
=> Pass attachment: Fetch *sources for attachments recursively

Gems/AudioEngineWwise/Code/CMakeLists.txt, Gems/AudioSystem/Code/CMakeLists.txt
This PR adds aliases in our audio gems so that unified launchers can depend on them. Otherwise, audio won't be loaded in the unified launchers (in the case that the game depends on audio).
This is the other half of the fix required to get audio working in the MultiplayerSample unified launcher: https://github.com/o3de/o3de-multiplayersample/pull/462
Built the MultiplayerSample unified launcher and verified that the audio now works. Also tested the game launcher and verified audio continues to work for it as well.
=> Fixed missing aliases in audio gems for unified launchers

Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridRayTracingPass.cpp
This PR fixes issue https://github.com/o3de/o3de/issues/16519
The issue happened because when probe ray tracing image was created, it may contains random data. 
When frame update count > 1, the DiffuseProbeGridRayTracing pass only writes to part of the image which are for the part of probes updating in current frame.
But the following passes which write to distance image or irradiance image all have blend function enabled which could use the probes data from the probe ray tracing image which may not be initialized. 
Follow the repro steps mentioned in the GHI https://github.com/o3de/o3de/issues/16519
=> Fix a diffuse probe grid issue when frame update count > 1

Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceFence.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceQuery.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceQueryPool.h, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceFence.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceQuery.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceQueryPool.cpp, Gems/Atom/RHI/Code/Tests/MultiDeviceQueryTests.cpp, Gems/Atom/RHI/Code/atom_rhi_public_files.cmake, Gems/Atom/RHI/Code/atom_rhi_tests_files.cmake
This PR is part of https://github.com/o3de/sig-graphics-audio/pull/137 (original proposal including discussion in https://github.com/o3de/sig-graphics-audio/issues/120, there referred to as (part of) commit 3 in the Planned git history sub-section) and introduces multi-device resource classes, in particular:
- `MultiDeviceFence`
- `MultiDeviceQuery`
- `MultiDeviceQueryPool`
|Preparation|[#16138](https://github.com/o3de/o3de/pull/16138)|merged|
|Base …
=> Introduce multi-device queries and fences

Code/Framework/AzCore/AzCore/std/containers/span.h
This PR fixes the message `Call to <function name> is ambiguous` when an `AZStd::array` is passed as a parameter to a function which accepts different types of `AZStd::span`, like this:
```
void A(AZStd::span<int> a) {  }
void A(AZStd::span<AZStd::string> a) {  }
....
AZStd::array<int, 3> b;
A(b);
```
This code change is similar to what is done eg. in the current standard library of MSVC.
No other tests than compiling the engine successfully
=> Fix implicit conversion from array to span

cmake/3rdParty.cmake
The query for the environment variable `LY_3RDPARTY_PATH` in 3rdParty.cmake is wrong, since it does not correctly detect if a system environment variable with this name exists.
This PR changes this to the syntax as suggested by https://cmake.org/cmake/help/latest/variable/ENV.html , which is also the syntax used in other CMake scripts in the engine.
After defining the LY_3RDPARTY_PATH-Variable in the Windows dialog "Environment Variables", it was picked up by the engine (eg. cmake output "-- Using package ..."), which was not the case before.
=> Fix LY_3RDPARTY_PATH environment variable query being wrong

Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/SimpleSpotLight.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingCommon.azsli, Gems/Atom/Feature/Common/Code/Source/CoreLights/SimpleSpotLightFeatureProcessor.cpp, Gems/AtomTressFX/Assets/Shaders/HairLightTypes.azsli
Normalizes the direction-vector of simple spot lights before uploading it to the GPU, to mirror the DiskLightFeatureProcessor.
Create a default scene with one simple spot light as the only light source and modify the direction.
=> normalize the direction of simple spot lights on the CPU

Code/Tools/SceneAPI/SceneCore/Tests/Utilities/PatternMatcherTests.cpp, Code/Tools/SceneAPI/SceneCore/Utilities/PatternMatcher.cpp, Code/Tools/SceneAPI/SceneCore/Utilities/PatternMatcher.h, Code/Tools/SceneAPI/SceneUI/RowWidgets/NodeListSelectionWidget.cpp, Code/Tools/SceneAPI/SceneUI/RowWidgets/NodeListSelectionWidget.h, Code/Tools/SceneAPI/SceneUI/SceneWidgets/ManifestWidgetPage.cpp, Code/Tools/SceneAPI/SceneUI/SceneWidgets/ManifestWidgetPage.h, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp, Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.cpp, Gems/SceneProcessing/Registry/SoftNameSettings.setreg
This is a set of bugfixes and optimizations that I discovered while trying to test FBX Settings for a file with a lot of submeshes:
* Optimization (PatternMatcher.cpp): changed Scene's PatternMatcher to only create the regex pattern matcher once on first use. This changed the time to display the LECT.fbx FBX Settings (which contains 27 submeshes) from 3.5 seconds to 2.99 seconds. The savings scale by the number of submeshes and the number of regex patterns.
* Optimization (NodeListSelectionWidget.cpp): changed the method of populating the widget's combobox list. The previous method worked fine for a few entries, but seemed to get exponentially worse as the number of entries went up. The new version seems to have a consistently negligible performance cost.
* Optimization …
=> Misc scene-related bugfixes and optimizations

Gems/AtomLyIntegration/AtomViewportDisplayInfo/Code/Source/AtomViewportDisplayInfoSystemComponent.cpp
One line crash fix for native android VR (tested with Quest 2)
GetCurrentPipeline() returns the pipeline at idx 0 of the m_currentPipelines array, which in VR is nullptr.
Dunno how important it is to draw the renderpipeline ID in VR?
=> Fix for nullptr crash on default pipeline dereference in native VR

Code/Framework/AzCore/AzCore/DOM/DomValue.cpp, Code/Framework/AzCore/AzCore/DOM/DomValue.h, Code/Framework/AzCore/AzCore/RTTI/AttributeReader.h, Code/Framework/AzCore/AzCore/base.h, Code/Framework/AzCore/Tests/DOM/DomValueBenchmarks.cpp, Gems/Atom/Feature/Common/Code/Source/PostProcess/DepthOfField/DepthOfFieldSettings.cpp
The AttributeReader had a feature gap that attempting to read an attribute that was of type `long` and `unsigned long` wasn't possible.
This issue is more apparent on Linux where the DPE stores it's attributes in a Dom::Value where it uses the standard C type aliases  of `int64_t` and `uint64_t`
However, while the standard type aliases are always 64-bits across platforms, they are *NOT* the same underlying type.
So on Windows `int64_t` and `uint64_t` are of type `long long` and `unsigned long long` respectively.
However on Linux and Android `int64_t` and `uint64_t` are of type `long` and `unsigned long long` respectively.
#Depth of field setting fixes
Clamped the setting of the Depth of Field Settings m_qualityLevel to [0, 2)
The DepthOfFieldSettings `m_qualityLevel` value is used to …
=> Fixed reading of `long/unsigned long` Attributes in the AttributeReader on Linux/Android

AutomatedTesting/Registry/viewport.setreg, Gems/AtomLyIntegration/AtomImGuiTools/Code/Source/AtomImGuiToolsSystemComponent.cpp, Gems/AtomLyIntegration/AtomImGuiTools/Code/Source/AtomImGuiToolsSystemComponent.h
This PR added a render pipeline selection menu to ImGui menu so user can switch render pipeline at runtime. 
The render pipeline paths are defined in setting registry "/O3DE/Viewport/SwitchableRenderPipelines". 
A setting registry file is added to AutomatedTesting project. 
Run AutomatedTesting game launcher. Enable ImGui menu. Select Render Pipeline -> LowEndRenderPipeline. The render pipeline was changed to LowEndPipeline ( in debug info text)
=> Add render pipeline switching menu in ImGui menu

Gems/PhysX/Code/Source/ArticulationLinkComponent.cpp
This PR is bugfix for problems reported  (partially) https://github.com/o3de/o3de/issues/16479 and  
https://github.com/o3de/o3de/issues/16572
Successful build with PhysX 5 enabled against https://github.com/o3de/o3de-physics-test-scene using VS2019.
=> Added maybe unused to eliminate C2220 on VS2019 and VS2022

Code/Tools/SceneAPI/SceneCore/Containers/Utilities/SceneGraphUtilities.inl, Code/Tools/SceneAPI/SceneCore/Events/GraphMetaInfoBus.h, Code/Tools/SceneAPI/SceneData/Behaviors/BehaviorsMeshGroup.cpp, Code/Tools/SceneAPI/SceneData/Behaviors/BehaviorsSkeletonGroup.cpp, Code/Tools/SceneAPI/SceneData/Behaviors/BehaviorsSkinGroup.cpp, Code/Tools/SceneAPI/SceneData/Behaviors/BlendShapeRuleBehavior.cpp, Code/Tools/SceneAPI/SceneData/Behaviors/LodRuleBehavior.cpp, Code/Tools/SceneAPI/SceneData/Behaviors/LodRuleBehavior.h, Code/Tools/SceneAPI/SceneData/Behaviors/SkinGroup.h, Code/Tools/SceneAPI/SceneData/Tests/GraphData/RulesTests.cpp, Code/Tools/SceneAPI/SceneUI/RowWidgets/NodeTreeSelectionWidget.cpp, Code/Tools/SceneAPI/SceneUI/SceneWidgets/SceneGraphWidget.cpp, Gems/Atom/RPI/Code/Source/RPI.Builders/Model/MorphTargetExporter.cpp, Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/MorphTargetRule.cpp, Gems/PhysX/Code/Source/Pipeline/MeshBehavior.cpp, Gems/SceneProcessing/Code/Source/Config/Components/SoftNameBehavior.cpp, Gems/SceneProcessing/Code/Source/Config/Components/SoftNameBehavior.h, Gems/SceneProcessing/Code/Source/Config/SettingsObjects/SoftNameSetting.cpp
This is a small optimization that changes the VirtualTypes set to an unordered_set. For a test file with ~1500 meshes, this reduces the FBX Settings page refresh time from ~250 seconds to ~220 seconds. It has a negligible effect on files with a small number of meshes.
Used PIX to profile before/after timings with this change.
=> Optimization - change VirtualTypes set to unordered_set

Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponentTypes_Source.jinja, Gems/Multiplayer/Code/Include/Multiplayer/Components/MultiplayerComponentRegistry.h, Gems/Multiplayer/Code/Source/Components/MultiplayerComponentRegistry.cpp
In certain cases a network component might be in a gem that loads on clients but does load on servers.
In such a case, a component version check fails because the server includes the component in the version hash but client doesn't.
This PR adds an option `OmitFromClientServerVersionHandshake` to add a toggle to disable a network component from a version checks between a client and a server.
```xml
<Component
Name="MyServerOnlyNetworkComponent"
OverrideController="true"
OverrideInclude="Source/Components/MyServerOnlyNetworkComponent.h"
OmitFromClientServerVersionHandshake="true"
```
On a multiplayer enable project with a server-only components as shown above.
=> An option to skip version check for a component in a clients-server handshake

Gems/Atom/RHI/Metal/Code/Source/RHI/Device.cpp, Gems/Atom/RHI/Vulkan/Code/CMakeLists.txt, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Model/ModelAssetHelpers.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Model/ModelLodAsset.h, Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.cpp, Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.h, Gems/Atom/RPI/Code/Source/RPI.Reflect/Model/ModelLodAsset.cpp, Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/ActorAsset.cpp
- Add support to pad skinned mesh buffers in order for them to respect RPI::SkinnedMeshBufferAlignment. This helps ensure we are able to respect alignment restrictions across all backends.
- In this case SkinnedMeshBufferAlignment is set to be 192 in order for it to respect  
- Metal has a restriction where each typed buffer needs to start at 64 byte boundary.
- At the same time a lot of our stream buffer views are RGB or RGBA so they need to be 12 and 16 byte aligned or all the element count/element offset logic will break.
- Removed Mac specific Vulkan builder and just have support for one builder across all platforms as we will want Mac to be able to process Vulkan related shaders too
- Fix ios crash related to Bindless allocator running out of space.
Related ASV PR - …
=> Add support to pad skinned mesh buffers to respect needed alignment

Code/Framework/AzCore/AzCore/std/string/regex.h
The AZStd::basic_regex template `extended` static const member variable was missing a definition to allow it to be ODR used and therefore the symbol was missingduring linking of the SceneCore library when the regex code is not inlined.
=> Linux Debug build fix in SceneCore

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/ComputePass.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ComputePass.cpp
Added the ability for subclasses and owners of a ComputePass to be notified when the compute shader is reloaded from disk. This was necessary to add because the Pass SRG is recreated and the owners or subclasses would not be aware that the shader constants require update.
Thanks to this new callback the shader constants can be refreshed/updated by owners of a compute pass or subclass of a compute pass.
It was tested in the Volumetric Cloudscape Gem which has several compute shaders that required this callback
when the compute shader is reloaded from Disk.
=> ComputePass Shader Reload Callback

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
- moves UIElement storage onto the stack to correctly portray ownership and prevent ambiguity during creation
- fixes #16478 
- fixes #16500 
locally, using the Editor project
=> fix UI Element creation in DPE-based Inspector

Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
Fixes node alignment shortcuts in Script Canvas
Verified alignment hotkeys worked in the Script Canvas editor
Closes #16600
=> Prevent QAction::eventFilter: Ambiguous shortcut overload closes #16600

Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
Fixes a release build error on Linux related to 'Unused Variable'  `prefix`. (Prefix is used in the `AZ_RPI_PASS_ERROR` which is def'd out in release builds)
Built `o3de-multiplayersample` in release build on Linux
=> Fix Linux release build error

Code/Framework/AzCore/AzCore/Task/TaskExecutor.cpp, Code/Framework/AzFramework/Tests/Scene.cpp, Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Converters/FIR-Filter.cpp, Gems/Atom/RPI/Code/Source/RPI.Reflect/Image/StreamingImageAsset.cpp
These errors occur on clang15 which is standard for ubuntu 23.xx
Most of them are related to macros that expand to a tautology, or a no-op, which clang15 is better at detecting.
These are just compile fixes for errors generated by the compiler.  They should not change behavior.
Just compilation and basic run tests.
=> Fixes a bunch of linux compile errors for clang15

scripts/build/Jenkins/Jenkinsfile
Adds a regex match to ensure only the project path is used in project only AR builds
=> Add regex to match the project path

Gems/Atom/RHI/DX12/External/AMD_D3D12MemoryAllocator/v2.0.1/dx12ma/D3D12MemAlloc.cpp
This PR fixes the following warnings in `D3D12MemAlloc.cpp` which occur with Clang16 on Windows:
* `error: unused function 'BitScanLSB' [-Werror,-Wunused-function]`
* `error: unused variable 'suballocations1st' [-Werror,-Wunused-variable]`
* `error: misleading indentation; statement is not part of the previous 'if' [-Werror,-Wmisleading-indentation]`
* `error: 'this' pointer cannot be null in well-defined C++ code; comparison may be assumed to always evaluate to false [-Werror,-Wtautological-undefined-compare]`
Removing the `if (this == NULL)` checks might be debatable, the alternative would be to disable this warning when using clang.
Compiling the engine with MSVC and Clang.
=> Fix Clang16 compile errors on Windows

Code/Tools/SceneAPI/SDKWrapper/AssImpSceneWrapper.cpp, Code/Tools/SceneAPI/SceneBuilder/SceneSystem.cpp
Any DAE files that have a scale set in it were importing at 1:1 size with the scale setting ignored. This is because the DAE importer in AssImp stores the scale in the root node transform matrix (see https://github.com/assimp/assimp/blob/master/code/AssetLib/Collada/ColladaLoader.cpp#L175-L182 ). The O3DE SceneSystem code was only looking for the scale in the metadata fields, which are set by FBX.
This change extracts the scale from the root transform to use for scaling the input.
Eventually, this should get investigated further to see why the root transform isn't being used directly as a part of node transformation and import. It's possible that more information should be getting extracted and used from this transform.
Imported the attached DAE file. …
=> Fix DAE import scale

scripts/o3de/o3de/cmake.py
Originally code was added to insert the o3de script path to resolve an error that came up while testing the export project script. However, the logic to remove the temporary path is bad, popping off the tail even though the path was inserted in the front.
Generated a project locally, no python errors
=> Fix bad python sys.path temporary logic

Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
Fixes #16497 
This fixes an issue where we were trigger any applicable `ChangeNotify` attributes twice anytime a property was changed. This is because `OnValueChanged` is called for both the `RequestWrite` and `OnEditingFinished` triggers that come from property handlers. However, in the RPE we only trigger `ChangeNotify` on `RequestWrite`, which is the correct behavior since there can be 1 or many `RequestWrite` changes before the user is done editing the field (e.g. presses Enter or unfocuses the field).
This issue wasn't made apparent until the linked bug, which displays a popup message on the `ChangeNotify` and so it was showing the popup twice.
This change plus the fix to https://github.com/o3de/o3de/issues/16231 which makes it so that asset fields can be cleared, resolve the issues …
=> Fix to only trigger ChangeNotify in response to RequestWrite

Gems/Atom/RHI/Code/Include/Atom/RHI/BufferPool.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceBuffer.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceBufferPool.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceBufferPoolBase.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceIndexBufferView.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDevicePipelineLibrary.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceStreamBufferView.h, Gems/Atom/RHI/Code/Source/RHI/BufferPool.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceBuffer.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceBufferPool.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceBufferPoolBase.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceIndexBufferView.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceStreamBufferView.cpp, Gems/Atom/RHI/Code/Tests/MultiDeviceBufferTests.cpp, Gems/Atom/RHI/Code/atom_rhi_public_files.cmake, Gems/Atom/RHI/Code/atom_rhi_tests_files.cmake, Gems/Atom/RHI/Metal/Code/Source/RHI/AsyncUploadQueue.h, Gems/Atom/RHI/Vulkan/Code/Source/RHI/AsyncUploadQueue.h
This PR is part of https://github.com/o3de/sig-graphics-audio/pull/137 (original proposal including discussion in https://github.com/o3de/sig-graphics-audio/issues/120, there referred to as (part of) commit 3 in the Planned git history sub-section) and introduces multi-device resource classes, including:
- `MultiDeviceBuffer`
- `MultiDeviceBufferPoolBase`
- `MultiDeviceBufferPool`
- `MultiDeviceIndexBufferView`
- `MultiDeviceStreamBufferView` …
=> Introduce multi-device buffer resources

Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
Fixes #16352 
Added null dereference check in the `UpdateCorrespondingImplicitConnection` that was causing a crash in certain cases.
Tested reproduction steps and verified Script Canvas no longer crashes.
=> Fixed null dereference crash in implicit connection logic

Gems/EMotionFX/Code/EMotionFX/Source/Actor.cpp
Fixed #16650 . The problem was that when Atom model product assets were renamed from 'model.azmodel' to 'model.fbx.azmodel', the Atom model and EMFX skin asset subid calculations were fixed to account for the name change, but the EMFX morph target asset subid calculation was missed. 
This PR applies the same fix to the morph target asset ID calculation that was applied to the skin asset ID calculation a few lines above it in the file.
Ran through the steps in #16650 and verified that the morph targets now show up.
=> Fix morph target asset loading to handle new 'model.fbx.azmodel' naming

Gems/AtomLyIntegration/CommonFeatures/Code/Source/Debug/RenderDebugEditorComponent.cpp
Fixes #16060 
This fixes an issue with empty groups being shown in the `Debug Rendering` component if `Enable Render Debugging` is disabled in DPE mode. This is due to an old hack in the RPE where since it didn't support visibility attributes on groups, it would recursively look through all children and if they are all hidden then it would hide the group as well. The DPE actually does support visibility attributes on groups, so you can just put a single visibility attribute on the group instead of having to put one on each element.
We have a backlog item to go and remove the hack extraneous visibility attributes once the DPE is enabled by default:
https://github.com/o3de/o3de/issues/16462
Here is the result of the groups being hidden properly now in the DPE (previously the groups would …
=> Fixed Debug Rendering component group visibility issue

Code/Framework/AzCore/AzCore/Asset/AssetJsonSerializer.cpp, Code/Framework/AzCore/Tests/AssetJsonSerializerTests.cpp
There are two scenarios where the AssetId wasn't be preserved with the changes in commit 3393f127db73e410449a06e5daa417786c06c4c2
The first scenario is if the Asset Id is not registered with the loaded Asset Catalog in the Asset Builder or if the Asset wasn't processed yet.
The second scenario is if the Asset Id is registered with the Asset Catalog, but the Asset Type isn't registered with the Asset Manager, therefore not allowing the Asset to be loaded successfully using it's Autoload behavior.
Verified that the InputConfigurationComponent InputEventBindingAssets AssetId references were successfully copied over to prefab's .spawnable product without zero'ing out the Asset Id
```xml
<Class name="InputConfigurationComponent" field="element" version="4" …
```
=> Updated the AssetJsonSerializer to preserve the Asset Id on load

scripts/o3de/o3de/project_manager_interface.py
This fixes an issue with the snap package installed SDK and Project Manager where you will get multiple errors showing a gem was "Removed or Unregistered" during the create new project workflow with a remote repo.
**Root Cause**
The root cause is when the project manager downloads a template from a remote repo, its template is stored in `$HOME/O3DE/Templates`, it cannot resolve the engine path because it is trying to get the engine path from the project path. For project templates, we shouldn't care about its engine path because its not an actual project yet (that is a different issue). The logic attempts to resolve the engine path by walking up the path of the template until `engine.json` is found. While this works for templates in the snap installation (because the templates are inside …
=> [Linux] Fix linux snap package issues with Project Manager

Code/Framework/AzCore/AzCore/DOM/DomUtils.h
This was causing the Attribute for the Button Text to be not be marshaled correctly.
Validated that the Button Text on the Transform Component "Add non-uniform scale"
=> Fix for marshaling of references to pointers types through the Dom Utils API

Code/Tools/ProjectManager/Source/CreateProjectCtrl.cpp
This fixes a situation where the user may opt to cancel a new project creation if they click on 'Create Project' but warnings such as gem dependency issues can opt them to cancel the creation. Even if they press cancel, the new files are created but not added, so the project information (path) on the project creation workflow is no longer valid because the folder now exists.
(Refer to the [GHI](https://github.com/o3de/o3de/issues/16669) for more info)
Followed steps described in the [GHI](https://github.com/o3de/o3de/issues/16669).
Fixes https://github.com/o3de/o3de/issues/16669
=> Project Manager: Fix Broken workflow when cancelling new project creation

Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/ImageSubresource.h, Gems/Atom/RHI/Code/Include/Atom/RHI/ImagePool.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceImage.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceImagePool.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceImagePoolBase.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceStreamingImagePool.h, Gems/Atom/RHI/Code/Include/Atom/RHI/StreamingImagePool.h, Gems/Atom/RHI/Code/Source/RHI/ImagePool.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceImage.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceImagePool.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceImagePoolBase.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceStreamingImagePool.cpp, Gems/Atom/RHI/Code/Source/RHI/StreamingImagePool.cpp, Gems/Atom/RHI/Code/Tests/MultiDeviceImageTests.cpp, Gems/Atom/RHI/Code/atom_rhi_public_files.cmake, Gems/Atom/RHI/Code/atom_rhi_tests_files.cmake, Gems/Atom/RHI/Vulkan/Code/Source/RHI/AsyncUploadQueue.h
This PR is part of https://github.com/o3de/sig-graphics-audio/pull/137 (original proposal including discussion in https://github.com/o3de/sig-graphics-audio/issues/120, there referred to as (part of) commit 3 in the Planned git history sub-section) and introduces multi-device resource classes, including:
- `MultiDeviceImage`
- `MultiDeviceImagePoolBase`
- `MultiDeviceImagePool`
- `MultiDeviceStreamingImagePool`
- `MultiDeviceSwapChain` …
=> Introduce multi-device image resources

Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/AssetBrowser/AtomToolsAssetBrowser.h, Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h, Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowser.cpp, Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp, Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp, Gems/Atom/Tools/MaterialCanvas/Registry/paths.materialcanvas.setreg, Gems/Atom/Tools/MaterialEditor/Registry/paths.materialeditor.setreg, Gems/Atom/Tools/PassCanvas/Registry/paths.passcanvas.setreg, Gems/Atom/Tools/ShaderManagementConsole/Registry/paths.shadermanagementconsole.setreg
Replaced explicit checks for ignoring the cache folder with configurable settings so that SMC could access generated shaders and materials
Built and tested material editor, material canvas, and shader management console to see that each respected the filter settings.
=> SMC: Allow access to generated shaders and materials in intermediate assets folder

Code/Framework/AzCore/AzCore/IO/Path/PathParser.inl, Code/Framework/AzCore/Tests/IO/Path/PathTests.cpp
Windows Paths such as `C:/foo/bar/./baz` now correctly compare equal to `C:/foo/bar/baz` and POSIX paths such as `/baz/bar/./foo` now compare equal to `/baz/bar/foo`
Added Paths containing Dots to the Path Unit Test ComparePaths ParamTest to validate that paths with a dot in them compares successfully to a paths that don't contain a dot in them.
=> Fixed comparison of file paths with '.' using the AZ Path API

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
Fixed #16073 
This fixes an edge-case where container elements have a visibility of `ShowChildrenOnly` so only their children are actually shown. This caused an issue where a remove button to delete that element is expected on the elements, but is missing in this case because the children of that container element didn't have the appropriate parent container info to display that button.
Here it is working now on surface tags (where previously the remove buttons on the elements were missing):
Tested the components mentioned in the bug and verified the remove buttons now show up and work as expected when the DPE is enabled.
=> DPE: Fixed edge case for ShowChildrenOnly on parent container elements

Code/Tools/ProjectManager/Source/ProjectBuilderWorker.cpp
When Project Manager builds a project for the first time, or if there are errors during the configure process, it will abruptly close with a segmentation fault. This address the issue by protecting against the root cause of the crash (described below)
**Root Cause**
The project manager uses `QProcress->realAllStandardOutput()` to report the last line from the stdout pipe while waiting for the process to complete. However, its possible that an error that occurs during this process is only coming through stderr, and stdout is flushed out already. This causes the following line:
```
// Show last line of output
UpdateProgress(configOutput.split('\n', Qt::SkipEmptyParts).last());
```
To crash with
```
thread #22, name = 'QThread', stop reason = signal SIGABRT
* frame #0: 0x00007ffff3496a7c …
```
=> Fix segmentation fault for Project Manager on first build

Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/AssetBrowser/AtomToolsAssetBrowser.h, Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowser.cpp, Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp, Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorMainWindow.cpp, Gems/Atom/Tools/PassCanvas/Code/Source/Window/PassCanvasMainWindow.cpp, Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.cpp
SMC, MC, and other tools work primarily with source files that are not directly tied to asset types. This change implements support in the atom tools asset browser for setting up extension based file filters in lieu of the asset group based filters.
Opened the four tools using this as a browser.
Confirmed that standard asset browser type filters were hidden and disabled.
Confirmed that all file type filters were registered and appeared in the options menu.
Confirmed that individual filters displayed files matching specified extensions.
Confirmed that disabling all filters showed an unfiltered tree of assets.
Confirmed that tools saved settings and shut down correctly.
Confirmed that material canvas files that did not appear in the asset browser previously are now available, selectable, …
=> Atom tools, SMC, MC: Atom tools asset browser support for extension based file filters

Code/Framework/AzFramework/AzFramework/Visibility/VisibleGeometryBus.cpp, Code/Framework/AzFramework/AzFramework/Visibility/VisibleGeometryBus.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h
Added a transparent flag to the visible geometry structure.
Updated mesh component controller to automatically detect and set the transparent flag on visible geometry based on materials.
Compiled project and loaded existing levels. None of this code is used actively in the development branch yet. 
Verified behavior in other projects using the visible geometry bus and structure.
=> Added transparent flag to visible geometry structure. Auto detecting and setting it in mesh component.

Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilder.cpp, Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilderUtils.cpp, Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.cpp, Gems/Atom/RPI/Code/Source/RPI.Edit/Common/AssetUtils.cpp
This PR fixes the issue that AP won't process fbx and material assets in parallel. This issue is related to this change https://github.com/o3de/o3de/pull/14862
The reason the issue happened because the change made from that PR 
1. If all the pending jobs left have missing source job dependencies.
2. The AP would only bring one job from the pending jobs to process. 
3. If there is one job in process, the other pending jobs would wait. 
Since the PR was used to address an intermediate asset issue, we can't revert it unless we have other solution for that issue.
The fix we have in this PR to address the problem is to have accurate source dependencies for both fbx and material files so they won't go down that route. 
For fbx file, the missing source dependency was caused by wrong job key for …
=> Fixed an issue that AP only have one job running when process fbx and material files.

Gems/NvCloth/Code/Source/Components/EditorClothComponent.cpp
This fixes some additional properties in the Cloth component that were specifying the incorrect property handler, so they were missing an input widget in the DPE.
AFTER:
Tested the Cloth component and verified the properties now show up and function as expected.
=> Fixed some cloth component properties not creating their input widgets

Gems/WhiteBox/Code/Source/EditorWhiteBoxComponent.cpp, Gems/WhiteBox/Code/Source/EditorWhiteBoxComponent.h
Fixes #16693 
In the White Box component, the "Mesh Asset" field wasn't being shown when changing the "Default Shape" to "Mesh Asset". This is because a property refresh was required, but the White Box component was using multiple change notifies for that single data element. The DPE only supports a single change notify on a data element (it does, however, properly support multiple change notifies up its parent hierarchy). This component used multiple change notifies to have one trigger a custom method, and then the second to trigger the property refresh. But this can actually be accomplished in a single method by returning the property refresh level.
I've updated the White Box component to use a single change notify and it now works. I've also added a backlog story to investigate if we …
=> Fixed change notify usage in the White Box component

Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
Fixes #16703 
There is logic that detects if a new value was set based on the `OnValueChanged` event so that we don't invoke the `OnChanged` unless a value has been set, which was also gating if the `ChangeNotify` should be triggered. However, there are cases where a value won't be set but we do want to still trigger the `ChangeNotify`, such as in the Cloth component with the "Simulate in editor" checkbox, which is a pure `UIElement` with no backing data element and only a change notify trigger to make the cloth be simulated/stop simulation. In this case, there will be no value set, but we still want the `ChangeNotify` to trigger.
Tested the "Simluate in editor" checkbox with both DPE enabled and disabled and verified cloth correctly simluates in both scenarios.
=> Fixed UIElement change notify

cmake/Platform/Common/Configurations_common.cmake, cmake/Platform/Linux/Configurations_linux_x86_64.cmake, scripts/build/build_node/Platform/Linux/package-list.ubuntu-bionic.txt, scripts/build/build_node/Platform/Linux/package-list.ubuntu-focal.txt, scripts/build/build_node/Platform/Linux/package-list.ubuntu-jammy.txt
These changes add a check to see if lld is installed on the system as part of the cmake configuration, and if so adds a flag for the Linux+clang build to make use of it. This is to speed up build times by using lld which is a faster and more memory efficient linker than ld.
https://github.com/o3de/o3de/issues/7635
Configured and built engine with changes on Fedora 38 with the lld package installed and uninstalled to make sure both worked. One consideration is that if the engine is built with lld uninstalled, lld is installed, then a project is created and build files generated for it, the build files will specify to use lld instead of ld as the engine does. This doesn't seem to cause any problems but may …
=> Use lld linker by default for Linux clang build if it is installed

.github/workflows/stabilization-pr-checklist.yaml
Minor fix to the stabilization checklist automation to only trigger when the PR is first opened or reopened. Current behavior will trigger a comment after every commit to the PR.
Tested in a fork of the repo
=> Set stabilization checklist to trigger only on opened PR

Gems/PhysX/Code/Source/Articulation.cpp, Gems/PhysX/Code/Source/Articulation.h, Gems/PhysX/Code/Source/Pipeline/PhysicsPrefabProcessor.cpp
The old behavior is to support only one collider per articulation link, which is not true.
This PR addresses an issue with articulation in: https://github.com/o3de/o3de/issues/16711
Manual test against this URDF imported with URDF/SDF importer with PhysX debug gem.
[urdf.zip](https://github.com/o3de/o3de/files/12609194/urdf.zip)
Before:
After:
=> Fix missing support for multi-collider articulation links

Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
Using Multiplayer gem, it is a valid scenario to declare a network property with Authority->Server direction, for example:
```cpp
<NetworkProperty Type="bool" Name="LightServerState" Init="false" ReplicateFrom="Authority" ReplicateTo="Server"
IsRewindable="false" IsPredictable="false" IsPublic="true" Container="Object" ExposeToEditor="false" 
ExposeToScript="false"  GenerateEventBindings="true" Description="Current light state"/>
```
This currently results in a compile error. This PR fixes the codegen to correctly build the network code for client and server binaries.
Tested with a multiplayer gem enabled project.
=> Fixes codegen for authority->server network properties for client-server code split

Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_Common.azsli, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_SurfaceEval.azsli, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_VertexEval.azsli, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_Common.azsli, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_SurfaceEval.azsli, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_VertexEval.azsli
This change updates the material graph template material SRGs to include a placeholder variable. Including and referencing this variable ensures that the material SRG always exists across all shaders that might use it. This initial resolved one assert that triggered when adding or removing material inputs from a material graph, consequently adding or removing variables from the material SRG and corresponding connections in the material type. As the AP processes the material and shader changes, the runtime may receive individual shader updates with inconsistent SRG data until everything is fully compiled and synchronized.
This change may be reverted after subsequent changes that may also address the issue.
Relates to https://github.com/o3de/o3de/issues/16034
Relates to …
=> Material Canvas: Updating material graph shaders to not optimize out material SRG

Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialGraphCompiler.cpp, Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialGraphCompiler.h, Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp
This change provides an option to delete files that were previously generated using the current template before creating new ones. The option was useful while debugging and may also be useful if switching between different material output nodes that might use the same file names. The option is disabled by default. These changes are pulled from a larger set.
Option is disabled by default but tested in material canvas while iterating on material graphs.
=> Material Canvas: Option to delete previously generated files before creating new ones

engine.json
Increment the engine major version to prevent there being any engine version overlap between development and stabilization from this point on.
Related RFC https://github.com/o3de/sig-core/issues/44
n/a this does not change any functionality
=> Increment engine major version post stabilization

scripts/o3de/ExportScripts/export_source_ios_xcode.py, scripts/o3de/o3de/export_project.py
This export script provides rudimentary support for iOS devices on the experimental macOS build of O3DE. The main functionality runs CMake commands to prepare assets and generate the XCode project file for the given project in the directory. This does not do the full export process however.
Due to the need to setup an AppleID, and a provisioning profile inside of XCode, this is currently handled manually in the Xcode IDE. Future work on this script would include utilizing `xcodebuild` to automate that portion of the process. For now, to get something in before release, we stop at just XCode project generation.
The script was tested on a local macOS machine with a verified iOS device. O3DE Atom Sampler project was used to verify the build process ran correctly. Outcome was a single xcode …
=> adding initial iOS export script

Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
Fixes https://github.com/o3de/o3de/issues/16721 https://github.com/o3de/o3de/issues/16739 https://github.com/o3de/o3de/issues/16723 https://github.com/o3de/o3de/issues/16722 https://github.com/o3de/o3de-extras/issues/525
Now that all the ChangeNotify issues have been resolved, we are seeing intermittent crashes when modifying properties in the DPE due to input events being sent to widgets that have just been deleted. This fix prevents the crash by switching to use `deleteLater()` which lets Qt optimize the deletion (typically on the following event tick) and is consistent with how the RPE handles widget deletion.
A follow-up PR will be done to reintroduce handler + widget recycling (https://github.com/o3de/o3de/issues/16135) which will optimize DPE performance by eliminating the need to …
=> Fixed intermittent crash in DPE when modifying values

.github/workflows/stabilization-pr-checklist.yaml
Another fix to allow Github Actions to trigger on PRs from a fork. Github recently changed this behavior for security reasons, this event type (pull_request_target) reverts to the i[ntended behavior](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)
Tested in a fork, with a PR from another fork
=> Change PR checklist GHA event type

.github/CODEOWNERS, scripts/lldb/.lldb/o3destd_lldb.py, scripts/lldb/.lldbinit, scripts/lldb/README.md
AZStd string classes(`string`, `string_view`, `fixed_string`), hash_table classes(`unordered_map`, `unordered_set`, `unordered_multimap`, `unordered_multiset`), contiguous container classes(`vector`, `fixed_vector`)  can be visualized in the lldb debugger by sourcing in the `o3destd_lldb.py` script into lldb.
Verified the lldb debugger print the summary for AZStd::string variables to the watch window
=> Adding lldb python formatter for AZStd string and hash_table classes

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.h, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/GenericComboBoxCtrl.inl
- attempts to construct natively handled DOM values where possible, instead of defaulting to opaque types. This allows the values to be diffed correctly and only patch when necessary
- Fix valueHashed to be stored as a u4 to prevent unnecessary shared_ptr diffs/patches
locally, using the Editor project
=> optimization to reduce valueHashed patches

Code/Framework/AzCore/AzCore/Console/Console.cpp
Any console command registered with the AZ_CONSOLEFREEFUNC macro would previous attempt to log its "value" out to the console window using the data type associated with the command and because a free function isn't associated with a class type, it would output "<empty>".
So commands such as "LoadLevel" would always log "LoadLevel : <empty>" and not the name of the level
fixes #16775 
Verified the `LoadLevel` command in the AutomatedTesting project logged the level name when specified.
Verified the `sys_PakPriority` CVAR logged it's current value when no inputs are supplied.
=> Updated the AZ Console to output the inputs to console commands which are not CVars

Gems/PhysX/Code/Source/ArticulationLinkComponent.cpp
Resolves a warning as error created by an unused variable
Compiled without warnings or errors
=> Fixing warning as error caused by unused variable

Gems/Atom/Feature/Common/Assets/Scripts/material_find_overrides_demo.lua, Gems/Atom/Feature/Common/Assets/Scripts/material_property_overrides_demo.lua, Gems/Atom/Feature/Common/Assets/Scripts/material_property_overrides_demo.py, Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/MaterialAssignment.h, Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/MaterialComponentBus.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentUtil.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialAssignment.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h, Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp, Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.h, Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/MaterialComponentRequestBus.names
Correcting typo where the word default was missing an “L” in some material related functions.
Updated behavior context binding deprecation.
Building
=> Correcting spelling of "Default" in material component

Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.h
In the DX12 CommandList::CommitShaderResources: Check if the Bindless descriptor table was bound to the expected index, not just if it was already bound.
We had a problem that the Bindless SRG was not bound for a custom pass. Checking if it was bound to the expected index, and setting if it it was not, solved the problem.
I think what happens is this: There is a single `CommandList` in the `FrameGraphExecuteGroup` that's used for all scopes in the group.
When one of the scopes uses the Bindless SRG it sets it as a descriptor table in the DX12 CommandList. The index is defined in the PipelineLayout of the scope.
When another scopes also needs the Bindless SRG it's possible (likely?) that it uses another index for the Bindless SRG as the one before.
This means that the DescriptorTable might …
=> DX12: Fix binding of Bindless for multiple scopes in a group

Gems/DiffuseProbeGrid/Code/Include/DiffuseProbeGrid/DiffuseProbeGridFeatureProcessorInterface.h, Gems/DiffuseProbeGrid/Code/Source/Components/DiffuseProbeGridComponentController.cpp, Gems/DiffuseProbeGrid/Code/Source/Components/DiffuseProbeGridComponentController.h, Gems/DiffuseProbeGrid/Code/Source/EditorComponents/EditorDiffuseProbeGridComponent.cpp, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.cpp, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.h
Fix issue (https://github.com/o3de/o3de/issues/16720)
The reason is that if the raytracing isn't supported. The `DiffuseProbeGridRenderPass `will return early in its `SetupFrameGraphDependencies `function. And `diffuseProbeGrid->GetTextureReadback().Update(GetName())` would be skipped. The bake function's callback function won't never be called which means the baking was started, baking pass was added, but the baking process won't never finish. 
The function added a CanBakeTextures function to check if the baking is supported and give possible cause. 
Disable dx12 raytracing support (o3de\Gems\Atom\RHI\DX12\Code\Source\RHI\Device.cpp, ln 254)
set `m_raytracing = false;`
Run Editor with AutomatedTesting project and open Graphics/stanza level. Select Diffuse Probe Grid 1 entity and press …
=> This change fix a diffuse probe grid bake issue with pc which doesn't support raytracing

Code/Framework/AzCore/AzCore/IO/Path/PathParser.inl, Code/Framework/AzCore/Tests/IO/Path/PathTests.cpp
This is a cherry pick of commit 183d594453d712e4d9991f96e502bd0f3e847faa
Windows Paths such as `C:/foo/bar/./baz` now correctly compare equal to `C:/foo/bar/baz` and POSIX paths such as `/baz/bar/./foo` now compare equal to `/baz/bar/foo`
Added Unit Test scenarios to verify the modifications to CompareRelative function were able to compare paths which references a directory using "./" succeeded.
Also verified existing Path UnitTest succeeds
=> (Cherry-Pick) Fixed comparison of file paths with '.' using the AZ Path API (#16674)

Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorTab.cpp
add a new CVar, "ed_enableDPEAssetEditor", to enable the experimental DPE-based implementation of the Asset Editor
Locally, in the Editor project
=> introduce a CVar for AssetEditor DPE support

Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceCopyItem.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceDispatchItem.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceDispatchRaysItem.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceDrawItem.h, Gems/Atom/RHI/Code/atom_rhi_public_files.cmake
This PR is part of https://github.com/o3de/sig-graphics-audio/pull/137 (original proposal including discussion in https://github.com/o3de/sig-graphics-audio/issues/120, there referred to as (part of) commit 3 in the Planned git history sub-section) and introduces multi-device resource classes, in particular:
- `MultiDeviceCopyItem`
- `MultiDeviceDispatchItem`
- `MultiDeviceDispatchRaysItem`
- `MultiDeviceDrawItems` …
=> Introduce multi-device items

.automatedtesting.json, .gitignore
Removes automated tests for o3de-extras from o3de stabilization, as the components for o3de-extras at the development branch are not being tested for the release. Alternatively, we can include the tests but force the AR builds to run at the stabilization branch.
Includes a change to .gitignore to prevent this from being merged back to development.
Tested in a sandbox Jenkins build
=> Disable o3de-extras automated testing for stabilization

Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorTab.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
Ensures that the DPE requests size updates when handling DOM changes or expander changes, even on Linux.
fixes #14863 
locally in the Editor project, for both Windows and Linux
=> Fix DPE resizing on Linux

Code/Framework/AzCore/AzCore/DOM/DomComparison.cpp, Code/Framework/AzCore/AzCore/DOM/DomUtils.cpp, Code/Framework/AzCore/AzCore/DOM/DomUtils.h, Code/Framework/AzCore/AzCore/Serialization/EditContext.cpp, Code/Framework/AzCore/AzCore/Serialization/EditContext.h, Code/Framework/AzCore/AzCore/Serialization/EnumConstantJsonSerializer.cpp, Code/Framework/AzCore/AzCore/Serialization/EnumConstantJsonSerializer.h, Code/Framework/AzCore/AzCore/Serialization/Json/JsonSerialization.cpp, Code/Framework/AzCore/AzCore/Serialization/Json/JsonSerialization.h, Code/Framework/AzCore/AzCore/Serialization/Json/JsonSystemComponent.cpp, Code/Framework/AzCore/AzCore/azcore_files.cmake, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
The Dom `GenerateHierarchicalDeltaPatch` function has been updated to perform a Deep Comparison of Dom Contents being compared. This allows Dom Values that are value equal, but not pointer equal to compare equivalent.
Such as in the case when two Dom Values which stores a label with the same string value of "Exposure" is compared to each other
The Dom::Utils `MarshalOpaqueValue` function has been updated to marshal a C++ object to a Dom Value using JSON Serialization which results in a Dom Object instead of an opaque value
The Dom::Utils `ValueToType` function was updated to use Json Serialization to convert a Dom::Value back into a C++ object when the C++ type supports SerializeContext or JsonRegistrationContext reflection
The EditContext `EnumConstant` class has had a Json Serializer …
=> Document Property Editor Slider fixes

Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Logger.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Logger.h
Fixes #16449 
This fixes the crash when closing the Script Canvas tool. This fix has been cherry-picked from here: https://github.com/BytesOfPiDev/o3de/commit/52da522b11862e83089d7caacf5988cb3823dffc
Closed the Script Canvas tool and verified the Editor no longer crashes.
=> Cherry-pick to fix crash when closing Script Canvas

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabComponentAdapter.cpp
Fixes #16788 and #16790
Fixes issue with prefab overrides not working through the DPE. The main change is just removing the CreateAndEdit/ApplyComponentOverridePatch methods that weren't creating the patches properly and creating extra undo/redo nodes. Instead, I just let the prefab public handler create the patches and undo/redo nodes, which is the same logic flow if you have DPE enabled but Outliner overrides enabled but not Inspector overrides. This change does keep the logic to make sure the override label(s) get updated properly in the inspector.
Tested the repro steps as well as ad-hoc testing.
=> Fixed prefab overrides not working with DPE enabled

cmake/Platform/Windows/Packaging/Bootstrapper.wxs, cmake/Platform/Windows/Packaging/Shortcuts.wxs
Changes the WiX windows templates to remove the `[Developer Preview]` title in dialog boxes and in add/remove programs. Addresses https://github.com/o3de/o3de/issues/15872. This will impact the next release cycle if we don't want this message in the installed release version
Will be testing this in a branch build
=> Remove developer preview title from Shortcuts and Bootstrapper WiX templates

Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.cpp
For raytracing passes with DX12, if a SRG other than the bindless SRG contains bindless arrays, the bindless SRG was potentially bound to the wrong SRG slot, thereby overwriting the bound SRG, and also effectively not binding the bindless SRG.
Windows and DX12
=> Make sure the bindless Srg is bound to the correct slot for Raytracing Passes with DX12

Code/Tools/SceneAPI/SceneCore/Containers/Views/PairIterator.h
This PR changes the declaration of the static members of `PairIteratorCategory` from `const` to `constexpr`, which otherwise results in a linker error using `Debug` build on linux, with the following errors (similar for the other members):
```
[build] ld.lld: error: undefined symbol: AZ::SceneAPI::Containers::Views::Internal::PairIteratorCategory<int*, int*>::s_sameCategory
[build] >>> referenced by PairIteratorTests.cpp:27 (Code/Tools/SceneAPI/SceneCore/Tests/Containers/Views/PairIteratorTests.cpp:27)
[build] >>>               Code/Tools/SceneAPI/SceneCore/CMakeFiles/SceneCore.Tests.dir/debug/Unity/unity_1_cxx.cxx.o:(AZ::SceneAPI::Containers::Views::Internal::PairIteratorCategoryTests_Declaration_SameCategory_TwoIteratorsHaveEqualCategory_Test::TestBody())
[build] clang-16: error: linker …
```
=> Fix linux linker error in debug mode for PairIteratorCategory

Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceRayTracingAccelerationStructure.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceRayTracingBufferPools.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceRayTracingPipelineState.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceRayTracingShaderTable.h, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceRayTracingAccelerationStructure.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceRayTracingBufferPools.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceRayTracingPipelineState.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceRayTracingShaderTable.cpp, Gems/Atom/RHI/Code/atom_rhi_public_files.cmake
This PR is part of https://github.com/o3de/sig-graphics-audio/pull/137 (original proposal including discussion in https://github.com/o3de/sig-graphics-audio/issues/120, there referred to as (part of) commit 3 in the Planned git history sub-section) and introduces multi-device resource classes, in particular:
- `MultiDeviceRayTracingShaderTable`
- `MultiDeviceRayTracingPipelineState`
- `MultiDeviceRayTracingBufferPools`
- `MultiDeviceRayTracingBlas`
- `MultiDeviceRayTracingTlas`
| …
=> Introduce multi-device ray tracing resources

Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceTransientAttachmentPool.h, Gems/Atom/RHI/Code/Include/Atom/RHI/TransientAttachmentPool.h, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceTransientAttachmentPool.cpp, Gems/Atom/RHI/Code/Source/RHI/TransientAttachmentPool.cpp, Gems/Atom/RHI/Code/atom_rhi_public_files.cmake
This PR is part of https://github.com/o3de/sig-graphics-audio/pull/137 (original proposal including discussion in https://github.com/o3de/sig-graphics-audio/issues/120, there referred to as (part of) commit 3 in the Planned git history sub-section) and introduces `TransientAttachmentPool`.
It is important to note that this PR only introduces this resource class but does not call it currently on either the RHI or RPI level (this will happen after all multi-device resources have been properly introduced into the code base).
|Preparation|[#16138](https://github.com/o3de/o3de/pull/16138)|merged|
|Base Resources|[#16202](https://github.com/o3de/o3de/pull/16202)|merged|
| Pipelines | …
=> Introduce multi-device TransientAttachmentPool

Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
This fixes an issue in Linux where the Material Editor fails to launch. 
**Root Cause**
With the Headless Server refactor, applications that require a NativeUI needs to have the AzFramework::NativeUISystemComponent listed as a required component. This was done for `AzToolsApplication`, but not for `AtomToolsApplication`. Since `AtomToolsApplication` does not inherit `AzToolsApplication`, that was missed.
**Fix**
Since this does not inherit from `AzToolsApplication`, the `AzFramework::NativeUISystemComponent` was added to the `AtomToolsApplication` list of required components
TBD
=> Fix Material Editor failing to Launch in Linux

Code/Framework/AzToolsFramework/AzToolsFramework/Asset/AssetUtils.cpp
It was discovered that the Asset Processor has very slow performance when performing processing for iOS platform. Part of the reason for this was because it was processing macOS assets even though they should be unrelated. This issue occurred even after setting the mac platform as disabled in the Asset Processor Registry settings.
This PR is a one-line fix to correct that behavior. It corrects the `AssetUtils::ReadEnabledPlatformsFromSettingsRegistry` to also consider the host platform in the logic for detecting enabled platforms, instead of assuming it is enabled by default. 
The changes were tested on a macOS laptop. Asset Processor was tested in workloads for O3DE Atom Sample Viewer in scenarios where ios is enabled, and mac platform is disabled. Afterwards it was tested in the …
=> Asset processor skippable host fix

Gems/Atom/Feature/Common/Code/Source/AuxGeom/FixedShapeProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/PostProcess/LookModification/LookModificationSettings.cpp, Gems/Atom/Feature/Common/Code/Source/PostProcess/LookModification/LookModificationSettings.h, Gems/Atom/Feature/Common/Code/Source/PostProcessing/BlendColorGradingLutsPass.cpp, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.cpp, Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceBlurPass.cpp, Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceDownsampleDepthLinearPass.cpp, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Asset/AssetUtils.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/AttachmentReadback.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ComputePass.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/FullscreenTrianglePass.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Specific/ImageAttachmentPreviewPass.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/RPIUtils.cpp, Gems/AtomTressFX/Code/Passes/HairGeometryRasterPass.cpp
A separate set of changes was causing errors starting the main editor. Following the trail of error messages, it was not obvious where the error was occurring because the same message was used for different cases.
Updated pass and post process shader load error messages to distinguish between asset load failure and instance creation failure.
Corrected multiple checks for valid asset ids or asset pointers that should have been checking for the asset to be ready.
Checking the asset pointer and asset ID does not confirm that the asset is ready for use.
All of the utility functions used to load the shaders we're already doing blocking loads to force the shader assets to be ready. 
Changed strings to constexpr const char*.
Build project. Loaded levels in automated testing project. Currently …
=> Updating pass and post process shader load error messages and readiness checks

Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/Process/JobRunner/TestImpactProcessJobInfo.h, Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/Process/JobRunner/TestImpactProcessJobRunner.h, Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/TestRunner/Common/Job/TestImpactTestJobInfoGenerator.h, Code/Tools/TestImpactFramework/Runtime/Common/Code/Source/TestRunner/Common/Run/TestImpactTestCoverageSerializer.cpp, Gems/ScriptCanvasTesting/Code/Source/Framework/ScriptCanvasTestUtilities.h
Fix various Clang16 compile warnings on Windows, such as wrong usage of `typename` and ambiguous references
Compile with Clang16 and MSVC
=> Fix various Clang16 compile warnings on Windows

Code/Framework/AzCore/AzCore/Console/ConsoleFunctor.h, Code/Framework/AzCore/AzCore/Serialization/AZStdContainers.inl, Code/Framework/AzCore/AzCore/Serialization/EditContext.cpp, Code/Framework/AzCore/AzCore/Serialization/EditContext.h, Code/Framework/AzCore/AzCore/Serialization/SerializeContext.cpp, Code/Framework/AzCore/AzCore/Serialization/SerializeContext.h, Code/Framework/AzCore/Tests/Serialization.cpp
Updated the IAssociativeDataContainer interface to expose a `GetAssociativeType` function that can return whether the associative container is a set, map, unordered_set or unordered_map
Updated the IDataContainer interface to expose a `IsSequenceType` function which returns if the DataContainer is a sequence type such as a (Fixed)Vector, (Forward)List or Array.
A const member overload for `GetAssociativeContainerInterface` function have added to allow calling on a const IDataContainer pointer.
Two new console commands have been added to the Edit Context which can log the name of fields that have been reflected to the Edit Context that are sequence types or associative types.
The console commands are `ed_logReflectedAssociativeContainerFields` and `ed_logReflectedSequenceContainerFields`. …
=> Associative Container low-level API improvements

Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPassData.h
Adds the include `SerializeContext.h` to the file `RayTracingPassData.h` (which uses `AZ::SerializeContext` later on), which could otherwise lead to compile errors if the file is included somewhere where `AZ::SerializeContext` has not been included before.
Compile with MSVC and Clang
=> Add missing include in RayTracingPassData.h

Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceBuffer.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceImage.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDevicePipelineLibrary.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceShaderResourceGroupData.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceStreamingImagePool.h, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceBuffer.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceImage.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceShaderResourceGroupData.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceStreamingImagePool.cpp
This PR is part of https://github.com/o3de/sig-graphics-audio/pull/137 (original proposal including discussion in https://github.com/o3de/sig-graphics-audio/issues/120, there referred to as (part of) commit 3 in the Planned git history sub-section) and introduces multi-device resource classes, in particular:
- `MultiDeviceBufferView`
- `MultiDeviceImageView`
As mentioned in [RFC120](https://github.com/o3de/sig-graphics-audio/issues/120), we do not want full multi-device versions (i.e. inheriting from a multi-device version of `ResourceView`) of `BufferView` and `ImageView`, since the memory management is quite involved and resources store references to their views.
Our goal is to just use a light-weight combination of resource (referenced by a raw pointer) and descriptor, as this does not …
=> Introduce multi-device buffer/image views

Code/Framework/AzCore/Tests/Console/ConsoleTests.cpp, Code/Framework/AzCore/Tests/Settings/SettingsRegistryMergeUtilsTests.cpp, Code/Framework/AzCore/Tests/Settings/SettingsRegistryOriginTrackerTests.cpp, Code/Framework/AzCore/Tests/Settings/SettingsRegistryTests.cpp, Code/Framework/AzFramework/Tests/DocumentPropertyEditor/SettingsRegistryAdapterTests.cpp, Code/Framework/AzTest/AzTest/Utils.cpp, Code/Framework/AzTest/AzTest/Utils.h
Moved the CreateTestFile function to the AzTest library, which allows it to be used by all google test UnitTest.
The CreateTestFile function has also been updated to only create files within a temporary directory to make sure the user workspace isn't populated with test files
Updated the AZ Console and Settings Registry Unit test to use the `AZ::Test::CreateTestFile` function
Verified that all `AzCore.Tests` pass.
=> Consolidate the  `CreateTestFile` function into the AzTest library

Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp, Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.h, Gems/ScriptCanvas/Code/Editor/View/Windows/mainwindow.ui
Set the starting state of menu options to disabled and only enable them when graphs are open.
Closes #16599
=> Ensure only relevant menu options are enabled when no graphs are open

Code/Framework/AzCore/AzCore/Serialization/AZStdContainers.inl, Code/Framework/AzCore/AzCore/Serialization/EditContextConstants.inl, Code/Framework/AzCore/AzCore/Serialization/Json/JsonSystemComponent.cpp, Code/Framework/AzCore/AzCore/Serialization/Json/PointerJsonSerializer.cpp, Code/Framework/AzCore/AzCore/Serialization/Json/PointerJsonSerializer.h, Code/Framework/AzCore/AzCore/Serialization/PointerObject.cpp, Code/Framework/AzCore/AzCore/Serialization/PointerObject.h, Code/Framework/AzCore/AzCore/Serialization/SerializationUtils.cpp, Code/Framework/AzCore/AzCore/Serialization/SerializeContextEnum.inl, Code/Framework/AzCore/AzCore/Serialization/Utils.h, Code/Framework/AzCore/AzCore/azcore_files.cmake, Code/Framework/AzCore/Platform/Common/VisualStudio/AzCore/Natvis/azcore.natvis, Code/Framework/AzCore/Tests/Serialization/Json/PointerSerializerTests.cpp, Code/Framework/AzCore/Tests/azcoretests_files.cmake, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.h, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/Visitor.h, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/KeyQueryDPE.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/KeyQueryDPE.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/PropertyEditorToolsSystem.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
Added support to the Legacy Reflection Bridge to access Enum options reflected to the Serialize Context, to allow an enum value to be displayed as string instead of a number
Added support for a ToString attribute which works with both the EditContext and SerializeContext, that can be used to convert a type instance to a string.
So far the AZStd::pair reflection has a `ToString` attribute which can convert both elements of a pair to a string.
The Legacy Reflection Bridge associative container support has been updated to query the `ToString` attribute for any key it is processing and use that attribute function to convert the key to a string.
This allows aggregate types like a pair to be convertable to a label that is displayable in the DPE.
fixes #16771
fixes #16770
Verified the …
=> Document Property Editor Map Improvements

Code/Editor/Plugins/EditorAssetImporter/AssetBrowserContextProvider.cpp, Code/Editor/Plugins/EditorAssetImporter/AssetBrowserContextProvider.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserBus.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserEntityInspectorWidget.cpp
Modify the asset inspector to load the scene settings when the scene settings button is clicked in the inspector, rather than when an asset is selected from the asset browser. 
For assets that have thousands of submeshes and can take some time to load, this should unblock developers that want to inspect those assets and are not interested in viewing the scene settings.
Manually in the inspector
=> Scene Settings Load Changes

Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp
On Linux, the terrain system would sometimes crash when changing values on the Terrain System level component. These crashes were caused from dereferencing null rtData structures on teardown. The fix is just to put in a null check.
Repro steps:
* Create a new level.
* Add a Terrain System and a Terrain Renderer level component.
* Add an entity with a Terrain Layer Spawner and an Axis Aligned Bounding Box sized 1024 x 1024 x 100.
* On the Terrain System, change Min Height to -512.
* (crash)
Ran on Linux, verified that the Terrain System could be modified with the repro steps above.
=> Fix terrain crash from dereferencing a null rtData structure.

Code/Framework/AzCore/AzCore/Serialization/Json/PointerJsonSerializer.cpp, Code/Framework/AzCore/AzCore/Serialization/Json/PointerJsonSerializer.h, Code/Framework/AzCore/Tests/Serialization/Json/JsonSerializerConformityTests.h, Code/Framework/AzCore/Tests/Serialization/Json/PointerSerializerTests.cpp, Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialFunctorSourceDataSerializer.cpp
The Loading of an AZ::PointerObject is now strict with it requiring that the JSON being deserialized to be a JSON object and the fields of "$address" and "$type" are required to exist.
This makes sure that de-serializing to an `AZ::PointerObject` doesn't succeed in the cases when the [Dom::Utils::ValueToType](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/DOM/DomUtils.h#L361-L374) function first converts the DOM::Value to a RapidJSON document and then use JSON Deserialization to convert the type to an `AZ::PointerObject`.
Verified that the CVar Editor correctly shows the property handlers for integers, bools and string values
Also verified that modifying checkbox values correctly applies the change to the underlying bool of a console variable
=> Updated the Json Deserialization for AZ::PointerObject

AutomatedTesting/Gem/PythonTests/automatedtesting_shared/registry_utils.py
```
20:40:35  ..\..\..\..\..\..\AutomatedTesting\Gem\PythonTests\automatedtesting_shared\registry_utils.py:16
20:40:35    D:\workspace\o3de\AutomatedTesting\Gem\PythonTests\automatedtesting_shared\registry_utils.py:16: DeprecationWarning: invalid escape sequence '\O'
20:40:35      """
20:40:35
20:40:35  ..\..\..\..\..\..\AutomatedTesting\Gem\PythonTests\automatedtesting_shared\registry_utils.py:42
20:40:35    D:\workspace\o3de\AutomatedTesting\Gem\PythonTests\automatedtesting_shared\registry_utils.py:42: DeprecationWarning: invalid escape sequence '\O'
20:40:35      """
20:40:35
20:40:35  ..\..\..\..\..\..\AutomatedTesting\Gem\PythonTests\automatedtesting_shared\registry_utils.py:64
20:40:35    D:\workspace\o3de\AutomatedTesting\Gem\PythonTests\automatedtesting_shared\registry_utils.py:64: …
```
=> Escaping windows registry key in pydoc to fix python warning in Editor Python Test

Code/Framework/AzNetworking/AzNetworking/Serialization/ISerializer.h
Fix the compile warning `error: implicit conversion from 'unsigned long long' to 'unsigned long' changes value from 18446744073709551615 to 4294967295 [-Werror,-Wconstant-conversion]
`, which is shown by Clang16.
This function was introduced in PR #16626, and I assume the wrong type for the default parameter was overlooked then.
Compiling the Engine with Clang and MSVC
=> Fix clang compile warning about implicit conversion of default parameter value

Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
The variable is causing a set, but not used warning when building with clang
```
o3de/Code/Framework/AzToolsFramework/./AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h:396:31: error: variable 'proxyAddress' set but not used [-Werror,-Wunused-but-set-variable]
void* proxyAddress{};
```
Built using Clang 16 on a Linux platform successfully
=> Clang build fix removed unused `proxyAddress` variable.

Gems/ScriptCanvas/Code/Editor/Nodes/NodeDisplayUtils.cpp
Add translation support to method node execution slots. 
Closes #13692
=> Script Canvas: Add translation support to method node execution slots

Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuteGroupMerged.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuteGroupMerged.h, Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuter.cpp
The device removed error message was always "GPU device was removed while working on pass Merged. Check the log file for more detail.", even though we know the name of the pass when GPU-CPU in-sync is turned on.
This PR replaces the `Merged` in the error message with the Pass name.
Vulkan and Windows
=> Vulkan: Better device removed error message when GPU-CPU in-sync is on

scripts/build/Platform/Android/gradle_windows.cmd
Previously the gradle_windows.cmd script would set the JDK_HOME environment variable which is not used by the Android SDK Manager and Gradle.
This worked on Jenkins due to the system JAVA_HOME variable being set to Java 8 in the older AMI images for building Android on Jenkins, but once the JAVA_HOME environment variable was set to a version other than 8 in the newer AMIs,
the Jenkins build is now failing due to SDK Manager trying to use that version.
It is being tested by validating that the gradle AR build is able to succeed.
=> Fixing the gradle_windows.cmd script to set the JAVA_HOME env

Code/Framework/AzCore/AzCore/Serialization/AZStdContainers.inl
conditionally unused variables via `if constexpr` incorrectly.
Compiled the [Serialization.cpp](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/Tests/Serialization.cpp) which includes the AZStdContainers.inl using the `MSVC 19.29.30152.0` toolset
=> Workaround Visual Studio 2019 compiler defect where it warns about

Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp
Using project exporter will fail on Linux release package due to an unused variable error. Cherry picked from commit https://github.com/o3de/o3de/commit/554a8d78fe5e8dfbb0d996b253daf78bde176bd9
=> Cherry Pick unused variable fix on Linux to point release

Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.cpp
Fixes #16923 . There was a divide by zero bug that would happen in the ClipmapBounds constructor due to m_detailTextureSize getting rounded down to zero when the render distance is lower than the texture scale. By clamping the detail texture size to be at least 1 pixel, the divide-by-zero is avoided.
Went through the steps in the bug and verified the crash is gone. Note that there are still other crashes (#16889 and #16927 ) that can show up while testing this bugfix, but this specific bug is fixed.
=> Fix divide-by-zero bug when surface material size is too large.

Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp, Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.h
Fixes #16889 and #16927 . The sector pointers in the terrain ray tracing data were freed in some cases before they were accessed, causing arbitrary memory to get overwritten. This PR ensures the ray tracing data is freed before the sectors, and adds an assert to validate that assumption.
NOTE: There was a previous PR #16887 submitted to development that hid the issue somewhat, but didn't solve it. When merging point-release changes back to development, any merge conflicts should favor this PR over that one.
Performed the repro steps in the referenced bugs and verified that they no longer crash.
=> Fix terrain renderer memory trashing.

Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/ColorPicker.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/ColorPicker/PaletteCard.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/TableView.cpp, cmake/Platform/Common/MSVC/Configurations_msvc.cmake
The QT and AWS library are using Microsoft extension for `stdext::checked_array_iterator` which has been deprecated as part of the MSVC compiler 14.38 toolset.
This fixes the compiler warning of 
`// warning C4996: 'stdext::checked_array_iterator<const T *>': warning STL4043: stdext::checked_array_iterator,`
The deprecation of the check_array_iterator class occured in this Microsoft STL commit a few months back
https://github.com/microsoft/STL/commit/90dcf2672a5062f4be144b27a7232720d4d2c744
Verified that building the entire O3DE engine solution using Visual Studio 2022 17.8.0 Preview 5.0 with the 14.38 toolset compiled successfully
=> MSVC 14.38 toolset build fixes (VS2022 17.8.x series).

Code/Editor/LogFile.cpp
Previously the Windows was queried using GetVersionEx which only returns Windows 8 for any version of Windows 8 or newer.
The new method uses a WQL query to access Win32_OperatingSystem class for the current version information of the OS
The output now looks like the following when run on a Windows 10 OS "Microsoft Windows 10 Enterprise|C:\Windows|\Device\Harddisk0\Partition3 10.0.19045"
The previous output for a Windows 10 machine was
"Windows 8 6.2 (C:\Windows)"
Verified that Windows 10 was detected on a Window 10 OS
=> Switch detection of Windows version to access WMI

Gems/Atom/Feature/Common/Assets/Materials/Pipelines/MainPipeline/ForwardPassVertexAndPixel.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/DualSpecular.azsli
Fixing Skin Dual Specular and IBL getting applied twice.
Dual Spec factor was getting overridden by copy-pasted code.
IBL was getting applied twice because the flag we set in the normal encoding to notify the DiffuseCompositePass whether or not to apply the global IBL wasn't being turned off when we used the FORCE_IBL_IN_FORWARD_PASS macro.
This macro causes the global IBL to be applied during the forward pass, which means the application of it in the DiffuseCompositePass isn't necessary.
=> Fixing Skin Dual Specular and IBL getting applied twice

Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorDisabledCompositionComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorPendingCompositionComponent.cpp
Fixes #16807 .
PR #15985 previously fixed some of the issues related to disabled/pending components and how they work relative to component aliases, but there was still a case where loading a prefab containing a disabled or pending component after an Editor restart would assert and crash.
The reason for this is that while editing, the component would get added to the component, then get its SerializedIdentifier set, then get added to the PendingComponent map. If it meets all of its requirements, it then gets removed from the list and added to the entity. If not, it stays in the pending map.
However, when serializing out the component, the SerializedIdentifier doesn't directly get serialized out with the component. It gets serialized as the key for the PendingComponent map, but it wasn't …
=> Fix asserts/crashes caused by missing component serialized identifiers.

Code/Editor/Lib/Tests/test_EditorUtils.cpp, Code/Editor/Objects/DisplayContextShared.inl, Code/Framework/AzCore/AzCore/Debug/Trace.cpp, Code/Framework/AzCore/AzCore/Debug/Trace.h, Code/Framework/AzCore/AzCore/Memory/Memory_fwd.h, Code/Framework/AzCore/Platform/Android/AzCore/Debug/Trace_Android.cpp, Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/Debug/Trace_UnixLike.cpp, Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/Debug/Trace_WinAPI.cpp, Code/Legacy/CrySystem/AZCoreLogSink.h, Code/Legacy/CrySystem/AZCrySystemInitLogSink.cpp, Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleApplication.cpp, Gems/LyShine/Code/Source/LyShineLoadScreen.cpp
A special "<no-window>" window constant as been added to the Trace system via the `AZ::Debug::Trace::NoWindow` constant which allows the output of a trace message to skip printing both the window name parameter and the adjoining ":" separator which is used to split the trace message from the window.
Verified that running the `sys_DumpAllocationRecords` console command did not output the "<window-name> :" part to the console when printing the callstack
=> Added support to skip the output of a window in the Trace system

Code/Framework/AzCore/AzCore/Settings/CommandLine.cpp, Code/Framework/AzCore/AzCore/Settings/CommandLine.h, Code/Framework/AzCore/AzCore/Settings/CommandLineParser.cpp, Code/Framework/AzCore/AzCore/Settings/CommandLineParser.h, Code/Framework/AzCore/AzCore/Settings/ConfigParser.h, Code/Framework/AzCore/AzCore/azcore_files.cmake, Code/Framework/AzCore/Platform/Android/AzCore/AzCore_Traits_Android.h, Code/Framework/AzCore/Platform/Android/platform_android_files.cmake, Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/Settings/CommandLineParser_UnixLike.cpp, Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/Settings/CommandLineParser_WinAPI.cpp, Code/Framework/AzCore/Platform/Linux/AzCore/AzCore_Traits_Linux.h, Code/Framework/AzCore/Platform/Linux/platform_linux_files.cmake, Code/Framework/AzCore/Platform/Mac/AzCore/AzCore_Traits_Mac.h, Code/Framework/AzCore/Platform/Mac/platform_mac_files.cmake, Code/Framework/AzCore/Platform/Windows/AzCore/AzCore_Traits_Windows.h, Code/Framework/AzCore/Platform/Windows/platform_windows_files.cmake, Code/Framework/AzCore/Platform/iOS/AzCore/AzCore_Traits_iOS.h, Code/Framework/AzCore/Platform/iOS/platform_ios_files.cmake, Code/Framework/AzCore/Tests/Settings/CommandLineTests.cpp
The Command Line Parser supports a user supplied callback function which is passed each parsed command line option paired with it's value or a positional parameter when the option field is empty.
The existing `AZ::CommandLine` class has been retrofitted to use the `AZ::Settings::CommandLineParser` under the hood.
Verified the AZ::CommandLine test passes successuflly.
Also added additional UnitTest to verify the `AZ::Settings::ParseCommandLine` function directly.
=> Adding implementation of a no-heap allocation Command Line Parser

scripts/build/Platform/Linux/build_linux.sh, scripts/build/Platform/Mac/build_mac.sh, scripts/build/Platform/Windows/build_windows.cmd
This allows a single build step in the Jenkins pipeline to build multiple build configuration such as "profile" and "release" at once.
This is done by separating the build configs using a semi-colon.
e.g `"debug;profile;release"`
This opens up the ability for Jenkins to add multiple build configurations such as "profile" and "release" to an installer by specifying the `CONFIGURATION` env to be `profile;release`
Locally verified on both Windows and Linux the `scripts/build/ci_build.py` script to run the `installer` pipeline step was able to build both `profile` and `release` configuration when the `build_config.json` [CONFIGURATION](https://github.com/o3de/o3de/blob/development/scripts/build/Platform/Windows/build_config.json#L469) env was set to `profile;release`
=> Allow the Jenkins CONFIGURATION env to specify multiple build configs

Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/ColorPicker.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/ColorPicker/PaletteCard.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/TableView.cpp, cmake/Platform/Common/MSVC/Configurations_msvc.cmake
* MSVC 14.38 toolset build fixes (VS2022 17.8.x series).
The QT and AWS library are using Microsoft extension for `stdext::checked_array_iterator` which has been deprecated as part of the MSVC compiler 14.38 toolset.
* Update cmake/Platform/Common/MSVC/Configurations_msvc.cmake
=> [Cherry-Pick from development] MSVC 14.38 toolset build fixes (VS2022 17.8.x series). (#16966)

Code/Framework/AzCore/AzCore/RTTI/TypeInfo.h
Because the `AZStd::span` class has a default template argument, Visual Studio 2019 compiler gets has a parsing bug between selecting the function overload which accepts a "template template" parameter which is templated on a type parameter followed by a non-type parameter `<class, auto>` and the
overload which accepts a "template template" parameter argument which is templated on a variadic argument list of type parameters `<class...>`
As the AZStd::span is a type parameter, followed by a non-type paraamter `<T, Extent=std::numeric_limits<size_t>::max()>`., the former overload should be the one that is selected.
```
17:44:41
D:\workspace\o3de\Code\Framework\AzCore\AzCore/RTTI/TypeInfo.h(515,5):
error C2668: 'AZ::AzGenericTypeInfo::Internal::GetTemplateIdentity':
ambiguous call to …
```
=> VS2019 fix: Fixed ambigious call to the GetTemplateIdentity

Code/Framework/AzCore/AzCore/Serialization/AZStdContainers.inl
conditionally unused variables via `if constexpr` incorrectly.
Built using VS2019 successfully in the point-release branch
=> [Cherry-pick] Workaround Visual Studio 2019 compiler defect where it warns about

Gems/Atom/Feature/Common/Assets/Materials/Types/Eye.materialtype, Gems/Atom/Feature/Common/Assets/Shaders/Materials/Eye/Eye_MaterialSrg.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/Eye/Eye_SurfaceEval.azsli, Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/Math.azsli
The bugs would show up in versions of the Eye model different from the original Eye.fbx.
Other Eye meshes would have different model relative radius than the original `Eye.fbx`, and the original shader
code would assume that the model relative radius of the Eye "sphere" was 0.5. This new version of the shader
code normalizes the vector data, so the Radius is now 0.5 but from a normalized space.  
Added Sigmoid and PseudoSigmoid functions in Atom/RPI/Math.azsli. The PseudoSigmoid function leverages the Sigmoid function but adds control over the inflection point and how wide the sigmoid is around the inflection point.
A macro `USE_NORMALIZED_SPACE_ALGORITHM` was left in `Eye_SurfaceEval.azsli` to help the developer go back and forth between the old and the new methods of calculating the …
=> Fixed bugs in the shaders used by the Eye Material.

Code/Framework/AzCore/Tests/Console/ConsoleTests.cpp, Code/Framework/AzCore/Tests/Settings/SettingsRegistryMergeUtilsTests.cpp, Code/Framework/AzCore/Tests/Settings/SettingsRegistryOriginTrackerTests.cpp, Code/Framework/AzCore/Tests/Settings/SettingsRegistryTests.cpp, Code/Framework/AzFramework/Tests/DocumentPropertyEditor/SettingsRegistryAdapterTests.cpp, Code/Framework/AzTest/AzTest/Utils.cpp, Code/Framework/AzTest/AzTest/Utils.h
Cherry-picks this PR from development to the point-release as it is a prerequisite for cherry-picking a separate PR in o3de-extras for fixing SDF importing.
Value: High, enables cherry-picking of SDF import fixes for nested models. Most non-trivial SDF files have nested models, this makes them work.
Blast Radius: Low, this PR only affects test code.
Ran AzCore.Tests after the cherrypick and verified they all passed.
=> Cherrypick - Consolidate the  `CreateTestFile` function into the AzTest library (#16859)

Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp
Added a fix to that allows pass timings to be properly recorded when a pass does not do anything for a single frame.
This fix was tested on Windows using the Vulkan and DX12 RHI.
=> Fixed pass timings not showing correct values in certain cases

Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.h
Prior to this PR, ImGUI GPU Profiler did not report any timings for the `RayTracingAccelerationStructure`. These changes add support proper reading out and displaying of the timings for this scope. A screenshot of the fix is shown below:
Tested within the editor on Windows using the Vulkan and DX12 RHI.
=> Added support to show GPU timings for the RayTracingAccelerationStructure Pass

Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorScriptCanvasComponent.h, Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
Assigning graph to selected entities was not working, this change updates the code to rely on the outcome of the AddComponentsToEntities function to apply the asset Id to the selection
Tested in editor
Closes #11705
=> Fixed 'assign ScriptCanvas graph to entity'

Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/ContextMenus/ConnectionContextMenu.cpp
Closes #13555 
Disables the "Duplicate" option from the connection context menu
=> Disable duplicate action from connections context menu

Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/UiDropdownBus.names, Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/UiDropdownOptionBus.names, Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/UiTextBus.names, Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/UiTextInputBus.names, Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/UiTooltipBus.names, Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/UiTooltipDisplayBus.names
Update the Script Canvas nodes to have a subtitle that explains which category they belong to
Closes #16142
=> Added subtitles to UI Set Text nodes

Gems/ImGui/Code/CMakeLists.txt, Gems/ImGui/Code/Source/ImGuiManager.cpp
1. Allow IMGUI in release builds
2. Add `O3DE_IMGUI_RELEASE_ENABLED` CMake var to let the user turn it off if desired
3. Fix issue displaying IMGUI console in release build when sys_deactivateConsole was used
Created a release build with debug symbols enabled, used sys_deactivateConsole=0 and 1 and tried opening/closing the console and typing commands, changed levels, quit, etc.
=> Allow IMGUI in release mode and fix sys_deactivateconsole

Gems/AudioEngineWwise/Assets/AudioBank_Dependencies.xml, Gems/AudioEngineWwise/Assets/GameAudioSeedList.seed
Adds a `GameAudioSeedList.seed` file for users to use to generate asset lists to make sure their game audio is included in .pak files.
Addresses https://github.com/o3de/o3de/issues/16987
Added AudioEngineWwise to AutomatedTesting and used the AssetBundler to generate the asset list from `GameAudioSeedList.seed`, then verified the `.bnk` and `.xml` files ended up in the asset list.
=> Add Wwise seed lists for game audio and libs

Code/Framework/AzCore/AzCore/DOM/DomUtils.h, Code/Framework/AzCore/AzCore/DOM/DomValue.cpp, Code/Framework/AzCore/AzCore/DOM/DomValue.h, Code/Framework/AzCore/AzCore/RTTI/ReflectContext.h, Code/Framework/AzCore/AzCore/Serialization/EditContext.h, Code/Framework/AzCore/Tests/AttributeDomInteropTests.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/AggregateAdapter.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.h, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyRowWidget.cpp
Both the Reflected Property Editor and Document Property Editor weren't not triggering ChangeValidate events.
For the Reflected Property Editor, the reason why it wasn't triggering ChangeValidate events was that the
`PropertyRowWidget::HandleChangeValidateAttribute` function incorrectly casted the ChangeValidate attribute function to a function that returned a `bool` type. However all of the Change Validate functions return the type of `AZ::Outcome<void, AZStd::string>`.
The Document Property Editor issue was more involved.
First the signature of the ChangeValidate functions had the form of `AZ::Outcome<void, AZStd::string>(C::*)(void*, const Uuid&)`.
Now the way the DomUtils API works now when it comes to storing non-builtin types such as Uuids, it uses Json Serialization to map a Uuid …
=> Fix ChangeValidate functions not triggering in Property Editors

Code/Framework/AzCore/AzCore/Component/ComponentApplication.cpp, Code/Framework/AzCore/CMakeLists.txt, Code/Framework/AzFramework/AzFramework/Archive/Archive.cpp, Code/Framework/AzFramework/AzFramework/Archive/ArchiveVars.cpp, Code/Framework/AzFramework/AzFramework/feature_options.cmake, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Libraries.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/UnitTesting/UnitTestingLibrary.cpp, engine.json
The Tool applications such as the Editor, AssetProcessor and AssetBundler now can work in release configuration when NOT using the monolithic-permutation.
There are two main changes.
1. Updated the default value for `sys_PakPriority` CVAR to change its file search priority to FileFirst in release configuration. Previously this was Pak only
2. Updated the Settings Registry Development Settings Overrides to allow merging from the engine, each active gem and the active project `Registry` folders when using the release configuration.
Both this changes combined allows the AssetProcessor and Editor to locate the files within the project directory and to load necessary settings registry files required for operation. For example the AssetProcessor(Batch) needs to load the …
=> Changes to support Tool applications(Editor, AP, AssetBundler) in non-monolithic release

Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialTypeBuilder.cpp, Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Maya/Scripts/Python/stingraypbs_converter/fbx_to_atom.py, Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Maya/Scripts/Python/stingraypbs_converter/stingrayPBS_converter.py, Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Maya/Scripts/Python/stingraypbs_converter/stingrayPBS_converter_maya.py, Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Substance/builder/atom_material.py, Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Substance/builder/sb_gui_main.py, Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/azpy/o3de/renderer/materials/material_utilities.py
The material type builder produces a default material type file with all properties explicitly listed. This is done for technical artists and scriptures to be able to easily enumerate all of the properties without parsing the material type format, which was much more complicated than it is and can reference other files. When this feature was added, it used the source material extension and did not register an asset type uuid.
This change renames the extension to avoid confusion with normal materials and adds the uuid to prevent the error spam in the editor.
Fixes https://github.com/o3de/o3de/issues/13677
Tested by enabling feature and building materials to see files with new extension were produced without causing warnings.
=> Fixed warnings and errors related to material type builder producing all properties material

Gems/ScriptCanvas/gem.json, engine.json
Script Canvas node registration was changed in https://github.com/o3de/o3de/pull/16678 and code changes need to be made to support these changes.  Bumping the ScriptCanvas gem and engine versions so developers(e.g. PopcornFX) have a version to use in CMakeLists to determine which registration method to use
Increments the ScriptCanvas gem major version and engine major version.
Related: https://github.com/o3de/o3de/pull/16678
- there are no code changes, but configured and built with AutomatedTesting on PC anyways
=> Bump version for ScriptCanvas changes

Gems/Atom/RPI/Code/Source/RPI.Public/Image/StreamingImage.cpp
The instance ID class was changed to support multiple sub ids and require explicit construction from different data sources like assets, asset ids, or uuids, which set the sub Ids differently. The streaming image function was searching for an existing instance based on a raw uuid treated as an asset id but creating the instance using the asset id from the asset creator, which could assign different sub Ids and a creation token, affecting the instance id.
To guarantee that the instance is created and looked up using the same id, we switched to the create from UUID function so that sub Ids will be ignored.
Create from CPU data error message no longer appears in console
=> fix error caused by streaming image instance being created from cpu data with mismatching ids

Gems/Atom/RPI/Code/Source/RPI.Public/RenderPipeline.cpp
Follow-up to [PR !15823](https://github.com/o3de/o3de/pull/15823)
Fixes some issues that came up in an environment with multiple views:
- Unregistering a view no longer deletes the view-tag from `m_pipelineViewsByTag`, allowing immediate re-registration of a view for that view-tag
- Don't clear the vector of views in `m_pipelineViewsByTag`, since the engine assumes entries for persistent views in the  have always one viewPtr in the array, and only check for validity, but not existence
- Rebuild the `m_persistentViewsByViewTag` when the pipeline changed, since otherwise invalid view-pointers would stick arround when the game-mode is started from the editor
=> Fixes issues when unregistering a view

Code/Framework/AzFramework/AzFramework/Physics/PhysicsSystem.h, Gems/PhysX/Code/Source/ArticulationLinkComponent.cpp, Gems/PhysX/Code/Source/ArticulationLinkComponent.h
This PR resolves https://github.com/o3de/o3de/issues/16990, by adding a handler that destroys articulations if the scene is removed. It also prevents a crash during the deactivation of the component by checking if the scene is a `nullptr`.
This PR was tested by reproducing the behavior described in https://github.com/o3de/o3de/issues/16990.
=> Fix destruction of articulations

Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabComponentAdapter.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabOverrideLabelHandler.cpp
- fixes prefab override icon size #17063 
- fixes prefab override label assert/crash #17065 
=> prefab override fixes

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
Properly inherit DescriptorAttributes::ParentContainerCanBeModified attribute, along with the other parent container attributes. This ensures that containers with invisible members properly display container edit controls
=> properly inherit DescriptorAttributes::ParentContainerCanBeModified attribute

Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
Fixes dangling column widgets existing in the layout when they've already been removed from the dom hierarchy. We were getting away with this before prefab overrides were enabled, because the first column widgets were always simple labels that didn't have handlers associated with them.
Fixes #17073
=> fix for "Add Material Component" crash when prefab overrides are enabled

Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
hide handler widgets when being removed to prevent visual artifacts
=> Fix for DPE widgets being briefly visible during reset

Gems/DiffuseProbeGrid/gem.json, Gems/LyShineExamples/gem.json, Gems/SceneLoggingExample/gem.json, Gems/Terrain/gem.json, cmake/Platform/Common/Install_common.cmake
Discovered an issue when trying to build a project from the project manager using CMake configure:
```
CMake Error at C:/workspace/dev/o3de/install/cmake/LYWrappers.cmake:766 (message):
ly_de_alias_target called on non-existent target: Gem::UiBasics.Tools
Call Stack (most recent call first):
C:/workspace/dev/o3de/install/cmake/SettingsRegistry.cmake:137 (ly_de_alias_target)
C:/workspace/dev/o3de/install/cmake/SettingsRegistry.cmake:270 (o3de_get_gem_load_dependencies)
C:/workspace/dev/o3de/install/CMakeLists.txt:116 (ly_delayed_generate_settings_registry)
-- Configuring incomplete, errors occurred!
See also "C:/workspace/sdk-test/SDKTestProject/build/windows/CMakeFiles/CMakeOutput.log".
See also …
```
=> Adding fixes for CMake configuration when starting from SDK Installer build of O3DE

Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp, Gems/Atom/RHI/Code/Include/Atom/RHI/CommandList.h, Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.h, Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.cpp, Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.h, Gems/Atom/RHI/Null/Code/Source/RHI/CommandList.h, Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.h, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridVisualizationAccelerationStructurePass.cpp
This PR speeds up the Raytracing Acceleration Structure Build by moving the barriers between BLAS build calls to right before the TLAS build. The BLAS build commands do not depend on each other. This means that the barriers are not necessary there and they impact the performance quite a bit. We also moved the RaytracingAccelerationStructurePass to the Async Compute Queue.
The performance impact of the barriers is especially noticeable when multiple Actor components are in the scene. In a scene with 16 Actors the runtime of the pass was reduced from ~5.2ms to ~0.5ms (on DX12), as reported by the PassTimings in O3DE.
Unfortunately the speedup for Vulkan was not nearly as big. Here the pass timings only got down to ~4ms.
I think the Build calls are parallelized with DX12, whereas they are …
=> Raytracing Acceleration Structure Build: Moved the BLAS barriers to right before the TLAS build

engine.json
Bump the engine MINOR version so the point release version number is higher than the last release, but lower than development branch which is > 3.x.x
A corresponding change has been made in the nightly Jenkins job so the engine version matches `2.2.0`
n/a there is a non-code change
=> Increment engine version for point release

Code/Framework/AzToolsFramework/AzToolsFramework/Archive/ArchiveComponent.cpp
Using path instead of building pathview for archive file injection; stops accidental garbage names from being produced
Fixes #16869
=> Fix AddFileToArchive

Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTreeToTableProxyModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetEntryChangeset.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetEntryChangeset.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp
Users with large asset databases have had issues with long startup times in the main editor. Profiling has shown that the bottlenecks lie in the asset browser views and models synchronizing/populating and reflecting changes as assets are added and removed.
Most of the time was spent in the following functions
AssetEntryChangeset::Synchronize
AssetBrowserTreeToTableProxyModel::ProcessParents 
These changes add some high level optimizations, caching various values, replacing vectors and linear searches with unordered sets, removing seemingly unnecessary recursion, and other changes.
We should continue exploring options to remove or replace AssetBrowserTreeToTableProxyModel. The largest stall occurs initializing this class after the main asset browser model has been initialized. From what I …
=> Asset browser optimizations (changing container types, removing recursion, fixing memory leak)

Gems/Atom/RPI/Code/Source/RPI.Public/Image/AttachmentImage.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Image/ImageSystem.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Image/StreamingImage.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.h, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.cpp
This change addresses a recently reported performance drop and memory leak that was introduced after material, hot reloading, and instance id changes were merged into the development branch. The main problem causing the slowdown in leak was introduced by changes to the editor material component, trying to compensate for an older bug where the DPE was not refreshing material component previews. The on asset ready handler was getting triggered and handled several times, by several different entities referencing the same materials, updating their own previews even though they weren’t being displayed. The handler was removed, as it was not required by the RPE and does not seem to be required any more by the DPE on the point released branch.
Other fixes include making sure attachment images …
=> Fix performance drop caused by updating material component previews every time the asset load notification is received

Code/Framework/AzCore/AzCore/Memory/AllocatorManager.cpp, Gems/UiBasics/CMakeLists.txt
Fixes a 'unused variable' compile error when trying to use the package.py script from DefaultProject to build a linux monolithic release.  Specifically, building a monolithic release installer on linux fails with compile errors, and cmake errors.
The compiler errors were 'unused variable', the cmake errors were that other libraries like lyshine and so on were asking for the uibasics targets without necessarily having the same logic around them. 
Since the UiBasics builders and tools don't contain any actual code or targets, the dummy aliases are fine to have in any configuration and simplifies the use of them from other locations.
Tested by running a linux build release install for monolithic install.
=> Fixes compile errors and cmake errors for linux release

Gems/ScriptCanvas/Code/Editor/View/Widgets/GraphTabBar.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Core.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/GraphSerialization.cpp
Fixed that it was possible to open multiple copies of a graph by using the reopen graph option and also ensured that containers get cleared during serialization which was causing the number of slots to grow each time a graph was save/loaded.
Closes #17049
=> Fixed opening graphs resulting in duplicated slots

Gems/Atom/RHI/Code/Include/Atom/RHI/CommandList.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/GpuQuery/QueryPool.h, Gems/Atom/RPI/Code/Source/RPI.Public/GpuQuery/Query.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/GpuQuery/QueryPool.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/GpuQuery/TimestampQueryPool.cpp, Gems/Atom/RPI/Code/Tests/System/GpuQueryTests.cpp
This specific PR transitions resources related to `SingleDeviceQuery` to use `MultiDeviceQuery`.
This PR is part of a much bigger effort of multiple PRs mentioned as commit 4 in [this RFC](https://github.com/o3de/sig-graphics-audio/blob/main/rfcs/MultiDeviceSupport/MultiDeviceResources.md#planned-git-history). These PRs are designed to have an easier time transitioning the RPI to the new MultiDevice classes. Everything could be transitioned at once using a https://github.com/o3de/o3de/pull/14079, however that is clearly very hard to review with more than 600 files being touched. Therefore, we decided to split the merge request into multiple smaller ones to make reviewing easier even though that increases the amount of changes a little (see below why). The reviewed PRs will be merged into …
=> Query-related resources

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
- Implements support for IndexedChildNameLabelOverride
- const correct Find() so that it can be used from const functions
- Fixes #16058 
Locally in the Editor project
=> DPE Inspector support for IndexedChildNameLabelOverride

Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_Common.azsli, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_SurfaceEval.azsli, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/StandardPBR.materialgraphnode, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/StandardPBR.materialgraphtemplate, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test5.materialgraph, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test9.materialgraph, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test_normalmaps.materialgraph, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test_propertysorting.materialgraph, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test_scrolling_uvs.materialgraph
- This change updates material craft templates and material types to perform alpha clipping using the same logic as the stock material types.
- Opacity factor input was added to standard PBR node, to be used as a multiplier for tinted and blended opacity modes and a clipping threshold for cut out.
- Added simple code generation block for alpha clipping death and shadows.
- Updated test graphs and templates with new field
Fixes https://github.com/o3de/o3de/issues/16874
Compiled existing test graphs and templates
Created graphs to test different opacity modes
Configure different graphs with different values for alpha and opacity factor
=> Fix alpha clipping, cut out, and add opacity factor in material graph based material types

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/XR/XRRenderingInterface.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/XR/XRSpaceNotificationBus.h, Gems/Atom/RPI/Code/atom_rpi_public_files.cmake, Gems/Camera/Code/Source/CameraComponentController.cpp, Gems/Camera/Code/Source/CameraComponentController.h
Added AZ::RPI::XRSpaceNotificationBus
This notification EBus provides an event that is dispatched
per frame at the correct time by the XR Gem. This event is called
OnXRSpaceLocationsChanged(...), which provides the correct
transform data for the Headset and each Eye for the current
frame that is in-flight.
This change improves considerably the rendering of the XR Pipeline
for two reasons:
1- The Headset and Eye poses (transforms) are reported at the correct
time for each frame. This improves jitter (by reducing it).
2- Previously both eyes were using the exact same world Transform. Now
each Eye has the correct world Transform. This improves the sense
of depth if the XR scene.
This PR was tested with the OpenXRTest project from o3de-extras Gems using a Meta Quest Pro device. It was tested …
=> New XRSpaceNotificationBus

Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialTypeBuilder.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentExporter.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentExporter.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.cpp
- Moved generate source materials progress dialog into its own class so that it can be used in multiple places.
- Updated overlooked, manually invoked function to also use the progress dialog and wait on assets to be processed.
- Updated function that generated material file names to handle and replace dots in the material name.
Tested updated functions with large models containing 50+ materials and dots in material names.
=> fixed missed generate source materials function to use progress dialog

Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
Changed the spacing and margins for the DPE to look more like the RPE. This reduces a large gap between the property rows that added screen real estate and required extra scrolling. This was especially a problem for large property stacks, like material component with complex scenes that have 20, 50, or more materials.
Open the material component with 50+ materials to see that the gap has been reduced.
Examined other components like mesh and transform to make sure reduced gap did not interfere with them.
=> Reduce the gap between DPE property rows

cmake/Platform/Windows/Packaging/Tests/test_installer.py
Switches installer test to build a project with latest Visual Studio (2022) instead of Visual Studio 2019.  Visual Studio 2022 has been the default version available for some time now from Microsoft.  As time goes on more and more users will use the newer version and that is what our tests should use.
- n/a this test will run on the build machines and does not impact the build.
=> Use latest Visual Studio (2022) for testing installer project builds

Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h, Gems/LyShine/Code/Source/Draw2d.cpp
This commit fixes some instances where `Image`-related resources where missed during the conversion step (https://github.com/o3de/o3de/pull/17040) from single to multi device versions.
- `Gem::Atom_RPI.Tests.main`
=> Adding missing image conversions

Gems/Meshlets/Code/Source/Meshlets/MeshletsDispatchItem.cpp, Gems/Meshlets/Code/Source/Meshlets/MeshletsRenderObject.cpp, Gems/Meshlets/Code/Source/Meshlets/MeshletsRenderObject.h, Gems/Meshlets/Code/Source/Meshlets/MeshletsRenderPass.cpp, Gems/Meshlets/Code/Source/Meshlets/MeshletsUtilities.cpp, Gems/Meshlets/Code/Source/Meshlets/MeshletsUtilities.h
This commit fixes some instances where `Buffer` and `PipelineState`-related resources where missed during the conversion step (https://github.com/o3de/o3de/pull/17040) from single to multi device versions.
- `Gem::Atom_RPI.Tests.main`
=> MultiDeviceBuffers and -pipelines in Meshlets Gem

Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
When the threading gods are angry `FileProcessor::AssessAddedFile()` can get called on the Main thread via `notifyUuidManagerAndFileProcessor` and Qt thread from `FileWatcher::fileAdded` resulting in a [lockup in sqlite3 trying to insert the same file](https://github.com/o3de/o3de/issues/17097).  This usually repros on the first run when there are lots of assets and there is a higher likelihood of encountering the race condition.
Fixes https://github.com/o3de/o3de/issues/17097
This code was part of an optimization in https://github.com/o3de/o3de/pull/12654
I'm not 100% certain there may be some case where a modified file needs to have FileAdded called again to fix up some intermediate assets, please comment if you can think of a test case for this.
- ran AssetProcessor to build all …
=> Fix duplicate FileProcessor::AssessAddedFile call

Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabComponentAdapter.cpp
- move the dom update code out of the InProgressEdit and into the general case, so that it happens for the FinishedEdit case as well
- Fixes #17066 
Locally, in the Editor project
=> fixed prefab adapter DOM update to fire regardless of update type

Registry/AssetProcessorPlatformConfig.setreg
This change removes the legacy .cdf character format which no longer exists.  It also excludes a couple common folders that can add thousands of files to the AssetProcessor.
When examining the Sqlite database for the Carbonated project I noticed it included files in the `.git` and `Gems` folders.  The `.git` folder is common with projects stored in Git and the `Gems` folder is common for projects that include gems inside their project. 
Excluding these two folders excluded 5k+ files in the Carbonated project and decreased the database size from 70mb to 40mb.
Now, if the `Gems` folder thing seems to dangerous for existing projects - we can move that setting into project templates so it only applies to new projects.  Of course in the long run we want to use a single `Assets` folder inside …
=> Exclude .git, Gems and remove legacy .cdf

Gems/Atom/RHI/Metal/Code/Source/RHI.Builders/ShaderPlatformInterface.cpp
Fix the following build error on Mac:
```
/Users/github/o3de/Gems/Atom/RHI/Metal/Code/Source/RHI.Builders/ShaderPlatformInterface.cpp:408:122 Too few arguments to function call, expected 5, have 4
```
Built using cmake + xcode
=> Fix MAC Compile error in Atom Metal RHI

Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
While testing support for transparency in material canvas, users posted videos and screenshots of grainy textures with jagged edges where opacity factor and transparency were being applied. These results were different compared to the original standard material types, with the primary difference being the sampler settings. While the samplers are configurable in texture nodes, this change updates the default values for material canvas samplers to match the most common values used by preexisting material types.
Created new texture nodes to confirm the values are updated.
=> Changing material canvas default sampler settings to common values from preexisting material types

Gems/Atom/Feature/Common/Code/Include/Atom/Feature/SkinnedMesh/SkinnedMeshInputBuffers.h, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshInputBuffers.cpp, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Model/ModelLod.h, Gems/Atom/RPI/Code/Source/RPI.Public/MeshDrawPacket.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Model/ModelLod.cpp, Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Draw/EditorStateMeshDrawPacket.cpp, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.cpp, Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp
This commit fixes some instances where `Image/Buffer`-related resources where missed during the conversion step (https://github.com/o3de/o3de/pull/17040) from single to multi device versions, mainly in ModelLod.
- `Gem::Atom_RPI.Tests.main`
=> Missing image/buffer resources in ModelLod

Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/MaterialComponentBus.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
This is an optimization that causes the material component to only render custom previews if properties are overridden on the slot that would display the preview.
If no custom or live preview is rendered then the property asset control thumbnail widget will display the thumbnail for the assigned or default material asset.
- Prior to this, material component rendered live, custom previews for every material slot.
- After this, material component only renders those previews if the slot has custom properties set.
- If no custom properties are set, it uses the property asset control thumbnail widget to display the loading animation and eventually the loaded thumbnail.
- For some reason, the property editor does not always refresh when the thumbnail is ready without mousing over.
- When used …
=> Editor material component optimization to only render custom previews if properties are overridden

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
- fixes the instance pointer used for certain DPE attributes
- fixes #16762 and #17084 
=> fix instance pointer for EditorData attributes

scripts/o3de/ExportScripts/export_source_ios_xcode.py
A small error was discovered with the iOS exporter script where it would mistakenly use the path of the installer SDK binaries for asset processor, due to a mislabeled parameter. This PR introduces a one line fix to correct the behavior.
Tested on a mac with the AtomSampleViewer project. Export script successfully ran generating xcode file and processing assets.
=> Make sure ios export script uses correct asset processor path

Gems/Atom/RPI/Code/Source/RPI.Public/Image/AttachmentImage.cpp
Fixes https://github.com/o3de/o3de/issues/17178
The pass system is creating an attachment image instance from the brdf texture attachment image asset when the editor starts up and when the level opens. The function that creates the instance ID for the attachment image was changed to use the asset id and the creation token instead of just the asset ID.
If the editor is loaded while the initial batch of assets is still being processed by the AP, the pass system seems to load the attachment asset and create an instance with one creation token as the editor starts, then again with another creation token when opening the level. Because of that, the same asset is being re-registered with the same attachment name/ID, triggering the assert.
Temporarily reverting the change so that it only …
=> Fix attachment image assert on editor startup with clean cache

Code/Legacy/CrySystem/AZCoreLogSink.h
Make sure error logs are only printed once
Look below the change to see that the error log will be printed again based on if it has a window or not.
Fixes #17161
=> Remove Error Log Duplicate Spam

scripts/o3de/ExportScripts/export_source_built_project.py, scripts/o3de/o3de/export_project.py
* Remove option for headless server (not available in the 2310 release)
* Add missing parameter for 'platform'
* Fix logging to default to INFO -quiet is not set
launched project exporter for o3de-atomsampleviewer
```
scripts\o3de.bat export-project -es export_source_built_project.py -pp d:\github\o3de-atom-sampleviewer -out d:\output
```
=> Fixes for project export_project

scripts/o3de/ExportScripts/export_source_built_project.py, scripts/o3de/o3de/export_project.py
This PR fixes the export script issue found in issue https://github.com/o3de/o3de/issues/17192. For now it focuses on correcting erroneous behavior for profile builds by allowing the abillity to compile non-monolithic builds.
These changes were tested from an SDK install using a minimal project template. @AMZN-Gene has confirmed that these changes do work and provide a working launcher.
=> adjusting export script to allow for non-monolithic building

Gems/ScriptCanvas/Code/Editor/View/Widgets/GraphTabBar.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Core.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/GraphSerialization.cpp
Cherry picks the fix for https://github.com/o3de/o3de/issues/17166
Fixed opening graphs resulting in duplicated slots (#17109)
* Fixed opening graphs resulting in duplicated slots
* Fixed comparison operation to account all paths
-  testing was done in original branch
- compiled and ran Editor
=> Cherry-pick Script Canvas fix to point release

cmake/Tools/Platform/Android/android_post_build.py, scripts/o3de/o3de/android_support.py
Simplified asset synchronization for Android.
Fixes #17177
Instead of creating symbolic links for each Folder
and asset in `<ProjectRoot>/Cache/android`, it is simpler
and less error prone to simply create a single symbolic
link or; in case of Windows, a Junction, from
`<build>/android/app/src/main/assets`
TO:
`<ProjectRoot>/Cache/android`
Also instead of removing each sym link recursively, it suffices to simply remove the link to the root asset folder.
This PR was validated with a Windows10 host machine, and generating an Android APK for Meta Oculus Quest Pro device.
=> Simplified asset synchronization for Android.

scripts/o3de/ExportScripts/export_source_built_project.py, scripts/o3de/o3de/export_project.py
This PR addresses issue https://github.com/o3de/o3de/issues/17213. The old parameter `--no-monolithic` is now converted to allow users to specify `monolithic` or `non-monolithic` in the export settings
PR was tested on a local SDK installation including the code changes. Export script behaved as expected for both the monolithic and non-monolithic switches provided.
=> adjusting monolithic parameter to conform to export settings format

Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceImage.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceSwapChain.h, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceSwapChain.cpp, Gems/Atom/RHI/Code/atom_rhi_public_files.cmake
This PR is part of https://github.com/o3de/sig-graphics-audio/pull/137 (original proposal including discussion in https://github.com/o3de/sig-graphics-audio/issues/120, there referred to as (part of) commit 3 in the Planned git history sub-section) and introduces multi-device resource classes, including:
- `MultiDeviceSwapChain`
As noted in our original PR to introduce `MultiDeviceImage*` resources (https://github.com/o3de/o3de/pull/16591), specifically in this discussion (https://github.com/o3de/o3de/pull/16591#discussion_r1320087572), we chose to …
=> Introduce multi-device SwapChain
