Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/ScriptEditorComponent.cpp
- Implements SetDynamicEditDataProvider/m_editDataProvider functionality in the DPE-based inspector
- Properly tags ScriptPropertyGroup::m_properties as unmodifiable (ContainerCanBeModified)
- fixes #17193 
- fixes #17194 
- implement a StackEntry constructor for a tiny bit of efficiency and safety
- formatted code according to style guidelines
=> Implement support for SetDynamicEditDataProvider

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/WindowContext.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Specific/SwapChainPass.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/WindowContext.cpp
This specific PR transitions resources related to `SwapChain*` to `MultiDeviceSwapChain*`.
This PR is part of a much bigger effort of multiple PRs mentioned as commit 4 in [this RFC](https://github.com/o3de/sig-graphics-audio/blob/main/rfcs/MultiDeviceSupport/MultiDeviceResources.md#planned-git-history). These PRs are designed to have an easier time transitioning the RPI to the new MultiDevice classes. Everything could be transitioned at once using a https://github.com/o3de/o3de/pull/14079, however that is clearly very hard to review with more than 600 files being touched. Therefore, we decided to split the merge request into multiple smaller ones to make reviewing easier even though that increases the amount of changes a little (see below why). The reviewed PRs will be merged into a …
=> SwapChain-related resources

Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp
Fixes issue https://github.com/o3de/o3de/issues/17156
The BLAS of non-animated meshes where not added to the changedBlasList, resulting in missing barriers for these meshes, or no barriers at all if no animated meshes are present in the scene.
Windows and Vulkan/DX12
=> RaytracingAccelerationStructurePass: Fixed barriers for non-animated meshes

Gems/PhysX/Code/Editor/Source/ComponentModes/Joints/JointsComponentModeCommon.cpp, Gems/PhysX/Code/Editor/Source/ComponentModes/Joints/JointsComponentModeCommon.h, Gems/PhysX/Code/Source/EditorHingeJointComponent.cpp, Gems/PhysX/Code/Source/EditorPrismaticJointComponent.cpp
The current API for manipulating joint parameters via `EditorJointRequestBus` does not allow modifications of the parameters of motors. The modifications in this PR allow such changes for `EditorHingeJointComponent` and `EditorPrismaticJointComponent`. 
This change will be used by a [ROS 2 Gem](https://github.com/o3de/o3de-extras/tree/development/Gems/ROS2) from creating joints automatically rather than from the Editor (e.g. using Robot Importer tool, which creates _prefabs_ out of URDF or SDFormat descriptions). 
The code can be used as follows:
```cpp
jointComponent->Activate();
PhysX::EditorJointRequestBus::Event(
AZ::EntityComponentIdPair(entityId, jointComponent->GetId()),
&PhysX::EditorJointRequests::SetBoolValue,
PhysX::JointsComponentModeCommon::ParameterNames::EnableMotor,
true); …
```
=> Add setters to modify PhysX joints' motors

scripts/o3de/o3de/android_support.py
Fixes various issues around tool detection for the android generation scripts that only occur on Linux/Mac
Ran `o3de.sh android-configure --list --validate` on both Linux and Mac
Ran `o3de.sh android-generate -B build/android` on both Linux and Mac
Ran `gradlew assembleProfile` on o3de-atomsampleviewer on Linux and Mac
=> Fix Linux/Mac errors for the android generation scripts

scripts/o3de/ExportScripts/IgnoreAssetProcessor.profile.setregpatch, scripts/o3de/ExportScripts/export_source_built_project.py, scripts/o3de/o3de/export_project.py, scripts/o3de/tests/ExportScripts/test_export_source_built_project.py, scripts/o3de/tests/test_export_project.py
This PR fixes the issue found in https://github.com/o3de/o3de/issues/17222. The PR fixes the processor by preventing connecting to the asset processor via a setregpatch file. The file looks like this:
```
[
{
"op": "add",
"path": "/O3DE/Autoexec/ConsoleCommands/bg_ConnectToAssetProcessor",
"value": false
}
]
```
The script generation was tested from an O3DE Installer SDK and minimal game project template. Unit tests have also been added to ensure accuracy with patch generation.
=> Adding launcher setregpatch generation for profile builds

Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
This PR fixes #17217 
What does this PR do?
This PR fix the hard coded animation editor's multi sample settings, use the main editor's multi sample setting instead.
In Bug #17217 , it is because the shaders are compiled according to the multi sample state from the render pipeline loaded to the main editor, but the animation editor is hard coded to read the multi sample state  in `MainRenderPipeline.azasset`, so if the engine is not started with main render pipeline, there is a chance that the multi sample state is mismatch.
Here I fix the multi sample state for the render pipeline in animation editor, at least load the same multi sample state from the activated application, to ensure the multi sample state matches the shaders'.
Self tested, it works for me.
=> Fix hard-coded multi sample setting for animation viewport renderer 

Gems/GraphCanvas/Code/StaticLib/GraphCanvas/GraphicsItems/GlowOutlineGraphicsItem.h, Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindowSession.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/ValidationPanel/GraphValidationDockWidget.cpp
Remove the blur from the Script Canvas highlight nodes function as it was identified to degrade performance significantly.
Closes #17174
https://github.com/o3de/o3de/assets/58790905/5bcf6220-a6cd-4287-8f90-3ef1a839f12a
=> Removed blur from highlights, it degraded performance significantly

Gems/AtomLyIntegration/CommonFeatures/Code/Source/ScreenSpace/EditorDeferredFogComponent.cpp
In the deferred fog component, we can set fog start distance and fog end distance. If the fog start distance is larger than the fog end distance, one may come across wired unexpected rendering result. Our artist found this in one of our real projects.
Here I put a protection to ensure that the deferred fog's end distance is larger than its start distance to prevent the issue.
Self tested. It is a minor fix, so I suppose a simple self test might be enough.
=> Fix deferred fog issue because its start distance can be larger than end distance

Gems/Atom/RHI/Code/Source/RHI/DrawList.cpp
This PR fixes the transparent surface flickering when there are a lot of transparent material slots in the same mesh.
The reason why the transparent surface will flick:
The engine sorts the transparent objects' draw call by the sort key and the depth of the object, however, when there are a lot of transparent material slots in the same object, the sort key and the depth are all the same, then in each frame, the order of those transparent draw calls might change, making the transparent surface flickers. We came across this issue in one of our real projects.
So in this PR, I added a last resort to ensure the draw calls of transparent objects have a certain order to prevent the flickering when the above sorting condition fail.
Self tested.
=> Fix the transparent material slot flickering

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabComponentAdapter.cpp
Fixes an edge case where properties would not appear in the DPE if registered after a group was manually closed.
For an example of the issue, see attached GHI.
Fixes #17242 
=> DPE | Fix grouping issue where properties would not be shown if registered after a group.

Templates/DefaultProject/Template/export.bat, Templates/MinimalProject/Template/export.bat
Fix hardcoded path in the template export
Created a new project (DefaultProject) with the Project Exporter, verified the engine path was substituted correctly
**Note** Will bypass AR since there are no AR tests that invokes the project creation + export at this time.
=> Fix hardcoded path in the template export

Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/Limits.h, Gems/Atom/RHI/Code/Include/Atom/RHI/DrawItem.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceBuffer.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceDispatchItem.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceDrawItem.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceImage.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDevicePipelineLibrary.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceRayTracingAccelerationStructure.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceResource.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceShaderResourceGroupData.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceStreamBufferView.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceStreamingImagePool.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceSwapChain.h, Gems/Atom/RHI/Code/Source/RHI/DrawPacket.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceBuffer.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceBufferPool.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceDrawItem.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceImage.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDevicePipelineLibrary.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDevicePipelineState.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceRayTracingAccelerationStructure.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceShaderResourceGroupData.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceStreamingImagePool.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceSwapChain.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceTransientAttachmentPool.cpp, Gems/Atom/RHI/Code/Tests/MultiDeviceShaderResourceGroupTests.cpp, Gems/Atom/RHI/Code/atom_rhi_public_files.cmake
During the integration of multi-device resources into the engine (as is currently done on the branch [multi-device-resources](https://github.com/o3de/o3de/tree/multi-device-resources)), further testing revealed smaller issues, which have been fixed on that branch and shall now propagate to the multi-device classes already in `development`.
This also includes some integration of code that changed the single-device resource classes in the mean while and now is replicated in the multi-device classes.
The full list of PRs already in `development` is as follows:
|Preparation|[#16138](https://github.com/o3de/o3de/pull/16138)|merged|
|Base Resources|[#16202](https://github.com/o3de/o3de/pull/16202)|merged|
| Pipelines | …
=> Update multi-device resource classes

Code/Framework/AzFramework/AzFramework/Quality/QualityCVarGroup.cpp, Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugAuditTrail.cpp
Some whitespace fixes done by clang-format
Fixes some clang-17 compilation errors related to type casts. Some whitespace fixes by my formatter as well.
Built on Ubuntu Linux with Clang-17 in the point release branch
=> Fix clang-17 compilation errors in profile config

Code/Tools/Android/ProjectGenerator/README.md, Code/Tools/Android/ProjectGenerator/config_data.py, Code/Tools/Android/ProjectGenerator/discovery.py, Code/Tools/Android/ProjectGenerator/keystore_generator.py, Code/Tools/Android/ProjectGenerator/keystore_settings.py, Code/Tools/Android/ProjectGenerator/main.py, Code/Tools/Android/ProjectGenerator/project_generator.py, Code/Tools/Android/ProjectGenerator/subprocess_runner.py, Code/Tools/Android/ProjectGenerator/threaded_lambda.py, Code/Tools/Android/ProjectGenerator/wait_dialog.py, Code/Tools/ProjectManager/Platform/Linux/Python_linux.cpp, Code/Tools/ProjectManager/Platform/Mac/Python_mac.cpp, Code/Tools/ProjectManager/Platform/Windows/Python_windows.cpp, Code/Tools/ProjectManager/Source/ProjectButtonWidget.cpp, Code/Tools/ProjectManager/Source/ProjectButtonWidget.h, Code/Tools/ProjectManager/Source/ProjectUtils.h, Code/Tools/ProjectManager/Source/ProjectsScreen.cpp, Code/Tools/ProjectManager/Source/ProjectsScreen.h, Code/Tools/ProjectManager/Source/PythonBindings.cpp, Code/Tools/ProjectManager/Source/PythonBindings.h, scripts/o3de/o3de/command_utils.py
The Android Project Generator tool.
This PR adds a new feature to the ProjectManager (**o3de.exe**), by means of a set of python scripts, that automate the creation of Keystore files and the generation of an Android Project.
The following picture show the location of the menu option `Open Android Project Generator...`:  
And this is how the APG UI looks like:  
The UI was developed with the `tkinter` python module because it facilitates manual execution of this tool from the terminal using the python version that ships with O3DE.  The initial iteration of this UI was developed with PySide2, but it required to run from the Editor and made it impossible to run from the terminal.
What used to be a runtime exception for `o3de.bat android-configue --set-value` for Keystore passwords has been …
=> The Android Project Generator tool.

Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp
Allow the right click contextual menu to show up in the Asset Browser in thumbnail view if you click on an empty area (create new asset, change sort type, etc).
Notes:
- `AzAssetBrowserRequestHandler::AddContextMenuActions()` will only work if there is an entry selected, thus if selection is empty on rclick, I select the current folder
- The menu is disabled in search mode or in root folder as these contexts are invalid (cannot create a new asset outside of the project)
- The folder rename option is the only one not usuable. Should be either supported in the future or the folder edit option should be hidden in this context
Open a project, put the asset browser in thumbnail view, right click in empty area. Check that asset creation is working, sort types, folder move and delete
=> new: Allow contextual menu on asset browser when no selection

Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserFilterModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserFilterModel.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTableViewProxyModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTableViewProxyModel.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserThumbnailViewProxyModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserThumbnailViewProxyModel.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTreeToTableProxyModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetPicker/AssetPickerDialog.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntryUtils.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserListView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/EntryDelegate.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/EntryDelegate.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/Model/AssetCompleterModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/Model/AssetCompleterModel.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp, Gems/GraphModel/Code/Include/GraphModel/Model/Slot.h, Gems/GraphModel/Code/Source/Model/Slot.cpp, Gems/LyShine/Code/Editor/AssetTreeEntry.cpp, Gems/LyShine/Code/Editor/AssetTreeEntry.h, README.md
Optimize asset browser entry filters to use visitors instead of recursively building child containers
Optimize asset browser entry filters to use sets instead of vectors
Optimize asset browser entry filter string comparisons Optimize asset browser table view
Added expand all button to asset browser menu
Fixes https://github.com/o3de/o3de/issues/17091
Fixes https://github.com/o3de/o3de/issues/14645
Fixes https://github.com/o3de/o3de/issues/17247
Fixes https://github.com/o3de/o3de/issues/16272
Fixes https://github.com/o3de/o3de/issues/14645
Tested performance of asset browser filters using the multiplayer sample project
Enabling and disabling asset browser type filters updates immediately instead of taking several seconds
This should also improve performance of other asset browser …
=> Fix lockup when filtering asset browser entries by type

Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp, Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserEntityInspectorWidget.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserEntityInspectorWidget.h
On the entity inspector widget, allow to browse to asset dependency via right-click menu or on double click on the item.
Changes:
- New private class in Entity Inspector to handle dependent assets tree view
- The call to `AssetBrowserInteractionNotificationBus::SelectAsset` will no longer fail if the caller widget is not a child of the asset browser (new fallback to get the asset browser directly if not found in caller widget hierarchy)
Selected multiple asset types, deleted the entry while entity was selected and re-browsed to the dependency
=> new: Allow to browse to asset in the dependency tree view

Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.h, Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelectionRequestBus.h
Fix #17264.
Issue occured because the Action callback for `o3de.action.edit.deselectAll` was capturing a pointer of the current `EditorTransformComponentSelection`. Problem is that this class is destroyed and re-created anytime `PropertyEntityIdCtrl::StartEntityPickMode()` is called, thus the dangling pointer.
The fix proposal is to rely on the EditorTransform event bus, which will call the last valid instance of the class. There might be a better approach to prevent this problem that I'm not aware of.
If this is the way to go, I'll update the PR to add the unit test for the new command.
I believe that I should also update the other action callbacks in this class that are also capturing `this`.
1. Open a level with some content
2. Select an entity
3. Pick the reparent icon on the …
=> fix: Do not use dangling ptr for EditorTransform when echap key is hit

Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityActionComponent.cpp
handle missing descriptor for component. The entity this is refering to is Player Spawner 1 I think its failing to fetch the NetworkPlayerSpawnerComponent and then trying to access a null variable. 
```
~~1701837734320~~1~~0x7fce977fe6c0~~AssetProcessor~~Request started builder [B622F462B28B4CA7ABA64B0EC28CB31A] task (process) Prefabs/PlayerSpawner.prefab 
~~1701837734340~~1~~0x7fce977fe6c0~~AssetBuilder~~AssetBuilder: AllocatorManager before: allocatedBytes = 89103760 capacityBytes = 214748364800
~~1701837734340~~1~~0x7fce977fe6c0~~AssetBuilder~~AssetBuilder: Running processJob task
~~1701837734340~~1~~0x7fce977fe6c0~~AssetBuilder~~AssetBuilder: Source = /home/michaelpollind/O3DE/Projects/Multi/Prefabs/PlayerSpawner.prefab
~~1701837734340~~1~~0x7fce977fe6c0~~AssetBuilder~~AssetBuilder: …
```
=> bugfix: resolve crash when loading multiplayer sample

Code/Tools/Android/ProjectGenerator/project_generator.py, Code/Tools/Android/ProjectGenerator/subprocess_runner.py
It was found that the "android-generate" subcommand only finds the project config settings if the
working directory is the project root directory.
Validated with a project, for which the `build dir` and `root dir` where in completely different locations of the file system and was able to compile and deploy to a Meta Quest Pro devices using Android Studio.
=> android-generate runs from project root

scripts/o3de/o3de/android_support.py
When generating android projects for O3DE, you can set the asset mode to 'PAK' mode. This is not enough, however, since by default only release builds use pak files. In order to search for Pak files in non-release configurations, the [LY_ARCHIVE_FILE_SEARCH_MODE](https://github.com/o3de/o3de/blob/development/Code/Framework/AzFramework/AzFramework/feature_options.cmake) needs to be set to search for Pak files as well as loose assets. 
This also fixes gradle dependency issue for merge{config}Assets
The android generation script was ran to generate the NewpaperDelivery project with bundled android assets. Validated the generated build.gradle for `app` contains the additional cmake variable. Ran `gradlew.bat assembleProfile` and verified the pak files are located within the APK under the …
=> Fix Android Project Generation with Pak mode

Gems/Atom/Feature/Common/Code/Source/PostProcessing/TaaPass.cpp, Gems/Atom/Feature/Common/Code/Source/PostProcessing/TaaPass.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
I think updating an imported attachment image is a **commonly used** functionality, it is currently already  being used in TaaPass.cpp.
According to our real Gem developing experiences, we have quite a lot situations where we need this feature. But currently we don't have a common one in the Pass class. So I think it should be reasonable to implement one in the Pass class.
This PR moves most of the logic inside the `TaaPass::UpdateAttachmentImage` into a new function named `UpdateImportedAttachmentImage`, and putting this function in Pass class, so that the future developers can use this feature for their purpose.
Self tested, and commonly used in our real projects.
=> Abstract an UpdateImportedAttachmentImage function in Pass.h

Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
fixes "share prior column" error where updated widgets were adding duplicate attributes when being reset by the handler, because their prior cached attributes hadn't been removed.
fixes main bug reported here:
https://github.com/o3de/o3de/issues/17208
If other issues mentioned in that GHI still exist, please separate those out into different bug reports.
locally, in the Editor and DPEStandalone apps
=> make sure cached attributes are removed before they are re-added

Code/Framework/AzAndroid/java/com/amazon/lumberyard/io/APKHandler.java, Code/Framework/AzCore/Platform/Android/AzCore/Android/Utils.cpp, Gems/Atom/Bootstrap/Assets/seedList.seed, Gems/Atom/Feature/Common/Assets/seedList.seed, Gems/Atom/RPI/Assets/seedList.seed, Gems/AtomLyIntegration/AtomFont/Assets/seedList.seed, Gems/AtomLyIntegration/AtomViewportDisplayIcons/Assets/seedList.seed, Gems/AtomLyIntegration/CommonFeatures/Assets/seedList.seed, Gems/DiffuseProbeGrid/Assets/seedList.seed, Gems/LyShine/Assets/seedList.seed
This fixes an issue where Pak files are not being loaded when the pak priority indicates that pak files should be included during asset loading in an Android APK File.
**Root Cause**
- Locating the assets directory early on relied on the location of 'engine.json', which is valid for LOOSE asset mode. But for APKs that only contain PAK files, this file is not present, so it will be unable to locate the assets folder.
- When searching for the @product@/*.pak, the archive system normalizes the a 'current path' to '.', which is valid for normal file systems. However, using the Android Asset Manager's list method, it does not recognize this as the current folder.
- Even after the paks are finally loaded, a lot of the current seedlist files did not have android enabled as a platform, so they …
=> Fix Android Pak loading inside an APK

Code/Framework/AzCore/AzCore/DOM/DomUtils.h
- fixes string constructible types failing conversion when not implicitly strings, which especially caused certain opaque types to fail
- fixes https://github.com/o3de/o3de/issues/17287
- locally in the Editor and DPEStandalone projects
=> fix string constructible types failing conversion when not implicitly strings

Gems/LyShine/Code/Source/UiRenderer.cpp
This is similar to #17218, after that PR, I happen to found that the UI editor has the same issue. This PR fixes #17295, i.e., the same hard-coded multi sample setting in the UI renderer.
When the main editor starts with pipelines with multi sample 1 (e.g., low end pipeline etc.), and launch the UI editor, the UI editor by default hard-coded to read the multi sample from main pipeline, but the shaders are compiled with multi sample 1, then we will get a lot of console errors complaining about the mismatch multi sample between pass and shaders.
This time I also checked the other editors in the engine (I checked  script canvas, track view editor, material editor and material canvas editor), it seems that these editors are not starting any render pipeline or they are already handling the …
=> Fix hard-coded multi sample settings for UI renderer

Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserFilterModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetPicker/AssetPickerDialog.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetSelectionModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetSelectionModel.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorWidget.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.cpp, Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.cpp, Gems/LyShine/Code/Editor/AssetTreeEntry.cpp
Reverted changes to the asset browser filter model that had filtering auto recurse and use partial asset browser entry matching.
Cleaned up asset picker dialog selection model utility functions and propagation settings.
Always clearing selection model results when the selection changes in case nothing was selected.
Optimized asset browser entry path functions so the path is resolved when set instead of get. Returning string reference.
Deleted unused asset browser entry filter utility functions.
Improved asset browser table and thumbnail view filters.
Updated property asset control to allow assigning, dragging, and dropping source asset browser entries, resolving compatible product assets.
- Confirmed that filtering by asset type does not lock up the editor.
- Confirmed that model assets …
=> Asset browser: fixing filters and performance part 2

Code/Tools/SceneAPI/SceneData/Behaviors/AnimationGroup.h, Code/Tools/SceneAPI/SceneData/Behaviors/BehaviorsAnimationGroup.cpp, Code/Tools/SceneAPI/SceneData/Behaviors/BehaviorsMeshGroup.cpp, Code/Tools/SceneAPI/SceneData/Behaviors/BehaviorsSkeletonGroup.cpp, Code/Tools/SceneAPI/SceneData/Behaviors/BehaviorsSkinGroup.cpp, Code/Tools/SceneAPI/SceneData/Behaviors/MeshGroup.h, Code/Tools/SceneAPI/SceneData/Behaviors/SkeletonGroup.h, Code/Tools/SceneAPI/SceneData/Behaviors/SkinGroup.h, Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Behaviors/ActorGroupBehavior.cpp, Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Behaviors/ActorGroupBehavior.h, Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Behaviors/MotionGroupBehavior.cpp, Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Behaviors/MotionGroupBehavior.h, Gems/PhysX/Code/Source/Pipeline/MeshBehavior.cpp, Gems/PhysX/Code/Source/Pipeline/MeshBehavior.h, Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.cpp, Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.h, Gems/SceneLoggingExample/Code/Behaviors/LoggingGroupBehavior.cpp, Gems/SceneLoggingExample/Code/Behaviors/LoggingGroupBehavior.h
This PR fixes some missing `m_preferredOrder` values which are used for the order of the tabs in the Asset Inspector window:
The following values are now used (the ones marked with * were added by me), I did not resolve existing duplicate values:
* MeshGroup: 0
* SkeletonGroup: 1
* SkinGroup: 1
* AnimationGroup: 2
* MotionGroup: 2
* ActorGroup: 3
* MeshBehavior (PhysX): 5 *
* PrefabGroupBehavior: 6 *
* LoggingBehavior: 10 *
I chose 5 and 6 for Mesh/PrefabGroup behaviour since they used to use INT_MAX and were displayed to the right of the ones with smaller numbers, so their order remains unchanged. Without this change, all entries which dont explicitly specify the tab order (MeshBehavior, PrefabGroupBehavior, LoggingBehavior) are shown in implementation-specific order, since they are …
=> Add missing m_preferredTabOrder values

Gems/Atom/RHI/Vulkan/Code/Source/RHI.Loader/LoaderContext.cpp
Fix debug labels on Vulkan (the ones that appear on Renderdoc)
Did a capture with Renderdoc when running on Vulkan
=> Fix debug labels on Vulkan

Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserFilterModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserListModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTableViewProxyModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTableViewProxyModel.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserThumbnailViewProxyModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserThumbnailViewProxyModel.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserViewUtils.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserViewUtils.h
Consolidate some duplicated asset browser view code by adding utility functions for highlighting text and setting asset browser entry item drag and drop flags.
Performed brother cleanup, like variable initialization.
Tested dragging and dropping files and folders and thumbnail view.
The function disables dragging folders but allows files to be dropped onto them.
Dragging folders was supported in one location but the drop handling code ignored it.
Search filter colors highlight in all tested asset browser and asset picker views.
=> Create utility functions for asset browser highlighting and item flags

Gems/Atom/Feature/Common/Code/Include/Atom/Feature/LightingChannel/LightingChannelConfiguration.h, Gems/Atom/Feature/Common/Code/Source/LightingChannel/LightingChannelConfiguration.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorAreaLightComponent.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorDirectionalLightComponent.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/EditorMeshComponent.cpp, Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp
Cleans up lighting channel config UI.
Removes extra group surrounding each lighting channel config entry.
Adds labels with indices to each lighting channel in the container instead of printing the data type.
=> Update lighting channel config ui to remove extra groups and add labels each channel

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Material/Material.h, Gems/Atom/RPI/Code/Source/RPI.Public/Material/Material.cpp
The material instance class currently listens to the shader reload notification bus to reinitialize itself whenever shaders or shader variants change. Prior to this change, that reinitialization completely reset the material to its default, serialized state, erasing any material property value overrides that had been applied at runtime. This change preserves material property values by recording them before reinitializing the material and restoring them after.
Resolves https://github.com/o3de/o3de/issues/14944
Manual testing following the repro steps listed in the linked bug.
=> Preserve material property values after material is reinitialized due to shader or shader variant changes

Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Window/AtomToolsMainWindow.h, Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp, Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp, Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.h, Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorMainWindow.cpp, Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorMainWindow.h, Gems/Atom/Tools/PassCanvas/Code/Source/Window/PassCanvasMainWindow.cpp, Gems/Atom/Tools/PassCanvas/Code/Source/Window/PassCanvasMainWindow.h
Changing material editor and other tools to open documentation links instead of having dedicated help dialogs.
Add in terms of use and other details to about dialogs.
Resolves https://github.com/o3de/o3de/issues/8638
Confirmed that pressing F1 or clicking the help menu action opens the designated url in the browser instead of opening a help dialog
=> Updating material editor, canvas, and other atom tools to reference docs URLs

Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_SurfaceEval.azsli, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_SurfaceEval.azsli
This change updates material canvas shaders to invert the surface normal when rendering back faces. The original PBR material types handled this deep inside common functions that expected standardized material SRG properties, textures, options, and other parameters. Material canvas does not produce a standard material SRG or properties and cannot use these functions because everything is dynamically defined by the the graph.
Resolves https://github.com/o3de/o3de/issues/17254
=> Material Canvas: Negate surface normals when rendering back faces

Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Mocks/MockMeshFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/OcclusionCullingPlane/OcclusionCullingPlane.cpp, Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbe.cpp, Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbe.h, Gems/Atom/RHI/Code/Include/Atom/RHI/CommandList.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h, Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp, Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.h, Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp, Gems/WhiteBox/Code/Source/Rendering/Atom/WhiteBoxAtomRenderMesh.cpp
This change resolves a problem with mesh feature processor, where event handlers are connected after the mesh handle has already been acquired and the model potentially already loaded. This issue forced callers to manually invoke the event handler function just in case the model was already loaded or potentially have it called twice if the model was reloaded. With this change, the event handlers are set up front on the descriptor before acquire is called to ensure that the handlers are available and called if the assets are already loaded. It reduces boilerplate code throughout samples and systems to handle the event manually.
Additionally common this change moves the custom materials container into the descriptor as primary storage, so that it can be set up front, stored in one place, …
=> Update mesh feature processor so materials and event handlers are set up in the descriptor before acquire

Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp, Gems/Atom/RHI/Code/Include/Atom/RHI/DrawPacket.h, Gems/Atom/RHI/Code/Include/Atom/RHI/DrawPacketBuilder.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceDrawItem.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceDrawPacket.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceDrawPacketBuilder.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceObject.h, Gems/Atom/RHI/Code/Source/RHI/DrawPacketBuilder.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceDrawItem.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceDrawPacket.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceDrawPacketBuilder.cpp, Gems/Atom/RHI/Code/Tests/MultiDeviceDrawPacketTests.cpp, Gems/Atom/RHI/Code/atom_rhi_public_files.cmake, Gems/Atom/RHI/Code/atom_rhi_tests_files.cmake
This PR is part of https://github.com/o3de/sig-graphics-audio/pull/137 (original proposal including discussion in https://github.com/o3de/sig-graphics-audio/issues/120, there referred to as (part of) commit 3 in the Planned git history sub-section) and introduces multi-device resource classes, including:
- `MultiDeviceDrawPacket`
- `MultiDeviceDrawPacketBuilder`
- `Gem::Atom_RHI.Tests.main`
- Added a new test `MultiDeviceDrawPacketTests`
=> Introduce multi-device DrawPacket-related resources

Code/Tools/SceneAPI/SceneUI/CommonWidgets/SceneSettingsCard.cpp, Code/Tools/SceneAPI/SceneUI/CommonWidgets/SceneSettingsCard.h
When changing the scene settings for eg. a FBX file, and then right-clicking on some of the log messages to show additional data, the editor crashes in some cases.
This happens because the vector `m_additionalLogDetails` in `SceneSettingsCard` is not appended to for each log message, just for some warnings and errors, but it is later queried by the line number of the right-clicked log message, which leads to wrong messages being shown if there are info-messages at the start of the list and crashes due to out-of-bounds access of the array when right-clicking on entries further down the list.
I changed the data type of `m_additionalLogDetails` to use a `QMap` with the line number as key, such that both cases work correctly.
I was not able to test this with the latest development version, …
=> Fix crash when right-clicking on log messages in scene setting view

Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceDrawPacketBuilder.h
fixes truncation warning when mixing u8s and ints. Technically dangerous if the deviceIndex can exceed 256...
=> quick fix for truncation warning

Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.cpp, Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.h, Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocumentRequestBus.h, Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.cpp, Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.h
This is a check system that verifies a few conditions before allowing a variantlist file to be saved.
This way we enforce a few invariants that are helpful, even possibly necessary, for correct runtime behavior.
those are:
- no duplicated variants (same option choices on multiple rows)
- no root-like variants (**that's the same as a duplicate**, but the root is hidden in a variantlist, it's "inherited from the system" (in a way) but present)
- no jumps in stable id count space (I think the variant selector algorithm relies on compactness, but not certain).
Those are reflected in a new aggregate struct called DocumentVerificationResult, and the function is callable on SMCDocumentRequestsBus.
In the SMCDocument.cpp file there is a small refactoring works that extracts the hasher/variantkey …
=> [Smc] variantlist invariants verifier feature

Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicProperty/DynamicProperty.cpp
Some sliders and spin boxes were being clamped to zero and one because they had soft limits but no hard limits set. This change restores code that ensures limits are set to the extent of the data type if unspecified.
Resolves https://github.com/o3de/o3de/issues/17331
Manual testing and providing the changes to the original reporter to confirm that the issues are resolved.
=> Force atom tools dynamic property spinners and sliders to always have min/max attributes

Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.cpp
Resolve issue where material component default material slot always shows error indicator
Built project.
Launched editor.
Opened sponza level..
Selected entity with material component.
Saw that indicator no longer appeared next to default material slot with no material specified.
=> fix asset property control error indicator so that it doesn't show up for unspecified default assets

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ExpanderSettings.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabComponentAdapter.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabOverrideLabelHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabPropertyEditorNodes.h, Code/Framework/AzToolsFramework/Tests/Prefab/Overrides/PrefabInspectorOverrideTests.cpp, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceDrawPacketBuilder.h
- changes DPE expansion state saving to use the first column entry with a string as its path value, instead of exclusively requiring Labels. This is useful for adapters (like the prefab override adapter) that want to use node types other than generic Labels for their first column text
- fixes #17333 
=> Fix expansion state saving/restoring for PrefabOverrideLabelHandler

Gems/Achievements/CMakeLists.txt, Gems/MiniAudio/3rdParty/Findminiaudio.cmake, Gems/MiniAudio/CMakeLists.txt
- Fixes https://github.com/o3de/o3de/issues/17327 by declaring external targets for SDK builds.  The `miniaudio.h` and `stb_vorbis.c` files are not needed by the SDK but `permutations.cmake` CMake still refers to those targets.
- Fixes the default gem name for the Achievments gem in cmake
- Created a local O3DE SDK
- Created a project with MiniAudio, configured, built and opened the Editor and verified I could play audio
=> Fix MiniAudio compile issue in SDK (Installer buillds)

Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/ImageBuilder.settings, Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/BuilderSettingManager.cpp
Disable image builder platform support if the setting is marked Enabled=false
**Tested by:**
1) Ran AssetProcessor with pc and server enabled, and see that Cache/pc contains images, but Cache/server no longer generates images.
2) Open image settings in Editor.exe and server still hidden
Fixes #17334
=> Atom Image Builder Respects Platform Settings

Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableSystemComponent.cpp
Ensure root spawnable print log actually has the spawnable's name, otherwise the log thinks the name is empty.
=> Root Spawnable Print Log Fix

Gems/MiniAudio/Code/Source/Clients/MiniAudioModule.cpp
Fixing compile issue with monolithic release.  Point release branch does not have the macro changes development has for supporting gem renaming, so I've reverted that code here.
-configured and build monolithic MiniAudio library
=> Fix mini audio release

Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderBuilderUtility.cpp, Gems/Atom/RHI/Code/Include/Atom/RHI.Edit/ShaderPlatformInterface.h, Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/DeviceFeatures.h, Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/ShaderStages.h, Gems/Atom/RHI/Code/Include/Atom/RHI/PipelineStateDescriptor.h, Gems/Atom/RHI/Code/Source/RHI.Edit/Utils.cpp, Gems/Atom/RHI/Code/Source/RHI/PipelineStateDescriptor.cpp, Gems/Atom/RHI/DX12/Code/Include/Atom/RHI.Reflect/DX12/ShaderStageFunction.h, Gems/Atom/RHI/DX12/Code/Source/RHI.Builders/ShaderPlatformInterface.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/Conversions.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/Device.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/PipelineState.cpp, Gems/Atom/RHI/Vulkan/Code/Include/Atom/RHI.Reflect/Vulkan/ShaderStageFunction.h, Gems/Atom/RHI/Vulkan/Code/Source/RHI.Builders/ShaderPlatformInterface.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI.Reflect/Conversion.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Framebuffer.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/GraphicsPipeline.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Pipeline.cpp, Gems/Atom/RPI/Code/Source/RPI.Edit/Shader/ShaderVariantAssetCreator.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Shader/ShaderVariant.cpp, Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderAssetCreator.cpp, Gems/Atom/RPI/Code/Tests/Shader/ShaderTests.cpp
Adds support for geometry shaders for Vulkan and DX12 Backends.
Note, this PR breaks DDGI gem and DDGI gem needs to be recompiled.
Ran on Windows with Dx12 and Vulkan RHI
=> Support for geometry shader

Templates/DefaultProject/Template/project.json
- Add MiniAudio Gem to the DefaultProject template
- created a project with DefaultProject template, built it, opened the editor and verified the components could be added and play audio.
=> Add MiniAudio Gem to DefaultProject template

Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
Fixes the Save and Save As Feature being disabled in Script Canvas when the script was opened from the Script Canvas Component
Closes #17323
=> Fixed issue with Save options being disabled

Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
Found another path that needed document actions to be enabled. Ideally MainWindow.cpp needs a significant refactor and cleanup to remove all these edge cases.
=> Additional fix for #17323

Registry/AssetProcessorPlatformConfig.setreg
Update Registry/AssetProcessorPlatformConfig.setreg to ensure server asset platform generates _null shader variants
Fixes #17366
=> Server Asset Platform Generates Null Shader Variants

Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialTypeBuilder.cpp, Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialTypeBuilder.h
This PR adds the option for Gems to add their own materialpipelines via settings files by using the `MaterialPipelineFilesByGem` json key. This was previously only possible by adding all required materialpipelene paths to a settings file of a project, because json arrays are not merged and project settings take precedence over gem settings.
With the new method a list of materialpipelines can be specified per gem in the settings json, and since json dictionaries are merged without problem, all pipelines can later be queried in `MaterialTypeBuilder.cpp`.
For backwards compatibility the old version of specifying a single array is still supported. With this change, all pipelines from `MaterialPipelineFiles` and the entries of `MaterialPipelineFilesByGem` are merged.
This implements the second …
=> Allow gems to add material pipelines

Code/Tools/AWSNativeSDKInit/CMakeLists.txt
Cherry pick development branch fix for an AWS Native SDK CMake typo (commit 6710afd3e005e6a68a0baca3a3f50fdb4fabff77)
Fixes #17368
=> Fix AWS Native SDK CMake Typo

Gems/MiniAudio/Code/Source/Clients/MiniAudioImplementation.cpp
Fixes a compile warning treated as an error.
configured and built a new project using the MiniAudio gem
=> fix warning as error for vorbis integer conversions

Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp
Fixes https://github.com/o3de/o3de/issues/17390
This PR fixes the issue with the "Add Component" filter for prefabs' container entities. The filter sometime doesn't work as expected, which then allows users to add unsupported components to container entities. This is not what we want.
See details in GHI.
Tested in editor.
https://github.com/o3de/o3de/assets/11157226/407ce25e-37ea-494d-ad85-1552df0102d9
=> Set "Add Component" filter correctly for container entity

Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp, Gems/AtomLyIntegration/AtomRenderOptions/Code/Source/AtomRenderOptions.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
Recently, the mesh feature processor events for model and SRG changes were updated so that they could be registered with the descriptor, before the mesh handle was acquired. This change was necessary to eliminate explicit and redundant calls that compensated for the model already being loaded. Having the handlers registered beforehand allowed them to be executed correctly when the model asset was ready and the instance was created, whether the model was already loaded or if it loaded in the future. If the model was already loaded, the handler would be executed within the scope of the acquire function as soon as the connection to the asset bus is made. The problem with this is that several of the model change event handlers throughout the code base reference their mesh handle member …
=> Fixing mesh feature processor on model change event

Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceBuffer.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceImage.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceQuery.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceResource.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceShaderResourceGroup.h, Gems/Atom/RHI/Code/Include/Atom/RHI/SingleDeviceRayTracingPipelineState.h, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceBuffer.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceImage.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceQuery.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceRayTracingAccelerationStructure.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceRayTracingPipelineState.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceResource.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceShaderResourceGroup.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
This PR is part of a much bigger effort of multiple PRs mentioned as commit 4 in [this RFC](https://github.com/o3de/sig-graphics-audio/blob/main/rfcs/MultiDeviceSupport/MultiDeviceResources.md#planned-git-history). These PRs are designed to have an easier time transitioning the RPI to the new MultiDevice classes. Everything could be transitioned at once using a [single big commit](https://github.com/o3de/o3de/pull/14079), however that is clearly very hard to review with more than 600 files being touched. Therefore, we decided to split the merge request into multiple smaller ones to make reviewing easier even though that increases the amount of changes a little (see below why). The reviewed PRs will be merged into a [branch of o3de](https://github.com/o3de/o3de/tree/multi-device-resources) …
=> Fixes for some minor issues/warnings.

Gems/Atom/Tools/ShaderManagementConsole/Scripts/GenerateShaderVariantListForAllShaders.py
Changing shader management console batch generation script to generate all shader variant lists into a temp folder before copying to the project shader variant folder. This keeps materials, shaders, and shader variant lists from reprocessing in the ap as they are being generated.
Prompting the user before running the script so that they are aware existing shader variants in the project folder will be deleted.
Used script to regenerate shader variant lists for the automated testing project.
=> update SMC batch script to prompt user and generate files to temp folder first

Gems/Atom/Feature/Common/Assets/seedList.seed, Gems/Atom/Feature/Common/Registry/material_pipelines.setreg, Gems/DiffuseProbeGrid/Assets/seedList.seed
Added missing assets for lowend render pipeline which are used for android.
remove other platforms from DiffuseProbeGrid shader seeds since they are only available for pc & linux.
Build an android release build with a newly create o3de project. Have it running on an android device.
=> Android asset bundle fixes

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
- correctly parse dynamic container elements by allowing items with SerializeContext::ClassElement::FLG_DYNAMIC_FIELD to be parsed, even if they don't have editData (since their children still might)
- simplify container actions to always use the passed containerIndex; this fixes problems with invisible in-between ancestors, like dynamic containers
- partial fix for #17365 ; dynamic container elements can be displayed, removed, and moved, but not yet added by the DPE
=> handle dynamic container elements

Gems/Atom/Feature/Common/Code/Source/CommonSystemComponent.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/OcclusionCullingPlane/OcclusionCullingPlaneComponentController.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/PostFxLayerComponentController.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/SpecularReflections/SpecularReflectionsComponentController.cpp
Removing many unused Atom feature processors in headless mode
Fixes #17370 
Tested by running Multiplayer Sample headless server and seeing the game doesn't crash
=> Headless App: Remove Graphics Feature Processors

Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleApplication.cpp, Gems/Atom/Tools/ShaderManagementConsole/Registry/scripts.shadermanagementconsole.setreg, Gems/Atom/Tools/ShaderManagementConsole/Scripts/CreateShaderVariantListDocumentFromShaderInProjectFolder.py, Gems/Atom/Tools/ShaderManagementConsole/Scripts/CreateShaderVariantListDocumentFromShaderInSameFolder.py, Gems/Atom/Tools/ShaderManagementConsole/Scripts/GenerateShaderVariantListForAllShaders.py, Gems/Atom/Tools/ShaderManagementConsole/Scripts/GenerateShaderVariantListUtil.py
- Added an idle_wait_frames call to shader variant list generation script loops to give the application time to garbage collect graphics resources from creating material instances and SRGs.
- Disabled texture loading and function that enumerates shader items from material instances.
- Replaced asset browser interactions create new variant list side by side command with python scripts that can create the shader variant list in the shader folder or the project folder.
-- These scripts will automatically name and save the shader variant list document.
- Updated settings to register new scripts with file and asset browser menus.
- Tested all scripts manually.
- Verified that badge script successfully processes all shader assets, generating shader variant lists in the project folder without …
=> SMC Python script updates and fixes

Gems/Atom/RHI/Code/Source/RHI/FrameScheduler.cpp, Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.cpp
Fixes this dead end bug in the shader management console:
recompact wouldn't fix the problem, in fact, using it in the first place would put the user in a predicament and render the document unsavable.
The bug was caused by a too quick sweep and "fix" pass on the code using string search, to change all stableid count starts at 1. But the subsequent code was working with 0 start. Changed the increment to postcrement for fix.
=> Smc compaction stableidfix

Gems/QtForPython/Code/Source/Platform/Linux/InitializeEmbeddedPyside2.h
Affects issue #14813 - it turns out the python library we ship with changed the name of its deployed dynamic library.  It used to be called `libpython3.10.so` but is now called `libpython3.10.so.1.0`.  This changes the hardcoded path in the linux-only PAL file to look in this path for that file, which now works.
Local testing, on this ubuntu 22.04 machine.  The files are all deployed correctly, the wrong name is used for the library.  After this fix, it can find and locate the library, since it uses the RUNPATH of the Editor binary, which points at the same folder the editor binary lives in.
=> Fixes the path to the Python DLL for linux

Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.h
- Attempting to create an editor gradient image component, or load a prefab with one, was asserting and crashing because of a size mismatch
- Compared editor image gradient RTTI and allocator set up to similar components
- Inserted missing allocator macro
Resolves https://github.com/o3de/o3de/issues/17255
Attempting to add the component before changes crashed
Attempting to add the component after changes didn't crash
=> Fix editor image gradient allocation crash

Gems/ScriptCanvasDeveloper/Code/CMakeLists.txt, Gems/ScriptCanvasDeveloper/Code/Include/ScriptCanvasDeveloper/ScriptCanvasDeveloperComponent.h, Gems/ScriptCanvasDeveloper/Code/Source/ScriptCanvasDeveloperComponent.cpp
possibly fixes issue #15959 - a crash on startup if you enable the Script Canvas Developer gem on Linux.
Its probably a memory stomp on other platforms but Linux might reveal it more readily than other ones and show symptoms.
It turns out that the script canvas developer gem enables imgui for its static library, but not for its gem modules.  this causes a mismatch in the size of the object - specifically, the component object factory (as created in the gem module) is NOT derived from the IMGUI Bus listener, as that is `ifdef IMGUI_ENABLED`, but in the actual code (as coming from the static library), it is derived from it, and calls into those functions.   This causes it to call into and modify code outside its actual class size.
This PR changes it so that the object's size and vtable …
=> Potential fix for ScriptCanvasDeveloper crash

Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/Functions/split2.materialgraphnode, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/Functions/split3.materialgraphnode, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/Functions/split4.materialgraphnode, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test_split_conversions.materialgraph, Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialGraphCompiler.cpp, Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
This change adds a material graph node setting for property groups that up convert to the same vector size. In addition to checking the data types for slots and connections, the new setting will be examined for a minimum required size for compatibility with node shader code.
Another approach would have been to add an output slot with a fixed data type and size and include it in the property conversion groups. For example, each of the split nodes could have an output slot with the complete vector 2, 3, or 4. This would have worked without any code changes.
Created test graph with different split nodes showing automatic conversion without generating errors.
=> Fix MC split nodes by adding attribute for minimum size for vector up conversions

Code/Framework/AzToolsFramework/AzToolsFramework/UI/Logging/TracePrintFLogPanel.cpp, Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Window/AtomToolsMainWindow.h, Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
The log panel was using the system tick bus queue to add a function that captured 'this' pointer. Clicking reset deleted the log panel tab, which was still being referenced by the queued function, causing it to crash when the function was invoked. Fixed this by removing the connect to the bus as needed logic and keeping it connected at all times, disconnecting on destruction.
After fixing the issue, switched to using the newer styled version of the log panel.
Resolves https://github.com/o3de/o3de/issues/17410
Verified that the crash no longer occurred after changing the system tick bus handler registration.
=> fixed trace print log panel crash when pressing reset

Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ComponentEditor.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ComponentEditor.hxx
Fixes #17329  Required component notification UI empty issue
Added a navigation mesh component and verified the required component notification UI showed the components to add in a list and I could select them to add those components.
=> Fix required components notification UI

Gems/Atom/RPI/Code/Source/RPI.Public/Image/AttachmentImage.cpp
Fixed an issue that AttachmentImage::FindOrAsset won't work for AttachmentImage created with unique name.
ASV RenderToTexture sample.
=> Fixed an issue that AttachmentImage::FindOrAsset won't work for AttachmentImage created with unique name.

Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.cpp, Code/Framework/AzFramework/Tests/Platform/Common/Xcb/MockXcbInterface.cpp, Code/Framework/AzFramework/Tests/Platform/Common/Xcb/MockXcbInterface.h, Code/Framework/AzFramework/Tests/Platform/Common/Xcb/XcbInputDeviceMouseTests.cpp
Fixes the code in the XCB mouse input handler.
The code was previously assuming every raw motion event coming in was either for the x or y axis of the mouse.  However, raw motion events have a mask to describe which axis the event packet contains.  When you roll the wheel, or presumably, move the Z axis or other axes of a multi-axis device, it sets those bits to indicate which axes the data represents.
This change makes it so that the mouse movement code only considers the axes data if bit 0x1 or 0x2 are set (x and y mouse motion).
Wheel motion is captured by the button press code elsewhere.
Compile and building in linux debug and profile.  In debug, clear box testing and profile opaque box testing.  
The event now only triggers X and Y when I actuallymove the mouse X and y, and does not …
=> Fix issue #14877 - mouse wheel being intepreted as x-axis movement on linux

Gems/PhysX/Code/Source/Shape.cpp
While setting local pose, for eCapsule a rotation is applied, this happens in:
- [SetLocalPose](https://github.com/o3de/o3de/blame/6555c1eacc9e057831fdabedbab39d70c8510b25/Gems/PhysX/Code/Source/Shape.cpp#L253)
- [CreatePxShapeFromConfig](https://github.com/o3de/o3de/blob/6555c1eacc9e057831fdabedbab39d70c8510b25/Gems/PhysX/Code/Source/Utils.cpp#L486)
This PR applies inverse rotation while reading local pose
PhysX tests do not test if local pose is set correctly.
This does not impact Editor directly. 
External code that uses `GetLocalPose` will be able get accurate shape rotation for CapsuleShape
=> Apply inverse rotation to PhysX capsule when quering local pose

Gems/LyShine/Code/Source/LyShinePass.cpp, Gems/LyShine/Code/Source/RenderGraph.cpp
Fix for the GHI: https://github.com/o3de/o3de/issues/17415
The issue was because the RttChildPass was re-created when viewport was resized. So the render target of the RttChildPass was cleared in the pass. Although the UICanvas' render graph node wasn't redrawn when that happened. 
Basically the RttChildPass' enable/disable was not synced with the condition check around m_renderToRenderTargetCount which to trigger the uicanvas re-draw to the render target. 
The fix is to disable the RttChildPass by default unless the uicanvas render is called. 
Follow the steps mentioned in the GHI.
=> Fixed an issue that the UI render target texture became black when resize the viewport.

Code/Framework/AzFramework/Platform/Linux/AzFramework/Input/LibEVDevWrapper.h
This fixes the following linux compilation error related to the Linux gamepad implementation caused by non-deterministic unity builds
```
/home/github/o3de/Code/Framework/AzFramework/Platform/Linux/AzFramework/Input/Devices/Gamepad/InputDeviceGamepad_Linux.cpp:369:32: error: member access into incomplete type 'const struct input_absinfo'
absInfo->value, absInfo->minimum, absInfo->maximum, absInfo->fuzz, absInfo->flat);
^
/home/github/o3de/Code/Framework/AzFramework/Platform/Linux/AzFramework/Input/LibEVDevWrapper.h:36:72: note: forward declaration of 'AzFramework::input_absinfo'
using functionType_libevdev_get_abs_info        = const struct input_absinfo*(*)(struct libevdev *dev, unsigned int code);
^
In file included from /home/ANT.AMAZON.COM/spham/O3DE/Projects/NewProjectPhysX4/build/lin …
```
=> Fix Linux / Unity build issue with Linux Gamepad

Gems/Atom/Feature/Common/Code/Source/CoreLights/CoreLightsSystemComponent.cpp
Disable atom lighting features for headless applications
Tested by running headless server and connecting clients. Shadows appear for clients, but headless server keeps shadows disabled.
Fixes #17452
=> Fix Headless Server Crashing Due to Shadows

Code/Editor/Platform/Linux/Editor/Core/QtEditorApplication_linux.h, Code/Editor/Platform/Mac/Editor/Core/QtEditorApplication_mac.h, Code/Editor/Platform/Windows/Editor/Core/QtEditorApplication_windows.h
This PR fixes missing include guards in `QtEditorApplication_*.h`.
=> Fix missing include guard in `QtEditorApplication_*.h`

Templates/DefaultProject/Template/project.json, Templates/ScriptOnlyProject/Template/project.json
Added RemoteTools Gem to the default project template
to enable Lua Debugging by default.
It's been an old complaint, in particular for new
O3DE developers, being baffled for a while trying
to figure out why they can't debug a Lua Script.
Created a new project from the Default template and made sure
I was able to debug Lua code.
=> Added RemoteTools Gem to the default project template

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp, Code/LauncherUnified/Platform/iOS/launcher_project_ios.cmake, cmake/Tools/layout_tool.py, scripts/o3de/ExportScripts/export_source_ios_xcode.py, scripts/o3de/tests/ExportScripts/test_export_source_ios_xcode.py
This PR updates the existing iOS export script to bring functionality closer in line with updates for the PC and Android export scripts. The logic is upgraded such that the entire export process can now fully automate building the IPA package for the game launcher. 
This means the only manual steps required from the user are setting up Xcode for the first time with a valid Apple ID and provisioning profile, and uploading the IPA to their iOS device. A follow up PR will include necessary documentation changes.
Unit tests were added to verify script behavior with arguments.
Export testing was performed on a macbook pro with mac os 13.6.3, using Xcode 14.3.2. IPAs were confirmed to be created with the intended pak files in the asset folder and installed on a physical ios 16 device.
There is …
=> Update iOS Export scripts

Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceBuffer.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceBufferPool.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceImage.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceQuery.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceResource.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceShaderResourceGroup.h, Gems/Atom/RHI/Code/Include/Atom/RHI/RayTracingPipelineState.h, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceBuffer.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceBufferPool.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceImage.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceQuery.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceRayTracingAccelerationStructure.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceRayTracingPipelineState.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceResource.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceShaderResourceGroup.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceTransientAttachmentPool.cpp
Porting some already reviewed and merged changes from https://github.com/o3de/o3de/tree/multi-device-resources
- Bugfix for buffer mapping.
- Consolidate Views.
- Fix handling of nullptr during Activate* in MDTransientAttachmentPool.
- Fixes for some minor issues/warnings.
Gem::Atom_RHI.Tests.main
Gem::Atom_RPI.Tests.main
=> Porting bugfixes from the multi-device-resources branch.

Code/Framework/AzCore/AzCore/PlatformId/PlatformDefaults.h, Code/Framework/AzToolsFramework/AzToolsFramework/Asset/AssetSeedManager.cpp, Code/Tools/AssetBundler/CMakeLists.txt, Code/Tools/AssetBundler/assetbundlerbatch_files.cmake, Code/Tools/AssetBundler/assetbundlergui_files.cmake, Code/Tools/AssetBundler/source/models/SeedListTableModel.cpp, Code/Tools/AssetBundler/source/utils/AssetBundlerBatchBuildTarget.cpp, Code/Tools/AssetBundler/source/utils/AssetBundlerBuildTarget.cpp, Code/Tools/AssetBundler/source/utils/applicationManager.cpp
- fixes an issue where AssetBundler would show errors for platforms that were not enabled. 
- fixes an issue where AssetBundlerBatch was looking for the cmake_dependencies setreg using the AssetBundler specialization and if not found wouldn't know where all the gems were and a bunch of engine assets would be missed. This change mirrors how the AssetProcessor and AssetProcessorBatch handle that issue. Fixes https://github.com/o3de/o3de/issues/17442
- fixes https://github.com/o3de/o3de/issues/17298
- Ran AssetBundler and AssetBundlerBatch with engine dependencies on Mac and Windows and compared the before/after generated asset lists.
=> Misc Asset Bundler / Asset Bundler Batch fixes

Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp, Code/Framework/AzToolsFramework/Tests/Input/QtEventToAzInputMapperTests.cpp
Fixes #14768 
When tabbing out of the editor using alt tab, the editor would not reset the alt key upon return because the key release event would never reach it.
To fix this, code was added to the QtEventToAzInputMapper to reset all key states when the application was deactivated or reactivated.
However, that code was calling the base InputChannel::UpdateState function, which is non virtual, and the Input Channel for keyboard is actually a subclass which has special handling.  It needs to be cast into its actual concrete type and then ProcessRawInputEvent needs to be called for it to actually reset the modifier key states.
Because of this, the look camera and other components which queried the modifier key states were not getting the correct state.
Note that this should also have an …
=> Fixes the ALT key being held down after alt-tabbing

Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/GrowTextEdit.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/GrowTextEdit.h
Fixes #16908
Adjusts the GrowTextEdit class so that its size is correctly detected by the DPE resizing code.
=> DPE - Fix GrowTextEdit sizing

Gems/EMotionFX/Code/Source/Integration/Components/SimpleLODComponent.cpp
Stop animation simple LOD component from crashing on headless server applications due to missing camera viewport context
Fixes #17470
=> Headless App: LOD Component Crash Fix

Code/Framework/AzCore/AzCore/PlatformId/PlatformDefaults.cpp
Ensure AssetProcessor properly generates setreg files for cache/server
"Server" asset platform will return the host (Windows/Linux/Mac/etc) platform code. 
SettingsRegistryBuilder requires the platform code in order to generate the bootstrap.<client/server/unified>.<config>.setreg
Tested by running asset processor with server=enabled and seeing the bootstrap.setreg files populate.
- Bootstrap setreg contains all the important settings, such as physX collider groups
Fixes #17476
=> Server Asset Platform Generates Bootstrap Setting Registry

Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/ShaderResourceGroups/DefaultDrawSrg.azsli
Consider implementing a deferred rendering pipeline, we would need to send a full-screen draw with the a material index so that the shading pass can know what exactly the material instance is, therefore we may need to customize the draw srg, but in the current settings, all material types are sharing the same draw srg and there is no space for the developers to customize it.
So this PR introduce a macro to distinguish whether or not using the customized draw srg, one can define this when necessary in a Gem outside the engine.
Also, since the standard multilayer pbr and standard pbr material types are sharing the same lighting model, in the shaders inside the deferred shading pass we may not be able to distinguish them between each other, here I add a macro to tell that.
These few lines of …
=> Add support for custom draw srg for potential deferred rendering implementation with multiple material types

Gems/RemoteTools/Code/CMakeLists.txt
Fixes https://github.com/o3de/o3de/issues/17474
The Include folder is empty/missing and not needed in the RemoteTools gem, and CMake treats this as an error when trying to generate a project from the SDK with this gem active.
- built the RemoteTools targets after modifying the CMakeLists to ensure it still compiles
=> Fix missing Include folder error in SDK

Gems/MiniAudio/Code/CMakeLists.txt, Gems/MiniAudio/Code/Platform/Android/platform_android.cmake, Gems/MiniAudio/Code/Platform/Linux/platform_linux.cmake, Gems/MiniAudio/Code/Platform/Mac/platform_mac.cmake, Gems/MiniAudio/Code/Platform/Windows/platform_windows.cmake, Gems/MiniAudio/Code/Platform/iOS/platform_ios.cmake, Gems/MiniAudio/Code/Source/Clients/MiniAudioImplementation.cpp, Templates/DefaultProject/Template/project.json
During testing of project export for iOS using the Default Project template, it was discovered that the main source of issues was compilation errors for the MiniAudio Gem. The main source of the issue was that iOS was expecting objective c code, but Xcode treats the code files as CPP only, thus preventing the expected ObjC runtime from getting linked.
This PR fixes all compilation and linking errors that block export from projects using the Default Project template. The template has also been updated to remove AWSCore as well.
The changes were tested on a macbook pro with xcode and a physical iPhone device. The app successfully exported and ran on the iOS device, and expected PAK files were verified for release mode.
=> iOS MiniAudio Gem Compilation fixes

Templates/DefaultProject/Template/Registry/Platform/Android/quality.setreg, Templates/DefaultProject/Template/Registry/Platform/Linux/quality.setreg, Templates/DefaultProject/Template/Registry/Platform/Mac/quality.setreg, Templates/DefaultProject/Template/Registry/Platform/Windows/quality.setreg, Templates/DefaultProject/Template/Registry/Platform/iOS/quality.setreg, Templates/DefaultProject/Template/Registry/quality.client.setreg, Templates/DefaultProject/Template/Registry/quality.headless.setreg, Templates/DefaultProject/Template/Registry/quality.server.setreg, Templates/DefaultProject/Template/Registry/quality.setreg, Templates/DefaultProject/template.json, scripts/o3de/o3de/engine_template.py
- add quality settings with platform overrides and launcher type overrides (client, server, headless)
- add some print output when a project or gem is successfully created.
- created a project, verified the new files existed
- verified no new errors or warnings appear when running the editor related to the quality settings
=> Add quality settings to default project template

Code/Framework/AzFramework/Platform/Windows/AzFramework/Windowing/NativeWindow_Windows.cpp, Code/Framework/AzFramework/Platform/Windows/AzFramework/Windowing/Resources.h, Code/Framework/AzFramework/Platform/Windows/platform_nativeui_windows_files.cmake, Code/LauncherUnified/Platform/Windows/launcher_project_windows.cmake, Templates/DefaultProject/Template/Resources/LegacyLogoLauncher.bmp, Templates/DefaultProject/Template/Resources/Splash.bmp, Templates/DefaultProject/template.json, Templates/MinimalProject/Template/Resources/LegacyLogoLauncher.bmp, Templates/MinimalProject/Template/Resources/Splash.bmp, Templates/MinimalProject/template.json
- changes the game launcher background from windows default (bright white) to black
- draws a splash bitmap centered in the window (windows only for now) - splash comes from [o3de logo pack ](https://github.com/o3de/artwork)
- replaces `LegacyLauncherLogo.bmp` with `Splash.bmp`
This is still in draft, need to fix coding style, c-style casting, and hopefully add the splash to Linux and Mac launchers.
- ran the profile game launcher on Windows and verified the splash screen is shown before the renderer starts drawing
=> Add splash on black background to game launcher

Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/Handle.h, Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp
This PR makes sure the XR System is initialized
only after the Asset System is initialized.
This change was required because the new version
of the OpenXRVk Gem requires an asset that defines all actions supported by the application, this asset is required during XR Session initialization.
The AZ::RHI::Handle template class is now available in all script contexts. This is necessary because in an upcoming PR for o3de-extras some OpenXR APIs are exposed to the behavior context.
Validated with OpenXRTest running on Link mode, and on device with a Meta Quest Pro.
=> XR Initializes after Asset System

Gems/Atom/Feature/Common/Code/Source/CommonSystemComponent.cpp
Only unregister Atom feature processors on servers if they were enabled.
Tested by running headless server and seeing spam reduction on shutdown due to calling "unregister" on features that were never enabled in the first place.
=> Headless Server: Atom Feature Processor Cleanup

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/ContainerActionButtonHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/ContainerActionButtonHandler.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/GenericButtonHandler.h
Fixes #17275
Rewrites the DPE Layout class to be more straightforward, since the missing refreshes were due to edge cases tied to overly complex logic.
Verified that the new code fixes issues like buttons and labels disappearing when clearing containers.
Some container bugs are still present, but they were verified to be unrelated to this change and will be addressed separately.
=> DPE | Layout classes rewrite to fix refresh issues with containers.

Gems/Atom/RHI/Code/Source/RHI/Scope.cpp
The hardware queue class was reset in the 'Scope::Deactivate' function. This function is called every frame.
All passes in the Engine set the hardware queue class through the 'InitScope' function of the 'ScopeProducer'. This is only called once when initializing the scope. This means that after one frame the hardware queue class was always Graphics, regardless of the value passed to the 'InitScope' function.
This fixes the issue with the queues mentioned in this PR: https://github.com/o3de/o3de/pull/17022
Tested with Windows + Vulkan/Dx12 and a level with two animated actors
=> Don't reset the hardware queue class when a scope is deactivated

Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp
This MR adds code to resolve the `@EXEFOLDER@` alias for watch paths in settings registry entries.
**Background:**
While we are developing one of our gems, we need to test it with different versions of O3DE. The setup is that the two engine versions are in different folders (with their respective build folders), and both use the same instance of the Gem, but use different projects.
The problem is that we are generating an .azsli file with CMake, with the content depending on the engine version, and we want to include that .azsli file in the shader code of our gem. This is currently done by placing the generated .azsli file in the source directory, but this is not satisfactory since now CMake has to be rerun when changing engine versions. With the suggested change we can add a scanfolder …
=> Resolve @EXEFOLDER@ alias in settings registry watch paths

Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
Fixes #17506
Replaces regular delete with Qt's `deleteLater` in the Editor.
This was the original code, but we had to change it during the submission process as it triggers the automated leak detection in unit tests. The problem is that direct deletion that was implemented in its place can cause instability (see bug above).
While fixing the leak detection would be more effective, I could not find a way yet so a viable fix for now is to detect whether we're running unit tests or not, and change the type of deletion based on that.
Manual testing, the crash above no longer occurs even on multiple tries (while it consistently reproduced on 1 or 2 tries before).
=> DPE | Delete widgets later in the Editor

Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/VectorInput.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/VectorInput.h
resolves issue https://github.com/o3de/o3de/issues/16956
not sure what the difference is between setting the background-color this way and using a property to drive it.  This doesn't seem like the correct solution but this does resolve the issue in the PR wonder what the difference in the handling would cause this? would be interested in seeing why this would be the case with QT? maybe there is a better solution that I haven't found?
follow steps of the linked PR
[Screencast from 2023-12-03 22-47-03.webm](https://github.com/o3de/o3de/assets/854359/2eae373b-8a38-46b3-96f3-ec2d18efa3f6)
=> bugfix: resolve VectorInput labels gray upon activate/deactive component

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/AttachmentReadback.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/AttachmentReadback.cpp
This PR is part of a much bigger effort of multiple PRs mentioned as commit 4 in [this RFC](https://github.com/o3de/sig-graphics-audio/blob/main/rfcs/MultiDeviceSupport/MultiDeviceResources.md#planned-git-history). These PRs are designed to have an easier time transitioning the RPI to the new MultiDevice classes. Everything could be transitioned at once using a [single big commit](https://github.com/o3de/o3de/pull/14079), however that is clearly very hard to review with more than 600 files being touched. Therefore, we decided to split the merge request into multiple smaller ones to make reviewing easier even though that increases the amount of changes a little (see below why). The reviewed PRs will be merged into a [branch of o3de](https://github.com/o3de/o3de/tree/multi-device-resources) …
=> Multi device attachment readback

Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceDispatchItem.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceDispatchRaysItem.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceDrawPacketBuilder.h, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceDrawPacketBuilder.cpp
This PR introduces a number of fixes to multi-device classes, in particular `MultiDeviceDispatchItem`, `MultiDeviceDispatchRaysItem` and `MultiDeviceDrawPacketBuilder`.
- Clean-up in `MultiDeviceDispatchItem`
- Reflect changes to API in `MultiDeviceDispatchRaysItem`
- The `MultiDeviceDrawPacketBuilder` has a use case (one example is the `TerrainMeshManager::BuildDrawPacket`), where it can be partially setup, then copied to create multiple `DrawPacket`s with shared properties, but differing in a few parameters. For this, proper copying must be supported.
=> Fixes to multi-device *Items and DrawPacketBuilder

Templates/GraphicsGem/Template/Code/Source/Tools/Components/Editor${Name}Component.cpp, Templates/GraphicsGem/Template/Code/Source/Tools/Components/Editor${Name}Component.h
The existing GraphicsGem Template was calling a pair of obsolete function in the controller class:
`m_controller.EnableFeatureProcessor(GetEntityId());` and
`m_controller.DisableFeatureProcessor();`
The fix was to simply remove the declaration
and implementation of the override:
`void OnEntityVisibilityChanged(bool visibility) override;`
Generated a new project after the fix and it compiles.
=> Fixes GraphicsGem Template Compilation

Code/Framework/AzCore/AzCore/IO/FileIO.h, Code/Framework/AzCore/Platform/Android/platform_android_files.cmake, Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/IO/FileIO_UnixLike.cpp, Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/IO/FileIO_WinAPI.cpp, Code/Framework/AzCore/Platform/Linux/platform_linux_files.cmake, Code/Framework/AzCore/Platform/Mac/platform_mac_files.cmake, Code/Framework/AzCore/Platform/Windows/platform_windows_files.cmake, Code/Framework/AzCore/Platform/iOS/platform_ios_files.cmake, Code/Framework/AzToolsFramework/AzToolsFramework/Asset/AssetUtils.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Asset/AssetUtils.h, Code/Tools/AssetProcessor/native/AssetManager/AssetCatalog.cpp, Code/Tools/AssetProcessor/native/AssetManager/ExcludedFolderCache.cpp, Code/Tools/AssetProcessor/native/AssetManager/FileStateCache.cpp, Code/Tools/AssetProcessor/native/AssetManager/FileStateCache.h, Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp, Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h, Code/Tools/AssetProcessor/native/tests/AssetCatalog/AssetCatalogUnitTests.cpp, Code/Tools/AssetProcessor/native/tests/FileStateCache/FileStateCacheTests.cpp, Code/Tools/AssetProcessor/native/tests/MissingDependencyScannerTests.cpp, Code/Tools/AssetProcessor/native/tests/UnitTestUtilities.cpp, Code/Tools/AssetProcessor/native/tests/UnitTestUtilities.h, Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.cpp, Code/Tools/AssetProcessor/native/tests/utilities/assetUtilsTest.cpp, Code/Tools/AssetProcessor/native/unittests/UnitTestUtils.cpp, Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp, Code/Tools/AssetProcessor/native/utilities/UuidManager.cpp, Code/Tools/AssetProcessor/native/utilities/assetUtils.cpp, Code/Tools/AssetProcessor/native/utilities/assetUtils.h
* Vastly improves startup time of AP on linux (and potentially windows too, actually).
* Fixes several iffy unit tests.
Please note that there are basically 2 parts to it, explained here
* Moved the initialization of the file cache earlier, and moved the first use of it (building the catalog) later, and made use of the file cache in doing so
* Made it so that the file cache API specifies that it is case insensitive, which is in fact the case for the file cache - just wasn't enforced in the Pass Thru version.
* Updated the startup sequence.  It used to be that a catalog rebuild was triggered at the same time as the file scan.  Now the catalog build happens after the file scan updates the file cache.  This means the catalog build can use the file cache.
The above changes were small and in …
=> Improve ap startup on linux

Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceBuffer.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceImage.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceRayTracingAccelerationStructure.h, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceBuffer.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceImage.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceRayTracingAccelerationStructure.cpp
Fixes a few crashes appearing when using multi-device resources, specifically a multi-threading bug and a bug in the multi-device TLAS where buffers got invalidated.
- `Gem::Atom_RHI.Tests.main`
- `Gem::Atom_RPI.Tests.main`
=> Fixes to parallel cache access and to GetTlas*Buffer

Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyStringComboBoxCtrl.hxx, Gems/PhysX/Core/Code/Editor/CollisionGroupWidget.cpp, Gems/PhysX/Core/Code/Editor/CollisionLayerWidget.cpp
Fixes #17427
With the current setup, changes to the Collision Layer properties of a collider would not be picked up by the level until other changes triggered an edit to the level. This was due to an incorrect setup of the widgets for the component, which didn't correctly signal when they were being edited. Restoring those notifications fixes the issue.
=> Ensure Collider widgets correctly signal when they're being edited

Gems/MiniAudio/Code/Include/MiniAudio/MiniAudioPlaybackBus.h, Gems/MiniAudio/Code/Source/Clients/MiniAudioPlaybackComponent.cpp, Gems/MiniAudio/Code/Source/Clients/MiniAudioPlaybackComponentController.cpp, Gems/MiniAudio/Code/Source/Clients/MiniAudioPlaybackComponentController.h, Gems/MiniAudio/Code/Source/Tools/EditorMiniAudioPlaybackComponent.cpp, Gems/MiniAudio/Code/Source/Tools/EditorMiniAudioPlaybackComponent.h
* Add a pause method for the Playback component
* Make it so that the `MiniAudioPlaybackComponentController::Play()` method does not set the PCM frame to 0, so that it may continue playing where it left off
* Make the `MiniAudioPlaybackComponentController::Stop()` set the PCM frame to 0
* Make `MiniAudioPlaybackComponentController::GetVolumePercentage()` return a percentage
Add a pause button in the editor:
Add a pause method and expose it to the behavior context:
These changes were tested against the main branch (2310.2 release).
Ping @AMZN-alexpete @AMZN-daimini @nick-l-o3de @SelfishOlex @gadams3 @spham-amzn
=> MiniAudio: Add a pause method for the Playback component

cmake/Platform/Windows/Packaging/Tests/conftest.py
The installer test is failing because `TemporaryDirectory` does not create all elements of a folder path. https://jenkins.build.o3de.org/job/O3DE-development_nightly-installer/145/execution/node/672/log/
This change will ensure the path exists before `TemporaryDirectory` is used.
- n/a will run test on Jenkins
=> Fix release installer test missing folder

Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Maya/Scripts/Python/legacy_asset_converter/constants.py, Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Maya/Scripts/Python/legacy_asset_converter/create_maya_files.py, Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Maya/Scripts/Python/legacy_asset_converter/image_conversion.py, Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Maya/Scripts/Python/legacy_asset_converter/lumberyard_data.py, Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Maya/Scripts/Python/legacy_asset_converter/main.py, Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Maya/Scripts/Python/legacy_asset_converter/standardPBR.template.material
This PR fixes the "LegacyAssetConverter" python utility which allows to convert textures and materials from lumberyard to o3de. The tool is properly explained via [this legacy documentation](https://github.com/o3de/community/tree/main/Migration%20Guides/Lumberyard%20to%20O3DE/Misc-Documents/Tutorials/Legacy-Asset-Conversion-Utility) (which will be updated in another PR)
- Prevent multiple runtime errors when trying to access a wrong key in a dictionnary/box
- Fix material template path to be absolute
- Fix converter texture path to be relative to the material instead of relative to the parent "Object" folder
- Allow to run the tool without maya installed
Converted all of the assets of the "StarterGame" lumberyard project Gem without issues (3gbs). Only on import in o3De ~5 materials had …
=> fix: "LegacyAssetConverter" to export assets lumberyard to o3de

Gems/LmbrCentral/Code/Source/Shape/EditorSplineComponent.cpp, Gems/LmbrCentral/Code/Source/Shape/EditorSplineComponent.h, Gems/LmbrCentral/Code/Source/Shape/SplineComponent.cpp, Gems/LmbrCentral/Code/Source/Shape/SplineComponent.h, Gems/LmbrCentral/Code/Tests/SplineComponentTests.cpp, Gems/LmbrCentral/Code/include/LmbrCentral/Shape/SplineComponentBus.h
Fixes splines in the DPE inspector.
The spline component would crash when trying to select a spline type, while it now works as expected again.
My guess as to what the issue was is that using an AZ::u64 as a ComboBox value, the RPE would pass it correctly while the DPE tries to convert it somewhere down the line. I honestly think using an enum works much better in the component either way as it helps readability and debugging. Will keep an eye on other components that may have similar setups to see if this broke anything else tho.
=> DPE | Fix Spline type handling

Registry/prefab.tools.setreg
Removing more visual components on server spawnables; one of which is PopcornFx component which was already creating spam on servers
Tested by running Multiplayer Sample headless server and connecting/playing with a client. Noticing reduced spam on servers.
=> Remove More Visual Components from Server Spawnables

Code/Framework/AzCore/Tests/SystemFileTest.cpp
`FileDescriptorCapturer_DoesNotDeadlock_WhenMoreThanPipeSizeContent_IsCaptured`
My assumption here is that stdout was being spammed somehow by pytest or other threads running at the same time.  To fix this, I made it write to a temp file in a auto delete temp folder instead.
The above test was succeeding when run directly (even with repeat 1000), but was failing every single time for me when run in parallel by pytest.
After this change it no longer failed during local ci_build pytest runs.  I would assume its been flaky on jenkins but could be working by luck.
=> Fix a flaky test

Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceRayTracingAccelerationStructure.h, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceRayTracingAccelerationStructure.cpp
This commit fixes handling of the `TLAS*Buffers`, which are created in the `CreateBuffers()` call, and need to be cached in the multi-device case (as a `Shutdown()` triggers the buffers to be invalidated).
A repeated call to `CreateBuffers()` internally advances the `m_currentBufferIndex`, hence the single-device variants of the `TLAS*Buffers` need to be retrieved anew.
Second, the creation of the multi-device buffers is now guarded with a `lock_guard`.
=> Proper handling of TLASBuffers

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Material/Material.h, Gems/Atom/RPI/Code/Source/RPI.Public/Material/Material.cpp
Add a interface function to get access to the `RPI::ShaderResourceGroup` for the MaterialSRG of a material.
Use the interface function in a custom gem.
=> add GetShaderResourceGroup() to RPI::Material

Gems/Atom/RPI/Code/Source/RPI.Public/ViewportContext.cpp
This fixes a bug that can happen in a scenario with multiple active cameras, where the view-tags are different when in play mode vs editor mode: 
The pipeline-view of the editor-camera is assigned to one of the pipeline views upon game start. 
Upon exit, the editor-camera is registered as the default view for the pipeline, but that does not de-register the camera from the already registered pipelineview with potentially a different tag. 
This previously led to a case where a single view is registered for multiple view-tags, which doesn't work.
Starting and stopping the Game-Mode from the editor with a custom render-pipeline that has multiple views, and with the MainPipeline to ensure normal behaviour is unchanged.
=> Try to de-register the view for a viewport before registering it as a default view

Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h
Exposes the m_isSkinnedMesh - flag maintained by the MeshFeatureProcessor
locally tested
=> expose IsSkinnedMesh() for a model of a mesh-handle

Code/Editor/EditorPreferencesPageGeneral.cpp, Code/Editor/EditorPreferencesPageGeneral.h
Fixes #2327
Removes legacy settings from Editor Preferences. These were not ported over when the viewport was reimplemented years ago (see attached issue for more context). As such, they have no effect when changed.
=> Editor Preferences | Remove unused deep selection settings

Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp, Code/Framework/AzCore/AzCore/Asset/AssetTypeInfoBus.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.cpp
The PropertyAssetCtrl widget would incorrectly detect assets being dragged as text drags when the lineedit was hovered, which resulted in incorrect drops and a very small area where the drop operation would be successful. Dragging text into the field is not very helpful to the UX since the autocompleter is not triggered, so even dropping a correct path or asset name in the field would not result in the asset being selected without additional interactions.
This said, I just removed text dropping onto the PropertyAssetCtrl LineEdit so that asset drops are detected correctly on the whole field.
Manual UX testing.
=> Inspector | Fix asset dropping into asset input fields

Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
Fixes #17509
Asset Browser would try to select the first element after the filter is changed, but that would result in an error in index conversion down the line.
Overall I don't think the functionality made much sense to begin with, so I just resorted to clearing the selection on filter changes.
This prevents the assert in debug mode.
=> Asset Browser | Clear selection on filter changes.

Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.cpp, Gems/Terrain/Code/Source/EditorComponents/EditorTerrainWorldComponent.cpp, Gems/Terrain/Code/Source/EditorComponents/EditorTerrainWorldDebuggerComponent.cpp, Gems/Terrain/Code/Source/EditorComponents/EditorTerrainWorldRendererComponent.cpp, Gems/Terrain/Code/Source/TerrainRenderer/EditorComponents/EditorTerrainMacroMaterialComponent.cpp
Fixes #5811
Adds help urls for these components:
Terrain World (https://docs.o3de.org/docs/user-guide/components/reference/terrain/world/)
Terrain World Debugger (https://docs.o3de.org/docs/user-guide/components/reference/terrain/world-debugger/)
Terrain World Renderer (https://docs.o3de.org/docs/user-guide/components/reference/terrain/world-renderer/)
Terrain Macro Material (https://docs.o3de.org/docs/user-guide/components/reference/terrain/terrain-macro-material/)
Terrain Physics Heightfield Collider (https://docs.o3de.org/docs/user-guide/components/reference/terrain/terrain-physics-collider/)
=> Terrain | Add Help Url to components that have docs pages

Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
Fixes an edge case that would cause a crash when an asset was dropped in the Outliner with no level loaded.
=> Entity Outliner | Prevent dropping an asset when no level is loaded.

Code/Editor/AssetEditor/AssetEditorWindow.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorWidget.cpp
Fixes #16351
Assets in the Asset Editor can be duplicated via "Save As..." even when they have no unsaved changes.
Also changes the Asset Editor to start as its own window as default instead of in the top left window area, disrupting the layout.
=> Asset Editor | Allow "Save As" to be selected when asset is not dirty.

Code/Framework/AzCore/AzCore/Component/Component.h, Code/Framework/AzCore/Platform/Android/AzCore/Component/Component_Platform.inl, Code/Framework/AzCore/Platform/Linux/AzCore/Component/Component_Platform.inl, Code/Framework/AzCore/Platform/Mac/AzCore/Component/Component_Platform.inl, Code/Framework/AzCore/Platform/Windows/AzCore/Component/Component_Platform.inl, Code/Framework/AzCore/Platform/iOS/AzCore/Component/Component_Platform.inl
This PR fixes 3 instances of the following compile error with Clang-16 on Windows:
```
.../o3de-2/Gems/Compression/Code/Source/Clients/CompressionSystemComponent.cpp:56:5: error: expected ';' after top level declarator
AZ_COMPONENT_IMPL(CompressionSystemComponent, "CompressionSystemComponent",
^
../Code/Framework/AzCore\AzCore/Component/Component.h:487:9: note: expanded from macro 'AZ_COMPONENT_IMPL'
AZ_COMPONENT_IMPL_WITH_ALLOCATOR(_ComponentClassOrTemplate, _DisplayName, _Uuid, AZ::ComponentAllocator, __VA_ARGS__)
^
../Code/Framework/AzCore\AzCore/Component/Component.h:478:113: note: expanded from macro 'AZ_COMPONENT_IMPL_WITH_ALLOCATOR'
AZ_RTTI_NO_TYPE_INFO_IMPL(_ComponentClassOrTemplate, __VA_ARGS__ AZ_VA_OPT(AZ_COMMA_SEPARATOR, __VA_ARGS__) AZ::Component) \
^
```
No manual tests were …
=> Fix clang-16 compile errors

Code/Framework/AzCore/AzCore/Serialization/SerializationUtils.cpp, Code/Framework/AzCore/AzCore/Serialization/Utils.h, Code/Framework/AzCore/AzCore/Slice/SliceComponent.cpp, Code/Framework/AzCore/AzCore/Slice/SliceComponent.h, Code/Tools/SerializeContextTools/Converter.cpp, Code/Tools/SerializeContextTools/Dumper.cpp, Code/Tools/SerializeContextTools/Runner.cpp, Code/Tools/SerializeContextTools/SliceConverter.cpp, Code/Tools/SerializeContextTools/SliceConverter.h, Code/Tools/SerializeContextTools/Utilities.cpp, Code/Tools/SerializeContextTools/Utilities.h
Repair the pipeline to convert .slice and .ly to .prefab, via an optionnal path to skip the asset processor (we deserialize the files ourselves to get needed values).
(Follow-up to https://github.com/o3de/o3de/pull/17397 and https://github.com/o3de/o3de/pull/17377).
- Add the optional argument "slices" used to list the wanted dependencies to convert
- Rely on the optional argument "project-path" already in usage for other commands
- Auto skip save backups folders
- Move InspectSerializedFile method to AzCore serialization utils
- Add method in SliceComponent to load slice file and get the root entity
*StarterGame level on Lumberyard*
*StarterGame level on O3de*
- The slice converter cannot handle layers (yet). When converting a level with layers, need to move its entities out of the layer …
=> fix: Allow to convert .slice to .prefabs

Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/BasePBR/BasePBR_SurfaceEval.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/EnhancedPBR/EnhancedPBR_SurfaceEval.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/Eye/Eye_SurfaceEval.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialFunctions/StandardGetAlphaAndClip.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/AlphaInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/BaseColorInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/ClearCoatInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/DetailMapsInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/EmissiveInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/MetallicInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/NormalInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/OcclusionInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/RoughnessInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/SpecularInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/SubsurfaceInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/TransmissionInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MultilayerPBR/StandardMultilayerPBR_Common.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/Skin/Skin_SurfaceEval.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/StandardPBR/StandardPBR_SurfaceEval.azsli, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_SurfaceEval.azsli, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_SurfaceEval.azsli
The current material texture sampling function inside `XXXInput.azsli` files is hard-coded to use `map.Sample(sampler, uv)`, this works in a forward rendering context since the draw-call is sent and rendered in an object-wise manner, the hard-ware can do the derivatives automatically for each object.
But consider a deferred render pipeline, where the shading draw calls are sent in a full-screen space manner (i.e., shading the G-Buffer), the hard-ware derivatives would be wrong. Actually I have noticed some artifacts caused by this mismatch in my prototype deferred pipeline (wrong sampled texture color in the border of frontier and background objects).
This PR adds a new parameter `uvDxDy` to new overloaded functions of those functions related to texture sampling, and pass the derivatives …
=> Allow passing customized derivatives to texture sampling functions for a possible deferred render pipeline

Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/DeviceFeatures.h, Gems/Atom/RHI/Code/Include/Atom/RHI/FrameGraph.h, Gems/Atom/RHI/Code/Include/Atom/RHI/FrameGraphInterface.h, Gems/Atom/RHI/Code/Include/Atom/RHI/Scope.h, Gems/Atom/RHI/Code/Source/RHI/FrameGraph.cpp, Gems/Atom/RHI/Code/Source/RHI/Scope.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/CommandQueue.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/CommandQueue.h, Gems/Atom/RHI/DX12/Code/Source/RHI/Device.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/FrameGraphExecuteGroupMerged.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/FrameGraphExecuter.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/AsyncUploadQueue.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandQueue.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandQueue.h, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Fence.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Fence.h, Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuteGroupHandler.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuteGroupPrimary.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuteGroupSecondary.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuter.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/NullDescriptorManager.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/PhysicalDevice.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/PhysicalDevice.h, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Queue.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Queue.h, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Scope.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Scope.h, Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp
For a device -> device copy we need a GPU -> CPU -> GPU synchronization, if no vendor specific extensions are pesent. This PR introduces this synchronization via the already existing `Fence` class. It consists of two parts:
1. Use timeline semaphores instead of fences in Vulkan, if the device supports it. Timeline semaphores are available as a extensions and in Vulkan 1.2. So most desktop GPUs should support them. The fallback to `VkFence` is probably still needed for older Android devices. Fences for DX12 are very similar to Vulkan timeline semaphores, so almost nothing had to be changed there.
2. Add a list of fences a scope must wait for before executing. These fences can be signaled from the CPU.
This was tested in the branch https://github.com/msat-huawei/o3de/tree/wait-for-fences, …
=> Scope: Added feature to wait a fence to be triggered

Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/Interpreted/ExecutionInterpretedOut.cpp
Adds a null check to ExecutionInterpretedOut for when resultsBVP is null
=> Fix ScriptCanvas crash when generic functions are invoked

Code/Tools/AWSNativeSDKInit/include/AWSNativeSDKInit/AWSNativeSDKInit.h, Code/Tools/AWSNativeSDKInit/source/AWSNativeSDKInit.cpp
Fix AWSNativeSDKInit interface so that users can call the status PreventAwsEC2MetadataCalls with default parameters
Tested by
Invoking AWSNativeSDKInit::PreventAwsEC2MetadataCalls() without any compiler errors
=> AWSNativeSDKInit::PreventAwsEC2MetadataCalls Default Param Compiler Error Fix

cmake/Platform/Common/Install_common.cmake
The CMakePresets.json from the root was missing from the install file list, so was never copied over.
This causes errors when trying to use them to build O3DE from the SDK version.
Built the install target, found the file copied over.  Now configuring a project using the installer with a preset file functions as expected.  Before, it would be missing, so none of the presets could be found.
=> Update install to include missing CMakePresets.json

Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/TimeView/TrackDataWidget.cpp
Fixes a crash when trying to emplace animation event node data into a vector.
AZStd::vector::emplace first parameter is an iterator, not an index into the vector
Fixes https://github.com/o3de/o3de/issues/17635
Note: standard c++ doesn't support passing '0' into std::vector::emplace (https://github.com/o3de/o3de/issues/17636)
=> Fix Animation Event Node Tooltip Recording Crash

Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/RenderMeshComponentRequestBus.names
Generated the latest & updated the frriendly naming for the RenderMeshComponentRequestBus Script Canvas nodes.
If there are other nodes that need updating, please see the [Node Text Replacement Documentation](https://www.docs.o3de.org/docs/user-guide/scripting/script-canvas/editor-reference/text-replacement/)
Closes #17620
=> Update ScriptCanvas names for RenderMeshComponentRequestBus

Gems/Atom/RHI/Code/Include/Atom/RHI/RHISystem.h, Gems/Atom/RHI/Code/Source/RHI/RHISystem.cpp, Gems/Atom/RHI/Code/Tests/DrawPacketTests.cpp, Gems/Atom/RHI/Code/Tests/RHITestFixture.h, Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp
During testing of multi-device resources in the `multi-device-resource` branch, one outcome was that the number of devices cannot easily be changed at run-time.
The previous method envisioned just adding a new virtual device at run-time, which does not work, as a number of common resources are initialized during the general setup and cannot easily be modified after the fact.
This new method changes this behavior to passing the number of devices as a flag `--device-count <count>`, which is then passed from `RPISystem` to `RHISystem`, which now still initializes a single device in case no flag or `1` is provided, which takes `count` of the physical devices (if available), but if `< count` physical devices are available, the existing physical devices are added as virtual devices in …
=> Change setup of virtual device support

Gems/Atom/RHI/Code/Include/Atom/RHI/IndirectArguments.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceBufferPool.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceDispatchItem.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceIndirectBufferView.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceShaderResourceGroupData.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceSwapChain.h, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceBufferPool.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceIndirectBufferSignature.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceShaderResourceGroupData.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceSwapChain.cpp, Gems/Atom/RHI/Code/Tests/MultiDeviceIndirectBufferTests.cpp
This PR fixes a few issues in the multi-device classes that have been found during our on-going testing in the `multi-device-resources` branch:
- `IndirectArguments.h`
- Previously the template arguments have not been used properly in the constructors
- `MultiDeviceBufferPool`
- `MapBuffer` now returns a map of pointers (instead of a vector), one per device, indexed by the `deviceIndex`
- `MultiDeviceDispatchItem`
- `DispatchItem` can also work without a `m_countBuffer`
- `MultiDeviceIndirectBufferView`
- Due to the `*Items` holding a raw pointer to a `IndirectBufferView`, someone needs to hold the memory now, which is now done with a cache guarded by a mutex
- `MultiDeviceShaderResourceGroupData`
- Moved the default parameter to the header
- `MultiDeviceSwapChain`
- Need the ability to …
=> Fixes to multi-device resources

Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
Adds a one-frame delay after duplication to ensure manipulators are shown correctly on the newly duplicated entity.
=> Fix manipulators showing up incorrectly after duplicate

Code/Tools/AssetProcessor/native/unittests/AssetProcessorManagerUnitTests.cpp, Code/Tools/AssetProcessor/native/unittests/AssetProcessorManagerUnitTests.h
Caused by this file being compiled with AssetProcessorManagerTest.h/cpp which also has the AssetProcessorManager_Test class when using unity build.
Happens with cmake-2.28.4 and newer.
=> Naming clash fix that happens with newest cmake.

Gems/Atom/RHI/Code/Include/Atom/RHI/SwapChain.h, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceSwapChain.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.h
Images of the MultiDeviceSwapChain were stale when recreated, this is fixed in `ProcessRecreation` now.
Also removing unnecessary forwards of Shutdown calls,  since Shutdown got called twice so far. This doesn't have any stability impact, but is wasteful.
Note: there is still an issue that already exists in development, see: https://github.com/o3de/o3de/pull/15949#discussion_r1539086079
`Gem::Atom_RHI.Tests.main`
=> Bugfix for MultiDeviceSwapChain which did not properly recreate images.

Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/Limits.h, Gems/Atom/RHI/Code/Include/Atom/RHI/FrameScheduler.h, Gems/Atom/RHI/Code/Include/Atom/RHI/Scope.h, Gems/Atom/RHI/Code/Include/Atom/RHI/ScopeProducer.h, Gems/Atom/RHI/Code/Include/Atom/RHI/ScopeProducerEmpty.h, Gems/Atom/RHI/Code/Include/Atom/RHI/ScopeProducerFunction.h, Gems/Atom/RHI/Code/Source/RHI/FrameGraph.cpp, Gems/Atom/RHI/Code/Source/RHI/FrameGraphCompiler.cpp, Gems/Atom/RHI/Code/Source/RHI/FrameScheduler.cpp, Gems/Atom/RHI/Code/Source/RHI/Scope.cpp, Gems/Atom/RHI/Code/Source/RHI/ScopeProducer.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/FrameGraphExecuter.cpp, Gems/Atom/RHI/Metal/Code/Source/RHI/FrameGraphExecuter.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuter.cpp, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/RenderPass.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/RenderPassData.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp, Gems/Atom/RPI/Code/Source/RPI.Reflect/Pass/PassData.cpp
This PR introduces the device index to `ScopeProducer`s and consequently to the `RenderPass` data that allows to set the device index in json for each pass. By default, we introduce the invalid device index (-1) which makes sure the scope will get assigned to a device automatically (the default device with index 0 for now). This is necessary to implement a sample that actually runs stuff on multiple GPUs though without any synchronization or proper dependencies in the frame graph yet. These changes we would like to postpone until the [multi-device-resources branch](https://github.com/o3de/o3de/tree/multi-device-resources) has been merged to development. 
`Gem::Atom_RHI.Tests.main`
`Gem::Atom_RPI.Tests.main`
=> Multi-device: Using device indices in RenderPass

Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingClosestHit.azsl, Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingCommon.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingMiss.azsl, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/SpecularReflections/SpecularReflectionsFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceFilterPass.cpp, Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceTracePass.cpp, Gems/Atom/Feature/Common/Code/Source/SpecularReflections/SpecularReflectionsFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/SpecularReflections/SpecularReflectionsFeatureProcessor.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/SpecularReflections/SpecularReflectionsComponentConfig.cpp, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.cpp
This PR adds the option to only use ray-traced reflections by selecting "Ray Tracing" in the "Specular Reflections" level component. This was previously not possible.
There are now 4 methods for specular reflections, where the first three are the same as before (when selecting [Hardware Ray Tracing][Ray Trace Fallback Data]-> [no][], [yes][no], [yes][yes]), left-to-right in following image which uses a different mesh LOD for ray tracing to see the difference between the methods:
* Screen-space: Use screen-space reflections only
* Hybrid SSR-RT: Use ray tracing for hit detection and screen-space data for surface evaluation (not entirely sure if this description is correct)
* Hybrid SSR-RT + Ray Tracing fallback: Use screen-space reflection data when available and ray tracing when not
* Ray …
=> Add support for ray-traced reflections in SpecularReflectionsFeatureProcessor

scripts/o3de/o3de/utils.py, scripts/o3de/tests/test_utils.py
PR fixes [[Creating a project with the CPP keyword as the project name causes a compilation error.](https://github.com/o3de/o3de/issues/17629#top)](https://github.com/o3de/o3de/issues/17629)
Now when cpp keyword is used for the project name an underscore is appended to identifier for cpp.
Add UTs.
Manual check.
=> Add sanitizing identifier for cpp when cpp keyword is used as the project name

Gems/Atom/Feature/Common/Code/Source/Shadows/ProjectedShadowFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/Shadows/ProjectedShadowFeatureProcessor.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/FeatureProcessor.h, Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
As of right now, when there are many lights on the scene, then usually most of them are outside the Camera frustum. Each light has a max range that it can cast shadow to. 
But current implementation always goes through object culling, shadowmap rendering etc. for all lights. This happens even if all shadows possibly casted from the light source are outside camera view.
This PR aims to improve performance by skipping unnecessary work for all shadows that won't be visible. 
This is achieved by culling light on the CPU to limit the amount of lights that processing is done for. 
Used intersection test: sphere (center=lightPosition, radius=maxRange) with view frustum of every persistent View.
There are other scenarios when culling shadows is also possible.
I hope that minimizing light impact …
=> Shadow culling outside view frustum

Code/Framework/AzToolsFramework/Tests/PythonLoaderTests.cpp
Since it was introduced, this test won't build correctly on my machine
```
TEST_F(AzToolsFrameworkPythonLoaderFixture, TestReadPythonEggLinkPaths_Valid)
```
The problem relates to this line:
```
static constexpr auto testEggLinkPaths = AZStd::to_array<const char*>({ "/lib/path/one", "/lib/path/two", "/lib/path/three" });
```
which triggers this error during the build:
```
fatal error C1001: Internal compiler error.
```
Up to now I resorted to just commenting out this test whenever I had to build the tests locally.
I've played around with the definition though and it looks like using the constructor instead of `AZStd::to_array` fixes the issue.
Ran test locally to verify it passes (while it would not build before this change)
=> Fix build issue with Python unit test.

Code/Framework/AzFramework/AzFramework/Input/Devices/Mouse/InputDeviceMouse.cpp, Code/Framework/AzFramework/AzFramework/Input/Devices/Mouse/InputDeviceMouse.h
Fixes issue #14879 
The issue was caused by the fact that the mouse input device was checking a variable that was tracking how much time since the last mouse input event, and considering things to be a new input event if more than a certain amount of time passed.
However, this function was being called for each axis on the Mouse (So X, Y, Z separately), but the "Time Since last event" variable was shared across the axes and thus would cause the X axis (the first) to act differently from the others.
The change does 2 things - one, it makes a per-axis time, and two, it only emits a "no movement" event artificially if there were no events this frame (and does so at the end of the frame), instead of what was happening before, which was to always emit a "no input" 0 axis event, at the begin of …
=> Fixes issue #14879 (Mouse input inconsistencies)

Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/AssetPlatformComponentRemover.cpp
Just silences unused variable warnings that are treated as errors.
=> Minor compile fix for release builds (unused variables)

Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceIndirectBufferView.h
Forgot to clear the cache for copy assignment operations on `MultiDeviceIndirectBufferView`, which, if not done, would lead to wrong results from the cache if the object being assigned to already had cache entries.
=> `MultiDeviceIndirectBufferView` Fix

Gems/Atom/Tools/ShaderManagementConsole/Scripts/CreateShaderVariantListDocumentFromShader.py, Gems/Atom/Tools/ShaderManagementConsole/Scripts/CreateShaderVariantListDocumentFromShaderInProjectFolder.py, Gems/Atom/Tools/ShaderManagementConsole/Scripts/CreateShaderVariantListDocumentFromShaderInSameFolder.py
Fixes an issue recognizing files as shader files on systems that have a "." in the full path. The original logic both uses the improper approach to determine a file extension and assumes that the only "." is used to deliminate the extension.
Run on the Shader Management Console on Linux (after applying a temporary fix for the python loading)
=> Fix logic for determining the file extension for shader files

Code/Editor/AnimationContext.cpp, Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp, Code/Editor/CryEdit.cpp, Code/Editor/CryEdit.h, Code/Editor/CryEditDoc.cpp, Code/Editor/EditorViewportWidget.cpp, Code/Editor/EditorViewportWidget.h, Code/Editor/MainWindow.cpp, Code/Editor/MainWindow.h, Code/Editor/Plugins/ComponentEntityEditorPlugin/ComponentEntityEditorPlugin.cpp, Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/AssetCatalogModel.cpp, Code/Editor/Resource.h, Code/Editor/TrackView/TrackViewDialog.cpp, Code/Editor/TrackView/TrackViewNodes.cpp, Code/Editor/Viewport.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.hxx
Removes more references to slices in the level editor UI.
Inspector cleanup will simplify other refactoring efforts related to prefab overrides and action manager support.
=> Slice Level UI Removal | Inspector and Asset Browser cleanup

Code/Editor/CryEdit.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTreeToTableProxyModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTreeToTableProxyModel.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetEntryChangeset.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp
Just a slight improvement to editor startup time and smoothness once its started.  
Created by using the valgrind + callgrind profiler, and then doing micro-optimizations on the resulting hot spots.
The real problem is that the actual structure / behavior of that sort filter model needs a full replacement.
For me on linux, this improved the amount of time Editor was frozen up in profile on AutomatedTesting from about 8 seconds on startup, to about 5 seconds on startup.  Not huge, but I imagine if you have a big project that might be significant percentage faster.
Just manual testing - starting editor in dev branch vs this other branch, poking around at the Asset Browser UI, making sure it behaved about the same as before but without as much impact on performance.
=> A few small improvements for the editor startup time

scripts/build/Platform/Windows/build_config.json
Adds the installer node label to the Windows `install_mono_release` build. 
Due to changes in https://github.com/o3de/o3de/pull/17623, the python venv location is now in the home path of "C:\\users\\builduser\\.o3de\\.venv" instead of the AR workspace path of "D:\\workspace\\{python_venv_path}\\.venv". This causes python path issues if the build pipeline utilizes a new instance between build steps, since the python venv runtime is not pulled again in the new instance
This change will maintain the same instance across the Windows installer pipeline to retain the venv path
Tested in a sandbox installer job: https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE-test_nightly-installer/detail/O3DE-test_nightly-installer/59/pipeline/485
=> Add installer node label to install_mono_release

Code/Editor/splashscreen_background.png
Fixes the proportions of the splash image for the Editor.
Note that the previous image had the wrong size, which meant that it was stretched to fit. The new proportions are how it was meant to look, and centered correctly so that the logo is framed.
(Note that this will be cherry-picked to the point release branch once it's approved in development)
Before:
After:
=> Fix the proportions of the Editor splashscreen for 23.10.3

Code/Editor/EditorPreferencesPageGeneral.cpp, Code/Editor/EditorPreferencesPageGeneral.h, Code/Editor/EditorViewportSettings.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/API/SettingsRegistryUtils.h, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.h, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicRequestBus.h, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicRequestHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicRequestHandler.h, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSettings.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.h, Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportSettings.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportSettings.h, Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake, Code/Framework/AzToolsFramework/Tests/Prefab/PrefabDetachPrefabAndRemoveContainerTests.cpp, Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
This change allows Prefab containers to be set as "Editor Only" which will cause their children to be exported into the runtime and CTRL+G mode but not the container itself.  A crash bug was found while fixing and experimenting with this.
It turns out that there is an instance leak as well as a blind spot in the export process in Instance.cpp which causes a crash
as dead memory is referenced.  This PR fixes this crash.
I also noticed that detach was not symmetrical with creating a prefab, that is, creating a prefeb creates the container and moves the children into the container, but the default behavior of detach does not do the opposite.
I reworked detach to do the opposite, but kept the underlying APIs and functions the same as before for backward compatibility, so all existing uses of …
=> Fixes a crash and improves detach Prefab

Gems/AWSClientAuth/Code/Tests/AWSClientAuthGemMock.h, Gems/HttpRequestor/Code/Include/HttpRequestor/HttpRequestParameters.h, Gems/HttpRequestor/Code/Include/HttpRequestor/HttpRequestorBus.h, Gems/HttpRequestor/Code/Include/HttpRequestor/HttpTextRequestParameters.h, Gems/HttpRequestor/Code/Source/HttpRequestManager.cpp, Gems/HttpRequestor/Code/Source/HttpRequestorSystemComponent.cpp, Gems/HttpRequestor/Code/Source/HttpRequestorSystemComponent.h
This PR adds additional Bus functions in the HTTP Requestor Gem to allow the user to specify the client configuration.
This enables the user to change the configuration and for example change timeouts.
This PR was tested by adding different configurations for the HTTP Requestor gem with different timeouts.
=> Add methods for client configuration in HTTP Requestor gem

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/AggregateAdapter.cpp
Fixes a crash when selecting multiple entities and trying to add a Material Component from the Mesh Component.
Verified the DPE does not crash anymore.
=> DPE | Prevent crash on multi-edit when back of the patch is not an index.

Templates/PythonToolGem/Template/Editor/Scripts/bootstrap.py
Fixes the [Python Tool Gem Template](https://github.com/o3de/o3de/tree/development/Templates/PythonToolGem) to handle bootstrap.py in non-Editor applications.
Fixes https://github.com/o3de/o3de/issues/17701
Created a new gem with template and followed repro steps in https://github.com/o3de/o3de/issues/17701
=> Add try/catch block to handle situations when the editor is not involved

Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
Fixes a _potential_ warning generated for some compilers
This warning did not occur to me nor did it in AR, (I'm on Linux Clang16) but it could on some compilers.
Compiling and running
=> Fixes a possible "Shadowed Variable" warning.

Gems/PhysX/Common/CMakeLists.txt, Templates/DefaultProject/Template/project.json, cmake/Gems.cmake
This fixes the situation where the Assets in the enabled 'PhysXCommon' gem was not being picked up by the Asset Processor as source assets. 
fixes https://github.com/o3de/o3de/issues/17700
fixes https://github.com/o3de/o3de/issues/17671 
On a new project with PhysX, PhysXCommon enabled, ran Asset Processor and confirmed the Physics Materials are processed.
=> Fix Physics Material Assets in PhysXCommon to be processed in the AssetProcessor

Gems/EditorPythonBindings/Code/Source/PythonUtility.cpp
Fixes code that can trigger warnings in some compilers introduced by this PR: https://github.com/o3de/o3de/pull/17589
=> Fix PythonBehaviorDescription function signatures from triggering warnings in some compilers

Code/Framework/AzToolsFramework/AzToolsFramework/API/PythonLoader.cpp
Fixes the following build errors:
```
n file included from /home/spham/O3DE/Projects/Test1/build/linux/o3de/Code/Framework/AzToolsFramework/CMakeFiles/AzToolsFramework.dir/Unity/unity_3_cxx.cxx:3:
/home/spham/github/o3de/Code/Framework/AzToolsFramework/AzToolsFramework/API/PythonLoader.cpp:51:18: error: unused variable 'loadResult' [-Werror,-Wunused-variable]
bool loadResult = m_embeddedLibPythonModuleHandle->Load(false, true);
^
/home/spham/github/o3de/Code/Framework/AzToolsFramework/AzToolsFramework/API/PythonLoader.cpp:125:20: error: unused variable 'parseOutcome' [-Werror,-Wunused-variable]
const auto parseOutcome = AZ::Settings::ParseConfigFile(systemFileStream, parserSettings);
^
2 errors generated.
```
Project built in release and launched the Game Launcher
=> Fix release compilation issues

Code/Editor/CryEditDoc.cpp
I can't find where SequenceObject would be registered against  CClassFactory. this is the last call to NewObject so ObjectManager is completely unused going forward.
=> feat: remove unused save logic for SequenceObject

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/AggregateAdapter.cpp
Cherry-picks https://github.com/o3de/o3de/pull/17718 for release 23.10.3
=> [Cherry-Pick] DPE | Prevent crash on multi-edit when back of the patch is not an index.

Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/PassDescriptor.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
This fixes linux first time asset processing crash in the Editor caused by dangling pointer(`PassDescriptor::m_passRequest`) during attempts to access its `m_passData` in [PassUtils::GetPassData](https://github.com/o3de/o3de/blob/c895a337424e16c207ffd3033e6cf1d66893f06c/Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassUtils.h#L48).
This crash occurs only on first time startup of the Editor when there are no assets. In this situation, when feature processors adds render passes, it creates the `RPI::PassRequest` as a local variable and creates the pass from the Request. (i.e. in the [SilhouetteFeatureProcessor](https://github.com/o3de/o3de/blob/c895a337424e16c207ffd3033e6cf1d66893f06c/Gems/Atom/Feature/Common/Code/Source/Silhouette/SilhouetteFeatureProcessor.cpp#L155-L165).  
It seems …
=> Fix linux editor first time crash

Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceDispatchRaysIndirectBuffer.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceDispatchRaysItem.h, Gems/Atom/RHI/Code/atom_rhi_public_files.cmake
This PR is part of https://github.com/o3de/sig-graphics-audio/pull/137 (original proposal including discussion in https://github.com/o3de/sig-graphics-audio/issues/120, there referred to as (part of) commit 3 in the Planned git history sub-section) and introduces `MultiDeviceDispatchRaysIndirectBuffer`.
It is important to note that this PR only introduces this resource class, but does not call it currently on either the RHI or RPI level (this will happen after all multi-device resources have been properly introduces into the code base).
=> Introduce a multi-device DispatchRaysIndirectBuffer

Gems/Atom/Tools/ShaderManagementConsole/Scripts/GenerateShaderVariantListForMaterials.py
Cherry pick for fixing the logic for determining the file extension for shader files from https://github.com/o3de/o3de/pull/17689
Run on the Shader Management Console on Linux on a system that has '.' in the current working directory
=> Cherry Pick Fix logic for determining the file extension for shader files

Gems/EditorPythonBindings/Code/Source/PythonUtility.cpp
Cherry pick for fixing missing primitive types for python bindings from https://github.com/o3de/o3de/pull/17753
Same as https://github.com/o3de/o3de/pull/17753
=> Cherry pick fix for python bindings on Linux for methods that return size_t

Code/Framework/AzFramework/AzFramework/Quality/QualityCVarGroup.cpp, Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugAuditTrail.cpp
Currently the 23.10.3 point-release branch can't be compiled on clang 17 due to compilation errors, this was already fixed at `development` thanks to the #17273 PR.
This PR cherry-picks the 93c4b7a commit from the merge of the mentioned PR into the 23.10.3 point release branch.
I compiled and ran the editor by opening a project in my local machine.
=> Cherry-pick clang 17 compiler errors fix from development

Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.hxx, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.ui
Prefabs can now be set as Editor Only in their actual prefab file (ie, by editing the prefab itself, and selecting the container).
Also fixes the UI for Editor Only mode, adds tooltip, and makes it so you cannot add components to the prefab container (it was previously supposed to be forbidden but you could still accidentally add them with copy and paste/right click menu).
It does not affect any defaults or any existing files - you must explicitly alter your prefabs to be Editor Only for this to have any effect.
The upshot though is, if you create, say, an entity, which, when activated, gets its parent and does something to it, turning this entity into a prefab can still be made to work even though its parent will be the prefab container ordinarily.
It also reduces the overall number of …
=> Prefabs themselves can be set as Editor Only.

AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/editor_test_helper.py, AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py, AutomatedTesting/Gem/PythonTests/editor/EditorScripts/EditorWorkflow_EditorCameraBeThisCameraIsClearedWhenChangingLevel.py, AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/LayerBlender_E2E_Editor.py, AutomatedTesting/Gem/PythonTests/scripting/Debugger_HappyPath_TargetMultipleEntities.py, cmake/Gems.cmake
This fixes the situation where the gem dependency check in cmake encounters a dependent gem that is tagged with a specific or minimum version in its dependeny list, i.e. [Ros2RoboticManipulationTemplate/project.json](https://github.com/o3de/o3de-extras/blob/c7b8a76003225731ba9f079ae29c5b26f6c13829/Templates/Ros2RoboticManipulationTemplate/Template/project.json#L43)
During the dependency lookup, the process checks each gem in the gem dependency list for its `gem.json` file based on a path that is cached in a property [\@GEMROOT:${gem_name}](https://github.com/o3de/o3de/blob/6cc4b1c328a16dd441b5198d44642f901e02eb36/cmake/Gems.cmake#L100). But if a gem dependency includes a version restriction like in [Ros2RoboticManipulationTemplate/project.json](https://github.com/o3de/o3de-extras/blob/c7b8 …
=> Fix Gem Dependency checking with dependent gems that include versioning

Gems/Atom/RHI/DX12/Code/Source/RHI/FrameGraphCompiler.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/FrameGraphExecuter.cpp, Gems/Atom/RHI/Metal/Code/Source/RHI/FrameGraphExecuter.cpp
This PR fixes smaller issues found while testing with `dx12` and includes
- Choosing the correct `DeviceBuffer` in `FrameGraphCompiler` (`dx12`)
- Choosing the correct `Scope` in `FrameGraphExecuter` (`dx12` & `metal`)
=> Fixes in FrameGraph* for backends

Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp, Code/Framework/AzToolsFramework/Tests/Input/QtEventToAzInputMapperTests.cpp
CHERRY-PICK from dev to point-release/23103 PR #17464
Fixes the ALT key being held down after alt-tabbing (#17464)
When tabbing out of the editor using alt tab, the editor would
not reset the alt key upon return because the key release event
would never reach it.
To fix this, code was added to the QtEventToAzInputMapper to
reset all key states when the application was deactivated
=> Cherrypick PR 17464 from development to point release

Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.cpp, Code/Framework/AzFramework/Tests/Platform/Common/Xcb/MockXcbInterface.cpp, Code/Framework/AzFramework/Tests/Platform/Common/Xcb/MockXcbInterface.h, Code/Framework/AzFramework/Tests/Platform/Common/Xcb/XcbInputDeviceMouseTests.cpp
Fix issue #14877 - mouse wheel being intepreted as x-axis movement on linux (#17424)
* Fix issue #14877 - mouse wheel being intepreted as x-axis movement on Linux
* Fixed existing tests and added a new test case
The old tests were not mocking the new function called inside xcb. I also added a new test that makes sure that this does not regress.
=> Cherry-pick pull request #17424 from dev to point-release/23103

Gems/ScriptCanvasDeveloper/Code/CMakeLists.txt, Gems/ScriptCanvasDeveloper/Code/Include/ScriptCanvasDeveloper/ScriptCanvasDeveloperComponent.h, Gems/ScriptCanvasDeveloper/Code/Source/ScriptCanvasDeveloperComponent.cpp
Potential fix for ScriptCanvasDeveloper crash (#17420)
CHERRY-PICK from 4eacb15 from development -> point-release/23103
fixes issue #15959
This fixes a potential memory stomp issue, where the size of an object in the dll that creates it does not match the size of the object in static library that contains code that uses it, causing it to modify memory in unexpected location and leading to an assert on linux during startup if the Script Canvas Developer gem (ScriptCanvasDeveloper) is active.
Signed-off-by: Nicholas Lawson <70027408+nick-l-o3de@users.noreply.github.com>
=> Cherry-pick PR17420 from dev to point-release

scripts/build/Platform/Windows/build_windows.cmd
A number of fixes to resolve issues found in: https://github.com/o3de/o3de/issues/17791
- Changes the errorlevel variable in the Windows build script to enforce expansion
- Changes Windows build errorlevel comparators to numeric
Tested in sandbox Jenkins
=> Windows build script errorlevel fixes

Code/Framework/AzCore/AzCore/IO/FileIO.h, Code/Framework/AzCore/Platform/Android/platform_android_files.cmake, Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/IO/FileIO_UnixLike.cpp, Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/IO/FileIO_WinAPI.cpp, Code/Framework/AzCore/Platform/Linux/platform_linux_files.cmake, Code/Framework/AzCore/Platform/Mac/platform_mac_files.cmake, Code/Framework/AzCore/Platform/Windows/platform_windows_files.cmake, Code/Framework/AzCore/Platform/iOS/platform_ios_files.cmake, Code/Framework/AzToolsFramework/AzToolsFramework/Asset/AssetUtils.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Asset/AssetUtils.h, Code/Tools/AssetProcessor/native/AssetManager/AssetCatalog.cpp, Code/Tools/AssetProcessor/native/AssetManager/ExcludedFolderCache.cpp, Code/Tools/AssetProcessor/native/AssetManager/FileStateCache.cpp, Code/Tools/AssetProcessor/native/AssetManager/FileStateCache.h, Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp, Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h, Code/Tools/AssetProcessor/native/tests/AssetCatalog/AssetCatalogUnitTests.cpp, Code/Tools/AssetProcessor/native/tests/FileStateCache/FileStateCacheTests.cpp, Code/Tools/AssetProcessor/native/tests/MissingDependencyScannerTests.cpp, Code/Tools/AssetProcessor/native/tests/UnitTestUtilities.cpp, Code/Tools/AssetProcessor/native/tests/UnitTestUtilities.h, Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.cpp, Code/Tools/AssetProcessor/native/tests/utilities/assetUtilsTest.cpp, Code/Tools/AssetProcessor/native/unittests/UnitTestUtils.cpp, Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp, Code/Tools/AssetProcessor/native/utilities/UuidManager.cpp, Code/Tools/AssetProcessor/native/utilities/assetUtils.cpp, Code/Tools/AssetProcessor/native/utilities/assetUtils.h
Improve ap startup on linux (#17526)
* Improves the startup time of AP on linux.
Note that this could also potentially improve it on mac and windows, as well as metafile processing in general.
Most of this change is just moving the initialization of the catalog until the file cache is warmed up and then using the file cache to fix path cases on case sensitive file systems.
The rest of it is fixing the unit tests to account for this - the mock for the file system wasn't sufficient to actually use this new code as it would do things like always answer false for "is directory".
With this change, all unit tests pass in debug on linux, with no unexpected assertions and no failures.  In addition, AP starts and idles very quickly without any long freezes during startup.
* Fixes a warning I'm not …
=> CHERRY-PICK from dev to point-release/23103 PR #17526

Gems/Atom/RHI/Code/Source/RHI/RHISystem.cpp, Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/PhysicalDevice_Windows.cpp
This PR fixes issues with device virtualization that showed when testing with `dx12`, which includes
- `dx12` returns more devices than are present in a system (including the same GPU twice
- `dx12` (and `metal`) do not store their list of physical devices but create them anew
- `dx12` might add a software rasterizer (which does not work with `Atom`) to the list of devices
This PR only takes as many GPUs from the list as is indicated by the `device-count` parameter, does not iterate over the pointers any longer (as they might be different) and does not add devices which carry the `DXGI_ADAPTER_FLAG_SOFTWARE` to the list of devices.
=> Fixes to virtual device initialization

Gems/DebugDraw/Assets/Shaders/SphereIntersection.azsl
This PR fixes the calculation of the hit position of the new sphere intersection shader introduced in #17734. The values of `ProceduralGeometryIntersectionAttributes` are supposed to be stored in object (BLAS) space, but were stored in world space, which leads to wrong shadows in raytraced reflection.
Left image: old code, right image: new code; the shadow in the reflection of the red sphere now looks more correct.
Create a small scene (image above), move the shapes around and see if the shadows look plausible.
=> Fix sphere intersection attributes not being in object space

Gems/Atom/Asset/Shader/Config/Platform/Android/shader_build_options.json
Fixes runtime shader bug on Qualcomm GPUs.
For Android, it is necessary to compile the shaders with the macro "PRE_HLSL_2021", which fixes a runtime error where StandardPBR related shaders fail to create their PSO (Pipeline State Object) in devices with Qualcomm GPUs like some Samsung phones or Meta Quest devices.
Long Story: Starting with HLSL 2021, the ternary operator: "cond ? true : false" stopped compiling for vectors and is limited to only scalar variables. HLSL 2021 introduced new keywords like "select" which function as the ternary operator for vectors. The problem is that the generated SPIRV binary for the "select" keyword causes runtime issues in Qualcomm GPUs.
SOLUTION: The macro "PRE_HLSL_2021" was instroduced in all of the shaders that call "select" with the purpose of NOT …
=> Fixes runtime shader bug on Qualcomm GPUs

Code/Tools/TestImpactFramework/Runtime/Common/Code/Source/TestRunner/Common/Run/TestImpactTestCoverageSerializer.cpp, Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/TestImpactNativeShardedInstrumentedTestRunner.cpp, Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestRunner/Native/TestImpactNativeShardedRegularTestRunner.cpp, Gems/Atom/RHI/DX12/External/AMD_D3D12MemoryAllocator/v2.0.1/dx12ma/D3D12MemAlloc.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.h
This PR fixes some build errors with Clang-17 on Windows when using a no-unity build.
The change in `Device.cpp/.h` is necessary because `AsyncUploadQueue` is forward-declared in the header file but is used as a member variable with `RHI::Ptr<AsyncUploadQueue>`, so either AsyncUploadQueue needs to be included in the header file or the destructor needs to be implemented in the cpp file. I changed it to the latter option.
Compile code with unity and no-unity cmake option.
=> Fix Clang-17 nounity compile errors on Windows

Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
This resolves a problem with timeline semaphores on devices with Vulkan <1.2.
The solution was proposed by @akioCL on the sig-graphics-audio [Discord](https://discord.com/channels/805939474655346758/816043793576886273/1228019420237135945) in a discussion with @galibzon
I only have access to devices with Vulkan versions >=1.2, so I could not actually test this.
=> Request the timeline semaphore extension for Vulkan <1.2

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPISystem.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPISystemInterface.h, Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp, Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRenderer.cpp
Shader Management Console (SMC) has error validation spam because it was loading shader with MSAA enabled and then a pass later on would try to bind a texture with MSAA count of 1 (i.e non-msaa resource). This would spam each frame. This was happening because the PreviewRender pipeline was relying on other scenes to set the correct msaa count but in the case of SMC there are no other scenes. Hence we added a check for that and broadcast the default settings before initializing the pipeline.
Tested Editor, Material Editor, Material Canvas, Shader Management Console on PC
=> Fix SMC validation error spam related to MSAA count

AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py, Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
The `interface` name is a reserved keyword for some compilers, renamed it to avoid compile errors
=> Renamed variable from interface to avoid compile error

Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserBus.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserComponent.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTreeToTableProxyModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.h
Fixes crash when full refreshing AssetProcessor
Also fixes a crash when deleting elements out of the file system
Also fixes a crash when clicking on thumbnails while they are generating.
All three of the cases above were easy to repro 100%
1. Click the Rescan All button in AP -> crash
2. Duplicate any folder in the asset tree using Windows Explorer or Linux or whatever.  Then delete it.  Crash
3. Click in AB on "Editor" -> "Icons" -> Crash.
Testing all three of the above cases to ensure no crash anymore.
Testing duplicating/adding new script canvas assets to ensure they appear.
Deleting assets and ensuring they disappear
Clicking around in the AB while icons are generating
Doing the same in "list view" / search result mode.
=> Fixes crash when full refreshing AssetProcessor

Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Graph.cpp
Fixes a nullptr crash when running the ScriptCanvas upgrade tool.
Locally on PC by running the ScriptCanvas upgrade tool
=> Fix for ScriptCanvas Upgrade Tool nullptr crash

Gems/Atom/RHI/Vulkan/Code/CMakeLists.txt, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
This PR disables timeline semaphores for Quest
devices only. Otherwise the runtime crashes.
This was accomplished by leveraging the fact that
the user must flag the Android project as target for Meta Quest device. The CMake variable `ANDROID_USE_OCULUS_OPENXR` is set to true and this fix leverages this CMake variable to define the new C++ macro
named DISABLE_TIMELINE_SEMAPHORES.
Tested on Quest Pro and Quest 3. Without this fix both of them crash.
=> Fixes crash on Quest devices

Code/Editor/TrackView/TrackViewAnimNode.cpp, Code/Editor/TrackView/TrackViewAnimNode.h
ITransformDelegate is used with CBaseObject, we're not currently registering this object against any CBaseObject so we can safely drop this interface.
=> feat: remove ITransformDelegate from CTrackViewAnimNode

Code/Tools/ProjectManager/Source/ProjectUtils.cpp, Code/Tools/ProjectManager/Source/ProjectUtils.h, Code/Tools/ProjectManager/Source/ProjectsScreen.cpp, Code/Tools/ProjectManager/Source/UpdateProjectCtrl.cpp
Make the "Open existing project" dialog on the project manager target a "project.json" file instead of any directory. 
This change will prevent user mistakes after cloning repository for an O3DE project, this way we know for sure when we are in the right directory. (I recently [tried out most of the O3DE samples out there](https://github.com/o3de/o3de.org/issues/2549), and as the project is sometimes in a subdirectory I made the mistake a few times)
Also used this change to make a small refacto so that "project.json" and "engine.json" used in the project manager project use the same constant.
Tested locally by adding a project using my change (and checked the values via debugger)
=> new: Project manager add project dialog to target project.json instead of any directory

Code/Framework/AzFramework/AzFramework/Asset/AssetCatalog.cpp, Code/Framework/AzFramework/AzFramework/Asset/AssetRegistry.h, Code/Tools/AssetProcessor/native/AssetManager/AssetCatalog.cpp
Adding a warning whenever a legacy asset id is used. This will help developers track which assets are old and need to be updated to the modern asset id.
Allows developers to catch and fix old assets before the legacy asset table is removed entirely.
Deprecation GHI: https://github.com/o3de/o3de/issues/17861
=> Print Warning When Using Legacy Asset IDs

Code/Tools/AssetProcessor/Platform/Linux/AssetProcessor_Traits_Linux.h, Code/Tools/AssetProcessor/Platform/Mac/AssetProcessor_Traits_Mac.h, Code/Tools/AssetProcessor/Platform/Windows/AssetProcessor_Traits_Windows.h, Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp, Code/Tools/AssetProcessor/native/assetprocessor.h, Code/Tools/AssetProcessor/native/resourcecompiler/rcjob.cpp
Moved the `AP_MAX_PATH_LEN` define into the platform-specific files. Mostly because our linux CI has longer paths than 260 chars, and that limitation shouldn't be a problem on linux, even for thirdparty - libraries
Compile and build assets on windows and linux. I have no opportunity to test this on mac.
=> Set different max path lenghts for the different platforms

Gems/Atom/RHI/Vulkan/Code/Source/RHI/Queue.cpp
During the last re-write of PR #17761, this change in the class hierarchy was not correctly reflected in this line of code, this currently returns now a `nullptr` instead of a pointer to the `TimelineSemaphore`.
=> Fix waitSemaphore dynamic cast

Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Datum.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Data/Data.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Data/DataTypeUtils.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/AbstractCodeModel.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/ExtractProperty.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/FunctionCallNode.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/FunctionCallNode.h
Fixes an error where a ScriptCanvas "ExtractProperty" node will fail to process on linux, if one of the properties is a "int64_t" type.  On Linux, that type fails the "IsNumber" check in ScriptCanvas as linux treats "int64_t" as a "long", instead of "AZ:s64".  
Also adds some debugging and renaming that came as a result of tracking this thing down.
Building assets for Linux, PC, Android, and iOS
=> Fix to ScriptCanvas' ExtractProperty failing on Linux when a property is of type int64_t

Code/Editor/TrackView/TrackViewNodes.cpp, Code/Editor/TrackView/TrackViewSequence.cpp
this ends up resolving the initial crash but, I can occasional get this into a state where SubmitPendingNotifcations end up in a state where this assert is hit in CTrackViewSequence. seems like the force call when you delete a node will set m_selectionRecursionLevel = 1 so when this is called the assert will get hit.  
follow the steps in the listed PR: 
ref: https://github.com/o3de/o3de/issues/15048
=> bugfix: partial fix crash when renaming a deleted node (GHI-15048)

Code/Editor/TrackView/TrackViewAnimNode.cpp, Code/Legacy/CryCommon/IMovieSystem.cpp, Code/Legacy/CryCommon/IMovieSystem.h, Gems/Maestro/Code/Source/Cinematics/AnimAZEntityNode.cpp, Gems/Maestro/Code/Source/Cinematics/AnimAZEntityNode.h, Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.cpp, Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.h, Gems/Maestro/Code/Source/Cinematics/AnimNode.h
when adding entity to trackview they can appear rotated. looks like this was a regression that I introduced with https://github.com/o3de/o3de/issues/9326
look at the referenced ticket
ref: https://github.com/o3de/o3de/issues/14978
=> bugfix: resolve rotated entities when adding them to trackview (GHI-14978)

Code/Framework/AzQtComponents/AzQtComponents/Components/DockTabBar.cpp
DockTabBar implements its own version of tabText that implements ellipses for the text. for the action menu we probably don't want to do any kind of ellipses. 
follow referenced ticket.
ref: https://github.com/o3de/o3de/issues/10817
=> bugfix: fix ellipsis text for track view close key/undock key (GHI-10817)

Code/Editor/IEditorImpl.cpp, Code/Editor/Include/IObjectManager.h, Code/Editor/Objects/ObjectManager.cpp, Code/Editor/Objects/ObjectManager.h
AxisHelperHitRadius is never referenced in the code, this cvar should be easily removed.
=> feat: remove unused Viewport cvar from ObjectManager

Code/Tools/AssetProcessor/native/ui/BuilderInfoMetricsModel.cpp
Changes the formatting of the Asset Processor metrics column from (e.g):
"123ms, 12s, 34m, 2h, 1d"
to
"1d 2h 23m 12s 123ms"
This makes the output a bit more readable (larger -> smaller metrics) and is a bit more common/expected in terms of duration output.
Locally, running windows version of Asset Processor.
=> Reformat of the Asset Processor Metrics column

Gems/Atom/RHI/DX12/Code/Source/RHI/Scope.cpp
This PR fixes the following compile error on Windows with Clang-17:
```
.../o3de/Gems/Atom/RHI/DX12/Code/Source/RHI/Scope.cpp:103:17: error:
integer value 2147483647 is outside the valid range of values [0, 33554431]
for the enumeration type 'D3D12_RESOURCE_STATES' [-Wenum-constexpr-conversion]
103 |                 (D3D12_RESOURCE_STATES)DX12_RESOURCE_STATE_VALID_API_MASK;
|                 ^
```
The problem is that the value of `DX12_RESOURCE_STATE_VALID_API_MASK` is calculated as `~0x80000000`, which is too large for the enum since the max allowes size is basically all defined enum values or-ed together, which is `0x1FFFFFF` (33554431). The size of the `D3D12_RESOURCE_STATES` enum cannot be specified explicitly since it is defined in the system header `d3d12.h`.
Other solutions to fix …
=> Fix Clang-17 compile error about enum-constexpr-conversion on Windows

Code/Framework/AzCore/AzCore/Math/PackedVector2.h, Code/Framework/AzCore/AzCore/Math/PackedVector4.h, Code/Framework/AzCore/AzCore/azcore_files.cmake, Code/Framework/AzCore/Tests/Math/PackedVectorTest.cpp, Code/Framework/AzCore/Tests/azcoretests_files.cmake, scripts/commit_validation/commit_validation/pal_allowedlist.txt
introducing a packed variants for vector2/4 seems to make a lot of sense. its not too uncommon to have a packed float4 stream or some variants or a 2/2. 
probably should for the struct to be packed because  because depending on the system padding might be inserted before or after or between member variables. for 64 bit systems its multiples of 4 so 3 uint16 with have an extra uint16 added at the end for alignment I believe. 
run unit test included
=> feat: add packed vector variants for 2/4 with unit tests

Code/Framework/AzToolsFramework/AzToolsFramework/UI/LegacyFramework/Core/EditorFrameworkApplication.cpp, Code/Tools/LuaIDE/Source/LUA/LUAEditorSettingsDialog.cpp, Code/Tools/LuaIDE/Source/LUA/LUAEditorSettingsDialog.hxx, Code/Tools/LuaIDE/Source/LUA/LUAEditorSettingsDialog.ui
This is handling https://github.com/o3de/o3de/issues/17840 . This could be also only Linux related but I am not sure. I only tested this issue on Linux.
Compiled and run on my local Ubuntu 22.04 computer.
This PR is kind of a suggestion. As described in the issue, the fix I am providing is not using the 
QStandardPaths::writableLocation(QStandardPaths::AppDataLocation)
function to retrieve the load/save folder the the settings. Instead using the projects user folder. So its not a real fix neither to understand why this strange behavior happens. But I thought having the settings files in the user folder is better so I leave it for now as a fix.
I also changed the locations of the 3 buttons for close, save and save & close.
From this:
to this:
If the fix and/or the UI change isn't the …
=> [Lua Editor] Fix Lua Editor not handling load and save of the settings dialog

Code/Tools/LuaIDE/Source/LUA/LUAEditorBreakpointWidget.cpp, Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.cpp, Code/Tools/LuaIDE/Source/LUA/LUAEditorStyleMessages.cpp, Code/Tools/LuaIDE/Source/LUA/LUAEditorStyleMessages.h, Code/Tools/LuaIDE/Source/LUA/LUAEditorSyntaxHighlighter.cpp, Code/Tools/LuaIDE/Source/LUA/LUAEditorSyntaxHighlighter.hxx, Code/Tools/LuaIDE/Source/LUA/LUAEditorView.cpp
Match VSCode "DarkModern" theme in the Lua Editor. Fix some UI update logic and add simple regex on top of existing system to perform needed checks. The new highlight options are exposed as user setting.
Before:
After:
On a local build against multiple lua scripts found online
=> Improve lua editor syntax highlighting and update style

Gems/Atom/Feature/Common/Assets/Materials/Pipelines/MultiView/MultiViewForwardPassVertexAndPixel.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PostProcessing/Tonemap.azsli, Gems/Atom/Feature/Common/Assets/Shaders/SkyBox/SkyBox.azsl
Fixing filmic tonemapping function and created aces tonemapping as a separate function to differentiate the two
Filmic tonemapping now matches the implementation here: https://github.com/dmnsgn/glsl-tone-map/blob/main/filmic.glsl
And looks much less washed out in testing than the previous implementation
=> Fixing filmic tonemapping function

Gems/Atom/Feature/Common/Assets/Shaders/Materials/Eye/Eye_PixelGeometryData.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/Eye/Eye_PixelGeometryEval.azsli
Eyes didn't render at all on Quest 3. Now they do (might be something wrong with specular on Quest 3/Android though, will investigate that in a follow up PR)
=> Fixed eye shader to work natively on Quest 3

Code/Editor/GameEngine.cpp, Code/Editor/IEditorImpl.cpp
pretty simple to just start remove references to sendEvent for ObjectManager these events are only consumed by BaseObject but we don't spawn any BaseObjects in the engine.
=> feat: remove usage of SendEvent for ObjectManager

Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicInterface.h
Modify PrefabPublicInterface to allow instantiation of prefabs with rotation.
This PR allows to set the initial transform of the prefab during InstantiatePrefab from PrefabPublicInterface.
It was cherry-picked and used against 2310.2 project.
=> Allow to instantiate prefab with rotation.

Gems/RemoteTools/Code/CMakeLists.txt, Gems/RemoteTools/Code/Source/RemoteToolsSystemComponent.cpp, Gems/RemoteTools/Code/Tests/RemoteToolsTest.cpp
Fix remote tool message broken by the last commit on my PR #17879. 
The change at the origin of the defect was made to allow the unit test to go through, but I did not re-test it after and it was merged as is. This fixes the remote tool message, add proper unit test for message serialization, and I also removed changes made on "last target" as it is used internally to track the desired target (changing it can make the lua editor need to double click to connect on said target).
Local build against attached script canvas debug and lua script debug
=> hotfix: Remote tool send remote message fix and add proper unit test

Code/Tools/LuaIDE/Source/LUA/LUAEditorStyleMessages.cpp, Code/Tools/LuaIDE/Source/LUA/LUAEditorStyleMessages.h
This PR introduces a new property to the LUA Editor's settings dialog, allowing users to toggle anti-aliased font rendering on or off. This feature enables the use of non-anti-aliased fonts, which can produce better results for certain font types.
Tested on my local computer Ubuntu 22.04 LTS.
Here some pictures. Here is anti-aliasing enabled:
Here is anti-aliasing disabled:
With the PR https://github.com/o3de/o3de/pull/17894 a new issue was introduced. The issue is that when the Editor opens a LUA script file the font retrieved by the changed method GetFont() wasn't correctly initialized. To make the m_font update directly after de-serialization the AZ::SerializeContext::IEventHandler was used.
Best regards
Yaakuro
=> [LUA Editor] Allow none anti-aliased fonts.

Gems/Atom/RHI/Code/Source/RHI/FrameGraph.cpp
Turn the ErrorOnce into WarnOnce, because this situation can happen in our pipeline legitimately, and our CI doesn't like errors, but tolerates warnings.
=> change the error about unused scope attachments to a warning

Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserBus.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserComponent.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTreeToTableProxyModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.h
This is a cherrypick of an already accepted fix that went into the stabilization branch for the point release/
What this change essentially does is make it so that when the AB gets told to do a full refresh it dumps its data and then doesn't generate any incremental "add / remove / data change" events until its refreshed its entire data.  This also makes child models do the same thing.  The crashes were caused by sending out those messages during full refresh when old data had already been deleted and new data was being filled out, or, assuming that its okay to invoke code on objects partially destructed.
* Fixes crash when full refreshing AssetProcessor (#17869)
* Also fixes a crash when deleting elements out of the file system 
* Also fixes a crash when clicking on thumbnails while they …
=> Cherrypick from point-release to dev - crash fix es

Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceDrawItem.h, Gems/Atom/RHI/Code/Include/Atom/RHI/ScopeProducerFunction.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Buffer/BufferSystemInterface.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/CopyPass.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/RenderPass.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPIUtils.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/CopyPassData.h, Gems/Atom/RPI/Code/Source/RPI.Public/Buffer/BufferSystem.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/AttachmentReadback.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/CopyPass.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/RPIUtils.cpp, Gems/Atom/RPI/Code/Source/RPI.Reflect/Pass/PassData.cpp
This PR enhances the `CopyPass` to allow for copy operations between resources on different devices.
As current APIs do not directly support copy operations between different devices (even virtual ones), this PR implements this functionality by going through CPU memory via a staging buffer.
For that, we also introduce a new `CommonBufferPoolType::Staging` to allow for the creation of the staging buffers necessary for the copy operations.
A CopyPass receives as input an `Input` slot as well as an `Output` slot from previous passes, if these passes reside on different devices or devices other than the default device, `SourceDeviceIndex` and `DestinationDeviceIndex` have to specified accordingly.
This PR consists of 4 commits, which are necessary, but the first two (TimelineSemaphores and …
=> Multi device copy pass and fixes

Code/Framework/AzFramework/AzFramework/Asset/AssetCatalog.cpp
Removing 2 of 3 legacy asset id warnings.  When an asset is reprocessed, asset processor triggers a OnCatalogAssetChanged event. [It triggers the event for both the normal asset id, and the legacy asset id equivalent](https://github.com/o3de/o3de/blob/8e66aced697f18e82afeb2cadb7974537202f73e/Code/Framework/AzFramework/AzFramework/Asset/AssetCatalog.cpp#L891-L911) even if the legacy asset id isn't ultimately used.
The legacy asset warning still exists, but only inside the [AssetProcessor's GetProductAssetInfo()](https://github.com/o3de/o3de/blob/development/Code/Tools/AssetProcessor/native/AssetManager/AssetCatalog.cpp#L1715-L1728
); this appears to only be called when a legacy asset is actually being processed.
1. Build assets from scratch and see no false warnings about legacy asset ids …
=> Fix False Reports of Using Legacy Assets 

engine.json
Bumps the engine version to `2.3.0` for stabilization/2409
Tested on Jenkins
=> Update engine.json for 24.09

Code/Framework/AzFramework/AzFramework/Asset/AssetCatalog.cpp
Removing 2 of 3 legacy asset id warnings. When an asset is reprocessed, asset processor triggers a OnCatalogAssetChanged event. [It triggers the event for both the normal asset id, and the legacy asset id equivalent](https://github.com/o3de/o3de/blob/8e66aced697f18e82afeb2cadb7974537202f73e/Code/Framework/AzFramework/AzFramework/Asset/AssetCatalog.cpp#L891-L911) even if the legacy asset id isn't ultimately used.
The legacy asset warning still exists, but only inside the [AssetProcessor's GetProductAssetInfo()](https://github.com/o3de/o3de/blob/development/Code/Tools/AssetProcessor/native/AssetManager/AssetCatalog.cpp#L1715-L1728); this appears to only be called when a legacy asset is actually being processed.
How was this PR tested?
Build assets from scratch and see no false warnings …
=> Fix False Reports of Using Legacy Assets

Gems/Atom/Asset/ImageProcessingAtom/Code/Include/Atom/ImageProcessing/ImageProcessingDefines.h
It enables PGM in Atom Image Builder. PGM is very simple grayscale format, that is useful with integration with some other software.
By loading the ocuppancy grid map created by [Navigation2](https://github.com/ros-navigation/navigation2) .
=> Support PGM image format in ImageProcessingAtom.

Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp, Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h, Code/Tools/AssetProcessor/native/ui/MainWindow.cpp, Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
Display information as AssetProcessor (AP) analyzes assets. How many assets are new files, are outdated, have altered dependencies, or have new builders
1. a. Ran AP from scratch using no-cache folder: the normal "analyzing jobs remaining" shows countdown of all assets. Initial scanner pass is nearly instant... all assets are "Unregistered/new files".
b. Restarted AP with Fast Scan enabled, and disabled. See that scanner file information is displayed during analysis mode, and is also printed to console after scan is complete.
2. Profiled analysis mode to ensure statistical tracking did not affect processing time.
=> AssetProcessor Analysis Stats 

Code/Editor/AnimationContext.cpp, Code/Editor/EditorViewportWidget.cpp, Code/Editor/EditorViewportWidget.h, Code/Editor/Include/HitContext.h, Code/Editor/Objects/EntityObject.cpp, Code/Editor/Objects/EntityObject.h, Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp, Code/Editor/ViewManager.cpp, Code/Editor/ViewManager.h, Code/Editor/ViewPane.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/API/ComponentEntityObjectBus.h, Code/Legacy/CryCommon/IMovieSystem.h, Gems/Maestro/Code/Source/Cinematics/Movie.cpp, Gems/Maestro/Code/Source/Cinematics/Movie.h, Gems/Maestro/Code/Source/Components/EditorSequenceComponent.cpp
I can't find where ComponentEntityEditorRequests gets bound to, looks like this EBus should be removed at some point. I was going to start with removing GetSandboxObject and just remove this call. also helps that CEntityObject constructor is never called.
=> feat: remove unused call GetSandboxObject

Gems/NvCloth/Code/Source/Components/ClothComponentMesh/ClothComponentMesh.cpp
Fix issue https://github.com/o3de/o3de/issues/16937
Cloth would crash on linux whenever simulated.  I got a 100% repro rate just by choosing the plane asset and having it "simulate in editor".
Changing the code in the manner in the PR causes it to have a 0% repro rate for me and the cloth simulates smoothly in the editor.
I don't fully understand why though, since I am not familiar with Atom Packed vectors v AZ:: Vectors.   Its my intuition that since the buffer being written to IS an atom buffer, it should be treated as an atom packed vector4 rather than an AZ::Vector4.
Just reproing the error 100% before the change, and 0% after.
=> Fix a physx cloth sim crash on linux

Gems/Atom/Feature/Common/Code/Source/Shadows/ProjectedShadowFeatureProcessor.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RasterPass.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/View.cpp
Added some guards that prevent crashes
that may occur under some custom render pipeline
configurations.
Custom pipelines don't crash anymore and the default main pipeline works well. Also tested ASV samples.
=> Added some guards that prevent crashes

Code/Editor/TrackView/TVCustomizeTrackColorsDlg.cpp, Code/Editor/TrackView/TrackViewAnimNode.cpp, Code/Editor/TrackView/TrackViewAnimNode.h, Code/Editor/TrackView/TrackViewNodes.cpp, Code/Legacy/CryCommon/Maestro/Types/AnimNodeType.h, Code/Legacy/CryCommon/Maestro/Types/AnimParamType.h, Gems/Maestro/Code/Source/Cinematics/Movie.cpp, Gems/Maestro/Code/Source/Cinematics/SceneNode.cpp
removed the cry legacy camera. I can't see a way to create this type of node in the editor. I don't think there is currently a way to use this node. shouldn't hurt to remove all the code associated with the legacy camera.
=> feat: remove legacy cry camera from trackview

Gems/ScriptCanvas/Code/Editor/Framework/ScriptCanvasReporter.h, Gems/ScriptCanvas/Code/Editor/Framework/ScriptCanvasReporter.inl, Gems/ScriptCanvas/Code/Editor/SystemComponent.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LiveWindowSession/LiveLoggingDataAggregator.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindowSession.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindowTreeItems.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindowTreeItems.h, Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/ExecutionNotificationsBus.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/ExecutionNotificationsBus.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Debugger.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Debugger.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/ExecutionBus.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/ExecutionStateHandler.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/ExecutionStateHandler.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/Interpreted/ExecutionInterpretedDebugAPI.cpp
Work on #9192, #2583, #17643, #10795. Script canvas logger can now show graph names and entity names. Code has been mostly restored to the Lumberyard's state.
GraphInfo class has been moved back to its old state so that it can be serialized (only used by the debugger to send remote messages, make no sense to hold a ptr to execution state there)
There are two things which still needs to be done to have all of the functionnalities back:
- Fix the focus on double click in log entry (broken by #6394 and for now I'm unsure if there is an alternative already in the engine to get a NodeId from its assetNodeId)
- Fill the entities tab with entities spawned and placed in the scene
https://github.com/o3de/o3de/assets/19243508/88626984-d114-49bc-883f-871cc0de1057
Locally against the newspaper sample …
=> Script canvas logger can now identify graph and entity names

Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTreeToTableProxyModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTreeToTableProxyModel.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.h
Fixes the problem caused by storing the complete tree view of the Asset Browser at launch time. Now only creates the table when a search is started.
Tested on various data sets.
=> New Tree to Table proxy that works at the end of the proxy chain

Gems/NvCloth/Code/Source/Components/ClothComponentMesh/ClothComponentMesh.cpp
Cherrypicks a fix that was commited to stabilization/2409 into development.
Fixes a physx-cloth sim crash on linux.
Same as the original PR.  See https://github.com/o3de/o3de/pull/17971
=> Cherrypick - Fix physx cloth sim crash on linux from stabilization

Gems/Atom/Feature/Common/Code/Include/Atom/Feature/PostProcess/DepthOfField/DepthOfFieldParams.inl, Gems/Atom/Feature/Common/Code/Source/PostProcess/DepthOfField/DepthOfFieldSettings.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/PostProcess/DepthOfField/DepthOfFieldComponentConfig.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/DepthOfField/EditorDepthOfFieldComponent.cpp
Implements #5660. Auto focus can now be set to focus on a specific entity.
[Screencast from 05-27-2024 02:35:40 PM.webm](https://github.com/o3de/o3de/assets/32801410/864ecf51-f2dd-4a60-8f17-ae1e02974f44)
Tested manually.
=> Add entity focus for Depth Of Field component

Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/SliderCombo.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/SliderCombo.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyDoubleSliderCtrl.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyDoubleSliderCtrl.hxx, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals_Impl.h
Also adds a new function to the DPE to allow for handlers to clean up any internal state they have before new attributes are set.  Sliders are the only ones using this new function, but if we find controls that have internal state that causes problems like this we can update them to function correctly.
Also adds an assert to check for the case where the widgets being used by the DPE are sending signals while being recycled and cleared.
The slider was the only one I found that caused that assert, but the assert is also handled and continues without a crash if it hits, so it should be safer and less crashy even when compiled in profile mode.
The root cause of this problem is documented in the issue it fixes, which is https://github.com/o3de/o3de/issues/16947 (Issue #16947)
I did try several …
=> Fixes a refresh issue with sliders in the DPE

Tools/LyTestTools/ly_test_tools/cli/codeowners_hint.py, Tools/LyTestTools/ly_test_tools/o3de/asset_processor.py
When a python testcase fails, and the codeowners are not set up properly, the test fail message will contain python - exceptions and a stack trace caused by the LyTestTool, which are unrelated to any exceptions or stack traces caused by the actual failure.
Run a failing test-case and review the test - output.
=> fix python exceptions raised when a test case fails

Gems/Atom/RHI/Code/Include/Atom/RHI/RayTracingBufferPools.h, Gems/Atom/RHI/Code/Source/RHI/RayTracingBufferPools.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingBlas.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingBlas.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingBufferPools.h
(Reopened PR from #18009 because DCO got stuck and did not report a status).
This PR fixes validation warnings for DX12 and Vulkan due the wrong `BufferBindFlags` being used for initializing the staging buffers which are used to upload AABB data for building BLASes of procedural geometry.
The DX12 validation error was:
> ERROR: ID3D12CommandList::CopyBufferRegion: Resource state (0x400000: D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE) of resource (0x000002750024F6A0:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a destination buffer.  Expected State Bits (all): 0x400: D3D12_RESOURCE_STATE_COPY_DEST, Actual State: 0x400000: D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE, Missing State: 0x400: D3D12_RESOURCE_STATE_COPY_DEST. [ EXECUTION ERROR #538: …
=> Fix validation warnings due to incorrect buffer bind flags for the AABB staging buffer when building a BLAS with procedural geometry

python/get_python.sh, python/python.sh
Enabling configuring and building o3de on windows with git bash. Previously we cannot configuring o3de on windows under git bash since immediately `python.sh` will assume we are under Unix environment. This causes failing of setup an python virtual environment. This is important to me because I use git bash on windows as daily drive. The fix to this is also fairly simple.
Locally tested.
=> Enabling get_python.sh to work on windows git bash.

Gems/Atom/Feature/Common/Assets/Passes/DepthExponentiation.pass, Gems/Atom/Feature/Common/Assets/Passes/EsmShadowmaps.pass, Gems/Atom/Feature/Common/Assets/Passes/ShadowParent.pass, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/ESM.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/ProjectedShadow.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/Shadow.azsli, Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/CoreLights/ViewSrg.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Shadow/DepthExponentiation.azsl, Gems/Atom/Feature/Common/Assets/Shaders/Shadow/KawaseShadowBlur.azsl, Gems/Atom/Feature/Common/Code/Source/CoreLights/EsmShadowmapsPass.cpp, Gems/Atom/Feature/Common/Code/Source/CoreLights/EsmShadowmapsPass.h, Gems/Atom/Feature/Common/Code/Source/Shadows/ProjectedShadowFeatureProcessor.cpp, Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/Math.azsli, Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorAreaLightComponent.cpp
1. Corrects the `PerspectiveDepthToLinear()` formula and it related parameters. [Ref plot](https://www.desmos.com/calculator/tx9mz0qwzb)
2. This MR corrects the implementation of the **Exponential Shadow Map** for projected light. Based on the formula proposed in the [orignal paper](https://jankautz.com/publications/esm_gi08.pdf).
3. Convert the ESM attachment images to`R32_FlOAT` because `R16_FLOAT` will easily overflow. 
The current  `PerspectiveDepthToLinear()` formula in o3de is wrong, as it plots the curve of `z_1` in https://www.desmos.com/calculator/tx9mz0qwzb. After the correction I also found the ESM implementation in the Atom is also incorrect as it is storing the `linearDepth` as opposed to `exponentiation` in the `DepthExponentiation.pass`. 
With the correction of …
=> Fix ESM Shadow and LinearDepth for Projected light shadow.

Gems/Atom/RHI/Code/Include/Atom/RHI/RayTracingBufferPools.h, Gems/Atom/RHI/Code/Source/RHI/RayTracingBufferPools.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingBlas.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingBlas.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingBufferPools.h
This PR cherrypicks #18012 from development to stabilization.
Same as the original PR
=> Cherry-pick: Fix validation warnings due to incorrect buffer bind flags for the AABB staging buffer when building a BLAS with procedural geometry

Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingIntersectionAttributes.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingClosestHitProcedural.azsl, Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingClosestHitProcedural.shader, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.cpp, Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/DeviceFeatures.h, Gems/Atom/RHI/Code/Include/Atom/RHI/RHIUtils.h, Gems/Atom/RHI/Code/Source/RHI/RHIUtils.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/Device.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp, Gems/DebugDraw/Assets/Shaders/ObbIntersection.azsl, Gems/DebugDraw/Assets/Shaders/ObbIntersection.shader, Gems/DebugDraw/Assets/Shaders/SphereIntersection.azsl, Gems/DebugDraw/Assets/Shaders/SphereIntersection.shader, Gems/DebugDraw/Code/Source/DebugDrawSystemComponent.cpp
This PR fixes a problem with devices which support raytracing but do not support float16 by adding a fallback implementation for the `ProceduralGeometryIntersectionAttributes` struct with getters and setters which uses octahedron-encoding and quantization to store normals and tangents instead of half-precision floating point.
Test both version on Windows with DX12 and Vulkan by changing the return value of `GetDefaultSupervariantNameWithNoFloat16Fallback()`, while introducing some errors into the code in `RayTracingIntersectionAttributes.azsli` to visually verify that both code paths (with and without `NO_FLOAT_16` macro are taken) are taken. When using the correct code, both versions are visually indistinguishable, only a diff image shows some differences between the two "compression" …
=> Add fallback implementation for the ProceduralGeometryIntersectionAttributes struct if float16 is not supported by the RHI

Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
This PR adds a function, which set the ray tracing material of  a procedural geometry instance, to `RayTracingFeatureProcessor`, which was omitted when the other procedural geometry functions were introduced in #17734. The same function for triangle geometry already exists and is called `SetMeshMaterials`.
Manual test with one of our internal Gems (the DebugDraw gem does not use this function since the debug shapes are always re-created when the color changes).
=> Add missing "SetProceduralGeometryMaterial" method to RayTracingFeatureProcessor

Code/Framework/AzFramework/AzFramework/Visibility/OcclusionBus.cpp, Code/Framework/AzFramework/AzFramework/Visibility/OcclusionBus.h, Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
Added functions to the occlusion request bus interface for making volume to volume queries.
These functions can be implemented by an occlusion culling system to perform visibility tests between shapes and entities.
Compiled code. Launch editor. Separate testing in multiplayer sample.
=> Extended occlusion request bus interface with functions for volume to volume queries

Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/SliderCombo.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/SliderCombo.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyDoubleSliderCtrl.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyDoubleSliderCtrl.hxx, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals_Impl.h
This cherrypicks https://github.com/o3de/o3de/pull/18003 to dev from stab.
* Fixes a refresh issue with sliders in the DPE
Also adds a new function to the DPE to allow for handlers to clean up any internal state they have before new attributes are set.  Sliders are the only ones using this new function, but if we find controls that have internal state that causes problems like this we can update them to function correctly.
Also adds an assert to check for the case where the widgets being used by the DPE are sending signals while being recycled and cleared.
The slider was the only one I found that caused that assert, but the assert is also handled and continues without a crash if it hits, so it should be safer and less crashy even when compiled in profile mode.
The root cause of this …
=> Cherrypick bugfix from stab to dev - Fixes a refresh issue with sliders in the DPE (#18003)

Code/Tools/ProjectManager/Source/ProjectInfo.h, Code/Tools/ProjectManager/Source/ProjectUtils.cpp, Code/Tools/ProjectManager/Source/PythonBindings.cpp
This PR is a bugfix for https://github.com/o3de/o3de/issues/17988.
Changes ensure that if the project being deleted also contains a folder of matching project name in the O3DE/Restricted folder, the contents of that folder are also properly deleted.
Testing was performed manually using the ProjectManager in the Visual Studio debugger. I confirmed that upon project deletion, the project info correctly indicates the restricted folder, and checks for that folder's existence, and deletes the folder accordingly.
=> Ensure Project Manager properly deletes restricted project folder when needed

Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingIntersectionAttributes.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingClosestHitProcedural.azsl, Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingClosestHitProcedural.shader, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.cpp, Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/DeviceFeatures.h, Gems/Atom/RHI/Code/Include/Atom/RHI/RHIUtils.h, Gems/Atom/RHI/Code/Source/RHI/RHIUtils.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/Device.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp, Gems/DebugDraw/Assets/Shaders/ObbIntersection.azsl, Gems/DebugDraw/Assets/Shaders/ObbIntersection.shader, Gems/DebugDraw/Assets/Shaders/SphereIntersection.azsl, Gems/DebugDraw/Assets/Shaders/SphereIntersection.shader, Gems/DebugDraw/Code/Source/DebugDrawSystemComponent.cpp
This PR cherry-picks PR #18036 from stabilization to development.
Same as in the original PR
=> Cherry-pick to development: Add fallback implementation for the ProceduralGeometryIntersectionAttributes struct if float16 is not supported by the RHI

Code/Tools/ProjectManager/Source/ProjectInfo.h, Code/Tools/ProjectManager/Source/ProjectUtils.cpp, Code/Tools/ProjectManager/Source/PythonBindings.cpp
This PR merges changes from https://github.com/o3de/o3de/pull/18037, which fixes an issue where restricted project folders were not deleted upon project deletion.
=> Merge changes for project manager restricted project folder deletion

Docker/entrypoint.sh
Fixes an issue with permissions in the docker container for the installed O3DE under `/opt/O3DE`
Even though a default o3de user is created with the following
```
RUN addgroup --gid 1000 "$O3DE_USER" \
&& adduser --gid 1000 --gecos "" --disabled-password "$O3DE_USER" \
&& usermod -a -G sudo $O3DE_USER \
&& echo "$O3DE_USER ALL=(ALL:ALL) NOPASSWD: ALL" | tee /etc/sudoers.d/$O3DE_USER
```
When the entry script maps the `o3de` user to the input `$GID`:
```
usermod -u "$UID" "$O3DE_USER" 2>/dev/null && {
groupmod -g "$GID" "$O3DE_USER" 2>/dev/null ||
usermod -a -G "$GID" "$O3DE_USER"
}
```
The permissions originally set for `/opt/O3DE` does not get properly matched, resulting in file permission issues when `entrypoint/sh` is bootstrapped.
=> Fix permission issues in docker container for the installed o3de

Code/Framework/AzFramework/AzFramework/Input/Devices/Mouse/InputDeviceMouse.cpp, Code/Framework/AzFramework/AzFramework/Input/Devices/Mouse/InputDeviceMouse.h, Code/Framework/AzFramework/AzFramework/Input/System/InputSystemComponent.cpp, Code/Framework/AzFramework/AzFramework/Input/System/InputSystemComponent.h, Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.cpp, Code/Framework/AzFramework/Platform/Windows/AzFramework/Input/Devices/Mouse/InputDeviceMouse_Windows.cpp
This PR allows setting a registry key "O3DE/InputSystem/Mouse/CaptureMouseCursor" to disable mouse capture.
It is useful in two scenarios:
- during a debugging session, where you can be left with the system without a cursor and active breakpoint
- simulation use case, where switching context and focus does not always work, and the user is left with the GameLauncher window minimized and without a mouse cursor.
It is supported on Linux and Windows. I have no capability to implement MacOS version.
=> Registry option to disable mouse capture

Docker/entrypoint.sh
This reverts commit d7a5ab5513069b34eaf48c1969797499d2b48b02. The ownership changes for O3DE introduced a 2+ minute delay on docker startup, and was unnecessary
=> Revert "Fix permission issues in docker container for the installed o3de (#18047)"

Code/Legacy/CryCommon/IRenderer.h, Gems/ImGui/Code/Source/ImGuiManager.h
removed a couple references to VertexFormat
=> feat: remove unused logic that references VertexFormat

Code/Editor/TrackView/TrackViewNodes.cpp, Code/Editor/TrackView/TrackViewNodes.h, Gems/LyShine/Code/Editor/Animation/UiAnimViewNodes.cpp, Gems/LyShine/Code/Editor/Animation/UiAnimViewNodes.h
wanted to rework this code a bit and fix a couple problems with the track view tree view. I resolve the cut arrows in the treeview and simplified the logic for icons. I would like to revisit the icons in the treeview but this should be a good place to start.  It doesn't seem like its necessary to stash the QIcons in a table, not sure the overhead but it can't be worth having a qmap. 
- open the trackview
- add an entity from the scene.
=> feat: minor refactor trackview tracknodes icons

Gems/Atom/Feature/Common/Assets/Passes/ReflectionScreenSpace.pass, Gems/Atom/Feature/Common/Assets/Passes/ReflectionScreenSpaceRayTracing.pass
The JSON parser appears to be locale dependent, so for locales where the floating point is a comma instead of a period this leads to wrong parsing of the numbers.
ASV reflections sample.
=> Fix for floats that are strings.

Gems/Atom/RHI/Vulkan/Code/Source/RHI/Queue.cpp
Found this bug through corresponding validation layer errors.
ASV Multi-GPU RPI sample.
=> Fix for missing wait stage for semaphore in Vulkan.

Gems/Atom/RHI/DX12/Code/Source/RHI/FrameGraphExecuteGroupMerged.cpp
This PR fixes the following compile error when using a nounity build on Windows:
```
.../Gems/Atom/RHI/DX12/Code/Source/RHI/FrameGraphExecuteGroupMerged.cpp:70:43: error: member access into incomplete type 'Device'
70 |             request.m_deviceIndex = device.GetDeviceIndex();
|                                           ^
.../Gems/Atom/RHI/DX12/Code/Source\RHI/CommandListBase.h:24:15: note: forward declaration of 'AZ::DX12::Device'
24 |         class Device;
|               ^
```
Compile with `-DLY_UNITY_BUILD=OFF` on Windows.
=> Fix nounity-build on Windows

Code/Framework/AzFramework/AzFramework/Input/Devices/Mouse/InputDeviceMouse.cpp, Code/Framework/AzFramework/AzFramework/Input/Devices/Mouse/InputDeviceMouse.h, Code/Framework/AzFramework/AzFramework/Input/System/InputSystemComponent.cpp, Code/Framework/AzFramework/AzFramework/Input/System/InputSystemComponent.h, Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.cpp, Code/Framework/AzFramework/Platform/Windows/AzFramework/Input/Devices/Mouse/InputDeviceMouse_Windows.cpp
This is a cherry-pick of the PR https://github.com/o3de/o3de/pull/18042 that was merged into `development`.
The change in the codebase is small, so the chance of introducing a bug to the stabilization branch is also small. The feature is quite important for simulation.
Copy from #18042 :
> This PR allows setting a registry key "O3DE/InputSystem/Mouse/CaptureMouseCursor" to disable mouse capture.
> It is useful in two scenarios:
> - during a debugging session, where you can be left with the system without a cursor and active breakpoint
> - simulation use case, where switching context and focus does not always work, and the user is left without a mouse cursor with the GameLauncher window minimized
#18042 was tested on Linux and Windows, I tested it again after cherry-picking on Linux.
=> Cherry-pick: Registry option to disable mouse capture (#18042)

Gems/LyShine/Code/Editor/Animation/UiAnimViewNodes.cpp, Gems/LyShine/Code/Editor/Animation/UiAnimViewNodes.h, Gems/LyShine/Code/Editor/Animation/UiAnimViewSequence.cpp, Gems/LyShine/Code/Editor/Animation/UiAnimViewSequence.h
This is logic that is fully deprecated. I removed logic that is associated with CEntityObject.
=> feat: remove ifdefed logic releated to CEntityObject

Code/Framework/AzCore/AzCore/Serialization/EditContextConstants.inl, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEntityIdCtrl.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEntityIdCtrl.hxx
Fixes Issue #16541
Fixes Issue #18052
Makes it so that you MUST use the entity outliner to modify parenting of entities.  This prevents a whole series of issues related to parenting that already has a ton of code written in the outliner to prevent various side effects and issues.
Manual testing - making sure you can still copy the entity name and click on it and see the tooltip and that you can still "copy component" / "paste component" and undo and redo and all that but that all other transform parent manipulations must go thru the outliner.
=> Fix unparent prefab entities

.automatedtesting.json
Reverts switching the o3de-extras branch to multi-device-resources introduced in #17974 which was necessary to make the CI happy. This depends on https://github.com/o3de/o3de-extras/pull/716 being merged first.
=> Revert using the multi-device-resources branch for o3de-extras.

Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuter.cpp
Fixes a compile error w.r.t. wrongly const declared data types.
Defined `AZ_FORCE_CPU_GPU_INSYNC` in `Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/Base.h` and compiled.
=> Compile fix for when AZ_FORCE_CPU_GPU_INSYNC is defined.

cmake/Platform/Linux/ProcessDebugSymbols.cmake
objcpy reports "debuglink section already exists" as there seems to be such a section already present. The following issue helped here: https://github.com/softprops/lambda-rust/issues/41
Compiled with this and got rid of the error.
=> Fix debug symbol error.

Gems/Atom/RHI/Code/Source/RHI/RayTracingShaderTable.cpp
Fix #18086. Empty RayTracingShaderTableDescriptors are allowed, so the assert can simply be removed.
As described in #18086.
=> Bugfix for #18086: Assert trigger when reloading Sponza level

Gems/Atom/RHI/DX12/External/md5/openssl/md5.c
PR #18019 includes `md5`, which currently does not compile (on Windows with clang 17.0.6) with the following build error message:
```
[build] D:/projects/o3de/engine/Gems/Atom/RHI/DX12/External/md5/openssl/md5.c:234:4: error: call to undeclared library function 'memcpy' with type 'void *(void *, const void *, unsigned long long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
[build]   234 |                         memcpy(&ctx->buffer[used], data, size);
[build]       |                         ^
[build] D:/projects/o3de/engine/Gems/Atom/RHI/DX12/External/md5/openssl/md5.c:234:4: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
[build] D:/projects/o3de/engine/Gems/Atom/RHI/DX12/External/md5/openssl/md5.c …
```
=> Missing include fix for md5 

Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/CoreLights/DirectionalLightBus.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DirectionalLightComponentController.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DirectionalLightComponentController.h
Since we are already exposing Get/SetIntensity in DirectionalLightBus.h, it makes a lot of sense to also expose Get/SetIntensityMode there. It is useful for implementing gems that receives directional lights, like implementing participant media rendering that reacts directional lights.
Tested on Windows with both RHI. Exposing it should not cast any effect on existing things.
=> Expose GetIntensityMode/SetIntensityMode  in DirectionalLightBus.h

Gems/Atom/RHI/DX12/Code/Source/RHI/Fence.cpp
This fixes a problem when we wait for more than one fence at the same time.
According to the [documentation](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createeventa), there cannot be two different events with the same name. Creating the second event returns the first one again:
```
If the named event object existed before the function call, the function returns a handle to the existing object and [GetLastError](https://learn.microsoft.com/en-us/windows/desktop/api/errhandlingapi/nf-errhandlingapi-getlasterror) returns ERROR_ALREADY_EXISTS.
```
We therefor had only one event for two fences, sometimes leading to the problem that the wrong thread continued.
AtomSampleViewer on Windows+DX12. The Multi GPU RPI sample with the Copy Test Pipeline led to a deadlock …
=> DX12: Remove name from FenceEvent windows event

.automatedtesting.json
Makes it so that when the AR system builds branches based on stabilization/2409, it uses the stabilization/2409 version of o3de-extras as well, instead of o3de-extras:development branch
! DO NOT MERGE THIS CHANGE BACK TO DEVELOPMENT !
I'll be triggering an AR to test it.
example of the problem: https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-18056/2/pipeline/129
Lots of Atom-related API change errors, its checking development of extras out instead of the stabilization branch during AR.
=> DO NOT MERGE TO DEV - Makes o3de.git/stabilization/2409 use o3de-extras.git/stabilization/2409

Code/Framework/AzFramework/AzFramework/Visibility/OcclusionBus.cpp, Code/Framework/AzFramework/AzFramework/Visibility/OcclusionBus.h, Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
This PR cherry picks occlusion bus functions, comments, and changes from development branch to stabilization. There are no functional changes, just updates to the interface being used in other projects.
Compiled stabilization branch and automated testing project.
Launch editor and material canvas.
While testing, discovered that current stabilization branch is not compatible with atom sample viewer, extras, or multiplayer sample, which will need stabilization branches created.
=> Cherry picking occlusion bus changes to stabilization 2409

Gems/Atom/RHI/DX12/Code/Source/RHI/Device.cpp
Properly checks feature support for wive operation.
Before the CheckFeatureSupport would return E_INVALIDARG and silently fail at least on AMD and
with this fix it will properly get that feature support with logging if it fails.
Running the editor and game launcher in profile mode.
=> DX12 RHI: Fix the check for wive operation

Gems/Atom/RPI/Code/Source/RPI.Public/Pass/CopyPass.cpp
This PR fixes a few things in the CopyPass:
- Copying on the same device was always performed on the default device
- The host buffer for the host-to-device copy was wrongly allocated in the Readback Buffer Pool, instead of the Staging Buffer Pool
- The destination format was missing when copying a image to a buffer on the same device
AtomSampleViewer on Windows with DX12/Vulkan
=> CopyPass fixes

Gems/Atom/RHI/DX12/Code/Source/RHI/Device.cpp
The `signalOnCPU` device feature was set to true inside `#ifdef O3DE_DX12_VRS_SUPPORT`. It should always be set to true as all DX12 Fences can be signalled from the CPU.
Windows and DX12
=> DX12: Fixed setting the signalOnCPU feature

Gems/Atom/RHI/Code/Source/RHI/RayTracingAccelerationStructure.cpp
`MultiDeviceObject::IterateObjects` has no implementation that supports a callback returning a boolean, it needs to be a `ResultCode`.
Compiled an ran a code sample where this is used (so far it's not used anywhere else, that's why the bug didn't appear).
=> Bugfix for wrong iteration.

Gems/Atom/RHI/Code/Source/RHI/RayTracingAccelerationStructure.cpp
This fixes https://github.com/o3de/o3de/issues/18099.
The issue was that the `GetDeviceRayTracingBlasDescriptor()` did not correctly pass the `m_BuildFlags` to the `DeviceRayTracingBlasDescriptor`, which left them in the default state (`AZ::RHI::RayTracingAccelerationStructureBuildFlags::FAST_TRACE`) and did not pass `AZ::RHI::RayTracingAccelerationStructureBuildFlags::ENABLE_UPDATE | AZ::RHI::RayTracingAccelerationStructureBuildFlags::FAST_BUILD` correctly on.
=> Fix missing build flags passed to DeviceRayTracingBlasDescriptor

scripts/build/Platform/Linux/build_config.json
Removes snap core 20 jobs from the installer pipeline.
Implements https://github.com/o3de/rfcs/issues/54
TBD
=> Remove snap core 20 from the build scripts

scripts/build/Platform/Linux/build_config.json
Removes snap core 20 jobs from the installer pipeline.
Implements https://github.com/o3de/rfcs/issues/54
Cherry pick https://github.com/o3de/o3de/pull/18121 into development
=> [Cherry-pick] Remove snap core 20 from the build scripts (#18121)

Gems/Atom/RHI/Code/Include/Atom/RHI/PipelineState.h, Gems/Atom/RHI/Code/Source/RHI/PipelineState.cpp, Gems/Atom/RHI/Code/Source/RHI/PipelineStateCache.cpp
We encountered an issue that happens mainly when loading very large levels with loads of meshes. 
The issue originates in the `PipelineStateCache` and how `PipelineState`s are created there and how that interplays with multi-threaded `MeshDrawPacket` creation.
During `appendShader` in `MeshDrawPacket::DoUpdate()`, it calls 
```cpp
const RHI::PipelineState* pipelineState = shader->AcquirePipelineState(pipelineStateDescriptor);
```
which in turn calls
```cpp
m_pipelineStateCache->AcquirePipelineState(m_pipelineLibraryHandle, descriptor, m_asset->GetName());
```
This then checks the read-only cache, the thread-local cache, and if neither provides something in return, it calls 
```cpp
ConstPtr<PipelineState> pipelineState = CompilePipelineState(globalLibraryEntry, threadLibraryEntry, …
```
=> Fix multi-threaded creation of PipelineStates in PipelineStateCache

Code/Framework/AzFramework/AzFramework/Visibility/OcclusionBus.cpp, Code/Framework/AzFramework/AzFramework/Visibility/OcclusionBus.h, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Culling.h, Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
Added occlusion state enum, with invalid state, to replace bool return values Updated occlusion bus functions to return occlusion state enum and invalid state as needed Added an optional entity id member to rhi culling structure to pass through to culling system Updated calls in multiplayer sample and culling system Added support for non uniform transform when recording visible geometry transforms
Compiled code without errors.
Tested in editor and came launcher.
Confirmed behavior with other local changes.
=> OcclusionBus improved support for culling by entity ID

Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceObject.h, Gems/Atom/RHI/Code/Include/Atom/RHI/Object.h, Gems/Atom/RHI/Code/Source/RHI/BufferPool.cpp, Gems/Atom/RHI/Code/Source/RHI/Fence.cpp, Gems/Atom/RHI/Code/Source/RHI/ImagePool.cpp, Gems/Atom/RHI/Code/Source/RHI/IndirectBufferSignature.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceObject.cpp, Gems/Atom/RHI/Code/Source/RHI/PipelineLibrary.cpp, Gems/Atom/RHI/Code/Source/RHI/PipelineState.cpp, Gems/Atom/RHI/Code/Source/RHI/QueryPool.cpp, Gems/Atom/RHI/Code/Source/RHI/RayTracingAccelerationStructure.cpp, Gems/Atom/RHI/Code/Source/RHI/RayTracingBufferPools.cpp, Gems/Atom/RHI/Code/Source/RHI/RayTracingPipelineState.cpp, Gems/Atom/RHI/Code/Source/RHI/RayTracingShaderTable.cpp, Gems/Atom/RHI/Code/Source/RHI/ResourcePool.cpp, Gems/Atom/RHI/Code/Source/RHI/ShaderResourceGroupPool.cpp, Gems/Atom/RHI/Code/Source/RHI/StreamingImagePool.cpp, Gems/Atom/RHI/Code/Source/RHI/SwapChain.cpp, Gems/Atom/RHI/Code/Source/RHI/TransientAttachmentPool.cpp, Gems/Atom/RHI/Code/Tests/MultiDeviceDrawPacketTests.cpp
We recently found that calls to `SetName()` are not passed on to the `DeviceObject`s, which leads to incomplete log output, e.g.
```
<12:23:00> [Error] (DeviceBufferPoolBase) - Failed to map buffer ''.
<12:23:00> [Error] (BufferPool) - Unable to map buffer 'EsmParameterBuffer(Directional)(MainPipeline_0)7'.
<12:23:00> [Error] (BufferPool) - Failed to map buffer 'EsmParameterBuffer(Directional)(MainPipeline_0)7'.
<12:23:00> [Error] (RPI::Buffer) - Failed to update RHI buffer. Error code: 2
```
Since `SetName()` is not set consistently before or after the call to `Init()`, it is either directly passed on in the call to `MultiDeviceObject::SetName()` or after creating the `DeviceObject`s in the respective calls to `Init()`.
=> Pass on `Name` to DeviceObjects

Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiPassTree.h, Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiPassTree.inl
Currently the passes in the ImGui pass tree are all expanded by default, if the pipeline has a lot of passes, seeking for a pass in a pipeline can be painful.
This PR adds an "Expand All Passes" check box to allow expanding/collapsing all passes, and the default behavior of it is to expand all by default, remaining the current behavior but allows users to collapse all passes and only expand his/her wanted pass, making the life easier to find a pass in a long pipeline.
Tested in windows.
=> Allow collapsing all passes in pass tree view

Gems/Atom/RHI/Vulkan/Code/Source/RHI/Image.cpp
The current `UpdateMipMemoryBindInfo(uint16_t mipLevel)` did not consider the 3D volume texture case.  
Consider the example if we have `64x64x64(width,height,layer` 3d texture and the block size is 16x16x16. When `boundBlockCount` is 20, without `(% blockCountPerColumn)`, we would get `offset.y` to `(20/4 *16) = 80`. The later `extent.height = mipSize.m_height-offset.y = ((unsigned)64-80)` will be a huge positive number because of integer overflow, thus led to error in Sparse binding.
| Before | After Fix |
| :-------: | :----------: |
|   ![1721430474192](https://github.com/user-attachments/assets/3de3eb12-6527-49ad-8e11-eb6ba4ef2d32) | ![1721430496319](https://github.com/user-attachments/assets/08271e64-926a-4ff3-bcc7-33e051eb96e8)
|
Locally Tested.
=> Fixing Vulkan SparseBinding memoryBindings for 3D texture

Gems/Atom/RHI/Vulkan/Code/Source/RHI/AliasedHeap.cpp
Working on a sample where multiple consecutive compute shaders access a single transient buffer attachment, I found that no barriers were inserted into Vulkan's command buffer. The cause is that the buffers initialized in the AliasedHeap have their descriptor set too late which causes the initial setting of the queue owner to fail.
An own small sample in the ASV.
=> Bugfix for generating Buffer Barriers in Vulkan for Transient Attachments

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Buffer/Buffer.h
This fixes a spurious crash that happens when the destructor of an RPI::Buffer is finished before the thread waiting for the GPU upload fence is executed. 
Fixes a crash with the following sequence:
- `RPI::Buffer::Init()`
- Create wait thread with lambda in line 175 with `WaitOnCpuAsync()`
- `RPI::Buffer::~Buffer()`
- Calls `WaitForUpload()` to block until GPU upload is finished
- current thread happens to be called before the async waiting thread
- class destructor finishes, data members are destroyed  
- destructor for `m_pendingUploadMutex`
- destructor for `m_streamFence`
- lambda is executed and tries to lock already destroyed `m_pendingUploadMutex`
The fix reorders the data members and ensures that `m_pendingUploadMutex` still exists during the destructor of `m_streamFence`
Tested …
=> Fix a crash if a RPI::Buffer is destroyed during upload

Gems/Atom/Feature/Common/Code/Source/Debug/RayTracingDebugFeatureProcessor.cpp, Gems/Atom/RHI/Code/Source/RHI/DeviceRayTracingAccelerationStructure.cpp, Gems/Atom/RHI/Code/Source/RHI/RayTracingAccelerationStructure.cpp, Gems/DiffuseProbeGrid/Assets/Passes/DiffuseProbeGridQueryFullscreenWithAlbedo.pass
This PR fixes two warnings and a typo in RayTracingDebugFeatureProcessor:
- Assert about setting the RT-Acceleration structure build flags before assigning a AABB when using procedurel geoemtry
- DX12 validation error due to the `FallbackNormal` attachment of `ReflectionScreenSpaceRayTracingPass` being used for both `NormalInput` and `DirectionInput` of `DiffuseProbeGridQueryFullscreenWithAlbedoPass`. I fixes this by changing the `SlotType` of the inputs in Diffuse-GI-Pass to `Input`
```
..\Gems\Atom\RHI\Code\Source\RHI\FrameGraph.cpp(130): (62068)
'void AZ::RHI::FrameGraph::ValidateOverlappingAttachment(
AttachmentId, ScopeAttachmentUsage, ScopeAttachmentAccess, const ScopeAttachment &) const'
When adding two overlapping attachments in a scope, neither should have write
access, but a …
```
=> Fix a validation warning due to overlapping attachments in DiffuseProbeGrid and an AZ_Assert for the AABB BLAS descriptor

scripts/build/build_node/Platform/Linux/package-list.ubuntu-bionic.txt, scripts/build/build_node/Platform/Linux/package-list.ubuntu-focal.txt, scripts/build/build_node/Platform/Linux/package-list.ubuntu-jammy.txt
It modifies build nodes in preparation for another pr https://github.com/o3de/o3de/pull/17913
I checked correctness of package names
=> libxcb-image0-dev  and xxd added to dependencies of build nodes

Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiPassTree.h, Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiPassTree.inl
This PR adds a search bar to the PassTree view of the ImGui debug gui, such that finding a specific pass is faster than manually searching through the list. The same option already exists for the "Timestamp view" window.
Each pass which matches the search term, and all of their parents up to the root pass are shown, which matches the behavior of the Timestamp view.
Run the Editor on Windows, use a few search terms to make sure the correct passes show up.
=> Add search bar to ImGui PassTree view

Gems/Atom/RHI/Code/Source/RHI/RayTracingAccelerationStructure.cpp
Introduced by https://github.com/o3de/o3de/pull/18126, the weird handling of the `GetTLAS*Buffer` methods can lead to this method returning a `nullptr`, which was not accounted for when calling `SetName` on it, which leads to a crash when switching levels.
Tested by reloading or switching between levels.
=> Fix a crash during level reload when resource allocation fails

Gems/Atom/Feature/Common/Assets/Passes/DebugRayTracingPass.pass
The `DebugRaytracingPass` is injected behind the `AuxGeomPass`, but is connected to the output slot of the `PostProcessPass`.
This is a problem if the Debug Pass is used in a custom render pipeline that uses the `AuxGeomPass`, but not the `PostProcessPass`.
This PR changes this connection to the output slot of the `AuxGeomPass`, so the Debug Pass can function in any render pipeline that contains at least the `AuxGeomPass`.
On Vulkan / Windows with a custom render pipeline.
=> Make the Debug Raytracing Pass more portable

AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py, AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py
Increases timeout for the multiplayer basic connectivity tests.
Jenkins AR was failing at random, and the logs revaled that 15 attempts
were simply not enough for the server to always start 100% of the time.
I've vastly increased the timeout to about 10.5 minutes (since it is
an increasing backoff.)  This only affects automated testing.
I would rather this test fail because something is definitely,
positively wrong, than it fail because the server is busy or some
other process is happening in the background or something.
Note that this will only increase the time these tests take when
the server actually fails to start for some reason, in the normal
working case, the editor will still connect within a few seconds and
the timeout will not hit.
```
ctest -j12 -C profile --output-on-failure …
```
=> Increase multiplayer AR Test timeout

Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.h, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
To be able to utilize the raytracing acceleration structures in a multi-GPU context, the `RayTracingAccelerationStructurePass` needs to run on all devices and build the TLAS and BLAS instances on these devices.
Simply duplicating the pass on all devices does not suffice, as the current design uses a boolean to see if the acceleration structures need to be built, which would not work with multiple passes on different devices in a multi-threaded context.
Our solution changes the following aspects:
1. The `RayTracingAccelerationStructurePass` now implicitly runs on all devices that support ray tracing
- This is done by explicitly creating `ScopeProducer`s for each device with ray tracing support
2. The revision check is done once during `FrameBeginInternal` as well as all code that should be …
=> Implicitly multi-device RayTracingAccelerationStructurePass

Code/Framework/AzCore/AzCore/Serialization/EditContextConstants.inl, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEntityIdCtrl.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEntityIdCtrl.hxx
* Fixes issue where invalid parenting can be done via inspector
Fixes Issue #16541
Fixes Issue #18052
Makes it so that you MUST use the entity outliner to modify parenting of entities.  This prevents a whole series of issues related to parenting that already has a ton of code written in the outliner to prevent various side effects and issues.
See the original PR at https://github.com/o3de/o3de/pull/18073 for additional information.  This is just a cherrypick.
=> Cherrypick from stabilization to dev - Fix unparent prefab entities (#18073)

Code/Editor/NewLevelDialog.cpp
AutomatedTesting\Gem\PythonTests\editor\EditorScripts\BasicEditorWorkflows_LevelEntityComponentCRUD.py
I really have no idea how this didn't constantly crash before.
tTis script opens a New Level Dialog and before it even manages to fully appear, it auto-accepts it, which calls the GetTemplatePath function. This function dereferences (without checking), the pointer given by the ui to the currently selected item in the list view.
There is no default selection so this would always be nullptr.
I don't know when this changed, but this change makes it so that there is a preferred default selection, and if the default is missing, it uses the first item in the list as a final failsafe.
Tested by running the script.  It crashed 100% of the time for me before, and after, it no longer crashes. …
=> Fixes a crash in test LevelEntityComponentCRUD test

Gems/AudioSystem/Code/Source/Engine/AudioSystem.cpp, Gems/AudioSystem/Code/Source/Engine/AudioSystem.h
Fix for audio system stealing CPU time. 
Updating audiosystem update to use microseconds to allow for sub-millisecond sleeping.
_try_acquire_for_ converts relative time (4ms) to absolute time (now+4ms). Instead of using a custom duration type use the built-in AZStd::chrono::microseconds which stores 64-bit integers so can safely be added to epoch time (now) to produce absolute time.
Tested by running on iOS and seeing that AudioSystem::InteralUpdate no longer instantly returns after calling _try_aquire_for_
=> Fix for Audio Thread Taking 90% Frame Time

AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py, AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py
This is a cherry-pick of the already merged PR 18138 from stabilization https://github.com/o3de/o3de/pull/18138
* Adds additional timeout to the whole test
* Increases timeout for the multiplayer basic connectivity tests.
Jenkins AR was failing at random, and the logs revaled that 15 attempts were simply not enough for the server to always start 100% of the time.
I've vastly increased the timeout to about 10.5 minutes (since it is an increasing backoff.)  This only affects automated testing.
I would rather this test fail because something is definitely, positively wrong, than it fail because the server is busy or some other process is happening in the background or something.
Note that this will only increase the time these tests take when the server actually fails to start for some …
=> Cherry-pick from stabilization - Increase multiplayer AR Test timeout 

Code/Editor/NewLevelDialog.cpp
This is a cherry-pick of the already merged bugfix https://github.com/o3de/o3de/pull/18164 from stabilization
AutomatedTesting\Gem\PythonTests\editor\EditorScripts\BasicEditorWorkflows_LevelEntityComponentCRUD.py
I really have no idea how this didn't constantly crash before.
The above named script opens a New Level Dialog and before it even manages to fully appear, it auto-accepts it, which calls the GetTemplatePath function. This function de-references (without checking), the pointer given by the UI to the currently selected item in the list view.
There is no default selection so this would always be nullptr, resulting in a nullptr de-reference.
I don't know when this changed, but this change makes it so that there is a preferred default selection, and if the default is missing, it uses …
=> cherry-pick bugfix from stabilization - Fixes a crash in test LevelEntityComponentCRUD test

Code/Editor/Platform/Windows/Editor/Core/QtEditorApplication_windows.cpp, Code/Framework/AzFramework/Platform/Windows/AzFramework/Windowing/NativeWindow_Windows.cpp
Fixes the issue where the gamepad (and other input device) detection was only happening on game launch, but not when a device has been added or removed after game launch.
Cherry pick of https://github.com/o3de/o3de/pull/18181
Fixes https://github.com/o3de/o3de/issues/18040 
Test scenario described by https://github.com/o3de/o3de/issues/18040 with the Paper Delivery Boy project
=> [Cherry-Pick] Add WM_DEVICECHANGE handling for the Native Windows Launcher to trigger input notification changes

Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp, Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp, Code/Editor/QtUtil.h, Code/Editor/Viewport.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserEntityInspectorWidget.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Favorites/AssetBrowserFavoritesView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Favorites/AssetBrowserFavoritesView.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.h
Fixes issue https://github.com/o3de/o3de/issues/18067
Fixes an issue where if you click on an item in the Asset Browser window when it was already selected, it would not previously update the inspector to show the selected item details (it would only respond to selection change).  I tried updating on focus, but focus happens for many other reasons too like rolling the mouse wheel or scroll bar.  So I kept it "on click" on an item without changing focus.
Old behavior: 
1. Click on an asset in the Asset Browser.  Inspector shows that asset details and selects the asset
2. Click on anything else in any other part of gui.  Inspector shows that detail of what you clicked on
3. Click again on asset in Asset Browser (same one as before).  Because it was already selected the inspector does not …
=> Fix several selection and focus related issues for the Asset Browser.

Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderDataSystem.cpp, Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderWorker.cpp, Gems/ScriptCanvas/Code/Editor/Assets/ScriptCanvasFileHandling.cpp, Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp, Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Assets/ScriptCanvasFileHandling.h, Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Bus/EditorScriptCanvasBus.h, Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorGraph.h, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LiveWindowSession/LiveLoggingWindowSession.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindowSession.cpp, Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/GraphSerialization.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/GraphSerialization.h
Follow-up to https://github.com/o3de/o3de/pull/17912. And work for https://github.com/o3de/o3de/issues/9192.
**As a user**:
- When a graph is open and has entries in the live trace window, double click on an entry to jump to the right node (see video below)
- Be notified when the remote debugging gem is not enabled (see image below)
**As a developer**:
- This PR allows to match node UIDs from runtime graphs to editor graph. This is the basis needed to make a scriptCanvas breakpoint debugging system.
- The node UIDs in the **.scriptcanvas** json are now the same in the **.scriptcanvas_compiled** runtime binary files, allowing easier debug when you break in the lua VM (possible to use g_saveRuntimeAssetsAsPlainTextForDebug to check the binary file content). …
=> Further fixes for the ScriptCanvas debugging facilities

Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
From Mesa 24 onward there's a rendering issue with all objects of the default scene appearing black (#17673) (#18088).
The PR #17905 solved the problem in `development` branch, this cherry-pick PR brings the solution to `stabilization/2409`.
I built an tested both before and after the cherry-pick by opening a default template project, and it does solves the rendering issue.
=> [Cherry-Pick] Fix Mesa 24 rendering issues on 24.09 (#17905)

Templates/CppToolGem/Template/Code/CMakeLists.txt, Templates/GraphicsGem/Template/Code/CMakeLists.txt, Templates/UnifiedMultiplayerGem/Template/Code/CMakeLists.txt
Cherry picks template fix from https://github.com/o3de/o3de/pull/18182
=> [Cherry Pick] Removing $<TARGET_OBJECTS::Gem...> usage from project templates 

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/RenderPass.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/PassData.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/RenderPassData.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp, Gems/Atom/RPI/Code/Source/RPI.Reflect/Pass/PassData.cpp
This is almost the same with #17906 before multi-device-resources branch get merged, as we discussed there, I re-create this PR here to development branch.
In the current code, we would have to set the device index for each render pass, in real render pipeline, there are quite a lot parent passes, the render passes are hidden behind the parent pass, being not able to set the device index for them easily.
This PR supports inheriting device index from parent pass, so that user/developer can batch set the device index for multiple child passes, to easily create multi-device pipeline.
Self tested on Windows with one/two devices.
=> Support inheriting device index from parent pass

Templates/ScriptOnlyProject/Template/package.sh, cmake/Platform/Common/Install_common.cmake
Fixes issue : https://github.com/o3de/o3de/issues/18054
This might have been causing all sorts of other issues in other specific cases too, but this is the one that brought it to my attention.
Root cause analysis (as best as I can tell)
When generating the installer, the cmake script to do so would copy assets for gems, and in doing so, would glob all the files and directories in that candidate gem folder over to the target folder.
In order for such "asset only" gems to function, they need to have a cmakelists.txt generated which created a Builders target.  So it would generate one...
To do so, it would check each candidate gem folder, and if it found that the candidate gem folder DID NOT have a cmakelists.txt generated already (which happens if it contains targets), it would make one …
=> Fixes script-only "Quickstart" mode.

Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp, Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.h, Code/Editor/ViewManager.cpp, Code/Editor/ViewManager.h, Code/Framework/AzToolsFramework/AzToolsFramework/API/ToolsApplicationAPI.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/EditorMenu.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/EditorMenu.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/MenuManager.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/MenuManager.h, Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/MenuManagerInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
This cherry picks a [fix for placing entities/prefab](https://github.com/o3de/o3de/pull/17768) instantiation for viewport interactions to where the mouse is located, rather than at (0,0,0)
Verified fix on Windows and Linux
=> [Cherry Pick] Allow for Entity creation and Prefab instantiation in place via viewport interactions

Code/Framework/AzFramework/AzFramework/Visibility/VisibleGeometryBus.cpp, Code/Framework/AzFramework/AzFramework/Visibility/VisibleGeometryBus.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h, Gems/WhiteBox/Code/Source/EditorWhiteBoxComponent.cpp, Gems/WhiteBox/Code/Source/EditorWhiteBoxComponent.h, Gems/WhiteBox/Code/Source/Rendering/WhiteBoxRenderDataUtil.cpp, Gems/WhiteBox/Code/Source/Rendering/WhiteBoxRenderDataUtil.h, Gems/WhiteBox/Code/Source/WhiteBoxComponent.cpp, Gems/WhiteBox/Code/Source/WhiteBoxComponent.h, Gems/WhiteBox/Code/whitebox_supported_files.cmake
This implements the visible geometry request bus on the white box components. This allows other tools and systems, like occlusion culling, to mine geometric data from white box components using a general purpose bus and data structures.
Tested by exporting data in separate project
=> Implement conversion from white box render data to visible geometry struct

Gems/AWSGameLift/Code/AWSGameLiftServer/Source/Platform/Linux/PAL_linux.cmake, Gems/AWSGameLift/Code/AWSGameLiftServer/Source/Platform/Windows/PAL_windows.cmake, cmake/3rdParty/Platform/Linux/BuiltInPackages_linux_aarch64.cmake, cmake/3rdParty/Platform/Linux/BuiltInPackages_linux_x86_64.cmake, cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
Pulled AWSGameLiftServer 3p package out of built-in packages; this hash already exists in the GameLift gem
=> Update AWSGameLiftServer 3rd Party Package Hash

Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h, Gems/Atom/RHI/Code/Include/Atom/RHI/Buffer.h, Gems/Atom/RHI/Code/Include/Atom/RHI/DispatchItem.h, Gems/Atom/RHI/Code/Include/Atom/RHI/DispatchRaysIndirectBuffer.h, Gems/Atom/RHI/Code/Include/Atom/RHI/DispatchRaysItem.h, Gems/Atom/RHI/Code/Include/Atom/RHI/DrawPacketBuilder.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceObject.h, Gems/Atom/RHI/Code/Include/Atom/RHI/PipelineLibrary.h, Gems/Atom/RHI/Code/Source/RHI/Buffer.cpp, Gems/Atom/RHI/Code/Source/RHI/DrawItem.cpp, Gems/Atom/RHI/Code/Source/RHI/FrameScheduler.cpp, Gems/Atom/RHI/Code/Source/RHI/MultiDeviceObject.cpp, Gems/Atom/RHI/Code/Source/RHI/PipelineState.cpp, Gems/Atom/RHI/Code/Source/RHI/ShaderResourceGroupData.cpp, Gems/Atom/RHI/Code/Tests/MultiDevicePipelineStateTests.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/RenderPass.h, Gems/DebugDraw/Code/Source/DebugDrawSystemComponent.cpp, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.cpp
Mostly refactoring a bit and some minor bug fixes.
- Bugfix for RayTracingAccelerationStructurePass.
- meshInfos in RayTracingFeatureProcessor should be multi-device.
- Changed BindlessIndices to multi-device for RayTracingFeatureProcessor.
- Introduced a static MultiDeviceObject::IterateDevices method and use it wherever possible.
- Also added a static MultiDeviceObject::IsDeviceSet method.
- MultiDeviceObject::IterateObjects now supports callbacks with boolean return type.
- Removed unused GetSerializedData in the multi-device PipelineLibrary. GetSerializedDataMap fulfills that purpose.
- Added multi-device BufferView::GetBindlessReadIndex().
- RenderPass::m_lastDeviceIndex default initialization changed to InvalidDeviceIndex.
- Minor other changes.
Ran ASV Samples.
=> Refactoring of multi-device code.

Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp
`Pass::SetDeviceIndex()` does not have any effect without this since the ScopeProducer needs to be updated after the pass's device index changed.
With a minor modification testing this in the ASV RPI MultiGPU sample.
=> Bugfix: Pass::SetDeviceIndex not working.

Templates/ScriptOnlyProject/Template/package.sh, cmake/Platform/Common/Install_common.cmake
Cherry-pick https://github.com/o3de/o3de/pull/18189 from stab to dev.
Fixes issue : https://github.com/o3de/o3de/issues/18054
This might have been causing all sorts of other issues in other specific cases too, but this is the one that brought it to my attention.
Root cause analysis (as best as I can tell)
When generating the installer, the cmake script to do so would copy assets for gems, and in doing so, would glob all the files and directories in that candidate gem folder over to the target folder.
In order for such "asset only" gems to function, they need to have a cmakelists.txt generated which created a Builders target.  So it would generate one...
To do so, it would check each candidate gem folder, and if it found that the candidate gem folder DID NOT have a cmakelists.txt generated …
=> Cherrypick from stab to dev - Fixes script-only "Quickstart" mode. (#18189)

Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/Bits.h, Gems/Atom/RHI/Code/Include/Atom/RHI/Buffer.h, Gems/Atom/RHI/Code/Include/Atom/RHI/BufferPool.h, Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceBufferPool.h, Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceImagePool.h, Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceStreamingImagePool.h, Gems/Atom/RHI/Code/Include/Atom/RHI/Image.h, Gems/Atom/RHI/Code/Include/Atom/RHI/ImagePool.h, Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceObject.h, Gems/Atom/RHI/Code/Include/Atom/RHI/PipelineLibrary.h, Gems/Atom/RHI/Code/Include/Atom/RHI/StreamingImagePool.h, Gems/Atom/RHI/Code/Source/RHI/Buffer.cpp, Gems/Atom/RHI/Code/Source/RHI/BufferPool.cpp, Gems/Atom/RHI/Code/Source/RHI/DeviceShaderResourceGroup.cpp, Gems/Atom/RHI/Code/Source/RHI/FrameAttachment.cpp, Gems/Atom/RHI/Code/Source/RHI/Image.cpp, Gems/Atom/RHI/Code/Source/RHI/ImagePool.cpp, Gems/Atom/RHI/Code/Source/RHI/ResourcePool.cpp, Gems/Atom/RHI/Code/Source/RHI/StreamingImagePool.cpp, Gems/Atom/RHI/Code/Tests/FrameGraphTests.cpp
This PR changes the API of images and buffers to support having an own device mask which may include less devices than the pool they were allocated from as well as updating this device mask when necessary. This might be used for resources that are only required on a subset of devices that may change in dynamic scheduling situations as passes are moved between devices.
Tested with sample code in the RHI MultiGPU sample in ASV.
=> Multi-device masks for Images and Buffers

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/CopyPass.h
Fixes a bug where a variable does not get 0 initialized resulting in other variables not being initialized when by random chance a specific value is already present.
Create, delete and recreate a copy pass so that the memory is initialized with the old copy pass's values.
=> Bugfix for uninitialized variable.

Assets/Engine/Schema/enginedependency.xmlschema, Gems/LmbrCentral/Code/Source/Builders/CopyDependencyBuilder/XmlBuilderWorker/XmlBuilderWorker.cpp
Fixes the issue detailed here:
https://github.com/o3de/o3de/issues/17876
1) Updates the enginedependency.xmlschema to treat "path" as a Source instead of a Product
2) During XmlBuilderWorker, pulls out the path dependencies - and only if they are (a) SourceFiles and (b) have wildcards, does it add them as source dependencies.
By adding / removing files under a wildcard capture and checking to see the dependencies are indeed updated.
=> Setting wildcard paths in engine dependencies xml files to SourceFiles

Code/Tools/ProjectManager/Source/ProjectExportController.cpp, Code/Tools/ProjectManager/Source/ProjectExportWorker.cpp, Code/Tools/ProjectManager/Source/ProjectExportWorker.h, Code/Tools/ProjectManager/Source/ProjectInfo.h, Code/Tools/ProjectManager/Source/ProjectsScreen.cpp, scripts/o3de/ExportScripts/export_source_android.py, scripts/o3de/ExportScripts/export_source_built_project.py
This PR fixes https://github.com/o3de/o3de/issues/18226.
At the end of export, a new dialog window appears for all standardized export platforms, where clicking "Yes" opens the folder containing the exported contents of the project.
Testing was performed manually on a Windows machine. The export processes for PC and Android was tested and verified to correctly show the exported files in the OS file explorer, and also to not affect the Project Card's build indicator. Error cases in exporting also confirmed that the build indicator was not affected.
=> fixing export button to not affect build indicator, and to show exported files in the end

Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/UnifiedAttachmentDescriptor.h, Gems/Atom/RHI/Code/Source/RHI.Reflect/UnifiedAttachmentDescriptor.cpp, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassAttachment.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/PassAttachmentReflect.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassAttachment.cpp, Gems/Atom/RPI/Code/Source/RPI.Reflect/Pass/PassAttachmentReflect.cpp
This PR adds the option to define a default buffer view for transient image and buffer attachments, such that a buffer/image view does not need to be defined when the attachment is used in a slot in a different pass and the default view is sufficient. This is especially useful when defining the size of a transient buffer in c++ in `BuildInternal()` (eg. when using a constant from c++ as the buffer size) of a pass class, and then using the same attachment in multiple different passes. Without this change, each pass who uses the attachment would need to update its buffer view separately. With this change, only the buffer declaration needs to be updated.
An alternative would of course be to use an imported buffer/image, but this would also require additional code to manage the resource and …
=> Add option to set a default buffer/image view for transient buffer/image attachments

Code/Framework/AzFramework/AzFramework/Input/System/InputSystemComponent.cpp
It is bugfix to #18208 
I used following setreg file:
```
{
"O3DE":
{
"InputSystem":
{
"Mouse":
{
"CaptureMouseCursor": false
}
}
}
}
```
I've run following configurations:
- Editor with CaptureMouseCursor set to false - OK 
- Editor with CaptureMouseCursor set to false - OK
- GameLauncher (ap before) with CaptureMouseCursor set to false OK
- GameLauncher (ap before) with CaptureMouseCursor set to true OK
- GameLauncher(ap before), headless with CaptureMouseCursor set to true OK
- GameLauncher(ap before), headless with CaptureMouseCursor set to false OK
=> Allow to disable mouse capture in Editor

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp, Gems/Atom/RPI/Code/Tests/Pass/PassTests.cpp
Adds a new method: `Pass::ChangeConnection`. Used to change how an Input or InputOutput slot is connected to a slot from a different pass.
ASV: https://github.com/o3de/o3de-atom-sampleviewer/pull/688
=> Add Pass::ChangeConnection.

Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
Actors in the scene would cause a crash "randomly" when
* duplicated
* spawned new instances
* ctrl-g
* FBX Settings panel accesed and changed
see
https://github.com/o3de/o3de/issues/18027
The crash was caused by the mesh feature processor releasing the last reference to the actors stream buffers when the thumbnail previewer was asked to make a preview of it (which happens when you save the FBX settings, or view a thumbnail, or when the mesh changes on disk, browse to it in the asset browser for the first time this session, etc). 
Note that the crash would occur later (so not when you viewed a thumbnail or browsed or saved the settings) but was primed to occur later by viewing a thumbnail, hence it seeming like a random crash.
The main sequence of events leading to the crash is that the …
=> Fixes a crash when actors are in the scene and thumbnailer accesses it.

Code/Editor/IEditor.h, Code/Editor/IEditorImpl.cpp, Code/Editor/IEditorImpl.h, Code/Editor/Lib/Tests/IEditorMock.h, Gems/LyShine/Code/Editor/HierarchyClipboard.cpp
This abstraction seems a bit unnecessary. I simply just inlined the implementation.
=> feat: remove CreateQMimeData from IEditor

cmake/Platform/Common/Install_common.cmake
Cherry picks https://github.com/o3de/o3de/pull/18231 which fixes an installer issues where gems cannot be resolved
Tested with locally built installer
=> Fix for missing gem.json in packaged Gems from the installer (#18231)

Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorTab.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorTab.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorWidget.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorWidget.h
Fixes issue: https://github.com/o3de/o3de/issues/14878
There were actually 2 issues that caused this.
One is a use-after-free, it would attempt to talk to the tab after the tab was deleted, by deleting the tab prematurely in the save handler, instead of on close.
The other was the assumption that the source control "RequestEdit" operation was synchronous.  It is not - it exits immediately after queuing the event and will invoke the lambda later, during TickBus / System Tickbus on the main thread.
However, the code calling the function clearly expected it to block until complete, since after leaving that scope it would clean up objects (deleting tabs, closing windows, etc).
Just manual testing.  This was a 100% crash and it even corrupted data files since it brought the app down during …
=> bugfix - Fixes crash on close of AssetEditor when you click "save"

Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/PassData.h, Gems/Atom/RPI/Code/Source/RPI.Reflect/Pass/PassData.cpp
This PR adds the missing include file `<Atom/RHI.Reflect/Limits.h>` to `PassData.h`, since later the struct `PassData` uses `RHI::MultiDevice::InvalidDeviceIndex` to initialize a member variable, which is defined in `Limits.h`.
This error was not visible since the include order in `PassData.h` is not as it is commonly recommended, with the main header file (the corresponding .h file to a .cpp file) in the topmost position. Clang-format would not sort the includes correctly in this case, since it does not recognize a main include if it uses anglebrackets. Therefore, I added a blank line after the main include.
There is the rather new format option `MainIncludeChar: AngleBracket` which could be used to fix this, but I am not sure whether adoption of clang-format 19 is widespread enough to …
=> Add missing include in PassData.h

scripts/build/Platform/Linux/build_config.json
This fixes the missing monolithic assets that were missing from the Linux debian package. This uses the same steps to build the full default + monolithic support installs for the SDK as found in the windows install steps.
Fixes https://github.com/o3de/o3de/issues/18250
Built the installer locally and followed the steps described in https://github.com/o3de/o3de/issues/18250
=> Add monolithic assets that were missing from the Linux installer

Code/Framework/AzCore/AzCore/Component/Entity.cpp
This PR make an error message when multiple, conflicting components are being activated. It can help to navigate issues like:
https://github.com/o3de/o3de/issues/18234
It can be considered as partial bugfix, and its impact on existing stabilized codebase is minimal.
I am asking reviewers to accept this contribution as bugfix to stabilization/2409.
Run with PhysX and PhysX5 gem activated together.
=> Adjusment to error message with incompatible components activation

Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorTab.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorTab.h, Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorWidget.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorWidget.h
This cherry-picks the changes already submitted from https://github.com/o3de/o3de/pull/18216 from stabilization into development.
Fixes issue: https://github.com/o3de/o3de/issues/14878
There were actually 2 issues here, both are fixed by this.
One is a use-after-free, it would attempt to talk to the tab after the tab was deleted, by deleting the tab prematurely in the save handler, instead of on close.
The other was the assumption that the source control "RequestEdit" operation was synchronous.  It is not - it exits immediately after queueing the event.  This caused the code to leave scope and clean up (including deleting the variables in lambda captures) before the operation was complete.
ust manual testing. This was a 100% crash and it even corrupted data files since it brought the app …
=> Fixes crash on close of Asset AssetEditor (#18216)

Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridBlendDistancePass.cpp, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridBlendIrradiancePass.cpp, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridBorderUpdatePass.cpp, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridClassificationPass.cpp, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridPreparePass.cpp, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridRayTracingPass.cpp, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridRelocationPass.cpp, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridRenderPass.cpp, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridVisualizationPreparePass.cpp, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridVisualizationRayTracingPass.cpp
There was spurious warning from SRG compilation when DiffuseProbe grid was used with more than one pipeline. 
It can be considered a minor bug fix to spurious warning message.
Run with ROS 2 camera using :
https://github.com/o3de/o3de/pull/18254
=> Adjust DiffuseProbeGrid to prevent multiple SRG compilations

Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
Fixes an issue where setting a Material's image property will fail, as the value gets erroneously converted to an asset id.
On PC, using a custom shader & material with an image property.  Setting the property to a runtime create AttachmentImage now succeeds as expected.
=> Remove bad check for RPI::Image to return an AssetID.

Code/Framework/AzCore/AzCore/Serialization/Json/JsonSerializationMetadata.inl
Removed an include of a file of itself.
The include didn't break anything so far because the file contains a `#pragma once`.
Compiled on Windows using clang.
=> remove an extraneous include

Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserFilterModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTableViewProxyModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTreeToTableProxyModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.cpp
Fixes issue https://github.com/o3de/o3de/issues/18051
This was caused by a number of asynchronous things happening when searches were being performed.  The main problem was actually a series of out of order operations where, for example, the search criteria changed before the view was ready to switch between search and non-search.
This also has a side effect of reducing the flicker when thumbnails are updating, and speeds up the search process significantly.
It also fixes an unreported bug where repeatedly searching then clearing the search would result in the table view not updating and being blank.
Tested each available view of Asset Browser (tree, table, thumbnail) while 
* searching for various terms rapidly
* clearing the search, adding new search terms
* incremental searches
* …
=> Fix asset browser freeze and crash when repeatedly searching.

cmake/Gems.cmake
This PR fixes a CMake error when an optional dependency, eg. from "gem_names" in project.json" is not present. This is most prominently used in AtomSampleViewer, which adds optional dependencies for `OpenXRVk` and `XR`.
Without this fix, I get the following error message when I try to bulid AtomSampleViewer:
```
CMake Error at cmake/Gems.cmake:111 (message):
Unable to locate gem path for Gem "OpenXRVk".  Is the gem registered in
either the ~/.o3de/o3de_manifest.json, D:/code/o3de/engine.json, any
project.json or any gem.json which itself is registered?
```
After this fix, the optional dependencies are ignored correctly, and I can build AtomSampleViewer successfully.
@spham-amzn Since you touched this code most recently, is this the correct place to add the new check?
Add AtomSampleViewer …
=> Fix optional dependencies in project.json not working correctly

Gems/Atom/RPI/Code/Source/RPI.Public/GpuQuery/Query.cpp, Gems/Atom/RPI/Code/Tests/System/GpuQueryTests.cpp
Currently there is a warning every frame due to AssignNewFrameIndexToSubQuery is being executed multiple times if we have multiple devices.
This warning is unnecessary and running AssignNewFrameIndexToSubQuery multiple times in a frame is kind of expected after we introduce multi devices support, we might run a pass on multiple devices multiple times like we did in #18159 .
Therefore, this PR removes this warning.
Tested on Windows with 2 devices.
=> Fix of AddScopeQueryToFrameGraph being executed multiple times.

Gems/Atom/RHI/Vulkan/Code/Source/RHI/TimelineSemaphoreFence.cpp
This fixes a potential issue where a CPU thread is waiting on a Timeline Semaphore Fence, and another thread calls reset() on the Fence, which increases the value of m_pendingValue.
Since `vkWaitSemaphores` uses a pointer to the pending value, this could mean, depending on how exactly the driver implements this, that the value the Fence is waiting for now changed, and will never be triggered.
This seemingly fixes a spurious deadlock issue with `AttachmentReadback`, if we use it to read some statistics values from the GPU each frame in combination with shader hot reloading. 
The `AttachmentReadback` deadlock doesn't occur anymore.
Windows and Vulkan, RTX 3090, driver version 560.70
=> Fix a potential deadlock with Vulkan Timeline Semaphores

Gems/Atom/RPI/Code/Source/RPI.Public/Pass/AttachmentReadback.cpp
Due to some race conditions (mostly caused by shader hot reload), an `AttachmentReadback` - Object is reset (e.g. from the destructor) before the readback was triggered by the GPU. During the readback later the callback function then tries to access non-existent readback items and crashes.
Have a continuous `AttachmentReadback` for various statistics running while causing shader hot reloads sometimes triggered an exception in that function. This seemingly doesn't happen anymore. 
Tested on Windows and Vulkan
=> Fix a spurious crash with AttachmentReadback

Gems/Atom/RHI/Vulkan/Code/Source/RHI/Conversion.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
Fixed bug that occurs when a device supports both
"Fragment Shading Rate" and "Fragment Density Map".
The solution is to give exclusive priority to "Fragment Rate Shading" when
defining the Format Capabilities for "RHI::FormatCapabilities::ShadingRate".
By checking only one of them, we avoid color format selection errors when looking
for color formats compatible with RHI::FormatCapabilities::ShadingRate.
Otherwise the runtime may end up using color formats that are ONLY supported for "Fragment Density Map"
when trying to use "Fragment Shading Rate" feature.
This error was evident when enabling the XR Gem, because the
FoveatedImagePass was using a color format for the Shading Rate
attachment that was only compatible with a Density Map attachment.
The following validation error disappeared …
=> Shading rate attachment format fix

python/python.sh, scripts/o3de/o3de/export_project.py
This fixes the project export script on Linux with ROS2 enabled. Also removes the default seedlist path from the settings since not all of the templates will have this.
The o3de export-project command will use a python venv from O3DE's embedded python rather that the system one. This causes problems when trying to export ROS2 enabled O3DE projects because the ROS2 gem performs ros2 system validation, which includes the detection of some python modules. 
```
Traceback (most recent call last):
[INFO] root:   File "/opt/ros/humble/share/ament_cmake_core/cmake/package_templates/templates_2_cmake.py", line 21, in <module>
[INFO] root:     from ament_package.templates import get_environment_hook_template_path
[INFO] root: ModuleNotFoundError: No module named 'ament_package'
```
When the o3de …
=> Fix project-export for ROS2 enabled projects on Linux

Gems/AtomLyIntegration/CMakeLists.txt
This PR fixes a missing alias in `Gems/AtomLyIntegration/CMakeLists.txt` for the HeadlessServer target. Without this change I get the following linker error when trying to build the MyTestProject.HeadlessServerLauncher target (MyTestProject depends on an internal gem which depends on various Atom targets and the AtomLyIntegration.Common target):
```
Atom_AtomBridge.lib(AtomBridgeModule.cpp.obj) : error LNK2005: 
"public: __cdecl AZ::AtomBridge::Module::Module(void)"
(??0Module@AtomBridge@AZ@@QEAA@XZ) already defined in
Atom_AtomBridge.Headless.lib(AtomBridgeModule.cpp.obj)
Atom_AtomBridge.lib(AtomBridgeModule.cpp.obj) : error LNK2005:
"public: virtual class AZStd::vector<struct AZ::Uuid,class AZStd::allocator>
__cdecl AZ::AtomBridge::Module::GetRequiredSystemComponents(void)const " …
```
=> Add missing alias for Atom_AtomBridge.HeadlessServers

Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingPipelineState.cpp
Fixes the Vulkan validation error
```
vkDebugMessage: [ERROR][Validation] Validation Error: [ VUID-vkDestroyPipeline-pipeline-00765 ] Object 0: handle = 0x5555581e0070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bdce5fd | Cannot call vkDestroyPipeline on VkPipeline 0x65908900000009ac[] that is currently in use by a command buffer. The Vulkan spec states: All submitted commands that refer to pipeline must have completed execution (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkDestroyPipeline-pipeline-00765)
```
which appears when a RayTracingPipelineState is freed while a frame using it is still in flight.
Running the ASV RHI Ray Tracing sample switching to another sample.
=> Fix validation error of ray-tracing pipeline still in use.

scripts/o3de/o3de/export_project.py
Add check for the require 'tix' package needed for tkinter configuration of the project export screen. The `tix` package is required along with the `tk` package if you want to use the configuration ui for project export with the following command
`o3de.sh export-project --configure` . 
This fix, in conjunction with https://github.com/o3de/o3de.org/pull/2580 will provide better messaging and instructions to resolve the system dependency.
Fixes https://github.com/o3de/o3de/issues/18246 
Followed the step of `o3de.sh export-project --configure`  with and without the `tix` package installed on Ubuntu
=> Improve messaging for missing Tix package

Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/Serialization/Locale_UnixLike.h
Fixes the following compilation error on Mac:
```
In file included from /Users/o3de/github/o3de/Code/Framework/AzCore/Platform/Mac/AzCore/Serialization/Locale_Platform.h:10:
/Users/o3de/github/o3de/Code/Framework/AzCore/Platform/Mac/AzCore/Serialization/../../../Common/UnixLike/AzCore/Serialization/Locale_UnixLike.h:22:17: error: unknown type name 'locale_t'
locale_t m_createdLocale;
^
```
Built on Mac locally
=> Fix compile error for Mac

Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/BasePBR/BasePBR_VertexEval.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/EnhancedPBR/EnhancedPBR_LightingBrdf.azsli
This PR fixes two calls of the 8-parameter version of the `EvaluateVertexGeometry_BasePBR` function, where the last three parameters were not in the correct order, and a missing `#endif`.
The function `EvaluateVertexGeometry_BasePBR` is defined in `BasePBR_VertexEval.azsli`, and the last three parameters are `..., uint instanceId, bool useVertexColor0, float4 color0)`. I found this mismatch because the AssetProcessor was showing warnings like `.../BasePBR_VertexEval.azsli:98:96: warning: implicit truncation of vector type [-Wconversion]`.
Run the AssetProcessor and check if the mentioned warnings no longer occur.
=> Fix parameter order in calls to EvaluateVertexGeometry_BasePBR

Code/Framework/AzCore/AzCore/Math/Matrix4x4.cpp, Code/Framework/AzCore/Tests/Math/Matrix4x4Tests.cpp, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/MatrixUtility.azsli
The funciton `Matrix4x4::GetInverseTransform` uses `Constants::Tolerance` (0.001) to determine if a given matrix can be inverted by checking if the determinant is smaller than this value. This is not sufficient for matrices which contain scales smaller than around 0.1, eg. the following matrix with uniform scale of 0.1 could not be inverted by this function, as its determinant is 0.001, which is exactly the epsilon value:
```
/ 0.1  0   0   0 \
|  0  0.1  0   0 |
|  0   0  0.1  0 |
\  0   0   0   1 /
```
The proposed solution removes the epsilon value, ie. sets it to 0, for the following reasons:
* One function further down in the function `GetInverseFull` an epsilon value of 0 is used
* Other libraries, such as [glm](https://github.com/g-truc/glm/blob/33b4a621a697a305bc3a7610d290677b96beb …
=> Fix epsilon of GetInverseTransform function being too large

cmake/Platform/Common/RuntimeDependencies_common.cmake
When a gem contains an `OBJECT` cmake target (as is suggested for "private" targets in the [Gem public/private API RFC](https://github.com/o3de/sig-core/issues/37); but this specific part of the RFC was apparently never really adopted, neither for the gem template nor for existing gems), and this gem is then used by a project which uses a SDK build of the engine, there is the following cmake error (in this case I registered the o3de/install folder as an engine source):
```
CMake Error at D:/code/o3de/install/cmake/Platform/Common/RuntimeDependencies_common.cmake:233 (message):
OBJECT_LIBRARY Library MyGem.Private.Object specified
MAP_IMPORTED_CONFIG_PROFILE = PROFILE; but did not have any of
IMPORTED_LOCATION_xxxx set
Call Stack (most recent call first): …
```
=> Ignore imported object libraries as dependency when generating runtime dependencies

Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp, Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp, Gems/Multiplayer/Code/Tests/LocalRpcTests.cpp
Fix for network packet being corrupted on the host causing the packet that's received by client to end up having no data attached.
GetNetBindComponent()->GetSendAuthorityToAutonomousRpcEvent().Signal(rpcMessage) ends up calling 2 callbacks
1. NetworkEntityManager::HandleLocalRpcMessage. This is the one that ends up leaving rpcMessage in a bad state
2. EntityReplicator::OnSendRpcEvent
HandleLocalRpcMessage would store the packet to a list via std::move and cause the packet to become invalid for anyone trying to use the packet in a later callback.
Also ensures that the client-server only tries to locally handle Authority->Autonomous RPCs if it's indeed the player. Otherwise you'll rightly receive an asset on the client-server "Entity proxy does not have autonomy", because it's the remote …
=> Unified Launcher Stream Error Fix

Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/IndirectRendering.azsli, Gems/Atom/Feature/Common/Code/Source/PostProcessing/BloomDownsamplePass.cpp, Gems/Atom/Feature/Common/Code/Source/PostProcessing/FastDepthAwareBlurPasses.cpp, Gems/Atom/Feature/Common/Code/Source/PostProcessing/NewDepthOfFieldPasses.cpp, Gems/Atom/Feature/Common/Code/Source/PostProcessing/SubsurfaceScatteringPass.cpp, Gems/Atom/Feature/Common/Code/Source/PostProcessing/SubsurfaceScatteringPass.h, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.cpp, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.h, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPassData.h, Gems/Atom/RHI/Code/Include/Atom/RHI/DispatchRaysItem.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/ComputePass.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/ComputePassData.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ComputePass.cpp, Gems/Atom/RPI/Code/Source/RPI.Reflect/Pass/PassData.cpp
This adds a "IndirectDispatch" flag and a "IndirectDispatchBufferSlot", which assumes whatever buffer is attached to the slot uses the `DispatchIndirectCommand`  or the `DispatchRaysIndirectCommand` structure and contains the desired number of threads, to allow Indirect Dispatch of Compute and Raytracing - passes from the .pass file. 
Additionally, currently both the ComputePass and RayTracingPass have the flag "Make Fullscreen Pass", which selects the first input or inputOutput slot and uses it as source for the number of threads. This can be somewhat brittle, since the number of threads can then unintentionally change simply by re-orders the slots during development.
This PR now also adds a "FullscreenSizeSourceSlot" field that allows selecting the slot name that will be used to …
=> Indirect Dispatch and updated Fullscreen Dispatch for RPI::ComputePass and RPI::RayTracingPass, 

Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/Serialization/Locale_WinAPI.h
Prevent an assert on O3DE startup on my computer given that the locale is higher than the string size. Follow-up to https://github.com/o3de/o3de/pull/18171
(got  "LC_COLLATE=C;LC_CTYPE=English_United Kingdom.1252;LC_MONETARY=C;LC_NUMERIC=C;LC_TIME=C" in local on windows)
Local build and launch
=> Fix assert on startup by extending a fixed string size

Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.h, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
Reverts the previous change that creates multiple scopes within one pass and creates multiple passes instead.
The reason is to follow the convention that every pass runs on one device only (each pass has a device index).
Tested in the ASV.
=> One RayTracingAccelerationStructurePass per device

Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp, Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp, Gems/Multiplayer/Code/Tests/LocalRpcTests.cpp
Cherry pick https://github.com/o3de/o3de/pull/18294 from 2409
Fix for network packet being corrupted on the host causing the packet that's received by client to end up having no data attached.
GetNetBindComponent()->GetSendAuthorityToAutonomousRpcEvent().Signal(rpcMessage) ends up calling 2 callbacks
1. NetworkEntityManager::HandleLocalRpcMessage. This is the one that ends up leaving rpcMessage in a bad state
2. EntityReplicator::OnSendRpcEvent
HandleLocalRpcMessage would store the packet to a list via std::move and cause the packet to become invalid for anyone trying to use the packet in a later callback.
Also ensures that the client-server only tries to locally handle Authority->Autonomous RPCs if it's indeed the player. Otherwise you'll rightly receive an asset on the client-server …
=> Cherry Pick: Unified Launcher Stream Error Fix

scripts/o3de/o3de/export_project.py
* Add check for the require 'tix' package needed for tkinter configuration of the project export screen
Cherry picks https://github.com/o3de/o3de/pull/18252 into development
=> Cherry-pick : Improve messaging for missing Tix package

python/python.sh, scripts/o3de/o3de/export_project.py
Cherry picks https://github.com/o3de/o3de/pull/18293
* Update python.sh to use system python when running o3de export-project in a ROS2 enabled environment
=> Cherry Pick : Fix project-export for ROS2 enabled projects on Linux

Code/Tools/ProjectManager/Source/ProjectUtils.cpp, Code/Tools/ProjectManager/tests/UtilsTests.cpp
The python layer is not available while testing these functions.
Code was added in commit # c9c732b5d94 from https://github.com/o3de/o3de/pull/18037 that made it hit the python interface when deleting folders but that interface isn't available and nullptr when unit testing.
Also makes it work in parallel by using temp folders instead of real ones.
running the actual aztest module across this, in debug, on windows, with the crt heap checker enabled + leak detection enabled and whiteboxing every path.
=> Fixes a crash / nullptr dereference in MoveProject_MovesExpectedFiles

Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/Serialization/Locale_WinAPI.h
This PR picks #18312 from stabilization/2409 to development.
I am having the same issue in development, in Chinese environment, the `getlocale` returns 
```
LC_COLLATE=C;LC_CTYPE=Chinese (Simplified)_China.utf8;LC_MONETARY=C;LC_NUMERIC=C;LC_TIME=C
```
It is longer than 85, then I am getting exactly the same assert. And I found that it's been fixed in stabilization/2409.
Tested in Chinese environment.
=> Cherry pick locale fix from stabilization/2409 to development

Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/BasePBR/BasePBR_VertexEval.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/EnhancedPBR/EnhancedPBR_LightingBrdf.azsli
Cherry pick from dev to stab/2409
Fix parameter order in calls to EvaluateVertexGeometry_BasePBR
Run PC
=> [Cherry-pick] Fix parameter order in calls to EvaluateVertexGeometry_BasePBR (#18302)

Gems/Atom/Feature/Common/Assets/Passes/Mobile/Subpass3Parent.pass
Subpass3Parent.pass is having the same template name as Subpass2Parent.pass, which would cause some error in some of our scripts. I think it's a typo. This PR fixes it.
Tested on Windows
=> Typo fix of MobileSubpass3ParentPassTemplate

Gems/Atom/RHI/Metal/Code/Source/RHI/Conversions.cpp, Gems/Atom/RHI/Metal/Code/Source/RHI/Conversions.h, Gems/Atom/RHI/Metal/Code/Source/RHI/ImageView.cpp
Sometimes depending on the shadow atlas the shadow map texture would only have an array size of 1 which meant that the shadow map texture was getting tagged as texture 2d. This meant that the drivers were silently always returning the first pixel in the texture during the forward pass with no warning or api validation error (This is a driver issue which is getting addressed now). This fix recreates the view and tags the texture correctly as a texture2darray.
Tested Editor by creating a simple spot light and enabling shadows.
=> Fix shadows Projected + Directional shadows on Metal

Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp
Fixes https://github.com/o3de/o3de/issues/18305 by moving the `RaytracingAccelerationStructurePass` back to the Graphics queue
Opened a levelthat previously failed when changing the `r_displayInfo` to `1`
=> Move RaytracingAccelerationStructurePass back to Graphics Queue for 2409

AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py
The variable needed to be a class variable, not an instance one.
Actually properly increases the test timeout as expected.
This time I actually had a debugger break in python to actually inspect the timeout value.
Last time I was running the automated test suites and slowing it down to try to make it fail.
=> Fixes the multiplayer connectivity test timeout

Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshInputBuffers.cpp, Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceGeometryView.h, Gems/Atom/RHI/Code/Include/Atom/RHI/GeometryView.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Model/ModelLod.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Model/ModelLodAssetCreator.h, Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Model/ModelLod.cpp, Gems/Atom/RPI/Code/Source/RPI.Reflect/Model/ModelAssetHelpers.cpp, Gems/Atom/RPI/Code/Source/RPI.Reflect/Model/ModelLodAssetCreator.cpp
1. Made some naming more explicit so the code is easier to follow (for example m_drawPacketListsByLod -> m_meshDrawPacketListsByLod  and  meshDataIter -> modelDataIter)
2. Added SetStreamBufferView to GeometryView to allow setting an individual stream buffer view without having to clear and set all the stream buffer views.
3. Added ReleaseTrackedBuffers() so custom components could release tracked buffer references from ModelLod
4. Changed SetMeshAabb(AZ::Aabb&& aabb) to SetMeshAabb(AZ::Aabb aabb) to make it useable in more scenarios (if there's a good reason this should use move semantics please let me know).
=> Model and geometry view changes

Gems/ScriptCanvasDeveloper/Code/CMakeLists.txt
Fix issue https://github.com/o3de/o3de/issues/17572
Sig-Release has decided that this should be APPROVED for stabilization 2409
Tools modules should depend on the Tools modules of other dependencies.  SCD was depending on the runtime version of ImGUi, which was in turn depending on the runtime version of LmbrCentral.
1. Built an install version of O3DE from latest stabilization
2. Created a default game project with no changes
3. Verified that it works fine
4. used the project manager to add just Script canvas Developer to it
5. Verified that the problem occurs, and editor fails to start up
6. Made this one line change to the scripts
7. Rebuilt the installer
8. rebuilt the project based on this new installer with the fix
9. Problem is gone and SCD works.
=> Fixes a crash if you enable Script canvas developer Gem

Gems/Atom/Feature/Common/Assets/Shaders/Materials/Skin/Skin_SurfaceEval.azsli, Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/BlendColorGradingLuts.azsl, Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/LookModificationTransform.azsl, Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.cpp, Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.h, Gems/Atom/RHI/Metal/Code/Source/RHI/Conversions.cpp, Gems/Atom/RHI/Metal/Code/Source/RHI/Conversions.h, Gems/Atom/RHI/Metal/Code/Source/RHI/ImageView.cpp
- Cherry pick the shadow fix from stab - https://github.com/o3de/o3de/pull/18326
- Fix compile errors from Geometryview change 
- Fix runtime errors due to function constants change. O3DE can not track type uint for function constants and hence the drivers complain during PSO compilation - 
```
Constant o_numSourceLuts_tmp (0) is of type MTLDataTypeUInt but value found has type MTLDataTypeInt
```
Tested Editor on AutomatedTesting.
=> Fix various Mac related issues.

Code/Framework/AzCore/AzCore/Serialization/AZStdContainers.inl
Fixes issue https://github.com/o3de/o3de/issues/18348
NOTE: Pending approval for inclusion into stabilization. 
The function that it depended on was simply not implemented. While it is not ideal for it to walk the memory linearly when removing an element from a set, it's still worth implementing for cases where the set is being used in a way that relies on indices, which is the case for the UI.
It was a 100% repro before applying this.  If you look at the code, its implementing an unimplemented function.
Anything calling this code would have crashed or failed before, since the function was unimplemented.
After this, I can work on unordered sets in the UI without it crashing.  Its possible it fixes other containers with no index (such as sets).
=> Fixes a crash when you try to remove elements from unordered set.

Gems/Atom/RPI/Code/Include/Atom/RPI.Builders/Model/ModelExporterContexts.h, Gems/Atom/RPI/Code/Source/RPI.Builders/Model/MaterialAssetBuilderComponent.h, Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.h, Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelExporterComponent.cpp, Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelExporterContexts.cpp, Gems/Atom/RPI/Code/atom_rpi_builders_files.cmake
We have a Gem that adds additional data to every submesh of every created Model Asset file.
This PR adds a new build context that's executed after a Model Asset is finished building, where we generate this additional data.
I also needed to move the `ModelExporterContexts.h` file into an include directory so the new context can actually be used.
Tested on Windows with and without a Gem that uses the new processing step.
=> AssetBuilder: Model Exporter: Add step after model asset creation

Gems/Atom/RHI/Code/Include/Atom/RHI/DrawArguments.h
Indirect draw argument does not necessarily have `m_countBuffer` (the `m_maxSequenceCount` can also be used to specify the number of operations). Now the code doesn't check whether it's null before accessing it, if someone sends an indirect draw without count buffer, an access violation would happen.
This PR fix it by checking it before accessing, just like what it is usually done in `DispatchRaysArguments` and `DispatchArguments`
Tested in Windows
=> Check count buffer of indirect draw arguments before accessing.

Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
This PR adds interface to `RayTracingFeatureProcessor` and `MeshFeatureProcessor` to access some of the members that are necessary for Gems to implement some features that need to scan over ray tracing meshes.
Tested in Windows
=> Add interface to expose members that are not necessary to be kept private

Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp, Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.h, Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.cpp, Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.h, Code/Framework/AzFramework/Platform/Linux/AzFramework/AzFramework_Traits_Linux.h, Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp
When running O3DE on AWS EC2 using NiceDCV as the remote client viewer, O3DE is unable to trap/set the mouse cursor position when in camera 'free-look' mode. It may be caused by the remote client itself is setting the cursor position independently and not getting the set cursor messages that O3DE is setting through XCB. This PR adds a work-around that will at least make the Editor usable in this remote client scenario by not relying on the actual mouse position but instead tracking the 'expected' mouse position and calculating the delta from here. This scenario cannot be detected in the Editor so a cvar was created to enable this fix.
For game mode, its possible to detect this situation by evaluating what the mouse movement deltas are being received by O3DE. Game mode does not require the …
=> Fix hyper-sensitve camera rotation remote clients

Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp, Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
Fixes a situation where if two or more sources create a cyclic dependency, the Asset Processor won't infinitely add them into the analysis pass
Locally running the Asset Processor, ensuring that the situation where a cyclic depedency is found, the previously-examined file is not re-examined.
=> Asset Processing:  Handling cyclic source dependencies

Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp, Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.h, Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.cpp, Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.h, Code/Framework/AzFramework/Platform/Linux/AzFramework/AzFramework_Traits_Linux.h, Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp
Cherry picks the fix for hyper-sensitive camera rotations on remote clients:
* Add CVAR to control whether or not to capture mouse movements to calculate mouse-controlled camera rotations
* Make the mouse capture cvar option Linux only through PAL traits
* Change xcb client to detect if the mouse position capture does not work on the system instead of relying on the cvar
=> Cherry Pick: Fix hyper-sensitive camera rotation remote clients (#18354)

Registry/AssetProcessorPlatformConfig.setreg, Registry/sceneassetimporter.setreg
Enables importing simple (non-reference) USD files
Tested by loading a USD
=> Asset Import Universal Scene Description (USD) Files

Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.h
fixes issue https://github.com/o3de/o3de/issues/18365
Note that Stabilization branch is locked, I will open an exception request.
The hook to register and unregister actions happens once during startup, and is not meant to have any connection to the lifetime of the objects.
The crash was happening because the EditorTransformComponentSelection object was being destroyed and recreated every time you enter pick mode, but its action registration captured its 'this' pointer.
usually, such action registration would be placed inside some kind of long lived singleton "manager" object, aka a system component, but in this case, it was put in an ephemeral object.  note that this is still a singleton object, there is only ever one of it, and it is essentially the "manager", its just special in that …
=> Fix crash after leaving picking mode

Code/Editor/splashscreen_background.png
Updates the splash screen for version 2409 to
Launched the Editor and verified the updated splash screen
=> Update O3DE Splash Screen background

Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp, Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.h
Adds a `m_modelChangedEventHandler` to the `meshDescriptor` of `AtomActorInstance`s.
The callback was introduced in https://github.com/o3de/o3de/pull/17309 but not added to actor meshes.
The `MeshComponentNotificationBus::Events::OnModelReady` and `MeshHandleStateNotificationBus::Events::OnMeshHandleSet` events thus always contained a null model.
I also added the entity id to the `meshDescriptor`. It was introduced in https://github.com/o3de/o3de/pull/18131
I'm not sure this is correct, but it doesn't seem to break anything. @gadams3 Does this make sense for actors?
Tested on Windows with an actor in the scene
Tested with the MainPipeline and a custom pipeline that relies on `MeshHandleStateNotificationBus::Events::OnMeshHandleSet` events
=> Added model change event listener to AtomActorInstance

Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponentTypes_Source.jinja
Catch, at compile time, if autogen registers the same Multiplayer auto-component multiple times.
Jinja logic creates a dictionary to track how many times each component is registered. It prints an error describing which auto-component and how many times it was registered (so users know how many instances they need to remove).
Fixes #18369
Purposely tried to register a multiplayer auto-component multiple times.
For example, by putting `Source/AutoGen/NetworkAnimationComponent.AutoComponent.xml` inside of both `multiplayersample_files.cmake` and `multiplayersample_autogen_files.cmake`
=> Multiplayer Component Registration: Compile Time Check for Duplicates 

Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridVisualizationAccelerationStructurePass.h
Introduces a forward declaration for `DiffuseProbeGrid` in the `DiffuseProbeGridVisualizationAccelerationStructurePass .h` header file, which currently worked only in the right include order and not stand-alone.
=> DiffuseProbeGridVisualizationAccelerationStructurePass header missing forward declaration

Gems/Atom/RHI/Code/Source/RHI/TransientAttachmentPool.cpp
As discussed on [Discord](https://discordapp.com/channels/805939474655346758/951793790425894973/1290464876526964769), `ImageView`s on `TransientAttachments` were recreated every frame.
The issue was that `ActivateImage/ActivateBuffer` was called twice in a row, once with `DontAllocateResources` and once without. 
The current implementation incorrectly freed the image/buffer every time the `DontAllocateResources` flag was set as the `DeviceTransientAttachementPool` did not return a `DeviceImage`.
The fix is to only clean up the `Image/Buffer` and subsequently the `m_cache` if resources should be allocated but fail for some reason.
Tested with samples in the `ASV`.
=> Fix issue where transient attachments are recreated

Gems/Atom/Feature/Common/Assets/Passes/BRDFTexture.pass, Gems/Atom/Feature/Common/Assets/Passes/BlendColorGradingLuts.pass, Gems/Atom/Feature/Common/Assets/Passes/BloomDownsample.pass, Gems/Atom/Feature/Common/Assets/Passes/CheckerboardResolveColor.pass, Gems/Atom/Feature/Common/Assets/Passes/ChromaticAberration.pass, Gems/Atom/Feature/Common/Assets/Passes/ContrastAdaptiveSharpening.pass, Gems/Atom/Feature/Common/Assets/Passes/DebugRayTracingPass.pass, Gems/Atom/Feature/Common/Assets/Passes/DepthDownsample.pass, Gems/Atom/Feature/Common/Assets/Passes/DepthOfFieldWriteFocusDepthFromGpu.pass, Gems/Atom/Feature/Common/Assets/Passes/DownsampleLuminanceMinAvgMaxCS.pass, Gems/Atom/Feature/Common/Assets/Passes/DownsampleMinAvgMaxCS.pass, Gems/Atom/Feature/Common/Assets/Passes/DownsampleSinglePassLuminance.pass, Gems/Atom/Feature/Common/Assets/Passes/EyeAdaptation.pass, Gems/Atom/Feature/Common/Assets/Passes/FilmGrain.pass, Gems/Atom/Feature/Common/Assets/Passes/FullscreenShadow.pass, Gems/Atom/Feature/Common/Assets/Passes/LuminanceHistogramGenerator.pass, Gems/Atom/Feature/Common/Assets/Passes/OpaqueParent.pass, Gems/Atom/Feature/Common/Assets/Passes/PaniniProjection.pass, Gems/Atom/Feature/Common/Assets/Passes/ReflectionScreenSpaceRayTracing.pass, Gems/Atom/Feature/Common/Assets/Passes/SkyVolumeLUT.pass, Gems/Atom/Feature/Common/Assets/Passes/SsaoCompute.pass, Gems/Atom/Feature/Common/Assets/Passes/SsaoParent.pass, Gems/Atom/Feature/Common/Assets/Passes/Taa.pass, Gems/Atom/Feature/Common/Assets/Passes/Vignette.pass, Gems/Atom/Feature/Common/Assets/Passes/WhiteBalance.pass, Gems/Atom/Feature/Common/Assets/Shaders/SkyAtmosphere/SkyVolumeLUT.azsl, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPassData.h, Gems/Atom/RPI/Code/Source/RPI.Reflect/Pass/PassData.cpp
This is a followup to [!18255](https://github.com/o3de/o3de/pull/18255), and renames some of the existing fields of the `ComputePassData` and `RayTracingPassData` to remove spaces.
Note that this is a separate PR since these changes are entirely optional, but do introduce breaking changes.
There are several options on this, which are equally valid, which is why i would like to get reviewer feedback on this.
- Option A: Rename fields to conform to the style of other `PassData` fields. 
- Option B: Rename new fields from the other PR and add spaces, to at least make the `ComputePassData` somewhat consistent, if not the `RayTracingPassData`.
- Option C: Do nothing/close this PR, since the field names are not _that_ important.
Vulkan on Windows
=> Harmonize ComputePassData and RayTracingPassData Field Names

Gems/Atom/RHI/Code/Include/Atom/RHI/FrameAttachment.h, Gems/Atom/RHI/Code/Include/Atom/RHI/FrameGraphAttachmentDatabase.h, Gems/Atom/RHI/Code/Include/Atom/RHI/TransientAttachmentPool.h, Gems/Atom/RHI/Code/Source/RHI/FrameGraphCompiler.cpp, Gems/Atom/RHI/Code/Source/RHI/TransientAttachmentPool.cpp
1. When MD transient attachments are not used on one device after they have been before, they were not removed properly and triggered asserts that attachments have been added to the frame graph that are not used.
2. The clear value needs to be set to the clear value from the first scope, so it needs to be retrieved from the device the first scope runs on. Therefore, we store that device index and use it to retrieve the optimized clear value.
With a sample that runs a pass on one device and then moves it to another device.
=> Fixing two issues with the frame graph when multi-device features are used.

Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/NsightAftermathGpuCrashTracker_Windows.cpp, Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/NsightAftermathGpuCrashTracker_Windows.h, Gems/Atom/RHI/Vulkan/Code/Source/Platform/Windows/RHI/NsightAftermathGpuCrashTracker_Windows.cpp, Gems/Atom/RHI/Vulkan/Code/Source/Platform/Windows/RHI/NsightAftermathGpuCrashTracker_Windows.h
Adapts to API changes for the NSight Aftermath GpuCrash Tracker, already introduced sometime in the beginning of 2023
Windows + Vulkan, set `LY_AFTERMATH_PATH` to `path/to/NVIDIA_Nsight_Aftermath_SDK_2024.2.0.24200` and compile the engine.
=> Adapt GpuCrashTracker to aftermath version 2024.2.0.24200

engine.json
Updates the engine version to `2.3.1` and copyright year to `2024`
Local testing on compiled installer
=> Bump engine.json version for point-release 24091

AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py, Gems/Atom/RPI/Code/Source/RPI.Private/RPISystemComponent.cpp
It cherry picks two existing test crash fixes from development into the 2409.1 point release
These PRs provide no conflicts and were already tested in dev. 
They fix the CRUD crash and the Multiplayer Timeout test failures.
See below - github shows the commits in this PR below this box.
=> Cherry pick two test crash fixes into the 2409.1 point release

Code/Editor/splashscreen_background.png, Code/Framework/AzCore/AzCore/Serialization/AZStdContainers.inl, Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp, Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.h, Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.cpp, Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.h, Code/Framework/AzFramework/Platform/Linux/AzFramework/AzFramework_Traits_Linux.h, Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.h, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindowSession.cpp, Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp, Gems/ScriptCanvasDeveloper/Code/CMakeLists.txt
Cherry-picks missed PRs from stabilization (`main` is the same) to development so they are not missed.
CI Build script and manual testing:
```
[ci_build] ctest -j12 -C profile --output-on-failure -L "(SUITE_smoke|SUITE_main)" -LE "(REQUIRES_gpu|REQUIRES_tiaf)" -T Test --no-tests=error
Build name: Win32-MSBuild
Create new tag: 20241015-2027 - Experimental
Test project D:/o3de-repos/o3de/build/windows
Start   7: AZ::AzFramework.NativeUI.Tests.main::TEST_RUN
Start  10: AZ::AzManipulatorTestFramework.Tests.main::TEST_RUN
Start  28: AZ::SerializeContextTools.Tests.main::TEST_RUN
Start  29: AZ::AssetBundler.Tests.main::TEST_RUN
Start  33: test_commit_validation.smoke::TEST_RUN
Start  46: cli_test_driver.main::TEST_RUN
Start  47: test_detect_file_changes.main::TEST_RUN
Start  48: …
```
=> Cherrypick stab to dev 03

Gems/Atom/RPI/Code/CMakeLists.txt, Gems/Atom/RPI/Code/Source/RPI.Edit/Common/DllMain.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/DllMain.cpp
This PR partially reverts [PR18315](https://github.com/o3de/o3de/pull/18315) because too many symbols are exported on Windows with a debug build (Windows dlls cannot export more than 2^16 symbols, which is exceeded in the `Atom_RPI.Public` target).
I want to keep the other changes of the original PR (mostly change `static const char*` in header files (+ definition in cpp file) to  `static constexpr char*`), which will be needed eventually if I want to properly convert these targets to shared libraries.
A proper solution is certainly possible, but not straight-forward:
* Add export macros to all classes (easy)
* Add additional macros to disable warnings about base classes not having a dll interface (`AZ_PUSH_DISABLE_DLL_EXPORT_BASECLASS_WARNING`, easy)
* Add additional macros to disable …
=> Change Atom_RPI shared libraries back to static libraries

Code/Editor/TrackView/TrackViewDopeSheetBase.cpp, Code/Editor/TrackView/TrackViewPythonFuncs.cpp, Code/Legacy/CryCommon/IMovieSystem.cpp, Code/Legacy/CryCommon/IMovieSystem.h, Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.cpp, Gems/Maestro/Code/Source/Cinematics/AnimNode.cpp, Gems/Maestro/Code/Source/Cinematics/AnimNode.h, Gems/Maestro/Code/Source/Cinematics/AnimPostFXNode.cpp, Gems/Maestro/Code/Source/Cinematics/AnimSplineTrack.h, Gems/Maestro/Code/Source/Cinematics/AnimTrack.h, Gems/Maestro/Code/Source/Cinematics/CompoundSplineTrack.cpp, Gems/Maestro/Code/Source/Cinematics/CompoundSplineTrack.h
I migrated the rest of the Get and set values for the node. wonder if this abstraction could be simplified a bit. All these separate overloaded functions seem kind of cumbersome. some kind of container seems more appropriate though. I was thinking of maybe something with a variant? 
ref: https://github.com/o3de/o3de/issues/9133
=> feat: migrate GetValue SetValue (GHI-1933)

Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshInstanceGroupList.cpp
The MeshModelInstance class, typically accesible from a MeshHandle, now offers a mechanism to report whenever a MeshDrawPacket within the MeshModelInstance has been updated via an AZ::Event of type:  
```cpp
using MeshDrawPacketUpdatedEvent =
Event<const ModelDataInstance&, const AZ::RPI::MeshDrawPacket&>;
```
This is important for FeatureProcessors that leverage the MeshFeatureProcessor to work with MeshHandles. Each time a MeshDrawPacket inside a MeshModelInstance changes, all the DrawItems get their DrawListTag enabled/disabled state reset.
If such reset occurs, a FeatureProcessor can now react to such event and force updating the ObjectSrg or DrawListTag Enable state as needed.
Tested on a game project where my FeatureProcessor now gets notified whenever there's a change in a …
=> Added MeshDrawPacket Update Event.

Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.cpp, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
Adds functionality/access for the manipulation of passes which are especially useful when inserting passes and changing connections automatically.
- Make `GetPassDescriptor` public.
- Add an overload of `ChangeConnection` with a pass name (supporting keywords such as `PipelineGlobal`) instead of a `Pass*`.
- Fix `DirectionalLightFeatureProcessor` child pass retrieval in case passes are inserted.
With a sample code that inserts passes into the pipeline and changes connections.
=> Extend Pass functionality to improve inserting passes.

python/python.cmd
This fixes O3DE command line python calls in windows environments where the %USERPROFILE% has spaces in the path (i.e. the user name has spaces) which is causing problems during the bootstrapping of Python on windows systems.
The python virtual environment is stored under the %USERPROFILE%/Python/venv root path, and calls to python via `python.cmd` is routed to the python script in the created venv. But the system calls to python is not double-quoted, which causes problems with the batch interpreter. 
While the actual python system call was double-quoted, the surrounding `activate` and `deactivate` calls were not. This addresses this issue.
Tested on a non-space %USERPROFILE% environment to ensure calls are still valid. 
Tested on a profile named "Test User" (whitespace in the …
=> Double-quote windows command calls to support spaces in paths

Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
I get the following validation error currently when the Vulkan device is initialized which this PR fixes:
```
vkDebugMessage: [ERROR][Validation] Validation Error: [ VUID-VkDeviceCreateInfo-pNext-pNext ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x901f59ec | vkCreateDevice: pCreateInfo->pNext chain includes a structure with unknown VkStructureType (1000458000); Allowed structures are [VkDeviceDeviceMemoryReportCreateInfoEXT, VkDeviceDiagnosticsConfigCreateInfoNV, VkDeviceGroupDeviceCreateInfo, VkDeviceMemoryOverallocationCreateInfoAMD, VkDevicePrivateDataCreateInfoEXT, VkPhysicalDevice16BitStorageFeatures, VkPhysicalDevice4444FormatsFeaturesEXT, VkPhysicalDevice8BitStorageFeatures, VkPhysicalDeviceASTCDecodeFeaturesEXT, …
```
=> Fix for Vulkan validation error when subpassMergeFeedback is not supported.

Gems/Atom/Asset/Shader/Code/AZSL/Platform/Android/Vulkan/AzslcHeader.azsli, Gems/Atom/Asset/Shader/Code/AZSL/Platform/iOS/Metal/AzslcHeader.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/BicubicPcfFilters.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/DirectionalLightShadowCalculator.azsli, Gems/Atom/RHI/Metal/Code/Source/RHI.Builders/ShaderPlatformInterface.cpp
1. Fix ios/Mac performance issues (20x drop) introduced via the introduction of [[clang::optnone]]
2. Address shadow banding issues due to half precision
3. Minor cleanup
Tested AutomatedTesting on iOS
=> Address various mobile fixes in the 24.09 release

Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/IndexableList.h, Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArray.cpp, Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArrayFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
Fix leaking of decal textures when reloading levels due to incorrect ref counting of RPI::View objects (which contains the View SRG that holds strong references to images) when copying/moving lambdas that captured a RPI::ViewPtr
Run PC and reload the level multiple times
=> Fix leaking of Decal textures when reloading levels

Gems/Atom/Feature/Common/Assets/Shaders/SkinnedMesh/LinearSkinningCS.azsl, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/SkinnedMesh/SkinnedMeshShaderOptions.h, Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshDispatchItem.cpp, Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshInputBuffers.cpp, Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshShaderOptionsCache.cpp, Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshShaderOptionsCache.h, Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshVertexStreamProperties.cpp, Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceGeometryView.h, Gems/Atom/RHI/Code/Source/RHI/Buffer.cpp, Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.cpp, Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/ActorAsset.cpp, Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp, Gems/EMotionFX/Code/EMotionFX/Source/Mesh.cpp, Gems/EMotionFX/Code/Include/Integration/ActorComponentBus.h, Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp
A recreation of #18426. Fix crash when importing an Actor with only blendshape but without skinning. Closes #18381. 
The implementation is made in the following aspects: 
- Mark `SKIN_JOINTINDICES` and `SKIN_WEIGHTS` as optional so that it won't trigger an error when these streams aren't found. 
- Add some additional null check and make some asserts only active when there's skinning
- Add a new skinning method call `NoSkinning` which skips the skinning calculation in the skinning shader. When an Actor doesn't have skin weights, then the skinning method falls back to `NoSkinning` automatically. 
- Make Asset Builder still align buffers when the model has only blendshapes, to avoid alignment errors under vulkan
Tested on windows, both DX12 and Vulkan. It now works well with Actors with only …
=> Fix editor crash when importing actor with only blendshapes but no skin weights

Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/Device_Windows.cpp
This commit disables the D3D12 Debug Layer Warning message with code 202, which overwhelms the Logs
with the following message, when the Debug layer is enabled, for example., when running the Editor in `debug` configuration:
```
D3D12 WARNING: ID3D12CommandList::DrawIndexedInstanced:
Element [6] in the current Input Layout's declaration references input slot 6,
but there is no Buffer bound to this slot. This is OK, as reads from an empty
slot are defined to return 0. It is also possible the developer knows the data
will not be used anyway. This is only a problem if the developer actually
intended to bind an input Buffer here. [ EXECUTION WARNING #202:
COMMAND_LIST_DRAW_VERTEX_BUFFER_NOT_SET]
...
...
...
```
On Windows, running the Editor, when the RHI is set to DX12 (`-rhi=dx12`) the …
=> Disable overwhelming D3D12 Warning 202

Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp
Fixes issue https://github.com/o3de/o3de/issues/18388
Turns out it would still look for Visual studio after the Ninja requirement was met.  This change makes it early out if its in a script only project, and build anyway, without trying to find visual studio.
Full installer testing (from locally built installer).
=> Fix Visual Studio Requirement in Project Manager when in script only mode

Code/Tools/SerializeContextTools/CMakeLists.txt
This PR replaces the build dependency `$<TARGET_OBJECTS:SerializeContextTools.Object>` with `SerializeContextTools.Private.Object` (link to the target instead of the object files) in the `AZ::AzSerializeTools` targets.
AR
=> Remove $<TARGET_OBJECTS: from SerializeContextTools targets

Code/Tools/SceneAPI/SceneBuilder/Importers/AssImpSkinWeightsImporter.cpp, Code/Tools/SceneAPI/SceneBuilder/Importers/AssImpSkinWeightsImporter.h
The `AssimpSkinWeightsImporter` class currently searches for skin weights in the `AssImpSceneNodeAppendedContext`. These weights are then added to a list of pending skin weights. The weight data is added in the `AssImpFinalizeSceneContext`.
The justification for splitting this into two phases is given in the 'AssImpSkinWeightsImporter.h' file. According to that, the name of the bones, may change after the `AssImpSceneNodeAppendedContext` is executed. However, the name of the bones is sanitized in the first phase, and then stored in the pending work items. Which means that renamed bones will not work anyhow. I assume that bone renaming no longer happens? Is this true?
Why do we need this change: We do some processing of the meshes in our own Gem. For this we need to modify the skin weights …
=> Merge phases of AssImpSkinWeightsImporter

cmake/Platform/Windows/Packaging/PostInstallSetup.wxs, cmake/Platform/Windows/Packaging/Template.wxs.in
This removes the post-installation step to bootstrap python. This step is not necessary since python will be bootstrapped as needed when Project Manager is launched. On Windows systems where there is a non-admin local user, installing O3DE will bootstrap python for the admin user if its different from the current user, so when launching Project Manager, the bootstrapping will occur anyways.
Tested on a locally built installer
=> Remove python bootstrapping from post install steps on Windows

cmake/Platform/Windows/Packaging/PostInstallSetup.wxs, cmake/Platform/Windows/Packaging/Template.wxs.in
This reverts commit 448d9a5bb7ce124bfbcf0c0d0b242476a1ddf39b to restore the windows python-bootstrapping during the install process
=> Revert "Remove python bootstrapping from post install steps on Windows"

Code/Framework/AzFramework/AzFramework/Viewport/ClickDetector.cpp, Code/Framework/AzFramework/AzFramework/Viewport/ClickDetector.h
`ClickDetector::m_detectionState` is not initialized in construction. On Windows, it's fine. But on Linux it would cause the viewport camera grabbing mouse first time opening a level. (m_detectionState is initialized with DetectionState::WaitingForMove)
Manually tested.
=> fix: viewport camera grab mouse first time opening a level

Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Multiplayer system will automatically load level if property is available
Create a game session via GameLift (create-game-session) and used --game-properties "Key=level,Value=MyLevel"
=> Load Multiplayer Level if Session "Level" Property Is Available

Gems/AWSGameLift/Code/AWSGameLiftServer/CMakeLists.txt
GameLift server should only bring in Multiplayer gem server, not unified. Otherwise, this causes servers to enable AZ_TRAIT_CLIENT, breaking an important multiplayer paradigm
Fixes #18444 
Created a small GameLift demo using Multiplayer Template. GameLauncher was able to connect to cloud. 
GameLauncher: AZ_TRAIT_CLIENT 1 AZ_TRAIT_SERVER 0
ServerLauncher: AZ_TRAIT_CLIENT 0 AZ_TRAIT_SERVER 1
UnifiedLauncher: AZ_TRAIT_CLIENT 1 AZ_TRAIT_SERVER 1
Editor: AZ_TRAIT_CLIENT 1 AZ_TRAIT_SERVER 1
=> GameLift Server Gem: AZ_TRAIT_SERVER 1, AZ_TRAIT_CLIENT 0 

Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshOutputStreamManager.cpp, Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshVertexStreamProperties.cpp, Gems/Atom/RHI/Code/Include/Atom/RHI/BufferProperty.h, Gems/Atom/RHI/Code/Include/Atom/RHI/CopyItem.h, Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceCopyItem.h, Gems/Atom/RHI/Code/Source/RHI.Reflect/AttachmentEnums.cpp, Gems/Atom/RHI/Code/Source/RHI/BufferScopeAttachment.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.cpp, Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/AsyncUploadQueue.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Conversion.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/ImagePoolResolver.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Scope.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Scope.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/CopyPass.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/CopyPass.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassLibrary.cpp
Major changes:
- CopyPass: add a MultiDeviceCopyPass with just one InputOutput slot to copy within a multi-device buffer/image
- CopyPass: add support to copy depth/stencil images
- Add m_sourceFormat to CopyBufferToImageDescriptor to give more control and stay consistent with CopyImageToBufferDescriptor which has m_destinationFormat
Minor changes:
- Fix for CopyPass to create a transient attachment when cloneInput is enabled and the input is not transient.
- Add copy flags to be able to copy some buffers between devices (SkinnedMeshOutputStreamManager.cpp and SkinnedMeshVertexStreamProperties.cpp)
- Allow RW access when the scope attachment usage is copy as this happens when copying multi-device resources between devices (AttachmentEnums.cpp)
- Fix for BufferScopeAttachment during clear …
=> CopyPass improvements (mainly for multi-device usage)

Code/Framework/AzCore/AzCore/Math/Matrix3x4.inl, Code/Framework/AzCore/Tests/Math/MathTestData.h, Code/Framework/AzCore/Tests/Math/TransformTests.cpp
This PR fixes a wrong behavior about the `TransformServiceFeatureProcessor` when a transform with negative scale is passed to `SetTransformForId`, it is not correctly returned when calling `GetTransformForId`/`GetNonUniformScaleForId`.
In the following code the values of `matrix` and `retrievedMatrix` are not the same:
```c++
Transform transform{ Vector3::CreateZero(), AZ::Quaternion::CreateIdentity(), -1.f };
Vector3 nonUniformScale{ 2.f, 3.f, 4.f };
m_transformServiceFeatureProcessor->SetTransformForId(m_transformObjectId, transform, nonUniformScale);
Matrix3x4 matrix{ Matrix3x4::CreateFromTransform(transform));
matrix.MultiplyByScale(nonUniformScale);
Transform retrievedTransform{ m_transformServiceFeatureProcessor->GetTransformForId(m_transformObjectId) };
Vector3 …
```
=> Fix TransformServiceFeatureProcessor Set/Get transform functions for negative scales

Gems/Atom/RPI/Code/Source/RPI.Public/RenderPipeline.cpp
This is necessary for the BRDFTexturePipeline to run on all devices when the root pass gets recreated.
=> Bugfix for the device index of root pass.

Gems/Atom/RHI/Vulkan/Code/Source/RHI/ShaderModule.cpp
spirv bytecode from uint8 vector to uint32 vector, the size should be div by 4
bug fix
run the example of o3de
=> correct spirv bytecode vector size

Code/Framework/AzCore/AzCore/Math/Matrix3x3.h, Code/Framework/AzCore/AzCore/Math/Matrix3x3.inl, Code/Framework/AzCore/Tests/Math/Matrix3x3Tests.cpp, Gems/Atom/RHI/Code/Source/RHI/ConstantsData.cpp
a `float3x3` takes up effectively 11 bytes in a GPU constant-buffer: Each float3 segment is aligned to 16 byte borders, with padding after the first and second segment, but no padding after the last segment, which means any 4-byte variable after a 3x3 matrix will be packed after the last float3 segment. Some Visualization [here](https://maraneshi.github.io/HLSL-ConstantBufferLayoutVisualizer/?visualizer=FAZwLgTgrgxmAEAVApueBvY9vwGYBsB7AQzAGYAPM+AWwH0CTyqBuLHR0+AB2JgGtkAEzoA3YhDYBfNsBgAjKLlzII8ZBWI1u+ZBnbYUaMKjDSWQA), though that link might be temporary.
`ConstantsData::SetConstant<Matrix3x3>` converted the Matrix3x3 into a Matrix3x4, and wrote 12 floats into the constant buffer, overwriting some variables following the float3x3.
This PR adds `Matrix3x3::StoreToRowMajorFloat11()` and …
=> Added functions StoreToRow/ColumnMajorFloat11 for Matrix3x3 for GPU constant buffer packing

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/View.h, Gems/Atom/RPI/Code/Source/RPI.Public/View.cpp
Added functions to the view that return the matrices with the clip space offset applied.
Tested with the MainPipeline and a custom pipeline that needs the clipToView matrix in a separate buffer
=> View: Expose matrices with offsets applied

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/CopyPass.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/CopyPass.cpp
This PR adds `ScopeQuery`s to the `CopyPass`, allowing the user to call
- `GetTimestampResultInternal`
- `GetPipelineStatisticsResultInternal`
for the `CopyPass` to measure and track performance.
For copies on the same device, the behaviour mimics that of the `RenderPass`, it is possible to query the `TimestampResult` as well as the `PipelineStatisticsResult` for the pass at hand.
For copies between devices, `ScopeQuery`s are attached to both `Scope`s running on different devices, the `PipelineStatisticsResult` is just the sum of both `Scope`s results.
`TimestampResult` does not have a perfect solution for now (as discussed here https://github.com/o3de/o3de/pull/18268, there exists no ideal solution as of now), assuming both devices have the same reference frame for their ticks, …
=> Add ScopeQueries to CopyPass

Gems/Atom/Feature/Common/Code/CMakeLists.txt
This PR changes the `Atom_Feature_Common.Public` target back to a static library, since the current version with a shared library leads to occasional crashes when selecting an Entity in the editor (The hash value of an `AZ::Name` variable is 0 in `AZ::DocumentPropertyEditor::CallbackAttributeDefinition::InvokeOnDomValue`, which leads to a wrong codepath being chosen which eventually leads to a crash). This error was introduced in #18405, but the change to a shared library was not supposed to be in there; it was likely an oversight when rebasing the PR which was originally developed on top of #18315 (which itself was partially reverted with a more correct version still being in development).
This crash does not happen every time and does also not happen with the same likelyhood on …
=> Change Atom_Feature_Common.Public back to static library

Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceStreamingImagePool.h, Gems/Atom/RHI/Code/Source/RHI/DeviceStreamingImagePool.cpp, Gems/Atom/RHI/Code/Source/RHI/StreamingImagePool.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/AsyncUploadQueue.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/StreamingImagePool.cpp, Gems/Atom/RHI/Metal/Code/Source/RHI/StreamingImagePool.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/AsyncUploadQueue.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/StreamingImagePool.cpp
This fixes a crash that can happen when an Image is released very quickly after it was created, and the Image has not yet finished uploading Mip-Levels.
This can happen in the Preview Renderer for materials with textures, where the material is used in one frame and immediately released. To somewhat reliably trigger this open the material-selection dialog such that many materials are visible at once, and the preview-images are created on demand, and the detail-preview window of a random material is also accessed. 
The sequence to the crash (or assert) is roughly like this:
- `~Material` calls `~MaterialProperty` which is a streaming-Image
- `~RPI::StreamingImage()` calls `Shutdown()`
-  This clears all references to the `DeviceResources` in the `RHI::Image`: The `DeviceResourceView` are …
=> Make sure RHI::Images stick around while Upload - Requests are pending

Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/CopyPass.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp
Previous changes to timestamp recording in the `Renderpass` as well as `RayTracingAccelerationStructurePass` lead to unusable behaviour in the ImGui Timestamp View, as can be seen here:
- The RT pass reported weird timings as it exists early and might report old timestamps
- Pausing cleared the latest timestamp and did not allow to inspect the results properly
With this PR, the behaviour is now again as intended:
Start a sample and open up the ImGui GPU Profiler with its Timestamp View.
=> Fix resetting and recording of timestamps

Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/CapsuleLightFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/DirectionalLightFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/DiskLightFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/PointLightFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/PolygonLightFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/QuadLightFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/SimplePointLightFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/SimpleSpotLightFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/ImageBasedLights/ImageBasedLightFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Source/CoreLights/CapsuleLightFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/CoreLights/DiskLightFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/CoreLights/PointLightFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/CoreLights/PolygonLightFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/CoreLights/QuadLightFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/CoreLights/SimplePointLightFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/CoreLights/SimpleSpotLightFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/ImageBasedLights/ImageBasedLightFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshFeatureProcessor.cpp
Exposes more functions to various feature processor interfaces.
- `GetLightBuffer`, `GetLightCount` in all light feature processors
-  `GetSpecularImage`, `GetDiffuseImage`, `GetExposure`, `GetOrientation` in the image based light feature processor
- Added a `ModelDataInstanceInterface` in the mesh feature processor. This one needs a bit more changes, as the `MeshHandle` needs to be cast to the implementation of `ModelDataInstance` when it is used.
On Windows with the MainPipeline and a custom one that relies on these functions
=> Expose more functions to feature processor interfaces

Code/Framework/AzQtComponents/AzQtComponents/Components/InputDialog.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/InputDialog.h
As described in the GHI https://github.com/o3de/o3de/issues/15048, renaming a deleted Track View node crashes the Editor. 
https://github.com/o3de/o3de/pull/17882 provided a partial fix with remaining occasional assert hit in CTrackViewSequence.
I was not able to reproduce this assert hit. However, there is an obvious UI issue that allows to delete the node in the process of its renaming or even open multiple rename popups simultaneously. 
The root cause is the bug in AzQtComponents::InputDialog that prevents it to be modal. Namely, accordingly to QT docs, the `setWindowModality` method has no effect is called after `show`. Please see https://doc.qt.io/qt-6/qwidget.html#windowModality-prop.
The PR fixes this issue. The "Console Variable Name" window is now modal as it's supposed to.
The …
=> Track View Fix: AzQtComponents::InputDialog should be modal (GHI-15048)

Gems/Stars/Code/Source/StarsFeatureProcessor.cpp
It fixes issue described here : https://github.com/o3de/o3de/issues/18474
- Cherry picked against 24.09
- ROS 2 Gem enabled
- ROS 2 Camera added
- Visualize camera in RQT
=> Fix use case for Star Gem in console mode

Code/Framework/AzTest/CMakeLists.txt
The import location of the `gmock` library, which is built from source via FetchContent, is not set correctly for the install layout of the engine, leading to the following error:
```
CMake Error in D:/code/o3de/install/Code/Framework/AzTest/CMakeLists.txt:
IMPORTED_LOCATION not set for imported target "gmock" configuration
"Profile".
```
Build the install target of the engine and check if the aforementioned error is no longer happening.
=> Fix import location of gmock library in install target not being set

Gems/Maestro/Code/Source/Cinematics/AssetBlendTrack.cpp, Gems/Maestro/Code/Source/Cinematics/AssetBlendTrack.h, Gems/Maestro/Code/Source/Cinematics/Tests/AssetBlendTrackTest.cpp
Fixes the issue https://github.com/o3de/o3de/issues/14801.
The `CAssetBlendTrack` class was missing the public
`void SetValue(float time, const Maestro::AssetBlends<AZ::Data::AssetData>& value, bool bDefault = false);`
method override, and then external usage of ths mehod in `CAnimComponentNode::InitializeTrackDefaultValue(..)` raised assert in the base `TAnimTrack:: SetValue(...)` method.
So, this PR:
- implements missing method override (and 2 related public methods);
- adds Unit Tests covering updated public methods.
- Unit Tests covering updated public methods functionality pass OK.
- Repro steps for the issue [#14801](https://github.com/o3de/o3de/issues/14801) now do not raise asserts in Editor, instead the track is reset (nullified) in …
=> Track View Fix: Implement the public override of the externally used method, thus removing asserts (issue #14801).

Code/Editor/AnimationContext.cpp, Code/Editor/AnimationContext.h, Code/Editor/TrackView/TrackViewAnimNode.cpp, Code/Editor/TrackView/TrackViewNodes.cpp
As it was reported in GHI https://github.com/o3de/o3de/issues/14980, there are bugs in TrackView with respect to undoing entity deletion with the SequenceAgent  component.
The PR 
1. fixes the assert failures reported in the GHI. The cause of the asserts is earlier rebounding of the entity to be undeleted by the Undo transaction. The entity has not completed the reversion process when the TrackView code tries to bound it. The fix introduces the bound call on OnPrefabInstancePropagationEnd when the entities are guaranteed to be fully reverted.
The video below shows the current behavior
https://github.com/user-attachments/assets/6e946682-c420-4953-89f4-c4e6b0997754
2. fixes the unreported issue with the color of the entity name ("Shader Ball" in this test case). When the entity is not …
=> Fixed issues with undoing deletion of entity with SequenceAgent (GHI-14980)

AutomatedTesting/ShaderLib/scenesrg.srgi, AutomatedTesting/ShaderLib/viewsrg.srgi, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Decals/DecalStructures.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/CapsuleLight.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/DirectionalLight.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/DiskLight.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/LightStructures.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/PointLight.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/PolygonLight.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/QuadLight.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/SimplePointLight.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/SimpleSpotLight.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingSceneSrg.azsli, Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/CoreLights/SceneSrg.azsli, Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/CoreLights/ViewSrg.azsli, Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/SceneSrgIncludesAll.azsli, Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/ViewSrgIncludesAll.azsli, Gems/Atom/Feature/Common/Assets/Shaders/LightCulling/LightCulling.azsl, Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingCommon.azsli, Gems/AtomTressFX/Assets/Shaders/HairLightTypes.azsli, Templates/MinimalProject/Template/ShaderLib/scenesrg.srgi, Templates/MinimalProject/Template/ShaderLib/viewsrg.srgi, Templates/ScriptOnlyProject/Template/ShaderLib/scenesrg.srgi, Templates/ScriptOnlyProject/Template/ShaderLib/viewsrg.srgi
- Move duplicated structure definitions for light types and decals from `ViewSrg`, `LightCulling` and `RayTracingSceneSrg` to separate files
- Add a include to `scenesrg.srgi` and `viewsrg.srgi` before the first definiton of the partial srgs.
This is a breaking change, since `scenesrg.srgi` and `viewsrg.srgi` are part of the project, and they now need these lines:
scenesrg.srgi:
```
#define AZ_COLLECTING_PARTIAL_SRG_INCLUDES
#include <Atom/Feature/Common/Assets/ShaderResourceGroups/SceneSrgIncludesAll.azsli>
#undef AZ_COLLECTING_PARTIAL_SRG_INCLUDES
```
viewsrg.srgi:
```
#define AZ_COLLECTING_PARTIAL_SRG_INCLUDES
#include <Atom/Feature/Common/Assets/ShaderResourceGroups/ViewSrgIncludesAll.azsli>
#undef AZ_COLLECTING_PARTIAL_SRG_INCLUDES
```
Vulkan on Windows, made sure shaders compile and …
=> Consolidate structure definitions for Lights and Decals

Gems/Atom/RHI/Code/Source/RHI/RayTracingAccelerationStructure.cpp
The function `RayTracingTlasDescriptor::GetDeviceRayTracingTlasDescriptor(int deviceIndex)` does not correctly propagate `m_instanceMask` to `DeviceRayTracingTlasDescriptor` (which means the default value of `1` is used for all instances of `DeviceRayTracingTlasDescriptor`.
Test with an external gem which uses additional bits of the instanceMask and verify that they are propagated to the GPU by using the `InstanceInclusionMask` parameter of `TraceRay()`.
=> Fix RayTracingTlasDescriptor not propagating m_instanceMask to DeviceRayTracingTlasDescriptor

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/CopyPass.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/CopyPass.cpp
Multi-device image to image copy pass fails in the ASV RPI MultiGPU sample.
The reason is that the input attachment not being a part of the host to device scope cannot be accessed during the resource compilation. Instead, we need to store the format.
ASV RPI MultiGPU sample
=> Bugfix: multi-device image to image copy pass fail

Templates/DefaultProject/Template/ShaderLib/scenesrg.srgi, Templates/DefaultProject/Template/ShaderLib/viewsrg.srgi
Followup to [PR 18498](https://github.com/o3de/o3de/pull/18498): add missing includes in DefaultProject - template
=> added missing includes in srgi files

Code/Editor/Resource.h, Code/Editor/TrackView/TrackViewDialog.cpp
As reported in https://github.com/o3de/o3de/issues/4113, hovering over the Stop With Hard Reset option in Track View crashes the Editor.
The cause of the crash in `EntityPropertyEditor::HandleMenuEvent` was incorrect setting of action data in `CTrackViewDialog::InitToolbar`. Namely, 
`qaction->setData(true);`
for the Stop with Hard Reset action resulted in an unexpected side-effect in `EntityPropertyEditor::HandleMenuEvent`. Comparison 
`if (action->data() == kPropertyEditorMenuActionMoveUp)`
is true when the `QVariant` holds boolean `true` as returned by `action->data()`.
The fix is to set up the action data with a unique value as done for other menu actions.
The current behavior is recorded:
https://github.com/user-attachments/assets/1a421a6c-f050-431f-b98b-049eaa83ee76
Tested locally, …
=> Fixed the crash on hovering over the Stop With Hard Reset option in Track View (GHI-4113)

Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/Device_Windows.cpp
Running an application with `dx12` in `Debug` mode currently prints the following deprecation warning:
```
D3D12 MESSAGE: ID3D12Device::SetFeatureMask: ID3D12DebugDevice::SetFeatureMask has been replaced by ID3D12DebugDevice2::SetDebugParameter [ MISCELLANEOUS MESSAGE #989: DEPRECATED_API]
```
This PR implements the debug parameter setting via the new functionality.
Run atom-sampleviewer with `dx12` in `Debug` mode.
=> [Dx12] SetDebugParameter instead of (deprecated) SetFeatureMask

Code/Editor/AnimationContext.h
https://github.com/o3de/o3de/pull/18496 introduced a build warning on windows preventing to build. Fix is simply to not dllexport this class by removing the macro, its only used within the editor module and thus useless.
The question remain on how the CI pipeline went through it without notifying the issue
=> Fix compilation on windows

Code/Editor/TrackView/2DBezierKeyUIControls.cpp, Code/Editor/TrackView/AssetBlendKeyUIControls.cpp, Code/Editor/TrackView/CaptureKeyUIControls.cpp, Code/Editor/TrackView/CommentKeyUIControls.cpp, Code/Editor/TrackView/ConsoleKeyUIControls.cpp, Code/Editor/TrackView/EventKeyUIControls.cpp, Code/Editor/TrackView/GotoKeyUIControls.cpp, Code/Editor/TrackView/KeyUIControls.h, Code/Editor/TrackView/ScreenFaderKeyUIControls.cpp, Code/Editor/TrackView/SelectKeyUIControls.cpp, Code/Editor/TrackView/SequenceKeyUIControls.cpp, Code/Editor/TrackView/SoundKeyUIControls.cpp, Code/Editor/TrackView/TimeRangeKeyUIControls.cpp, Code/Editor/TrackView/TrackEventKeyUIControls.cpp, Code/Editor/TrackView/TrackViewAnimNode.cpp, Code/Editor/TrackView/TrackViewAnimNode.h, Code/Editor/TrackView/TrackViewKeyPropertiesDlg.cpp, Code/Editor/TrackView/TrackViewKeyPropertiesDlg.h, Code/Editor/TrackView/TrackViewNode.cpp, Code/Editor/TrackView/TrackViewNode.h, Code/Editor/TrackView/TrackViewSequence.cpp, Code/Editor/TrackView/TrackViewSequence.h, Code/Editor/TrackView/TrackViewSequenceManager.cpp, Code/Editor/TrackView/TrackViewTrack.cpp, Code/Editor/TrackView/TrackViewTrack.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyRowWidget.cpp
As reported in https://github.com/o3de/o3de/issues/10816, the key's green marker values used to display incorrectly on selection.
This PR fixes the issue, as well as does some code refactoring.
In more details
1) green marker issue was caused by missed data propagation to the editor UI on the marker selection. The issue is fixed in the method `CTrackViewKeyPropertiesDlg::OnKeySelectionChanged`
2) unreported visual glitch was noticed. The data label for a single entry was displayed as "1 elements". Fixed.
Video shows the current behavior:
https://github.com/user-attachments/assets/320e807f-2951-4d34-8978-0ae839e333b9
3) Partial code refactoring/improving of the TrackView sources. _It's an outgoing effort._
a) Typo in the name of `CTrackViewSequence::SubmitPendingNotifcations` fixed.
b) …
=> Green markers should display consistent values when selected (GHI-10816)

Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.h
This fixes the problem described in https://github.com/o3de/o3de/pull/16850
The remembered bindless index is reset when the pipeline layout changes.
The srg indices should only change when the pipeline layout changes, if I understand this correctly. So as long as the pipeline layout stays the same the bindless srg cannot be overwritten by another srg.
Windows and DX12. Tested the MainPipeline and a Pipeline where problems with bindless occur
=> DX12: Fix binding of bindless resources

Code/Editor/TrackView/TrackViewNode.cpp, Code/Editor/TrackView/TrackViewNodes.cpp, Code/Legacy/CryCommon/Maestro/Types/AnimNodeType.h, Gems/Maestro/Code/Source/Cinematics/Movie.cpp
Closes #7025 describes the bug when adding an Environment node to a sequence fails with the warning and has no effect.
Upon looking in the code it was found out that this node type was deprecated in Jan 2016. There is no code implementation for this node.
This PR removes the UI for the Environment node. The respective popup menu looks as following after the change:
Closes [7025](https://github.com/o3de/o3de/issues/7025)
Tested locally, Windows 10.
=> Track View: Remove the Environment node UI (GHI-7025)

Code/Editor/TrackViewNewSequenceDialog.cpp, Code/Editor/TrackViewNewSequenceDialog.h
It is shown in GHI https://github.com/o3de/o3de/issues/3941 that a very long sequence name reveals a UI  defect.
This PR addresses the issue by introducing a new input validator for this text field. In addition to previous functionality, i.e. excluding slash, duplicate name, special invalid name,  this validator limits a sequence name by 160 characters. It is assumed that 160 characters is more than enough to give a proper name. Longer name is inconvenient to perceive and fit in UI.
The video below shows an attempt to enter a longer than acceptable name and the UI behavior when the length is maximal.
https://github.com/user-attachments/assets/96c91a78-f817-414d-9fed-566c8630f919
Additionally, the validator changes the validation approach to be more user-friendly. Previously, the …
=> Updated the input validation in CTVNewSequenceDialog (GHI-3941)

Gems/Atom/Feature/Common/Assets/Shaders/LightCulling/LightCulling.azsl, Gems/Atom/Feature/Common/Code/Source/CoreLights/LightCullingPass.cpp
This PR fixes how Orthographic camera interacts with shadows.
Without this PR, some lights that are visible in viewport are culled by the LightCulling.azsl shader.
For Orthographic camera function `GenerateScreenUVToRayConstants` always returned (0,0,0,0) because pairs of planes are parallel. These rays were very rarely correct and resulted in invalid results. 
PR reworks the logic of computing Tile AABB to also work for Orthographic projections.
An example level of 30x30 shaderball spaced 1 m apart + 5x5 disk lights spaced every 5 m were placed on Default Level.  
Each light has intensity of 200 lm and Attenuation radius of 10 m
=> Fix Light Culling for Ortographic camera

Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
This PR aims to fix a bug with projects not been removed from the UI when they are deleted (when just 1 project is left)
This bug is is described [here](https://github.com/o3de/o3de/issues/18452#issue-2645272932) but essentially if only 1 project was left and the user deleted it. It 
1.  Was removed from the users files
2. but remained visible in the UI until the project manager was restarted or refreshed
Now if just 1 project remains and the user deletes it, it is removed from the UI as expected.
https://github.com/user-attachments/assets/6fdc606f-54da-4680-aa95-bf3d4b443fe2
Tested locally (manually) in a profile build
OS: Debian 12 (bookworm)
=> Fix: add if check to remove left project buttons when projects.isEmpty()

Code/Editor/Core/EditorActionsHandler.cpp, Code/Editor/CryEdit.cpp, Code/Editor/CryEdit.h, Gems/AWSCore/Code/Source/Editor/Constants/AWSCoreEditorMenuNames.h, Gems/AWSCore/Code/Source/Editor/UI/AWSCoreEditorMenu.cpp
Fix https://github.com/o3de/o3de/issues/18486
In help menu :
- Use o3de news blog instead of AWS news
- Point to discord instead of dead link to community page
- Move GameLift link and AWS support to AWS menu
In CryEdit:
- Remove methods declared without a body
This is what is is like with the change
Local build on windows
=> DocMenu: Fix broken help links, move AWS doc and remove unused methods from cryedit.h

Code/Framework/AzCore/AzCore/Memory/SystemAllocator.cpp, Code/Framework/AzFramework/AzFramework/Archive/ZipDirStructures.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Archive/ArchiveComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Archive/ArchiveComponent.h, Code/Framework/AzToolsFramework/Tests/ArchiveTests.cpp, Code/Tools/AzTestRunner/src/main.cpp
POTENTIAL fix to https://github.com/o3de/o3de/issues/18421
(more testing required, its not a 100% repro of the above, but these are definitely corruption issues anyway even if it doesn't solve the above).
* Fixes a memory corruption issue caused by concurrent access of the m_threads member of the Archive Component class by eliminating this member and replacing it with std::async usage.  This is simpler, and eliminates the need to manually mess with promise and future.
* Adds back the ability for AzCore systemAllocator to use the os allocator when a flag is set for it to do so.  Note that this flag was already being set when ASAN was enabled but was not being honored.
* Fixes a buffer overrun detected by ASAN in the ZipDirStructures.cpp
* Fixes a buffer overrun detected by ASAN in main.cpp …
=> Fixes memory corruption issues in ArchiveAPI

Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/Module/DynamicModuleHandle_WinAPI.cpp
I ran into a problem when using the SDK build with the following scenario:
* Engine SDK, an external gem as source code, and a project which builds the external gem from source and uses the engine SDK
* The external gem "MyGem" creates the module library `MyGem.Editor.dll`, which depends on `MyGemDependency.dll`, which is also built by this gem (The dependency could also be a prebuilt dll)
* `MyGem.Editor.dll` and  `MyGemDependency.dll` are in projectdir/build/* (project-based build)
* At runtime the editor (`Editor.exe` form the engine SDK) loads `MyGem.Editor.dll` dynamically, which needs to load `MyGemDependency.dll` as well; the search paths for `MyGemDependency.dll` according to Proecss Monitor) are:
* `sdkdir/.../` (Editor.exe directory)
* …
=> Add current dll directory to library search path in LoadLibrary

Code/Tools/LuaIDE/Source/LUA/LUAEditorSyntaxHighlighter.cpp, Code/Tools/LuaIDE/Source/LUA/LUAEditorSyntaxHighlighter.hxx
This change should both improve performance of parsing and prevent unwanted highlighting in comment blocks. The regex was simply run on too much content.
Follow-up to https://github.com/o3de/o3de/pull/17894. Issue also mentionned in https://github.com/o3de/o3de/pull/17915
Before
After the fix
Local build on windows in dev branch, tried various lua scripts
=> Fix Lua Editor: Only run regex on subset provided by parser instead of entire line

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/StreamingImage.h, Gems/Atom/RPI/Code/Source/RPI.Public/Image/StreamingImage.cpp
Follow-up to #18479: This PR avoids an assert that is triggered if the upload-callback is executed after Shutdown() was already called.
This also introduces a mutex to ensure the upload-callback and shutdown interfere, since both can be triggered from separate threads. 
Vulkan on Windows, making sure default behavior still works, especially the preview-renderer.
=> Don't try to evict mipchain-assets after the image has been shutdown

Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceShaderResourceGroupData.h
The main advantage of a typed buffer is to use the texture mapping and texture filtering hardware to do format conversion.
When attempting to use this feature where one for example would use an `R10G10B10A2_UNORM` format for the buffer on the C++ side, which would translate to a `float4` format in shader, it would refuse to bind it since the stride of `R10G10B10A2_UNORM` is 4, and the stride of `float4` is 16.
This check is correct when using a `StructuredBuffer`, though.
This PR changes the check to be skipped for typed buffers.
This PR was tested by binding a typed buffer in `R10G10B10A2_UNORM` format with the engine running in Vulkan and DirectX 12.
=> ⌨️ Skip stride size assert when binding a typed buffer.

Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp, Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.h
This PR modifies Bootstrap component to run BRDF pipeline. 
It fixes : https://github.com/o3de/o3de-extras/issues/792 
PR is meant to not change execution of non-console mode app.
Build and run test level with terrain and ROS 2 camera:
There is version of this fix targeted for main:
https://github.com/RobotecAI/o3de/commit/82ef86146b5337d4730744a7a8347ead549575be#diff-1d5588829cc3fe55631fa88df3454631556b59d34e30078021c425963cf75f6bR608
There is also fix that exists only in o3de-extras:
https://github.com/o3de/o3de-extras/pull/801
=> Added logic to boostrap component that run BRDF pipeline in console mode

Code/Tools/AssetProcessor/native/utilities/BatchApplicationManager.cpp, Code/Tools/AssetProcessor/native/utilities/GUIApplicationManager.cpp
Adds in the omitted `AssetProcessor::PlatformConfiguration::Reflect(context);` for the AssetProcessorBatch, without which running the APB in Asset Cache client mode would result in an error when attempting to load settings.json
By running the AssetProcessorBatch in client mode for the Asset Cache.
=> AssetProcessorBatch Reflect Fix

Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/Module/DynamicModuleHandle_WinAPI.cpp
Bug Fix.
I noticed my gamepad stopped working.
After some debugging I found that O3DE
failed to load "XInput9_1_0.dll".
The failured was introduced in PR #18525:
https://github.com/o3de/o3de/pull/18525
According to MSFT Docs:
https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexw When using `LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR`:
```
The lpFileName parameter must specify a fully qualified path.
```
The failure occured because "XInput9_1_0.dll" is NOT a fully qualified path and it is expected to be found in the SYSTEM32 directory.
The solution is to only use `LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR` when the module path is fully qualified.
Gamepad Controller works again.
Gamepad Controller works.
=> Fixes loading XInput9_1_0.dll.

Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.cpp, Gems/LyShine/Code/Editor/EditorMenu.cpp, Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
Several windows for file opening have been implemented using AssetBrowserComponentRequests::PickAssets. However, a few windows remain unaddressed, specifically the file opener from the Lua editor, the UI editor and the script canvas. It previously used the os specific file opening.
This PR homogenize the remaining Windows.
| Name  | New | Original |
| :------------ | :---------: | ---------: |
| Script canvas |  <img src="https://github.com/user-attachments/assets/3ab0554b-84ba-43bc-bae7-56df78003463" width="800"/> |  <img src="https://github.com/user-attachments/assets/ba431d33-bd6d-40b4-bc42-86490974cc93" width="900"/> |
| UI Editor           |  <img src="https://github.com/user-attachments/assets/83d94b2e-7690-4626-91b4-1f4d16287a3b" width="800"/> |  <img …
=> Homogenization of file opening windows

Gems/Camera/Code/Source/CameraComponentController.cpp, Gems/Camera/Code/Source/CameraComponentController.h
This is useful for rendering to texture using features like:
- Sky atmosphere
- Global illumination 
Since a lot of features processors don't behave with multiple cameras this function is activated after changing registry setting: `/O3DE/Atom/ExperimentalFeaturesEnabled` to `true` It is to prevent exposure of this function to the majority of users.
**Note** that some of existing feature processors, are not supporting multiple cameras correctly at the moment. Using this feature with those can lead to UB also in Editor, which is not beneficial. This feature is intended for advanced cases. I would consider to hide all render to texture section in next PR.
This function allows to change the camera pipeline (both in Editor and GameMode):
https://github.com/o3de/o3de/issues/18473
I've run 2409 …
=> Add function "Allow pipeline changes" to CameraComponent

Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiGpuProfiler.h, Gems/Atom/Utils/Code/Source/ImGuiGpuProfiler.cpp
This PR improves the handling of multi-GPU passes in the GPU Profiler -> TimestampView.
It does the following:
- Report total frame duration per device
- Show one timeline per device vertically
- Split the pass runtime view per device horizontally
One remaining issue is that multiple timelines are drawn and scaled independently at the moment.
Since there currently is no way to match/synchronize timestamps between devices, each GPU scales its own timeline to the full length of the window, instead of scaling all passes the same and shifting them along as needed.
This would require something like [calibrated timestamps](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_calibrated_timestamps.html) to handle better.
In the meantime, timelines are internally consistent …
=> Handle multiGPU Passes in ImGui Timestamp View

Gems/Atom/RHI/Code/Include/Atom/RHI/ShaderResourceGroupData.h, Gems/Atom/RHI/Code/Source/RHI/ShaderResourceGroupData.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/DescriptorContext.cpp, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Shader/ShaderResourceGroup.h, Gems/Atom/RPI/Code/Source/RPI.Public/Shader/ShaderResourceGroup.cpp
This PR fixes two issues with bindless:
1. Fix https://github.com/o3de/o3de/issues/16305 for DX12: Create raw buffers views for the bindless descriptors. According to the [documentation](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/sm5-object-rwbyteaddressbuffer) of (RW)ByteAddressBuffer, buffer descriptors bound to it need to be raw buffer descriptors.
2. Fix a MultiGPU bug in `ShaderResourceGroup::SetBindlessViews`. The returned bindless indices always contained the bindless indices of the last device. Now bindless indices per device are returned.
Windows + DX12/Vulkan. Tested the MainPipeline and the BindlessPrototype sample in the Atom Sample Viewer.
The BindlessPrototype sample was previously broken with DX12 or Vulkan+MultiGPU. It's now working again.
Before:
Fixed:
=> Bindless fixes

Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/Ibl.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/Ltc.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/SimpleSpotLight.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/BasePBR/BasePBR_LightingData.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/Eye/Eye_VertexEval.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/BaseColorInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/DetailMapsInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/NormalInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/OcclusionInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/RoughnessInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/SpecularInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/Skin/Skin_SurfaceEval.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/Skin/Skin_VertexEval.azsli, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/StreamBufferViewsBuilderInterface.h, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshInstanceGroupList.cpp, Gems/Atom/Feature/Common/Code/Source/Mesh/StreamBufferViewsBuilder.cpp, Gems/Atom/Feature/Common/Code/Source/Mesh/StreamBufferViewsBuilder.h, Gems/Atom/Feature/Common/Code/atom_feature_common_files.cmake, Gems/Atom/Feature/Common/Code/atom_feature_common_public_files.cmake, Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceDrawItem.h, Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceDrawPacket.h, Gems/Atom/RHI/Code/Include/Atom/RHI/DispatchItem.h, Gems/Atom/RHI/Code/Include/Atom/RHI/DrawItem.h, Gems/Atom/RHI/Code/Include/Atom/RHI/DrawPacket.h, Gems/Atom/RHI/Code/Source/RHI/DrawPacket.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/MeshDrawPacket.cpp
Added Compute Shader support in *.MaterialPipeline
and *.MaterialType.
This feature is important for alternative rendering methods
like Texture/Object Space Shading that need to leverage
the O3DE Material pipeline.
The RFC is here: https://github.com/o3de/sig-graphics-audio/pull/167  
Please follow the RFC for details.
New APIs tested on Quest3 with our private project, and made sure the Engine worked fine with AutomatedTesting and AtomSampleViewer.
=> Added Compute Shader support in *.MaterialPipeline

Code/Tools/LuaIDE/Source/LUA/LUAEditorFindDialog.cpp, Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.cpp, Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.hxx
Fix https://github.com/o3de/o3de/issues/14189
In the Lua Editor's Find Tool, an issue was identified with the Find All, Replace All and Replace buttons when no script was selected. Since searching for text is unnecessary without an open file, those buttons have now been greyed out if no file is opened.
- Opened the Lua editor and the find tool with no script. Checked that the Find All, Replace All and Replace buttons was greyed out
- Opened a script and the find tool. Checked that I could search for a string with the Find All and could replace with replace All and Replace buttons
=> Fix Lua Editor: greyed out FindAll if no script opened

Code/Framework/AzQtComponents/AzQtComponents/Utilities/ScreenGrabber_win.cpp
This PR fixes a compile error that occurs when compiling the engine with Clang on Windows in a release build. The locally defined function `GetLastErrorString()` is only used as parameter to `AZ_Assert`, meaning it is not called in release builds, which leads to a unused function warning.
Compile with Clang on Windows with Release configuration
=> Fix a compile error with Clang on Windows in Release build

Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/IShaderVariantFinder.h, Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderAsset.cpp
Fixes a linking error for the `ShaderVariantFinderNotification` ebus introduced after #18427.
Build the engine.
=> Bugfix: linking on Linux doesn't work.

Gems/Atom/RHI/Vulkan/Code/Source/RHI.Reflect/Conversion.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Conversion.cpp
During testing, we found that copy performance is significantly slower (multiple times) on `vulkan` compared to `dx12` and found that it can be traced back to how memory is held on the host side.
By introducing the `VK_MEMORY_PROPERTY_HOST_CACHED_BIT`, the performance for copy operations involving the host on `vulkan` is now "identical" to `dx12`.
From the [specification](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkMemoryPropertyFlagBits.html)
> VK_MEMORY_PROPERTY_HOST_CACHED_BIT bit specifies that memory allocated with this type is cached on the host. Host memory accesses to uncached memory are slower than to cached memory, however uncached memory is always host coherent.
=> Introduce Vulkan HOST_CACHED_BIT

Gems/Atom/RHI/Code/Include/Atom/RHI/RHIBus.h
The `RHIRequirementRequest` Ebus (introduced in https://github.com/o3de/o3de/pull/18450) might be called from multiple threads when new buffers/images are allocated. During allocation the `GetRequiredAlignment` function is called.
This resulted in error messages like `Bus static const char *AZ::EBus<AZ::RHI::RHIRequirementsRequest>::GetName() [Interface = AZ::RHI::RHIRequirementsRequest, BusTraits = AZ::RHI::RHIRequirementsRequest] has multiple threads in its callstack records. Configure MutexType on the bus, or don't send to it from multiple threads
`.
This PR fixes this problem by adding a mutex to the Bus.
Tested on Windows and Linux with a Gem that implements the `RHIRequirementRequest` bus.
=> Add a mutex to the RHIRequirmentRequest Ebus

Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
Removes the common `R10G10B10A2_PACK32` format from supported surface formats when SetHDRMetadata is null.
When using KDE with Wayland and enabling HDR on your monitor the engine will select the `R10G10B10A2_PACK32` which ends up looking grey and dim due to no SetHDRMetadata support in the VK RHI, this fixes that and gives you a proper SDR image.
I used the wayland branch on my fork with this setup:
- Fedora 41
- KDE Wayland
- Main monitor HDR Enabled
I also tested with XCB just to make sure.
=> Vulkan RHI: Don't expose HDR surface format when SetHDRMetadata is null

Code/Editor/Core/QtEditorApplication.cpp, Code/Framework/AzCore/AzCore/Serialization/DataPatch.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/ComponentMimeData.cpp, Code/Framework/AzToolsFramework/Tests/AssetFileInfoListComparison.cpp, Code/Framework/AzToolsFramework/Tests/AssetSeedManager.cpp, Code/Tools/AssetBundler/source/utils/applicationManager.cpp, Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp, Code/Tools/AssetProcessor/native/utilities/GUIApplicationManager.cpp, Code/Tools/PythonBindingsExample/source/Application.cpp, Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionEvents/EventDataEditor.cpp, Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionEvents/MotionEventEditor.cpp, Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionEvents/MotionEventPresetCreateDialog.cpp, Gems/EMotionFX/Code/Source/Editor/Plugins/SimulatedObject/SimulatedObjectWidget.cpp, Gems/EMotionFX/Code/Source/Editor/PropertyWidgets/EventDataHandler.cpp, Gems/LmbrCentral/Code/Source/Builders/SliceBuilder/SliceBuilderWorker.cpp, Gems/LyShine/Code/Editor/PropertiesContainer.cpp, Gems/LyShine/Code/Pipeline/LyShineBuilder/UiCanvasBuilderWorker.cpp, Gems/PhysX/Core/Code/Source/ForceRegion.cpp, Gems/RemoteTools/Code/Source/RemoteToolsSystemComponent.cpp
Initialize the Serialize-context to nullptr, so the user gets an assert instead of a crash caused by accessing an uninitialized pointer.
=> initialize AZ::SerializeContext to nullptr

Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/Module/DynamicModuleHandle_WinAPI.cpp
This is a fix for a problem introduced by https://github.com/o3de/o3de/pull/18525
I encountered a problem when loading a dll that is not in the engine path, but in an installed library that is in the dll search path.
A previous fix (https://github.com/o3de/o3de/pull/18535) solved a related problem when loading dlls with a relativ path.
According to the [documentation](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexw) the `LoadLibraryExW` function behaves the same as the (previously used) `LoadLibraryW` function when the flags are `0`. So `LOAD_LIBRARY_SEARCH_DEFAULT_DIRS` are not really the default dirs used in `LoadLibraryW`.
@galibzon Can you check if loading `XInput9_1_0.dll` still works with these changes. I think it should as it uses the …
=> Fallback to LoadLibraryW in case a dll cannot be loaded

Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.h, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
Fixes one consequence of the issue #11500:
With earlier code prefabs could be saved with "torn-off" Entities having a TrackView `EditorSeqenceComponrnt`: 
with a spoiled (empty) "Parent Entity" sentence in the `TransformComponent` of this entity.
Such prefab is still loaded wrongly with the current code without even warning, which seems not very user - friendly.
This optional fix:
* Adds checks for "Parent Entity" sentences in the "Entities" container of a prefab being loaded;
* When an empty parent statement is found, reports error and links the entity to the `ContainerEntity` of the prefab;
* In case a user resaves this PR, it will be finally fixed.
In most practical cases the AssetBuilder now will deserialize a buggy `prefab` into a correct `spawnable` (with error report).
This PR is …
=> Track View: Optional fix for GHI #11500: fix prefabs previously stored with invalid entity parents.

Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayer.h, Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp, Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h, Gems/Multiplayer/Code/Tests/CommonBenchmarkSetup.h, Gems/Multiplayer/Code/Tests/MockInterfaces.h
Connect console command now accepts a connection ticket for servers that need some validation to allow a client connection. Separated by : `connect <ip_address>:<port>:<connection_ticket>`
This is a quality of life ask from the recent GameLift demo. Removes the need to add any client-side logic for connecting to GameLift servers (or any server that needs some form of auth during connection) 
Fixes #18542 
Tested by connecting to a GameLift server using the connection ticket
Tested by running 4 possibilities
1. `"connect"`
2. `"connect <ip-address>"`
3. `"connect <ip-address>:<port>"`
4. `"connect <ip-address>:<port>:<ticket>"`
=> Multiplayer Connect Console Command Accepts Ticket

AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/editor_entity_utils.py, AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.h, Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilder.cpp
Added a set of small fixes that facilitate Level creation with Python.
1. Fixed bug in the `MaterialBuilder.cpp` where Material names like "metal.001.material" were being produced as "metal.azmaterial". With this fix the same source file is now produced as "metal.001.azmaterial". This bug was messing with the possibility of finding a material product asset from the path of the source asset.
2. Improved editor_python_test_tools/utils.py by Try/Excepting the inclusion of the `multiplayer` module.
Not all projects use the Multiplayer Gem.
3. Added new Global Method to the BehaviorContext (for Automation only) that allows to add the NonUniformScaleComponent to an entity. `azlmbr.editor.AddNonUniformScaleComponent(entityId: EntityId, scale: Vector3)`
Validated with AutomatedTesting and our …
=> Added a set of small fixes that

Code/Framework/AzNetworking/AzNetworking/Framework/INetworking.h, Gems/MultiplayerCompression/Code/Source/MultiplayerCompressionSystemComponent.cpp, Gems/MultiplayerCompression/Code/Source/MultiplayerCompressionSystemComponent.h
Multiplayer Compression requires NetworkSystemComponent to function
Fixes a crash on startup when Compression tries to call AZ::Interface<AzNetworking::INetworking>::Get() but receives a nullptr
Issue uncovered via Discord chat: https://discord.com/channels/805939474655346758/1318673254184910969
=> Multiplayer Compression System Component Dependency Crash Fix

Code/Editor/TrackView/TrackViewSequence.h, Code/Framework/AzFramework/AzFramework/Input/Devices/Mouse/InputDeviceMouse.cpp, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h, Gems/LyShine/Code/Editor/Animation/UiAnimViewSequence.h
It is known that the Editor does not pass Valgrind Memcheck test on Linux, see GHI https://github.com/o3de/o3de/issues/12217
This PR addresses some use cases of uninitialized variables
1. `CTrackViewSequence m_time` found by code review
2. `InputDeviceMouse::Implementation  m_captureCursor`
Valgrind analysis 
```
==24779== Conditional jump or move depends on uninitialised value(s)
==24779==    at 0x8AE594B: AzFramework::XcbInputDeviceMouse::SetSystemCursorState(AzFramework::SystemCursorState) (o3de-maestro/Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.cpp:319)
==24779==    by 0x8AE4FF9: XcbInputDeviceMouse (o3de-maestro/Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.cpp:94)
==24779==    by 0x8AE4FF9: …
```
=> Fixes for some use cases of uninitialized variables

Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.cpp
In most 3d authoring software, double clicking on an entity in the entity outliner window makes the camera focused on said entity in the viewport. This PR allows to reproduce this behavior.
Currently, when an entity is selected, you need to press Z to go to this entity.
This PR changes the default behavior of the double click :
- For an editor entity, for a prefab and for an entity inside a prefab : go to the selected entity
https://github.com/user-attachments/assets/c26a6cdf-e62b-4e6d-83f5-f4dafe1fecef
Local windows build, on the GnomebodysHome project. Selected an entity, a prefab and an entity inside a prefab.
=> New: double clicking in an item in entity outliner does a camera go-to

Code/Editor/TrackView/TrackViewNodes.cpp
Closes https://github.com/o3de/o3de/issues/15042
Previous UI context menus for adding / managing tracks of a component were shown in the movie attached to the GHI https://github.com/o3de/o3de/issues/15042.
I understand that the issue was filed by the author because he was confused by UI inconsistency:
- The "`Add Tracks`" menu item disappeared after adding all possible tracks for a selected component node, 
- The name of the "`<Component Node Name> Tracks`" menu item, designed to list the added and thus manageable tracks,  was probably misleading, especially because this menu item always remained disabled. And the "`<Component Node Name>`" part of the menu item name seems ambiguous as the context menu anyway belongs to the component node selected by RMB (right mouse button) click.
So this …
=> Track View: Fix issue #15042 , - update code forming UI context sub-menus for adding / managing tracks of a component.

python/requirements.txt, scripts/build/build_node/Platform/Common/requirements.txt, scripts/build/build_node/Platform/Windows/requirements.txt
Update Jinja to 3.1.5 to resolve security notices:
https://github.com/o3de/o3de/security/dependabot/120
https://github.com/o3de/o3de/security/dependabot/121
https://github.com/o3de/o3de/security/dependabot/122
https://github.com/o3de/o3de/security/dependabot/123
https://github.com/o3de/o3de/security/dependabot/124
https://github.com/o3de/o3de/security/dependabot/125
Built the code without errors
=> Updated Jinja to 3.1.5 to resolve security notices

Code/Framework/AzCore/AzCore/Serialization/EditContextConstants.inl
This PR replaces usages of the two-parameter macro `AZ_CRC` (string value and crc value) with the macro `AZ_CRC_CE` (only string value). This was already done for the entire repository in #18120, but some usages were added shortly after that.
Compile on Windows + AR
=> Update usages of AZ_CRC macro with 2 parameters

Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.cpp, Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.hxx, Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.ui, Code/Tools/LuaIDE/Source/LUA/RecentFiles.cpp, Code/Tools/LuaIDE/Source/LUA/RecentFiles.h, Code/Tools/LuaIDE/lua_ide_files.cmake
Fix https://github.com/o3de/o3de/issues/14078
Whenever a lua script is opened, it is added to the list of recent files and the user can have an history of those recently opened files. Clicking on any file in this list will open that specific file. Additionally, the user has the option to clear the list of recent files.
- Opened the Lua editor and a few scripts. Clicked on the new "Open Recent Files" option from the menu. Noted that the list was fully populated and proceeded to open a script from the recent files list.
- Closed the editor to check that the recent files list was saved
=> Add recent files menu to the Lua Editor

Code/Editor/AnimationContext.cpp, Code/Editor/AnimationContext.h, Code/Editor/CryEdit.cpp, Code/Editor/CryEdit.h, Code/Editor/EditorViewportWidget.cpp, Code/Editor/EditorViewportWidget.h, Code/Editor/TrackView/TVSequenceProps.cpp, Code/Editor/TrackView/TrackViewDialog.cpp, Code/Editor/TrackViewNewSequenceDialog.cpp
Closes https://github.com/o3de/o3de/issues/2833
Closes https://github.com/o3de/o3de/issues/4590
Partially fixes: https://github.com/o3de/o3de/issues/5361  -  "The camera does not move when autostarting inEditor" part.
(Whether this issue is fully fixed could be tested after merging the needed PR  https://github.com/o3de/o3de/pull/18544)
1. While investigating issues I've encountered a couple of user-unfriendly UI deficiencies, so this PR fixes these, namely:
- None of existing sequences is selected when TrackView dialogue is started;
- When entering a name for a new creating sequence, the name input dialogue counterintuitively blocks text input when the input becomes equal to a name of an existing sequence, instead of disabling the OK button.
2. The PR …
=> Track View: Fix issues #2833 and #4590, - add switching cameras in the Editor Viewport according to a Director track keys setup.

Code/Tools/Android/ProjectGenerator/config_data.py, Code/Tools/Android/ProjectGenerator/main.py, Code/Tools/Android/ProjectGenerator/project_generator.py, scripts/o3de/o3de/android_support.py
The Android Project Generator UI can now pass additional CMake extra arguments for configuration. For example:
```
-DMYGEN_ENABLE=ON -DMY_ANDROID_VAR=OFF
```
Validated two scenarios with our internal Android app on Quest3:
1- Single CMake argument: `-DMYGEN_ENABLE=ON`
2- Two CMake arguments: `-DMYGEN_ENABLE=ON -DMY_ANDROID_VAR=OFF`
=> AGP accepts extras CMake arguments

Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Maya/requirements.txt, Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Resources/py27/requirements.txt, Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/requirements.txt, python/requirements.txt, scripts/build/build_node/Platform/Common/requirements.txt, scripts/build/build_node/Platform/Windows/requirements.txt
Updated certifi to 2024.07.04 to resolve security notices:
https://github.com/o3de/o3de/security/dependabot/74
https://github.com/o3de/o3de/security/dependabot/73
https://github.com/o3de/o3de/security/dependabot/72
https://github.com/o3de/o3de/security/dependabot/71
https://github.com/o3de/o3de/security/dependabot/70
https://github.com/o3de/o3de/security/dependabot/69
https://github.com/o3de/o3de/security/dependabot/55
https://github.com/o3de/o3de/security/dependabot/54
https://github.com/o3de/o3de/security/dependabot/117
https://github.com/o3de/o3de/security/dependabot/116
https://github.com/o3de/o3de/security/dependabot/115
https://github.com/o3de/o3de/security/dependabot/114
Built code without errors
=> Updated certifi to resolve security notices

Code/Framework/AzFramework/Platform/Common/WinAPI/AzFramework/IO/LocalFileIO_WinAPI.cpp, Code/Legacy/CryCommon/WinBase.cpp, Code/Legacy/CrySystem/LocalizedStringManager.cpp
`Int32x32To64` macro internally truncates the arguments to int32, while `time_t` is 64-bit on most/all modern platforms. Therefore, usage of this macro creates a Year 2038 bug.
I detailed this issue a while ago in a writeup, and spotted the same issue in this repository when updating the list of affected repositories:
<https://cookieplmonster.github.io/2022/02/17/year-2038-problem/>
One more note - `WinBase.cpp` technically redefined `Int32x32To64` as operating on `uint64`, but without a deeper dive into the codebase I couldn't ascertain if it's used everywhere. With my changes, there is no need to worry about this problem in the first place.
Untested. It's a simple enough change that I hope a CI success will suffice.
=> Fix a Y2038 bug by replacing `Int32x32To64` with regular multiplication

Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.cpp
Fix #14153. The Lua Editor was crashing when modifications were made to a file and closed. This was due to a manual deletion on a QWidget (Qt always have ownership of QWidget).
Local build. Tested with the description of the issue :
- Open an existing script / new script
- Make a change to the file and save
- Close the script file
- Modifying a saved script in Lua Editor, then closing it's tab and choosing either Continue or Save
=> The lua editor doesn't crash anymore
=> Lua Editor : Fix issue #14153 - Crash when closing file

Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassLibrary.cpp
The output slot of a copy pass should not be cleared, especially when only copies an area and not the whole attachment bound to the slot.
ASV
=> Bugfix: Removing Clear in CopyPass Output slot.

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Material/Material.h, Gems/Atom/RPI/Code/Source/RPI.Public/Material/Material.cpp
Fixed race condition related with Material::m_shaderVariantReadyEvent.
`AZ::Event` is not thread safe. `MeshDrawPacket::Update()` was calling
`m_material->ConnectEvent(m_shaderVariantHandler);` from multiple threads.
The fix was to add a Mutex in Material class
that protects usage of `Material::m_shaderVariantReadyEvent`
fixes #18561
Tested in the Editor with `--rhi=vulkan` because there's a deadlock in DX12 when switching levels (Another issue to debug later see #18597).
Before this fix, When loading `SinglePlayer` level from `StarterGame` project, the Editor would always crash assert
as described in GHI #18561.
Then I created a `Default` level, to have a level I can switch to.
After the fix, loading the `SinglePlayer` level always succeeded, and I was able to change levels back and …
=> Fixed race condition related with Material::m_shaderVariantReadyEvent.

Code/Framework/AzCore/AzCore/std/containers/vector.h
Deletes the potential overloaded functions that use the iterator for position based operations to prevent accidental usage of AZStd::vector.  This is following [lemonade-dm's advice](https://github.com/o3de/o3de/issues/17636#issuecomment-2032334083)
Fixes https://github.com/o3de/o3de/issues/17636 
Followed steps in https://github.com/o3de/o3de/issues/17636
=> Prevent accidental use of `iterator` argument on AZStd::vector operations

Code/Framework/AzCore/AzCore/std/containers/intrusive_set.h
When using [intrusive_multiset_member_hook](https://github.com/o3de/o3de/blob/b8a8d94a5b3fb0819eec2e8886fdf297ab074c9d/Code/Framework/AzCore/AzCore/std/containers/intrusive_set.h#L120) in conjunction with [intrusive_multiset](https://github.com/o3de/o3de/blob/b8a8d94a5b3fb0819eec2e8886fdf297ab074c9d/Code/Framework/AzCore/AzCore/std/containers/intrusive_set.h#L144), a compile error when instantiating the template  occurs in the member function [Rotate](https://github.com/o3de/o3de/blob/b8a8d94a5b3fb0819eec2e8886fdf297ab074c9d/Code/Framework/AzCore/AzCore/std/containers/intrusive_set.h#L928) saying that:
```
getParentSide': is not a member of ....
```
When instantiating `intrusive_multiset`, the `Hook` template parameter can either be `intrusive_multiset_base_hook` or …
=> Fix intrusive_multiset::Rotate compilation error when using intrusive_multiset_member_hook

Gems/Multiplayer/Code/Source/Components/SimplePlayerSpawnerComponent.cpp, Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp
Properly spawn network prefabs that contain multiple entities in the right location by ensuring to keep children entities local transform. The child entity (as long as it contains a Network Transform) will move along as the parent controller is updated on the server/game
Adding fix to avoid distracting warnings during the network spawn process
Tested by running a server and 2 game launchers.
1. Created a 2-entity network player and ensured hierarchy remained
2. Tested using spawn points off the origin
Fixes #17987
=> Fix Network Prefab Multi-Entity Spawn Transform

Code/Framework/AzToolsFramework/AzToolsFramework/API/EditorViewportIconDisplayInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/Mocks/MockEditorViewportIconDisplayInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorHelpers.cpp, Code/Framework/AzToolsFramework/Tests/EditorViewportIconTests.cpp, Gems/AtomLyIntegration/AtomViewportDisplayIcons/Code/Source/AtomViewportDisplayIconsSystemComponent.cpp, Gems/AtomLyIntegration/AtomViewportDisplayIcons/Code/Source/AtomViewportDisplayIconsSystemComponent.h
Fixes issue https://github.com/o3de/o3de/issues/18567
Consider viewing the diff in side-by-side instead of combined mode.
This batch renders icons.  Note that the old API was retained, for backward compatibility, so all existing code in other gems will still work (none were found in the engine), but the new API is preferred.
After this change, I can't really notice a difference between icons on and off in terms of rendering for Startergame (A couple thousand icons).
Before this change, it would drop to about 4ps, from 60.
* Tested on the starter game assets
* Tested on a custom level which had multiple different icons at the same time
* Tested on a level with no icons.
* Basic editor smoke tests like selecting stuff, moving it, looking around, looking at blank areas with no icons at all, …
=> Fixes Slow Icon Rendering, Issue #18567

Code/Framework/AzFramework/AzFramework/Spawnable/Script/SpawnableScriptAssetRef.cpp, Code/Framework/AzFramework/AzFramework/Spawnable/Script/SpawnableScriptAssetRef.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/PerformanceCollectionNotificationBus.h, Gems/Atom/RPI/Code/Source/RPI.Private/PerformanceCVarManager.cpp, Gems/Atom/RPI/Code/Source/RPI.Private/RPISystemComponent.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/PerformanceCollectionNotificationBus.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp, Gems/Atom/RPI/Code/atom_rpi_public_files.cmake, Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/EditorMaterialSystemComponentNotificationBus.h
Improvements for Editor and in-Game Automation
1. Added SetAssetId(), GetAssetId() and IsValid() to `SpawnableScriptAssetRef` class and exposed them in the BehaviorContext for both Python and Lua. This helps a Lua script to create `SpawnableScriptAssetRef`s on the fly, while being able to check their validity before attempting to spawn them.
2. Regarding RPI Performance Collection, I added the `AZ::RPI::PerformanceCollectionNotificationBus` which notifies whenever the current batch of performance collection is complete. This is important because scripts can know when the collection is completed and submit a different performance collection job as needed.
3. `EditorMaterialSystemComponentNotificationBus` now uses a `mutex`, because the Editor was crashing saying that the …
=> Improvements for Editor and in-Game Automation

Code/Legacy/CrySystem/DebugCallStack.cpp, Code/Legacy/CrySystem/DebugCallStack.h, Code/Legacy/CrySystem/IDebugCallStack.h, Code/Legacy/CrySystem/SystemInit.cpp
First improvement over https://github.com/o3de/o3de/issues/6000. (**windows-only**)
Fixes and improve the built-in crash reporting dialog by replacing invalid MFC code with `NativeUIRequests` dialog. The MFC dialogs where compiling but never showing up as their resources IDS were never registered.
When a crash occurs, this is now what happens :
- You get a dialog to state that issue occured. If you want to report it, you can press "yes" and it will open o3de github on default browser and open the folder with crash dump and log in a windows explorer
- Past that you get the chance to try to save your current work (as it is using an old API, pretty sure its broken so that would need an additionnal cleanup)
- Finally, and *- only if the crash can be recoverred from -* you get this dialog. …
=> Built-in Crash Reporter : Fix and improve message box dialogs

Code/Framework/AzCore/AzCore/Serialization/Json/JsonDeserializer.cpp, Code/Framework/AzCore/AzCore/Serialization/SerializeContext.h, Code/Framework/AzFramework/AzFramework/Spawnable/Script/SpawnableScriptAssetRef.h, Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityHelpers.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityHelpers.h, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorEntityIconComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorEntityIconComponent.h, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorInspectorComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorInspectorComponent.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.hxx, Code/Framework/AzToolsFramework/Tests/EntityInspectorTests.cpp, Code/Framework/AzToolsFramework/Tests/UI/EntityPropertyEditorTests.cpp, Gems/MiniAudio/Code/Include/MiniAudio/SoundAssetRef.h, Registry/AssetProcessorPlatformConfig.setreg
See https://github.com/o3de/o3de/issues/18620 for a detailed issue report and what this fixes.
This PR fixes the issue by doing a few specific things to remedy it.
The main issue is described in #18620 but the gist of it is that Entity Icons are supposed to be the first visible draggable component in the inspector.   But they've been broken for a very long time and are always just using the transform icon until you click on them in the inspector.
While investigating this I found that the root cause is actually a fairly deep serialization issue causing all component ordering (at least, from the user's visible point of view) to be ignored and never saved, thus the icon system, which relies on querying the component ordering, never having the data to work with.
The main way I solved this …
=> Fixes issue #18620 - Icons not being correct And related other issues.

Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Logger.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Logger.h
This fixes a linker error when building the ScriptCanvas.Editor gem in release mode, but only when unity builds are turned off.
```
158/267] Linking CXX shared module bin/release/libScriptCanvas.Editor.so
FAILED: bin/release/libScriptCanvas.Editor.so 
: && /usr/bin/clang++-14 -fPIC -fno-exceptions -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Wno-inconsistent-missing-override -Wrange-loop-analysis -Wno-unknown-warning-option -Wno-parentheses -Wno-reorder -Wno-switch -Wno-undefined-var-template -msse4.1  -O2  -Wl,--no-undefined -fpie -Wl,-z,relro,-z,now -Wl,-z,noexecstack -shared  -o bin/release/libScriptCanvas.Editor.so External/ScriptCanvas-ad8df5c6/Code/CMakeFiles/ScriptCanvas.Editor.dir/release/Editor/ScriptCanvasEditorGem.cpp.o  -Wl,-rpath,"\$ORIGIN" …
```
=> Fix Linux release + non-unity builds for Empty Project

Gems/Atom/RHI/DX12/Code/Source/RHI/StreamingImagePool.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/StreamingImagePool.h
Fixes DX12::StreamingImagePool related deadlock.
Fixes #18623
Unlike Vulkan, DX12::StreamingImagePool uses a TiledAllocator, which is protected by `m_tileMutex`. The bug:
On the Main thread `m_tileMutex` was being locked before calling `AllocateImageTilesInternal`, and `AllocateImageTilesInternal` enqueues Work with AsyncUploadQueue and waits for it (While keeping `m_tileMutex` locked). This work is eventually processed by `Secondary Copy Queue`.
Due to unrelated work enqueued on The `Secondary Copy Queue`, the function `StreamingImagePool::ShutdownResourceInternal()` was being called which also locks `m_tileMutex`. The deadlock would occurred if the Main Thread already had `m_tileMutex` locked.
The Fix: Both `AllocateImageTilesInternal` and `DeAllocateImageTilesInternal` only use …
=> Fixes DX12::StreamingImagePool related deadlock.

Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.cpp
The issue was happening because during level switch we had following logic
1. RenderPipeline::ResetPersistentView is called which clears the main view
2.  DirectionalLightFeatureProcessor::CacheCascadedShadowmapsPass clears m_cascadedShadowmapsPasses
3.  RenderPipeline::SetPersistentView sets the main view
4. DirectionalLightFeatureProcessor::OnRenderPipelinePersistentViewChanged gets called but it incorrectly wasnt re-adding the cascade passes.
Fix - Remove the check within Step 4 that was skipping the part that re-added all the needed passes
Fixes https://github.com/o3de/o3de/issues/18477
Tested on shader ball scene within the editor (platform: PC)
=> Fix for shadows not working after switching levels

Code/Framework/AzToolsFramework/AzToolsFramework/API/EditorViewportIconDisplayInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/Mocks/MockEditorViewportIconDisplayInterface.h, Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorHelpers.cpp, Code/Framework/AzToolsFramework/Tests/EditorViewportIconTests.cpp, Gems/AtomLyIntegration/AtomViewportDisplayIcons/Code/Source/AtomViewportDisplayIconsSystemComponent.cpp, Gems/AtomLyIntegration/AtomViewportDisplayIcons/Code/Source/AtomViewportDisplayIconsSystemComponent.h
Chery-picks commit 40cdf65 from development.
* Fixes Slow Icon Rendering, Issue #18567
Fixes issue https://github.com/o3de/o3de/issues/18567
This batch renders icons.  Note that the old API was retained, for backward compatibility, so all existing code in other gems will still work (none were found in the engine), but the new API is preferred.
After this change, I can't really notice a difference between icons on and off in terms of rendering for Startergame (A couple thousand icons).
Before this change, it would drop to about 4ps, from 60.
I'm sure there's always a way to improve this further but just this change alone is enough for the icon rendering to no longer matter in terms of profiler performance, so other things should probably be looked at before we return to this.
basic tests …
=> Cherrypick from Dev - Fixes Slow Icon rendering

Gems/LyShine/Code/Source/LyShinePass.cpp, Gems/LyShine/Code/Source/RenderGraph.cpp, Registry/sceneassetimporter.setreg
- Adds support to load .obj files within O3DE
- Minor crash fixes by adding a null check. Use Hide whitespace
Tested on PC with .obj assets
=> Added .obj support + minor crash fixes

Gems/AWSGameLift/Code/AWSGameLiftServer/CMakeLists.txt
GameLift server should only bring in Multiplayer gem server, not unified. Otherwise, this causes servers to enable AZ_TRAIT_CLIENT, breaking an important multiplayer paradigm
Fixes #18444
=> Merging GameLift Fix to 24092 

Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/MaterialComponentBus.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
Added two new methods to MaterialComponentRequestBus:
1. IsMaterialAssetReady(const MaterialAssignmentId& materialAssignmentId);
2. IsDefaultMaterialAssetReady(const MaterialAssignmentId& materialAssignmentId);
This is useful because at runtime you may not get the actual value of a particular material property if the MaterialAsset associated to a particular MaterialAssignmentId has not been loaded in memory.
For a Lua or Python script, once IsMaterialAssetReady() returns `true`. it is guaranteed that any of the GetPropertyValueXXX() methods will actually return a non-default value.
Validated with a Lua Script that, upon entering Game mode, printed the states of  `IsDefaultMaterialAssetReady`  and `IsMaterialAssetReady` during `OnTick` events, along with the value of `baseColor.color` …
=> MaterialComponentRequestBus::IsMaterialAssetReady

Code/Tools/SceneAPI/SDKWrapper/AssImpSceneWrapper.cpp, Code/Tools/SceneAPI/SceneBuilder/SceneSystem.cpp
This aims to fix the issue where some glTF files being imported with wrong rotations.
Some glTF files don't store coordinate system information and require manual adjust when imported into O3DE (rotate 90 degrees on X axis). This PR fixes this by assuming model files using DCC coordinate system unless explicitly specified by the model.
Export a glTF file from Unreal Engine to O3DE.
=> Assimp importer use DCC (Y-Up) coordinate system by default.

Code/Framework/AzCore/AzCore/Math/Quaternion.cpp, Code/Framework/AzCore/AzCore/Math/Quaternion.h, Code/Framework/AzCore/AzCore/Math/Quaternion.inl, Code/Framework/AzCore/Tests/Math/QuaternionTests.cpp, Gems/Maestro/Code/Source/Cinematics/CompoundSplineTrack.cpp
Closes https://github.com/o3de/o3de/issues/18639
* Adds methods for `Quaternion` to Euler (actually Tait-Bryan) Angles computations for `XYZ`, `YXZ`, `ZYX` rotations:
* * Adds these new (and older but missed) `Quaternion` methods to behavior contex reflection; adds `AZ::Script::Attributes::Deprecated` attribute to old reflected methods which should be deprecated (but `AZ::Script::Attributes::ExcludeFrom` attribute is added as comment only for now).
* * Adds unit tests for these new methods and also adds comparing `XYZ` conversions to old "Euler" conversions (which are presumably to be deprecated, please see Issue https://github.com/o3de/o3de/issues/10929);
* * Adds missing comments to declarations of methods to be deprecated.
* * Moves the `Quaternion::GetEulerRadians()` method (which is …
=> Track View: Fix issue #18639 : recording camera rotations.

Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.hxx
Fixes issue #4864 - https://github.com/o3de/o3de/issues/4864
Turns out that the outliner was creating undo/redo on selection change, which is fine, but not if the selection change is BECAUSE of an undo/redo.
Tested by undoing and redoing many slice edits and operations including opening and closing.
=> Fixes an assert that occurs if you undo/redo prefab focus

Gems/Atom/RHI/Code/Include/Atom/RHI/Device.h, Gems/Atom/RHI/Code/Tests/Device.h, Gems/Atom/RHI/DX12/Code/Source/RHI/CommandQueue.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/CommandQueue.h, Gems/Atom/RHI/DX12/Code/Source/RHI/Device.cpp, Gems/Atom/RHI/DX12/Code/Source/RHI/Device.h, Gems/Atom/RHI/Metal/Code/Source/RHI/Device.h, Gems/Atom/RHI/Null/Code/Source/RHI/Device.h, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.h, Gems/Atom/RHI/Vulkan/Code/Source/RHI/PhysicalDevice.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/PhysicalDevice.h, Gems/Atom/RPI/Code/Tests/Common/RHI/Stubs.h, Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiGpuProfiler.h, Gems/Atom/Utils/Code/Source/ImGuiGpuProfiler.cpp
https://github.com/o3de/o3de/pull/18500 introduced multiple timelines for multiple GPUs to the GPU Profiler -> TimestampView.
And it already mentioned one remaining issue, which is that GPU timestamps are not in one reference frame, hence cannot be compared directly against one another, i.e. timelines are not scaled/shifted appropriately in relation to one another.
This can be solved with calibrated timestamps ([vulkan](https://registry.khronos.org/vulkan/specs/latest/man/html/VK_KHR_calibrated_timestamps.html) / [dx12](https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12commandqueue-getclockcalibration)), which returns a "simultaneous" timestamp on the CPU and a GPU.
Given this, one can relate timestamps from multiple GPUs to CPU timestamps, hence bring them into one …
=> Calibrated Timestamps for multi-device timestamp comparability

Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.h
Improves
https://github.com/o3de/o3de/issues/18656
It turns out that when you make a trivial edit, so for example, modifying a simple entity property like a property field or a transform, the system already 
1. updates the instance being edited (its cached json DOM) when it captures the undo
2. updates the template it belongs to (the prefab file in memory that the instance came from) as part of the commit op.
3. updates the actual entity being modified (this happens as you drag the entity around or modify its properties)
4. adds instances of this prefab being modified to the queue to propagate to other instances in the level.
The problem is, it adds the instance being edited to that queue *as well as* any other instances in the scene of that same prefab.
The main thing that this does is …
=> Improves the performance of making trivial edits in a large level

Code/Editor/AnimationContext.cpp
Closes https://github.com/o3de/o3de/issues/15023
Partially fixes https://github.com/o3de/o3de/issues/8486:
The  `CSelectTrack` track is animated in TrackView, but is not properly animated in Play Game mode.
Adds forcing recent changes made in TrackView, - updating in-memory prefab using Undo/Redo framework, - when switching into Play Game mode.
Also ensures that the active sequence restarts from the beginning.
Editor run under Windows, a cut-scene with reproduction steps from the issue https://github.com/o3de/o3de/issues/15023 created.
When playing game after adding transform keys, without any other actions, sequence is properly animated.
=> [Track View] Fix for the issue #15023: Force recent changes made in TrackView when switching to Play Game mode

Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Asset/AssetUtils.h, Gems/Atom/RPI/Code/Source/RPI.Reflect/Asset/AssetUtils.cpp
Fixes deadlocks that occurred on some ASV tests.
Some AtomSampleViewer tests use `AZ::RPI::AssetUtils::AsyncAssetLoader` to load StreamingImages, which always deadlocks if StreamingImage resources are instantiated under the scope of AssetBus::OnAssetXXX events:
```
** Main Thread                | ** Secondary Copy Queue Thread
AssetBus::lock(mutex)         |
AssetBus::OnAssetReady        |
StreamingImage::FindOrCreate  |
AsyncUploadQueue::queueWork   |
Wait For Work Complete        |
|
| workQueue signaled
| Pop Work
| StreaminImage::Destructor()
| AssetBus::Disconnect()
| AssetBus::lock(mutex) <- Deadlocked
```
The solution is that AsyncAssetLoader simply saves the asset reference upon OnAssetXXX events, and connects to the SystemTickBus to dispatch the callback on the next System Tick. …
=> Fixes deadlocks that occurred on some ASV tests.

Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp, Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.h, Gems/Atom/Feature/Common/Code/Source/SkyAtmosphere/SkyAtmosphereFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/SkyAtmosphere/SkyAtmosphereFeatureProcessor.h, Gems/Camera/Code/Source/CameraComponentController.cpp, Gems/Camera/Code/Source/CameraComponentController.h, Gems/Stars/Code/Source/StarsFeatureProcessor.cpp
This is a collection of simulation-related cherry-picks that should be integrated into the next `point release`.
- #18475 - fixes the issue with stars rendering in ROS2 Camera
- #18476 - fixes the issue with sky rendering in ROS2 Camera
- #18524 - experimental feature (hidden behind the registry setting) to allow pipeline modifications in render-to-texture functionality (used in ROS2 Camera)
- #18531 - fixes the issue with terrain rendering in ROS2 Camera
One additional fix from #18510 was included in this PR, as it was related to the same codebase, namely:
> The BRDF texture pipeline was included under "if (loadDefaultRenderPipeline)", which means if the default pipeline isn't loaded, as is the case for VR/XR, the BRDF texture pipeline wouldn't run and the BRDF texture would never get …
=> sig-simulation cherries for 2409.2 point release

Code/Editor/Util/EditorUtils.h, Code/Framework/AzCore/AzCore/std/string/regex.h, Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/IO/SystemFile_WinAPI.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/TitleBarOverdrawScreenHandler_win.cpp, Code/Tools/TestImpactFramework/Runtime/Common/Code/Source/Artifact/Factory/TestImpactTestRunSuiteFactory.cpp, Gems/Atom/Utils/Code/Include/Atom/Utils/StableDynamicArray.inl, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/AbstractCodeModel.cpp, cmake/Platform/Common/Clang/Configurations_clang.cmake
See https://github.com/o3de/o3de/issues/18470 w.r.t. compiler flags. However, this should be fixed properly in the code at some point to avoid those depricated flags.
Multiple errors need to be fixed in order to get o3de to compile with clang 19. Many (rather serious/obvious) errors are within template functions that are never instantiated but which clang 19 seems to at least compile partially.
Compiling o3de with clang 19.
=> Clang 19 fixes.

Gems/Atom/RHI/Vulkan/Code/Source/RHI/Instance.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.h
This adds initial support for HDR output on the Vulkan RHI, the same amount of support as the DX12 RHI.
This should be possible even though there isn't a direct P2020 color space available in Vulkan as [VKD3D](https://github.com/HansKristian-Work/vkd3d-proton) can handle
displaying DX12 games using that color space (by the looks of it) just fine.
You can see some parts on how this is handled:
- Converting the DX12 color space enum: [here](https://github.com/HansKristian-Work/vkd3d-proton/blob/b5696e19c4b22b1c341a78391d9618acf8e004ff/libs/vkd3d/swapchain.c#L1496)
- Converting the DX12 HDR metadata: [here](https://github.com/HansKristian-Work/vkd3d-proton/blob/b5696e19c4b22b1c341a78391d9618acf8e004ff/libs/vkd3d/swapchain.c#L859)
- Distro: Fedora KDE Spin 41
- Enabled HDR on my main monitor …
=> Vulkan RHI: HDR Support

Gems/Atom/RPI/Code/Source/RPI.Public/Image/StreamingImage.cpp
/We5233 is enabled in `Configurations_msvc.cmake`, somehow this one is not caught by the CI which is using `MSVC 19.36.32532.0`, but it would be caught compiling in visual studio 2019.
This PR fixes it.
Running in Windows
=> Fix compiling in Visual Studio 2019

Gems/Atom/Feature/Common/Assets/Shaders/LightCulling/LightCulling.azsl
This PR improves number of lights that can be culled away before running __Opaque Pass__.
Main motivation was to minimize effect of black box flickering on long scenes with many lights
An example scene was created:
100 x 100 cadeus were place 1m apart
25 x 25 Lights were placed 5m apart
Each light contains 
- Spot / Disk Light - radius 40m
- Quad Light - radius 8m
- Point Light - radius 2m
https://github.com/user-attachments/assets/834b907c-aaea-4e18-a87f-9e95a824dc9b
> [!NOTE]
> More black boxes are visible in the video than on a single frame because they are flickering due to unpredictable light ordering when number of lights for tile exceeds `NVLC_MAX_POSSIBLE_LIGHTS_PER_BIN` 
https://github.com/user-attachments/assets/e99c7064-66cf-4531-8e21-08399ca5d92a
> [!NOTE]
> Flickering is …
=> Improve light culling for Disk and Spot Lights

Gems/Atom/Utils/Code/Source/ImGuiGpuProfiler.cpp
The ImGui GPU profiler currently collects passes from all pipelines, even ones that are not active.
E.g. when the Preview Pipeline runs for one frame the pass timings are written, but then never updated again.
This leads to passes from past renderings still showing up in the Profiler:
https://github.com/user-attachments/assets/d41bb210-32ac-4483-a397-a085c49e306f
This commit adds a check while collecting the passes and ignores passes from render pipelines that are don't render this frame.
Tested on Windows
=> ImGuiGpuProfiler: Ignore idle pipelines

Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/MaterialComponentBus.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
Fixes #18687 
`MaterialComponentController::OnSystemTick()` was missing the
additional check that `m_notifiedMaterialAssets` must be empty in order to call
`SystemTickBus::BusDisconnect()`.
Also added `GetMaterialMapCopy()` function to `MaterialComponentRequestBus`
so Lua scripts can actually make a copy of the current MaterialMap.
Validated on Win11 with Lua script that follows the steps as reported by Reverb. The Lua Script is available as an attachment in GHI #18687 .
=> Fixes #18687

Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/MaterialComponentBus.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
Cherry-pick #18688 
* Fixes #18687
Inside MaterialComponentController::OnSystemTick was missing the additional check that `m_notifiedMaterialAssets` must be empty in order to call `SystemTickBus::BusDisconnect()`.
Also added `GetMaterialMapCopy()` function to `MaterialComponentRequestBus` so Lua scripts can actually make a copy of the current MaterialMap.
Validated on Windows with Lua Script attached to #18687
=> Fixes #18687 (#18688)

Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderDataSystem.cpp
When a Script Canvas graph is processed by AP, the `DataSystem` class stores the results of processing a source file for both editor-configurable properties and for runtime ready assets for faster retrieval when many are being simultaneously processed.
The map that stores the processed data `m_buildResultsByHandle` was not being cleared between uses of this system which was leaving it with invalid (e.g. deleted) variable data.
This change ensures that the `m_buildResultsByHandle` map is cleared before each compilation so that no stale data is present when compiling the graph.
Closes #16010
=> Clear build results before each compilation

Gems/Terrain/Code/Mocks/Terrain/MockTerrainRPISystemComponent.h, Gems/Terrain/Code/Source/Components/TerrainSystemComponent.cpp, Gems/Terrain/Code/Tests/TerrainTestFixtures.cpp, Gems/Terrain/Code/Tests/TerrainTestFixtures.h, Gems/Terrain/Code/terrain_mocks_files.cmake
The TerrainSystemComponent uses the `PassSystemInterface` in its Activate function, but does not depend on the RPISystem.
This PR adds this needed dependency.
Tested on windows with the startergame-assets project
=> TerrainSystemComponent: Add RPISytem as a dependency

Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/PreviewRenderer/PreviewContent.h, Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRenderer.cpp, Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRenderer.h, Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRendererCaptureState.cpp, Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRendererCaptureState.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewContent.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewContent.h
Fixes #18646
It was found that the PreviewRenderer was not allowing itself enough time for the scene to be loaded in GPU and ready to render.
Instead of simply increasing the wait time, this fix uses a more reliable signal from the MeshFeatureProcessor that notifies us when the MeshDrawPacket has been updated in GPU memory and ready to render:
AZ::Render::ModelDataInstanceInterface::MeshDrawPacketUpdatedEvent
Validated on PC (Debug & Profile builds) with a large scene from KitBash3D. See attached video:
<video src="https://github.com/user-attachments/assets/c4b76ee2-bdb4-4c00-aed4-c2a4bc63cd55" controls></video>
=> Fixes Material Previews are not showing actual material

Code/Editor/AnimationContext.cpp, Code/Editor/TrackView/KeyUIControls.h, Code/Editor/TrackView/SelectKeyUIControls.cpp, Code/Editor/TrackView/TrackViewDialog.cpp, Code/Editor/TrackView/TrackViewDopeSheetBase.cpp, Code/Editor/TrackView/TrackViewTrack.cpp, Code/Legacy/CryCommon/AnimKey.h, Code/Legacy/CryCommon/IMovieSystem.cpp, Code/Legacy/CryCommon/IMovieSystem.h, Gems/Maestro/Code/Source/Cinematics/AnimTrack.h, Gems/Maestro/Code/Source/Cinematics/Movie.cpp, Gems/Maestro/Code/Source/Cinematics/Movie.h, Gems/Maestro/Code/Source/Cinematics/SceneNode.cpp, Gems/Maestro/Code/Source/Cinematics/SceneNode.h, Gems/Maestro/Code/Source/Cinematics/SelectTrack.cpp, Gems/Maestro/Code/Source/Cinematics/SelectTrack.h
Closes https://github.com/o3de/o3de/issues/5361 - in the part related to Playing Game mode;
Closes https://github.com/o3de/o3de/issues/8486 - in the part related to Playing Game mode;
The legacy implementation of the Director -> Camera (switching) cut-scene track in `ISelectKey` / `ISelectTrack` / `CAnimSceneNode` classes has the following major problems:
* The `ApplyCameraKey()` code implements only editor viewport camera switching, but in Game mode camera switching is unsupported;
* This code does not evaluate **invalid** `ISelectKey`{s}, which were added by user but not initialized with correct camera controller `EntityId` and `Entity` name;
* As legacy implementation for the additional animation camera has been removed, this code still changes existing camera properties (FoV, near …
=> [TrackView] Refactor and fix camera switching  both in Editing and Play Game modes

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassAttachment.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/CopyPass.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassAttachment.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp
Since pointers are kept to the PassAttachments we need a container that doesn't change location when reallocating, i.e., a deque, and due to the pointers being kept even during a rebuild, we need to not clear the container.
See GHI #18438
ASV
=> Make the number of potential PassAttachments variable.

Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/VariablePanel/GraphVariablesTableView.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/AbstractCodeModel.cpp
The name of the variable selected when promoting a node's slot was incorrectly set to "(1) (1)", even though an effort was made to determine a viable name, it wasn't being used. This change uses the name if it was determined.
The other change fixes the AP error that would happen after promoting the variable. When a variable was promoted it was being added to the Abstract Code Model as a function scope variable, however, a promoted variable is used as a variable reference, for this to work correctly the variable should be a member variable, otherwise the behavior would be undefined since the variable would be within the function's scope and not actually a reference.
Closes #3101
=> Script Canvas: Fixed issue with promoting variables from a node's slot

Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
#18673 changed how attachment bindings are stored in the pass class, but not all functions which access these were updated correctly. For example, the function `FindAttachmentBinding` would iterate over all entires in `m_attachmentBindings` and return a potentially invalid value, as the number of valid entires is stored separately in `m_attachmentBindingsSize`. 
AR + Test with an internal gem, which crashes due to the previous behavior, and does no longer crash with this PR.
=> Fix some pass attachment binding-related functions not being updated to the new deque-based storage method

Gems/ScriptCanvas/Code/Editor/View/Widgets/VariablePanel/GraphVariablesTableView.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/VariablePanel/GraphVariablesTableView.h, Gems/ScriptCanvas/Code/Editor/View/Widgets/VariablePanel/VariableDockWidget.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/VariablePanel/VariableDockWidget.h
When variables got renamed the variable's datum label was not being updated, since that's a serialized field, not updating it meant that the data saved to the source file was out of sync with what was actually present in the editor.
Also found that the GraphModel was not notifying of a data change on rename.
Closes #11397
=> Update the variable's property tree on rename

Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Slot.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Slot.h
When a variable is renamed the Slot class was not handing the rename. While fixing this I noticed that `PostActivate` was being called twice which didn't appear to cause any side effects but was not correct. 
Changed the handler for `VariableNotificationBus` to MultiHandler, a graph can have multiple nodes which have slots with different VariableId, but same graph Id. It's possible we should change the `GraphScopedId` to use the Node ID, Graph ID, and Variable ID to be more accurate. 
Closes #7996
=> Update slot names if the referenced variable is renamed

Gems/Atom/Feature/Common/Code/Include/Atom/Feature/ScreenSpace/DeferredFogParams.inl, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/ScreenSpace/DeferredFogSettingsInterface.h, Gems/Atom/Feature/Common/Code/Source/ScreenSpace/DeferredFogSettings.cpp, Gems/Atom/Feature/Common/Code/Source/ScreenSpace/DeferredFogSettings.h, Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/ScreenSpace/DeferredFogComponentConfig.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/ScreenSpace/DeferredFogComponentConfig.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/ScreenSpace/DeferredFogComponentController.cpp
Closes https://github.com/o3de/o3de/issues/14746
Unifies generation of boolean 'Enable' attributes in `DeferredFogRequestsBus`, `class DeferredFogSettingsInterface`, `class DeferredFogSettings`, `class DeferredFogComponentConfig`, `class DeferredFogComponentController`:
removing legacy definitions and usage or these atributes in above mentioned classes and adding `AZ_GFX_BOOL_PARAM()` macros to `DeferredFogParams.inl`.
This exposes missing boolean 'Enable' attributes of DeferredFog to the bus  and behavior reflections.
Release and Profile Editors were run under Windows, desired functionality observed:
https://github.com/user-attachments/assets/84b3a2ed-2181-4430-9f41-47120268b3f9
=> Fix issue #14746: expose Enable controls of DeferredFog to TrackView sequence

Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/ColorManagement/TransformColor.azsli, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/ColorManagement/TransformColor.h
The ColorSpaceId enum in TransformColor.h was missing the ACEScc field.
Removed the ColorSpaceIdCount because it was never used, and wasn't present in the .azsli enum.
This fixed the bloom example in AtomSampleViewer, resolving:
https://github.com/o3de/o3de-atom-sampleviewer/issues/391
=> Updated C++ ColorSpaceId to match the Shader.

Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Core.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Core.h
When saving a new file in ScriptCanvas it would sometimes go to the executable's folder instead of the project's root folder. The problem was that we'd send `AzQtComponents::FileDialog::GetSaveFileName` an invalid filename and the function would handle that by returning the executable's folder.
This change stores the suggested filename that was used when creating the new asset and using it for the open save file dialog but also it ensures that the folder that we specify exists.
Also removed some additional file name validation, the `AzQtComponents::FileDialog::GetSaveFileName` already verifies that the filename is valid.
Closes #13616 
Closes #13163
=> ScriptCanvas: Fix default file path when saving a new graph

Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
Currently, the Vulkan backend allocates as many queues as reported to be available in each queue family (`Device::InitInternal` in Vulkan's `Device.cpp:162`) while only needing 3, maybe (but unlikely) 4 queues: a graphics, a compute and a transfer queue (`CommandQueueContext::BuildQueues`) and a queue to present on, which if one of the first three supports it as usually is the case, that one is used (`CommandQueueContext::GetOrCreatePresentationCommandQueue`).
The issue is that on my 4090 (https://vulkan.gpuinfo.org/displayreport.php?id=35268#queuefamilies) this creates 30 queues and if I now increase the device count to get multiple logical devices, it fails to allocate a 6th device already as apparently the nvidia driver has a hard limit on how many queues can be created (for 6 it would …
=> Vulkan: Allocate only one queue per queue family.

Code/Framework/AzCore/AzCore/Asset/AssetManager.cpp, Code/Framework/AzCore/AzCore/EBus/EventSchedulerSystemComponent.cpp, Gems/EMotionFX/Code/Tests/AnimGraphCopyPasteTests.cpp, Gems/EMotionFX/Code/Tests/InitSceneAPIFixture.h, Gems/EMotionFX/Code/Tests/MotionExtractionBusTests.cpp, Gems/EMotionFX/Code/Tests/SystemComponentFixture.h, Gems/Maestro/Code/Source/Cinematics/AnimTrack.h, Gems/Maestro/Code/Tests/Tracks/AnimTrackTest.cpp, Gems/Multiplayer/Code/Tests/CommonHierarchySetup.h, Gems/Multiplayer/Code/Tests/CommonNetworkEntitySetup.h, Gems/Multiplayer/Code/Tests/MultiplayerSystemTests.cpp, Gems/Multiplayer/Code/Tests/NetworkEntityTests.cpp, Gems/Multiplayer/Code/Tests/NetworkRigidBodyTests.cpp, Gems/ScriptEvents/Code/Include/ScriptEvents/ScriptEventSystem.cpp, Gems/ScriptEvents/Code/Include/ScriptEvents/ScriptEventSystem.h, Gems/ScriptEvents/Code/Source/Editor/ScriptEventsSystemEditorComponent.cpp, Gems/ScriptEvents/Code/Source/ScriptEventsSystemComponent.cpp, Gems/SurfaceData/Code/Tests/MixedAllocatorTest.cpp
Fixes every ASAN issue that I found while running every gem's googletest/googlemock tests with debug + Address Sanitizer.
This does NOT fix ASAN issues that might be lurking in the actual editor, runtime, tools that are not exposed by their tests, or changes required 3rd party libraries, or our use of them.  I intend to follow up with corrections for MCPP and OpenMesh both of which need work for ASAN.
Running through the tests in question.
Basic smoke test of the editor and tools.
=> Fixes all remaining Address Sanitizer issues in gem tests

Gems/Atom/RHI/Code/Include/Atom/RHI/Buffer.h, Gems/Atom/RHI/Code/Include/Atom/RHI/BufferView.h, Gems/Atom/RHI/Code/Include/Atom/RHI/FrameGraphCompiler.h, Gems/Atom/RHI/Code/Include/Atom/RHI/Image.h, Gems/Atom/RHI/Code/Include/Atom/RHI/ImageScopeAttachment.h, Gems/Atom/RHI/Code/Include/Atom/RHI/ImageView.h, Gems/Atom/RHI/Code/Include/Atom/RHI/Resource.h, Gems/Atom/RHI/Code/Include/Atom/RHI/ShaderResourceGroupData.h, Gems/Atom/RHI/Code/Source/RHI/Buffer.cpp, Gems/Atom/RHI/Code/Source/RHI/BufferScopeAttachment.cpp, Gems/Atom/RHI/Code/Source/RHI/BufferView.cpp, Gems/Atom/RHI/Code/Source/RHI/FrameGraphCompileContext.cpp, Gems/Atom/RHI/Code/Source/RHI/FrameGraphCompiler.cpp, Gems/Atom/RHI/Code/Source/RHI/Image.cpp, Gems/Atom/RHI/Code/Source/RHI/ImageScopeAttachment.cpp, Gems/Atom/RHI/Code/Source/RHI/ImageView.cpp, Gems/Atom/RHI/Code/Source/RHI/Resource.cpp, Gems/Atom/RHI/Code/atom_rhi_public_files.cmake, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Conversion.cpp, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Buffer/Buffer.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Specific/DownsampleSinglePassLuminancePass.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Image/Image.h
As surfaced in https://github.com/o3de/o3de/issues/18706, there is an issue with the change in implementation that happened during the transition to multi-device resources.
The initial goal was not to have a two-layer cache hierarchy for `ResourceView`s and `DeviceResourceView`s, but leave the lower level as is and re-create `ResourceView` s on demand.
`DeviceResource`s have a "recreation" cache, a cache that does not actually cache the resource by holding its memory, but a cache that holds raw pointers to the memory.
I.e., if some other code (for example `DeviceShaderResourceGroupData`) already requested a `DeviceResourceView` on a `DeviceResource` and was holding a smart pointer to this object, then the cache in the `DeviceResource` would be able to provide access to this as well, …
=> Add recreation cache for `ResourceView` to `Resource`

Code/Tools/SceneAPI/SceneBuilder/SceneSystem.cpp, Templates/DefaultProject/Template/Registry/assimp_settings.setreg, Templates/DefaultProject/template.json, Templates/MinimalProject/Template/Registry/assimp_settings.setreg, Templates/MinimalProject/template.json, Templates/ScriptOnlyProject/Template/Registry/assimp_settings.setreg, Templates/ScriptOnlyProject/template.json
The new behavior shall assume AssImp's transform is always Y-up. The new behavior can be enabled by setting registry /O3DE/Preferences/SceneAPI/AssImpReadRootTransform, which is disabled by default.
Not yet tested
=> [WIP] Add a setting registry that allows AssImp to change behavior when importing coordinates

Code/Editor/TrackView/KeyUIControls.h, Code/Editor/TrackView/StringKeyUIControls.cpp, Code/Editor/TrackView/TrackViewDopeSheetBase.cpp, Code/Editor/TrackView/TrackViewDopeSheetBase.h, Code/Editor/TrackView/TrackViewKeyPropertiesDlg.cpp, Code/Editor/TrackView/TrackViewPythonFuncs.cpp, Code/Editor/editor_lib_files.cmake, Code/Legacy/CryCommon/AnimKey.h, Code/Legacy/CryCommon/IMovieSystem.h, Code/Legacy/CryCommon/Maestro/Bus/SequenceComponentBus.h, Code/Legacy/CryCommon/Maestro/Types/AnimValueType.h, Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.cpp, Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.h, Gems/Maestro/Code/Source/Cinematics/AnimNode.cpp, Gems/Maestro/Code/Source/Cinematics/AnimSerializer.cpp, Gems/Maestro/Code/Source/Cinematics/AnimSplineTrack.h, Gems/Maestro/Code/Source/Cinematics/AnimTrack.h, Gems/Maestro/Code/Source/Cinematics/CompoundSplineTrack.h, Gems/Maestro/Code/Source/Cinematics/StringTrack.cpp, Gems/Maestro/Code/Source/Cinematics/StringTrack.h, Gems/Maestro/Code/Source/Components/SequenceAgent.cpp, Gems/Maestro/Code/Source/Components/SequenceComponent.cpp, Gems/Maestro/Code/maestro_static_files.cmake
Closes https://github.com/o3de/o3de/issues/9044
Adds new `CStringTrack` support:
* Updated  `enum class AnimValueType`, adding `String` enum value;
* Updated `IAnimTrack` interface, adding getters and setters for `AZStd::string` values (in `IMovieSystem.h`; also fixed some typos and unified formatting in several places);
* Updated `TAnimTrack`, `TAnimSplineTrack` and `CCompoundSplineTrack` template classes, adding getters and setters for `AZStd::string` values;
* Added new `struct IStringKey`; updated `AnimSerializer::ReflectAnimTypes()` with serialization of string for this key type;
* Updated `class SequenceComponentRequests` (and thus` SequenceComponentRequestBus`):
* * Updated `class AnimatedValue` interface, adding abstract getters and setters for `AZStd::string` values;
* * Updated …
=> [Track View] Add string track support, - fixing issue #9044.

Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbNativeWindow.cpp, Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbNativeWindow.h, Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp
This PR introduces a CVAR parameter `r_resizable`, responsible for setting the resizable flag on the window's style mask when creating the window, allowing for setting the resizability of the game window when launching the game via a command-line argument. By default, this argument is set to true, which means the window is resizable by default.
Additionally, it fixes the way the resizable flag was handled in XcbNativeWindow. Previously, the window would always be resizable regardless of whether this flag was set or not. Now it will only be resizable when this flag is set.
A game launcher was built and run with parameters `r_resizable=0` and `r_resizable=1` on Ubuntu 24, which uses the XCB interface to manage the window. With `r_resizable=0` the window was not resizable, and with …
=> Allow to set window resizability from a console parameter and fix resizability handling in XCB.

Gems/Atom/Feature/Common/Code/Source/PostProcess/PostProcessFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/ScreenSpace/DeferredFogPass.cpp, Gems/Atom/Feature/Common/Code/Source/ScreenSpace/DeferredFogSettings.h
When the DeferredFog component is present in a level, the noise texture for the fog was reloaded every frame. This took about 0.75ms every frame on my machine.
This PR fixes two things for the fog settings:
1. The `m_blendedPerViewSettings` in the PostProcesFeatureProcessor were deleted every frame and created anew. Thus a potentially loaded image was also deleted. We now reset the settings per view instead of clearing the whole map.
2. The noise texture was reloaded every time a settings changed in the DeferredFogSettings. Added a variable to remember which images is currently loaded.
Tested on Windows with Vulkan/DX12 in a level with fog
=> DeferredFog: Don't reload the noise texture every frame

Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/GraphOutliner/GraphOutlinerDockWidget.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LiveWindowSession/LiveLoggingDataAggregator.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LiveWindowSession/LiveLoggingDataAggregator.h, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LiveWindowSession/LiveLoggingWindowSession.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LiveWindowSession/LiveLoggingWindowSession.h, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindow.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindow.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Asset/ExecutionLogAsset.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Asset/ExecutionLogAsset.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/ExecutionNotificationsBus.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/ExecutionNotificationsBus.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Bus.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Logger.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Logger.h
When closing the Script Canvas editor, there is a double delete because the tabWidget created during initialization is tracked and destroyed by the parent, if we don't clear out the parent, the owning widget will attempt to delete it which results in a double deletion.
Also simplified the code that tracks the logging, one of the causes for the crash is that a member variable of AssetData class was being kept, this data would get deleted by the asset at some point which left it in an undefined state, when the owning object got deleted it would try to invoke the dtor for the ExecutionLogAsset which was already invalid resulting in the crash.
Closes #18724
=> ScriptCanvas: Fix crash on SC editor close

Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
Fixes https://github.com/o3de/o3de/issues/16415
The `DocumentPropertyEditor` requested a size update for every change in the Dom, even just a changed numerical value. This led to a performance problem when moving objects around the scene as a stylesheet was repolished every frame. On my machine this took around 14ms per frame, though it was significantly slower on other machines (see the linked issue)
The size update request was introduced in https://github.com/o3de/o3de/pull/16394 to fix issue https://github.com/o3de/o3de/issues/15945
Since then the DPE has changed quite a bit, and the size update request in `HandleReset` of the DPE is probably enough. I tried to reproduce the issue with my fix and could not do so.
See also the discussion on Discord: …
=> DPE: Don't request a size update for every Dom change

Code/Framework/AzCore/AzCore/Memory/SystemAllocator.cpp, Code/Framework/AzCore/Tests/Math/Matrix3x4Tests.cpp
Fixes:
https://github.com/o3de/o3de/issues/18720
Also fixes a compile error for the latest windows SDK.
I was unable to test this without also fixing a compiler error introduced by the latest windows SDK.
The latest windows SDK changed the basic definition of the macro `INFINITY` from being a huge number on its own, to be two huge numbers multiplied by each other.  This causes the compiler to error out with a 'math overflow' whenever INFINITY is used anywhere.
One of our tests uses it as an input number to test whether it can detect an infinite matrix.  I've bracketed the test with a push and pop for that warning.  It only happens on MSVC and only with latest SDK.
Actual testing was using vulkan rhi and malloc, but also compiling the tests and running azcore.tests
```
[----------] Global …
```
=> Fixes a issue #18720 (vulkan malloc crash) and compile error

Code/Editor/TrackView/KeyUIControls.h, Code/Editor/TrackView/TrackViewAnimNode.cpp, Code/Editor/TrackView/TrackViewAnimNode.h, Code/Editor/TrackView/TrackViewCurveEditor.cpp, Code/Editor/TrackView/TrackViewDopeSheetBase.cpp, Code/Editor/TrackView/TrackViewKeyPropertiesDlg.cpp, Code/Editor/TrackView/TrackViewTrack.cpp, Code/Editor/TrackView/VectorKeyUIControls.cpp, Code/Editor/editor_lib_files.cmake, Code/Legacy/CryCommon/IMovieSystem.h, Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.cpp, Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.h, Gems/Maestro/Code/Source/Cinematics/AnimNode.cpp, Gems/Maestro/Code/Source/Cinematics/AnimNode.h, Gems/Maestro/Code/Source/Cinematics/AnimSplineTrack.h, Gems/Maestro/Code/Source/Cinematics/AnimSplineTrack_Vec2Specialization.cpp, Gems/Maestro/Code/Source/Cinematics/AnimTrack.h, Gems/Maestro/Code/Source/Cinematics/CompoundSplineTrack.cpp, Gems/Maestro/Code/Source/Cinematics/CompoundSplineTrack.h
Closes: https://github.com/o3de/o3de/issues/18640
Closes: https://github.com/o3de/o3de/issues/18575
* Previously many glitches were noted, when users could not select a Sub-Key, if a Compond Key was selected, and vice-versa.
* There was no UI representing Compound Keys for editing in Key Properties Dialogs (both stationary in TrackVewDialog "Key" tab and "On Spot", - by  left button double click or right-button click-sub-menu) .
* UI sliders (i.e. min/max key value ranges) were not set in accordance with sub-track target properties.
* Manually adding keys to "Position" and "Rotation" Transform sub-tracks -> shifted / rotated animated entity from the last user-set positiion / orientation.
* Adds support for Key Editing UI with 3 or 4 values, stored in Compound Tracks.
Fully implemented for …
=> [Track View] Fix Compound Tracks Keys evaluation (selection, editing, addition).

Code/Framework/AzCore/AzCore/Settings/CommandLine.cpp, Code/Framework/AzCore/Platform/Android/AzCore/Settings/CommandLineParser_Platform.h, Code/Framework/AzCore/Platform/Android/platform_android_files.cmake, Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/Settings/CommandLineParser_UnixLike.cpp, Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/Settings/CommandLineParser_UnixLike.h, Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/Settings/CommandLineParser_WinAPI.cpp, Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/Settings/CommandLineParser_WinAPI.h, Code/Framework/AzCore/Platform/Linux/AzCore/Settings/CommandLineParser_Platform.h, Code/Framework/AzCore/Platform/Linux/platform_linux_files.cmake, Code/Framework/AzCore/Platform/Mac/AzCore/Settings/CommandLineParser_Platform.h, Code/Framework/AzCore/Platform/Mac/platform_mac_files.cmake, Code/Framework/AzCore/Platform/Windows/AzCore/Settings/CommandLineParser_Platform.h, Code/Framework/AzCore/Platform/Windows/platform_windows_files.cmake, Code/Framework/AzCore/Platform/iOS/AzCore/Settings/CommandLineParser_Platform.h, Code/Framework/AzCore/Platform/iOS/platform_ios_files.cmake, Code/Framework/AzFramework/Platform/Common/WinAPI/AzFramework/IO/LocalFileIO_WinAPI.cpp, Code/Tools/AssetProcessor/AssetBuilder/main.cpp, Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp, Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
This MR enables adding assets with unicode filenames or from unicode subfolders on Windows machines without enabled `Beta: Use Unicode UTF-8 for worldwide language support` (Windows 10) setting.
The only real production change for this was to remove the explicit check and error message in `assetProcessorManager.cpp`, and the change in `LocalFileIO::CreatePath` to enable creation of unicode folders. Everything else just seems to work™. The other changes were primarily for testing the AssetBuilder with the `-debug` flag from the commandline for these assets, which is also a nice thing to have.
Screenshot of the Asset, the Mesh component and the Material comonent:
Create some test FBX files with various non-latin characters (including material names).
All assets process successfully and can …
=> Enable usage of unicode asset names

Code/Framework/AzCore/AzCore/Memory/SystemAllocator.cpp, Code/Framework/AzCore/Tests/Math/Matrix3x4Tests.cpp
(Cherrypicking from stabilization branch)
See the original https://github.com/o3de/o3de/pull/18736
* Fixes a issue #18720 and a compile error with latest Windows SDK
Fixes:
https://github.com/o3de/o3de/issues/18720
I was unable to test this without also fixing a compiler error introduced by the latest windows SDK.
The latest windows SDK changed the basic definition of the macro `INFINITY` from being a huge number on its own, to be two huge numbers multiplied by each other.  This causes the compiler to error out with a 'math overflow' whenever INFINITY is used anywhere.
One of our tests uses it as an input number to test whether it can detect an infinite matrix.  I've bracketed the test with a push and pop for that warning.  It only happens on MSVC and only with latest SDK.
=> Cherrypick from stab: Fixes a issue #18720 (vulkan malloc crash) and compile error

Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.cpp
When declaring a buffer view with a clear action in a pass file, the buffer view is not taken into account when performing the clear action and the whole buffer is cleared instead in Vulkan (DX12 does not do this).
Test with an internal gem which uses this specific configuration for a slot (Bufferview of 1 uint from a larger buffer, the clear action should only clear this single uint):
```
"Name": "SomeBuffer",
"ShaderInputName": "m_someBuffer",
"SlotType": "InputOutput",
"ScopeAttachmentUsage": "Shader",
"BufferViewDesc": {
"m_elementOffset": "0",
"m_elementCount": "1",
"m_elementSize": "4",
"m_elementFormat": "R32_UINT"
},
"LoadStoreAction": {
"LoadAction": "Clear",
"StoreAction": "Store"
}
```
This code does not work correctly on Vulkan (works fine with DX12), and works as expected …
=> Fix buffer clear action clearing whole buffer instead of buffer view on Vulkan

Gems/Atom/RHI/DX12/Code/Source/RHI/ShaderResourceGroupPool.h
This PR adds a missing include in `RHI/DX12/.../ShaderResourceGroupPool.h`, which fixes a compile error when building the engine on Windows without unity build.
Compile with `-DLY_UNITY_BUILD=OFF` on Windows.
=> Add missing include in DX12/ShaderResourceGroupPool.h

Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassAttachment.h, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/CopyPass.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassAttachment.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp
This PR introduces a new `PassAttachmentBindingList` class which is used instead of the (`int m_attachmentBindingsSize`,`AZStd::deque<PassAttachmentBinding> m_attachmentBindings`)-pair to store pass attachment bindings with the same guarantees about pointer validity as before.
I introduced this class since the original approach does not guard against iteration over `m_attachmentBindings`, which is not allowed since it contains only valid entries in the range [0..`m_attachmentBindingsSize`]. In the original [PR18673](https://github.com/o3de/o3de/pull/18673) some instances of this iteration were missed, which were fixed in [PR18698](https://github.com/o3de/o3de/pull/18698); and now I found some more instances where such illegal iterations are still present (eg. in …
=> Ensure for-each loops with AZ::RPI::Pass::m_attachmentBindings use the correct attachment binding count

Code/Framework/AzCore/AzCore/Math/MathUtils.h, Code/Framework/AzNetworking/AzNetworking/DataStructures/FixedSizeBitset.inl, Code/Framework/AzNetworking/AzNetworking/DataStructures/RingBufferBitset.h, Code/Framework/AzNetworking/AzNetworking/DataStructures/RingBufferBitset.inl
This PR renames the function `AZ::Log2(uint64_t maxValue)` to `AZ::RequiredBitsForValue(uint64_t maxValue)`, since this what the function actually calculates (see #18653). The new function name is derived from the `RequiredBytesForValue<MAX_VALUE>()` function a few lines further down in the same file.
AR
=> Rename AZ::Log2 function to "RequiredBitsForValue"

Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/NsightAftermathGpuCrashTracker_Windows.cpp, Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/NsightAftermathGpuCrashTracker_Windows.h, Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/NsightAftermath_Windows.cpp, Gems/Atom/RHI/Vulkan/Code/Source/Platform/Windows/RHI/NsightAftermathGpuCrashTracker_Windows.cpp, Gems/Atom/RHI/Vulkan/Code/Source/Platform/Windows/RHI/NsightAftermathGpuCrashTracker_Windows.h
Moved  the `GpuCrashTracker` class to `AZ::DX12`/`AZ::Vulkan` namespaces.
Previously the crash trackers for DX12 and Vulkan were in the global namespace leading to linker errors in some situations. E.g. when a Gem uses the APIs introduced in https://github.com/o3de/o3de/pull/18450 for both Vulkan and DX12. This Gem needs to link to to both RHI backends linking both crash trackers.
Tested on Windows with and without aftermath with a Gem that links to both Vulkan and DX12
=> Move Aftermath crash tracker into namespaces

Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp
The TerrainMeshManager of the Terrain gem adds meshes to the ray tracing scene via `RayTracingFeatureProcessorInterface::AddMesh`, but does not set `m_instanceMask` on the `RayTracingFeatureProcessorInterface::Mesh` parameter (which has the default value 0), which leads to the terrain not being visible to ray tracing at all.
Create a small test scene with a terrain, and add the DebugRayTracing component. Without this PR, the terrain is not visible at all in the debug visualization; with this PR it shows up as expected.
* Left image: Terrain without ray tracing
* Middle image: RT debug visualization without this PR (only the groundplane and the shaderball are visible)
* Right image: RT debug visualization with this PR
Special thanks to @kh-huawei for finding this problem and for providing …
=> Fix RT-instanceMask for Terrain ray tracing meshes not being set

Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/GraphOutliner/GraphOutlinerDockWidget.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LiveWindowSession/LiveLoggingDataAggregator.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LiveWindowSession/LiveLoggingDataAggregator.h, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LiveWindowSession/LiveLoggingWindowSession.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LiveWindowSession/LiveLoggingWindowSession.h, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindow.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindow.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Asset/ExecutionLogAsset.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Asset/ExecutionLogAsset.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/ExecutionNotificationsBus.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/ExecutionNotificationsBus.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Bus.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Logger.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Logger.h
On the current stabilization of 25.05 version, the "SC editor close crash" bug is still present, thus I'm opening this PR to cherry-pick the bugfix PR to the `stabilization/25050` branch.
Original PR: #18734
Original issue: #18724
> [!NOTE]
> (Tested on Fedora Linux 40, on `profile`.)
I tested before and after the cherry-picking:
Before the cherry-pick:
1. Open the Script Canvas and close the editor: it will crash o3de.
After the cherry-pick:
1. Same as before
2. I made a little graph that spins the entity on the Z axis, with a rotation speed of `delta time * Speed`, where `Speed` is a "From Component" variable, initialized with `10` on the level.
On both cases, no problems found.
=> 25.05 Stabilization: ScriptCanvas: Fix crash on SC editor close

Code/Framework/AzCore/AzCore/std/containers/deque.h
This PR adds a missing dereference operator in the body of the function `AZStd::deque::at(size_t)`.
Try to use the function `deque::at(size_t) const`, which does not compile without this PR.
=> Add missing dereference operator in deque at() function

Gems/Atom/Feature/Common/Assets/Shaders/Materials/StandardPBR/StandardPBR_PixelGeometryEval.azsli
If a material type is not enabling parallax, it's material srg probably don't have `m_parallaxUvIndex` etc. But it is also including `ParallaxDepth.azsli` even `ENABLE_PARALLAX` is false, this will cause shader compile errors in some cases.
This MR fixes the include, as well as what we are doing in `MaterialGraphName_PixelGeometryEval.azsli`
Tested in windows.
=> Include ParallaxDepth.azsli for StandardPBR only when necessary

AutomatedTesting/Gem/PythonTests/editor/EditorScripts/BasicEditorWorkflows_LevelEntityComponentCRUD.py, Code/Framework/AzCore/Tests/AZStd/String.cpp, Gems/LyShine/Code/Source/TextMarkup.cpp, Gems/LyShine/Code/Source/UiTextComponent.cpp, Gems/MotionMatching/Code/Source/CsvSerializers.cpp
Some conversions from string to float, or float to string for tests or for serialize/deserialize 
... were not being done in the invariant ("C") locale and would fail if on a machine that had comma set as the decimal separator.
Ran the CI build locally.
=> Fixes intermittent test failures

Gems/Atom/Feature/Common/Code/Source/Debug/RayTracingDebugFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/Debug/RayTracingDebugFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.cpp
The application crashes in the DebugRayTracingPass when the level contains a terrain.
The `RayTracingDebugFeatureProcessor` adds the Debug - pass on demand if the Raytracing Debug - LevelComponent exists in the Scene, but it holds on to the pass.
If the Pipeline is rebuild (which the Terrain-Component causes), the debug - pass is not part of the rebuild pipeline hierarchy, which:
- causes a crash in the `IsEnabled()` function of the RayTracingPass, because `m_pipeline` is a nullpointer.
- means the DebugRayTracingPass will never be executed.
This PR fixes both issues by inserting a new `DebugRayTracingPass` in the `AddRenderPasses()` - function if the level contains a RayTracingDebug - component, and enabling / disabling of the pass happens more loosely coupled.
There is a separate issue …
=> Avoid a crash with the DebugRayTracingPass with terrain rendering

Code/Framework/AzToolsFramework/AzToolsFramework/API/ToolsApplicationAPI.h, Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.h, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/ScriptEditorComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/ScriptEditorComponent.h
fixes 
https://github.com/o3de/o3de/issues/10076 
Script properties would not initialize properly the first time a script is assigned.  They are expected to read the "Properties" block and then create a copy of that block in the component, to use as a cache.
The problem is that scripts load asynchronously, and the properties block is only created later, once the script loads, which is not inside the user-initiated "undo redo" block caused by assigning the script, and thus, is not saved.
This error also affected any file that was saved in such a state.  This fix retroactively causes those situations to repair themselves when the level is opened and warns the user when the fix is applied so that they can save the level again to permanently fix it.
Used the assets attached to the issue …
=> Fix lua script initialization properties (fixes #10076)

Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
This PR fixes an `AZ_Error` condition in `AZ::RPI::Pass::FrameBegin(...)` which checks if the pass is in the correct state. The condition only allows a pass to be in the `Idle` state, but the error message suggests `Queued` is also allowed. According to the discussion in #18752, the error message is correct and `Queued` is also allowed, so I changed the condition.
This was not a problem in the MainPipeline, but in a internal gem I was calling `Pass::QueueForBuildAndInitialization()` from `FeatureProcessor::Render`, which lead to this error message.
Tested using an internal gem, which ran into this error message. The same message does no longer occur, and as far as I can tell nothing else broke as a result.
=> Fix error message condition about pass state in Pass::FrameBegin

Code/Framework/AzToolsFramework/AzToolsFramework/API/ToolsApplicationAPI.h, Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.h, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/ScriptEditorComponent.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/ScriptEditorComponent.h
This is a cherry-pick of 
https://github.com/o3de/o3de/pull/18771 from stabilization into dev.
(fixes #10076)
* Fixes lua not initializing properties
* Makes sure that the user is warned when the fixup happens. Makes sure that the fixup only informs the user when something actually changes in the level, that requires their attention, and not when they are just changing scripts via properties and such.
=> (Cherry pick from Stab) Fix lua script initialization properties

Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialTypeBuilder.cpp
Material type builder is now iteratively combines materialtypes-materialpipelines-shadertemplates and generated the shaders for all cases, and **all material types are going through the same `VertexAndPixel` logic**. When writing the shading logics inside a `XXXVertexAndPixel.azsli` for a customize material pipeline, the developer has no way to know what material type is going to compile with, if someone wants to customize the shading for some specific material types it becomes impossible, especially some material types are sharing the same lighting model.
This PR automatically adds a macro definition before including the shader template's shader:
e.g.:
standardpbr_customized/material/pipeline_customized/shader.azsl
```
#define MATERIAL_PIPELINE_OBJECT_SRG_MEMBERS \
#define …
```
=> Add material type name definition in material pipeline generated shader

Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/Ltc.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/ClearCoatInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/SubsurfaceInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/MultilayerPBR/StandardMultilayerPBR_Common.azsli, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.h, Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/ShaderResourceGroups/DefaultDrawSrg.azsli, Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialPipelineSourceData.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/MeshDrawPacket.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Shader/ShaderResourceGroup.h, Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialTypeBuilder.cpp, Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialPipelineSourceData.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/MeshDrawPacket.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Shader/ShaderResourceGroup.cpp
This commit adds the ability to `*.materialpipeline` assets to add custom shader constants to DrawSrg.
The mechanism is implemented with json property `"drawSrgAdditions"`, which operationally works identical to the existing `"objectSrgAdditions"`.
Both consists as arrays of lines, where each line typically represents the data type and name of a shader constant that should be added to DrawSrg. Example:
```
"drawSrgAdditions": [
"float4 m_vector;",
"uint2 m_counters;"
]
```
Added API to MeshFeatureProcessor to query DrawSrgs from a given subMesh:
```
//! Returns the DrawSrg from the first DrawItem that matches @drawListTag
//! and its material pipeline matches @materialPipelineMask.
//! The search is done only within the DrawItems of the subMesh identifiable by the tuple (@meshHandle, …
```
=> MaterialPipeline assets can customize DrawSrg

Code/Editor/EditorViewportWidget.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
This is a follow-up to PR #18766.
When a sequence has Director with Camera Selection track, cameras are being switched during Undo / Redo.
Same happens when the Instance Update Executor is cleaning the prefab in-memory DOM Template after Undo / Redo.
Marking camera Entities as dirty in both cases rises redundant warnings and could break Undo / Redo operation.
So this PR disables marking camera Entities as dirty while Undo / Redo or DOM Template clean-up is in progress.
Profile and Release Editors run, expected behaviour noted: no redundant warnings noted.
=> [Track View] Fix switching camera while in Undo / Redo

Code/Editor/AnimationContext.cpp, Code/Editor/TrackView/TrackViewAnimNode.cpp, Code/Editor/TrackView/TrackViewNodes.cpp
Closes https://github.com/o3de/o3de/issues/6643
In fact, issue #6643 was mostly fixed earlier, so this PR just updates `CAnimationContext` to fix determination of "Editing Mode", excluding "Simulation Mode" from modes where editing features are enabled.
While analysing repro steps of #6643, I noted that Track View Dialog allows to add a sequence entitty as a Node to itself, 
so this PR also disables this troublesome feature, whichg may lead to unexpected cycled dependencies.
Profile and Release Editors run, expected behaviour noted.
=> [TrackView] Block adding a sequence to self.

Gems/ScriptCanvas/Code/CMakeLists.txt
Fixes bug https://github.com/o3de/o3de/issues/18790
>   Script canvas would crash (debug) or perform
>     undefined behavior when you pressed CTRL+G and the
>     script canvas window was open.
> 
>     This was because the CMake file applied a preprocessor
>     definition to targets in ScriptCanvas as PRIVATE, and that
>     preprocessor definition changed the size of a type
>     (It removed a member variable).
> 
>     The problem is, that header also contains a templated
>     function from a static library that will be compiled in other
>     compile units, not just the private target in ScriptCanvas,
>     causing undefined behavior.
> 
Its a 100% crash in debug, 0% crash after fixing.  So just run it in debug and make sure it doesn't crash anymore.
=> (stabilization) BUGFIX - Crash on CTRL+G if SC is open.

Gems/Atom/Feature/Common/Code/Source/Debug/RayTracingDebugFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/Debug/RayTracingDebugFeatureProcessor.h
This PR removes the `OnRenderPipelineChanged` override from `RayTracingDebugFeatureProcessor`, which leads to problems when more than one pipeline is used in the scene.
For example, in the AtomSampleViewer with samples derived from `CommonSampleComponentBase` there are two pipelines (`RPISamplePipeline` and `BRDFTexturePipeline`), and `OnRenderPipelineChanged` is called for both pipelines in this order, which later leads to the debug pass only being added to the latter one. `AddRenderPasses` is only called for `RPISamplePipeline`, and works as expected.
Open a small test scene and a scene with terrain and enable the debug ray tracing pass, check if it shows up as expected.
=> Remove OnRenderPipelineChanged override from RayTracingDebugFeatureProcessor

Gems/Atom/RHI/Vulkan/Code/Source/RHI/DescriptorSet.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/DescriptorSet.h
The SinglePlayer - Level in the [StarterGame-Assets](https://github.com/o3de/startergame-assets/tree/main) has about 8000 draw-items for each raster-pass (roughly 5000 objects, and most object have 2 LODs). With the passes of two material-pipelines active (MainPipeline and LowEndPipeline, total about 20 Passes), this results in about 160.000 unique Draw-SRGs alone, and with the pre-allocation of the small_vector optimization for the descriptor sets in Vulkan, the entire level needs about 66 GB of RAM, compared to the 6 GB of DX12.    
This PR reduces the RAM requirements to about 10 GB, which is still a lot, but at least manageable.
I've tested this with the Malloc Allocator, since the level is also quite unstable with the HPHA - allocator, 
Windows, using Vulkan
=> Reduce pre-allocated memory for vulkan descriptor sets

AutomatedTesting/Gem/PythonTests/editor/EditorScripts/BasicEditorWorkflows_LevelEntityComponentCRUD.py, Code/Framework/AzCore/Tests/AZStd/String.cpp, Gems/LyShine/Code/Source/TextMarkup.cpp, Gems/LyShine/Code/Source/UiTextComponent.cpp, Gems/MotionMatching/Code/Source/CsvSerializers.cpp
This cherry picks pull [18760](https://github.com/o3de/o3de/pull/18760)
from development (commit 8719dc3e6f40512b954f4baa99b0b0298b7331fc) into stabilization to fix the same issue found there.
* Fixes intermittent test failures
Some conversions from string to float, or float
to string for tests or for serialize/deserialize
were not being done in the invariant ("C") locale and would fail if on a machine that had comma set as the decimal separator.
* Add longer test timeout in case of flakiness
=> (Stabilization) Cherry-pick from dev - Fixes intermittent test failures

Code/Tools/SceneAPI/SceneBuilder/SceneImporter.cpp
When importing GLB/GLTF files, the root bone would be split into a child of the scene root disconnected from the rest of the skeleton, which results in the actor not being rendered. This PR makes sure the bone data remains in the root node.
Possibly fixes https://github.com/o3de/o3de/issues/10084
Import a GLB/GLTF skinned character into o3de.
=> Prevent Assimp importer from spliting its bone at scene root into a disconnected child when importing GLB/GLTF files.

Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.h, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoEntityOverrides.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoEntityOverrides.h
fixes issue:
https://github.com/o3de/o3de/issues/18794
The crash was caused by the current focused Instance being queued for reload (and then reloaded, which involves it being deleted and recreated) while the property system was still live editing it and still had messages in the queue for it, causing use-after-free.
The issue has more information on how to repro.
The fix here is to make sure that the instance being edited is in the list of instances NOT to respawn, since it is already updated by the inspector.
I Created a level that had the following structure which not only has prefabs, but prefabs-in-prefabs, and more than 1 of each.
Each of the entities have a "Debug Text" component on them, which provides a color picker and a text field to type in to try to repro the bug.
Did every …
=> (Stabilization) BUGFIX: Fixes a crash when editing overrides on a prefab instance.

Code/Framework/AzCore/AzCore/Math/MathUtils.h
This PR implements #14490. It introduces a template function, `SmoothCriticallyDamped()`, to `AzCore/Math/MathUtils.h`. It implements a critically damped ease-in/ease-out function for smoothly interpolating values toward a target over time.
https://github.com/user-attachments/assets/24fc7970-e98d-47a9-a482-6b79a70c2c74
O3DE currently offers linear interpolation via `AZ::Lerp()`, but lacks a built-in utility for critically damped smoothing.
The code is directly copied over from an older commit in the O3DE codebase, which should be covered under Apache 2.0 and MIT licenses:
https://github.com/o3de/o3de/blob/b4a2edec6a36381b85d3118608543e7535961d36/Code/Legacy/CryCommon/Cry_Math.h#L605-L662
See further discussion here: https://github.com/o3de/o3de/issues/14490#issuecomment-1472857858
On …
=> Add SmoothCriticallyDamped function to MathUtils.h

python/requirements.txt
https://github.com/o3de/o3de/security/dependabot/118
https://github.com/o3de/o3de/security/dependabot/109
https://github.com/o3de/o3de/security/dependabot/108
https://github.com/o3de/o3de/security/dependabot/107
https://github.com/o3de/o3de/security/dependabot/106
https://github.com/o3de/o3de/security/dependabot/102
https://github.com/o3de/o3de/security/dependabot/101
https://github.com/o3de/o3de/security/dependabot/100
=> Updated dependabot packages

AutomatedTesting/Gem/PythonCoverage/Code/Source/PythonCoverageEditorSystemComponent.cpp
If you try to compile with LY_DISABLE_TEST_MODULES=ON, the test coverage system (related to the Test Impact Analysis Framework) will not define any symbols, and the PythonCoverageEditorSystemComponent.cpp will
fail to compile due to a missing define.
Build and run the editor with `-DLY_DISABLE_TEST_MODULES=ON`
Without this fix, it cannot actually build (AutomatedTesting project).
=> (stabilization) Compile fix - Fixes pythontestcoverage compile error if tests are disabled

Gems/LmbrCentral/Code/Source/Builders/SliceBuilder/SliceBuilderComponent.cpp, Gems/LmbrCentral/Code/Source/Builders/SliceBuilder/SliceBuilderWorker.cpp
This fix is to make sure dynamicslices are unconditionally built and can be used by UiSpawner.
For historical reasons the IsDynamic field in slices can not be set to true and prevents the dynamicslice asset (required by UiSpawner component) from being built. This PR ought to fix it by forcing SliceBuilderWorker to ignore IsDynamic value and always build dynamicslices.
Draft, not tested yet.
=> Force SliceBuilderWorker to unconditionally produce dynamic slices.

Code/Framework/AzCore/AzCore/Script/ScriptPropertySerializer.cpp
Fixes a problem with Script Properties serialization that Address Sanitizer (ASAN) found live.
Its unclear what problems this cause, since its going to be reading from uninitialized memory.  Problems range from mystery crashes to debug checks and so on.  In profile, it probably blows on through.
See the comment in code for the case example and justification.
Without this change, the JSON serializer would continue down the serialization stack, not knowing that the actual types of the "default" and the "value" ptrs differ and eventually it would static cast the "default" ptr given into the same typeid as the "value" ptr and then compare them.  For example, it would assume that since a the ScriptAssetRef (containing an assetId) was the type of the value, it could convert the "default" to a …
=> Fixes a buffer overrun ASan error in LUA Script Properties

Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Overrides/PrefabOverrideHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ComponentEditor.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ComponentEditor.hxx, Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/Utils.cpp, Gems/PhysX/Core/Code/Source/EditorMeshColliderComponent.cpp
During investigation of the Physics Material Slots issue, I was running in Debug with Address Sanitizer Enabled.
These changes fix a few of the errors that were found alongside CRT or Qt or AZ Asserts.
1. Wrong index used in AssetrBrowserTableView.  The table View has 2 different filter models depending on whether the user is searching for something via the text search field or not. When it is using the text search field it has to use a slightly different approach to reading the data or it will be pulling it from the wrong model.
2. AssetBrowserThumbnailView updated to match 1) above.
3. PrefabOverrideHandler.cpp - The Prefab Override Handler needs to refresh the entire property grid when overrides are reverted.  Refreshing only attributes and values does not work since reverting …
=> (stabilization) Fix a few ASan and other corruption errors found.

Code/LauncherUnified/launcher_generator.cmake
This PR changes behavior when triggering Assets build via cmake.
Currently, when running 
```bash
cmake --build ${build_path} --target ${project_name}.Assets
```
AssetProcessorBatch is triggered in the backgroud, all logs are gathered and only when the process exits, all logs are dumped at once. This behavior makes it really hard to monitor Asset build process.
This PR changes this behavior to make all stdout from run command to be available in the parent stdout as soon as it is published.
- [add_custom_command](https://cmake.org/cmake/help/v3.10/command/add_custom_command.html)
- [console job pool](https://cmake.org/cmake/help/v3.10/prop_gbl/JOB_POOLS.html#prop_gbl:JOB_POOLS)
Tested with Ninja Multi-Config generator
Build was split to 2 phases:
1. Build AssetProcessorBatch
```bash
cmake …
```
=> Do not buffer cmake Assets build logs

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/SettingsRegistrar.cpp
Fixes a potential stack buffer overflow error, detected by Address Sanitizer.
This one happens every time you change the view in the Property Editor and it tries to save the expansion state
of properties.
The use-after free occurs because the AZ::IO::FixedMaxPath function ".AsPosix()" returns a temporary object.
This temporary object was being cached in a char* pointer, and then used after the original call site of AsPosix() resolved.
This is an Address Sanitizer (ASan) Detection.  It detects it 100% of the time when clicking around in the property editor.  The detection goes away when the bug is fixed.
=> (Stabilization)Fixes an additional ASan detection in settings registry.

Gems/Atom/RHI/Code/Include/Atom/RHI/ShaderResourceGroupData.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Shader/ShaderResourceGroup.h
This PR fixes #18494: it allows basic SRG constants to have different values on different GPUs, which is needed when bindless indices are stored in constants, since the bindless indices for the same resource can be different across multiple GPUs.  
Windows, vulkan & dx12
=> support srg constants with different values on different GPUs

Gems/Atom/RPI/Code/Source/RPI.Public/DllMain.cpp
This PR fixes a compile error in `Atom/RPI.Public/DllMain.cpp` when building the engine with a monolithic-nounity configuration (see #18813).
The EBus instantiation calls need to be outside of the `#if !defined(AZ_MONOLITHIC_BUILD)` region, since they are not related to monolithic/non-monolithic mode, but rather just need to exist in one of the cpp files built by the Gem::Atom_RPI.Public target.
Compile the GameLauncher with a monolithic+nounity configuraiton.
=> (Stabilization) Fix compile error when building with a monolithic-nounity-configuration

AutomatedTesting/Gem/PythonCoverage/Code/Source/PythonCoverageEditorSystemComponent.cpp, Code/Framework/AzCore/AzCore/Script/ScriptPropertySerializer.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/SettingsRegistrar.cpp, Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpConnection.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabComponentAdapter.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Overrides/PrefabOverrideHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.h, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoEntityOverrides.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoEntityOverrides.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ComponentEditor.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ComponentEditor.hxx, Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/Utils.cpp, Gems/PhysX/Core/Code/Source/EditorMeshColliderComponent.cpp, Gems/ScriptCanvas/Code/CMakeLists.txt
Normally I'd individually cherrypick these but it turns out that there is nothing currently in stabilization yet (such as version changes or "do not merge" commits) so I can just merge the whole branch.
Merges the following pull requests:
* Fixes an additional ASan detection in settings registry. ([#18822](https://github.com/o3de/o3de/pull/18822))
* Fix a few ASan and other corruption errors found. ([#18819](https://github.com/o3de/o3de/pull/18819))
* Fixes a buffer overrun ASan error in LUA Script Properties ([#18807](https://github.com/o3de/o3de/pull/18807))
* Fixes compilation if test modules are disabled. ([#18786](https://github.com/o3de/o3de/pull/18786))
* Fixes containers (vectors, maps, etc) not saving state or undos when modified in the inspector …
=> Merge from stabilization 25050 to development branch

Gems/PhysX/Core/Code/Source/ArticulationLinkComponent.cpp
This PR added PX locks to articulation setters and getter, as suggested https://github.com/o3de/o3de/issues/18506
Debug build of ROS2ManipuilationTemplate with debugger attached.
=> Added PhysX locking to ArticulationLink component.

Gems/PhysX/Core/Code/Source/ArticulationLinkComponent.cpp, Gems/PhysX/Core/Code/Source/ArticulationLinkComponent.h
It implements missing API calls from Simulation Body API to ArticulationComponent. 
It allows to move root of articulation during simulation
It is also contains some write / read locks.
Against 25.05  with Simulation Entities PR in o3de-extras
https://github.com/user-attachments/assets/3fa418f6-50ae-477f-a734-327b65ea6181
=> Allow to modify position of root link of PhysX articulation

Code/Framework/AzFramework/AzFramework/Asset/GenericAssetHandler.h
GenericAssetHandler typically store assets in XML format. This PR allows GenericAssetHandler to load/save assets in a different ObjectStream format such as json/binary.
This can be applied all assets using GenericAssetHandler (editable in AssetEditor).
Pass a different streamType argument to GenericAssetHandler constructor.
=> Allow GenericAssetHandler to load/save objects in custom ObjectStream format.

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
Removed a variable that is never used.
Tested on Windows with Clang 19
=> Remove an unreferenced variable (clang build fix)

Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpSocket.cpp, Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpSocket.h, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindow.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Utils/ScriptCanvasConstants.h
A couple fixes related to Remote Tools system.
Fixes https://github.com/o3de/o3de/issues/18812
Does not fix, but improves https://github.com/o3de/o3de/issues/17643
1. Change the remote tools port to be something that's far less likely to be camped on by another service.
2. Makes it so that the Remote Tools system only reports once per port that it cannot bind.
3. Restores the "LIVE" tab in SC (which uses Remote Tools)
The third point above was caused by a previous PR, https://github.com/o3de/o3de/pull/18734
After that PR was submitted, I went back with ASan and fixed several SC issues to resolve crashes, and that line that calls SetParent is no longer necessary.
The Live tab disappeared because it was reparented as a child of the docking window, which removes it from the tab view, which …
=> Fix Remote Tools Spam and restore SC live window

Gems/Atom/RHI/Code/Source/RHI/RayTracingAccelerationStructure.cpp
Currently the `DeviceRayTracingTlas` of the multi device `RayTracingTlas` are recreated every time the `CreateBuffers` function is called. This leads to some problems as the acceleration structure buffers of the Tlas are in a `FrameCountMaxRingBuffer` to ensure they are valid until the current frame was actually rendered.
This manifested as validation errors like this in Vulkan:
```
[Error] (vkDebugMessage) - [ERROR][Validation] Validation Error: [ VUID-vkDestroyAccelerationStructureKHR-accelerationStructure-02442 ] Object 0: handle = 0x20dc0d80070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xaf03fd73 | Cannot call vkDestroyAccelerationStructureKHR on VkAccelerationStructureKHR 0xf353c500000dbf4f[] that is currently in use by a command buffer. The Vulkan spec states: All submitted …
```
=> Don't recreate device TLAS every frame

Gems/AtomLyIntegration/CommonFeatures/Code/Source/Debug/RayTracingDebugComponentController.cpp, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Debug/RayTracingDebugComponentController.h, Gems/AtomLyIntegration/CommonFeatures/Code/Source/Debug/RayTracingDebugEditorComponent.cpp
This PR fixes a crash when adding the "Debug Ray Tracing" component to a level on a device which does not have RTX support or opening a level which contains this component on such a device (#18841).
Since I do not have access to a non-RTX GPU or non-RTX iGPU, I commented out the ray-tracing related extensions in RHI/Vulkan, which yielded the same error message and crash as in the linked issue, and with the changes for this PR the crash was resolved.
The "Debug Ray Tracing" component now also shows whether ray tracing is supported on the current device or not (left: RTX not supported, right: RTX supported):
=> Fix crash when using "Debug Ray Tracing" component on non-RTX GPU

Code/Framework/AzCore/CMakeLists.txt, Code/Framework/AzManipulatorTestFramework/CMakeLists.txt, Code/Framework/AzToolsFramework/CMakeLists.txt
This PR enables several targets to be available to projects / gems that use prebuilt SDK.
Those targets are
- AzCoreTestCommon
- AzTestShared
- AzCoreTestDLL
- AzManipulatorTestFramework.Static
- AzToolsFrameworkTestCommon
Without this change, some outside gems that are built with the project fail on configure step because some targets are not available if engine was built with `-DLY_DISABLE_TEST_MODULES=ON`
It changes usage of `PAL_TRAIT_BUILD_TESTS_SUPPORTED` to `PAL_TRAIT_TEST_GOOGLE_TEST_SUPPORTED` for targets that aren't tests themselves.
Affected targets `*.Tests` are available only if `(PAL_TRAIT_TEST_GOOGLE_TEST_SUPPORTED AND PAL_TRAIT_BUILD_TESTS_SUPPORTED)` 
1. Built SDK engine after change.
2. Use engine with `MinimalProject` project and `ROS2` gem enabled
3. Build tests from …
=> Enable common test utility targets for sdk

Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
When refreshing the gem catalog in the project manager, the Gem model needs to be cleared up, otherwise duplicate entries are added which can lead to incompatibilities with gems that are no longer valid. As in the case of changing the version of a gem and refreshing the catalog.
Fixes #18796
=> Project Manager: Clear the gem model on refresh to avoid duplicates

Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp
fixes https://github.com/o3de/o3de/issues/18871
possibly others, if they have undo redo issues.
basically, any time you made a continuous edit, the two different property editor systems would fight each other.
Normal one-off edits were fine (checkbox, button, delete button, etc) But any continous edits (slider, color, transform) were broken.
example of the fighting, drag the color around in a color control
```ComponentAdapter
PropertyColorCtrl::valueChanged => PropertyEditorGUIMessages::RequestWrite,
PropertyManagerComponent::RequestWrite
m_currentUndoBatch = BeginUndoBatch ("Modify Property")
BeginUndoBatch: empty stack, so it creates one and returns it
PropertyManagerComponent::RequestWrite (singleton) continues
emits IndividualPropertyHandlerEditNotifications::Bus::Events::OnValueChange …
```
=> Fixes issues with undo and redo and continuous edits

Gems/RecastNavigation/Code/CMakeLists.txt, Gems/RecastNavigation/Code/recast-o3de.patch, cmake/PatchIfNotAlreadyPatched.cmake
fixes issue https://github.com/o3de/o3de/issues/18878
CMake 4.xx will issue a fatal error if it encounters a cmake file that requests a cmake version under 3.5.
cmake.org now has 4.xx as the recommended latest stable release, and `winget install cmake` will install 4.x
Recast navigation asks for cmake version 3.0 (~10 years ago) even though it compiles just fine with cmake 4.x and 3.22.
This change updates the code in the following ways
1. cherry-pick the cmake utility to patch a file if its not already patched from development (this utility is not used unless you invoke it so it will not affect any other pipelines)
2. Change the recast cmake script to apply a patch to it which changes the minimum version of cmake it asks for from 3.0 to 3.22
CMake configure
Build and run in profile with …
=> Allows O3DE to compile with cmake v4.xx

Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpSocket.cpp, Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpSocket.h, Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/DllMain.cpp, Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindow.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Utils/ScriptCanvasConstants.h
Merge additional fixes from stabilization into development
The following fixes are included
* Fixes issues with undo and redo and continuous edits ([#18872](https://github.com/o3de/o3de/pull/18872))
* Fixes spam when a TCP socket fails to bind in Remote tools. ([#18838](https://github.com/o3de/o3de/pull/18838))
* Fix SceneNotification/ShaderReloadNotificationBus instantiation compile error when building a monolithic-nounity-configuration ([#18825](https://github.com/o3de/o3de/pull/18825))
The following commits originally came from development and, while included
for the purposes of history tracking, did not affect any lines in development
when merged:
* Update slot names if the referenced variable is renamed ([#18852](https://github.com/o3de/o3de/pull/18852))
* ScriptCanvas: Fix default …
=> Merge stabilization 25.05.0 into development

Gems/Atom/Feature/Common/Code/Source/CoreLights/ShadowmapPass.cpp, Gems/Atom/Feature/Common/Code/Source/CoreLights/ShadowmapPass.h, Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/RenderAttachmentLayout.h, Gems/Atom/RHI/Code/Source/RHI.Reflect/RenderAttachmentLayout.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
This fix adds the function `IsEqual(..., const bool compareLoadStoreAction)` to the `RenderAttachmentConfiguration` and some other classes, and uses it during `Scene::RebuildPipelineStatesLookup()` to avoid duplicating the PipelineState caused only by the `LoadStoreAction`.
This works because the actual `LoadStoreAction` used by the GPU is controlled by the FrameGraph and taken from the Scope (i.e. the Pass), and not from the draw-item.   
Concretely this fixes issue [18727](https://github.com/o3de/o3de/issues/18727), where the `ShadowMap` - passes use the same drawlist tag, but can have different clearing actions depending on a shadow-cache setting.
Previously this resulted in multiple Pipeline - States in the PipelineStatesLookup in the Scene, and an error message (and a fallback to the …
=> Don't check the LoadStoreAction for the pipelineStatesLookup

Gems/LyShine/Code/Editor/EditorWindow.cpp, Gems/LyShine/Code/Editor/LyShineEditorSystemComponent.cpp
LyShine has implemented property handlers for some of asset types it uses such as sprites, however, the handlers only gets registered when UI editor window starts. This PR moves their registration to LyShineEditorSystemComponent::Activate() so that other editors such as Asset Editor can use the handlers.
Define a custom generic asset type that has a member as AzFramework::SimpleAssetReference<LmbrCentral::TextureAsset> and set its DataElement as "Sprite". Create and edit such asset in AssetEditor.
=> Move the registration of property handlers to LyShineEditorSystemComponent so that they can be handled by Asset Editor.

Code/Tools/SceneAPI/SDKWrapper/AssImpSceneWrapper.cpp, Code/Tools/SceneAPI/SDKWrapper/AssImpSceneWrapper.h, Code/Tools/SceneAPI/SceneBuilder/Importers/AssImpMaterialImporter.cpp, Code/Tools/SceneAPI/SceneBuilder/Importers/AssImpMaterialImporter.h, Code/Tools/SceneAPI/SceneCore/Import/SceneImportSettings.cpp, Code/Tools/SceneAPI/SceneCore/Import/SceneImportSettings.h
FBX and GLTF files can have texture files embedded. This PR adds a option to allow assimp importer to extract such textures into the model directory.
Should solve https://github.com/o3de/o3de/issues/2430
WIP
=> Add an option for assimp importer to extract embedded textures from model files.

Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
Disables RTAS compaction for models with too many submeshes.
Previously models with too many submeshes broke the raytracing scene as creating BLAS was halted (see [this line](https://github.com/o3de/o3de/blob/e0a467f21d779e982bb9833a4cafdef24b8fa86a/Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp#L960) in `RayTracingFeatureProcessor.cpp`), leading to missing models.
This PR removes the `ENABLE_COMPACTION` compaction flag from all submeshes of these models and prints a warning.
Tested on Windows with DX12 and Vulkan and a model with more than 344 submeshes
=> Disable RTAS compaction for models with too many submeshes

Gems/Atom/Feature/Common/Code/Include/Atom/Feature/RayTracing/RayTracingFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Source/MorphTargets/MorphTargetComputePass.cpp, Gems/Atom/Feature/Common/Code/Source/MorphTargets/MorphTargetComputePass.h, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.cpp, Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshComputePass.cpp, Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshComputePass.h, Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshFeatureProcessor.h, Gems/Atom/RHI/Code/Source/RHI/DeviceShaderResourceGroupData.cpp
The RaytracingAccelerationStructurePass was previously duplicated for every device that supports raytracing.  This PR reverts that behavior. Multi Device render pipelines are now responsible for duplicating the pass for every device where raytracing is needed.
RTAS are now only allocated on devices where an RTAS pass exists.
Additionally this PR adds support for duplicating the MorphTarget and Skinning passes. Previously the engine assumed that only one instance of these passes with a specific name exists in the pipeline. 
Tested on Windows with the MainRenderPipeline and a multi device render pipeline that need RTAS on multiple devices.
=> RaytracingAccelerationStructurePass: MultiDevice Refactor

Gems/Atom/RPI/Code/Source/RPI.Public/DynamicDraw/DynamicDrawContext.cpp
Cherrypicks the following commit from dev:
Author: antonmic <56370189+antonmic@users.noreply.github.com>
Date:   Thu May 8 04:29:00 2025 -0700
Fixing DrawLinear issue in DynamicDrawContext caused by GeometryView changes (#18899)
from https://github.com/o3de/o3de/pull/18899
Fixes various UICanvas / LyShine rendering issues, like the mouse cursor and others.
Fixes https://github.com/o3de/o3de/issues/18769
Fixes https://github.com/o3de/o3de/issues/18890
Fixes https://github.com/o3de/o3de/issues/18898
=> Cherrypick from dev: Fixing DrawLinear issue in DynamicDrawContext caused by GeometryView

Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorTab.cpp
This is a follow-up of https://github.com/o3de/o3de/pull/18823 , which allows GenericAssetHandler to save objects in a custom ObjectStream format. This PR allows Asset Editor to use AZ::Data::AssetHandler::SaveAssetData to save the asset in-place so that it will be saved in the custom ObjectStream format.
Load a asset from the Asset Editor, modify it and use Ctrl-S to save the asset in-place.
=> Use AZ::Data::AssetHandler::SaveAssetData to serialize in memory asset in AssetEditorTab::GenerateSaveDataSnapshot().

Templates/ScriptOnlyProject/Template/.command_settings, Templates/ScriptOnlyProject/template.json
This Pull Request adds a `.command_settings` file to `ScriptOnlyProject` template, this fix #18887.
> [!NOTE]
> This commit adds `.commands_settings` file, which by default is ignored:
https://github.com/o3de/o3de/blob/7e655e3c908c183fccbc5bdc22a0f2a12c15789c/.gitignore#L25
I created a new Script-Only project, built it and opened it. After asset processing completion, I closed the editor, opened the export settings, but made no changes, then used the export option to linux on project manager.
The project got exported as expected.
Tested on same environment of the issue (Fedora Linux 40, PC).
=> add .command_settings file to ScriptOnlyProject template, fix #18887

Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/Ltc.azsli
This PR adds a clamp to the output in the cosine integration of the edge in a hemisphere.
Given `v1` and `v2` are normalized and both have positive `z` (above XY), I understand that:
- `cross(v1, v2).z` will be the signed area element; positive or negative depending on winding: `[-1, 1]`.
- `theta_sinTheta` roughly scales with the angle between the vectors, maxing around π: `[0, π]`
Hence, the total output should scale to `[-π, π]`
In some cases, depending on the models, this result might be out of this range, causing rendering issues as in #18683
Two additional typos and one obsolete initialization were fixed in this PR. 
Fixes #18683
Issue #18683 was reproduced; the change fixed it. The modified code was also used with different levels/projects and no other issues were registered.
=> Clamp output in cosine integration of edge in a hemisphere

Gems/Atom/RPI/Code/Source/RPI.Public/View.cpp
Related to this PR [#18467](https://github.com/o3de/o3de/pull/18467).
The results saved in `m_XXXWithOffset` through the `m_clipSpaceOffset` non-zero branch should be set to `m_shaderResourceGroup` correctly, which would ensure the correctness of viewsrgs when `m_clipSpaceOffset`'s set by `TaaPass`.
Start Editor in TAA mode and see if anti-aliasing result is correct
=> Set correct jittered matrix to view srg. (fixes #18467)

Code/Editor/TrackView/AssetBlendKeyUIControls.cpp, Code/Editor/TrackView/KeyUIControls.h, Code/Editor/TrackView/TrackViewDopeSheetBase.cpp, Code/Legacy/CryCommon/Maestro/Types/AssetBlendKey.h, Code/Legacy/CryCommon/Maestro/Types/AssetBlends.h, Gems/EMotionFX/Code/EMotionFX/Source/MotionInstance.cpp, Gems/EMotionFX/Code/EMotionFX/Source/MotionLayerSystem.cpp, Gems/EMotionFX/Code/EMotionFX/Source/MotionSystem.cpp, Gems/EMotionFX/Code/EMotionFX/Source/MotionSystem.h, Gems/EMotionFX/Code/Source/Integration/Components/SimpleMotionComponent.cpp, Gems/EMotionFX/Code/Source/Integration/Components/SimpleMotionComponent.h, Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorSimpleMotionComponent.cpp, Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.cpp, Gems/Maestro/Code/Source/Cinematics/AssetBlendTrack.cpp
Closes GHI https://github.com/o3de/o3de/issues/8485
Closes GHI https://github.com/o3de/o3de/issues/9138
This PR just revives the functionality pre-designed by existing code: play simple motions setup by `CAssetBlendTrack` keys, while the responsibility to blend motions is left to existing `MotionSystem` of `EMotionFX` GEM.
Motions are being played in game mode in case the original `SimpleMotionComponernt` of an actor, added to sequence, has "Play on active" flag set.
As per initial design, motions are not fully controlled by the sequence time, as virtual properties provided by the `SimpleMotionComponernt` and the `MotionInstance`->`MotionSystem`->`Motion` pipeline would need wide refactoring to achieve such control.
Actually, the whole system of `MotionInstance`s in `EMotionFX` GEM IMO …
=> [Track View] Fix issues 8485 and 9138: SimpleMotionComponent playing motions setup by CAssetBlendTrack keys.

scripts/o3de/o3de/engine_template.py
This also restricts templates and gems.  It works with the script as well as the O3DE.EXE gui.
Fixes issue #18836 
Testing:
Attempting to create invalid template, project, gems.
=> Prevents creation of invalid project/gem/template names

Gems/LyShine/Assets/LyShine/Shaders/LyShineUI.azsl
This PR closes https://github.com/o3de/o3de/issues/18904 by marking texture index as non-uniform.
Tested on Windows 11 dx12 backend with AMD GPU. Artifacts have disappeared with this PR:
=> Fix artifacts in Lyshine UI image by marking texture index as non-uniform.

Gems/Terrain/Assets/Shaders/Terrain/TerrainDetailHelpers.azsli
Closes: https://github.com/o3de/o3de/issues/18924
When using AMD GPUs, one need to explicitly mark or signal when you're accessing non-uniform texture indices. This PR does this to eliminate artifacts seen on the terrain.
Tested on Windows 11 dx12 with AMD GPU:
=> Fix terrain artifacts by marking texture index as non-uniform.

Gems/Camera/Code/Source/CameraComponent.cpp
I noticed that the CameraNotificationBus wasn't dispatching the "OnActiveViewChanged" event correctly to ScriptCanvas, and I tracked it down to a simple typo.
Tested on the 2409.2 tag on Bazzite Linux (Fedora 41)
=> Fix OnActiveViewChanged event in scripts

Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp
This PR fixes that `RayTracingAccelerationStructurePass` is not inserting a TimestampQuery or PipelineStatisticsQuery if animated meshes are present in a scene (and no static meshes are currently moving). This omission lead to the RayTracingAccelerationStructurePass always showing up as 0ms in the "TimestampView", even though BLAS update/BLAS build and TLAS build commands are issued each frame for the animated meshes.
Create a small test scene with a "Actor" and "Simple Motion" component, and load an animated test model, then open the GpuProfiler/TimestampView debug window and look at the pass times. Without this PR, the time of the RayTracingAccelerationStructurePass is only >0 for a very short time if the whole model is being moved by the transform component, and with this PR the time …
=> Fix RayTracingAccelerationStructurePass not reading scope query resut when only animated meshes are updated

Code/Editor/splashscreen_background.png
This updates the O3DE editor splash screen for the 25.05 release with this image:
=> Update O3DE Splash Screen background for 25.05

Gems/Atom/Feature/Common/Code/Include/Atom/Feature/LightingChannel/LightingChannelConfiguration.h, Gems/Atom/Feature/Common/Code/Source/LightingChannel/LightingChannelConfiguration.cpp
1. Before SetLightingChannelMask and GetLightingChannelMask worked incorrect. Problem was in bit operations.
2. Changed default light flags set. In preview version was set only one (first) light layer. I think default set must have all accessible light layer. Because if you create game, you have many assets, and in practice most of them use all layers and only a small amount using custom light layer sets.
https://github.com/o3de/o3de/issues/18949
Check in game and all looks good.
=> Fix LightingChannelFlags in LightingChannelConfiguration

Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceSwapChain.h, Gems/Atom/RHI/Code/Source/RHI/DeviceSwapChain.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/Instance.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.h
This adds the needed Vulkan extension for `VK_COLOR_SPACE_HDR10_ST2084_EXT` and hardens the checks to use `SetHDRMetaData`. 
Previously, it was possible to not be in an HDR colorspace but have the `A2R10G10B10` VK format which would cause problems when calling into `SetHDRMetaData`.
Linux Fedora 42, tested with `PAL_TRAIT_LINUX_WINDOW_MANAGER` set to xcb and wayland.
=> Vulkan: Fix HDR crash

Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/MeshDrawPacket.h, Gems/Atom/RPI/Code/Source/RPI.Public/MeshDrawPacket.cpp
GetDrawSrg() now returns a const reference and the function itself is const.
This update prevents the possibility of modifying
the content of the MeshDrawPacket::m_perDrawSrgs array.
The inspiration for this update occurred because
inadvertently I was getting crashes when using the non-const references in a way that was modifying the array of DrawSrgs.
Tested on Win11 and Android (Quest3).
=> Improved the Mesh FP GetDrawSrg API.

Code/Editor/AssetEditor/AssetEditorWindow.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorTab.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorWidget.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorWidget.h
* Moved the Asset Editor settings to use the Settings Registry rather than AZ::UserSettings
* Ensure that the AssetEditor defaults to a folder in the project path
* Fixed the logic to store the last used path per asset type
=> Improved AssetEditor recent files and last used folders

cmake/LYWrappers.cmake
Remove the dependency from an `TARGET`  `add_custom_command`. `add_custom_command` can either be a `TARGET` command or it can have dependencies, but not both. According to the comment above the if explains why this should be a `POST_BUILD` command so I removed the dependency.
I'm getting many warnings like the following when using CMake >= 3.31:
```
CMake Warning (dev) at cmake/LYWrappers.cmake:383 (add_custom_command):
The following keywords are not supported when using
add_custom_command(TARGET): DEPENDS.
Policy CMP0175 is not set: add_custom_command() rejects invalid arguments.
Run "cmake --help-policy CMP0175" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
Call Stack (most recent call first): …
```
=> Fix a CMake warning in add_custom_command

Gems/PhysX/Core/Code/Source/PhysXCharacters/API/CharacterController.cpp, Gems/PhysX/Core/Code/Source/PhysXCharacters/Components/CharacterControllerComponent.cpp
In CharacterController.cpp and in CharacterControllerComponent.cpp was not implemented SetUpDirection. 
https://github.com/o3de/o3de/issues/14081
We use this in our Game Reverb many times and all looks good,
=> CharacterController_FixUpDirection

Code/Tools/AssetProcessor/native/resourcecompiler/rccontroller.cpp, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp, Gems/AtomLyIntegration/AtomFont/Code/Source/AtomFont.cpp
Fixes the showstopper crash on startup problem we encountered with the 2505 prerelease.
2 phases of testing, windows only currently but the code isn't platform specific.
First phase of testing, I used a synthetic Asset Processor (I modified asset processor) to only compile until it had finished compiling critical assets and then slow down immensely so that the editor would load without any non-critical assets, which made the problems 100% reproducable, since they are timining related.
Then I fixed the issues, was easy to test since they were now 100% repro.
Then for the second phase of testing I reverted everything except for the actual fixes, so it was using a vanilla asset processor, and tested it using vanilla everything just the fixes. (No issue anymore).
Then for the second phase I …
=> Fix crash on startup issue for 25050

Gems/Atom/Feature/Common/Code/Source/CubeMapCapture/CubeMapRenderer.cpp
The crash was introduced by this #17974 almost a year ago.
Fixed it by reverting it to its previous version:
```
m_previousGlobalIblExposure = sceneSrg->GetConstant<float>(m_globalIblExposureConstantIndex);
m_previousSkyBoxExposure = sceneSrg->GetConstant<float>(m_skyBoxExposureConstantIndex);
```
Was able to capture both Specular and Diffuse Cubemaps on Win11 with Vulkan
=> Fixed crash when doing Cubemap Captures.

Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineState.cpp
Memory fix provided by carbonated. 
Tested AutomatedTesting default level on ios as well as mac via M1 machine
=> Fix memory leak related to vertex/pixel/compute shader functions for Metal

Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabSaveLoadHandler.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/AbstractCodeModel.cpp, Templates/ScriptCanvasNode/Template/${Name}_files.cmake, Templates/ScriptCanvasNode/Template/CMakeLists.txt, Templates/ScriptCanvasNode/Template/Source/${Name}.cpp
* Update the **ScriptCanvasNode Template** by updating it to confirm to impactful change for [Script Canvas](https://github.com/o3de/o3de/pull/16678).
* Fix unused variable warning
Fixes #18923 
* Create a new C++ Gem
* Followed the [instructions](https://github.com/o3de/o3de/blob/development/Templates/ScriptCanvasNode/Template/README.md)  to create ScriptCanvasNode in the new gem 
* Create a new minimal project and included the new gem
* Built the project
=> Fix ScriptCanvasNode Template 

Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Editor/GraphModelBus.h, Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/ContextMenuActions/BreakpointMenuActions/BreakpointActionsMenuGroup.cpp, Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/ContextMenuActions/BreakpointMenuActions/BreakpointActionsMenuGroup.h, Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/ContextMenuActions/BreakpointMenuActions/BreakpointContextMenuAction.h, Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/ContextMenuActions/BreakpointMenuActions/BreakpointContextMenuActions.cpp, Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/ContextMenuActions/BreakpointMenuActions/BreakpointContextMenuActions.h, Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/ContextMenus/NodeContextMenu.cpp, Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/ContextMenus/NodeContextMenu.h, Gems/GraphCanvas/Code/graphcanvas_staticlib_files.cmake, Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp, Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorGraph.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/ExecutionNotificationsBus.h, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Debugger.cpp, Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Debugger.h
Work on https://github.com/o3de/o3de/issues/9192. Last **pre-RFC work** for the full script canvas debugging pipeline (will release a document in a few days, and this PR helps to understand the core of said pipeline).
Upon right click on a node, display the option **"Add breakpoint"** which will register a breakpoint in the client debugger for this node (it is registered for all the runtime instances of this graph). 
Said option is **left always disabled** as we currently don't have a generic way to properly pause the logic without freezing the editor, this means that I will have to **extract scriptcanvas editor in a separate executable** via another PR once the RFC is approved.
Took the opportunity to apply clang-format on a few files which will be impacted by the RFC.
**Note:**
- You …
=> ScriptCanvas breakpoint support : Allow to add breakpoint on node and stop execution when breakpoint is hit (disabled behind code)

Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabSaveLoadHandler.cpp
Closes #2376
I found a very old issue with a recent comment and decided to investigate it. Steps to reproduce:
- create a level with a prefab
- delete this prefab from the drive (using the operating system tools)
- try to save a new prefab under the same name
When a prefab is deleted from the disk, AssetProcessor discovers it and sends a notification. However, O3DE keeps the prefab in memory because it is still loaded in the level (user is notified that the file was removed and has a chance to save it back from O3DE). Because the prefab is kept in memory, a new prefab under the same name cannot be created in memory. This triggers a crash later, when saving the prefab from memory to the output file (it is missing in memory due to the name collision).
A proper fix for the issue would be to …
=> Fix #2376: check templateId collision when saving prefab

Gems/Atom/Feature/Common/Code/Source/AuxGeom/AuxGeomBase.h, Gems/Atom/Feature/Common/Code/Source/AuxGeom/DynamicPrimitiveProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/AuxGeom/DynamicPrimitiveProcessor.h, Gems/Atom/Feature/Common/Code/Source/AuxGeom/FixedShapeProcessor.h, Gems/Atom/Feature/Common/Code/Source/ImGui/ImGuiPass.cpp, Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbe.h, Gems/Atom/Feature/Common/Code/Source/Shadows/ProjectedShadowFeatureProcessor.h, Gems/Atom/RHI/Code/Include/Atom/RHI/GeometryView.h, Gems/Atom/RHI/Code/Tests/MultiDeviceDrawPacketTests.cpp, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/FullscreenTrianglePass.h, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Specific/ImageAttachmentPreviewPass.h, Gems/Atom/RPI/Code/Source/RPI.Public/DynamicDraw/DynamicDrawContext.cpp, Gems/Atom/RPI/Code/Source/RPI.Public/Model/ModelLod.cpp, Gems/AtomTressFX/Code/Rendering/HairRenderObject.h, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGrid.h, Gems/Stars/Code/Source/StarsFeatureProcessor.h, Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp, Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.h
Adds a deviceMask to the constructor of `GeometryView` to fix a race condition:
The `MeshDrawPacket::DoUpdate` function sets the multi-device `GeometryView` in the `DrawPacketBuilder`, which in turn sets the `DeviceGeometryView` in the respective device objects. Before this PR the `DeviceGeometryViews` where created on demand. I.e. in the `SetGeometryView` function of the `DrawPacketBuilder`.
The `MeshDrawPacket::DoUpdate` function is called in parallel during the `Simulate` function in the `MeshFeatureProcessor`. If two draw packages use the same mesh, the `GetDeviceGeometryView` of the `GeometryView` might be called at the same time from different threads, leading to a race condition.
This PR fixes this problem by creating the `DeviceGeometryViews` in the constructor, instead of …
=> Fix a race condition in GeometryView

Code/Tools/LuaIDE/Source/LUA/LUAEditorGoToLineDialog.cpp, Code/Tools/LuaIDE/Source/LUA/LUAEditorGoToLineDialog.hxx, Code/Tools/LuaIDE/Source/LUA/LUAEditorGoToLineDialog.ui, Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.cpp
Fixed 18854 : https://github.com/o3de/o3de/issues/18854
One another issue is that the current implementation expects line numbers start at 1 and columns at 0. I did not change that behavior. Better would be, at some point to change the column also to start at the value 1 instead of 0.
Just tested on my local computer.
=> [LUA Editor] Fix autofocus issue for the goto line dialog and support also columns

Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.cpp, Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.h, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabOverrideLabelHandler.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabOverrideLabelHandler.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/PropertyHandlerWidget.h, Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/ValueStringFilter.cpp
Fix https://github.com/o3de/o3de/issues/19013
When doing a search in DPE-powered property trees, the matching text on labels should have a background color to outline that it matches the search.
Local build against development branch
=> DPE : Fix search linting on widgets

Code/Tools/SceneAPI/SceneBuilder/SceneSystem.cpp
This PR fixed a mistake in #18829, that causes assimp importer to revert to old transform paradigm when importing FBX mesh files, which results in the orientation of FBX mesh different from Blender (which uses the same coordinate system as O3DE).
Export FBX mesh from Blender to O3DE, the orientation should remain the same in all combinations of front and up axis in the export option.
=> Fix a mistake introduced in #18829 that results in assimp importing FBX meshes through old transform behavior.

Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTableViewProxyModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserThumbnailViewProxyModel.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserViewUtils.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserViewUtils.h
* Fixes https://github.com/o3de/o3de/issues/17610
- Dragging an asset into the same folder it already exists in no longer causes any action to happen.
- This works between the same view, but also different Views such as the Asset Thumbnail view and tree view.
* Fixes https://github.com/o3de/o3de/issues/18010
- The dead zone for beginning a drag is now the same as the dead zone for any other drag operation in the application.
Just manual tests
* Dragging an asset from somewhere to the to the same place
* Dragging an asset from somewhere onto a different place
* a different folder in the same view
* a different folder in the tree view on the left
* the same folder in the tree view on the left.
The above were tested on several different assets, dragging from the list view and icon and tree …
=> Fix some issues with drag interactivity in the Asset AssetBrowser

Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
I was working on the "StarterGame" project and upon switching the LOD type in the mesh component from SpecificLOD to default it crashed in the DPE code. This adds a basic early return to prevent dereferencing `currentColumnLayout`. Callstack can be seen below
[error.log](https://github.com/user-attachments/files/20813512/error.log)
=> DPE : Prevent currentColumnLayout nullptr to be deref

Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/EditorBaseComponentMode.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/UI/LegacyFramework/Core/EditorFrameworkApplication.cpp, Code/Tools/AssetProcessor/native/utilities/ApplicationManager.cpp, Gems/Atom/RHI/Code/Include/Atom/RHI/GeometryView.h, Gems/Atom/RPI/Code/Source/RPI.Public/Model/ModelLod.cpp
This PR marks the `AZ::RHI::GeometryView` constructor with one parameter, which was introduced in [PR19009](https://github.com/o3de/o3de/pull/19009) as `explicit`. This ensures that the class is not instantiated implicitly, eg. by assigning a value of the parameter type in a class member declaration, which is more ambiguous than calling the class constructor explicitly.
(There are 3 small unrelated changes, which are necessary for compiling the engine with Clang on Windows due to unused variable errors, which are not triggered for MSVC.)
Compile the engine and ASV in profile and release mode.
=> Make AZ::RHI::GeometryView constructor with one parameter explicit

Code/Tools/SceneAPI/SDKWrapper/AssImpSceneWrapper.cpp, Code/Tools/SceneAPI/SDKWrapper/AssImpSceneWrapper.h, Code/Tools/SceneAPI/SceneBuilder/SceneSystem.cpp
Rotate the imported models 180 degrees on Z axis to face the positive Y axis.
Previous fixes on animation coordinate only tested on unreal-exported animations. When tested with mixamo animations the orientation of animations are incorrect. This PR took the transform algorithm from assimp to ensure the right orientation for fbx animations.
This PR also rotates models by 180 degrees on Z axis. Previously the importer uses blender's orientation which places front axis on -Y. This PR places the front axis on Y instead.
Tested characters and animations imported from mixamo and unreal engine
=> Fix the coordinate system transform for fbx animations.

Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
This fixes a crash in the AssetProcessor, that happens sometimes when a asset reprocessing is triggered from the GUI: The loop holds a reference to the front of the `m_activeFiles` - vector, but the function `CheckSource()` calls `AssessFileInternal()`, which modifies `m_activeFiles`, potentially invalidating the memory of used by that reference.
Windows, triggering the reprocessing of materials.
=> Fix a potential AP crash when reprocessing assets

scripts/o3de.sh
When the installer (.deb) installs on linux, it
creates a symlink to the o3de.sh script in the user's bin directory (on the path) so the user can just run `o3de.sh` from anywhere on their machine.
However, the script needs to know where the actual o3de python path is, relative to the script, and thus needs to de-symlink like all the other scripts (see python/python.sh and such, they all have this section at the top).
Runing o3de.sh from random places on the linux computer, not in that folder.
=> Fixes the installer o3de.sh script working on linux.

Gems/Atom/Feature/Common/Code/Include/Atom/Feature/RayTracing/RayTracingFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.h, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h, Gems/Atom/RHI/Code/Include/Atom/RHI/RayTracingAccelerationStructure.h, Gems/Atom/RHI/Code/Include/Atom/RHI/RayTracingCompactionQueryPool.h, Gems/Atom/RHI/Code/Source/RHI/RayTracingAccelerationStructure.cpp, Gems/Atom/RHI/Code/Source/RHI/RayTracingCompactionQueryPool.cpp, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridVisualizationPreparePass.cpp
Currently the RTAS pass needs to run every frame on every device that needs acceleration structures.
With this PR it's allowed to not have a RTAS pass on every device in every frame and also to add devices to the RT deviceMask dynamically.
I also added a check when accessing the submeshes in the BLAS instances. This should probably fix the issue described here: https://discordapp.com/channels/805939474655346758/816043793576886273/1379566028916527226
- Detect new RT devices in the `BeginFrame` function and add Device resources to all needed BLAS/... . For this new functions for adding/removing devices were added to the RT datastructures
- Save the last built version, and the build queues per device instead of globally
- Removed the multi-device `RayTracingTlasDescriptor` and pass …
=> Make the DeviceMask in RaytracingFeatureProcessor dynamic

Code/Framework/AzFramework/AzFramework/IO/LocalFileIO.cpp
This RP fixes asset names with non-ascii characters being incorrectly converted to lower-case when searching for them in the cache folder during editor startup. The function `std::tolower` uses the current locale to do this conversion, and on my machine (Windows 10 without the UTF-8 region setting enabled) it appears to be using a non utf8-locale to convert the two utf8-bytes of the `Ä` character to some other bytes, which are no longer valid utf8.
By using `AZStd::tolower` instead, the locale for the conversion is set to a default `std::locale{}`, which does not show this behavior, but also does not convert non-ascii characters to lower case. In the cache folder, however, the asset name is in lower case (eg. `ä.fbx.abdata.json`), so this might lead to problems on Linux which uses a …
=> Ensure call to ::tolower in cache path resolve function does not invalidate utf8 characters

Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp, Code/Editor/EditorPreferencesPageFiles.cpp, Code/Editor/Settings.cpp, Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserBus.h, Code/Framework/AzToolsFramework/AzToolsFramework/Script/LuaEditorSystemComponent.cpp
Fix #19047 so that users can open scripts (i.e Lua scripts) with the choosen editor instead of using the built-in by double-clicking on the file.
Also added a new action to the contextual menu "Open with external editor"
By default on windows, the "Scripts editor" setting is now empty (it was already the case for Linux).
⚠️  This is mostly a quick fix
- Editor Settings are not up to date. We need to change the logic to settings registry (https://docs.o3de.org/docs/user-guide/settings/). 
- If I understood well, the editor set in the "Scripts editor" setting was never used by the Asset Browser. Whenever you click on "Open with associated application..." it is going through `OpenWithOS` which uses the default application set for the OS to open this kind of file. We might want to improve …
=> Fix #19047 - Fix External scripts editor settings

Code/LauncherUnified/launcher_generator.cmake
The O3DE SDK from the Debian package installs into the `/opt/` directory, which requires superuser permissions. The `<project>.Assets` target attempts to create a lock file in this directory, causing an error. This pull request resolves the issue by relocating the lock file to `<project>/user/AssetProcessorTemp`, where the necessary user permissions are available.
1. Installed SDK in /opt.
2. Created project.
3. Used `<project>.Assets` target without problem.
=> Adjust the asset processor batch lock file path

Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
The raytrace feature processor was incorrectly using `auto` instead of `auto &` when iterating over its structures.  Most of the time, this would only be a slight performance hit, but fatally, when a mesh was cleared out of the raytracing feature processor, it used
```cpp
for (auto [deviceIndex, uncompactedBlasEnqueuedForDeletion] : m_uncompactedBlasEnqueuedForDeletion)
{
uncompactedBlasEnqueuedForDeletion.erase(id);
}
```
The lack of the ampersand meand that the erase was being carried out on a copy of the map, which would not actually remove the item from the original map, leaving bogus entries in there.
100% crash before this fix, 0% crash after this fix.  Fairly straightforward.
=> Fixes a crash that occurs when meshes update in RaytraceFeatureProcessor (due to hot reload or AP finish)

Gems/Vegetation/Code/Tests/PrefabInstanceSpawnerTests.cpp
As reported in https://discord.com/channels/805939474655346758/869974333009854464/1387552271369506866
When building all gems on MSVC latest, we currently run into an unused variable warning which fails the build. With this fixed, it is possible to run the install target on windows.
Related to 
- https://github.com/o3de/o3de/pull/18994
- https://github.com/o3de/o3de/pull/19049
Local windows build on dev branch latest
=> Add maybe_unused to fix vegetation test gem build on MSVC latest

Code/Tools/AssetProcessor/native/tests/AssetProcessorMessagesTests.cpp, Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/StreamingImageController.h, Gems/Atom/RPI/Code/Source/RPI.Public/Image/StreamingImageController.cpp, Gems/EditorPythonBindings/Code/Tests/PythonGlobalsTests.cpp
The `OnSetTargetMip` of the `StreamingImageController` sets the `m_lastAccessTimestamp` of the image and the calls `ReinsertImageToLists`.
`ReinsertImageToLists` first removes the image from the list and then reinserts it with the new priority.
Unfortunately the `m_lastAccessTimestamp` is also used in the comparison operator in the `m_evictableImages` set.
Therefor the image is not actually removed from `m_evictableImages` and it will stay there even after the image is deleted.
This leads to use after free, and to random crashes later on.
This PR fixes this problem by first removing the image from the lists, then set the timestamp, and finally insert the image into the lists again.
Tested with a project that sets the target mip of an image.
=> Fix StreamingImageController OnSetTargetMip

Gems/Atom/RHI/Vulkan/Code/Source/RHI/BufferView.cpp
Currently the Vulkan backend does not allow accessing structured buffers from the bindless srg. Since a `ByteAddressBuffer` can also be used to read a struct with the syntax `buffer.Load<MyStruct>(index * sizeof(MyStruct))`, it makes sense to allow structured buffers to be accessed like this as well (A simple workaround for this issue is to just use a R32-typed buffer view instead, but if the source data is already a vector of structs, it makes sense to also use a structured buffer for this).
Change some typed buffer views created with `RHI::BufferViewDescriptor::CreateRaw`, which are accessed with the bindless srg, to structured buffer views created by `RHI::BufferViewDescriptor::CreateStructured`, and verify that the rendering result is still correct:
* MeshFeatureProcessor.cpp: eg. …
=> Enable generation of bindless indices for structured buffer views in Vulkan

AutomatedTesting/Gem/PythonTests/assetpipeline/CMakeLists.txt, AutomatedTesting/Gem/PythonTests/assetpipeline/metadata_relocation_tests/CMakeLists.txt, AutomatedTesting/Levels/MetadataTest/MetadataTest.prefab
Two fixes here.  One is that the `periodic` test
was running when it should not, because it was not marked with SUITE_periodic in its pytest marks.
The other is that the test itself had an invalid
asset reference to the bunny model.  Its no clear
to me why the reference changed, but it did.  This is a very ancient asset, so its possible that it changed some time in the deep past.
1. Running `main` and seeing this test run (when it should not)
2. Fixing the code
3. running `main` and seeing this test no longer run.
4. running `periodic` and seeing this test run still.
5. Fixing the actual failing test also, so that it passes in `periodic`
=> Fixes `main` tests running a periodic test which fails

.github/workflows/android-build.yml, .github/workflows/linux-build.yml, .github/workflows/windows-build.yml
- (Windows, Linux, Android): Changes the archive target of the 3P packages within the build from the uncompressed packages to the compressed packages stored in `downloaded_packages`. This is to reduces instances where the uncompressed packages are not being written to disk or are somehow corrupted.
- (Windows, Linux, Android): Adds check for existing artifacts in rerun situations and uses them instead of the last run
- (Windows, Linux, Android): Increases the build job timeout to 330mins, to grab more artifacts before timing out
Tested in my fork. Example run here: https://github.com/amzn-changml/o3de/actions/runs/16029644667
=> AR 3P archive target change and retry reuse

Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/TransmissionInput.azsli, Gems/Atom/Feature/Common/Assets/Shaders/Materials/StandardMultilayerPBR/StandardMultilayerPBR_Common.azsli, Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/Textures/sample_texture_2d.materialgraphnode
Added the CS_SAMPLERS - define to a few places where it was still missing, so all materials can be used in a compute or raytracing shader.
Ran into shader compile errors when developing material hit shaders for raytracing passes.
=> Added missing CS_SAMPLERS - defines

Code/Framework/AzCore/AzCore/Instance/InstancePool.h, Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableMonitor.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/ColorPicker/PaletteCardCollection.cpp, Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/ColorPicker/PaletteCardCollection.h, Code/Tools/CrashHandler/Support/platform/Windows/crash_handler_support_windows_files.cmake, Gems/ScriptEvents/Code/Include/ScriptEvents/ScriptEventsAssetRef.h
Cherry picks the same PR from 25.05.1.
Note that most of these were already fixed in dev, so I discarded any changes that were already in dev, preferred to keep existing to minimize the amount of changes.
Just compilation - compile profile, release, in both latest msvc as well as clang19.
=> Cherry-pick from point release 2505.1 - Fixes all `unused variable` compile warnings.

Gems/Atom/RPI/Code/Source/RPI.Public/Material/MaterialSystem.cpp
For Android the `AZ_TRAITS_SCENE_MATERIALS_MAX_SAMPLERS` isn't set, so the fallback values is 0.
But the Srg-Layout of the `SceneMaterialSrg` still contains the `m_samplers` array with a hardcoded size of 8, even though the layout is not used by any shader on that platform.
The modified assert previously was triggered anytime the array size didn't match, now it triggers only if the maximum number of samplers can't fit in the SRG - array.
Trying to start the OpenXR office level on an Pixel 7a.
=> Defuse an assert when not using the SceneMaterialSrg (e.g. on android)

Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/LuaMaterialFunctor.cpp
During the material refactoring the handling of shader parameters changed, and the function `SetShaderConstant` was renamed to `SetShaderParameterValue`.
In lua functors, this isn't checked at compile time: To keep old lua material functors compatible, this PR re-introduces the `SetShaderConstant` function(s) for lua only.
=> restore SetShaderConstant lua functions for backwards compatability

Gems/Atom/Feature/Common/Assets/Passes/OpaqueParent.pass, Gems/Atom/Feature/Common/Assets/Passes/SsaoParent.pass
This PR changes the connection to the "DepthLinear" attachment through a slot to the "Parent" pass instead of connecting to "PipelineGlobal". This should not affect the functionality at all. But the big benefit is that it makes the `SsaoParent.pass` more versatile insofar as that it can be used in scenarios where different "DepthLinear" attachments are used. By connecting via "PipelineGlobal", only one specific connection is possible---by using "Parent", further options are enabled.
Run a project. Should not change anything.
=> Non-global DepthLinear attachment connection for SSAO

Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingSceneSrg.azsli, Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingSceneUtils.azsli, Gems/Atom/Feature/Common/Code/Include/Atom/Feature/RayTracing/RayTracingFeatureProcessorInterface.h, Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp, Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h, Gems/Atom/Feature/Common/Code/atom_feature_common_public_files.cmake, Gems/Atom/RHI/Assets/ShaderLib/Atom/RHI/IndexFormat.azsli, Gems/Atom/RHI/Assets/ShaderLib/Atom/RHI/VertexFormat.azsli, Gems/Atom/RHI/Assets/atom_rhi_asset_files.cmake, Gems/Atom/RHI/Code/CMakeLists.txt, Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/IndexFormat.h, Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/VertexFormat.h, Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceIndexBufferView.h, Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceRayTracingAccelerationStructure.h, Gems/Atom/RHI/Code/Include/Atom/RHI/RayTracingAccelerationStructure.h, Gems/Atom/RHI/Code/Source/RHI.Reflect/IndexFormat.cpp, Gems/Atom/RHI/Code/Source/RHI.Reflect/VertexFormat.cpp, Gems/Atom/RHI/Code/Source/RHI/DeviceIndexBufferView.cpp, Gems/Atom/RHI/Code/atom_rhi_reflect_files.cmake, Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingBlas.cpp, Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingBlas.cpp, Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/VertexBufferOperations.azsli, Gems/Atom/RPI/Assets/atom_rpi_asset_files.cmake, Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.cpp, Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp
This PR adds support for additional vertex formats for ray tracing geometry. While the ray tracing API in `RayTracingFeatureProcessorInterface` already allows to configure the vertex formats of each property (eg. `m_normalFormat` in `RayTracingFeatureProcessorInterface::SubMesh`, they were not yet implemented and using anything other than a float-32 format would not work.
The following formats are now supported (`*_OCT` are octahedron-encoded normals and tangents, where the number is the total number of bits required for one normal/tangent):
* Position: `R32G32B32_FLOAT`, `R16G16B16A16_FLOAT`
* Normal: `R32G32B32_FLOAT`, `R16G16B16_FLOAT`, `N32_OCT`, `N16_OCT`, `N8_OCT`
* UV: `R32G32_FLOAT`, `R16G16_FLOAT`, `R8G8_UNORM`
* Tangent: `R32G32B32A32_FLOAT`, `R16G16B16A16_FLOAT`, `T32_OCT`, …
=> Add support for additional ray tracing vertex formats

Gems/AFR/CMakeLists.txt, Gems/AFR/Code/CMakeLists.txt, Gems/AFR/Code/Include/AFR/AFRBus.h, Gems/AFR/Code/Include/AFR/AFRFeatureProcessor.h, Gems/AFR/Code/Include/AFR/AFRTypeIds.h, Gems/AFR/Code/Source/AFRFeatureProcessor.cpp, Gems/AFR/Code/Source/AFRModuleInterface.cpp, Gems/AFR/Code/Source/AFRModuleInterface.h, Gems/AFR/Code/Source/Clients/AFRModule.cpp, Gems/AFR/Code/Source/Clients/AFRSystemComponent.cpp, Gems/AFR/Code/Source/Clients/AFRSystemComponent.h, Gems/AFR/Code/Source/Tools/AFREditorModule.cpp, Gems/AFR/Code/Source/Tools/AFREditorSystemComponent.cpp, Gems/AFR/Code/Source/Tools/AFREditorSystemComponent.h, Gems/AFR/Code/afr_api_files.cmake, Gems/AFR/Code/afr_editor_private_files.cmake, Gems/AFR/Code/afr_editor_shared_files.cmake, Gems/AFR/Code/afr_private_files.cmake, Gems/AFR/Code/afr_shared_files.cmake, Gems/AFR/gem.json, Gems/AFR/preview.png, engine.json
This PR introduces alternate frame rendering (AFR) functionality to the engine by latching on to a `RenderPipeline`, capturing all passes that are not already scheduled to a fixed device (as well as the `CopyToSwapchain` pass which always runs on the default display device), alternating them between the devices over successive frames and inserting a `CopyPass` from the auxiliary GPUs to the display GPUs at the end, right before `CopyToSwapchain`.
AFR is currently enabled by adding a command lind parameter `--afr <PartialPipelineName>` (e.g. `--afr MainPipeline` to run for the MainPipeline (not an exact match as additional runtime parameters might be added to a pipeline name, like `ViewportId`), if no name is pipeline name is passed, it latches onto the first pipeline which has a …
=> Introduce Alternate Frame Rendering capability to the engine
