- scripts/o3de/o3de/manifest.py
This protects against None being returned from `get_project_json_data` and `get_engine_json_data` methods respectively.
> Added if checks in the get_project* and get_engine* functions in manifest.py

- Code/Editor/ActionManager.cpp
- Code/Editor/ActionManager.h
- Code/Editor/Core/LevelEditorMenuHandler.cpp
- Code/Editor/CryEdit.cpp
- Code/Editor/Resource.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/AzToolsFrameworkTestHelpers.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/AzToolsFrameworkTestHelpers.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ActionBus.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelectionRequestBus.h
Problem with DCO so we need to cherry pick this branch.
Signed-off-by: aaguilea <aaguilea@amazon.com>
> Cherry Picking (lyn1751)

- CONTRIBUTING.md
Signed-off-by: Royal OBrien <obwando@obwando.com>
> Adding contributing guide pointer markdown

- Code/Framework/AzQtComponents/AzQtComponents/Components/Style.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BaseStyleSheet.qss
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/MessageBox.qss
- Code/Framework/AzQtComponents/AzQtComponents/Components/resources.qrc
> fix for [LYN-4828], message box style changes

- README.md
Updated to list the current supported version of Wwise.
> Update Wwise version info in Readme.md

- Gems/AtomLyIntegration/ImguiAtom/Code/Source/ImguiAtomSystemComponent.cpp
> Fixed warning of variable not being used in release of ImguiAtom.

- AutomatedTesting/Gem/PythonTests/editor/EditorScripts/Menus_ViewMenuOptions.py
- AutomatedTesting/Gem/PythonTests/editor/test_Menus.py
- Removed check for Viewport > Change Move Speed
Signed-off-by: jckand-amzn <jckand@amazon.com>
> Updating expected View menu options for test_Menus_ViewMenuOptions_Work

- Code/LauncherUnified/Platform/iOS/Launcher_iOS.mm
Signed-off-by: mgwynn <mgwynn@amazon.com>
> Adding header to resolve undefined type error

- Gems/Multiplayer/Code/Source/ReplicationWindows/ServerToClientReplicationWindow.cpp
Signed-off-by: pereslav <pereslav@amazon.com>
> Fixed crash when non-net entities get activated

- Code/Framework/AzFramework/AzFramework/Session/ISessionHandlingRequests.h
- Code/Framework/AzFramework/AzFramework/Session/ISessionRequests.h
- Code/Framework/AzFramework/AzFramework/Session/SessionConfig.h
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftActivityUtils.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftActivityUtils.h
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftCreateSessionActivity.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftCreateSessionOnQueueActivity.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftJoinSessionActivity.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftLeaveSessionActivity.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftSearchSessionsActivity.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/awsgamelift_client_files.cmake
- Gems/AWSGameLift/Code/AWSGameLiftServer/Source/AWSGameLiftServerManager.cpp
1. Give default value to primitive type to avoid unexpected behavior on different compiler
2. Add more logs
Manual tested, and pass unit test
> [LYN-4820] Add more logs for gamelift workflow

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/PhysicalDevice.cpp
Ref'ed variable only used in assert
> SPEC-7601 windows monolithic_release_vs_2019 build failed

- Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiCpuProfiler.inl
Update helpers to fix casting compile error
> Profiler: fix build error due to cast on Mac

- Code/Tools/ProjectManager/Resources/ProjectManager.qss
- Code/Tools/ProjectManager/Source/ProjectUtils.cpp
- Code/Tools/ProjectManager/Source/ProjectUtils.h
> Project Manager: Showing a progress bar when copying projects

- cmake/Platform/Windows/PackagingPostBuild.cmake
- A built tag file with the commit info is included in the 'latest' upload
- Silenced output of upload script
> [stabilization/2106] upload a copy of the bootstrap installer to the 'latest' folder for tagged builds

- Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/Outliner/OutlinerSortFilterProxyModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerSortFilterProxyModel.cpp
fix outliner sorting using incorrect types for comparisons, fixes for [LY-122258] and [LYN-3666].
> fix outliner sorting using incorrect types for comparisons

- Code/Tools/ProjectManager/Source/GemCatalog/GemFilterTagWidget.cpp
- Code/Tools/ProjectManager/Source/ProjectUtils.cpp
> Aftermath for PR-1956 and PR-2025

- Gems/Vegetation/Code/Source/Debugger/DebugComponent.cpp
> Fix unused variable warning in release configuration: DebugComponent::DrawInstanceDebug

- Code/Editor/EditorViewportWidget.cpp
- Code/Editor/RenderViewport.cpp
> Text changed and default behaviour changed

- scripts/build/Jenkins/Jenkinsfile
Merging #2097 to stabilization/2106
Signed-off-by: brianherrera <briher@amazon.com>
> Remove separate git lfs steps.

- scripts/build/bootstrap/incremental_build_util.py
Removed some unnecessary codes.
Renamed some functions for better readability.
Added a timeout function and wrap volume operations with the new timeout function "with timeout()".
Converted .format() to fstring.
> Cleanup incremental build scripts

- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ActionBus.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorDefaultSelection.h
- Code/Framework/AzToolsFramework/Tests/ComponentModeTestDoubles.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorTubeShapeComponentMode.cpp
- Gems/PhysX/Code/Editor/ColliderComponentMode.cpp
- Gems/PhysX/Code/Editor/EditorJointComponentMode.cpp
- Gems/WhiteBox/Code/Source/SubComponentModes/EditorWhiteBoxDefaultMode.cpp
LYN-4942
Signed-off-by: aaguilea <aaguilea@amazon.com>
> Changed all amazon reverse urls to o3de reverse urls

- Code/Editor/Plugins/ProjectSettingsTool/ProjectSettingsToolWindow.cpp
- Code/Editor/Plugins/ProjectSettingsTool/ProjectSettingsToolWindow.h
> [development] update mobile settings editor tool to support new project path structure

- AutomatedTesting/Levels/Physics/C14902098_ScriptCanvas_PostPhysicsUpdate/onpostphysicsupdate.scriptcanvas
- AutomatedTesting/ScriptCanvas/C14195074_ScriptCanvas_PostUpdateEvent.scriptcanvas
- AutomatedTesting/ScriptCanvas/C14902097_ScriptCanvas_PreUpdateEvent.scriptcanvas
> update sc that is used in physics tests to use the 'PhysicsSystemInterface' instead of 'System Interface'

- Gems/LyShine/Code/CMakeLists.txt
- Gems/LyShine/Code/Source/LyShineModule.cpp
- Gems/LyShine/Code/lyshine_common_module_files.cmake
- Gems/LyShine/Code/lyshine_static_files.cmake
> Split LyShine .Editor target to .Tools and .Builders

- Gems/LyShine/Code/Source/LyShineSystemComponent.cpp
- Gems/LyShine/Code/Source/LyShineSystemComponent.h
> Fix LyShine bus attempt to connect twice

- Code/Framework/AzCore/AzCore/Script/ScriptContextDebug.cpp
Fixed Lua class enumeration, there was a crash when traversing into methods and documented what the Lua calls are intended for
> Fixed Lua class enumeration, there was a crash when traversing into methods

- Gems/Atom/RHI/Metal/Code/Source/Platform/Mac/RHI/Metal_RHI_Mac.cpp
- Gems/Atom/RHI/Metal/Code/Source/Platform/iOS/RHI/Metal_RHI_iOS.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/SwapChain.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/SwapChain.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Shader/ShaderResourceGroupPool.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/WindowContext.cpp
Add shader name to SRGPool for debugging purposes
Set default value of rpi_vsync_interval to 1
> Metal sync interval support

- Tools/LyTestTools/ly_test_tools/o3de/asset_processor_utils.py
> Added Lua Editor window to kill process list.

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp
> SPEC-7737 Vulkan SwapChain fails to compile in release

- Gems/Atom/RHI/Metal/Code/Source/Platform/iOS/RHI/Metal_RHI_iOS.cpp
> Quick compile fix

- Gems/PhysX/Code/Editor/DocumentationLinkWidget.cpp
> UI tweaks of the physics doc link widget

- Gems/ScriptEvents/Code/Include/ScriptEvents/ScriptEventDefinition.h
> Change the code so a temporary string isn't created

- cmake/Platform/Common/Install_common.cmake
Signed-off-by: Axel Nana <axel.nana@aliens-group.com>
> Cherry-Pick: Add missing `*.hxx` pattern

- Code/Framework/AzFramework/Platform/Windows/AzFramework/Asset/AssetSystemComponentHelper_Windows.cpp
When the Asset Processor is launched via `LaunchAssetProcessor` from a parent project, this change will terminate it when the parent process terminates.
> Terminate AssetProcessor when spawned by the parent project process

- Code/Tools/AssetProcessor/native/InternalBuilders/SettingsRegistryBuilder.cpp
> Fixed the SettingsRegistryBuilder not merging the Registry directories within Gems

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp
Checked for there being no entities selected and handled the enabling of the text message.
> Im gui no entity problem

- Code/Tools/AssetProcessor/native/InternalBuilders/SettingsRegistryBuilder.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/Conversions.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/Metal.h
> fix reference to temporary

- AutomatedTesting/Gem/PythonTests/physics/TestSuite_Main.py
- AutomatedTesting/Gem/PythonTests/physics/TestSuite_Sandbox.py
> Moving test_C15425929_Undo_Redo flaky test to sandbox test suite

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Connection.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Slot.cpp
> Crash guard when the data has a list with an empty contract

- AutomatedTesting/Gem/PythonTests/largeworlds/landscape_canvas/test_GeneralGraphFunctionality.py
Signed-off-by: jckand-amzn <jckand@amazon.com>
> Adding xfail mark to test_LandscapeCanvas_GraphClosed_OnEntityDelete

- Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Header.jinja
> Fix autogen template RewindableObject construction for linux platform

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Variable/GraphVariable.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Variable/GraphVariable.h
> Script Canvas: Fixed Scope and Initial Value selection boxes

- cmake/LYTestWrappers.cmake
> Made LyTT Tests check if they are disabled for the platform.

- Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp
> Project Manager: Check for Minimum VS Subversion and Link to Workload Install Instructions for VS

- Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilder.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Translation/GraphToLua.cpp
- Gems/ScriptCanvasTesting/Assets/ScriptCanvas/UnitTests/LY_SC_UnitTest_EntityIdInputForOnGraphStart.scriptcanvas
- Gems/ScriptCanvasTesting/Code/Tests/ScriptCanvas_RuntimeInterpreted.cpp
Never could truly reproduce https://github.com/o3de/o3de/issues/2190, but this fixes a similar problem related to direct entity references.
> fix entity reference removal when not in a variable

- Gems/StartingPointInput/Code/Source/InputConfigurationComponent.cpp
> Corrected the text message

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/AbstractCodeModel.cpp
fixes https://github.com/o3de/o3de/issues/2486
> remove null data check from connected slots

- Code/Framework/AzNetworking/AzNetworking/ConnectionLayer/ConnectionMetrics.cpp
- Code/Framework/AzNetworking/AzNetworking/ConnectionLayer/ConnectionMetrics.h
- Code/Framework/AzNetworking/AzNetworking/ConnectionLayer/ConnectionMetrics.inl
- Code/Framework/AzNetworking/AzNetworking/ConnectionLayer/IConnection.h
- Code/Framework/AzNetworking/AzNetworking/ConnectionLayer/IConnection.inl
- Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpConnection.cpp
- Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpConnection.h
- Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpConnection.cpp
- Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpConnection.h
- Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpConnection.inl
- Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpNetworkInterface.cpp
- Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpSocket.cpp
- Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugSystemComponent.cpp
New AzNetworking metrics display plus connection quality debug widgets using ImGui
Signed-off-by: kberg-amzn <karlberg@amazon.com>
> New AzNetworking metrics display plus connection quality debug widgets using ImGui

- cmake/Platform/Common/Directory.Build.props
> disable vcpkg for every project

- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
Corrects math computing blend factors to interpolate state between received network updates
Signed-off-by: kberg-amzn <karlberg@amazon.com>
> Corrects math computing blend factors to interpolate state between received network updates

- Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Common.jinja
Signed-off-by: Olex Lozitskiy <mr.olexander@gmail.com>
> Minor corrections in code gen for usability

- Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Source.jinja
Signed-off-by: pereslav <pereslav@amazon.com>
> Fixed autogen namespace always going upper case

- Gems/Atom/Feature/Common/Assets/Scripts/material_property_overrides_demo.lua
O3DE vector usage in lua has changed since script was written
> fixing material property override lua test script

- Code/Framework/AzCore/Tests/Asset/AssetManagerLoadingTests.cpp
Signed-off-by: stankowi <4838196+AMZN-stankowi@users.noreply.github.com>
> Disabling a flaky test ContainerFilterTest_ContainersWithAndWithoutFiltering_Success

- Code/Tools/ProjectManager/Platform/Windows/ProjectBuilderWorker_windows.cpp
- Code/Tools/ProjectManager/Source/ProjectBuilderController.cpp
> Check for build process exit status and display log link in more cases.

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ModularViewportCameraController.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ModularViewportCameraController.cpp
This is a follow-on PR from https://github.com/o3de/o3de/pull/2346 to keep the functional and doc changes separate.
> Documentation pass for modular viewport camera controller

- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/MaterialEditorApplication.cpp
- Gems/Atom/Tools/MaterialEditor/Scripts/GenerateAllMaterialScreenshots.py
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleApplication.cpp
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleApplication.h
Updating test scripts
Synchronizing SMC and ME application classes
> Fixing issues with shader management console startup

- Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableEntitiesInterface.cpp
- Code/Framework/AzFramework/Tests/Spawnable/SpawnableEntitiesManagerTests.cpp
> Fixed EntitySpawnTicket move constructor

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Math/Vector2Nodes.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Math/Vector3Nodes.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Math/Vector4Nodes.h
> Added Get Direction Vector node for Vector2,3 and 4

- Gems/QtForPython/Editor/Scripts/show_object_tree.py
Signed-off-by: Garcia Ruiz <aljanru@amazon.co.uk>
> Improve ui object tree to show the actual instance class

- Code/Editor/Settings.cpp
- Code/Framework/AzCore/AzCore/std/chrono/types.h
- Code/Framework/AzCore/AzCore/std/containers/ring_buffer.h
- Code/Framework/AzCore/AzCore/std/utils.h
- Gems/LyShine/Code/Editor/HierarchyMenu.cpp
Two smaller bugs, some incorrect code, and a better check for ring_buffer::insert source iterators
> Bunch of small bug fixes

- Code/Tools/AssetProcessor/native/AssetManager/SourceFileRelocator.cpp
Since the engine target version is c++17 using std::bind is a likely indicator of older code :)
> Use lambda instead of AZStd::bind

- scripts/build/Jenkins/Jenkinsfile
Signed-off-by: shiranj <shiranj@amazon.com>
> Cherry pick from stabilization: Include build failure root cause in email notification (#2491)

- Gems/LyShine/Code/Editor/Animation/UiAnimUndoManager.cpp
- Gems/LyShine/Code/Editor/AssetTreeEntry.cpp
> warnings not previously detected

- .gitignore
- Code/Framework/AzCore/AzCore/Script/ScriptProperty.cpp
- Code/Framework/AzCore/AzCore/Script/ScriptProperty.h
- Code/Framework/AzCore/AzCore/Script/ScriptPropertySerializer.cpp
- Code/Framework/AzCore/AzCore/Script/ScriptPropertySerializer.h
- Code/Framework/AzCore/AzCore/Script/ScriptSystemComponent.cpp
- Code/Framework/AzCore/AzCore/Serialization/DynamicSerializableField.cpp
- Code/Framework/AzCore/AzCore/Serialization/DynamicSerializableField.h
- Code/Framework/AzCore/AzCore/Slice/SliceComponent.h
- Code/Framework/AzCore/AzCore/azcore_files.cmake
- Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/ScriptEditorComponent.cpp
- Gems/LmbrCentral/Code/Source/Builders/LuaBuilder/LuaBuilderComponent.cpp
- Gems/ScriptEvents/Code/Include/ScriptEvents/Internal/VersionedProperty.cpp
> Add JSON serializer support for the Lua component properties

- Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorAnimGraphComponent.cpp
> Open the EMFX editor even if no asset is specified

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyRowWidget.cpp
User sentiment on discord seem to be positive about this change
> Adjustment to property row so the label is more visible

- Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiCpuProfiler.inl
Fixes a bug with the visualizer where there would be empty rows shown (threads without any profiling regions). This was especially noticeable when going from a high thread count sample (MultiThread) to a low thread count sample, where most of the visualizer would be empty lines. This adds a data culling step to remove the threads without any remaining execution data + an early out so that all threads shown onscreen must have some regions recorded.
> CPU Visualizer: fix empty rows being shown

- Code/Editor/EditorPreferencesPageViewportMovement.cpp
- Code/Editor/EditorViewportSettings.h
- Code/Editor/EditorViewportWidget.cpp
- Code/Editor/GotoPositionDlg.cpp
- Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
- Code/Editor/ViewportTitleDlg.cpp
Signed-off-by: aaguilea <aaguilea@amazon.com>
> Removing the legacy code from the old camera

- Gems/ScriptCanvas/Code/Editor/SystemComponent.cpp
> Updated path to icon that was emitting a warning

- Gems/AWSCore/Code/Tools/ResourceMappingTool/controller/view_edit_controller.py
- Gems/AWSCore/Code/Tools/ResourceMappingTool/model/constants.py
- Gems/AWSCore/Code/Tools/ResourceMappingTool/model/error_messages.py
- Gems/AWSCore/Code/Tools/ResourceMappingTool/model/notification_label_text.py
- Gems/AWSCore/Code/Tools/ResourceMappingTool/tests/unit/controller/test_view_edit_controller.py
Signed-off-by: junbo <junbo@amazon.com>
Verified in the Resource Mapping Tool and passed all unit tests.
> Set the default region for the Resource Mapping Tool when no region is configured via AWS CLI

- Code/Framework/AzFramework/Platform/Windows/AzFramework/Input/Devices/Keyboard/InputDeviceKeyboard_Windows.cpp
- Code/Framework/AzFramework/Platform/Windows/AzFramework/Input/Devices/Mouse/InputDeviceMouse_Windows.cpp
> Fix for checking environment variable existence

- Code/Framework/AzFramework/Platform/Mac/AzFramework/Windowing/NativeWindow_Mac.mm
- Code/Framework/AzFramework/Platform/iOS/AzFramework/Windowing/NativeWindow_ios.mm
> Fix minor typo

- Gems/Atom/Feature/Common/Code/Source/AuxGeom/DynamicPrimitiveProcessor.cpp
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/DynamicDraw/DynamicBuffer.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/DynamicDraw/DynamicDrawInterface.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/DynamicDraw/DynamicDrawSystem.h
- Gems/Atom/RPI/Code/Source/RPI.Public/DynamicDraw/DynamicDrawContext.cpp
> Fix byte alignment issue for index/vertex buffers

- AutomatedTesting/Gem/PythonTests/smoke/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/smoke/test_RemoteConsole_CPULoadLevel_Works.py
Moving smoke test to sandbox while the issue is root caused.
> moving smoke test to sandbox suite to investigate failures

- Code/Framework/AzQtComponents/AzQtComponents/Components/FancyDocking.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.hxx
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyRowWidget.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyRowWidget.hxx
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ReflectedPropertyEditor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ReflectedPropertyEditor.hxx
> LY-91616 Dyn Veg: Push (up) and Pop (down) Items in Descriptor List

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyRowWidget.cpp
> compile fix

- Code/Legacy/CrySystem/XConsole.cpp
> Auto-completing the inserted text by pressing TAB within Editor's Console results in a silent crash

- Code/Framework/AzToolsFramework/AzToolsFramework/PythonTerminal/ScriptHelpDialog.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/PythonTerminal/ScriptHelpDialog.h
Checking EditorWindowRequests::GetAppMainWindow before searching for main window
> AtomTools: Fix python terminal help crash ATOM-16242

- Code/Framework/AzToolsFramework/AzToolsFramework/Logger/TraceLogger.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Logger/TraceLogger.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
Added message filter support to TraceLogger
> AtomTools: restoring log message filter to ignore source control spam

- cmake/LYWrappers.cmake
> Change LY_UNITY_BUILD default to "ON"

- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/SpinBox.cpp
> Fixed wheel working on spinbox non focused

- scripts/build/Jenkins/Jenkinsfile
Add missing {} for string interpolation
> Add missing {} for string interpolation

- AutomatedTesting/Gem/PythonTests/prefab/PrefabLevel_BasicWorkflow.py
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicInterface.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicRequestBus.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicRequestHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicRequestHandler.h
Signed-off-by: chiyteng <chiyteng@amazon.com>
Add a new automated test for verifying if Prefab deletion workflow works:
Tested the new test by running this command: python\python.cmd -m pytest AutomatedTesting\Gem\PythonTests\prefab\TestSuite_Main.py::TestAutomation::test_PrefabLevel_BasicWorkflow --build-directory windows_vs2019\bin\debug
> Add a new auto test for delete prefab workflow

- Code/Tools/ProjectManager/Source/FormBrowseEditWidget.cpp
- Code/Tools/ProjectManager/Source/FormBrowseEditWidget.h
- Code/Tools/ProjectManager/Source/FormFolderBrowseEditWidget.cpp
> Pressing Enter/Return Key While File Browse Widget is Focused Opens File Browser

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasGrammar_Header.jinja
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasGrammar_Source.jinja
> Completed namespace support for the ScriptCanvasGrammar template

- cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake
- cmake/3rdParty/Platform/Mac/BuiltInPackages_mac.cmake
- cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
> Remove unused hdf5 3rdParty package from the known packages list

- Gems/Atom/RPI/Code/Source/Platform/Common/VisualStudio/Natvis/shaderoptiongroup.natvis
- Gems/Atom/RPI/Code/Source/Platform/Windows/platform_windows_files.cmake
Added .natvis file to visualize option values in a ShaderOptionGroup.
> Shader options natvis

- Gems/Multiplayer/Code/Include/Multiplayer/NetworkEntity/INetworkEntityManager.h
- Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp
- Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.h
- Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityTracker.cpp
- Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityTracker.h
- Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityTracker.inl
Signed-off-by: pereslav <pereslav@amazon.com>
> Added the ability to look up a Net Entity ID for a given AZ Entity ID

- Gems/AtomLyIntegration/ImguiAtom/Code/Source/DebugConsole.h
- Gems/GameState/Code/CMakeLists.txt
- Gems/GameStateSamples/Code/CMakeLists.txt
- Gems/GameStateSamples/Code/Source/GameStateSamplesModule.cpp
Fix the GameStateSamples Gem and remove an unused variable from DebugConsole.h
> Fix the GameStateSamples Gem and remove an unused variable from DebugConsole.h

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Application/AtomToolsApplication.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/main.cpp
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/main.cpp
Deleted a bunch of unused headers
> AtomTools: moved more startup code from main cpp files into the base application class

- Gems/AudioEngineWwise/Code/Source/Engine/AudioSystemImpl_wwise.cpp
> fixing wwise warns/compilation errors

- Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp
- Code/Editor/Controls/ReflectedPropertyControl/PropertyMiscCtrl.cpp
- Code/Editor/Controls/ReflectedPropertyControl/ReflectedPropertyItem.cpp
- Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp
- Code/Editor/Lib/Tests/test_ViewportManipulatorController.cpp
- Code/Editor/MainWindow.cpp
- Code/Editor/Objects/BaseObject.cpp
- Code/Editor/Objects/EntityObject.cpp
- Code/Editor/TrackView/TrackViewKeyPropertiesDlg.cpp
A few small modernizations as well ( override )
Signed-off-by: Nemerle <96597+nemerle@users.noreply.github.com>
> Replace `std::bind` usages by lambdas in Code/Editor

- Code/Tools/TestImpactFramework/Frontend/Console/Code/Source/TestImpactConsoleUtils.cpp
- Gems/AudioEngineWwise/Code/Source/Engine/FileIOHandler_wwise.cpp
> SPEC-8039 [Windows] profile_vs2019_nounity build failure in TestImpactConsoleUtils.cpp

- Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogHeaderWidget.cpp
- Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
- Code/Tools/ProjectManager/Source/GemCatalog/GemInspector.cpp
- Code/Tools/ProjectManager/Source/GemCatalog/GemItemDelegate.cpp
- Code/Tools/ProjectManager/Source/GemCatalog/GemModel.cpp
- Code/Tools/ProjectManager/Source/GemCatalog/GemModel.h
- Code/Tools/ProjectManager/Source/GemCatalog/GemRequirementDelegate.cpp
- Code/Tools/ProjectManager/Source/GemCatalog/GemSortFilterProxyModel.cpp
Improves Gem Catalog Search (searches, Name, DisplayName, Creator, Summary, and Features)
Closes #2909
> Improves Gem Catalog Search, Gem Display Names now used in Gem Catalog

- Gems/PhysX/Code/Source/EditorColliderComponent.cpp
> fixed case where the Physics Asset could not be set correctly

- Code/Tools/RemoteConsole/Core/RemoteConsoleCore.cpp
- Code/Tools/RemoteConsole/Core/RemoteConsoleCore.h
- Tools/RemoteConsole/ly_remote_console/ly_remote_console/remote_console_commands.py
- Tools/RemoteConsole/ly_remote_console/tests/unit/test_remote_console_commands.py
Adds a message that the Remote Console sends when it connects. This message is used to verify that the RC has connected. Tested by running local test 100/100 times.
> Adds a verification response for the remote console connecting

- Gems/Terrain/gem.json
- Gems/Terrain/preview.png
Updated the description per UX/doc guidance, removed the unused icon, and added a functioning doc link.
> Updated Terrain Gem Info

- AutomatedTesting/Gem/PythonTests/smoke/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/smoke/test_RemoteConsole_CPULoadLevel_Works.py
Test has been passing in sandbox suite for the past 4 runs.
> Moving fixed smoke test from sandbox to smoke suite

- Gems/AWSClientAuth/cdk/README.md
- Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Launchers/Windows/Env_PyCharm.bat
- Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Launchers/Windows/Env_Python.bat
- Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Launchers/Windows/Env_WingIDE.bat
- Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Launchers/Windows/Launch_MayaPy_PyCharmPro.bat
- Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Launchers/Windows/Launch_VScode.bat
- Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Launchers/Windows/Launch_WingIDE-7-1.bat
- Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Launchers/Windows/Launch_mayapy_WingIDE-7-1.bat
- Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Launchers/Windows/Setuo_copy_oiio.bat
- cmake/LYPython.cmake
- python/python.cmd
- python/python.sh
Signed-off-by: Garcia Ruiz <aljanru@amazon.co.uk>
> Added pdbs for python windows in order to allow python/c++ debugging on VS

- AutomatedTesting/Gem/PythonCoverage/Code/Source/PythonCoverageEditorSystemComponent.cpp
- Code/Framework/AzCore/AzCore/std/function/function_base.h
- Code/Framework/AzCore/AzCore/std/function/function_template.h
- Code/Framework/AzCore/AzCore/std/parallel/binary_semaphore.h
- Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/std/parallel/internal/condition_variable_WinAPI.h
- Code/Framework/AzCore/Tests/AZStd/Hashed.cpp
- Code/Framework/AzCore/Tests/AZStd/Ordered.cpp
- Code/Tools/SceneAPI/SceneCore/Tests/Containers/Views/PairIteratorTests.cpp
- Code/Tools/TestImpactFramework/Runtime/Code/Include/TestImpactFramework/TestImpactClientSequenceReport.h
- Code/Tools/TestImpactFramework/Runtime/Code/Include/TestImpactFramework/TestImpactRepoPath.h
- Code/Tools/TestImpactFramework/Runtime/Code/Source/Platform/Windows/TestEngine/JobRunner/TestImpactWin32_TestTargetExtension.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.h
- Gems/Blast/Code/Source/Family/DamageManager.h
- Gems/PhysX/Code/Tests/PhysXJointsTest.cpp
- Gems/PhysX/Code/Tests/PhysXSceneTests.cpp
- Gems/WhiteBox/Code/Source/Core/WhiteBoxToolApi.cpp
- cmake/Platform/Common/MSVC/Configurations_msvc.cmake
https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=msvc-160
> Setting /permissive- to make MSVC more "standard"

- Gems/Terrain/Code/Source/Components/TerrainWorldComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainWorldDebuggerComponent.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.h
- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.cpp
- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.h
- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystemBus.h
Cleaned up a few things in the terrain system / components. Draw packets now only build when things change. Added some basic culling so that only sectors that might be visible by the view are drawn.
> First pass terrain cleanup

- Code/Editor/Platform/Mac/main_dummy.cpp
- Code/Tools/AssetProcessor/Platform/Mac/main_dummy.cpp
> [Mac] Fix crash in Editor and AssetProcessor.

- Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/std/parallel/internal/condition_variable_WinAPI.h
> Changes the cast for WinAPI mutex

- Gems/Atom/RPI/Tools/CMakeLists.txt
Signed-off-by: qingtao <qingtao@amazon.com>
> Add atom_rpi_tools to install package.

- Gems/Blast/Code/Source/Family/DamageManager.h
> Fix Blast Gem Compiler Error

- AutomatedTesting/Gem/PythonTests/physics/TestSuite_Main.py
- AutomatedTesting/Gem/PythonTests/physics/TestSuite_Sandbox.py
The test has been passing in sandbox for the past 30 days. Moving it from sandbox to main
> Moving physics test from sandbox to main

- Code/Legacy/CryCommon/Cry_Camera.h
- Code/Legacy/CryCommon/Cry_Matrix34.h
- Code/Legacy/CryCommon/Cry_Vector4.h
> Fix some debug compile errors introduced by https://github.com/o3de/o3de/pull/3903

- Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.cpp
- Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.h
> Add RayTracingPass support for the Scene Srg

- Code/Framework/AzToolsFramework/AzToolsFramework/Asset/AssetBundler.cpp
- Code/Framework/AzToolsFramework/Platform/Linux/AzToolsFramework/Archive/ArchiveComponent_Linux.cpp
- Code/Tools/Standalone/Source/LUA/LUAEditorMainWindow.cpp
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvert.cpp
- Gems/Atom/Asset/Shader/Code/Source/Editor/AtomShaderConfig.cpp
- Gems/Atom/Asset/Shader/Code/Source/Editor/CommonFiles/CommonTypes.cpp
- Gems/Atom/Asset/Shader/Code/Source/Editor/PrecompiledShaderBuilder.cpp
- Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderBuilderUtility.cpp
- Gems/Atom/RHI/Code/Source/RHI.Edit/Utils.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI.Builders/ShaderPlatformInterface.cpp
- Gems/Atom/RPI/Code/Source/RPI.Builders/Common/AnyAssetBuilder.cpp
- Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilder.cpp
- Gems/Atom/RPI/Code/Source/RPI.Builders/Model/MaterialAssetBuilderComponent.cpp
- Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelExporterComponent.cpp
- Gems/Atom/RPI/Code/Source/RPI.Builders/Pass/PassBuilder.cpp
- Gems/AtomLyIntegration/AtomBridge/Code/Source/Editor/AssetCollectionAsyncLoaderTestComponent.cpp
- Gems/EditorPythonBindings/Code/Source/PythonProxyBus.cpp
- Gems/LmbrCentral/Code/Source/Builders/MaterialBuilder/MaterialBuilderComponent.cpp
- Gems/LmbrCentral/Code/Source/Builders/SliceBuilder/SliceBuilderWorker.cpp
- Gems/LyShine/Code/Pipeline/LyShineBuilder/UiCanvasBuilderWorker.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/SubgraphInterface.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/Interpreted/ExecutionInterpretedAPI.cpp
- Gems/ScriptEvents/Code/Builder/ScriptEventsBuilderWorker.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
> Fixes for release builds for unused variable warnings

- AutomatedTesting/Levels/Physics/ScriptCanvas_CollisionEvents/ScriptCanvas_CollisionEvents.ly
- AutomatedTesting/Levels/Physics/ScriptCanvas_CollisionEvents/collision_events_script.scriptcanvas
- AutomatedTesting/Levels/Physics/ScriptCanvas_PreUpdateEvent/ScriptCanvas_PreUpdateEvent.ly
- AutomatedTesting/ScriptCanvas/ScriptCanvas_PostUpdateEvent.scriptcanvas
- AutomatedTesting/ScriptCanvas/ScriptCanvas_PreUpdateEvent.scriptcanvas
PS D:\o3de\branch_automation> python\python.cmd -m pytest --build-directory build/bin/profile  AutomatedTesting\Gem\PythonTests\physics\TestSuite_Periodic.py -k "ScriptCanvas_"
==================== test session starts =================================
platform win32 -- Python 3.7.10, pytest-5.3.2, py-1.9.0, pluggy-0.13.1
rootdir: D:\o3de\branch_automation
collected 98 items / 92 deselected / 6 selected
AutomatedTesting\Gem\PythonTests\physics\TestSuite_Periodic.py ......                                                                                                            [100%]
======== 6 passed, 92 deselected, 1 warning in 113.71s (0:01:53) =================
> Fixed Physics SC tests

- Gems/Terrain/Code/Source/Components/TerrainLayerSpawnerComponent.cpp
> Change TerrainLayerSpawner to use axis aligned box.

- Gems/AWSClientAuth/Code/CMakeLists.txt
- Gems/AWSCore/Code/CMakeLists.txt
- Gems/AWSGameLift/Code/AWSGameLiftClient/CMakeLists.txt
- Gems/AWSMetrics/Code/CMakeLists.txt
Update AWS Gems cmake target with correct runtime dependencies
Local tested
> [SPEC-7868] Update AWS Gems cmake target with correct runtime dependencies

- Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/std/parallel/internal/thread_WinAPI.cpp
- Code/Framework/AzCore/Platform/Windows/AzCore/std/parallel/internal/thread_Windows.cpp
- Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/Device_Windows.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI/Device.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI/PipelineLibrary.cpp
> More PAL related changes required for restricted platforms.

- AutomatedTesting/Gem/PythonTests/AWS/README.md
- AutomatedTesting/Gem/PythonTests/AWS/Windows/aws_metrics/aws_metrics_automation_test.py
- scripts/build/Platform/Windows/build_config.json
- scripts/build/Platform/Windows/destroy_cdk_applications.cmd
Signed-off-by: junbo <junbo@amazon.com>
Verified the script locally. Couldn't verify it on Jenkins since the Jenkins parameters are only defined for nightly build. Will work with Shirang and SDETs to create a new test suite to run AWSI automation tests.
> [AWS Automation] Stack tear down mechanism for the deployment on Jenkins

- AutomatedTesting/Gem/PythonTests/scripting/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
- AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Sandbox.py
> Marking script canvas failing tests as xfail until they can be reworked to make them pass.

- Gems/Terrain/Code/Tests/TerrainMocks.h
> Change shape type in test mock plus bugfix.

- cmake/OutputDirectory.cmake
> Detects that binary dir and install prefix are not the same

- Gems/Atom/Asset/Shader/Code/Source/Editor/AzslCompiler.cpp
- Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderAssetBuilder.cpp
- Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderBuilderUtility.cpp
- Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderVariantAssetBuilder.cpp
- Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Common/JsonUtils.h
- Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilder.cpp
- Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialSourceDataSerializer.cpp
- Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialUtils.cpp
- Gems/AtomLyIntegration/AtomBridge/Code/Source/Editor/AssetCollectionAsyncLoaderTestComponent.cpp
Addressing a rename comment on PR https://github.com/o3de/o3de/pull/3999
Renamed AtomMaxFileSize to DefaultMaxFileSize
> Renamed AtomMaxFileSize to DefaultMaxFileSize

- AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/test_DistanceBetweenFilter.py
Signed-off-by: jckand-amzn <jckand@amazon.com>
> Marking DistanceBetweenFilter tests with xfail due to Editor deadlock

- Gems/EMotionFX/Code/EMotionFX/Source/Recorder.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/Recorder.h
> Fixed the crash by clear out the item and map array

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterWindow.cpp
> Animation Editor: Closing the Create Group window creates a new Parameter Group

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ComponentEditor.cpp
- Gems/PhysX/Code/Include/PhysX/EditorColliderComponentRequestBus.h
- Gems/PhysX/Code/Source/EditorColliderComponent.cpp
- Gems/PhysX/Code/Source/EditorColliderComponent.h
- Gems/PhysX/Code/Source/EditorRigidBodyComponent.cpp
Signed-off-by: aaguilea <aaguilea@amazon.com>
> Warning System Changes (polish) Redo

- Gems/EMotionFX/Code/EMotionFX/CommandSystem/Source/AnimGraphCommands.cpp
> Clear the recorder when deactivating the anim graph.

- Code/Editor/Core/QtEditorApplication_linux.cpp
- Code/Framework/AzFramework/Platform/Linux/AzFramework/Input/Devices/Keyboard/InputDeviceKeyboard_xcb.cpp
- Code/Framework/AzFramework/Platform/Linux/AzFramework/Windowing/NativeWindow_Linux_xcb.cpp
- Code/Framework/AzFramework/Platform/Linux/platform_linux.cmake
- Code/Framework/AzFramework/Platform/Linux/platform_linux_files.cmake
- scripts/build/build_node/Platform/Linux/package-list.ubuntu-focal.txt
> Add support for keyboard events from xcb on Linux

- Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
Instanced the RayTracingBLAS objects to enable re-use when the same model is added multiple times.
> Instance the ray tracing BLAS objects

- scripts/build/Platform/Windows/build_config.json
Utilizes the new domain for all installation packages and license files for the installer
> Change installer domain to o3debinaries.org

- Gems/Multiplayer/Code/Tests/ClientHierarchyTests.cpp
- Gems/Multiplayer/Code/Tests/ServerHierarchyTests.cpp
Fixes for LYN-6883 and LYN-6884
Signed-off-by: AMZN-Olex <5432499+AMZN-Olex@users.noreply.github.com>
> Debug build clang fixes for Multiplayer.Tests

- Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
> Instance BLAS objects at the subMesh level in the RayTracingFeatureProcessor

- Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Common.jinja
> Fix AutoGen of RPCs with no params

- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/fbx_tests.py
PR to enable FBX_Tests on Sandbox
> Signed-off-by: LesaelR <LesaelR@amazon.com>

- cmake/Platform/Mac/InstallUtils_mac.cmake.in
> [Mac] Set working directory to the install directory so that cmake can find includes in the engine root's cmake directory.

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/Method.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/Method.h
Remove false error for lookup on methods, that occurs during (de)serialization
> Remove false error for lookup on methods

- Gems/AWSMetrics/cdk/aws_metrics/batch_analytics.py
Signed-off-by: Junbo Liang <junbo@amazon.com>
Verified that the CDK application for the Metrics gem could be deployed successfully
> [AWSMetrics][cdk] Add the athena work group as a dependency of named queries

- scripts/build/Platform/Linux/build_config.json
- scripts/build/Platform/Mac/build_config.json
> Updated Linux and Mac configs to show test results.

- Gems/PhysX/Code/Source/EditorShapeColliderComponent.cpp
- Gems/PhysX/Code/Source/EditorShapeColliderComponent.h
Removed redundant code following advice from Sean Cove.
> Removed redundant code

- Tools/LyTestTools/tests/CMakeLists.txt
- Tools/LyTestTools/tests/integ/test_process_utils_linux.py
Adds an integ test for process_utils on Linux. Tested by executing the test manually on a Linux EC2.
> Linux integ test

- Code/Framework/AzNetworking/AzNetworking/Framework/NetworkingSystemComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/FocusMode/FocusModeInterface.h
- Gems/Multiplayer/Code/Source/Components/NetworkCharacterComponent.cpp
> Added missing EntityId.h include to FocusModeInterface.h

- Gems/EMotionFX/Code/EMotionFX/Source/MotionSet.cpp
> Animation Editor: Creating Motion Sets does not increment them correctly

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserFilterModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetPicker/AssetPickerDialog.cpp
Signed-off-by: igarri <igarri@amazon.com>
> Flipped CVar to activate AssetBrowser Search View changes

- Code/Framework/AzNetworking/AzNetworking/DataStructures/FixedSizeBitsetView.inl
- Code/Framework/AzNetworking/Tests/DataStructures/FixedSizeBitsetTests.cpp
- Code/Framework/AzNetworking/Tests/DataStructures/FixedSizeBitsetViewTests.cpp
- Code/Framework/AzNetworking/Tests/TcpTransport/TcpTransportTests.cpp
- Code/Framework/AzNetworking/Tests/UdpTransport/UdpTransportTests.cpp
- Code/Framework/AzNetworking/Tests/Utilities/IpAddressTests.cpp
- Code/Framework/AzNetworking/Tests/Utilities/QuantizedValuesTests.cpp
Some minor updates to expand test coverage. Updated FixedSizeBitsetView Asserts to Warns since they failure cases can be handled by the user.
> Quick updates to AzNetworking unit tests

- Code/Framework/AzTest/AzTest/Platform/Common/Unimplemented/Platform_Unimplemented.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Shader/Metrics/ShaderMetricsSystem.cpp
Put the ShaderMetrics.json in the @user@ folder, plus an unrelated #include path fix.
> Put the ShaderMetrics.json in the @user@ folder.

- Code/Framework/AzCore/AzCore/Math/Vector2.h
- Code/Framework/AzCore/AzCore/Math/Vector2.inl
- Code/Framework/AzCore/AzCore/Math/Vector3.h
- Code/Framework/AzCore/AzCore/Math/Vector3.inl
- Code/Framework/AzCore/AzCore/Math/Vector4.h
- Code/Framework/AzCore/AzCore/Math/Vector4.inl
https://github.com/o3de/o3de/issues/4216
> Added Floor, Ceil, and Round functions to AZ::Vector2/3/4

- Templates/DefaultProject/Template/project.json
- Templates/MinimalProject/Template/project.json
> Added the "external_subdirectories" array object to the Project Templates

- Code/Framework/AzToolsFramework/AzToolsFramework/Archive/ArchiveComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.cpp
- Gems/AtomTressFX/Code/Assets/HairAsset.h
- Gems/AtomTressFX/Code/Rendering/HairCommon.cpp
- Gems/AtomTressFX/Code/Rendering/HairFeatureProcessor.cpp
- Gems/AtomTressFX/Code/Rendering/HairRenderObject.cpp
- Gems/AtomTressFX/External/Code/src/TressFX/TressFXAsset.cpp
- Gems/AtomTressFX/External/Code/src/TressFX/TressFXSettings.cpp
- Fix unused release warnings
- Fixed compile errors from missing includes
- Commented out missing AZ_ATOM_PROFILE_FUNCTION macro
> Fix release build errors on Linux/Mac

- Code/Framework/AzCore/AzCore/IO/SystemFile.cpp
- Code/Framework/AzCore/AzCore/IO/SystemFile.h
- Code/Framework/AzCore/Platform/Android/AzCore/IO/SystemFile_Android.cpp
- Code/Framework/AzCore/Platform/Common/UnixLikeDefault/AzCore/IO/SystemFile_UnixLikeDefault.cpp
- Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/IO/SystemFile_WinAPI.cpp
- Code/Framework/AzFramework/AzFramework/IO/LocalFileIO.cpp
- Code/Framework/AzFramework/Platform/Android/AzFramework/IO/LocalFileIO_Android.cpp
- Code/Framework/AzFramework/Platform/Common/UnixLike/AzFramework/IO/LocalFileIO_UnixLike.cpp
- Code/Framework/AzFramework/Platform/Common/WinAPI/AzFramework/IO/LocalFileIO_WinAPI.cpp
- Code/Framework/AzFramework/Tests/FileIO.cpp
- Code/Framework/AzTest/AzTest/Printers.cpp
- Code/Framework/AzTest/AzTest/Printers.h
- Code/Framework/AzTest/AzTest/Printers.inl
- Code/Framework/AzTest/AzTest/Utils.h
- Code/Framework/AzTest/AzTest/aztest_files.cmake
This takes the implementation in LocalFileIO and uses it for SystemFile
and then just has LocalFileIO call the SystemFile implementation
> Added IsDirectory function to SystemFile

- Gems/Multiplayer/Code/Tests/CommonBenchmarkSetup.h
Updated test code to the latest network code.
> [SIG-Network] Development build fix for test code

- AutomatedTesting/Config/shader_global_build_options.json
- AutomatedTesting/Gem/Code/enabled_gems.cmake
- AutomatedTesting/Registry/assets_scan_folders.setreg
- Gems/AtomTressFX/Assets/Shaders/HairLightingEquations.azsli
- Gems/AtomTressFX/Code/Passes/HairPPLLResolvePass.cpp
- Gems/AtomTressFX/Code/Rendering/HairFeatureProcessor.cpp
- Gems/AtomTressFX/Code/Rendering/HairGlobalSettings.cpp
- Gems/AtomTressFX/Code/Rendering/HairGlobalSettings.h
Signed-off-by: Adi-Amazon <barlev@amazon.com>
> Hair - Adding the Hair Gem to the automated testing

- Code/Framework/AzFramework/AzFramework/Input/Mappings/InputMappingAnd.cpp
- Code/Framework/AzFramework/AzFramework/Input/Mappings/InputMappingOr.cpp
> Auto-expand input mappings.

- Code/Editor/EditorModularViewportCameraComposer.cpp
- Code/Editor/EditorModularViewportCameraComposer.h
- Code/Editor/EditorPreferencesPageViewportCamera.cpp
- Code/Editor/EditorPreferencesPageViewportCamera.h
- Code/Editor/EditorViewportSettings.cpp
- Code/Editor/EditorViewportSettings.h
- Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp
- Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.h
I'm going to aim to add some tests to this later this afternoon but wanted to get to this posted as I think it will be helpful for @amzn-rhhong with the EMFX camera work.
> Add focus camera and custom camera input

- scripts/build/Jenkins/Jenkinsfile
Merge "mars pipeline" SNS topic and "create github issue" SNS topic to one "post ar build" SNS topic which will be used to handle events after a build finished.
Signed-off-by: shiranj <shiranj@amazon.com>
> Send message to post_ar_build SNS topic after build finished

- Code/Tools/Standalone/CMakeLists.txt
> Makes Editor depend on LuaIDE

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/AbstractCodeModel.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Results/ErrorText.h
- Gems/ScriptCanvasTesting/Assets/ScriptCanvas/UnitTests/LY_SC_UnitTest_MultipleOut.scriptcanvas
- Gems/ScriptCanvasTesting/Code/Tests/ScriptCanvas_RuntimeInterpreted.cpp
> fix for late compilation errors on untyped input

- Code/Tools/ProjectManager/Resources/ProjectManager.qss
- Code/Tools/ProjectManager/Source/EngineSettingsScreen.cpp
- Code/Tools/ProjectManager/Source/EngineSettingsScreen.h
- Code/Tools/ProjectManager/Source/FormBrowseEditWidget.cpp
- Code/Tools/ProjectManager/Source/FormBrowseEditWidget.h
- Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
- Code/Tools/ProjectManager/Source/GemCatalog/GemModel.cpp
- Code/Tools/ProjectManager/Source/UpdateProjectSettingsScreen.cpp
> Integrate gem catalog refresh crash fix (#5112)

- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassLibrary.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassSystem.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassSystemInterface.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassLibrary.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassSystem.cpp
Signed-off-by: garrieta <garrieta@amazon.com>
> Added "RemovePassTemplate" method.

- cmake/Platform/Common/Install_common.cmake
- cmake/Platform/Mac/Install_mac.cmake
> Corrects mistake naming the override commands

- scripts/build/Jenkins/Jenkinsfile
Signed-off-by: shiranj <shiranj@amazon.com>
> Fix typo when calling upload_to_s3.py

- cmake/Platform/Common/Install_common.cmake
> Missed escaping these variables and breaks runtime dependencines in install

- scripts/build/Jenkins/Jenkinsfile
> Update snapshots list to stablization/2110

- Code/Framework/AzCore/AzCore/Script/ScriptSystemComponent.cpp
- Gems/Atom/Feature/Common/Code/Source/EditorCommonSystemComponent.cpp
- Gems/LmbrCentral/Code/Source/LmbrCentral.cpp
> Removing redundant registration of script assets

- Code/Framework/AzFramework/AzFramework/Matchmaking/IMatchmakingRequests.h
- Code/Framework/AzFramework/AzFramework/Matchmaking/MatchmakingNotifications.h
- Code/Framework/AzFramework/AzFramework/Matchmaking/MatchmakingRequests.h
- Code/Framework/AzFramework/AzFramework/Session/ISessionHandlingRequests.h
- Code/Framework/AzFramework/AzFramework/Session/ISessionRequests.h
- Code/Framework/AzFramework/AzFramework/Session/SessionConfig.h
- Code/Framework/AzFramework/AzFramework/Session/SessionNotifications.h
- Code/Framework/AzFramework/AzFramework/Session/SessionRequests.h
- Gems/AWSGameLift/Code/AWSGameLiftClient/Include/Request/AWSGameLiftCreateSessionOnQueueRequest.h
- Gems/AWSGameLift/Code/AWSGameLiftClient/Include/Request/AWSGameLiftCreateSessionRequest.h
- Gems/AWSGameLift/Code/AWSGameLiftClient/Include/Request/AWSGameLiftSearchSessionsRequest.h
- Gems/AWSGameLift/Code/AWSGameLiftClient/Include/Request/AWSGameLiftStartMatchmakingRequest.h
Autogen API documentation is missing description for session and matchmaking interfaces, see https://docs.o3de.org/docs/api/frameworks/azframework/struct_az_framework_1_1_create_session_request.html
> Add missing exclamation mark for documentation

- cmake/Platform/Common/Install_common.cmake
- cmake/Platform/Linux/Install_linux.cmake
- cmake/Platform/Mac/Install_mac.cmake
Closes #5181 (fixes development's installer)
> Copy commands need to be per permutation/per configuration

- Gems/Terrain/Assets/Shaders/Terrain/TerrainPBR_ForwardPass.azsl
- Gems/Terrain/Code/Source/TerrainRenderer/Components/TerrainMacroMaterialComponent.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.h
Fixing some warnings, some potential bugs, and removing some shader code that's no longer needed.
> Terrain macro material fixes

- Code/Framework/AzCore/AzCore/Utils/Utils.cpp
> Fixed the return value of the ConvertToAbsolutePath function

- Code/Editor/EditorViewportWidget.cpp
- Gems/Camera/Code/Source/CameraEditorSystemComponent.cpp
(changed to stabilization branch)
https://github.com/o3de/o3de/issues/4463
> No longer can create camera in an empty level

- AutomatedTesting/Passes/MainPipeline.pass
- Gems/AtomTressFX/Code/Rendering/HairFeatureProcessor.h
> AutomatedTesting - adding Hair to MainPipeline

- Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
Original change (https://github.com/o3de/o3de/pull/5193) went to development by mistake, should have been submitted to stabilization. Cherry-picking so that it's in the GA build.
> CHERRYPICK - LYN-7547 | Focus Mode - It is possible to create a child entity of a closed container

- README.md
> Update README.md CMake link and instructions

- Code/Tools/GridHub/CMakeLists.txt
> Adds LuaIDE->GridHub dependency

- scripts/build/Platform/Linux/build_config.json
- scripts/build/Platform/Linux/pipeline.json
> [Linux] Update Jenkins Linux build to use Ubuntu 20, clang 12

- cmake/LYWrappers.cmake
- cmake/Platform/Common/Install_common.cmake
- cmake/install/Findo3de.cmake.in
Solves the TIFF:TIFF issue in the game jam installer (was fixed in stabilization and development, this is a cherry-pick from stabilization)
> installer fixes for game jam

- AutomatedTesting/Gem/Code/Source/AutomatedTestingSystemComponent.cpp
Tested Editor with AutomatedTesting project
Signed-off-by: AMZN-Olex <5432499+AMZN-Olex@users.noreply.github.com>
> Correcting system requirements for the startup

- Gems/GraphCanvas/Code/Source/Translation/TranslationBuilder.cpp
> Fix material editor crash on shutdown if graph canvas gem is loaded

- Code/Editor/CryEdit.cpp
- Code/Editor/CryEditDoc.cpp
- Code/Legacy/CryCommon/ISystem.h
- Code/Legacy/CryCommon/Mocks/ISystemMock.h
- Code/Legacy/CrySystem/System.cpp
- Code/Legacy/CrySystem/System.h
- Code/Legacy/CrySystem/SystemInit.cpp
> Removes VTUNE profiler hooks from Cry

- Code/Framework/AzFramework/Platform/Windows/AzFramework/Windowing/NativeWindow_Windows.cpp
- Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/SwapChain_Windows.cpp
> Fix alt-tabbing out of full screen on Windows.

- cmake/Platform/Common/MSVC/Configurations_msvc.cmake
> Fixes for CMake 3.22rc

- Gems/AWSGameLift/cdk/aws_gamelift/fleet_configurations.py
> Fix minor repeated AMAZON_LINUX in the code comment

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DiskLightDelegate.cpp
> SpotLight debug draw to include display cone

- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
Fix test thread being created multiple times
(cherry picked from commit 73202c209152645a304702f6c7e8d984ebd51dd4)
> [LYN-7245] Cherry Pick - Fix test thread being created multiple times

- Code/Framework/AzFramework/Platform/Mac/AzFramework/Asset/AssetSystemComponentHelper_Mac.cpp
- Code/Tools/BundleLauncher/O3DE_SDK_Launcher.cpp
- Code/Tools/ProjectManager/Platform/Linux/ProjectUtils_linux.cpp
- Code/Tools/ProjectManager/Platform/Mac/ProjectUtils_mac.cpp
- Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp
- Code/Tools/ProjectManager/Source/ProjectUtils.h
- Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
Bringing https://github.com/o3de/o3de/pull/5264 to stabilization
> [MacOS] Launching Editor from ProjectManager and other misc. fixes

- Gems/Terrain/Code/Source/Components/TerrainWorldDebuggerComponent.cpp
If a terrain layer spawner went outside the world bounds, the debug wireframe wouldn't update correctly because the heights were outside the wireframe sector AABBs.  Adjusted the logic to account for this.
> Fix terrain wireframe refresh.

- AutomatedTesting/Gem/PythonTests/NvCloth/tests/NvCloth_AddClothSimulationToActor.py
- AutomatedTesting/Gem/PythonTests/NvCloth/tests/NvCloth_AddClothSimulationToMesh.py
> Cloth automated tests only check for cloth gem errors and warnings

- Code/Tools/ProjectManager/Source/GemCatalog/GemInspector.cpp
- Code/Tools/ProjectManager/Source/PythonBindings.cpp
(Info not accurate but a demonstration of it being displayed)
> Fix Additional Gem Info Handling and Display

- Gems/AtomContent/ReferenceMaterials/Tools/Launch_Cmd.bat
- Gems/AtomContent/ReferenceMaterials/Tools/Launch_Maya.bat
- Gems/AtomContent/ReferenceMaterials/Tools/Project_Env.bat
- Gems/AtomContent/Sponza/Tools/Launch_Cmd.bat
- Gems/AtomContent/Sponza/Tools/Launch_Maya.bat
- Gems/AtomContent/Sponza/Tools/Project_Env.bat
- Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Env_Maya.bat
Signed-off-by: Jonny Gallowy <gallowj@amazon.com>
> Fixed .bat chain for launching maya for AtomContent gems

- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.cpp
> Non MSVC Release build fix

- Gems/EMotionFX/Code/Source/Editor/PropertyWidgets/BlendSpaceMotionContainerHandler.cpp
> EMotion FX: Fix for the Y motion coordinate not being editable in blend space nodes

- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPISystem.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RenderPipeline.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Scene.h
- Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/RenderPipeline.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
Merge pull request #4426 from aws-lumberyard-dev/Atom/santorac/FixSceneSrgTime
> Cherrypick: Fixed potential render scene time precision issues

- scripts/build/Platform/Linux/build_config.json
- scripts/build/build_node/Platform/Linux/package-list.ubuntu-bionic.txt
> Some fixes for clang-12

- Gems/Atom/RHI/Code/Include/Atom/RHI/SwapChain.h
- Gems/Atom/RHI/Code/Source/RHI/FrameGraphAttachmentDatabase.cpp
- Gems/Atom/RHI/Code/Source/RHI/SwapChain.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.h
Move swapchain and image recreation to the end of the frame
> ATOM-16749 [Linux] UI Editor viewport flashes after dragging

- scripts/build/Jenkins/Jenkinsfile
Merging https://github.com/o3de/o3de/pull/5450 from stabilization/2110 to development
> Remove timeout in the mount step

- Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.h
> Adding missing pragma once at XcbInputDeviceMouse.h

- Gems/Terrain/Assets/Shaders/Terrain/TerrainCommon.azsli
https://github.com/o3de/o3de/issues/5461
> Adding m_exposure field to terrain's object srg to sync it with the default object srg

- Gems/AWSClientAuth/gem.json
- Gems/AWSCore/gem.json
- Gems/AWSGameLift/gem.json
- Gems/AWSMetrics/gem.json
Following AudioEngineWwise as an example
Signed-off-by: liug <liug@amazon.com>
> Update AWS gem info content

- Gems/Terrain/Code/Source/TerrainRenderer/Components/TerrainSurfaceMaterialsListComponent.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/Components/TerrainSurfaceMaterialsListComponent.h
> Various bug fixes.

- Code/Editor/LyViewPaneNames.h
- Code/Editor/MainWindow.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MorphTargetsWindow/MorphTargetGroupWidget.cpp
> Animation Editor: Remove preview label

- scripts/build/Jenkins/Jenkinsfile
Signed-off-by: shiranj <shiranj@amazon.com>
> Merge Jenkinsfile from development to stabilization

- Gems/Terrain/Code/Tests/LayerSpawnerTests.cpp
> Add missing shape failure test, tidying up.

- scripts/o3de/o3de/utils.py
Use the correct deleting file function (we checked that the path is a file previously)
> Fix trying to remove a cache file

- Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.cpp
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassFilter.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassFilter.cpp
> Fixed a typo with pass filter

- Gems/EditorPythonBindings/Code/Source/PythonLogSymbolsComponent.cpp
- Gems/EditorPythonBindings/Code/Source/PythonProxyObject.cpp
{lyn3736} adding init files to module paths
* fixing class names in PYI files
Signed-off-by: jackalbe <23512001+jackalbe@users.noreply.github.com>
> {lyn3736} adding init files to module paths

- Gems/PhysX/Code/Source/Joint/PhysXJointUtils.cpp
- Gems/PhysX/Code/Source/Joint/PhysXJointUtils.h
> prevent twist limits being created with equal lower and upper limits

- Gems/StartingPointCamera/Code/Include/StartingPointCamera/StartingPointCameraConstants.h
- Gems/StartingPointCamera/Code/Include/StartingPointCamera/StartingPointCameraUtilities.h
- Gems/StartingPointCamera/Code/Source/CameraLookAtBehaviors/SlideAlongAxisBasedOnAngle.cpp
- Gems/StartingPointCamera/Code/Source/CameraLookAtBehaviors/SlideAlongAxisBasedOnAngle.h
- Gems/StartingPointCamera/Code/Source/StartingPointCamera/StartingPointCameraUtilities.cpp
fixes #3959 
Also after a discussion on the issue's thread we ended up switching from a Dropdown to individual CheckBoxes for each vector component.
> Entering the Game Mode when the SlideAlongAxisBasedOnAngle in the Camera Rig is set results in an assert

- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
Removed `SurfaceManipulator` while a fix for LYN-7989 "Fix SurfaceManipulator to handle there not being Terrain" is being explored.
> Remove SurfaceManipulator.

- Gems/Terrain/Code/Tests/TerrainHeightGradientListTests.cpp
- Gems/Terrain/Code/Tests/TerrainSurfaceGradientListTests.cpp
> Redoing tests that got lost when TerrainPhysicsManager was merged.

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRequestBus.h
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportToolBar.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportToolBar.h
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.h
https://user-images.githubusercontent.com/69218254/141227262-32b8bd0f-6841-4d2a-b532-bdd3d5843e90.mp4
> Follow character option

- Code/Framework/AzCore/AzCore/Name/NameDictionary.cpp
Fixed the other call to CreateVariable
> Fixed the other call to CreateVariable

- Code/Editor/Lib/Tests/test_TrackViewPythonBindings.cpp
> TrackView Fixture now disables save on finalize

- cmake/Platform/Common/MSVC/Configurations_msvc.cmake
```
git cherry-pick 5a3cd96eab655260f494daca914e91e8bc492725
```
Relates to https://github.com/o3de/o3de/pull/5314
> Cherry-pick PR#5314: "Fixes for CMake 3.22rc" to stabilization/2110

- cmake/Platform/Common/Install_common.cmake
Closes https://github.com/o3de/o3de/issues/5559
> Private dependencies are not propagated to other targets in generated install layout

- Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
Fixing RPC autogen so that RPCs without parameters compile (and function).
> RPCs Without Parameters Compile

- Gems/Atom/RHI/Code/Include/Atom/RHI/CommandQueue.h
- Gems/Atom/RHI/Code/Source/RHI/CommandQueue.cpp
> Remove CPU Spin lock to help conserve power/perf

- Code/Framework/AzToolsFramework/AzToolsFramework/Component/EditorComponentAPIComponent.cpp
This fix makes SetComponentProperty work with prefab system
> SetComponentProperty is now supported by undo operation

- Code/Framework/AzCore/AzCore/Serialization/Json/JsonSystemComponent.cpp
- Code/Framework/AzCore/AzCore/Serialization/Json/UnsupportedTypesSerializer.cpp
- Code/Framework/AzCore/AzCore/Serialization/Json/UnsupportedTypesSerializer.h
> Add message to indicate Json serialization of bitset is not supported

- Code/Framework/AzCore/AzCore/Asset/AssetCommon.h
Fix AssetBus connection policy to re-lock the mutex afterwards since some destructors in the calling methods are still altering the context
Also made the unlock conditional.
> Fix AssetBus connection policy to re-lock the mutex afterward

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
> Bugfix - Render normal is incomplete when multiple mesh present.

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetPicker/AssetPickerDialog.cpp
Signed-off-by: AMZN-Igarri <82394219+AMZN-Igarri@users.noreply.github.com>
> Revert Asset Picker View to previous one

- Gems/Atom/Feature/Common/Editor/Scripts/ColorGrading/__init__.py
- Gems/Atom/Feature/Common/Editor/Scripts/ColorGrading/capture_displaymapper.py
- Gems/Atom/Feature/Common/Editor/Scripts/ColorGrading/initialize.py
- Gems/Atom/Feature/Common/Tools/ColorGrading/cmdline/CMD_ColorGradingTools.bat
- Gems/Atom/Feature/Common/Tools/ColorGrading/cmdline/Env_Python.bat
- Gems/Atom/Feature/Common/Tools/ColorGrading/cmdline/User_Env.bat.template
Addresses the following: https://github.com/o3de/o3de/issues/5654
(AMZN Jira ATOM-16694)
> upgraded capture_displaymapper util and some cleanup

- Gems/AWSCore/cdk/README.md
- Gems/AWSCore/cdk/core/core_stack.py
- Gems/AWSCore/cdk/example/example_resources_stack.py
- scripts/build/Platform/Windows/deploy_cdk_applications.cmd
* Add option to cleanup resources that are retained by default (Merged from https://github.com/o3de/o3de/pull/5470)
> AWS Core CDK: Add option to cleanup resources that are retained by default (#5470)

- cmake/SettingsRegistry.cmake
Adds a runtime cycle dependency check. Example of an output:
```
CMake Error at E:/o3de/o3de/install/cmake/SettingsRegistry.cmake:74 (message):
Runtime dependency detected: Multiplayer.Tools --> Multiplayer.Builders*
--> Multiplayer.Editor --> Multiplayer.Builders*
Call Stack (most recent call first):
E:/o3de/o3de/install/cmake/SettingsRegistry.cmake:93 (ly_get_gem_load_dependencies)
E:/o3de/o3de/install/cmake/SettingsRegistry.cmake:93 (ly_get_gem_load_dependencies)
E:/o3de/o3de/install/cmake/SettingsRegistry.cmake:93 (ly_get_gem_load_dependencies)
E:/o3de/o3de/install/cmake/SettingsRegistry.cmake:167 (ly_get_gem_load_dependencies)
E:/o3de/o3de/install/CMakeLists.txt:117 (ly_delayed_generate_settings_registry)
```
Relates to https://github.com/o3de/o3de/issues/5611
> Detects runtime dependency cycles

- Code/Legacy/CrySystem/SystemInit.cpp
- Code/Tools/AWSNativeSDKInit/CMakeLists.txt
- Code/Tools/AWSNativeSDKInit/aws_native_sdk_init_tests_files.cmake
- Code/Tools/AWSNativeSDKInit/source/AWSLogSystemInterface.cpp
- Code/Tools/AWSNativeSDKInit/source/AWSNativeSDKInit.cpp
- Code/Tools/AWSNativeSDKInit/tests/AWSLogSystemInterfaceTest.cpp
- Code/Tools/AWSNativeSDKInit/tests/AWSNativeSDKInitTest.cpp
- Gems/AWSClientAuth/Code/Tests/Authorization/AWSCognitoAuthorizationControllerTest.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/CMakeLists.txt
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/AWSGameLiftClientManager.cpp
##Testing
Manual tested and pass unit test
> Add cvar for aws log level

- AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/hydra_editor_utils.py
- Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp
> Add support for getting the level entity when prefabs are enabled.

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/RenderPlugin/RenderOptions.cpp
> render solid skeleton option

- AutomatedTesting/Gem/PythonTests/Terrain/EditorScripts/TerrainPhysicsCollider_ChangesSizeWithAxisAlignedBoxShapeChanges.py
- AutomatedTesting/Gem/PythonTests/Terrain/EditorScripts/Terrain_SupportsPhysics.py
- AutomatedTesting/Gem/PythonTests/Terrain/TestSuite_Main.py
- AutomatedTesting/Levels/Base/Base.prefab
> Terrain Supports Physics test

- Code/Framework/AzCore/AzCore/Asset/AssetCommon.h
Fix AssetBus connection policy to re-lock the mutex afterward since some destructors in the calling methods are still altering the context (#5575)
Also made the unlock conditional.
(cherry picked from commit 63713ca284cb8ed9bd0720359805c92bf2badb13)
> Cherry Pick - Fix asset bus connection policy

- Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/NewDepthOfFieldTileReduce.azsl
> Fix DOF flickering on Vk due to missing LDS sync

- Gems/Atom/Tools/AtomToolsFramework/Code/Tests/ViewportInteractionImplTests.cpp
This is a follow-up PR from https://github.com/o3de/o3de/pull/5719 to add a test to validate the new functionality.
It would have been nice to test more things, but currently it's impossible to instantiate `ViewportContextManager` in a test on its own. We hopefully will be able to add more tests in future 🙂 
before (not listening to notification bus)
```
[----------] 1 test from ViewportInteractionImplFixture
[ RUN      ] ViewportInteractionImplFixture.ViewportInteractionRequestsReturnsNewViewWhenItIsChanged
D:/o3de/Gems/Atom/Tools/AtomToolsFramework/Code/Tests/ViewportInteractionImplTests.cpp(207): error: Value of: cameraTransform
Expected: is close
0.000000,   0.866025,  -0.500000, -50.000000, …
```
> Add test for ViewportInteractionImpl use of ViewportInteractionRequestBus

- AutomatedTesting/Gem/PythonTests/Terrain/EditorScripts/Terrain_SupportsPhysics.py
- AutomatedTesting/Gem/PythonTests/Terrain/TestSuite_Main.py
> Changes from comments made after merge

- Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/NewDepthOfFieldTileReduce.azsl
* Fix DOF flickering on Vk due to missing LDS sync
* Added another sync
> CherryPick (Dev to Stab) - Fix DOF flickering on Vk due to missing LDS sync (#5723)

- AutomatedTesting/Gem/PythonTests/editor/EditorScripts/AssetBrowser_SearchFiltering.py
- AutomatedTesting/Gem/PythonTests/editor/EditorScripts/AssetBrowser_TreeNavigation.py
- AutomatedTesting/Gem/PythonTests/editor/TestSuite_Main_Optimized.py
- AutomatedTesting/Gem/PythonTests/editor/TestSuite_Periodic.py
Signed-off-by: jckand-amzn <jckand@amazon.com>
> Updating AssetBrowser tests around new TableView model

- Gems/LmbrCentral/Code/Source/Scripting/TagComponent.cpp
https://github.com/o3de/o3de/issues/4060
> Renamed RequestTaggedEntities to Get Entity By Tag as it only returns the first entity

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportToolBar.cpp
> Disable option that are currently not available.

- scripts/o3de/o3de/download.py
- scripts/o3de/o3de/manifest.py
- scripts/o3de/o3de/print_registration.py
- scripts/o3de/o3de/register.py
- scripts/o3de/o3de/repo.py
- scripts/o3de/o3de/utils.py
> Change warn to warning to remove deprecation messages from Python

- Code/Tools/ProjectManager/Resources/Backgrounds/DefaultBackground.jpg
- Code/Tools/ProjectManager/Resources/Backgrounds/FtueBackground.jpg
Updated default and first-time backgrounds.
> Updated Project Manager backgrounds

- cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake
Update package hash for fixed pyside2 3P package
> Update package and hash for pyside2

- Gems/Multiplayer/Code/CMakeLists.txt
- Gems/Multiplayer/Code/Source/MultiplayerGem.cpp
- Gems/Multiplayer/Code/Source/MultiplayerToolsSystemComponent.cpp
- Gems/Multiplayer/Code/Source/MultiplayerToolsSystemComponent.h
- Gems/Multiplayer/Code/multiplayer_tools_files.cmake
+ Tested with clean empty project Cache folder
+ Resolves #5611
> Refactored away circular dependencies in Multiplayer gem cmake targets.

- scripts/o3de/o3de/manifest.py
- scripts/o3de/o3de/register.py
This behavior can be overridden using the --force option.
> Prevent updates to o3de_manifest.json if it is corrupted.

- Gems/Multiplayer/Code/CMakeLists.txt
- Gems/Multiplayer/Code/Source/MultiplayerGem.cpp
- Gems/Multiplayer/Code/Source/MultiplayerToolsSystemComponent.cpp
- Gems/Multiplayer/Code/Source/MultiplayerToolsSystemComponent.h
- Gems/Multiplayer/Code/multiplayer_tools_files.cmake
Merges PR 5707 that resolves #5611.
Previous accepted PR into dev: https://github.com/o3de/o3de/pull/5707
> Merges PR 5707 that resolves #5611 from dev to stab/2110.

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyVectorCtrl.hxx
- Gems/Terrain/Code/CMakeLists.txt
- Gems/Terrain/Code/Source/Components/TerrainWorldComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainWorldComponent.h
> Adds check to make sure that there are not too many samples created.

- Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialSourceData.cpp
- Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/MaterialAsset.cpp
> Updated material version warning messages to include the affected asset

- Gems/Prefab/PrefabBuilder/PrefabGroup/ProceduralAssetHandler.cpp
This adds the context menu to the Asset Browser to "Save as Prefab.." so that a Procedural Prefab
asset template can be saved in the source assets folder
> {lyn7060} adding 'Save as Prefab' for ProcPrefab

- Gems/Multiplayer/Code/CMakeLists.txt
- cmake/Platform/Common/Install_common.cmake
- cmake/Platform/Mac/Install_mac.cmake
- cmake/Version.cmake
- scripts/build/Platform/Windows/env_windows.cmd
- scripts/build/Platform/Windows/installer_windows.cmd
> Cherry-picking some changes from stabilization into development

- Gems/EMotionFX/Code/MCore/Source/Algorithms.cpp
- Gems/LyShine/Code/Source/Draw2d.cpp
- Gems/LyShine/Code/Source/UiTextComponent.cpp
- Gems/ScriptCanvas/Code/Editor/View/Widgets/DataTypePalette/DataTypePaletteModel.cpp
> Fix some compilation errors due to warnings of potentially returning initialized variables.

- Gems/PhysX/Code/Source/EditorColliderComponent.cpp
> Fix collider component validation function by checking if the asset is ready

- Code/Framework/AzToolsFramework/Platform/Linux/AzToolsFramework/API/PythonLoader_Linux.cpp
> Fixed unused variable warning in Release configuration in Linux.

- .github/ISSUE_TEMPLATE/ar_bug_report.md
Signed-off-by: mcphedar <mcphedar@amazon.com>
> Updating the name of the AR bug template

- Gems/Terrain/Code/Source/EditorComponents/EditorTerrainHeightGradientListComponent.h
- Gems/Terrain/Code/Source/EditorComponents/EditorTerrainLayerSpawnerComponent.h
- Gems/Terrain/Code/Source/EditorComponents/EditorTerrainSurfaceGradientListComponent.h
- Gems/Terrain/Code/Source/TerrainRenderer/EditorComponents/EditorTerrainSurfaceMaterialsListComponent.h
> Added missing doc links.

- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/BuilderSettingManager.cpp
- Gems/QtForPython/Code/Source/Platform/Linux/InitializeEmbeddedPyside2.h
> Fix unused variable errors

- Code/Framework/AzToolsFramework/Platform/Linux/AzToolsFramework/API/PythonLoader_Linux.cpp
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/BuilderSettingManager.cpp
- Gems/QtForPython/Code/Source/Platform/Linux/InitializeEmbeddedPyside2.h
Cherry-picking 2 fixes for unused-variable errors
https://github.com/o3de/o3de/pull/5830
https://github.com/o3de/o3de/pull/5843
> Cherry pick release unused warning error into Stabilization/2110

- scripts/build/Jenkins/Jenkinsfile
Don't fail the build when AP logs upload fails
> Don't fail the build when AP logs upload fails

- Code/Framework/AzQtComponents/AzQtComponents/Components/FancyDocking.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/FancyDockingDropZoneWidget.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BrowseEdit.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/Internal/OverlayWidgetLayer.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/Internal/OverlayWidgetLayer.h
added const to variables that should only have const access in AzQtComponent
> chore: update static const declerations in AzQtComponent

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.h
- Gems/EMotionFX/Code/EMotionFX/Source/JointSelectionBus.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/EMStudioManager.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/EMStudioManager.h
- Gems/EMotionFX/Code/EMotionFX/emotionfx_files.cmake
https://user-images.githubusercontent.com/69218254/142978002-c020a8aa-e33a-45d1-88ec-4863b294427e.mp4
> Add joint selection visual support

- AutomatedTesting/Gem/PythonTests/assetpipeline/ap_fixtures/ap_missing_dependency_fixture.py
- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/missing_dependency_tests.py
- AutomatedTesting/TestAssets/RelativeProductPathsNotDependencies.txt
- AutomatedTesting/TestAssets/RelativeSourcePathsNotDependencies.txt
- AutomatedTesting/TestAssets/ValidAssetIdNotDependency.txt
- AutomatedTesting/TestAssets/ValidUUIDsNotDependency.txt
Updated assert to print both lists sorted, to make it easier to compare and fix
> updated missing dependency tests to use assets that aren't deprecated

- Gems/GraphCanvas/Code/Source/Translation/TranslationBuilder.cpp
- Gems/ScriptCanvas/Assets/TranslationAssets/Classes/AWSGameLiftAcceptMatchRequest.names
- Gems/ScriptCanvas/Assets/TranslationAssets/Classes/AWSGameLiftCreateSessionOnQueueRequest.names
- Gems/ScriptCanvas/Assets/TranslationAssets/Classes/AWSGameLiftCreateSessionRequest.names
- Gems/ScriptCanvas/Assets/TranslationAssets/Classes/AWSGameLiftJoinSessionRequest.names
- Gems/ScriptCanvas/Assets/TranslationAssets/Classes/AWSGameLiftPlayer.names
- Gems/ScriptCanvas/Assets/TranslationAssets/Classes/AWSGameLiftSearchSessionsRequest.names
- Gems/ScriptCanvas/Assets/TranslationAssets/Classes/AWSGameLiftStartMatchmakingRequest.names
- Gems/ScriptCanvas/Assets/TranslationAssets/Classes/AWSGameLiftStopMatchmakingRequest.names
- Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/GeneralNodePaletteTreeItemTypes.h
- Gems/ScriptCanvas/Code/Editor/View/Widgets/ScriptCanvasNodePaletteDockWidget.cpp
- Gems/ScriptCanvas/Code/Tools/TranslationGeneration.cpp
> Updated GameLift names, improved Getter/Setter generation

- Gems/EMotionFX/Code/EMotionFX/Source/Motion.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/Motion.h
- Gems/EMotionFX/Code/EMotionFX/Source/MotionData/MotionData.h
- Gems/EMotionFX/Code/EMotionFX/Source/MotionData/MotionDataSampleSettings.h
- Gems/EMotionFX/Code/EMotionFX/Source/MotionData/NonUniformMotionData.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/MotionData/NonUniformMotionData.h
- Gems/EMotionFX/Code/EMotionFX/Source/MotionData/UniformMotionData.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/MotionData/UniformMotionData.h
- Gems/EMotionFX/Code/EMotionFX/emotionfx_files.cmake
> EMotion FX: Added helper to sample a pose from a motion without an motion instance

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTableModel.cpp
Fixes #5832
https://user-images.githubusercontent.com/82394219/143225399-2bc49b99-70ae-43eb-a7ee-0b2add6bd26a.mp4
> Fix: Connected filterChanged signal to update the Asset Browser Table Model properly

- Code/Framework/AzCore/AzCore/Console/ConsoleDataWrapper.inl
- Code/Framework/AzFramework/AzFramework/Windowing/NativeWindow.cpp
- Code/Framework/AzFramework/AzFramework/Windowing/NativeWindow.h
- Code/Framework/AzFramework/AzFramework/Windowing/WindowBus.h
- Code/Framework/AzFramework/Tests/Mocks/MockWindowRequests.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/RenderViewportWidget.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp
> Add a way to set the vsync_interval CVar from code

- Code/Tools/ProjectManager/Resources/ProjectManager.qss
- Code/Tools/ProjectManager/Source/ExternalLinkDialog.cpp
- Code/Tools/ProjectManager/Source/ExternalLinkDialog.h
- Code/Tools/ProjectManager/Source/GemCatalog/GemUninstallDialog.cpp
- Code/Tools/ProjectManager/Source/GemCatalog/GemUpdateDialog.cpp
- Code/Tools/ProjectManager/Source/LinkWidget.cpp
- Code/Tools/ProjectManager/Source/ProjectManagerSettings.cpp
- Code/Tools/ProjectManager/Source/ProjectManagerSettings.h
- Code/Tools/ProjectManager/project_manager_files.cmake
User can elect for dialog to never be shown again.
> Adds Warning Dialog When Following an External Link in Project Manager

- AutomatedTesting/Editor/Scripts/scene_mesh_to_prefab.py
- Gems/PythonAssetBuilder/Editor/Scripts/scene_api/scene_data.py
Added support for all the remaining mesh modifiers with documentation
Updated the example script to use most of these
> Procedural Prefabs - Add mesh modifier support

- cmake/Platform/Linux/Packaging/postrm.in
- cmake/Platform/Linux/Packaging/prerm.in
> Removes egg-info files from linux uninstall

- Gems/PhysX/Code/Editor/DebugDraw.cpp
> LYN-6430 Add debug draw for heightfields.

- Gems/AudioSystem/Code/Source/Engine/FileCacheManager.cpp
> Fix for bug cause by null pointer when loading audio library

- Gems/AudioSystem/Code/Source/Editor/ATLControlsPanel.cpp
> Fixed bug  when deleting event

- Gems/AudioEngineWwise/Code/Source/Editor/AudioSystemEditor_wwise.cpp
> Improvement to filter types

- Gems/LmbrCentral/Code/Source/Audio/AudioListenerComponent.cpp
Inappropriate data used to determine audio listener position
> Fix - Entity ID

- Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportRenderer.cpp
> Removing warnings from material editor viewport

- Gems/Atom/Feature/Common/Code/Source/ImGui/ImGuiPass.cpp
- Gems/Atom/Feature/Common/Code/Source/ImGui/ImGuiPass.h
- Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/DX12_Windows.h
- Gems/Atom/RHI/DX12/Code/Source/RHI/PipelineLayout.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingShaderTable.cpp
Also allow different D3D12_ROOT_SIGNATURE flags to be set for each platform.
> Fix debug ImGui asserts I introduced in [b2c13b2].

- Gems/AudioSystem/Code/Source/Editor/QSimpleAudioControlListWidget.cpp
> Fix for bug in switch group

- Code/Tools/ProjectManager/Source/ProjectButtonWidget.cpp
- Code/Tools/ProjectManager/Source/ProjectButtonWidget.h
> Right click menu support for project buttons

- Gems/PhysX/Code/Source/Pipeline/MeshGroup.cpp
- Registry/AssetProcessorPlatformConfig.setreg
Cherry picked from development: https://github.com/o3de/o3de/pull/6050
> Add additional check to check material library is loaded when trying to retrieve names

- Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.h
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabTestFixture.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabTestFixture.h
- Code/Framework/AzToolsFramework/Tests/TransformComponent.cpp
- Code/Framework/AzToolsFramework/Tests/UI/EntityOutlinerTests.cpp
Fixing PR to be based off of correct branch
> Fixing pivot offset when performing undo on Transform component

- Gems/Multiplayer/Code/Tests/CommonBenchmarkSetup.h
- Getting rid of GoogleTest warning spam in benchmark runs.
> Multiplayer benchmark cleanup

- Gems/GraphCanvas/Code/Source/Translation/TranslationSerializer.cpp
A handful of places in tight loops were looking up JSON and map entries multiple times in a row
Moving and reusing string variables in tight loops
Deferring string creation, copying, assignment until needed
> Optimizations to graph canvas translation json serializer

- AutomatedTesting/Assets/TestAnim/rin_skeleton.fbx
- AutomatedTesting/Assets/TestAnim/rin_skeleton.fbx.assetinfo
- AutomatedTesting/Assets/TestAnim/scene_export_actor.py
- Code/Tools/SceneAPI/SceneData/GraphData/BoneData.cpp
- Gems/PythonAssetBuilder/Editor/Scripts/scene_api/actor_group.py
- Gems/PythonAssetBuilder/Editor/Scripts/scene_api/physics_data.py
{lyn2264} Adding Python API for Actor Group
* updating the IBoneData with behavior attributes
* adding actor_group.py for making actor group JSON data
* adding physics_data.py for making physics JSON data
> {lyn2264} Adding Python API for Actor Group

- Gems/Blast/AssetProcessorGemConfig.setreg
- Registry/AssetProcessorPlatformConfig.setreg
Cherry picking https://github.com/o3de/o3de/pull/6205 from RTE branch to development.
> Fixed critical json property (cherry picked from RTE branch)

- Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
> Fix debug compilation.

- Gems/Atom/RHI/Code/Include/Atom/RHI/MemorySubAllocator.h
- Gems/Atom/RHI/DX12/Code/Source/RHI/MemoryView.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
> Fixes some missing includes/declaring budgets and if->ifdef

- Gems/LyShine/Code/Source/UiCanvasManager.cpp
> Fix assert in LyShine when unloading a level

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabAssetFixupTests.cpp
Addressing feedback from https://github.com/o3de/o3de/pull/6077#pullrequestreview-825750414
> Removing unused variable and fix typo

- scripts/build/Jenkins/Jenkinsfile
> Fix pipeline name passed to post ar build sns

- Gems/Atom/RHI/DX12/Code/Source/RHI/ShaderResourceGroupPool.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/ShaderResourceGroupPool.cpp
> Fixed SRG updated related crash

- Gems/ScriptCanvas/Code/Editor/Components/EditorScriptCanvasComponent.cpp
- Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorScriptCanvasComponent.h
- Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorScriptCanvasComponentSerializer.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Modifier.h
And add fail save for missing text in EditorSC component
> Fix missing asset handler error in AP when loading old SC files

- Code/Framework/AzFramework/Platform/iOS/AzFramework/Process/ProcessWatcher_iOS.cpp
> Fix namespace Az for AZ in ProcessWatcher for iOS

- Gems/Atom/RHI/Code/Source/RHI/ConstantsData.cpp
- Gems/Atom/RPI/Code/Tests/ShaderResourceGroup/ShaderResourceGroupConstantBufferTests.cpp
> Revert previous update to ConstantsData::SetConstantArray<bool> and fix unit tests

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
> Fixed nullptr error

- Gems/ScriptCanvas/Code/Editor/GraphCanvas/Components/NodeDescriptors/EBusHandlerEventNodeDescriptorComponent.cpp
> Fixed incorrect condition that led to badly named slots

- Gems/Atom/Feature/Common/Assets/Passes/DiffuseProbeGridRender.pass
Fix for DX12 spamming validation warnings every frame
> Fix for dx12 validation spam

- Code/Framework/AzCore/AzCore/Script/ScriptContextDebug.cpp
Lua script debugging completed results in Lua Editor loading problem
> Fix: Lua script debugging loading problem

- Code/Tools/ProjectManager/Platform/Windows/ProjectBuilderWorker_windows.cpp
> Add a missing comma to fix generator

- Gems/Atom/RHI/DX12/Code/Source/RHI/ShaderResourceGroupPool.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineState.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/ShaderResourceGroupPool.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/ShaderResourceGroupPool.cpp
2 PRs addressing this bug checked into dev are as follows 
https://github.com/o3de/o3de/pull/6315
https://github.com/o3de/o3de/pull/6317
> Rte fixes for stability

- Gems/ScriptCanvas/Code/Editor/Framework/ScriptCanvasGraphUtilities.inl
> [Mac] Fix build error in ScriptCanvas module

- Code/Framework/AzCore/AzCore/Memory/AllocationRecords.cpp
- Code/Framework/AzCore/AzCore/Memory/AllocatorBase.cpp
- Code/Framework/AzCore/AzCore/Memory/BestFitExternalMapAllocator.cpp
- Code/Framework/AzCore/AzCore/Memory/BestFitExternalMapAllocator.h
- Code/Framework/AzCore/AzCore/Memory/BestFitExternalMapSchema.cpp
- Code/Framework/AzCore/AzCore/Memory/BestFitExternalMapSchema.h
- Code/Framework/AzCore/AzCore/Memory/PoolSchema.cpp
- Code/Framework/AzCore/AzCore/Memory/PoolSchema.h
- Code/Framework/AzCore/AzCore/Memory/SystemAllocator.cpp
- Code/Framework/AzCore/AzCore/Memory/SystemAllocator.h
REF: https://github.com/o3de/o3de/issues/6281
> chore: remove "using namespace " from AZCore Memory

- Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderWorker.h
- Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderWorkerUtility.cpp
- Gems/ScriptCanvas/Code/Editor/Components/EditorScriptCanvasComponent.cpp
- Gems/ScriptCanvas/Code/Editor/Framework/ScriptCanvasGraphUtilities.inl
- Gems/ScriptCanvas/Code/Editor/Nodes/NodeDisplayUtils.cpp
- Gems/ScriptCanvas/Code/Editor/View/Widgets/ScriptCanvasNodePaletteDockWidget.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Asset/RuntimeAsset.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Asset/RuntimeAsset.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Asset/RuntimeAssetHandler.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Asset/SubgraphInterfaceAssetHandler.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Core.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Core.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/ExecutionContext.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/ExecutionState.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/Interpreted/ExecutionInterpretedAPI.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/Interpreted/ExecutionStateInterpreted.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/RuntimeComponent.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/FunctionCallNode.cpp
- Gems/ScriptCanvas/Code/Tests/ScriptCanvasBuilderTests.cpp
> Simplify structure of ScriptCanvas Asset data classes.

- Gems/WhiteBox/Code/CMakeLists.txt
- Gems/WhiteBox/gem.json
Fixes https://github.com/o3de/o3de/issues/6424
> Add EditorPythonBindings as an explicit dependency of the White Box Tool

- Gems/ScriptCanvas/Code/scriptcanvasgem_common_files.cmake
> remove uber build exceptions

- Code/Framework/AzCore/AzCore/Time/TimeSystem.cpp
- Code/Framework/AzCore/Tests/Time/TimeTests.cpp
> adding TimeSystem unit tests

- Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR.materialtype
- Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR_Anisotropy.lua
- Gems/Atom/Feature/Common/Assets/Materials/Types/Skin.materialtype
- Gems/Atom/Feature/Common/Assets/Materials/Types/Skin_SpecularF0.lua
- Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_ClearCoatState.lua
- Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_HandleOpacityMode.lua
> Hide the invalid parameters in the EnhancedPBR in the Material Editor

- Code/Tools/LuaIDE/Source/LUA/LUAEditorContext.cpp
the path is case sensitive under linux so this will fail if the path is lowered.
REF: https://github.com/o3de/o3de/issues/5899
> bugfix[Linux]: resolve Lua script file not found

- Gems/Atom/Asset/Shader/Code/Source/Editor/AzslShaderBuilderSystemComponent.cpp
- Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_DepthPass_WithPS.azsl
- Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_ForwardPass.azsl
- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Surfaces/BasePbrSurfaceData.azsli
- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Surfaces/StandardSurface.azsli
- Gems/Atom/RHI/Metal/Code/Source/RHI.Builders/ShaderPlatformInterface.cpp
Modify metal shader pipeline to pass the invariant along to msl.
> Add precise keyword to the depth and forward pass shaders. 

- Code/Framework/AzToolsFramework/AzToolsFramework/Slice/SliceUtilities.cpp
> Slice save path incorrect, and error message incomplete

- Gems/Atom/Feature/Common/Assets/Passes/DiffuseComposite.pass
- Gems/Atom/Feature/Common/Code/Source/CommonSystemComponent.cpp
- Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseCompositePass.cpp
- Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseCompositePass.h
- Gems/Atom/Feature/Common/Code/atom_feature_common_files.cmake
> Added pass class

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.cpp
Editor issue after clicking Find Layer in Asset Browser and find Slice in Asset Browser in Slice mode
> Editor bug using find layer

- Code/Framework/AzCore/AzCore/Math/IntersectSegment.cpp
- Code/Framework/AzCore/AzCore/Math/Sfmt.cpp
REF: https://github.com/o3de/o3de/issues/6281
> chore: remove "using namespace " from AZCore Math

- scripts/build/build_node/Platform/Linux/Dockerfile
This is the initial Dockerfile used for local development or for remote CI environments for Ubuntu. Build and test instructions are in the Dockerfile comments.
> Development dockerfile for Linux

- Gems/Terrain/Code/Source/Components/TerrainSurfaceDataSystemComponent.cpp
> Restore BusDisconnect() that got accidentally removed on a recent commit

- Code/Framework/AzCore/AzCore/Interface/Interface.h
In some cases, the interface being queried may be persistently nullptr
(e.g. a gem isn't active, or a feature was disabled by a cvar). In this
case, querying the interface would always enter the writer-lock branch
with existing code because nullptr was synonymous with "we haven't
queried for this variable yet."
This PR adds an additional state variable that is set when s_instance is
assigned to, so that after the variable is queried and found to be null,
future queries can enter the read-lock branch.
> Disambiguate null interface case

- Code/Framework/AzCore/AzCore/IO/Path/Path.h
- Code/Framework/AzCore/AzCore/IO/Path/Path.inl
- Code/Framework/AzCore/AzCore/IO/Path/PathReflect.cpp
- Code/Framework/AzCore/AzCore/Serialization/Json/PathSerializer.cpp
- Code/Framework/AzCore/AzCore/Serialization/Json/PathSerializer.h
- Code/Framework/AzCore/AzCore/azcore_files.cmake
- Code/Framework/AzCore/Tests/Serialization/Json/PathSerializerTests.cpp
- Code/Framework/AzCore/Tests/azcoretests_files.cmake
Added UnitTest for Json Serialization of AzCore Path types
resolves #2477
> Introduced a Json Serializer for the AzCore mutable path classes

- scripts/build/Platform/Linux/build_config.json
- scripts/build/Platform/Linux/deploy_cdk_applications.sh
- scripts/build/Platform/Linux/destroy_cdk_applications.sh
- scripts/build/Platform/Linux/pipeline.json
Need the help from the infra team to set up the Jenkins job and environment variables as we did for Windows. Also needs to make sure that the O3DE_AWS_PROJECT_NAME variable has a different name for each platform.
Build scripts are include in https://github.com/o3de/o3de/pull/6278.
Ran the pipe on Jenkins. (I couldn't set the Jenkins parameters so the deployment and tests are expected to fail).
https://jenkins-pipeline.agscollab.com/job/O3DE-LY-FORK/job/LinuxAWSIAutomationJenkins/4/
> Define AWSI automation tests pipe for Jenkins

- Gems/ScriptCanvas/Code/Editor/Components/EditorScriptCanvasComponent.cpp
- Gems/ScriptCanvas/Code/Editor/View/Widgets/GraphTabBar.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
> Fix for file-save-as-new and open asset

- Gems/EMotionFX/Code/EMotionFX/Source/Velocity.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/Velocity.h
- Gems/EMotionFX/Code/EMotionFX/emotionfx_files.cmake
* Added helper functions for calculating linear and angular velocities.
* Added debug visualization helper for linear and angular velocities.
> EMotion FX: Linear and angular velocity calculation and debug visualization helpers

- Code/Framework/AzFramework/AzFramework/azframework_files.cmake
- Code/Framework/AzFramework/Platform/Common/Default/AzFramework/Process/ProcessWatcher_Default.cpp
> ProcessWatcher fixes.

- Code/Editor/Common/spline_edit-00.png
- Code/Editor/Common/spline_edit-01.png
- Code/Editor/Common/spline_edit-02.png
- Code/Editor/Common/spline_edit-03.png
- Code/Editor/Common/spline_edit-04.png
- Code/Editor/Common/spline_edit-05.png
- Code/Editor/Common/spline_edit-06.png
- Code/Editor/Common/spline_edit-07.png
- Code/Editor/Common/spline_edit-08.png
- Code/Editor/Common/spline_edit-09.png
- Code/Editor/Common/spline_edit-10.png
- Code/Editor/Common/spline_edit-11.png
- Code/Editor/Common/spline_edit-12.png
- Code/Editor/Common/spline_edit-13.png
- Code/Editor/Common/spline_edit-14.png
- Code/Editor/Common/spline_edit-15.png
- Code/Editor/Common/spline_edit-16.png
Verified the images under `Editor/Common` were unused. Built/ran tests and Editor.
> Removed unused images under Editor/Common

- Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.cpp
> on demand reflect az events when they are the return value of ebuses

- Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeBlendNNode.cpp
> Fix: Blend node applies both poses at value 1

- cmake/AzAutoGen.py
> Removes unnecessary loop

- scripts/build/Platform/Android/build_config.json
- scripts/build/Platform/Android/pipeline.json
- scripts/build/Platform/Linux/pipeline.json
- scripts/build/Platform/Mac/build_config.json
- scripts/build/Platform/Mac/pipeline.json
- scripts/build/Platform/Windows/build_config.json
- scripts/build/Platform/Windows/pipeline.json
- scripts/build/Platform/iOS/pipeline.json
> More packaging cleanup

- Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilder.cpp
- Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilder.h
- Gems/ScriptCanvas/Code/Editor/Components/EditorScriptCanvasComponent.cpp
- Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorScriptCanvasComponent.h
Fixes crash: https://github.com/o3de/o3de/issues/6543
Makes impossible to reproduce: https://github.com/o3de/o3de/issues/6540
> Fix issues caused by SC editor component holding onto a live graph

- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/ManipulatorSnapping.cpp
- Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.cpp
Small fix to address alpha color values not being respected correctly
> Small workaround and fix to ensure line fade (alpha) displays correctly

- AutomatedTesting/Gem/PythonTests/editor/EditorScripts/AssetBrowser_SearchFiltering.py
Added a delay when entering a string in the search bar in order to catch issues such as #5832
https://user-images.githubusercontent.com/82394219/144096421-5986d56c-1f1a-4413-b5b5-0466ac5e8f24.mp4
Signed-off-by: AMZN-Igarri <82394219+AMZN-Igarri@users.noreply.github.com>
> AssetBrowser SearchFilteringTest: Added delay when inserting a string to the search file.

- .gitignore
> git.ignore cleanup

- Gems/Atom/RPI/Code/Source/RPI.Public/DynamicDraw/DynamicDrawContext.cpp
- Gems/LyShine/Code/Source/Draw2d.cpp
- Gems/LyShine/Code/Source/UiRenderer.cpp
Prevents a crash if the LyShine shader has failed to load.
> Add better error handling for failed loading of the LyShine shader

- Code/Framework/AzTest/AzTest/Platform/Windows/ScopedAutoTempDirectory_Windows.cpp
Previously it was using `GetTickCount()` for the creation of the
directory which can collide if  there are multiple processes
creating a temporary directory via the `ScopedAutoTempDirectory`
constructor.
> Updated the Windows ScopedAutoTempDirectory creation logic to use a Uuid

- Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
LYN-9183 Fix Terrain Heightfield Collider component to list physics materials from the library
> LYN-9183 Fix Terrain Heightfield Collider component to list physics materials from the library

- Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/UiFlipbookAnimationBus.names
> Updated node subtitle, closes #6855

- cmake/Platform/Mac/InstallUtils_mac.cmake.in
> [Mac] Remove quotes around list in install utils

- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp
> Bugfix - ViewportInteractionImp connected to the wrong id in RenderViewportWidget

- Code/Editor/Util/EditorUtils.cpp
- Code/Editor/Util/EditorUtils.h
- Gems/LyShine/Code/Editor/Animation/Util/UiEditorUtils.cpp
Removed some unused EditorUtils functions.
> Removed some unused EditorUtils functions

- cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake
- cmake/3rdParty/Platform/Mac/BuiltInPackages_mac.cmake
- cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
> Updating assimp to the v12 packages

- Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/PhysicalDeviceDescriptor.h
- Gems/Atom/RHI/Code/Include/Atom/RHI/FrameScheduler.h
- Gems/Atom/RHI/Code/Include/Atom/RHI/RHISystem.h
- Gems/Atom/RHI/Code/Include/Atom/RHI/RHISystemInterface.h
- Gems/Atom/RHI/Code/Source/RHI/RHISystem.cpp
- Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/Device_Windows.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI/PipelineLibrary.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Shader/Shader.cpp
- Support to add a different PSO cache per vendor/driver version. 
- Added support to have a different cache for Warp
- Added a way to reset PSO cache for everyone
> Different Pso cache per vendor/driver

- Code/Editor/EditorViewportWidget.cpp
> Fix Camera angle on switch levels

- cmake/PAL.cmake
Signed-off-by: byrcolin <byrcolin@amazon.com>
> fix edge case with deprecated pal functions

- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h
- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h
- Gems/Atom/Feature/Common/Code/Mocks/MockMeshFeatureProcessor.h
- Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Mesh/MeshComponentBus.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/EditorMeshComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.h
- Gems/Vegetation/Code/Tests/VegetationMocks.h
Adding ray tracing toggle to mesh component UI
Signed-off-by: windbagjacket <nibor@ntlworld.com>
> Adding ray tracing toggle to mesh component UI

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentSystemRequestBus.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.h
> Atom Tools: added function to get the number of active documents

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Application/AtomToolsApplication.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
> Atom Tools: Bind exit function for python tests

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentApplication.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentApplication.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_files.cmake
- Gems/Atom/Tools/MaterialEditor/Code/Source/MaterialEditorApplication.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/MaterialEditorApplication.h
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleApplication.cpp
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleApplication.h
Moving some duplicated code to a common base class
> Atom Tools: Created base class for document-based applications

- Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/Outliner/OutlinerListModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/EntryDelegate.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Editor/RichTextHighlighter.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Editor/RichTextHighlighter.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
resolves #6972 
Signed-off-by: AMZN-Igarri <82394219+AMZN-Igarri@users.noreply.github.com>
> Fix: Entity Outliner: Outliner is unusable with the Editor in slice mode

- Gems/Atom/Asset/Shader/Code/Source/Editor/AzslShaderBuilderSystemComponent.cpp
- Gems/Atom/Asset/Shader/Code/Source/Editor/PrecompiledShaderBuilder.cpp
- Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridBlendDistance.precompiledshader
- Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridBlendIrradiance.precompiledshader
- Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridBorderUpdateColumn.precompiledshader
- Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridBorderUpdateRow.precompiledshader
- Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridClassification.precompiledshader
- Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridRayTracing.precompiledshader
- Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridRayTracingClosestHit.precompiledshader
- Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridRayTracingMiss.precompiledshader
- Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridRelocation.precompiledshader
- Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridRender.precompiledshader
- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/PrecompiledShaderAssetSourceData.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderAssetCreator.h
- Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/PrecompiledShaderAssetSourceData.cpp
- Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderAssetCreator.cpp
> Support supervariants in the PrecompiledShaderBuilder

- Code/Tools/ProjectManager/Source/PythonBindings.cpp
- Gems/Atom/Asset/ImageProcessingAtom/gem.json
- Gems/Atom/Bootstrap/gem.json
- Gems/Atom/Component/DebugCamera/gem.json
- Gems/Atom/Feature/Common/gem.json
- Gems/Atom/RHI/DX12/gem.json
- Gems/Atom/RHI/Metal/gem.json
- Gems/Atom/RHI/Null/gem.json
- Gems/Atom/RHI/Vulkan/gem.json
- Gems/Atom/RHI/gem.json
- Gems/Atom/RPI/gem.json
- Gems/Atom/Tools/AtomToolsFramework/gem.json
- Gems/AtomLyIntegration/AtomBridge/gem.json
- Gems/AtomLyIntegration/AtomFont/gem.json
- Gems/AtomLyIntegration/AtomImGuiTools/gem.json
- Gems/AtomLyIntegration/AtomViewportDisplayIcons/gem.json
- Gems/AtomLyIntegration/AtomViewportDisplayInfo/gem.json
- Gems/AtomLyIntegration/CommonFeatures/gem.json
- Gems/AtomLyIntegration/EMotionFXAtom/gem.json
- Gems/AtomLyIntegration/ImguiAtom/gem.json
Signed-off-by: byrcolin <byrcolin@amazon.com>
> fix launcher not showing gems

- Code/Tools/ProjectManager/Source/Application.cpp
- Code/Tools/ProjectManager/Source/Application.h
- Code/Tools/ProjectManager/Source/EngineInfo.h
- Code/Tools/ProjectManager/Source/EngineSettingsScreen.cpp
- Code/Tools/ProjectManager/Source/GemRepo/GemRepoScreen.cpp
- Code/Tools/ProjectManager/Source/ProjectUtils.cpp
- Code/Tools/ProjectManager/Source/ProjectUtils.h
- Code/Tools/ProjectManager/Source/PythonBindings.cpp
- Code/Tools/ProjectManager/Source/PythonBindings.h
- Code/Tools/ProjectManager/Source/PythonBindingsInterface.h
- scripts/o3de/o3de/engine_properties.py
- scripts/o3de/o3de/manifest.py
Cherry picking 2 critical fixes from development:
- 3405cee2efebba807ccf8cbebec6017031809340 https://github.com/o3de/o3de/pull/6184
- 73419387c5235eba97ab11f194e6c1049c43f981 https://github.com/o3de/o3de/pull/6828
**Testing**
- Project Manager compiles/runs
- Project Manager gets/sets engine info
- Dialog is presented when duplicate engine is detected
> Duplicate engine detection and help in Project Manager

- Gems/AWSCore/Code/Include/Framework/AWSApiRequestJob.h
- Gems/AWSCore/Code/Include/Framework/ServiceRequestJob.h
Move the queued-events constructors for AWSApiClientJob and ServiceRequestJob from public to protected, and add short description for them
> Minor class definition updates for AWSGem

- Code/Editor/CryEdit.cpp
> Fixing crash when opening different level during simulation mode

- Gems/Atom/Tools/MaterialEditor/Code/Source/Platform/Linux/MaterialEditor_Traits_Linux.h
- Gems/Atom/Tools/MaterialEditor/Code/Source/Platform/Mac/MaterialEditor_Traits_Mac.h
- Gems/Atom/Tools/MaterialEditor/Code/Source/Platform/Windows/MaterialEditor_Traits_Windows.h
> Atom Tools: removing unused traits for ME executable extension

- Gems/ScriptCanvas/Assets/TranslationAssets/Classes/MaterialData.names
- Gems/ScriptCanvas/Assets/TranslationAssets/Nodes/Input_InputHandler.names
- Gems/ScriptCanvas/Code/Editor/View/Widgets/ScriptCanvasNodePaletteDockWidget.cpp
- Gems/ScriptCanvas/Code/Editor/View/Widgets/ScriptCanvasNodePaletteDockWidget.h
Closes #6924
Closes #6920
Closes #6166
Closes #6925
Closes #6873
> Addressed a few Script Canvas translation issues

- Code/Editor/CMakeLists.txt
- Code/Editor/CryEdit.cpp
- Code/Editor/IEditorImpl.cpp
- Code/Editor/IEditorImpl.h
- Code/Editor/MainWindow.cpp
> Removed unused AWSNativeSDK dependency from Editor

- Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
- Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
- Gems/PhysX/Code/Source/HeightfieldColliderComponent.cpp
- Gems/PhysX/Code/Source/Utils.cpp
- Gems/PhysX/Code/Source/Utils.h
- Gems/PhysX/Code/Tests/EditorHeightfieldColliderComponentTests.cpp
- Gems/PhysX/Code/Tests/EditorTestUtilities.cpp
- Gems/PhysX/Code/Tests/EditorTestUtilities.h
> LYN-7640 Terrain Physics Materials hooked up all the way down to PhysX

- AutomatedTesting/Gem/PythonTests/AWS/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/AWS/README.md
- AutomatedTesting/Gem/PythonTests/AWS/common/aws_credentials.py
- AutomatedTesting/Gem/PythonTests/AWS/common/aws_utils.py
- AutomatedTesting/Gem/PythonTests/AWS/common/constants.py
- scripts/build/Platform/Linux/build_config.json
- scripts/build/Platform/Linux/deploy_cdk_applications.sh
- scripts/build/Platform/Linux/destroy_cdk_applications.sh
- scripts/build/Platform/Linux/pipeline.json
- scripts/build/Platform/Windows/deploy_cdk_applications.cmd
- scripts/build/Platform/Windows/destroy_cdk_applications.cmd
- scripts/build/Platform/Windows/pipeline.json
- Verified the scripts and automation tests locally
- Ran on Jenkins (Jobs failed due to the IAM role permission issue Allie is looking into)
> Update deployment scripts to support AWSI automation tests on Linux

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.cpp
> Introduce shortcut labeling in "Find in Viewport" context menu item

- Gems/VirtualGamepad/Code/CMakeLists.txt
- Gems/VirtualGamepad/gem.json
> Adding missing dependency on LyShine to the VirtualGamepad

- Code/Tools/AzTestRunner/CMakeLists.txt
- Code/Tools/AzTestRunner/Platform/Android/platform_android.cmake
> Remove unused AzFramework dependency from AzTestRunner

- Gems/ScriptEvents/Code/Include/ScriptEvents/ScriptEventDefinition.cpp
> Remove error state when user attempts to save empty script event.

- Code/Framework/AzCore/AzCore/std/string/string_view.h
- Code/Tools/AssetProcessor/native/utilities/ApplicationManager.cpp
- Gems/Atom/RHI/Code/Include/Atom/RHI/ThreadLocalContext.h
> Fixed string_view compilation in GCC 10+.

- Gems/EMotionFX/Code/MysticQt/Source/RecentFiles.cpp
Recent files were only shown from sub-folders of the project and assets from gems (inside project and external) were not visible.
> EMotion FX: Recent files menu in Animation Editor also shows files from external gems

- Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorNonUniformScaleComponentMode.cpp
> fix for changes in non-uniform scale component mode not persisting

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Window/AtomToolsMainWindow.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorWindow.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorWindow.h
> Atom Tools: move performance metrics status bar widgets to base window

- Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
- Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
> LYN-7637 Allow Terrain Physics Collider to assign a default physics material

- Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.cpp
update the prefab path for procedural prefabs so that the prefab template can be found from the level prefab load event. It is important that it points to the realative/path/to/the.procprefab using the correct front slashes for the source asset path
> {ghi7197} update the prefab path for procedural prefabs

- Gems/MotionMatching/Docs/Images/FeatureHistograms.png
- Gems/MotionMatching/Docs/Images/FeaturePositionRPE.png
- Gems/MotionMatching/Docs/Images/FeaturePositionVis.png
- Gems/MotionMatching/Docs/Images/FeatureScatterplotPCA.png
- Gems/MotionMatching/Docs/Images/FeatureSharedRPE.png
- Gems/MotionMatching/Docs/Images/FeatureTrajectoryRPE.png
- Gems/MotionMatching/Docs/Images/FeatureTrajectoryVis.png
- Gems/MotionMatching/Docs/Images/FeatureVelocityRPE.png
- Gems/MotionMatching/Docs/Images/FeatureVelocityVis.png
- Gems/MotionMatching/Docs/Images/TrajectoryHistory.png
- Gems/MotionMatching/README.md
* Added several new sections (trajectory history, motion matching data, motion matching instance)
* Added images for the available feature visualizations and UI editors.
* Added feature histogram and scatterplot.
File can be previewed [here](https://github.com/aws-lumberyard-dev/o3de/tree/jillich/MMReadMe/Gems/MotionMatching#readme).
> Motion Matching: ReadMe.md update

- Gems/Atom/Utils/Code/Include/Atom/Utils/ImageComparison.h
- Gems/Atom/Utils/Code/Source/ImageComparison.cpp
- Gems/Atom/Utils/Code/Tests/ImageComparisonTests.cpp
Small refactor to pull out function. 
Linked to this ASV PR: https://github.com/o3de/o3de-atom-sampleviewer/pull/325
Signed-off-by: hershey5045 <43485729+hershey5045@users.noreply.github.com>
> Small refactor on ImageComparison utils.

- AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_AutoComponent_RPC.py
- AutomatedTesting/Levels/Multiplayer/AutoComponent_RPC/AutoComponent_RPC.prefab
- AutomatedTesting/Levels/Multiplayer/AutoComponent_RPC/AutoComponent_RPC.scriptcanvas
- AutomatedTesting/Levels/Multiplayer/AutoComponent_RPC/AutoComponent_RPC_NetLevelEntity.scriptcanvas
Re-adding the Authority->Client RPC test now that ScriptCanvas is fixed for Editor play-mode.
_AutomatedTesting\Levels\Multiplayer\AutoComponent_RPC\AutoComponent_RPC.scriptcanvas_
_AutomatedTesting\Levels\Multiplayer\AutoComponent_RPC\AutoComponent_RPC_NetLevelEntity.scriptcanvas_
> AutomatedTesting: Adding Multiplayer Authority->Client RPC Test

- Gems/ImGui/Code/Include/LYImGuiUtils/HistogramGroup.h
- Gems/ImGui/Code/Source/LYImGuiUtils/HistogramGroup.cpp
Added a helper function to find a container by name in the histogram container.
> ImGui: Added FindContainerByName() helper

- Gems/MotionMatching/Code/Source/KdTree.cpp
> Motion Matching: Fix for nightly build issue

- AutomatedTesting/Gem/PythonTests/automatedtesting_shared/base.py
- Tools/LyTestTools/ly_test_tools/launchers/platforms/android/launcher.py
- Tools/LyTestTools/ly_test_tools/launchers/platforms/base.py
- Tools/LyTestTools/ly_test_tools/launchers/platforms/linux/launcher.py
- Tools/LyTestTools/ly_test_tools/launchers/platforms/mac/launcher.py
- Tools/LyTestTools/ly_test_tools/launchers/platforms/win/launcher.py
- Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
- Tools/LyTestTools/tests/unit/test_launcher_android.py
- Tools/LyTestTools/tests/unit/test_launcher_base.py
- Tools/LyTestTools/tests/unit/test_launcher_linux.py
- Tools/LyTestTools/tests/unit/test_launcher_mac.py
- Tools/LyTestTools/tests/unit/test_launcher_win.py
- Tools/LyTestTools/tests/unit/test_o3de_editor_test.py
> Changed kill to protected.

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/Workspace.cpp
https://user-images.githubusercontent.com/69218254/152289858-c356fb66-c7c6-43f0-8344-8629a7eb23aa.mp4
> Load workspace should activate the graph by default.

- Gems/Atom/RPI/Code/Source/RPI.Public/DynamicDraw/DynamicDrawSystem.cpp
>  ATOM-17264 ASV: StreamingImageTest crashes

- Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/UserInterface_Compressed.preset
- Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/UserInterface_Lossless.preset
The texture was treated as in linear space which leads to the color change when renders.
Change to sRGB fixes the issue.
> Fix for github issue https://github.com/o3de/o3de/issues/6380

- Registry/gem_autoload.materialeditor.setreg
- Registry/gem_autoload.shadermanagementconsole.setreg
> Atom Tools: fix gem autoload settings registry files

- AutomatedTesting/Gem/PythonTests/smoke/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/smoke/test_CLITool_AssetBuilder_Works.py
Signed-off-by: Rosario Cox <lesaelr@amazon.com>
> Moving test_CLITool_AssetBuilder_Works to sandbox.

- Gems/GraphCanvas/Code/Source/Components/SceneComponent.cpp
- Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
Closes #7454 
Closes #7336 
Closes #6524
> Fixed group and bookmark display on graph load

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
> Focus Mode | Remove const reference to prevent issues in nightly builds.

- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/DiskLightFeatureProcessorInterface.h
- Gems/Atom/Feature/Common/Code/Source/CoreLights/DiskLightFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/CoreLights/DiskLightFeatureProcessor.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/AuxGeom/AuxGeomDraw.h
> Add a function to get the internal data for a disk light from it's feature processor

- Tools/LyTestTools/tests/integ/sanity_tests.py
> Added server launcher sanity test.

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Translation/GraphToLuaUtility.cpp
closes https://github.com/o3de/o3de/issues/7350
> initial locale safety for translating to Lua on multiple platforms

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Node.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/NodeFunctionGeneric.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Math/Vector2Nodes.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Math/Vector3Nodes.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Math/Vector4Nodes.h
Closes https://github.com/o3de/o3de/issues/7502
> fix errors when generic nodes fail to add slots

- AutomatedTesting/Gem/PythonTests/automatedtesting_shared/base.py
Prevents repeated calls to open and communicate with the AssetProcessor from the Physics tests. Also fixes NoneType errors that appeared after applying the fix. Continues to leave the AssetProcessor open between the series of tests, which means test durations are identical before and after this change.
This addresses the intermittent failures seen in https://github.com/o3de/o3de/issues/7488 which passes locally 20/20 times after this fix. Continuing to test locally to search for additional issues. Any other issues found will be handled in a separate pull request.
@o3de/sig-core To avoid continually paying toward this tech debt, Physics should continue to move their unoptimized tests in module PhysicsTests_Main away from their TestAutomationBase class, and into the …
> Prevent unsafe calls to AssetProcessor

- Gems/MotionMatching/Code/CMakeLists.txt
> Motion Matching: Fix for test build on nightly linux builds

- AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
> Disabled tests that are reported failing on nightly builds

- Tools/LyTestTools/ly_test_tools/_internal/managers/abstract_resource_locator.py
- Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
- Tools/LyTestTools/ly_test_tools/o3de/editor_test_utils.py
- Tools/LyTestTools/tests/unit/test_editor_test_utils.py
- Tools/LyTestTools/tests/unit/test_o3de_editor_test.py
Tested by running locally with failed assets. Unit tests pass.
> Collects failed assets on LyTestTools test failures

- cmake/3rdParty/Platform/Mac/BuiltInPackages_mac.cmake
Update to fix bad Mac SQLite3 package
> Fix Mac SQL Package

- Gems/LmbrCentral/Code/Source/Shape/AxisAlignedBoxShapeComponent.cpp
- Gems/LmbrCentral/Code/Source/Shape/AxisAlignedBoxShapeComponent.h
- Gems/LmbrCentral/Code/Source/Shape/EditorAxisAlignedBoxShapeComponent.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorAxisAlignedBoxShapeComponent.h
- Gems/LmbrCentral/Code/Tests/AxisAlignedBoxShapeTest.cpp
> make aabb shape component incompatible with non-uniform scale component

- Gems/MotionMatching/README.md
> Motion Matching: Added sections about the cost function and motion matching search to the readme

- AutomatedTesting/Passes/MainPipeline.pass
> Added the DiffuseProbeGridVisualizationCompositePass

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ViewportInputBehaviorController/IdleBehavior.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ViewportInputBehaviorController/IdleBehavior.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ViewportInputBehaviorController/ViewportInputBehaviorController.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_files.cmake
- Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportWidget.cpp
> Atom Tools: Restoring idle behavior for viewport input behavior contoller

- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.cpp
- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.h
> [Terrain] Update ProcessFromListOfVector2 API functions to use bulk queries.

- Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportWidget.cpp
> MaterialEditor fix for MSAA state

- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.cpp
- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.h
> Fix build error due to const qualifiers not matching

- AutomatedTesting/Gem/PythonTests/largeworlds/gradient_signal/EditorScripts/ImageGradient_ModifiesSurfaces.py
- Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
Updated the `SetImageAssetPath` API on image gradient to be more robust.
- An empty path will now unassign the asset
- Invalid asset paths will still be ignored
- Valid asset path but for an asset that doesn't match the type will be ignored
Also updated the recently added automated test for image gradients to make use this API.
Signed-off-by: Chris Galvan [chgalvan@amazon.com](mailto:chgalvan@amazon.com)
> Updated SetImageAssetPath on image gradient to be more robust

- Code/Tools/AssetProcessor/native/tests/assetmanager/TestEventSignal.h
> [LYN-10331] Fixed missing include

- Gems/Profiler/Code/Source/ImGuiCpuProfiler.cpp
- Gems/Profiler/Code/Source/ImGuiCpuProfiler.h
resolves #4365
- Increased the initial profiler ImGui window size
- Updated thread render order so the main thread is always on top
https://user-images.githubusercontent.com/24445312/154368144-d32e709f-74c2-423a-befd-a43e13af4979.mp4
> [development] added option to control update frequency in profiler visualizer

- Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/MSAAResolveCustom.shader
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceBlurHorizontal.shader
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceBlurVertical.shader
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceComposite.shader
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceTrace.shader
Signed-off-by: Yaakuro <y1@codeposer.net>
> Remove redundant ProgramVariant tag because it got deprecated.

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Contracts/MethodOverloadContract.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Contracts/TypeContract.cpp
> Removed carriage return from errors

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.h
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.cpp
> Prevent the character to go out of bound in animation viewport

- Gems/Atom/RHI/Code/Source/RHI/Resource.cpp
Signed-off-by: Bindless-Chicken <1039134+Bindless-Chicken@users.noreply.github.com>
> Fix missing format parameter in RHI::Resource

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.h
> add the render option reflection so it show up in the preference window

- Gems/ScriptCanvas/Assets/TranslationAssets/Nodes/Timing_HeartBeat.names
> Fixed Heartbeat node's translation

- Gems/ScriptCanvas/Code/Editor/Nodes/NodeDisplayUtils.cpp
> Make sure nodes always have a title

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/ColorGrading/EditorHDRColorGradingComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/SurfaceData/EditorSurfaceDataMeshComponent.h
- Gems/GradientSignal/Code/Source/Editor/EditorGradientSurfaceDataComponent.h
- Gems/LmbrCentral/Code/Source/Shape/EditorReferenceShapeComponent.h
- Gems/LyShine/Code/Source/World/UiCanvasOnMeshComponent.cpp
- Gems/PhysX/Code/Source/EditorRigidBodyComponent.cpp
- Gems/SurfaceData/Code/Source/Editor/EditorSurfaceDataColliderComponent.h
- Gems/SurfaceData/Code/Source/Editor/EditorSurfaceDataShapeComponent.h
- Gems/Vegetation/Code/Source/Debugger/EditorAreaDebugComponent.h
- Gems/Vegetation/Code/Source/Editor/EditorAreaBlenderComponent.h
- Gems/Vegetation/Code/Source/Editor/EditorBlockerComponent.h
- Gems/Vegetation/Code/Source/Editor/EditorDescriptorListCombinerComponent.h
- Gems/Vegetation/Code/Source/Editor/EditorDescriptorListComponent.h
- Gems/Vegetation/Code/Source/Editor/EditorDescriptorWeightSelectorComponent.h
- Gems/Vegetation/Code/Source/Editor/EditorDistanceBetweenFilterComponent.h
- Gems/Vegetation/Code/Source/Editor/EditorDistributionFilterComponent.h
- Gems/Vegetation/Code/Source/Editor/EditorMeshBlockerComponent.h
- Gems/Vegetation/Code/Source/Editor/EditorPositionModifierComponent.h
- Gems/Vegetation/Code/Source/Editor/EditorRotationModifierComponent.h
- Gems/Vegetation/Code/Source/Editor/EditorScaleModifierComponent.h
- Gems/Vegetation/Code/Source/Editor/EditorShapeIntersectionFilterComponent.h
- Gems/Vegetation/Code/Source/Editor/EditorSlopeAlignmentModifierComponent.h
- Gems/Vegetation/Code/Source/Editor/EditorSurfaceAltitudeFilterComponent.h
- Gems/Vegetation/Code/Source/Editor/EditorSurfaceMaskDepthFilterComponent.h
- Gems/Vegetation/Code/Source/Editor/EditorSurfaceMaskFilterComponent.h
- Gems/Vegetation/Code/Source/Editor/EditorSurfaceSlopeFilterComponent.h
> Additional help page changes in #2321

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/NodeFunctionGeneric.h
> Fix debug warning to error

- Code/Framework/AzCore/AzCore/Serialization/Json/JsonImporter.cpp
- Code/Framework/AzCore/AzCore/Serialization/Json/JsonImporter.h
- Code/Framework/AzCore/Tests/Serialization/Json/TestCases_Importing.cpp
> [JsonSerialization] Add an error message with the path to the file that failed to be imported.

- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.cpp
> Bulk queries for surface weight data weren't returning sorted results.

- Gems/MotionMatching/Assets/Levels/MotionMatching_ControllableCharacter/CameraController_ControllableCharacter.scriptcanvas
- Gems/MotionMatching/Assets/Levels/MotionMatching_ControllableCharacter/InputBindings_ControllableCharacter.inputbindings
* Input bindings for mouse and gamepad input
* Camera can be changed by moving mouse left/right
* Camera can be changed by moving the right joystick on a gamepad
https://user-images.githubusercontent.com/43751992/155515877-d74e9afd-fd45-43d5-8228-2c2b0d20aba2.mp4
> Motion Matching: Camera controller for controllable character demo

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.h
https://user-images.githubusercontent.com/69218254/155468295-afa12e7d-e373-4ba1-87ac-940dd0c0ce7c.mp4
> Add a simple fps counter

- Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignment.cpp
- Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignmentId.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.cpp
> Binding functions for editor material component automated tests

- Templates/DefaultProject/Template/Gem/Platform/iOS/${NameLower}_ios_files.cmake
- Templates/MinimalProject/Template/Gem/Platform/iOS/${NameLower}_ios_files.cmake
> Fixed path to ios resources folder in template projects.

- cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake
- cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
Pass unit test
Tested locally with GameLiftLocal
> Update O3DE to use latest gamelift server sdk

- Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderDataSystem.cpp
> remove unnecessary build success message

- Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
Resolves https://github.com/o3de/o3de/issues/7657
Attempts to better log a rare error where an empty result gets reported from _exec_editor_test, to properly report the failure. Does not directly address the underlying cause, but should no longer emit an unexpected error from the modified code.
> Safely record unexpected results

- Gems/ScriptCanvas/Code/Editor/Assets/ScriptCanvasFileHandling.cpp
fix up saved data that WAS stored in an unordered container after all
> Remap Ids in SC internal, unordered containers.

- Gems/Atom/RHI/Code/Source/RHI/ValidationLayer.cpp
- Also added a cvar to disable this for non-rendering engineers
> Add support to enable device validation for debug builds

- Code/Framework/AzCore/AzCore/std/ranges/ranges_algorithm.h
- Code/Framework/AzCore/Tests/AZStd/RangesAlgorithmTests.cpp
> Add `AZStd::ranges::all_of` and `AZStd::ranges::any_of`

- Tools/LyTestTools/ly_test_tools/o3de/editor_test_utils.py
> fixed bug if asset job logs don't exist
