- Code/Editor/EditorViewportWidget.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ModularViewportCameraController.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ModularViewportCameraController.cpp
This is one more follow-on change from both https://github.com/o3de/o3de/pull/2346 and https://github.com/o3de/o3de/pull/2769 (got delayed with the Game Jam so just getting back to them).
We have the means to control at what priority the camera controller responds to events (as all priority events are dispatched to it). Right now that logic is quite specific to handle cases in the Editor Viewport, but as we're hoping to in future use the `ModularViewportCameraController` in other tools/viewports this logic should really be moved outside.
This change makes this possible so in other situations a much simpler priority determination could be used (e.g. Only responding to events that are at Normal priority for example). We still make `DefaultCameraControllerPriority` available for use as it …
> Make camera controller priority customizable

- Code/Editor/CryEditDoc.cpp
- Code/Editor/CryEditDoc.h
GetActivePathName was using default - constructed enum DocumentEditingMode()
SaveLevel was not using destName when constructing newFilePath
Other code changes:
* LogLoadTime is simplified by using QFile
* reduce nesting in DoSaveDocument by using early return.
* marked a few eligible methods as const
* Simplified OnEnvironmentPropertyChanged a bit
this is a split version of #2252 
> CCryEditDoc: fix a few bugs 

- Gems/PhysX/Code/Source/PhysXCharacters/API/Ragdoll.cpp
- Gems/PhysX/Code/Source/PhysXCharacters/API/Ragdoll.h
fixes #2650 
The root of the crash was connecting/disconnecting to the AZ::Event SceneSimulationStart when not on the main thread, as that is not thread safe.
The connection/disconnection was originally handled from Enable/EnableQueued and Disable/DisabledQueued which can be called from other threads within EmotionFX. I've moved the connection/disconnection to the Constructor / destructor, as the handler is responsible for executing the queued enable/disable actions and it makes sense to have that connection happen external to the Enable/disable path.
> fixed Ragdoll component can crash on deactivate

- cmake/Platform/Windows/Packaging/Bootstrapper.wxs
- cmake/Platform/Windows/Packaging/BootstrapperTheme.wxl.in
- cmake/Platform/Windows/Packaging/BootstrapperTheme.xml.in
- cmake/Platform/Windows/Packaging_windows.cmake
- Enable files in use dialog in bootstrap installer to close running o3de tools during uninstall or repair
- Fixed installer toolset path propagation after variable name change
> [development] installer work - added 'files in use' page and fixed toolset path propagation

- Code/Framework/AzFramework/AzFramework/Asset/AssetSystemComponentHelper.cpp
In case an asset platform setting is missing it was supposed to be set to a 'pc' value.
Instead it was set to an empty string.
> Fix logic in ReadConnectionSettingsFromSettingsRegistry

- Code/Framework/AzFramework/Platform/Linux/AzFramework/Process/ProcessWatcher_Linux.cpp
Inner scope numEnvironmentVars was shadowing the outer scope, and prevented env variable memory from being freed.
> Fix memory leak in ProcessLauncher::LaunchProcess

- scripts/o3de/tests/unit_test_enable_gem.py
The enable-gem unit test would fail if there wasn't an
o3de_manifest.json file in the users $HOME/.o3de directory
The change now is to patch the call to load the o3de manifest
> Fixed the enable-gem command unit test

- Tools/LyTestTools/ly_test_tools/benchmark/data_aggregator.py
`CI` should be set to true in Jenkins-based builds, and false if run locally, according to https://jenkins.build.o3de.org/env-vars.html/
Should consider if we want some other identifier in the Elasticsearch index so different developers don't conflate their build results with others run on the same day.
> performance metrics: Upload benchmark results to local index for locally-run builds.

- Code/Framework/AzCore/AzCore/Module/Environment.cpp
- Code/Framework/AzCore/AzCore/Module/Environment.h
Move almost all destruction logic to EnvironmentVariableHolderBase::UnregisterAndDestroy.
Specialized templates have DestructDispatchNoLock instead that can either destroy the held value,
or the holder itself.
UnregisterAndDestroy has been moved to the cpp file.
All of these changes reduce the profile build time and size on linux
Here, the size of `bin/profile` goes down by ~200MB.
> EnvironmentVariableHolder: reduce the size of template instantiation.

- Gems/LyShine/Code/Source/LyShineDebug.h
Signed-off-by: Tom spot Callaway <spotaws@amazon.com>
If -D_RELEASE is set, Gems/LyShine/Code/Source/LyShineDebug.cpp does not compile with this error:
```
/home/fedora/rpmbuild/BUILD/o3de/Gems/LyShine/Code/Source/LyShineDebug.h:36:31: error: unknown type name 'CV_r_DebugUIDraw2dFont'
DeclareStaticConstIntCVar(CV_r_DebugUIDraw2dFont, 0);
```
This is because the header that defines DeclareStaticConstIntCVar(), `CryCommon/ISystem.h`, is wrapped in
`#ifndef _RELEASE`.
This pull requests moves `CryCommon/ISystem.h` outside of the conditional, which seemed to be the simplest way to address this. An alternate method would be to wrap all of the CV_r_DebugUIDraw* uses in the same conditional, but that was more intrusive and I was not sure it was correct.
> pull CryCommon/ISystem.h include out of _RELEASE conditional

- Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp
- Code/Editor/Util/FileUtil.cpp
- Code/Editor/Util/FileUtil.h
Most of the path-related context menu options in the Asset Browser were not working. Fixed the logic to make sure it deals with a full, normalized path, which removed some guess-work the former logic was trying to do with files vs. folders.
Tested the following context menu options on both files and folders and verified they now perform the expected behaviors:
- Open in Explorer
- Copy Name to Clipboard
- Copy Path to Clipboard
Also tested the additional context menu options specific for files (e.g. Open in Asset Editor, Open in associated application, etc...)
Fixes #2533
Fixes #2433 
Fixes #2558 
> Fixed Asset Browser path related context menu options.

- Gems/AWSCore/Code/CMakeLists.txt
- Gems/AWSCore/Code/Include/Private/AWSCoreInternalBus.h
- Gems/AWSCore/Code/Include/Private/Configuration/AWSCoreConfiguration.h
- Gems/AWSCore/Code/Include/Private/Editor/UI/AWSCoreResourceMappingToolAction.h
- Gems/AWSCore/Code/Source/Configuration/AWSCoreConfiguration.cpp
- Gems/AWSCore/Code/Source/Editor/UI/AWSCoreEditorMenu.cpp
- Gems/AWSCore/Code/Source/Editor/UI/AWSCoreResourceMappingToolAction.cpp
- Gems/AWSCore/Code/Tests/Credential/AWSDefaultCredentialHandlerTest.cpp
- Gems/AWSCore/Code/Tests/Editor/AWSCoreEditorManagerTest.cpp
- Gems/AWSCore/Code/Tests/Editor/AWSCoreEditorSystemComponentTest.cpp
- Gems/AWSCore/Code/Tests/Editor/UI/AWSCoreEditorMenuTest.cpp
- Gems/AWSCore/Code/Tests/Editor/UI/AWSCoreResourceMappingToolActionTest.cpp
- Gems/AWSCore/Code/Tests/ResourceMapping/AWSResourceMappingManagerTest.cpp
- Gems/AWSCore/Code/Tools/ResourceMappingTool/README.md
- Gems/AWSCore/Code/Tools/ResourceMappingTool/resource_mapping_tool.py
- Gems/AWSCore/Code/Tools/ResourceMappingTool/tests/unit/utils/test_file_utils.py
- Gems/AWSCore/Code/Tools/ResourceMappingTool/utils/file_utils.py
- cmake/Platform/Common/Install_common.cmake
1. Modify install_common.cmake so install target will include resource mapping tool python code
2. Add log path argument for resource mapping tool so logging file gets generated in project user/log directory while launching from Editor (as tool should not modify files where it is located)
3. Launch python tool with `-B` argument so no .pyc gets generated as install target is expected to run under read-only directory
Manual testing through both general build target and install target, and verified that logging file is generated under project user/log directory
Unit test pass
> [LYN-5268] Copy resource mapping tool to install target and add argument for log path

- Code/Editor/Lib/Tests/test_EditorUtils.cpp
- Code/Editor/Lib/Tests/test_Main.cpp
- Code/Editor/Objects/BaseObject.cpp
- Code/Editor/Objects/BaseObject.h
- Code/Editor/Objects/EntityObject.cpp
- Code/Editor/Objects/EntityObject.h
- Code/Editor/Objects/Gizmo.h
- Code/Editor/Objects/GizmoManager.cpp
- Code/Editor/Objects/LineGizmo.cpp
- Code/Editor/Objects/ObjectLoader.cpp
- Code/Editor/Objects/ObjectLoader.h
- Code/Editor/Objects/ObjectManager.cpp
- Code/Editor/Objects/SelectionGroup.cpp
- Code/Editor/Objects/TrackGizmo.cpp
- Code/Editor/Platform/Windows/Util/Mailer_Windows.cpp
- Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
- Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/ComponentPalette/ComponentPaletteWindow.cpp
- Code/Editor/Plugins/EditorCommon/DockTitleBarWidget.cpp
- Code/Editor/Plugins/FFMPEGPlugin/main.cpp
- Code/Editor/Plugins/ProjectSettingsTool/PlatformSettings_Android.cpp
- Code/Editor/Plugins/ProjectSettingsTool/Validators.cpp
A few 'typedefs' replaced by 'using's
This shouldn't have any functional changes at all, just c++17 modernization
It's a part 2 of a split #2847
*Note to reviewers this is a split PR meant to ease reviewing, but sadly I cannot say if this or any other part will compile correctly in isolation.*
Signed-off-by: Nemerle <nemerle5+git@gmail.com>
> Editor code: tidy up BOOLs,NULLs and overrides pt2.

- AutomatedTesting/Gem/PythonTests/smoke/CMakeLists.txt
The serialize context tools were not being auto built by CI because of
this.
> Fixes incorrect build dependencies for tests

- Tools/LyTestTools/ly_test_tools/benchmark/data_aggregator.py
CI is only available on Jenkins v2.289.1, nightly builds are still run on Jenkins 2.277.4
> fix: Switch local environment detection to depend on BUILD_NUMBER instead of CI

- Code/Framework/AzFramework/Platform/Windows/AzFramework/Input/Devices/Keyboard/InputDeviceKeyboard_Windows.cpp
- Code/Framework/AzFramework/Platform/Windows/AzFramework/Input/Devices/Mouse/InputDeviceMouse_Windows.cpp
The underlying issue was that the mouse and keyboard were being re-registered via RegisterRawInputDevices from the LyShine module. This occurred because the static variable that tracks whether a device has been registered wasn't persisting across dlls.
The RenderViewportWidget, which is used in the Main Editor viewport as well as the UI Editor viewport, creates new input devices when not in game mode in order to handle correct input event ordering between AzFramework input events and Qt events.
> Fix input not working in Ctrl-G mode after UI Editor is opened

- AutomatedTesting/Gem/PythonTests/AWS/CMakeLists.txt
Signed-off-by: junbo <junbo@amazon.com>
Merged the fix from https://github.com/o3de/o3de/pull/2951 since the Stabilization branch is frozen now.
> Stabilization AWSTests.periodic failing on Linux due to a File Not Found error

- Gems/AWSCore/Code/Tools/ResourceMappingTool/tests/unit/utils/test_aws_utils.py
- Gems/AWSCore/Code/Tools/ResourceMappingTool/utils/aws_utils.py
S3 boto3 client always returns all buckets even specify region while configuring client, have to add extra request call to query bucket location and filter results manually
Buckets in Region us-east-1 have a LocationConstraint of null , see https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.get_bucket_location
Pass unit test
> [SPEC-7931] Filter boto3 s3 list_buckets results based on region

- AutomatedTesting/Gem/PythonTests/smoke/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/smoke/test_RemoteConsole_CPULoadLevel_Works.py
- AutomatedTesting/Gem/PythonTests/smoke/test_RemoteConsole_GPULoadLevel_Works.py
Fixed the nullrenderer flag. Added new test that enables the flag with separate CTest registrations. Moved the test from sandbox to smoke suite
> Moving load level test from sandbox to smoke with fixes

- scripts/build/Jenkins/Jenkinsfile
Properly escapes "%" for the build url env var. Will be tested in Jenkins.
> Escape character in Jenkins for test metrics

- AutomatedTesting/Gem/PythonTests/atom_renderer/atom_hydra_scripts/hydra_GPUTest_AtomFeatureIntegrationBenchmark.py
- AutomatedTesting/Gem/PythonTests/atom_renderer/atom_utils/benchmark_utils.py
- AutomatedTesting/Gem/PythonTests/atom_renderer/test_Atom_GPUTests.py
- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/ProfilingCaptureBus.h
- Gems/Atom/Feature/Common/Code/Source/ProfilingCaptureSystemComponent.cpp
- Gems/Atom/Feature/Common/Code/Source/ProfilingCaptureSystemComponent.h
- Tools/LyTestTools/ly_test_tools/benchmark/data_aggregator.py
The CPU times logged are about ~8.2-8.3ms for CullingAndLod and SponzaBenchmark, 16-17ms for AtomFeatureIntegrationBenchmark
The ProfilingCaptureSystem seems to be limited to only take data from a single frame in a single invocation, so calculating statistics of the CPU frame times has been delegated to the Python side after refactoring.
> performance benchmarks: Aggregate and report CPU frame times.

- Code/Tools/SceneAPI/SceneBuilder/Importers/AssImpBoneImporter.cpp
- Code/Tools/SceneAPI/SceneBuilder/Importers/AssImpImporterUtilities.cpp
Import all nodes as bones. O3DE's concept of a bone is different than AssImp's.
Updated GetLocalSpaceBindPoseTransform to only use the offset matrix if the parent is also a bone.
Results:
All test assets I've tried match Blender's "Rest Position" when loaded in the Character tool.
All test animations I've tried work generally as well as they worked before, and a few better. This resolves the issue that was originally opened, an internal test asset loaded the skeleton incorrectly.
Signed-off-by: stankowi <4838196+AMZN-stankowi@users.noreply.github.com>
> Updated skeleton logic:

- Code/Framework/AzCore/AzCore/std/createdestroy.h
- Code/Framework/AzCore/Tests/AZStd/CreateDestroy.cpp
The uninitialized_default_construct and uninitialized_value_construct
functions implementations have been removed and the Standard library
implementations have been brought into the AZStd namespace scope
Closes #2835 
> Converted the AZStd implementations of unintialized construct to use std

- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/ProfilingCaptureBus.h
- Gems/Atom/Feature/Common/Code/Source/ProfilingCaptureSystemComponent.cpp
- Gems/Atom/Feature/Common/Code/Source/ProfilingCaptureSystemComponent.h
- Gems/Atom/RHI/Code/Include/Atom/RHI/CpuProfiler.h
- Gems/Atom/RHI/Code/Include/Atom/RHI/CpuProfilerImpl.h
- Gems/Atom/RHI/Code/Source/RHI/CpuProfilerImpl.cpp
- Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiCpuProfiler.inl
This PR implements capturing multiple frames of CPU profiling data and saving it to disk so that it can be analyzed offline (which will be implemented in the visualizer in a future PR). Now, the ProfilingCaptureSystemComponent offers endpoints for capturing one frame of profiling data (with a blocking IO call) in addition to an arbitrary amount of frames (using an IO thread). 
https://user-images.githubusercontent.com/64656371/127545500-06bed756-0d15-48ff-8966-6ddf402af690.mp4
Resulting file size on disk was 70 MB from ~3000 frames of data.
> [ATOM-16021] Initial continuous capture support 

- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/View.h
- Gems/Atom/RPI/Code/Source/RPI.Public/View.cpp
View SRG would only compile if certain parameters changed on the view, however it was possible to grab the SRG from the view and manually modify it without the changed flag being set on the view. Changing the view to compile SRG every frame (small cost and necessary in some cases anyway) to fix some issues we've been seeing.
> Removing condition from View SRG compilation

- cmake/Platform/Windows/PackagingPostBuild.cmake
The "Latest" tagged installer uploads were failing the file filter because the upload script now collects files as full path before performing the regex.
> [development] updated file regex when uploading latest tagged installer

- AutomatedTesting/Gem/Code/CMakeLists.txt
Since AutomatedTesting contains a MainPipeline.pass file that includes a custom LyShine pass, other tools need to have a runtime dependency on LyShine.
An alternative is to have the Material Editor depend on the same "tools" gems as the main Editor. This is a bigger task however that can be addressed in a separate PR. It requires some code and/or CMakeLists modification in certain gems that don't expect to be running in a tool other than the main Editor (ex. gems that need to be fixed up are EditorPythonBindings and Gestures).
> Add LyShine gem runtime dependency for Material Editor in AutomatedTesting Project

- scripts/build/Platform/Windows/build_config.json
- scripts/build/TestImpactAnalysis/git_utils.py
- scripts/build/TestImpactAnalysis/tiaf_persistent_storage_s3.py
The `missing_ok` parameter for `PathLib`'s `unlink()` method requires Python 3.8+ whereas we currently use version Python 3.7.10. This fix simply makes a call to `is_file()` before calling `unlink()`.
The unrelated commit with the change to the TIAF jenkins job has been OK'd my @amzn-changml offline and fixes the erroneous use of using `!BRANCH_NAME!` instead of `!CHANGE_TARGET!` for the `dst-branch` script parameter. This was causing all PR builds to seed but the fix will now correctly ensure PR builds draw from the appropriate destination branch's TIAF coverage data. Likewise, the archiving of the historical data objects in the S3 persistent storage has been removed as a) this was causing a permissions issue and b) the data in this bucket is no longer human accessible anyway. …
> Fix for PathLib unlink wrong version parameter.

- Gems/Atom/RHI/Code/CMakeLists.txt
- Gems/Atom/RHI/Code/Platform/Linux/renderdoc_linux.cmake
- Gems/Atom/RHI/Code/Platform/Windows/renderdoc_windows.cmake
Temporary workaround for #2990
> Hide RenderDoc integration behind LY_RENDERDOC_ENABLED option

- scripts/build/TestImpactAnalysis/git_utils.py
- scripts/build/TestImpactAnalysis/mars_utils.py
- scripts/build/TestImpactAnalysis/tiaf.py
- scripts/build/TestImpactAnalysis/tiaf_persistent_storage_s3.py
This change list introduces important bug fixes: 
- Previously, the commit distance calculation for PR builds was failing due to the fact that the commits were on different branches, causing the TIAF script to fall back to regular testing. Furthermore, the diff generated for the commits was including the source commit, causing change lists for PR builds to be larger than they should be. This has now been fixed by not calculating the commit distance for PR builds and building the diff from a common ancestor.
- The MARS job document erroneously had the key `src_commit` populated by both the source and destination commit. This has been fixed and the existing MARS data purged accordingly.
- The MARS sequence job document erroneously had the efficiency miscalculated. This is now properly …
> TIAF script fixes

- scripts/build/TestImpactAnalysis/tiaf.py
- scripts/build/TestImpactAnalysis/tiaf_persistent_storage.py
There is a peculiar issue that arises in branch builds from time to time where the last commit hash as retrieved from the S3 storage is the same as the commit hash for the job being built. It does not appear that the problem is occurring client-side yet the alternative explanation of a server-side issue raises yet further questions as there should be no way that a job being run can retrieve its own commit hash from the historic data record in the s3 bucket, unless a job for that commit has already been run (which does not appear to be the case). As a consequence, additional logging and sanity checking has been added to the TIAF scripts to aid in debugging should this problem persist.
> Tiaf scripts logging and sanity checking

- Code/Editor/EditorViewportWidget.cpp
This looks like it might have been a bad merge, but the input was no longer being fully reenabled after game mode.
> Fix for input not being reenabled after game mode

- Gems/EditorPythonBindings/Code/Source/PythonLogSymbolsComponent.cpp
- Gems/EditorPythonBindings/Code/Source/PythonLogSymbolsComponent.h
- Gems/EditorPythonBindings/Code/Source/PythonProxyBus.cpp
- Gems/EditorPythonBindings/Code/Source/PythonProxyObject.cpp
- Gems/EditorPythonBindings/Code/Source/PythonReflectionComponent.cpp
- Gems/EditorPythonBindings/Code/Source/PythonSymbolsBus.h
- Gems/EditorPythonBindings/Code/Source/PythonSystemComponent.cpp
- Gems/EditorPythonBindings/Code/Source/PythonSystemComponent.h
Fixes: Python Console: Script Help opens empty in AutomatedTesting project
When the symbols are reflected, this solution queues the symbols to be logged instead of immediately writes out the symbols to disk. This is because not every use of the Python bindings components write out the PYI symbols such as the Python asset builder (PAB) gem. Previously if the PAB was activated first, the log symbols logic would be skipped. 
This fixes the missing Python symbols in the Editor
This also fixes the PYI files to write out for the AutomatedTesting project
Signed-off-by: Jackson <23512001+jackalbe@users.noreply.github.com>
> {LYN-2336} Fix: Python Console script help opens empty

- Code/Tools/ProjectManager/Source/NewProjectSettingsScreen.cpp
- Code/Tools/ProjectManager/Source/NewProjectSettingsScreen.h
- Code/Tools/ProjectManager/Source/ProjectSettingsScreen.cpp
- Code/Tools/ProjectManager/Source/ProjectSettingsScreen.h
- Code/Tools/ProjectManager/Source/UpdateProjectSettingsScreen.cpp
- Allow manually typing the path in the project location field
- Check for whether the path is absolute
- Automatically generate the path location when using the default path and changing the name only
Fixes #2446 
Signed-off-by: AMZN-alexpete <26804013+AMZN-alexpete@users.noreply.github.com>
> Allow project path changing and auto-completion

- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/AWSGameLiftClientModule.cpp
- Gems/AWSGameLift/Code/AWSGameLiftServer/Source/AWSGameLiftServerModule.cpp
- Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugModule.cpp
It is expected that gem module name match cmake target name
```
ly_add_target(
NAME AWSGameLift.Clients ${PAL_TRAIT_MONOLITHIC_DRIVEN_MODULE_TYPE}
NAMESPACE Gem
```
```
ly_add_target(
NAME AWSGameLift.Servers ${PAL_TRAIT_MONOLITHIC_DRIVEN_MODULE_TYPE}
NAMESPACE Gem
```
```
ly_add_target(
NAME Multiplayer.Debug ${PAL_TRAIT_MONOLITHIC_DRIVEN_MODULE_TYPE}
NAMESPACE Gem
```
> [SPEC-7971] Update gem module name to match cmake target name

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/NotificationWindow.cpp
Fixes #2496 
The EMFX toast notifications were using the Qt::Popup window flag, which makes them modal, which in turn blocks input while they are visible. I changed the window flags instead to be window and stay on top, so it will still get the same behavior as a modal without actually being modal.
> Prevent EMFX notifications from being modal, which was blocking input while visible.

- Gems/LyShine/Code/Editor/Animation/UiAnimViewAnimNode.cpp
Turns out there was another change needed for https://github.com/o3de/o3de/pull/3046
> Fixed Signed/Unsigned Mismatch fix in LyShine UiAnimViewAnimNode.cpp

- Code/Editor/EditorViewportWidget.cpp
- Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
- Code/Editor/Viewport.cpp
- Code/Editor/Viewport.h
Fixes #2498 
Updated the logic when creating entities via the right-click menu in the viewport to use the same hit detection as dragging/dropping into the viewport from the Asset Browser.
NOTE: The previous logic being used for ViewToWorld currently has all of the input params for hit test as unused, so I'm guessing we are deprecating this function, from a quick search it looks like mostly legacy editor stuff (Editor/Objects) for CBaseObject is what is using those calls. If we do want to go the route of fixing that API so it works though I'm open to that.
Also fixed a warning message due to an argument being passed to tr() that wasn't formatted to take any arguments as input anymore.
> Fixed creating entities in the viewport logic to use hit test detection.

- scripts/build/TestImpactAnalysis/tiaf.py
- scripts/build/TestImpactAnalysis/tiaf_persistent_storage.py
- scripts/build/TestImpactAnalysis/tiaf_persistent_storage_local.py
- scripts/build/TestImpactAnalysis/tiaf_persistent_storage_s3.py
Fix for corner case where:
1. TIAF was already run previously for a given commit.
2. There was no last commit hash when TIAF last ran on said commit due to no coverage data existing get for the branch.
3. TIAF has not been run on any other commits between the run for said commit and the last run for said commit.
The above results in TIAF being stuck in a state of generating an empty change list (and thus doing no work) until another commit comes in. This is problematic if the TIAF needs to be re-run for whatever reason on said commit under these conditions.
The fix stores the last commit hash (if any) used for the TIAF run on every commit. When a sequence is re-run for a given commit **and** TIAF has not been run on any subsequent commits (if any) TIAF will attempt to use the last commit …
> Address commit re-run corner case.

- Code/Tools/ProjectManager/Source/ProjectUtils.cpp
Changed "Coping file" to "Copying file" in ProjectUtils.cpp
resolves #2926
> Typo fix in duplicate project progress window

- Code/Tools/ProjectManager/Source/Application.cpp
A white bar appeared at the bottom of the Project Manager on start-up until the window was resized.
> Fix issue with white bar on bottom of Project Manager

- AutomatedTesting/Gem/PythonTests/atom_renderer/atom_hydra_scripts/hydra_GPUTest_LightComponent.py
- Small mistake on my part, forgot to update the atom_component_helpers.LIGHT_TYPES call to atom_constants.LIGHT_TYPES since I had to move the non-hydra stuff to a separate module.
> Fixes AttributeError in Light Component GPU test.

- Code/Framework/AzCore/AzCore/EBus/Event.h
- Code/Framework/AzCore/AzCore/EBus/Event.inl
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.cpp
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.h
- Code/Framework/AzCore/Tests/EventTests.cpp
- Added a `StealHandlers` function to AZ::Event to allow one event to "steal" all the handlers from another event.
- Split the Settings Registry mutex out to a setting modification mutex and a notification event mutex
- Wrapped the Settings Registry notification event signaling into a function that uses a lock and swap algorithm to allow signaling connected event handlers without having any mutex locked
- Added more fine-grained locking of the Settings Registry modification mutex to reduce lock time.
resolves #3066
> Settings registry notification deadlock fix

- cmake/Tools/Platform/Android/android_support.py
Fixes #3117
**Root Cause**
There are 2 custom tasks that occur during the android gradle build:
* syncLYLayoutMode{config}
Use the layout tool to sync the android assets (through a directory junction) from `app\src\main\assets` to the android cache files for a project
* copyNativeArtifacts{config}
Copy files from the Registry in the build output folder to the same `app\src\main\assets`
If `copyNativeArtifacts` occurs before `syncLYLayoutMode`, then what happens is that the .setreg files are copied into `app\src\main\assets` just fine, but when `syncLYLayoutMode` task is executed, it will wipe out the `app\src\main\assets` folder and replace it with the directory junction.
The original build.gradle script for app did not declare a rule that `copyNativeArtifacts` must occur after …
> Fix android gradle scripts to prevent `cmake_dependencies.<game>.<game>_gamelauncher` from being wiped out of the APK

- Gems/Atom/Utils/Code/Include/Atom/Utils/StableDynamicArray.h
Fixes the following error
```
In file included from /src/github/o3de-atom-sampleviewer/Gem/Code/Source/SkinnedMeshContainer.cpp:9:
In file included from /src/github/o3de-atom-sampleviewer/Gem/Code/Source/SkinnedMeshContainer.h:15:
In file included from /src/github/o3de/Gems/Atom/Feature/Common/Code/Include/Atom/Feature/SkinnedMesh/SkinnedMeshFeatureProcessorInterface.h:10:
In file included from /src/github/o3de/Gems/Atom/Feature/Common/Code/Include/Atom/Feature/SkinnedMesh/SkinnedMeshRenderProxyInterface.h:11:
/src/github/o3de/Gems/Atom/Utils/Code/Include/Atom/Utils/StableDynamicArray.h:166:9: error: no template named 'aligned_storage_t' in namespace 'AZStd'; did you mean 'std::aligned_storage_t'?
AZStd::aligned_storage_t<PageSize, alignof(T)> m_data; ///< aligned storage for all the …
```
> Fix Non-Unity compile error with Atom Sample Viewer and the Atom Gem

- Gems/PhysX/Code/Source/BallJointComponent.cpp
- Gems/PhysX/Code/Source/FixedJointComponent.cpp
- Gems/PhysX/Code/Source/HingeJointComponent.cpp
- Gems/PhysX/Code/Source/Joint/PhysXJointUtils.cpp
- Gems/PhysX/Code/Tests/PhysXJointsTest.cpp
Fixes #2474 
Also fixed joint global constraints when no lead entity was selected
Added tests for global constraints on ball and hinge joints.
> fixed joint crash when no lead entity is selected

- Gems/Atom/RHI/Code/Include/Atom/RHI/CpuProfiler.h
- Gems/Atom/RHI/Code/Include/Atom/RHI/CpuProfilerImpl.h
- Gems/Atom/RHI/Code/Source/RHI/CpuProfilerImpl.cpp
This PR adds a new profiling macro, `AZ_ATOM_PROFILE_DYNAMIC` to allow for region names determined at runtime. The main challenge here was finding a way to guarantee the lifetime of `GroupRegionName` objects, as they previously were static. I added members to `CpuProfilerImpl` to store `GroupRegionNames` and their corresponding region names. This storage is not garbage collected since `GroupRegionName` passes everything around through raw pointer, I did include a warning if the storage gets large.
Completes ATOM-15954
> Profiler: Runtime region name support

- AutomatedTesting/Gem/PythonTests/atom_renderer/atom_hydra_scripts/hydra_AtomEditorComponents_AddedToEntity.py
- AutomatedTesting/Gem/PythonTests/atom_renderer/test_Atom_MainSuite.py
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/RadiusWeightModifier/EditorRadiusWeightModifierComponent.cpp
Fixes #3106 
Updated Radius Weight Modifier component name to be consistent with the other related components. Verified existing levels with this component still load as expected.
> Updated Radius Weight Modifier component name for consistency.

- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
Appending is standard and preferred but the tabs elide from the end (instead of middle) and cut it off
> AtomTools: prepend asterisk to denote modified document tabs

- AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/README.txt
- AutomatedTesting/Gem/PythonTests/editor/EditorScripts/AssetPicker_UI_UX.py
- AutomatedTesting/Gem/PythonTests/editor/EditorScripts/BasicEditorWorkflows_LevelEntityComponentCRUD.py
- AutomatedTesting/Gem/PythonTests/editor/EditorScripts/Menus_EditMenuOptions.py
- AutomatedTesting/Gem/PythonTests/editor/EditorScripts/Menus_FileMenuOptions.py
- AutomatedTesting/Gem/PythonTests/editor/EditorScripts/Menus_ViewMenuOptions.py
- AutomatedTesting/Gem/PythonTests/scripting/Pane_PropertiesChanged_RetainsOnRestart.py
- AutomatedTesting/Gem/PythonTests/smoke/Editor_NewExistingLevels_Works.py
- Gems/QtForPython/Editor/Scripts/tests/log_main_window.py
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Entity/EntityNodes.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Math/TransformNodes.h
Fixes #3138 
Replaced some Lumberyard references in Script Canvas tooltips and some comments with O3DE.
> Replaced some Lumberyard references with O3DE.

- Gems/PhysX/Code/Source/EditorColliderComponent.cpp
- Gems/PhysX/Code/Source/EditorColliderComponent.h
> Fixes #2796 Collider retains phys mesh asset reference after changing to shape

- Code/Framework/AzFramework/Platform/Windows/AzFramework/Windowing/NativeWindow_Windows.cpp
Make sure WM_WINDOWPOSCHANGED bubbles up so that we can see WM_SIZE.
> Fix NativeWindow_Windows returning the wrong size.

- Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.cpp
I'm still digging into why this is a problem, but additional error messaging is useful for now.
Signed-off-by: stankowi <4838196+AMZN-stankowi@users.noreply.github.com>
> Better error reporting on mixing skinned and unskinned meshes.

- Gems/Atom/Asset/Shader/Code/Source/Editor/CommonFiles/Preprocessor.cpp
- Gems/Atom/Asset/Shader/Code/Source/Editor/CommonFiles/Preprocessor.h
- Gems/Atom/Asset/Shader/Code/Tests/McppBinderTests.cpp
- Gems/Atom/Asset/Shader/Code/atom_asset_shader_builders_tests_files.cmake
[ATOM-13679] ShaderAssetBuilder: Create UnitTest To Validate
STDOUT Data Capture From MCPP
azvsnprintf was being used improperly, in particular
in windows if the data to print was larger than the
local buffer in the stack, then azvsnprintf returns -1.
Also azvsnprintf needs a +1 in buffer size to accomodate for
the '\0' character at the end and that was not done.
Added UnitTest to validate all cases:
1. Data to print is smaller than the local buffer.
2. Data to print is the same size as the local buffer.
3. Data to print is bigger than the local buffer.
Signed-off-by: garrieta <garrieta@amazon.com>
> [ATOM-13679] ShaderAssetBuilder: Create UnitTest To Validate

- Gems/LyShine/Code/Source/UiCanvasFileObject.h
An asset filter was being applied when loading a UI canvas from stream to ignore all assets other than Slices and Lua scripts, so script canvas assets were not being preloaded. The fix is to remove the filter and allow all asset types to go through.
We don't want Asset Processor to load unnecessary assets such as textures, but this doesn't happen because the UI canvas builder passes in a custom filter to only load slice assets when it loads the UI canvas for building.
> Fix script canvases not loading if on a UI canvas element

- scripts/build/Jenkins/Jenkinsfile
- scripts/build/Platform/Windows/build_config.json
- scripts/build/Platform/Windows/pipeline.json
Allow customized Jenkins parameters for different pipelines so that we can define different Jenkins parameters for a new pipeline and doesn't affect AR build parameters.
Add aws integration deployment pipeline.
> Allow customized Jenkins parameters for different pipelines and add aws integration deployment pipeline

- Code/Editor/Lib/Tests/test_ViewportManipulatorController.cpp
This fixes a link error on Mac
> Move static variable initialization out of class definition

- Code/Tools/SceneAPI/SceneCore/Utilities/DebugOutput.cpp
- Code/Tools/SceneAPI/SceneCore/Utilities/DebugOutput.h
- Gems/SceneProcessing/Code/Source/SceneBuilder/SceneBuilderWorker.cpp
- Gems/SceneProcessing/Code/Source/SceneBuilder/SceneBuilderWorker.h
Moved BuildDebugSceneGraph out of SceneProcessing gem and into DebugOutput class to allow the function to be shared, which ensures the same dbgsg format is outputted among any calls to the function.
> Move BuildDebugSceneGraph function out of SceneProcessing gem

- Code/Framework/AzCore/AzCore/Component/ComponentApplication.cpp
- Code/Framework/AzCore/AzCore/Console/Console.cpp
- Code/Framework/AzCore/AzCore/Console/Console.h
- Code/Framework/AzCore/AzCore/Console/IConsole.h
- Code/Framework/AzCore/AzCore/Module/Module.h
- Code/Framework/AzCore/Tests/Console/ConsoleTests.cpp
An AZ Console instance will now store any console commands that could be
dispatched from a configuration file into a deferred queue, that can be
invoked later.
This can be used to defer execution of console commands in configuration files such as
.cfg, .setreg and .setregpatch files that are defined in gem modules that
have not been loaded yet.
The defered execution can then be invoked at any point later in the
application
Updated the Component Application CreateCommon function to invoke deferred console commands
after all the gems have loaded
fixes #2062
> Added a deferred queue to the AZ Console class

- cmake/TestImpactFramework/LYTestImpactFramework.cmake
This fixes the bug where existing TIAF static artifacts were not being removed prior to being generated, resulting in target deletions to erroneously result in integrity errors due to the dynamic dependency map attempting to remove a source file that still exists in a build target (it doesn't, it's just that the deleted build target's source-to-target mapping artifact was still there, causing it to be parsed by the TIAF runtime).
> Erase existing artifacts before generating new artifacts.

- Gems/LmbrCentral/Code/Source/Scripting/EditorTagComponent.cpp
Fixes #3313 
Allow Tag components to be added to UI elements for ease of use. This allows the user another way of accessing UI elements instead of only by name.
Here is a simple Script Canvas example of showing elements by tag at different time delays:
> Allow Tag components to be added to UI elements.

- Code/Framework/AzCore/AzCore/azcore_files.cmake
> Adding missing AssetManager_private.h header to cmake

- Gems/Atom/Feature/Common/Assets/Scripts/material_find_overrides_demo.lua
- Gems/Atom/Feature/Common/Assets/Scripts/material_property_overrides_demo.lua
- Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/MaterialComponentBus.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
There were issues creating scripts in script canvas using the material component related buses. 
Material component bus functions used AZ name to look up material property names. Script canvas did not support editing these in nodes or the inspector. These were replaced with AZStd string.
Script canvas did not support AZStd any. Explicit functions had to be added to access and modify material properties with specified types.
There is still a known issue where script canvas will currently only allow selecting dynamic slice assets.
> AtomTools: better script canvas support for material component 

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Application/AtomToolsApplication.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/main.cpp
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/main.cpp
Atom tools launch or check for the existence of a local server in order to prevent multiple application processes from running. These checks were being done far too late, after initialization and asset processing, leaving time for multiple processes to start before the server or checks. Zombie processes could start and run indefinitely without user interaction because the event loop was being entered despite the request to exit the application early.
These changes launch the server and checks immediately after the application object is constructed and exit before any other work is done if the application will not be run.
> AtomTools: fix multiple material editor processes launching

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/ComponentPalette/ComponentPaletteWidget.cpp
Fixes #3336 
When performing the search filter on the component palette, include the category name in the match instead of just the component name.
> Include the category name when performing search in the component palette.

- scripts/build/Jenkins/Jenkinsfile
Adds logging for `CHANGE_ID` and `COMMIT_ID` to facilitate cross-referencing between Jenkins and TIAF for unexpected `CHANGE_ID` values in TIAF.
> Add extra logging for CHANGE_ID and COMMIT_ID.

- Gems/Multiplayer/Code/Include/Multiplayer/NetworkEntity/INetworkEntityManager.h
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
- Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp
- Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.h
(on non-dedicated servers)
-Exposes an AutoActivate flag to INetworkEntityManager and ensured it got respected for all paths
-Tweak SpawnDefaultPlayerPrefab to not immediately activate its spawned entity to allow SetAllowAutonomy to be picked up from the net bind component during component activation
> Ensure network autonomy gets set before entity activation

- Code/Legacy/CrySystem/XConsole.cpp
Fixes #3357 
There was a change recently that switched CXConsole::GetSortedVars from inserting into the input array to push_back, and almost all usages of GetSortedVars would do a resize on count before invoking, so you would wind up with a vector of empty strings for the first half, and the actually variables in the second half. Instead of updating all the usages of GetSortedVars (since this is legacy code anyways), just updated it to do a clear before it starts appending to the vector.
> Fixed console variables crash.

- Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.h
- Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Header.jinja
- Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Source.jinja
Fixing compiler error.  Multiplayer Auto Components will forward decl their corresponding Controller for a use with unique_ptr.  The unique_ptr destructor (which is called during the component's destruction) needs the complete type, but the component's ~ was defined inside the .h where controller is still an incomplete type.  Moved Multiplayer Auto Component destructor to cpp (which #includes the controller) so that when it comes time to destroy the unique_ptr<Controller> it can do so on a complete type. 
Plus sneaking in minor spelling fix.
> Fix Multiplayer AutoComponent Delete Incomplete Type Compile Error 

- Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Header.jinja
- Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Source.jinja
DefineRpcInvocations requires the ControllerBase not the ComponentBase (see the other usages of DefineRpcInvocations). This fixes issues with Server to Authority RPCs where GetParent is undefined due to the wrong base type.
> Fix type error with Server to Authority RPC generation

- Tools/LyTestTools/tests/unit/test_builtin_helpers.py
There was a random failure in the unit tests because of a new _find_project_json() function in the AbstractResourceLocator class that needs to be mocked in a test that is dependent on that class. Tested by running unit tests locally and verifying that the function in question is mocked properly.
> fixes a flaky lytesttools unit test

- Gems/Atom/Bootstrap/Code/CMakeLists.txt
- Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp
- Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.h
- Gems/Atom/Bootstrap/Code/Source/Platform/Android/BootstrapSystemComponent_Traits_Platform.h
- Gems/Atom/Bootstrap/Code/Source/Platform/Android/bootstrap_android_files.cmake
- Gems/Atom/Bootstrap/Code/Source/Platform/Linux/BootstrapSystemComponent_Traits_Platform.h
- Gems/Atom/Bootstrap/Code/Source/Platform/Linux/bootstrap_linux_files.cmake
- Gems/Atom/Bootstrap/Code/Source/Platform/Mac/BootstrapSystemComponent_Traits_Platform.h
- Gems/Atom/Bootstrap/Code/Source/Platform/Mac/bootstrap_mac_files.cmake
- Gems/Atom/Bootstrap/Code/Source/Platform/Windows/BootstrapSystemComponent_Traits_Platform.h
- Gems/Atom/Bootstrap/Code/Source/Platform/Windows/bootstrap_windows_files.cmake
- Gems/Atom/Bootstrap/Code/Source/Platform/iOS/BootstrapSystemComponent_Traits_Platform.h
- Gems/Atom/Bootstrap/Code/Source/Platform/iOS/bootstrap_ios_files.cmake
- Gems/Atom/Feature/Common/Assets/Passes/LowEndRenderPipeline.azasset
- Gems/Atom/RHI/Metal/Code/Source/RHI/ArgumentBuffer.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/ArgumentBuffer.h
- Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/CommandListBase.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/CommandListBase.h
- Gems/Atom/RHI/Metal/Code/Source/RHI/NullDescriptorManager.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/ShaderResourceGroup.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/ShaderResourceGroup.h
- Use low end pipeline on mobile by default for BootStrapComponent (via Palification)
- Track the need to bind null heap within Argument buffers
- Only bind the null heap if its needed
- Track its usage for Vertex/Fragment stages
- Increase null dummy buffer to 1K to address GPU crash oon thee first frame
> Atom starter game ios fixes

- Gems/Atom/Feature/Common/Code/Source/CoreLights/CapsuleLightFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/Decals/DecalFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArrayFeatureProcessor.cpp
- Gems/Atom/RHI/Code/Include/Atom/RHI/BufferPool.h
- Gems/Atom/RHI/Code/Source/RHI/BufferPool.cpp
- Gems/Atom/RHI/Code/Source/RHI/BufferPoolBase.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI/IndirectBufferSignature.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI/QueryPool.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI/QueryPool.h
- Gems/Atom/RHI/Null/Code/Source/RHI/BufferPool.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Buffer/Buffer.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Buffer/BufferSystem.cpp
- Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiGpuProfiler.inl
Fixes asserts related to buffer allocation using null rhi
Fixes GPU crashes when releasing Indirect draw and query related dx12 objects
Fixes imgui profiler related to viewing buffer allocations
Removed buffer update related asserts from RPI as they can happen within RHI
> Multiple RHI related fixes as described below

- Code/Legacy/CrySystem/SystemInit.cpp
This allows the CVars declared in CrySystem module to execute commands
invoked before it was loaded.
This is particularly useful for the load level command.
For example the load level command can be placed in a setreg file
```JSON
{
"Amazon": {
"AzCore": {
"Runtime": {
"ConsoleCommands": {
"LoadLevel": "Levels/main/main.spawnable"
}
}
}
}
}
```
resolves #2062
> Updated the CrySystem module to execute deferred console commands

- Gems/Atom/RHI/Code/Include/Atom/RHI/CpuProfilerImpl.h
- Gems/Atom/RHI/Code/Source/RHI/CpuProfilerImpl.cpp
- Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiCpuProfiler.h
- Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiCpuProfiler.inl
This PR implements the second half of saved capture deserialization. The main challenge here was figuring out a way to deserialize the thread id, since we're pulling an integral value from disk (which is fine for some platforms) but others require thread ids to be pointers. I swapped out using `AZStd::thread_id` for just a simple `size_t` that we get from hashing the thread id, tested deserialization + normal use and everything works the same. This pattern is repeated in other places throughout the codebase so it should be platform safe. 
Also includes some minor fixes throughout the visualizer to get rid of fudge factors and do a little optimization.
> Visualizer: finish deserialization of captures

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentMainWindow.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Window/AtomToolsMainWindow.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_files.cmake
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorWindow.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorWindow.h
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.cpp
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.h
- this change consolidates and cleans up the remaining common code between the material editor and shader management console main window classes
- all code that integrates the document system with the main window lives in AtomToolsDocumentMainWindow
- AtomToolsDocumentMainWindow was basically a copy of what remained from the material editor main window with a few virtual functions replacing material editor specific logic 
- there should not be any functional changes in either application, just significantly less divergent code that needs to be tested, and less code needed to create a new multi document application with tabbed views
> AtomTools: moved remaining document and window common code from ME and SMC to base class

- Code/Framework/AzFramework/AzFramework/Physics/Collision/CollisionGroups.cpp
- Code/Framework/AzFramework/AzFramework/Physics/Collision/CollisionGroups.h
- Code/Framework/AzFramework/AzFramework/Physics/Collision/CollisionLayers.h
- Gems/PhysX/Code/Include/PhysX/UserDataTypes.h
- Gems/PhysX/Code/Include/PhysX/UserDataTypes.inl
* Added a helper function for constructing CollisionGroup from CollisionGroups::Id. 
* Removed remaining touch bending related code
Signed-off-by: pereslav <pereslav@amazon.com>
> Added a helper function for constructing CollisionGroup from CollisionGroups::Id. Removed remaining touch bending related code

- scripts/build/Jenkins/Jenkinsfile
- scripts/build/Platform/Windows/build_config.json
- scripts/build/Platform/Windows/pipeline.json
1. Fix PIPELINE_ENV override issue in multi-steps pipeline, if a build configuration contains multiple steps, each step was using parent configuration's PIPELINE_ENV override, now it will use PIPELINE_ENV override defined in each step's configuration.
2. Add a new pipeline env "NONBLOCKING_STEP" to allow a multi-steps pipeline proceed to next step if current step fails.
3. Make AWS integration deployment as a non-blocking upstream step of periodic_test step in nightly pipeline.
> Add awsi deployment as a non-blocking step in nightly pipeline

- Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/Taa.azsl
This helps prevent ringing artifacts in high contrast areas while in motion. Due to Catmull-Rom's use of negative weights, it's possible to have a very high value neighbor sample with a negative weight completely overwhelm the result leading to a negative output. This change reduces the sharpness of the catmull rom filter in high contrast areas so the negative weights contribute less to the final result.
Due to the changes to use float3 instead of float4 in SampleCatmullRom5Tap(), the performance of TAA actually improves by about 10%.
Before:
After:
> Adjust the sharpness of TAA's Catmull-Rom filter based on local area luminance

- Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/CoreLights/AreaLightComponentConfig.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/CoreLights/DirectionalLightComponentConfig.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/AreaLightComponentConfig.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DirectionalLightComponentConfig.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorAreaLightComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorDirectionalLightComponent.cpp
The editor slider for the softening boundary width is not correct. It goes gray and not selectable for combinations that should be selectable.
Basically we want it always on for ESM, or ESM+PCF options since it controls the ESM filter kernel size.
For PCF, we ONLY want it on when using boundary search. Bicubic doesn't use it. Also, no-filtering doesn't use it either.
Tested all the above combinations for both directional and area lights.
> Fixing the softening boundary width editor options

- Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableSystemComponent.cpp
RootSpawnable was meant to replace the level system but the update to the level system never quite reached the point where that fully worked. There's just too much legacy code to go over.
LYN-4146
> Disabling RootSpawnable warning

- Code/Framework/AzNetworking/AzNetworking/AutoGen/AutoPacketDispatcher_Header.jinja
- Code/Framework/AzNetworking/AzNetworking/AutoGen/AutoPacketDispatcher_Inline.jinja
- Code/Framework/AzNetworking/AzNetworking/ConnectionLayer/IConnectionListener.h
- Code/Framework/AzNetworking/AzNetworking/PacketLayer/IPacketHeader.h
- Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpConnection.cpp
- Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpConnection.h
- Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpFragmentQueue.cpp
- Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpFragmentQueue.h
- Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpNetworkInterface.cpp
- Code/Framework/AzNetworking/Tests/TcpTransport/TcpTransportTests.cpp
- Code/Framework/AzNetworking/Tests/UdpTransport/UdpTransportTests.cpp
- Gems/Multiplayer/Code/Source/AutoGen/Multiplayer.AutoPackets.xml
- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.cpp
- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.h
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
This change adds a mechanism for users to designate packets as part of a handshake such that
- Handlers for said packets must implement an IsHandshakeComplete
- Packets designated as HandshakePackets are always processed
- Packets which are not and are received while IsHandshakeComplete returns false, will be skipped (and ultimately retried)
- This is only applicable at the Handler scope, so MultiplayerSystemComponent can have different requirements than MultiplayerEditorConnection as an example
As part of this, this changes DispatchPacket and related functions from returning a bool to the enum PacketDispatchResult which has values for Success, Pending and Failure. Success and Failure map to what was true and false. Pending indicates that a datum should be skipped and retried.
This is …
> Move packet dispatch to return an enum that includes a pending option

- Gems/AWSGameLift/Code/AWSGameLiftServer/CMakeLists.txt
- Gems/AWSGameLift/Code/AWSGameLiftServer/Include/Request/IAWSGameLiftServerRequests.h
- Gems/AWSGameLift/Code/AWSGameLiftServer/Source/AWSGameLiftServerManager.cpp
- Gems/AWSGameLift/Code/AWSGameLiftServer/Source/AWSGameLiftServerManager.h
- Gems/AWSGameLift/Code/AWSGameLiftServer/Source/AWSGameLiftServerSystemComponent.cpp
- Gems/AWSGameLift/Code/AWSGameLiftServer/Source/AWSGameLiftServerSystemComponent.h
- Gems/AWSGameLift/Code/AWSGameLiftServer/Tests/AWSGameLiftServerManagerTest.cpp
- Gems/AWSGameLift/Code/AWSGameLiftServer/Tests/AWSGameLiftServerSystemComponentTest.cpp
- Gems/AWSGameLift/Code/AWSGameLiftServer/awsgamelift_server_files.cmake
As title descriped, add server public interface so multiplayer developer can decide when to notify server process on GameLift instance is ready.
Pass unit test coverage 92% without gamelift sdk wrapper
Pass manual local testing with GameLiftLocal
> [LYN-4065] Expose GameLift server api to notify server process ready

- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/BicubicPcfFilters.azsli
- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/DirectionalLightShadow.azsli
- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/ReceiverPlaneDepthBias.azsli
- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/DirectionalLightFeatureProcessorInterface.h
- Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/CoreLights/DirectionalLightBus.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/CoreLights/DirectionalLightComponentConfig.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DirectionalLightComponentConfig.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DirectionalLightComponentController.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DirectionalLightComponentController.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorDirectionalLightComponent.cpp
Adding a technique called "receiver plane bias" to the directional shadows. (http://web.archive.org/web/20120209060144/http://developer.amd.com/media/gpu_assets/Isidoro-ShadowMapping.pdf)
This technique reduces shadow acne with large pcf kernels and steep angles between the light and the surface being shaded.
The cost is a few ddx/ddy to estimate the surface geometry and a few ALU instructions.
I also made this a shader option with a checkbox in the editor so the GPU cost can be removed if the feature is turned off.
My observation is that normal offset biasing (which will come after this task) greatly benefits from using this technique in conjunction.
> Adding receiver plane bias to directional shadows

- Code/Tools/ProjectManager/Resources/ProjectManager.qss
- Code/Tools/ProjectManager/Source/ProjectButtonWidget.cpp
- Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
- Code/Tools/ProjectManager/Source/ScreensCtrl.h
Image right after starting O3DE.exe
Fixes issue similar to this: https://github.com/o3de/o3de/issues/3630
Also adds tooltip to the project name that displays the path.
Also fixes issues where project buttons would fail to be found when changing their status because of different path separators.
Also fixed an issue where project buttons weren't deleted when they should be, 
closes #3629
> Remove Tab Overlay on Project Manager Startup + More Fixes

- Code/Framework/AzGameFramework/AzGameFramework/Application/GameApplication.cpp
- Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/PlatformLimitsDescriptor.h
- Gems/Atom/RHI/Code/Source/RHI.Reflect/PlatformLimitsDescriptor.cpp
- Gems/Atom/RHI/Code/Source/RHI/RHISystem.cpp
- Gems/Atom/RHI/DX12/Code/Include/Atom/RHI.Reflect/DX12/PlatformLimitsDescriptor.h
- Gems/Atom/RHI/DX12/Code/Source/RHI.Reflect/PlatformLimitsDescriptor.cpp
- Gems/Atom/RHI/Registry/PhysicalDeviceDriverInfo.setreg
- Gems/Atom/RHI/Registry/Platform/Android/PlatformLimits.setreg
- Gems/Atom/RHI/Registry/Platform/Linux/PlatformLimits.setreg
- Gems/Atom/RHI/Registry/Platform/Mac/PlatformLimits.setreg
- Gems/Atom/RHI/Registry/Platform/Windows/PlatformLimits.setreg
- Gems/Atom/RHI/Registry/Platform/iOS/PlatformLimits.setreg
Changed path Amazon to O3DE. Fixed issues that setreg is not loaded in game launchers.
> ATOM-16346 Change Atom setreg path

- Code/Editor/Controls/ConsoleSCB.cpp
- Code/Editor/CryEdit.cpp
- Code/Editor/CryEditPy.cpp
- Code/Framework/AzCore/AzCore/Debug/Trace.cpp
- Code/Framework/AzCore/AzCore/Debug/Trace.h
- Code/Framework/AzCore/Platform/Common/Apple/AzCore/Debug/Trace_Apple.cpp
- Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/Debug/Trace_UnixLike.cpp
- Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/Debug/Trace_WinAPI.cpp
- Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
Adds the following command line arguments
--wait-for-debugger: This will make the Editor wait until the debugger has been attached, this check happens at the earliest stage possible
--attach-debugger: It will prompt the VS debugger to attach to the user:
These debugger attachment utilities can also called anytime in python scripts via:
general.wait_for_debugger() and general.attach_debugger()
Also, tests using the new framework can just mark the test to be debugged via configurable param.
Example:
```
class C111111_RigidBody_EnablingGravityWorksUsingNotificationsPoC(EditorSharedTest):
attach_debugger = True
from . import C111111_RigidBody_EnablingGravityWorksUsingNotificationsPoC as test_module
```
> Added debugger attachment utilities to the engine, fixed crash when showing console variables, improvements to timeout handling and small cleanup

- Gems/Blast/Code/Source/Components/BlastFamilyComponent.h
The reflection `Field` function didn't register `Asset<BlastAsset>` class type correctly due to being 'const'.
When running the editor it doesn't crash because the editor blast family component does register the type correctly, since it also has a `Asset<BlastAsset>`, bit not const. But when running the launcher the type doesn't get registered to the generic uuid map and then later it's not able to deserialize it, causing the blast family component to assert.
> Fixed blast asset reflection

- Code/Tools/ProjectManager/Resources/ProjectManager.qss
Fixed the "Edit Project Settings:" text so that the descender are not cut off.
> Fix text descenders cutoff on Configure Gems page.

- Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/Outliner/EntityOutliner.qss
- Code/Editor/Style/NewEditorStylesheet.qss
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutliner.qss
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/LevelRootUiHandler.cpp
-Fix a missing QPainter::restore call
-Remove 0px font sizes from our qss, which was just getting ignored by Qt and triggering a warning
> Fix some Qt runtime warnings

- scripts/build/Jenkins/Jenkinsfile
Do not submit until https://github.com/aws-lumberyard/o3de-mars/pull/21 is submitted.
Adds the benchmark script to the AR pipeline. Manual runtime of script is 264ms. The benchmark upload stage will also be non blocking on failure.
> Adds the MARS benchmark script in AR

- Gems/ScriptCanvas/Code/Editor/Nodes/NodeCreateUtils.cpp
- Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Core.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Core.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Serialization/DatumSerializer.cpp
When users write graphs that use the AZ::Event mechanism, the input into their "connect to AZ::Event" nodes can't be serialized in Json. This is now fixed.
> hot fix for json AZ::Event (as input into nodes) serialization

- scripts/build/Jenkins/Jenkinsfile
Send build failure root cause data to SNS topic that triggers lambda function to automatically create Github issues.
> Auto-cut Github issue on build failures from main/development

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
Writing `MeshComponentController::GetLocalBounds` the same way as `MeshComponentController::GetWorldBounds` to check the `aabb` is correct before doing operations to it.
> Fixed assert: Avoid doing operations over invalid Aabb

- .github/ISSUE_TEMPLATE/nightly_build_failure_bug_template.md
Signed-off-by: mcphedar <mcphedar@amazon.com>
This template will be used for nightly build failure reporting.
> Adding a template for nightly build failures

- cmake/3rdParty/Platform/Android/BuiltInPackages_android.cmake
- cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake
- cmake/3rdParty/Platform/Mac/BuiltInPackages_mac.cmake
- cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
- cmake/3rdParty/Platform/iOS/BuiltInPackages_ios.cmake
The previous version of the package was dynamic on some platforms,
and static on others.  This makes it static across the board and
also makes it compatible with other 3p libraries wanting to use
zlib.
> Updates zlib to rev2 of the package, static only

- Gems/LyShine/Code/CMakeLists.txt
- Gems/Terrain/Code/CMakeLists.txt
- Templates/DefaultGem/Template/Code/CMakeLists.txt
Removes the OUTPUT_NAME from the .Editor target in the Gem template.
Removes the same from Gems that have it currently.
relates #3189
> Fix the DefaultGem template's Editor target

- Code/Framework/AzCore/AzCore/Debug/Trace.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/Conversions.cpp
- Fixed error in iOS profile non-unity build `error: unused variable 'INVALID_OFFSET'`. The global variable is static const only visible to the cpp, removed since it's not used.
- Fixed error in windows release `'timeoutSeconds': unreferenced formal parameter`
> Fixed unused variable warnings

- cmake/Platform/Common/RuntimeDependencies_common.cmake
Mac needs this path to fix the library load paths using install name tool for libraries that depend on Python.
> Set target_file variable since it's still being used in Mac runtime dependencies cmake file

- Code/Editor/EditorPreferencesDialog.cpp
- Code/Editor/EditorPreferencesPageViewportGizmo.cpp
- Code/Editor/EditorPreferencesPageViewportGizmo.h
- Code/Editor/EditorViewportSettings.cpp
- Code/Editor/EditorViewportSettings.h
- Code/Editor/EditorViewportWidget.cpp
- Code/Editor/IEditorImpl.cpp
- Code/Editor/Objects/ObjectManager.cpp
- Code/Editor/PreferencesStdPages.cpp
- Code/Editor/Settings.cpp
- Code/Editor/Settings.h
- Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/ViewportInteraction.h
- Code/Framework/AzManipulatorTestFramework/Source/ViewportInteraction.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/EditorVertexSelection.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/ManipulatorView.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/ScaleManipulators.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/ScaleManipulators.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/TranslationManipulators.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/TranslationManipulators.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportMessages.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/RenderViewportWidget.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorPolygonPrismShapeComponentMode.cpp
- Gems/PhysX/Code/Editor/EditorSubComponentModeAngleCone.cpp
Resolves #3579 and Fixes #2425
This PR provides the ability to control the manipulator line bound width (the threshold to use for mouse (ray) picking intersections).
It also updates the EditorPreferences page to reflect the relevant manipulator settings and removes the old Gizmo values (these were no longer used). As I don't want to confuse git with the renames + changes, I'm going to leave the filenames as-is for now and will do a follow-up PR to rename to `CEditorPreferencesPage_ViewportManipulator`.
I also added some helpful debug drawing for the manipulator bounds (see `ed_manipulatorDisplayBoundDebug) to visualize what the bounds are, even if the visuals are still just using a line. Might be worth discussing with UX in future if we want to use the cylinder rendering to give a more …
> Expose the ability to control manipulator line bounds

- Gems/Atom/RPI/Code/Source/RPI.Builders/Model/MaterialAssetBuilderComponent.cpp
Testing:
- Testing with AR run on a clean cache
- Tested locally with clean cache, no errors.
> Reintroduce materialtype dependency on fbx files.

- Code/Editor/EditorPreferencesPageViewportGizmo.cpp
- Code/Editor/EditorPreferencesPageViewportGizmo.h
- Code/Editor/EditorPreferencesPageViewportMovement.cpp
- Code/Editor/EditorViewportSettings.cpp
- Code/Editor/EditorViewportSettings.h
- Code/Editor/EditorViewportWidget.cpp
- Code/Editor/EditorViewportWidget.h
- Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/ViewportInteraction.h
- Code/Framework/AzManipulatorTestFramework/Source/ViewportInteraction.cpp
- Code/Framework/AzManipulatorTestFramework/Tests/ViewportInteractionTest.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/EditorVertexSelection.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/ManipulatorSnapping.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/ManipulatorView.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/RotationManipulators.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/RotationManipulators.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportMessages.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportMessages.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/RenderViewportWidget.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorPolygonPrismShapeComponentMode.cpp
- Gems/PhysX/Code/Editor/ColliderRotationMode.cpp
- Gems/PhysX/Code/Editor/EditorSubComponentModeAngleCone.cpp
- Gems/PhysX/Code/Editor/EditorSubComponentModeRotation.cpp
This PR compliments the previous change https://github.com/o3de/o3de/pull/3890 by providing the option to customize the angular manipulator bounds separate to the linear manipulator line bounds.
This PR also splits up the `ViewportInteractionRequests` into `ViewportSettingsRequests` which can more simply be implemented just for `EditorViewportWidget` - this is a better separation as thing like GridSnapping did not make sense being in `RenderViewportWidget` now.
> Expose setting to adjust angular manipulator circle bound

- AutomatedTesting/Gem/PythonTests/AWS/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/AWS/Windows/aws_metrics/aws_metrics_automation_test.py
- AutomatedTesting/Gem/PythonTests/AWS/Windows/client_auth/aws_client_auth_automation_test.py
- AutomatedTesting/Gem/PythonTests/AWS/Windows/core/test_aws_resource_interaction.py
- Code/Tools/TestImpactFramework/Frontend/Console/Code/Source/TestImpactCommandLineOptions.cpp
- Code/Tools/TestImpactFramework/Runtime/Code/Include/TestImpactFramework/TestImpactTestSequence.h
- Code/Tools/TestImpactFramework/Runtime/Code/Source/TestImpactUtils.cpp
- cmake/LYTestWrappers.cmake
- ctest_pytest.ini
- scripts/build/Platform/Linux/build_config.json
- scripts/build/Platform/Windows/build_config.json
- scripts/ctest/ctest_driver.py
- scripts/ctest/sanity_test.py
Signed-off-by: junbo <junbo@amazon.com>
- Created a new test suite called "awsi"
- Updated the Jenkins jobs for Window to run AWSI automation tests in nightly build.
- Verified that the AWSI automation tests passed on Jenkins. The awsi_deployment job failed as expected since the Jenkins parameters for deployment are only defined for nightly build currently.
https://jenkins-pipeline.agscollab.com/job/O3DE-LY-FORK/job/LYN-5862/
> Add AWSI automation tests to a new test suite and pipe

- Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
MeshFeatureProcessor::SetVisible now adds or removes the mesh from the raytracing scene as appropriate.
> Remove mesh from raytracing scene when hidden

- Gems/Gestures/Code/Include/Gestures/GestureRecognizerClickOrTap.inl
- Gems/Gestures/Code/Include/Gestures/GestureRecognizerDrag.inl
- Gems/Gestures/Code/Include/Gestures/GestureRecognizerHold.h
- Gems/Gestures/Code/Include/Gestures/GestureRecognizerHold.inl
- Gems/Gestures/Code/Include/Gestures/GestureRecognizerPinch.inl
- Gems/Gestures/Code/Include/Gestures/GestureRecognizerRotate.inl
- Gems/Gestures/Code/Include/Gestures/GestureRecognizerSwipe.inl
Adding null pointer checks in case the global environment is not set up outside of the editor.
This is resulting in crashes now that tools like the material editor are loading the same gems as the main editor.
Will also explore adding cry system to atom tools to set up the environment which was previously not needed.
> Adding null checks to Gestures gem if gEnv isn't set

- Code/Editor/EditorViewportWidget.cpp
- Code/Editor/EditorViewportWidget.h
- Code/Editor/Viewport.cpp
- Code/Framework/AzFramework/AzFramework/Visibility/BoundsBus.h
- Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/AzManipulatorTestFramework.h
- Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/AzManipulatorTestFrameworkTestHelpers.h
- Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/IndirectManipulatorViewportInteraction.h
- Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/ViewportInteraction.h
- Code/Framework/AzManipulatorTestFramework/Source/AzManipulatorTestFrameworkUtils.cpp
- Code/Framework/AzManipulatorTestFramework/Source/IndirectManipulatorViewportInteraction.cpp
- Code/Framework/AzManipulatorTestFramework/Source/ViewportInteraction.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/API/ComponentEntitySelectionBus.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportMessages.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportMessages.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorSelectionUtil.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorSelectionUtil.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorVisibleEntityDataCache.cpp
- Code/Framework/AzToolsFramework/Tests/ComponentModeTestFixture.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ModularViewportCameraController.cpp
This PR is the beginning of resolving https://github.com/o3de/o3de/issues/3578. This change lays the groundwork for supporting better viewport interaction model integration tests by supporting the new visibility system work. This is currently implemented by `EditorViewportWidget` which is not instantiated at test time (for AzToolsFramework tests). The main 'visible entities' call has been split out from `MainEditorViewportInteractionRequestBus` (which will eventually be removed).
There's also a few minor tidy-up changes that I spotted along the way
> Preparatory work to allow for more viewport integration tests

- Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp
- Code/Framework/AzFramework/Tests/CameraInputTests.cpp
I spotted a small issue with the camera orbit code where if you use the 'Go to position' option and wind up having the camera look-at point and camera translation be at the same point, trying to orbit (holding Alt) will break this behavior (as the `CreateTransformFromLook` will fail). This just checks to see if look-at and the camera translation are the same, if they are we just fallback to the internal ray intersection options.
(I also fixed up the internal naming convention for the camera tests to follow the requirements made by GTest)
Before fix:
```
[----------] 1 test from CameraInputFixture
[ RUN      ] CameraInputFixture.OrbitCameraInputHandlesLookatAndSelfAtSamePositionWhenOrbiting …
```
> Camera orbit fix

- Gems/AudioEngineWwise/Code/Source/Engine/Config_wwise.cpp
- Gems/AudioEngineWwise/Code/Source/Engine/FileIOHandler_wwise.cpp
One fixes string literal format specifiers warnings that were recently enabled.
One fixes a FileFunc utility that was removed.
> Fix compile errors in the Wwise Gem

- Code/Legacy/CrySystem/SystemCFG.cpp
Add [[maybe_unused]] to some local variables that are only referenced as arguments to CryLogAlways that is not compiled in release.
> Add [[maybe_unused]] to some local variables.

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/EBusEventHandler.cpp
Fixed an issue where EBusEventHandler nodes did not consider variables in slots.  The 'Remove unused variables' function and slot highlighting relies on this functionality, and possibly the GraphVariablesTableView
Signed-off-by: AMZN-alexpete <26804013+AMZN-alexpete@users.noreply.github.com>
> Fix ebus node slots not checked for vars

- Gems/Gestures/Code/Include/Gestures/GestureRecognizerClickOrTap.inl
- Gems/Gestures/Code/Include/Gestures/GestureRecognizerDrag.inl
- Gems/Gestures/Code/Include/Gestures/GestureRecognizerHold.inl
- Gems/Gestures/Code/Include/Gestures/GestureRecognizerPinch.inl
- Gems/Gestures/Code/Include/Gestures/GestureRecognizerRotate.inl
- Gems/Gestures/Code/Include/Gestures/GestureRecognizerSwipe.inl
This is an update from a previous change that added early return null checks for the global environment and its timer. Those changes fixed crashes when gestures was activated and running outside of the main editor. But the changes also resulted in warnings that went unnoticed. This round of changes allows gestures to run without warnings, using inline checks and default values instead of returning early.
> Fixing gestures gem warnings when gEnv/pTimer is null

- Gems/EditorPythonBindings/Code/Source/PythonProxyBus.cpp
{LYN6482} Fix warning as error in Editor Python Bindings
Signed-off-by: Jackson <23512001+jackalbe@users.noreply.github.com>
> {LYN6482} Fix warning as error in Editor Python Bindings

- Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeInspectorPlugin.cpp
- Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeInspectorPlugin.h
- Gems/EMotionFX/Code/Tests/D6JointLimitConfiguration.h
- Gems/EMotionFX/Code/Tests/Mocks/PhysicsSystem.h
- Gems/EMotionFX/Code/Tests/ProvidesUI/Ragdoll/CanCopyPasteColliders.cpp
- Gems/EMotionFX/Code/Tests/ProvidesUI/Ragdoll/CanCopyPasteJointLimits.cpp
- Gems/EMotionFX/Code/Tests/UI/CanAddToSimulatedObject.cpp
- Gems/EMotionFX/Code/Tests/UI/RagdollEditTests.cpp
Following the same approach as cloth plugin, which is to ask if the system component of the gem is available (in this case PhysX::SystemComponent).
Fixes #2540
> Fixed ragdoll panel being available in Animation Editor when PhysX gem is enabled.

- Code/Framework/AzManipulatorTestFramework/Source/IndirectManipulatorViewportInteraction.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorBoxSelect.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorBoxSelect.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.h
- Code/Framework/AzToolsFramework/Tests/EditorTransformComponentSelectionTests.cpp
This PR adds a number of tests to verify the current behavior of entity selection in the Viewport Interaction Model.
A new AZ_CVAR (`ed_viewportStickySelect`) has been added in anticipation for toggling 'sticky' mode (what we have today) vs 'non-sticky' mode (in future this will almost certainly be moved to the Settings Registry).
There still need to be a few more box select tests, but then new functionality can be added to support the new type of selection that a host of users prefer.
There are a few other small fixes that were identified with the tests and some pretty minor formatting changes (after running `clang-format`).
Relates to https://github.com/o3de/o3de/issues/3578
```
Note: Google Test filter = EditorTransformComponentSelectionViewportPickingManipulatorTestFixture* …
```
> Initial test coverage for viewport selection before introducing new 'single' select functionality

- Code/Framework/AzFramework/Platform/Linux/AzFramework/Application/Application_Linux_xcb.h
- Code/Framework/AzFramework/Platform/Linux/AzFramework/Windowing/NativeWindow_Linux_xcb.h
> Adding missing pragma header guards to _xcb.h header files

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/EBusEventHandler.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/Method.cpp
When nodes were cloned by the object stream, OnWriteEnd() gets called, which was causing ebus nodes and method nodes to falsely warn that they couldn't find their methods in behavior context
> remove false error from deserializing BC nodes

- Code/Framework/AzFramework/AzFramework/Archive/Archive.cpp
- Code/Framework/AzFramework/AzFramework/Visibility/EntityVisibilityBoundsUnionSystem.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorVisibleEntityDataCache.cpp
- Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
- Gems/Atom/RHI/Code/Source/RHI/FrameScheduler.cpp
- Gems/Atom/RHI/Code/Source/RHI/PipelineStateCache.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/MeshDrawPacket.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Model/ModelLod.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RasterPass.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Shader/Shader.cpp
- Gems/Atom/RPI/Code/Source/RPI.Reflect/Model/ModelAsset.cpp
- Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderAsset.cpp
- Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderVariantTreeAsset.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/SurfaceData/SurfaceDataMeshComponent.cpp
- Gems/SurfaceData/Code/Source/Components/SurfaceDataColliderComponent.cpp
- Gems/SurfaceData/Code/Source/SurfaceDataSystemComponent.cpp
Many of these are just extra noise in the profile, but the one in Archive.cpp could also cause PIX to crash.
> Remove extra/bad profile markers

- cmake/Projects.cmake
`file(ARCHIVE_CREATE` will fail if the directory is not there
> Creates destination directory if it doesnt exists

- Code/Framework/AzCore/AzCore/Casting/numeric_cast.h
- Code/Framework/AzCore/AzCore/Casting/numeric_cast_internal.h
- Code/Framework/AzCore/AzCore/Serialization/Json/CastingHelpers.h
- Code/Framework/AzCore/AzCore/azcore_files.cmake
- Code/Framework/AzQtComponents/AzQtComponents/Components/FancyDocking.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/GradientSlider.cpp
before: 872s
after: 824s (5.5% reduction)
> Improves numeric_cast compilation

- Code/Framework/AzCore/AzCore/Component/EntitySerializer.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
The terrain feature processor was crashing due to an invalid shader name.  The shader name has been fixed, but the feature processor has also been hardened so that it no longer crashes if a shader fails to load.
Also, while testing, this inadvertently exposed a second crash in EntitySerializer that occurs when components don't serialize in correctly.
> Fix GHI 4041 Terrain Shader Crash

- cmake/ConfigurationTypes.cmake
- cmake/Configurations.cmake
- cmake/Platform/Common/Install_common.cmake
- cmake/install/ConfigurationType_config.cmake.in
- cmake/install/ConfigurationTypes.cmake
In a project-centric / engine SDK was used, we were using the same configuration types that we defined for the engine. However, that doesnt mean that the SDK contains all those configuration types.
This change tweaks the SDK CMake's file to only expose the configuration types that the SDK was generated for.
To achieve it, we generate a file that appends the configuration during the install step of that configuration. The install step is per configuration.
Closes #2526
> Limits configuration types a project sees when using an engine SDK

- Gems/LmbrCentral/Code/Source/Shape/ShapeGeometryUtil.cpp
- Gems/LmbrCentral/Code/Tests/ShapeGeometryUtilTest.cpp
Addresses this issue https://github.com/o3de/o3de/issues/3342
When the PolygonPrism shape has vertices that form long thin triangles, you get in the realm of numerical precision errors and can end up in an infinite loop.  These changes add a few checks for conditions where those precision errors can cause an infinite loop, either because:
1. the final 3 vertices form a thin triangle that is classified as non-ear in any permutation
2. a combination of thin triangles causing havoc with the ear classification and the point-in-triangle test.
**Tests**
- Added a unit test that uses a real world example that caused an infinite loop before the changes.
Signed-off-by: AMZN-alexpete <26804013+AMZN-alexpete@users.noreply.github.com>
> fix infinite loop due to thin triangles

- Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/PlatformIncl_UnixLike.h
- Code/Legacy/CryCommon/platform.h
- Code/Legacy/CrySystem/XML/XMLBinaryNode.cpp
- Code/Legacy/CrySystem/XML/xml.cpp
- Code/Tools/AssetProcessor/native/AssetManager/SourceFileRelocator.cpp
- Code/Tools/AssetProcessor/native/utilities/assetUtils.cpp
- Gems/AudioSystem/Code/Source/Engine/ATL.cpp
- Gems/AudioSystem/Code/Source/Engine/ATLAudioObject.cpp
- Gems/LmbrCentral/Code/Source/Builders/SliceBuilder/SliceBuilderWorker.cpp
- Gems/Vegetation/Code/Source/AreaSystemComponent.cpp
The fixed width 64-bit integer types are defined differently per platform.
Some platforms define it as "long", others define it as "long long". For
consistency, `AZ::u64` or `AZ::s64` is always defined to "long long".
However, this causes problems for formatting those types, because on
platforms where `uint64_t` is a `long`, `PRIu64` gives the wrong format
string for `AZ::u64`. Previously this was fixed by redefining the `PRI`
macros so that they work for `AZ::u64`, but that breaks the ability to
format `uint64_t`.
We could add an AZ-specific version of the `PRI` macros for 64-bit integer
types, but we don't really need to, since they are `long long` on every
platform we support.
* Use `%ll` for `AZ::u64`
* Use `PRIu64` for `uint64_t`
> Avoid redefining `PRI` macros on Linux

- Gems/EMotionFX/Code/Source/Editor/PropertyWidgets/AnimGraphTransitionHandler.cpp
> EMotion FX: Resetting the anim graph while in the middle of selecting transitions for interruption crashes the Editor

- Code/Editor/EditorViewportWidget.cpp
- Code/Editor/EditorViewportWidget.h
- Code/Editor/IEditorImpl.cpp
- Code/Editor/Viewport.cpp
- Code/Editor/Viewport.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/EditorVertexSelection.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportMessages.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorHelpers.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorSelectionUtil.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorSelectionUtil.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
- Gems/PhysX/Code/Editor/EditorViewportEntityPicker.cpp
This is a tidy-up PR now we have some more test coverage in-place. It removes some redundant calls that are no longer needed and also performs some more small clean-ups.
> Remove redundant API calls from EditorViewportWidget and use new WorldToScreen call

- Code/Editor/CryEditPy.cpp
- Code/Editor/EditorViewportWidget.cpp
- Code/Editor/EditorViewportWidget.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportMessages.h
This bus was needed to fix an issue in the legacy viewport which is no longer used and can be removed
> Remove viewport freeze request bus

- Code/Editor/CryEdit.cpp
- Code/Framework/AzFramework/Platform/Linux/AzFramework/Process/ProcessWatcher_Linux.cpp
Fix issue where ProjectManager fails to launch because some of the environment variables that is needed to connect to the xcb display was not carried forward from the Editor process.
> Linux fix launch project manager from editor

- scripts/build/bootstrap/incremental_build_util.py
This PR updates the inc_build_util script to support build nodes that utilize NVMe-based storage. Required when we migrate all our linux nodes from C4 to to C5. Nodes that still use the current device setup will continue operating normally. 
Tested in our fork:
- Running linux build on c5.9xlarge prior to update: build failed
- Running linux build on c5.9xlarge after update: build succeeds
- Running linux build on c4.8xlarge after update: build succeeds
> Add support for NVMe volumes to mounting script

- Code/Framework/AzCore/AzCore/IO/Path/Path.h
- Code/Framework/AzCore/AzCore/IO/Path/Path.inl
- Code/Framework/AzCore/AzCore/IO/Path/PathParser.inl
- Code/Framework/AzCore/Tests/IO/Path/PathTests.cpp
This issue is caused by the Path comparison logic using the path
separator of the left path in a comparison of two paths(left and right)
to determine whether the PathComparison is case-sensitive or not.
The logic has been updated to only perform a non-case-sensitive path
comparison if both paths are using the WindowsPathSeperator of `\`
Also fixed issue with the Hashing algorihtm of the Path class to always
hash the root directory as if it is `/`.
This allows a path of "C:\foo" and "C:/foo" to hash to the equivalent
value.
> Fixed issue where two Paths could compare equal to each other, but hash differently

- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
- Code/Framework/AzToolsFramework/Tests/EditorTransformComponentSelectionTests.cpp
This PR adds a `ScopedUndoBatch` to `ChangeSelectedEntity` (it was just that easy 😄) to ensure that a 'parent' undo step is recorded so when undo is pressed, the previous entity is selected (instead of an independent deselect, and then select undo step)
Before change:
```
[ RUN      ] EditorTransformComponentSelectionViewportPickingManipulatorTestFixture.UnstickyUndoOperationForChangeInSelectionIsAtomic
D:/o3de/Code/Framework/AzToolsFramework/Tests/EditorTransformComponentSelectionTests.cpp(1014): error: Value of: selectedEntitiesAfter
Expected: has 1 element and that element is equal to 8-byte object <05-73 D6-BA 68-01 00-00>
Actual: {}
[  FAILED  ] EditorTransformComponentSelectionViewportPickingManipulatorTestFixture.UnstickyUndoOperationForChangeInSelectionIsAtomic (118 ms)
```
After …
> Ensure undo/redo operation for change entity selection is atomic

- AutomatedTesting/Gem/PythonTests/atom_renderer/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/atom_renderer/atom_hydra_scripts/TestAssets/ShaderAssetBuilder/DependencyValidation.azsl.txt
- AutomatedTesting/Gem/PythonTests/atom_renderer/atom_hydra_scripts/TestAssets/ShaderAssetBuilder/DependencyValidation.shader.txt
- AutomatedTesting/Gem/PythonTests/atom_renderer/atom_hydra_scripts/TestAssets/ShaderAssetBuilder/Test1Color.azsli.txt
- AutomatedTesting/Gem/PythonTests/atom_renderer/atom_hydra_scripts/TestAssets/ShaderAssetBuilder/Test2Color.azsli.txt
- AutomatedTesting/Gem/PythonTests/atom_renderer/atom_hydra_scripts/TestAssets/ShaderAssetBuilder/Test3Color.azsli.txt
- AutomatedTesting/Gem/PythonTests/atom_renderer/atom_hydra_scripts/hydra_ShaderAssetBuilder_RecompilesShaderAsChainOfDependenciesChanges.py
- AutomatedTesting/Gem/PythonTests/atom_renderer/test_Atom_ShaderBuildPipelineSuite.py
- Gems/Atom/Asset/Shader/Code/CMakeLists.txt
- Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderAssetBuilder.cpp
- Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderBuilderUtility.cpp
- Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderBuilderUtility.h
- Gems/Atom/Asset/Shader/Code/Tests/ShaderBuilderUtilityTests.cpp
- Gems/Atom/Asset/Shader/Code/atom_asset_shader_builders_tests_files.cmake
- Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/FastDepthAwareBlurHor.azsl
- Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/FastDepthAwareBlurVer.azsl
- Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/SMAA.azsli
[ATOM-5441] Shader Builders May Fail When Multiple
New Files Are Added
ShaderAssetBuilder::CreateJobs now recursively parses *.azsl files
looking for #include lines and builds the list of source dependencies
using a depth-first algorithm. It was using MCPP before but not anymore
(during CreateJobs).
The new algorithm may over prescribe, but fixes the issues
when multiple new shader related files are added, at once or out of order, to a game project
or Gem.
Overall the new ShaderAssetBuilder::CreateJobs() is around 40% faster
and, of course, handles source dependencies in a robust way.
Signed-off-by: garrieta <garrieta@amazon.com>
> [ATOM-5441] Shader Builders May Fail When Multiple  New Files Are Added

- Code/Tools/Standalone/Source/Editor/LuaEditor.cpp
Fixes the following crash
```
System: Trace::Assert
/home/ANT.AMAZON.COM/spham/github/o3de/Code/Framework/AzCore/./AzCore/Memory/Memory.h(582): (140737286531712) 'static AZ::IAllocator &AZ::AllocatorStorage::EnvironmentStoragePolicy<AZ::SystemAllocator>::GetAllocator() [Allocator = AZ::SystemAllocator]'
System: Allocator 'SystemAllocator' NOT ready for use! Call Create first!
System: ------------------------------------------------
System: AZ::AllocatorStorage::EnvironmentStoragePolicy<AZ::SystemAllocator>::GetAllocator() (+0x102) [0x4d1492]
System: AZ::Internal::AllocatorInstanceBase<AZ::SystemAllocator, AZ::AllocatorStorage::EnvironmentStoragePolicy<AZ::SystemAllocator> >::GetAllocator() (+0x9) [0x4d1369]
System: AZ::Internal::AllocatorInstanceBase<AZ::SystemAllocator, …
```
> Fix LuaIDE crash at startup caused by missing System Allocator Initialization

- Code/Framework/AzFramework/AzFramework/Archive/Archive.cpp
- Code/LauncherUnified/Launcher.cpp
- Code/Legacy/CrySystem/AZCoreLogSink.h
- Code/Legacy/CrySystem/LevelSystem/LevelSystem.cpp
- Code/Legacy/CrySystem/System.cpp
- Code/Tools/RemoteConsole/Core/RemoteConsoleCore.cpp
- Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp
- Gems/HttpRequestor/Code/Source/HttpRequestManager.cpp
This removes the `TerminateProcess()` / `exit()` calls from `CSystem::Quit`, and fixes all the crashes and leaks that were occurring as a result of the atexit code now running.
> Perform global deinitialization when exiting the game launcher

- AutomatedTesting/Gem/PythonTests/atom_renderer/atom_hydra_scripts/hydra_AtomEditorComponents_AddedToEntity.py
- AutomatedTesting/Gem/PythonTests/atom_renderer/test_Atom_MainSuite.py
Adds Reflection Probe component to the test all AtomEditorComponents test
1/1 Test #14: AutomatedTesting::AtomRenderer_HydraTests_Main.main::TEST_RUN ...   Passed  165.55 sec
100% tests passed, 0 tests failed out of 1
unrelated test for material editor basic was timing out frequently but this test function is working with these changes.
> Reflection Probe component added to AtomEditorComponents test

- AutomatedTesting/Gem/PythonTests/AWS/README.md
- AutomatedTesting/Gem/PythonTests/AWS/Windows/aws_metrics/aws_metrics_automation_test.py
Signed-off-by: Junbo Liang <junbo@amazon.com>
Make sure that the s3 bucket is cleared at the end of automation tests to avoid new objects delivered to it after the cleanup.
> Fix the destruction failure and update the instructions for running automation tests

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/DescriptorSet.cpp
Signed-off-by: Peng <tonypeng@amazon.com>
> [ATOM][RHI][Vulkan] - Account for null descriptor for sampler.

- Code/Editor/EditorPreferencesPageViewportGeneral.cpp
- Code/Editor/EditorPreferencesPageViewportGeneral.h
- Code/Editor/EditorViewportSettings.cpp
- Code/Editor/EditorViewportSettings.h
- Code/Editor/EditorViewportWidget.cpp
- Code/Editor/EditorViewportWidget.h
- Code/Editor/ViewportTitleDlg.cpp
- Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/ActionDispatcher.h
- Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/AzManipulatorTestFramework.h
- Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/ImmediateModeActionDispatcher.h
- Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/ViewportInteraction.h
- Code/Framework/AzManipulatorTestFramework/Source/ImmediateModeActionDispatcher.cpp
- Code/Framework/AzManipulatorTestFramework/Source/ViewportInteraction.cpp
- Code/Framework/AzManipulatorTestFramework/Tests/GridSnappingTest.cpp
- Code/Framework/AzManipulatorTestFramework/Tests/ViewportInteractionTest.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportMessages.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.h
- Code/Framework/AzToolsFramework/Tests/EditorTransformComponentSelectionTests.cpp
This PR moves the AZ_CVAR to the SettingsRegistry.
It also includes some tidy-up changes to the manipulator test framework as well
> Expose sticky select option to the SettingsRegistry

- Gems/EMotionFX/Code/EMotionFX/Source/Actor.cpp
- Gems/EMotionFX/Code/Source/Editor/ActorJointBrowseEdit.cpp
Wrong invalid index type caused the crash. Selecting another joint was broken as well and got fixed directly, too. The selection done event was never received due to not being connected to the node hierarchy widget.
Resolves #4108
> EMotion FX: Resetting the Motion extraction joint when the Anim Graph is active crashes the Editor

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
Atom Sample Viewer would hit an assert when indexing an AZstd::vector on an Android build running on devices with PowerVR GPUs.
The issue was traced to the Vulkan RHI's Device::InitFeaturesAndLimits() method. On GPUs where the timestampComputeAndGraphics flag in the physical device limits is false, it iterates over the Queue families to check if any of them have timestampValidBits > 0 in order to add RHI::QueryTypeFlags::Timestamp support.
The assert hits because at that point the m_commandQueueContext is not initialized meaning the AZstd::vector that it is trying to index into is empty.
Moving the Device::InitFeaturesAndLimits() method inside Device::InitializeLimits() after the m_commandQueueContext is initialized fixes the issue and is confirmed working on multiple devices with PowerVR …
> Fixed crash in Atom Vulkan RHI when physical device limits timestampComputeAndGraphics is false

- Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableEntitiesInterface.cpp
- Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableEntitiesInterface.h
- Code/Framework/AzFramework/Tests/Spawnable/SpawnableEntitiesInterfaceTests.cpp
- Code/Framework/AzFramework/Tests/frameworktests_files.cmake
This commit also includes some tweaks to the begin/end functions and unit tests.
Ticket: https://github.com/o3de/o3de/issues/4110
Signed-off-by: AMZN-koppersr <82230785+AMZN-koppersr@users.noreply.github.com>
> Added array index operators to Spawnable(Const)EntityContainerView.

- Code/Framework/AzCore/AzCore/EBus/EBus.h
Fixes the following:
```
[2021-09-16T05:41:47.746Z] D:\workspace\o3de\Code\Framework\AzCore\AzCore/EBus/EBus.h(1731,1): error C4265: 'AZ::Internal::EBusNestedVersionRouter<AZ::EBus<UnitTest::EBusInterfaceV2,Interface>>': class has virtual functions, but its non-trivial destructor is not virtual; instances of this class may not be destructed correctly [D:\workspace\o3de\build\windows_vs2019\Code\Framework\AzCore\AzCore.Tests.vcxproj]
[2021-09-16T05:41:47.746Z]           with
[2021-09-16T05:41:47.746Z]           [
[2021-09-16T05:41:47.746Z]               Interface=UnitTest::EBusInterfaceV2
[2021-09-16T05:41:47.746Z]           ]
[2021-09-16T05:41:47.746Z]           };
[2021-09-16T05:41:47.746Z]   ^
[2021-09-16T05:41:47.746Z]   D:/workspace/o3de/Code/Framework/AzCore/Tests/EBus.cpp(2439): …
```
> Fix missing virtual destructor causing debug build failure

- Gems/LmbrCentral/Code/Source/Editor/EditorCommentComponent.cpp
Fixes #4049 
Tested the repro steps and verified the error message no longer displays, and the Comment component viewport icon now shows as intended.
> Fixed the Comment component viewport icon.

- AutomatedTesting/Gem/PythonTests/AWS/Windows/aws_metrics/aws_metrics_automation_test.py
- Gems/AWSClientAuth/cdk/utils/name_utils.py
- Gems/AWSClientAuth/cdk/utils/resource_name_sanitizer.py
- Gems/AWSMetrics/cdk/aws_metrics/aws_metrics_stack.py
- Gems/AWSMetrics/cdk/aws_metrics/batch_analytics.py
- Gems/AWSMetrics/cdk/aws_metrics/batch_processing.py
- Gems/AWSMetrics/cdk/aws_metrics/dashboard.py
- Gems/AWSMetrics/cdk/aws_metrics/data_ingestion.py
- Gems/AWSMetrics/cdk/aws_metrics/data_lake_integration.py
- Gems/AWSMetrics/cdk/aws_metrics/real_time_data_processing.py
Signed-off-by: Junbo Liang <junbo@amazon.com>
Currently some resource names are hardcoded in the automation tests but it could become a problem when we set up long AWS project name on Jenkins since the resource name can be trimmed. Export them to the CloudFormation stack outputs will help to avoid this kind of failure.
Also make some updates to trim the resource name of the client auth gem when it's too long.
- Verified that the CDK application with a long project name ("DEVELOPMENT-CLEAN-AWSAUTO") could be deployed via the Jenkins script and AWSI automation tests for all the gems passed.
> [AWSI Automation] Export more AWS resource names via CloudFormation stack outputs for the automation tests

- Code/Legacy/CrySystem/AZCoreLogSink.h
Fix up for b53bf52e0dc0a2af6886b35478a9c65eb64e03ba:
For `Disconnect()` to be able to be called more than once, the pointer that `Disconnect()` calls `delete` on needs to be set to `nullptr`. Calling `delete` on a `nullptr` does nothing, so the next time `Disconnect()` is called, it does not attempt to re-delete the same pointer.
> Allow for `AZCoreLogSink::Disconnect()` to be called more than once

- Code/Tools/TestImpactFramework/Runtime/Code/Include/TestImpactFramework/TestImpactClientSequenceReport.h
- Code/Tools/TestImpactFramework/Runtime/Code/Include/TestImpactFramework/TestImpactClientSequenceReportSerializer.h
- Code/Tools/TestImpactFramework/Runtime/Code/Include/TestImpactFramework/TestImpactUtils.h
- Code/Tools/TestImpactFramework/Runtime/Code/Source/TestImpactClientSequenceReport.cpp
- Code/Tools/TestImpactFramework/Runtime/Code/Source/TestImpactClientSequenceReportSerializer.cpp
- Code/Tools/TestImpactFramework/Runtime/Code/Source/TestImpactUtils.cpp
This PR adds sequence report serialization. This functionality is necessary for various future features and optimizations including the Python test selection and prioritization.
> Add deserialization to sequence reports.

- cmake/Platform/Linux/PAL_linux.cmake
- cmake/Projects.cmake
First the Cache directory itself was being added to the archive. It has
been updated to query the assets from the asset type folder i.e
Cache/<asset-type>
Second execute_process is being used to invoke CMake `tar` command to
create the zip archive since the CMake `file(ARCHIVE_CREATE)` adds the
files to the archive relative to the current working directory which is
${CMAKE_BINARY_DIR} when invoking the install script.
This was causing the archive to store files with a path of "../../Cache/pc"
> Fixed creation of the Engine.pak file

- cmake/AzAutoGen.py
Fix AzAutoGen to output to a proper directory.  
Using path.commonpath instead of path.commonprefix.  commonpath, unlike commonprefix, always return a valid path. 
For example, path.commonprefix(["/usr/hello.txt", "/usr/helium.cpp"] would return "/usr/he" where as path.commonpath would return the directory "/usr/".  
If there is only one file in the folder then path.commonpath returns the entire file (not the directory) so I kept the check for os.path.isfile and slice off the filename if needed.
> LYN6729: Fix AzAutoGen to Output to Proper Path

- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Material/MaterialAsset.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Material/Material.cpp
- Gems/Atom/RPI/Code/Tests/Material/MaterialTests.cpp
An early-return in Material::SetPropertyValue was breaking initialization because Init() was called multiple times, and on subsequent initializations the property values weren't getting reset.
Added a unit test to ensure this kind of thing doesn't happen again.
Testing:
Atom Sample Viewer full test suite on vulkan and dx12. Test either passed or failed in exactly the same way before the bug was introduced (using local baseline to verify).
RPI unit tests passed.
Ran the editor and used material component to apply metallic materials. This was showing the black material before, and shows correctly now.
> Fixed a recently introduced Material initialization bug.

- Code/Editor/EditorToolsApplication.cpp
- Code/Editor/EditorToolsApplication.h
- Code/Editor/EditorViewportWidget.cpp
- Code/Editor/EditorViewportWidget.h
- Code/Framework/AzFramework/AzFramework/Viewport/ClickDetector.cpp
- Code/Framework/AzFramework/AzFramework/Viewport/ClickDetector.h
- Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/ImmediateModeActionDispatcher.h
- Code/Framework/AzManipulatorTestFramework/Source/ImmediateModeActionDispatcher.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportMessages.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
- Code/Framework/AzToolsFramework/Tests/EditorTransformComponentSelectionTests.cpp
This test adds some final coverage for Manipulator ditto commands (that were not working 100% correctly with the updated click changes (https://github.com/o3de/o3de/pull/4094 and https://github.com/o3de/o3de/pull/4149).
To make testing mouse inputs more reliable in the tests a new time interface was introduced that can be overridden at test time for the `ClickDetector`.
One way to solve this would have been to simply add a delay into the test, but this needlessly extends the running time and could add up if we start having to do it more often. 
I discussed the options at some length with @greerdv and we decided this is the best option (instead of providing an API to override the double click interval itself that could lead to further issues or insert a new ClickDetector).
In a perfect …
> Additional test support for Manipulator Ditto commands

- cmake/3rdParty.cmake
- cmake/Platform/Common/RuntimeDependencies_common.cmake
This allows 3rdParty libraries to be marked as "system" libraries. These libraries are considered to be part of the host system, and are not copied to the build output directory.
> Add support for marking 3rdParty libraries as supplied by the host system

- Code/Framework/AzFramework/AzFramework/Archive/ZipDirCache.cpp
- Code/Framework/AzFramework/AzFramework/Archive/ZipDirCacheFactory.cpp
- Code/Framework/AzFramework/AzFramework/Archive/ZipDirStructures.cpp
- Code/Framework/AzFramework/AzFramework/Archive/ZipDirStructures.h
The location of a file entry in a Zip file is calculated after the local file
header + the length of the filename + the length of the extra field
length per the ZIP file spec.
https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT
> Fixed calculation of each archive file data offset.

- Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkHitVolumesComponent.h
- Gems/Multiplayer/Code/Source/Components/NetworkHitVolumesComponent.cpp
Fix compiler error.  EntityPreRenderEvent went from accept 2 parameters to 1.  Updated to properly take the one float for deltaTime.
> LYN6808: Fix Compiler Error Due to EntityPreRenderEvent

- Gems/Camera/Code/CMakeLists.txt
- Gems/Camera/Code/Source/CameraComponent.cpp
- Gems/Camera/Code/Source/CameraComponent.h
- Gems/Camera/Code/Source/CameraComponentController.cpp
- Gems/Camera/Code/Source/CameraComponentController.h
- Gems/Camera/Code/Source/CameraEditorSystemComponent.cpp
- Gems/Camera/Code/Source/CameraGem.cpp
- Gems/Camera/Code/Source/EditorCameraComponent.cpp
- Gems/Camera/Code/Source/EditorCameraComponent.h
- Gems/Camera/Code/Source/ViewportCameraSelectorWindow.cpp
This fixes the camera crash outlined in https://github.com/o3de/o3de/issues/4170 by removing the component's view reference.
> Remove legacy Cry dependencies from the Camera Gem

- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
Fixes #4169 
Prevent crash in Landscape Canvas by closing any open graphs after prefab propagation completes to ensure the corresponding Entity still exists. There are some edge cases that could cause the entity to be deleted during prefab propagation that aren't being caught currently (e.g. if you create a prefab out of that Entity), so this prevents the user from getting into a bad state where they'd be attempting to modify data on an Entity that no longer exists.
> Prevent crash in Landscape Canvas when creating a prefab from an open graph.

- Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR_Common.azsli
- Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR_Displacement.lua
The original implementation would interpret the else condition as nil, and lead to an error
argument #2 to 'SetShaderConstant_float' (number expected, got nil)
Tested with an automated hydra test I am working on locally, which led to the issue.
> Modify CalcOverallHeightRange to not return nil

- Gems/Atom/RHI/Code/Include/Atom/RHI/SwapChain.h
- Gems/Atom/RHI/Code/Source/RHI/SwapChain.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandQueue.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/RenderViewportWidget.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp
Changes:
Removed the hack that blocks presenting swapchain until window resizing happens.
Applied reasonable fixes.
Cause:
The cause is that the resizing event is blocked intentionally by the viewport widget, which proves to be unnecessary because RHI handles that pretty well, and assumes resizing happens immediately (see comments in Vulkan::SwapChain::AcquireNewImage and Vulkan::SwapChain::PresentInternal).
When the resizing event is suspended, then the surface and swapchain mismatch, while presenting is still happening every frame in a different thread. Thus, in Vulkan, it always gives VK_ERROR_OUT_OF_DATE_KHR when presenting swapchain and acquiring the new image (vkQueuePresentKHR, vkAcquireNextImageKHR). And it can further cause deadlock even when resizing is done afterwards.
Note the …
> ATOM-16079 [RHI][Vulkan] - Linux Swapchain rendering issue on the first frame

- Gems/EMotionFX/Code/EMotionFX/Source/ActorInstance.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphInstance.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphMotionNode.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphStateMachine.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/BlendSpace1DNode.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/BlendSpace2DNode.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/BlendTree.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeBlend2Node.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/MotionSystem.cpp
Added some basic profile instrumentation for anim graphs to capture the update phases and the most important anim graph nodes.
> EMotionFX: Basic profile instrumentation for anim graph

- scripts/build/Jenkins/Jenkinsfile
This change is required to support spot instances in the AR pipeline where instances can experience interruptions. 
- When a node goes offline the job is retried on a new node. Retry is located outside of the node block otherwise Jenkins will attempt to retry the job on the same failed node.
- Valid script errors are handled properly and the status is updated in Jenkins
- Remove error statement from nonblocking step and to prevent it from hiding the exceptions
Retries are currently set on the node level. When the pipeline uses multiple nodes only the jobs on the current node will be retried. The next iteration will track which stage the node is running and retry at the current stage.
Tests:
- Node terminated: Stages for that platform are retried on a new node. All other stages continue …
> Retry pipeline stages when a node goes offline 

- Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilder.cpp
- Gems/Atom/RPI/Code/Source/RPI.Builders/Model/MaterialAssetBuilderComponent.cpp
Notes:
- When includeMaterialPropertyNames is enabled, job dependency types for all material files can be set to process only once. Then if the materialtype file is changed in the future, we can rely on the newly implemented load-time mechanism to add the new properties. 
- Remove source dependency in MaterialBuilder. We only need the job dependency. 
- AP load time when adding a dummy property in StandardPBR.materialtype is down from 45s to 10s. 
Testing:
- Observed that adding a dummy property in StandardPBR.materialtype does not cause fbx and standalone material asset rebuild.
- Added a dummy property in StandardPBR.materialtype then reprocessed the fbx and standalone material asset. Observed that removing the dummy property does not cause a rebuild of the fbx and standalone material …
> Switch job dependency type to OrderOnce for material assets when property names are present.

- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Converters/PixelOperation.cpp
- Gems/Atom/Asset/ImageProcessingAtom/Config/Albedo.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/AlbedoWithCoverage.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/AlbedoWithGenericAlpha.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/AlbedoWithOpacity.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/AmbientOcclusion.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/CloudShadows.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/Decal_AlbedoWithOpacity.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/Detail_MergedAlbedoNormalsSmoothness.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/Displacement.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/Emissive.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/Greyscale.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/LensOptics.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/LightProjector.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/Minimap.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/MuzzleFlash.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/Opacity.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/Reflectance.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/ReflectanceWithSmoothness_Legacy.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/Reflectance_Linear.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/SF_Image.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/SF_Image_nonpower2.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/Terrain_Albedo.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/Terrain_Albedo_HighPassed.preset
- Gems/Atom/Asset/ImageProcessingAtom/Config/UserInterface_Compressed.preset
The issue was because the compression of ETC formats took too long.
Replaced all ETC and PVRTC formats with ASTC formats.
Signed-off-by: Qing Tao <qingtao@amazon.com>
> LYN-6793 [iOS] [asset_profile] 4 assets fail to process for iOS

- Gems/Atom/RPI/Code/Source/RPI.Reflect/Buffer/BufferAssetCreator.cpp
since the initial data is going to be memcpy'd anyways.
Tested with the SkinnedMeshExampleComponent in AtomSampleViewer, which creates buffers on the CPU with up to 4billion vertices, and tested with the O3DE Editor.
> Use resize_no_construct when creating a buffer asset, 

- Gems/EditorPythonBindings/Code/Source/PythonProxyBus.cpp
Came across this error while writing a test. Updating the error message.
> Fix a minor spelling mistake

- Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Behaviors/ActorGroupBehavior.cpp
- Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Groups/ActorGroup.cpp
Fixing the actor behavior to ignore actor asset generation for files that only contain nodes/bones. We're only checking for blend shapes and skins now. In case neither is present in an FBX, we don't export the actor asset.
This makes a plain skeleton a special case where users manually need to add the actor group for the fbx. The most common use case for these are animation files anyway, where we don't want to export actor assets.
Also increased the version number of the actor group so that they are all getting reprocessed and the unneeded actor assets get removed.
> EMotion FX: Asset Processor generates an Actor for every FBX

- Gems/EMotionFX/Code/EMotionFX/Source/NodeGroup.cpp
Fixing a crash related to the small array conversion that made multiple assets crash the actor builder.
> EMotion FX: Crash in the actor builder when fbx meta data contains node groups

- Code/Framework/AzCore/AzCore/IO/FileReader.cpp
- Code/Framework/AzCore/AzCore/IO/FileReader.h
- Code/Framework/AzCore/AzCore/IO/SystemFile.cpp
- Code/Framework/AzCore/AzCore/IO/SystemFile.h
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.cpp
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.cpp
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.h
- Code/Framework/AzCore/AzCore/azcore_files.cmake
- Code/Framework/AzCore/Tests/IO/FileReaderTests.cpp
- Code/Framework/AzCore/Tests/azcoretests_files.cmake
The new FileReader class allows using either a FileIOBase or SystemFile
classes for reading files.
If a non-nullptr FileIOBase is supplied, the FileIOBase is used,
otherwise SystemFile is used.
Updated the SettingsRegistryMergeUtils
`MergeSettingsToRegistry_ConfigFile` function to use the FileReader.
This allows .cfg such as the autoexec.cfg to be read using FileIO,
therefore allowing it to be read from the engine.pak file.
Because the AZ::Console::ExecuteConfigFile uses the
`MergeSettingsToRegistry_ConfigFile` function for merging *.cfg files to
the SettingsRegistry, this allows the AZ::Console to run console
commands from files within pak files thanks to the ArchiveFileIO being
the default FileIOBase instance
Signed-off-by: lumberyard-employee-dm …
> Moved the SettingsRegistryFileReader class to more general FileReader

- Gems/Atom/RHI/Code/Source/RHI.Edit/ShaderCompilerArguments.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI.Builders/ShaderPlatformInterface.cpp
- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderVariantAsset.h
Vulkan PDBs are currently broken because debug data isn't stripped from
the shader binary. Furthermore, sub-id hashing is broken because sub-ids
count from 1 which generates a collision on the first sub-object.
Changing the default value for the sub-id argument resolves this.
> Disable Vulkan PDB generation and fix D3D12 PDBs

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
- Code/Framework/AzToolsFramework/Tests/FocusMode/EditorFocusModeTests.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabFocus/PrefabFocusTests.cpp
- Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
Added unit tests for the functionality that is currently available in development. New PRs will be updated to include unit tests before they are submitted.
Also changed AZ::EntityId() checks to use InvalidEntityId to avoid an instantiation.
> LYN-6826 | Focus Mode - Introduce unit tests for EditorFocusMode and PrefabFocus classes

- Code/Editor/EditorViewportWidget.cpp
when editor preferences > general preferences > restore viewport camera on game mode exit
This will be properly fixed when the Editor Camera Location Storage is supported.
> LYN-6874 : Restore viewport setting causes error when exiting game mode

- Code/Framework/AzFramework/AzFramework/Viewport/ScreenGeometry.h
- Code/Framework/AzFramework/AzFramework/Viewport/ViewportScreen.cpp
- Code/Framework/AzFramework/AzFramework/Viewport/ViewportScreen.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/ScaleManipulators.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/TranslationManipulators.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.h
- Code/Framework/AzToolsFramework/Tests/EditorTransformComponentSelectionTests.cpp
- Code/Framework/AzToolsFramework/Tests/Viewport/ViewportScreenTests.cpp
- Gems/AtomLyIntegration/AtomFont/Code/Source/FFont.cpp
This is a fairly significant behavior change to make the way entity space is handled in the viewport more standard while also retaining some of the interesting features we developed while building the new Viewport Interaction Model.
In the Editor today we default to parent space, which while useful in certain situations, is used far less widely than local space. Selecting an entity will now show the entities local transform.
It's still possible to quickly switch to world space by holding Shift. To access Parent or World space permanently, the Viewport UI toggles in the top right of the viewport can be used.
Before this change, reference space (local/parent/world) was not only used for the reference frame orientation, but also to determine how to move entities in a group (manipulating a …
> Update to how entity space is treated in the viewport

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.cpp
Fixes an issue with the order of operations on Entity Outliner construction that would cause a crash on layout refresh.
This would only occur in situations where the Entity Outliner is constructed while a level is already loaded.
Also added an additional fix to make sure the root entity is expanded on construction and not just on prefab propagation end.
> Editor crashes after changing the layout when the Prefab system is enabled

- Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
On MacOS, CompositionMode_DestinationIn makes the entire Projects screen (and window) transparent so you can see through the application.  This fix maintains the darkening effect without the transparent window.
Tests:
- ran the code on windows & osx using screenshots to compare before/after
> Fix transparency issue on MacOS

- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Inspector/InspectorWidget.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Inspector/InspectorWidget.ui
• A previous change introduced a heading section of the top of the inspector
• The code was incorrectly attempting to delete child widgets and layouts from the layout of each section
• Size policies were also updated to give priority to the section containing the property groups
• Tested material component property editor and material editor to make sure that widgets were laid out correctly at the top of the inspector
> Atom Tools: Fixing problems with inspector property group layout and deletion

- Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
Disables a problematic child reparenting code path in EditorEntityModel that led to the series of remove -> add -> remove notifications for reparented entities that led to unnecessary updates and a sporadic QSortFilterProxyModel crash
> Restore event listening behavior in EntityOutlinerListModel

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/Interpreted/ExecutionInterpretedAPI.cpp
- cmake/Platform/Common/Configurations_common.cmake
It now follows the schema defined by `AZ_DEBUG_BUILD`  define instead.
> Replace `PROFILE` define with `AZ_PROFILE_BUILD`

- Code/Framework/AtomCore/AtomCore/Instance/InstanceData.h
- Code/Framework/AtomCore/AtomCore/Instance/InstanceDatabase.h
- Code/Framework/AtomCore/Tests/InstanceDatabase.cpp
TEMPOrphan will remove an instance from the database so it will not be found using Find or FindOrCreate. The instance will still persist until its use-count drops to 0, at which point it will be deleted. This is to enable the model asset to remove existing buffer/modellod/model instances and replace them with new instances that have the up to date data. 
Added unit tests for testing. Expanded the parallel tests. In addtion to Creating and immediately letting the refcount drop to 0, I added a mode to hold on to a reference, and added a mode to orphan an instance, and a mode that does both.
Changed the duration for the parallel tests to a float so that small times can be used when needing to run the tests to repro issues locally
> Adding a temporary Orphan function to the InstanceDatabase

- cmake/Tools/Platform/Android/generate_android_project.py
The android project generate script used to check .../3rdParty/3rdParty.txt, but this step was removed a while ago.
With this step, third_party_path then was reset to its parent, which is .../3rdParty.
But now without this step, third_party_paty will be set to a level above .../3rdParty.
This issue won't cause any building errors, but it will eat up disk spaces because it downloads 3rd party packages to 2 locations.
> Fix 3p path setting to the upper level

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorBus.h
Fix for:
```
[2021-09-30T00:27:55.672Z] In file included from ../../Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorBus.cpp:9:
[2021-09-30T00:27:55.672Z] ../../Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorBus.h:46:20: error: too few template arguments for class template 'unordered_set'
[2021-09-30T00:27:55.672Z]             AZStd::unordered_set<AZ::Data::Asset<AZ::Data::AssetData>> m_openAssets;
```
in non-unity builds
> Fix missing include for AZStd::unordered_set in AssetEditorBus.h

- Code/Editor/EditorModularViewportCameraComposer.cpp
- Code/Editor/EditorViewportCamera.cpp
- Code/Editor/Lib/Tests/Camera/test_EditorCamera.cpp
- Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ModularViewportCameraController.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ModularViewportCameraControllerRequestBus.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ModularViewportCameraController.cpp
This functionality is no longer required and winds up just making things more complicated, removing for simplicity sake 🙂
> Remove camera LookAtAfterInterpolation

- Code/Framework/AzGameFramework/AzGameFramework/Application/GameApplication.cpp
- Code/Legacy/CrySystem/SystemInit.cpp
- cmake/Projects.cmake
This makes the engine.pak file consistent with naming scheme of other pak files such as assets.pak.
It will also help avoid issues with mounting the file on Linux.
Cherry-picked commit 2a92346e24177d2a0bc7c936b65a98cdfa867196 to fix issue with the Engine.pak file not being mounted in Release builds due to the `m_archiveFileIO::Exists` check only checking for file existence within a Pak.
> Updated references to Engine.pak to be lowercase engine.pak

- Code/Framework/AzFramework/CMakeLists.txt
- Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbApplication.cpp
- Code/Framework/AzFramework/Tests/Main.cpp
- Code/Framework/AzFramework/Tests/Platform/Android/platform_specific_test_targets.cmake
- Code/Framework/AzFramework/Tests/Platform/Common/Xcb/Actions.h
- Code/Framework/AzFramework/Tests/Platform/Common/Xcb/Main.cpp
- Code/Framework/AzFramework/Tests/Platform/Common/Xcb/MockXcbInterface.cpp
- Code/Framework/AzFramework/Tests/Platform/Common/Xcb/MockXcbInterface.h
- Code/Framework/AzFramework/Tests/Platform/Common/Xcb/Printers.cpp
- Code/Framework/AzFramework/Tests/Platform/Common/Xcb/Printers.h
- Code/Framework/AzFramework/Tests/Platform/Common/Xcb/XcbInputDeviceKeyboardTests.cpp
- Code/Framework/AzFramework/Tests/Platform/Common/Xcb/azframework_xcb_tests_files.cmake
- Code/Framework/AzFramework/Tests/Platform/Linux/platform_specific_test_targets.cmake
- Code/Framework/AzFramework/Tests/Platform/Mac/platform_specific_test_targets.cmake
- Code/Framework/AzFramework/Tests/Platform/Windows/platform_specific_test_targets.cmake
- Code/Framework/AzFramework/Tests/Platform/iOS/platform_specific_test_targets.cmake
- Code/Framework/AzFramework/Tests/frameworktests_files.cmake
This creates a new library, AzFramework.Xcb.Tests.so. Only inside that library, calls to the xcb functions get routed to a mock. This allows the tests to run a full event loop without talking to a live X server.
> Add a unit test for `XcbInputDeviceKeyboard`

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.h
- Gems/EMotionFX/Code/Source/Integration/System/SystemComponent.cpp
- Gems/EMotionFX/Code/Source/Integration/System/SystemComponent.h
Untangled the system component from editor ticking dependencies and moved it to the main window which is the more logical place for it.
> Animation Editor: Move real-time plugin updates from SystemComponent to the main window

- Code/Framework/AzCore/AzCore/Asset/AssetManager.cpp
- Gems/Vegetation/Code/Tests/DynamicSliceInstanceSpawnerTests.cpp
- Gems/Vegetation/Code/Tests/PrefabInstanceSpawnerTests.cpp
- Gems/Vegetation/Code/Tests/VegetationTest.h
This replicates the old behavior of the EBusQueuePolicy::Execute
function that would continue to execute functions if new ones were added
during the execution of the current queue.
Split the TestFixture class from the AssetHandler and EBus handler for the DynamicSliceInstanceSpawnerTests and
PrefabInstanceSpawnerTest.
This avoids the AssetMananager destructor from deleting the test fixture
if the call to UnregisterHandler is ever removed. This also allows the
memory allocators to get online earlier.
> Changed the AssetManager DispatchEvents function to continously pump the AssetBus of queued functions until empty.

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_GPU.py
- Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportComponent.cpp
- Passes locally and I got it to fail locally before by making the test take longer.  The original failure appears timeout related.
- Also fixed the spelling of "configurtion" to be "configuration".
- Sample output below:
```
C:\git\o3de>C:\git\o3de\python\runtime\python-3.7.10-rev1-windows\python\python.exe -m pytest -vv -s --build-directory=".\build\bin\profile" AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Main_GPU.py -k test_MaterialEditorLaunch_AllRHIOptionsSucceed
#
#
|MaterialEditor.log| 2021-09-30T19:02:34{0000000000005290}[Material Editor]     Loaded viewport configuration: materialeditor/viewportmodels/beveledcylinder.modelpreset.azasset.
|MaterialEditor.log| 2021-09-30T19:02:34{0000000000005290}[Material Editor]     Finished loading viewport configurations. …
```
> Fix Vulkan RHI test failure by increasing timeout

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
'MaterialEditor' on Linux/Mac does not have an '.exe' extension
> Update MaterialEditor launcher to use platform traits for executable extensions

- Code/Framework/AzFramework/Platform/Windows/AzFramework/Windowing/NativeWindow_Windows.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI/AsyncUploadQueue.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI/AsyncUploadQueue.h
Fixed the memory leaking with ID3D12CommandAllocator in DX12 AsyncUploadQueue. Add reset for the ID3D12CommandAllocator when the commandlist was executed.
Fixed another small memory leak in NativeWindow.
https://github.com/o3de/o3de/issues/4323
Signed-off-by: Qing Tao <qingtao@amazon.com>
> ATOM-16558 Buffer memory leak

- Code/Framework/AzToolsFramework/AzToolsFramework/API/ViewportEditorModeTrackerInterface.h
- Code/Framework/AzToolsFramework/AzToolsFramework/API/ViewportEditorModeTrackerNotificationBus.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/ComponentModeCollection.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/FocusMode/FocusModeSystemComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorDefaultSelection.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorPickEntitySelection.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/ViewportEditorModeTracker.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/ViewportEditorModeTracker.h
- Code/Framework/AzToolsFramework/Tests/Viewport/ViewportEditorModeTests.cpp
**Overview**
This PR changes the id associated with each `ViewportEditorModeTracker` from `ViewportId` to `EntityContxtId`. The implication here is that trackers are now organized by entity context and not viewport.
**Testing**
```
[==========] Running 31 tests from 5 test cases.
[----------] 4 tests from ViewportEditorModesTestsFixture
[ RUN      ] ViewportEditorModesTestsFixture.NumberOfEditorModesIsEqualTo4
[       OK ] ViewportEditorModesTestsFixture.NumberOfEditorModesIsEqualTo4 (0 ms)
[ RUN      ] ViewportEditorModesTestsFixture.InitialEditorModeStateHasAllInactiveModes
[       OK ] ViewportEditorModesTestsFixture.InitialEditorModeStateHasAllInactiveModes (1 ms)
[ RUN      ] ViewportEditorModesTestsFixture.SettingOutOfBoundsModeActiveRetur …
```
> Change editor viewport mode tracker id from viewport to entity context.

- Gems/PhysX/Code/CMakeLists.txt
The benchmark code is still built, as it is part of the PhysX.Tests project.
Currently jenkins has a 1500sec(25min) timeout, the benchmarks can sometimes take over 1500sec and cause a build failure for timeout.
Jenkins currently doesn't upload the results of the benchmarks, so this is ok.
> Moving run Physx Benchmarks behind a cmake flag

- Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/Debug/Trace_UnixLike.cpp
Hi O3DE Team
The current implementation for performDebuggerDetection is giving wrong results. processStatusView.find(tracerPidString) will return the starting location of that string.  If I am not wrong continuing in the logic, checking the first letter "t" is not a whitespace and neither "0" it will return always true.
Signed-off-by: Yaakuro <y1@codeposer.net>
> Fix issue that gives wrong results for running debugger

- Code/Framework/AzCore/AzCore/EBus/EBus.h
Change urls to point to O3DE documentation.  Fixes issue #913 that was transferred to sig-docs-community.
Fix o3de/o3de.org#913
> AzCore/Ebus/Ebus.h: Fix docs urls Issue#913

- Code/Editor/UndoDropDown.cpp
- Code/Tools/AssetProcessor/native/ui/AssetTreeModel.cpp
- Code/Tools/AssetProcessor/native/ui/ProductAssetTreeModel.cpp
- Code/Tools/AssetProcessor/native/ui/SourceAssetTreeModel.cpp
When the parent is the tree root element, beginInsertRows must be
called with an invalid (but legal) index. A QModelIndex with a row
index of zero when the parent has no children is an illegal index
and will result in "undefined behavior", like the "index out of
range" one.
Therefore, if our parent is the tree root element, we use QModelIndex()
instead.
Fixes #2343
This PR also contains two other commits which are not strictly necessary, one
makes the code more in line with Qt best practices, the other adds some debugging
asserts.
> Fix "index out of range" error in AssetProcessor

- Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
- Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.h
- Code/Editor/Viewport.h
- Code/Framework/AzToolsFramework/AzToolsFramework/API/ToolsApplicationAPI.h
This is a change spotted with the visibility removal changes while looking at `HitTest` function. This code no longer needs to exist in the engine/editor.
> Remove legacy sandbox picking - no longer used

- Gems/Multiplayer/Code/CMakeLists.txt
- Gems/Multiplayer/Code/Include/Multiplayer/Components/NetBindComponent.h
- Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkHierarchyRootComponent.h
- Gems/Multiplayer/Code/Tests/CommonBenchmarkSetup.h
- Gems/Multiplayer/Code/Tests/ServerHierarchyBenchmarks.cpp
- Gems/Multiplayer/Code/multiplayer_tests_files.cmake
Already proving useful by pointing out a performance defect. (I have fixes for that that will go in a separate PR.)
```
Run on (32 X 3394 MHz CPU s)
CPU Caches:
L1 Data 32K (x16)
L1 Instruction 32K (x16)
L2 Unified 524K (x16)
L3 Unified 33554K (x2)
---------------------------------------------------------------------------------------------------------------
Benchmark                                                                     Time             CPU   Iterations
---------------------------------------------------------------------------------------------------------------
ServerDeepHierarchyBenchmark/RebuildHierarchy                              43.7 us         43.9 us        16000
ServerDeepHierarchyBenchmark/RebuildHierarchyRemoveAndAddLastChild          133 us          134 us …
```
> First google benchmarks for hierarchy components.

- Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridBlendDistancePass.cpp
- Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridBlendIrradiancePass.cpp
- Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridBorderUpdatePass.cpp
- Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridClassificationPass.cpp
- Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridRelocationPass.cpp
- Gems/Atom/Feature/Common/Code/Source/MorphTargets/MorphTargetDispatchItem.cpp
- Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshDispatchItem.cpp
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPIUtils.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ComputePass.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/RPIUtils.cpp
Create helper function for getting threads per
group from a compute shader
Added GetComputeShaderNumThreads() functions to RPIUtils.
Updated existing code that was looking for 'numthreads' attribute data
with the new GetComputeShaderNumThreads() API.
Signed-off-by: garrieta <garrieta@amazon.com>
> Create helper function for getting threads per

- Gems/LmbrCentral/gem.json
per: https://github.com/o3de/o3de.org/pull/993
Signed-off-by: Mike Cronin <58789750+micronAMZN@users.noreply.github.com>
> Updated LmbrCentral gem.json documentation_url field. This doc is being moved 

- Gems/EMotionFX/Code/CMakeLists.txt
- Gems/EMotionFX/Code/Source/Integration/Components/SimpleLODComponent.cpp
- Gems/EMotionFX/Code/Source/Integration/Components/SimpleLODComponent.h
The LOD level for skinned meshes is determined in the render phase, which is after the animation update and is also specific to the camera/target Atom renders to, which means that different render targets could end up using different LOD levels depending on how much screen space the character's bounding box takes.
In order to make sure that all transformations are calculated by EMotion FX that the skinned mesh Atom wants to render are available, the Simple LOD Component takes ownership of the LOD level and uses the Atom LOD override. That way Atom adapts to the LOD level determined by the Simple LOD component and makes sure the skeletal matches with the geometry LOD levels.
> EMotion FX: Simple LOD Component to use Atom LOD override

- Gems/Atom/Feature/Common/Assets/Passes/EnvironmentCubeMapForwardMSAA.pass
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionComposite.azsl
Removed the ScatterDistanceOutput texture from the EnvironmentCubeMapForwardMSAAPass.
Removed unused Srgs from the ReflectionCompositePass.
> Clean up benign errors that occur when a Reflection Probe is baked

- AutomatedTesting/Registry/physx_overrides/Collider_AddingNewGroupWorks.setreg_override
- AutomatedTesting/Registry/physx_overrides/Collider_CollisionGroupsWorkflow.setreg_override
- AutomatedTesting/Registry/physx_overrides/Collider_DiffCollisionGroupDiffCollidingLayersNotCollide.setreg_override
- AutomatedTesting/Registry/physx_overrides/Collider_NoneCollisionGroupSameLayerNotCollide.setreg_override
- AutomatedTesting/Registry/physx_overrides/Collider_SameCollisionGroupSameCustomLayerCollide.setreg_override
- AutomatedTesting/Registry/physxsystemconfiguration.setreg
- Gems/Blast/Code/Source/Components/BlastSystemComponent.cpp
- Gems/Blast/Code/Source/Components/BlastSystemComponent.h
- Gems/PhysX/Code/Editor/Source/Components/EditorSystemComponent.cpp
- Gems/PhysX/Code/Source/System/PhysXSystem.cpp
- Gems/PhysX/Code/Source/SystemComponent.cpp
- Avoid saving blast global configuration unnecessarily every time the editor is opened.
- Fixed how to obtain the default physics material library. The relative path needs to be from the project folder, not the asset folder inside the project. It was also missing saving the physx configuration after a the default library is assigned to it.
- Fixed asset id for physics material asset 'assets/physics/surfacetypemateriallibrary.physmaterial'
> Fixed PhysX and Blast creation of default config files

- Gems/AtomTressFX/Code/Rendering/HairFeatureProcessor.cpp
- Gems/AtomTressFX/Code/Rendering/HairRenderObject.cpp
- Gems/AtomTressFX/Code/Rendering/HairRenderObject.h
- The index was not passed every frame although the objects' material array was built during the frame
Signed-off-by: Adi-Amazon <barlev@amazon.com>
> Hair - fixing per object UI control per object

- scripts/build/Platform/Windows/build_config.json
The TIAF job is not successfully writing to its persistant storage location, causing all jobs to run TIAF on a change list generated between `c9a3b51fa934af1ae316a787571111e23bcf9ec9` and the commit for the PR build. As the current focus of development is on integrating Python tests into TIAF, the job will be disabled and this issue fixed once the Python tests integration is complete.
> Disable TIAF Jenkins job

- Code/Legacy/CrySystem/ViewSystem/ViewSystem.cpp
- Gems/AtomLyIntegration/AtomViewportDisplayInfo/Code/Source/AtomViewportDisplayInfoSystemComponent.cpp
Fixes two unrelated crashes when attempting to "quit" launcher from the debug console. 
- AtomViewportDisplayInfo's `OnRenderTick()` relies on data that was being released from memory by `~AtomFont()` dtor lines 367-372.
- Invoke wouldn't dispatch because `__vfptr` points to an empty vftable. Memory tests reveal that the empty table belonged to CrySystem's `LegacyViewSystem > DebugCamera > InputChannelEventListener.` DebugCamera dtor was never called.
Since memory issues are not consistently reproducible, I've included video:
https://user-images.githubusercontent.com/90814386/138777413-1dd63c84-c0d9-4c89-91e4-70ef5d919822.mp4
> Fixes debug console's "quit" issues

- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/InvalidClicks.h
This was a total [_schoolboy error_](https://www.urbandictionary.com/define.php?term=Schoolboy%20Error) on my part, I'd not initialized the object state correctly 🙈
Depending on the random bits that happened to be in `m_invalidClickPosition`, the message may get displayed on screen or not. The initial opacity should also _not_ have been set to `1.0`.
> Fix 'focus' text appearing when it shouldn't

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserComponent.cpp
There seemed to be a memory leak in the AssetBrowserComponent. It was calling `release` instead of `reset` in `m_assetBrowserModel` so it wasn´t really being deleted.
> Fixed memory leak of the in the AssetBrowserComponent

- Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiGpuProfiler.h
- Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiGpuProfiler.inl
This was happening because the time variable storing the last update time was not initialized, therefore an arbitrarily large value was assigned and the update condition was never satisfied.  
Furthermore, the condition `m_lastUpdateTimeMicroSecond == 0` could be ignored since the alternative condition `now - m_lastUpdateTimeMicroSecond > 1000000` will be already satisfied after the first tick, which can be considered as negligible.
https://github.com/o3de/o3de/issues/5079
Signed-off-by: Santi Paprika <santi.gonzalez.cs@gmail.com>
> Fix frozen metrics on the timestamp view when using the 'Once per Second' update frequency mode

- Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/AssetCatalogModel.cpp
- Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/AssetCatalogModel.h
Previous logic would keep visiting next entries in `m_extensionToAssetType` map, if the previous entry had multiple types.
The old code was only exiting the inner loop.
The main change is that now the first found matching asset type is returned.
> Fix asset type retrieval in AssetCatalogModel::GetAssetType

- Templates/PythonToolGem/Template/.gitignore
- Templates/PythonToolGem/template.json
Added .gitignore file to the gemplate for our base python tool so that `__pycache__` and `.pyc` files will be ignored.
> Added .gitignore for __pycache__ and pyc files to the python tool gemplate

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSerializer.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSerializer.h
- Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_editor_files.cmake
The editor component contains an editor specific, dynamically generated version of the material slots to display all the possible options, organize properties for the user interface, and add custom actions.
The critical data is already stored inside of the component controller configuration, which only stores a map of modified or overridden values.
This change disables serialization of the redundant data for prefabs.
> Created custom JSON serializer for editor material component

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.hxx
Cherry-picking @pollend 's fix to the Entity Outliner issue described here: https://github.com/o3de/o3de/issues/4798
Fix had been submitted to development, but we also want it in Stabilization for GA.
> Cherry-pick: resolve entity ordering for EntityOutliner

- Code/Framework/AzCore/AzCore/Math/Internal/SimdMathCommon_sse.inl
- Code/Framework/AzCore/AzCore/Math/Internal/SimdMathVec1_sse.inl
- Code/Framework/AzCore/AzCore/Math/Internal/SimdMathVec2_sse.inl
- Code/Framework/AzCore/AzCore/Math/Internal/SimdMathVec3_sse.inl
- Code/Framework/AzCore/AzCore/Math/Internal/SimdMathVec4_sse.inl
This fixes an issue that was causing unit tests to fail on Linux in profile
builds with clang 12, specifically the `MATH_Vector2.TestReciprocal`
test:
```
TEST(MATH_Vector2, TestReciprocal)
{
AZ_TEST_ASSERT(Vector2(2.0f, 4.0f).GetReciprocal().IsClose(Vector2(0.5f, 0.25f)));
AZ_TEST_ASSERT(Vector2(2.0f, 4.0f).GetReciprocalEstimate().IsClose(Vector2(0.5f, 0.25f)));
}
```
The second test, `GetReciprocalEstimate()`, is the one that was failing.
`GetReciprocalEstimate()` would return the same value in both clang 6 and
clang 12, but clang 12 would generate different code for `IsClose()`.
`IsClose(Vector2 a, Vector2 b, float tolerance)` works like this:
* subtract b from a, and take the absolute value of the result, store in c
* check that all the elements of c are less than the tolerance
The …
> Perform sse float comparisons with the floating-point intrinsics

- Code/Tools/AssetProcessor/native/tests/AssetProcessorTest.h
Fix Assert Absorber being leaked due to one of the tests setting m_errorAbsorber to nullptr without deleting the object
> [LYN-7245] Fix Assert Absorber being leaked

- Tools/LyTestTools/ly_test_tools/o3de/asset_processor.py
* adding more time via ap_max_activate_time so that the Debug version of AP-GUI can load all the builder DLLs
Signed-off-by: jackalbe <23512001+jackalbe@users.noreply.github.com>
> {lyn7621} adding more time via ap_max_activate_time

- Code/Tools/ProjectManager/Source/CreateProjectCtrl.cpp
- Code/Tools/ProjectManager/Source/CreateProjectCtrl.h
Fixes an issue https://github.com/o3de/o3de/issues/4754 caused by a copy/paste error in a previous update which resulted in an empty path being submitted when enabling a gem.
**Testing** 
- created a new project with an added gem, which failed before the change and succeeds after.
> Fix new project path when enabling gem

- Code/Framework/AzToolsFramework/AzToolsFramework/ContainerEntity/ContainerEntitySystemComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/FocusMode/FocusModeSystemComponent.cpp
- Code/Framework/AzToolsFramework/Tests/BoundsTestComponent.cpp
- Code/Framework/AzToolsFramework/Tests/BoundsTestComponent.h
These missing calls were causing a lot of tests to fail afterwards when running `AzToolsFrameworkTests` locally. These calls are required and there's spam in the logs without them unfortunately.
```
[==========] Running 945 tests from 156 test cases.
...
[----------] Global test environment tear-down
[==========] 945 tests from 156 test cases ran. (197202 ms total)
[  PASSED  ] 945 tests.
```
> Add missing reflection calls

- Code/Editor/Lib/Tests/test_ViewportManipulatorController.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputManager.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputManager.h
This change stops all inputs being cleared when focus changes between windows/widgets.
How things currently stand there's a problem when holding Alt (to begin camera orbit). If the user clicks outside the Viewport (e.g. changing selection of an entity in the outliner), then as the input is cleared it's as if Alt was released and clicking back in the viewport has the camera no longer orbit. This can be very disruptive to an artist/designer's flow, so I'd like to avoid it but at the same time I don't want this to cause any other issues.
I'd be very grateful to get people's feedback and ideas/suggestions and can potentially get QA involved too if they know of any existing edge cases or good things to test.
~I'm also going to investigate authoring a test for this which is why this is in draft …
> Do not clear input channels everytime focus changes

- Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/Debug/Trace_WinAPI.cpp
Move Exception PrintCallstack call before any ebus calls to help track down issue with crash during an exception
> [LYN-7245] Move Exception PrintCallstack call before any ebus calls

- Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/Spawnable/SpawnAllEntitiesBenchmarks.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/Spawnable/SpawnableBenchmarkFixture.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/Spawnable/SpawnableBenchmarkFixture.h
- Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
Adds 3 benchmarks for SpawnAllEntities call in SpawnableEntitiesManager:
1. Spawns a single spawnable a very large number of times
2. Spawns  a single big spawnable with a very large number of entities in it
3. Combines 1 and 2 to compare which performs better by altering the number of entities in a spawnable and the number of spawn calls.
Here are the results from a local run - 
Run on (20 X 3312 MHz CPU s)
CPU Caches:
L1 Data 32K (x10)
L1 Instruction 32K (x10)
L2 Unified 1048K (x10)
L3 Unified 14417K (x1)
```
Benchmark                                                                        Time             CPU   Iterations
------------------------------------------------------------------------------------------------------------------ …
```
> Add benchmarks for SpawnAllEntities call in SpawnableEntitiesManager

- Code/Framework/AzFramework/AzFramework/IO/LocalFileIO.cpp
Fix bug in LocalFileIO::ConvertToAliasBuffer when a resolved alias ends in a path separator, in which case we do not want to consume it when replacing it with the alias.
eg. If the @products@ alias resolves to "C:\\" and we call ConvertToAliasBuffer with "C:\\some_folder\\some_file.txt", the current behaviour results in "@products@some_folder\\some_file.txt", but it needs to be "@products@\\some_folder\\some_file.txt"
> Fix bug in LocalFileIO::ConvertToAliasBuffer when a resolved alias ends in a path separator.

- Code/Framework/AzFramework/Platform/Linux/AzFramework/Asset/AssetSystemComponentHelper_Linux.cpp
This adds support for the `ap_tether_lifetime` cvar in Linux. It extends
the solution implemented in #2799 to add the same support on Linux.
> [Linux] Terminate AssetProcessor when spawned by the parent project process

- Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
Cleaning up and adding additional debug messages to track down SEGFAULT occurring in unit tests.
These will be removed once the issue is fixed.
> [LYN-7245] AP unit test segfault - Clean up debug messages

- Code/Framework/AzCore/AzCore/Task/TaskExecutor.cpp
- Code/Framework/AzCore/AzCore/Task/TaskGraph.cpp
- Code/Framework/AzCore/AzCore/Task/TaskGraph.h
- Code/Framework/AzCore/AzCore/Task/TaskGraph.inl
- Code/Framework/AzCore/Tests/TaskTests.cpp
- Gems/Atom/Feature/Common/Code/Source/FrameCaptureSystemComponent.cpp
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Culling.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Scene.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
Enable use of TaskGraph in the png capture code.
Enable TaskGraphEvents to wait for multiple TaskGraphs to complete.
> Enable Atom CullingScene to use TaskGraph

- Gems/Atom/Bootstrap/Assets/seedList.seed
- Gems/Atom/Feature/Common/Assets/seedList.seed
- Gems/Atom/RPI/Assets/seedList.seed
- Gems/AtomLyIntegration/AtomFont/Assets/seedList.seed
- Gems/AtomLyIntegration/AtomViewportDisplayIcons/Assets/seedList.seed
- Gems/AtomLyIntegration/CommonFeatures/Assets/seedList.seed
- Gems/AtomTressFX/Assets/seedList.seed
The seedlist files themselve are pretty verbose, so here is the output when you use AssetBunderlBatch.exe with --print
Contents of ( D:\GitHub\stabilization2110\o3de\Gems\LyShine\Assets\seedList.seed ):
textures/cursor_default.tif.streamingimage                  pc, linux, android, ios, mac, provo, salem
lyshine_dependencies.xml                                    pc, linux, android, ios, mac, provo, salem, jasper
shaders/lyshineui.azshader                                  pc, linux
passes/lyshineparent.pass                                   pc, linux
passes/lyshinepasstemplates.azasset                         pc, linux
Contents of ( D:\GitHub\stabilization2110\o3de\Gems\Atom\Bootstrap\Assets\seedList.seed ):
passes/mainrenderpipeline.azasset                           pc, linux
Contents of …
> Creating default seedList.seed files for Atom gems

- Gems/EMotionFX/Code/Source/Integration/Components/SimpleLODComponent.cpp
Modifying a copy to not overrun if the target is smaller than the size of the default value array
Signed-off-by: Tommy Walton <waltont@amazon.com>
> Fix for crash when using Simple LOD distance component

- Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArray.cpp
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Shader/Shader.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Shader/ShaderVariant.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderAsset.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Material/Material.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassLibrary.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Specific/ImageAttachmentPreviewPass.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Shader/Shader.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Shader/ShaderVariant.cpp
- Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/MaterialAsset.cpp
- Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderAsset.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/DiffuseGlobalIllumination/EditorDiffuseProbeGridComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/ReflectionProbe/EditorReflectionProbeComponent.cpp
This fixes the problem described in the title.
Consolidated the responsibility to update the root shader variant
asset into the Shader() class. It was unnecessarily spread across
Shader(), ShaderVariant() and ShaderAsset().
In particular OnAssetReloaded now makes a temporary copy of the root
ShaderVariantAsset and updates the ShaderAsset with such reference
only when OnAssetReloaded() is called on behalf of the ShaderAsset.
> Shaders changes require two or more change cycles before updating

- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.h
Remove AssetProcessorManagerTest AssertAbsorber  and update test to use the one from the base class instead.
AssetProcessorManagerTest and its parent class both have an instance of the same AssertAbsorber which is unnecessary, this unifies to use just one.
> [LYN-7245] Remove AssetProcessorManagerTest AssertAbsorber 

- Code/Framework/AzFramework/AzFramework/Input/Buses/Requests/InputDeviceRequestBus.h
- Code/Framework/AzFramework/AzFramework/Input/Devices/Gamepad/InputDeviceGamepad.cpp
- Code/Framework/AzFramework/AzFramework/Input/Devices/Gamepad/InputDeviceGamepad.h
- Code/Framework/AzFramework/AzFramework/Input/Devices/Keyboard/InputDeviceKeyboard.cpp
- Code/Framework/AzFramework/AzFramework/Input/Devices/Keyboard/InputDeviceKeyboard.h
- Code/Framework/AzFramework/AzFramework/Input/Devices/Motion/InputDeviceMotion.cpp
- Code/Framework/AzFramework/AzFramework/Input/Devices/Motion/InputDeviceMotion.h
- Code/Framework/AzFramework/AzFramework/Input/Devices/Mouse/InputDeviceMouse.cpp
- Code/Framework/AzFramework/AzFramework/Input/Devices/Mouse/InputDeviceMouse.h
- Code/Framework/AzFramework/AzFramework/Input/Devices/Touch/InputDeviceTouch.cpp
- Code/Framework/AzFramework/AzFramework/Input/Devices/Touch/InputDeviceTouch.h
- Code/Framework/AzFramework/AzFramework/Input/Devices/VirtualKeyboard/InputDeviceVirtualKeyboard.cpp
- Code/Framework/AzFramework/AzFramework/Input/Devices/VirtualKeyboard/InputDeviceVirtualKeyboard.h
This augments the existing functionality that allows for an input device implementation to be swapped out at runtime,
> Allow input devices to be constructed with a custom implementation.

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Optimized.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_OcclusionCullingPlaneAdded.py
Adding P0 Occlusion Culling Plane test, and including it in the TestSuite_Main_Optimized.py.
Here is the output from running the grid test ("hydra_AtomEditorComponents_OcclusionCullingPlaneAdded.py") in editor:
pyRunFile ../../Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_OcclusionCullingPlaneAdded.py
Report:
[SUCCESS] Success: Occlusion Culling Plane Entity successfully created
[SUCCESS] Success: Entity has a Occlusion Culling Plane component
[SUCCESS] Success: UNDO deletion success
[SUCCESS] Success: REDO …
> Adding P0 Occlusion Culling Plane test

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusPublicInterface.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/LevelRootUiHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/LevelRootUiHandler.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabUiHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabUiHandler.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabViewportFocusPathHandler.cpp
Introduce shortcuts to open and close prefabs for editing. Also refactor current context menu and click interactions to match.
To be more precise:
- Right clicking on a focused prefab now correctly displays the "Close Prefab" context menu item. This will close the focused prefab, and move the focus up one level to its parent (exactly the same behavior as pressing the "up one level" button in the breadcrumbs);
- Both context menu items now show the shortcuts associated to those actions;
- Pressing + while a single prefab is selected opens it for editing. Since most compact US keyboards (for example on laptops) have + as a shift modifier for =, we have both = and + act as the + shortcut to simplify usage in those environments;
- Pressing - while a prefab is in focus closes it. Note that the …
> LYN-7536 | Focus Mode - Introduce shortcuts to open/close prefab editing

- Templates/PythonToolGem/Template/Editor/Scripts/${NameLower}_dialog.py
Updated the custom Python tool template to include logic to help the user quickly iterate on design by creating/launching a new tool if the user executes the script from the `Python Scripts` tool. This allows you to quickly makes changes in your Python script/tool and see the results immediately without having to close/re-launch the Editor.
> Add quick iteration workflow to the custom python tool template.

- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/SpinBox.cpp
looks like the delta already accounts for the additional change when you scroll past the edge of the screen so the delta is consistent. seems a lot nicer to use then having the movement clip at the edge of the screen. I was looking at blender and it seems to instead hides the mouse cursor when using a spinbox and does the mouse cycling behavior when using the transform widgets for an item in the editor and clips the cursor to edge of the viewport and cycles the mouse back over. I think it might be worth implementing for the viewport. 
https://user-images.githubusercontent.com/854359/139109561-ebf53d57-a4ce-440b-bddf-40462da9e3e6.mp4 
> bugfix: cycle mouse to the other side of the screen when using scrollbox

- Gems/Atom/Feature/Common/Code/Source/AuxGeom/AuxGeomDrawQueue.cpp
When calling reserve vertex amount the function seems to ignore the previous offset.
> vertexbuffer / indexBuffer reserve amount seems off in the auxgeom draw queue

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Optimized.py
- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_HDRColorGradingAdded.py
Added P0 test for HDR Color Grading component
pyRunFile ../../Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_HDRColorGradingAdded.py
Report:
[SUCCESS] Success: HDR Color Grading Entity successfully created
[SUCCESS] Success: Entity has an HDR Color Grading component
[SUCCESS] Success: HDR Color Grading component disabled
[SUCCESS] Success: HDR Color Grading component enabled
[SUCCESS] Success: Enable HDR Color Grading parameter enabled
[SUCCESS] Success: …
> Test parallel P0  HDR Color Grading Component

- Code/Editor/EditorViewportWidget.cpp
- Code/Editor/EditorViewportWidget.h
- Code/Framework/AzFramework/AzFramework/Viewport/ViewportBus.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiDisplay.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiDisplay.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiDisplayLayout.h
- Gems/ImGui/Code/Source/LYCommonMenu/ImGuiLYCommonMenu.cpp
This change ensures that the ImGui main menu displays below the viewport border when it is showing.
This PR also fixes some issues with high dpi displays (prior to this change certain elements on the top menu bar would appear in the wrong place (see below)
Before:
This PR also fixes an issue when returning from Focus Mode (after the viewport border had been displayed) where the Viewport UI clusters would return to the top of the viewport and not sit below the ImGui menu).
Please see the video below of the ImGui menu repositioning when the vieport border is displayed or not
https://user-images.githubusercontent.com/82228511/140072604-231753b7-d7b4-4e8c-98c6-18981ef5af58.mp4
> Ensure ImGui menu is displayed when the Viewport UI viewport border is showing

- Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp
The issue was that EditorActorComponent (added by the drag and drop of the FBX into the entity) continued with the loading of an actor asset even though the component is not activated due to incompatible services, which ultimately lead to logic which should never have been reached and crashing. 
Also fixed EditorActorComponent missing activation and deactivation of the base editor component class, which is necessary.
All tests from EMotionFX.Editor.Tests passed.
> Fixed editor crash dropping an fbx to entity inspector

- Gems/AtomTressFX/Assets/Passes/HairParentShortCutPass.pass
- Gems/AtomTressFX/Assets/Passes/HairShortCutGeometryShading.pass
- Gems/AtomTressFX/Assets/Shaders/HairRenderingFillPPLL.azsl
- Gems/AtomTressFX/Assets/Shaders/HairShortCutGeometryShading.azsl
- Removing unused depth buffer from Srg to fix metal shader build
- Back light correction.  This fix will block TT lobe (back lobe) from allowing light transfer
- By doing this we remove the requirement to add self shadowing in most cases, hence removing heavy render pass.
Exception:
- Thin hair will still pass light and therefor there is still a need to read depth buffer and compare as a second step to avoid adding heavy shadowing pass / comparison.
Before change - TT lighting not blocked:
After change - preventing TT back light transfer due to thickness:
Images courtesy of Apocalypse Studios and Denis Dyack and are WIP on the hair technology enhancing the TressFX by AMD
> Hair - crucial optimization and bug fix

- Code/Legacy/CryCommon/ISystem.h
- Code/Legacy/CryCommon/platform_impl.cpp
- Code/Legacy/CrySystem/SystemInit.cpp
This works around the crash by statically linking editor common to EditorAssetImporter. There is some kind of mis-configuration where AZ::SystemAllocator is not correctly configured in the dynamic binary. I would like to investigate this more but this should address the crash atleast. 
how do static fields work between shared libraries? InitializeEditorCommonISystem is called in IEditorImpl.cpp but why is no allocator defined.  
issue: https://github.com/o3de/o3de/issues/4813
> bugfix: resolve crash with FBX Settings (#4813)

- Code/Framework/AzFramework/Platform/Mac/AzFramework/Asset/AssetSystemComponentHelper_Mac.cpp
- Code/Tools/BundleLauncher/O3DE_SDK_Launcher.cpp
- Code/Tools/ProjectManager/Platform/Linux/ProjectUtils_linux.cpp
- Code/Tools/ProjectManager/Platform/Mac/ProjectUtils_mac.cpp
- Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp
- Code/Tools/ProjectManager/Source/ProjectUtils.h
- Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
1. Fix "Open Editor" button not launching Editor on Mac.
2. Update LaunchAssetProcessor() paths on Mac.
3. LaunchAssetProcessor() uses ProcessWatcher wrappers.
4. SDK Launcher registers the engine when launching.
NOTE: Mac doesn't support running AP in tethered mode yet. Linux uses `prctl()` which isn't an option on MacOS. MacOS does support process termination notifications through kqueues/kevents or Grand Central Dispatch. But those options are callback based and would require modifying the child process's(in our case AP) source. This needs more investigation on Mac.
> [MacOS] Launching Editor from ProjectManager and other misc. fixes

- AutomatedTesting/Gem/PythonTests/CMakeLists.txt
Removing flaky multiplayer tests. Will bring back once we can reproduce and correct the flakes
> Removing Flaky Multiplayer Tests

- Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/Outliner/EntityOutliner.qss
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutliner.qss
Closes #5172
Removed line including property `flat` in `m_display_options` from both the `EntityOutliner.qss`
> fix issue #5172

- Code/Editor/Platform/Linux/Editor/Core/QtEditorApplication_linux.cpp
- Code/Editor/Platform/Linux/Editor/Core/QtEditorApplication_linux.h
- Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbApplication.cpp
- Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbConnectionManager.h
- Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbEventHandler.h
- Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.cpp
- Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.h
- Code/Framework/AzFramework/Tests/Platform/Common/Xcb/Actions.h
- Code/Framework/AzFramework/Tests/Platform/Common/Xcb/MockXcbInterface.cpp
- Code/Framework/AzFramework/Tests/Platform/Common/Xcb/MockXcbInterface.h
- Code/Framework/AzFramework/Tests/Platform/Common/Xcb/XcbBaseTestFixture.h
- Code/Framework/AzFramework/Tests/Platform/Common/Xcb/XcbInputDeviceKeyboardTests.cpp
- Code/Framework/AzFramework/Tests/Platform/Common/Xcb/XcbInputDeviceMouseTests.cpp
- Code/Framework/AzFramework/Tests/Platform/Common/Xcb/azframework_xcb_tests_files.cmake
This does a few things:
* [Linux] Return the active window when there's no cursor constraint window
* [Linux] Add unit tests for xcb mouse input
* [Linux] Unify Editor and Game raw mouse event handling
> [Linux] Unify Editor and Game raw mouse event handling

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Optimized.py
- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_BloomAdded.py
Added P0 test for Bloom component + Updated Docstring for missing Enable HDR Color Grading toggle
pyRunFile ../../Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_BloomAdded.py
Report:
[SUCCESS] Success: Bloom Entity successfully created
[SUCCESS] Success: Entity has a Bloom component
[SUCCESS] Success: Bloom component disabled
[SUCCESS] Success: Bloom component enabled
[SUCCESS] Success: Enable Bloom parameter enabled
[SUCCESS] Success: UNDO deletion success …
> Test parallel Add P0 Bloom

- Gems/Terrain/Code/Source/Components/TerrainHeightGradientListComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainHeightGradientListComponent.h
Using the Altitude Gradient as an input to the Height Gradient List can cause infinite recursion since it is both setting and fetching the same height value.  Added guards to warn if this occurs and gracefully handles the situation.
> Prevent infinite recursion with Altitude Gradient.

- Code/Tools/SceneAPI/SceneUI/CommonWidgets/ProcessingOverlayWidget.cpp
Set the appropriate window flags on the `ProcessingOverlayWidget` so that it always appears on top of the asset importer window which creates it. Tested making a change in the scene settings and verified the processing dialog always shows on top.
> Set window flags so the processing overlay widget always appears on top.

- AutomatedTesting/Gem/PythonTests/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/Multiplayer/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Sandbox.py
Moving flaky multiplayer tests into sandbox so they will still be ran nightly, but we can still fix and create new tests
> Moving Flaky Multiplayer Tests into Sandbox

- Code/Legacy/CryCommon/ISystem.h
- Code/Legacy/CryCommon/platform_impl.cpp
- Code/Legacy/CrySystem/SystemInit.cpp
-prevent export of ModuleInitISystem and ModuleShutdownISystem
> bugfix: resolve crash with FBX Settings  (#4813) (#4944)

- Gems/Terrain/Code/Source/Components/TerrainHeightGradientListComponent.cpp
- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.cpp
- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.h
Added functionality to the "Use Ground Plane" toggle.  Now, when it's enabled, the Terrain Layer Spawner will always provide valid terrain data at the minimum height of the spawner box, even if no Terrain Height Gradient List exists.  If it's disabled, it won't provide any terrain data unless the Terrain Height Gradient List exists.
> Use Ground Plane non functional

- Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
previously negative terrain world bounds wouldn't draw correctly in some circumstances. See GHI-5338 for more info. Now this works correctly -
> GHI-5338 - Fixing incorrect calculation of sector bounds for negative values

- Code/LauncherUnified/launcher_generator.cmake
- Code/Legacy/CrySystem/XConsole.cpp
The fix simply removes the setting of a bool in server mode which had made the XConsole code process text before the DebugConsole/ImGui got a chance to.
The problem didn't occur if server launcher had loaded a map, and during load complete it will explicitly Show(false) the XConsole.  That also sets the bool to false.  So normal operation of the DebugConsole should have this XConsole bool set to false.  This will skip XConsole from handling text and pass processing along to the next handlers, so ImGuiPass would get a chance to do it properly.
Also there's a quick fix here for CMake to make sure the ServerLauncher target adds a runtime dependency on CrySystem.  If you had a clean build dir and only built ServerLauncher target, it wouldn't build CrySystem and the application would fail to …
> Fix issue with Server Launcher debug console not accepting keystrokes

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DeferredFogAdded.py
Added P0 test for Deferred Fog component
pyRunFile ../../Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DeferredFogAdded.py
Report:
[SUCCESS] Success: Deferred Fog Entity successfully created
[SUCCESS] Success: Entity has a Deferred Fog component
[SUCCESS] Success: Deferred Fog component disabled
[SUCCESS] Success: Deferred Fog component enabled
[SUCCESS] Success: Enable Deferred Fog parameter enabled
[SUCCESS] Success: UNDO deletion success
[SUCCESS] …
> Test parallel Add P0 Deferred Fog

- Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.cpp
> Modify Atom DrawWireCircle2d to account for viewport aspect ratio

- Code/Tools/AssetProcessor/native/tests/AssetProcessorTest.h
Fix Assert Absorber being leaked due to one of the tests setting m_errorAbsorber to nullptr without deleting the object (#5176)
(cherry picked from commit 916fb413c93f92d3c4aea46dac4d7908b48a10fa)
> Cherry Pick - Fix Assert Absorber being leaked

- Gems/Terrain/Code/Source/Components/TerrainWorldRendererComponent.cpp
It's not currently hooked up, so setting invisible for now until it does something.
https://github.com/o3de/o3de/issues/5179
> Rendered World Size in the Terrain World Render component set to invisible

- .gitignore
This will ignore any restricted folder/subfolder in the repo. While the recommended path moving forward will be to setup the platform repos outside the o3de folder, adding as a safeguard for older restricted platform workflows.
> Add restricted folder to gitignore

- Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR_ForwardPass.azsl
StandardMultilayerPBR_ForwardPass.azsl. the type of input.m_normal is float
Github issue: https://github.com/o3de/o3de/issues/2522
Changed to float3. The current ASV tests are not affected but
using the RPI/Mesh example with Mesh: objects/suzanne.azmodel
and the material:
StandardMultilayerPbrTestCases/005_UseDisplacement.material
Showed a clear improvement.
> StandardMultilayerPBR_ForwardPass.azsl. the type of input.m_normal is

- Code/Editor/EditorModularViewportCameraComposer.cpp
- Code/Editor/EditorModularViewportCameraComposer.h
This is a follow-up PR to https://github.com/o3de/o3de/pull/5301 to improve the feedback for the default orbit point.
> Improvements to feedback for default camera orbit point (when no entity is selected)

- Gems/Prefab/PrefabBuilder/PrefabBuilderTests.cpp
We were destructively moving the DOM template into the builder, leaving the Prefab system with an invalid DOM when teardown occurs. For now, this just copies the document to fix this specific test failure, but we may want to consider making `FindTemplateDom` return a const document and requiring that mutations get routed through the prefab system component to avoid similar situations in the future.
> Fix Prefab builder test

- Gems/Profiler/Code/Source/CpuProfilerImpl.cpp
- Gems/Profiler/Code/Source/CpuProfilerImpl.h
The limit seems to be trigged by profiler calls to AssetDataStream::Read.
Contents of m_cachedTimeRegions when full is repeated indefinitely:
Signed-off-by: rbarrand <43485729+hershey5045@users.noreply.github.com>
> Improve handling of cached data limits.

- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Inspector/InspectorPropertyGroupWidget.cpp
Changed material editor inspector to queue its initial invalidation instead of invalidating immediately. If several documents are opened at the same time they will each destroy properties from the previous document and repopulate with their own, rebuilding the UI between documents, causing a huge delay.
> Queuing inspector invalidation to remove stall opening/closing several documents

- Gems/AtomLyIntegration/CommonFeatures/Code/CMakeLists.txt
> Add missing runtime dependency to atom ly integration

- Code/Editor/CryEdit.cpp
quick access bar was always center to my primary monitor because the point is only relative to the main window not globally. 
> bugfix:  correctly center quick access bar

- Gems/EMotionFX/Code/EMotionFX/Source/DualQuatSkinDeformer.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/DualQuatSkinDeformer.h
* Moved from job system to task graph for the multi-threaded dual quaternion skinning deformer.
* Prepare the task graph at init time and reuse it at runtime.
> EMotion FX: Taskify dual quat skinning deformer

- Gems/EMotionFX/Code/Source/Integration/System/SystemComponent.cpp
- Gems/EMotionFX/Code/Source/Integration/System/SystemComponent.h
* Motion extraction should only be applied when in game mode or for entities that belong to the Animation Editor. We don't want our entities to move in editor mode.
* Moved code into separate function that actually applies the trajectory delta to the entity/character controller.
Fixes the root cause for https://github.com/o3de/o3de/pull/1468
> EMotion FX: Apply motion extraction only in game-mode and for anim editor entities

- Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
Opening the Update Project screen was taking longer and longer each time because each time it opened we added another data listener which re-created the status filter UI for every gem added.  To fix we just need to disconnect before filling the model.  Fun!
> Don't update status filter when filling gem model

- Code/Framework/AzQtComponents/AzQtComponents/Components/FancyDocking.cpp
looks like the main window is deactivated when you drag a tabbed window. 
issue: https://github.com/o3de/o3de/issues/4658
> bugfix[Linux]: resolve dragging window with more than one tabbed  (#4658)

- Code/Tools/ProjectManager/Source/PythonBindings.cpp
- scripts/o3de/o3de/download.py
- scripts/o3de/o3de/utils.py
Also check last_updated field to compare for gem updates. This method will be replaced once a gem versioning system has been introduced.
> Add ability to overwrite o3de object when downloading

- scripts/build/Jenkins/Jenkinsfile
Fixes: https://github.com/o3de/o3de/issues/5425 
We no longer need a timeout here. A timeout mechanism was added to the mount script to raise an exeception if the EBS volume is not mounted in the configured timeframe.
This also causes a bug with the retry mechanism where Jenkins will hit this timeout in the event the node goes offline during the setup stage instead of raising an exception.
> Remove timeout in the mount step

- Gems/LyShine/Code/Editor/Animation/UiAnimViewDialog.cpp
This is a fix for issue https://github.com/o3de/o3de/issues/2709.
Users couldn't find track editor view in UI animation editor due to for somehow the default size of the view is set to zero. The view could also be collapsed by users clicking on the vertical separator line and dragging to the right to resize the view to be zero, causing users to think the track editor is missing or broken.
In order to prevent the track editor view is collapsed and invisible, we make the minimum size of track editor and curve editor the same since both track and curve editors are using the same view widget in UI animation editor while not in "Both" mode.
Verified in UI animation editor that this fix works even set the size of the view be zero by manually modifying value from the Windows …
> Prevent track editor view's default size to be zero

- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.h
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportToolBar.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/EMStudioPlugin.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/RenderPlugin/RenderOptions.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/RenderPlugin/RenderWidget.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/RenderPlugin/ViewportPluginBus.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionWindowPlugin.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionWindowPlugin.h
- Gems/EMotionFX/Code/Source/Editor/ColliderContainerWidget.cpp
- Gems/EMotionFX/Code/Source/Editor/ColliderContainerWidget.h
- Gems/EMotionFX/Code/Source/Editor/Plugins/Cloth/ClothJointInspectorPlugin.cpp
- Gems/EMotionFX/Code/Source/Editor/Plugins/Cloth/ClothJointInspectorPlugin.h
- Gems/EMotionFX/Code/Source/Editor/Plugins/HitDetection/HitDetectionJointInspectorPlugin.cpp
- Gems/EMotionFX/Code/Source/Editor/Plugins/HitDetection/HitDetectionJointInspectorPlugin.h
- Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeInspectorPlugin.cpp
- Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeInspectorPlugin.h
- Gems/EMotionFX/Code/Source/Editor/Plugins/SimulatedObject/SimulatedObjectWidget.cpp
- Gems/EMotionFX/Code/Source/Editor/Plugins/SimulatedObject/SimulatedObjectWidget.h
- Gems/EMotionFX/Code/Source/Integration/Rendering/RenderActorSettings.h
https://user-images.githubusercontent.com/69218254/140852128-4181b8ca-bf8d-4884-b594-21ca06c9daf1.mp4
video explain it better than anything.
1. Change the grid to a checkerboard
2. ViewportPluginRequests bus to retrieve the custom viewport id from the atom render widget
3. Deprecate old render function to legacy in the render plugins. You might have notice that the new render code is basically a duplication of the old code plus changing it to use the atom aux geom render. This is because the legacy render code eventually will go away with the openGL render plugin - the plan is NOT having both atom and OpenGL render both available as options, otherwise we would spend the time to make an abstract debug draw layer.
4. Added the collider option to UI
> Render Colliders

- Templates/PythonToolGem/Template/Code/CMakeLists.txt
- Templates/PythonToolGem/Template/gem.json
The `PythonToolGem` gemplate needs to have the `QtForPython` gem as a proper dependency, otherwise the user would need to separately/explicitly enable the `QtForPython` gem in their project in order to make use of `PySide2` and all of our helper methods.
1. Adding it to the `dependencies` in the `gem.json` makes sure that the `QtForPython` gem will be enabled as a dependency (if not already enabled in the project) when the user enables the gem that was created from the gemplate.
2. Having it listed in the `RUNTIME_DEPENDENCIES` of the `.Editor` module will make sure it gets registered properly in the `<build-dir>/bin/$<CONFIG>/Registry/cmake_dependencies.<project-name>.editor.setreg`, which in turn will make sure the `EditorPythonBindings` will be able to bootstrap it.
Thanks to …
> Ensure QtForPython is a proper dependency for the PythonToolGem.

- Code/Tools/ProjectManager/Source/GemCatalog/GemFilterWidget.cpp
We can re-enable this in the commit that adds the platform meta data
> Temporarily disable the platform filter

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserFilterModel.cpp
This change activates the AssetBrowserTableView to have it as the default option.
> Activate AssetBrowserTableView feature

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp
Fix for issue [Component Edit Mode does not disable Entity Inspector interaction](https://github.com/o3de/o3de/issues/5239).
The `EntityPropertyEditor` class was missing the connection/disconnection to the `ViewportEditorModeNotificationsBus` which caused it to not respond to component mode enter/leave events. This has now been fixed by adding the pertinent calls to the class constructor and destructor.
https://user-images.githubusercontent.com/77458631/141110506-07dfb04b-1abf-448a-b831-a643dc77e553.mp4
> Fix for Issue #5239: Component Edit Mode does not disable Entity Inspector interaction

- Gems/Atom/Feature/Common/Code/Source/PostProcessing/BlendColorGradingLutsPass.cpp
- Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbeFeatureProcessor.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/FullscreenTrianglePass.cpp
- Registry/Platform/Mac/bootstrap_overrides.setreg
1. Add nullptr checks to prevent crashes when non-critical shaders fail to compile.
2. Add a higher "launch_ap_timeout" for Mac because launching a newly built/downloaded AP can take a while.
Logs with callstack for the crashes:
[Editor_crash_rpfp.log](https://github.com/o3de/o3de/files/7499576/Editor_crash_rpfp.log)
[Editor_crash_fstp.log](https://github.com/o3de/o3de/files/7499578/Editor_crash_fstp.log)
> Fix Editor crashes on asset failures

- Code/Framework/AzFramework/Platform/Windows/AzFramework/Windowing/NativeWindow_Windows.cpp
This change was made years ago in CrySystem (see CSystem::HandleMessage in System.cpp), but looks like it never made it into the NativeWindow_Windows version.
> Don't allocate memory when processing WM_INPUT messages.

- Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialSourceData.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/AssetCreator.h
- Gems/Atom/RPI/Code/Source/RPI.Edit/Material/LuaMaterialFunctorSourceData.cpp
- Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialSourceData.cpp
- Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialTypeSourceData.cpp
- Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/MaterialTypeAsset.cpp
- Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/MaterialTypeAssetCreator.cpp
- Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/ShaderCollection.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.h
- Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.h
The material editor document and material source data can now load and create material and type assets directly from JSON after loading into source data structures. The material editor no longer requires the asset processor to cook materials, parent materials, material types before material documents can be opened. 
This should resolve intermittent AR and automated test failures that were caused by rapidly saving and reopening interdependant documents back to back before they could be processed by the AP. This has also been a longstanding issue in the material editor for the user but was rarely encountered.
The material document is also now only monitoring external changes from the source files.
Other fixes were made to the atom tools framework document system. The containers and …
> Material editor creates material assets from source JSON data instead of relying on AP

- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.h
Remove AssetProcessorManagerTest AssertAbsorber and update test to use the one from the base class instead (#5216)
(cherry picked from commit b3301414ad1f76161fa88eaf8650f42bfb94617c)
> Cherry Pick - Remove AssetProcessorManagerTest AssertAbsorber

- Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
- Code/Tools/AssetProcessor/native/unittests/UnitTestRunner.h
Leaving in the print for absorbed asserts to avoid running into future situations where important asserts are accidentally absorbed.  Color is yellow since the assert is absorbed so it might not be a certain error.
> Remove temporary debug messages

- Gems/Atom/RHI/DX12/Code/Include/Atom/RHI.Reflect/DX12/PlatformLimitsDescriptor.h
- Gems/Atom/RHI/Metal/Code/Include/Atom/RHI.Reflect/Metal/PlatformLimitsDescriptor.h
- Gems/Atom/RHI/Vulkan/Code/Include/Atom/RHI.Reflect/Vulkan/PlatformLimitsDescriptor.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RasterPass.cpp
Small change to make the RasterPass Scope jobs split the work more evenly over the cores, saves about 0.5ms / frame in the test scene (10K random objects)
Work distribution before
Work distribution after
> Atom CPU threading optimization

- AutomatedTesting/Gem/PythonTests/assetpipeline/ap_fixtures/bundler_batch_setup_fixture.py
Updated to use absolute project path since paths are now relative to the working directory
> [LYN-8102] Failed to open asset catalog file

- Gems/EMotionFX/Code/Source/Integration/System/SystemComponent.cpp
Material editor and other tools load runtime dependencies from game projects. The EMFX system component is checking for game mode by getting a pointer to the editor interface, which will not exist outside of the main O3DE editor.
> Added a null pointer check to EMFX system component

- Code/Editor/TrackView/AtomOutputFrameCapture.cpp
- Code/Editor/TrackView/AtomOutputFrameCapture.h
- Code/Editor/TrackView/SequenceBatchRenderDialog.cpp
- Gems/Atom/Feature/Common/Code/Source/PostProcess/PostProcessFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/PostProcess/PostProcessFeatureProcessor.h
- Gems/Atom/Feature/Common/Code/Source/PostProcessing/EyeAdaptationPass.cpp
PostFxs will not render correctly in track mode since the aggregated views that happen during PostFxLayerComponentController:OnTick are only 1). entities with a camera component, 2). editor camera.
Since track view contains its own render pipeline with its own view, the changes in this PR will allow setting up a view alias within the PostProcessFeatureProcessor in order to mimic the postfx settings of other views. This will allow other future widgets as well to perform the same behavior. 
* Add view alias map to post process feature processor class. This will be used to map one view to a different view when GetLevelSettingsFromView() is called by individual postfx feature passes (depth of field pass, eye adaptation pass, etc.)
* Update track view code by setting the view alias within the …
> Fix track view bug where postfxs do not render correctly.

- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.h
Fixes #5085 
Prevent crash in the Entity Outliner by preventing the user from modifying entities/components through Landscape Canvas after the graph corresponding to that entity is no longer in prefab focus. Tested modifying a Landscape Canvas component on the root instance, inside a prefab, and inside nested prefabs.
> Fixed LC crash by preventing graphs from staying open after they are no longer in prefab focus.

- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
Fix for [Trying to select multiple entities by clicking and dragging on the viewport crashes the Editor](https://github.com/o3de/o3de/issues/4300).
The issue couldn't be reproduced locally due to lack of dual monitors so a fix has been put in place in `EditorTransformComponentSelection::SetupBoxSelect()` to only attempt to draw the box if the `min` and `max` vectors of the AABB are valid.
> Fix attempted rendering of invalid Entity selection boxes.

- Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja
- Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
Ensuring the 4 types of RPCs (1)Autonomous->Authority (2)Authority->Autonomous (3)Authority->Client and (4)Server->Authority all compile. Invoking anything that starts from Autonomous or Authority requires a controller (otherwise just requires a component), and anything handled by Authority or Autonomous requires a controller for Handle on OnEvent methods (otherwise OnEvent and Handle occurs on the component)
> Fix to Allow Compiling the 4 Types of RPCs

- Code/Framework/AzCore/AzCore/Name/NameDictionary.cpp
the owner has removed it!
This fixes the issue by forcing NameDictionary to not transfer
ownership. This means ComponentApplication()::Destroy will fully destroy
the NameDictionary before the OS::Allocator is destroyed.
In Windows the bug was not happening when running AssetProcessorBatch
because for Windows, _exit() is called before the application shutsdown
forcing all module to properly decrease the reference count of
EnvironmentVaqriableHolderBase::m_useCount for NameDictionary.
In MacOS, there's no _exit() so when the NameDictionary destructor was being called
before existing the application the reference count wouldn't be 0, and
would eventually try to destry the NameDictionary BUT the OS::Allocator
was already destroyed.
Signed-off-by: galibzon …
> ASV Trace::Assert Environment.h(438) You are using an invalid variable,

- Code/Legacy/CrySystem/SystemInit.cpp
Removing old cry code that would load client.cfg for server launcher. Client.cfg should not be loaded by default. It was confusing seeing client.cfg in the server.log. If devs want to load a cfg then they can provide it via commandline (--console-command-file).
> Removing Old Cry Code that Causes ServerLauncher to Load Client.cfg  

- Code/Framework/AzCore/AzCore/Math/Vector3.h
- Code/Framework/AzCore/AzCore/Math/Vector3.inl
- Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.cpp
- Gems/Atom/RPI/Code/Source/RPI.Reflect/Model/ModelAsset.cpp
- Gems/Atom/RPI/Code/Tests/Model/ModelTests.cpp
Update: PR now comes with a test and is ready for review. The problem was we were not looking at the right 'view' of the mesh data when there is more than one `ModelLodAsset::Mesh`.
https://user-images.githubusercontent.com/82228511/140947276-8d20518a-2975-41e6-948a-fb91883e5987.mp4
https://user-images.githubusercontent.com/82228511/140948367-a0bec721-6c15-432e-989c-38f36c3414cd.mp4
I've added a test that reproduces the old issue, see the below output with my changes reverted
```bash
[----------] 1 test from BruteForceMultiModelIntersectsFixture
[ RUN      ] BruteForceMultiModelIntersectsFixture.IntersectWithSecondMesh
D:/o3de-2/Gems/Atom/RPI/Code/Tests/Model/ModelTests.cpp(1437): error: Value of: m_mesh->GetModel()->LocalRayIntersectionAgainstModel( AZ::Vector3(15.0f, 0.0f, 5.0f), …
```
> Fix brute force mesh intersection function

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_SSAOAdded.py
Adds a basic P0 parallel automation test for SSAO (screen space ambient occlusion) component
Report:
[SUCCESS] Success: SSAO Entity successfully created
[SUCCESS] Success: Entity has a SSAO component
[SUCCESS] Success: SSAO component disabled
[SUCCESS] Success: SSAO component enabled
[SUCCESS] Success: UNDO deletion success
[SUCCESS] Success: REDO deletion success
Test result:  SUCCESS
.\python\python.cmd -m pytest --build-directory atom_dev/bin/profile …
> SSAO component P0 automation

- Gems/Blast/Code/Source/Components/BlastSystemComponent.cpp
Blast gem cleanup m_materialLibrary asset on Deactivate to avoid holding onto asset reference after AssetManager has shutdown
> Blast gem cleanup m_materialLibrary asset on Deactivate

- Gems/AWSCore/cdk/README.md
- Gems/AWSCore/cdk/core/core_stack.py
- Gems/AWSCore/cdk/example/example_resources_stack.py
- scripts/build/Platform/Windows/deploy_cdk_applications.cmd
Generated and deployed stack with option on, on stack deletion resources were deleted.
Generated and deployed stacks with option off, on stack deletion resources were retained as is current behaviour.
> AWS Core CDK: Add option to cleanup resources that are retained by default

- AutomatedTesting/Gem/PythonTests/PythonAssetBuilder/mock_asset_builder.py
o3de\AutomatedTesting\Gem\PythonTests\PythonAssetBuilder\mock_asset_builder.py
- adding more logging
- updated keys for platforms (pc, server)
> {lyn7352} adding more logging around mock_asset_builder.py (#5103)

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_LookModificationAdded.py
Add P0 test for Look Modification component
pyRunFile ../../Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_LookModificationAdded.py
Report:
[SUCCESS] Success: Look Modification Entity successfully created
[SUCCESS] Success: Entity has a Look Modification component
[SUCCESS] Success: Look Modification component disabled
[SUCCESS] Success: Look Modification component enabled
[SUCCESS] Success: Enable look modification parameter enabled
[SUCCESS] Success: Entity has the Color Grading LUT set …
> Look Modification P0 Automation

- Gems/Atom/RHI/Code/Source/RHI/PipelineStateCache.cpp
- Gems/Atom/RHI/DX12/Code/Include/Atom/RHI.Reflect/DX12/PlatformLimitsDescriptor.h
- Gems/Atom/RHI/Metal/Code/Include/Atom/RHI.Reflect/Metal/PlatformLimitsDescriptor.h
- Gems/Atom/RHI/Vulkan/Code/Include/Atom/RHI.Reflect/Vulkan/PlatformLimitsDescriptor.h
Pull over the changes to move some expensive validation to debug builds only, and use finer grained jobs for the frame scheduler work.
> cherry pick atom optimizations

- AutomatedTesting/Gem/PythonTests/Physics/utils/FileManagement.py
- Tools/LyTestTools/ly_test_tools/environment/file_system.py
- Tools/LyTestTools/tests/unit/test_file_system.py
os.chmod() sets the file attributes, not adds/removes.
The lock/unlock file utilities were wrong and they were setting the file attributes to be only-writtable (clearing any other permissions like readable). On windows this doesn't affect read access but it does on linux.
So a file that was
R-- becoming -W-
instead of the expected
R-- becoming RW-
Platform linux -- Python 3.7.10+, pytest-5.3.2, py-1.9.0, pluggy-0.13.1
rootdir: /o3de/o3de_aljanru, inifile: pytest.ini
plugins: timeout-1.3.4, mock-2.0.0, ly-test-tools-1.0.0
collected 14 items
AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Main.py ..xx..........                                                                                             [100%]
============= 12 passed, 2 xfailed in 83.72s (0:01:23) …
> Fixed physics tests on linux

- Code/Framework/AzCore/AzCore/IO/Streamer/FullFileDecompressor.cpp
- Code/Framework/AzCore/AzCore/Jobs/Internal/JobManagerWorkStealing.cpp
- Code/Framework/AzCore/AzCore/Jobs/Internal/JobManagerWorkStealing.h
- Code/Framework/AzCore/AzCore/Jobs/JobManagerComponent.cpp
- Code/Framework/AzCore/AzCore/Jobs/JobManagerDesc.h
- Gems/AWSCore/Code/Source/AWSCoreSystemComponent.cpp
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImagePreview.cpp
- Gems/Atom/Utils/Code/Source/AssetCollectionAsyncLoader.cpp
all worker threads use that name to label their threads
With this change we now see these names in pix
> Add a name to JobManager

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabViewportFocusPathHandler.cpp
Temporarily remove the "Up one level" button in the viewport toolbar breadcrumbs for prefab focus mode, since it makes the UX confusing. It will be restored after the upcoming release, but that work requires some areas to be refactored.
> LYN-8194 | Remove Back Arrow button temporarily from the navigation bar

- Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
- Code/Tools/ProjectManager/Source/GemCatalog/GemModel.cpp
- Code/Tools/ProjectManager/Source/GemCatalog/GemModel.h
- Code/Tools/ProjectManager/Source/GemRepo/GemRepoScreen.cpp
**PSA: Don't use select on _QItemSelectionModel_ it does not set _currentIndex_ so it can get out of sync with what is actually selected causing confusing bugs. Instead use _setCurrentIndex_**
Replaces gem and selects new gem when downloading and deleting remote gems, 
Fixes other gem selection issues
> Fully Replaces Remote Gems in Model and Selects Them When Downloading and Deleting

- Gems/StartingPointCamera/Code/Source/CameraLookAtBehaviors/SlideAlongAxisBasedOnAngle.cpp
- Gems/StartingPointCamera/Code/Source/CameraLookAtBehaviors/SlideAlongAxisBasedOnAngle.h
This is a followup PR to #5410 
This disables the checkbox when the other two are activated so you cannot pass a zero vector.
https://user-images.githubusercontent.com/82394219/141302570-830c122d-e3e2-45d5-8aa6-47fc26a9df8a.mp4
> CameraRigComponent - Disable Component Checkbox when the two others are toggled

- Code/Framework/AzFramework/AzFramework/Components/TransformComponent.cpp
- Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp
The change in `TransformComponent::SetParentImpl` fixes a warning when `TransformComponent::SetParent()` is called on inactive entities which is a common case to do at the Asset Builder stage.
The warning happens inside `Component::GetEntityId()` : "Can't get component %p entity ID as it is not attached to an entity yet!"
It also returns InvalidEntityId in that case which makes it impossible to do `SetParentId(InvalidEntityId)` since it prints a warning "An entity can not be set as its own parent." and doesn't update the parent ID.
> Fixed IMGUI Entity Outliner to show net entities

- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/DirectionalLightShadow.azsli
Adjusting the tolerance fixes the issue with shadow map cascades clipping out at certain angles.
ATOM-16753
> Fix for cascade shadow map clipping out too close to the camera

- Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.h
Cascade shadow maps are shimmering very badly when the camera moves. Implemented a fix taken from the Microsoft DirectX samples which is to clamp the cascade ortho matrix to a constant size based upon the camera.
Before (512x512 shadowmaps with 4 cascades):
https://user-images.githubusercontent.com/61609885/141698286-162e3c67-69c5-4fe0-8880-b2d37ad84c58.mp4
https://user-images.githubusercontent.com/61609885/141698472-6b20f555-f382-4e15-a63f-96c37350f78e.mp4
> Fix for CSM shimmering

- Gems/AtomTressFX/Code/Builders/HairBuilderComponent.cpp
Errors were being reported that the hair asset was being registered with the asset manager multiple times. It was being registered once within the generic asset handler and again manually.
> Fixing double registration of hair asset

- Code/Framework/AzCore/AzCore/Asset/AssetManager.cpp
- Code/Framework/AzCore/Tests/Asset/AssetManagerLoadingTests.cpp
Fixed a rare race condition where an asset would fully unload and be requested to start loading again before the previous streamer request could be removed.
Re-enabled a disabled test that had the same failure cause
Cleaned up the other test to run a bit quicker and fix its overly long timeout
> [LYN-7463] Fix insert streaming request failure

- Gems/ScriptCanvas/Code/Editor/View/Widgets/CanvasWidget.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Asset/RuntimeAsset.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Asset/RuntimeAsset.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Asset/RuntimeAssetHandler.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/ExecutionState.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/Interpreted/ExecutionInterpretedAPI.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/Interpreted/ExecutionStateInterpreted.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/RuntimeComponent.cpp
In order to prevent dead locks when SC assets require each other, or worse catastrophic side effects from modifying the Lua state in places other than the main thread, SC runtime assets that require one time, static initialization do so when their first using entity activates.
> Move SC runtime asset static initialization out of data loading threads

- Code/Framework/AzCore/AzCore/Asset/AssetManager.cpp
- Code/Framework/AzCore/Tests/Asset/AssetManagerLoadingTests.cpp
* Fix race condition where asset would finish loading and another request would start before the streamer request could be cleared
* Re-enable disabled test which was failing for the same reason.
Fix test timeout which was way too long.
Reduce test iterations to keep test time safely under 5 seconds.
* Instead of using a mutex, re-order the statements to remove the streamer request first
(cherry picked from commit 0cea59d66998585f07c54e55f68dd117363fb4ea)
> Cherry Pick: [LYN-7463] Fix insert streaming request failure (#5604)

- AutomatedTesting/Gem/PythonTests/AWS/Windows/aws_metrics/aws_metrics_automation_test.py
- AutomatedTesting/Gem/PythonTests/AWS/Windows/core/test_aws_resource_interaction.py
- AutomatedTesting/Gem/PythonTests/AWS/common/resource_mappings.py
- Gems/AWSCore/Code/Include/Private/ResourceMapping/AWSResourceMappingConstants.h
- Gems/AWSCore/Code/Tests/ResourceMapping/AWSResourceMappingManagerTest.cpp
Same changes as https://github.com/o3de/o3de/pull/4885, but includes python test.
unit tests pass 
```
Loading: C:/Users/stankoa/source/o3de/build/windows_vs2019/bin/profile/AWSCore.Tests.dll
OKAY Library loaded: C:/Users/stankoa/source/o3de/build/windows_vs2019/bin/profile/AWSCore.Tests.dll
OKAY Symbol found: AzRunUnitTests
[==========] Running 101 tests from 21 test cases.
[----------] 22 tests from AWSResourceMappingManagerTest
[ RUN      ] AWSResourceMappingManagerTest.ActivateManager_ParseInvalidConfigFile_ConfigDataIsEmpty
[       OK ] AWSResourceMappingManagerTest.ActivateManager_ParseInvalidConfigFile_ConfigDataIsEmpty (13 ms)
[ RUN      ] AWSResourceMappingManagerTest.ActivateManager_ParseValidConfigFile_ConfigDataIsNotEmpty
[       OK …
```
> Update resource mapping schema to make default account ID optional

- Code/Editor/CryEdit.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/API/ToolsApplicationAPI.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp
Added event to `AzToolsFramework::EditorEventsBus` to signal when the Editor has been fully initialized. This will allow test scripts to listen for this event instead of needed arbitrary wait commands before beginning the test.
> Added event to signal when the Editor is fully initialized

- Gems/PhysX/Code/Editor/Source/ComponentModes/Joints/JointsComponentMode.cpp
Happens if 'limits' or 'breakable' settings are off on the joint when entering component mode.
> Fixed empty cluster UI appearing in joints component mode.

- AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Main_Optimized.py
Fix the wrong cmd line args used for enable prefab system in automated tests.
Tests passed by using the following command with xfail temporally removed:
```
python\python.cmd -m pytest AutomatedTesting\Gem\PythonTests\Physics\TestSuite_Main_Optimized.py::TestAutomationWithPrefabSystemEnabled --build-directory windows_vs2019\bin\profile
```
> Fix prefab enabled automated tests

- Code/Editor/AboutDialog.ui
- Code/Editor/StartupLogoDialog.ui
Updated the name on the splash screen and about dialog to development
Cherry-picked name update in stabilization first (#5647) so that it doesn't get reverted when the stabilization/2110 -> development merge is done later today.
Signed-off-by: Chris Galvan chgalvan@amazon.com
> Updated splash screen and about dialog with development name

- Code/Tools/ProjectManager/Source/ProjectBuilderController.cpp
- Code/Tools/ProjectManager/Source/ProjectManagerSettings.cpp
- Code/Tools/ProjectManager/Source/ProjectManagerSettings.h
- Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
- Code/Tools/ProjectManager/Source/UpdateProjectCtrl.cpp
- Code/Tools/ProjectManager/project_manager_files.cmake
Temporary solution to show the build button in more instances when the project has not been built correctly by Project Manager. Project Manager creates a file when a project is successfully built. This will be replaced by a more permanent solution that will cover more instances without a tracking file.
> Create file in project directory on successful build for Project Manager

- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/AWSGameLiftClientManager.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/AWSGameLiftClientManager.h
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftAcceptMatchActivity.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftAcceptMatchActivity.h
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftCreateSessionActivity.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftCreateSessionActivity.h
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftCreateSessionOnQueueActivity.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftCreateSessionOnQueueActivity.h
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftJoinSessionActivity.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftJoinSessionActivity.h
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftLeaveSessionActivity.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftSearchSessionsActivity.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftSearchSessionsActivity.h
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftStartMatchmakingActivity.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftStartMatchmakingActivity.h
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftStopMatchmakingActivity.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftStopMatchmakingActivity.h
- Gems/AWSGameLift/Code/AWSGameLiftClient/Tests/Activity/AWSGameLiftCreateSessionActivityTest.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/Tests/Activity/AWSGameLiftCreateSessionOnQueueActivityTest.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/Tests/Activity/AWSGameLiftJoinSessionActivityTest.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/Tests/Activity/AWSGameLiftSearchSessionsActivityTest.cpp
Previously we move gamelift client ownership to the system component, so we don't need to pass it to each activity. Instead we can get it in activity scope directly.
Pass unit test
> Move gamelift client usage into each activity scope

- AutomatedTesting/Gem/PythonTests/AWS/Windows/client_auth/aws_client_auth_automation_test.py
- Gems/AWSClientAuth/Code/Include/Private/Authorization/AWSClientAuthCognitoCachingAuthenticatedCredentialsProvider.h
- Gems/AWSClientAuth/Code/Include/Private/Authorization/AWSCognitoAuthorizationController.h
- Gems/AWSClientAuth/Code/Source/Authorization/AWSClientAuthCognitoCachingAuthenticatedCredentialsProvider.cpp
- Gems/AWSClientAuth/Code/Source/Authorization/AWSCognitoAuthorizationController.cpp
- Gems/AWSClientAuth/Code/Tests/Authorization/AWSCognitoAuthorizationControllerTest.cpp
- Gems/AWSClientAuth/Code/awsclientauth_files.cmake
Builds off changes in https://github.com/o3de/o3de/pull/5475 . Will rebase after those are merged so those commits no longer appear here.
The purpose of these changes is to allow calls to Cognito to proceed w/o providing an AWS account ID, in the event that none is provided.
unit tests pass
```
OKAY Library loaded: C:/Users/stankoa/source/o3de/build/windows_vs2019/bin/profile/AWSClientAuth.Tests.dll
OKAY Symbol found: AzRunUnitTests
[==========] Running 92 tests from 9 test cases.
[----------] 16 tests from AWSCognitoAuthorizationControllerTest
[ RUN      ] AWSCognitoAuthorizationControllerTest.Initialize_Success
[       OK ] AWSCognitoAuthorizationControllerTest.Initialize_Success (23 ms)
[ RUN      ] …
```
> AWSClientAuth updated to use custom CognitoCachingCredentialsProvider

- Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
- scripts/o3de/o3de/disable_gem.py
- scripts/o3de/o3de/download.py
- scripts/o3de/o3de/repo.py
- IMPORTANT: change `originuri` to `origin_uri` to match the naming scheme of the rest of gem.json
- fix issue where downloaded gems cannot be added because gem download status has changed
- fix issue where gem could not be disabled if a path to the gem.json was provided instead of the gem folder.  Remote gems that do not exist on disk do not have a folder, so project manager was sending the path to the gem.json which is not a folder
- fixed issue where downloaded gems with hashes did not match because repo_name was added to remote gem jsons programatically
- fixed file handle left open when comparing hash
- fixed `template_name_name` syntax error and removed unused shutil import
- fix issue where uninstalled gems were not removed from projects
> Fixes for misc gem download issues

- Gems/Terrain/Assets/Shaders/Terrain/TerrainPBR_ForwardPass.azsl
Somehow, accessing IN.m_uv before the later calculations use it seems to make the values become stable and stop flickering.
> Workaround for NVidia flicker bug.

- Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.h
Shadows were behaving very badly with 2+ viewports in the Editor. With two viewports you would get bad clipping on one or the other.
Basically the DirectionalLightFeatureProcessor was trying to cache the camera matrices but it ended up just putting them all in the same slot in a hash table.
I removed the hash table lookup entirely and switched to just calling GetCameraTransform() directly. The function looks pretty cheap and the code is much simpler.
Checked ASV and tried many viewport configurations in the Editor. Seems perfectly stable now.
ATOM-16535
> Fix for shadowmaps not behaving properly with two viewports in the Editor

- Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
- Code/Tools/ProjectManager/Source/GemRepo/GemRepoInfo.h
- Code/Tools/ProjectManager/Source/GemRepo/GemRepoInspector.cpp
- Code/Tools/ProjectManager/Source/GemRepo/GemRepoModel.cpp
- Code/Tools/ProjectManager/Source/GemRepo/GemRepoModel.h
- Code/Tools/ProjectManager/Source/PythonBindings.cpp
- Code/Tools/ProjectManager/Source/PythonBindings.h
- Code/Tools/ProjectManager/Source/PythonBindingsInterface.h
Also renamed GetAllGemRepoGemsInfos to GetAllGemReposGemInfos
> Fix: Display Repo Gems on Repo Screen Correctly

- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/View.h
- Gems/Atom/RPI/Code/Source/RPI.Public/View.cpp
I was trying to use m_viewProjectionInverseMatrix in shaders and RenderDoc showed it contained garbage data which led me to discover it was never being set in code when the view was not offset.
This fix may not be optimal (uses GetInverseFull instead of GetInverseFast) and occurs everyframe so we could likely cache the data and update it every time m_worldToClipMatrix is updated.  Thoughts?
**Testing**
- verified m_viewProjectionInverseMatrix contains correct data in a shader using RenderDoc
> Fix missing clip to world matrix data

- Templates/DefaultProject/Template/cmake/EngineFinder.cmake
- Templates/MinimalProject/Template/cmake/EngineFinder.cmake
This fixes the cmake configuration errors when using a project-centric
workflow with newly crated projects
Original Commit hash: 289d783
fixes #5643
> Cherry-picking changes for EngineFinder.cmake.

- Gems/Atom/RPI/Code/Tests/Common/RPITestFixture.cpp
ShaderMetricsSystem spawns a lot of warnings when run Atom_RPI.Tests
Added @user@ path alias definition.
> ShaderMetricsSystem spawns a lot of warnings

- Code/Editor/EditorModularViewportCameraComposer.cpp
- Code/Editor/Lib/Tests/Camera/test_EditorCamera.cpp
- Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp
- Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp
- Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ModularViewportCameraController.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ModularViewportCameraControllerRequestBus.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ModularViewportCameraController.cpp
This PR fixes the pitch/yaw/roll behavior of the camera when in 'Be this camera'.
Tests have been added/updated...
```
[==========] Running 5 tests from 1 test case.
[----------] 5 tests from EditorCameraFixture
[ RUN      ] EditorCameraFixture.ModularViewportCameraControllerReferenceFrameUpdatedWhenViewportEntityisChanged
[       OK ] EditorCameraFixture.ModularViewportCameraControllerReferenceFrameUpdatedWhenViewportEntityisChanged (1 ms)
[ RUN      ] EditorCameraFixture.TrackingTransformIsTrueAfterTransformIsTracked
[       OK ] EditorCameraFixture.TrackingTransformIsTrueAfterTransformIsTracked (0 ms)
[ RUN      ] EditorCameraFixture.TrackingTransformIsFalseAfterTransformIsStoppedBeingTracked
[       OK ] …
```
> Fix for camera roll behavior when in 'Be this camera' mode

- Code/Tools/AssetProcessor/Platform/Linux/native/FileWatcher/FileWatcher_linux.cpp
The AssetProcessor on Linux uses `inotify` to monitor for file updates.
The AssetProcessor also uses a `ProcessWatcher` to launch child
AssetBuilder processes. `ProcessWatcher` accomplishes this by calling
`fork()`, which duplicates the current process, then calling `exec()`.
The `fork()` call also appears to duplicate any inotify fds. This
results in the subprocess consuming duplicate inotify watches, which is
a limited system resource (Ubunut 20 defaults
`/proc/sys/fs/inotify/max_user_watches` to 65536). The AssetProcessor
still has issues with this max, but this should free up at least half of
the uses.
> [Linux] Avoid duplicating inotify watches in forked AssetBuilder processes

- Code/Editor/EditorModularViewportCameraComposer.cpp
- Code/Editor/Lib/Tests/Camera/test_EditorCamera.cpp
- Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp
- Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
- Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp
- Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.h
- Code/Framework/AzFramework/Tests/CameraInputTests.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ModularViewportCameraController.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ModularViewportCameraControllerRequestBus.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ModularViewportCameraController.cpp
This PR is a quick follow-up on https://github.com/o3de/o3de/pull/5658
It allows the camera to no longer be constrained in pitch when tracking a transform (using 'Be this camera') as the transform being tracked _might_ have a really funky transform and we want to not limit users when using this feature).
This PR also fixes a couple of more minor camera bugs
Closes https://github.com/o3de/o3de/issues/3926
Closes https://github.com/o3de/o3de/issues/4141
> Camera fixes follow-up

- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
This change reduces the application update interval when the material editor is not the active application. This should resolve the usability issues that have been reported relating to significant decreases in performance when running the material editor alongside the main editor or other DCC tools. It will also decrease power consumption when the application is not active.
> Reduce material editor update interval when inactive

- Code/Tools/AssetProcessor/native/utilities/assetUtils.h
- Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/ImageBuilder.settings
- Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/Reflectance.preset
Update the file mask mapping in ImageBuilder.settings.
Change Reflectance.preset to use BC4 format since it only needs once channel.
> Follow up fix for ATOM-13512

- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/NodePalette/TreeItems/NodePaletteTreeItem.cpp
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/NodePalette/TreeItems/NodePaletteTreeItem.h
- Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
Fixes #3738 
Identified slow-down in Script Canvas tool being loaded due to the construction of a `QIcon` for the error icon of every node palette tree item (which is then x3 because the node palette is created for the actual node palette widget, the scene context menu, and connection context menu). This error icon isn't actually needed unless there is an error on the tree item, so moved the construction to the case when it actually needs to be displayed. This reduced the load time from ~1500ms to ~300ms, an improvement of ~80%.
Also added some `AZ_PROFILE_FUNCTION` calls that helped narrow down the source of the delay.
> Fixed slow Script Canvas loading by moving error icon construction in NodePaletteTreeItem.

- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/ModelPreset.h
- Gems/Atom/Feature/Common/Code/Source/Utils/EditorModelPreset.cpp
- Gems/Atom/Feature/Common/Code/Source/Utils/ModelPreset.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/CMakeLists.txt
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
- Gems/Atom/Tools/MaterialEditor/Code/CMakeLists.txt
- Gems/Atom/Tools/MaterialEditor/Code/Include/Atom/Viewport/MaterialViewportRequestBus.h
- Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportComponent.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportComponent.h
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/PresetBrowserDialogs/LightingPresetBrowserDialog.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/PresetBrowserDialogs/ModelPresetBrowserDialog.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/PresetBrowserDialogs/PresetBrowserDialog.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/PresetBrowserDialogs/PresetBrowserDialog.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewContent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewContent.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewUtils.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewUtils.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnail.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnail.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnailRenderer.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnailRenderer.h
The purpose of this change is to remove loading of large exr image files on material editor startup. Even though they are loaded asynchronously, they can use a considerable amount of memory until loading is complete and images are scale down.
These images were used for the lighting preset selection dialog in the viewport settings panel. The images are being replaced with the thumbnail widget now that we have preview rendering for lighting preset assets.
The other benefit of this change is that model presets will now also have preview images because they also have thumbnails. Previously it was expected that an artist would provide custom preview images for material editor models but that work was never done.
Added settings with default values so that the previews can be configured for the …
> Replacing material editor lighting preset selection dialog exr previews with lighting preset thumbnails

- Code/Editor/MainWindow.cpp
- Code/Editor/Settings.cpp
- Code/Editor/Settings.h
Preventing the prefab setting from being saved on Editor close.
This could be refactored to be more elegant, but given the current deadlines I strived to limit the blast radius.
> Settings Registry: Settings changed via --regset on Editor launch are saved when the Editor is closed

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ViewportInteractionImpl.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ViewportInteractionImpl.cpp
This was an oversight on my part, noticed the position returned was always that of the Editor camera
I'll add a test tomorrow but want to share this quickly for visibility
> Ensure ViewPtr in ViewportInteractionImpl is updated correctly when switching cameras

- Gems/PhysX/Code/Editor/EditorJointConfiguration.cpp
- Gems/PhysX/Code/Editor/EditorJointConfiguration.h
- Gems/PhysX/Code/Source/EditorBallJointComponent.cpp
- Gems/PhysX/Code/Source/EditorHingeJointComponent.cpp
Instead of an off/on state for the setup display on joints, There is now 3 options.
Never = Off.
Selected = Displayed when entity is selected. [Default]
Always = Always displayed.
> Change the joint setup display to an Enum of Never, Selected and Always.

- Code/Editor/2DViewport.cpp
- Code/Editor/EditorViewportWidget.cpp
- Code/Editor/EditorViewportWidget.h
- Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
- Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.h
- Code/Editor/Viewport.cpp
- Code/Editor/Viewport.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportMessages.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportMessages.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorSelectionUtil.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorSelectionUtil.h
This fix replaces legacy calls to `GetHitLocation` with `CalculateWorldPosition` which uses the new `IntersectorBus`.
The PR also removes legacy viewport calls that are no longer used.
> Updates and fixes to viewport placement

- Code/Framework/AzCore/AzCore/Time/ITime.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPISystem.h
- Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp
Note: I ran the full test suite on the AtomSampleViewer with these changes and got similar results as without this change (19 test failures).
> Update RPISystem::GetCurrentTime() to use TimeSystem

- Code/Framework/AzCore/AzCore/Time/TimeSystem.cpp
- Code/Framework/AzCore/AzCore/Time/TimeSystem.h
This was due to incorrectly setting m_lastSimulationTickTimeUs when t_simulationTickDeltaOverride was enabled to the override.
m_lastSimulationTickTimeUs is now always set to the current time so the delta calculation will always be correct.
> Fix large delta on next frame when turning t_simulationTickDeltaOverride off.

- Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.cpp
I noticed this text was not display correctly on high-dpi screens and was showing up on regular displays.
I think this fix was added a while back but the dpi scaling must have been addressed at a more fundamental level so this wound up being applied twice.
Before:
After:
> Fix for gizmo axis text not displaying correctly on high dpi screens

- Gems/Atom/Feature/Common/Code/Source/AuxGeom/AuxGeomBase.h
- Gems/Atom/Feature/Common/Code/Source/AuxGeom/AuxGeomDrawQueue.cpp
- Gems/Atom/Feature/Common/Code/Source/AuxGeom/AuxGeomDrawQueue.h
- Gems/Atom/Feature/Common/Code/Source/AuxGeom/FixedShapeProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/AuxGeom/FixedShapeProcessor.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/AuxGeom/AuxGeomDraw.h
- Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.cpp
- Greatly improved aux geom rendering for capsule lights
- Fixed issue with wireframe sphere (there was a ring missing close to the bottom pole, not very noticeable but fixed now)
- Added aux geom ability to draw hemispheres
- Added aux geom ability to draw open cylinders without disks at the end
- These two additions are used to draw a much better wireframe caspule
> Fixed capsule auxgeom draw for lights and other aux geom issues

- Code/Tools/AssetProcessor/assetprocessor_static_files.cmake
- Code/Tools/AssetProcessor/native/AssetManager/ExcludedFolderCache.cpp
- Code/Tools/AssetProcessor/native/AssetManager/ExcludedFolderCache.h
- Code/Tools/AssetProcessor/native/AssetManager/ExcludedFolderCacheInterface.h
- Code/Tools/AssetProcessor/native/AssetManager/FileStateCache.cpp
- Code/Tools/AssetProcessor/native/AssetManager/FileStateCache.h
- Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
- Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
- Code/Tools/AssetProcessor/native/tests/AssetProcessorTest.h
- Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
- Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
- Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp
- Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.h
Added a cache that builds a list of all watched folders that are ignored.
Added a FindWildcardMatches version which takes a list of ignored directories and will not scan any deeper if it finds one.
Updated wildcard dependency resolution code to take ignored folders into account
> [LYN-7520] Wildcard Source Dependencies include files in cache/excluded files

- Code/Editor/CryEdit.cpp
- cmake/Platform/Windows/Packaging/Bootstrapper.wxs
- cmake/Platform/Windows/Packaging/Shortcuts.wxs
Did a search&replace on "Developer Preview" in the solution and replaced with the "Stable 21.11" denomination.
> Replace old Developer Preview release name with Stable 21.11

- Code/Framework/AzFramework/AzFramework/Entity/EntityDebugDisplayBus.h
- Gems/Atom/Feature/Common/Code/Source/AuxGeom/AuxGeomDrawQueue.cpp
- Gems/Atom/Feature/Common/Code/Source/AuxGeom/AuxGeomDrawQueue.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/AuxGeom/AuxGeomDraw.h
- Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.cpp
- Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.h
- Addressed comments from https://github.com/o3de/o3de/pull/5737
- Fixed default sphere orientation to previous default (z up)
- Added ability to provide an orientation when drawing a sphere
- Added some previously added new shapes to DebugDisplayRequestBus
> Addressed feedback from previous PR plus some cleanup

- Gems/Atom/Feature/Common/Assets/Passes/ReflectionScreenSpace.pass
- Gems/Atom/Feature/Common/Assets/Passes/ReflectionScreenSpaceBlur.pass
- Gems/Atom/Feature/Common/Assets/Passes/ReflectionScreenSpaceBlurVertical.pass
- Gems/Atom/Feature/Common/Assets/Passes/ReflectionScreenSpaceComposite.pass
- Gems/Atom/Feature/Common/Assets/Passes/ReflectionScreenSpaceTrace.pass
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceBlurCommon.azsli
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceBlurVertical.azsl
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceBlurVertical.shader
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceComposite.azsl
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceTrace.azsl
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceTrace.shader
- Gems/Atom/Feature/Common/Code/Source/CommonSystemComponent.cpp
- Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionCopyFrameBufferPass.cpp
- Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceBlurPass.cpp
- Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceBlurPass.h
- Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceCompositePass.cpp
- Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceCompositePass.h
- Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceTracePass.cpp
- Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceTracePass.h
- Gems/Atom/Feature/Common/Code/atom_feature_common_files.cmake
Added a frame delay before activating SSR to avoid sampling the previous frame image before it is ready.
Improved fallback to IBL/probe reflections on a ray miss or camera facing ray.
Blurred the reflection buffer and added a depth-aware upsample.
Larger Gaussian kernel size for the mip blur.
> Fix for SSR initialization and visual quality improvements

- Code/Editor/ActionManager.cpp
- Code/Editor/ActionManager.h
- Code/Editor/MainWindow.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiCluster.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiDisplay.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiDisplay.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiSwitcher.cpp
This PR also removes an unused Qt property as we discovered it had no effect 🙈 
(and some Qt niceties like `show()`/`hide()` instead of using `setVisible(true/false)` everywhere)
Big thank you to @cgalvan too for their help with this! 🙂
> Improved look for viewport ui border close button

- Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
- Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.h
- Code/Tools/ProjectManager/Source/GemCatalog/GemModel.cpp
- Code/Tools/ProjectManager/Source/GemCatalog/GemModel.h
Deactivate a gem that fails to download, along with all gems that depend on it, and also for uninstalling a gem that has dependents
Download dependency gems automatically.
Allow re-attempting a download that fails.
> Extra gem download failure handling

- Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp
- Code/Editor/Lib/Tests/test_ViewportManipulatorController.cpp
- Code/Editor/ViewportManipulatorController.cpp
- Code/Editor/ViewportManipulatorController.h
- Code/Framework/AzFramework/AzFramework/Viewport/ClickDetector.cpp
- Code/Framework/AzFramework/AzFramework/Viewport/ClickDetector.h
- Code/Framework/AzFramework/Tests/ClickDetectorTests.cpp
Relates to LYN-7698 and LYN-8215
This definitely makes a big difference to _perceived_ click detection issues. Please see the before/after tests to confirm the behaviour.
I know the second viewport manipulator controller test isn't perfect (testing two things technically). I'd like to refactor it but I also don't think I can do that before EOD and I really want to merge this fix to the stabilization branch so please be aware it's a known area of improvement I will get back to soon 🙂 
before:
```
[ RUN      ] ClickDetectorFixture.DoubleClickIsNotRegisteredIfMouseDeltaHasMovedMoreThanDeadzoneInClickInterval
D:/o3de-2/Code/Framework/AzFramework/Tests/ClickDetectorTests.cpp(186): error: Value of: secondUpOutcome
Expected: is equal to ClickOutcome::Click
Actual: ClickOutcome::Nil (of type enum …
```
> Improvement for click detection when clicking quickly between mouse moves

- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/BuilderSettingManager.cpp
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/BuilderSettingManager.h
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/CubemapSettings.h
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/ImageProcessingDefines.h
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/EditorCommon.cpp
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/TexturePresetSelectionWidget.cpp
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvert.cpp
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvert.h
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvertJob.cpp
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvertJob.h
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImagePreview.cpp
Changes include:
-Fixed image preview issue which was trying to convert a compressed texture directly to QImage.
-Fixed texture resolution display for cubemap in texture setting editor.
-Sort the preset names in preset combo box
-Fixed a crash when showing IBLSkybox preset info in texture setting editor
> ATOM-16854 Texture Settings dialog box crashes in the Editor

- Gems/LmbrCentral/Code/Source/Ai/EditorNavigationAreaComponent.cpp
- Gems/LmbrCentral/Code/Source/Ai/EditorNavigationSeedComponent.cpp
- Gems/LmbrCentral/Code/Source/Ai/NavigationComponent.cpp
Removing the AI navigation components from the Add Component menu in the Entity Inspector.
Note that the components are still registered, so levels using them before this change will still work as expected. This is just the least intrusive fix we can have before release, so we can start redcoding the components appropriately in development soon.
> LYN-3447 | Navigation Components are unusable due to missing Agent Types

- Code/Framework/AzFramework/AzFramework/Archive/ArchiveVars.cpp
- Code/Framework/AzFramework/AzFramework/azframework_files.cmake
- Code/Framework/AzFramework/AzFramework/feature_options.cmake
- Code/Framework/AzFramework/CMakeLists.txt
- cmake/Deployment.cmake
Removed the generator expression from the `LY_ARCHIVE_FILE_SEARCH_MODE` define as Xcode doesn't support per-config per-file definitions.
Updated the #else block in ArchiveVars to default to PakOnly mode if the `LY_ARCHIVE_FILE_SEARCH_MODE` define isn't set.
Moved the the `LY_ARCHIVE_FILE_SEARCH_MODE` Cache Variable from cmake/Deployment.cmake to feature_options.cmake within the AzFramework folder.
> CMake Xcode Generator fix

- AutomatedTesting/Gem/PythonTests/editor/EditorScripts/EntityOutliner_EntityOrdering.py
- Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntitySortComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntitySortComponent.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntitySortComponentSerializer.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntitySortComponentSerializer.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
This change does a few things to address instability in entity order when prefabs are enabled:
- Changes ordering behavior on entity add to always be "insert after the last selected sibling of the new entity, or at the end if there is no selected sibling"
- Adds some logic to ensure selection stays frozen during prefab propagation to allow this behavior to be used
- Alters delta generation in `PrefabPublicHandler::CreateEntity` to use the template instead of reserializing the DOM - this avoids a whole bunch of patching issues caused by EditorEntitySortComponent doing post-hoc order fix-up and should generally be safer/faster as we're producing patches for the actual target for those patches
- Because the duplicate action is DOM-driven, and there's some thorniness around making changes …
> Fix several Prefab outliner ordering issues

- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/IndexedDataVector.h
- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/IndexedDataVector.inl
- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/MultiIndexedDataVector.h
- Gems/Atom/Feature/Common/Code/Tests/IndexedDataVectorTests.cpp
- Gems/Atom/Feature/Common/Code/Tests/MultiIndexedDataVectorTests.cpp
- Gems/Atom/Feature/Common/Code/atom_feature_common_tests_files.cmake
Also moving the tests for MultiIndexedDataVector currently in IndexedDataVectorTests to MultiIndexedDataVectorTests.
**Reviewer Note - File Rename**: The code in IndexedDataVectorTests is all new, don't bother looking at the comparison. The code that used to be in IndexedDataVectorTests has been moved to MultiIndexedDataVectorTests and only has minimal updates. This was done as two separate commits, so its easier to look at those individual diffs instead of the diff for the whole PR. (See d4a59a388491be7dbfd6c558704894a5377c6c81 and 4ae837410127b5428d3de8cf1ca31ceeaeee2629)
> Adding unit tests for IndexedDataVector

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
This is a regression introduced by https://github.com/o3de/o3de/pull/5762
The unit test that should have caught this was failing for unrelated reasons (unit tests don't use the Prefab EOS, but we rely on it in PrefabFocusHandler now). As such, this went unnoticed during testing yesterday.
This now fixes all checks that make sure to remove the level container from invalid operations (detach, delete).
Thanks @LB-BartoszDudzinski and @LB-KacperKapusta for picking up on the regression!
> Fix oversight from recent change to PrefabFocusHandler internals.

- scripts/build/Jenkins/Jenkinsfile
- scripts/build/tools/copy_file.py
This change is to use "Artifacts manager on S3" plugin to archive AP logs on S3 and then the AP logs are accessible from Jenkins UI.
We cannot specify S3 prefix when using "Artifacts manager on S3" plugin so we have to create the folder structure locally and archive that dummy folder.
Tried several copy commands but none of them worked, so I had to write our own copy script.
**copy**: Though we can use file path wildcard in source target parameter, this command cannot replicate the folder structure.
**xcopy**: Though we can use file path wildcard in source target parameter, here is a known issue that xcopy cannot deal with long path that exceeds 260 characters, the target file paths in dummy folder structure are very likely to exceed  260 characters.
**robocopy**: Wildcard can only be …
> Archive ap logs on s3

- Code/Framework/AzCore/AzCore/Asset/AssetContainer.cpp
- Code/Framework/AzCore/AzCore/Asset/AssetContainer.h
- Code/Framework/AzCore/AzCore/Asset/AssetManager.h
- Code/Framework/AzCore/Tests/Asset/AssetManagerLoadingTests.cpp
* Fixed race condition caused by trying to handle asset ready event before asset container has finished filling out all the data structures.
Added check to only handle asset ready once init is complete
Added unit test to verify fix
* Re-enable test
* Add missing space to error message
* Add comment on sleep
* Collapse nested namespace
* Collapse nested namespace
(cherry …
> [SPEC-7644] Cherry Pick - ParallelDeepAssetReferences is failing intermittently

- Gems/AWSCore/Code/CMakeLists.txt
- Gems/AWSCore/Code/Platform/Linux/PAL_traits_editor_linux.cmake
- Gems/AWSCore/Code/Platform/Mac/PAL_traits_editor_mac.cmake
- Gems/AWSCore/Code/Platform/Windows/PAL_traits_editor_windows.cmake
When the AWS Resource Mapping Tool was enabled for Linux, it pulled in the dependency for Pyside2 (required for the python script to work). However, Pyside2 is not supported (yet) for Mac, so we need a trait to completely skip buildint the ResourceMappingTool target on Mac
Signed-off-by: spham <82231385+spham-amzn@users.noreply.github.com>
> Add trait to enable/disable the Resource Mapping Tool

- Code/LauncherUnified/Platform/Common/UnixLike/Launcher_UnixLike.cpp
The function that modifies resource limits will return true always and warn instead
of giving an error.
closes #5471
> Modify resource limit function to warn rather than error

- cmake/Platform/Linux/runtime_dependencies_linux.cmake.in
The missing variable prevents the RPATH fix to even be applied 
> Restore missing variable 'target_filename_ext' needed to determine if RPATH fix is necessary or not

- Code/Tools/ProjectManager/Platform/Linux/ProjectBuilderWorker_linux.cpp
- Code/Tools/ProjectManager/Platform/Linux/ProjectUtils_linux.cpp
- Code/Tools/ProjectManager/Platform/Mac/ProjectBuilderWorker_mac.cpp
- Code/Tools/ProjectManager/Platform/Mac/ProjectUtils_mac.cpp
- Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp
- Code/Tools/ProjectManager/Source/ProjectBuilderWorker.cpp
- Code/Tools/ProjectManager/Source/ProjectUtils.cpp
- Code/Tools/ProjectManager/Source/ProjectUtils.h
Fix an issue where if CMake was not pre-installed and the path added to the "Path" environment variable, then Project Manager would also not find the version that comes with the installer.
This was due to the path only being added to a QProcessEnvironment that would take affect for child processes, so the spawned process would have the path to CMake in cmake/releases/bin, but Project Manager itself would not and so not be able to find it.
Note: The only reason that we were using QProcessEnvironment was to set this additional path. Now that it is being sent on the Project Manager process, it takes affect for all spawned processes as default, so there is no need to create and pass these objects around.
> Fix Project Manager not finding CMake on Windows

- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.h
- Code/Framework/AzToolsFramework/Tests/EditorTransformComponentSelectionTests.cpp
It was noticed near the end of last week that the feedback for icons (them turning yellow/orange when hovered) did not happen with a selection. This is the correct behavior when 'sticky select' is enabled (the old default) but is wrong when it's disabled. This change takes into account both stick/unsticky select and also makes the function testable with some additional coverage.
Fixes https://github.com/o3de/o3de/issues/5800
https://user-images.githubusercontent.com/82228511/142902805-30e8f9d0-f745-493b-9117-b8e96ace28ae.mp4
https://user-images.githubusercontent.com/82228511/142902821-f31efc4f-511f-4499-ae7e-e829175689a9.mp4
Note: The tests are not exhaustive but make it easy to add more should any bug be reported, this is a pretty good covering to start with.
```
[==========] Running 6 …
```
> Fix for how viewport icons highlight (accent) when sticky select is disabled

- Code/Framework/AzCore/AzCore/std/containers/fixed_vector.h
- Code/Framework/AzCore/Tests/AZStd/VectorAndArray.cpp
AZStd::fixed_vector had all its functions marked with constexpr, but this requires all member variables to be fully initialized. This meant that the internal array used to store elements always has to be fully initialized. This was done for trivial classes but not for non-trivial classes. As a result trivial classes always did a memset (or more optimized versions for smaller buffers) while the non-trivial version couldn't actually be stored in a constexpr variable. Since AZStd::fixed_vector is meant to be dynamic the choice was made to remove the constexpr from all non-static member functions in favor of avoiding the overhead of memset, which profiling showed was a considerable overhead depending on the reserved size. If a truly constexpr array is needed than AZStd::array is a better …
> Performance improvement for fixed_vector

- Code/Framework/AzCore/AzCore/Math/Matrix3x4.cpp
- Code/Framework/AzCore/AzCore/Math/Matrix3x4.h
- Code/Framework/AzCore/AzCore/Math/Matrix3x4.inl
- Code/Framework/AzCore/Tests/Math/MathTestData.h
- Code/Framework/AzCore/Tests/Math/Matrix3x4Tests.cpp
- Code/Framework/AzFramework/AzFramework/Viewport/ViewportBus.h
- Code/Framework/AzFramework/AzFramework/Viewport/ViewportScreen.cpp
- Code/Framework/AzFramework/AzFramework/Viewport/ViewportScreen.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Base.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/View.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/ViewportContext.h
- Gems/Atom/RPI/Code/Source/RPI.Public/View.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/ViewportContext.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ModularViewportCameraController.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ModularViewportCameraController.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Tests/ViewportInteractionImplTests.cpp
- Gems/AtomLyIntegration/AtomFont/Code/Source/FFont.cpp
- Gems/AtomLyIntegration/AtomViewportDisplayIcons/Code/Source/AtomViewportDisplayIconsSystemComponent.cpp
- Gems/Camera/Code/Source/CameraEditorSystemComponent.cpp
This change updates a number of functions to accept/return `Matrix3x4` for matrix transforms in the `WorldToScreen`/`ScreenToWorld` functions as that makes a lot more sense than `Matrix4x4`. I also removed a duplicate alias for a `MatrixChanged` event. 
I've added unit tests for the new `AZ::Matrix3x4::CreateFromMatrix4x4` and while I was there also added a `TransformPoint` function as it seemed odd that was missing from the API and could be added to the tests.
```
[----------] 1 test from MATH_Matrix3x4
[ RUN      ] MATH_Matrix3x4.TransformPoint
[       OK ] MATH_Matrix3x4.TransformPoint (0 ms)
[----------] 1 test from MATH_Matrix3x4 (0 ms total)
[----------] 5 tests from MATH_Matrix3x4/Matrix3x4CreateFromMatrix4x4Fixture
[ RUN      ] …
```
> Update return type for viewport screen functions

- Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp
- Code/Framework/AzToolsFramework/Tests/InstanceDataHierarchy.cpp
This PR addresses the Github Issue [ViewportEditorModeNotifications::Reflect method seems to not be called](https://github.com/o3de/o3de/issues/5848) and incidentally fixes the "warning as an error" issue with `InstanceDataHierarchyEnumContainerTest` that was blocking compilation of this PR.
```
Note: Google Test filter = *InstanceDataHierarchyEnumContainerTest*
[----------] 1 test from InstanceDataHierarchyEnumContainerTest
[ RUN      ] InstanceDataHierarchyEnumContainerTest.Test
[       OK ] InstanceDataHierarchyEnumContainerTest.Test (3 ms)
[----------] 1 test from InstanceDataHierarchyEnumContainerTest (5 ms total)
[----------] Global test environment tear-down
[==========] 1 test from 1 test …
```
> Fix for GHI5848 and InstanceDataHierarchyEnumContainerTest

- Code/Framework/AzCore/AzCore/std/containers/deque.h
- Code/Framework/AzCore/AzCore/std/containers/fixed_vector.h
- Code/Framework/AzCore/AzCore/std/containers/forward_list.h
- Code/Framework/AzCore/AzCore/std/containers/list.h
- Code/Framework/AzCore/AzCore/std/containers/vector.h
- Code/Framework/AzCore/AzCore/std/string/fixed_string.h
- Code/Framework/AzCore/AzCore/std/string/fixed_string.inl
- Code/Framework/AzCore/AzCore/std/string/string.h
- Code/Framework/AzCore/Tests/AZStd/String.cpp
- Code/Framework/AzCore/Tests/AZStd/VectorAndArray.cpp
There were already implementations for std::erase_if.
This adds the counterpart AZStd::erase versions
resolves #5734
> Adding missing C++20 std::erase implementations

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/Interpreted/ExecutionInterpretedAPI.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/Interpreted/ExecutionInterpretedAPI.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/Interpreted/ExecutionStateInterpreted.cpp
Since they were moved of the asset handler init path, RT dependencies were not getting fixed properly. This fixes that problem.
https://github.com/o3de/o3de/issues/5926
>  fix sc function static initialization of dependencies

- Code/Framework/AzCore/Tests/AZStd/VectorAndArray.cpp
fixes build break from PR https://github.com/o3de/o3de/pull/5735
> fix dev break. AZStd::fixed_vector cannot be constexp error

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewUtils.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewUtils.h
A source model asset can have multiple products including models and materials.
It’s not guaranteed that the first entry in the list of products for a model asset will be a model.
In this case the first product was the default material asset.
This caused some model previews to render a gray sphere depicting the default material.
> Fixed a bug with model previews and thumbnails.

- Code/Framework/AzCore/AzCore/Jobs/JobManagerComponent.cpp
GHI bug https://github.com/o3de/o3de/issues/5866 describes a scenario in which the Editor freezes on 6-thread CPUs.  This occurs because the Job Manager ends up with only 2 threads.  The freeze occurs when the main thread spawns a culling job and blocks on it, a Mesh Feature Processor job spawns processing jobs and blocks on them, and a Material/ShaderVariant load queues an asset load and blocks on it.  No new jobs can get started, and the main thread can't continue to process the asset load, so it freezes.
This workaround boosts the minimum number of threads from 2 to 3 by default, which fixes this specific scenario.  The longer-term fix would be to fix any jobs that block on other jobs to no longer block, so that even 1 job thread would work correctly.
> Workaround for Editor freeze.

- Gems/Atom/Feature/Common/Assets/Passes/SMAAEdgeDetection.pass
- Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/PostProcessing/ViewSrg.azsli
- Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceBlurPass.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/DescriptorSetLayout.h
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp
- Swapchain related fix for UI editor (only tested Windows)
-  Object of type VkQueue is simultaneously used in the main thread and the queue thread. Pushed the swapchain invalidation to the presentation queue thread
- Added padding for DepthOfFieldData to ensure it is 16 byte aligned
- Added aspect flag for SMAAEdgeDetectionTemplate pass
- Reduced MaxUnboundedArrayDescriptors so that it is under the maxDescriptorSetSampledImages limit
- Added CopyRead flag for ReflectionScreenSpaceBlurPass related transient resources.
> Various Vulkan fixes 

- Gems/Camera/Code/Source/CameraComponentController.cpp
- Gems/Camera/Code/Source/CameraComponentController.h
- Gems/Camera/Code/Source/EditorCameraComponent.cpp
This fixes #5477
There is some notes to this fix:
1 - When you lock the camera transform in "Be this camera" mode you can still move around but the camera transform won't be updated, once you unlock the camera transform and move while still being that camera will update its position to the current view.
2 - If you have moved while being this camera and with the transform locked, if you switch to another camera and return to the locked one will return to that camera locked transform.
Suggestions:
It would be worth thinking about having a button in the camera component that would let you recenter the current view to the camera's transform, so when you move when the transform locked you can return to the view. I've heard this from @HogJonny-AMZN and this could be expanded to a "look through …
> Camera locking when its transform is locked

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/Commands.cpp
- Gems/EMotionFX/Code/Tests/UI/CanUseFileMenu.cpp
Saving an anim graph did not adjust the dirty flag and thus the saved changes dialog kept showing anim graphs that already saved the latest changes.
Resolves #4523
> EMotion FX: Saving Anim Graph with CTRL+S displays unsaved changes prompt when no changes were made

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyIntCtrlCommon.h
- Code/Framework/AzToolsFramework/Tests/PropertyIntCtrlCommonTests.cpp
- Code/Framework/AzToolsFramework/Tests/PropertyIntCtrlCommonTests.h
- Code/Framework/AzToolsFramework/Tests/PropertyIntSpinCtrlTests.cpp
- Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
Also added tests to verify PropertyEditorGUIMessages::Bus::Handler::OnEditingFinished and PropertyEditorGUIMessages::Bus::Events::RequestWrite events are send by the int spin controls.
> Fix Integer Spin Controller not sending PropertyEditorGUIMessages::Bus::Handler::OnEditingFinished

- Code/Framework/AzFramework/AzFramework/Terrain/TerrainDataRequestBus.cpp
- Code/Framework/AzFramework/AzFramework/Terrain/TerrainDataRequestBus.h
Fixed the way in which GetSurfacePoint is exposed to BehaviorContext so that it is functional from ScriptCanvas.
> GetSurfacePoint - expose to BehaviorContext

- Code/Framework/AzCore/AzCore/IO/Path/Path.h
- Code/Framework/AzCore/AzCore/IO/Path/Path.inl
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryConsoleUtils.cpp
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryConsoleUtils.h
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.cpp
- Code/Framework/AzCore/Tests/Settings/SettingsRegistryMergeUtilsTests.cpp
The SettingsRegistryMergeUtils.cpp now supports specifying a path to a JSON Merge Patch formated settings registry file via the --regset-file option.
The option supports specify an anchor key to merge the settings underneath that is separated from the filepath via "::"
Ex. `--regset-file="Registry/custom.setreg::/Custom/Anchor"`
An AZ::Console command of "sr_regset-file" has also been added to allow merging of a setting registry file as well.
closes #5767 
> Added the --regset-file option for setreg file loading

- Code/Tools/ProjectManager/CMakeLists.txt
- Code/Tools/ProjectManager/Source/GemCatalog/GemInfo.h
- Code/Tools/ProjectManager/tests/GemCatalogTests.cpp
No new bugs were found through the development of tests (besides display name being set) but it did bring to question whether the intended results from some of the filters are the most desirable. Most filters work on an or basis relative to themselves and an and basis relative to other filters. 
This is outside of the scope of this PR but it might be worth considering whether a user would prefer platform selection to work on an or basis or (as it does currently) or an and basis.Using an or basis if a user selected the Windows, Android and iOS platforms all gems that supported at least one of those platforms would be shown. Instead the user might prefer it to work on an and basis wherein only the gems that supported all of those platforms would be shown. This way the user could determine …
> Added Tests for Gem Catalog Filtering

- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryConsoleUtils.h
The Legacy Cry XConsole code validates that CVars only contain
underscore and alphanumeric characters via an Assert in `debug`
configurations.
> Rename sr_regset-file CVar to sr_regset_file

- Gems/AudioSystem/Code/Source/Editor/AudioControlsWriter.cpp
This is due to a problem in the filepath.
> Audio System - Fix for bug while deleting file

- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Decals.azsli
- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lighting/StandardLighting.azsli
- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/LightingUtils.azsli
- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/Ibl.azsli
- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/Ltc.azsli
- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/PolygonLight.azsli
- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/QuadLight.azsli
- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Microfacet/Brdf.azsli
- Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/Math.azsli
This adds support for clearcoat to quad and polygon linearly transformed cosine lights. This is rather expensive since the polygon needs to be clipped against a separate clearcoat normal, so it effectively doubles the work on already expensive light types.
This change also fixes a bug with clearcoat in general where the regular specular was being suppressed too much based on the fresnel of the clearcoat. 
Also included are several fixes for warnings in the standard pbr shader. Most of these involved harmless vector truncations, but there was one case where some diffuse color information in partial metallics might have been getting lost.
> Adding clearcoat to linear transform cosine light and several bug fixes

- Code/Editor/Util/Image.cpp
change CImageEx:: ReverseUpDown function to avoid new uint32(width*height).
> optimization ReverseUpAndDown function

- Gems/Atom/RHI/Code/Include/Atom/RHI/Factory.h
- Gems/Atom/RHI/Code/Source/RHI/Factory.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI/Scope.cpp
Other external profilers aside from Pix (e.g. Nvidia Nsight) rely on the Pix events for instrumentation as well.
This PR adds the `--enablePixGpuMarkers` which enables Pix events without loading the Pix runtime for use with other GPU profilers.
> Add CLI option to enable PIX GPU events without expressing loading the Pix runtime

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
Without init the entity first it triggers a bunch of warning and asset during activation and that slows the process down significantly. 
> BUGFIX improve the start up time of the atom render plugin

- Code/Framework/AzQtComponents/AzQtComponents/Components/FancyDocking.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/FancyDockingDropZoneWidget.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/FancyDockingDropZoneWidget.h
these variables are fixed in place so I just declare them upfront as constexpr if its a primitive and a static const otherwise. avoides the duplicate static variables for FancyDockingDropZoneConstants.
> chore: remove duplicate instance of FancyDockingDropZoneConstants

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetWindow.cpp
Previously, if a motion was used by more than one motion set, and a user tried to remove it from one of the aforementioned sets, a prompt would appear asking if the user wanted to remove the motion entirely (which was recommended). However, that action would fail completely (it wouldn't remove the motion, or remove it from the motion set). Presumably, this was to prevent loss of the motion being used by another motion set. 
This fix allows the user to select Yes, and does cause the motion to be removed from the motion set. However, it still fails to remove the motion itself in its entirety, thus protecting other motion sets from losing a access to the motion, like the original functionality did.
> Bug motion set removal h

- Gems/LyShine/Code/Editor/AnchorPresetsWidget.cpp
- Gems/LyShine/Code/Editor/PropertiesWidget.cpp
I constrained the individual icons in a QVBoxLayout. I think I would like to have the rows constrain the container by their minimum width but that seems like a bit of a  more involved process. I can plan to do that next after this.  I increased the minimum width by a little bit so I can keep the icons the same size. 
https://user-images.githubusercontent.com/854359/142770173-5e8b8512-e668-4bab-87a0-e25a922a8606.mp4
I see the components in the entity inspector get clipped when the entity inspector is shrunk down. Properties in UI Editor is constrained by some minimum width where entries in the Entity Inspector just get clipped. 
ref: https://github.com/o3de/o3de/issues/5552
> UI Editor - bugfix: prevent Anchor buttons from overlapping when shrinking layout(#5552)

- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/BackLighting.azsli
Smoothing out the ndl term does a decent enough job of fixing the visual artifact in most cases:
(Note that one material screenshot test will need updating after this PR)
ATOM-16840
Signed-off-by: mrieggeramzn mriegger@amazon.com
> Fix for artifact with thin-film materials and shadows

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.cpp
- Gems/AudioEngineWwise/Code/Source/Editor/AudioSystemEditor_wwise.cpp
After associating a control and clicking Save, the control disappears. This bugfix ensures the association type processing is not omitted, allowing the correct display of the association.
> Bug -  association update

- Gems/PythonAssetBuilder/Code/Source/PythonAssetBuilderModule.cpp
This change was prompted by the Python asset builder activating in the material editor and asset processor, leading to conflicts as both initialized, started Python, spamming the console window and log with warnings while trying to save module symbol information.
Because PythonAssetBuilderSystemComponent also has a SystemComponentTag attribute declaring it as an AssetBuilder, it will still be discovered and automatically added to the asset builder.
Removing it from GetRequiredSystemComponents will stop the component from activating outside of the asset builder.
> Removing PythonAssetBuilderSystemComponent from GetRequiredSystemComponents

- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
- Gems/Multiplayer/Code/Source/MultiplayerToolsSystemComponent.cpp
```
==================================================================
2021-11-30T20:21:23{000000000000395C}[Module Manager]     Trace::Warning
D:/projects/lyengine/git/ly-dev/o3de/Code/Framework/AzCore/AzCore/Module/ModuleManager.cpp(34): 'bool __cdecl AZ::ShouldUseSystemComponent(const class AZ::ComponentDescriptor &,const class AZStd::vector<class AZ::Crc32,class AZStd::allocator> &,const class AZ::SerializeContext &)'
2021-11-30T20:21:23{000000000000395C}[Module Manager]     Component type MultiplayerToolsSystemComponent not reflected to SerializeContext!
2021-11-30T20:21:23{000000000000395C}[Module Manager]     ==================================================================
2021-11-30T20:21:23{000000000000395C}[Module Manager] …
```
> Fixing warnings caused by system components not added to serialize context

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
Previously the mesh deformer only got updated in OpenGLPlugin. That means if OpenGLPlugin is not enabled, the soft skinning won't happen and all the soft skinning based debug render will be incorrect.
> Update the deformer in the atom debug draw class

- Gems/AudioSystem/Code/Source/Editor/ATLControlsPanel.cpp
- Gems/AudioSystem/Code/Source/Editor/AudioControl.cpp
- Gems/AudioSystem/Code/Source/Editor/AudioControl.h
- Gems/AudioSystem/Code/Source/Editor/QConnectionsWidget.cpp
This prevents inappropriate connections being made and displays a message telling the user.
> Fix for bug - switch association fails

- cmake/Version.cmake
Allows `LY_VERSION_BUILD_NUMBER` to be set by the envvar `O3DE_BUILD_VERSION`. Currently defaults to `0`
> Add conditional to pull LY_VERSION_BUILD_NUMBER through environment var

- Gems/PhysX/Code/Source/Pipeline/MeshGroup.cpp
- Registry/AssetProcessorPlatformConfig.setreg
Adds ulterior check to ensure the PhysX material library asset is loaded correctly before trying to get materials data.
https://github.com/o3de/o3de/issues/6027
> Add additional check to ensure material library is loaded when trying to retrieve names.

- Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceKeyboard.h
my build was failing with redefinition error. 
> chore: add #prama once to XcbInputDeviceKeyboard

- Code/Framework/AzToolsFramework/AzToolsFramework/Entity/ReadOnly/ReadOnlyEntitySystemComponent.cpp
Fixes warning that fails the Mac builds after the read-only entity setup submission from yesterday:
```
2021-12-02T22:25:34.818Z] In file included from /Users/lybuilder/workspace/o3de/build/mac/Code/Framework/AzToolsFramework/CMakeFiles/AzToolsFramework.dir/Unity/unity_5_cxx.cxx:17:
[2021-12-02T22:25:34.818Z] /Users/lybuilder/workspace/o3de/Code/Framework/AzToolsFramework/AzToolsFramework/Entity/ReadOnly/ReadOnlyEntitySystemComponent.cpp:55:33: error: loop variable 'entityId' of type 'const AZ::EntityId' creates a copy from type 'const AZ::EntityId' [-Werror,-Wrange-loop-analysis]
[2021-12-02T22:25:34.818Z]         for (const AZ::EntityId entityId : entityIds)
[2021-12-02T22:25:34.818Z]                                 ^
[2021-12-02T22:25:34.818Z] …
```
> Fix warnings on Mac builds.

- scripts/build/Platform/Linux/build_config.json
- scripts/build/Platform/Mac/build_config.json
These jobs do not produce test xml's so we are disabling the test results stage because they are failing. Can only test during the nightly jobs.
> disabling unused test results jobs

- Gems/Atom/RHI/Code/Source/RHI/Factory.cpp
Build was failing around line 63 because s_pixGpuMarkersEnabled was not defined when USE_RENDERDOC was true:
#if defined(USE_RENDERDOC)
// If RenderDoc is requested, we need to load the library as early as possible (before device queries/factories are made)
bool enableRenderDoc = RHI::QueryCommandLineOption("enableRenderDoc");
s_pixGpuMarkersEnabled = s_pixGpuMarkersEnabled || enableRenderDoc;
> Fixing build fail when Renderdoc is enabled

- Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
Number args now show correctly in gem notifications
Closes #6120 
> Fix number argument in Project Manager notifications

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemScriptingHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
A couple of fixes to procedural prefab instantiation:
- Adds required editor components to the container entity of the procedural prefab (transform, visibility and lock). This issue was introduced by changes to the procprefab creation here: https://github.com/o3de/o3de/pull/4669
- Removes limitation that would cause procprefab instantiation to fail silently if no parent entity was explicitly selected. I think the assumption behind that decision is flawed, since there is currently no way to instantiate a procprefab so that it's not nested (since the level itself is a prefab).
> LYN-8733 | Instantiating a Procedural Prefab puts it at the root level

- Tools/LyTestTools/ly_test_tools/launchers/platforms/android/launcher.py
- Tools/LyTestTools/ly_test_tools/launchers/platforms/base.py
- Tools/LyTestTools/ly_test_tools/launchers/platforms/linux/launcher.py
- Tools/LyTestTools/ly_test_tools/launchers/platforms/win/launcher.py
Removes an old flag which was suppressing writing logs to logfiles. Tests previously relied on this for logging through RC.exe, which is no longer used.
Additionally fixes some interfaces which conflicted with the parent class, which would prevent certain launchers from even starting.
> Remove remote console flag suppressing game logs in GameLauncher and ServerLauncher apps

- AutomatedTesting/Gem/PythonTests/Physics/utils/FileManagement.py
- Tools/LyTestTools/ly_test_tools/environment/file_system.py
- Tools/LyTestTools/tests/unit/test_file_system.py
Example:
If the file that is to be backed-up is readonly, when restored that file will be readonly.
If the file that is to be backed-up is not readonly, when restored that file will be not readonly.
Fixes an issue that would mark physics setreg files to readonly after running AutomatedTesting when restoring from the backup.
> Automated testing create_backup and restore_backup respects file flags.

- Code/LauncherUnified/Platform/Android/Launcher_Android.cpp
Fixes https://github.com/o3de/o3de/issues/5853 where launching on Android would result in a confusing message logged with conflicting branding. 
Signed-off-by: gusmccallum <gusmccallum@hotmail.com>
> Updated android launcher to remove confusing branding

- Code/Framework/AzToolsFramework/AzToolsFramework/Logger/TraceLogger.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Logger/TraceLogger.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
Also switched the log message sink from a vector to a list so the entire container does not have to be rebuilt every time and entry is added.
> Changing trace logger to clear log file when opened

- Gems/Blast/AssetProcessorGemConfig.setreg
- Registry/AssetProcessorPlatformConfig.setreg
In order to work "critical" property needs to be without quotes.
Marking blast material library assets as criticals since it's necessary to be ready before the editor opens (same as physics materials)
> Fixed critical json property.

- scripts/o3de.py
- scripts/o3de/o3de/cmake.py
- scripts/o3de/o3de/disable_gem.py
- scripts/o3de/o3de/download.py
- scripts/o3de/o3de/enable_gem.py
- scripts/o3de/o3de/engine_properties.py
- scripts/o3de/o3de/engine_template.py
- scripts/o3de/o3de/gem_properties.py
- scripts/o3de/o3de/get_registration.py
- scripts/o3de/o3de/global_project.py
- scripts/o3de/o3de/manifest.py
- scripts/o3de/o3de/print_registration.py
- scripts/o3de/o3de/project_properties.py
- scripts/o3de/o3de/register.py
- scripts/o3de/o3de/repo.py
- scripts/o3de/o3de/sha256.py
- scripts/o3de/o3de/utils.py
- scripts/o3de/o3de/validation.py
- Added the -v/-vv option to the most commonly used o3de sub-commands
- Adds a custom argparse Action to make it easy to add verbosity option
to other commands as needed.
- Sets up parent-child loggers so that when verbosity is changed in a
sub-command it will be applied globally to all logger instances.
Also:
- Fixes up many warnings, PEP8 improvements
> Add verbosity option to some o3de.py sub-commands

- Code/Tools/ProjectManager/Source/Application.cpp
- Code/Tools/ProjectManager/Source/Application.h
- Code/Tools/ProjectManager/Source/EngineInfo.h
- Code/Tools/ProjectManager/Source/EngineSettingsScreen.cpp
- Code/Tools/ProjectManager/Source/GemRepo/GemRepoScreen.cpp
- Code/Tools/ProjectManager/Source/ProjectUtils.cpp
- Code/Tools/ProjectManager/Source/ProjectUtils.h
- Code/Tools/ProjectManager/Source/PythonBindings.cpp
- Code/Tools/ProjectManager/Source/PythonBindings.h
- Code/Tools/ProjectManager/Source/PythonBindingsInterface.h
- scripts/o3de/o3de/engine_properties.py
- scripts/o3de/o3de/manifest.py
This change adjust how auto-engine registration used to work and moves the logic now to Application.cpp and when an existing engine is found with the name of the engine we want to register a dialog is shown giving the user the option to force register, rename the engine or quit Project Manager.
**Additional misc fixes/changes**
- fixed exception and added warning when using manifest.get_registered with missing .json files
- created helper for displaying detailed error outcomes, which are likely to be our preferred error message GUI in the future to show general errors and detailed python errors.
- added an m_registered field to EngineInfo to indicate if an engine is registered or not
- fixed issue when editing engine properties but no new properties were provided 
**Testing**
- setup a …
> GUI for engine force registration and renaming

- Gems/Atom/RHI/Code/Source/RHI/Factory.cpp
Fixes a regression introduced when Nsight Pix markers were enabled.
> Enable Pix markers if the Pix DLL is loaded

- Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
- Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.h
Several read-only prefab related workflow changes:
- It should not be possible to create a new entity as a child of a read-only entity
- It should not be possible to delete a direct child of a read-only entity
- It should not be possible to duplicate entities that are direct children of read-only entities
- It should not be possible to create a prefab if the selection contains a read-only entity
Also updated the "Delete" and "Duplicate" actions in the context menu to be hidden instead of just disabled.
Note: the procedural prefab is incorrectly placed at the root of the level in this gif. The build this was tested on was outdated, the issue has been fixed in latest development.
> Some read-only prefab workflow updates.

- Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp
Improved logged to print entity name if improperly deleted; helps when debugging to find the problem entity.
Note: This hasn't been unit tested. I added this small update when running into this assert myself, but wasn't sure which entity was causing the problem.
> Print Entity name if Improperly Deleted

- Gems/ScriptCanvas/Code/Editor/Framework/ScriptCanvasGraphUtilities.inl
Fixes this build error: `error: format specifies type 'int' but the argument has type 'size_t' (aka 'unsigned long') [-Werror,-Wformat]`
> [Mac] Format string specifier for size_t should be %zu

- AutomatedTesting/Gem/AssetProcessorGemConfig.setreg
- Code/Tools/AssetProcessor/native/tests/AssetCatalog/AssetCatalogUnitTests.cpp
- Code/Tools/AssetProcessor/native/tests/assetscanner/AssetScannerTests.cpp
- Code/Tools/AssetProcessor/native/tests/platformconfiguration/platformconfigurationtests.cpp
- Code/Tools/AssetProcessor/native/unittests/AssetProcessorManagerUnitTests.cpp
- Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp
- Code/Tools/AssetProcessor/testdata/config_regular/AssetProcessorPlatformConfig.setreg
- Code/Tools/AssetProcessor/testdata/config_regular_platform_scanfolder/AssetProcessorPlatformConfig.setreg
- Gems/AtomContent/Sponza/Registry/AssetProcessorPlatformConfig.setreg
- Gems/AudioEngineWwise/AssetProcessorGemConfig.setreg
- Registry/AssetProcessorPlatformConfig.setreg
In the steps to create a distributable engine SDK along with a pre-built project as part of workflow 7, the Editor within the SDK root is asked to be launched, but the SDK root at the point is within a folder called `install`.
Previously the AssetProcessor would exclude any files that contained a directory segment with the name of "install", even if the "install" directory is outside of any ScanFolders.
The step with the issue is below
> For the convenience of the rest of your team, run the editor and supply the --project-path <project-root> to it, create a level and save it. This can be useful to confirm that when they get the engine and project there is a level they can use to make sure everything is working normally.
The <sdk-root> by is located by default at …
> RTE7 Team Collabration: Fix issue where the AssetProcessor would not process any engine assets

- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/Ltc.azsli
- Quad lights can produce nan if intersecting other surfaces. This is caused by a division by 0 in the edge integration functions. Fixed by saturating the output.
- Small refactoring on LTC edge integration functions. To make the terms more explicit.
Fixes #5912 
Signed-off-by: Thomas Poulet <1039134+Bindless-Chicken@users.noreply.github.com>
> Fix quad light NAN on contact with other surfaces

- cmake/Version.cmake
Check whether environment variables are defined instead of checking the env variable contents. Avoids the conditional failing with version numbers of 3 digits, such as 21.11.1.
> Check whether env variables are defined

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
Some additional read-only prefab workflow changes:
- Hide the "Toggle pivot" context menu option when there is a read-only entity in the selection
- Hide the "Instantiate Prefab" context menu option when there is a read-only entity in the selection
- Hide the "Instantiate Procedural Prefab" context menu option when there is a read-only entity in the selection
> Additional read-only prefab workflow changes.

- scripts/o3de/o3de/get_registration.py
- scripts/o3de/o3de/manifest.py
- scripts/o3de/o3de/print_registration.py
Added a --project-engine-name/-pen argument to print_registration.py to
output the engine registered with the project.
> Fixed the get_registration.py script to print the manifest data

- scripts/build/Jenkins/Jenkinsfile
Pass pipeline name to post ar build sns topic.
Pipeline name is required by the lambda function to create Jira issues on nightly build failures.
> Pass pipeline name to post ar build sns topic

- Code/Framework/AzToolsFramework/Tests/Main.cpp
This
Before:
```
==================================================================
Memory: Trace::Warning
D:/o3de-2/Code/Framework/AzCore/AzCore/Memory/AllocationRecords.cpp(412): 'void __cdecl AZ::Debug::AllocationRecords::SetMode(enum AZ::Debug::AllocationRecords::Mode)'
Memory: Records recording was disabled and now it's enabled! You might get assert when you free memory, if a you have allocations which were not recorded!
Memory: ==================================================================
ComponentApplicationLifecycle:
==================================================================
ComponentApplicationLifecycle: Trace::Warning
D:/o3de-2/Code/Framework/AzCore/AzCore/Component/ComponentApplicationLifecycle.cpp(33): 'bool __cdecl …
```
> Add ComponentApplicationLifecycle::RegisterEvent calls to AzToolsFrameworkTests

- Code/Editor/Lib/Tests/test_DisplaySettingsPythonBindings.cpp
This fixes a flaky test failure in `DisplaySettingsComponentFixture.DisplaySettingsComponent_ConvertToSettingsAllSet`
`DisplaySettingsComponentFixture` was missing a call to `AZ::UserSettingsComponentRequestBus::Broadcast(&AZ::UserSettingsComponentRequests::DisableSaveOnFinalize);`
Related to https://github.com/o3de/o3de/issues/5718
> Add call to DisableSaveOnFinalize

- Gems/Atom/Feature/Common/Assets/Passes/DiffuseProbeGridRender.pass
- Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/ImageSubresource.h
- Gems/Atom/RHI/Code/Include/Atom/RHI/FrameGraphAttachmentDatabase.h
- Gems/Atom/RHI/Code/Include/Atom/RHI/FrameGraphCompileContext.h
- Gems/Atom/RHI/Code/Source/RHI.Reflect/ConstantsLayout.cpp
- Gems/Atom/RHI/Code/Source/RHI.Reflect/ImageSubresource.cpp
- Gems/Atom/RHI/Code/Source/RHI/FrameGraphAttachmentDatabase.cpp
- Gems/Atom/RHI/Code/Source/RHI/FrameGraphCompileContext.cpp
- Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/Device_Windows.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI/Image.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Image.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/ShaderResourceGroupPool.cpp
- Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/ResourcePool/ResourcePoolSourceData.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp
- Gems/Atom/RPI/Code/Tests/Shader/ShaderTests.cpp
- Handle Dx12 validation error related to multiple resource transitions happening on the same resource.
- Added API to better query for image/buffer views associated with an attachment.
- Address possible serialization issues by usage of size_t
- Reduced number of Descriptor sets allowed per SRG Pool in order to reduce descriptor waste.
> Multiple bug fixes

- Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderWorker.cpp
- Gems/ScriptCanvas/Code/Editor/GraphCanvas/Components/NodeDescriptors/ScriptEventReceiverEventNodeDescriptorComponent.cpp
- Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/GraphUpgrade.h
- Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Controller.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Controller.h
- Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Model.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/ModelTraits.h
- Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Modifier.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Modifier.h
- Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Scanner.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/AbstractCodeModel.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/PrimitivesDeclarations.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/PrimitivesDeclarations.h
There was a subtle bug in the version explorer. Graphs that had dependencies on other graphs that would also be updated would load the outdated version of their dependency since the AP had not finished processing the new version of their dependency. This adds a step in the modification process that waits for the AP notification that the dependency has succeeded before updating the graph that is waiting.
> Make version explorer wait on AP for dependent assets

- Code/Framework/AzToolsFramework/AzToolsFramework/Application/EditorEntityManager.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Application/EditorEntityManager.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
This is a cherry-pick of an earlier fix that was pushed to development branch: https://github.com/o3de/o3de/pull/4922/files
This prevents an assert when ctrl+D is hit very fast before the entities can be created. Instead of an assert, the change fails the action and shows an error message in the log.
> Improve error messaging when duplicating entities before they are created

- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
There are some cases where we don't want to show the transform manipulators in the viewport for certain selected entities (focus root, and read-only entities). Previously, this culling was being done in the `RefreshSelectedEntityIds` method, but this only catches selection changes that occur outside of the viewport (e.g. selecting entities in the Entity Outliner). However, this doesn't get called if the selection was changed by the viewport itself (e.g. picking an entity by selecting it in the viewport). So, moved this logic to the `RegenerateManipulators` method so that it gets called everytime, regardless of who modified the selection.
> Fixed logic for when to cull entities from having their viewport manipulators regenerated.

- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/LightCulling/NVLC.azsli
- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Decals.azsli
Fix shader compiler warnings caused by light culling.
Added [branch] to some if statements that I definitely don't want flattened
ATOM-16908
> Fix warnings, add branch notifier

- scripts/build/Jenkins/Jenkinsfile
Uploads the Testing directory upon AR test failures. Also moves the Testing dir cleanup to the PostBuild step. Some minor cleanup on the Test Metrics, but no functional changes there.
This was tested in a separate branch in AR. Test artifacts were successfully uploaded. Also tested new conditional unix commands manually on Linux.
> Modified Jenkinsfile to upload test artifacts on failure

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ModularViewportCameraController.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ModularViewportCameraControllerRequestBus.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ModularViewportCameraController.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.h
Update `ModularViewportCameraController` interface to make follow behaviors easier and update follow behavior for EMFX Atom Viewport.
This change comes after discussions with @amzn-rhhong. This change likely isn't 100% perfect, but it is a big step in the right direction. I think Roman can likely make further polish updates to this if need be (we can also add getters if they are needed in future).
https://user-images.githubusercontent.com/82228511/145391424-993b511a-3d84-4eff-b473-f5f23870fb77.mp4
> Update modular viewport camera controller interface

- Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp
The current Visual Studio requirements direct the user to a Microsoft page we have no control over that promotes Visual Studio 2022 and makes it difficult to find the Visual Studio 2019 install.  This change, directs the user to the O3DE docs where we can provide the user with correct information and links.
```
A compatible version of Visual Studio is required to build this project.
Refer to the <a href='https://o3de.org/docs/welcome-guide/requirements/#microsoft-visual-studio'>Visual Studio requirements</a> for more information.
```
I have confirmed the URL (https://o3de.org/docs/welcome-guide/requirements/#microsoft-visual-studio) with @erickson-doug 
> Fix Visual Studio requirements text and doc link

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemScriptingHandler.cpp
- Code/Framework/AzToolsFramework/CMakeLists.txt
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabScriptingTests.cpp
Updated PrefabSystemScriptingHandler::CreatePrefabTemplate to set the component ID of the created transform component to the hash of the file path.
Since Procedural Prefabs are regenerated from an FBX all the time, the component ID of the transform needs to be stable so that saved patches can still be applied.
> Procedural Prefabs:  Stable transform component ID

- Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/View.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/View.cpp
Make View::SortFinalizedDrawLists use child jobs so they don't block the worker thread from doing other work while waiting.
Implement a TaskGraph version of the view draw list sort.
Fix a misc bug where the scene was waiting on a task graph event twice and so hanging.
Enable MeshFeatureProcessor::Simulate to be able to use jobs when no parent job is specified because the parent job is a task.
> Fix editor hang on level load

- Gems/PhysX/Code/Source/System/PhysXSystem.cpp
- Gems/PhysX/Code/Source/System/PhysXSystem.h
This cherry picks the changes from PR #6168 in the development branch to have the PhysXSystem load the material library using the LegacySystemInterfaceCreated lifecycle event
> Cherry-Picking 5eb058f67905c7815458fb3a2a50cb654e4a08a8 to fix PhysX Material Initialize issue

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.cpp
Change Vulkan RHI CommandList::SetStreamBuffers to not do 2 memory allocation per draw by using fixed_vector
This takes the high instance test from 20fps to 44fps in my local testing.
> Double AtomSampleViewer HighInstanceTest perf when using the vulkan api

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Procedural/ProceduralPrefabAsset.cpp
- Gems/SceneProcessing/Code/Source/SceneBuilder/SceneBuilderWorker.cpp
Removes the feature toggle for proc prefabs, enabling them by default whenever the prefab system is enabled.
Also version bumped the scene builder to ensure any existing procedural prefabs are rebuilt
> Proc Prefabs: Remove feature toggle

- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
- Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.cpp
This is a cherry-pick of https://github.com/o3de/o3de/pull/6256 to the `stabilization/2111RTE` branch
Already approved and have triage approval for the change to go to RTE (QA, SIG, SDM, UX)
> Fix for change with axis gizmo labels not appearing (#6256)

- Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.cpp
> Disable invalid operations related to procedural prefabs in the Inspector

- Code/Framework/AzFramework/Platform/Windows/AzFramework/Asset/AssetSystemComponentHelper_Windows.cpp
After this change, the AssetProcessor process will be torn down by
default after its parent process shuts down (if it was spawned by a
parent process).
> Enable lifetime tethering of the AP by default

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/MaterialPropertyUtil.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/MaterialPropertyUtil.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Tests/AtomToolsFrameworkTest.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/CreateMaterialDialog/CreateMaterialDialog.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorBrowserInteractions.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/ViewportSettingsInspector/ViewportSettingsInspector.cpp
Replaced saving paths relative to the material file with paths relative to the source asset folder. This was causing problems creating and saving materials in external projects. Saving material relative paths is less critical for copying and sharing materials now that the asset processor and material editor can handle and warn about broken texture references. The user can fix up broken texture references inside the material editor.
Updated all of the create and save functions for materials and presets to use the utility functions for determining the project path. Project templates no longer come with a materials folder. So the default path was updated to the assets folder underneath the project folder. If the assets folder is also not guaranteed to be there, this can be changed to use the …
> Fixed several material editor bugs related to file paths and hot reload prompts

- Code/Framework/AzCore/AzCore/Serialization/Json/JsonSerializer.cpp
- Code/Framework/AzCore/AzCore/Serialization/Json/JsonSerializer.h
- Code/Framework/AzCore/Tests/Serialization/Json/TestCases_TypeId.cpp
Fixes https://github.com/o3de/o3de/issues/6286
Unit testing this was a bit of an adventure, but I've got a working regression test now. The serializer was attempting to store the type ID for Asset's generic class info instead of the specific type UUID that's yielded by `azrtti_typeid`, which caused a type mismatch on deserialization and the asset to be discarded.
Signed-off-by: Nicholas Van Sickle <nvsickle@amazon.com>
> Ensure StoreTypeName stores the correct type for generic types

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.cpp
> Change Vulkan RHI CommandList::SetStreamBuffers to not do 2 memory allocation per draw by using fixed_vector

- Code/Tools/ProjectManager/Platform/Windows/ProjectBuilderWorker_windows.cpp
- Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp
Force Project Manager to check for and generate projects with a supported version of VS 2019. 
> Force Project Manager to generate VS2019 projects on Windows

- Code/Framework/AzCore/AzCore/Script/ScriptContextDebug.cpp
Lua script sets breakpoint debugging, the position of the script break is incorrect
> Fix: Lua breakpoint error

- Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/Outliner/OutlinerWidget.cpp
In the entity outliner search box, the matching results are not expanded and displayed (prefab mode) 
> keyword bug fixed

- Code/Framework/AzCore/AzCore/Time/TimeSystem.cpp
- Code/Framework/AzCore/AzCore/Time/TimeSystem.h
GetRealElapseTime now correctly calculates time from application start.
> corrected implementation of GetRealElapseTime

- Gems/Atom/RHI/Code/Source/RHI/CommandListValidator.cpp
- Gems/Atom/RHI/Code/Source/RHI/ShaderResourceGroupPool.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.h
Remove noisy profile marker in the SRG validator
Make the SRG compile marker say which srg is being compiled
Move some dx12 validation code behind the AZ_RHI_ENABLE_VALIDATION define
> Minor optimizations from profiling.

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.h
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportToolBar.cpp
1. Feed the correct camera config value to light processor to avoid triggering assert 
2. When the follow mode is on, it doesn't follow the character on the start.
> [Bugfix] Atom render viewport in animation editor - small fix

- Gems/EMotionFX/Code/MysticQt/Source/MysticQtConfig.h
When a new node group is added to Node Groups in the animation editor, garbled characters or many words are missing when the name of the node group is changed to Chinese
> Garbled name when using Chinese charaters

- Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp
- Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
Build BLAS objects from the BLAS instance list instead of the mesh list.
> Fix for missing meshes in the RayTracing Acceleration Structure

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/ProceduralPrefabSystemComponent.cpp
> Fix missing parent class reflection for ProceduralPrefabSystemComponent

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/ColorGrading/EditorHDRColorGradingComponent.cpp
Color grading component was unable to get the correct pass attachment when generating the LUT. The fix is to add the render pipeline name on the pass hierarchy request.
> Add MainPipeline to pass hierarchy for when HDR color grading component requests for the lut generation's image attachment.

- Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorMainWindow.ui
- Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorWindow.cpp
- Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorWindow.h
Audio Controls Editor bug fix: Ctrl-S doesn't work correctly when a level is loaded. The level is saved instead of audio controls.
This is due to how ACE handles shortcuts. It uses keyPressEvent() but in this case the keyboard event intercepted somewhere in the editor and ACE doesn't have a chance to handle it. The correct way is to use QAction with shortcut.
PR also removes unnecessary shortcut handling for the global undo/redo functionality.
> [AudioSystem] ACE bug fix: Ctrl-S doesn't work correctly when a level is loaded.

- Code/Framework/AzCore/AzCore/Math/Quaternion.cpp
- Code/Framework/AzCore/AzCore/Math/Quaternion.h
- Code/Framework/AzCore/AzCore/Math/Quaternion.inl
- Code/Framework/AzCore/Tests/Math/QuaternionTests.cpp
Direct conversion helpers for quaternion to the scaled axis-angle representation and back without the need to convert them first to the axis-angle format and manually scale (or normalize on the way back). This also avoids having to deal with the special case of an identity representation which is 0,0,0 in the scaled axis-angle format while our convention for axis-angle is 0,1,0 for the axis and 0 for the angle.
Added unit tests that check the conversion round-trips from quaternion -> (scaled) axis-angle -> quaternion as well as comparing the scaled axis-angle representations from the direct helper functions as well as the axis-angle while manually scaling/normalizing.
> Quaternion to scaled-axis angle representation (and back) helpers

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Sandbox.py
Moving the P0 DisplayMapper component test to sandbox since it has been seen in a few timeouts for AR. We don't believe the test itself is flakey, but we are sandboxing as part of a broader investigation into why it is the suspect in more than one AR failure.
Also removed test_dummy from sandbox since it was not a valid test and caused errors for missing fixtures.
**.\python\python.cmd -m pytest --build-directory atom_dev/bin/profile  .\AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Main.py**
================================================= test session starts 
platform win32 -- Python 3.7.10, pytest-5.3.2, py-1.9.0, pluggy-0.13.1
rootdir: D:\workspace\o3de, inifile: pytest.ini
collected 25 items …
> sandboxing DisplayMapper P0 test for investigation

- Code/Framework/AzToolsFramework/Tests/UI/AssetBrowserTests.cpp
I have been looking into this for a while now and it has something to do with how the product addition to the AssetBrowserModel is being mocked. For now I deleted the conflicting lines that are triggering the assert so it doesn't affect productivity but I am working on a proper solution that might take a little bit more time.
I am also looking into this.
```
QSortFilterProxyModel: inconsistent changes reported by source model
```
It is some issue related to how rows are currently being removed #6404 
closes #6148
Signed-off-by: AMZN-Igarri <82394219+AMZN-Igarri@users.noreply.github.com>
> Fix: AssetBrowserTest cannot be run in debug

- AutomatedTesting/Gem/PythonTests/AWS/CMakeLists.txt
Platform specific folder has been removed in [previous PR](https://github.com/o3de/o3de/pull/6278). Updated the CMake file for the new file path.
Verified the build locally.
> Fix the cmake issue for AWSI automation tests

- Gems/Atom/Utils/Code/Include/Atom/Utils/PngFile.h
- Gems/Atom/Utils/Code/Source/PngFile.cpp
- Gems/Atom/Utils/Code/Tests/PngFileTests.cpp
Expanded the Png support in Atom Utils to allow Png data to either come from a file path or an in-memory buffer (via array_view).  Also provided a unit test to validate it.
This is needed in the use case where png data is downloaded at runtime and just needs to get immediately converted to usable pixel data without caching it to a storage device first.
(cherry picked from commit 6193dcf603d3c16ee193e1e6dc868bd6d04f89bc)
> Add support for loading Png data directly from a memory buffer.

- Code/Editor/IEditorImpl.cpp
- Code/Editor/Include/IEditorClassFactory.h
- Code/Editor/Include/IViewPane.h
- Code/Editor/Plugin.cpp
- Code/Editor/Plugins/PerforcePlugin/PerforceSourceControl.h
- Code/Editor/PreferencesStdPages.cpp
- Code/Editor/Util/FileUtil.cpp
- Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
The primary issue was the use of the `interface` keyword (reserved by Windows) and re-defining `__uuidof` in a manner that was unnecessary.
> Fix compile issues blocking adoption of Pix 2108

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Animation/AttachmentComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/SurfaceData/SurfaceDataMeshComponent.cpp
- Gems/FastNoise/Code/CMakeLists.txt
- Gems/FastNoise/Code/Tests/FastNoiseTest.cpp
- Gems/GradientSignal/Code/CMakeLists.txt
- Gems/GradientSignal/Code/Include/GradientSignal/Util.h
- Gems/LmbrCentral/Code/include/LmbrCentral/Component/EditorWrappedComponentBase.h
- Gems/LmbrCentral/Code/include/LmbrCentral/Component/EditorWrappedComponentBase.inl
- Gems/LmbrCentral/Code/include/LmbrCentral/Rendering/MeshAsset.h
- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.cpp
- Gems/Vegetation/Code/CMakeLists.txt
Fixed the following issues:
* Changed EditorWrappedComponentBase to avoid calling Deactivate() on nested components that are already deactivated, by better tracking the active state of the nested components.
* TerrainSystem would non-deterministically match terrain areas to each other incorrectly due to uninitialized priority variables in the area priority compare function.  Because they were uninitialized, we could sometimes get both "a < b" as false and "b < a" as false due to the uninitialized priority values changing between calls, which implied equality.  With the variables initialized, areas are only equal if their IDs are equal, regardless of priority.
* TerrainSystem had a couple of shared_lock calls that should have been unique_lock calls, since the lock was being used for …
> Misc Bugfixes

- Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/NsightAftermath_Windows.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI/CommandListBase.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI/CommandListBase.h
- Gems/Atom/RHI/DX12/Code/Source/RHI/NsightAftermath.h
Avoids any cost associated with wrapping the cstring with an AZStd::string
> Change the nvidia Aftermath integration to use c strings directly 

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Logging/LogPanel_Panel.cpp
Double-click the text in the Lua Editor log interface, and the text will appear ghosted
> Lua Editor log - text ghosted

- Gems/EMotionFX/Code/Source/Integration/Components/SimpleLODComponent.cpp
Negative values (which are invalid) can be used as input in the LoD system.
> Negative distances invalid

- Gems/Atom/RHI/Code/Include/Atom/RHI/MemorySubAllocator.h
- Gems/Atom/RHI/Code/Source/RHI/ShaderResourceGroupPool.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI/MemoryView.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Shader/ShaderResourceGroup.cpp
These 4 markers removed tens of thousands of events, which reduced an example capture from 1685 ms to 1614 ms and made it far more readable.
Signed-off-by: Mike Balfour <82224783+mbalfour-amzn@users.noreply.github.com
>
> Removed chatty profile markers.

- Gems/GradientSignal/Code/Include/GradientSignal/GradientSampler.h
- Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
- Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.h
Switched from a regular mutex to a shared_mutex, since usage follows a many-reader-one-writer pattern.  This improves contention on the common read case when calling GetValue() from multiple terrain and vegetation threads simultaneously.
Also removed a chatty profile marker in GradientSampler::GetValue().
> Image Gradient: Switch to shared_mutex

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.cpp
In the entity outliner search box, the matching results are not expanded and displayed (slice mode)
> Fix for bug in entity outliner search box

- Gems/WhiteBox/Code/Source/Components/EditorWhiteBoxColliderComponent.cpp
- Gems/WhiteBox/Code/Source/EditorWhiteBoxComponent.cpp
Limit the max number to 1 when adding white box component or white box collider component. 
> White box limit

- Code/Framework/AzCore/AzCore/Math/Quaternion.h
- Code/Framework/AzCore/AzCore/Math/Quaternion.inl
- Code/Framework/AzCore/Tests/Math/QuaternionTests.cpp
* Added new helper functions to get the shortest equivalent of the rotation. In case the w component of the quaternion is negative the rotation is > 180° and taking the longer path. The quaternion will be inverted in that case to take the shortest path of rotation.
* Added unit test.
* Renamed the angle parameter of the CreateRotationX/Y/Z() functions into angleInRadians.
> Quaternion shortest equivalent

- Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp
Fix network binding component to use the new svg icons instead of png (which no longer exist).
The missing icon was causing an error in Editor: [Error] Failed to locate icon on disk: "Icons/Components/Viewport/NetBind.png"
Tested by adding a Network Binding component and seeing that there are no longer any errors, and that the icons appear.
> Fix Network Binding Component Icon

- Code/Framework/AzCore/AzCore/Math/Plane.inl
would be useful to add these assertions here to catch for cases where a plane is not correctly setup.
> chore: add assertions to plane to ensure normalization

- Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorMainWindow.ui
- Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorWindow.cpp
- Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorWindow.h
1. Panels now can be resized horizontally by dragging the boundary between them.
2. Added "File -> Refresh Audio System" action (same as "Game -> Refresh Audio") with "Ctrl-Shift-R" shortcut.
3. Added Ctrl-R shortcut for the "File->Reload" action.
> [AudioSystem] Audio Controls Editor minor improvements.

- Gems/EMotionFX/Code/Source/Integration/Components/SimpleLODComponent.cpp
Parameters of the Simple LOD distance component still take effect after Enable anim graph is disabled
> Parameters of LOD distance component still take effect when anim graph disabled

- Gems/Atom/Feature/Common/Code/Source/CoreLights/EsmShadowmapsPass.cpp
Early return if input attachment is null
> [MacOS] Fix crash caused by trying to dereference a nullptr

- AutomatedTesting/project.json
After opening File-"Project Settings-"Project Settings Tool, the Executable Name and Version Name fields are red, and the values ​​are illegal.
> Illegal exe name and version no. when opening Project Settings Tool

- Gems/GradientSignal/Code/CMakeLists.txt
- Gems/GradientSignal/Code/Include/GradientSignal/ImageAsset.h
- Gems/GradientSignal/Code/Tests/EditorGradientSignalPreviewTests.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalBenchmarks.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalImageTests.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalReferencesTests.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalServicesTests.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalSurfaceTests.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalTest.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalTestFixtures.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalTestFixtures.h
- Gems/GradientSignal/Code/Tests/GradientSignalTestMocks.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalTestMocks.h
- Gems/GradientSignal/Code/Tests/GradientSignalTransformTests.cpp
- Gems/GradientSignal/Code/gradientsignal_editor_tests_files.cmake
- Gems/GradientSignal/Code/gradientsignal_tests_files.cmake
Most of the changes are just cleanup and rearranging of some unit test code so that way it could be reused from the benchmark suite.  Also added a second constructor to ImageAsset() so that I could remove a hack in the unit tests for setting the assets to ready on construction.
The primary change is adding a set of benchmarks for measuring GetValue(), so that we can compare against GetValues() when it gets added.
```
-------------------------------------------------------------------------------------------------------------
Benchmark                                                                   Time             CPU   Iterations
------------------------------------------------------------------------------------------------------------- …
```
> Add benchmarks to GradientSignal.

- Code/Editor/EditorPanelUtils.cpp
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/AssetEditorToolbar/AssetEditorToolbar.ui
The Groups and Ungroups shortcut keys in Script Canvas Editor do not take effect
> Script Canvas Groups

- Gems/EMotionFX/Code/EMotionFX/Rendering/Common/RenderUtil.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeFootIKNode.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeTwoLinkIKNode.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/Mesh.cpp
- Gems/EMotionFX/Code/MCore/Source/Vector.h
a safeNormalize method already exists. make sense to already use the existing implementation under Vector3. 
ref: https://github.com/o3de/o3de/pull/6433
> chore[EmotionFX]: replace usage of SafeNormalize

- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/DirectionalLightShadow.azsli
- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/DirectionalLightFeatureProcessorInterface.h
- Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/CoreLights/DirectionalLightBus.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/CoreLights/DirectionalLightComponentConfig.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DirectionalLightComponentConfig.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DirectionalLightComponentController.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DirectionalLightComponentController.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorDirectionalLightComponent.cpp
Adding toggle (off by default) to blend between two shadow map cascades on the border between them. I set the blend zone at 0.015 (in the range 0->1) as the blend zone. This could be increased to better hide the transition. Idea came from the Microsoft Cascade 11 shadow map sample.
Also added from [branch] tags because I want to be explicit about avoiding the expensive code paths. (I reread Emil Perrson's optimization guide recently)
https://user-images.githubusercontent.com/61609885/144941809-4d368487-195d-4923-9b50-39629c182a42.mp4
ATOM-16894
> Adding cascade blending for pcf

- Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
Removed some unnecessary `ResetProjectsContent();` because it is already called by `NotifyCurrentScreen`
Fixes #6523
> Reflow Project Tiles Everytime They Are Updated

- AutomatedTesting/Gem/PythonTests/assetpipeline/ap_fixtures/clear_moveoutput_fixture.py
- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_relocator_tests.py
- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/C21968388/DependencyScannerAsset.prefab
Modify AP automated test `test_WindowsMacPlatforms_MoveCorruptedSliceFile_MoveSuccess` to test prefab files instead of slice files for slice deprecation.
> Make 'test_WindowsMacPlatforms_MoveCorruptedSliceFile_MoveSuccess' to use prefab instead

- Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignmentSerializer.cpp
- Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignmentSerializer.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/MaterialPropertyUtil.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
The bug reported that overridden texture properties would be lost whenever an entity was created, destroyed, or a prefab was created. Initially, it seemed like there was a problem with the custom JSON serializer for material properties. Debugging proved this to be incorrect because all of the data was converted to JSON values in the serializer on multiple passes. At some point during prefab patching, the data for the asset properties is lost while other values like colors and floats serialize correctly. Converting the asset data values into asset IDs resolves the immediate problem for the material component but the underlying issue is still under investigation by the prefab team. This change is being posted for review in case the underlying issue cannot be resolved in time for the next …
> Temporary fix for material component losing image overrides with prefabs

- scripts/build/Jenkins/Jenkinsfile
Changed test artifact upload check to CTEST_OPTIONS field. There exists test jobs that do not have a "TEST_SUITE" value for its CMAKE_TARGET field. All test jobs have a CTEST_OPTIONS field
> Changed test artifact upload check

- Gems/EMotionFX/Code/EMotionFX/Source/EMotionFXManager.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/EMotionFXManager.h
- Gems/EMotionFX/Code/EMotionFX/Source/Pose.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/Pose.h
- Gems/EMotionFX/Code/EMotionFX/Source/PoseData.h
- Gems/EMotionFX/Code/EMotionFX/Source/PoseDataFactory.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/PoseDataFactory.h
* Added debug draw function to the pose class for sharable and easy-to-use pose debug visualization that includes pose data debug rendering.
* Extended the pose data factory with the ability to add pose data types from outside of the EMFX SDK and external gems.
* In order to get access to the pose data factory, it got added to the EMFX manager.
> EMotion FX: Extendable pose data and pose debug visualization

- Gems/AtomLyIntegration/AtomViewportDisplayInfo/Code/Source/AtomViewportDisplayInfoSystemComponent.cpp
When going into game mode or after initializing some system that takes a few seconds, the FPS counter showed really large numbers, extending across the whole with of the viewport. In this case, values show "inf" now.
> Atom: Frame counter string sometimes extends across the whole width of the viewport

- Code/Framework/AzCore/AzCore/Serialization/Json/RegistrationContext.h
- Code/Framework/AzCore/Tests/Serialization/Json/JsonRegistrationContextTests.cpp
That exception is an access violation, which could not happen (i.e. the memory could be valid for the process). I hit this issue in another PR, the test was not dying in Jenkins.
The test doesnt have to be a death test. Also handled the situation better in the code to be able to continue in that scenario (useful for release configurations)
> Death test relies on an exception from occurring

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/AreaLightComponentController.cpp
for lights in automatic mode the attenuation is updated based on intensity. would there be a sensible way to have delegates notify the AreaLightComponentController that other fields should also be updated?
REF: https://github.com/o3de/o3de/issues/6128
> bugfix: update attenuation when light intensity changed for mode Automatic

- scripts/build/Jenkins/Jenkinsfile
Escape % for windows batch in palSh
When a branch name contains '/', env.BRANCH_NAME is URL encoded to "%2F" in Jenkinsfile, and when it's passed to Windows batch command, "%2" will be treated as special character of batch command. This will cause an issue that artifacts will be archived to the wrong S3 path when '/' is in branch name.
We need to escape "%" in Windows batch command.
> Escape % for windows batch command in palSh() function

- scripts/build/Jenkins/Jenkinsfile
Makes the `%` string replacement optional in the `palSh` function. This fixes an issue where `%%cI` in the git date prefix is being replaced with `%%%%cI` and preventing the installer build tag script from expanding the date variable
> Windows installer build tag date fix

- Gems/Atom/Feature/Common/Assets/Shaders/Depth/DepthPassCommon.azsli
Commit 67689d48cc0f142eccd4856b0686277b49ca42d0 enforced precision in
many vertex position outputs. This adds the attribute to the output of
the z-prepass, needed to ensure proper depth testing in the forward
passes.
Signed-off-by: Jeremy Ong <jcong@amazon.com>
> Add missing `precise` attribute to depth prepass output

- scripts/build/Platform/Linux/deploy_cdk_applications.sh
- Removed the inaccurate comments since the script will install nodejs directly
- Removed sudo for the npm call since it's not needed.
- Verified on a Linux EC2 instance and in an internal fork.
> Fix an issue where npm is not found when running AWSI deployment script on Linux

- Code/Tools/AssetProcessor/native/FileWatcher/FileWatcher.cpp
> Fixes VS2022 error C5233: explicit lambda capture 'isSlash' is not used

- Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityContextComponent.cpp
Same PR with the previously approved changes of https://github.com/o3de/o3de/pull/6738/commits/36140804d949d0cd1be0a4c2bb4f757d1b43074f . Creating a new PR since the commit history in previous branch got corrupted.
> Fix undo for create editor entity

- Code/Editor/NewLevelDialog.cpp
- Code/Editor/NewLevelDialog.ui
Fixes #6809 
Tested new level dialog and verified the input field for the level name is now focused by default.
> Fixed tab order for default input focus on new level dialog

- Gems/Atom/Feature/Common/Code/Source/Utils/EditorLightingPreset.cpp
- Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Common/ColorUtils.h
- Gems/Atom/RPI/Code/Source/RPI.Edit/Common/ColorUtils.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicProperty/DynamicProperty.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorAreaLightComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorDirectionalLightComponent.cpp
Ensures that the RGB values shown in the color picker match those being set in the component inspector. UX approved.
> change default color picker input color space to SRGB

- Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_DepthPass_WithPS.azsl
The "precise" keyword was recently added to several shader inputs, but one was missed. This led to inconsistency between the depth and forward passes which resulted in artifacts when parallax pixel depth offset was in use. See https://github.com/o3de/o3de/pull/6536
Testing: I used AtomSampleViewer to make a local baseline of all screenshots in _fulltestsuite_.bv.lua. The only change was to the parallax test cases, which were a clear improvement.
> Fixed depth clipping artifacts for parallax PDO.

- cmake/Platform/Mac/runtime_dependencies_mac.cmake.in
Remove quotes around list of paths
> [Mac] Fix build error caused due to exe files in Python.framework

- Tools/LyTestTools/ly_test_tools/_internal/pytest_plugin/test_tools_fixtures.py
- Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
- Tools/LyTestTools/ly_test_tools/o3de/editor_test_utils.py
- Tools/LyTestTools/tests/unit/test_editor_test_utils.py
- Tools/LyTestTools/tests/unit/test_fixtures.py
- Tools/LyTestTools/tests/unit/test_o3de_editor_test.py
Fixes crash log name for the crash log watchdog.
Also addresses an issue for tests using editor utils where the crash logs were being renamed. Tested locally and all unit tests pass.
> Crash log test tools bug

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabCatchmentProcessor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabDocument.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabDocument.h
PrefabCatchmentProcessor::ProcessPrefab was no longer updating the ProcessedObjectStore's referenced object list, this change exposes the referenced asset list in the new PrefabDocument API and uses them to update the referenced asset list.
Should fix https://github.com/o3de/o3de/issues/6561
Signed-off-by: Nicholas Van Sickle <nvsickle@amazon.com>
> Fix Prefab instance assets not preloading

- Gems/GradientSignal/Code/Tests/EditorGradientSignalPreviewTests.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalImageTests.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalReferencesTests.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalServicesTests.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalSurfaceTests.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalTest.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalTestFixtures.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalTestFixtures.h
- Gems/GradientSignal/Code/Tests/ImageAssetTests.cpp
The unit tests and benchmarks were previously relying on a MockShape, which worked, but was consuming 99.9% of the benchmark time as gmocks are apparently extremely expensive and shouldn't be used when benchmarking code.  This PR changes GradientSignal over to using actual Shape components by loading the LmbrCentral gem and removing most of the MockShape usage.  This also had the benefit of reducing the overall amount of test setup code required.
> Changed GradientSignal unit tests to use actual Shape components

- Code/Tools/AssetProcessor/native/tests/SourceFileRelocatorTests.cpp
There is a variable with the name "interface" which appears to be conflicting with the [MSVC keyword](https://docs.microsoft.com/en-us/cpp/cpp/keywords-cpp?view=msvc-170#ccli-and-ccx-keywords).  It's unclear what the exact parameters that caused the following error but it was found using Visual Studio 2019 v16.11.7 and v16.11.8, with and without unity files enabled:
```
D:/git/o3de/engine/Code/Tools/AssetProcessor/native/tests/SourceFileRelocatorTests.cpp(796,25): error C2332: 'struct': missing tag name [D:\git\o3de\engine\build\windowsUnity\Code\Tools\AssetProcessor\AssetProcessor.Tests.vcxproj]
auto* interface = AZ::Interface<ISourceFileRelocation>::Get();
^
D:/git/o3de/engine/Code/Tools/AssetProcessor/native/tests/SourceFileRelocatorTests.cpp(796,25): error C2226: syntax error: …
```
> [development] fix for a possible MSVC compiler bug

- Code/Editor/Lib/Tests/test_DisplaySettingsPythonBindings.cpp
- Code/Framework/AzCore/AzCore/std/string/fixed_string.inl
- Code/Framework/AzCore/AzCore/std/string/string.h
- Code/Legacy/CryCommon/IMovieSystem.h
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Styling/SelectorImplementations.h
- Gems/LyShine/Code/Source/Animation/AnimNode.h
- Gems/LyShine/Code/Source/Animation/UiAnimationSystem.cpp
- Gems/LyShine/Code/Source/Animation/UiAnimationSystem.h
- Gems/LyShine/Code/Source/LyShine.cpp
- Gems/Maestro/Code/Source/Cinematics/AnimPostFXNode.cpp
- Gems/Maestro/Code/Source/Cinematics/Movie.cpp
- Gems/Maestro/Code/Source/Cinematics/Movie.h
- Gems/TextureAtlas/Code/Source/TextureAtlasImpl.h
Updated the Maestro MovieSystem and LyShine AnimationSystem to register Anim Nodes and Anim Params into a member variable map.
Previously the registration was occurring in a global variable map inside
of Movie.cpp and UiAnimationSystem.cpp
Rolled back the changes to update the CUiAnimNode and CAnimParamType to
use the stateless allocator in their m_name string member.
This was only needed because those types were used in global memory.
Updated the string classes AZStd::hash specialization to be [transparent](https://en.cppreference.com/w/cpp/named_req/UnorderedAssociativeContainer) to allow keys which aren't off string types to be forwarded to their hashing algorithms without creation of an instance.
> Updated AnimNode registration in LyShine and Maestro to register to a member variable map

- Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR_DepthPass_WithPS.azsl
- Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR_ForwardPass.azsl
- Gems/Atom/Feature/Common/Assets/Materials/Types/Skin.azsl
- Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR_DepthPass_WithPS.azsl
- Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR_ForwardPass.azsl
- Gems/Atom/TestData/TestData/Materials/Types/AutoBrick_ForwardPass.azsl
- Gems/Atom/TestData/TestData/Materials/Types/MinimalPBR_ForwardPass.azsl
> Add missing 'precise' keyword for Vertex shaders

- Gems/HttpRequestor/Code/CMakeLists.txt
Related to: https://github.com/o3de/o3de/issues/6732
Rebuilding the project .sln shows this test is no longer in `TEST_SUITE_main` but is part of the `TEST_SUITE_sandbox` target:
--
Signed-off-by: allisaurus <34254888+allisaurus@users.noreply.github.com>
> Disable flaky HttpRequestor test

- Gems/AtomTressFX/Code/Rendering/HairRenderObject.cpp
- Gems/AtomTressFX/Code/Rendering/HairRenderObject.h
- The crash happens due to attempt to get an instance of the hair dynamic data before it was initialized.
- This will also lock texture resource as it is trying to load / create it, making it safer to use. Following push should include async load of the asset instead as a better solution.
> AtomTressFX - fix bug 'Creating / Saving a prefab containing an entity with Atom Hair will crash the Editor'

- cmake/Platform/Mac/runtime_dependencies_mac.cmake.in
Fixes https://github.com/o3de/o3de/issues/6908 
The rpath wasn't being set because of the typo and dxc wasn't able to find the dependency.
> [Mac] Fix AssetProcessor failures on MacOS

- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Shader/Shader.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderVariantAsset.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Shader/Shader.cpp
- Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderVariantAsset.cpp
Changed the Shader instanceId to the combined assetId and supervariant index.
> Allow InstanceDatabase<Shader> to support multiple instances with different supervariants

- Gems/WhiteBox/Code/CMakeLists.txt
> [development] added required runtime dependency Gem::PhysX.Editor to WhiteBox.Editor.Physics.Tests 

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Application/AtomToolsApplication.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
Thumbnails for the AtomLyIntegration common feature gem were no longer being rendered. The setup code was modified to initialize the thumbnail system after receiving a new event that critical assets finished compiling. This event was being sent and handled correctly in the main editor. This process was failing in other tools because the event was sent before systems were registered to listen for it.
To resolve the problem, atom tools application now explicitly connects to the asset processor and processes critical assets after the base application StartCommon function is called. This ensures that the connection is established and the event gets sent after all of the system components have been activated.
> Atom Tools: move asset processor connection to fix thumbnails

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/material_editor_utils.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomMaterialEditor_BasicTests.py
Removes unexpected lines since these cause the material editor (ME) tests to run the duration of the timeout.
Adds tests for ME for pane visibility for inspector and asset browser. This effectively batches the tests to reduce run time. Expected lines for window pane visibility are marked P1 for priority of test.
.\python\python.cmd -m pytest --build-directory atom_dev/bin/profile  .\AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Main.py
====================================== test session starts
platform win32 -- Python 3.7.10, pytest-5.3.2, py-1.9.0, pluggy-0.13.1
rootdir: D:\workspace\o3de, inifile: pytest.ini
collected 26 items
AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Main.py ........................... [100%] …
> Material Editor tests for window pane function

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
- Registry/gem_autoload.materialeditor.setreg
- Registry/gem_autoload.shadermanagementconsole.setreg
Atom tools are set up to inherit and automatically load all of the gems used by the game project. This is a great simplification that saves us from having to manually update cmake settings for every game project to push dependencies to every tool. The tradeoff is that some dependencies will be added to certain tools that have no relevance whatsoever, potentially wasting initialization time, memory utilization, and some processing. This change follows an existing example to update a couple of tools to forego initializing unused gems. They can easily be reenabled as needed.
> Atom Tools: disabling auto load of unused gems in some atom tools

- Gems/ImGui/Code/Include/LYImGuiUtils/HistogramGroup.h
- Gems/ImGui/Code/Source/LYImGuiUtils/HistogramGroup.cpp
- Gems/ImGui/Code/imgui_lyutils_static_files.cmake
* Added a helper class for a group containing several histograms.
* The group is shown using collapsible header.
> ImGui: Added new histogram group helper

- Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerConstants.h
- Gems/Multiplayer/Code/Source/NetworkEntity/NetworkSpawnableLibrary.cpp
- Gems/Multiplayer/Code/Source/NetworkEntity/NetworkSpawnableLibrary.h
- Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp
- Gems/Multiplayer/Code/Tests/PrefabProcessingTests.cpp
Updating NetworkingSpawnableLibrary to only store network spawnables (on-disk and in-memory) instead of all spawnables.
Tested: Ran automated testing levels which require using network spawnables to properly function 
> Updating NetworkingSpawnableLibrary to Only Store Network Spawnables

- Code/Editor/EditorPreferencesDialog.cpp
- Code/Editor/EditorPreferencesDialog.h
Fixes issue introduced by a recent change to the Editor Preferences that would override key event handling to prevent the dialog from being closed when Enter is pressed on a text input. The old implementation would use sendEvent to propagate the keyPress to the parent, but in some circumstances that would result in an infinite loop.
I have changed the function to instead directly call QDialog::keyPressEvent for propagation. I verified this change prevents the infinite loop and crash when switching context with Alt+Tab or similar shortcuts.
> System shortcuts crash the Editor when Global Preferences are open

- Gems/AWSMetrics/Code/Source/AWSMetricsConstant.h
- Gems/AWSMetrics/Code/Source/AWSMetricsServiceApi.cpp
- Gems/AWSMetrics/Code/Source/AWSMetricsServiceApi.h
- Gems/AWSMetrics/Code/Source/MetricsManager.cpp
- Gems/AWSMetrics/Code/Source/MetricsManager.h
- Gems/AWSMetrics/Code/Tests/AWSMetricsServiceApiTest.cpp
- Gems/AWSMetrics/Code/Tests/MetricsManagerTest.cpp
- Gems/AWSMetrics/cdk/api_spec.json
- Verified that all unit tests passed
- Verified that AWSMetrics end-to-end tests passed with the updated CDK application deployment
- Verified that AWSMetrics end-to-end tests passed with the old CDK application deployment (Backward compatible)
> [AWSMetrics] Update the auto-generated code to follow O3DE coding standard

- Code/Framework/AzCore/AzCore/DOM/DomUtils.cpp
- Code/Framework/AzCore/AzCore/DOM/DomValue.cpp
- Code/Framework/AzCore/AzCore/DOM/DomValue.h
- Code/Framework/AzCore/Tests/DOM/DomFixtures.cpp
- Code/Framework/AzCore/Tests/DOM/DomFixtures.h
- Code/Framework/AzCore/Tests/DOM/DomJsonBenchmarks.cpp
- Code/Framework/AzCore/Tests/DOM/DomJsonTests.cpp
- Code/Framework/AzCore/Tests/DOM/DomValueBenchmarks.cpp
- Code/Framework/AzCore/Tests/DOM/DomValueTests.cpp
- Code/Framework/AzCore/Tests/azcoretests_files.cmake
- Refactor out a test fixture for all DOM tests / benchmarks
- Optimize `GetType` implementation to not use `AZStd::variant::visit` (benchmark included to A/B the implementations)
- Tag a few more mutating Value functions with "Mutable" to avoid astonishing copy-on-writes
- Fix `Value::Accept` when called with SSO payloads
- Make `Utils::DeepCompareIsEqual` key comparison order agnostic
Benchmark results for GetType implementation:
```
DomValueBenchmark/AzDomValueGetType_UsingVariantIndex              18.2 ns         18.0 ns     40727273 items_per_second=443.667M/s
DomValueBenchmark/AzDomValueGetType_UsingVariantVisit              32.2 ns         32.2 ns     21333333 items_per_second=248.242M/s
```
Signed-off-by: Nicholas Van Sickle <nvsickle@amazon.com>
> A bit of Generic DOM tidying/fixup

- Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugSystemComponent.cpp
Couple of missing `ImGui::End` in the multiplayer debug UI causing asserts.
Moved some already existing ones out of the functions as they need to be called even if the` ImGui::Begin` function is returning false, as per the documentation.
> Fix missing ImGui::End in multiplayer windows

- cmake/Version.cmake
Cherry pick changes to stabilization/2111RTE to allow setting the build number as part of a version by forcing a string check and allowing Jenkins to set LY_VERSION_BUILD_NUMBER (and in turn O3DEBuildNumber in engine.json) for installer builds. This is required for an installer build from this branch to have a build number appended to the version, for example 21.11.1.
> Cherry pick changes to 2111RTE for installer version build number

- Code/Tools/AssetBundler/Platform/Linux/source/utils/GUIApplicationManager_Linux.cpp
Resolves ' Linux: Asset Bundler File > Close leaves a blank window' #5299 by switching from using the option to disable custom window decorations to selecting option none in the AssetBundler GUIApplicationManager_Linux.cpp file.
OptionDisabled (as previous):
OptionNone (as updated in this PR):
Note the title bar change. This allows file -> close to work as lines 194 through 200 of WindowDecorationWrapper.cpp:
`applyFlagsAndAttributes();`
`guest->installEventFilter(this);`
`m_titleBar->setWindowTitleOverride(guest->windowTitle());`
`updateConstraints();`
are no longer skipped due to the if block at line 189:
`
if (m_options & OptionDisabled)
{
return;
}
`
> issue5299: Resolved via change to not disable custom window decorations.

- Templates/DefaultGem/Template/CMakeLists.txt
- Templates/DefaultGem/Template/Code/CMakeLists.txt
- Templates/MinimalProject/Template/Gem/CMakeLists.txt
- cmake/3rdParty.cmake
- cmake/3rdParty/BuiltInPackages.cmake
- cmake/Configurations.cmake
- cmake/Install.cmake
- cmake/LYTestWrappers.cmake
- cmake/LYWrappers.cmake
- cmake/PAL.cmake
- cmake/Packaging.cmake
- cmake/RuntimeDependencies.cmake
The new `o3de_pal_dir` function raise errors when configuring projects/gems.
Many CMake errors are raised, but all of them seems to originate from the `o3de_pal_dir` which is invoked with incorrect arguments:
```
[cmake] CMake Error at C:/Aliens_Group/Sparky_Studios/o3de-gems/SSBehaviorTree/Code/CMakeLists.txt:21 (o3de_pal_dir):
[cmake]   o3de_pal_dir Function invoked with incorrect arguments for function named:
[cmake]   o3de_pal_dir
[cmake] 
[cmake] 
[cmake] CMake Error at C:/Aliens_Group/Sparky_Studios/o3de-gems/SSBehaviorTree/Code/CMakeLists.txt:26 (include):
[cmake]   include could not find requested file:
[cmake] 
[cmake]     C:/Aliens_Group/Sparky_Studios/o3de-gems/SSBehaviorTree/Platform/Windows/PAL_windows.cmake
```
This commit applies a simple fix to pass the last three …
> Fix issues when configuring projects and gems

- scripts/build/Jenkins/Jenkinsfile
Jenkins nightly build has duplicated parameters and duplicates need to be removed.
> Remove duplicated Jenkins parameters

- Code/Framework/AzCore/AzCore/DOM/DomPath.cpp
- Code/Framework/AzCore/AzCore/DOM/DomPath.h
- Code/Framework/AzCore/AzCore/DOM/DomValue.cpp
- Code/Framework/AzCore/AzCore/DOM/DomValue.h
- Code/Framework/AzCore/AzCore/azcore_files.cmake
- Code/Framework/AzCore/Tests/DOM/DomPathBenchmarks.cpp
- Code/Framework/AzCore/Tests/DOM/DomPathTests.cpp
- Code/Framework/AzCore/Tests/azcoretests_files.cmake
This also adds Value support for doing a path-based lookup.
The serialized representation is presently compliant with the JSON-pointer spec but the implementation supports Node types and may be later expanded if we require additional functionality (e.g. XPath style conditional querying).
Signed-off-by: Nicholas Van Sickle <nvsickle@amazon.com>
> Add Dom::Path class for representing positions in a Dom

- Code/Editor/ViewportTitleDlg.cpp
- Code/Editor/ViewportTitleDlg.h
Note: Cherry-pick of https://github.com/o3de/o3de/pull/6700
Note: This is not a direct cherry-pick, this change adds the option to toggle 'Show Grid' but keeps the existing style and behavior for the title dialog drop-down
> Cherry-pick of PR-6700 - Updates to ViewportTitleDlg to better expose grid snapping visualization

- Code/Tools/AWSNativeSDKInit/CMakeLists.txt
The `AWSNativeSDKTestLibs` target is now only defined when tests are enabled
> [development] fixed configure error with monolithic builds

- Code/LauncherUnified/Launcher.cpp
The launcher will crash on exit due to an access violation when clearing the `BudgetTracker` after CrySystem is unloaded.  This is from a recent change to how the budget pointers are tracked making the `BudgetTracker` responsible for clearing them so the system can be re-entrant.  Unfortunately, an assumption was made that all modules that use `Budget`s are managed by the `ComponentApplication` so they can be cleared prior to being unloaded.  This is a patch to manually reset the `BudgetTracker` prior to unloading CrySystem until the legacy system can be removed (or converted to an AZ-like module).
> [development] patch fix for launcher exit crash

- Registry/gem_autoload.materialeditor.setreg
- Registry/gem_autoload.shadermanagementconsole.setreg
Script canvas and related gems were already being disabled for some atom tools. The script canvas developer gem was not added initially because it’s not used in automated testing or other common projects.
> Atom Tools: updating gem autoload settings registry for ME and SMC to disable script canvas developer gem

- Code/Tools/ProjectManager/Source/Application.cpp
- Code/Tools/ProjectManager/Source/PythonBindings.cpp
- scripts/o3de/o3de/manifest.py
The previous PR #6984 did not handle the case where an engine was registered but the `engine.json` file was removed or corrupt as is the case for issue #6798.
**Update**
I've pushed and tested a change so that if the other engine's `engine.json` file is missing - which is the case when uninstalled - or corrupt, we do not prompt the user.  We also force registration every time, to handle the case where the old engine.json file is corrupt.  
Prior to this fix, the following repro steps produced this error message on Project Manager start:
Repro steps:
1. Download https://o3debinaries.org/stabilization-2111RTE/Latest/Windows/o3de_installer.exe
1. Install in default location (C:/O3DE/0.0.0.0)
1. Uninstall it.
1. Install O3DE in a new location (D:/O3DE/0.0.0.0)
This fix addresses that issue so …
> Handle case where engine.json missing or corrupt

- Code/Framework/AzQtComponents/AzQtComponents/Components/Style.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/TableView.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/TableView.h
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/TableView.qss
- Code/Framework/AzQtComponents/AzQtComponents/Gallery/TableViewPage.cpp
Refactored the styling of TableView header sections so that they can be customized through qss. Previously, we were explicitly overriding the drawing of `CE_HeaderSection` in our proxy style instead of letting Qt handle it by default. But, we were only filling the rectangle with a color, which is essentially what the default implementation does as well. So instead, I removed the custom drawing code and instead moved our default color to our `TableView.qss`, which already has an entry for how `QHeaderView::section` are to be handled, but the color was being ignored.
This will allow the user to customize the styling of TableView headers, such as the background color. I have updated the control gallery table view page with an example of overriding with a transparent background color for the …
> Refactored the styling of TableView header sections

- AutomatedTesting/Gem/PythonTests/largeworlds/landscape_canvas/EditorScripts/AreaNodes_DependentComponentsAdded.py
- AutomatedTesting/Gem/PythonTests/largeworlds/landscape_canvas/TestSuite_Main_Optimized.py
- Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityContextBus.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityContextComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityContextComponent.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
Bug fix for #6573 .
Currently if prefab system enabled, `SandboxIntegrationManager::CreateNewEntityAtPosition` will not fire `EditorEntityContextNotification::OnEditorEntityCreated` notification, causing the error in automated tests while setting prefab system enabled flag to true.
The test mentioned in #6573 with the repro steps taken passed  after the fix applied.
Tested using the following command:
`python\python.cmd -m pytest AutomatedTesting\Gem\PythonTests\largeworlds\landscape_canvas\TestSuite_Periodic.py::TestAutomation::test_LandscapeCanvas_AreaNodes_DependentComponentsAdded --build-directory windows_vs2019\bin\profile`
> Fire OnEditorEntityCreated notification in SandboxIntegrationManager::CreateNewEntityAtPosition

- scripts/o3de/tests/unit_test_manifest.py
The manifest.py `get_all_templates` method was modified to add a call to
`get_all_gems` and `get_gem_templates`.
Those calls were not mocked, so they tried to load an o3de_manifest.json
file that was on user's machine, which failed on the CI node.
Also added a mock call for `load_o3de_manifest`, that validates that it
is not called to catch this issue during Automated Review.
Resolve failure in job https://jenkins.build.o3de.org/job/O3DE/job/development/1544/
> Updating mock calls in unit_test_manifest.py to fix test

- Code/Editor/CryEdit.cpp
- Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
This temporarily fixes the editor log debug message from stomping over its own log. The core of the issue will be separately investigated in a newly tracked issue. Also renames the editor logs when saving them so they don't stomp on each other.
> Temporary fix for editor log stomping during python tests

- Gems/Blast/Editor/Scripts/blast_asset_builder.py
- Gems/Blast/Editor/Scripts/blast_chunk_processor.py
- Gems/Blast/Editor/Scripts/bootstrap.py
Combining the original scene manifest with the new manifest to allow the OnPrepareForExport to execute
Renamed 'azlmbr.asset.entity' to 'azlmbr.entity' updated as well
Results in a .blast_chunks product asset now
> Combining the original scene manifest with the new manifest

- Gems/AudioEngineWwise/Code/Source/Engine/FileIOHandler_wwise.cpp
Fixed missing include in the `AudioEngineWwise` gem causing compile issue. (I'm guessing some of the recent red-coding efforts had removed an include that was pulling in `FileRequest`).
Built/ran Editor with project using audio and verified it still works.
> Fixed missing include compile issue

- Gems/EMotionFX/Code/EMotionFX/Source/Actor.cpp
Some models cause the engine to crash and exist when dragged into a scene. This resolves the issue.
> Model drag causes crash

- Code/Framework/AzCore/AzCore/Serialization/ObjectStream.cpp
- Code/Framework/AzCore/AzCore/Serialization/ObjectStream.h
- Code/Framework/AzCore/AzCore/Serialization/std/VariantReflection.inl
- Code/Framework/AzCore/Tests/Serialization.cpp
- Code/Framework/AzFramework/AzFramework/Asset/AssetBundleManifest.cpp
Posting @lumberyard-employee-dm fix for ObjectStreamWriteElementOverride always being expected to handle serialization.  There is now a return value enum which can direct the serializer to perform default serialization.
I've included unit tests for this new functionality.
This fixes an issue with AssetBundleManifest serialization where versions <= 2 would be written out by the override but versions newer than that were expected to be written using the default serialization but weren't, resulting in an empty manifest.
Fixes LYN-9039
> [LYN-9039] Object stream write response change

- Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityContextComponent.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/CMakeLists.txt
- Gems/ScriptCanvasDeveloper/Code/CMakeLists.txt
- Fix gcc error caused by implicit conversion of Qt::ByteArray to const char*
```
/home/ANT.AMAZON.COM/spham/github/o3de/Code/Framework/AzCore/./AzCore/std/string/string_view.h:618:13:   required by substitution of ‘template<class It, class End, class> constexpr AZStd::basic_string_view<char>::basic_string_view(It, End) [with It = QByteArray; End = int; <template-parameter-1-3> = <missing>]’
/home/ANT.AMAZON.COM/spham/github/o3de/Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityContextComponent.cpp:450:86:   required from here
/home/ANT.AMAZON.COM/spham/github/o3de/Code/Framework/AzCore/./AzCore/std/concepts/concepts.h:780:48: error: ‘QByteArray::operator QNoImplicitBoolCast() const’ is private within this context
780 |         && same_as<decltype(declval<const I>() - …
```
> Fix GCC Build Errors

- Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphInstance.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphMotionNode.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphTimeCondition.cpp
- Gems/EMotionFX/Code/MCore/Source/Random.h
This is a quick fix to use the rand() function instead of the seeded random generator on the motion node. This change avoid the copied anim graph instance to repeat the same sequences for picking the motions.
Later we should have a separate option for decide whether a graph should be deterministic or not and that probably should be a global network settings.
> Only use a deterministic random when network option is enabled.

- Code/Editor/TrackView/TrackViewDialog.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.h
Adds additional checks to ensure the operation fails (as you shouldn't be able to add entities to read-only entities/prefabs) but does it gracefully and without crashing.
> Editor crashes upon adding entity to Procedural Prefab via Landscape Canvas or Track View tools

- Code/Editor/EditorViewportWidget.cpp
Modified the `EditorViewportWidget` to disable its render pipeline until a level has been loaded to address some performance issues (e.g. Animation Editor getting < 30 FPS even with no level loaded).
Before:
- Idle no level loaded, EMFX ~28 FPS
- Rin loaded in EMFX < 5 FPS
After:
- Idle no level loaded, EMFX ~170 FPS
- in loaded in EMFX ~97 FPS
Also swapped `eNotify_OnEndSceneOpen` for `eNotify_OnEndLoad` since the latter is triggered after the former when a level is loaded, and allows the use of `GetIEditor()->IsLevelLoaded()` which is updated in between the two events being triggered.
Also part of this change, restores the previous gradient background when no level is loaded from before:
> Disable render pipeline for EditorViewportWidget until a level has been loaded

- Code/Framework/AzToolsFramework/AzToolsFramework/FocusMode/FocusModeInterface.h
- Code/Framework/AzToolsFramework/AzToolsFramework/FocusMode/FocusModeSystemComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/FocusMode/FocusModeSystemComponent.h
- Code/Framework/AzToolsFramework/Tests/FocusMode/EditorFocusModeTests.cpp
Introduces new function in the FocusMode API to retrieve a full list of entities that are in focus.
```
//! Returns a list of the ids of all the entities that are descendants of the focus root.
virtual EntityIdList GetFocusedEntities(AzFramework::EntityContextId entityContextId) = 0;
```
The list is cached to make it possible for multiple customers to use it without additional overhead.
The handler will do its best to update the list when something changes in the editor, but on propagation we have no guarantee about the state of the scene so we have to just recreate the list from scratch.
Also adds 4 new unit tests to ensure the list is correct on regular use and after entities are added/removed
```
[ RUN      ] EditorFocusModeFixture.GetFocusedEntitiesBase
[       OK ] …
```
> Focus Mode - Introduce API to return a list of EntityIds for all entities in the focused subtree

- scripts/build/Jenkins/Jenkinsfile
Resolves https://github.com/o3de/o3de/issues/7175 by checking for the existence of the ebs_snapshot file before attempting to stash it.
> EBS snapshot Jenkinsfile fix

- Code/Framework/AzCore/AzCore/std/containers/span.h
- Code/Framework/AzCore/AzCore/std/containers/span.inl
- Code/Framework/AzFramework/Tests/AssetCatalog.cpp
The recent addition of `AZStd::span` and `AZStd::byte` types seem to have broken VS 2019 16.11.8 builds due to symbol leakage when using unity files.  The following error would be produced during the building of the AzFramework.Tests target
```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\rpcndr.h(192,14): error C2872: 'byte': ambiguous symbol [D:\git\o3de\engine\build\windowsUnityPix\Code\Framework\AzFramework
\AzFramework.Tests.vcxproj]
typedef byte cs_byte;
^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\rpcndr.h(191,23): note: could be 'unsigned char byte'
typedef unsigned char byte;
^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\cstddef(29,12): note: or       'std::byte'
enum class byte : …
```
> [development] fixed ambiguous 'byte' type MSVC build error

- Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabBehaviorTests.cpp
- Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.cpp
On my Linux machine, the full path to O3DE has a subdirectory that has a '.' in it. (i.e. /home/s.pham/github/o3de for example). In these situations, UpdateManifest call for the PrefabGroupBehavior is attempting to derive a filename based on the full path. In order to get the relative path, it substitutes out the watch folder. But the substitution happens after the attempted substitution of the '.' for the file extension, so the intermediate original full path will be substituted too. In that scenario, it will not be able to substitute out the watch folder since it wont match, resulting in the 'relativeSourcePath' being the (incorrect) absolute path.
The fix is simply to move the '.' extension substitution AFTER the watch folder substitution. Long term, this should be use the AZCore Path …
> Fix failing scene compilations on Linux

- Gems/Terrain/Assets/Shaders/Terrain/TerrainDetailHelpers.azsli
- Gems/Terrain/Assets/Shaders/Terrain/TerrainPBR_ForwardPass.azsl
- Gems/Terrain/Assets/Shaders/Terrain/TerrainSrg.azsli
- Gems/Terrain/Code/Source/TerrainRenderer/ClipmapBounds.h
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.h
This results in a lot of code removal and some simplifications for the shader. Note to reviewers: `UpdateDetailTexture()` contains mostly code removals and only a few changes, but github sees it as mostly changes. It may be easier to review in an external diff tool.
See https://github.com/o3de/o3de/pull/7134 for related review.
> TerrainDetailMaterialManager to use ClipmapBounds for its detail mateiral id texture.

- Code/Framework/AzCore/AzCore/Debug/Profiler.h
- Code/Framework/AzCore/AzCore/Debug/Profiler.inl
- Gems/Profiler/Code/Source/CpuProfilerImpl.cpp
- Gems/Profiler/Code/Source/CpuProfilerImpl.h
Unlike the #7098 draft, this change is only updating the Profiler interface to forward the format string arguments.  Changes to the Profiler gem to utilize the format string arguments will come later.
> [development] updated Profiler interface to allow the forwarding of format string arguments

- Gems/Blast/Editor/Scripts/blast_chunk_processor.py
{lyn5525} fixing the chunk mesh group logic for the Blast gem
fixing the chunk mesh group logic for the Blast gem so that the chunks are defined both as a selected mesh node and unselect all the rest of the mesh nodes
> {lyn5525} fixing the chunk mesh group logic for the Blast gem

- AutomatedTesting/Levels/Multiplayer/AutoComponent_RPC/AutoComponent_RPC_NetLevelEntity.scriptcanvas
Replaced an outdated script node inside _AutoComponent_RPC_NetLevelEntity.scriptcanvas_ 
Tested by seeing that AssetProcessor.exe completed processing the graph successfully and the test ran without problems.
> Multiplayer Test Script: Replacing an Out-Dated Script Node

- Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
Function Culling.cpp::ProcessWorklist has a couple of variables which is unused when compiling a profile causing
a -Werror compile error. Fix is to move variables and code increment them under debugging ifdef.
NOTE: I did not test the code since there was another unused variable error. However, variables are local to the function so this change should not cause any problems.
Signed-off-by: Jackerty <contact.jackerty@gmail.com>
> Moves Culling.cpp::ProcessWorklist debug variables under preprocessing

- Code/Legacy/CryCommon/WinBase.cpp
- Code/Legacy/CryCommon/platform.h
- Code/Legacy/CryCommon/platform_impl.cpp
- Code/Legacy/CrySystem/XML/xml.cpp
Remove legacy function 'CrySetFileAttributes' and replace its only use with AZ::IO::SystemFile::* functions
**note** 
This replicates the original call to ```CrySetFileAttributes``` in ```CXmlNode::saveToFile``` by using AzCore functions, but does not fix the underlying flaw of this function. ```CXmlNode::saveToFile``` was relying on ```CrySetFileAttributes``` to make sure the file is writeable, and it wend directly to the OS (Windows) SetFileAttributes call, but the actual write uses the FileIOBase::Instance(), which is a layer above the final file system that can also handle aliases like ```@user```.  So the original logic will always silently fail on 'SetFileAttributes' on the xml files that it is writing to anyways because they mostly used aliases in the path, not actual paths. …
> Remove legacy 'CrySetFileAttributes'

- Code/Editor/EditorViewportWidget.cpp
Fixes #7285 
Fixed issue with the viewport not rendering after creating a new level. A performance fix was done recently to not enable the viewports render pipeline until a level has been loaded. The event being listened for `eNotify_OnEndLoad` is only sent when an existing level is loaded, not when a new one is created. So needed to add an extra case to listen for the event when a new level has been created.
> Fixed issue with viewport not rendering when creating a new level

- Gems/Atom/RPI/Code/Source/RPI.Public/RPIUtils.cpp
Implemented the component indexing of the `GetSubImagePixelValues` API. Also expanded support for additional formats, and improved the error logging when attempting to query an unsupported pixel format.
> Extended sub image pixel API to support component indexing.

- Code/Framework/AzCore/Platform/Android/AzCore/std/parallel/internal/thread_Android.cpp
- Code/Framework/AzCore/Platform/Common/Apple/AzCore/std/parallel/internal/thread_Apple.cpp
- Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/std/parallel/internal/thread_UnixLike.cpp
- Code/Framework/AzCore/Platform/Linux/AzCore/std/parallel/internal/thread_Linux.cpp
This change avoids AZStd threads being prevented from using 100% of a core
PAL-ified default thread priority for pthread platforms.
Fix threads not getting named on Apple platforms by setting the thread name ptr on the thread_info struct.
> Update default AZStd thread priority on Apple platforms.

- cmake/Platform/Common/GCC/Configurations_gcc.cmake
- Reordered warning flags
- Removed unnecessary ignore warning flags
-Wno-format-security
-Wno-multichar
-Wno-tautological-compare
-Wno-unknown-pragmas
-Wno-unused-function
-Wno-enum-compare
-Wno-invalid-offsetof
> Reorder and Remove unnecessary GCC ignore warning flags

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabUiHandler.cpp
Fixes small issue that would result in a lot of warnings being printed out to the VS output.
> Prefabs UX | Fixes issue with painters being saved and not restored

- Gems/Terrain/Code/Source/TerrainRaycast/TerrainRaycastContext.cpp
- Gems/Terrain/Code/Tests/TerrainSystemBenchmarks.cpp
Terrain ray cast benchmarks and optimization:
- Added some benchmarks that exercise terrain ray casting.
- Optimized terrain ray casting by removing an unnecessary AABB intersection check (this was suggested by @invertednormal in the original review, but I forgot to actually remove it until now).
- Fixed a bug where we were not normalizing the ray direction before performing the Moller-Trumbore ray<->triangle intersection calculations.
> Terrain ray cast benchmarks and optimization.

- scripts/build/Jenkins/Jenkinsfile
Fixes https://github.com/o3de/o3de/issues/7165 
Resolves an issue where the pipeline can stall for hours if it fails outside of a build step or while waiting for an available build resource. This timeout at the pipeline level will abort the run if there is inactivity for 1 hour. Activity in any of the pipeline stages will reset it. 
The timeout value is set within the Jenkinsfile since it is applied before any configs are loaded. 
Tested in a branch and the pipeline successfully aborted while it stalled waiting for an available resource and no other pipeline activity for 1 hour.
> Add overall timeout for the AR pipeline

- Code/Editor/Core/LevelEditorMenuHandler.cpp
- Code/Editor/CryEdit.cpp
- Code/Editor/CryEditDoc.cpp
- Code/Editor/GameEngine.cpp
- Code/Editor/GameExporter.cpp
- Code/Editor/GameExporter.h
- Code/Editor/MainWindow.cpp
- Code/Framework/AzFramework/AzFramework/API/ApplicationAPI.h
- Code/Framework/AzFramework/AzFramework/Application/Application.cpp
- Code/Framework/AzFramework/AzFramework/Archive/Archive.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBundle/AssetBundleComponent.cpp
- Code/Legacy/CrySystem/LevelSystem/LevelSystem.cpp
- Code/Legacy/CrySystem/SystemInit.cpp
- Gems/GameStateSamples/Code/Include/GameStateSamples/GameStateMainMenu.inl
- Gems/ImGui/Code/Source/LYCommonMenu/ImGuiLYCommonMenu.cpp
- Gems/LmbrCentral/Code/Source/Builders/LevelBuilder/LevelBuilderComponent.cpp
Currently there are 2 calls 'IsPrefabSystemEnabled' and 'IsPrefabSystemForLevelsEnabled' that read the same settings registry value. The second call was added in expectations of a diverging effort for conversion of slice levels to prefabs. But that did not turn out to be the case and the 2 calls just add more confusion to developers on which to use. So, deprecated the later in favor of 1 call that can be used everywhere.
> Deprecate IsPrefabSystemForLevelsEnabled and use IsPrefabSystemEnabled everywhere

- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderOptionGroupLayout.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderOptionTypes.h
- Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderOptionGroupLayout.cpp
- Gems/Atom/RPI/Code/Tests/Material/LuaMaterialFunctorTests.cpp
- Gems/Atom/RPI/Code/Tests/Material/MaterialFunctorTests.cpp
- Gems/Atom/RPI/Code/Tests/Material/MaterialTests.cpp
- Gems/Atom/RPI/Code/Tests/Material/MaterialTypeAssetTests.cpp
- Gems/Atom/RPI/Code/Tests/Material/MaterialTypeSourceDataTests.cpp
- Gems/Atom/RPI/Code/Tests/Shader/ShaderTests.cpp
Added new utility functions for easily creating the value set for a ShaderOptionDescriptor.
Made ShaderOptionDescriptor default value optional, picking the first available value as the default ... by default.
> Minor cleanup of some shader option related unit tests.

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Application/AtomToolsApplication.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocument.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentRequestBus.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicProperty/DynamicProperty.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocument.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRendererCaptureState.h
- Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.h
- Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportComponent.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialInspector/MaterialInspector.h
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/ViewportSettingsInspector/ViewportSettingsInspector.h
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.cpp
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.h
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocumentRequestBus.h
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleApplication.cpp
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.cpp
• Moved all of the common save and load code to the document base class
• Moved undo and redo support to document base class but will probably extract to its own class or replace with one from AzTF
• Streamlined material editor, shader management console, and other tools with updated document code
• Cleaned up some of shader management console loading code, added support for saving, as well as getting and setting the shader variant list source data structure
> Atom Tools: move boilerplate document management code to atom tools framework

- Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/DepthOfFieldWriteFocusDepthFromGpu.shader
- Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/DeviceFeatures.h
- Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/PhysicalDeviceDescriptor.h
- Gems/Atom/RHI/Code/Include/Atom/RHI/PipelineLibrary.h
- Gems/Atom/RHI/Code/Include/Atom/RHI/PipelineStateCache.h
- Gems/Atom/RHI/Code/Source/RHI/PipelineLibrary.cpp
- Gems/Atom/RHI/Code/Source/RHI/PipelineStateCache.cpp
- Gems/Atom/RHI/Code/Tests/PipelineState.h
- Gems/Atom/RHI/Code/Tests/PipelineStateTests.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI/PipelineLibrary.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI/PipelineLibrary.h
- Gems/Atom/RHI/Metal/Code/Source/Platform/iOS/RHI/Metal_RHI_iOS.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/Device.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/PhysicalDevice.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/PhysicalDevice.h
- Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineLibrary.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineLibrary.h
- Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineState.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineState.h
- Gems/Atom/RHI/Null/Code/Source/RHI/PipelineLibrary.h
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/PipelineLibrary.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/PipelineLibrary.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Shader/Shader.cpp
- Gems/Atom/RPI/Code/Tests/Common/RHI/Stubs.h
- API changes to handle Metal drivers implictly doing save/load of PipelineLibrary data
- Fixed up code related to Metal device selection
- PipelineLibrary support for Mac and ios
> Metal pso caching support via MTLBinaryArchive

- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/RenderPipeline.cpp
Pipeline used to enable/disable it's pipeline pass, which would recursively enable/disable all sub-passes in that tree. Adding new control mechanism so pipelines don't have to enable/disable passes (which can happen on a per frame basis in certain tools).
> Changed how pass system controls pipeline tick rate

- Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/GSI.preset
- Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/GSI16.preset
- Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/GSI32.preset
- Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/GSI8.preset
- Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/ImageBuilder.settings
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/PresetSettings.cpp
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/PresetSettings.h
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvert.cpp
Added preset config for converting gradient signal images (GSI) to the expected pixel format.
Currently, there is a separate builder process to produce single channel, uncompressed formats for images ending in the "_gsi" suffix, but this goes to a custom asset data `ImageAsset`. Instead of having a separate asset type, we want to utilize the standard `StreamingImageAsset` for image gradients. In order for this to happen. We needed to be able to convert the input image to an uncompressed format with matching bit depth and number of channels. The existing preset configs only allowed you to specify a single destination pixel format, so I've added a new enum, `OutputTypeHandling`. The default will still choose the single output format based on the preset. There is an additional value which …
> Added preset for converting gsi images

- Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabBehaviorTests.cpp
- Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.cpp
- Gems/SceneProcessing/Code/Source/Generation/Components/MeshOptimizer/MeshOptimizerComponent.cpp
- Gems/SceneProcessing/Code/Source/SceneBuilder/SceneBuilderWorker.cpp
- Gems/SceneProcessing/Code/Tests/MeshBuilder/MeshOptimizerComponentTests.cpp
Fixes required to get all of the source scene asset (i.e. FBX) files to process cleaning via the Asset Processor.
Unique naming, adding transforms, blank LOD rules, and so much more!
> {lyn9996} fixes for the default procedural prefab

- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabFocus/PrefabFocusTests.cpp
- Adds two unit tests for the FocusOnParentOfFocusedPrefab API function;
- Rename all tests to comply with GoogleTest guidelines (removing underscores).
- Re-enabled two tests (FocusOnOwningPrefabRootContainer and  FocusOnOwningPrefabRootEntity)
These were disabled due to the fixture not supporting the PrefabEOS correctly, but that has been fixed in #7304
> Focus Mode | Add unit tests for FocusOnParentOfFocusedPrefab

- cmake/Platform/Android/Toolchain_android.cmake
There was an issue in CMake where it set the
CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH cache variable to OFF only when
configuring for Android
https://gitlab.kitware.com/cmake/cmake/-/issues/22634
This caused the find_program calls in o3de cmake files to fail.
Such as the call to located the "aws" binary in
cmake/LYPackage_S3Downloader.cmake
> Fix find_program not finding host platform programs when using Android

- cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake
- cmake/3rdParty/Platform/Mac/BuiltInPackages_mac.cmake
- cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
Verified that the package can be downloaded successfully on Windows, Linux and Mac.
> Update O3DE to use new version of AWS IoT Device SDK

- Gems/EditorPythonBindings/Code/Source/PythonSystemComponent.cpp
Fixing Python PYI symbols on Editor start by processing the queue symbols
after the "azlmbr import" step since that is what queues the symbols
> {ghi7403} fixing Python PYI symbols on Editor start

- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/material_editor_utils.py
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocument.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentNotificationBus.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentRequestBus.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentSystemRequestBus.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicProperty/DynamicProperty.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicProperty/DynamicPropertyGroup.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocument.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicProperty/DynamicProperty.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicProperty/DynamicPropertyGroup.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.h
- Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocumentRequestBus.h
- Gems/Atom/Tools/MaterialEditor/Code/Source/MaterialEditorApplication.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialInspector/MaterialInspector.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialInspector/MaterialInspector.h
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.cpp
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.h
• This removes a direct dependency on dynamic property groups and data from the document system.
• Added support for names, descriptions, and nesting to dynamic property groups.
• Moved property related functions from base document classes into material editor document classes because dynamic property groups are an implementation detail of the material editor document to support material type flexible data format.
• Change material document to use a table of dynamic property groups instead of a map of properties.
• Added functions to traverse groups and properties.
• This keeps groups and properties organized consistently with the material type file as well as what’s expected in the UI.
• Document data can now be maps directly to the inspector reflective property editors instead of …
> Atom Tools: Document system exposes reflected object data

- Gems/Atom/Feature/Common/Code/Source/Material/Transform2DFunctor.cpp
- Gems/Atom/Feature/Common/Code/Source/Material/Transform2DFunctor.h
- Gems/Atom/Feature/Common/Code/Source/Material/Transform2DFunctorSourceData.cpp
- Gems/Atom/Feature/Common/Code/Source/Material/Transform2DFunctorSourceData.h
- Gems/Atom/Utils/Code/Include/Atom/Utils/MaterialUtils.h
- Gems/Atom/Utils/Code/Source/MaterialUtils.cpp
- Gems/Atom/Utils/Code/atom_utils_files.cmake
- Gems/Terrain/Assets/Shaders/Terrain/TerrainDetailHelpers.azsli
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.h
This adds support for uv transforms in terrain detail materials. To support this work, the code for generating a matrix from material properties was pulled out of the material functor and put into a new MaterialUtils file in Atom Utils.
Currently the shader is having to manually calculate the ddx/ddy of the transformed uv everywhere, which should only be necessary on seams. It may be possible to use wave intrinsics to only take the expensive path when necessary, but we'd need to upgrade our dxc to support this because of a bug o3de's currently used version. Even with that fixed locally I wasn't able to find a solution that worked - I could detect the seams correctly, but the code that would typically fix seams no longer worked when applied only to the seams.
Example detail texture with …
> Calculating uv transforms for terrain detail materials

- scripts/o3de/o3de/utils.py
Currently this is unhandled so Project Manager also does not show a useful error message.
> Catch URLError so that a message can be printed.

- Gems/Atom/Feature/Common/Assets/Passes/SsaoCompute.pass
removing compute queue flag from SSAO since some people are reporting crashes in the RHI
> removing compute queue flag from SSAO 

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
Fixes issue in nightly builds
```
[2022-02-04T08:06:01.127Z] In file included from /Users/lybuilder/workspace/o3de/build/mac/Code/Framework/AzToolsFramework/CMakeFiles/AzToolsFramework.dir/Unity/unity_31_cxx.cxx:3:
[2022-02-04T08:06:01.127Z] /Users/lybuilder/workspace/o3de/Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp:225:46: error: no viable conversion from 'optional<reference_wrapper<AzToolsFramework::Prefab::Instance>>' to 'const optional<reference_wrapper<const AzToolsFramework::Prefab::Instance>>'
[2022-02-04T08:06:01.127Z]         const InstanceOptionalConstReference previousFocusedInstance = GetInstanceReference(previousContainerRootAliasPath);
[2022-02-04T08:06:01.127Z]                                              ^ …
```
> Fix compilation error in converting between InstanceOptionalReference and InstanceOptionalConstReference

- AutomatedTesting/Gem/PythonTests/assetpipeline/ap_fixtures/bundler_batch_setup_fixture.py
Longer term we'll want to refactor these tests so they don't start failing to seemingly unrelated upstream changes, but for now this buys us time to work on other, more important things.
What happened to cause this:
The test_WindowsAndMac_BundlesAndBundleSettings_EquivalentOutput test bundles the same content in two different ways, with the final intention to compare and verify the results are the same.
It's bundling up the level levels\testdependencieslevel\testdependencieslevel.spawnable
Along the way, it verifies the bundles it gets are what it expects. One of the bundle settings it uses is a relatively small maximum bundle size of 5 mib.
Note that when we use a maximum bundle size, it's not a hard limit, it's just when we go to create a new bundle, if the current bundle size + next …
> Update default bundle size limit to fit slightly larger content.

- Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.cpp
Fixes #7456.
Clearing the parent entity from the transform is now focus-aware and won't force a prefab instance reparent.
Note that this code includes the use case it replaces - when the level is focused, the level container id is returned just like before.
> Undoing the Unparent action on an entity inside the Prefab crashes the Editor

- Gems/Atom/RHI/Code/Tests/PipelineState.h
> PipelineState build fix for non-unity builds

- AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Main_Optimized.py
- AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Periodic.py
- AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_AddColliderComponent.py
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp
Related to #7431, #2532 .
Remove the error message for now based on @AMZN-koppersr 's comment on an bug ticket:
> As this seems to be down to the fact it's valid to have assets that are not set, the best way forward is to just remove those three error messages. Long term it would be good though to have a way to indicate whether or not an asset is mandatory or optional. 
Tested with the following commands:
`python\python.cmd -m pytest AutomatedTesting\Gem\PythonTests\Physics\TestSuite_Main_Optimized.py::TestAutomationWithPrefabSystemEnabled --build-directory windows_vs2019\bin\profile`
`python\python.cmd -m pytest AutomatedTesting\Gem\PythonTests\Physics\TestSuite_Periodic.py::TestAutomation::test_Collider_AddColliderComponent --build-directory windows_vs2019\bin\profile`
Signed-off-by: …
> Remove error message from InMemorySpawnableAssetContainer

- Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.cpp
````
PrefabGroupBehavior.cpp:156:29: error: loop variable 'meshIndex' of type 'const AZ::SceneAPI::Containers::SceneGraph::NodeIndex' creates a copy from type 'const AZ::SceneAPI::Containers::SceneGraph::NodeIndex' [-Werror,-Wrange-loop-analysis]
for( const auto meshIndex : meshIndexContainer)
^
PrefabGroupBehavior.cpp:156:18: note: use reference type 'const AZ::SceneAPI::Containers::SceneGraph::NodeIndex &' to prevent copying
for( const auto meshIndex : meshIndexContainer)
^~~~~~~~~~~~~~~~~~~~~~
&
````
> Fixed range-loop-analysis warning reported as error on mac/ios

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Sandbox.py
- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_Atom_LevelLoadTest_Sandbox.py
- The Sponza level is causing a hard lock 4%-12% of the time when it is run as a level test.
- This should resolve the issue in https://github.com/o3de/o3de/issues/7486
- A proper fix will be done in the future (test moved to sandbox for now).
- Better logging will be added in the future to make debugging easier (it took far too long).
> Sandbox "Sponza" level from AtomLevelLoadTest_Editor tests.

- Gems/GradientSignal/Code/Source/Editor/EditorGradientSurfaceDataComponent.cpp
When duplicating an entity with a Gradient SurfaceData Component, it's possible to get a hang/crash due to a race condition between entity deactivation and the gradient preview job refresh. This change ensures that the preview job is canceled on deactivation.
Closes #7525 .
> Fix race condition crash with the gradient preview.

- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPIUtils.h
- Gems/Atom/RPI/Code/Source/RPI.Public/RPIUtils.cpp
- Gems/GradientSignal/Code/Include/GradientSignal/Components/ImageGradientComponent.h
- Gems/GradientSignal/Code/Include/GradientSignal/ImageAsset.h
- Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
- Gems/GradientSignal/Code/Source/ImageAsset.cpp
In the original change of the `ImageGradient` to use a `StreamingImageAsset` instead of the custom `GradientSignal::ImageAsset`, the GetValue(s) benchmarks performance degraded. This is because previously the `GradientSignal::ImageAsset` owned the raw byte data itself, as opposed to the `StreamingImageAsset` which has to go through the mip chain to retrieve the actual sub-image data. To optimize the performance, I've updated the `ImageGradient` to cache the raw image data once the asset has been loaded. This uses a new companion API that retrieves pixel values directly from a vector of bytes instead of passing a `StreamingImageAsset`.
GradientSignal ImageGradient benchmarks before change:
```
GradientGetValues/BM_ImageGradient/EbusGetValue:0/size:1024                      58.1 ms …
```
> Improved image gradient GetValue(s) performance by using cached image data

- Gems/Atom/Asset/Shader/Code/Source/Editor/AzslShaderBuilderSystemComponent.cpp
- Gems/Atom/RHI/Code/Include/Atom/RHI/RHIUtils.h
- Gems/Atom/RHI/Code/Source/RHI/RHIUtils.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI.Builders/ShaderPlatformInterface.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI.Builders/ShaderPlatformInterface.cpp
When `"Atom": {"GraphicsDevMode": true}` is found in a `.setreg` file,
PDBs for all shaders will be emitted to their corresponding output
locations. This allows global PDB generation without needing to
explicitly modify each `.shader` file to include the `GenerateDebugInfo`
compilation option.
Signed-off-by: Jeremy Ong <jcong@amazon.com>
> Introduce Atom/GraphicsDevMode settings registry key

- cmake/Platform/Common/Clang/Configurations_clang.cmake
- cmake/Platform/Common/GCC/Configurations_gcc.cmake
The _FORTIFY_SOURCE option must be used with the -O optimization flag.
> Linux Clang unoptimized build fix.

- Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp
Added cvar bg_AssertNetBindOnDeactrivationWithoutMarkForRemoval to Multiplayer::NetBindComponent.
This solves the issue of MultiplayerSample-like project launcher hanging in the background due a deadlock when writing AZ_Assert during on application shutdown.
Created #7584  to follow up on.
> Disabling problematic NetBindComponent assert with a configuration

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetPicker/AssetPickerDialog.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetPicker/AssetPickerDialog.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.hxx
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPIUtils.h
- Gems/Atom/RPI/Code/Source/RPI.Public/RPIUtils.cpp
- Gems/GradientSignal/Code/CMakeLists.txt
- Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
- Gems/GradientSignal/Code/Source/Editor/EditorStreamingImageAssetCtrl.cpp
- Gems/GradientSignal/Code/Source/Editor/EditorStreamingImageAssetCtrl.h
- Gems/GradientSignal/Code/Source/GradientSignalEditorModule.cpp
- Gems/GradientSignal/Code/gradientsignal_editor_files.cmake
Our Image Gradient component now uses a `AZ::RPI::StreamingImageAsset` for its image asset. But, only a subset of the total pixel formats for `AZ::RPI::StreamingImageAsset` are supported by the pixel retrieval API that the Image Gradient uses. So, the Image Gradient component now uses a custom asset property controller that behaves like the default asset property controller, with the exception that it prevents the user from selecting an asset that has a pixel format that isn't supported by the pixel retrieval API. To do this, the "OK" button on the picker is disabled for incompatible formats.
Tested and verified that other streaming image assets still use the default asset property controller. Also fixed a logic bug in the default asset picker where the "OK" button was always disabled …
> Only allow streaming image assets with supported pixel formats to be selected for an image gradient

- Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderWorker.cpp
The version of Lua has updated - script canvas needs to rebuild
all of the scriptcanvas files with the new lua version.
Fixes #7591 
This adds the lua interpreter version into the fingerprint of all scriptcanvas jobs
which will cause them to rebuild next time you start Asset Processor.
> Making scriptcanvas files rebuild due to new Lua version

- Gems/GradientSignal/Code/CMakeLists.txt
- Gems/SurfaceData/Code/CMakeLists.txt
The benchmark builds weren't building the dependent DLLs due to missing dependencies in the cmake files.
> Fix benchmark run crashes.

- cmake/Platform/Windows/Packaging/PostInstallSetup.wxs
- cmake/Platform/Windows/Packaging/Template.wxs.in
- scripts/o3de/o3de/register.py
Add logic to WiX script that calls
```
scripts/o3de.bat register --remove --this-engine
```
on uninstall and fixed two issues with unregistering the engine found along the way
1. engine was not removed from engine_paths because the engine root was passed in and validation expects `engine.json`
2. the `--this-engine` command does not pass the `args.remove` option for removal and I wanted to avoid any potential problems by passing in a path from WiX
*Testing*
- Tested the script command first to verify the register and unregister was working
- Created an installer and verified after installing it added the engine to o3de_manifest.json and after uninstalling the engine was removed from o3de_manifest.json
- Verified the script was run in the installer logs
```
MSI (s) (FC:1C) [10:29:18:310]: …
```
> Unregister engine on uninstall

- cmake/Platform/Linux/Configurations_linux.cmake
For some reason, adding the '-pie' to the exe link flags causes executables to not launch by double clicking it.  (This flag was introduced as part of https://github.com/o3de/o3de/pull/7358 
> Fix Clang built executables so they can be launched from the file explorer

- Code/Editor/Core/QtEditorApplication.cpp
- Code/Editor/Core/QtEditorApplication.h
Previously, with no level loaded in the main editor, and no assets loaded
in the EMotionFX editor, the AnimGraph viewport would only update at 15fps,
even on a 64 core machine.
Digging into this with Pix, I found that EMotionFX's UI would only get
updated for every other call to the ComponentApplication tick.
The Editor's QApplication instance controls how the
`ComponentApplication::OnTick` method is called. This is done in the
`maybeProcessIdle()` method. Generally, I found callstacks like this:
```
EditorQtApplication::maybeProcessIdle()
CCryEditApp::OnIdle()
CCryEditApp::IdleProcessing()
CGameEngine::Update()                  # ~2.2ms
PhysX::Update()                      # ~1.8ms
EMotionFX::Update()                  # ~0.2ms
calls QWidget::update() on all the widgets that change per …
```
> Improve the framerate of Editor widgets that update their UI based on the TickBus

- Code/Framework/AzCore/AzCore/Memory/HphaSchema.cpp
Updated the HpAllocator::bucket to align upwards to the nearest power of 2.
> MacOS build fix

- Code/LauncherUnified/launcher_generator.cmake
Fixes #7623
See an example of the use here:  https://github.com/o3de/o3de-multiplayersample/pull/113
Tested using the above CR as well. See details in there.
So that one can do the following:
Signed-off-by: AMZN-Olex <5432499+AMZN-Olex@users.noreply.github.com>
> Adds support for additional VS debugger args

- Code/Framework/AzCore/AzCore/Memory/HphaSchema.cpp
- Code/Framework/AzCore/AzCore/Memory/HphaSchema.h
Added a static assert in the HphaSchema.cpp file to validate that the
HpAllocator aligned storage buffer is at least the size of the
HpAllocator class.
> Mac Runtime Fix: Up the hard coded size for the HpAllocator buffer to 18KiB

- Gems/Atom/RHI/Vulkan/Code/CMakeLists.txt
- Gems/Atom/RHI/Vulkan/Code/Source/Platform/Windows/PAL_windows.cmake
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Instance.cpp
- cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
Enabling device validation will automatically load the VkLayer_khronos_validation.dll ensuring that validation checks will work correctly
> Add 3p vulkan validation layer support. 

- Code/Framework/AzTest/AzTest/GemTestEnvironment.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalTestFixtures.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalTestFixtures.h
The Gradient Signal Gem was failing to run its unit tests with gtest_repeat. This contains two fixes:
1. GemTestEnvironment was allocating m_parameters in the constructor, but deallocating in TeardownEnvironment, causing it to be invalid on a second run. This is moved to SetupEnvironment for balanced usage.
2. EBus usage that first occurs in a DLL creates a global context that gets destroyed when the DLL is unloaded, and never gets recreated again. The workaround is to force those EBuses to create their context in the main test DLL instead of a dependent one.
> gtest_repeat crashes

- Code/Framework/AzCore/AzCore/Serialization/Json/JsonSystemComponent.cpp
- Code/Framework/AzCore/AzCore/Serialization/Json/RegistrationContext.h
- Code/Framework/AzCore/AzCore/Settings/ConfigurableStack.cpp
- Code/Framework/AzCore/AzCore/Settings/ConfigurableStack.h
- Code/Framework/AzCore/AzCore/Settings/ConfigurableStack.inl
- Code/Framework/AzCore/AzCore/azcore_files.cmake
- Code/Framework/AzCore/Tests/Settings/ConfigurableStackTests.cpp
- Code/Framework/AzCore/Tests/azcoretests_files.cmake
The ConfigurableStack makes configuring stacks and arrays through the Settings Registry easier than using direct serialization to a container like AZStd::vector. It does this by using JSON Objects rather than JSON arrays, although arrays are supported for backwards compatibility. Two key words were added:
- $stack_before : Insert the new entry before the referenced entry. Referencing is done by name.
- $stack_after  : Insert the new entry after the referenced entry. Referencing is done by name.
to allow inserting new entries at specific locations. An example of a .setreg file at updates existing settings would be:
```
// Original settings
{
"Settings in a stack":
{
"AnOriginalEntry":
{
"MyValue": "hello",
"ExampleValue": 84
},
"TheSecondEntry":
{
"MyValue": "world"
}
}
}
// Customized …
```
> Improved the way the Settings Registry can handle stacks/arrays.

- Gems/GradientSignal/Code/Source/Editor/EditorGradientSurfaceDataComponent.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalReferencesTests.cpp
- Gems/SurfaceData/Code/Source/SurfacePointList.cpp
The problem is that SurfacePoint doesn't have default values when constructed, and a few of the unit tests weren't setting m_position because the values weren't strictly needed for the test. However, the SurfacePointList checks them for validity and asserted when they couldn't be found, which was hit-and-miss due to it being uninitialized memory that was usually but not always 0xCCCCCCCC.
Improved the assert message and set the position values everywhere.
> Fixed intermittent unit test failures.

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MotionEventPresetManager.cpp
The motion events in the timeview had the wrong colors assigned as they weren't correctly mapped to the given event presets.
Resolves #5989
> Animation Editor: Motion event colors aren't in sync with the event presets

- Code/Framework/AzCore/AzCore/std/ranges/ranges_adaptor.h
- Code/Framework/AzCore/AzCore/std/string/string_view.h
GCC doesn't accept accessing member variables inside the noexcept expression of a member function.
Second GCC requires that template specializations for an inner template be outside of all classes.
> GCC Build fix.

- Code/Editor/LogFile_mac.mm
- Gems/Microphone/Code/Source/Platform/Mac/MicrophoneSystemComponent_Mac.mm
Targeting macOS 12.x fails to compile due to some named constants being deprecated and replaced
> [development] fixes for targeting macOS Monterey (12.x)

- AutomatedTesting/Gem/PythonTests/Atom/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Benchmark_GPU.py
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_GPU.py
- When a timeout occurs in the `TestSuite_Main_GPU.py` file, it can potentially affect the benchmark test metrics. 
- While our underlying metrics problem had to do with clusters on the ES side, this loose end should also be tied off just in case it happens in the future and becomes a cause for metrics not posting.
- Test results below using command `C:\git\o3de>C:\git\o3de\python\runtime\python-3.7.10-rev1-windows\python\python.exe -m pytest -vv -s --build-directory=".\build\bin\profile" AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Benchmark_GPU.py`:
```
--- Expected lines ---
[ FOUND ] Benchmark metadata captured.
[ FOUND ] Pass timestamps captured.
[ FOUND ] CPU frame time captured.
[ FOUND ] Captured data successfully.
[ FOUND ] Exited game mode
Found 5/5 expected lines …
```
> Move benchmark test metrics to their own suite outside of the GPU suite.

- cmake/Platform/Linux/PackagingPostBuild_linux.cmake
The nightly linux builds have a deb package with a different sha256 than the accompanying checksum file.
i.e.
```
$ cat O3DE_latest.deb.sha256 
0bbefc977deb11f3dbe5eefdc7e36caaf607758147957fef060e96e6b519f5dd  O3DE_latest.deb%                                    
$ sha256sum O3DE_latest.deb                          
2905441099dc5467b008430e6e14f0c75c96474af965651c1f105a92d496cb5f  O3DE_latest.deb
```
It looks like cmake is writing the sha256 file after signing, but not recomputing the hash.
Signed-off-by: xaque <xaque@duck.com>
> Checksum of deb package needs to be recomputed after signing

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.h
* Ported line-based and solid skeleton rendering to debug display.
* Disabled depth testing for skeleton rendering so that we can see the skeleton through the solid mesh.
* Remembering the previous render flags and setting them back afterwards.
* Enabled depth testing for emfx debug, vertex & face normals, tangents and wireframe. We don't want to see them through the solid mesh to avoid visual clutter.
> EMotion FX: Ported skeleton rendering to debug display and fixed depth testing for debug rendering

- Gems/Atom/RHI/Registry/Platform/Windows/PlatformLimits.setreg
- This fixes the issue in AR with the nightly GPU run timing out.
> Sets AllowDescriptorHeapCompaction to true so the nightly GPU run won't time out

- Code/Tools/AssetProcessor/native/unittests/AssetProcessorServerUnitTests.cpp
- Code/Tools/AssetProcessor/native/utilities/BatchApplicationServer.cpp
Adding disconnect() to AssetProcessorServerUnitTest to match the connect()
Adding close() to BatchApplicationServer to match the listen() 
> {lyn10335} closing and disconnecting during AssetProcessorServerUnitTest

- Code/Framework/AzNetworking/AzNetworking/Utilities/EncryptionCommon.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftJoinSessionActivity.cpp
- Gems/AWSGameLift/Code/AWSGameLiftClient/Tests/Activity/AWSGameLiftJoinSessionActivityTest.cpp
- Gems/AWSGameLift/Code/AWSGameLiftCommon/Source/AWSGameLiftSessionConstants.h
- Gems/AWSGameLift/Code/AWSGameLiftServer/Source/AWSGameLiftServerManager.cpp
- Gems/AWSGameLift/Code/AWSGameLiftServer/Source/AWSGameLiftServerManager.h
- Gems/AWSGameLift/Code/AWSGameLiftServer/Source/GameLiftServerSDKWrapper.cpp
- Gems/AWSGameLift/Code/AWSGameLiftServer/Source/GameLiftServerSDKWrapper.h
- Gems/AWSGameLift/Code/AWSGameLiftServer/Tests/AWSGameLiftServerManagerTest.cpp
- Gems/AWSGameLift/Code/AWSGameLiftServer/Tests/AWSGameLiftServerMocks.h
- Gems/Multiplayer/Code/Include/Multiplayer/Session/ISessionHandlingRequests.h
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
The TLS/DTLS functionality is still pending on networking to verify, this PR is to add missing parts of GameLift Gem
* Add function to fetch certificate and private key from GameLift instance on server
* Add branch to make connection by using dns name on client
* Fix networking tls certificate pem file getter logic
Pass gamelift client and server unit test
Tested locally by mocking GameLift server sdk to return a self signed cert, it works as expected with TLS enabled connection. But when using ca cert (verified ca cert is valid by using openssl cli), networking layer fails on handshake. Pending on networking team to confirm TLS/DTLS solution is compatible with ca cert, then we can finish the last piece by adding gamelift required ca cert for client.
Signed-off-by: onecent1101 …
> Add required support for GameLift TLS certificate

- Gems/Atom/Tools/MaterialEditor/gem.json
- Gems/MessagePopup/gem.json
Fixes #7727, MaterialEditor does not depend on LyShine.  Also adds missing dependency to MessagePopup Gem which has a build dependency on `Gem::LyShine.Clients.API`
> Fixing LyShine dependency in gem.json

- Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.h
- Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/LuaMaterialFunctor.cpp
- Gems/ScriptEvents/Code/Include/ScriptEvents/ScriptEventRegistration.cpp
- Changed the LuaMaterialFunctor ScriptContext ID to be specific instead of the default
- Set the MutexType in BehaviorContextEventBus to recursive_mutex
Closes #6550
Closes #7620
Closes #6817
> Fixed Script Event registration going to the incorrect Behavior Context

- Gems/EMotionFX/Code/Source/Integration/Components/SimpleMotionComponent.cpp
GHI #5976 described that for really large numbers the edit field randomly changed digits. This does not happen on the latest version anymore and most likely was caused by a floating point issue that the editor team fixed. We're limiting the maximum values now additionally as in case such large numbers are needed, something is wrong with the global time scale.
Resolves #5976
> EMotion FX: Limiting max values for playspeed, blend-in and blend-out times for the simple motion component

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.h
- Gems/EMotionFX/Code/Source/Integration/Rendering/RenderActorSettings.h
while preventing Z-fighting
| Before | After |
| ----------- | ----------- |
|  ![image](https://user-images.githubusercontent.com/43751992/154443525-13cdf475-2687-4ee4-9a97-349de7c1a0e4.png) |   ![image](https://user-images.githubusercontent.com/43751992/154443565-0eb86170-3adb-4042-ac78-52de11821171.png)     |
> EMotion FX: Minimized distance between wireframe and solid mesh rendering

- Code/Framework/AzCore/AzCore/StringFunc/StringFunc.h
- Code/Framework/AzCore/AzCore/std/string/conversions.h
- Code/Framework/AzCore/Tests/AZStd/String.cpp
- Code/Framework/AzCore/Tests/StringFunc.cpp
- Gems/GraphCanvas/Code/Source/Translation/TranslationBus.h
This specifically implies to the value returning to_string overloads
Added a range based StringFunc::Join overload.
Reduced the number of AZStd::to_string calls in the TranslationKey
operator<< function.
> Fixed implicit conversion to bool in AZStd::to_string.

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
- Gems/EMotionFX/Code/Source/Integration/Components/ActorComponent.cpp
- Gems/EMotionFX/Code/Source/Integration/Rendering/RenderFlag.h
* Disabled depth testing for joint orientation debug rendering, so that we can also see them through the solid mesh rendering.
* Update transforms in case solid mesh rendering or any of the debug visualizations are enabled.
> EMotion FX: Update skeleton transforms when either solid mesh rendering or any of the debug visualizations is enabled

- Code/Tools/SceneAPI/SceneCore/Events/ExportEventContext.cpp
- Code/Tools/SceneAPI/SceneCore/Events/ExportEventContext.h
- Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.cpp
- Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.h
- Gems/SceneProcessing/Code/Source/SceneBuilder/SceneBuilderWorker.cpp
adding a 'debug' flag in the PreExportEventContext so that the scene builders can write out a human readable version of the product assets the Prefab gem has been updated to use the flag when writing out a procedural prefab product asset using a pretty JSON printer
> {lyn9869} adding a 'debug' flag in the PreExportEventContext

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphViewWidget.cpp
> set the shortcut to only work when the graph widget is on focus

- Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
- Tools/LyTestTools/tests/unit/test_o3de_editor_test.py
Reduces EditorTest NoneType errors, remove dead code, update docstrings, fix pep8 warnings.
Addresses a failure seen in https://github.com/o3de/o3de/issues/7657 which unexpectedly removed test reporting from an AR failure.
> Fix NoneType errors in EditorTest
