o3de/o3de

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.h
The changes to the Prefab Save workflows introduced in #7649 surfaced an issue with the EOS: when loading a level, OnContextReset triggers an update to the PrefabFocusHandler but at that time the rootInstance is still set to an invalid TemplateId. In that state, pressing Ctrl+S or clicking on Save in the File menu results in no action even if there are changes that need to be saved, because the cached TemplateId in the FocusHandler would be set to Invalid even though the root instance is valid.
Given the amount of hits the cached root template id would get anyways, I preferred removing the variable and just retrieving the updated value on demand. That fixes the issue.
> Focus Mode | Fix issue with cached focused TemplateId occasionally being set to Invalid by the EOS

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.cpp
There are 3 versions of LoadInstanceFromPrefab method in PrefabDomUtils that share a lot of same code. This PR creates a static helper method with the shared code and makes the 3 methods use it. It both reduces the amount of code and makes it easy to just change the default behavior in 1 function instead of 3 functions.
No new logic changes in this PR. Only moving things around and condensing the amount of code.
> Combine the 3 LoadInstanceFromPrefab methods to use a single helper method

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
- Gems/LyShine/Code/Source/UiRenderer.cpp
Both Animation Editor and UI Editor render viewports use the same render pipeline ("passes/MainRenderPipeline.azasset"), but each one needs its own unique name, otherwise it fails when both are opened at the same time, giving the following kind of errors:
````
[Error] (FrameScheduler) - Scope Root.MainPipeline.MainPipeline.MorphTargetPass already exists. You must specify a unique name.
````
Added viewport id suffix to render pipeline name to fix the issue.
> Fixed render viewport not working when both Animation Editor and UI Editor are opened in the editor.

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/EMStudioManager.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/RenderPlugin/RenderOptions.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/RenderPlugin/RenderPlugin.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/RenderPlugin/RenderPlugin.h
* It turned out via a flakey AR test that the RenderOptions were reflected multiple times. This happened as the RenderOptions were reflected by the base render plugin and thus the Atom as well as the OpenGL one reflected the render options.
* Also directly fixed another bug along the way, where the render options were not showing up in the Preferences window.
Resolves #7814 
> EMotion FX: Fixed reflection issue with render options and made them appear in the Animation Editor Preferences

- Gems/Terrain/gem.json
Testing:
* Updated gem.json
* Reran project manager
* Confirmed link now goes to Terrain gem documentation on o3de.org
> 7698: Fix broken documentation link for Terrain Gem

- Code/Tools/SceneAPI/SceneCore/Containers/GraphObjectProxy.cpp
- Code/Tools/SceneAPI/SceneCore/Tests/Containers/SceneBehaviorTests.cpp
Fixing some cases where the return value for GraphObjectProxy Invoke where a pointer, reference, or big value could be returned. Updated the tests to reflect the changes.
> {lyn10540} Fixing some cases where the return value for GraphObjectProxy Invoke

- Code/Framework/AzFramework/Platform/Linux/AzFramework/Asset/AssetSystemComponentHelper_Linux.cpp
- Code/Framework/AzFramework/Platform/Mac/AzFramework/Asset/AssetSystemComponentHelper_Mac.cpp
- Code/Framework/AzFramework/Platform/Windows/AzFramework/Asset/AssetSystemComponentHelper_Windows.cpp
The `<SDKRoot>/bin/<platform>/<config>/Default` directory will be
searched for the AssetProcessor.
In an install layout the AssetProcessor is copied over to the Default
permutation folder.
In the Monolithic permutation, tools are not build so there is no need to check
for the AP in that permutation.
> Added an additional search location for launching the AP.

- AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Main.py
- AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Main_Optimized.py
- AutomatedTesting/Gem/PythonTests/Prefab/tests/PrefabTestUtils.py
- AutomatedTesting/Gem/PythonTests/Prefab/tests/create_prefab/CreatePrefab_UnderAnotherPrefab.py
- AutomatedTesting/Gem/PythonTests/Prefab/tests/create_prefab/CreatePrefab_UnderChildEntityOfAnotherPrefab.py
- AutomatedTesting/Gem/PythonTests/Prefab/tests/create_prefab/CreatePrefab_WithNestedEntities.py
- AutomatedTesting/Gem/PythonTests/Prefab/tests/create_prefab/CreatePrefab_WithNestedEntitiesAndNestedPrefabs.py
Add the following new automated tests for complex workflows around creating a prefab:
- CreatePrefab_UnderChildEntityOfAnotherPrefab
- CreatePrefab_WithNestedEntities
- CreatePrefab_WithNestedEntitiesAndNestedPrefabs
Tested with the following commands:
`python\python.cmd -m pytest AutomatedTesting\Gem\PythonTests\Prefab\TestSuite_Main.py --build-directory windows_vs2019\bin\profile`
`python\python.cmd -m pytest AutomatedTesting\Gem\PythonTests\Prefab\TestSuite_Main_Optimized.py::TestAutomationNoAutoTestMode --build-directory windows_vs2019\bin\profile`
> Add automated tests for complex workflows around creating a prefab

- Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseGlobalIlluminationFeatureProcessor.cpp
Replaced the assert on the IrradianceImage with a conditional, since it may not be present in all pipelines.
> Fix for ASV shutdown assert on IrradianceImage

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.h
Removing another duplicated reflect call for the render options
> EMotion FX: Removing reflecting the render options from the Atom plugin

- Gems/Atom/RHI/Code/Source/RHI.Reflect/PipelineLayoutDescriptor.cpp
- Gems/Atom/RHI/Code/Source/RHI/PipelineLibrary.cpp
- Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/DX12_Windows.h
- Gems/Atom/RHI/DX12/Code/Source/RHI/PipelineLibrary.cpp
There is a bug where the same PSO hash for a shader (like StandardPBR_ForwardPass_EDS) yields a different PipelineLibrary binary file when written out from different user flows. For example a D3D12_GRAPHICS_PIPELINE_STATE_DESC with the same hash  when written out from ASV full test suite will yield a different binary when compared to the one written out from Editor user flow. The only difference between the two workflows is that the shader options differ but in the end both the flows should yield the same bytecode as they should pick the same shader variant yet the cached pso blob or the PipelineLibrary with the pso differs. This seems like a driver bug that we suspect is causing flickering issues. Need to follow up with Microsoft with this issue. Re-enable this once the issue is resolved …
> Disable PSO caching for DX12

- Gems/Atom/RHI/Registry/Platform/Windows/PlatformLimits.setreg
https://github.com/o3de/o3de/issues/7546
> Increase the default number of cpu descriptor handles to fix a crash on AMD gpus

- AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Periodic.py
- AutomatedTesting/Levels/Physics/Collider_AddingNewGroupWorks/Collider_AddingNewGroupWorks.prefab
- AutomatedTesting/Levels/Physics/Collider_CollisionGroupsWorkflow/Collider_CollisionGroupsWorkflow.prefab
- AutomatedTesting/Levels/Physics/Collider_NoneCollisionGroupSameLayerNotCollide/Collider_NoneCollisionGroupSameLayerNotCollide.prefab
- AutomatedTesting/Levels/Physics/Collider_SameCollisionGroupSameCustomLayerCollide/Collider_SameCollisionGroupSameCustomLayerCollide.prefab
- AutomatedTesting/Levels/Physics/Joints_Ball2BodiesConstrained/Joints_Ball2BodiesConstrained.prefab
- AutomatedTesting/Levels/Physics/Joints_BallBreakable/Joints_BallBreakable.prefab
- AutomatedTesting/Levels/Physics/Joints_BallNoLimitsConstrained/Joints_BallNoLimitsConstrained.prefab
- AutomatedTesting/Levels/Physics/Joints_Fixed2BodiesConstrained/Joints_Fixed2BodiesConstrained.prefab
- AutomatedTesting/Levels/Physics/Joints_FixedBreakable/Joints_FixedBreakable.prefab
- AutomatedTesting/Levels/Physics/Joints_GlobalFrameConstrained/Joints_GlobalFrameConstrained.prefab
- AutomatedTesting/Levels/Physics/Joints_Hinge2BodiesConstrained/Joints_Hinge2BodiesConstrained.prefab
- AutomatedTesting/Levels/Physics/Joints_HingeBreakable/Joints_HingeBreakable.prefab
- AutomatedTesting/Levels/Physics/Joints_HingeNoLimitsConstrained/Joints_HingeNoLimitsConstrained.prefab
- AutomatedTesting/Levels/Physics/Material_CharacterController/Material_CharacterController.prefab
- AutomatedTesting/Levels/Physics/Material_FrictionCombine/Material_FrictionCombine.prefab
- AutomatedTesting/Levels/Physics/Material_FrictionCombinePriorityOrder/Material_FrictionCombinePriorityOrder.prefab
- AutomatedTesting/Levels/Physics/Material_PerFaceMaterialGetsCorrectMaterial/Material_PerFaceMaterialGetsCorrectMaterial.prefab
- AutomatedTesting/Levels/Physics/Material_Restitution/Material_Restitution.prefab
- AutomatedTesting/Levels/Physics/Material_RestitutionCombine/Material_RestitutionCombine.prefab
- AutomatedTesting/Levels/Physics/Material_RestitutionCombinePriorityOrder/Material_RestitutionCombinePriorityOrder.prefab
Converted the following tests to use prefab system:
- Collider_AddingNewGroupWorks
- Collider_CollisionGroupsWorkflow
- Collider_NoneCollisionGroupSameLayerNotCollide
- Collider_SameCollisionGroupSameCustomLayerCollide
- Joints_Ball2BodiesConstrained
- Joints_BallBreakable
- Joints_BallNoLimitsConstrained
- Joints_Fixed2BodiesConstrained
- Joints_FixedBreakable
- Joints_GlobalFrameConstrained
- Joints_Hinge2BodiesConstrained
- Joints_HingeBreakable
- Joints_HingeNoLimitsConstrained
- Material_CharacterController
- Material_FrictionCombine
- Material_FrictionCombinePriorityOrder
- Material_PerFaceMaterialGetsCorrectMaterial
- Material_Restitution
- Material_RestitutionCombine
- Material_RestitutionCombinePriorityOrder
These two tests are also in Main_Optimized test suite, so leave them …
> Convert Physics automated tests from Periodic test suite to use prefab system

- Gems/EMotionFX/Code/EMotionFX/Source/MotionLayerSystem.cpp
- Gems/EMotionFX/Code/Source/Integration/Components/SimpleMotionComponent.cpp
- Gems/EMotionFX/Code/Source/Integration/Components/SimpleMotionComponent.h
- Gems/EMotionFX/Code/Tests/MotionLayerSystemTests.cpp
* Blend out time was not working previously.
* Added the freeze at last frame option to the UI. If disabled, the character goes back to bind pose after the motion ended. If enabled, it stays at the last frame of the animation in case it is not looping.
* Hiding the freeze at last frame option in case the loop option is enabled.
* Showing the blend out option only in case looping and freezing at last frame are disabled. Hiding otherwise.
Resolves #5977
https://user-images.githubusercontent.com/43751992/155109641-f41a1b24-28af-48d7-a539-1e6a8fc7ea30.mp4
> EMotion FX: Simple motion component blend out time not working (+some more fixes)

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.h
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.cpp
Fixed a bug with moving the ground plane along with the character, the Y coordinate was not taken into account.
Also removed the bounds check which prevents moving the groundplane before reaching 150 tiles for two reasons:
1. Code safety: If something changes in the ground plane texture, we won't notice as the repositioning is done so rarely that we won't notice a possible pop. If this is done every frame and tile, we will be able to identify issues with it right when they get introduced. Code safety is a higher virtue here than saving a repositioning ebus call.
2. By moving 150 tiles, we are 1/3 of the plane closer to the cliff already, so when repositioning, we will see a pop in the horizon.
> EMotion FX: Moving ground plane along with the character bug fix

- Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp
- Gems/Atom/Feature/Common/Code/Source/CoreLights/ShadowmapPass.cpp
- Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceBlurPass.cpp
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassFactory.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassLibrary.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassSystem.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassSystemInterface.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/PassDescriptor.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassFactory.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassLibrary.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassSystem.cpp
This PR changes the `GetPassTemplate` function from the pass library and pass system so that they return const pointer to const objects. Previously the returned object wasn't const allowing direct modification to the underlying template in the pass library.  
**This change will introduce a breaking change as all the call to `GetPassTemplate` will need to update their returned object signature to `const AZStd::shared_ptr<const RPI::PassTemplate>`.**
This PR also introduces the `HasTemplate` function in the pass system to expose the function with the same name in the pass library. This is intended as a replacement to the following pattern, that introduced a bump in the shared ptr counter.
```
const AZStd::shared_ptr<const RPI::PassTemplate> rtPassTemplate = …
```
> Make RPI pass template pointed object const

- Gems/AtomTressFX/CMakeLists.txt
- Gems/CrashReporting/Code/Source/GameCrashHandler.cpp
- Gems/MultiplayerCompression/Code/Source/MultiplayerCompressionModule.cpp
- Gems/ScriptCanvasDeveloper/Code/Game/Source/ScriptCanvasDeveloperGem.cpp
MultiplayerCompression and ScriptCanvasDeveloper gems
Removed the missing include directories from AtomTressFX CMakeLists.txt
This was causing the AtomTressFX arget when used as an IMPORTED target in
the SDK layout
fixes #7851
> Fixed the module name declarations in the CrashReporting,

- Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbNativeWindow.cpp
- Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbNativeWindow.h
Some window managers (like mutter) will query an application at some
interval to see if it is processing its event loop. They do this by sending
the window a `_NET_WM_PING` message. The application is expected to process
that message and send it back to the server.
During normal execution, responding to the `_NET_WM_PING` message is
handled by Qt. However, when the user enters game mode in the editor,
processing of Qt's event loop stops, and everything is processed by the
XcbNativeWindow instead. This adds the proper response to that event, so
that mutter does not consider the Editor process as hung while the user is
in game mode.
> [Linux] Respond to the `_NET_WM_PING` client message event

- Code/Framework/AzCore/AzCore/Debug/Trace.cpp
This commit adds a new "bg_assertsAutoBreak" CVAR which defaults
currently to `false`. When enabled, trace asserts will check if a debugger
is attached and emit a debugger interrupt if so.
The idea is that after introduction, developers will be *strongly*
encouraged to enable this flag so that active asserts currently are
fixed. After a period of time, this setting will default to true so that
asserts that trigger are more visible across the community.
> Add break on assert setting with debugger attached

- Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugAuditTrail.h
````
MultiplayerDebugAuditTrail.h:72:14: error: private field 'm_inputBuffer' is not used [-Werror,-Wunused-private-field]
char m_inputBuffer[AUDIT_SEARCH_BUFFER_SIZE] = {};
^
````
> Fixed warning treated as error in release in some platforms about not using m_inputBuffer in MultiplayerDebugAuditTrail

- Gems/Multiplayer/Code/Source/Components/LocalPredictionPlayerInputComponent.cpp
Correct long formatter usages to platform agnostic defines. Also update to static_casts of the original integral type vs numeric. 
> Switch LocalPredictionPlayerInputComponent string formatting to platform safe define

- Gems/Atom/RHI/Metal/Code/Source/RHI/SwapChain.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/SwapChain.h
The main issue was that Qt was changing the drawable size after the resize event to a different dimension. Hence there was a mismatch between the swap chain texture and the viewport/scissor size. The fix is to cache the dimension and update the metalLayer right before the drawable is requested.
> Fix GPU crash when loading a level from Editor

- Code/Editor/Platform/Linux/Editor/Core/QtEditorApplication_linux.cpp
- Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbEventHandler.h
- Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbNativeWindow.cpp
XCB_CLIENT_MESSAGE events include _NET_WM_PING events, which window managers
use to detect if an application is still responding. When Qt creates the
window, it sets the _NET_WM_PING atom of the WM_PROTOCOLS property, so window
managers will expect the application to support this protocol. By skipping the
filtering of this event, Qt processes the ping event normally, so that window
managers do not think that the Editor has stopped responding.
> [Linux] Do not filter XCB_CLIENT_MESSAGE events when in game mode in the Editor

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.h
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.cpp
* Fixed a bug with moving the ground plane while follow mode is disabled.
* Changed the "Reset Character" option to not re-create the entire entities and render objects, but just move the character to the origin which is what the former "Reset Transform" option did.
* Only showing the option in case a character is actually loaded.
Resolves #7757
> EMotion FX: Move character to origin & fix for move groundplane while follow character is disabled

- Gems/MotionMatching/Assets/Levels/MotionMatching_ControllableCharacter/CharacterController.scriptcanvas
- Gems/MotionMatching/Assets/Levels/MotionMatching_ControllableCharacter/MotionMatching_ControllableCharacter.animgraph
* New script canvas graph to control the target/goal position relative to the character based on gamepad input while being able to rotate the camera.
* The target will later on be used to create the curve from the character going into its facing direction towards the goal forming the trajectory prediction.
https://user-images.githubusercontent.com/43751992/155749883-c0c3c6ee-0def-4c65-9df9-c9dc6b2fd5ad.mp4
> Motion Matching: Added target position controller for new controllable character level

- Code/Framework/AzCore/AzCore/Math/Internal/SimdMathVec3_neon.inl
> Fixed CmpAllLt and CmpAllGt functions in Neon Vec3 class.

- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomGPU_AreaLightScreenshotTest.py
the key for an atom_constants.py component property path was changed in a different PR. That caused a failure in nightly GPU tests
`EXCEPTION raised:
Traceback (most recent call last):
File "d:\workspace\o3de\automatedtesting\gem\pythontests\editorpythontesttools\editor_python_test_tools\utils.py", line 308, in start_test
test_function()
File "D:/workspace/o3de/AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomGPU_AreaLightScreenshotTest.py", line 142, in AtomGPU_LightComponent_AreaLightScreenshotsMatchGoldenImages
AtomComponentProperties.light('Attenuation Radius Mode'), ATTENUATION_RADIUS_MODE['automatic'])
File "D:\workspace\o3de\AutomatedTesting\Gem\Editor\Scripts/../../PythonTests\Atom\atom_utils\atom_constants.py", line 374, in light
return properties[property]
KeyError: …
> Nightly GPU Area light - fixing a casing issue on a dictionary key

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/AssetSelection/AssetSelectionComboBox.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetSelection/AssetSelectionComboBox.cpp
Uses the thumbnail system to add preview images to combo box entries
Disabled by default
> Atom Tools: asset selection combo box thumbnail support

- cmake/3rdParty/Platform/iOS/BuiltInPackages_ios.cmake
> [iOS] Bump version of libpng for iOS. The new version has arm neon optimizations enabled.

- AutomatedTesting/Gem/PythonTests/smoke/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/smoke/test_CLITool_SerializeContextTools_Works.py
- Tools/LyTestTools/tests/CMakeLists.txt
Reenables LyTT tests on Linux, modifies SerializeContext to be tested when it is enabled, and simplifies some redundant naming.
> Reenable tests on Linux, remove secondary skip

- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/SurfaceManipulator.cpp
Sets a default callback to return no entity IDs to ignore when no callback has been installed via `InstallEntityIdsToIgnoreFn`.
> Fix for GHI-7879

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_GPU.py
- Change was simpler than expected, didn't really require anything other than switching the flag and running all of the tests afterwards.
- I re-tested the tests after enabling the prefabs and got expected passing results (2 expected failing Vulkan tests from https://github.com/o3de/o3de/blob/development/AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_GPU.py - `AtomGPU_LightComponent_AreaLightScreenshotsMatchGoldenImages_Vulkan` and `AtomGPU_LightComponent_SpotLightScreenshotsMatchGoldenImages_Vulkan`. These are being fixed internally.)
- Test Run 1: `TestSuite_Main.py`:
```
==== 30 passed, 2 warnings in 150.26s (0:02:30) ====
```
- Test Run 2: `TestSuite_Main_GPU.py:`
```
Use the following commands to re-run each test that failed locally
(NOTE: The 'PYTHON' or 'PYTHONPATH' …
```
> Enable prefabs for Atom automated tests.

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Buffer.h
- Change was suggested by @moudgils and it fixes the timeout issue. The test also passes after applying the change.
- Test run - edited the script to use only `Vulkan` RHI using command `C:\git\o3de\python\runtime\python-3.7.10-rev1-windows\python\python.exe -m pytest -vv -s --build-directory=".\build\bin\profile" Standalone\PythonTests\Automated\benchmark_runner_periodic_suite.py -k test_PerformanceBenchmarkPeriodicSuite`:
```
==== 1 passed in 1446.23s (0:24:06) ====
```
- The test is quite long but does pass now.
> Fixes Vulkan RHI timeout in the benchmark nightly GPU test

- cmake/Tools/Platform/iOS/build_ios_test.py
- cmake/Tools/Platform/iOS/launch_ios_test.py
Fix gtest_filter parameter being passed to AzTestRunner. On M1 Macs, the Mac gets chosen as the default test device for building. Make that parameter explicit for build so that an iOS device is chosen.
> [iOS] Fix issues in python scripts that are used to build and run tests on iOS

- Code/Editor/EditorViewportSettings.cpp
- Code/Editor/EditorViewportSettings.h
- Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp
- Code/Editor/Lib/Tests/test_ViewportManipulatorController.cpp
- Code/Editor/ViewportManipulatorController.cpp
- Code/Editor/ViewportManipulatorController.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportMessages.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/RenderViewportWidget.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp
rough implementation of a way to allow the cursor to wrap viewport when using manipulators. 
https://user-images.githubusercontent.com/854359/146664874-28871cab-5a39-4dfe-b466-804a14b5877a.mp4
> feat: add cursor wrap mode viewport rough implementation

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Sandbox.py
- AutomatedTesting/Gem/PythonTests/EditorPythonBindings/ComponentUpdateListProperty_test.py
- AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Periodic.py
> Remove unnecessary enable_prefab_system flag in some tests

- scripts/o3de/o3de/project_manager_interface.py
Does not include any helper functions or other common code that could be shared between methods, only the interface for Project Manager to call.
Is designed to be the minimal interface to expose to Project Manager and to do all data massaging and gathering offloaded work from Project Manager and minimizing calls to python through pybind.
Also centralizes the full Project Manager interface so only one .py files needs to be bound.
Psuedo-code for methods is included in documentation.
Project Manager's main responsibility will be de/serialization between data types ...Info cpp classes and dicts in python.
It will also only need to call this simpler interface, no call to a PythonBindings.cpp function should result in more than one call to a python function through pybind. An subsequent calls …
> Framework For Simplifed Python Interface for Project Manager

- AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Periodic.py
- AutomatedTesting/Gem/PythonTests/Physics/tests/material/Material_DefaultLibraryUpdatedAcrossLevels_after.py
- AutomatedTesting/Gem/PythonTests/Physics/tests/material/Material_DefaultLibraryUpdatedAcrossLevels_before.py
- AutomatedTesting/Levels/Physics/Material_DefaultLibraryUpdatedAcrossLevels/0/0.prefab
- AutomatedTesting/Levels/Physics/Material_DefaultLibraryUpdatedAcrossLevels/1/1.prefab
`os.getcwd()` was returning the _build\*\bin\profile_ directory causing the tests to blow up.
Sanitized CWD call to insure that it's returning the O3DE root directory by passing `os.getcwd()` through the LyTestTools Abstract Resource Locator's `_find_engine_root()` helper.
Addtionally, these tests have been updated to include the Slice → Prefab conversion.
Note: These tests will fail if we ever moved AutomatedTesting outside of the O3DE repo into its own project repository. If this every happens, there needs to be a strike team effort to rewrite a massive swath of tests to support the `AbstractResourceLocator` object so the `project()` method can be used to return the project path no matter where it's located. This effort was not used since it would require a larger rewrite of these …
> Fixing the failing test_Material_DefaultLibraryUpdatedAcrossLevels tests in Physics TestSuite_Periodic 

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetSelectionModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetSelectionModel.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.h
- Gems/ScriptCanvas/Code/Editor/View/Widgets/SourceHandlePropertyAssetCtrl.cpp
- Gems/ScriptCanvas/Code/Editor/View/Widgets/SourceHandlePropertyAssetCtrl.h
RegExpFilter was previously only being used by the script canvas component to enable selection of source assets. Material editor and other atom tools need to be able to use the asset picker to select multiple source file types. It was not possible to specify multiple file filters or extensions using a wild card regular expression. The filter was updated to pass in a QRegExp object that can be configured to support different types of expressions and existing code was updated to use wildcards explicitly.
> Atom Tools: Extend RegExpFilter to support any regular expression

- Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.cpp
remove invalid characters from the mesh group name to fix up nodes that use non-alpha-numeric characters
so node names like "foo:bar_baz" will become "foo_bar_baz"
> {lyn10803} remove invalid characters from the mesh group name

- Tools/LyTestTools/ly_test_tools/_internal/pytest_plugin/test_tools_fixtures.py
Tested by running locally.
Using .exit() because .skip() and .xfail() were returning failed tests for some reason.
> Disabling LyTestTools in debug config

- AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Sandbox.py
Upgrade Multiplayer AutomatedTesting to use the new editor test structure.
For more information see https://www.o3de.org/docs/user-guide/testing/parallel-pattern/
Tested by running Multiplayer pytest and seeing the tests run.
> _python/python.sh -m pytest --build-directory ./build/bin/profile/ ./AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Sandbox.py::TestAutomation_
Note: Because scripting doesn't work with network spawners I first disabled some of the test log checking which require networkspawnable scripting.
> Upgrade Multiplayer AutomatedTesting to use the Editor Test Framework

- Gems/MotionMatching/Code/Source/MotionMatchingInstance.cpp
- Gems/MotionMatching/Code/Source/TrajectoryQuery.cpp
- Gems/MotionMatching/Code/Source/TrajectoryQuery.h
- Gems/MotionMatching/README.md
* Building the future trajectory based on an exponential curve and the joystick input.
* The curve starts in the direction of the character and then bends towards the target.
* Facing direction gets interpolated from the current character facing direction to the relative joystick target position.
* In case the joystick is within a given deadzone (joystick centered) the facing direction can still be controlled so that the character can turn in-place.
* Added section about trajectory prediction to the ReadMe.md
https://user-images.githubusercontent.com/43751992/156764525-ec9a96ac-81d9-46ed-969c-deaf7ee7d3f5.mp4
> Motion Matching: Trajectory prediction based on joystick input using exponential curve

- Code/Editor/LogFile_mac.mm
- Gems/Microphone/Code/Source/Platform/Mac/MicrophoneSystemComponent_Mac.mm
If the version of MacOS is earlier than 12, then __MAC_12_0 will not be defined.
Ref: https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/cross_development/Using/using.html
> [MacOS] Update MacOS version check to use numbers instead of defines that may not exist

- Code/Framework/AzFramework/Tests/AssetProcessorConnection.cpp
The [WaitForConnectionStateToNotBeEqual](https://github.com/o3de/o3de/blob/5a4a96348f54caa25afa11e9ed29b86dd8e89094/Code/Framework/AzFramework/Tests/AssetProcessorConnection.cpp#L81-L90) function and the [WaitForConnectionStateToBeEqual](https://github.com/o3de/o3de/blob/5a4a96348f54caa25afa11e9ed29b86dd8e89094/Code/Framework/AzFramework/Tests/AssetProcessorConnection.cpp#L65-L74) function were querying the value of connection state atomic variable at two points within that function, which leads to a race condition where the AP connection thread can update the value the connection state before it is read in the return statement.
> Fixed checking of atomic variable within the APConnectionTest

- AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
These tests need to be removed or refreshed to have deterministic behaviors. They will be skipped from the periodic test suite until they are investigated.
> Skip invalid or broken periodic tests that fail in nightly builds

- Gems/Atom/Feature/Common/Assets/Shaders/ImGui/ImGui.azsl
- Gems/Atom/Feature/Common/Code/Source/ImGui/ImGuiPass.cpp
- Gems/Atom/Feature/Common/Code/Source/ImGui/ImGuiPass.h
Notes:
* Allow for 16 textures to be rendered per frame by ImGui (1 texture slot for font, then 15 user textures)
ASV Test:
```
RHI API: dx12
Test Script Count: 22
Screenshot Count: 210
Manually Validated Screenshots: 0/209
Screenshot automatic checks failed: 1
scripts/shadowtest.bv.luac D:/o3de/AtomSampleViewer/user/Scripts/Screenshots/Shadow//spot_filter_method.png 'Level H' 0.059251
```
> Add support for rendering textures with ImGui.

- Code/Framework/AzCore/AzCore/DOM/DomPatch.cpp
- Code/Framework/AzCore/AzCore/DOM/DomPatch.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/AdapterBuilder.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/AdapterBuilder.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/BasicAdapter.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/BasicAdapter.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
- Code/Framework/AzFramework/AzFramework/azframework_files.cmake
- Code/Framework/AzFramework/Tests/DocumentPropertyEditor/AdapterBuilderTests.cpp
- Code/Framework/AzFramework/Tests/DocumentPropertyEditor/DocumentPropertyEditorFixture.cpp
- Code/Framework/AzFramework/Tests/DocumentPropertyEditor/DocumentPropertyEditorFixture.h
- Code/Framework/AzFramework/Tests/framework_shared_tests_files.cmake
- Code/Framework/AzFramework/Tests/frameworktests_files.cmake
This implements the DocumentAdapter API (see the [Document Property Editor RFC](https://github.com/o3de/sig-content/blob/main/rfcs/rfc-11-document-property-editor.md) for reference) and comes with associated tooling:
- AdapterBuilder is an optional helper class that helps construct a DOM suitable for the DPE intended to be used by adapters. It allows constructing a DOM using a visitor pattern intended to be suitable for adapting data from other sources - in the near term, CVARs followed by the Reflection 2.0 visitor interface.
- DocumentSchema and the associated PropertyEditorNodes are a lightweight abstraction for defining the node schema - this is a work in progress that will need some runtime reflection for doing node name -> definition lookup for validation, but is intended to allow …
> Initial implementation of DocumentAdapter

- Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.h
Fixes #7670
At present it is illegal to move a child entity of a prefab into another container. Until that is fixed, this code prevents it happening.
> Prevents changing the parent of an entity in a prefab

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Benchmark_GPU.py
- AutomatedTesting/Levels/AtomFeatureIntegrationBenchmark/AtomFeatureIntegrationBenchmark.ly
- AutomatedTesting/Levels/AtomFeatureIntegrationBenchmark/AtomFeatureIntegrationBenchmark.prefab
- AutomatedTesting/Levels/AtomFeatureIntegrationBenchmark/filelist.xml
- AutomatedTesting/Levels/AtomFeatureIntegrationBenchmark/level.pak
- Converts the AtomFeatureIntegrationBenchmark into a prefab as slices are no longer used.
- Fixes the groundplane asset error and re-adds the groundplane material by doing so.
- Test passes after conversion:
```
C:\git\o3de>C:\git\o3de\python\runtime\python-3.7.12-rev1-windows\python\python.exe -m pytest -vv -s --build-directory="C:\git\o3de\build\bin\profile" C:\git\o3de\AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Benchmark_GPU.py
==== 2 passed in 177.80s (0:02:57) ====
```
> Convert AtomFeatureIntegrationBenchmark level to prefab.

- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MaterialAdded.py
Adds several P1 tests for Material component working with LOD's and overriding materials. Uses both container item EditorMaterialsComponentSlot accessor methods and ebus calls to azlmbr.render.MaterialComponentRequestBus.
Report:
[SUCCESS] Success: Material Entity successfully created
[SUCCESS] Success: Entity has a Material component
[SUCCESS] Success: Material component disabled
[SUCCESS] Success: Entity has an Actor component
[SUCCESS] Success: Material component enabled
[SUCCESS] Success: Entity Actor component gone
[SUCCESS] Success: Material component disabled
[SUCCESS] Success: Entity has a Mesh component
[SUCCESS] Success: Material component enabled
[SUCCESS] Success: Mesh Asset set …
> Material Component P1 null renderer tests

- AutomatedTesting/Gem/PythonTests/Terrain/EditorScripts/TerrainPhysicsCollider_MaterialMapping_Works.py
Tested against new expected value and a higher than expected value for glass distance to verify failure messaging.
Test Passed
------------
|  Output  |
------------
Starting test TerrainPhysicsCollider_MaterialMapping_Works...
Test TerrainPhysicsCollider_MaterialMapping_Works finished.
Report:
[SUCCESS] Success: Entered Game Mode
[SUCCESS] Success: PhysicsCube_Glass moved 12.013m, to PhysicsCube_Rubber's 0.029m
[SUCCESS] Success: Exited Game Mode
Test result:  SUCCESS
> Updating expected distance for glass surface and updated failure messaging

- Gems/MotionMatching/Code/Source/Feature.cpp
- Gems/MotionMatching/Code/Source/MotionMatchingInstance.h
- Gems/MotionMatching/Code/Source/PoseDataJointVelocities.cpp
- Gems/MotionMatching/Code/Source/PoseDataJointVelocities.h
* Profiling the latest version showed that calculating the joint velocities took a significant amount of time. After diving it turned out that we're sampling the animation too often, so consolidating that and sampling it only once decreased the time needed to calculate the joint velocities for the current pose significantly.
* Removed an unneeded/unused variable from the motion matching instance.
* Replaced a condition in the base feature with a clamp to simplify the code.
> Motion Matching: Performance improvement for calculating joint velocities

- AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_AutoComponent_NetworkInput.py
- AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_AutoComponent_RPC.py
- AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_BasicConnectivity_Connects.py
- AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_SimpleNetworkLevelEntity.py
- AutomatedTesting/Levels/Multiplayer/AutoComponent_NetworkInput/AutoComponent_NetworkInput.prefab
- AutomatedTesting/Levels/Multiplayer/BasicConnectivity_Connects/BasicConnectivity_Connects.prefab
- AutomatedTesting/Levels/Multiplayer/BasicConnectivity_Connects/Player.prefab
- AutomatedTesting/Levels/Multiplayer/SimpleNetworkLevelEntity/SimpleNetworkLevelEntity.prefab
- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
- Tools/LyTestTools/ly_test_tools/o3de/editor_test_utils.py
- Tools/LyTestTools/tests/unit/test_editor_test_utils.py
- Update Multiplayer editor test python scripts to use a range of server ports. When running tests rapidly on Linux, the Editor takes time to free up the port even after the app release it... cycling over ports give the test a free port that wasn't recently in use
- Update tests to use the new Network Player Spawner component
- Ran the tests and see they all succeed on Linux
`python/python.sh -m pytest --build-directory ./build/bin/profile/ ./AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Sandbox.py::TestAutomation`
> Fix Multiplayer Editor Flaky Tests

- Code/Tools/LuaIDE/Source/Editor/LuaEditor.cpp
The LuaIDE window and controls were not scaling on Windows for display scaling above 100%. For example if you have a 4K monitor you can configure Windows to scale your display to 200% to have larger text and controls. The other o3de editors scale as expected. 
Signed-off-by: billowsofcode <billowsofcode@gmail.com>
> LuaIDE supports DPI scaling

- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Model/ModelKdTree.h
- Gems/Atom/RPI/Code/Source/RPI.Reflect/Model/ModelKdTree.cpp
The Atom buffers are stored as `uint8_t` arrays, and then reinterpret
casted to the desired type. The TriangleIndices type exists to read 3
indexes at a time from a given index buffer. Previously, this type was
implemented using a `std::tuple` of three `uint32_t`s. However, MSVC uses
a different layout for their `tuple` compared to the implementation in
libc++. To test this, I made this small program:
```cpp
#include <iostream>
#include <memory>
#include <tuple>
int main()
{
std::tuple<uint32_t, uint32_t, uint32_t> mytuple {5, 42, 128};
std::cout << "mytuple is at " << std::addressof(mytuple) << "\n";
std::cout << "Element 1 is at " << std::addressof(std::get<0>(mytuple)) << "\n";
std::cout << "Element 2 is at " << std::addressof(std::get<1>(mytuple)) << "\n";
std::cout << "Element 3 is …
```
> Fix KdTree's TriangleIndices type to have fields in the same order on all platforms

- AutomatedTesting/Gem/PythonTests/editor/TestSuite_Main.py
Test is intermittently failing for an unknown reason when run on Jenkins. A ticket was logged to correct the results reporting to help identify the root cause of the test failure (#8108). Marking the test xfail until this can be fully investigated as it causes no cascading failures in its test class.
> Marking ComponentCRUD test as xfail

- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
> `connect` console command uses default port if not specified

- Gems/EMotionFX/Code/Tests/ProvidesUI/AnimGraph/AnimGraphModelTests.cpp
The current version of Qt used on Mac will emit a warning sometimes when a
window is recreated. This warning isn't affecting the functionality of the
EMotionFX window. However, because `QAbstractItemModelTester`, uses Qt
warnings to show where the model is inconsistent, the tests turn all
Qt warnings into Google Test failures. This allows the tests to ensure that
the `AnimGraphModel` conforms to the QAbstractItemModel API contract, but
has the side effect of bubbling up *any* Qt warning as a test failure. In
this case, this warning from Qt does not indicate any test failure, so we
filter it out.
Furthermore, that warning itself has [already been removed upstream][1],
and cherry-picked into 5.15.
[1]: https://github.com/qt/qtbase/commit/b58d6831de79ad21463e20c079093667918ee626 …
> [EMotionFX/Mac] Fix test failures from bogus Qt warnings in AnimGraphModel tests

- AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Main.py
- AutomatedTesting/Gem/PythonTests/Physics/tests/Physics_UndoRedoWorksOnEntityWithPhysComponents.py
- AutomatedTesting/Levels/Physics/Physics_UndoRedoWorksOnEntityWithPhysComponents/Physics_UndoRedoWorksOnEntityWithPhysComponents.prefab
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
This PR clears the dirty entities after an entity deletion action is completed. This is done due to the prefab undo cache trying to iterate through the dirty entities to identify changes. However, the prefab template would have already been updated by that point, resulting in bad patches.
Ideally these should have been already caught by the PrefabDeleteTests but the PrefabTestFixture doesn't add all the default editor components for entities. I've tried to update that but it would also require change the core behavior of how deletes are implemented. So, I'll be tackling that problem in a subsequent PR. For now, entity deletions will not generate bad patches and this fixes https://github.com/o3de/o3de/pull/8050 and https://github.com/o3de/o3de/issues/7946 and …
> Clear dirty entities after entity deletions to avoid double deletes

- Gems/ScriptCanvas/Code/Editor/ReflectComponent.cpp
- Gems/ScriptCanvas/Code/Editor/ReflectComponent.h
- Gems/ScriptCanvas/Code/Editor/SystemComponent.h
- Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.cpp
- Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Core.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Core.h
Previously we reflect AZ Event into serialize context on the fly through NodePalette, which causes AP and Editor out of sync of required AZ Event information
As @lumberyard-employee-dm pointed out, move Event serialize context reflection into a shared component, so both AP and Editor can have synced serialize context as required.
There is no runtime impact, the fix is for Editor and AP warning and error messages.
Manually tested scriptcanvas graph with AZ Event node, no more error message like following:
[Error] (Serialize) - Element with class ID 'XXXXXXX' is not registered with the serializer!
> Move AZ Event serialize context reflection into shared component

- Gems/GradientSignal/Code/Include/GradientSignal/GradientSampler.h
- Gems/LmbrCentral/Code/Source/Shape/ReferenceShapeComponent.cpp
- Gems/LmbrCentral/Code/Source/Shape/ReferenceShapeComponent.h
- Gems/Terrain/Code/Source/Components/TerrainHeightGradientListComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainHeightGradientListComponent.h
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.cpp
- Gems/Vegetation/Code/Source/Components/AreaBlenderComponent.cpp
- Gems/Vegetation/Code/Source/Components/AreaBlenderComponent.h
Fixed the cyclic dependency checks for the following components:
* Shape Reference
* Terrain Height Gradient List
* Vegetation Area Blender
These now use the thread-local method for detection, which means that they won't falsely trigger with simultaneous API usage from different threads.
> More reentrancy detection

- Code/Tools/AssetProcessor/native/utilities/GUIApplicationManager.cpp
If asset processor encountered a fatal error on startup before finishing start up, attempting to shutdown would not show the error and would crash AP instead due to startupErrorCollector being invoked after everything else has shutdown.  Fix was to invoke the error display (by destroy the collector) first.
> [LYN-10823] Asset Processor: Fixed crash on shutdown caused by startup error collector

- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.h
Fixes #8230
Test with a local install build.
When the server launcher isn't found, a more useful error is printed, for example:
[Error] (MultiplayerEditor) - The ServerLauncher binary is missing! (), (C:\git\o3de\install\bin\Windows\profile\Default\MyProject.ServerLauncher.exe) and (C:\git\myproject\build\bin\profile\MyProject.ServerLauncher.exe) were tried. Please build server launcher or specify using editorsv_process.
> Fixes ctrl-g crash with an installer when the server launcher is not found. Clarified error message.

- cmake/3rdParty/Platform/Android/BuiltInPackages_android.cmake
- cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake
- cmake/3rdParty/Platform/Mac/BuiltInPackages_mac.cmake
- cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
- cmake/3rdParty/Platform/iOS/BuiltInPackages_ios.cmake
Rev1 of the package had linux and android built in debug mode.
It also had unnecessary files in the package.
Rev2 of the package now builds for release on linux and android, and no longer has unnecessary files.  See the changes at https://github.com/o3de/3p-package-source/pull/101 for what went into rev2 of this package.
> Expat package to rev2 for release mode

- Gems/Atom/Utils/Code/CMakeLists.txt
- Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiGpuProfiler.h
- Gems/Atom/Utils/Code/Source/ImGuiGpuProfiler.cpp
- Gems/Profiler/Code/Include/Profiler/ImGuiTreemap.h
- Gems/Profiler/Code/Source/ImGuiTreemap.cpp
- Gems/Profiler/Code/Source/ImGuiTreemapImpl.h
- Gems/Profiler/Code/Source/ProfilerImGuiSystemComponent.cpp
- Gems/Profiler/Code/Source/ProfilerImGuiSystemComponent.h
- Gems/Profiler/Code/profiler_imgui_shared_files.cmake
The Profiler gem now exposes an ImGuiTreemap interface which can be
instantiated through a factory AZ::Interface. The entirety of the interface
is contained in [this header](https://github.com/o3de/o3de/pull/8224/files#diff-ec7ab3a76952f596f7051930f222f7ced8b541ad0f39421d53c232083b82593a).
The treemap accepts a tree of TreemapNodes, with arbitrary levels of
nesting. Each node can be named, associated with a weight, a group,
and several other features.
The ImGuiTreemap exposes a Render method to render a new ImGui window
displaying all nodes. The relative weights are the node are proportional
to the node area onscreen. The widget exposes the following features:
- Hierarchical HSV based coloring scheme
- Hover and selection support to display tooltips and node information
- Ability to …
> Add Treemap ImGui widget and Atom memory viz

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp
Bug fix for #3016.
When the user undoes changes for a larger group of selected entities (20+) the Editor noticeably hitches. This increases with the number of entities. At 40+ the hitch is multiple seconds and can cause the Editor to stop responding.
Root cause of this issue:
- Current system will destroy and recreate all these entities.
- While an entity destroyed, **Entity::Reset** is called and **OnEntityDestroyed** notification was sent.
- **EntityPropertyEditor::UpdateContents** is called every time when a selected entity gets destroyed, so the property editor will repeatedly refresh 20+ times, causing the very slow response.
Solution:
Replace **UpdateContents** with **QueuePropertyRefresh** so that we only refresh property editor once at next tick for multiple **UpdateContents** …
> Fix slow response while undoing multiple selected entities changes

- scripts/o3de/o3de/cmake.py
- scripts/o3de/o3de/disable_gem.py
- scripts/o3de/o3de/enable_gem.py
Added support to the o3de.py enable-gem and disable-gem to allow a
directory to be walked in order to add/remove explicit activation for
all gems underneath that directory.
Changed warning about gem being already enabled to an information
message
> enable-gem/disable-gem command supports bulk operations

- AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Main.py
- AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Periodic.py
- AutomatedTesting/Levels/Physics/ScriptCanvas_PostUpdateEvent/ScriptCanvas_PostUpdateEvent.prefab
- AutomatedTesting/Levels/Physics/ScriptCanvas_PreUpdateEvent/ScriptCanvas_PreUpdateEvent.prefab
- AutomatedTesting/Levels/Physics/ScriptCanvas_ShapeCast/ScriptCanvas_ShapeCast.prefab
- AutomatedTesting/ScriptCanvas/ScriptCanvas_PostUpdateEvent.scriptcanvas
- AutomatedTesting/ScriptCanvas/ScriptCanvas_PreUpdateEvent.scriptcanvas
- AutomatedTesting/ScriptCanvas/ScriptCanvas_ShapeCast.scriptcanvas
Converted the following tests:
- ScriptCanvas_PostUpdateEvent 
- ScriptCanvas_PreUpdateEvent 
- ScriptCanvas_ShapeCast
Here are commands used for testing:
```
python\python.cmd -m pytest AutomatedTesting\Gem\PythonTests\Physics\TestSuite_Periodic.py::TestAutomation::test_ScriptCanvas_PostUpdateEvent --build-directory windows_vs2019\bin\profile
```
```
python\python.cmd -m pytest AutomatedTesting\Gem\PythonTests\Physics\TestSuite_Periodic.py::TestAutomation::test_ScriptCanvas_PreUpdateEvent --build-directory windows_vs2019\bin\profile
```
```
python\python.cmd -m pytest AutomatedTesting\Gem\PythonTests\Physics\TestSuite_Periodic.py::TestAutomation::test_ ScriptCanvas_ShapeCast --build-directory windows_vs2019\bin\profile
```
```
python\python.cmd -m pytest …
```
> Convert ScriptCanvas_* automated tests to use prefab system

- Gems/Atom/Tools/MaterialEditor/Code/Source/MaterialEditorApplication.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorWindow.cpp
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.cpp
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleApplication.cpp
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.cpp
automatically updating the document extension to shader variant list when opening from a shader source file
> Atom Tools: fixing issues opening and saving documents in shader management console

- Gems/MotionMatching/Code/Source/BlendTreeMotionMatchNode.cpp
- Gems/MotionMatching/Code/Source/BlendTreeMotionMatchNode.h
- Gems/MotionMatching/Code/Source/Feature.h
- Gems/MotionMatching/Code/Source/MotionMatchingInstance.cpp
- Gems/MotionMatching/Code/Source/MotionMatchingInstance.h
- Gems/MotionMatching/Code/Source/MotionMatchingSystemComponent.cpp
- Gems/MotionMatching/Code/Source/TrajectoryQuery.cpp
- Gems/MotionMatching/Code/Source/TrajectoryQuery.h
* Using the updated time for calculating the joint velocities
* Force use target facing direction if joystick is in dead-zone
* Added new port to MM anim graph node for using the target facing direction
> Motion Matching: Use facing direction option + a few fixes

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentApplication.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/CreateDocumentDialog.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/ViewportSettingsInspector/ViewportSettingsInspector.cpp
This will display the absolute filepath of the document being created instead of just the file name.
This also fixes a bug where /Assets was being added twice to the default create document path.
> Atom Tools: displaying full file path in create document dialog plus bug fixes

- Code/Framework/AzCore/AzCore/Name/NameDictionary.h
- Gems/Atom/Tools/CMakeLists.txt
- Gems/Atom/Tools/ShaderManagementConsole/CMakeLists.txt
- Gems/Atom/Tools/ShaderManagementConsole/Code/CMakeLists.txt
- Gems/Atom/Tools/ShaderManagementConsole/gem.json
- Gems/Atom/Tools/ShaderManagementConsole/preview.png
- Gems/Atom/gem.json
- Gems/AtomLyIntegration/AtomBridge/Code/CMakeLists.txt
- Gems/AtomLyIntegration/AtomBridge/gem.json
ME project configuration has changed over time, going back and forth between being a gem and not.
SMC is a lesser known tool and was probably missed whenever those changes were made.
The goal of this change is to make them consistent and for other tools to follow the same pattern.
If the method for including one changes then they should all change.
> Atom Tools: Making SMC project/gem configuration and inclusion match ME

- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorHelpers.cpp
Restores previous behavior for editor helpers - makes them always visible, while the current editor hides them if they're owned by entities in a closed prefab. Behavior for icons stay the same (icons are only shown for entities that are actually directly selectable).
Before
After
Will discuss the change with UX before this is submitted.
FYI @rainbj @amzn-leenguy
> Focus Mode | Show helpers even when they're not selectable, but keep the current behavior for icons.

- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
CTRL+G starts 3x faster when using editorsv_hidden=true and editorsv_rhi_override=null compared to default setting.
On my machine SampleBase level in o3de-multiplayersample launches in 5 seconds with hidden and rhi=null, and 15 seconds without these settings. 
> Added editorsv_hidden switch.

- Gems/ScriptCanvas/Assets/TranslationAssets/Nodes/Math_StringToNumber.names
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Math/MathGenerics.h
Found an issue with the StringToNumber Script Canvas node where it doesn't accept any input. Got the following error when added this node to a graph:
`[Error] (ScriptCanvas) - NodeFunctionGenericMultiReturn failed to add a required data slot`
Verified that the node worked as expected with this PR.
Before:
After:
> Fix the StringToNumber Script Canvas node

- Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/MemoryStatistics.h
- Gems/Atom/RHI/Code/Source/RHI/FrameScheduler.cpp
- Gems/AtomLyIntegration/AtomViewportDisplayInfo/Code/Source/AtomViewportDisplayInfoSystemComponent.cpp
- Gems/AtomLyIntegration/AtomViewportDisplayInfo/Code/Source/AtomViewportDisplayInfoSystemComponent.h
This commit modifies `FrameScheduler::EndFrame` to collect basic memory
statistics unconditionally unless more details statistics are requested.
This operation is O(N) in the number of resource pools available which
doesn't amount to more than a dozen or so so this has no measurable
impact on frame time.
The line display changes color to yellow and red depending on usage
relative to VRAM available on the current physical device.
> Add VRAM usage metrics to viewport debug display

- AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_AutoComponent_NetworkInput.py
Removing RemoteConsole for Multiplayer Test because it's flaky; replacing it with the Trace ebus.
Tested by rerunning Multiplayer pytests and seeing success
Resolves Issue https://github.com/o3de/o3de/issues/7795
> Multiplayer RPC Test Removing Flaky RemoteConsole

- Gems/AtomContent/CMakeLists.txt
- Gems/AtomContent/ReferenceMaterials/CMakeLists.txt
- Gems/AtomContent/Sponza/CMakeLists.txt
The AtomContent_Sponza and AtomContent_ReferenceMaterials CMake targets
have been updated to match the names of the Gems.
This allows using the gems in the enabled_gems.cmake list to activate
the gem variants based off of the name Sponza and ReferenceMaterials.
relates https://github.com/o3de/o3de-atom-sampleviewer/pull/365
> Updating the Sponza and ReferenceMaterials CMake targets.

- Code/Framework/AzCore/AzCore/RTTI/AzStdOnDemandReflection.inl
- Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/MethodConfiguration.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/MethodOverloaded.cpp
The main purpose is to fix scriptcanvas container node naming issue and warning message, which leads to different issues have to solve:
1. BehaviorContext metadata parameters array size offset because of method invoker (class) type, credit to @lumberyard-employee-dm for his big help with this fix.
Introducing a new Method overload function for this use case which user can specify class type metadata explicitly. (it helps to avoid backward incompatible issue)
2. MethodOverload node deserialize process misses base node structure which causes method node lookup and refresh complain slot is not part of the node.
Move base node deserialize at the beginning to make sure node slot and cache is constructed at the beginning from file.
3. [Minor] MethodConfiguration argument default naming is hard …
> Fix container node naming issue and warning message

- Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/PrefabBenchmarkFixture.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/PrefabBenchmarkFixture.h
- Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/Propagation/SingleInstanceMultipleEntityBenchmarks.cpp
- Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
Added propagation benchmarks for adding, removing and updating component. These can be used to identify how long it will take to update a prefab with a large number of entities. 
```
Run on (20 X 3312 MHz CPU s)
CPU Caches:
L1 Data 32K (x10)
L1 Instruction 32K (x10)
L2 Unified 1048K (x10)
L3 Unified 14417K (x1)
----------------------------------------------------------------------------------------------------------------------
Benchmark                                                                            Time             CPU   Iterations
----------------------------------------------------------------------------------------------------------------------
SingleInstanceMultipleEntityBenchmarks/PropagateUpdateComponentChange/100         24.6 ms         22.9 ms           28 …
```
> Add propagation benchmarks for adding, removing and updating component 

- Code/Framework/AzCore/AzCore/std/containers/vector.h
The introduction of #5735 exposed a case where undefined behaviour was being allowed to occur in the range based version of `AZStd::vector::erase`.  This was discovered in the Profiler gem ImGui visualizer through the use of `AZStd::upper_bound` not finding the desired value and returning `begin()` thus producing `vector::erase(begin(), begin())`.  Rather than patching that instance (#8306), this change is to fix the root issue.
> [development] prevent the move operation in AZStd::vector::erase when the start/end iterators are the same

- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorVisibleEntityDataCache.cpp
If runtime shape components with debug drawing are spawned in the Editor (for example thru the dynamic vegetation system), they weren't previously being drawn. This was due to the fact that debug drawing in the Editor outside of game mode in controlled through Editor entity visibility, which queries the EditorEntityInfo to see if the entity is visible. Runtime entities don't have EditorEntityInfo, so they were invisible by default. This change makes them visible but not selectable.
> Fix runtime shape drawing in Editor.

- Templates/AssetGem/Template/Registry/assetprocessor_settings.setreg
- Templates/CppToolGem/Template/Registry/assetprocessor_settings.setreg
- Templates/DefaultGem/Template/Registry/assetprocessor_settings.setreg
- Templates/DefaultProject/Template/Gem/Registry/assetprocessor_settings.setreg
- Templates/DefaultProject/Template/Registry/assetprocessor_settings.setreg
- Templates/MinimalProject/Template/Gem/Registry/assetprocessor_settings.setreg
- Templates/MinimalProject/Template/Registry/assetprocessor_settings.setreg
- Templates/PythonToolGem/Template/Registry/assetprocessor_settings.setreg
The templates had the ScanFolder entries under the incorrect key of
"/Amazon/AssetProcessor" instead of "/Amazon/AssetProcessor/Settings".
> Fixed nesting of Settings for the AssetProcessor in Templates

- Code/Legacy/CryCommon/ISystem.h
- Code/Legacy/CrySystem/DllMain.cpp
Game and server launches failed to compile in release mode with -DLY_MONOLITHIC_GAME=ON
#Fixes #8308
```
Launcher.Static.lib(unity_0_cxx.obj) : error LNK2019: unresolved external symbol __imp_CreateSystemInterface referenced in function "enum O3DELauncher::ReturnCode __cdecl O3DELauncher::Run(struct O3DELauncher::PlatformMainInfo const &)" (?Run@O3DELauncher@@YA?AW4ReturnCode@1@AEBUPlatformMainInfo@1@@Z)
```
> Fixes linking issues with game and server launchers in release monolithic mode

- Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiGpuProfiler.h
- Gems/Atom/Utils/Code/Source/ImGuiGpuProfiler.cpp
This commit provides an ImGUI-based interface to save allocation data to
file in the `.o3de/Logs/MemoryCaptures` path and load captures taken
previously.
The "GPU Memory Profiler" window has two new buttons: "Save to CSV" and "Load from CSV" as shown below:
Initially, if no captures are available, hitting the "Load from CSV" button will display the following dialog:
When hitting "Save to CSV" a capture will be taken unless an active capture already exists, in which case a timestamp marked file will be saved to `.o3d3/Logs/MemoryCaptures`. If memory captures exist in that folder, they will display in the selection dialog when "Load from CSV" is pressed as below:
After selection of a CSV capture, data will be viewable as with a runtime capture, with an additional text message "Viewing data …
> Add Atom memory CSV capture save and load

- Code/Tools/ProjectManager/Source/Application.cpp
Tested on Ubuntu 20. Also tested on Windows to ensure the icon was still set properly there.
> [Linux] Set Icon for Project Manager Executable

- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponentsLevel_DisplayMapperAdded.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DisplayMapperAdded.py
Display Mapper LUT access updated to a valid LUT
P1 tests added to both game and level component versions of Display Mapper
currently it is not possible to set type or load a preset, but work-arounds have been used in these tests.
.\python\python.cmd -m pytest --build-directory atom_dev/bin/profile  .\AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Main.py
================================================= test session starts
platform win32 -- Python 3.7.12, pytest-5.3.2, py-1.11.0, pluggy-0.13.1
rootdir: D:\workspace\o3de, inifile: pytest.ini
collected 29 items
AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Main.py ..............................[100%]
================================================== warnings summary …
> Display Mapper P1 test expansion

- Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/AzManipulatorTestFrameworkTestHelpers.h
- Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/DirectManipulatorViewportInteraction.h
- Code/Framework/AzToolsFramework/Tests/ManipulatorCoreTests.cpp
This PR add a new Mixin type (`DirectCallManipulatorViewportInteractionFixtureMixin`) to compliment `IndirectCallManipulatorViewportInteractionFixtureMixin`. This is so Manipulators can be tested without the need for a `ToolsApplication` instance.
```
Note: Google Test filter = ManipulatorCore*
[==========] Running 4 tests from 2 test cases.
[----------] 3 tests from ManipulatorCoreFixture
[ RUN      ] ManipulatorCoreFixture.AllEntityIdComponentPairsRemovedFromManipulatorAfterRemoveEntity
[       OK ] ManipulatorCoreFixture.AllEntityIdComponentPairsRemovedFromManipulatorAfterRemoveEntity (4 ms)
[ RUN      ] ManipulatorCoreFixture.EntityIdComponentPairRemovedFromManipulatorAfterRemoveEntityComponentId
[       OK ] …
```
> Manipulator Test Framework Updates

- Tools/LyTestTools/ly_test_tools/_internal/managers/abstract_resource_locator.py
- Tools/LyTestTools/ly_test_tools/environment/file_system.py
- Tools/LyTestTools/tests/unit/test_abstract_resource_locator.py
- Tools/LyTestTools/tests/unit/test_file_system.py
Fixes an edge case when a relative build directory that exists in the project folder is provided to LyTestTools.
Tested the bug locally and ran unit tests.
> Lytesttools project path bug fix

- Gems/MotionMatching/Code/Source/FeatureVelocity.cpp
- Gems/MotionMatching/Code/Source/FeatureVelocity.h
- Gems/MotionMatching/Code/Source/MotionMatchingInstance.cpp
- Gems/MotionMatching/Code/Source/MotionMatchingInstance.h
- Gems/MotionMatching/Code/Source/MotionMatchingSystemComponent.cpp
* Added new helper to render the query pose and joint velocities (input pose for the motion matching search)
* Added CVAR to enable/disable usage of the Kd-tree and switch between brute-force search and using the acceleration structure.
* Added CVAR to enable/disable all debug visualizations.
* Added new helper function to render joint velocities based on a given pose, rather than always using the current character pose.
https://user-images.githubusercontent.com/43751992/158770690-76abd4fb-3e44-4748-b007-6e257355c592.mp4
Current CVARs for motion matching:
> Motion Matching: Added query pose and query joint velocity debug visualization and new CVARs for debug rendering control

- AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py
Update Multiplayer tests to store their cached level assets (which contains the spawnable player and scripts) inside the test artifacts. This way we can compare assets if any tests become flaky
Level cache is around 140KB per test, but gets compressed and stored around 30KB
Tested by running AutomatedTesting for multiplayer and seeing the newly add level folders inside the TestResults artifacts.
> Update Multiplayer Tests to Store their Cached Folder Level Assets

- Code/Framework/AzCore/AzCore/std/parallel/thread.h
- Code/Framework/AzCore/Platform/Linux/AzCore/std/parallel/internal/thread_Linux.cpp
- Code/Framework/AzFramework/AzFramework/Network/AssetProcessorConnection.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/SourceControl/PerforceComponent.cpp
- Code/Tools/AssetProcessor/native/tests/AssetProcessorMessagesTests.cpp
pthread only supports a thread name up to 15 characters + null terminator.
Consequently, if the user code was providing a name that was too long, it
would get the default "AZStd::thread" name. This change uses an elided
name, removing characters from the middle of the name, so that it fits
within the 16 byte limit. The decision to elide the middle was made so that
threads can be named with trailing numbers, and the number will be retained
in the thread's name.
> [Linux] Improve thread name support

- Gems/AtomLyIntegration/AtomViewportDisplayInfo/Code/Source/AtomViewportDisplayInfoSystemComponent.cpp
Added Editor viewport resolution and pipeline MSAA state.
Added RPI AssetStreamingImagePool usage.  This is rendered in red if the pool is close to capacity.
Tested Editor DX12/Vulkan.
> Add Resolution, MSAA, and RPI AssetStreamingImagePool usage to the Editor ImGui overlay

- Code/Framework/AzCore/AzCore/Math/MathUtils.h
- Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphNode.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeAccumTransformNode.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeSmoothingNode.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeTransformNode.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/KeyTrackLinearDynamic.h
- Gems/EMotionFX/Code/EMotionFX/Source/KeyTrackLinearDynamic.inl
- Gems/EMotionFX/Code/EMotionFX/Source/Pose.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/SpringSolver.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/Transform.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendSpace1DNodeWidget.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendSpace2DNodeWidget.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendSpaceNodeWidget.cpp
- Gems/Gestures/Code/Include/Gestures/GestureRecognizerPinch.h
- Gems/Gestures/Code/Include/Gestures/GestureRecognizerRotate.h
- Gems/MotionMatching/Code/Source/TrajectoryHistory.cpp
I replaced the usage of MCore::LinearInterpolate with AZ::Lerp. Any clue if there is a plan to move all the math utilities into Math and how would it be organized? 
MathUtils seems too general I guess would it make sense to split things across different headers and just have MathUtils collect those other referenced headers.
> chore: replace usage of MCore::LinearInterpolate with AZ::Lerp

- Gems/Terrain/Code/Include/Terrain/Ebuses/TerrainAreaSurfaceRequestBus.h
- Gems/Terrain/Code/Source/Components/TerrainHeightGradientListComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainHeightGradientListComponent.h
- Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainSurfaceGradientListComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainSurfaceGradientListComponent.h
- Gems/Terrain/Code/Source/Components/TerrainWorldDebuggerComponent.cpp
- Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.cpp
- Gems/Terrain/Code/Source/EditorComponents/EditorTerrainSurfaceGradientListComponent.cpp
- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.cpp
- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.h
- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystemBus.h
- Gems/Terrain/Code/Tests/TerrainSystemBenchmarks.cpp
Reworked the mutex locking on the terrain components and their ebus definitions so that it is now possible to run simultaneous parallel queries against the components, but they will exclusively lock when being modified or deactivated.
The terrain queries will still immediately block inside of these components on the calls to the GradientRequestBus, but that will be addressed in a future PR.
This also adds a new "Terrain" profile tag so that it's easier to see the Terrain calls in the profiles.
Example PIX captures showing calls inside the components successfully running in parallel, but then getting blocked for most of the call *inside* the functions.
Before:
After:
> Parallel terrain components

- AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/hydra_test_utils.py
Tested tests using **launch_and_validate_results** with the following commands:
```
python\python.cmd -m pytest AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Main_GPU.py::TestMaterialEditor --build-directory windows_vs2019\bin\profile
```
```
python\python.cmd -m pytest AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Main.py::TestMaterialEditorBasicTests --build-directory windows_vs2019\bin\profile
```
```
python\python.cmd -m pytest AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Benchmark_GPU.py::TestPerformanceBenchmarkSuite --build-directory windows_vs2019\bin\profile
```
```
python\python.cmd -m pytest AutomatedTesting\Gem\PythonTests\scripting\TestSuite_Periodic.py::TestAutomation --build-directory windows_vs2019\bin\profile
``` 
Signed-off-by: chiyenteng …
> Remove enable_prefab_system option from hydra_test_utils.launch_and_validate_results

- Gems/MotionMatching/Code/Source/Feature.h
- Gems/MotionMatching/Code/Source/FeatureTrajectory.cpp
- Gems/MotionMatching/Code/Source/FeatureVelocity.cpp
- Gems/MotionMatching/Code/Source/MotionMatchingData.cpp
- Gems/MotionMatching/Code/Source/MotionMatchingData.h
- Gems/MotionMatching/Code/Source/MotionMatchingInstance.cpp
- Gems/MotionMatching/Code/Source/MotionMatchingSystemComponent.cpp
- Gems/MotionMatching/Code/Source/PoseDataJointVelocities.cpp
- Gems/MotionMatching/Code/Source/PoseDataJointVelocities.h
* Multi-threaded feature extraction using the job system as well as the task graph.
* The pose pool is not multi-thread safe. We added a pose pool parameter to the extraction context to control the pool usage manually.
* Rather than using the default pose pool for the given actor instance, we now use the given pose pool from the context when calculating the features.
* Features are now separated into batches and then extracted simultaneously, each job/task having its own pose pool.
* Added CVAR to enable/disable multi-threaded feature extraction.
Extracting features for 36k frames / 20mins motion database previously took ~6425ms and now takes around ~280ms using a 32-core Threadripper, 23x speedup.
> Motion Matching: Multi-threaded feature extraction

- Gems/ScriptCanvas/Code/Editor/View/Widgets/ScriptCanvasNodePaletteDockWidget.cpp
- Gems/ScriptCanvas/Code/Tools/TranslationGeneration.cpp
After Gem filesystem alias change, it is not required to check against cmake target name, instead we can look for gem name directly.
Tested by generating and exploring translation file, both cases can route to correct translation asset directory.
> Fix translation file path

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Sandbox.py
Possible race condition because it passed in the AR to enable the Linux tests.
> Sandboxing shader reload Linux test to investigate why its sometimes failing.

- Code/Framework/AzQtComponents/AzQtComponents/Components/WindowDecorationWrapper.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Tests/WindowDecoratorWrapperTests.cpp
- Code/Framework/AzQtComponents/AzQtComponents/azqtcomponents_testing_files.cmake
Fixes a bug in WindowDecorationWrapper on X11 Window server based systems where guest widget constrains are not checked when resizing the window.
Also adds a test to check for this.
Closes #5369
> [Linux] Fix No Minimum Size For Project Manager

- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_OcclusionCullingPlaneAdded.py
adds a couple of property toggle tests and uniform scale of the entity transform for P1 tests for Occlusion Culling Plane component.
Report:
[SUCCESS] Success: Occlusion Culling Plane Entity successfully created
[SUCCESS] Success: Entity has a Occlusion Culling Plane component
[SUCCESS] Success: Show Visualization property set
[SUCCESS] Success: Show Visualization property set
[SUCCESS] Success: Transparent Visualization property set
[SUCCESS] Success: Transparent Visualization property set
[SUCCESS] Success: Occlusion Culling Plane entity scaled as expected
[SUCCESS] Success: Entity is …
> Occlusion Culling Plane component P1 null render test expansion

- Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedSurface_ForwardPass.azsli
- Gems/Atom/Feature/Common/Assets/Materials/Types/Skin.azsl
- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/BackLighting.azsli
- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lighting/LightingData.azsli
- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/DirectionalLight.azsli
- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/DiskLight.azsli
- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/PointLight.azsli
- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Surfaces/TransmissionSurfaceData.azsli
Some of the parameters introduced in https://github.com/o3de/o3de/pull/6428 (`shrinkFactor`,`transmissionNdLBias`,`distanceAttenuation`) were stored in both `surface.transmission.transmissionParams` and `LightingData` structures. 
The context in which these were used had both structures available, so the parameters can be removed from one of the structures. In this case, it makes more sense to remove it from `LightingData`, since these are surface specific properties, and also to reduce the number of useless registers in `LightingData`, because a non-transmissive material is not going to use them.
Signed-off-by: Santi Paprika <santi.gonzalez@huawei.com>
> Remove redundant transmission parameters from LightingData

- Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
Noticed override was missing for autocomponent's RpcStructs that derive from `IRpcParamStruct` which has single abstract method [serialize](https://github.com/o3de/o3de/blob/5acb360fbb986d624855fba68c2ec1b3158432b5/Gems/Multiplayer/Code/Include/Multiplayer/NetworkEntity/NetworkEntityRpcMessage.h#L111) method.  Fixes potential compiler warning.
* Built Editor, Server and Launcher.
* Ran unit tests
> Add missing override to auto generated RpcStructs deriving from IRpcParamStruct

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/RenderViewportWidget.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp
- Add support to properly transition from an old swapchain to a new swapchain. This involved deleting the old swapchain properly
- Add support to handle surface destruction by Qt.
- Add support to handle missed resize event after changes to surface dimensions
> Vulkan Swapchain related fixes.

- cmake/3rdParty/Platform/Android/BuiltInPackages_android.cmake
- cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake
- cmake/3rdParty/Platform/Linux/OpenSSL_linux.cmake
- cmake/3rdParty/Platform/Linux/cmake_linux_files.cmake
- cmake/3rdParty/Platform/Mac/BuiltInPackages_mac.cmake
- cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
- cmake/3rdParty/Platform/iOS/BuiltInPackages_ios.cmake
On Linux, O3DE will use the system default OpenSSL instead of shipping the OpenSSL package since the system default library gets kept up to date by the Linux community whenever there’s a security problem. Note that O3DE 3rd party system will still ship OpenSSL packages for all the other platforms (Windows, Mac, Android and iOS).
Test Done:
- Built MultiplayerSample successfully on Linux
- Ran AzNetworking tests on Linux
- Tested the client and server connection via self-signed cert using MultiplayerSample (Linux client -> Windows server). Connection was established successfully and got the "Certificate validation passed" message. The linux game launcher crashed due to some other unrelated asset issues after connected. …
> Use system default OpenSSL on Linux

- AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Main.py
- AutomatedTesting/Gem/PythonTests/Physics/tests/force_region/ForceRegion_PrefabFileInstantiates.py
- AutomatedTesting/Gem/PythonTests/automatedtesting_shared/base.py
- Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
Remove enable_prefab_system option from the following automated test helper classes/functions:
- EditorTestSuite::_exec_editor_test
- EditorTestSuite::_exec_editor_multitest
- TestAutomationBase::_run_test
Also remove slice related terms in ForceRegion_SliceFileInstantiates.
> Remove enable_prefab_system option from all automated test frameworks

- .github/ISSUE_TEMPLATE/config.yml
config.yml provides a mechanism to fine tune issue reporting. See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
Change:
* Removes blank issue report (Discussed at TSC by @forhalle)
* Adds link to security vulnerability reporting (https://github.com/o3de/o3de/issues/6804, discussed at TSC)
* Adds handy link for docs issues reporting (@sptramer)
> Provide config.yml to provide control over GitHub issue templates. Disable blank issues, add security and docs reporting links.

- Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
- Tools/LyTestTools/tests/unit/test_o3de_editor_test.py
Clarified wording of assert message to direct the user to issues in previous tests. Also cleaned up some minor test formatting. Tested by running unit tests.
> Clarifying unknown results in LyTestTools parallel editor tests

- AutomatedTesting/Gem/PythonTests/Physics/TestSuite_InDevelopment.py
- AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Periodic.py
- AutomatedTesting/Gem/PythonTests/Physics/tests/script_canvas/ScriptCanvas_SpawnEntityWithPhysComponents.py
- AutomatedTesting/Levels/Physics/ScriptCanvas_SpawnEntityWithPhysComponents/Ball_0.prefab
- AutomatedTesting/Levels/Physics/ScriptCanvas_SpawnEntityWithPhysComponents/ScriptCanvas_SpawnEntityWithPhysComponents.prefab
- AutomatedTesting/ScriptCanvas/ScriptCanvas_SpawnEntityWithPhysComponents.scriptcanvas
Manually converting ScriptCanvas_SpawnEntityWithPhysComponents to work with prefabs.
First I created a new prefab level with Terrain entity that I reparented to Level, renamed it to terrain, and added a Physix Collider and terrain data.
Created a Ball_0 entity, added a Physx Collider, Physx Rigid Body, and a Sphere Shape with the appropriate values. Afterwards, I turned that entity into a Prefab.
Created a Spawn_Node entity and added a script canvas node to it.
Updated ScriptCanvas_SpawnEntityWithPhysComponents.scriptcanvas to work with the new prefab spawning system over the slice spawner.
Added the test to the periodic suite from previously not being added to any suite.
Testing performed:
Executed automated testing 5 times in a row with successful results. 
`
python\python.cmd -m pytest …
> Convert ScriptCanvas_SpawnEntityWithPhysComponents to work with Prefabs

- Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.cpp
This was causing the materials to intermittently not show up. The region comparisons needed to use a 2D AABB check instead of a 3D one with height set to 0, because the camera height could cause the checks to fail.
> Surface materials weren't checking regions correctly.

- Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
Fixes a PyTest warning due to PyTest trying to collect 'TestData' because it has 'Test' in the name, but it doesn't need to collect it. Because TestData has an _ init _ method, PyTest cannot collect the test anyways.
In response to #8452.
Tested by running PyTest and seeing the warning no longer appears.
> Fixes PyTest Warning: Cannot Collect Test Class 'TestData'

- SECURITY.MD
Provide an initial SECURITY.md file for O3DE
Documentation referenced in change is in this PR: https://github.com/o3de/o3de.org/pull/1431. Will not push this change until security page is live on o3de.org
Issue reporting changes to discourage reporting via GHI: https://github.com/o3de/o3de/pull/8040
Having a security.md is a recommended best practice for open source projects. See:
* https://github.com/o3de/o3de/issues/6805 
* https://github.com/ossf/oss-vulnerability-guide/blob/main/guide.md
* https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository - SECURITY.md will get picked up and displayed as the security policy for the project.
> Provide initial SECURITY.md for O3DE

- Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.h
- Code/Framework/AzFramework/Tests/Platform/Common/Xcb/XcbInputDeviceMouseTests.cpp
XCB_BUTTON_INDEX_2 corresponds with the middle mouse button, and INDEX_3
to the right button, not the other way around. Verified with `xev`.
Fixes #7342 .
> [XCB] Fix swapped mouse button assignments

- AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Utils.py
- AutomatedTesting/Levels/Physics/Physmaterial_Editor_Test/Physmaterial_Editor_Test.prefab
- AutomatedTesting/Levels/Utils/Tracer_ErrorEntity/Tracer_ErrorEntity.prefab
- AutomatedTesting/Levels/Utils/Tracer_WarningEntity/Tracer_WarningEntity.prefab
Add physics automated test **test_UtilTest_Tracer_PicksErrorsAndWarnings** back into **TestSuite_Utils.py**, and convert the test levels **Tracer_WarningEntity** and **Tracer_ErrorEntity** into prefab format. This test passed after the conversion.
Also convert test level **Physmaterial_Editor_Test** but the test **UtilTest_Physmaterial_Editor** is still failing.
Using the following command for testing:
```
python\python.cmd -m pytest AutomatedTesting\Gem\PythonTests\Physics\TestSuite_Utils.py --build-directory windows_vs2019\bin\profile
```
> Fix/Convert physics automated tests from TestSuite_Utils

- cmake/3rdParty/Platform/iOS/BuiltInPackages_ios.cmake
Verified the iOS package using MultiplayerSample. Was able to connect iOS client and Windows server using self-signed cert.
> Update the iOS OpenSSL package used by O3DE

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Grid/GridComponentController.cpp
This prevents warnings or errors when the grid size is less than or equal to 0
> Don't render grid component if size <= 0

- Gems/PhysX/Code/Source/Module.cpp
- Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderDataSystem.cpp
- Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderDataSystem.h
The Script Canvas Builder didn't disconnect from busses leading
to a lock-up on builder shut down.
The PhysX module didn't declare its allocator type, resulting in a
random crash occuring during initialization, becuase at random it would
be allocated on an 8 byte instead of 16 byte boundary, resulting in
SIMD-alignment failures.
fixes #8614 
fixes #8613 
> Fix a couple crashes in MacOS Editor / builders

- Code/Framework/AzCore/Platform/Common/VisualStudio/AzCore/Natvis/azcore.natvis
Just a set of debug visualizers, no behavior changes.
Also shows m_view for `AZ::Name`
DPE row in VS debugger before:
DPE row in VS debugger after:
Signed-off-by: Nicholas VanSickle <nvsickle@amazon.com>
> Add Generic DOM natvis support

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/MethodConfiguration.cpp
as string_view doesn't have conversion to char*, and we can't guarantee there is always terminated string previous step
using string instead
> Fix corrupted default name

- Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignment.cpp
- Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignmentSerializer.cpp
Updating the material assignment serializer to include model UV overrides
JSON serializer does a basic conversion to and from a map of strings
> Material Component: fix prefab serialization for model UV overrides

- Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.cpp
The priority of behavior context node category name:
translation file -> behavior context metadata -> default category name
As the change impact ScriptCanvas Editor node palette, manually verified node palette look
> Consolidate default category name for behavior context node

- Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/Debug/Trace_UnixLike.cpp
I got a failure for Android release build since the MaxMessageLength and MaxStackLines variables are unused if AZ_ENABLE_DEBUG_TOOLS is not defined. This PR move the definition of these two variables into the #if defined(AZ_ENABLE_DEBUG_TOOLS) block.
> Fix the Android release build failure caused by unused variables

- Gems/AWSClientAuth/CMakeLists.txt
- Gems/AWSCore/CMakeLists.txt
- Gems/AWSGameLift/CMakeLists.txt
- Gems/AWSMetrics/CMakeLists.txt
Previously, CDK projects associated with the AWS gems were not being included in the `INSTALL` target, making it much harder to get started with these gems if working from an installer version of the engine (vs. source). This change updates CMAKE to include them as part of `INSTALL`.
Example: AWSCore built by `INSTALL` _before_:
...and AWSCore built by `INSTALL` _after_:
> Add AWS cdk dirs to install output

- .github/CODEOWNERS
Any changes to those areas of code will add the o3de/sig-core-maintainers and
o3de/sig-core-reviewers groups to any PRs being merge to the o3de protected branches
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
> Adding sections of code which SIG-Core group owns

- Code/Tools/RemoteConsole/Core/RemoteConsoleCore.cpp
Calling to the GetILevelSystem() API will cause an [assert](https://github.com/o3de/o3de/blob/development/Code/Legacy/CrySystem/LevelSystem/SpawnableLevelSystem.cpp#L153) when the prefab system is enabled, which causes the termination of O3DE application. This PR adds a checking for the prefab system to avoid the assert.
> Avoid assert from RemoteConsoleCore when use the prefab system

- cmake/3rdParty/Platform/Android/BuiltInPackages_android.cmake
Verified the Android OpenSSL library indirectly by testing AWS Native SDK built with this upgraded OpenSSL library on Android.
> Update O3DE to use new version of Android OpenSSL

- Templates/DefaultProject/Template/Gem/enabled_gems.cmake
Fixes #7478
After this change, the Multiplayer gem is no longer enabled in the DefaultProject template.
- Re-installed Windows in undersea laboratory clean room under the watchful eye of the Kraken.
- Hot-swapped cryo-frozen RAM modules during solar flare event while generating new DefaultProject at precisely 2/22/2022 22:22:22 and verified generation completed successfully in double-blind presidential run-off
- Made a coffee
> Remove Multiplayer Gem from DefaultProject Template

- Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainMacroMaterialManager.cpp
- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.cpp
This fixes a few bugs I ran into while testing out some custom terrain components:
* Fixed multiple out-of-bounds data accesses that occur if bounding box regions are small enough that they cause 0 points to be queried.
* Fixed order-of-initialization bugs with the macro material manager where asserts would trigger if macro material entities started up in certain specific orders relative to the macro material manager.
> Misc terrain bugfixes

- Gems/EMotionFX/Code/Tests/SystemComponentFixture.h
This was first fixed in commit 7a9520bd0264f68ba50466ac3bf8586405615701,
but the change in behavior to load the asset catalog in
AzFramework::Application instead of LmbrCentral in commit
3b9384f1e63fcef2605ad904976f413b11a6ed20 reintroduced loading the
AssetCatalog in the EMotionFX tests.
> Do not load the asset catalog in EMotionFX tests

- Code/Editor/EditorPreferencesPageViewportManipulator.cpp
- Code/Editor/Lib/Tests/test_ViewportManipulatorController.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/LinearManipulator.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportSettings.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportSettings.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
- Code/Framework/AzToolsFramework/Tests/EditorTransformComponentSelectionTests.cpp
This PR adds the ability to hold Ctrl and drag the `ScaleManipulator` to change the size of it (much as you can hold Ctrl and move the `TranslationManipulator` and `ScaleManipulator` without moving the Entity.
https://user-images.githubusercontent.com/82228511/161104601-63f10a7f-ce5f-43b1-ac4d-357130a22301.mp4
```
[----------] 1 test from EditorTransformComponentSelectionScaleManipulatorInteractionTestFixture
[ RUN      ] EditorTransformComponentSelectionScaleManipulatorInteractionTestFixture.UsingScaleManipulatorWithCtrlHeldAdjustsManipulatorBaseViewScale
[       OK ] EditorTransformComponentSelectionScaleManipulatorInteractionTestFixture.UsingScaleManipulatorWithCtrlHeldAdjustsManipulatorBaseViewSc …
```
> Adjust manipulator scale using scale manipulator

- Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/QComponentEntityEditorMainWindow.cpp
Gave the Entity Inspector window an object name so it can be found easier in automated testing.
> Gave Entity Inspector window an object name

- Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
- Tools/LyTestTools/tests/unit/test_o3de_editor_test.py
Tested by collecting a crash artifact locally and ran unit tests.
> Save crash artifacts in LyTestTools

- Gems/LyShineExamples/Code/Source/UiCustomImageComponent.cpp
Fixes https://github.com/o3de/o3de/issues/8671
> Adds a nullptr check for sprite in UiCustomImageComponent

- Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.cpp
- Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Utils/BehaviorContextUtils.cpp
- Gems/ScriptCanvasTesting/Assets/ScriptCanvas/UnitTests/LY_SC_UnitTest_GlobalMethodsCheckedOperation.scriptcanvas
- Gems/ScriptCanvasTesting/Code/Source/ScriptCanvasTestBus.cpp
- Gems/ScriptCanvasTesting/Code/Source/ScriptCanvasTestBus.h
- Gems/ScriptCanvasTesting/Code/Tests/ScriptCanvas_GlobalMethods.cpp
- Gems/ScriptCanvasTesting/Code/scriptcanvastestingeditor_tests_files.cmake
In order to support pre/post check for global method, need to process CheckedOperation and BranchOnResult scriptcanvas attributes. (we have similar feature supported on class method already)
Context: Instead of doing a check method before/after method node separately, we support to combine the check method and method into the same node.
added new test case
> Add check operation to global method

- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/NodePalette/Model/NodePaletteSortFilterProxyModel.cpp
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/NodePalette/Model/NodePaletteSortFilterProxyModel.h
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/NodePalette/NodePaletteTreeView.cpp
Sort the search result to help find target node easier
Logic:
if item has children, we check against the minimum sorting score from its children including itself
if item has no children, we just check against with its own sorting score
Sorting score logic:
1. item string match with filter, return -1
2. item string contains filter or filter regex, return item string length (assume shorter name has stronger relevance)
3. if none, return max int
https://user-images.githubusercontent.com/5900509/161163442-1ccb374f-cad9-4123-ba7c-b81bd047f808.mp4
> Sort search result by relevance to filter text

- Code/Framework/AzCore/AzCore/EBus/BusImpl.h
- Code/Framework/AzCore/AzCore/EBus/EBus.h
- Code/Framework/AzCore/AzCore/EBus/EBusSharedDispatchMutex.h
- Code/Framework/AzCore/AzCore/EBus/EBusSharedDispatchTraits.h
- Code/Framework/AzCore/AzCore/EBus/Policies.h
- Code/Framework/AzCore/AzCore/azcore_files.cmake
- Code/Framework/AzCore/Tests/EBus/EBusSharedDispatchMutexTests.cpp
- Code/Framework/AzCore/Tests/azcoretests_files.cmake
EBus currently supports LocklessDispatch, which enables the dispatch to run without any locks, while still keeping locks on BusConnect and BusDisconnect. This ensures that Connect/Disconnect are safe from each other, but it does not provide safety for a BusConnect / BusDisconnect call that occurs while a dispatch is in progress (or vice versa). It will assert in this scenario, but doesn't prevent it.
The goal here is to provide a means of using an EBus that still allows for parallel dispatches but also blocks the dispatches vs BusConnect / BusDisconnect. The theoretical solution is to use an EBus MutexType of shared_mutex, but this doesn't quite work in practice since there are some nuances required to handle the different types of locking and nested locking, and there's no one single …
> Add EBus support for shared_mutex

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_GPU.py
- AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py
- Code/Framework/AtomCore/Tests/InstanceDatabase.cpp
Changed AtomCore C++ tests to run for iterations instead of a duration, reducing total test module runtime from 109446ms to 723ms (99.3% reduction). Left in a change to test helper functions passing const&'s, which was a negligible improvement. Commented out test debugging statements.
Found this bottleneck while profiling the test suites.
Also fixes some inaccurate comments used by Atom Python-based tests.
Signed-off-by: Sean Sweeney <sweeneys@amazon.com>
> reduce atom test duration, fix comments

- AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py
- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.cpp
- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.h
- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.h
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Simplify multiplayer editor. Going back to original setup where editor connects and server listens, except this time the editor will keep trying to reconnect if it fails (for example if the server isn't finished launching, or the port isn't available yet)
Tested by:
1) Seeing successful AR python/python.sh -m pytest --build-directory ./AutomatedTesting/build/linux/bin/profile/ ./AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Sandbox.py::TestAutomation
2) Running editor CTRL+G mode
3) Running editor CTRL+G mode and exiting before the server is done loading
4) Running a server by hand and then entering CTLR+G mode
Resolves #8605
> Fix Multiplayer Editor Invalid Connection

- Code/Framework/AzCore/AzCore/Jobs/JobManagerComponent.cpp
- Code/Framework/AzCore/AzCore/Task/TaskGraphSystemComponent.cpp
- Code/Framework/AzCore/AzCore/Threading/ThreadUtils.cpp
- Code/Framework/AzCore/AzCore/Threading/ThreadUtils.h
Processes not marked as the main runtime or editor will have limited
thread slots allocated in the task graph to conserve memory and threads
spawned.
> Limit task graph concurrency on certain processes

- Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArray.cpp
Fixed the decal system to avoid calling BlockUntilLoadComplete on an invalid asset.
Fixed a warning message that was being always suppressed.
See https://github.com/o3de/o3de/issues/8773
> Fixed Decal Error Message

- Code/Tools/AssetProcessor/native/utilities/BuilderManager.cpp
- Code/Tools/AssetProcessor/native/utilities/BuilderManager.inl
This will allow log readers to determine how long the events have taken
so that very long CreateJobs events and their builders can be matched
> {lyn11886} adding logging for building events CreateJobs and Process

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/SurfaceData/SurfaceDataMeshComponent.cpp
- Gems/GradientSignal/Code/Include/GradientSignal/Editor/EditorGradientComponentBase.inl
- Gems/GradientSignal/Code/Include/GradientSignal/GradientSampler.h
- Gems/GradientSignal/Code/Source/Components/GradientSurfaceDataComponent.cpp
- Gems/GradientSignal/Code/Source/Components/SurfaceAltitudeGradientComponent.cpp
- Gems/GradientSignal/Code/Source/Components/SurfaceMaskGradientComponent.cpp
- Gems/GradientSignal/Code/Source/Components/SurfaceSlopeGradientComponent.cpp
- Gems/GradientSignal/Code/Source/Editor/EditorGradientSurfaceDataComponent.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalBenchmarks.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalSurfaceTests.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalTestMocks.h
- Gems/SurfaceData/Code/Include/SurfaceData/SurfaceDataModifierRequestBus.h
- Gems/SurfaceData/Code/Include/SurfaceData/SurfaceDataProviderRequestBus.h
- Gems/SurfaceData/Code/Include/SurfaceData/SurfaceDataSystemRequestBus.h
- Gems/SurfaceData/Code/Include/SurfaceData/Tests/SurfaceDataTestMocks.h
- Gems/SurfaceData/Code/Source/Components/SurfaceDataColliderComponent.cpp
- Gems/SurfaceData/Code/Source/Components/SurfaceDataShapeComponent.cpp
- Gems/SurfaceData/Code/Source/SurfaceDataSystemComponent.cpp
- Gems/SurfaceData/Code/Tests/SurfaceDataBenchmarks.cpp
- Gems/SurfaceData/Code/Tests/SurfaceDataTest.cpp
- Gems/Terrain/Code/Source/Components/TerrainSurfaceDataSystemComponent.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.cpp
- Gems/Vegetation/Code/Source/AreaSystemComponent.cpp
- Gems/Vegetation/Code/Source/Components/PositionModifierComponent.cpp
- Gems/Vegetation/Code/Source/Components/SurfaceMaskDepthFilterComponent.cpp
- Gems/Vegetation/Code/Source/Debugger/DebugComponent.cpp
- Gems/Vegetation/Code/Tests/VegetationMocks.h
* Added AZ::Interface support to SurfaceDataSystemComponent
* Changed all code-side usage of SurfaceDataSystemRequestBus to use the AZ::Interface instead so that it no longer has mutex-locked calls to the system component.
* Removed all extra locks of the SurfaceDataSystemRequestBus that were added to keep lock-inverted deadlocks from happening
* Made SurfaceDataProvider / SurfaceDataModifier busses use the EBusSharedDispatchTraits to allow for parallel queries
> [Terrain] Made surface system async-friendly

- Code/Framework/AzCore/AzCore/Task/TaskGraph.cpp
Signal the wait event if one was supplied
> Make TaskGraph return immediately if an empty TaskGraph is submitted

- Gems/EMotionFX/Code/Tests/AnimGraphFuzzTests.cpp
Sets up a single test that fuzzes 1000 times instead of setting up 100 tests that fuzz 10 times.
Profiling these tests showed this area was quite slow, particularly the cost to start each test. This reduces overall test duration of module Gem::EMotionFX.Tests by 13% from 118594ms to 103176ms. Notably, the majority of time in this test module remains spent repeatedly launching an AzFramework::Application.
Verified these changes locally in both profile and debug.
Signed-off-by: Sean Sweeney <sweeneys@amazon.com>
> reduce setup of emfx fuzz tests

- Gems/Atom/RHI/Registry/Platform/Windows/PhysicalDeviceDriverInfo.setreg
22.2.3 has issues creating the vulkan device.
> Add metadata to mark AMD Radeon driver 22.2.3 has issues.

- Code/Editor/CryEdit.cpp
- Code/Editor/IEditorImpl.cpp
Code to enter/exit simulation mode or game mode is not instantaneous, they cannot be called one after another at the same time without causing out of order events for creation and destruction of game entities.
To solve the problem, the code that makes the transition at the top level (`CryEdit.cpp`), it will exit simulation mode first and schedule the activation of game mode for the next frame.
Transitions tested:
- Editor mode to Game mode. Works.
- Editor mode to Simulation model. Works.
- Game mode to Simulation model. Not possible.
- Simulation mode to Game mode. Fixed by this PR.
Fixes #8714 
> Fixed bug transitioning from simulation mode to game mode in editor.

- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/LocalViewBookmarkLoader.cpp
- Gems/SurfaceData/Code/Source/SurfacePointList.cpp
The `SurfacePointList::GetInPositionIndexFromPosition` `foundMatch` variable is set, but not used release configuration due to AZ_Assert being compiled out.
> Clang 13 SurfaceData gem release build fix.

- Gems/GradientSignal/Code/Include/GradientSignal/Components/ImageGradientComponent.h
- Gems/GradientSignal/Code/Include/GradientSignal/GradientTransform.h
- Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
- Gems/GradientSignal/Code/Source/GradientTransform.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalImageTests.cpp
Added a bilinear filtering sample type to the Image Gradient component.
- Image Gradient now has a sampling type field with `Point` and `Bilinear` options
- `Point` sampling is the default and current implementation
- `Bilinear` type performs bilinear interpolation
> Implemented bilinear filtering sample type for image gradients

- Code/Tools/ProjectManager/Source/ProjectBuilderWorker.cpp
- Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
Previously the project button would get into an invalid state and the UI would be unreadable.
> Fix State Transition After Building Again After A Failed Build

- scripts/build/Platform/Linux/deploy_cdk_applications.sh
- scripts/build/Platform/Linux/destroy_cdk_applications.sh
The AWSI Linux automation tests are blocked by an known issue (https://github.com/o3de/o3de/issues/8794) where O3DE Python fails to create virtual environment. Each Jenkins job has its own EBS volume, so installing Python dependencies in awsi_deployment job won't affect other jobs. As a temporary workaround for unblocking the tests, we can use system/O3DE Python directly. This change is related to https://github.com/o3de/o3de/pull/8784.
Verified the deployment and destruction script on Jenkins.
> Remove the step for creating Python virtual environment to unblock AWSI automation tests on Linux

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/DespawnNodeable.ScriptCanvasNodeable.xml
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/SpawnNodeable.ScriptCanvasNodeable.xml
Fixes an issue when performing undo/redo operations on Spawn/Despawn nodes in ScriptCanvas is causing them to get corrupted. This seems to be related to parameter name collision of SpawnTicket.
> Renaming parameters to avoid name collision

- Gems/Atom/Asset/Shader/Config/Platform/Mac/shader_build_options.json
It was passing arguments incorrectly, activating a namespace called "mt,vk" instead of namespaces "mt" and "vk".
Fixes https://github.com/o3de/o3de/issues/8162
> Fixed AZSLc command line arguments on metal.

- .github/CODEOWNERS
Updated code ownership file to point asset pipeline systems to sig content, not sig core
> Updated code ownership file to point asset pipeline systems to sig content, not sig core

- Gems/Blast/Code/Include/Blast/BlastActor.h
- Gems/Blast/Code/Include/Blast/BlastSystemBus.h
- Gems/Blast/Code/Source/Actor/BlastActorImpl.cpp
- Gems/Blast/Code/Source/Actor/BlastActorImpl.h
- Gems/Blast/Code/Source/Components/BlastFamilyComponent.cpp
- Gems/Blast/Code/Source/Components/BlastFamilyComponent.h
- Gems/Blast/Code/Source/Components/BlastSystemComponent.cpp
- Gems/Blast/Code/Source/Components/BlastSystemComponent.h
- Gems/Blast/Code/Source/Family/BlastFamilyImpl.cpp
- Gems/Blast/Code/Source/Family/BlastFamilyImpl.h
- Gems/Blast/Code/Tests/Mocks/BlastMocks.h
- Renaming `GetTkGroup` to `CreateTkGroup` as it reflects better the operation it's doing.
- Replace old `AZ_CRC` with `AZ_CRC_CE`
- Protect Spawn/Despawn code in `BlastFamilyComponent`. Remove unnecessary checks to members from buses implementations (nobody can call them because it's only connected when it's spawned and data is valid).
- On BlastFamilyComponent spawn code, but the asset is not ready yet, load the asset. 
- Fixed bug when removing empty blast groups.
- Protect Spawn/Despawn code in `BlastFamilyImpl`.
- Added comments to clarify further who owns data.
Testing:
- Blast unit tests passed.
- Blast automated tests passed.
- Create level with blast assets from AutomatedTesting project and run it.
> Blast improvements

- Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderBuildArgumentsManager.cpp
`addedDefinitionCount` variables in `ShaderBuildArgumentsManager.cpp` (Atom gem) are unused for `release` build config. This PR suppress warnings (and errors) during build.
Very similar to #8859, which mentions `clang 13` as the used compiler. However, in this case, the errors were on `clang 12`. 
Signed-off-by: Piotr Jaroszek <piotr.jaroszek@robotec.ai>
> Atom gem release build fix

- Gems/GraphCanvas/Code/Source/Components/SceneComponent.cpp
The Qt bug for this workaround has been fixed, so restoring the BSP tree default behavior is safe and provides a boost in performance, saving about 30 seconds for a large graph load in local testing:
https://bugreports.qt.io/browse/QTBUG-18021
> - removed old bug workaround that hurts GraphCanvas performance

- Code/Framework/AzFramework/Tests/ArchiveCompressionTests.cpp
- Code/Framework/AzFramework/Tests/FileIO.cpp
Proposed changes were found while profiling tests, and reduce running AZ::AzFramework.Tests.main by 57% from 92752ms to 39867ms. Other tests in this module appear more tightly integrated with creating an actual application context.
Reduces sleeps when testing FileIO, though a more invasive fix would be to mock the system time responses that FileIO is depending on from the OS, or to mock more of the actual I/O. This would also prevent a rare edge case failure where actual system time is modified during test execution (could be user-initiated, though more likely automated in the case of DST, leap seconds, and internal clock drift)
Application start/stop was not required to test compression.
Verified these changes locally in both profile and debug.
Signed-off-by: Sweeney …
> reduce test setup in azframework tests

- Code/Editor/AboutDialog.ui
- Code/Editor/CryEdit.cpp
- Code/Editor/StartupLogoDialog.ui
Removes friendly version name labels in the Editor (since we now refer to releases just by their version number).
Changes the Editor titlebar to display the version number
Note that this works when the version number is supplied **as a string** in the CMake configuration:
The Jenkins instances that generate the installer set this value correctly, so the version will be displayed.
In local builds, that value defaults to 0. When no version number string is supplied, the Editor will display the text "Development Build" instead:
> Update version indicators in the Editor

- Code/Framework/AzCore/Tests/Asset/AssetManagerLoadingTests.cpp
- Code/Framework/AzCore/Tests/EBus.cpp
- Code/Framework/AzCore/Tests/EBus/ScheduledEventTests.cpp
- Code/Framework/AzCore/Tests/Streamer/FullDecompressorTests.cpp
- Code/Framework/AzCore/Tests/Streamer/SchedulerTests.cpp
- Code/Framework/AzCore/Tests/StreamerTests.cpp
Reduces the duration and frequency of tests calling sleep in AZ::AzCore.Tests.main.  This reduces the total time to execute all tests in this module by 60% from 124767ms to 50879ms.
These inefficiencies were found while profiling the test module. While it's best to avoid sleeps, I couldn't see a simple way to verify the same multi-thread conditions without sleeping.
Verified this remains consistently passing locally in both profile and debug.
Signed-off-by: Sean Sweeney <sweeneys@amazon.com>
> reduce sleeps in azcore tests

- Gems/Atom/Utils/Code/Include/Atom/Utils/AssetCollectionAsyncLoader.h
- Gems/Atom/Utils/Code/Source/AssetCollectionAsyncLoader.cpp
Even though asset.BlockUntilLoadComplete was being called on a worker
thread instead of the main thread, deadlocks were occurring under
stressful circumstances like setting Lattice values to 25^3
in ASV RPI/AssetLoadTest.
> Fixed deadlock due to asset.BlockUntilLoadComplete

- Code/Tools/AssetProcessor/native/unittests/FileWatcherUnitTests.cpp
- Code/Tools/AssetProcessor/native/unittests/RCcontrollerUnitTests.cpp
- Code/Tools/AssetProcessor/native/unittests/UtilitiesUnitTests.cpp
Reduces blind waiting on other parts of the application to be ready, as well as busy waits on conditions which are not expected to change.
Profiling these tests showed these areas were quite slow, and it may be possible to minimize sleeps further than this experiment. This reduces the duration of AZ::AssetProcessor.Tests by 60% from 200199ms to 82891ms.
Verified these changes locally in both profile and debug.
Signed-off-by: Sean Sweeney <sweeneys@amazon.com>
> reduce ap test calls to sleep

- scripts/build/Platform/Linux/build_config.json
- scripts/build/Platform/Linux/deploy_cdk_applications.sh
- scripts/build/Platform/Linux/destroy_cdk_applications.sh
This is a follow up fix related to https://github.com/o3de/o3de/pull/8827
We have to add the Python executable path to the PATH environment variable so that CDK can pick up the O3DE Python instead of the Linux system Python during the deployment since it is not running under a Python virtual environment any more. This is a temporary fix as https://github.com/o3de/o3de/pull/8827 and we will revert both of these two PRs once O3DE Python is fixed (https://github.com/o3de/o3de/issues/8794).
Verified the scripts on a local Linux machine.
> Add Python executable path to the Path environment variable

- Code/Tools/ProjectManager/Platform/Linux/ProjectBuilderWorker_linux.cpp
- Code/Tools/ProjectManager/Platform/Mac/ProjectBuilderWorker_mac.cpp
- Code/Tools/ProjectManager/Platform/Windows/ProjectBuilderWorker_windows.cpp
Update project manager so that building builds Editor, GameLauncher, and now **ServerLauncher** (on Windows and Linux, not Mac)
Tested by building a project and seeing ServerLauncher get created. Also works with projects that don't enable MultiplayerGem, I was worried that ServerLaunchers are only defined when MP gem is enabled, but apparently not.
Building ServerLauncher does not add much time to build either. Since the ServerLauncher is basically the GameLauncher, if the GameLauncher is already built it looks like ServerLauncher just compiles 1/1 cxx. This might change once the client/server split is implemented (see https://github.com/o3de/sig-network/blob/main/rfcs/rfc-net-20220118-1-clientserver.md)
Resolves #8407
> Update Project Manager to Build ServerLauncher

- Code/Framework/AzFramework/AzFramework/Physics/Material.cpp
The `OnReadEnd` function of the serialization of `MaterialSelection` class tries to validate the material ids after serialization by looking into the material library. The problem was when executed in the context of Asset Builder (due to a prefab), the material library is never loaded by the physics system because it's expecting the event "CriticalAssetsCompiled", which is not fired at asset processor time.
Fixed by adding a protection in `OnReadEnd` to only validate the material ids if it's not an asset builder. That way when prefabs are processing the data it will only write the ids out, and during editor/launcher it will validate it against the library.
Fixes #7550 
> Fixed physx material ids being set to null when used in a prefab

- scripts/build/Jenkins/Jenkinsfile
Missed one case due to slight differences prod and sandbox environments. Tested by using new regex against prod string.
> Adding another pytest quick link

- Gems/GraphModel/Code/Include/GraphModel/Model/IGraphContext.h
- Gems/GraphModel/Code/Tests/TestEnvironment.h
- Gems/LandscapeCanvas/Code/Source/Editor/Core/GraphContext.h
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaFilters/AltitudeFilterNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaFilters/DistributionFilterNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaFilters/ShapeIntersectionFilterNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/PositionModifierNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/RotationModifierNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/ScaleModifierNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/SlopeAlignmentModifierNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaSelectors/AssetWeightSelectorNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Areas/AreaBlenderNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Areas/BaseAreaNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/BaseNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/GradientModifiers/BaseGradientModifierNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/GradientModifiers/GradientMixerNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/AltitudeGradientNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/BaseGradientNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/ShapeAreaFalloffGradientNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Shapes/BaseShapeNode.cpp
This overload was added to compensate for a compile error that does not seem to be happening anymore.
Using the overloaded function would also require a reference to an instance of the derived context class instead of working with the interface ptr contained in every graph element.
> Graph Model: Removing overloaded template function to get data types from graph model contexts

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/MethodConfiguration.cpp
- Gems/ScriptCanvasTesting/Assets/ScriptCanvas/UnitTests/LY_SC_UnitTest_MultipleReturnSameTypeResults.scriptcanvas
- Gems/ScriptCanvasTesting/Code/Source/ScriptCanvasTestBus.h
- Gems/ScriptCanvasTesting/Code/Tests/ScriptCanvas_RuntimeInterpreted.cpp
As we can't create slot with same name and same type, adding result index into result data slot name if there are multiple results (Which follows the same format as input data slot)
> Fix method tuple result missing issue

- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Fix for https://github.com/o3de/o3de/issues/8870
Network entities are not cleared when a client disconnect from the server and when it tries to reconnect, an assert is triggered at https://github.com/o3de/o3de/blob/development/Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityTracker.cpp#L20 since the same entity is added to the map again.
Test Done:
- All multiplayer unit tests passed
- Connected two clients to the server. Disconnected and reconnected one of them successfully
> fix the issue where client can not connect to Server after disconnect

- Gems/GraphModel/Code/Source/Model/Slot.cpp
Adding basic math and numeric types, needed by material canvas, to graph model slot serializer.
This does not include advanced types like assets and other things that will be needed in the near future.
Eventually this should be pluggable so that new types can be added or natively supported by the serializer.
Only modifies Gems/GraphModel/Code/Source/Model/Slot.cpp
The rest is from https://github.com/o3de/o3de/pull/8998
> Graph Model: Added more numeric and math types to json serializer

- AutomatedTesting/Gem/PythonTests/Prefab/tests/reparent_prefab/ReparentPrefab_UnderAnotherPrefab.py
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceToTemplatePropagator.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
Changes in this PR: 
- Fixes [8957](https://github.com/o3de/o3de/issues/8957)
I'm reverting code that's added as part of[ this PR](https://github.com/o3de/o3de/pull/5747/files#diff-308bb40f413fd91e92bc448b7e35af07ddb3529cce9e2d21fb83872fa4847fb4R768), which added it in anticipation of upcoming override work. I'm reverting it to get base workflows stable. Will add any required code for overrides later.
- Changed an error to warning regarding partial patch application failures. This is consistent with other warnings sent by json serialization and EntityIdMapper for missing fields.
Testing:
Tested manually and also modified existing automated test to take focus mode into consideration. The test didn't catch the bug because it was trying to reparent prefabs without focusing on any prefab. …
> Fixed bug about reparenting prefab

- Code/Framework/AzCore/AzCore/Asset/AssetCommon.cpp
- Code/Framework/AzCore/AzCore/Asset/AssetCommon.h
- Code/Framework/AzCore/AzCore/Math/Uuid.cpp
- Code/Framework/AzCore/AzCore/Math/Uuid.h
- Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.h
- Code/Framework/AzCore/AzCore/Serialization/Json/JsonSerializer.cpp
- Code/Framework/AzCore/AzCore/Serialization/Json/PathSerializer.cpp
- Code/Framework/AzCore/AzCore/Serialization/ObjectStream.cpp
- Code/Framework/AzCore/AzCore/Serialization/ObjectStream.h
- Code/Framework/AzCore/Tests/Asset/AssetCommon.cpp
- Code/Framework/AzCore/Tests/UUIDTests.cpp
- Code/Framework/AzTest/AzTest/Platform/Windows/ScopedAutoTempDirectory_Windows.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp
- Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp
- Gems/EditorPythonBindings/Code/Tests/PythonLogSymbolsComponentTests.cpp
- Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.cpp
Both AssetId and Uuid have template functionality to allow AZStd::fixed_string as
the template instatation of their ToString calls. However, this leaves an
easy trap to fall into, especially in string format calls. It is easy to
use the Uuid::MaxStringBuffer when calling the AssetId to fixed string calls,
which leads to errors since the AssetId requires extra characters for the subId.
This change adds ToFixedString member functions to both classes, and updates
all direct references in the codebase to Uuid::MaxStringBuffer to use AssetId.
> Make Uuid / AssetId ToFixedString calls more consistent and less error prone. 

- Gems/GraphModel/Code/Include/GraphModel/Integration/EditorMainWindow.h
- Gems/GraphModel/Code/Include/GraphModel/Model/Common.h
- Gems/GraphModel/Code/Include/GraphModel/Model/DataType.h
- Gems/GraphModel/Code/Include/GraphModel/Model/Graph.h
- Gems/GraphModel/Code/Include/GraphModel/Model/GraphContext.h
- Gems/GraphModel/Code/Include/GraphModel/Model/GraphElement.h
- Gems/GraphModel/Code/Include/GraphModel/Model/Module/ModuleGraphManager.h
- Gems/GraphModel/Code/Include/GraphModel/Model/Slot.h
- Gems/GraphModel/Code/Source/Integration/GraphController.cpp
- Gems/GraphModel/Code/Source/Model/Graph.cpp
- Gems/GraphModel/Code/Source/Model/GraphContext.cpp
- Gems/GraphModel/Code/Source/Model/GraphElement.cpp
- Gems/GraphModel/Code/Source/Model/Module/ModuleGraphManager.cpp
- Gems/GraphModel/Code/Source/Model/Module/ModuleNode.cpp
- Gems/GraphModel/Code/Source/Model/Slot.cpp
- Gems/GraphModel/Code/Tests/TestEnvironment.cpp
- Gems/GraphModel/Code/Tests/TestEnvironment.h
- Gems/GraphModel/Code/graphmodel_editor_static_files.cmake
- Gems/LandscapeCanvas/Code/Source/Editor/Core/GraphContext.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Core/GraphContext.h
- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.h
- Instead of reimplementing graph context for every tool and test, upgraded the graph context interface into a base class and moved the implementation into it.
- Preserve the virtual functions necessary for landscape canvas special entity ID logic.
- Added functions for looking up types by name.
- Changed function that looked up types by enum to search instead of direct index because nothing is enforcing that types are added in the same order as the enumeration. This might benefit from removing the enumeration and relying only on UUIDs or switching to an associative container.
- Added construction parameters to pass in the system name, module details, and data types so the class does not need to be overridden in most cases.
- ~~Still need to address the case where the module manager …
> Graph Model: Move graph context implementation into base class

- Gems/Atom/Feature/Common/Editor/Scripts/ColorGrading/activate_lut_asset.py
- Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/PostProcess/ColorGrading/EditorHDRColorGradingBus.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/ColorGrading/EditorHDRColorGradingComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/ColorGrading/EditorHDRColorGradingComponent.h
- Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_public_files.cmake
"Activate LUT" are not exposed to Python.
This PR exposes in the behavior context, and for automation purposes only,
the functionality provided to the
user by the  "Generate LUT" and "Activate LUT" buttons
available in the "HDR Color Grading" component.
The equivalent to "Generate LUT" button can be done
by calling EditorHDRColorGradingRequestBus::GenerateLutAsync
and the completion event is signaled on
EditorHDRColorGradingNotificationBus::OnGenerateLutCompleted
The equivalent to "Activate LUT" button can be done
by calling EditorHDRColorGradingRequestBus::ActivateLutAsync
and the completion event is signaled on
EditorHDRColorGradingNotificationBus::OnActivateLutCompleted
> HDR Color Grading component's "Generate LUT" and

- Gems/Terrain/Code/Tests/TerrainSystemBenchmarks.cpp
This currently demonstrates that attempting to run multiple synchronous terrain queries in parallel results in locks that force them to run serially. It will be used to demonstrate the improvement once they're able to run in parallel.
> New terrain benchmark that tests parallel terrain queries.

- Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR.materialtype
- Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/ClearCoatPropertyGroup.json
- Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/DetailMapsPropertyGroup.json
- Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/EmissivePropertyGroup.json
- Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/OpacityPropertyGroup.json
- Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/SubsurfaceAndTransmissionPropertyGroup.json
- Gems/Atom/Feature/Common/Assets/Materials/Types/Skin.materialtype
- Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR.materialtype
- Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR.materialtype
Fixed the path to Lua functors to make them relative to the root of the assets system. This allows games and gems to `$import` property groups from Atom in their material types without triggering errors in the Asset Processor telling a Lua functor cannot be found.
> Make Lua functor paths be relative to the asset system root path

- Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/ToolsTestApplication.cpp
TargetManagement's polling for a connection in a side thread can take time to resolve on failure. It seems tests can't tear down until the thread is done with this. Disabling this behavior in TestToolsApplication vis IConsole to remove the slowdown. This speeds up hundreds of tests by over a second each.
This relates to https://github.com/o3de/o3de/issues/9022. 
> Optimize AzToolsFramework.Tests by disabling long poll connection polling

- Code/Framework/AzFramework/AzFramework/Terrain/TerrainDataRequestBus.h
- Gems/Terrain/Code/Source/Components/TerrainHeightGradientListComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainHeightGradientListComponent.h
- Gems/Terrain/Code/Source/Components/TerrainSurfaceGradientListComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainSurfaceGradientListComponent.h
This also required fixes to the Terrain components to avoid lock inversion deadlocks.
Demonstration of parallel terrain query benchmark running the queries in parallel without locking:
> [Terrain] Switch the terrain system to allow concurrent queries.

- CMakePresets.json
- Templates/DefaultProject/Template/.gitignore
- Templates/DefaultProject/Template/CMakePresets.json
- Templates/MinimalProject/Template/.gitignore
- Templates/MinimalProject/Template/CMakePresets.json
- cmake/Platform/Android/CMakePresets.json
- cmake/Platform/Common/CMakePresets.json
- cmake/Platform/Linux/CMakePresets.json
- cmake/Platform/Mac/CMakePresets.json
- cmake/Platform/Windows/CMakePresets.json
- cmake/Platform/iOS/CMakePresets.json
For host platforms of Windows, Linux and MacOS support for
configure, build and test presets has been added.
The non-host platforms of iOS and Android has supported for configure
and build presets.
Using the CMake presets with O3DE requires CMake 3.23.0 or above to be installed.
It is optional feature, so using the CMake without presets work as is in versions 3.22 and below.
How to use Presets can be seen from the [cmake(1)](https://cmake.org/cmake/help/latest/manual/cmake.1.html) page.
The list of presets can output for the configurationm build and test steps by running the following command
```
cmake --list-presets
cmake --build list-presets
ctest --list-presets
```
Below is an example of listing presets on Linux for the normal cmake command, cmake build wrapper command and ctest …
> Adding CMakePresets support for O3DE

- Gems/GradientSignal/Code/Include/GradientSignal/Components/ShapeAreaFalloffGradientComponent.h
- Gems/GradientSignal/Code/Include/GradientSignal/Ebuses/ShapeAreaFalloffGradientRequestBus.h
- Gems/GradientSignal/Code/Source/Components/ShapeAreaFalloffGradientComponent.cpp
- Gems/GradientSignal/Code/Tests/GradientSignalServicesTests.cpp
The previous approach was using the height of the query point as a part of the distance calculating, which gave us full 3D falloff. This really wasn't desirable behavior for either vegetation or terrain, so the gradient has been switched to use 2D falloff instead by default. Added a toggle to allow for either 2D or 3D falloff.
Added unit tests to validate and enforce the new behavior.
> [Terrain] Fix shape area falloff to calculate either 2D or 3D falloff.

- scripts/build/Platform/Linux/deploy_cdk_applications.sh
- scripts/build/Platform/Linux/destroy_cdk_applications.sh
- scripts/build/Platform/Windows/deploy_cdk_applications.cmd
- scripts/build/Platform/Windows/destroy_cdk_applications.cmd
When running [`deploy_cdk_applications`](https://github.com/o3de/o3de/blob/stabilization/2205/scripts/build/Platform/Windows/deploy_cdk_applications.cmd) with the `$BRANCH_NAME` and `$PIPELINE_NAME` env vars (such as on Jenkins),  `cdk deploy` would fail with errors like:
```
STABILIZATION--2205-NIGHTLY-CLEAN-WINDOWS-AWSCore failed: Error [ValidationError]: Template format error: Output STABILIZATION2205NIGHTLYCLEANWINDOWSResourceGroupOutput is malformed. The Name field of every Export member must be specified and consist only of alphanumeric characters, colons, or hyphens.
```
...if the `$BRANCH_NAME` included a slash (e.g.,: "stabilization/2205")
This change replaces any occurrences of `/` with empty string to avoid similar failures when the branch under test includes it.
* successfully …
> Remove invalid slash from AWS python test project names

- Code/Tools/SceneAPI/SceneData/Behaviors/ScriptProcessorRuleBehavior.cpp
- Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.cpp
{lyn12116} fix for an Editor crash for test_chunks.fbx
* moved AZ::Interface<Prefab::PrefabSystemComponentInterface>::Get()->RemoveAllTemplates(); logic into PrefabBuilder
* mesh group names shrunk by hashing node path
* only run the RemoveAllTemplates() before an Asset Processor request, not an Editor request
* all platforms will be affected
* the automated tests already cover these cases
> Fix lyn12116 test chunks crash

- Gems/AWSClientAuth/Code/Include/Authentication/AuthenticationProviderBus.h
- Gems/AWSClientAuth/Code/Include/Authentication/AuthenticationTokens.h
- Gems/AWSClientAuth/Code/Include/Authorization/ClientAuthAWSCredentials.h
- Gems/AWSClientAuth/Code/Source/Authentication/AWSCognitoAuthenticationProvider.cpp
- Gems/AWSClientAuth/Code/Source/Authentication/AuthenticationTokens.cpp
- Gems/AWSClientAuth/Code/Source/Authentication/GoogleAuthenticationProvider.cpp
- Gems/AWSClientAuth/Code/Source/Authentication/LWAAuthenticationProvider.cpp
- Gems/AWSClientAuth/Code/Tests/AWSClientAuthGemMock.h
- Gems/AWSClientAuth/Code/Tests/Authentication/AWSCognitoAuthenticationProviderTest.cpp
- Gems/AWSClientAuth/Code/Tests/Authentication/AuthenticationProviderManagerScriptCanvasBusTest.cpp
- Gems/AWSClientAuth/Code/Tests/Authentication/AuthenticationProviderManagerTest.cpp
- Gems/AWSClientAuth/Code/Tests/Authorization/AWSCognitoAuthorizationControllerTest.cpp
Removed the cached access token and ID token in the authentication providers to address security concerns around credentials in memory. Tokens will be sent out via the notification bus and the Client Auth gem won't store the access token and ID token for retrieval any more (The GetAuthenticationTokens API should be deprecated).  
Passed Client Auth gem unit tests and end-to-end tests (Python). Also verified the Google Signin and Login with Amazon (LWA) workflow.
> Remove the cached access token and id token to address security concerns

- Gems/Atom/RPI/Assets/seedList.seed
- Gems/LyShine/Assets/seedList.seed
When going through the[ bundling process for engine assets](https://docs.o3de.org/docs/user-guide/packaging/asset-bundler/bundle-assets-for-release/) I found several seeds were incorrect.
```
ERROR | Could not find asset ... from (Gems\LyShine\Assets\seedList.seed) Hint (shaders/lyshineui.azshader) 
ERROR | Could not find asset ... .from (Gems\Atom\RPI\Assets\seedList.seed) Hint (shader/decomposemsimage.azshader)
ERROR | Could not find asset ... from (Gems\Atom\RPI\Assets\seedList.seed) Hint (shader/imagepreview.azshader) 
ERROR | Could not find asset ... from (Gems\Atom\RPI\Assets\seedList.seed) Hint (shader/sceneandviewsrgs.azshader) 
```
This prevents a user from creating a valid engine .pak file for a game release.
I used the Asset Bundler to point to the correct locations for these …
> Fix LyShine and RPI invalid seedlist entries

- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MaterialAdded.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MeshAdded.py
updates the model used for these tests to ./Gems/Atom/TestData/TestData/Objects/ModelHotReload/sphere_5lods.fbx
updates test lines which expect this new path for LOD default mesh paths
relates to https://github.com/o3de/o3de/issues/7795
Report:
[SUCCESS] Success: Material Entity successfully created
[SUCCESS] Success: Entity has a Material component
[SUCCESS] Success: Material component disabled
[SUCCESS] Success: Entity has an Actor component
[SUCCESS] Success: Material component enabled
[SUCCESS] Success: Entity Actor component gone
[SUCCESS] Success: Material component disabled
[SUCCESS] Success: Entity has a Mesh component
[SUCCESS] Success: Material component enabled
[SUCCESS] Success: …
> updating sphere_5lod asset to use Atom testdata version

- Gems/Atom/Feature/Common/Code/Source/ProfilingCaptureSystemComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Assets/Scripts/Profiling/OutputProfileData.lua
Plus a small c++ change to expose the necessary ebus's to lua.
Script is expected to be active in the level to be profiled. A registry key needs to be active to trigger the profiling, plus several values can be overridden with other registry values.
Supported values: Number of frames to wait before beginning profiling, number of frames to record time for, Profile name, Whether to quit after all frames have been timed.
> Lua script that can trigger recording frametimes in the GameLauncher.

- Code/Framework/AzCore/AzCore/Serialization/AZStdContainers.inl
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyRowWidget.cpp
Closes #9065 
Fixes a crash in the Scene Inspector for fbx files with uninitialized optional properties. 
This change adds a check on the GetElementByIndex that prevents dereferencing a nullptr. That fixes the crash and results in this view:
I am not familiar with this area, so feel free to provide directions if you think this fix should be higer up the chain.
> Fix RPE crash when displaying uninitialized optional properties in FBX Settings Inspect panel

- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/NodePalette/Model/NodePaletteSortFilterProxyModel.cpp
Issue is when user gives search filter, we use QRegExp::escape to get string with every regexp special character escaped with a backslash.
For example, "+" -> "\\+"
After that, we also insert whitespace match between each character.
Which leads to "\\+" -> "\\\s*+\\s*"
Fix is to use QRegExp::escape for each character, not at very beginning for whole string.
https://user-images.githubusercontent.com/5900509/164568796-311826f3-1d38-427c-8854-9f460e327bdb.mp4
> Fix search field escape character issue

- Code/Legacy/CrySystem/LevelSystem/SpawnableLevelSystem.cpp
When unloading a level (root spawnable), the ReleaseRootSpawnable call already deletes that level's entities and removes them from the game entity context, so there should no longer be a need to also call ResetGameContext.
Calling ResetGameContext results in entities being deleted that are still being referenced in the spawn ticket. Later on when the spawn ticket is released via ReleaseRootSpawnable, the entities get deleted again causing crashes etc.
Fixes #8696.
> Fix double deletion of entities when unloading a level

- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/AdapterBuilder.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/AdapterBuilder.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
- Code/Framework/AzFramework/Tests/DocumentPropertyEditor/AdapterBuilderTests.cpp
- Code/Framework/AzFramework/Tests/DocumentPropertyEditor/CvarAdapterTests.cpp
- changed node value to be a property named "Value" instead of a naked child, for better encapsulation
- fixed tests to accommodate change
> changed node value from a child to a property for better encapsulation

- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/PhotometricValue.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorAreaLightComponent.cpp
Light component has an errant "\n."
1. Remove the trailing "\n"
2. Changed PhotometricUnit enum type to AZ::u8 instead of char because
python was interpreting as a string instead of a numeric value.
> Controller for Normal Shadow Bias parameter of the

- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MaterialAdded.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MeshAdded.py
fix for sphere_5lod model issue fixed in development which appears in stabilization now.
https://github.com/o3de/o3de/issues/8705
> Fixing a test model reference for sphere_5lod that fails AR in stabilization/2205

- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.h
Display viewport message when multiplayer editor cannot find a server. Stops attempting to connect to server when the server doesn't exist.
Tested by running CTRL+G with and without a ServerLauncher.
Resolves #9168 
> Mutliplayer Editor: Stop Attempting TCP Server Connection with Server Doesn't Exist

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Application/AtomToolsApplication.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
Adding test output redirection functions to facilitate new Python tests for material editor and other atom tools.
> Atom Tools: Adding test output redirect functions for QA

- Code/Tools/SceneAPI/SceneData/Behaviors/ScriptProcessorRuleBehavior.cpp
- Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.cpp
{lyn12116} fix for an Editor crash for test_chunks.fbx
* moved AZ::Interface<Prefab::PrefabSystemComponentInterface>::Get()->RemoveAllTemplates(); logic into PrefabBuilder
* only run the RemoveAllTemplates() before an Asset Processor request, not an Editor request
> Fix lyn12116 test chunks crash (#9056)

- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MaterialAdded.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MeshAdded.py
- Gems/Atom/Feature/Common/Assets/Passes/LowEndRenderPipeline.azasset
This crash can also be reproduced on Windows if we tell it to use the LowEndRenderPipeline(Gems\Atom\Bootstrap\Code\Source\Platform\Windows\BootstrapSystemComponent_Traits_Platform.h).
The crash is happening in Gems\LyShine\Code\Source\Draw2d.cpp OnBootstrapSceneReady() because the uiCanvasPass pointer is null. The pass never got created because ApplyRenderPipelineChange() in Gems\LyShine\Code\Source\LyShineFeatureProcessor.cpp was never called since it early returned in TryApplyRenderPipelineChanges() in Gems\Atom\RPI\Code\Source\RPI.Public\Scene.cpp because the m_allowModification flag in the descriptor was set to false. This is flag isn’t being set for the LowEndRenderPipeline(Gems\Atom\Feature\Common\Assets\Passes\LowEndRenderPipeline.azasset). Setting the flag there fixes the crash. …
> Fix crash in low end render pipeline caused by feature processors not getting added

- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/blank.materialcanvastemplate.azasset
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test1.materialcanvas.azasset
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test2.materialcanvas.azasset
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test3.materialcanvas.azasset
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test4.materialcanvas.azasset
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test5.materialcanvas.azasset
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
Updated all of the document class save and load functions to handle the graph model data.
Updated all of the test assets to use graph model graphs instead of placeholder strings.
Builds on top of PR #9104 
Only modifies Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp and test assets
> Material Canvas: Implemented document serialization, graph saving and loading

- Gems/Atom/Feature/Common/Assets/Passes/EnvironmentCubeMapPipeline.pass
Added the PipelineViewTag to the ReflectionComposite pass in the EnvironmentCubeMapPipeline.
> Crash when baking a Reflection Probe (GPU device removed)

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.cpp
ref issue: https://github.com/o3de/o3de/issues/9130
> bugfix: resolve tab order problem with component window for propertyAssetCtrl

- Code/Framework/AzCore/AzCore/Serialization/EditContextConstants.inl
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabSaveLoadHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyFilePathCtrl.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyFilePathCtrl.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyManagerComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
Added a property control for `AZ::IO::Path` fields. This is necessary for fields that can't use an asset reference (e.g. if they need to be able to specify a file path for an asset that hasn't been created yet).
- Browse edit with a popout button that launches a native file dialog
- Can configure filter for specific extensions
- Optionally specify a default file-name for a field with no value yet when launching the file dialog
- Protects user from entering file name with invalid AP characters by using `AzQtComponents::FileDialog::GetSaveFileName`
- Appropriately handles file paths for assets that already exist + ones that haven't been created yet
- Prevents user from choosing a file path outside of the configured asset safe folders
- Updated create prefab workflow error message when …
> Added property control for AZ::IO::Path

- Tools/LyTestTools/ly_test_tools/log/log_monitor.py
> Make log monitor respect the log_creation_max_wait_time parameter

- Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetSelection/AssetSelectionComboBox.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetSelection/AssetSelectionGrid.cpp
This addresses an issue where the asset grid or combo box could potentially have the same asset added multiple times.
This will not address the case if an asset in a different folder has the same file name.
That will result in the same name appearing in the list or dropdown multiple times but they will point to the correct asset.
> Bug fix for asset appearing multiple times in material editor asset selectors

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportToolBar.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportToolBar.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/Icons/toneMapping.svg
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/Icons/toneMapping.svg
The tool button was not showing tooltips but they reappear using the action.
Removed background from button icon art that interfered with button states.
Addresses https://github.com/o3de/o3de/issues/8641
> Fix material editor toolbar icon and tooltips for tonemapping button

- Gems/Multiplayer/Code/Source/Components/LocalPredictionPlayerInputComponent.cpp
This change addresses the crash described in https://github.com/o3de/o3de/issues/8463
It is possible for m_inputHistory to be length 0 and this was not properly accounted for.
> Fix Debug Desync crash in LocalPredicitonPlayerInputComponent

- Code/Editor/Plugins/FFMPEGPlugin/FFMPEGPlugin.cpp
- Code/Editor/TrackView/SequenceBatchRenderDialog.cpp
While FFmpeg supports whatever it was compiled to offer, we
should prefer and suggest codecs that are broadly supported across
all platforms.
Today, WebM (with VP9) is supported out of the box on current versions
of Microsoft Windows; Apple macOS, iOS, iPadOS, tvOS, and watchOS; and
virtually all currently available Linux distributions, including
Amazon Linux, Fedora Linux, Red Hat Enterprise Linux/CentOS Stream, and
Ubuntu Linux.
Hardware accelerated decoding is also broadly in place on desktop and mobile
platforms.
Signed-off-by: Neal Gompa <ngompa@fedoraproject.org>
> Use VP9 WebM by default for video encoding

- Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignment.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
Fix multiple issues with material overrides updating or previewing consistently
- Fixed problem where the mesh component was not notifying material component that slots had changed if the mesh asset was cleared.
- Fixed a problem with the material assignments applying property overrides consistently. The function that applies properties was returning failure if the material instance could not currently be compiled. The function now attempts to apply the property overrides if there are any and will return true if it recompiled or nothing needed to be recompiled. This keeps the material component from continuously requeueing certain materials, which prevented it from sending the notification that the instances were updated.
- Changed the material component instance inspector to do a reload …
> Fix multiple issues with material overrides updating or previewing consistently

- Gems/Terrain/Assets/Shaders/Terrain/ClipmapComputeHelpers.azsli
- Gems/Terrain/Assets/Shaders/Terrain/TerrainDetailClipmapGenerationPass.azsl
- Gems/Terrain/Assets/Shaders/Terrain/TerrainMacroClipmapGenerationPass.azsl
- Gems/Terrain/Assets/Shaders/Terrain/TerrainSrg.azsli
- Gems/Terrain/Code/Source/TerrainRenderer/ClipmapBounds.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/ClipmapBounds.h
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.h
1. Switched to using ClipmapBounds. This class has already done some of the smart update work.
2. Add bilinear and trilinear sampling for clipmaps. Trilinear is used when blending 2 clipmap layers. Point sampling is reserved for future optimization (far away clipmaps may not need precise sampling.)
3. Renamed MaxRenderDistance to MaxRenderRadius. The value is half of the clipmap, so radius reflects the meaning better.
> [Terrain] Add bilinear and trilinear sampling and switched to ClipmapBounds

- Code/Framework/AzFramework/AzFramework/Spawnable/Script/SpawnableScriptAssetRef.cpp
Addresses https://github.com/o3de/o3de/issues/8973
There's no way to actually hide the variable from Node Palette without it also getting hidden in Variable Manager. However there's a better example to display its getter and setter instead of two identical "asset" fields:
This doesn't break any currrent Lua/SC scripts in development.
> Fixing SpawnableScriptAssetRef display in SC

- Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/IrradiancePropertyGroup.json
The default irradiance color was recently changed to use the BaseColor texture average, but this is not compatible with mesh textures that are UV-unwrapped or low intensity.
This PR changes the default back to the Manual irradiance color.
> Change default irradiance color source to Manual

- Gems/Blast/Code/Source/Editor/EditorBlastFamilyComponent.cpp
- Gems/Blast/Code/Source/Editor/EditorBlastFamilyComponent.h
> Blast material asset property shows (default) when no assets assigned.

- Tools/LyTestTools/ly_test_tools/_internal/pytest_plugin/test_tools_fixtures.py
- Tools/LyTestTools/tests/unit/test_fixtures.py
Fix for https://github.com/o3de/o3de/issues/6971
When running through CTest, this output directory is normally set to:
`../o3de/<cmake_build_dir>/Testing/LyTestTools/<ctest_module_name>/`
When unset, the output will first try to redirect to:
`../o3de/<user_provided_cmake_build_dir>/Testing/LyTestTools/pytest_results/<timestamp>/`
If the user does not provide a build directory for LyTestTools, it will redirect to:
`<cwd>/pytest_results/<timestamp>/`
...and output a warning to notify the user that results were stored in a default location.
> Default test results into build directory, warn when unset

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Node.cpp
Background: when we Undo/Redo, we will rebuild the graph from previous stored snapshot. Each node has a cached slot name map AZStd::unordered_multimap<AZStd::string, SlotIterator> m_slotNameMap, and it is maintained so we don't really need to re-configure all slots.
The issue is m_slotNameMap is a multimap, we prevent slot with same name and same type, but it allows slot with same name but different type, which is the reported issue.
So when we try to rebuild graph for that node, it searches against m_slotNameMap, find a same name but different slot type, so it will try to create a new slot.
Fix is to use equal_range to get all matched slot name in the multimap which can capture existing slot.
https://user-images.githubusercontent.com/5900509/166067759-5d82f53a-5500-46d2-a256-0925757b24ec. …
> Fix duplicated slot name on Undo/Redo action

- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/NodePalette/Model/NodePaletteSortFilterProxyModel.cpp
Little tweak to improve node palette category
Put item without children at front, otherwise follow alphabetical order
> Group w/wo children item in node palette

- Code/Legacy/CryCommon/IMovieSystem.h
I added some missing mappings for Vector4 and added a deprecation notice to the already deprecated methods. 
issue: https://github.com/o3de/o3de/issues/9133
> chore: deprecate GetValue and SetValue for IAnimTrack using cryLegacy

- Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Common.jinja
- Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja
- Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
- Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkCharacterComponent.h
- Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkRigidBodyComponent.h
- Gems/Multiplayer/Code/Source/AutoGen/NetworkCharacterComponent.AutoComponent.xml
- Gems/Multiplayer/Code/Source/Components/NetworkCharacterComponent.cpp
- Gems/Multiplayer/Code/Source/Components/NetworkRigidBodyComponent.cpp
Updating NetworkRigidBodyComponent to require NetTransform by calling the base class's GetRequiredServices.
Also clean up NetRigidBody's and NetCharacter's incompatibility service; removed redundant services, and allow for XML to define Incompatible services without having to define HasContoller.
Tested by adding the NetworkRigidBodyComponent to an entity and now seeing that it requires adding the NetTransformComponent.
Tested by adding the NetworkRigidBodyComponent to an entity and then NetworkCharacterComponent, and seeing that they are still incompatible.
Resolves #8616
> Update NetworkRigidBody to Require NetworkTransform

- Code/Editor/EditorViewportWidget.cpp
- Code/Editor/EditorViewportWidget.h
- Code/Editor/Undo/Undo.cpp
- Code/Editor/Undo/Undo.h
I have some changes due to go into `EditorViewportWidget.h/cpp` and I now have muscle memory to reformat the code I'm working on (if I do this and then forget, it makes it all too easy to mix in functional changes with formatting changes, and there are quite a lot in this file). For that reason I'd really like to auto-format these files separate from any functional changes to make future edits much simpler.
_Note: Not all the transformations are necessarily going to be to everyone's liking, but that's just the nature of auto formatting. It's never going to be 100% perfect, but the gains are immense in productivity - unless there's anything super important I'd rather not add `// clang-format on/off` lines, but that is an option. I personally don't think the readability has been impacted …
> Formatting Only Change - run clang-format over EditorViewportWidget.h/cpp

- Code/Framework/AzCore/AzCore/Console/ILogger.h
- Code/Framework/AzCore/AzCore/Console/LoggerSystemComponent.cpp
- Code/Framework/AzCore/Tests/Console/LoggerSystemComponentTests.cpp
- Gems/AtomLyIntegration/ImguiAtom/Code/Source/DebugConsole.cpp
- Gems/AtomLyIntegration/ImguiAtom/Code/Source/DebugConsole.h
Before this fix, only a handful of logs were visible in the in-game console - namely audio and networking, but all other logs are not visible.
This change restores all missing log messages in the console window, until the log reckoning takes place.  
- DebugConsole now receives logs messages from `AZ::Debug::TraceMessageBus`, `m_logHandler` is removed
- LoggerSystemComponent sends messages through `Debug::Trace::Printf` instead of `Debug::Trace::Output`
- verified logs appear in console in the game launcher
- fixed `LoggerSystemComponent` AZLOG_ERROR unit test
```
[==========] Running 10 tests from 1 test case.
[----------] 10 tests from LoggerSystemComponentTests
[ RUN      ] LoggerSystemComponentTests.LogTraceTest
[       OK ] …
```
> Fix missing log messages in console window

- Gems/GradientSignal/Code/Source/UI/GradientPreviewWidget.cpp
Moved the gradient preview popout icon to be in the upper left corner instead of upper right. This change was suggested after a UX review that found when the Entity Inspector is shrunk to its minimum allowable size, the value column gets truncated which cuts off the image and causes the popout icon to be overlapped as well.
BEFORE:
AFTER:
> Moved gradient preview popout icon to the left corner

- Gems/AtomLyIntegration/CommonFeatures/Assets/Scripts/Profiling/OutputProfileData.lua
- Tools/LyTestTools/ly_test_tools/benchmark/data_aggregator.py
- Tools/LyTestTools/ly_test_tools/log/log_monitor.py
Additionally re-organize the benchmark upload python to make only having cpu data or gpu data acceptable. It's now only an error if there is no data or either kind.
> Make profiling lua script write out meta data

- Code/Framework/AzCore/AzCore/Interface/Interface.h
- Code/Framework/AzCore/AzCore/Module/Environment.h
- Code/Framework/AzCore/Tests/DLL.cpp
- Code/Framework/AzCore/Tests/DLLMainTest.cpp
- Code/Framework/AzCore/Tests/Serialization.cpp
- Code/Framework/AzCore/Tests/StreamerTests.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Shader/ShaderReloadDebugTracker.cpp
- Gems/WhiteBox/Code/Tests/WhiteBoxPhysicsTest.cpp
Updated the EnvironmentVariable class boolean checks.
The `operator bool` and `operator!` now check if the EnvironmentVariableHolderType type is non-nullptr and is in a constructed state.
This makes it consistent with the `operator*` and `operator->` methods and allows the construct as follows to always work
```
if (environmentVariable)
{
auto value = *environmentVariable;
}
```
Also removed the `Construct` environment variable class as it allows invoking the constructor over an already constructed value stored in the EnvironmentVariableHolder.
The `Construct` function itself required the EnvironmentVariable to be in a very specific state where the EnvironmentVariable has been constructed before and the destroyed in order to use safely.
The function that should be used to re-create an …
> AZ EnvironmentVariable boolean operator fixes

- Gems/MotionMatching/Code/Source/Feature.h
- Gems/MotionMatching/Code/Source/FeaturePosition.cpp
- Gems/MotionMatching/Code/Source/FeaturePosition.h
- Gems/MotionMatching/Code/Source/FeatureTrajectory.cpp
- Gems/MotionMatching/Code/Source/FeatureTrajectory.h
- Gems/MotionMatching/Code/Source/FeatureVelocity.cpp
- Gems/MotionMatching/Code/Source/FeatureVelocity.h
- Gems/MotionMatching/Code/Source/MotionMatchingInstance.cpp
Replaced the motion matching instance with a current pose and the feature matrix to make the debug draw independent of the motion matching instance.
> Motion Matching: Made debug draw independent of the mm instance

- AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Main.py
Disabling the following Physics TestSuite_Main flaky tests identified in the GHIs noted below.
Verified that automation suite was still able to run and no results present for skipped tests to save resources  on tests we don't trust until tests are back online.
#9364 ForceRegion_LinearDampingForceOnRigidBodies
#9365 ForceRegion_NoQuiverOnHighLinearDampingForce
#9368 Collider_ColliderRotationOffset
> 9366 disable flaky phys tests

- Gems/ScriptCanvas/Code/Editor/GraphCanvas/Components/NodeDescriptors/EBusHandlerEventNodeDescriptorComponent.cpp
- Gems/ScriptCanvas/Code/Editor/GraphCanvas/Components/NodeDescriptors/EBusHandlerNodeDescriptorComponent.cpp
- Gems/ScriptCanvas/Code/Editor/GraphCanvas/Components/NodeDescriptors/ScriptEventReceiverNodeDescriptorComponent.cpp
- Gems/ScriptCanvas/Code/Editor/Nodes/NodeCreateUtils.cpp
- Gems/ScriptCanvas/Code/Editor/Nodes/NodeCreateUtils.h
- Gems/ScriptCanvas/Code/Editor/Nodes/NodeDisplayUtils.cpp
- Gems/ScriptCanvas/Code/Editor/Nodes/NodeDisplayUtils.h
- Gems/ScriptCanvas/Code/Editor/Translation/TranslationHelper.h
- Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/EBusNodePaletteTreeItemTypes.cpp
- Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/EBusNodePaletteTreeItemTypes.h
- Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/GeneralNodePaletteTreeItemTypes.cpp
- Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/GeneralNodePaletteTreeItemTypes.h
- Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.cpp
- Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/MethodConfiguration.cpp
- Gems/ScriptCanvas/Code/Tools/TranslationGeneration.cpp
- Gems/ScriptCanvas/Code/Tools/TranslationGeneration.h
With this change, we can create .names file for BC global methods
Extra changes:
1. Use private helper function to reduce redundancy in TranslationGeneration
2. Fix translation bug for method with multi results
3. Cleanup lots of create on the fly string 
> Add translation support for global method

- scripts/build/Platform/Linux/build_config.json
- scripts/build/Platform/Linux/deploy_cdk_applications.sh
- scripts/build/Platform/Linux/destroy_cdk_applications.sh
- scripts/build/Platform/Windows/build_config.json
- scripts/build/Platform/Windows/deploy_cdk_applications.cmd
- scripts/build/Platform/Windows/destroy_cdk_applications.cmd
CDK applications shipped with AWSI gems are created with CDK v1 while the deploy/destroy scripts try to install the latest version of CDK (v2), which causes incompatible CDK operations. This PR is for fixing the CDK version used by the scripts.
Verified the deploy/destroy scripts locally on Windows and Linux.
> Fix the CDK version for AWSI automation tests to avoid installing CDK v2

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnail.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnail.h
SharedThumbnail intances invalidate their state `m_state = State::Unloaded` when they are notified that their underlying `assetId` is removed from the catalog. This puts the SharedThumbnail object in a state where it will get re-rendered if a thumbnail with the same `SharedThumbnailKey` is requested.
Fixes #7902
Signed-off-by: Sebastien Demers <sebastien.demers91@gmail.com>
> Invalidates thumbnail state when the asset is removed from the catalog asset

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/AzEventHandler.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/AzEventHandler.h
The duplicate addresses in the reflection code below caused a serialization error, and the serialized entries would double every time they were saved. This has been fixed with custom serialization for owning node.
```
->Field("m_parameterSlotIds", &AzEventEntry::m_parameterSlotIds)
->Field("m_parameterNames", &AzEventEntry::m_parameterSlotIds)
```
> fix AzEventHandler node reflection with custom serializer

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/AzEventHandler.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/AzEventHandler.h
Fixes https://github.com/o3de/o3de/issues/9243
Fixes a bug that causes ScriptCanvas graphs that contain an AZ::Event node to double their file size every time they are saved. Eventually, this can lead to a crash when attempting to open the file. This fix seamlessly repairs all previous content, users will not see the error, but will only see a reduction in file size whenever they next save the erroneous graphs.
* fix AzEventHandler node reflection with custom serializer
* fix Linux compile error
> Cherry pick: fix AzEventHandler node reflection with custom serializer (#9393)

- Gems/ScriptAutomation/Code/Source/ScriptAutomationSystemComponent.cpp
- Gems/ScriptAutomation/Code/Source/ScriptAutomationSystemComponent.h
Lua scripts are loaded using the serialization system now(Changed in https://github.com/o3de/o3de/pull/9343). The script asset needs to be compiled first. 
Calling `Load` on the `ScriptSystemRequestBus` executes the script immediately. But we want to queue the script for execution. So we compile the script, assign it to a newly created script asset, and return the asset.
> Fix build error caused due to incompatibility with recent changes in the script system

- Gems/AudioSystem/Code/Source/Editor/ATLControlsPanel.cpp
- Changes the order of text and icon in a filter sub-menu.
- Adjusts layout for another menu so icons look a bit nicer.
- Improves consistency.
closes #4542
New filters menu:
New add menu:
New add context menu:
> Moves icons in a sub-menu and adjusts layout (Audio Controls Editor)

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ReflectedPropertyEditor.cpp
The issue is that the AZStd::string class does not support dynamic allocations through the reflected AZStd::string [SerializeContext ClassData object factory](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Serialization/AZStdContainers.inl#L3284-L3296) due the [NullFactory](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Serialization/AZStdContainers.inl#L107-L113) being used.
It has been change to use the SerializeConext::CreateAny function instead.
fixes #9356
> Fixed crash when using the ChangeValidate attribute with a string field.

- Gems/LmbrCentral/Code/Source/Builders/LuaBuilder/LuaBuilderWorker.cpp
- Gems/LmbrCentral/Code/Tests/Builders/LuaBuilderTests.cpp
- Gems/LmbrCentral/Code/Tests/Lua/dependencyRegexStress.lua
The Lua dependency regex could miss a few standards uses of 'require', so the regex has been updated and a stressful regex has been added.
> make Lua dependency regex more robust

- Code/Tools/SceneAPI/SceneCore/Events/AssetImportRequest.cpp
- Code/Tools/SceneAPI/SceneCore/Tests/Events/AssetImporterRequestTests.cpp
- Gems/SceneProcessing/Code/Source/SceneBuilder/SceneBuilderWorker.cpp
- Gems/SceneProcessing/Code/Tests/SceneBuilder/SceneBuilderTests.cpp
{lyn12122} fixes for empty scene manifest loading
* Handle empty scene manifest by constructing a default scene rule set
* Check empty scene manifest during scene work building
> {lyn12122} fixes for empty scene manifest loading

- Gems/LyShine/Code/Source/UiCanvasComponent.cpp
- Gems/LyShine/Code/Source/World/UiCanvasOnMeshComponent.cpp
The UiCanvasOnMesh component wasn't getting the "OnCanvasLoaded" event from the UiCanvasRef bus if the UI canvas was set to load automatically in the UiCanvasAssetRef component. This is because the UiCanvasOnMesh component has a dependency on the UiCanvasAssetRef component so it is activated after the UiCanvasAssetRef component is activated and therefore connects to the bus after the canvas has already been loaded.
> Fix render target override issue in UiCanvasOnMesh component

- Templates/PrebuiltGem/Template/README.md
> Fixed typo in Prebuilt Gem instructions title

- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/material_editor_utils.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomMaterialEditor_BasicTests.py
- Code/Framework/AzToolsFramework/AzToolsFramework/Thumbnails/Thumbnail.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Thumbnails/Thumbnail.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Thumbnails/ThumbnailerBus.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Thumbnails/ThumbnailerComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Thumbnails/ThumbnailerComponent.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Thumbnails/ThumbnailerNullComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Thumbnails/ThumbnailerNullComponent.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Application/AtomToolsApplication.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentMainWindow.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentSystem.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentSystemRequestBus.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystem.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/main.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.h
- Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocumentRequestBus.h
- Gems/Atom/Tools/MaterialEditor/Code/Source/main.cpp
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/main.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/EditorCommonFeaturesSystemComponent.cpp
Atom tools application was never updated to handle Python arguments or return codes. Additionally, there have been AR stability issues, which seem to be related to calling idle_wait_frames within a Python script. The static function on the C++ side was connecting to the tick bus, counting tick events before allowing the Python script to continue processing. The previous implementation was not updating the main application event loop or sending tick events within the function local event loop. I'm not sure how this ever worked In atom tools or the main editor. The new version calls the application tick functions directly and removes the dependency on the tick bus.
Also required fixing material editor shut down issues caused by the thumbnail system, component service shut down order, and …
> Atom Tools: update base application handling for automated testing return values and fix problems with idle wait frames

- Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
Resolves #8808.
There were a few locations in the Asset Processor where copying an asset's full path to clipboard would only ever yield paths with a forward slash separator.
This commit converts those paths to use native separators so that they can be used within their respective environments directly after copying.
Affects paths copied from:
- Assets > Source Assets > [context menu] > Copy full path
- Assets > Product Assets > [context menu] > Copy full path
- Jobs > [context menu] > Copy
Signed-off-by: amzn-tmryan <104796591+amzn-tmryan@users.noreply.github.com>
> [Asset Processor] Use native separators when copying full asset path

- Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/EditorMaterialSystemComponentRequestBus.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/MaterialComponentBus.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentUtil.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentUtil.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
This change adds support to the material component and material instance inspector for editing material and property overrides across multiple selected entities. Prior to this, the material component would disable most editing features and display a warning message to the user whenever the number of selected entities != 1. This logic did not account for pinned inspectors, which maintain their own set of selected entities after they have been pinned. Multiple bugs and feature requests have been reported related to the messaging and lack of multi material customization.
- The material component no longer displays a warning message about having multiple entities selected.
- The material component and its dialogs respect and apply changes to the set of selected entities in the active …
> Material Component: Support for editing multiple selected entities

- Gems/WhiteBox/Code/Source/Viewport/WhiteBoxManipulatorViews.cpp
- Gems/WhiteBox/Code/Source/Viewport/WhiteBoxManipulatorViews.h
- Gems/WhiteBox/Code/Source/Viewport/WhiteBoxPolygonTranslationModifier.cpp
this is not a perfect solution but it addresses the problem where the manipulator is z-fighting in whitebox. might make sense to make this a post processing affect i.e render the polygon separately and use the depth test to highlight the selected polygon maybe? 
if you get close to the mesh you can see where the selected region is floating by a small margin. this is better then the current situation where this will z-fight.
> bugfix(Whitebox): add small margin to prevent z-fighting when working with polygon manipulator

- Code/Framework/AzCore/AzCore/RTTI/AzStdOnDemandReflection.inl
- Code/Framework/AzCore/AzCore/Serialization/AZStdContainers.inl
- Code/Framework/AzCore/AzCore/Serialization/SerializationUtils.cpp
- Code/Framework/AzCore/AzCore/Serialization/Utils.h
- Gems/EditorPythonBindings/Code/Source/PythonMarshalComponent.cpp
- Gems/EditorPythonBindings/Code/Source/PythonMarshalComponent.h
- Gems/EditorPythonBindings/Code/Source/PythonMarshalTuple.cpp
- Gems/EditorPythonBindings/Code/Source/PythonMarshalTuple.h
- Gems/EditorPythonBindings/Code/Tests/PythonPairTests.cpp
- Gems/EditorPythonBindings/Code/Tests/PythonTupleTests.cpp
- Gems/EditorPythonBindings/Code/editorpythonbindings_common_files.cmake
- Gems/EditorPythonBindings/Code/editorpythonbindings_tests_files.cmake
This allows tuples to be exposed and used explicitly, or implicitly interchanged with python tuples or lists.
When exposing methods to the BehaviorContext, it's recommended that people use AZStd::tuple<> when returning multiple return values so that the method is easy to use from Script Canvas. However, python didn't support tuple reflection, which made the APIs unusable from python. By adding tuple support to python, the APIs become easy to use from both methods.
Ex:
`didHit, position, normal = terrain.TerrainDataRequestBus(bus.Broadcast, 'GetClosestIntersection', math.Vector3(0.0, 0.0, 0.0), math.Vector3(1000.0, 1000.0, 0.0))`
> Add tuple support to python bindings.

- Gems/ScriptAutomation/Code/Source/ScriptAutomationScriptBindings.cpp
- Gems/ScriptAutomation/Code/Source/ScriptAutomationSystemComponent.cpp
Mark parameters used in AZ_Error/Warning/TracePrintf as maybe_unused
ifdef out lambda's that just call those macros
> Compile fixes for release config

- Code/Editor/AssetImporter/UI/SelectDestinationDialog.cpp
- Code/Editor/AssetImporter/UI/SelectDestinationDialog.ui
Also changed dialog title to Import Assets.
Resolves: #9210
Manually tested in a clean Windows profile build of development branch as of commit 204a10fe4ee6e2f8cefeaed9a2d900004853c34f morning of May 11th.
Signed-off-by: Mike Cronin <58789750+micronAMZN@users.noreply.github.com>
> Fixed link to Asset Processor docs from Import Assets dialog

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
This problem only occur when the root joint have non-freezed transform
> Fix an issue that causes wireframe render incorrectly

- Code/Editor/CryEdit.cpp
- Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
- Tools/LyTestTools/tests/unit/test_o3de_editor_test.py
Added Editor functionality to accept a file that contains a semicolon separated list of python modules. Also added LyTestTools functionality to create a temp file and passes it when there are too many batched tests.
Tested by running LyTestTools unit tests + locally modifying and running Physics test suite to use BatchedEditorTests.
> Fix LyTestTools cannot run more than 10 editor batched tests

- Gems/Terrain/Assets/Passes/TerrainDetailClipmapGenerationPass.pass
- Gems/Terrain/Assets/Passes/TerrainMacroClipmapGenerationPass.pass
- Gems/Terrain/Assets/Shaders/Terrain/ClipmapComputeHelpers.azsli
- Gems/Terrain/Assets/Shaders/Terrain/TerrainDetailClipmapGenerationPass.azsl
- Gems/Terrain/Assets/Shaders/Terrain/TerrainMacroClipmapGenerationPass.azsl
- Gems/Terrain/Assets/Shaders/Terrain/TerrainSrg.azsli
- Gems/Terrain/Code/Source/Components/TerrainSystemComponent.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/ClipmapBounds.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/ClipmapBounds.h
- Gems/Terrain/Code/Source/TerrainRenderer/Passes/TerrainClipmapComputePass.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/Passes/TerrainClipmapComputePass.h
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.h
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.cpp
- Gems/Terrain/Code/Tests/ClipmapBoundsTests.cpp
1. Created a special base pass for clipmap updating.
2. Clipmap compute pass will now be invoked only if there is a region to be updated.
3. The compute pass will distribute the region evenly to each compute thread. It is still dispatching at static thread numbers. We'll need some tests for dynamic numbers.
5. Fixed mod center no initialization in ClipmapBounds and added another test case for update region numbers.
To do:
1. There are still some float rounding issues within clipmap updating and sampling. One is by the precision of the rcp of the clipmap scale. Another is the actual view position doesn't match the clipmap center. Will fix these in later PR.
2. Add the margin for each clipmap to allow lazy update. This is partially done in the ClipmapCenter class using …
> [Terrain] Clipmap smart update initial version

- Code/Framework/AzNetworking/AzNetworking/Utilities/EncryptionCommon.cpp
I updated my system to `Ubuntu 22.04 LTS` looks like it comes with open ssl 3.0. This currently will fail to compile because ERR_func_error_string, ERR_load_BIO_strings are both deprecated. I updated the logic to handle compiling for 3 and above.
> chore: update EncryptionCommon to work with openssl 3.0

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Level_Loads.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/levelLoad_Atom_PbrMaterialChart.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/levelLoad_Atom_ShadowTest.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/levelLoad_Atom_Sponza.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/levelLoad_Atom_hermanubis.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/levelLoad_Atom_hermanubis_high.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/levelLoad_Atom_macbeth_shaderballs.py
Updated level load script in order to separate them into individual tests, as well as add a check to load an empty level ("base_empty") to ensure editor stability. These are P0 tests using the null renderer to ensure the level loads, and does not affect editor stability.
Here is more information on why this change is being implemented:
We initially had a version of the null renderer level load test that ran through each level in a loop (see "hydra_Atom_LevelLoadTest.py"). This version did catch several level load errors, but it did not contain the information needed to follow up on the issue. Since all levels were in a loop, they were all under the same timeout limitations, and it was unclear which specific level failed when the editor crashed/stalled. Separating them provides 2 benefits: …
> Adds seperated level load test

- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponentsLevel_DiffuseGlobalIlluminationAdded.py
adds additional P1 testing to Diffuse Global Illumination level component. we also add a diffuse probe grid since this level component only sets quality on the diffuse probe grid output so testing it without the probe grid is insufficient.
Report:
[SUCCESS] Success: Level has a Diffuse Global Illumination component
[SUCCESS] Success: UNDO Level component addition success
[SUCCESS] Success: REDO Level component addition success
[SUCCESS] Success: Quality Level set to Low
[SUCCESS] Success: Quality Level set to Medium
[SUCCESS] Success: Quality Level set to High
Test result: …
> Diffuse Global Illumination level component P1 test expansion

- Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbe.cpp
Changed MeshFeatureProcessor::SetVisible to only add or remove the mesh from the RayTracingFeatureProcessor if raytracing is enabled for the mesh.
All AtomSampleViewer tests passed
> ReflectionProbe visualization sphere is incorrectly added to the raytracing scene

- Code/Legacy/CryCommon/IMovieSystem.h
issue: https://github.com/o3de/o3de/issues/9326
this is a continuation of: https://github.com/o3de/o3de/pull/9134
> chore: deprecate SetParamValue/GetParamValue/Serialize Set/Pos/Rotation/Scale for IAnimNode

- Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
Changed fallback irradiance color to 1.0f.
Moved the lock in RayTracingFeatureProcessor::SetMesh to before the mesh list find operation.
> Changed fallback irradiance color to 1.0f

- Templates/CppToolGem/Template/Code/CMakeLists.txt
- Templates/DefaultGem/Template/Code/CMakeLists.txt
- Templates/PythonToolGem/Template/Code/CMakeLists.txt
The Trade-offs between an OBJECT and a STATIC LIBRARY are as follows
OBJECT_LIBRARY
---
1. Dead stripping isn't performed by default using clang/gcc
1. Symbols with external linkage are added to any linked shared library/executable
1. A duplicate copy of the object file isn't in an archive file
STATIC_LIBRARY
---
1. Dead stripping is performed by default using clang/gcc
1. Symbols with external linkage which are not used are not added to any linked shared library/executable
1. A duplicate copy of the object file existing the STATIC library.
For Gems the trade offs are the differences in shared library
size(.dll/.so/.dylib) size(larger for OBJECT libraries) vs a static
library that is only used internally within the gem and is not for
public consumption(Unneeded file in the build/install …
> Changing the Private Gem library target to be a STATIC library from an OBJECT library

- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MeshAdded.py
- Code/Framework/AzQtComponents/AzQtComponents/Gallery/ReflectedPropertyEditorPage.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/InstanceDataHierarchy.cpp
- Code/Framework/AzToolsFramework/Tests/InstanceDataHierarchy.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/EditorMeshComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/EditorMeshComponent.h
- Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp
- Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.h
- Gems/PhysX/Code/Editor/DebugDraw.cpp
- Gems/PhysX/Code/Editor/DebugDraw.h
Fixes #9478 
Fixed issue when trying to use an `UIElement` without a backing data element getting an incorrect/random order in the RPE (usually getting pinned to the top regardless of expected order).
The logic that was iterating through the children on the node in the `InstanceDataHierarchy` didn't handle the case where a child was found that had no edit data (which occurs on anything that is trying to be reflected from an `AZ::Component` because it has an `Id` parameter that is serialized but not exposed to the `EditContext`). So the logic wouldn't move forward past this child, which would result (usually) in any `UIElement` being pinned to the top, since it would never be able to correctly find the child index of the child that came before the `UIElement`.
Made the following changes:
- …
> Fixed UIElement ordering issue

- Gems/EditorPythonBindings/Code/Source/ActionManager/PythonActionManagerHandler.cpp
- Gems/EditorPythonBindings/Code/Source/ActionManager/PythonActionManagerHandler.h
- Gems/EditorPythonBindings/Code/Source/ActionManager/PythonEditorAction.cpp
- Gems/EditorPythonBindings/Code/Source/ActionManager/PythonEditorAction.h
As part of an investigation by @burelc-amzn ( https://github.com/o3de/o3de/pull/9279 ), it came up that `BehaviorArgument` will not invoke the destructor for stored objects when they get deallocated. As such, this would cause a memory leak on the Python side since callable objects referenced from the Action Manager would not be garbage collected when the system stopped referencing them.
Resolved the issue by splitting off the PyObject marshaling (`PythonEditorAction`) from the reference counting management (`PythonActionHandler`). This additionally allows us to easily un-register actions if that is ever needed.
> Action Manager | Refactor callable Python object tracking to prevent memory leaks

- cmake/Platform/Linux/ProcessDebugSymbols.cmake
These messages really clutter up the output during the build process:
```
[41/88] Linking CXX shared module bin/profile/libScriptCanvas.Editor.so
-- Detaching debug symbols from /build/ws/main/ninja-profile/bin/profile/libScriptCanvas.Editor.so into libScriptCanvas.Editor.so.dbg
[57/87] Linking CXX shared module bin/profile/libScriptCanvasTesting.Editor.so
-- Detaching debug symbols from /build/ws/main/ninja-profile/bin/profile/libScriptCanvasTesting.Editor.so into libScriptCanvasTesting.Editor.so.dbg
[58/87] Linking CXX shared module bin/profile/libScriptCanvasDeveloper.Editor.so
-- Detaching debug symbols from /build/ws/main/ninja-profile/bin/profile/libScriptCanvasDeveloper.Editor.so into libScriptCanvasDeveloper.Editor.so.dbg
[68/87] Linking CXX executable …
```
> Change mode of "Detaching debug symbols" messages to avoid spamming stdout during build

- Gems/LmbrCentral/Code/Source/Shape/BoxShape.cpp
Change turns off depth write for the filled box shape.
> Fix for Box shapes not rendering correctly when overlapping

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/Interpreted/ExecutionInterpretedAPI.cpp
This removes an assert which is no longer correct, no needed now that
all issues related to Lua Asset loading issues have been resolved.
Closes #9580
Fixes #9580
> remove overly aggressive assert in SC initialization

- cmake/Platform/Linux/LYWrappers_linux.cmake
Add check to prevent IMPORTED targets from attempting to do a post-build strip of debug symbols
> Fix Linux installer issue caused by new debug stripping options

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
> Fix mismatched `new[]` and `delete`

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
Tested both with a script canvas script and track view, and was able to set the visibility in both after this change.
Signed-off-by: Tommy Walton <waltont@amazon.com>
> Expose Set/GetVisibility to script canvas and track view.

- Gems/Atom/RHI/Code/Source/RHI.Private/FactoryManagerSystemComponent.cpp
Fixes #2051
The `RHI::FactoryManagerSystemComponent` had already the selection logic implemented. All that was missing was to populate the factories priority list.
In order to load the data into the member variable the user must define an entry in the settings registry using this path `/O3DE/Atom/RHI/FactoryManager/factoriesPriority`.
E.g. User specifies vulkan as top priority
```json
{
"O3DE":
{
"Atom":
{
"RHI":
{
"FactoryManager":
{
"factoriesPriority": [ "vulkan" ]
}
}
}
}
}
```
> Allows user to specify RHI priority by adding key in setreg file

- cmake/3rdParty/Platform/Android/BuiltInPackages_android.cmake
This is in response to development failing on some jenkins nodes.
Temporary fix for #7795 
I'm working on finding out why it doesnt' work on some of those machines and will prep a new package if necesasry.
> Temporarily reverts android to openssl1.1.1m

- Code/Framework/AzCore/AzCore/Math/MathReflection.cpp
- Code/Framework/AzCore/AzCore/Math/Vector2.cpp
- Code/Framework/AzCore/AzCore/Math/Vector3.cpp
- Code/Framework/AzCore/AzCore/Math/Vector4.cpp
- Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Controller.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Graph.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Graph.h
* Fix method overload node name for Vector2, Vector3, Vector4 and Quaternion
* Add check to upgrade tool when graph contains deprecated node
Changes involves ScriptCanvas editor usage only, tested locally by checking corresponding node name, and also use graph upgrade tool to make sure it can pickup expected graph in list
> Some overload node name fix and detect deprecate node when using upgrade tool

- Code/Framework/AzCore/AzCore/Component/Component.cpp
- Code/Framework/AzCore/AzCore/Component/Component.h
Fixes an issue related to timing described in https://github.com/o3de/o3de/issues/7579 .
* When nodes are selected in Script Canvas, its components are created and displayed in the detail pane of the Script Canvas editor
* If you select a group of nodes, and then delete them AFTER the components are rendered in the node inspector, everything works as expected
* If you select the group of nodes but press the delete key very quickly, before the selected components are rendered (less than half a second), then a crash occurs because invalidating the windows checks against the component's entities but the component may have already been deleted
This does not address the root timing issue, but is a safe fix to protect against this race condition.
> Fix for rapidly selecting and deleting a group of nodes in Script Canvas

- Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipService.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutorInterface.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicNotificationBus.h
Add new notification `OnRootPrefabInstanceLoaded` to inform users when the first root prefab instance load is done after loading current level file.
Tested manually with level opening/creating/switching. The breakpoint on code for sending `OnRootPrefabInstanceLoaded` is always triggered once the level being loaded, and all components in the root prefab instance's level container entity is de-serialized correctly when firing the notification.
> Add new notification for Root Prefab Instance's First Load

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/Inspector/InspectorWindow.cpp
This fixes a crash introduced by
20873d8427f3f13ff53c6eab7140d4c1a7293726. The Inspector window reuses
the widgets it creates. It does this by calling `takeWidget()` paired
with `setWidget()` on its `QScrollArea`. Calling `takeWidget()` removes
the current widget's parent, and returns ownership back to the caller.
To ensure that both the content widget and the no selection widget are
both destroyed, the Inspector window now takes back ownership of
whatever widget is in the scroll area (which can only be one of the
content widget or the no selection widget), and then deletes both of
them.
> [EMotionFX] Fix crash from Inspector window when closing the EMotionFX editor

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/FileManager.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/FileManager.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/AnimGraphPlugin.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/AnimGraphPlugin.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetManagementWindow.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetsWindowPlugin.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetsWindowPlugin.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionWindowPlugin.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionWindowPlugin.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/SceneManager/ActorsWindow.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/SceneManager/SceneManagerPlugin.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/SceneManager/SceneManagerPlugin.h
- Gems/EMotionFX/Code/Source/Editor/SaveDirtyFilesCallbacks.cpp
- Gems/EMotionFX/Code/Source/Editor/SaveDirtyFilesCallbacks.h
- Gems/EMotionFX/Code/emotionfx_editor_files.cmake
* Added save dirty file callbacks at a centralized place.
* Added save anim graph helpers to the file manager
* Removed the save dirty file callbacks from the plugins and register them from a centralized place
* Save dirty file callbacks still working with plugins not being present in the layout (now persistent).
> Animation Editor: Centralized save dirty file callbacks and made them persistent

- Code/Framework/AzFramework/AzFramework/Spawnable/InMemorySpawnableAssetContainer.cpp
When spawnable data is generated via prefab processing for editor game mode, the asset data already has an asset Id assigned. However, when creating an in-memory spawnable from serialized spawnable asset data (network server), the asset Id of the asset data is not assigned because asset Ids don't get serialized. 
If an asset is being created from asset data that has a valid asset Id but an asset Id is also passed to the constructor, an assert happens.
This PR adds a check to determine which is the appropriate constructor to call to avoid the assert.
> Fix assert when creating an in-memory spawnable

- Registry/prefab.editor.setreg
Fix bug #9016 by adding registry file `prefab.editor.setreg` in the Registry.
Verified by running the following command in editor's console:
```
pyRunFile <engine_path>\AutomatedTesting\Gem\PythonTests\largeworlds\dyn_veg\EditorScripts\ShapeIntersectionFilter_InstancesPlantInAssignedShape.py
```
> Add prefab.editor.setreg for enabling in-memory spawnables related automated tests on editor console

- Code/Framework/AzCore/Platform/Android/AzCore/IO/SystemFile_Android.cpp
- cmake/3rdParty/Platform/Android/BuiltInPackages_android.cmake
Android update to OpenSSL-1.1.1o - the previous update failed
becuase the build farm was on an older version of the NDK than
the package was built with.   Once the build farm is upgraded,
packages may use the new NDK, but until then, packages will use
the same NDK that the build farm does.
This also fixes a compile error (due to a warning-as-errors mode
triggering on a variable that was assigned but never used after
assignment).
See the openssl-1.1.1o-android-ndk-version-fix branch in
https://github.com/o3de/3p-package-source for the corresponding
changes to the package itself.
> Updates android to OpenSSL-1.1.1o and fixes a compile error

- Gems/Atom/RHI/Vulkan/Code/Source/Platform/Mac/Vulkan_Traits_Mac.h
- cmake/Tools/Platform/Android/android_deployment.py
The DX Shader Compiler has no "Az" at the end anymore.
The subprocess command in python, when using 'shell' has to be concatentated as the shell only views the first argument as all the arguments.
> Small changes to fix Android build and deploy on Mac

- Code/Framework/AzCore/AzCore/PlatformDef.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.cpp
- Gems/Multiplayer/Code/Source/Components/LocalPredictionPlayerInputComponent.cpp
- cmake/Platform/Common/Configurations_common.cmake
`AZ_DEBUG_BUILD` and `AZ_PROFILE_BUILD` already exist, but `AZ_RELEASE_BUILD` was missing and there is code using it, which was a bug.
Fixed Multiplayer gem cvars only defined when it's not release configuration.
> Added missing macro AZ_RELEASE_BUILD on release configuration.

- Code/Framework/AzCore/AzCore/Component/Component.cpp
- Code/Framework/AzCore/AzCore/Component/Component.h
- Gems/GraphCanvas/Code/Source/Components/SceneComponent.cpp
- Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
- Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Bus/ScriptCanvasBus.h
- Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.h
There are a few bugs logged ( https://github.com/o3de/o3de/issues/9335, https://github.com/o3de/o3de/issues/7579, https://github.com/o3de/o3de/issues/9335, https://github.com/o3de/o3de/issues/8016, https://github.com/o3de/o3de/issues/7849 ) that causes crashes in Script Canvas were all related to nodes being directly or indirectly deleted. 
This also undoes a previous fix attempt ( https://github.com/o3de/o3de/pull/9629 ) that instead tried to protect from accessing the nodes member variables in the middle of a deletion. (This partially fixed it in some situations, but the root cause was the timing issue that this change fixes), the description of the problem and a working solution was proposed in PR https://github.com/o3de/o3de/pull/9679 .  
But it seems all of the crashes can be …
> Fix for crashes on Linux when actions related to deleting nodes are invoked in Script Canvas

- Code/Editor/TrackView/2DBezierKeyUIControls.cpp
- Code/Editor/TrackView/AssetBlendKeyUIControls.cpp
- Code/Editor/TrackView/CaptureKeyUIControls.cpp
- Code/Editor/TrackView/CommentKeyUIControls.cpp
- Code/Editor/TrackView/ConsoleKeyUIControls.cpp
- Code/Editor/TrackView/EventKeyUIControls.cpp
- Code/Editor/TrackView/GotoKeyUIControls.cpp
- Code/Editor/TrackView/KeyUIControls.h
- Code/Editor/TrackView/ScreenFaderKeyUIControls.cpp
- Code/Editor/TrackView/SelectKeyUIControls.cpp
- Code/Editor/TrackView/SequenceKeyUIControls.cpp
- Code/Editor/TrackView/SoundKeyUIControls.cpp
- Code/Editor/TrackView/TimeRangeKeyUIControls.cpp
- Code/Editor/TrackView/TrackEventKeyUIControls.cpp
- Code/Editor/TrackView/TrackViewKeyPropertiesDlg.cpp
- Code/Editor/editor_lib_files.cmake
Fixes #7774 
There was a previous PR (https://github.com/o3de/o3de/pull/7201) that red-coded a legacy `IViewPane` class. This unintentionally broke the TrackView UI Key controls. The red-coded `CQtViewClass` and `IViewPane` classes were used by the original MFC Editor to register dockable view pane classes. Track View was (for some reason) piggy-backing on this system to instantiate key UI control classes (even though they weren't using any of the view pane bits of the classes, which is why the legacy view pane class appeared to be unused).
Even though this looks like a big change, this is all that's actually happening:
- The KeyUIControl classes were all declared + defined in cpp files, so moved the KeyUIControl declarations to a header file
- Updated the registration logic to explicitly …
> Restored broken TrackView KeyUI controls

- Gems/WhiteBox/Code/Source/Rendering/Atom/WhiteBoxAtomRenderMesh.cpp
- Gems/WhiteBox/Code/Source/Rendering/Atom/WhiteBoxAtomRenderMesh.h
looks like ApplyProperties is failing so the mesh will disappear. this is a continuation of the previous fix. 
https://user-images.githubusercontent.com/854359/169208246-afa59133-2f41-41a7-b16c-2c6d7326cc42.mp4
ref: https://github.com/o3de/o3de/pull/9442#event-6617921824
> bugfix(Whitebox): better handle updating material for whitebox mesh (GHI-9442)

- Code/Framework/AzCore/AzCore/Asset/AssetSerializer.h
- Code/Framework/AzCore/AzCore/Serialization/Json/JsonSerializer.cpp
- Code/Framework/AzCore/AzCore/Serialization/ObjectStream.cpp
- Code/Framework/AzCore/AzCore/Serialization/SerializeContext.cpp
- Code/Framework/AzCore/AzCore/Serialization/SerializeContext.h
- Code/Framework/AzFramework/AzFramework/Spawnable/InMemorySpawnableAssetContainer.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.hxx
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyManagerComponent.cpp
- Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/SerializationDependencies.cpp
- Gems/ImGui/Code/Source/LYCommonMenu/ImGuiLYEntityOutliner.cpp
- Tools/LyTestTools/ly_test_tools/_internal/pytest_plugin/test_tools_fixtures.py
Asset types are serialized with a custom serializer that uses the generic
serialization API. This allows for the serializer to be templated on the
asset type. Normally, the serialize context tries to create those generic
serializers only once, by keeping a map of AZ::TypeId->Serializer*. It
would look in the map to see if a serializer was already present, and only
if it wasn't found, it would create the serializer for that type.
However, the GenericClassInfo is allowed to override the typeid that
should be used to identify the types it handles. The map lookup was done
with the "canonical" typeid (ie, the result of AzTypeInfo<T>::Uuid()),
but then stored based on the generic's specialized typeid, (ie, the
result of SerializeGenericTypeInfo<T>::ClassInfoType::GetSpecializedTypeId()). …
> Fix memory leak when storing the generic class info for Assets

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/PipelineState.cpp
This a patch fix to prevent a NPE on Linux when switching viewports. It appears that there is a latent Job (RHI::FrameScheduler)  that still executes after a ```PipelineState::ShutdownInternal``` is called. This fix prevents access to the null pointer so that the job can terminate gracefully.
However, after switching viewport layouts, the window is not sized properly. (Created https://github.com/o3de/o3de/issues/9725 )
closing #9107
> Prevent Linux crash (NPE) when switching to a multi-view viewport

- Code/Framework/AzCore/AzCore/Math/Sphere.h
- Code/Framework/AzCore/AzCore/Math/Sphere.inl
- Code/Framework/AzCore/Tests/Math/SphereTests.cpp
small refactor of Sphere in AZCore Math. I think it would be worthwhile to make tall these API's consistent. not sure what that would entail. The default Set is unnecessary when you can just use a direct assignment copy constructor is useful when declaring a sphere. 
- introduced copy constructor
- use default assignment operator
- deprecate Set
> chore: simplify Sphere in AZCore Math

- Tools/LyTestTools/ly_test_tools/_internal/pytest_plugin/test_tools_fixtures.py
This reverts part of commit 6612d3cc7d.
> Re-disable the python tests in debug builds

- Code/Framework/AzFramework/AzFramework/TargetManagement/TargetManagementComponent.cpp
TargetJoinThread failed to Join since it was attempting to on itself. A thread joining on itself is normally a deadlock scenario but O3DE guards against this and fails silently. This led to the assert seen in https://github.com/o3de/o3de/issues/9612 which further caused AP to disconnect/crash.
This change moves the Join to a more appropriate spot.
Tested per the linked issue by opening the Lua IDE from Editor, closing the Lua IDE and confirming no assert occurred and AP did not disconnect/crash.
> Fix TargetJoinThread attempting to Join on itself

- Gems/AudioEngineWwise/Code/Source/Engine/AudioSystemImpl_wwise.cpp
- Gems/AudioEngineWwise/Code/Source/Engine/FileIOHandler_wwise.cpp
When formatting `AZ::u64` variables, use the `%llu` format rather than `PRIu64`.  In some places where 64-bit unsigned integer types have declarations from the Wwise SDK, they should be casted to the `AZ::u64` (`unsigned long long`) alias first for print, because they are likely typedefs of `unsigned long` on Android or Linux.
> [Wwise] Fixes print formatting errors on Android/Linux

- Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorUndo.cpp
- Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorUndo.h
- Gems/AudioSystem/Code/Source/Editor/QAudioControlTreeWidget.cpp
- Gems/AudioSystem/Code/Source/Editor/QAudioControlTreeWidget.h
- Renaming folders in the ATL controls panel of the audio controls
editor weren't added to the undo stack.
- This adds undo functionality whenever the user changes the name.
closes #6880
> Add undo/redo functionality to folder renames in Audio Controls Editor

- Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
#9804  Fixed incorrect properties display when the component is blocked from activating due to unresolved dependencies
> #9804 Fixed incorrect properties display when the component is blocked from activating due to unresolved dependencies

- Code/Framework/AzCore/AzCore/Math/Aabb.h
- Code/Framework/AzCore/AzCore/Math/Aabb.inl
- Code/Framework/AzCore/Tests/Math/AabbTests.cpp
small update to Aabb with span to avoid passing raw pointers and also fixed a crash when passing in points where the numPts is zero.  
> chore: add CreatePoints with span for aabb

- Code/Framework/AzCore/AzCore/Math/Geometry2DUtils.cpp
- Code/Framework/AzCore/AzCore/Math/Geometry2DUtils.h
minor improvement where these can take a span instead of a vector. should be compatibility with the case where a vector is passed in. 
> update Geometry2DUtils and Geometry3DUtils with span

- Gems/WhiteBox/Code/Source/EditorWhiteBoxComponentMode.cpp
- Gems/WhiteBox/Code/Source/EditorWhiteBoxComponentMode.h
ref: https://github.com/o3de/o3de/issues/8652
this adds the missing tooltips for whitebox in edit mode. 
> feature(Whitebox): add missing tooltips to WhiteBox when in Edit Mode (GHI-8652)

- AutomatedTesting/Gem/PythonTests/Terrain/EditorScripts/TerrainPhysicsCollider_ChangesSizeWithAxisAlignedBoxShapeChanges.py
- Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
- Code/Framework/AzFramework/AzFramework/Physics/ShapeConfiguration.cpp
- Code/Framework/AzFramework/AzFramework/Terrain/TerrainDataRequestBus.h
- Gems/PhysX/Code/Include/PhysX/SystemComponentBus.h
- Gems/PhysX/Code/Mocks/PhysX/MockPhysXHeightfieldProviderComponent.h
- Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
- Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.h
- Gems/PhysX/Code/Source/HeightfieldCollider.cpp
- Gems/PhysX/Code/Source/HeightfieldCollider.h
- Gems/PhysX/Code/Source/HeightfieldColliderComponent.cpp
- Gems/PhysX/Code/Source/HeightfieldColliderComponent.h
- Gems/PhysX/Code/Source/Utils.cpp
- Gems/PhysX/Code/Tests/EditorHeightfieldColliderComponentTests.cpp
- Gems/PhysX/Code/physx_files.cmake
- Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
- Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.cpp
- Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
- Gems/Terrain/Code/Tests/TerrainSystemBenchmarks.cpp
These changes make all terrain physics heightfield updates asynchronous, which makes the overall update time faster and keeps the editor more responsive.
The following changes were made to support this:
* Changed the HeightfieldProviderBus to support concurrent requests
* Removed the Create/Destroy flags from the Heightfield data updates. They didn't behave any different than Settings, and just added to the number of conditions and flags that needed to be checked, so they were consolidated down to just a "Settings" notification.
* Renamed "NumJobsMax" constant to "UseMaxJobs" for increased clarity.
* Added mutex to PhysXSystemBus so that it can be used from multiple threads, though not concurrently.
* Refactored all the duplicated HeightfieldCollider logic out of …
> [Terrain] First pass of async terrain physics

- AutomatedTesting/Gem/PythonTests/Terrain/TestSuite_Main.py
The Terrain_SupportsPhysics test intermittently fails because it creates a sphere that starts with penetrating the heightfield, and relies on waiting a certain amount of time to detect a collision. If the heightfield takes too long to initialize, the test can fail because the sphere won't detect the collision. Disabling the test until it can be improved and be made deterministic.
> Skip Terrain_SupportsPhysics test until it can be made more stable.

- Code/Tools/SceneAPI/SceneBuilder/Importers/AssImpSkinWeightsImporter.cpp
- Code/Tools/SceneAPI/SceneBuilder/Importers/AssImpSkinWeightsImporter.h
Fixed an issue that causes the skin mesh render only part of the mesh. The root cause is when sanitize name process actually change the bone name (e.g bone.001 -> bone_001), the skin weight data now will stores the sanitized name.
> Use sanitized name in skin weight data

- AutomatedTesting/Gem/PythonTests/Terrain/EditorScripts/Terrain_SupportsPhysics.py
- AutomatedTesting/Gem/PythonTests/Terrain/TestSuite_Main.py
- Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
The Terrain_SupportsPhysics test intermittently failed, which caused the test to get disabled. This PR re-enables a fixed version of the test.
1. The test was creating a sphere and a heightfield and waiting for a collision. However, the starting point of the sphere was intersecting the heightfield, so if the sphere fell faster than the heightfield initialized, it could end up below the heightfield without a collision. The fix is to disable gravity on the sphere, so it is guaranteed to collide once the heightfield finishes initializing.
2. The test exposed a subtle race condition in the new async terrain physics code where it could deadlock if the terrain system was shutting down in the middle of a terrain physics update. The fix is to verify that the terrain async system call actually …
> [Terrain] Fix and re-enable Terrain physics python test

- AutomatedTesting/Gem/PythonTests/editor/TestSuite_Main.py
These 2 editor automation tests delete the tmp_level during teardown but they can also run into a scenario where the tmp_level is still present during setup due to a previous crash or as a remnant of some other test suite run. In such cases, these 2 tests timeout and fail.  So, I added an additional guardrail to remove the tmp_level from disk if it exists before the test is begun.
> Add better guardrails for test level clean up for editor tests

- scripts/build/Jenkins/Jenkinsfile
In periodic multi-branch pipeline, PR builds always set PR status check "**continuous-integration/jenkins/pr-merge**", when people use JOB_LIST_OVERRIDE in periodic PR build to only build certain build configurations, we don't want the PR status check to be updated.
> Set periodic PR build status to unstable on sucess

- Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
- Code/Tools/AssetProcessor/native/ui/MainWindow.ui
* the "debug output" flag can be set inside the AP-GUI now so that users can see debug output while the AP-GUI tool is running
>
> Enabled Debug Output in AP-GUI

- Gems/WhiteBox/Code/Source/Components/EditorWhiteBoxColliderComponent.cpp
a new collider instance is created for every time the whitebox mesh is re-generated. This logic just ensure that the previous collider is removed when re-generating the new collider. 
ref: https://github.com/o3de/o3de/issues/7819
> bugfix(Whitebox): Destroy Physics Collider when whitebox mesh is submitted (GHI-7819)

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTableModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTableModel.h
Resolves assertion encountered during Editor startup in debug mode which was introduced by the changes in PR #9564. This issue is only seen in debug mode and does not appear to cause any issues otherwise.
Prior to PR #9564, there was rapid rebuilding of the Asset Browser's search result table model during Editor startup. Stopping the repeated rebuilds resulted in an empty `QPersistentModelIndex` map in the custom `AssetBrowserTableModel` when the editor finished loading. In turn, this resulted in us tripping [this assert](https://code.woboq.org/qt5/qtbase/src/corelib/itemmodels/qabstractitemmodel.cpp.html#2722) in `QAbstractItemModel::beginInsertRows` as signals made their way up from the base `AssetBrowserModel`.
This [Qt documentation](https://doc.qt.io/qt-5/qtwidgets-itemviews-customsor …
> Prevent AssetBrowserTableModel assertion at Editor startup

- Gems/Terrain/Assets/Shaders/Terrain/TerrainMacroHelpers.azsli
- Gems/Terrain/Assets/Shaders/Terrain/TerrainSrg.azsli
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainMacroMaterialManager.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainMacroMaterialManager.h
Macro material information is stored in a grid across the terrain, with each tile in the grid supporting up to 4 macro materials and covering 64m x 64m. Previously the total number of indexable macro materials was limited to a uint16, which means it would break with worlds larger than 8km x 8km. Also each tile stored the full macro material for every entry at 32 bytes per entry / 128bytes per tile.
This change makes it so the total number of tiles is limited to uint32, which should be more than large enough for any amount of terrain with the current terrain system. This change also adds a level of indirection, so the macro materials themselves are stored in a separate buffer, and the tiles just reference that buffer with 16 bit indices. This means the 4 macro materials per tile only cost …
> [Terrain] Macro materials can cover very large world areas

- Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridBlendDistancePass.cpp
- Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridBlendIrradiancePass.cpp
- Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridBorderUpdatePass.cpp
- Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridClassificationPass.cpp
- Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridPreparePass.cpp
- Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridQueryPass.cpp
- Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridRayTracingPass.cpp
- Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridRelocationPass.cpp
- Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridVisualizationAccelerationStructurePass.cpp
- Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridVisualizationPreparePass.cpp
- Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridVisualizationRayTracingPass.cpp
Changed the BuildCommandListInternal override in the DiffuseProbeGrid passes to split work based on the number of command lists
> Handle the command list index in the Diffuse GI passes

- Code/Framework/AzFramework/AzFramework/Spawnable/InMemorySpawnableAssetContainer.cpp
- Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableAssetBus.h
- Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableAssetHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabInMemorySpawnableConverter.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabToInMemorySpawnableNotificationBus.h
- Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
The "OnPreparingSpawnable" notification was a generic notification that was being called on every spawnable load. This PR replaces this notification with a more specific one that is only called on the tools side when a prefab template is to be processed and converted into an in-memory spawnable. This is used in editor networking code so that unchanged spawnables can be sent to the server and have their aliases resolved there instead of resolving them first on the client, which may have different alias resolving logic.
> Change OnPreparingSpawnable notification to be specific to tools

- Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
The QString and likely more, were being accessed after deletion.
Fixes #9707 
**Testing**
- Add, rename and remove projects
> Fix crash accessing from deleted path

- Code/Framework/AzCore/AzCore/Math/LineSegment.cpp
- Code/Framework/AzCore/AzCore/Math/LineSegment.h
- Code/Framework/AzCore/AzCore/Math/Ray.cpp
- Code/Framework/AzCore/AzCore/Math/Ray.h
- Code/Framework/AzCore/AzCore/azcore_files.cmake
- Code/Framework/AzCore/Tests/Math/LineSegmentTests.cpp
- Code/Framework/AzCore/Tests/Math/RayTests.cpp
- Code/Framework/AzCore/Tests/azcoretests_files.cmake
here is the start of introducing ray and LineSegment primative. I was thinking this could be a good strategy in standardizing things a bit. not sure how I would standardize IntersectSegment.h I was thinking along the lines of just using these primitive types in place of and introducing new method names if not consistent. 
If we do go this route is there any good reason to introduce methods to lets say get intersect ray with X and also having to implement it in the opposite case. i.e intersect AABB and AABB would provide an intersection method for a ray. 
There are some edge cases where we store the reciprocal of the direction. not sure if Ray should track that by default and the two places where I see this being uses Its being calculated when calling the method negating any reason to …
> feat: add Ray and LineSegment to AZCore/Math

- Gems/LmbrCentral/Code/Source/Shape/SplineComponent.cpp
seem PropertyEnumComboBoxCtrl.hxx its unable to fetch the EnumType from `AZStd::vector<AZStd::pair<ValueType, AZStd::string>`. Might make sense to write some test cases that that cover this case because this problems seems platform specific between linux and windows. This does address the serialization problem when I switched to `AZ::Edit::EnumConstant` since the other code path is marked as deprecated?
ref: https://github.com/o3de/o3de/issues/9904
> bugfix: fix spline types for SplineComponent for linux (GHI-9904)

- AutomatedTesting/Levels/Navigation/NavigationSample/city_generator.scriptcanvas
- AutomatedTesting/ScriptCanvas/ScriptCanvas_SpawnEntityWithPhysComponents.scriptcanvas
- AutomatedTesting/ScriptCanvas/Spawnables/DespawnOnEntityDeactivate.scriptcanvas
- AutomatedTesting/ScriptCanvas/Spawnables/MultipleSpawnsFromSingleTicket.scriptcanvas
- AutomatedTesting/ScriptCanvas/Spawnables/NestedSpawnerSpawner.scriptcanvas
- AutomatedTesting/ScriptCanvas/Spawnables/SimpleNestedSpawn.scriptcanvas
- AutomatedTesting/ScriptCanvas/Spawnables/SimpleSpawnDespawn.scriptcanvas
- AutomatedTesting/ScriptCanvas/Spawnables/SimpleSpawnNoDespawn.scriptcanvas
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/SpawnNodeable.ScriptCanvasNodeable.xml
Signed-off-by: Bartosz Cwiek [100559077+LB-BartoszCwiek@users.noreply.github.com](mailto:100559077+LB-BartoszCwiek@users.noreply.github.com)
Adding the missing dot at the end of the SpawnedEntitiesList parameter tooltip. Fixing the tooltip in existing AutomatedTesting .scriptcanvas files.
Before changes:
After changes:
> Fixing the lack of a dot at the end of SpawnedEntitiesList parameter tooltip

- scripts/build/Platform/Android/build_config.json
- scripts/build/Platform/Android/pipeline.json
- scripts/build/Platform/Linux/build_config.json
- scripts/build/Platform/Linux/pipeline.json
- scripts/build/Platform/Mac/build_config.json
- scripts/build/Platform/Mac/pipeline.json
- scripts/build/Platform/Windows/build_config.json
- scripts/build/Platform/Windows/pipeline.json
- scripts/build/Platform/iOS/build_config.json
- scripts/build/Platform/iOS/pipeline.json
Change nighty/weekly pipeline tag to periodic daily/weekly
Remove periodic build configurations that are also built in default pipeline
> Rename nightly weekly pipeline

- Gems/EMotionFX/Code/Source/Integration/Components/ActorComponent.cpp
- Gems/EMotionFX/Code/Source/Integration/Components/ActorComponent.h
- Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp
- Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.h
* Fixed a bug where the entity got reset to root level when unassigning the actor when using an attachment component.
* Removed attachment target actor variable that wasn't needed to be cached. (Fixed a crash)
* Code cleaning
Fixes #9550
https://user-images.githubusercontent.com/43751992/171650151-7ac1aa61-9ea8-4dae-b697-e0ad9a3e54b3.mp4
> EMotion FX: Unassigning the actor re-parents the entity to root level

- Code/Framework/AzCore/AzCore/std/ranges/ranges.h
- Gems/SceneProcessing/Code/Source/Generation/Components/MeshOptimizer/MeshOptimizerComponent.cpp
For some reason the `to_address` call in the AZStd::ranges::view_interface to avoid a incomplete base class error.
The MeshOptimizerComponent VS2022 was having issues capturing a captured variable into inner lambda.
Both of these issues I attribute for VS2022 compiler bugs.
> VS2022 Compile fixes.

- scripts/build/Platform/Linux/build_config.json
- scripts/build/Platform/Mac/build_config.json
- scripts/build/Platform/Windows/build_config.json
Puts in a exclude rule for GPU test in non-GPU benchmark jobs
> Explicltly call benchmark test in build config

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Benchmark_GPU.py
- Fixes an error currently appearing on benchmark GPU runs.
- The error observed can be found here: https://github.com/o3de/o3de/issues/7795#issuecomment-1148113928
>  Make Benchmark GPU test exclusive to Windows

- Code/Tools/AssetProcessor/native/utilities/ApplicationManager.h
- Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
- Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.h
- Code/Tools/AssetProcessor/native/utilities/AssetUtilEBusHelper.h
- Code/Tools/AssetProcessor/native/utilities/BatchApplicationManager.h
- Code/Tools/AssetProcessor/native/utilities/BuilderManager.cpp
- Code/Tools/AssetProcessor/native/utilities/BuilderManager.h
- Code/Tools/AssetProcessor/native/utilities/GUIApplicationManager.cpp
- Code/Tools/AssetProcessor/native/utilities/GUIApplicationManager.h
- Registry/AssetProcessorPlatformConfig.setreg
If the builder takes too long, the BuilderManager will timeout the process and terminate it.  
AP will now react to a builder failure by printing an error message and shutting down. 
Additionally, timeout was increased 3x from 5 minutes to 15 minutes as this situation was encountered when CPU was under heavy load.
Also fixed issue with StartupErrorCollector crashing on shutdown when QuitRequested is called
Fix was tested manually by lowering timeout to 1 second.
> Asset Processor - Fixed issue with AP waiting forever for builder registration

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEnumComboBoxCtrl.hxx
I noticed this when working on this PR: https://github.com/o3de/o3de/pull/9923. just a minor improvement shouldn't change this functionally. 
> chore: minor improvement replace push_back with emplace_back EnumValues

- Gems/ScriptCanvas/Code/Editor/View/Dialogs/ContainerWizard/ContainerTypeLineEdit.ui
Signed-off-by: LB-BartoszCwiek <v-bartosz.cwiek@lionbridge.com>
Fixed typo in the Container type tooltip.
Before changes:
After changes:
> Fixed typo in the Container type tooltip

- AutomatedTesting/Gem/PythonTests/Terrain/EditorScripts/Terrain_SupportsPhysics.py
This test was intermittently failing on AR runs, but it's not immediately clear why. It's possible that the OnCollisionBegin signal could be triggered *before* the test starts listening, which would cause the test to fail. By listening for collision persistence, this test should more robustly handle timing issues.
On the off chance that the timeout was too low in some scenarios, I've raised that as well. This seems much more unlikely to be the culprit, but it doesn't hurt to raise it, since the timeout only affects failures, not success.
> [Terrain] Changed test to watch for collision persistence instead of collision begin

- cmake/Platform/Common/RuntimeDependencies_common.cmake
Instead of searching to see if a target starts with "3rdParty::", instead the target is checked to see if it is IMPORTED.
> Updated detection of 3rdParty system libraries

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
Material component was previously only returning overridden property values. This prevented users from inspecting unmodified property values from script. This change keeps references to all of the material assets so that their default values can be accessed.
The material component will still only serialize manually assigned or overridden values. This change may lead to a subsequent revision, renaming override related functions like GetPropertyOverride to GetPropertyValue and GetMaterialOverride to GetMaterialAsset.
https://github.com/o3de/o3de/issues/9541
Tested the following script canvas script with and without overriding color values.
> Material Component: Returns default property values when there are no overrides

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
- Renamed save actions to clarify that “Save As” Is creating a new material from the settings in the inspector. “Save Over…” shows the name of the file that’s being overwritten in the menu option name.
- Removed the confusing “open” options from the material component inspector menu. Instead, any files that can be opened in the material editor now have links in the inspector heading. Clicking on any of the eligible material source files will open them in the material editor.
- This should address https://github.com/o3de/o3de/issues/9732 but is open to feedback for naming etc.
> Material Component: More explicit menu option names and links to open files in material editor

- AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py
GHI to fix the test: https://github.com/o3de/o3de/issues/9869
> Disabling test_Multiplayer_AutoComponent_RPC because it periodically fails

- Gems/Blast/Code/CMakeLists.txt
- Gems/PhysX/Code/CMakeLists.txt
- Gems/PhysX/Code/Source/Pipeline/MeshExporter.cpp
> Remove references to GFxFramework from PhysX and Blast gems

- Code/Tools/AssetProcessor/Platform/Mac/assetprocessor_mac.cmake
- Code/Tools/AssetProcessor/Platform/Mac/gui_info.plist
- cmake/Platform/Mac/runtime_dependencies_mac.cmake.in
Issue:  New files would not get deployed into application bundles at
all, leading to stale files in the bundles after changes were made.
Issue: AssetProcessor had a warning stating that the Product
Bundle Identifier did not match what in the info.plist file.
> Fixes mac deploying stale files and issuing warnings about info.plist

- Tools/LyTestTools/tests/unit/test_fixtures.py
- Tools/LyTestTools/tests/unit/test_py_logging_util.py
- Tools/LyTestTools/tests/unit/test_settings.py
Fixes unit tests from creating files in various ways. Issues found were mostly non-mocked file handlers. Also found issues with tests setting logging values. Tested by running all LyTestTools unit tests.
> Ly test tools unittest fix creating files

- Gems/Meshlets/ASV_GPU_and_CPU_Demo/MeshletsExampleComponent.cpp
- Gems/Meshlets/ASV_GPU_and_CPU_Demo/MeshletsExampleComponent.h
- Gems/Meshlets/ASV_GPU_and_CPU_Demo/Readme.txt
- Gems/Meshlets/ASV_GPU_and_CPU_Demo/SampleComponentManager.cpp
- Gems/Meshlets/Assets/Passes/MeshletsParent.pass
- Gems/Meshlets/Assets/Passes/MeshletsPassRequest.azasset
- Gems/Meshlets/Code/Source/Meshlets/MeshletsFeatureProcessor.cpp
- Gems/Meshlets/Code/Source/Meshlets/MeshletsFeatureProcessor.h
After this change there is no longer a need to manually add the passes to MainPipeline.pass
This submit also changes the location of the assets to reside inside ASV directories hence make it easy to test when updating with the ASV repo branch Atom/barlev/Meshlets_FinalWorkingVersion
> Meshlets - Adding pass injection to avoid manually altering the pass pipeline

- Gems/GradientSignal/Code/Include/GradientSignal/Components/ShapeAreaFalloffGradientComponent.h
- Gems/GradientSignal/Code/Source/Components/ShapeAreaFalloffGradientComponent.cpp
- Gems/LmbrCentral/Code/Source/Shape/TubeShape.cpp
- Gems/LmbrCentral/Code/Source/Shape/TubeShape.h
- Gems/LmbrCentral/Code/Tests/TubeShapeTest.cpp
While trying to use the Tube Shape with the Shape Falloff component with terrain, I discovered two separate bugs, fixed here:
1. The tube shape was returning non-zero DistanceFromPoint() values for points inside the tube.
2. The Shape Falloff component wasn't always refreshing correctly on shape component changes.
Before:
(bug 1) The interior of the tube in the shape falloff is hollow instead of solid.
(bug 2) The shape falloff only shows up while editing, but disappears again when not editing.
https://user-images.githubusercontent.com/82224783/173136816-b3890d90-c2c2-41c6-85e6-078232ca159c.mp4
After:
(bugs are fixed)
> [Terrain] Tube Shape / Shape Falloff Fixes

- Gems/Atom/Feature/Common/Code/Source/DisplayMapper/DisplayMapperPass.cpp
- Gems/Atom/Feature/Common/Code/Source/PostProcessing/LookModificationTransformPass.cpp
This fix was suggested on Discord, to fix a crash occurring when you try to redirect the final pass from the swapchain to a texture for example.
> Fix crash when binding swapchain to imported texture attachment

- Code/Tools/AssetProcessor/native/resourcecompiler/rcjob.cpp
- Code/Tools/AssetProcessor/native/tests/UnitTestUtilities.h
- Code/Tools/AssetProcessor/native/tests/resourcecompiler/RCJobTest.cpp
* The Asset Cache Server was not handling mixed paths when packing up the product artifacts
> {ly97798} fix to handle mixed path slashes for ACS

- Tools/LyTestTools/ly_test_tools/_internal/pytest_plugin/editor_test.py
- Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
- Tools/LyTestTools/ly_test_tools/o3de/editor_test_utils.py
- Tools/LyTestTools/tests/unit/test_o3de_editor_test.py
Minor fixes found while investigating another issue. Removes unused imports, variable name shadowing, and extra whitespace. Reduces pep8 warnings. Adds docstrings, type hints, and logging.
The only functional change is to the default number of parallel editors. If pipeline execution proves this value needs to be controlled, it can be modified by CTest registration.
Signed-off-by: Sweeney <sweeneys@amazon.com>
> Clean up EditorTest and set environment-aware default parallelism

- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MaterialAdded.py
- Gems/Atom/Feature/Common/Assets/Scripts/material_find_overrides_demo.lua
- Gems/Atom/Feature/Common/Assets/Scripts/material_property_overrides_demo.lua
- Gems/Atom/Feature/Common/Assets/Scripts/material_property_overrides_demo.py
- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Material/MaterialAssignment.h
- Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignment.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasViewportContent.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorViewportContent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/MaterialComponentBus.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentUtil.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewContent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Editor/Scripts/Materials/assign_material_to_all_entities.py
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.h
- Gems/Blast/Code/Source/Editor/EditorBlastMeshDataComponent.cpp
- Gems/Blast/Code/Source/Family/ActorRenderManager.cpp
- Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/MaterialComponentRequestBus.names
•	Added deprecated names to material component behavior context bindings
•	Updated script canvas display names and descriptions to match renamed functions
•	Changed get property value functions so that they return the default values stored in the active material asset
•	Updated and ran Lua and Python test scripts to verify that all properties are reported correctly
•	Minor changes to Lua scripts because script properties seems to be broken with prefabs
•	Tested using script canvas, Lua test scripts, material instance inspector, material editor, reporting property values to the output window
follow up changes for https://github.com/o3de/o3de/issues/9541
> Material Component: Updated and renamed material and property override functions

- AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/SurfaceDataRefreshes_RemainsStable.py
- Gems/GradientSignal/Code/Source/Components/LevelsGradientComponent.cpp
- Gems/SurfaceData/Code/Source/SurfaceDataSystemComponent.cpp
This fixes two small bugs:
1. The Levels Component was sending OnCompositionChanged() messages any time a value was set, even if the value was the same. Now it checks for differences before sending the notification.
2. The SurfaceData python test was sending the OnSurfaceChanged() notification to force vegetation refreshes, which broke due to a recent change to the API. However, the correct API for it to use was actually the RefreshSurfaceData() API, so I switched it to use the correct API instead of fixing up the previous notification usage.
> [Terrain] Misc Bugfixes

- Gems/AtomTressFX/External/Code/src/TressFX/TressFXSettings.cpp
removes a trailing space from the property name "Shadow LOD Start Distance" in TressFX hair gem
in testing I dumped the property tree editor property paths with type and this property now reports as
` Info: 'Controller|Configuration|TressFX Render Settings|Shadow LOD Start Distance' ('float', 'Visible')`
**atom component tests run:**
```
.\scripts\ctest\ctest_entrypoint.cmd --build-path atom_dev --suite main --ctest-executable "C:\Program Files\CMake\bin\ctest.exe" --config profile --tests-regex "AutomatedTesting::Atom_Main_Null" --generate-xml
Starting 'main' suite: The default set of tests, covers most of all testing.
Executing CTest None time(s) with command:
C:\Program Files\CMake\bin\ctest.exe --build-config profile --output-on-failure --parallel 16 --no-tests=error --label-exclude …
```
> hair gem shadow LOD start distance property remove trailing space

- Gems/Atom/RPI/Code/Source/RPI.Public/Material/Material.cpp
- Gems/Atom/RPI/Code/Tests/Material/MaterialTests.cpp
When a material property is updated on a material that doesn't have this property (which of course is a mistake), the material becomes stuck and cannot compile. 
As `Material::CanCompile` will return false (because its srg will not be queued for compilation), the material will simply try to compile every tick forever.
A simple fix is to check if the material compilation is required.
> Material: Fix Compile() when NeedsCompile() = false

- Code/Framework/AzFramework/AzFramework/Script/ScriptRemoteDebugging.cpp
- Code/Framework/AzNetworking/AzNetworking/Framework/INetworking.h
- Code/Framework/AzNetworking/AzNetworking/Framework/NetworkingSystemComponent.cpp
- Code/Framework/AzNetworking/AzNetworking/Framework/NetworkingSystemComponent.h
- Code/Tools/LuaIDE/Source/LUA/LUAEditorContext.cpp
- Code/Tools/LuaIDE/Source/StandaloneToolsApplication.cpp
Addresses https://github.com/o3de/o3de/issues/9075
The root cause of the issue is the manner in which Lua IDE halts the Editor when a breakpoint is hit. It does this by entering a while loop that only looks for other debug messages and thread yields. This unfortunately causes all network traffic to cease since network updates are sourced off the main thread's SystemTickBus.
There are a few potential fixes here
1. Allow SystemTickBus to operate in this debug state. Unfortunately, SystemTickBus also triggers things like high priority entity spawning so this did not seem appropriate for a stopped debug state.
2. Create a manual ForceUpdate function to allow AzNetworking to process traffic without SystemTickBus.
3. Move NetworkSystemComponent's updates off the main thread and SystemTickBus …
> Fix Lua IDE breakpoint stall and failure to register self as host

- Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpConnection.cpp
- Code/Tools/RemoteConsole/Core/RemoteConsoleCore.cpp
This addresses https://github.com/o3de/o3de/issues/10030. 
Issues addressed:
1. When a packet is compressed via TCP, the packet header continues to use the uncompressed payload size which causes buffer position issues on the receiving end.
2. TcpConnection's constructor for listeners never sets up m_compressor
3. When a packet is decompressed via TCP, the read buffer is advanced by the uncompressed size vs the compressed size. The read buffer has no concept of compression so it requires the size as received (compressed).
4. Not related, but RemoteConsole throws an AzSock error on startup. This just needed some edge case handling.
> Correct payload size calculations for compressed TCP and missing compressor

- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/PassAttachmentReflect.h
Fix for an apparent copy/paste error in the AZ_TYPE_INFO for PassFallbackConnection.
> fix typeinfo for PassFallbackConnection

- Code/Editor/Plugins/EditorAssetImporter/AssetImporterWindow.cpp
Signed-off-by: LB-BartoszCwiek <v-bartosz.cwiek@lionbridge.com>
Fixed wrong hyperlink under Fbx Settings>Help>Documentation and in the Scene Settings (PREVIEW) layout when clicking "Learn More..." button. 
Before changes Scene Settings documentation redirected to:
https://www.o3de.org/docs/user-guide/assets/
After changes it redirects to:
https://www.o3de.org/docs/user-guide/assets/scene-settings/
> Fixing wrong hyperlink for the Scene Settings

- .clang-format
As discussed in #dev-languages on Discord.
See https://clang.llvm.org/docs/ClangFormatStyleOptions.html
Signed-off-by: Joerg H. Mueller <joerg.mueller@huawei.com>
> Adopt BinPackArguments: false in .clang-format.

- Gems/Atom/Asset/ImageProcessingAtom/Code/Include/Atom/ImageProcessing/ImageProcessingBus.h
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/BuilderSettingManager.cpp
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/BuilderSettingManager.h
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/ImageBuilderComponent.cpp
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/ImageBuilderComponent.h
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvert.cpp
- Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvert.h
Currently, most of image processing is done inside the ImageProcessingAtom gem, and only a few functions are exposed.
It's interesting to expose some other functions to be able to do some image processing in memory, for example for a texture array  gem which only write one file for multiple images.
> ImageProcessing: expose some functions and allows in-memory processing

- Code/Framework/AzCore/AzCore/Math/Geometry3DUtils.cpp
- Code/Framework/AzFramework/Platform/Android/AzFramework/Application/Application_Android.cpp
- Code/Tools/Android/ProjectBuilder/gradle.properties.in
- cmake/Tools/Platform/Android/android_support.py
when building android the gradle step that builds c++ was not showing anything, making difficult to know the progression. Showing the C++ files compiled in the log, so it's more informative and doesn't spend 15 minutes without seeing anything in the log.
Also fixed some compilation errors from nightly build:
- `ThermalInfoHandler` is only defined in non release builds.
- multi-line comment error in linux gcc due to ending a line comment with `\`
> Android build shows C++ files progression.

- Code/Tools/AssetProcessor/native/FileServer/fileServer.cpp
- Gems/LyShine/Code/Editor/Animation/UiAnimViewUndo.cpp
- Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/EBusNodePaletteTreeItemTypes.cpp
- Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/GeneralNodePaletteTreeItemTypes.cpp
`toUtf8()` returns an object which will be destroyed as soon a the call finishes. By assigning its data to a `const char*` it keeps a reference to a deleted object. Fixed by passing it as parameter to the function, that way the data will be valid until the function finishes.
> Fix bug on FileServer converting QString to const char*

- Code/Tools/ProjectManager/Source/Application.cpp
- Code/Tools/ProjectManager/Source/Application.h
- Code/Tools/ProjectManager/Source/ProjectUtils.cpp
- Code/Tools/ProjectManager/Source/ProjectUtils.h
- Code/Tools/ProjectManager/Source/PythonBindings.cpp
- Code/Tools/ProjectManager/Source/PythonBindings.h
- Code/Tools/ProjectManager/Source/PythonBindingsInterface.h
- Code/Tools/ProjectManager/project_manager_tests_files.cmake
- Code/Tools/ProjectManager/tests/ApplicationTests.cpp
- Code/Tools/ProjectManager/tests/MockPythonBindings.h
- Code/Tools/ProjectManager/tests/PythonBindingsTests.cpp
- Code/Tools/ProjectManager/tests/UtilsTests.cpp
Idea 💡 how about not writing to the manifest and causing file locking errors when other unit tests are trying to read the manifest   Bonus points for not needed to re-configure every time because the manifest timestamp was changed 🚤 
Sarcasm aside, while this improves the speed and compatibility of the tests, it does lower our test coverage a bit because the Application::Init() call was acting like an integration test and likely running PythonBindings functions we were not unit testing.  But those should be identified and added in the PythonBindingsTests at a later time.
- added PythonBindings mock for tests that don't need actual python bindings (application test)
- removed unnecessary application from utils test
- prevent tests from calling RemoveInvalidProjects() code which would …
> Fix tests writing to manifest

- Gems/Atom/RPI/Code/Source/RPI.Reflect/Model/ModelAsset.cpp
A recent test failure contained the following assert:
[2022-06-17T08:41:29.792Z] E   [editor_test.log]  <08:40:21> (System) - Trace::Assert
[2022-06-17T08:41:29.792Z] E   [editor_test.log]   D:\workspace\o3de\Code\Framework\AzCore\AzCore/std/containers/vector.h(582): (15200) 'const struct AZ::RPI::ModelKdTree::MeshData &__cdecl AZStd::vector<struct AZ::RPI::ModelKdTree::MeshData,class AZStd::allocator>::operator [](unsigned __int64) const'
[2022-06-17T08:41:29.792Z] E   [editor_test.log]  <08:40:21> (System) - AZStd::vector<>::at - position is out of range
[2022-06-17T08:41:29.799Z] E   [editor_test.log]  <08:40:24> (System) - D:\workspace\o3de\Gems\Atom\RPI\Code\Source\RPI.Reflect\Model\ModelKdTree.cpp (265) : AZ::RPI::ModelKdTree::RayIntersectionRecursively
The line of code that's …
> Fix possible race condition with BuildKdTree().

- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
- Ensures the ReflectionAdapter gives attributes the correct instance
- aAd support for CallbackAttributes being bound to plain value types (this fixes up some ChangeNotify calls I saw)
Signed-off-by: Nicholas VanSickle <nvsickle@amazon.com>
> Fix DPE reflection support for bound attributes

- Code/Tools/Android/ProjectBuilder/build.gradle.in
Running `deploy_android.py` just generates the gradle solution, but it's not until the first time it's opened in Android Studio that it will run cmake configuration, and since the default configuration was debug it did the cmake for debug. Then when switching to profile it runs cmake configuration again, then you can build the project.
The most common configuration used is profile. So by setting it as default, the first time the Android Studio is opened it'll will configure cmake for profile and that way you only run cmake once and not twice for the most common case.
> Make profile the default configuration in Android.

- Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.h
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorMainWindow.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorMainWindow.h
Minor change, renaming inspector variables to be consistent across tools.
Might the document inspector and move it down to atom tools document application base class.
> Rename inspector widget variables to be consistent across atom tools.

- Gems/Multiplayer/Code/Source/Components/NetworkHierarchyRootComponent.cpp
Networked Entity Hierarchy rebuilds are triggered based on certain events occurring on contained entities. This includes state changes such as Activating. One side effect here is that an Activated entity can trigger a rebuild while children are not in an activated state. This causes the exception outlined in https://github.com/o3de/o3de/issues/10152.
There doesn't appear to be a mechanism to determine when a hierarchy is fully activated so instead this change guards against inactive entities.
A separate issue has been created to track a related problem on the AssetBuilder side of prefabs (https://github.com/o3de/o3de/issues/10196).
> Address exception during rebuilding a not fully active networked entity hierarchy

- AutomatedTesting/Levels/AWS/ClientAuth/ClientAuth.prefab
- AutomatedTesting/Levels/AWS/ClientAuthPasswordSignIn/ClientAuthPasswordSignIn.prefab
- AutomatedTesting/Levels/AWS/ClientAuthPasswordSignUp/ClientAuthPasswordSignUp.prefab
- AutomatedTesting/Levels/AWS/Core/Core.prefab
Previously, AWSCore and AWSClientAuth python tests were failing on account of their ScriptCanvas components not activating when their respective levels were run. Disabling, then re-enabling the SC components fixed the problem.
NOTE: had to manually fix file paths in .prefab files due to https://github.com/o3de/o3de/issues/10070
Python tests pass
```
// AWSCore tests
~\o3de>python\python.cmd -m pytest AutomatedTesting\Gem\PythonTests\AWS\core\test_aws_resource_interaction.py  --build-directory build\windows_vs2019\bin\profile
Pytest custom argument "--output-path" was not provided, defaulting Test Results output to: build\windows_vs2019\bin\profile\Testing\LyTestTools\pytest_results\2022-06-10T14-45-28-851301
================================================= test session starts …
```
> Fix component ScriptCanvas activation in AWS python tests

- Code/Framework/AzCore/AzCore/Preprocessor/Enum.h
- Code/Framework/AzCore/AzCore/Preprocessor/EnumReflectUtils.h
- Code/Framework/AzCore/AzCore/Serialization/EditContext.h
- Code/Framework/AzCore/Tests/EnumTests.cpp
Currently in the process of reflecting several material and shader related structs that use enums extensively. The same enum is used multiple times throughout some of the structs.
This utility function removes the boilerplate of adding all of the values manually for every data element.
Intended usage example
```
->DataElement(AZ::Edit::UIHandlers::Default, &StencilOpState::m_failOp, "Fail Op", "")
->Attribute(AZ::Edit::Attributes::EnumValues, AZ::Edit::GetEnumConstantsFromTraits<StencilOp>())
->DataElement(AZ::Edit::UIHandlers::Default, &StencilOpState::m_depthFailOp, "Depth Fail Op", "")
->Attribute(AZ::Edit::Attributes::EnumValues, AZ::Edit::GetEnumConstantsFromTraits<StencilOp>())
->DataElement(AZ::Edit::UIHandlers::Default, &StencilOpState::m_passOp, "Pass Op", "") …
```
> Added support for automatically registering enums with edit context

- Code/Framework/AzCore/AzCore/Preprocessor/Enum.h
- Code/Framework/AzCore/AzCore/Preprocessor/EnumReflectUtils.h
- Code/Framework/AzCore/AzCore/Serialization/EditContext.h
- Code/Framework/AzCore/Tests/EnumTests.cpp
- Gems/Atom/RHI/Code/Source/RHI.Edit/ShaderBuildArguments.cpp
- Gems/Atom/RHI/Code/Source/RHI.Reflect/RenderStates.cpp
- Gems/Atom/RPI/Code/Source/RPI.Edit/Shader/ShaderSourceData.cpp
- Gems/Atom/RPI/Code/Source/RPI.Edit/Shader/ShaderVariantListSourceData.cpp
Basic behavior and edit context reflection for ShaderBuildArguments, RenderState, ShaderSourceData, ShaderVariantListSourceData.
This does not yet include passes for descriptions or custom controls besides combo boxes for enum values. Descriptions, custom controls, and attributes for each property can be filled in iteratively by anyone familiar with the options, valid ranges, suitable control types.
Extends https://github.com/o3de/o3de/pull/10183 which adds a function for automatically populating edit context enum value attributes.
Screenshots testing edit context reflection in shader management console. Shader source data was only added for testing.
> Basic behavior and edit context reflection for ShaderSourceData and related types

- Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityModel.cpp
During the process of resolving #9780, we notice that we will generate undo nodes and update cache even for temporary making entity's parent id invalid during prefab propagation. This fix is to prevent these corner cases so that the workaround mentioned in #9780 could work as expected.
Tested following the workaround steps from #9780 with workaround changes https://github.com/aws-lumberyard-dev/o3de/pull/374.
> Prevent entity set as dirty while entity's parent is temporary invalid during propagation

- Gems/Atom/RHI/Code/Source/RHI/Factory.cpp
- Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/Device_Windows.cpp
- DRED previously was not working because DRED was enabled only after
device creation
- DRED output was missing context markers submitted from PIX events
- DRED page fault output was not emitted
- DRED output now logs to ~/.o3de/Logs/DRED/*.log. This avoids the issue
of DRED output being merged with log spew from other threads running
in the device-removed state
- Pix markers are now simply enabled globally on DX12 to support
instrumented crashes if compiled with PIX_ENABLED. They are needed for
proper TDR attribution but may now be disabled with
--disablePixGpuMarkers
The log emitted looks like this:
> Fix and improve DX12 DRED handling

- Gems/Atom/RPI/Code/Source/RPI.Public/RenderPipeline.cpp
- Gems/LyShine/Code/Source/Draw2d.cpp
If the root-pass of a custom renderpipeline isn't found, the engine crashes very late in the process, which makes it hard to attribute the actual cause of the crash.
The Feature Processor for LY-Shine relies on a renderpass with a specific name existing in the renderpipeline, and causes a crash if the pass doesn't exist, instead of disabling the functionality.
> Fix crashes when using a custom render-pipeline

- AutomatedTesting/Gem/PythonTests/smoke/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/smoke/test_CLITool_SerializeContextTools_Works.py
- Code/Framework/AzCore/AzCore/Debug/Trace.cpp
- Code/Framework/AzCore/AzCore/Debug/Trace.h
- Code/Framework/AzCore/AzCore/IO/GenericStreams.cpp
- Code/Framework/AzCore/AzCore/IO/GenericStreams.h
- Code/Framework/AzCore/AzCore/IO/SystemFile.cpp
- Code/Framework/AzCore/AzCore/IO/SystemFile.h
- Code/Framework/AzCore/AzCore/Utils/Utils.cpp
- Code/Framework/AzCore/AzCore/Utils/Utils.h
- Code/Framework/AzCore/Platform/Android/AzCore/IO/SystemFile_Android.h
- Code/Framework/AzCore/Platform/Common/Apple/AzCore/IO/SystemFile_Apple.h
- Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/IO/SystemFile_UnixLike.cpp
- Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/IO/SystemFile_UnixLike.h
- Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/Utils/Utils_UnixLike.cpp
- Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/IO/SystemFile_WinAPI.cpp
- Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/IO/SystemFile_WinAPI.h
- Code/Framework/AzCore/Tests/Debug/Trace.cpp
- Code/Framework/AzCore/Tests/Platform/Common/UnixLike/Tests/UtilsTests_UnixLike.cpp
- Code/Tools/SerializeContextTools/Application.cpp
- Code/Tools/SerializeContextTools/CMakeLists.txt
- Code/Tools/SerializeContextTools/Converter.cpp
- Code/Tools/SerializeContextTools/Converter.h
- Code/Tools/SerializeContextTools/Dumper.cpp
- Code/Tools/SerializeContextTools/Dumper.h
- Code/Tools/SerializeContextTools/Platform/Linux/PAL_linux.cmake
- Code/Tools/SerializeContextTools/Platform/Mac/PAL_mac.cmake
- Code/Tools/SerializeContextTools/Platform/Windows/PAL_windows.cmake
- Code/Tools/SerializeContextTools/main.cpp
Added a `dumptypes` command to the SerializeContextTools that can dump the reflected types(name and Uuid) to stdout or to a file using the --output-file.
The name and Uuid are separated by whitespace.
Added a `createtype` command to the SerializeContextTools that can create an instance of a reflected type and output it in json format. The instance can be written to stdout or to a file.
The dumptypes command can be run as follows
```bash
build/linux_ninja/bin/profile/SerializeContextTools dumptypes --project-path AutomatedTesting --output-file=<types.txt>
build/linux_ninja/bin/profile/SerializeContextTools dumptypes --project-path AutomatedTesting --output-file=<types.txt> --sort=id
```
An example createtype command could be
```bash
build/linux_ninja/bin/profile/SerializeContextTools …
```
> SerializeContextTools: `dumptypes` and `createtype` command 

- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
`PropertyEditorNodes` had an initializer list that was implicitly made up of `AttributeDefinition<bool>` copies - this change switches to an explicitly defined `initializer_list` with pointers to `AttributeDefinitionInterface*` in attempt to fix GCC builds (I have no way of validating this locally, but @alexmontAmazon helpfully pointed the issue out to me - if anyone has a way to validate that'd be appreciated!)
Signed-off-by: Nicholas Van Sickle <mail@nickvansickle.com>
> Take a stab at fixing GCC builds

- Gems/MotionMatching/Code/Source/FeatureMatrixMinMaxScaler.cpp
- Gems/MotionMatching/Code/Source/FeatureMatrixMinMaxScaler.h
- Gems/MotionMatching/Code/Source/FeatureMatrixTransformer.h
- Gems/MotionMatching/Code/Tests/MinMaxScalerTests.cpp
- Gems/MotionMatching/Code/motionmatching_files.cmake
- Gems/MotionMatching/Code/motionmatching_tests_files.cmake
* Added base transformer interface used for scaling and normalizing the feature matrix and query vector.
* Each transformer needs to provide an inverse transform as well.
* Added a min-max scaler for normalizing data based on first gathering the min/max values per feature component and then normalizing the data using that range.
* The min/max scaler also provides a way to specify the feature min/max values in case other than normalized ranges are desired.
* Clipping: The min/max scaler provides clipping support to guarantee the data values are within the expected feature range.
* Added a basic set of automated tests (will add some more ones as next).
> Motion Matching: Adding transformer interface and a min-max scaler used for feature normalization

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.cpp
The rotation manipulator was fixed in place making it hard to determine how the target object was oriented. This change makes the rotation manipulator follow the orientation of the target.
https://user-images.githubusercontent.com/854359/174224361-7e2e0063-6553-461e-b553-7bfe8488c43c.mp4
> feat(EMotionFX): improve functionality rotation manipulator by following orientation of target

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterEditor/Vector3GizmoParameterEditor.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterEditor/Vector3GizmoParameterEditor.h
The manipulator isn't need anymore since the opengl viewport was removed.  
> chore(EmotionFX): remove MCommon::TranslateManipulator from Vector3GizmoParameterEditor

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterEditor/RotationParameterEditor.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterEditor/RotationParameterEditor.h
one thing to note is how is this going to be used in practice seems kind of inconvenient to have the manipulator sit at 0,0,0? I would imagine this following the position of another parameter or parenting this to an existing bone. 
- add RotationManipulator for atom viewport
- remove MCore RotateManipulator
- fixed include paths 
https://user-images.githubusercontent.com/854359/174221449-6af8f018-adc9-42dd-97da-035753e48588.mp4
> feat(EmotionFX): add rotation manipulator for RotationParameter

- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Scene.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/SceneBus.h
- Gems/Atom/RPI/Code/Source/RPI.Public/RenderPipeline.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
Proposed fix for #9245: 
Add the event `PipelineStateLookupNeedsRebuild()` that causes a call to `RebuildPipelineStatesLookup()` during the next  `Scene::PrepareRender()`.
Trigger that event from `RenderPipeline::OnPassModified()` when appropriate.
> Fix for Vulkan crash if the multisampling state is changed

- Gems/Atom/Feature/Common/Assets/Passes/FullscreenShadow.pass
- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/DirectionalLightShadowCalculator.azsli
- Gems/Atom/Feature/Common/Assets/Shaders/Shadow/FullscreenShadow.azsl
- Gems/Atom/Feature/Common/Assets/Shaders/Shadow/FullscreenShadow.shader
- Gems/Atom/Feature/Common/Assets/atom_feature_common_asset_files.cmake
- Gems/Atom/Feature/Common/Code/Source/Shadows/FullscreenShadowPass.cpp
- Gems/Atom/Feature/Common/Code/Source/Shadows/FullscreenShadowPass.h
Issue was somehow ViewSrg::m_directionalLightShadows[m_lightIndex].m_cascadeCount could return a bogus number, causing cascadeCount to blow up the loop that writes to a fixed sized array. Clamped cascadeCount to maxCascadeCount and stored it as a member variable for reference in other functions.
> Fix for TDR caused by fullscreen shadow shader

- Code/Framework/AzCore/Platform/Android/AzCore/IO/SystemFile_Android.cpp
- Code/Framework/AzCore/Platform/Common/Apple/AzCore/IO/SystemFile_Apple.cpp
- Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/IO/SystemFile_UnixLike.cpp
- Code/Framework/AzCore/Platform/Linux/AzCore/IO/SystemFile_Linux.cpp
BSD based platforms such as MacOS and iOS do not support the system calls of `pipe2`.
Therefore the Apple platform implementation of [pipe](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/pipe.2.html) + [fcntl](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/fcntl.2.html)
Fixes compilation issue of AzCore.Tests on MacOS
The AzCore.Tests Trace UnitTest for MacOS were run
```
a483e72e0e72:o3de [user]$ build/mac_xcode/bin/profile/AzTestRunner libAzCore.T
ests.dylib AzRunUnitTests --gtest_filter=Trace*
cwd = /Users/Shared/Developer/o3de/o3de
LIB: libAzCore.Tests.dylib
Loading: …
```
> Split PAL implementation of PosixInternal::Pipe for UnixLike

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/RenderPlugin/RenderOptions.cpp
these are the default properties set by Orbit camera just moved the assignment directly to the property. I'm planning on remove the EmotionFX Camera. 
I plan to remove the rest of the manipulators after this change: https://github.com/o3de/o3de/pull/10181
> chore: remove OrbitCamera from RenderOptions

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp
Signed-off-by: LB-BartoszCwiek <v-bartosz.cwiek@lionbridge.com>
Fixed wrong hyperlink under Animation Editor > Help > Documentation.
Before changes Animation Editor documentation redirected to:
https://o3de.org/docs/
After changes it redirects to:
https://o3de.org/docs/user-guide/visualization/animation/
> Fixed wrong hyperlink for the Animation Editor

- Gems/GraphCanvas/Code/Source/Components/Slots/Data/DataSlotLayoutComponent.cpp
Signed-off-by: Artur Zięba <86952082+LB-ArturZieba@users.noreply.github.com>
**Change summary**
* Fixed a wording error on a tooltip that displays when attempting to drop an incompatible variable type onto Script Canvas node.
This fixes https://github.com/o3de/o3de/issues/10239.
> Fixed incompatible variable type error wording

- Gems/RecastNavigation/Code/Source/EditorComponents/EditorRecastNavigationPhysXProviderComponent.cpp
- Gems/RecastNavigation/Code/Source/EditorComponents/EditorRecastNavigationPhysXProviderComponent.h
- Gems/RecastNavigation/Code/Source/Misc/RecastNavigationMeshComponentController.cpp
- Gems/RecastNavigation/Code/Source/Misc/RecastNavigationPhysXProviderComponentController.cpp
- Gems/RecastNavigation/Code/Source/Misc/RecastNavigationPhysXProviderComponentController.h
- Gems/RecastNavigation/Code/Source/Misc/RecastNavigationPhysXProviderConfig.cpp
- Gems/RecastNavigation/Code/Source/Misc/RecastNavigationPhysXProviderConfig.h
Adds ability to filter which PhysX colliders are considered for navigation mesh calculation based on their assigned collision groups.
Ran unit tests.
Tested in the Editor that in-editor preview is affected by the collision group setting.
> Added collision group filtering to Recast Navigation PhysX Provider component

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
Fix for an assert on Editor start.
> Action Manager | Fix for PrefabIntegrationManager looking for the action manager interface when the system is not enabled and asserting.

- Gems/GraphModel/Code/Include/GraphModel/Integration/NodePalette/StandardNodePaletteItem.h
- Gems/LyShine/Code/Source/Animation/AnimTrack.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/NamedId.h
- Gems/ScriptCanvas/Code/scriptcanvasgem_headers.cmake
The CreateStandardNodeEvent and NamedId were surrounded with an extra set paranthesis and contained the name of the template parameter
The TUiAnimTrack contained the name of the template parameter "KeyType"
Signed-off-by: lumberyard-employee-dm <56135373+lumberyard-employee-dm@users.noreply.github.com
Here is how the names now look when running the following command
```
D:\o3de\o3de>build\windows_vs2019\bin\profile\SerializeContextTools.exe dumptypes --project-path AutomatedTesting > reflected_types_with_automated_testing_gems_by_typeid.txt
```
[reflected_types_with_automated_testing_gems_by_name.txt](https://github.com/o3de/o3de/files/8969984/reflected_types_with_automated_testing_gems_by_name.txt)
>
> Fix typenames of CreateStandardNodeEvent, NamedId and TUiAnimTrack

- AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Main.py
Disables Script Canvas Spawnables test to investigate an intermittent failure.
Task to Re-enable: https://github.com/o3de/o3de/issues/9789
Ran Prefab TestSuite_Main.py: 
```
================= 19 passed, 10 skipped, 1 warning in 24.14s ==================
```
> Disabling SC Spawnables tests for investigation

- Gems/LmbrCentral/Code/Source/Scripting/LookAtComponent.cpp
Fixes #10226 (the look at component would always set the uniform scale on the entity transform to 1).
Made a level with an entity looking at a moving target and verified that the scale was not trampled.
> fix bug with look at component setting uniform scale to 1

- Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.cpp
Fixes a bug in capsule debug draw where transform was being applied twice (both in DrawWireCapsule and in DrawWireCylinderNoEnds).
Manually tested with character physics debug draw.
> fix bug with transform being applied twice in capsule debug draw

- AutomatedTesting/Assets/ImageGradients/black_white_gsi.png
Adds missing test asset required by bilnear filtering test.
Fixes https://github.com/o3de/o3de/issues/10355
Ran GradientSignal tests locally: 
```
============================= 16 passed in 27.07s =============================
```
Ran periodic_test_profile suite on internal Jenkins:
```
[2022-06-25T20:34:57.506Z]       Start 184: AutomatedTesting::GradientSignalTests_Periodic_Optimized.periodic::TEST_RUN
[2022-06-25T20:35:36.260Z] 21/21 Test #184: AutomatedTesting::GradientSignalTests_Periodic_Optimized.periodic::TEST_RUN ......   Passed   37.72 sec
```
> Adding missing image gradient for bilinear filtering test

- Gems/Atom/Feature/Common/Code/CMakeLists.txt
- Gems/Atom/Feature/Common/Code/Source/Platform/Linux/runtime_dependencies_builders.cmake
- Gems/Atom/Feature/Common/Code/Source/Platform/Linux/runtime_dependencies_tools.cmake
- Gems/Atom/Feature/Common/Code/Source/Platform/Mac/runtime_dependencies_builders.cmake
- Gems/Atom/Feature/Common/Code/Source/Platform/Windows/runtime_dependencies_builders.cmake
- Gems/Atom/Feature/Common/Code/Source/Platform/Windows/runtime_dependencies_tools.cmake
- cmake/Gems.cmake
- cmake/Projects.cmake
- cmake/SettingsRegistry.cmake
Previously the .Tools variants including the Editor was getting the .Builders target added as dependenciees.
Added more verbose messages to the CMake scripts that determines the gem load dependencies to aid troubleshooting.
> Moved the Atom RHI DX12, Metal and Vulkan .Builders dependencies to only be added to the AssetBuilder

- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
This fixes a crash bug at runtime loading inputmapping assets in which a MemberAttribute attempts to bind to an incorrect member pointer. No regression test (yet) but can be tested as part of ReflectionAdapter testing.
Signed-off-by: Nicholas Van Sickle <mail@nickvansickle.com>
> DPE: Ensure instance pointers are correctly resolved

- Code/Framework/AzCore/Tests/Name/NameTests.cpp
For some reason it is tagging a clearly used variable as unused.
So the workaround is to provide the nameString capture a name of "nameString" which the MSVC compiler doesn't choke on.
> VS2022 17.3.0 warning workaround with referencing a lambda variable.

- cmake/Tools/Platform/Android/android_deployment.py
- cmake/Tools/Platform/Android/android_support.py
- cmake/Tools/Platform/Android/generate_android_project.py
- cmake/Tools/layout_tool.py
- Fixes how the parameter `--include-apk-assets` is read by the script. It was expecting a True/False value, but it's very easy to make the mistake of not putting True/False because all the other similar parameters do not work with a bool (`--overwrite-existing`, `--enable_unity_build`, `--unit-test`, `--debug`). So to make it consistent now  `--include-apk-assets` works like the others, they work by being there or not, but not with a bool.
- Fixes bug where android asset were always added into the APK, even when `--include-apk-assets` was not used.
- Fixes `copy_asset_files_to_layout` function, which it was missing to copy files if they don't exist in the target path.
- VFS assets now only copies the minimum assets that are necessary, not all …
> Fix android assets packaging in different modes (apk, sdcard, vfs)

- Code/Framework/AzQtComponents/AzQtComponents/Components/DockBarButton.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/DockBarButton.h
This fixes the minimization/maximization state of the main window. I use `WindowStateChange` event from the main window to determine the maximization state of the resize button. relying on just the user pressing the button does not cover all cases where the window is maximized/minimized.
test both clicking on the minimize/maximize button and also double clicking on the window. 
ref: https://github.com/o3de/o3de/issues/10048
> bugfix: fix minimization/maximization button for the Editor Window

- Gems/GraphModel/Code/Include/GraphModel/Model/Slot.h
- Gems/GraphModel/Code/Source/Model/Slot.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Core/DataTypes.h
- Gems/LandscapeCanvas/Code/Source/Editor/Core/GraphContext.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaFilters/AltitudeFilterNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaFilters/DistributionFilterNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaFilters/ShapeIntersectionFilterNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/PositionModifierNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/RotationModifierNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/ScaleModifierNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/SlopeAlignmentModifierNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaSelectors/AssetWeightSelectorNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Areas/AreaBlenderNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Areas/BaseAreaNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/GradientModifiers/BaseGradientModifierNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/GradientModifiers/GradientMixerNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/AltitudeGradientNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/BaseGradientNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/GradientBakerNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/ShapeAreaFalloffGradientNode.cpp
This custom data type and its special logic are no longer needed after changes to graph model to support multiple data types per slot.
Having this special data type also broke custom slot coloring after those changes.
Updated some function names and commenting per feedback from a prior PR.
Still debugging loss of automatic connections between landscape nodes with @cgalvan.
Tested restored highlighting to slots with corresponding type IDs
> Removing special invalid entity ID data type from landscape canvas

- Gems/PhysX/Code/Source/EditorRigidBodyComponent.h
- Gems/PhysX/Code/Source/RigidBodyComponent.h
- Gems/WhiteBox/Code/Source/Components/EditorWhiteBoxColliderComponent.cpp
- Gems/WhiteBox/Code/Source/Components/WhiteBoxColliderComponent.cpp
- Gems/WhiteBox/Code/Source/Components/WhiteBoxColliderComponent.h
Makes white box collider component incompatible with PhysX rigid body component (because the white box collider creates a rigid body itself, and since it uses a triangle mesh the rigid body can only be static or kinematic). Fixes #10349.
Manually verified that a rigid body component could not be added to an entity with a white box collider component.
> make white box collider component incompatible with rigid body component

- Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.cpp
{ghi10291} Default Proc Prefab applies correct translation
* reconfigured the logic so that the MeshData is matched with its own TransformData so that the SetLocalTransform() applies the correct 3x4 Matrix
* A side benefit will make this logic easier to extend in the future to find and apply other metadata about MeshData in the future
> {ghi10291} Default Proc Prefab applies correct translation

- Gems/Terrain/Assets/Shaders/Terrain/ClipmapComputeHelpers.azsli
- Gems/Terrain/Assets/Shaders/Terrain/TerrainPBR_ForwardPass.azsl
- Gems/Terrain/Assets/Shaders/Terrain/TerrainSrg.azsli
- Gems/Terrain/Code/Source/TerrainRenderer/ClipmapBounds.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.h
Normal bilinear has a typo and causes square blocks on terrain.
Add detail factor for clipmap so that it blends to macro at detail clipmap max distance.
> [Terrain] Fix bugs in terrain clipmap

- Code/Framework/AzCore/AzCore/Task/TaskGraph.cpp
Add a 'wait' if it's going to be signaled immediately because of an empty TaskGraph
> Fix TaskGraphEvent asserting when submitted with an empty TaskGraph

- Gems/Atom/RPI/Code/Source/RPI.Edit/Shader/ShaderSourceData.cpp
The warnings were due to the order of reflection.
In this case, the type SuperVariant was used by the type
ShaderSourceData, but ShaderSourceData was declared before SuperVariant.
Behavior context is not supposed to be order dependent - but it is,
currently, due to the way Lua binds.
Fixes a bug which causes an assert to pop up whenever AP starts. 
No issues found.
Tested on a mac.  After moving the code around, no more asserts on startup.
Example of error, for searchability
```
AssetBuilder: System: Trace::Assert
AssetBuilder:  /Volumes/Lumberyard/o3de-repos/o3de/Code/Framework/AzCore/AzCore/Script/ScriptContext.cpp(3461): (5006536192) 'AZ::LuaScriptCaller::LuaScriptCaller(AZ::BehaviorContext *, AZ::BehaviorMethod …
```
> Fixes Script reflection warnings on startup

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/GraphView/GraphView.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/GraphView/GraphView.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.h
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasGraphView.cpp
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Utils/GraphUtils.cpp
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Utils/GraphUtils.h
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/GraphCanvasGraphicsView/GraphCanvasGraphicsView.cpp
- Gems/GraphModel/Code/Include/GraphModel/GraphModelBus.h
- Gems/GraphModel/Code/Include/GraphModel/Integration/GraphController.h
- Gems/GraphModel/Code/Source/Integration/GraphController.cpp
Graph canvas provides various notifications that can be used to implement undo and redo but leave it up to the application to implement the functionality. Script canvas and landscape canvas rely on the main editor undo redo sequence point system. ATF document system provides hooks for undo redo as well but leave it up to the document class to decide what gets recorded and restored.
This change adds the support and notifications to graph model, the ATF graph view, and the material canvas document class.
Material canvas document is using the object serializer to store undo redo history of graph data. Choosing this approach instead of handling notifications for more fine-grained commands because operations can happen in batches and unpredictable order.
Added a utility class for managing …
> Material Canvas: Initial support for undo redo

- Code/Tools/AssetProcessor/assetprocessor_test_files.cmake
- Code/Tools/AssetProcessor/native/tests/BuilderManagerTests.cpp
- Code/Tools/AssetProcessor/native/tests/BuilderManagerTests.h
- Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
- Code/Tools/AssetProcessor/native/utilities/BuilderManager.cpp
- Code/Tools/AssetProcessor/native/utilities/BuilderManager.h
- Code/Tools/AssetProcessor/native/utilities/BuilderManager.inl
- Code/Tools/AssetProcessor/native/utilities/assetUtils.h
Add BuilderPurpose and reserve first builder for CreateJobs.
This will reduce the likelihood of CreateJobs having to wait for a builder to start up which should keep CreateJobs fast.
Usually this isn't an issue but when a lot of jobs are being cancelled (due to the user making changes while a file is processing) the AssetBuilders can be killed off and leave none left to run CreateJobs, which causes a delay before CreateJobs can run.
This is mostly for the use case when a user is (rapidly/frequently) making updates to a file.  When a job is in-flight, the only way it can be canceled is by another job for the same file, which requires CreateJobs to finish running.  This change ensures we can quickly complete CreateJobs to invalidate the old jobs ASAP.
Manually running AP
> Asset Processor - Reserve Builder for CreateJobs

- Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
my clang build was failing because these variables are unused.
> chore: remove unused variables from ApplicationManagerBase

- Gems/RecastNavigation/Code/Tests/NavigationMeshTest.cpp
- Gems/RecastNavigation/Code/recastnavigation_editor_tests_files.cmake
Disable async navigation unit tests as they have a tendency to occasionally fail in AR.
It's either timing or threading issues. The issue is being analyzed in https://github.com/o3de/o3de/issues/10343
Ran unit tests.
> Disable async Navigation unit tests to unblock AR

- Gems/ScriptCanvas/Code/Editor/Translation/TranslationHelper.cpp
- Gems/ScriptCanvas/Code/Editor/Translation/TranslationHelper.h
- Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/EBusNodePaletteTreeItemTypes.cpp
- Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/GeneralNodePaletteTreeItemTypes.cpp
- Gems/ScriptCanvas/Code/Editor/View/Widgets/ScriptCanvasNodePaletteDockWidget.cpp
- Gems/ScriptCanvas/Code/Tools/TranslationGeneration.cpp
- Gems/ScriptCanvas/Code/Tools/TranslationGeneration.h
Previously if .names file is located in other Gems/Project, SC Editor won't be able to locate it.
With this change, it should help user to locate their .names files easily.
Extra: put translation related util functions in common TranslationHelper
Change is Editor related only, tested locally with different node file, file searching works as expected
> Support navigate to translation .names file in any safe assets folder

- Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.cpp
Fixes #10248 
Nightly debug build was flagging a warning as error in an `OpenImageIO` include, so wrapped it with the macro to disable warnings for that include.
Was unable to reproduce this issue locally, but this should solve the error.
> Fixed OIIO include warning as compile error on nightly build

- Gems/Atom/Feature/Common/Assets/Passes/ContrastAdaptiveSharpening.pass
Contrast adaptive sharpening was causing a crash with recent pass changes. This is likely because an enum changed values under the hood, and the numbers used for certain properties in the pass's json changed with it. This changes CAS to use named bind flags and shader queue mask instead of numbers to fix the problem.
> Fix to contrast adaptive sharpening pass.

- Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.cpp
- Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.h
Fixes #10381
The gradient baker component doesn't inherit from the `EditorGradientComponentBase` since it's an Editor-only component, so it was missing the logic that re-configures the dependency monitor when the configuration changes. The issue was noticed in the gradient baker node because if you created a new one (as per the steps in #10381), it's preview wouldn't be updated when there were changes in its dependencies because the dependency monitor wasn't being re-setup. The gradient baker node did function properly if you were loading a graph of an existing gradient baker component that had already been configured.
Ran unit tests and the repro steps in #10381. Here's gif of it working, where previously the gradient baker node preview would stay static when the random seed button was …
> Fixed Gradient Baker not updating its dependency monitor when the configuration changes

- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Shader/ShaderReloadDebugTracker.h
This silences a warning about a variable that is only used in
non-release builds.
> Mark variable only used in non-release builds as unused

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentSystem.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentSystemRequestBus.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystem.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeConfig.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeManager.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/MaterialPropertyUtil.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Tests/AtomToolsFrameworkTest.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
- Gems/Atom/Utils/Code/Source/TestUtils/AssetSystemStub.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentUtil.cpp
Added a new setting and support for auto saving documents in material editor, material canvas, shader management console. Autosave is currently disabled by default. It can be enabled and the interval configured in the settings dialog.
Other settings were also added to suppress warning messages that pop up when opening materials and other documents that might generate warnings or need to be resaved. These messages will still be logged. Disabling all of the dialogs and prompts in the settings dialog while enabling automatic save and automatic reload makes editing and seeing updates almost seamless without invasive changes. Only concern is thrashing the hard drive and asset processor with continuous changes.
As part of this, I also updated some utility functions and unit tests to handle …
> Atom Tools: Implement autosave support and settings for ME MC SMC

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutorInterface.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.hxx
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyColorCtrl.cpp
The InstanceUpdateExecutor was listening to PropertyEditorGUIMessages' RequestWrite and OnEditingFinished to pause/resume instance propagation during property editing. However, these messages are sent from any RPE. 
Instead, this PR moves the pausing/resuming of instance propagation to handlers within the EntityPropertyEditor.
Also checked that all AzToolsFramework property handlers send OnEditingFinished.
Fixes #9853. The FBX settings tool uses the RPE and adds its own custom controls that don't send OnEditingFinished events. That won't matter now because we're only pausing/resuming propagation on tools that use the EntityPropertyEditor (Entity Inspector). 
> Only pause/resume instance propagation for EntityPropertyEditor instead of all RPEs

- Gems/PhysX/Code/Tests/EditorHeightfieldColliderComponentTests.cpp
Temporarily disables 3 unit tests that can intermittently fail due to race conditions. These will get reenabled in a subsequent PR once I find and fix the race condition.
Ran the unit tests and verified the 3 disabled tests no longer appear.
> [Terrain] Disabling unit tests that can intermittently fail until this can be properly fixed

- Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayer.h
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
- Gems/Multiplayer/Code/Tests/CommonBenchmarkSetup.h
- Gems/Multiplayer/Code/Tests/MockInterfaces.h
- Gems/Multiplayer/Code/Tests/MultiplayerSystemTests.cpp
- Gems/ScriptCanvas/Assets/TranslationAssets/Properties/MultiplayerAgentType_Client.names
- Gems/ScriptCanvas/Assets/TranslationAssets/Properties/MultiplayerAgentType_ClientServer.names
- Gems/ScriptCanvas/Assets/TranslationAssets/Properties/MultiplayerAgentType_DedicatedServer.names
- Gems/ScriptCanvas/Assets/TranslationAssets/Properties/MultiplayerAgentType_Uninitialized.names
Currently the client disconnect signal will only be sent on the client side during disconnection but there're use cases where the server needs to handle this event as well (e.g. send player leave metrics event to the backend). With this PR, the signal will be sent on both of the client and server side. This PR also reflects MultiplayerAgentType to Behavior context so that the GetOnClientDisconnectedEvent method output can be represented properly in Script Canvas.
Unit tests for the Multiplayer Gem passed. Also verified that the signal was sent out on the client and server manually.
> Send the client disconnect signal on both of client and server

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentMainWindow.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
This change implements support for dragging supported files from the I said browser, file browser, or other file source into the application client area. This will allow opening whatever document types are supported for that application using drag and drop. For example, material source files can be dragged from explorer or the asset browser into the client area and it will open in the application. Utility functions were added to validate all of the file paths being dragged in to make sure that they are valley inn and supported file folders.
The asset browser entry functions responsible for reading and writing mime data for were updated to support multi selection. Previously, even though the function signatures and comments made it seem like multiple files were supported, only one entry …
> Atom Tools: Implement drag and drop to open documents

- Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
Fixes saving an SC file when it was opened from the raw file open menu, rather than from recent saves
Fixes https://github.com/o3de/o3de/issues/10476
Saved files from recent menu, file open menu, and when opening files via the script canvas editor component open button
> fix SC open file when not using recent file list

- Gems/Terrain/Assets/Shaders/Terrain/TerrainDetailClipmapGenerationPass.shader
- Gems/Terrain/Assets/Shaders/Terrain/TerrainMacroClipmapGenerationPass.shader
Signed-off-by: Ken Pruiksma <pruiksma@amazon.com>
Currently certain terrain shaders are failing on mac since mac doesn't support bindless textures. The solution for now is to just turn off those shaders on mac. 
https://github.com/o3de/o3de/issues/8601
Tested to make sure the shaders continue to work on pc and the shader assets build successfully.
> [Terrain] Removing clipmap generation shaders from mac until it supports bindless.

- Gems/AWSMetrics/Code/Include/MetricsAttribute.h
- Gems/AWSMetrics/Code/Source/MetricsAttribute.cpp
- Gems/AWSMetrics/Code/Source/MetricsEvent.cpp
- Gems/AWSMetrics/Code/Tests/MetricsAttributeTest.cpp
- Gems/AWSMetrics/Code/Tests/MetricsEventTest.cpp
- Gems/AWSMetrics/Code/Tests/MetricsQueueTest.cpp
Forward declare AWSCore class to remove build dependency
- Unit tests passed
- Verified with the MultiplayerSample project manually
> Fix an issue where the build for a project with AWSMetrics gem enabled may fail because of missing AWSCore headers

- Gems/Terrain/Code/Source/Components/TerrainWorldComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainWorldComponent.h
Signed-off-by: Ken Pruiksma <pruiksma@amazon.com>
Previously users could put in a min value into the world bounds that was larger than the max value iand visa versa. This change makes an error message pop up when you attempt to do that, and doesn't actually apply the value unless it's valid.
Fixes https://github.com/o3de/o3de/issues/9783
Tested setting the min/max value in the editor to make sure invalid values were not allowed to be applied.
> [Terrain] Validating that the world min bounds is less than the world max bounds.

- Gems/ScriptCanvas/Assets/TranslationAssets/Classes/MacroMaterialData.names
- Gems/ScriptCanvas/Assets/TranslationAssets/Classes/TerrainSurfaceGradientMapping.names
- Gems/Terrain/Code/Source/Components/TerrainSurfaceGradientListComponent.cpp
Signed-off-by: Ken Pruiksma <pruiksma@amazon.com>
This change adds .names files for some terrain modules. This helps distinquish the Getter & Setter for various properties. Also updated the names internally for TerrainSurfaceGradientListComponent to be more standardized.
Fixes https://github.com/o3de/o3de/issues/8082
Generated and checked the .names files from the editor.
> Adding .names for a couple terrain modules. 

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterEditor/Vector3GizmoParameterEditor.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterEditor/Vector3GizmoParameterEditor.h
I applied the changes I made to the RotationParameterEditor.h. there are several improvements with this change. 
- the gizmo fails to get removed from the scene when the parameter is deleted
- updating the value for the vector3 parameter will also update the gadget in the scene.
- add a Vector3GizmoParameter to the scene check updating the parameter value and also manipulating the gizmo
- verify behavior in the graph.
> feat: improve functionality of Vector3GizmoParameterEditor

- Code/Framework/AzCore/AzCore/Component/ComponentApplication.cpp
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.cpp
- Code/Framework/AzFramework/AzFramework/Process/ProcessCommunicatorTracePrinter.cpp
- Code/Framework/AzFramework/AzFramework/Process/ProcessCommunicatorTracePrinter.h
- Code/Framework/AzQtComponents/AzQtComponents/Components/FilteredSearchWidget.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Logging/StyledTracePrintFLogPanel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Logging/StyledTracePrintFLogPanel.h
- Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
- Code/Tools/AssetProcessor/native/resourcecompiler/rccontroller.cpp
- Code/Tools/AssetProcessor/native/ui/ProductDependencyTreeModel.h
- Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
- Code/Tools/AssetProcessor/native/utilities/BuilderManager.cpp
- Code/Tools/AssetProcessor/native/utilities/GUIApplicationManager.cpp
- Gems/LmbrCentral/Code/Source/Builders/SliceBuilder/SliceBuilderWorker.cpp
- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
These bugs were noticed on Mac but may apply to other platforms.
1. Spurious "Allocator mode changed" warning that occurs because
the allocator default mode is not the same between the Allocator
Manager and the Application Descriptor.  The remedy is to
set the Application Descriptor to contain the same default tracking
mode as the Allocator Manager, so changing it one place will
change it across the board.
2. Config Files (CFG) parsing is always optional, and is no longer
a warning, just a printf if its missing.
3. Pump the stderror/stdout IPC handles before shutting down to make
sure no errors and warnings are lost
4. IPC from out-of-process builders was being consumed and split by
newlines (with the newlines not being included in the forwarded
output).  This causes subsequent printfs to …
> Fixes several spurious warnings that occur in the Asset Processor

- cmake/Tools/Platform/Android/android_deployment.py
- cmake/Tools/Platform/Android/deploy_android.py
- Fix android asset deployment issue due to 'secure_mkdirs' error.
- Use adb found in system if found one. This allows to use other adbs other than the Android platform SDK one, for example the adb from Oculus Development Hub if that's what the system has as default.
- Do not kill adb server by default, added option to do so. Killing the adb server at the end causes to lose all the settings done previously to adb, as reverse commands or wiki connections, so by default won't reset but the user can use the option `--kill-adb-server` if they desire to kill the server at the end of deployment.
- Improve deploy script messages when assets are embedded into apk.
- Deployed assets into Android mobile and Quest 2.
- Tested running deploy script with and …
> Fix android asset deployment

- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_batch_tests.py
- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/assets_with_direct_preload_dependency/testa.auto_test_input
- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/assets_with_direct_preload_dependency/testb.auto_test_input
- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/assets_with_nested_preload_dependency/testa.auto_test_input
- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/assets_with_nested_preload_dependency/testb.auto_test_input
- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/assets_with_nested_preload_dependency/testc.auto_test_input
- Gems/TestAssetBuilder/Code/Source/Builder/TestDependencyBuilderComponent.cpp
- Gems/TestAssetBuilder/Code/Source/Builder/TestDependencyBuilderComponent.h
- Gems/TestAssetBuilder/Code/Source/TestAssetBuilderModule.cpp
- Gems/TestAssetBuilder/Code/testassetbuilder_files.cmake
Adds a test builder which takes `.auto_test_input` files containing a relative path to another file and outputs `.auto_test_asset` files with an `Asset<T>` reference.
Updated the 2 existing python tests to use the new builder and moved them out of sandbox into periodic
Ran test locally and on Jenkins
> Asset Processor - Update test_validateDirectPreloadDependency_Found in asset_processor_batch_dependency_tests.py [LYN-11477]

- Code/Framework/AzCore/AzCore/StringFunc/StringFunc.h
- Code/Framework/AzCore/AzCore/std/azstd_files.cmake
- Code/Framework/AzCore/AzCore/std/concepts/concepts.h
- Code/Framework/AzCore/AzCore/std/containers/array.h
- Code/Framework/AzCore/AzCore/std/containers/variant.h
- Code/Framework/AzCore/AzCore/std/containers/variant.inl
- Code/Framework/AzCore/AzCore/std/containers/variant_impl.h
- Code/Framework/AzCore/AzCore/std/iterator.h
- Code/Framework/AzCore/AzCore/std/iterator/common_iterator.h
- Code/Framework/AzCore/AzCore/std/ranges/common_view.h
- Code/Framework/AzCore/AzCore/std/ranges/elements_view.h
- Code/Framework/AzCore/AzCore/std/ranges/join_view.h
- Code/Framework/AzCore/AzCore/std/ranges/join_with_view.h
- Code/Framework/AzCore/AzCore/std/ranges/ranges.h
- Code/Framework/AzCore/AzCore/std/ranges/ranges_adaptor.h
- Code/Framework/AzCore/AzCore/std/ranges/ranges_algorithm.h
- Code/Framework/AzCore/AzCore/std/ranges/single_view.h
- Code/Framework/AzCore/AzCore/std/ranges/split_view.h
- Code/Framework/AzCore/AzCore/std/ranges/subrange.h
- Code/Framework/AzCore/AzCore/std/ranges/transform_view.h
- Code/Framework/AzCore/Tests/AZStd/Iterators.cpp
- Code/Framework/AzCore/Tests/AZStd/RangesAlgorithmTests.cpp
- Code/Framework/AzCore/Tests/AZStd/RangesViewTests.cpp
Furthermore added implementation of range algorithms of for_each and count.
Updated StringFunc::Join to use join_with_view and transform_view for join a string.
Fixed ITER_CONCEPT(I) to correctly check the supplied iterator type I for the `iterator_concept` type alias when `AZStd::iterator_traits` primary template(non-specialized) template is being used.
Fixed AZStd::visit overload with the return type template parameter to force the visitor to have the same return type for all variant alternatives.
> Added implementation of transform_view and join_with_view

- Code/Tools/ProjectManager/Source/DownloadController.cpp
- Code/Tools/ProjectManager/Source/DownloadController.h
Fixes a bug on queued download for remote gems.
Issue is that `m_gemName` is not set when `StartGemDownload` is emitted. Reason is the slot is set to `StartDownload` which doesn't update `m_gemName`. Connecting the signal to an updated `SetGemToDownload` should fix the issue.
This is also dependent to PR [#10487](https://github.com/o3de/o3de/pull/10487). Without it some gems gets removed to the list view.
Check the repro steps in Issue [#9685](https://github.com/o3de/o3de/issues/9685)
> Fixes gem queue download issue in Gem Catalog ( #9685)

- Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/Utils/Utils_UnixLike.cpp
The cerror header is needed for errno and ENOENT symbols.
> Mac and iOS Utils_UnixLike.cpp build fix

- Code/Tools/AssetProcessor/native/utilities/AssetServerHandler.cpp
Fixes starting up AP: Server address () is invalid! Reverting back to ()
Started AP with no setreg for the asset cache server and no error message came up
> Fixes a faulty error message about an invalid server address.

- scripts/build/Jenkins/Jenkinsfile
Fixes a condition in which the nightly build uses the boolean parameter as environment string, which always evaluates to true. Using the params key properly returns the boolean value 
Tested in a sandbox Jenkins instance using a test nightly build pipeline
> Change fail_fast variable to params key

- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.h
Due to a timing issue with prefab propagation, the opportunistic connections created when creating nodes for proposal were being deleted right after they were created, which gave the appearance of the feature not working at all. Here is a gif of the feature working now with this change (before this change, the connection between the output `Bounds` slot of the shape and the input `Preview Bounds` on the gradient would not be created):
I tested various opportunistic connections such as chaining multiple gradients/gradient modifiers. Also tested modifying component property values manually in the Entity Inspector and verified they get auto-updated in the graph properly.
> Fixed opportunistic connections not working in Landscape Canvas

- Code/Framework/AzToolsFramework/AzToolsFramework/PropertyTreeEditor/PropertyTreeEditor.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/Components/TerrainSurfaceMaterialsListComponent.cpp
Signed-off-by: Ken Pruiksma <pruiksma@amazon.com>
Previously if an ElementData had no name, the PropertyTreeEditor could explode when building a node map. Since it's possible for components to provide their own ElementData using SetDynamicEditDataProvider, there's no guarantee that the ElementData will actually have a name. This change makes it so the node will be skipped if it has no name, and a warning will be generated that helps guide people to the problem.
This change also adds behavior context definitions for a couple terrain classes that were involved in the original bug. While they didn't end up being required to fix the bug, they're still helpful to have. 
Fixes https://github.com/o3de/o3de/issues/7701
Tested using script provided with bug. The affected component now has a name, …
> [Terrain] Fixing property tree editor to not explode when a editMetaData has no name

- Code/Framework/AzCore/AzCore/Console/ConsoleDataWrapper.inl
- Code/Framework/AzCore/AzCore/Console/ConsoleFunctor.inl
- Code/Framework/AzCore/AzCore/Console/ConsoleTypeHelpers.h
- Code/Framework/AzCore/AzCore/Console/ConsoleTypeHelpers.inl
- Code/Framework/AzCore/AzCore/Debug/Trace.cpp
- Code/Framework/AzCore/AzCore/Preprocessor/Enum.h
- Code/Framework/AzCore/AzCore/RTTI/TypeInfo.h
- Code/Framework/AzCore/AzCore/RTTI/TypeSafeIntegral.h
- Code/Framework/AzCore/AzCore/std/containers/fixed_vector.h
- Code/Framework/AzCore/Tests/Console/ConsoleTests.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/CvarAdapter.cpp
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Added a boolean to detect if a type specializes AzEnumTraits through the `HasAzEnumTraits_v` constexpr variable
The AzTypeInfo::Name method will output the name of the EnumType if that type specializes AzEnumTraits.
This occurs even if the type doesn't specialize AzTypeInfo
The AZ::Console now supports setting CVars of Enum type automatically without the need to specialized the ConsoleTypeHelpers `ValueToString` and `StringSetToValue` functions.
Additionally if the Enum type specializes the AzEnumTraits(this can be done by using the AZ_ENUM* macros), then AZ::Console also supports setting the CVar values using name of the enum option.
Fixed issue in fixed_vector extension constructor causing an ambiguous overload when attempting supply an AZStd::fixed_string<512>(CVarString) to an …
> Enum support improvements

- Gems/Terrain/Assets/Shaders/Terrain/ClipmapComputeHelpers.azsli
- Gems/Terrain/Assets/Shaders/Terrain/TerrainDetailClipmapGenerationPass.azsl
- Gems/Terrain/Assets/Shaders/Terrain/TerrainMacroClipmapGenerationPass.azsl
- Gems/Terrain/Assets/Shaders/Terrain/TerrainMacroHelpers.azsli
- Gems/Terrain/Assets/Shaders/Terrain/TerrainPBR_ForwardPass.azsl
Encoded the "has normal" info into the macro color alpha channel, so that in the forward pass it knows when to use the vertex normal instead.
> [Terrain] Fix the clipmap rendering when macro normal map is not set

- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/GraphCanvasTreeModel.cpp
More investigation will come later, revert to prevent unexpected behavior from OnAssetReady callback.
Original issue is caused by model changed on the fly not included for sorting. Need to figure out a different way for node palette top category sorting which should be light weighted.
> Revert qt layout change signal

- python/requirements.txt
Fixes an issue with the atomicwrites python lib, as the 1.4.0 version was accidentally wiped from Pypi. This updates requirements.txt for version 1.4.1
Resolves https://github.com/o3de/o3de/issues/10590
> Update requirements.txt for atomicwrites

- Gems/MotionMatching/Code/Source/FeatureAngularVelocity.cpp
- Gems/MotionMatching/Code/Source/FeatureAngularVelocity.h
- Gems/MotionMatching/Code/Source/MotionMatchingSystemComponent.cpp
- Gems/MotionMatching/Code/Source/PoseDataJointVelocities.cpp
- Gems/MotionMatching/Code/motionmatching_files.cmake
Angular joint velocities visualized:
https://user-images.githubusercontent.com/43751992/177787079-34431e48-a040-4fcb-81d5-4a418868ebc7.mp4
Comparison of a motion matching node using angular joint velocities (plus an extra positional feature on the spine) vs. the default configuration:
https://user-images.githubusercontent.com/43751992/177787123-d13b7c26-b67c-4f21-abd5-2d48975f47a1.mp4
We can see that the left character (having the extra features) deviates from the path more while keeping especially the upper body more smooth in the body's movement phases. Basically we trade animation smoothness with path/control accuracy here.
> Motion Matching: Added angular joint velocity feature

- Gems/LyShine/Assets/Passes/LyShinePassRequest.azasset
The Low End Pipeline doesn't have a DebugOverlayPass, but DebugOverlayPass just uses an InputOutput, so we can make the LyShine pass point to the output of the previous pass which is the AuxGeomPass. This makes the LyShine pass injection work with both the Main Pipeline and the Low End Pipeline.
> Fixing LyShine Pass to work with low end pipeline

- Code/Framework/AzFramework/AzFramework/Asset/AssetCatalog.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystem.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRenderer.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRenderer.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRendererCaptureState.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRendererCaptureState.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRendererIdleState.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRendererIdleState.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRendererLoadState.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRendererLoadState.h
- Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
- Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/EditorMaterialSystemComponentNotificationBus.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnailRenderer.cpp
The material editor and related tools now support autosaving modified files. Those files will be processed by the AP and should automatically reload in the main editor. Because a lot of the processing was done on TickBus, assets would not reload and the changes would not be reflected until the main editor regained focus. This PR moves a handful of systems to use SystemTickBus instead, allowing those assets to be processed and reloaded without requiring that the main editor have focus. This also fixes issues with Stacking material preview capture requests, preview is not updating when assets change, and previous updating out of order.
These changes should benefit any other external tools or scripts that modify assets that a user or developer would want to see immediately in the main editor …
> Update asset catalog, preview renderer, and editor material components to support hot reloading on system tick

- Gems/Atom/Feature/Common/Code/3rdParty/ACES/ACES/Aces.h
- Gems/Atom/Feature/Common/Code/Source/DisplayMapper/DisplayMapperConfigurationDescriptor.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportSettings.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/DisplayMapper/EditorDisplayMapperComponent.cpp
This fix allows to use integer values when using
GetComponentProperty and SetComponentProperty in python
for `Display Mapper` component
- Example GetComponentProperty:
propertyPath = "Controller|Configuration|Type"
outcome = azlmbr.editor.EditorComponentAPIBus(busType,
'GetComponentProperty', componentIdPair, propertyPath)
result = outcome.GetValue()
print(f"value of {propertyPath} is {result}, type = {type(result)}")
In the code above result is of type integer and the value is 0.
- Example SetComponentProperty:
outcome = azlmbr.editor.EditorComponentAPIBus(busType,
'SetComponentProperty', componentIdPair, propertyPath, 1)
print(f"outcome success = {outcome.IsSuccess()}")
Before `SetComponentProperty` required a python class that was not serialized so the
only way around was to use …
> Display Mapper component unable to set properties from python

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportSettings.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportSettings.cpp
The workaround was to add explicit Get & Set methods to
EntityPreviewViewportSettings, and calling those methods
in the ->Property() function call in BehaviorContext definition.
Fixes the following lua script context error:
-----------------------------------------
System: Trace::Assert
D:/github/o3de/Code/Framework/AzCore/AzCore/Script/ScriptContext.cpp(3461):
(52824) '__cdecl AZ::LuaScriptCaller::LuaScriptCaller(class
AZ::BehaviorContext *,class AZ::BehaviorMethod *)'
System: The argument type: const Render::DisplayMapperOperationType&
for method:
EntityPreviewViewportSettings::displayMapperOperationType::Setter is
not serialized and/or reflected for scripting.
Make sure const Render::DisplayMapperOperationType& is …
> Fixes the following lua script context error:

- Code/Framework/AzCore/AzCore/Math/VectorConversions.h
mark code as deprecated. there is an existing logic that does the same conversion. 
ref: https://github.com/o3de/o3de/issues/10596
> chore: add depreciation notice for VectorConversions

- Code/Framework/AzCore/AzCore/Preprocessor/EnumReflectUtils.h
- Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.h
- Code/Framework/AzCore/Tests/EnumTests.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportSettings.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportSettings.cpp
Fix the issue the underlying issue with reflecting a method that contains a parameter that accepts cv-qualified, ref-qualified or pointer decorated enum type to the BehaviorContext.
The issue is that the BehaviorContext internal `SetParameters` function was only providing the underlying type for an unqualified enum type and not an enum type decoarated with cvref qualifiers and pointers.
For example given an enum type of `enum class TestEnum`, the underlying type was only provided if a method took a `TestEnum` by value
|EnumType|Type after RemoveEnumT|
|---|---|
|`TestEnum`|`int`|
|`const TestEnum`|`const TestEnum`|
|`TestEnum&`|`TestEnum&`|
|`TestEnum*`|`TestEnum*`|
|`const TestEnum&`|`const TestEnum&`|
The SetParametersStripped function has now been updated to provide the underlying type …
> Behavior context enum decay update

- Gems/Terrain/Code/Mocks/Terrain/MockTerrain.h
- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.cpp
- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.h
- Gems/Terrain/Code/Source/TerrainSystem/TerrainSystemBus.h
Currently, changes to terrain heights and surfaces cause those components to call TerrainSystem::RefreshArea, which refreshes the entire terrain spawner area. This PR creates a new API called TerrainSystem::RefreshRegion that enables just a specific region of the terrain to be marked dirty, instead of the entire spawner area. The code for the new API is just a subset of what was already in RefreshArea.
RefreshArea() was modified to call the new RefreshRegion() API, so it's being implicitly tested by all of the terrain code already. It's also been separately tested and used separately with another upcoming PR, in which gradients can broadcast a dirty region on changes, instead of just broadcasting that the entire gradient changed.
> [Terrain] Split out separate API for refreshing terrain region

- scripts/build/Jenkins/Jenkinsfile
- scripts/build/Platform/Linux/build_config.json
- scripts/build/Platform/Windows/build_config.json
- scripts/build/bootstrap/incremental_build_util.py
This will move the validation build to its own stage in the pipeline (`Validate`), ahead of the `Build` stage. This will allow us to fast fail the build if there are validation issues, rather than spinning up all nodes for an AR that would always fail review.
In addition, we can use this stage for the opposite use case: We can bypass the build stage if the validation stage determines the PR contains non-code files (like an update to a Markdown file). This will likely be defined as specific paths, rather than a wildcard.
There is a small penalty for running this stage, however, as the validation task adds approx 5 mins to spin up, validate, and tear down the stage. I've also included some speedups to hopefully offset this:
- Add a fix for Linux incremental disk unmounting (essentially a …
> Create a separate Validation stage

- cmake/Platform/Android/Toolchain_android.cmake
When LY_NDK_DIR was set as an environment variable, it wasn't being properly detected by the Android toolchain file
Configured android with `LY_NDK_DIR` set as an environment variable that pointed to the NDK.
> Android LY_NDK_DIR env detection fix

- Gems/Atom/RHI/Code/Include/Atom/RHI/CommandList.h
Fix the following compilation issue on Mac and iOS.
````
/Users/lybuilder/workspace/o3de/Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.cpp:207:32: error: no viable conversion from 'const RHI::DispatchRaysItem' to 'const AZ::RHI::SubmitItem'
ValidateSubmitItem(dispatchRaysItem);
````
> Adding missing include DispatchRaysItem.h in CommandList header, which causes Mac/iOS to fail to compile

- Gems/EMotionFX/Code/EMotionFX/Source/Importer/Importer.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/Importer/Importer.h
this array `m_layerIDsToIgnore` is modified but not used in any meaningful way.
> chore(EMotionFX): remove m_layerIDsToIgnore from Importer

- Code/Editor/Util/FileUtil.cpp
clang wouldn't let me build because the cancelButton is an unused variable. There shouldn't be any logical changes to the source code.
> chore: remove unused variable and c style cast for FileUtil

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp
This fixes an issue when "Esc" is pressed to deselect entities while a property control is still in focus in an editing state. The entity's data changes on "Esc", but an undo command is not registered because the selected entities have already been cleared when the BeforePropertyModified event is sent. In BeforePropertyModified, only selected entities are automatically marked as dirty.
To see this issue in the Editor, instantiate a prefab and enter focus mode. Edit a text field in the Entity Inspector and press Esc. Notice that the prefab is not marked as having unsaved changes in the Entity Outliner even though it does have unsaved changes.
This PR clears the focus of the currently focused child widget of the Entity Property Editor in the BeforeEntitySelectionChanged handler to trigger …
> Complete current editing before changing entity selection

- Gems/LmbrCentral/Code/Source/Scripting/EditorTagComponent.cpp
- Gems/LmbrCentral/Code/Source/Scripting/EditorTagComponent.h
The editor version of the tag component was connecting to the TagGlobalRequestBus which returns the entityIds of all the entities with a specified tag. Since the editor component's tag is the same as the runtime component's tag, a runtime script can get access to an editor component in game mode and change it.
Level entities are not actually affected by this issue because the level entities are deactivated during game mode, but UI canvas entities are affected because each UI canvas has its own entity context and doesn't need to deactivate during game mode.
I've looked through the codebase and didn't find any editor code that was actually making requests on the TagGlobalRequestBus, so this change shouldn't break anything. PostFxLayerComponentController uses the TagComponentRequestBus, …
> Don't connect to TagGlobalRequestBus from editor tag component

- AutomatedTesting/Gem/PythonTests/scripting/ScriptEvents_ReturnSetType_Successfully.py
- AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
- AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_constants.py
- AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_tools.py
- AutomatedTesting/ScriptCanvas/T92569006_ScriptCanvas.scriptcanvas
- Fixed deprecated test code that caused the test script to fail
- replaced many ambiguous variables and function arguments with constants from the utils file
- moved a local function from the test script into the script tools file since it can potentially be used in other tests
- fixed the script canvas file associated with this test. The script event send/receive nodes had an old format or something and did not behave when called by the script canvas file
> Fix for test script ScriptEvents_ReturnSetType_Successfully

- Code/Framework/AzCore/AzCore/Task/TaskExecutor.cpp
- Code/Framework/AzCore/AzCore/Task/TaskExecutor.h
- Code/Framework/AzCore/AzCore/Task/TaskGraph.cpp
- Code/Framework/AzCore/AzCore/Task/TaskGraph.h
- Code/Framework/AzCore/AzCore/Task/TaskGraph.inl
- Code/Framework/AzCore/Tests/TaskTests.cpp
- Gems/Atom/Feature/Common/Code/Source/FrameCaptureSystemComponent.cpp
- Gems/Atom/RHI/Code/Source/RHI/FrameScheduler.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/View.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/DualQuatSkinDeformer.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/DualQuatSkinDeformer.h
- Gems/MotionMatching/Code/Source/MotionMatchingData.cpp
- Gems/RecastNavigation/Code/Source/Misc/RecastNavigationMeshComponentController.cpp
- Gems/RecastNavigation/Code/Source/Misc/RecastNavigationMeshComponentController.h
- Gems/RecastNavigation/Code/Source/Misc/RecastNavigationPhysXProviderComponentController.cpp
- Gems/RecastNavigation/Code/Source/Misc/RecastNavigationPhysXProviderComponentController.h
All TaskGraph events and graphs now have a required cstr label as a
constructor argument to aid debugging.
> Add cstr labels to all task graphs and events

- cmake/3rdParty/Platform/Android/VkValidation_android.cmake
Vulkan validation libs are optional and shouldn't stop from building.
Changed the script so it warns the user that it couldn't locate the libs and that validation will be disabled.
After the fix I was able to build with android without having the validation libs present.
> Making non fatal if vulkan validation libs are not found.

- AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/pyside_utils.py
This change allows us to be more precise about selecting UI widgets in interactive tutorials. 0 is the default index, which is the current behavior.
Signed-off-by: Mike Cronin <58789750+micronAMZN@users.noreply.github.com>
Adds an option to specify the index of the object returned by find_child_by_hierarchy(). Currently it returns the object at index 0 always. In this change, 0 is the default if no index is specified.
Tested locally in up to date development branch. Manually tested with various scripts, selecting various UI objects by specifying indices or allowing the default 0 index.
> Adding an optional index argument to find_child_by_hierarchy()

- Gems/Atom/Feature/Common/Code/Source/AuxGeom/FixedShapeProcessor.cpp
The winding for the debug sphere is reversed so the surfaces would render inward. this just flips the windings so they face outward.
run whitebox gem and set
```
cl_whiteBoxVertexManipulatorSize 5
```
verify both the top and bottom poles of the sphere and also the outer surfaces. 
ref: https://github.com/o3de/o3de/issues/6773
additional discussion here: https://github.com/o3de/o3de/pull/9925
> bugfix(graphics): fix winding for debug sphere to render faces outward (GHI-6773)

- Code/Editor/CryEdit.cpp
- Code/Editor/Settings.cpp
- Code/Editor/Settings.h
This change addresses SystemTick running uncapped when the Editor is in the background.
This change adds the cvar `ed_backgroundSystemTickFPS` with a default of 30 FPS. This cvar is used when the Editor is both in the background and is set to not fully update while in the background. When in this state it will cap Editor updates to a maximum of `ed_backgroundSystemTickFPS` FPS by sleeping any free time.
The logic used is very similar to logic used to limit FPS when VSync and Max FPS are specified in [`System.cpp`](https://github.com/o3de/o3de/blob/97d791bc9e46f3e18c8c12e981f12a6da225547d/Code/Legacy/CrySystem/System.cpp#L639).
Change was tested by comparing CPU/GPU utilization of Editor while fully active and while backgrounded. With this …
> Limit SystemTick updates when Editor is backgrounded

- AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Sandbox.py
Fixing omitted EditorSharedTest import so shared tests can run successfully in Sandbox. Fixes the error below:
```
[2022-07-20T05:52:10.974Z] =================================== ERRORS ====================================
[2022-07-20T05:52:10.974Z] _ ERROR collecting AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Sandbox.py _
[2022-07-20T05:52:10.974Z] D:\workspace\o3de\AutomatedTesting\Gem\PythonTests\Prefab\TestSuite_Sandbox.py:16: in <module>
[2022-07-20T05:52:10.974Z]     class TestAutomationAutoTestMode(EditorTestSuite):
[2022-07-20T05:52:10.974Z] D:\workspace\o3de\AutomatedTesting\Gem\PythonTests\Prefab\TestSuite_Sandbox.py:21: in TestAutomationAutoTestMode
[2022-07-20T05:52:10.974Z]     class …
```
> Fixing omitted EditorSharedTest import

- Gems/RecastNavigation/Code/Source/Misc/RecastNavigationPhysXProviderComponentController.cpp
This gives heightfields the ability to just return the subset of the heightfield that overlaps the Recast tile instead of the entire heightfield.
Tried the fix out on a level with a large terrain and tiny Recast area, and verified that the debug drawing of the Recast mesh looked correct, and used breakpoints to verify the heightfield was only returning ~15000 points instead of 51 million.
> Change Recast to use the optional AABB with GetGeometry.

- Code/Framework/AzCore/AzCore/std/algorithm.h
- Gems/EMotionFX/Code/EMotionFX/Source/TransformData.h
- Gems/MotionMatching/Code/Source/KdTree.cpp
- Gems/MotionMatching/Code/Source/KdTree.h
- Gems/MotionMatching/Code/Source/MotionMatchingEditorSystemComponent.cpp
The KD-tree was storing feature values previously which was duplicated data from the feature matrix. With this change, we are reading the data directly from the feature matrix.
Additionally we're calculating the median now instead of just the average value to separate the data between the nodes.
> Motion Matching: Optimize memory usage in KD-tree + use median instead of average

- Code/Framework/AzFramework/AzFramework/Components/TransformComponent.cpp
- Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/TransformBus.names
- Gems/ScriptCanvas/Code/Editor/Translation/TranslationHelper.cpp
As requested by https://github.com/o3de/o3de/issues/10647, add SetWorldRotation Node
PS. fix the translation file look up bug, which previously only look for file name end with (it leads to return back wrong file having same suffix name)
Using script canvas to set world rotation and local rotation respectively
https://user-images.githubusercontent.com/5900509/180097145-fa3dcbbe-d865-428c-b374-f4f045ae360c.mp4
SetWorldRotation node
> Add set world rotation node to scriptcanvas

- Code/Framework/AzCore/Platform/Common/VisualStudio/AzCore/Natvis/azcore.natvis
This fixes the forward_list iterator types as well to be casted to the correct forward_list::iterator type.
Previously it was being cast to the list::iterator type which is not compatible.
Added a [next] entry in the forward_list iterator entry that allows traversing the iteratorxs entries in the debugger with the list node values shown
Also added a [next] and [prev] entry in list iterator netry that allows traversing the iterator entries
Examined a forward_list_iterator and forward_list_const_iterator in the MSVC debugger to validate the entries were correct.
> Fixed native visualizers for the AZStd forward_list and fixed_list classes

- Code/Tools/SerializeContextTools/Application.cpp
- Code/Tools/SerializeContextTools/Dumper.cpp
- Code/Tools/SerializeContextTools/Utilities.cpp
The `dumpsc` command for the SerializeContextTools has been updated to support loading a project's Editor gem modules if the --project-path parameter is supplied.
Changed the --output argument for the `dumpsc` command to output relative to the current working directory, instead of relative to the project path.
When the project path wasn't specified this would output files within the executable directory instead of the current working directory.
Added an "IsComponent" field to the dumped SerializeContext content.
Ran the `dumpsc` command with the project path pointing to the AutomatedTesting project.
Here are the results of that `dumpsc` command …
> SerializeContextTools `dumpsc` support for loading project gems

- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
Adding editorsv_print_server_logs. Useful flag for seeing server prin…ts, warnings, and errors without having to open up the server console or server.log file. 
Fixes part 1 #10774. Doesn't actually remove server spam, but at least you can turn off seeing it in the editor.
Run the editor with multiplayer enabled with editorsv_print_server_logs enabled and disabled and making sure the logs do and dont appear respectively.
> Editorsv_print_server_logs to Turn On/Off Seeing Server Logs in the Editor Console

- Gems/Atom/RPI/Code/CMakeLists.txt
- Gems/Atom/RPI/Code/atom_rpi_test_utils_files.cmake
- Gems/Atom/RPI/Code/atom_rpi_tests_files.cmake
- Gems/Terrain/Code/CMakeLists.txt
- Gems/Terrain/Code/Tests/TerrainTestFixtures.cpp
- Gems/Terrain/Code/Tests/TerrainTestFixtures.h
- Gems/Terrain/Code/Tests/TerrainWorldComponentTests.cpp
- Gems/Terrain/Code/Tests/TerrainWorldDebuggerComponentTests.cpp
- Gems/Terrain/Code/Tests/TerrainWorldRendererComponentTests.cpp
- Gems/Terrain/Code/terrain_tests_files.cmake
This adds unit tests that successfully activate/deactivate the Terrain World component, Terrain World Debugger component, and the Terrain World Renderer component. Even though the tests are simple, they at least raise the minimum bar of functionality for the components a few steps beyond "it compiles". For example, it will catch any memory leaks or unexpected system dependencies.
To make it possible to activate the Terrain World Renderer, I also needed to extract some of the Atom RPI test harness code into a separate build target so that I could use it from the Terrain tests as well, without needing to rewrite and maintain two versions of the test harness.
Ran the unit tests for Atom and Terrain and verified they all ran and passed.
> [Terrain] Simple unit tests for terrain level components

- .github/ISSUE_TEMPLATE/bug_template.md
Fixes typo in big sur name, updates to latest Mac OS codename in bug template.
N/A - Change is for a process file, confirmed text change through visual inspection.
> Fix bug template to remove mac os typo

- Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
- Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.h
Fixes #10792 - a crash when heightfield baking is requested for a component that has no heightfield. There was no TerrainSystem in the level, hence no physics heightfield was created.
Made the checkbox to be disabled in the UI in this case and added a safety check in the baking function.
Various manual testing
> Fixed crash when heightfield baking is requested for a non-existing heightfield

- Code/Tools/AssetProcessor/native/ui/CacheServerData.cpp
- Code/Tools/AssetProcessor/native/ui/CacheServerData.h
- Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
- Code/Tools/AssetProcessor/native/ui/MainWindow.ui
- Code/Tools/AssetProcessor/native/ui/style/AssetProcessor.qrc
- Code/Tools/AssetProcessor/native/ui/style/AssetProcessor.qss
- Code/Tools/AssetProcessor/native/ui/style/Browse.png
- Code/Tools/AssetProcessor/native/ui/style/Browse_on.png
This updates the user interface for the AP's Shared Cache tool page.
* Adds a support button
* Status field is easier to read
* The Save Changes button is now default blue
Manually tested to make sure the UX works as expected.
> {lny13480} Updated Shared Cached interface based on feedback from UX

- Code/Framework/AzCore/AzCore/std/containers/deque.h
- Code/Framework/AzCore/AzCore/std/containers/forward_list.h
- Code/Framework/AzCore/AzCore/std/containers/list.h
- Code/Framework/AzCore/AzCore/std/containers/vector.h
- Code/Framework/AzCore/AzCore/std/function/function_template.h
- Code/Framework/AzCore/AzCore/std/smart_ptr/shared_ptr.h
- Code/Framework/AzCore/AzCore/std/string/regex.h
- Code/Framework/AzCore/AzCore/std/string/string.h
- Code/Framework/AzCore/AzCore/std/string/string_view.h
- Code/Framework/AzCore/AzCore/std/utils.h
- Code/Framework/AzCore/Tests/AZStd/DequeAndSimilar.cpp
- Code/Framework/AzCore/Tests/AZStd/FunctionalBasic.cpp
- Code/Framework/AzCore/Tests/AZStd/Lists.cpp
- Code/Framework/AzCore/Tests/AZStd/String.cpp
- Code/Framework/AzCore/Tests/AZStd/VectorAndArray.cpp
Deduction guides were added for deque, forward_list, list, vector, function_template, shared_ptr, basic_regex, string, pair.
Removed `using namespace AZStd` calls at namespace scope in the deque, lists and vector UnitTest files.
> Adding C++17 deduction guides for AZStd container types

- Gems/Multiplayer/Code/Include/Multiplayer/Components/NetBindComponent.h
- Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Per https://github.com/o3de/o3de/issues/10006, this change reflects MarkForRemoval from NetBindComponent and ClearAllEntities from MultiplayerSystemComponent.
This was tested by using the repro steps in https://github.com/o3de/o3de/issues/9999. Fix was confirmed by replacing the DestroyEntity call with MarkForRemoval and confirming efficacy.
> Reflect MarkForRemoval and ClearAllEntities from appropriate net components

- Gems/PhysX/Code/Editor/SettingsWidget.cpp
Fixes #10712 
Added missing punctuation mark from label in PhysX Configuration tool.
Launched PhysX Configuration tool and verified the punctuation mark is now there, which makes it consistent with the other tabs inside the PhysX Configuration tool.
> Fixed missing punctuation in PhysX Configuration label

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DPEDebugViewer/DPEDebugWindow.ui
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
- fix horizontal scrollbar appearing for DPE
- partial fix for DPE debugview not showing expanders
- fix debug view not always reading CVAR value correctly
- reduce DPE debug view's size
> Minor DPE Debug View fixes

- Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/ScreenSpace/DeferredFogComponentConfig.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/ScreenSpace/EditorDeferredFogComponent.cpp
Signed-off-by: Artur Zięba <86952082+LB-ArturZieba@users.noreply.github.com>
Changed two of the Deferred Fog Component's properties parameters:
* Changed the "Enable Deferred Fog" property from "false" by default, to "true". This way when the Deferred Fog, and the PostFX Layer components are added, the fog is displayed right away, which could help avoid confusion for new users.
* Changed the "Octaves Blend Factor" property slider clamped values from [0.2 - 0.8] to [0.0 - 1.0]. Since the allowed values are [0.0 - 1.0], the slider could be used for all available values without impacting the value precision noticeably.
Verified manually on a separate branch:
https://user-images.githubusercontent.com/86952082/177996798-0a756871-736f-4b92-8897-917cf6ae0723.mp4
Compared to the current build …
> Changed two properties parameters in Deferred Fog Component

- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponentsLevel_DisplayMapperAdded.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DisplayMapperAdded.py
updates display mapper null-render AR tests to set/get previously unreachable properties.
while I can now set/get the preset, I am still calling the ebus to load the preset since the button isn't otherwise exposed to python automation.
https://github.com/o3de/o3de/issues/8348
this was run in editor for both test scripts with no failures
there was a warning in the output, but this was present before these changes
`[Warning] (AzToolsFramework) - GenericValue could not be found in the combo box`
```
Start 164: AutomatedTesting::Atom_Main_Null_Render_02.main::TEST_RUN
1/4 Test #164: AutomatedTesting::Atom_Main_Null_Render_02.main::TEST_RUN ...   Passed   53.53 sec
Start 165: AutomatedTesting::Atom_Main_Null_Render_03.main::TEST_RUN
2/4 Test …
```
> displaymapper null-render test update

- Gems/Terrain/Code/Source/TerrainRenderer/TerrainMacroMaterialManager.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainMacroMaterialManager.h
This PR makes macro materials fall back to the entity ID for order if their priorities are the same. This isn't meant to offer true stability across runs, but keeps the macro material from looking broken in a session. Currently it's possible for different terrain tiles to have different macro material orders for the same materials if the priorities are the same. With this change, all the tiles will have the same order.
Tested a level with many macro materials of different / same priorities.
> [Terrain] Macro material order determinism

- Gems/RecastNavigation/Code/Source/Misc/RecastNavigationMeshComponentController.cpp
- Gems/RecastNavigation/Code/Tests/NavigationMeshTest.cpp
Fixing a bug where a navigation mesh would not update a file if all the physical colliders were removed within that tile.
With these changes, that tile will now be updated to have no navigation data, instead of keeping the stale data before colliders were removed.
Added a unit test for this scenario as well: `NavigationTest.NavUpdateThenDeleteCollidersThenUpdateAgainThenFindPathShouldFail`
Unit tests.
```
[==========] Running 24 tests from 1 test case.
[----------] 24 tests from NavigationTest
[ RUN      ] NavigationTest.GetNativeNavMesh
[       OK ] NavigationTest.GetNativeNavMesh (26 ms)
[ RUN      ] NavigationTest.TestAgainstEmptyPhysicalBody
[       OK ] NavigationTest.TestAgainstEmptyPhysicalBody (14 ms)
[ RUN      ] …
```
> Bug fix for updating nav mesh tiles when all physical colliders were removed within that tile's volume

- Code/Framework/AzCore/AzCore/Math/VertexContainerInterface.h
- Code/Framework/AzCore/Tests/Math/Matrix3x4Tests.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorPolygonPrismShapeComponentMode.cpp
replace usage of deprecated VectorConversions
> chore: AZCore replace usage of VectorConversions

- Gems/ScriptCanvas/Code/Editor/Framework/Interpreter.cpp
Fixes crash from using the SC interpreter to start and stop a non-pure SC graph, for example one connected to the tick bus. Now, the interpreter will properly call Initialize() on the hosted m_executor after the stop button has been pressed and before the start button is pressed.
Found bug and proved fix with the SC interpreter widget.
> fix restart script use of non-pure graphs in interpreter

- Code/Framework/AzCore/AzCore/Component/ComponentApplication.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasAutoGenRegistry.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasAutoGenRegistry.h
- Gems/ScriptCanvas/Code/Source/ScriptCanvasCommonGem.cpp
- Gems/ScriptCanvas/Code/Source/SystemComponent.cpp
- Gems/ScriptCanvasPhysics/Code/Source/ScriptCanvasPhysicsSystemComponent.cpp
- Gems/ScriptCanvasTesting/Code/Source/Framework/ScriptCanvasTestFixture.h
- Gems/ScriptCanvasTesting/Code/Source/ScriptCanvasTestingEditorModule.cpp
- Gems/ScriptCanvasTesting/Code/Source/ScriptCanvasTestingSystemComponent.cpp
- Gems/StartingPointInput/Code/Source/StartingPointInputGem.cpp
- cmake/AzAutoGen.py
Because of this change https://github.com/o3de/o3de/pull/8790, we can utilize Environment variable to store static object across modules, which hugely simply ScriptCanvas autogen use case.
Extra:
1. In order to support this change, have to change module load workflow by breaking CreateClass and RegisterComponentDescriptors into separate loop. So all static objects from Gems can be created in CreateClass step, then when invoke RegisterComponentDescriptors step, all required static objects can be found. (module loading process is idempotent, it should be safe to break into separate loop) 
2. During game jam, find out user can give random informal project name, update current sanitized target name logic by taking alphabetic letter and number only
All ScriptCanvas nodes can be registered …
> Simplify autogen usage by using environment variable

- Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja
Fix Multiplayer auto-component archetype property so that they use their Init value. If the init value is empty, then don't init and leave it empty
Fixes auto-component archetype property so that jinja uses the Init value. Before this change the value of properties were undefined, for example, an int could be initialized to some random number, often leading to confusing outcomes which needed debugging.
Resolves #4099 
1) Made sure existing Multiplayer Sample are compiled
2) Added a Multiplayer component in editor and see that the archetype proper was now initialized
> Fix Multiplayer Component Archetype Property Init

- Gems/Atom/Feature/Common/Code/Source/MorphTargets/MorphTargetComputePass.cpp
- Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshComputePass.cpp
- Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshFeatureProcessor.h
Skinned mesh FP and passes would delete the dispatch list after it submits it in the command list. This would break with the recent estimate item count changes since the skinning dispatch submission now using the provided range. If there are two passes, that range will be the same for both passes, but the first pass will delete the dispatch list after submitting it, so the second pass will try to access an empty list using the provided ranges and crash.
Changed the behavior so that only one skinning pass will get the full item count and subsequent skinning passes will receive a count of zero to avoid duplicate work (this duplicate work would also break motion vectors since it would update the previous position buffer twice in the same frame, so motion vectors would be zero).
In the future …
> Fixing crash with skinned meshes when baking reflection probes

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp
When pasting components onto selected entities, it was assumed that all entities were of a certain type. This change checks entity type and uses the correct filter to determine whether the components are compatible with the selected entities.
Fixes #4236.
> Fix for pasting incompatible components

- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/LightingUtils.azsli
- Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
- Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/Math.azsli
OOBB reflection probes were transforming point to object space but not the reflection vector.
> Fixed parallax correction for OOBB reflection probes

- Code/Framework/AzCore/Platform/Common/VisualStudio/AzCore/Natvis/azcore.natvis
Added a simple view DisplayString for `AZStd::variant to remove the index
from being displayed.
The DomPathEntry uses that simple view for AZStd::variant
Removed the `AZStd::optional` and `AZStd::nullopt_t` entries as those are no
longer used. The MSVC toolset std::optional and std::nullopt_t entries
are used since we alias those classes into the AZStd namespace from std.
Adds natvis entries for the DOM PrefixTree class for visualizing the associated prefixes.
By looking at a Dom::PrefixTree in the watch window
> Adding Native Visualization entry for the Dom PrefixTree.

- Gems/MotionMatching/Code/Source/TrajectoryQuery.cpp
> Motion Matching: Use target facing direction for strafing

- Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp
- Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.h
Adding the host ip address to the multiplayer viewport connection status. It's a common mistake for users to accidently connect to the wrong ip address. This is a feature so that devs can quickly see on screen which server ip they are using.
Partial fix for #9514
1. Ran the editor with editor server enabled; noticed that the connection status contained the server IP. Closed the server and made sure the server ip was still present on the client even after disconnected.
2. Launched ServerLauncher and GameLauncher and attempted to connect to an incorrect port. See the connecting attempt status and then disconnect status with the wrong ip address in the viewport status; thus making it easier for users to see that they used the wrong ip address
> Add the Host IP Address to the Multiplayer Viewport Connection Status

- scripts/build/build_failure_rca/preprocess/rules.json
- scripts/build/build_failure_rca/rca_patterns/Asset-Processing.json
- scripts/build/build_failure_rca/rca_patterns/Build-Environment.json
- scripts/build/build_failure_rca/rca_patterns/Cmake.json
- scripts/build/build_failure_rca/rca_patterns/Compilation.json
- scripts/build/build_failure_rca/rca_patterns/Test.json
Add build failure RCA patterns in O3DE repo. Build failure RCA lambda functions will read these patterns using Github API.
RFC: https://github.com/o3de/sig-build/blob/main/rfcs/rfc-bld-20220623-1-build-failure-rca.md
> Add build failure RCA patterns

- Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/DisplayMapperSRGB.azsl
- Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/DisplayMapperSRGB.shader
- Gems/Atom/Feature/Common/Assets/atom_feature_common_asset_files.cmake
- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/DisplayMapper/DisplayMapperPass.h
- Gems/Atom/Feature/Common/Code/Source/DisplayMapper/DisplayMapperPass.cpp
The GammaSRGB Display Mapper simply applied a fixed-gamma 2.2 curve on top of the internal AcesCG color space, whereas its name suggests that it should output to the (non-linear) sRGB color space. This is now fixed by first transforming to the correct sRGB color primaries and using the sRGB transfer curve.
All occurences of DisplayMapperOnlyGammaCorrection* have been renamed to DisplayMapperSRGB* to clearly reflect this change. The only functional change is in DisplayMapperSRGB.azsl (used to be called DisplayMapperOnlyGammaCorrection.azsl).
Note: this rename also affects the o3de-atom-sampleviewer project in one location: ToneMappingExampleComponent.cpp:300.
I'll add a PR there if this PR gets approved.
- A synthetic test scene where a diffuse square is illuminated such that a pure white …
> Fix GammaSRGB Display Mapper to output sRGB

- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_PhysicalSkyAdded.py
This PR updates the Null Renderer Physical Sky automation to include all P1 checks.
Test passed when runs locally in editor:
[SUCCESS] Success: Physical Sky Entity successfully created
[SUCCESS] Success: Entity has a Physical Sky component
[SUCCESS] Success: Sky Intensity set to Nit
[SUCCESS] Success: Sky Intensity set to Ev100
[SUCCESS] Success: Sky Intensity set to 0
[SUCCESS] Success: Sky Intensity set to 4.0
[SUCCESS] Success: Sun Intensity set to 1
[SUCCESS] Success: Sun Intensity set to 8.0
[SUCCESS] Success: Turbidity set to 5
[SUCCESS] Success: Turbidity set to 1
[SUCCESS] Success: Sun Radius Factor set to 0.0
[SUCCESS] Success: Sun Radius Factor set to 1.0
[SUCCESS] Success: Enable Fog …
> Update Physical Sky automation to P1

- Gems/GradientSignal/Code/Include/GradientSignal/Editor/EditorGradientBakerComponent.h
- Gems/GradientSignal/Code/Include/GradientSignal/Editor/EditorGradientBakerRequestBus.h
- Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.cpp
- Gems/GradientSignal/Code/Tests/EditorGradientSignalBakerTests.cpp
- Gems/GradientSignal/Code/gradientsignal_editor_files.cmake
Added `GradientBakerRequestBus` with APIs to get/set the appropriate fields on the gradient baker and also an event for initiating the bake action. Also added a unit test for verifying support for output resolutions of non-square resolution.
Tested new APIs from python script and ran unit tests.
> Added GradientBakerRequestBus so we can expose the gradient baker to script

- Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/AssetBuilderSDK.h
- Code/Tools/AssetProcessor/native/resourcecompiler/rcjob.cpp
Fixes an issue with AP jobs piling up as a result of many rapid changes to a file.
This block of code was really not serving any purpose.  If the fingerprint of a file changed, AP would pick up the file change and trigger another job anyway.  rccontroller would attempt to cancel the already-running job but this would fail since there was no listener set up at this point.
By removing this block, AP is much more responsive to rapidly changing files with no apparent downsides.
Note that testing also showed that a file which was opened for write with no shared access (exclusive write) would fail at the CreateJobs stage since the file can't be opened to even create the job, further making this code useless since it wasn't even possible to get to this code while the file was still locked. …
> [LYN-14130] Asset Processor - Removed job grace period and fingerprint-changing wait

- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RenderPipeline.h
- Gems/Atom/RPI/Code/Source/RPI.Public/RenderPipeline.cpp
- Gems/Atom/RPI/Code/Tests/System/RenderPipelineTests.cpp
Proposed quick fix for #9559: Check and assert if a view is registered a second time with a different view tag.
This is the easiest proposed fix in that it just doesn't allow registering a view with a different ViewTag. Not sure if this is a problem, or if using a view for multiple ViewTags is something people want to use.
Unfortunately the only way to unregister a persistent view is to register a different view with the same ViewTag, so this makes the Pipeline somewhat less flexible.
> add a check if a view is already registered

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.h
- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportToolBar.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/MotionData/NonUniformMotionData.cpp
- Gems/EMotionFX/Code/Source/Integration/Rendering/RenderFlag.h
Fixed the problem that when rotation is enabled the character feet sink under the ground.
Before:
After:
https://user-images.githubusercontent.com/69218254/181704634-c0de6960-8b5d-4277-af24-827b01350f36.mp4
Also added some debug rendering for root motion
> Fix the root motion extraction rotation problem

- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/LocalViewBookmarkLoader.cpp
Fixes a crash bug when slices are enabled when using view bookmarks
Fixes https://github.com/o3de/o3de/issues/10305
Fixes https://github.com/o3de/o3de/issues/10305
Tested starting the Atom Sample Viewer project and verified the Editor did not crash
> Fix crash with view bookmarks

- Gems/GraphCanvas/Code/Source/Widgets/NodePropertyDisplayWidget.cpp
- Gems/GraphCanvas/Code/Source/Widgets/NodePropertyDisplayWidget.h
Thanks to @cgalvan with his shared information. As ScriptCanvas node has edit and read-only widget, when hovering mouse over the node, node needs to switch between above two modes. And with extra resizeEvent getting triggered, we are able to see the weird flickering behavior.
Before fix
https://user-images.githubusercontent.com/5900509/181655632-b0c092b8-82f2-415c-a02a-f6b2efc8965a.mp4
With this PR change
https://user-images.githubusercontent.com/5900509/181655656-e50afdc5-aa99-40cd-b6ec-851a658c3409.mp4
> Fix ScriptCanvas Editor node flickering issue

- Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp
- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserBus.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserComponent.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AzToolsFrameworkModule.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Script/LuaEditorSystemComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Script/LuaEditorSystemComponent.h
- Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
- Code/Framework/AzToolsFramework/Tests/Script/LuaEditorSystemComponentTests.cpp
- Code/Framework/AzToolsFramework/Tests/UI/AssetBrowserTests.cpp
- Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
- Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
- Gems/ScriptCanvas/Code/Editor/SystemComponent.cpp
- Gems/ScriptCanvas/Code/Editor/SystemComponent.h
This PR contains changes for:
- Adding the ability to notify the model/view that a new asset was created
- This is useful for cases such as creating a new file that needs to be opened for editing in the view
- Adding the ability to create empty ScriptCanvas assets from the AssetBrowser
- Adding the ability to create empty Lua scripts and Lua component scripts from the AssetBrowser
- These changes also include:
- LuaEditorSystemComponent in AzToolsFramework which contains the Lua asset creator code, can serve as a general Lua system component in the Editor, and moves us towards potentially having a Lua editor gem some day
- AssetBrowserFileCreationNotificationBus with API for notifying the AssetBrowser that a new file was created through it, and for notifying individual …
> Add ability to create script assets through the editor Asset Browser

- Code/Framework/AzCore/Platform/Common/VisualStudio/AzCore/Natvis/azcore.natvis
This adds Visual Studio debugger visualizations for the AZStd::span type.
Ran Visual Studio and examined a few span<> variables in the debugger.
Before:
After:
> Add VS debug visualization for AZStd::span

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h
This PR changes `DPELayout` to cache `sizeHint` and `minimumSize` calculations and return those calculations until `QLayout::invalidate` is called.
If a cached value is present then it will be returned. If the cached value (a `QSize` member) is invalid then it will recalculate the layout size.
**Testing**
- Added logging statements to see when the functions were being called, and when cached values were returned/recalculated.
- Verified the DPE still works with some tif assets found in the AutomatedTesting project.
> DPE: Add item size caching and invalidation to DPELayout

- Code/Framework/AzCore/AzCore/Math/SimdMath.h
- Code/Framework/AzCore/AzCore/Math/SimdMathVec1.h
- Code/Framework/AzCore/AzCore/Math/SimdMathVec2.h
- Code/Framework/AzCore/AzCore/Math/SimdMathVec4.h
- Code/Framework/AzCore/Tests/Math/Vector2Tests.cpp
this just cleans up the existing test cases for Vector4Tests. 
- replace usage of == used with Vector4 with EXPECT_THAT
- replace TestAngles with separate parameterized tests, avoids a lot of the custom logic with parametrized test cases. 
run
```
./AzTestRunner ./libAzCore.Tests.so AzRunUnitTests --gtest_filter="*MATH_Vector2*"
```
> chore: cleanup Vector2Tests

- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
Prior to this PR, the DocumentPropertyEditor (DPE) was displaying container names and their sizes in two columns. This change combines the two into a single label which takes up space in only one column.
DPE with combined labels (ignore the element names as that's related to a different change):
RPE view:
**Testing**
- Tested in the editor using the DPE cvars
- Compared the DOM from before and after the change:
> DPE: Combine container name and size labels

- Code/Framework/AzCore/Tests/Math/Vector4Tests.cpp
this just cleans up the existing test cases for Vector4Tests. 
- replace usage of == used with Vector4 with EXPECT_THAT
- replace TestAngles with separate parameterized tests, avoids a lot of the custom logic with parametrized test cases. 
run
```
./AzTestRunner ./libAzCore.Tests.so AzRunUnitTests --gtest_filter="*MATH_Vector4*"
```
> chore: cleanup Vector4Tests

- Code/Framework/AzCore/Tests/Math/Vector3Tests.cpp
this just cleans up the existing test cases for Vector3Tests. 
- replace usage of == used with Vector4 with EXPECT_THAT
- replace TestAngles with separate parameterized tests, avoids a lot of the custom logic with parametrized test cases. 
run
```
./AzTestRunner ./libAzCore.Tests.so AzRunUnitTests --gtest_filter="*MATH_Vector4*"
```
> chore: cleanup Vector3Tests

- Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
- Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
Fixed a bug where old leftover code was preventing paths that were above a scanfolder from being reprocessed.
Also added a "Reprocess Source Asset" context menu item to jobs.
This fixes https://github.com/o3de/o3de/issues/10808
Manually
> Asset Processor - Fix Reprocess Folder on scanfolder parent path

- Code/Framework/AzCore/Tests/Math/Vector2Tests.cpp
- Code/Framework/AzCore/Tests/Math/Vector3Tests.cpp
- Code/Framework/AzCore/Tests/Math/Vector4Tests.cpp
Fixes #11026 
Fixed redefinition of struct/fixture names in `Vector2/3/4` unit tests, causing compile errors.
Verified local unity build now compiles and ran `AzCore` unit tests.
> Fixed compile errors in Vector2/3/4 unit tests

- Gems/ScriptCanvas/Code/Asset/EditorAssetSystemComponent.cpp
- Gems/ScriptCanvas/Code/Asset/EditorAssetSystemComponent.h
- Gems/ScriptCanvas/Code/Editor/SystemComponent.cpp
Prior to this PR, double clicking on ScriptCanvas assets in the AssetBrowser would not open them in the ScriptCanvas editor. This is also exhibited in their opener not showing up in the context menu.
This PR removes one of two `.scriptcanvas` file openers and fixes the other so that ScriptCanvas assets can be opened via the AssetBrowser.
Before fix:
After fix:
**Testing**
- Verified that ScriptCanvas files can be opened in the ScriptCanvas editor using double-click as well as the context menu option
> AssetBrowser: Fix ScriptCanvas file openers

- Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderWorker.cpp
- Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderWorker.h
- Gems/ScriptCanvas/Code/Editor/Assets/ScriptCanvasFileHandling.cpp
- Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Assets/ScriptCanvasFileHandling.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/GraphSerialization.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/GraphSerialization.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/ScriptEventBase.cpp
After deserialization, the source graphs are no longer activated, which stops their script event assets from loading if they are present.
Fixes #10972 
All SC assets were rebuilt, editor tests were successful.
> Do not activate graphs on CreateJobs(), which results in not loading assets.

- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/TableView.qss
arrows for the tableview fails to show up on linux. 
in the asset processor open up Builder/metrics. 
- click the green icon bottom right of the Editor
- select builder
- click metrics
> bugfix: fix rendering of arrow for tableview for linux

- Gems/Camera/Code/Source/CameraComponentController.cpp
remove dependency from VectorConversions for CameraComponentController.cpp
> chore: remove Vector3ToVector2 for Gems/Camera

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
Prior to this PR, combo box handlers in the DPE were being populated while their list of values from the adapter had not yet been consumed. This resulted in the combo box controls defaulting to the 0th item in their list of values and rendering their selected value unchangeable in the GUI.
This PR swaps the order of consumption and combo box population so that the values are available when the GUI is created. The change could affect any widgets loaded in a DPE that's standing in place of the RPE, so it's worth extra scrutiny.
DPE before and after change:
RPE values:
**Testing**
- Visual inspection of the code to verify nothing would break if executed in a different order (still could use an expert's opinion on this one)
- Verified the DOM can still be modified using other …
> DPE: Fix combobox handler starting values and reassignment

- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_cache_server.py
- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/acs_local_change/test_00.png
- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/acs_local_change/test_01.png
* adding a test to the regress that the local changes should persist on the local machine instead of using the cached archive
python/python.cmd -B -m pytest -v --build-directory bin/profile AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_cache_server.py
=========== test session starts ===========
cachedir: .pytest_cache
rootdir: C:\work\o3de, inifile: pytest.ini
collected 1 item
..\..\AutomatedTesting\Gem\PythonTests\assetpipeline\asset_processor_tests\asset_processor_cache_server.py::TestsAssetProcessorGUI_Windows::test_AssetCacheServer_LocalWorkUnaffected[windows-AutomatedTesting] PASSED       [100%]
=========== 1 passed in 13.53s ===========
> {lyn13342} added an asset cache server test for local changes

- Code/Framework/AzCore/AzCore/Asset/AssetManager.cpp
- Code/Framework/AzCore/Tests/Asset/AssetManagerLoadingTests.cpp
Fixes another bug with asset loading/reloading and asset containers caused by the following situation:
1. Asset is loaded and referenced
2. Reload occurs and completes
3. GetAsset is called for the same asset and starts the load process
4. Before the load can complete, the original reference is released
5. Asset containers for the AssetId are unloaded
6. Load cannot complete since there is no container remaining
This fix prevents this by verifying the creation token of the unloading asset matches the token for the container asset, which is the same check done in ReleaseAsset to prevent incorrectly removing old assets from m_asset
Created and ran unit test
> [LYN-14013] Asset Manager - Fix old asset references destroying containers for current loads

- Gems/Atom/Tools/AtomToolsFramework/Code/Source/GraphView/GraphView.cpp
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/GraphCanvasEditor/GraphCanvasAssetEditorMainWindow.cpp
Not all key bindings were working in material canvas graph view because they were competing with key bindings from the graphics view.
https://github.com/o3de/o3de/issues/10909
Verify key bindings worked and stopped printing messages about ambiguous bindings for those keys
> Material Canvas: fixing graph view key bindings

- scripts/o3de/o3de/manifest.py
- scripts/o3de/tests/test_manifest.py
The get_gem_external_subdirectories function wasn't removing the path
that completely visited from the set of visited gem paths when detecting
a cycle.
Also changed the visited gem `set` to a `list` to maintain insertion
order so that the error output show the visit order that led to the
cycle.
Validated that the `o3de.py enable-gem -gn <gem-name> -pp <project-name>` command no longer incorrectly reported a cycle for the Atom RHI gems when enabling a gem.
```
[ERROR] o3de.manifest: A cycle has been detected when visiting external subdirectories at gem path "/home/user/o3de/Gems/Atom/RHI/DX12". The visited paths are: {'/home/user/o3de/Gems/Atom/Asset/Shader', …
```
> Fix for cycle detection logic in the o3de manifest.py

- Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
The save-as dialog started in the wrong location and did not reveal previous .scriptcanvas files.
Closes #10789 
Closes #10698 
Closes #10398
Closes #9692
Save as  use revealed the bug, and the fix.
> fix save-as window

- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.cpp
- Code/Framework/AzCore/AzCore/Utils/Utils.cpp
- Code/Framework/AzCore/AzCore/Utils/Utils.h
- Code/Framework/AzCore/Platform/Common/Unimplemented/AzCore/Utils/Utils_Unimplemented.cpp
- Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/Utils/Utils_UnixLike.cpp
- Code/Framework/AzCore/Platform/Common/VisualStudio/AzCore/Natvis/azcore.natvis
- Code/Framework/AzCore/Platform/Windows/AzCore/Utils/Utils_Windows.cpp
- Code/Framework/AzCore/Tests/Settings/SettingsRegistryMergeUtilsTests.cpp
The Utils function which retrieves paths from the SettingsRegistry have
been updated to accept an optional pointer to the SettingsRegistry to
use to lookup the paths.
Added a GetGemPath function which can query the SettingsRegistry for the
absolute path to the gem root by supplying the gem name.
Updated the ReadFile utility function to support reading into an
`AZStd::vector<AZStd::byte>`
Updated the WriteFile utility function to write from an
`AZStd::span<AZStd::byte>`
Added UnitTest to validate the supplying a SettingsRegistry instance to the GetEnginePath, GetProjectPath, GetGemPath and GetO3deDirectory functions
> Updating the AZCore Utils functions

- Code/Framework/AzFramework/AzFramework/Spawnable/Spawnable.h
Add helpful types for Multiplayer auto-components.
Without this change, network components often have to escape in the following way:
```
<ArchetypeProperty Type="AZ::Data::Asset&lt;AzFramework::Spawnable&gt;" Name="CoinSpawnable"
ExposeToEditor="true" Description="Prefab to use for coins" />
```
With this change, one can do it as:
```
<ArchetypeProperty Type="AzFramework::SpawnableAsset" Name="CoinSpawnable"
ExposeToEditor="true" Description="Prefab to use for coins" />
```
Compiled o3de-multiplayersample.
> Added friendly types for Multiplayer auto-components

- Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
Adds files missed from previous PR https://github.com/o3de/o3de/pull/11044 addressing https://github.com/o3de/o3de/issues/10909
Retested key bindings with latest development branch
> Material Canvas: fixed more shortcuts by adding shortcut context to asset browser actions

- scripts/o3de/tests/test_global_project.py
This was causing a directory structure of "~/.o3de" to be added to
current directory.
Validated, that the "~" directory was no longer created when running the o3de CLI test.
> Added missing expansion of home directory in the global_project test

- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Shapes/AxisAlignedBoxShapeNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Shapes/AxisAlignedBoxShapeNode.h
- Gems/LandscapeCanvas/Code/Source/LandscapeCanvasSystemComponent.cpp
- Gems/LandscapeCanvas/Code/landscapecanvas_editor_static_files.cmake
Added support to Landscape Canvas for the `Axis Aligned Box Shape`.
Tested and verified the `Axis Aligned Box Shape` can be parsed from an existing entity, and can also be created in the graph.
> Added Landscape Canvas support or Axis Aligned Box Shape

- Code/Editor/ViewportTitleDlg.cpp
Address issues with viewport controls using different actions in the legacy action manager to drive functionality.
Verified functionality is unchanged both with the new Action Manager on and off.
> Action Manager | Refactor Viewport Snapping options to work when the legacy action manager is not instantiated.

- Code/Framework/AzCore/AzCore/Component/ComponentApplication.cpp
- Code/Framework/AzCore/AzCore/Component/ComponentApplication.h
- Code/Framework/AzCore/AzCore/DOM/DomUtils.cpp
- Code/Framework/AzCore/AzCore/Module/Module.h
- Code/Framework/AzCore/AzCore/Name/Internal/NameData.cpp
- Code/Framework/AzCore/AzCore/Name/Internal/NameData.h
- Code/Framework/AzCore/AzCore/Name/Name.cpp
- Code/Framework/AzCore/AzCore/Name/Name.h
- Code/Framework/AzCore/AzCore/Name/NameDictionary.cpp
- Code/Framework/AzCore/AzCore/Name/NameDictionary.h
- Code/Framework/AzCore/AzCore/RTTI/ReflectContext.cpp
- Code/Framework/AzCore/Tests/Name/NameBenchmarks.cpp
- Code/Framework/AzCore/Tests/Name/NameTests.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
- Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArray.cpp
- Gems/Atom/Feature/Common/Code/Source/Shadows/ProjectedShadowFeatureProcessor.cpp
- Gems/LyShine/Code/Source/World/UiCanvasOnMeshComponent.cpp
- Gems/RecastNavigation/Code/Tests/NavigationMeshTest.cpp
- Gems/Stars/Code/Source/StarsFeatureProcessor.cpp
Add support to the NameDictionary class to allow for local instances to
be created in addition to a global instance.
Switched the NameDictionary to register an instance pointer with an
`AZ::Interface<AZ::NameDictionary>`
The NameDictionary::IsReady and NameDictionary::Instance function now
returns the instance registered with the AZ::Interface
Changed the NameDictionary::Create function to not create a static
instance if it a NameDictionary instance is associated with an
AZ::Interface. Also simplified the logic to just invoke
`LoadDeferredNames` to link static Names into that NameDictionary instance
deferred head
Updated the Internal::NameData class to store a reference to the
NameDictionary that created it.
This allows the Internal::NameData class to avoid accessing the global
instance …
> NameDictionary non-singleton support

- Code/Framework/AzCore/AzCore/Math/Quaternion.inl
- Code/Framework/AzCore/Tests/Math/QuaternionTests.cpp
Fixes #11000 
The issue occurred because the terms which are used in the atan2 calls both go to zero when the pitch is exactly +-pi, which destroys any information they contain about the roll and yaw.
Also fixes another issue where accuracy would be severely affected when the pitch is close to +- pi, because asin has extremely high sensitivity near +-1.
Added further test cases in the quaternion unit tests which target pitch angles of +-pi. Verified that all branches in the revised function were being called during the tests. Ran a quaternion -> Euler -> quaternion cycle on 1000000 random quaternions.
> fix quaternion to Euler angle conversion when pitch is close to +-pi

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
- Gems/AtomLyIntegration/EMotionFXAtom/Registry/AnimViewport.setreg
Add the missing auxGeom FPs to anim editor. Without it the debug render stop working.
Run the editor, open anim editor, see the debug render function back up again.
> Add missing FPs for anim editor

- Gems/Terrain/Code/Source/Components/TerrainWorldRendererComponent.cpp
Added sections for mesh and detail materials in the world renderer component. Changed the ordering it so mesh settings are first, followed by detail material settings. This is only an ordering change - no content has changed.
> [terrain] Created sections for some properties in the Terrain world renderer component

- Code/Framework/AzFramework/AzFramework/Script/ScriptRemoteDebuggingConstants.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Utils/ScriptCanvasConstants.h
The AZ::Name::FromStringLiteral API was updated and the newly added
ScriptRemoteDebuggingConstants.h and ScriptCanvasConstants.h needs to be
updated to use that API.
Built AzFramework and the ScriptCanvas Gems successfully
> Development build fix

- Gems/GraphCanvas/Code/Source/Widgets/NodePropertyDisplayWidget.cpp
See warning when hovering mouse over node with combobox, it complains some ebus is still connected with other id before trying to connect to it.
Previously, moving layout cleanup call into the QTimer (for removing layout item from scene) somehow breaks the logic in this use case. As UpdateLayout does get triggered multiple times. When m_nodePropertyDisplay is null QTimer won't be trigger, we still need to ClearLayout to clear stale layout item.
The fix is straightforward, when QTimer should be triggered, we do ClearLayout inside QTimer. When QTimer won't be triggered, we keep old behavior. 
Tested manually, no more warnings.
> Avoid layout clean up warning

- AutomatedTesting/Gem/PythonTests/editor/EditorScripts/BasicEditorWorkflows_LevelEntityComponentCRUD.py
- AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/LayerBlender_E2E_Editor.py
- AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/PrefabInstanceSpawner_Embedded_E2E.py
- AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/PrefabInstanceSpawner_External_E2E.py
Increases the timeout to 10s for tests that verify a spawnable is properly processed on level save. These tests have intermittently failed to find the spawnable after the previously set 5s.
Ran all updated tests locally without issue.
> Increasing timeout in automated tests that verify level save

- Gems/LmbrCentral/Code/Source/Audio/EditorAudioMultiPositionComponent.h
- Sets the behavior type for Multi-Position Audio Component
fixes #10542
> Set the default enum for Multi-Position Audio Component

- Gems/AtomLyIntegration/CommonFeatures/Assets/Objects/Hermanubis/Hermanubis_stone.material
This material has a version 5 but uses a property name in version 4. The value will be ignored.
Other updates in https://github.com/o3de/o3de-atom-sampleviewer/pull/484
Tested on ASV SSR which uses this material.
> Update ASV material versions so warnings should be gone

- Code/Editor/Settings.cpp
- Code/Editor/Settings.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MorphTargetsWindow/PhonemeSelectionWindow.cpp
Removed unused legacy GUI settings from `SGUI_Settings`. The only setting in it still used is `nToolbarIconSize`, so we should look at moving that when working on the new toolbar management. Also removed commented out unused font family.
Built/ran unit tests. No compile errors after removing the unused settings.
> Removed legacy unused GUI settings

- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Styling/Parser.cpp
Fixed spam of `Qt: Invalid font-family:` whenever opening a tool that uses `GraphCanvas` (e.g. Script Canvas, Material Canvas, Landscape Canvas), even though the font families specified were valid. The previous check for an invalid font family was using `QFontInfo::exactMatch` which only checks against font families registered with your operating system, not ones that are explicitly added to our `QApplication` (e.g. our default font we ship with, Open Sans). Updated the check to query against the `QFontDatabase` which will accurately check against both any font families on your operation system + any explicitly registered only with the application.
Ran all `GraphCanvas` tools and warning messages are gone. Also tested by manually specifying an invalid font-family and seeing the warning …
> Fixed false positive invalid font family warning in Graph Canvas

- Tools/LyTestTools/tests/unit/test_abstract_resource_locator.py
- scripts/build/Jenkins/Jenkinsfile
Reduces log spam when test artifacts are uploaded. Had the options between --no-progress and --only-show-errors for the aws cp command. Decided on the --only-show-errors to minimize log size and the Jenkins log still shows the aws command.
Tested by intentionally failing AR and uploading artifacts. Jenkins logs reduced from 15 MB to 4 MB during testing.
> Remove AR artifact upload spam

- Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/ScriptEventMenu.cpp
When using the Save As ScriptEvent menu option, if users canceled, they would be presented with an error dialog. Canceling is not an error, so this change does not show an error dialog if no error message is returned.
In ScriptCanvas editor using the Save As ScriptEvent option and canceling the Save As operation
> Avoid reporting an error when the file open dialog is canceled

- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/Card.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/Card.h
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/Card.qss
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/CardHeader.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/CardHeader.h
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/Internal/RectangleWidget.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/Internal/RectangleWidget.h
- Code/Framework/AzQtComponents/AzQtComponents/Gallery/CardPage.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Gallery/CardPage.ui
- Code/Framework/AzQtComponents/AzQtComponents/azqtcomponents_files.cmake
It's a new style for card that is meant for "sections" in property
editors for grouping things.
To implement the underline in CardHeader a new internal widget was
introduced, a simple single-colored Rectangle. It wasn't feasible
to implement the underline with stylesheets because:
* the color may change at runtime so it can't be explicitly set
in the stylesheet
* ::setStylesheet() would conflict with what's happening in
Card::polish()
Separator card header styling got partially decoupled from the Card
itself because CardHeader will be later used stand-alone (see #10960).
Fixes: #10958
#10958
A new widget testing the functionality was added to card page in the O3DEQtControlGallery. It was also tested with the upcoming patch that uses …
> Implement separator Card

- Code/Framework/AzCore/AzCore/RTTI/AzStdOnDemandReflection.inl
The LuaScriptCaller does not copy const ref return values when executing
methods. In the case of `optional<T>::value_or`, it is possible for one
of its parameters to be its return value. In this case, the LuaScriptCaller
will allocate a new variable for the parameter, then clean up the value
used for the parameter and the value used for the return. If the return
value is the same as one of the parameters, it results in a double free.
This fixes the issue for `optional<T>::value_or` by forcing a copy of the
return value to take place.
```cpp
#include <AzCore/IO/ByteContainerStream.h>
#include <AzCore/Memory/Memory.h>
#include <AzCore/Memory/SystemAllocator.h>
#include <AzCore/RTTI/BehaviorContext.h>
#include <AzCore/Script/ScriptContext.h> …
```
> Update reflection of optional<T>::value_or to copy its return value

- Gems/AtomLyIntegration/AtomFont/Code/Source/AtomFontSystemComponent.cpp
Allow font on dedicated servers if it has rendering enabled
Resolves #10868 
Ran the ServerLauncher and see that debug font is rendering.
> Allow Font on Dedicated Server if it has a Renderer

- Gems/Atom/RPI/Code/Source/RPI.Public/FeatureProcessorFactory.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainMacroMaterialManager.h
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp
This PR fixes an issue with macro materials on large terrains, when the draw distance is greater than 8km causing the uint16 tile index to overflow. This change also removes noisy warnings from feature processor factory (sometimes these functions are called with the expectation that they may fail) and an unneeded include.
Tested several levels with draw distance > 8km before and after to ensure it was fixed.
> [Terrain] Fix for macro materials when terrain render distance > 8km

- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/AdapterBuilder.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/AdapterBuilder.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/CvarAdapter.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.h
- Code/Framework/AzFramework/Tests/DocumentPropertyEditor/CvarAdapterTests.cpp
- Code/Framework/AzQtComponents/AzQtComponents/DPEDebugViewStandalone/ExampleAdapter.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorWidget.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorWidget.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DPEDebugViewer/DPEDebugModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyManagerComponent.cpp
Prior to this PR, the DPE didn't have a way of notifying editors that its internal document had changed (user changes a property, for example). This meant that editors such as the Asset Editor wouldn't know when they could save the file.
This PR makes generally the following changes to enable saving and other property change signalling from the ReflectionAdapter to interested parties (the AssetEditorWidget in this case):
- The ReflectionAdapter now has a PropertyChangeEvent which can signal to functions taking a PropertyChangeInfo struct as described above
- The ReflectionAdapter is already listening for property change events in it's message handler, so we call its NotifyPropertyChanged function from there with the relevant data
- The AzToolsFramework::AssetEditorWidget …
> DPE: Enable ReflectionAdapter to signal that a property has changed

- Gems/Terrain/Code/Source/Components/TerrainWorldDebuggerComponent.cpp
The extra code to push the camera center point forward made some users confused, so this switches it back to the previous behavior of just using the camera's center as-is.
Closes #11020 .
Verified in-Editor that the new behavior works as expected.
> [Terrain] Revert debugger camera behavior.

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Datum.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Datum.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/SlotConfigurations.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/SlotConfigurations.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/FunctionCallNode.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Serialization/DatumSerializer.cpp
Fixes https://github.com/o3de/o3de/issues/8384
Problem is function node slot not constructed correctly. The metadata gets used to construct function node slot is from subgraphinterface. The metadata marks slot m_isOverloadedStorage = True which means slot is potentially a dynamic slot. When user reset slot, the slot datum type gets cleared.
The fix is to only copy type and value from subgraphinterface metadata for function node slot.
PS. Fix datum serializer error which could drop serialized data after reopening an existing graph. See following clip as an example.
https://user-images.githubusercontent.com/5900509/183148500-c0d262a4-6caa-4dc9-800a-578be56e95ec.mp4
Manually tested following GHI reproduce step, can't reproduce crash
> Fix function node slot reset crash

- Code/Framework/AzCore/AzCore/IO/Path/Path.h
- Code/Framework/AzCore/AzCore/IO/Path/Path.inl
- Code/Framework/AzCore/AzCore/IO/Path/PathParser.inl
- Code/Framework/AzCore/Tests/IO/Path/PathTests.cpp
The RootPath function was not returning the root directory part of the
path if that part didn't match the preferred path separator.
Also fixed the PathDecomposition functions to correctly propagate the
preferred separator of the path being decomposed to the returned
PathView.
Updated the ComparePathSegments and HashSegments functions of the
PathParser to be constexpr again by using std::is_constant_evaluated
intrinsic to branch the logic on compile time vs run time.
Added test to validate the Path Decompositions functions when using a
path instance with the windows path separator set as the preferred
separator, but the RootPath itself containied a Posix path separator
Added UnitTest to …
> Fixed the AZ::IO::Path RootPath function

- .github/CODEOWNERS
- Gems/Compression/Code/Include/Compression/CompressionInterfaceAPI.h
- Gems/Compression/Code/Include/Compression/CompressionInterfaceStructs.h
- Gems/Compression/Code/Include/Compression/DecompressionInterfaceAPI.h
- Gems/Compression/Code/Source/Clients/CompressionModule.cpp
- Gems/Compression/Code/Source/Clients/DecompressionFactoryImpl.cpp
- Gems/Compression/Code/Source/Clients/DecompressionFactoryImpl.h
- Gems/Compression/Code/Source/Tools/CompressionFactoryImpl.cpp
- Gems/Compression/Code/Source/Tools/CompressionFactoryImpl.h
- Gems/Compression/Code/compression_private_files.cmake
Registered an instance of the DecompressionFactory with an AZ::Interface.
Added VisitCompressionInterfaces/VisitDecompressionInterfaces functions
to both Compression and Decompression Archive Factories.
> Adding implementation of the Decompression Factory to the Compression Gem

- Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
Allows one to specify `Suffix="units"` for an ArchetypeProperty in an auto-component XML definition. For example:
```
<ArchetypeProperty Type="float" Name="Speed" ExposeToEditor="true" Suffix="world units per second" ....
```
Results in:
In o3de-multiplayersample using the following xml auto definition:
```
<?xml version="1.0"?>
<Component
Name="EnergyBallComponent"
Namespace="MultiplayerSample"
OverrideComponent="false"
OverrideController="true"
OverrideInclude="Source/Components/Multiplayer/EnergyBallComponent.h"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<ComponentRelation Constraint="Required" HasController="true" Name="NetworkTransformComponent" Namespace="Multiplayer" …
```
> Added Suffix to Edit reflection options for network auto-components

- Gems/EMotionFX/Assets/Editor/Images/Icons/ArrowRightGray.png
- Gems/EMotionFX/Code/MysticQt/Source/DialogStack.cpp
- Gems/EMotionFX/Code/MysticQt/Source/DialogStack.h
Arrow image asset could be removed because it's not used anywhere
anymore.
Fixes #10960
Implements new Container Card headers in EmotionFX instead of regular push buttons
Clicked around in Animation Editor around elements that use the DialogStack.
Current look:
> Use container card header in EmotionFX

- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Fixes the ImGui server option to "Launch Local Client". It would previously launch the client, but wouldn't auto-connect.
Fixes #11187 
Opened ImGui and tested "Launch Local Client" on both Linux and Windows
> Fix ImGui Server Option 'Launch Local Client' to Auto-Connect on Windows and Linux

- Code/Framework/AzCore/AzCore/IO/FileIO.cpp
- Code/Framework/AzCore/AzCore/IO/FileIO.h
- Code/Framework/AzFramework/Platform/Android/AzFramework/IO/LocalFileIO_Android.cpp
- Code/Framework/AzFramework/Platform/Common/UnixLike/AzFramework/IO/LocalFileIO_UnixLike.cpp
- Code/Framework/AzFramework/Platform/Common/WinAPI/AzFramework/IO/LocalFileIO_WinAPI.cpp
The `AZ::IO::FileIOBase::FindFiles` function would attempt to convert
the located file back into an alias path, which makes it cumbersome to
use when a real path is needed.
Updated the FileIO platform specific CreatePath and FindFiles functions
to use AZ::IO::FixedMaxPath
fixes #10436
Validated that FileIOTest and Archive test passes
> Updated the `FileIOBase::FindFiles` to not convert to alias

- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_PostFXRadiusWeightModifierAdded.py
Adds P1 null render tests for PostFX Radius Weight Component namely the radius property is exercised.
```
Report:
[SUCCESS] Success: PostFX Radius Weight Modifier Entity successfully created
[SUCCESS] Success: Entity has a PostFX Radius Weight Modifier component
[SUCCESS] Success: PostFX Radius Weight Modifier component was removed successfully
[SUCCESS] Success: Entity has a PostFX Radius Weight Modifier component
[SUCCESS] Success: PostFX Radius Weight Modifier component disabled
[SUCCESS] Success: PostFX Radius Weight Modifier component enabled
[SUCCESS] Success: Radius property set successfully
[SUCCESS] …
```
> P1 null render tests for PostFX Radius Weight Modifier

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp
Address the issue in https://github.com/o3de/o3de/issues/9700
The asset in the ticket will not create skinnedMeshInstance due to another issue (source asset must contain one bone and a skinned mesh). That issue has been addressed and now produce a warning msg in the log.
However, when the skinnedMeshInstance is missing, AtomActorInstance registerActor function will crash because it cannot find the instance. This change will do an early return on the registerActor() function, thus prevent the crash. 
Tested with repo steps in https://github.com/o3de/o3de/issues/9700
> Early return when failed to create skinnedMeshInstance in atomActorInstance to prevent crash.

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MorphTargetsWindow/MorphTargetGroupWidget.cpp
Add a null guard in morphTargetWindow. A potential solution of https://github.com/o3de/o3de/issues/8584 (for the crash in UI).
Perform repo steps in https://github.com/o3de/o3de/issues/8584
> Fix a crash for morph target window

- Code/Framework/AzCore/AzCore/Module/Environment.h
This disables the `Set()` functions of an `EnvironmentVariable` if a type
doesn't support move assignment or copy assignment.
> [Environment] Allow for move-only and copy-only types to be stored in environment variables

- Code/Editor/ProcessInfo.cpp
ref: https://github.com/o3de/o3de/issues/6624
correct the logic to correctly display memory size. integer was too small so when I multiplied the value by 1024 it would overflow the integer. 
verify on linux and verify memory size in bottom right of the editor.
> bugfix: increase size to avoid integer overflow when reporting memorysize

- scripts/build/build_node/Platform/Linux/install-ubuntu.sh
Adds Chrony to the Ubuntu build nodes to ensure that the time is synced to a higher resolution than the default (previously > 500ms). This ensures the target build files are in sync during the skew correction system task
Run in a sandbox Jenkins instance
> Add NTP sync to Ubuntu build nodes

- Gems/ScriptCanvas/Assets/TranslationAssets/Classes/AWSMetrics_AttributesSubmissionList.names
- Gems/ScriptCanvas/Assets/TranslationAssets/Classes/AWSMetrics_MetricsAttribute.names
- Gems/ScriptCanvas/Code/Editor/Nodes/NodeDisplayUtils.cpp
- Gems/ScriptCanvas/Code/Editor/Translation/TranslationHelper.cpp
- Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/GeneralNodePaletteTreeItemTypes.cpp
1. Fix translation for behavior class property node. Both class property and global constant getter should follow the same translation file format.
2. Fix translation file name inconsistency for behavior class node. While retrieving translation file, it should use the same sanitize function as the one used for creating translation file.
3. Update AWSMetrics node translation file by following correct format for closing https://github.com/o3de/o3de/issues/8581
Tested in Editor to make sure ScriptCanvas Node can be created with expected name
> Fix translation for class property and file name issue

- Code/Framework/AzCore/AzCore/Math/Quaternion.cpp
- Code/Framework/AzCore/AzCore/Math/Quaternion.h
- Code/Framework/AzCore/AzCore/Math/Quaternion.inl
- Code/Framework/AzCore/Tests/Math/QuaternionPerformanceTests.cpp
- Code/Framework/AzCore/Tests/Math/QuaternionTests.cpp
this change was in response to the PR referenced here. this adds tait-bryan angles for XYZ, YXZ, and ZYX. 
ref: https://github.com/o3de/o3de/pull/10508
this can be verified with the unit tests added.
> feat(AZCore): add CreateFromEuler/Radians/Degrees(XYZ,YXZ,ZYX)

- Gems/LmbrCentral/Code/Source/Ai/EditorNavigationAreaComponent.cpp
- Gems/LmbrCentral/Code/Source/Shape/PolygonPrismShape.cpp
- Gems/LmbrCentral/Code/Source/Shape/ShapeGeometryUtil.cpp
remove usage of VectorConversions from LmbrCentral
> chore: update LmbrCentral remove usage of VectorConversions

- Code/Framework/AzCore/Tests/Math/Matrix3x4Tests.cpp
- Code/Framework/AzFramework/AzFramework/Viewport/ViewportScreen.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/ManipulatorView.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/TranslationManipulators.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorHelpers.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
- Code/Framework/AzToolsFramework/Tests/Viewport/ViewportScreenTests.cpp
ref: https://github.com/o3de/o3de/pull/10597
remove the usage of VectorConversion.h from the rest of Framework.
> chore: update Framework and remove usage of VectorConversions

- Code/Framework/AzCore/AzCore/Component/ComponentApplication.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasAutoGenRegistry.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasAutoGenRegistry.h
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasGrammarRegistry_Source.jinja
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasNodeableRegistry_Source.jinja
- Gems/ScriptCanvas/Code/Source/ScriptCanvasCommonGem.cpp
- Gems/ScriptCanvasTesting/Code/Source/Framework/ScriptCanvasTestFixture.h
- AutoGen ScriptCanvas components weren't being properly unregistered
from the Component Application.
- Cache component descriptors so when a node registry is unregistered it
can unregister the descriptors too.
fixes #11004 
Ran AutomatedTesting.GameLauncher, open Console, type "quit".  Ensured clean shutdown.
> Fixes ComponentApplication shutdown in Launcher

- Code/Editor/EditorPreferencesPageViewportGeneral.cpp
- Code/Editor/EditorPreferencesPageViewportGeneral.h
- Code/Editor/EditorViewportSettings.cpp
- Code/Editor/EditorViewportSettings.h
- Code/Editor/EditorViewportWidget.cpp
- Code/Editor/EditorViewportWidget.h
- Code/Framework/AzCore/AzCore/Math/MatrixUtils.cpp
- Code/Framework/AzCore/AzCore/Math/MatrixUtils.h
This PR adds cvars to control the editor camera near and far planes.
We sometimes need to watch some details from a very near point of view, which is too close to the object and found no way to set the near and far planes.
We successfully used both cvar in our project.
> Add settings to set editor camera near and far plane distances

- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/Motion/SceneDebug/Jack_Idle_Aim_ZUp.dbgsg
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/Motion/SceneDebug/jack_idle_aim_zup.dbgsg.xml
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/OneMeshMultipleMaterials/SceneDebug/single_mesh_multiple_materials.dbgsg
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/OneMeshMultipleMaterials/SceneDebug/single_mesh_multiple_materials.dbgsg.xml
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/ShaderBall/SceneDebug/shaderball.dbgsg
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/ShaderBall/SceneDebug/shaderball.dbgsg.xml
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoMeshLinkedMaterials/SceneDebug/multiple_mesh_linked_materials.dbgsg
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoMeshLinkedMaterials/SceneDebug/multiple_mesh_linked_materials.dbgsg.xml
- Code/Tools/SceneAPI/SceneBuilder/Importers/AssImpTransformImporter.cpp
- Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabBehaviorTests.cpp
- Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.cpp
When generating a procedural prefab, create entities for scene nodes with transform data that don't have a corresponding parent node with mesh data. This preserves the parent/child node hierarchy.
GHI https://github.com/o3de/o3de/issues/9808
Added a unit test. Manually instantiated procedural prefab in the Editor.
> Add entities for transform nodes not associated with a mesh

- Code/Framework/AzCore/Tests/Asset/AssetManagerLoadingTests.cpp
Replaces calls to AssetBus::ExecuteQueuedEvents with AssetManager::Instance().DispatchEvents which will loop until all events have been processed from the queue.
Also added several additional calls before checking container count to ensure the queue is empty and containers have been released before we attempt to verify that.
Fixes https://github.com/o3de/o3de/issues/11200
Ran unit tests
> Asset Manager - Fix AssetManager tests using AssetBus::ExecuteQueuedEvents

- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
Signed-off-by: amzn-ahmadkrm <ahmadkrm@amazon.com>
Adds shortcut keys to the tooltip descriptions of the Transform icons in the Viewport: 
This PR changes 3 strings in:
AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
> Add shortcut keys to Viewport Transform icon tooltips

- Assets/Engine/textures/default_icon.png
Fixes #10639 
Deleted unused legacy Lumberyard icon.
Ran the editor and the Lumberyard icon no longer appears in the Asset Browser.
> Deleted deprecated file

- Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp
- Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.h
Adds multiplayer viewport debug messaging on the server. Making it easier for users to tell (1) servers and client apps apart and (2) quickly seeing how many clients are connected to a server.
_Dedicated server not hosting_
_Dedicated server hosting but not yet connected to any clients_
_Dedicated server hosting with clients in the game_
Resolves #9514 
Running ServerLauncher.exe, connecting clients, disconnecting clients and seeing debug text update
Running GameLauncher.exe, starting a client-server, connecting clients, disconnecting clients and seeing debug text update
> Multiplayer Server Viewport Debug Text

- AutomatedTesting/Editor/Scripts/scene_mesh_to_prefab.py
- Code/Tools/SceneAPI/SceneCore/Containers/Scene.cpp
- Code/Tools/SceneAPI/SceneCore/Events/AssetImportRequest.cpp
- Code/Tools/SceneAPI/SceneCore/Events/AssetImportRequest.h
- Code/Tools/SceneAPI/SceneCore/Events/ExportProductList.h
- Code/Tools/SceneAPI/SceneData/Behaviors/ScriptProcessorRuleBehavior.cpp
- Code/Tools/SceneAPI/SceneData/Behaviors/ScriptProcessorRuleBehavior.h
- Code/Tools/SceneAPI/SceneData/SceneData_testing_files.cmake
- Code/Tools/SceneAPI/SceneData/Tests/GraphData/GraphDataBehaviorTests.cpp
- Code/Tools/SceneAPI/SceneData/Tests/SceneManifest/SceneScriptRuleTests.cpp
* guarding the script hanlder life time between C++ and Python
* it is now possible to cleanly disconnect and clear out the handler in Python callback without affecting the C++ allocation
* added unit tests to regress the script rule feature
* did some manual testing as well to make sure the plumbing works
> {lyn13990} Fixing the Script Rule feature in the scene pipeline

- Code/Framework/AzCore/AzCore/Memory/HphaSchema.cpp
- Code/Framework/AzCore/AzCore/Memory/HphaSchema.h
- Code/Framework/AzCore/Tests/Memory/HphaSchemaErrorDetection.cpp
This allows removal of the includes of the HphaSchema.cpp files from within the HphaSchemaErrorDetection.cpp file
For the other cpp include of MallocSchema.cpp, it turns out it was never
used anywhere within the HphaSchemaErrorDetection test, so it has been removed.
This allows removal of  the using namespace calls for ::AZStd and ::AZ from the Internal namespace in the HphaSchemeaSchemaErrorDetection.cpp.
For example the `initializer_list` class is aliased in the AZStd namespace. So when `initializer_list` is specified instead of `AZStd::initializer_list`, it would cause a compilation issue because the `Internal::AZStd::initializer_list` symbol is not available because it wasn't aliased inside of the Internal namespace.
Pretty much the issues that occurs with including a cpp file with a …
> Moved the HphaSchema implementations to a base template classoved the HphaSchema implementations to a base template class

- Code/Framework/AzCore/AzCore/Name/Internal/NameData.cpp
- Code/Framework/AzCore/AzCore/Name/NameDictionary.cpp
- Code/Framework/AzCore/AzCore/Name/NameDictionary.h
- Code/Framework/AzCore/Tests/Name/NameTests.cpp
The NameDictionary
`NameTest.ConcurrencyDataTest_EachThreadRepeatedlyCreatesAndReleasesOneName_NoCollision`
was sporadically failing due to a race condition in `NameData::release`,
where the m_useCount member could be decremented to 0, followed another
thread invoking `NameDictionary::FindName` to locate that NameData
instance and initialize an AZ::Name with it which increments
the m_useCount back up to 1 and then that same thread can
have that AZ::Name instance go out of scope causing the m_useCount to
decrement back to 0.
What then occurs, is that one of threads can invoke
`NameDictionary::TryReleaseName` which deletes the name data instance,
while another thread could attempt to access the deleted
`m_nameDictionary` member of the NameData class.
Signed-off-by: lumberyard-employee-dm …
> Fixed race condition in the NameData::release function

- Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
This change resolves problems with material canvas code generation discovered after doing a clean pull from GH. The code generation logic searches for lines containing special markers denoting that code or data can be inserted at that point. The markers for inserting shader code instructions include a list of expected variables that’s parsed from that line. After performing a clean grab from GH, the last variable name on the line included an extra line ending character which caused the variable name to not be recognized and not have code generated for it. The additional line ending characters and other delimiters were added for tokenizing.
tested changes on multiple local machines
automated tests are scheduled to be written when the features …
> Material Canvas: Fixing code generation failures caused by line endings

- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNode.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNode.cpp
Graph model graph controller implements its own serialization that sits on top of what graph canvas does for serializing clipboard data. Whenever graph model nodes are deserialized from the clipboard they need to rebuild their non serialized slot data. Material canvas dynamic nodes were not reinitializing their slot definitions from the slot configurations whenever this happened which left them blank and without values.
https://github.com/o3de/o3de/issues/10910
https://github.com/o3de/sig-graphics-audio/issues/51
Manually tested clipboard operations in material canvas graph view
> Material Canvas: Fix cut, copy, paste, duplicate clipboard operations

- Code/Framework/AzCore/AzCore/Serialization/EditContextConstants.inl
Improved documentation for the property refresh levels. Specifically, calling out that `AttributesAndValues` doesn't include the `Visibility` attribute.
Documentation change only, so just rebuilt and verified the full build still compiles.
> Improved the documentation on the property refresh levels

- Code/Framework/AzCore/AzCore/Name/Name.cpp
- Code/Framework/AzCore/AzCore/Name/Name.h
- Code/Framework/AzCore/Platform/Android/AzCore/std/parallel/config_Android.h
Fixes #10608
Sets `native_thread_invalid_id` to 0 to match the same invalid value as linux.
What was happening is that due to the way the variables were initialized `s_staticNameListThread` arrived with value 0 and it wasn't the same as `native_thread_invalid_id` (value used by `AZStd::thread::id` in its default constructor), so it never got to assign `s_staticNameListThread` to the current thread id.
Build and run default level on pc and android without crashing.
> Fixed Name::SetNameLiteral on Android

- Code/Editor/EditorViewportSettings.cpp
- Code/Framework/AzCore/AzCore/Component/ComponentApplication.cpp
- Code/Framework/AzCore/AzCore/Component/ComponentApplication.h
- Code/Framework/AzCore/AzCore/Component/ComponentApplicationLifecycle.cpp
- Code/Framework/AzCore/AzCore/Console/Console.cpp
- Code/Framework/AzCore/AzCore/DOM/DomPrefixTree.inl
- Code/Framework/AzCore/AzCore/Math/Uuid.cpp
- Code/Framework/AzCore/AzCore/Math/Uuid.h
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistry.h
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryConsoleUtils.cpp
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryConsoleUtils.h
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.cpp
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.h
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryOriginTracker.cpp
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryOriginTracker.h
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryScriptUtils.cpp
- Code/Framework/AzCore/AzCore/UnitTest/Mocks/MockSettingsRegistry.h
- Code/Framework/AzCore/AzCore/azcore_files.cmake
- Code/Framework/AzCore/Tests/Settings/SettingsRegistryConsoleUtilsTests.cpp
- Code/Framework/AzCore/Tests/Settings/SettingsRegistryOriginTrackerTests.cpp
- Code/Framework/AzCore/Tests/Settings/SettingsRegistryTests.cpp
- Code/Framework/AzCore/Tests/azcoretests_files.cmake
- Code/Framework/AzFramework/AzFramework/Archive/Archive.cpp
- Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableSystemComponent.cpp
- Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/EditorCommonFeaturesSystemComponent.cpp
- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.cpp
- Gems/Multiplayer/Code/Source/NetworkEntity/NetworkSpawnableLibrary.cpp
Added implementation of a Settings Registry File Origin Tracker
The Settings Registry File Origin Tracker is responsible storing which files resulted in a particular value of a setting being read.
It does so by using the SettingsRegistry NotifyEvent mechanism to retrieve files being merged and add origin structs to the origin tracker's Prefix Dom Tree when setting values are added, modified, or removed. The origin tracker will also track if a settings value was changed in-memory.
Modified the Settings Registry implementation to send NotifyEvent signals for each key during a merge operation rather than only at the end of merging a json object.
Added a settings registry console command (`sr_dump_origin`) to dump all in-memory settings registry origins to the console.
Registered the origin …
> Settings registry editor/origin tracking

- Gems/Atom/RPI/Code/Tests/Common/RPITestFixture.cpp
- Gems/Atom/RPI/Code/Tests/System/SceneTests.cpp
This PR fixes intermittent unit test failure for FeatureProcessorManagement test
It is possible for ShaderMetrics.json ( a file created for each test) file to be corrupted from a previous run and make the test fail for subsequent runs. To prevent this, the PR uses a scoped directory which gets destroyed after the end of the test. So, even if the file gets corruped in one run, it wouldn't affect subsequent runs. I've also moved the user folder registration from the test fixture to the only test that needs it. Leaving it in the text fixture will make it possible for the same issue to reoccur when tests run in parallel.
Thanks to @lawsonamzn  for the suggestion to use scoped directory.
1. Before these changes, I …
> Make FeatureProcessorManagement test use a scoped temp directory

- Gems/Multiplayer/Code/Source/Components/NetworkTransformComponent.cpp
Fixes #11282
TLDR: an assert is being hit during host+loadlevel in a client-server hosted scenario.
Tested wIth a multiplayer project in client-server mode
> Client-server fixes with deactivate/activate for an autonomous entity

- Code/Editor/EditorViewportSettings.cpp
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryConsoleUtils.cpp
- Use a compatible type in both cases of ternary statement
- Updated event handlers to be of the correct signature
Fixes a compile error introduced to `development` branch.
Local build
> Fixes a build error in development

- Code/Framework/AzCore/Platform/Android/AzCore/AzCore_Traits_Android.h
- Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/std/parallel/internal/thread_UnixLike.cpp
- Code/Framework/AzCore/Platform/Linux/AzCore/AzCore_Traits_Linux.h
- Code/Framework/AzCore/Platform/Linux/AzCore/std/parallel/internal/thread_Linux.cpp
- Code/Framework/AzCore/Platform/Mac/AzCore/AzCore_Traits_Mac.h
- Code/Framework/AzCore/Platform/Windows/AzCore/AzCore_Traits_Windows.h
- Code/Framework/AzCore/Platform/iOS/AzCore/AzCore_Traits_iOS.h
- Code/Framework/AzFramework/AzFramework/Network/AssetProcessorConnection.cpp
The pthread library does not set the `errno` global when errors occur and instead returns the error code as the return value.
Clamped the hardcoded thread affinity for the Send and Recv thread for connecting to the AP
Every platform hardcodes the cpu affinity to 4, which would set the AP Send and Recv thread to try to be spawn on the 5th cpu.
This causes an issue on Linux with thread creation, if the machine only has less than 5 logical cores and the `nosmt` kernel flag is used to turn off simultaneous multithreading.
> Fixed output of pthread create_thread errors on Linux and Android

- Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.cpp
Add the DiffuseProbeGridUpdatePass after the DepthPrePass instead of the RayTracingAccelerationStructurePass.
Only add the DiffuseProbeGridVisualizationPass if the pipeline has an AuxGeom pass.
This allows the DiffuseProbeGridFeatureProcessor to handle pipelines that do not have the RayTracingAccelerationStructurePass and/or the AuxGeom pass.
> Add the DiffuseProbeGridUpdatePass after the DepthPrePass

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.hxx
Removes some redundant code in the Entity Outliner that prevents the previously focused prefab container from being forcefully collapsed. The previous logic relied on the false assumption that the previously focused prefab needs to be collapsed, which is not true when the new focus is a descendant of the previous one. Also, other existing notifications already enforce the correct handling of expanded states for the prefab hierarchy.
Fixes #11272 
Manual testing to verify the issue above no longer reproduces.
> Prefabs UI | Fix Outliner code to correctly expand ancestors of current focus

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ReflectedPropertyEditor.cpp
Fixes #11232
Added null dereference to prevent crash when the source node is null in a GroupElementToggle
Ran the editor to make sure it didn't crash when the hidden visibility attribute was added
> Fixed crash in GroupElementToggle when the hidden attribute was added

- Code/Framework/AzFramework/AzFramework/Entity/EntityDebugDisplayBus.h
- Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.cpp
- Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.h
when I was working on this change: https://github.com/o3de/o3de/pull/9925. I would rather of passed a vector then the beginning and a size into this method. This is just a minor tweak to the API to avoid passing in a raw pointer.
> feat: add DrawPolyLine that accepts a span instead of a pointer and a size

- Code/Editor/EditorViewportSettings.cpp
- Code/Editor/EditorViewportSettings.h
- Code/Editor/ViewportManipulatorController.cpp
- Code/Editor/ViewportManipulatorController.h
remove mouse wrap logic in the viewport. I need to revisit this with quite a few other changes before this could work. 
The manipulator has to work in screen space because at the moment its possible to drag far enough where the position for the object is reset to (0, 0, 0).  
ref: https://github.com/o3de/o3de/pull/6497/files
should pass with existing test cases, verify that dragging in the viewport has not changed.
> chore: remove mouse wrap for manipulator viewport

- Code/Framework/AzCore/AzCore/Asset/AssetManager.cpp
* this gives the authors of these handlers more information around the deserialization warning
manual testing to see the message in the logs
> {lyn14355} updating the AssetHandler::LoadAssetDataFromStream warning

- Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayer.h
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
- Gems/Multiplayer/Code/Tests/CommonBenchmarkSetup.h
- Gems/Multiplayer/Code/Tests/MockInterfaces.h
- Gems/Multiplayer/Code/Tests/MultiplayerSystemTests.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/EventHandlerTranslationUtility.h
Adds an `AzEventDescription` to `GetOnEndpointDisconnectedEvent` in `MultiplayerSystemComponent.cpp`. Additionally fixes several typos of `Disonnected` -> `Disconnected`
Launched Material Editor and did not observe an error around reflection of the event.
> Reflect GetOnDisconnectedEvent Description plus typo fixes

- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryConsoleUtils.cpp
Broken when #11263 and #11028 merged together
> Trace methods now must be accessed through the instance

- Gems/EMotionFX/Code/CMakeLists.txt
- Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeTransformNode.cpp
- Gems/EMotionFX/Code/MCore/Source/AzCoreConversions.h
- Gems/EMotionFX/Code/Tests/MCore/AZCoreConversionsTest.cpp
- Gems/EMotionFX/Code/Tests/TransformUnitTests.cpp
- Gems/EMotionFX/Code/emotionfx_tests_files.cmake
replaces the MCore variant with AZ::Quaternion::CreateFromEulerAnglesRadians 
this should be covered under the existing unit test.
> chore(EmotionFX): update AzEulerAnglesToAzQuat with AZ::Quaternion::CreateFromEulerAnglesRadians

- Code/Tools/SceneAPI/SceneUI/RowWidgets/ManifestVectorWidget.ui
Fixes padding on the "Add Modifier" button in scene settings
Manual testing, visual verification.
> Scene settings button padding

- cmake/Platform/Common/MSVC/Configurations_msvc.cmake
- cmake/Platform/Windows/Configurations_windows.cmake
This moves command line flags that only apply to MSVC into the right place.
> Move MSVC-only flags to the Configurations_msvc file

- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Shapes/ReferenceShapeNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Shapes/ReferenceShapeNode.h
- Gems/LandscapeCanvas/Code/Source/LandscapeCanvasSystemComponent.cpp
- Gems/LandscapeCanvas/Code/landscapecanvas_editor_static_files.cmake
Added Landscape Canvas support for the `Shape Reference` node. This shape node is unique in that it takes an input shape bounds which is what it forwards on as its shape bounds to other listeners.
Tested created and graphing existing entities with the Shape Reference component. Verified changing the inbounds shape connections in the graph resulted in the appropriate input shape being referenced by listeners.
> Added support for Shape Reference node

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Conversion.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Conversion.h
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphCompiler.h
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Scope.cpp
documentation: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkAccessFlagBits.html
```
VK_ACCESS_TRANSFER_WRITE_BIT specifies write 
access to an image or buffer in a [clear](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#clears) or [copy](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#copies) operation. Such access occurs in the VK_PIPELINE_STAGE_2_ALL_TRANSFER_BIT pipeline stage.
```
VK_ACCESS_TRANSFER_WRITE_BIT specifies a write access on an image this is placed on the barrier proceeding the  vkcmdclearimage. This appears to be reletaed to AMD where the clear and read seem to be happening at the same time. this produces the square artifacts on the image. …
> bugfix(Vulkan): set access bit on image barrier

- Gems/Atom/RHI/Code/Include/Atom/RHI.Edit/Utils.h
This was triggered by AsyncComputeShadow.shader in Atom Sample Viewer, which sets AddBuildArguments.debug = true.
Same cause described below, but this one is more hidden because it's using a template.
https://github.com/o3de/o3de-atom-sampleviewer/pull/493
Tested AsyncComputeShadow.shader now it compiles.
> [Atom] Fix shader compilation error

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.h
This PR removes an unnecessary warning on identifying other path prefix types (e.g. `/LinkId/{someString}/`) in prefab template propagation (during selective deserialization).
As we have forced template propagation when entering and exiting prefab focus mode (#11120), which frequently updates link id in instance DOM, we should remove the warning statement so it won't pollute editor console.
There is no impact because we already skipped processing any patches like this. The warning is just for debugging purpose.
> Prefab | Remove warning on identifying link id patch during template propagation

- Code/Tools/SceneAPI/SceneCore/Containers/Scene.cpp
- Code/Tools/SceneAPI/SceneCore/Events/ExportProductList.cpp
- Code/Tools/SceneAPI/SceneCore/Mocks/MockBehaviorUtils.h
- Code/Tools/SceneAPI/SceneCore/Tests/Containers/SceneBehaviorTests.cpp
- Code/Tools/SceneAPI/SceneCore/Tests/Containers/SceneGraphTests.cpp
- Code/Tools/SceneAPI/SceneCore/scenecore_testing_files.cmake
- Code/Tools/SceneAPI/SceneData/Behaviors/ScriptProcessorRuleBehavior.cpp
- Code/Tools/SceneAPI/SceneData/Tests/SceneManifest/SceneScriptRuleTests.cpp
Some EBuses are currently scoped to Common which causes the Lua script context to inspect and assert around data types that are not properly set up for Lua scripting. These errors and asserts are improperly logged during asset pipeline builds; this leads to confusion. Since the EBuses are only meant for Python automation they will be changed to Automation.
* from ScopeFlags::Common to ScopeFlags::Automation
* using UnitTest::ScopeForUnitTest() to fix up unit tests
Fixed the unit tests in SceneCore and SceneData.
> {lyn14636} switching script buses to Automation

- Code/Framework/AzCore/AzCore/Asset/AssetDataStream.cpp
- Code/Framework/AzCore/AzCore/Serialization/ObjectStream.cpp
This removes the profile markers from AssetDataStream::Read and Seek, and from ObjectStreamImpl::LoadClass. These methods can get called potentially on a byte-by-byte basis when serializing in assets, which makes the overhead of the markers far greater than the value they provide.
These markers were previously added when using a different profiling system, where the markers consumed far less overhead. They now consume more overhead, making these markers relatively expensive without being useful.
Ran PIX and verified that the markers no longer show up.
Before:
After:
> Removed a couple of "chatty" profile markers.

- Code/Tools/LuaIDE/Source/LUA/LUAEditorContext.cpp
Fixes https://github.com/o3de/o3de/issues/9380
Signed-off-by: Lars Gleim <lgleim@users.noreply.github.com>
LuaEditor by default casts all paths provided via the `-files` command line flag to lower case, which breaks paths on case-sensitive platforms (e.g. Linux)
Building the Editor & confirming that files provided via the `-files` flag are opened
> Remove to_lower conversion of LuaEditor files CLI parameters

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.cpp
This fixes some Asset Picker Widget error states. 
* If an asset is removed while the widget is active, it now displays an error icon showing that it has been removed. (Previously, you had to restart the Editor to get the error icon)
* If the asset reference is cleared while the error icon is shown, the error icon is now cleared. (Previously, the error icon remained)
Closes #11346 .
Ran through the repro steps on #11346 .
> Fix bugs with the Error icon on the Asset Picker Widget.

- Code/Tools/SceneAPI/SceneCore/Containers/GraphObjectProxy.cpp
- Code/Tools/SceneAPI/SceneCore/Containers/GraphObjectProxy.h
- Code/Tools/SceneAPI/SceneCore/Tests/Containers/SceneBehaviorTests.cpp
This adds methods to fetch and assign data in the GraphObject node.
Added unit tests:
- SceneGraphBehaviorScriptTest.GraphObjectProxy_Fetch_GetsValue
- SceneGraphBehaviorScriptTest.GraphObjectProxy_GetClassInfo_HasProperties
> {lyn14020} added Fetch to GraphObjectProxy

- scripts/build/build_node/Platform/Linux/package-list.ubuntu-bionic.txt
- scripts/build/build_node/Platform/Linux/package-list.ubuntu-focal.txt
- scripts/build/build_node/Platform/Mac/install-xcode.sh
- scripts/build/build_node/Platform/Windows/install_utiltools.ps1
Bumps the version of CMake in the AR build nodes to 3.24.0. Addresses https://github.com/o3de/o3de/issues/10939 and allows generation of the VS2022 solution using the VS2022 msbuild 
> Bump the version of CMake to 3.24.0 in the AR build nodes

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Datum.cpp
ref: https://github.com/o3de/o3de/issues/8060
when viewing the node in the node inspector the label of the field will be displayed as [0]. this sets the override for the label so a proper display name is shown.
- open script in scriptcanvas and view node in node inspector.
- verify that the label text correctly displays a proper label.
> bugfix(ScriptCanvas): correctly display labels in the Node Inspector used to display [0]

- Gems/LmbrCentral/Code/Source/Shape/BoxShape.cpp
- Gems/LmbrCentral/Code/Source/Shape/CapsuleShape.cpp
- Gems/LmbrCentral/Code/Source/Shape/CylinderShape.cpp
- Gems/LmbrCentral/Code/Source/Shape/DiskShape.cpp
- Gems/LmbrCentral/Code/Source/Shape/PolygonPrismShape.cpp
- Gems/LmbrCentral/Code/Source/Shape/PolygonPrismShape.h
- Gems/LmbrCentral/Code/Source/Shape/QuadShape.cpp
- Gems/LmbrCentral/Code/Source/Shape/SphereShape.cpp
- Gems/LmbrCentral/Code/include/LmbrCentral/Shape/ShapeComponentBus.h
The polygon prism has a complex scheme for managing its shared mutex so that it doesn't get double-locked on the same thread, which can cause a deadlock. However, the scheme was getting bypassed when the shared mutex was passed directly into the IntersectionDataCache. It needed a bit more logic to *not* pass the shared mutex in the case that it was already exclusively locked.
Closes #11372 .
Ran through the steps in 11372 and verified that they no longer lock up the Editor. Also tried adding / removing / modifying vertices in the same situation and verified they all worked.
> Fix for polygon prism single-thread deadlock.

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/BufferMemoryPageAllocator.cpp
Fix a leak related to not deleting the VkBuffer after checking for it's memory requirements. It does this by removing the manual creation and destruction(incorrectly) of the VkBuffer and instead calling the Device::GetBufferMemoryRequirements which handles caching as well as creation/destruction of the VkBuffer properly. 
Tested by running full test suite (modified slightly) on pc using vulkan backend
> Fix a leak within Vulkan backend

- Code/Framework/AtomCore/AtomCore/Instance/InstanceId.cpp
- Code/Framework/AtomCore/AtomCore/Instance/InstanceId.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialUtils.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Material/MaterialAsset.h
- Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilder.cpp
- Gems/Atom/RPI/Code/Source/RPI.Builders/Model/MaterialAssetBuilderComponent.cpp
- Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialUtils.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Material/Material.cpp
This PR attempts to address issues with material related workflows, hot reloading, material editor and canvas.
The material system and builder provide user settings to control whether materials and their connections to material types are fully baked in the AP or when the assets are loaded in the editor/game. These settings also control asset dependencies between materials and material types. This can help preview times while making iterative changes to shaders and material types because it stops the AP from rebuilding all of the materials and models that reference the modified assets. However, it also breaks the expected dependencies between materials and material types, leading to atypical handling of material related assets, requiring manual dependency tracking, and prevents asset …
> Changing material builder settings and (AtomCore) AZ::Data::InstanceId to support material editor and canvas workflows

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphCompiler.h
It fixes the following vulkan validation that is spamming each frame 
[Error] (vkDebugMessage) - [ERROR][Validation] Validation Error: [ VUID-vkCmdPipelineBarrier-srcAccessMask-02815 ] Object 0: handle = 0x20fa61bc598, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x24d88c2b | vkCmdPipelineBarrier(): .pImageMemoryBarriers[0].srcAccessMask bit VK_ACCESS_TRANSFER_WRITE_BIT is not supported by stage mask (VK_PIPELINE_STAGE_VERTEX_SHADER_BIT|VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT|VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT|VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT|VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT|VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT). The Vulkan spec states: The srcAccessMask member of each element …
> Fix a Vulkan validation error that was spamming every frame

- Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/MemoryUsage.h
Fixed a false asset issue when memory budget was set to 0.
Open loft scene with setreg  "O3DE/Autoexec/ConsoleCommands/bg_assertsAutoBreak" value set to 'true'
> Fix a heap memory validataion issue when memory budget is set to 0.

- Gems/ScriptAutomation/Code/Tests/ScriptAutomationApplicationFixture.cpp
- Error was reported about failure to write to UserSettings.xml
- Added a call to DisableSaveOnFinalize to avoid the error
Attempts to eliminate an error that was produced in a recent unit test. May not solve the issue in the (apparently) flaky test, but we've seen this cause problems in the past and this is the remedy.
Built and ran `ScriptAutomation.Tests`.
> Disable UserSettings Save in a test fixture

- Gems/Multiplayer/Code/Include/Multiplayer/Components/NetBindComponent.h
- Gems/Multiplayer/Code/Include/Multiplayer/NetworkEntity/NetworkEntityUpdateMessage.h
- Gems/Multiplayer/Code/Source/MultiplayerStats.cpp
- Gems/Multiplayer/Code/Source/NetworkEntity/EntityReplication/EntityReplicationManager.cpp
- Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityTracker.h
- Gems/Multiplayer/Code/Tests/CommonNetworkEntitySetup.h
- Gems/Multiplayer/Code/Tests/NetworkEntityTests.cpp
- Gems/Multiplayer/Code/Tests/NetworkInputTests.cpp
- Gems/Multiplayer/Code/Tests/ServerHierarchyTests.cpp
- Gems/Multiplayer/Code/multiplayer_tests_files.cmake
This change introduces a significant number of unit tests to the Multiplayer Gem. These units cover various pieces of basic functionality across the NetworkEntity classes in addition to shoring up a few other areas.
Ran Multiplayer.Tests and verified completeness with OpenCppCoverage.
> Add several unit tests for NetworkEntity in Multiplayer Gem

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutorInterface.h
This PR ensures that only unique instances are added to the propagation queue. This prevents a lot of patch generation and additional logic for each duplicate instance in the queue.
Tested manually on large levels to ensure that locking and unlocking many entities at once doesn't cause significant slowdown or memory spike. Before this change, locking 1000 entities in a 3000 entity level took almost 2 mins to finish and memory spiked up to 50GB. After this the time came down to less than a second and memory only increased 0.2 GB. Created a follow up issue to see why memory is spiking for operations: https://github.com/o3de/o3de/issues/11401
Will run unit and automated tests that existing prefab workflows are …
> Add a set to ensure only unique instances get added to propagation queue

- Code/Framework/AzCore/AzCore/Serialization/AZStdContainers.inl
- Code/Framework/AzCore/AzCore/Serialization/SerializeContext.h
added method to discern between associative containers with mapped
values and simple containers with only keys. Added GetValueByKey to
retrieve values from associative containers by key.
added method to discern between associative containers with mapped
values and simple containers with only keys. Added GetValueByKey to
retrieve values from associative containers by key.
locally with Generic DOM code
> associative containers: added method to retrieve a value by key and the ability to discern containers with mapped types from simple keyed containers

- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
Added an alignment attribute in the DPE, so that a PropertyEditor can be created with specific alignment.
Currently only supports AlignLeft and AlignRight. This is part of an effort to get the DPE Layout to look more similar to the RPE- Layout.
PR was tested by adding the alignment attribute to three different PropertyEditors.
Current view with alignment:
Previous view without alignment:
> Created an Alignment attribute in the DPE

- AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py
- Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerEditorServerBus.h
- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorAutomation.cpp
- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorAutomation.h
- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
- Gems/Multiplayer/Code/multiplayer_editor_shared_files.cmake
Util.py multiplayer util no longer reads through log events. Instead there is a bus handler (MultiplayerEditorServerNotificationBusHandler) which can listen for important multiplayer editor notifications.
Multiplayer pytest have been flaky in the past, so I wanted to rule out the possibility that parsing logs was causing the flakiness. With 1000's of spam lines to read through, it possible that parsing logs were causing the tests to time out. 
Note: This is only part 1 for fixing #10673. 
Remaining work:
1. Individual tests themselves are still parsing logs, these need to change by listening for specific multiplayer events.
2. Individual tests were built using script canvas which periodically need updating and are unusually large (13Mb); we want to move these tests to C++ to rule out any …
> Multiplayer PyTest Util No Longer Parses Logs

- pytest.ini
Adds a 20 minute pytest timeout to the pytest.ini config file. This config file is used in AR and will apply its timeout to each test case. Timeout provides full stack trace on timeout.
Tested by using a short timeout locally.
> Adding 20 minute pytest timeout

- Code/Framework/AzCore/AzCore/base.h
not sure how this is failing to pass AR when it fails to compile on my linux machine. I attached my ubuntu system in the description if that is any use. snprintf is a dependency is stdio. 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```
> bugfix: fix compiling errors with azvsnprintf for linux

- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportMessages.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportMessages.h
- Code/Framework/AzToolsFramework/Tests/Viewport/ViewportInteractionTests.cpp
This adds a new overload to the FindClosestPickIntersection API that lets you determine no hit was found, vs the previous version that always returned a hit point based on default distance if no hit was found.
This functionality will be needed by the upcoming paintbrush feature that projects the paintbrush into the viewport, but shouldn't show the paintbrush when no intersections are found.
Added new unit tests to verify both versions of the API, testing both the case that a point is hit and the case that no hit point is found.
Tested locally with paintbrush functionality to ensure that it works with the paintbrush use case.
> FindClosestPickIntersection API extension to detect optional results

- Code/Framework/AzCore/Platform/Android/AzCore/Debug/Trace_Android.cpp
- Code/Legacy/CryCommon/StlUtils.h
Built the TEST_SUITE_main and Editor target using VS2022 successfully
Built the AzFramework target using Android.
> Adding missing includes to fix Windows VS2022 and Android non-unity build

- Code/Legacy/CrySystem/Log.cpp
This was incorrectly removed in #11301 for the path that uses the old
CLog behavior of `LogStringToFile` for formatting string output.
Only the new `LogWithCallback` function which performs no formatting of
the message should not automatically add the newline.
Validated the debug console output in Visual Studio were separated with newlines.
> Adding newline back to the debug console for Windows and Android

- Code/Framework/AzCore/AzCore/Settings/SettingsRegistry.h
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.cpp
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.h
- Code/Framework/AzCore/AzCore/UnitTest/Mocks/MockSettingsRegistry.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/SettingsRegistryAdapter.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/SettingsRegistryAdapter.h
- Code/Framework/AzFramework/AzFramework/azframework_files.cmake
- Code/Framework/AzFramework/Tests/DocumentPropertyEditor/SettingsRegistryAdapterTests.cpp
- Code/Framework/AzFramework/Tests/frameworktests_files.cmake
- Code/Framework/AzQtComponents/AzQtComponents/DPEDebugViewStandalone/main.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DPEDebugViewer/DPEDebugModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DPEDebugViewer/DPEDebugTextView.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DPEDebugViewer/DPEDebugWindow.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DPEDebugViewer/DPEDebugWindow.h
Integrates @noortor work for implementing a Settings Registry Adapter that can view and edit the associated Settings Registry.
The Settings Registry Adapter can be played in the [DPEDebugViewStandalone](https://github.com/o3de/o3de/blob/development/Code/Framework/AzQtComponents/CMakeLists.txt#L79-L91) application under the AzQtComponents folder.
The Settings Registry Adapter can modify existing fundamental type fields of objects and arrays which are string, bool, float and int, but currently cannot add or remove fields from an array or object.
Added the WM_DeleteOnClose attribute the [DPEDebugWindow class and DocumentPropertyEditor](https://github.com/o3de/o3de/blob/development/Code/Framework/AzQtComponents/AzQtComponents/DPEDebugViewStandalone/main.cpp#L217-L220) to fix shutdown crash in …
> Adding Settings Registry Adapter feature

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ReflectedPropertyEditor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ReflectedPropertyEditor.hxx
ref: https://github.com/o3de/o3de/issues/11193
this handles releasing the last prompt if one is already open when setting a key for a variable in the canvas.
follow the instructions in the referenced ticket.
https://user-images.githubusercontent.com/854359/184549797-7f8c88cf-feda-41f8-a700-69f2219fef9b.mp4
> bugfix(ScriptCanvas): prevent multiple prompts when providing a key

- Code/Tools/LuaIDE/Source/LUA/LUAEditorPlainTextEdit.cpp
this resolves the font size problem with the lua text editor
follow steps linked: https://github.com/o3de/o3de/issues/10514
> bugfix(Lua Editor): correctly handle updaing font size for lua editor

- Code/Tools/LuaIDE/Source/LUA/LUAEditorContext.cpp
- Code/Tools/LuaIDE/Source/LUA/LUAEditorContext.h
ref: https://github.com/o3de/o3de/issues/11412
This introduces a helper method to fetch the documentInfo since all the asset ids are expected to be lower case. Linux filesystem ignores case so this just ensures that whatever is fed into this interface is correctly converted. 
verify that a lua document can be saved with capitlization.
> bugfix(Lua Editor): better handle fetching documents by id for linux

- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h
- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h
- Gems/Atom/Feature/Common/Code/Mocks/MockMeshFeatureProcessor.h
- Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
Added the interface function `bool GetVisible(const MeshHandle& meshHandle) const` for the MeshFeatureProcessor, since it was missing.
Use the function in code to find out the visibility state of a mesh.
> Added GetVisible() to the MeshFeatureProcessor

- Gems/LandscapeCanvas/Assets/LandscapeCanvas/StyleSheet/graphcanvas_style.json
- Gems/LandscapeCanvas/Code/Source/Editor/Core/Core.h
- Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaFilters/BaseAreaFilterNode.h
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/BaseAreaModifierNode.h
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaSelectors/AssetWeightSelectorNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaSelectors/AssetWeightSelectorNode.h
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/BaseNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/BaseNode.h
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Terrain/TerrainHeightGradientListNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Terrain/TerrainHeightGradientListNode.h
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Terrain/TerrainLayerSpawnerNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Terrain/TerrainLayerSpawnerNode.h
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Terrain/TerrainSurfaceGradientListNode.cpp
- Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Terrain/TerrainSurfaceGradientListNode.h
- Gems/LandscapeCanvas/Code/Source/LandscapeCanvasSystemComponent.cpp
- Gems/LandscapeCanvas/Code/landscapecanvas_editor_static_files.cmake
Added support for the Terrain Layer Spawner node, as well as Height and Surface Gradient List wrapped nodes that extend the spawner. As part of this PR had to make some modifications to Landscape Canvas that assumed there would only be Vegetation wrapped nodes.
Ran Landscape Canvas automated tests. Also tested the vegetation wrapper nodes to make sure they still function as expected.
> Implemented Terrain Layer Spawner and Height/Surface Gradient List wrapped nodes

- Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp
Signed-off-by: Sondre Agledahl <sondre@sondre.io>
Trivial rewording of message dialog that pops up when creating a desktop shortcut for a project, following UX suggestions from @amzn-leenguy in #7780.
Verified updated message is displayed and links to desktop. Ran `RUN_TESTS` target.
> Reword desktop shortcut creation message

- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/NodePalette/TreeItems/IconDecoratedNodePaletteTreeItem.h
Methods of this class check for null on m_iconPixmap so we should
initialize it as such.
This fixes crashes when this class is used but icon is not actually set.
Initializes a pointer field to nullptr.
By running the debugger.
> Initialize field in IconDecoratedNodePaletteTreeItem

- Gems/RecastNavigation/Code/Source/Misc/RecastNavigationPhysXProviderComponentController.cpp
Fixes #11418
```
[==========] Running 24 tests from 1 test case.
[----------] 24 tests from NavigationTest
[ RUN      ] NavigationTest.GetNativeNavMesh
[       OK ] NavigationTest.GetNativeNavMesh (39 ms)
[ RUN      ] NavigationTest.TestAgainstEmptyPhysicalBody
[       OK ] NavigationTest.TestAgainstEmptyPhysicalBody (103 ms)
[ RUN      ] NavigationTest.BlockingTest
[       OK ] NavigationTest.BlockingTest (23 ms)
[ RUN      ] NavigationTest.BlockingTestWithDebugDraw
[       OK ] NavigationTest.BlockingTestWithDebugDraw (20 ms)
[ RUN      ] NavigationTest.BlockingNonIndexedWithDebugDraw
[       OK ] NavigationTest.BlockingNonIndexedWithDebugDraw (20 ms)
[ RUN      ] …
```
> Bug fix for Aabb assert in Recast Navigation unit tests in Debug

- scripts/build/Platform/Android/pipeline.json
- scripts/build/Platform/Linux/pipeline.json
- scripts/build/Platform/Windows/pipeline.json
Switches the CI build label for Windows and Android builds to an image that contains VS2019, VS2022, and CMake 3.24. Prevents issues with CMake pathing for CI builds prior to CMake 3.24, but requires a clean build
Tested in a sandbox instance, with a clean build
> Change build label for CMake/VS2022 update

- scripts/build/Platform/Android/build_config.json
- scripts/build/Platform/Android/pipeline.json
- scripts/build/Platform/Linux/pipeline.json
- scripts/build/Platform/Windows/build_config.json
- scripts/build/Platform/Windows/pipeline.json
Removes the hardcoded generator for Windows AR builds to allow use of VS2022+. CMake uses a default list of generators starting from latest versions of VS2022 through a registry scan.
Nightly builds will be preserved on the VS2019 generator to allow for regression coverage.
Run successfully on a sandbox Jenkins instance, with a clean build
> VS2022 Windows AR generator change

- Code/Tools/ProjectManager/Platform/Windows/ProjectBuilderWorker_windows.cpp
- scripts/build/Platform/Android/build_config.json
- scripts/build/Platform/Android/pipeline.json
- scripts/build/Platform/Linux/pipeline.json
- scripts/build/Platform/Windows/build_config.json
- scripts/build/Platform/Windows/pipeline.json
Removes the hardcoded generator in Project Manager to support VS2022+ in Windows. CMake defaults to the latest version of Visual Studio if no generator is specified (though we can add docs for using the `CMAKE_GENERATOR` env var for specific use cases). 
Note this combines: https://github.com/o3de/o3de/pull/11447 and https://github.com/o3de/o3de/pull/11448 to allow for testing. 
Resolves https://github.com/o3de/o3de/issues/8478 and https://github.com/o3de/o3de/issues/10911
Run on a sandbox Jenkins instance, with clean build
> VS2022 Windows project manager support

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Operators/Math/OperatorMul.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Operators/Math/OperatorMul.h
- Gems/ScriptCanvasTesting/Assets/ScriptCanvas/UnitTests/LY_SC_UnitTest_OperatorMul.scriptcanvas
adds support to vector2/3/4 and color to multiply node. 
add script canvas unit test for multiply just not sure how to run the test for the script canvas
> feat(ScriptCanvas): add vector2/3/4 and color to multiply node
