- Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp
> Change default MSAA samples to 4

- Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeWidget.cpp
> Animation Editor crashes when selecting a node in Skeleton Outliner

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentExporter.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentExporter.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.h
> Atom Tools: added scriptable export function to editor material component slot to enable testing

- Code/Editor/LogFile_mac.mm
> [Mac] Compare the MacOS version against the deployment target and not the SDK version

- Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
Tested by running unit tests locally
> fixes test tools crash log not found error

- Gems/QtForPython/Editor/Scripts/show_object_tree.py
Changes the ObjectTree picker behavior to improve the readability of which widget is being picked.
> Improve ObjectTree tool to show the extents of the hovered widget during picking

- AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Sandbox.py
> Added basic game/server launcher connection test.

- Gems/LyShine/Code/Editor/CanvasSizeToolbarSection.cpp
Fix issue #8046
Signed-off-by: Andre Mitchell <andre.mitchell@bytesofpi.com>
> Prevent invalid resolutions from being entered for a UI Canvas.

- Registry/gem_autoload.materialeditor.setreg
- Registry/gem_autoload.serializecontexttools.setreg
- Registry/gem_autoload.shadermanagementconsole.setreg
> Updated top key in setreg files for autoload from "Amazon" to "O3DE".

- .github/CODEOWNERS
> Starting codeowners files.

- Code/Tools/SerializeContextTools/Converter.cpp
- Gems/AudioEngineWwise/Code/Source/AudioEngineWwiseGemSystemComponent.cpp
> Build fixes for INSTALL target.

- Gems/EMotionFX/Code/Source/Editor/JointSelectionWidget.cpp
> Fixed crash on mac when selecting ragdoll joints within an Activate Ragdoll Joints node in Anim Graph.

- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/LocalViewBookmarkComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/LocalViewBookmarkLoader.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/LocalViewBookmarkLoader.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewBookmarkLoaderInterface.h
This is a small follow-up PR to address a couple of small issues discovered in the initial View Bookmark PR (see https://github.com/o3de/o3de/pull/7855).
> A few small follow-up updates for View Bookmarks after initial PR

- Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp
> Updated Visual Studio Version to 16.11 and 17.0

- Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/Device_Windows.cpp
> Address DX12 validation spam

- scripts/build/build_node/Platform/Windows/init_setup.ps1
Activates crash reporting on any Windows Jenkins AR build node
> Activate registry entry for Windows crash reporting

- Gems/EMotionFX/Code/EMotionFX/CommandSystem/Source/MotionCommands.cpp
> EMotion FX: Editor crashes after closing Animation Editor

- scripts/o3de/o3de/download.py
- scripts/o3de/o3de/utils.py
> Print download progress if there's no specified progress function

- Gems/Atom/RHI/Code/Source/RHI/BufferView.cpp
- Gems/Atom/RHI/Code/Source/RHI/ImageView.cpp
> Fix a typo related to view hash

- Code/Framework/AzCore/AzCore/Task/TaskGraph.cpp
- Code/Framework/AzCore/AzCore/Task/TaskGraphSystemComponent.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
> Default flag sytems to use TaskGraph

- Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
- Gems/ScriptCanvas/Code/Editor/Components/GraphUpgrade.cpp
- Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorGraph.h
- Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/GraphUpgrade.h
- Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Controller.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Modifier.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/View.ui
Fixes and minor upgrades for version explorer.
> Code to changes to make it easier to upgrade graphs for end of object stream support.

- cmake/3rdParty/Platform/Android/BuiltInPackages_android.cmake
Package has been promoted and verified.
> Update O3DE to use new version of Android AWS Native SDK

- Gems/ScriptCanvasDeveloper/Code/CMakeLists.txt
> Enabled ImGui for ScriptCanvasDeveloper gem

- Code/Editor/EditorPreferencesPageViewportCamera.cpp
- Code/Editor/EditorPreferencesPageViewportCamera.h
- Code/Editor/EditorViewportCamera.cpp
- Code/Editor/EditorViewportCamera.h
- Code/Editor/EditorViewportSettings.cpp
- Code/Editor/EditorViewportSettings.h
- Code/Editor/EditorViewportWidget.cpp
- Code/Editor/EditorViewportWidget.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/AzToolsFrameworkTestHelpers.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/AzToolsFrameworkTestHelpers.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportMessages.h
This change still needs a bit more testing and maybe a couple more comments but it's more or less there, will try and get it merged tomorrow.
> Add support for default camera orientation

- scripts/o3de/o3de/utils.py
> Add simple download resuming based on file size returned.

- Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignmentSerializer.cpp
- Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialUtils.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Material/Material.cpp
- Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/MaterialPropertyValue.cpp
- Gems/Atom/RPI/Code/Tests/Material/MaterialAssetTestUtils.cpp
- Gems/Atom/RPI/Code/Tests/Material/MaterialAssetTests.cpp
- Gems/Atom/RPI/Code/Tests/Material/MaterialTests.cpp
- Gems/Atom/RPI/Code/Tests/Material/MaterialTypeSourceDataTests.cpp
-Fix issues when open saved material using attachment image.
-Add unit tests for attachment image in material's tests
> Follow up change for ATOM-17383.

- scripts/build/Jenkins/Jenkinsfile
Uploads the default directory for crash artifacts. Tested by running in Sandbox Jenkins.
Edit: Mac has also been added and tested in sandbox
> Upload crash artifacts in AR

- scripts/build/Platform/Linux/build_config.json
> Make asset_profile_nounity non-blocking

- Code/Framework/AzFramework/AzFramework/Spawnable/Script/SpawnableScriptMediator.cpp
- Code/Framework/AzFramework/AzFramework/Spawnable/Script/SpawnableScriptMediator.h
> Fixing OnSpawnCompleted/OnDespawnCompleted callbacks

- Code/Framework/AzCore/Platform/Android/platform_android_files.cmake
> Fixed Android AzCore Utils.cpp path

- Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
> Merge https://github.com/o3de/o3de/pull/8863 to stabilization

- Code/Tools/AssetProcessor/AssetBuilder/TraceMessageHook.cpp
This should fix an issue where AssetBuilder error stream and out stream messages getting out of order when printed in the log
> [LYN-1623] Asset Processor: Use stdout instead of stderr

- Tools/LyTestTools/ly_test_tools/_internal/managers/abstract_resource_locator.py
- Tools/LyTestTools/tests/unit/test_abstract_resource_locator.py
> Added logging to json decode error.

- scripts/build/Platform/Linux/deploy_cdk_applications.sh
- scripts/build/Platform/Linux/destroy_cdk_applications.sh
- scripts/build/Platform/Windows/deploy_cdk_applications.cmd
- scripts/build/Platform/Windows/destroy_cdk_applications.cmd
Signed-off-by: Junbo Liang [68558268+junbo75@users.noreply.github.com](mailto:68558268+junbo75@users.noreply.github.com)
Reviewed at https://github.com/o3de/o3de/pull/8784 and https://github.com/o3de/o3de/pull/8827
> Cherry-pick 8712cc3 and 7021b27 from development: Use O3DE Python to run cdk deploy

- Gems/AWSCore/Code/Tools/ResourceMappingTool/tests/unit/utils/test_aws_utils.py
- Gems/AWSCore/Code/Tools/ResourceMappingTool/utils/aws_utils.py
- Verified error message in log and pop up window when credentials couldn't be retrieved successfully
- Passed unit tests
> #8651 Fix resource mapping tool unhandled exceptions

- Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderBuildArgumentsManager.cpp
- Gems/Atom/Feature/Common/Code/Source/Debug/RenderDebugSettings.h
Also fixing `RenderDebugSettings` compilation error being friend with itself.
> Fixed release configuration errors due to unused variables.

- scripts/o3de/o3de/repo.py
Fix for repo list that is expected to directly contain strings of the repos added (copy/paste error from above code).
> Fix for repositories that contain repositories.

- scripts/build/Jenkins/Jenkinsfile
reverting the use of replace content plugin in AR
> Revert jenkins plugin

- Gems/Atom/Feature/Common/Code/Source/FrameCaptureSystemComponent.cpp
> Fixed an issue with CaptureScreenshotWithPreview

- Code/Tools/CrashHandler/Tools/ToolsCrashHandler.cpp
> Remove unused crash handler code

- Gems/Atom/Feature/Common/Code/Source/ImGui/ImGuiPass.cpp
- Gems/Atom/Feature/Common/Code/Source/ImGui/ImGuiPass.h
> Fixed git issue 8649 and 8647

- AutomatedTesting/Gem/PythonTests/Prefab/tests/reparent_prefab/ReparentPrefab_UnderAnotherPrefab.py
- Code/Framework/AzFramework/AzFramework/Physics/Material.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceToTemplatePropagator.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
- Code/Tools/AssetProcessor/native/resourcecompiler/RCBuilder.cpp
- Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
- Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderBuildArgumentsManager.cpp
- Gems/Atom/Feature/Common/Code/Source/AuxGeom/AuxGeomDrawQueue.cpp
- Gems/Atom/Feature/Common/Code/Source/Debug/RenderDebugSettings.h
- Gems/Atom/Feature/Common/Code/Source/FrameCaptureSystemComponent.cpp
- Gems/LyShine/Assets/LyShine/Shaders/LyShineUI.shader
- Gems/LyShine/Assets/Passes/LyShineChildPass.pass
- Gems/LyShine/Assets/Passes/RttChildPass.pass
- Gems/LyShine/Code/Source/Draw2d.cpp
- Gems/LyShine/Code/Source/RenderGraph.cpp
- Gems/LyShine/Code/Source/UiCanvasComponent.cpp
- Gems/LyShine/Code/Source/UiRenderer.cpp
- Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
- Gems/PhysX/Code/Editor/DebugDraw.cpp
- Gems/PhysX/Code/Editor/DebugDraw.h
- Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
- scripts/build/Platform/Linux/deploy_cdk_applications.sh
- scripts/build/Platform/Linux/destroy_cdk_applications.sh
- scripts/build/Platform/Windows/deploy_cdk_applications.cmd
- scripts/build/Platform/Windows/destroy_cdk_applications.cmd
Merging:
stabilization/2205          7c52d94dcf [upstream/stabilization/2205] Merge pull request #8999 from aws-lumberyard-dev/allisaurus/fix-illegal-slash
into:
development                 84968a2124 [origin/development] [Terrain] Fix shape area falloff to calculate either 2D or 3D falloff. (#9057)
Manually merged files
modified:   Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderBuildArgumentsManager.cpp
modified:   Gems/Atom/Feature/Common/Code/Source/Debug/RenderDebugSettings.h
modified:   Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
modified:   Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
modified:   Code/Tools/AssetProcessor/native/resourcecompiler/RCBuilder.cpp
modified:   Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp …
> Stabilization to dev merge - 05/22/2022

- Gems/Atom/Feature/Common/Assets/Materials/Types/DepthPass_WithPS.azsli
- Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedSurface_ForwardPass.azsli
- Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialFunctions/EnhancedParallaxDepth.azsli
- Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR_ForwardPass.azsl
Cherry-picked https://github.com/o3de/o3de/pull/9135 into the development branch
> Cherry-Pick Fix For Inconsistent Depth Calculations

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportToolBar.cpp
> Animation Editor: Added the debug rendering flag to the render viewport

- Gems/Atom/Feature/Common/Code/Source/Utils/EditorLightingPreset.cpp
Fixes 
https://github.com/o3de/o3de/issues/8395
https://github.com/o3de/o3de/issues/7428
> Fix typos in lighting preset exposure control edit context descriptions

- Code/Editor/AboutDialog.cpp
- Code/Editor/StartupLogoDialog.cpp
- Code/Editor/StartupLogoDialog.qrc
- Code/Editor/splashscreen_background.png
- Code/Editor/splashscreen_background_2021_11.jpg
- Code/Tools/AssetBundler/source/utils/utils.cpp
- Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/ParallaxInput.azsli
- Gems/Atom/Feature/Common/Assets/Passes/EnvironmentCubeMapPipeline.pass
- Gems/Atom/Feature/Common/Assets/Passes/LowEndRenderPipeline.azasset
- Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignment.cpp
- Gems/Atom/Feature/Common/Code/Source/Utils/EditorLightingPreset.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportToolBar.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetSelection/AssetSelectionComboBox.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetSelection/AssetSelectionGrid.cpp
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportToolBar.cpp
- Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/Icons/toneMapping.svg
- Gems/Atom/Tools/MaterialEditor/Code/Source/Window/Icons/toneMapping.svg
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
- Gems/Multiplayer/Code/Source/Components/LocalPredictionPlayerInputComponent.cpp
- cmake/Platform/Linux/Packaging/postinst.in
git merge -S stabilization/2205
CONFLICT (modify/delete): Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/SpawnTicketInstance.h deleted in HEAD and modified in stabilization/2205. Version stabilization/2205 of Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/SpawnTicketInstance.h left in tree.
CONFLICT (modify/delete): Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/SpawnTicketInstance.cpp deleted in HEAD and modified in stabilization/2205. Version stabilization/2205 of Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/SpawnTicketInstance.cpp left in tree.
Auto-merging Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
Auto-merging Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCan …
> Stabilization to dev merge - 04/28/2022

- Code/Tools/ProjectManager/Platform/Mac/ProjectUtils_mac.cpp
- Gems/Blast/Code/Editor/ConfigurationWidget.h
- Gems/Blast/Code/Source/Editor/Material/LegacyBlastMaterialPrefabConversion.cpp
> Fixed blast compilation error in non-unity build. Fixed also mac error.

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionExtractionWindow.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionExtractionWindow.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionPropertiesWindow.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionPropertiesWindow.h
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionWindowPlugin.cpp
- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionWindowPlugin.h
> Animation Editor: Moved motion properties to unified inspector window

- cmake/3rdParty/FindWwise.cmake
- Reads version information from a header file in the SDK.
- Compares it against a "minimum" SDK version and prints versions if
there's no supported version available to use.
closes #4945
> Updated FindWwise.cmake to check Wwise version

- Code/Framework/AzCore/Platform/Android/AzCore/std/parallel/internal/thread_Android.cpp
- Gems/Atom/RHI/Registry/Platform/Android/PlatformLimits.setreg
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Instance.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Memory.cpp
> Fixing errors found while running O3DE on Android.

- .github/CODEOWNERS
> Updated CODEOWNERS for sig-graphics-audio

- Templates/PrebuiltGem/Template/preview.png
- Templates/PrebuiltGem/preview.png
> Updated the PrebuiltGem template to the new O3DE icon.

- AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Main.py
> disable flaky test while under investigation #9422

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuter.cpp
> Use a merged execute group for unmergable scopes that don't need a renderpass

- AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Main.py
> disable flaky physics test #9301

- Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
- Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
- Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.h
- Gems/PhysX/Code/Source/Shape.cpp
- Gems/PhysX/Code/Source/Shape.h
- Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
- Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
- Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.cpp
- Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.h
> Heightfield material operations optimization

- Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp
- Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.h
https://user-images.githubusercontent.com/69218254/167970469-39514881-5bf3-4b95-9732-de884ff268c5.mp4
<-- see video above to see it in action -->
Skin attachment works in editor
P.S: We might be overdue on refactor ActorComponent / EditorActorComponent to use the shared component base. If we had done that work a lot of the same logic between the editor/runtime component could share the same code and avoid a lot of code duplication. 
> Skin attachment works in editor

- Gems/PhysX/Code/Tests/PhysXSystemTests.cpp
> PhysX Unit tests fix

- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_LookModificationAdded.py
Adding P1 automaton support for the Look Modification component.
Atom_Main_Null_Render passes without issue:
1/4 Test #158: AutomatedTesting::Atom_Main_Null_Render_02.main::TEST_RUN ...   Passed   54.53 sec
Start 159: AutomatedTesting::Atom_Main_Null_Render_03.main::TEST_RUN
2/4 Test #159: AutomatedTesting::Atom_Main_Null_Render_03.main::TEST_RUN ...   Passed   49.84 sec
Start 157: AutomatedTesting::Atom_Main_Null_Render_01.main::TEST_RUN
3/4 Test #157: AutomatedTesting::Atom_Main_Null_Render_01.main::TEST_RUN ...   Passed   46.46 sec
Start 156: AutomatedTesting::Atom_Main_Null_Render_00.main::TEST_RUN
4/4 Test #156: AutomatedTesting::Atom_Main_Null_Render_00.main::TEST_RUN ...   Passed   38.31 sec
Report:
[SUCCESS] Success: Look Modification Entity successfully created
[SUCCESS] Success: …
> Adding P1 automation support for Look Modification component

- cmake/3rdParty/Platform/Mac/BuiltInPackages_mac.cmake
Update mac to use fixed Mac Qt package
Signed-off-by: spham <82231385+spham-amzn@users.noreply.github.com>
> Update package rev and hash for qt for mac

- Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Grid/GridComponentBus.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Grid/GridComponentController.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Grid/GridComponentController.h
Updating comments and formatting after finding issues when writing documentation
> Grid component: updating comments and formatting

- Gems/Blast/Code/Source/Editor/Material/LegacyBlastMaterialAssetConversion.cpp
> #9561 Non-monolithic release build fix

- scripts/build/Platform/Android/pipeline.json
- scripts/build/Platform/Linux/pipeline.json
- scripts/build/Platform/Mac/pipeline.json
- scripts/build/Platform/Windows/pipeline.json
- scripts/build/Platform/iOS/pipeline.json
Fix nightly/weekly tag name in pipeline.json
> Fix nightly/weekly tag name

- Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.h
- Code/Framework/AzCore/AzCore/std/createdestroy.h
- Code/Framework/AzCore/Tests/Script.cpp
- Code/Tools/SceneAPI/SceneBuilder/ImportContexts/AssImpImportContexts.cpp
- Code/Tools/SceneAPI/SceneBuilder/ImportContexts/AssImpImportContexts.h
- Code/Tools/SceneAPI/SceneBuilder/ImportContexts/ImportContexts.cpp
- Code/Tools/SceneAPI/SceneBuilder/ImportContexts/ImportContexts.h
- Gems/Blast/Code/Source/Components/BlastFamilyComponent.cpp
- Gems/PhysX/Code/Source/Module.cpp
- Gems/PhysX/Code/Source/System/PhysXSystem.cpp
- Gems/PhysX/Code/Source/System/PhysXSystem.h
- Gems/PhysX/Code/Tests/PhysXEditorTest.cpp
- Gems/PhysX/Code/Tests/PhysXTestEnvironment.cpp
- Gems/SceneProcessing/Code/Source/Config/Components/SceneProcessingConfigSystemComponent.cpp
- cmake/Platform/Common/Clang/Configurations_clang.cmake
There's a few different leaks being fixed by this PR, check the individual commits for the details
> Fix memory leaks

- scripts/o3de/tests/test_download.py
> Add tests to check for repo object updates

- Tools/LyTestTools/ly_test_tools/_internal/pytest_plugin/terminal_report.py
> Added additional logging for tests with unknown results.

- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_LightAdded.py
P1 Light Component Automation - Adding support for Intensity Mode and Shadowmap Size
Test project F:/git/o3de/build_development_new
Start 159: AutomatedTesting::Atom_Main_Null_Render_02.main::TEST_RUN
1/4 Test #159: AutomatedTesting::Atom_Main_Null_Render_02.main::TEST_RUN ...   Passed   56.08 sec
Start 160: AutomatedTesting::Atom_Main_Null_Render_03.main::TEST_RUN
2/4 Test #160: AutomatedTesting::Atom_Main_Null_Render_03.main::TEST_RUN ...   Passed   47.93 sec
Start 158: AutomatedTesting::Atom_Main_Null_Render_01.main::TEST_RUN
3/4 Test #158: AutomatedTesting::Atom_Main_Null_Render_01.main::TEST_RUN ...   Passed   44.86 sec
Start 157: AutomatedTesting::Atom_Main_Null_Render_00.main::TEST_RUN
4/4 Test #157: AutomatedTesting::Atom_Main_Null_Render_00.main::TEST_RUN ...   Passed   44.54 sec …
> P1 Light Component Automation Adjustments

- AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/prefab_utils.py
- AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Main.py
- AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Main_Optimized.py
- AutomatedTesting/Gem/PythonTests/Prefab/tests/delete_prefab/DeletePrefab_ContainingNestedEntitiesAndNestedPrefabs.py
Used existing "CreatePrefab_WithNestedEntitiesAndNestedPrefabs" test as reference.
> Automated test for deleting nested prefab

- Code/Editor/TrackView/TrackViewAnimNode.cpp
updating the endpoints for the methods that were deprecated. 
ref: https://github.com/o3de/o3de/pull/9327
> chore: update calling Set/Pos/Rotation/Scale for CTrackViewAnimNode

- .github/CODEOWNERS
- engine.json
Start incrementing the internal version number to track breaking changes.
Signed-off-by: AMZN-nggieber <52797929+AMZN-nggieber@users.noreply.github.com>
> Enable Internal Versioning Increment Review

- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
QA is blocked, needing these additional command line options for their new automated test framework for ME. These changes will apply to ME, MC, SMC, and future tools.
> Atom Tools: Command line options for log file and batch mode for automated tests

- AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Main_Optimized.py
Linux is currently failing for unknown reasons when running these tests. Disabling until we find a solution.
https://github.com/o3de/o3de/issues/7795
> Disabling Spawnables python tests

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
Signed-off-by: Noor Mahini <nmahini@berkeley.edu>
> removed option to close level prefab in editor

- Gems/WhiteBox/Code/Source/EditorWhiteBoxComponentMode.cpp
- Gems/WhiteBox/Code/Source/EditorWhiteBoxComponentMode.h
- Gems/WhiteBox/Code/Source/EditorWhiteBoxComponentModeBus.h
- Gems/WhiteBox/Code/Source/EditorWhiteBoxComponentModeTypes.h
- Gems/WhiteBox/Code/Source/SubComponentModes/EditorWhiteBoxTransformMode.cpp
- Gems/WhiteBox/Code/Source/SubComponentModes/EditorWhiteBoxTransformMode.h
- Gems/WhiteBox/Code/whitebox_editor_supported_files.cmake
This adds the ability to do fine tuning adjustment in whitebox. Early work in progress on this feature. I'm not quite sure how this will work functionally.
> feat(WhiteBox): implement transform mode

- Gems/LyShine/Code/Source/UiCanvasComponent.cpp
> Add error checking around attachment image asset format for UI Canvas

- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/pythonassetbuildertests.py
- Code/Tools/SceneAPI/SceneCore/Utilities/DebugOutput.cpp
> {lyn13016} output scene manifest during scene building

- Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/ScriptEventMenu.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/ScriptEventMenu.h
> Guard SE parse actions with validity check; update menu action enabled

- Gems/EMotionFX/Code/CMakeLists.txt
- Gems/EMotionFX/Code/EMotionFX/Pipeline/RCExt/Actor/ActorBuilder.cpp
- Gems/EMotionFX/Code/Tests/ActorBuilderTests.cpp
> EMotion FX: Remove GFxFramework

- .github/CODEOWNERS
> Add Sig-Content as owner of AzCore/Asset

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.cpp
- Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/MaterialComponentRequestBus.names
Instead of entering all of the data with behavior context reflection, the translation file was updated with names and tooltips for all of the functions and parameters on the material component request bus.
> Material Component: Updated data file with names and tooltips for script canvas nodes

- AutomatedTesting/Levels/Navigation/NavigationSample/NavigationSample.prefab
- AutomatedTesting/Levels/Navigation/NavigationSample/click_to_move_player.scriptcanvas
- AutomatedTesting/Levels/Navigation/NavigationSample/set_navmesh_debug_radius.scriptcanvas
- Gems/RecastNavigation/Code/Include/RecastNavigation/RecastNavigationMeshBus.h
- Gems/RecastNavigation/Code/Include/RecastNavigation/RecastNavigationProviderBus.h
- Gems/RecastNavigation/Code/Source/Components/DetourNavigationComponent.cpp
- Gems/RecastNavigation/Code/Source/Components/RecastNavigationMeshComponent.cpp
- Gems/RecastNavigation/Code/Source/Components/RecastNavigationMeshComponent.h
- Gems/RecastNavigation/Code/Source/Components/RecastNavigationPhysXProviderComponent.cpp
- Gems/RecastNavigation/Code/Source/Components/RecastNavigationPhysXProviderComponent.h
- Gems/RecastNavigation/Code/Source/Misc/RecastHelpers.h
- Gems/RecastNavigation/Code/Source/Misc/RecastNavigationDebugDraw.cpp
- Gems/RecastNavigation/Code/Source/Misc/RecastNavigationDebugDraw.h
- Gems/RecastNavigation/Code/Source/Misc/RecastNavigationMeshCommon.cpp
- Gems/RecastNavigation/Code/Source/Misc/RecastNavigationMeshCommon.h
- Gems/RecastNavigation/Code/Source/Misc/RecastNavigationPhysXProviderCommon.cpp
- Gems/RecastNavigation/Code/Source/Misc/RecastNavigationPhysXProviderCommon.h
- Gems/RecastNavigation/Code/Tests/MockInterfaces.h
- Gems/RecastNavigation/Code/Tests/NavigationMeshTest.cpp
**Update: tested and confirmed on Linux and Windows.**
- added a new API UpdateNavigationMeshAsync
- added underlying structures to support threading within Navigation components
- unit tests for async scenarios
- updated NavigationSample level in AutomatedTesting project to use new async api
> Navigation gem - added async API to update navigation mesh

- AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Main_Optimized.py
- AutomatedTesting/Gem/PythonTests/editor/TestSuite_Main.py
Ticket to investigate Prefab Test Issues: https://github.com/o3de/o3de/issues/9789
Ticket to investigate Editor Test Issues: https://github.com/o3de/o3de/issues/9971
> Skipping Lua Spawnable and Editor Transform tests

- AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_02.py
- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_GridAdded.py
Adds a Grid component to a new entity and makes sure every single property type can have its value set.
**Test command:** `C:\git\o3de>C:\git\o3de\python\runtime\python-3.7.12-rev2-windows\python\python.exe -m pytest -vv -s --build-directory="C:\git\o3de\build\bin\profile" C:\git\o3de\AutomatedTesting\Gem\PythonTests\Atom\TestSuite_Main_Null_Render_Component_02.py -k AtomEditorComponents_GridAdded`
**Results:**
```
Starting test AtomEditorComponents_Grid_AddedToEntity...
Test AtomEditorComponents_Grid_AddedToEntity finished.
Report:
[SUCCESS] Success: Grid Entity successfully created
[SUCCESS] Success: Entity has a Grid component
[SUCCESS] Success: Grid Size value set successfully
[SUCCESS] …
```
> P1 Grid component null render test

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
> Material Component: temporarily reverting default material asset function to fix tests

- Gems/AtomTressFX/Assets/Shaders/HairComputeSrgs.azsli
- Gems/AtomTressFX/Assets/Shaders/HairFullScreenUtils.azsli
- Gems/AtomTressFX/Assets/Shaders/HairLightTypes.azsli
- Gems/AtomTressFX/Assets/Shaders/HairLighting.azsli
- Gems/AtomTressFX/Assets/Shaders/HairLightingEquations.azsli
- Gems/AtomTressFX/Assets/Shaders/HairRenderingFillPPLL.azsl
- Gems/AtomTressFX/Assets/Shaders/HairRenderingResolvePPLL.azsl
- Gems/AtomTressFX/Assets/Shaders/HairRenderingSrgs.azsli
- Gems/AtomTressFX/Assets/Shaders/HairShortCutGeometryDepthAlpha.azsl
- Gems/AtomTressFX/Assets/Shaders/HairShortCutGeometryShading.azsl
- Gems/AtomTressFX/Assets/Shaders/HairShortCutResolveColor.azsl
- Gems/AtomTressFX/Assets/Shaders/HairShortCutResolveDepth.azsl
- Gems/AtomTressFX/Assets/Shaders/HairSimulationCommon.azsli
- Gems/AtomTressFX/Assets/Shaders/HairSimulationCompute.azsl
- Gems/AtomTressFX/Assets/Shaders/HairSimulationComputeSrgs.azsli
- Gems/AtomTressFX/Assets/Shaders/HairStrands.azsli
- Gems/AtomTressFX/Assets/Shaders/HairUtilities.azsli
> Hair - changing the header MIT license to match O3DE

- Assets/Editor/Prefabs/Default_Level.prefab
Resolves #9516
Signed-off-by: prophetl33t 29117146+prophetl33t@users.noreply.github.com
> Add PhysX collider to the default level ground

- Code/Framework/AzCore/AzCore/Script/ScriptSystemComponent.cpp
Resolves #9921
Signed-off-by: prophetl33t <29117146+prophetl33t@users.noreply.github.com>
> Fix lua script with empty data crashing the engine

- Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/Device_Windows.cpp
Signed-off-by: Jeremy Ong <jcong@amazon.com>
> Remove enum references that are not defined in 10.0.19041.0

- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_batch_tests_2.py
Signed-off-by: Rosario Cox <lesaelr@amazon.com>
> Correcting a typo that caused a test to not be sandboxed correctly.

- Code/Editor/Core/LevelEditorMenuHandler.cpp
- Code/Editor/CryEdit.cpp
- Code/Editor/EditorToolsApplication.cpp
This is interesting when working in a team, when updating the level from a version control software.
> Editor: Allow to re-open the current level

- AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py
Temporarily disables test which has failed development 5 times in a row, plus multiple AR runs #10392
AR
> disable test to unblock development / AR

- Gems/MotionMatching/Code/Tests/MinMaxScalerTests.cpp
> Motion Matching: Additional min-max scaler tests

- Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.h
> [Terrain] Add notification and the ability to refresh clipmaps when editor data changes

- Gems/ScriptCanvas/Code/Editor/Assets/ScriptCanvasFileHandling.cpp
- Gems/ScriptCanvas/Code/Editor/Components/EditorUtils.cpp
- Gems/ScriptCanvas/Code/Editor/Components/GraphUpgrade.cpp
- Gems/ScriptCanvas/Code/Editor/Framework/Configuration.cpp
- Gems/ScriptCanvas/Code/Editor/Framework/ScriptCanvasGraphUtilities.inl
- Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorDeprecationData.cpp
- Gems/ScriptCanvas/Code/Editor/View/Widgets/GraphTabBar.cpp
- Gems/ScriptCanvas/Code/Editor/View/Widgets/SourceHandlePropertyAssetCtrl.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Controller.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Model.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Modifier.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Scanner.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/UpgradeHelper.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Core.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Core.h
Fixes Open In SC editor button on SC Editor Component
Changes name `SourceHandle::Path` to `SourceHandle::RelativePath`
Editor Testing
> Fix "open in SC editor button" on SC Component

- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/WindowContext.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Specific/SwapChainPass.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/WindowContext.cpp
Cleanup of how swapchain data is grouped and how it is managed in a more cohesive manner. 
Ran ASV full test suite and the Editor.
> Minor cleanup of how multiple swapchains are managed within WindowContext

- Code/Editor/ProcessInfo.cpp
add missing memory size from editor.
ref: https://github.com/o3de/o3de/issues/9879
open editor and verify memory size is present on the bottom right of the editor window.
> bugfix: correctly show memory usage in linux

- Gems/Terrain/Code/Source/TerrainRenderer/Passes/TerrainClipmapComputePass.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/Passes/TerrainClipmapComputePass.h
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.h
> [Terrain] Disable clipmap manager when clipmap is not enabled

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
Disable the terrain feature processor for animation editor.
Run automation and performed the repo steps in https://github.com/o3de/o3de/issues/10474
> Disable the terrain feature processor for anim editor

- Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/EditorModeFeedbackFeatureProcessor.cpp
> Fix unused variable

- Tools/LyTestTools/ly_test_tools/_internal/managers/artifact_manager.py
- Tools/LyTestTools/ly_test_tools/_internal/managers/ly_process_killer.py
- Tools/LyTestTools/ly_test_tools/_internal/managers/workspace.py
- Tools/LyTestTools/ly_test_tools/environment/file_system.py
- Tools/LyTestTools/ly_test_tools/environment/process_utils.py
- Tools/LyTestTools/ly_test_tools/environment/watchdog.py
- Tools/LyTestTools/ly_test_tools/launchers/platforms/base.py
- Tools/LyTestTools/ly_test_tools/log/log_monitor.py
- Tools/LyTestTools/ly_test_tools/o3de/asset_processor.py
- Tools/LyTestTools/ly_test_tools/o3de/settings.py
- Tools/LyTestTools/tests/unit/test_file_system.py
- cmake/LYTestWrappers.cmake
Changes CTest to run pytest with stdout level logging instead of log level logging. Also change non critical functions to use debug logging instead of info level.
Ran CTest locally and observed logging
> Changes CTest pytest stdout logging and LyTestTools logging improvements

- Tools/LyTestTools/ly_test_tools/launchers/exceptions.py
- Tools/LyTestTools/ly_test_tools/launchers/platforms/base.py
- Tools/LyTestTools/ly_test_tools/o3de/asset_processor.py
Timeout messages were extended with additional explanatory text. Given that only logging messages were changed I'm going to rely on AR to verify functionality.
> Detailed timeout messages.

- Gems/MotionMatching/Code/Source/CsvSerializers.cpp
- Gems/MotionMatching/Code/Source/CsvSerializers.h
- Gems/MotionMatching/Code/Source/FeatureAngularVelocity.cpp
- Gems/MotionMatching/Code/Source/FeatureMatrix.cpp
- Gems/MotionMatching/Code/Source/FeatureSchema.cpp
- Gems/MotionMatching/Code/Source/FeatureSchema.h
- Gems/MotionMatching/Code/motionmatching_files.cmake
CSV exporters for skeletal poses, motion matching query vectors and best matching frames
> Motion Matching: .CSV serializers for skeletal poses, query vectors and best matching frames

- scripts/o3de/o3de/download.py
> Fix registering projects and templates after downloading

- Code/Tools/AssetProcessor/native/resourcecompiler/rcjob.cpp
The error message when product sub IDs collided only listed one file path, this updates the message to list both paths in the collision, to make errors easier to debug.
We had a test FBX file that triggered this error (see https://github.com/o3de/o3de/issues/10720), and this change was used to help debug.
Without this change, we were only seeing the filename of one of the two colliding asset IDs in the output. It was difficult for us to trace this to what was actually colliding, and where to debug. The scene building Gem has many different systems generating product assets, with sub ID logic spread throughout these. So, if the collision was between the sub ID of an azmodel and a physics mesh, that would be a …
> Added second filename for product sub ID collisions

- Gems/Terrain/Assets/Passes/TerrainDebugPassRequest.azasset
- Gems/Terrain/Assets/Passes/TerrainParentPass.pass
- Gems/Terrain/Assets/Passes/TerrainPassRequest.azasset
- Gems/Terrain/Code/Source/Components/TerrainWorldRendererComponent.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/Passes/TerrainClipmapComputePass.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/Passes/TerrainClipmapComputePass.h
- Gems/Terrain/Code/Source/TerrainRenderer/Passes/TerrainClipmapDebugPass.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.h
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
- Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.h
Added a checkbox to turn on clipmap at runtime in the editor.
Tested in Terrain 1k level by turn it on and off for several times.
> [Terrain]Add a checkbox to turn on clipmap

- Tools/LyTestTools/ly_test_tools/_internal/managers/abstract_resource_locator.py
- Tools/LyTestTools/ly_test_tools/_internal/managers/artifact_manager.py
- Tools/LyTestTools/ly_test_tools/_internal/pytest_plugin/terminal_report.py
- Tools/LyTestTools/ly_test_tools/_internal/pytest_plugin/test_tools_fixtures.py
- Tools/LyTestTools/ly_test_tools/builtin/helpers.py
- Tools/LyTestTools/ly_test_tools/launchers/platforms/base.py
- Tools/LyTestTools/ly_test_tools/o3de/settings.py
- Tools/LyTestTools/tests/unit/test_abstract_resource_locator.py
- Tools/LyTestTools/tests/unit/test_artifact_manager.py
- Tools/LyTestTools/tests/unit/test_builtin_helpers.py
- Tools/LyTestTools/tests/unit/test_fixtures.py
- Tools/LyTestTools/tests/unit/test_terminal_report.py
Removes unused/deprecated code from LTT. Improves quality of unit tests. Minor improvements to rerun command formatting.
Locally ran smoke and main test suite.
> Improved quality of LTT unit tests and some code structure

- Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
- Code/Tools/AssetProcessor/native/ui/MainWindow.h
Fix minor spelling mistake with Assetprocessor/native/ui/MainWindow
> chore: fix spelling mistake FirstTimeAddedToRejectedList

- Code/Framework/AzCore/AzCore/std/azstd_files.cmake
- Code/Framework/AzCore/AzCore/std/ranges/filter_view.h
- Code/Framework/AzCore/AzCore/std/ranges/reverse_view.h
- Code/Framework/AzCore/Tests/AZStd/RangesViewTests.cpp
Add support for the C++20 ranges::filter_view
Also added support for the C++20 ranges::reverse_view
Added unit test to validate the filter_view and reverse_view functionality
> Adding implementation of C++20 ranges::filter_view

- Tools/LyTestTools/ly_test_tools/launchers/platforms/base.py
- Tools/LyTestTools/ly_test_tools/o3de/asset_processor.py
- Tools/LyTestTools/ly_test_tools/o3de/asset_processor_config_util.py
- Tools/LyTestTools/ly_test_tools/o3de/asset_processor_utils.py
Improves exception messaging and code clean up in LyTestTools AssetProcessor files. Removes redundant or unused functions as well.
Ran smoke and main test suites locally
> Improves LTT AP files messaging

- LICENSE.txt
Updates the references for 3P licenses to point to the https://github.com/o3de/3p-package-source repo
Not tested as it is a non-code change
> Update license references

- Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_Vector2Functions_SetX.names
- Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_Vector2Functions_SetY.names
- Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_Vector3Functions_SetX.names
- Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_Vector3Functions_SetY.names
- Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_Vector3Functions_SetZ.names
- Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_Vector4Functions_SetW.names
- Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_Vector4Functions_SetX.names
- Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_Vector4Functions_SetY.names
- Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_Vector4Functions_SetZ.names
Addresses some grammatical errors in the Math/Vector ScriptCanvas nodes
Closes #10713 
Reopened the ScriptCanvas editor after making changes and reviewed tooltips for correctness
> Fixed grammatical errors

- scripts/build/Jenkins/Jenkinsfile
Pass full pipeline name to post AR build SNS topic.
> Pass full pipeline name to post AR build SNS topic

- Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja
- Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
Fixes https://github.com/o3de/o3de/issues/11156
Added a repro case to o3de-multiplayersample and confirmed that the project compiles.
> Corrected codegen for rewindable array network properties

- Code/Framework/AzCore/AzCore/Interface/Interface.h
- When static AZ::Names were getting the NameDictionary interface before
the interface static had been initialized, it cause future calls to
Get() to go into the fast read path and return nullptr.
- Protect the AZ::EnvironmentVariable<T*> static by wrapping it in an
accessor function.  This helps ensure that the static environment
variable is initialized/constructed once on first access.
fixes #11125 
Ran AutomatedTesting.GameLauncher in Debug, no startup exceptions in `AZ::Interface<AZ::NameDictionary>` anymore.
Ran AzCore.Tests
> Fixes an issue with AZ::Interface<T>::Get()

- Gems/Atom/RHI/Vulkan/3rdParty/Findglad_vulkan.cmake
Build Atom on Linux and Android
> Updated the glad_vulkan to portability reference the Atom RHI vulkan gem

- Gems/ScriptCanvas/Assets/TranslationAssets/Nodes/Multiply_E9BB45A1-AE96-47B0-B2BF-2927D420A28C.names
- Gems/ScriptCanvas/Assets/TranslationAssets/Nodes/Subtract_D0615D0A-027F-47F6-A02B-E35DAF22F431.names
Fixed minor typos in Script Canvas math nodes
Verified visually that tooltip was correct
Closes #10713
> Fixed typos in Script Canvas math nodes

- Tools/LyTestTools/ly_test_tools/environment/file_system.py
- Tools/LyTestTools/tests/unit/test_file_system.py
This is an audit of the file system tests. Redundant/pointless tests were removed and new edge cases were covered.
Ran locally. All unit tests passed.
> Audited file system tests.

- Gems/EMotionFX/Code/Tests/AnimGraphStateMachineInterruptionTests.cpp
When builing the AnimGraphStateMachineInterruptionTests.cpp in debug
configuration using the MSVC v143 toolset, the `EXPECT_EQ` calls fail to
compile when both parameters are bools.
Instead of using EXPECT_EQ for the comparison of booleans, EXPECT_THAT
is used instead and that avoids the compiler issue.
Below is the compiler issue
```
1>------ Build started: Project: EMotionFX.Tests, Configuration: debug
x64 ------
1>AnimGraphStateMachineInterruptionTests.cpp
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(171,25):
error C2039: 'Compare': is not a member of 'testing::internal'
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(171,25):
error C2039:                         EXPECT_EQ(activeObjects.m_stateA, …
```
> Workaround VS2022 compiler issue in Debug configuration

- Code/Framework/AzCore/Tests/Asset/AssetManagerLoadingTests.cpp
Add some debug output for 2 unit tests to help diagnose cause of timeout occurring on AR runs
Ran unit test
> Asset Manager - Add some debug output for 2 unit tests to help diagnose cause of timeout

- Gems/MotionMatching/Code/Source/CsvSerializers.cpp
- Gems/MotionMatching/Code/Source/FeatureAngularVelocity.cpp
- Gems/MotionMatching/Code/Source/FeatureMatrix.cpp
- Gems/MotionMatching/Code/Source/FeatureMatrix.h
- Gems/MotionMatching/Code/Source/FeaturePosition.cpp
- Gems/MotionMatching/Code/Source/FeatureTrajectory.cpp
- Gems/MotionMatching/Code/Source/FeatureVelocity.cpp
- Gems/MotionMatching/Code/Source/FrameDatabase.cpp
- Gems/MotionMatching/Code/Source/FrameDatabase.h
- Gems/MotionMatching/JupyterNotebooks/LearnedMotionMatching.ipynb
* Added CSV export for the frame database
* Added Jupyter Notebook for inspecting the exported data
> Motion Matching: Added CSV exporter for the frame database

- Code/Editor/EditorViewportWidget.cpp
- Code/Editor/EditorViewportWidget.h
Quick fix for the issue @hultonha found on the PR #11052.
Please note I couldn't test it and won't have the time to do so until thuesday, but it should be good
> Quick fix for #11052

- Gems/MotionMatching/Code/Source/CsvSerializers.cpp
- Gems/MotionMatching/Code/Source/CsvSerializers.h
- Gems/MotionMatching/Code/Source/FrameDatabase.cpp
- Gems/MotionMatching/Code/Source/FrameDatabase.h
> Motion Matching: Added transform space option for csv serializer

- Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/TestEngine/Common/TestImpactTestEngine.h
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Source/TestImpactClientSequenceReportSerializer.cpp
fixes #11228
Built TestImpactFramework folder using VS2022
> TestImpactFramework VS2022 build fixes

- Code/Editor/Core/QtEditorApplication.cpp
- Code/Editor/LogFile.cpp
- Code/Editor/LogFile.h
- Code/Framework/AzCore/AzCore/Debug/Trace.h
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryConsoleUtils.cpp
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryOriginTracker.h
- Code/Framework/AzCore/Platform/Android/AzCore/Debug/Trace_Android.cpp
- Code/Framework/AzCore/Platform/Common/Apple/AzCore/Debug/Trace_Apple.cpp
- Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/Debug/Trace_WinAPI.cpp
- Code/Framework/AzCore/Platform/Linux/AzCore/Debug/Trace_Linux.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Gallery/main.cpp
- Code/Framework/AzTest/AzTest/Platform/Windows/Platform_Windows.cpp
- Code/Legacy/CryCommon/IConsole.h
- Code/Legacy/CryCommon/ILog.h
- Code/Legacy/CryCommon/IMiniLog.h
- Code/Legacy/CryCommon/ISystem.h
- Code/Legacy/CryCommon/Mocks/IConsoleMock.h
- Code/Legacy/CrySystem/AZCoreLogSink.h
- Code/Legacy/CrySystem/Log.cpp
- Code/Legacy/CrySystem/Log.h
- Code/Legacy/CrySystem/RemoteConsole/RemoteConsole.h
- Code/Legacy/CrySystem/RemoteConsole/RemoteConsole_impl.inl
- Code/Legacy/CrySystem/XConsole.cpp
- Code/Legacy/CrySystem/XConsole.h
- Code/Tools/RemoteConsole/Core/RemoteConsoleCore.h
- Gems/EMotionFX/Code/Tests/AnimGraphCopyPasteTests.cpp
The Cry console code only supported outputting a message up to 4096 + 32 characters in a single call.
A new CryOutput function has been added to allow a message of up to a theoretical size of (2^-64-1) to be output.
Updated the Trace `OutputToDebugger` for Android and Windows to more than 4096 characters in a single to the android logcat window and the windows debugger output window in a single call.
Verified using the `sr_dump_origin ""` command which outputs more than 4096 characters when dumping the origins of the entire settings registry.
```
sr_dump_origin
[CONSOLE] Executing console command 'sr_dump_origin'
(SettingsRegistry) - Key: "" Origin: "<in-memory>" Value when Merged: <object> …
```
> Allows Console Window to output more than 4K at a time

- Gems/ScriptCanvas/Code/Editor/View/Widgets/VariablePanel/GraphVariablesTableView.cpp
As requested in https://github.com/o3de/o3de/issues/11339
Verified in ScriptCanvas Editor, make sure graph variable is working
> Add support to sort graph variable in scriptcanvas

- Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Headers/TestImpactFramework/TestImpactClientSequenceReport.h
This PR fixes the result of a broken merge.
> Fix broken merge in report serializer.

- Code/Tools/ProjectManager/Source/AddRemoteProjectDialog.cpp
- Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
- Code/Tools/ProjectManager/Source/ProjectsScreen.h
- Code/Tools/ProjectManager/Source/PythonBindings.cpp
- Code/Tools/ProjectManager/Source/PythonBindings.h
- Code/Tools/ProjectManager/Source/PythonBindingsInterface.h
Also use validation function now that the dependent PR has been merged
> Removing the remote project dialog flag now everything is in place

- Tools/LyTestTools/ly_test_tools/_internal/pytest_plugin/failed_test_rerun_command.py
- Tools/LyTestTools/ly_test_tools/_internal/pytest_plugin/terminal_report.py
- Tools/LyTestTools/tests/unit/test_failed_rerun_command.py
- Tools/LyTestTools/tests/unit/test_terminal_report.py
Adds all args to the pytest retry command.
Tested locally by running failed tests via ctest, pytest, and pycharm. Ran unit tests locally
> Added all args to pytest retry command

- Code/Tools/ProjectManager/Source/CreateProjectCtrl.cpp
- Code/Tools/ProjectManager/Source/EngineScreenCtrl.cpp
- Code/Tools/ProjectManager/Source/GemsGemRepoScreen.cpp
- Code/Tools/ProjectManager/Source/UpdateProjectCtrl.cpp
> Rename Gem Repositories to its new name

- scripts/build/build_failure_rca/rca_patterns/Cmake.json
Update cmake build failure RCA pattern
> Update cmake build failure RCA pattern

- Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugSystemComponent.cpp
> Minor Code Spelling Fix in Multiplayer ImGui Code 

- Code/Tools/AssetProcessor/native/utilities/GUIApplicationManager.cpp
Fixes bug #11542 
Checked with testbed and works correctly.
> Fix for EnableSource always true

- Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
Minor change rejecting dynamic property groups that don’t contain any properties.
Also added several comments to the material document open function.
https://github.com/o3de/o3de/issues/7983
Drastic changes as recorded in the original issue, opening the eye material type before and after the changes to confirm that the empty groups no longer appeared.
> Material Editor: Ignoring empty property groups in document and inspector

- Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/JointLimitOptimizer.cpp
replaces console warnings for joint limit optimizer with toast messages
manual testing in animation editor
> replace console warnings for joint limit optimizer with toast messages

- Code/Framework/AzCore/Tests/DOM/DomPrefixTreeBenchmarks.cpp
- Code/Framework/AzCore/Tests/StatisticalProfilerBenchmarks.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/Propagation/PropagationBenchmarkFixture.cpp
- Gems/AWSCore/Code/Tests/Editor/UI/AWSCoreEditorMenuTest.cpp
- Gems/Atom/RHI/Code/Tests/AllocatorTests.cpp
- Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/Device_Windows.cpp
- Gems/Atom/RHI/DX12/Code/Source/RHI/PipelineLayout.cpp
It fixes the windows clang build
By building with clang on Windows
> Fix windows clang build

- scripts/build/build_node/Platform/Linux/install-ubuntu-build-tools.sh
- scripts/build/build_node/Platform/Linux/install-ubuntu-git.sh
- scripts/build/build_node/Platform/Linux/package-list.ubuntu-jammy.txt
Adds setup logic for Ubuntu 22.04 build nodes
Execute setup-ubuntu.sh on a fresh ubuntu 22.04 machine
> Updates to add Ubuntu 22.04 (jammy) build node setup scripts

- Gems/Multiplayer/Code/Include/Multiplayer/Components/MultiplayerController.h
- Gems/Multiplayer/Code/Source/Components/LocalPredictionPlayerInputComponent.cpp
- Gems/Multiplayer/Code/Source/Components/MultiplayerController.cpp
- Gems/Multiplayer/Code/Source/Components/NetworkCharacterComponent.cpp
- Gems/Multiplayer/Code/Source/Components/NetworkRigidBodyComponent.cpp
- Gems/RemoteTools/Code/Source/RemoteToolsSystemComponent.cpp
Renames IsAuthority/IsAutonomous in Multiplayer to IsNetworkRoleAuthority/IsNetworkRoleAutonomous. Also adds a safety check in RemoteTools.
Built MPS
> Rename IsAuth/IsAuto to IsNetEntityRoleAuth/Auto

- Gems/WhiteBox/Code/Source/EditorWhiteBoxComponentMode.cpp
- Gems/WhiteBox/Code/Source/SubComponentModes/EditorWhiteBoxDefaultMode.cpp
- Gems/WhiteBox/Code/Source/SubComponentModes/EditorWhiteBoxEdgeRestoreMode.cpp
- Gems/WhiteBox/Code/Source/Viewport/WhiteBoxEdgeScaleModifier.cpp
- Gems/WhiteBox/Code/Source/Viewport/WhiteBoxEdgeTranslationModifier.cpp
- Gems/WhiteBox/Code/Source/Viewport/WhiteBoxEdgeTranslationModifier.h
- Gems/WhiteBox/Code/Source/Viewport/WhiteBoxPolygonScaleModifier.cpp
- Gems/WhiteBox/Code/Source/Viewport/WhiteBoxPolygonTranslationModifier.h
- Gems/WhiteBox/Code/Source/Viewport/WhiteBoxVertexTranslationModifier.h
- Gems/WhiteBox/Code/Source/Viewport/WhiteBoxViewportConstants.cpp
- Gems/WhiteBox/Code/Source/Viewport/WhiteBoxViewportConstants.h
This just updates the CVAR based on the functionality of the color. I think this is a lot more maintainable. 
some of the color are slightly different.
> chore(WhiteBox): update cvar constants based on functionality

- Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.ui
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowser.ui
Cherry picks the fix for #11593 from development into Stabilization as requested.
#11593
Tested in development.
> Cherry picked Fix for DoubleClicking in Asset Browser

- Tools/LyTestTools/ly_test_tools/_internal/exceptions.py
- Tools/LyTestTools/ly_test_tools/_internal/managers/abstract_resource_locator.py
- Tools/LyTestTools/ly_test_tools/mobile/android.py
- Tools/LyTestTools/ly_test_tools/o3de/ap_log_parser.py
- Tools/LyTestTools/ly_test_tools/o3de/asset_processor.py
- Tools/LyTestTools/ly_test_tools/o3de/editor_test_utils.py
- Tools/LyTestTools/ly_test_tools/o3de/multi_test_framework.py
- Tools/LyTestTools/ly_test_tools/o3de/pipeline_utils.py
- Tools/LyTestTools/ly_test_tools/o3de/settings.py
- Tools/LyTestTools/tests/unit/test_abstract_resource_locator.py
- Tools/LyTestTools/tests/unit/test_builtin_helpers.py
Adds typed exceptions to LyTT and EditorTest to clarify where exceptions are coming from.
Tested locally and on AR.
> Added typed exceptions to LyTT.

- Code/Tools/SceneAPI/SDKWrapper/AssImpMaterialWrapper.cpp
- Code/Tools/SceneAPI/SceneBuilder/Importers/AssImpMaterialImporter.cpp
Added material name.
Changes a warning message to a log message, and adds details.
Manually
> Downgraded default material settings from warning to log.

- scripts/build/build_failure_rca/rca_patterns/Asset-Processing.json
Merge build failure RCA pattern fix from development to stabilization branch
Tested in development branch
> Fix rca patterns in stabilization branch

- Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/FocusedEntityState.cpp
Fixes https://github.com/o3de/o3de/issues/11186
> Fix for GHI11186

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
Fix GHI https://github.com/o3de/o3de/issues/11741
> Fix Crash on Esc out of Prefab Edit Mode with nested prefabs

- Code/Editor/Plugins/EditorAssetImporter/ImporterRootDisplay.cpp
Updates the title text to be regular size on the Scene Settings UI
Manual testing + visual verification
> Fixed bolding & size of title text on scene settings UI

- Gems/ScriptCanvas/Code/Editor/View/Dialogs/ContainerWizard/ContainerWizard.cpp
- Gems/ScriptCanvas/Code/Editor/View/Widgets/VariablePanel/VariablePaletteTableView.cpp
add frame to container wizard.
- create variable in script canvas
- select a container type "map, set, array"
> bugfix: add frame to ContainerWizard

- Gems/Multiplayer/Code/Include/Multiplayer/Components/MultiplayerController.h
- Gems/Multiplayer/Code/Source/Components/LocalPredictionPlayerInputComponent.cpp
- Gems/Multiplayer/Code/Source/Components/MultiplayerController.cpp
- Gems/Multiplayer/Code/Source/Components/NetworkCharacterComponent.cpp
- Gems/Multiplayer/Code/Source/Components/NetworkRigidBodyComponent.cpp
- Gems/Multiplayer/Code/Source/NetworkEntity/EntityReplication/EntityReplicationManager.cpp
- Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp
- Gems/RemoteTools/Code/Source/RemoteToolsSystemComponent.cpp
Ports the following changes from development to stabilization/2210.
https://github.com/o3de/o3de/pull/11668
https://github.com/o3de/o3de/pull/11755
These changes include API clarity changes, a high priority bug fix and some low impact cleanup.
Original PRs were tested in development as isolated fixes.
> Port priority Multiplayer fixes from dev to stabilization/2210

- Code/Tools/SceneAPI/SceneUI/CommonWidgets/SceneSettingsCard.h
> Added missing includes causing non-uber builds to fail

- Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp
Fix for https://github.com/o3de/o3de/issues/11924
Manually tested in Editor.
> Add mesh handle state notification upon atom actor instance release.

- cmake/Tools/Platform/Android/android_support.py
- cmake/Tools/Platform/Android/unit_test_generate_android_project.py
* Fixes the Android Unit tests failures on Linux
* Fixes a file casing issue with the Android toolchain file
Ran unit test for Android scripts on Linux
Generated and deployed AutomatedTesting project to an Android device
> Fixes for Android Project scripts on Linux

- AutomatedTesting/Assets/TestAnim/scene_export_actor.py
- AutomatedTesting/Assets/TestAnim/scene_export_motion.py
- AutomatedTesting/Assets/ap_test_assets/script_reinsert.py
- AutomatedTesting/Editor/Scripts/auto_lod.py
- AutomatedTesting/Editor/Scripts/scene_mesh_to_prefab.py
- AutomatedTesting/Gem/PythonTests/PythonAssetBuilder/export_chunks_builder.py
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoSceneFiles_OneWithPythonOneWithout_PythonOnlyRunsOnFirstScene/python_builder.py
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/script_basics/base_example.py
- AutomatedTesting/TestAssets/test_chunks_builder.py
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.cpp
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryImpl.h
- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiManager.cpp
- Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingResourceList.h
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRenderer.cpp
- Gems/Blast/Editor/Scripts/blast_chunk_processor.py
These would eventually cause random crashes.  They were detected by switching AzCore SystemAllocator to use the OS malloc and free instead of pooling, so that all allocations would go directly to the operating system, and then using the Microsoft Debug CRT heap corruption detection features in debug builds.   Several use-after-free bugs were immediately found.  Note that this change only fixes the memory corruption bugs found, it does not modify the SystemAllocator or switch debug features on, itself.
The specific errors are as follows:
- Python files:  Deleting an event handler while inside the event handler invalidates the 'this' pointer which is then subsequently used.
- Settings Registry:  Mutating the settings registry while iterating over it in a visitor pattern.  The iterators are …
> Fixes several memory/heap corruption bugs

- AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
- AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MeshAdded.py
- Code/Tools/SceneAPI/SceneCore/Containers/Utilities/SceneGraphUtilities.cpp
- Code/Tools/SceneAPI/SceneCore/Containers/Utilities/SceneGraphUtilities.h
- Code/Tools/SceneAPI/SceneCore/DataTypes/Rules/IClothRule.h
- Code/Tools/SceneAPI/SceneCore/Utilities/SceneGraphSelector.cpp
- Code/Tools/SceneAPI/SceneCore/Utilities/SceneGraphSelector.h
- Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.cpp
- Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.h
- Gems/Atom/TestData/TestData/Objects/SkinnedMesh/MeshOptimization/sameposition_differentjointids_shouldnotweldvertices.fbx
- Gems/NvCloth/Code/Source/Pipeline/SceneAPIExt/ClothRule.cpp
- Gems/SceneProcessing/Code/Source/Generation/Components/MeshOptimizer/MeshOptimizerComponent.cpp
- Registry/sceneassetimporter.setreg
This PR cherry-picks commit fcdb2c36fdd90cb8447cbe2da2df694e33733955 and commit 0d2ef3018a8e2a03fd4c705904d73fd2d92f6afc from development to stabilization. These are bug fixes for GHI-7588 and GHI-9598. These were originally reviewed in https://github.com/o3de/o3de/pull/11082 and https://github.com/o3de/o3de/pull/10096
Built and ran the editor locally. Vertex welding is functioning again, new vertex welding hydra test passes, and assets that previously failed to process due to mesh merging issues now process correctly.
> Merge GHI-7588 and GHI-9598 from development to stabalization

- AutomatedTesting/Objects/bunny.fbx
Adds back a file to development I deleted in error.
Just checked file is now back.
> Added back file deleted in error

- Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableEntitiesInterface.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasNodeable_Source.jinja
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/CreateSpawnTicketNodeable.ScriptCanvasNodeable.xml
Change has already been reviewed in PR https://github.com/o3de/o3de/pull/12014
Just cherry pick into stab branch
> Merge short term fix from development for prefab assignment in node inspector

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
When dragging a container entity inside a focused prefab, we need to treat its owning instance as the parent instance. 
> Fix not being able to move nested instance within owning focused prefab

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
Merges stabilization commits up to 1164e464792 into o3de development.
AR will be built.
> Stabilization 2210 Merge to Development 2022.09.22

- scripts/build/Jenkins/Jenkinsfile
Add a pointer in the stabilization/2210 branch
Tested in sandbox Jenkins
> Add stabilization snapshot

- Code/Tools/SceneAPI/SceneCore/Events/AssetImportRequest.cpp
This fixes a stack overflow issue that might happen when serializing the scene manifest to a JSON doc when the "Debug Output" flag is set to true.
Manually reprocessed the AutomatedTesting/Assets/** assets which used to cause a stack overflow.
> {lyn15166} fixes a stack overflow issue with debug scene manifest

- Code/Tools/SceneAPI/SceneCore/Events/AssetImportRequest.cpp
Mac compile fix for debug output feature
The Mac build does not have have this compile error now.
> {lyn15166} Mac compile fix for debug output feature

- pytest.ini
- python/requirements.txt
Fixes issue https://github.com/o3de/o3de/issues/12073 
Followed repro steps for issue
> Add necessary python modules in package to satisfy pytest

- Code/Framework/AzCore/AzCore/std/string/fixed_string.inl
- Code/Framework/AzCore/AzCore/std/string/string.h
Compiled the following code without error
```c++
constexpr auto jsonCompleteString = []()
{
auto result = AZStd::fixed_string<2>("\n");
result += "]";
return result;
}();
```
> Fix assert in string/fixed_string append asserts

- Code/Framework/AzCore/AzCore/Serialization/Json/JsonImporter.cpp
> Adding support to replace a filesystem @alias@ in the JsonImporter

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Graph.cpp
Fix scriptcanvas node replacement connection drop issue.
Before rebuilding all connections, system will remove all existing ones. But existing implementation doesn't clean up connection metadata properly, connection endpoints data are still stored in `m_graphData.m_endpointMap` which causes connection can not be rebuilt correctly.
Solution is to use existing `RemoveConnection` function for proper cleanup.
Tested with problem graph.
> Fix scriptcanvas replacement connection drop issue

- Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Handlers/EntityBus.names
Added name to event slot on "On Entity Activated" and "On Entity Deactivated"
Closes #9625
> Added a label on exit slot of On Entity Activated and Deactivated

- Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/ComboBoxNodePropertyDisplay.cpp
- Gems/GraphCanvas/Code/Source/Widgets/GraphCanvasComboBox.cpp
- Gems/GraphCanvas/Code/Source/Widgets/GraphCanvasComboBox.h
this removes some unused code and  cleans up the existing code.
> chore(Graph Canvas): cleanup up GraphCanvasComboBox

- Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbNativeWindow.cpp
Fix a gpu crash by ensuring we recreate the swapchain and swapchain images after modifying the surface.
Run ASV full test suite
> Fix gpu crash within Full test suite

- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/GraphCanvasGraphicsView/GraphCanvasGraphicsView.cpp
- Gems/LyShine/Code/Editor/Animation/UiAnimViewSequence.cpp
- Gems/LyShine/Code/Include/LyShine/Animation/IUiAnimation.h
- Gems/LyShine/Code/Source/Animation/AnimSplineTrack_Vec2Specialization.h
- Gems/LyShine/Code/Source/Animation/AnimTrack.h
Built the INSTALL target using VS2022 17.4.0 Preview 3
> VS2022 17.4.0 Preview3 fixes

- Code/Framework/AzFramework/Platform/Mac/AzFramework/Windowing/NativeWindow_Mac.mm
This change was missed from:
https://github.com/o3de/o3de/pull/12552
@moudgils has helped building Mac.
> Fix mac build error

- AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Main.py
- AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Periodic.py
- Promoted all tests from the Periodic suite that have consistently passed in Nightly builds to the Main suite
- Re-organized tests in the Main suite to match order of test files in tests directory
Ran updated Main and Periodic suites locally with no issues.
> Promoting several Periodic tests to Main suite

- AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/consts/scripting.py
- AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/QtPyScriptCanvasNodePalette.py
- AutomatedTesting/Gem/PythonTests/scripting/NodePalette_HappyPath_ClearSelection.py
Signed-off-by: Michael <michleza@amazon.com>
updated test script to use QtPy framework
updated QtPy NodePalette class to include a clear button function 
added a constant to the scripting constants file
pytest via CLI
python console via O3DE editor
> Migrated NodePalette_HappyPath_ClearSelection to QtPy

- AutomatedTesting/Gem/PythonTests/Prefab/tests/instantiate_prefab/InstantiatePrefab_LevelPrefab.py
- Updates the file path to test prefab with correct casing for Linux platform
- Ran updated Periodic suite locally without issue
> Fixing casing with prefab file path for Linux

- Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.cpp
> Check for valid unbounded array address in DispatchRays

- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
Keeps main window from closing an application from shutting down if request to save modified files is cancelled while closing the main window.
Also adds clean up for views added to the document tabbed window.
Resolves https://github.com/o3de/o3de/issues/12495
Verified that application and main window stay open if save on shut down is cancelled.
> Atom Tools: Stop application from shutting down if user cancels saving modified files

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionExtractionWindow.cpp
Added multi select options for root motion extraction options.
https://user-images.githubusercontent.com/69218254/197111746-08f590df-ede9-4cfb-9923-b3de31cc7081.mp4
med._
> EMFX: Allow multi edit on root motion extractions

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
Fix for warnings that are being treated as errors by converting unsigned ints to int
Locally
> Int Conversion Error

- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Functions/clamp.materialcanvasnode
fixes a config file typo
Confirmed that no errors were reported to the file and that it loaded correctly by creating that node type
> Material canvas: fixing typo in clamp node config

- Gems/LmbrCentral/Code/Tests/ShapeTestUtils.cpp
- Gems/LmbrCentral/Code/include/LmbrCentral/Shape/ShapeComponentBus.h
A couple of small followup items from #12763 
Ran LmbrCentral unit tests.
> apply feedback from PR #12763

- Tools/LyTestTools/ly_test_tools/o3de/multi_test_framework.py
- Tools/LyTestTools/tests/unit/test_o3de_multi_test_framework.py
Signed-off-by: Chiang <evanchia@amazon.com>
Moves some MultiTest framework functionality into shared functions to make it easier to maintain. Adds new unit tests
Ran smoke and main test suite locally.
> Adds shared functions for MultiTest framework

- Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
> Fix compile error that toolId was unused

- Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Controller.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Scanner.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/View.ui
See details in reported GHI https://github.com/o3de/o3de/issues/13009
[Extra] Fix scan progress bar not showing up.
Tested in Editor, and upgrade tool shows correctly
> Fix upgrade tool extra row issue

- Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp
The GameLauncher now starts at the screen resolution
and fullscreen mode as specified in the command line via the CVARs: r_width, r_height, r_fullscreen.
REMARK: It was found that Atom's BootstrapSystemComponent::Activate() is called BEFORE Legacy/System.cpp::ExecuteCommandLine(), the solution for now is to our own command line parsing for the required CVARs.
Validated that AutomatedTesting.GameLauncher starts at the request screen resolution specified by --r_width and --r_height when given in the command line arguments.
Also made sure it enters fullscreen mode if --r_fullscreen=true
> The GameLauncher now starts at the screen resolution

- Code/Tools/AssetBundler/source/utils/applicationManager.cpp
Cleaned up help message for asset bundler batch. Instead of strings for these values is old and not necessary, so this makes it cleaner and more obvious you should use the text.
tested locally, manually. verified help message printed as expected
> Cleaned up help message for asset bundler batch

- Gems/PhysX/Code/Source/EditorRigidBodyComponent.cpp
- Gems/PhysX/Code/Tests/RigidBodyComponentTests.cpp
> Fixed PhysX Editor unit tests

- Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/LocalViewBookmarkLoader.cpp
This PR makes a small change in LocalViewBookmarkComponent to only mark the entity dirty if it has actually changed. This prevents unnecessary undo command creation.
> Mark LocalViewBookmarkComponent entity dirty only when changed

- Gems/AudioEngineWwise/Code/Source/AudioEngineWwiseGemSystemComponent.cpp
- Gems/AudioEngineWwise/Code/Tests/AudioEngineWwiseTest.cpp
- Gems/AudioSystem/Code/Source/AudioSystemGemSystemComponent.cpp
- Removed structs and functions that are no longer needed.
fixes #13229, #13259
Built and ran audio unit tests.
> Fix Wwise gem allocators

- AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/editor_component/editor_component_validation.py
- AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/editor_component/editor_physx_collider.py
- AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/editor_component/test_values/phsyx_collider_test_values.py
- AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/editor_entity_utils.py
- AutomatedTesting/Gem/PythonTests/Physics/tests/EntityComponentTests/PhysX_Collider_Component_CRUD.py
Signed-off-by: FuzzyCarterAWS <jscar@amazon.com>
This PR updates code feedback that was mistakenly not pushed up before #11240 was validated and merged.
Validated that tests still passed
> Updating code based upon feedback and replacing TODOs with GHIs.

- Code/Framework/AzCore/AzCore/Component/ComponentApplication.cpp
Also added support for controlling the cration of the core_metrics.\*.json file via a setting key.
The boolean setting of "/O3DE/Metrics/Core/CreateLogger" controls the creation of the Core Metrics logger.
If the settings is missing the Core Metrics Logger will be created by default in non-release builds and not created in release builds..
Validated that running the AssetProcessor and AssetBuilder applications did not create in a `core_metrics.*.json` files.
As those applications don't tick, the core_metrics event logger instance is created from them.
> Defer creation of the Core Metrics Logger until first game tick

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetsWindowPlugin.cpp
This one makes more sense.
Fixes #13272
Changes one label as requested on review
Manually
> Change label in motion sets editor

- AutomatedTesting/Registry/material_pipelines.setreg
- Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialTypeBuilder.cpp
- Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialTypeBuilder.h
Enabled the material pipeline for the Automated Testing project, so any asset build failures will be caught.
Ran the AP with the automated testing project and saw successful building of the MaterialPipelineTest assets.
The real test is whether this will pass Automated Review, as that's what was failing before...
> Enabled the material pipeline for the Automated Testing project

- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/ComponentModeSwitcher.cpp
- Code/Framework/AzToolsFramework/Tests/ComponentModeSwitcherTests.cpp
Signed-off-by: amzn-ahmadkrm <ahmadkrm@amazon.com>
Fixes https://github.com/o3de/o3de/issues/13327
The problem was that the switcher duplicated the active component mode icon when it was in component mode and the user carried out a component editing action then pressed undo. On Undo, all the components disconnect from the component mode delegate and reconnect. This switcher uses this notification to update add/remove components, but when the Editor is in component mode there is the "active" button which doesn't get affected leading to the icon being duplicated.
The switcher now checks if it is in component mode before adding / removing components to itself under the assumption that the Entity …
> Bug Fix: Component mode switcher duplicates switcher component icon on undo while in component mode

- Gems/Atom/RHI/Metal/Code/Source/RHI/BindlessArgumentBuffer.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/BufferView.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineState.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/Scope.cpp
- Gems/EMotionFX/Code/Source/Editor/Plugins/ColliderWidgets/ClothJointWidget.cpp
- Gems/EMotionFX/Code/Source/Editor/Plugins/ColliderWidgets/HitDetectionJointWidget.cpp
- Gems/EMotionFX/Code/Source/Editor/Plugins/ColliderWidgets/RagdollNodeWidget.cpp
Small correctness fix for bindless on Mac
> Mac build fixes to do with long being 64 bits on Mac and 32 bits elsewhere.

- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/default_script/cube_icosphere.fbx
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/default_script/default_script.py
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/default_script/default_script.setreg
- AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/scene_scripting_tests.py
This PR adds an auto test to regress the default scene script feature.
test_DefaultBuilderScript_ScriptOnlyRunsOnExpectedAsset does the testing
> {lyn15164} auto test for the default scene script feature

- Code/Framework/AzCore/AzCore/Name/NameDictionary.cpp
- Code/Framework/AzCore/AzCore/Serialization/ObjectStream.cpp
- Code/Framework/AzCore/AzCore/Serialization/SerializeContext.cpp
- Code/Framework/AzCore/AzCore/Serialization/SerializeContext.h
- Code/Framework/AzCore/AzCore/std/hash_table.h
- Code/Framework/AzCore/Tests/Name/NameTests.cpp
- Code/Framework/AzCore/Tests/TaskTests.cpp
This fixes some minor issues found in AzCore as a result of running the AzCore tests with the address sanitizer enabled on Linux.
> Test fixes found with the address sanitizer

- Tools/LyTestTools/ly_test_tools/o3de/editor_test_utils.py
- Tools/LyTestTools/ly_test_tools/o3de/multi_test_framework.py
Signed-off-by: Chiang <evanchia@amazon.com>
Adds additional debug text to EditorTest exceptions
No functional changes, testing in AR.
> Adding additional debug text to editortest exceptions

- .github/CODEOWNERS
Include TestCatalog.cpp under sig-content
Unable to test
> Update code owners - TestCatalog h/cpp

- Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp
> Move default fullscreen state switch to after the initial swap chain has been created

- Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.h
> Fixed compilation error in Metal

- Code/Framework/AzCore/Platform/Common/Apple/AzCore/std/parallel/internal/semaphore_Apple.h
- Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
- Gems/Atom/RHI/Code/Source/RHI/ValidationLayer.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/NullDescriptorManager.cpp
> Fix Mac compilation errors in debug and release configurations

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/ReflectionProbe/EditorReflectionProbeComponent.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/ReflectionProbe/EditorReflectionProbeComponent.h
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/ReflectionProbe/ReflectionProbeComponentController.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/ReflectionProbe/ReflectionProbeComponentController.h
Adds shape translation offset support for reflection probe component.
> Shape translation offset support for reflection probe component

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Overrides/PrefabOverridePublicHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Overrides/PrefabOverridePublicHandler.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Overrides/PrefabOverridePublicInterface.h
Signed-off-by: Nikhil Raktale <raktalen@amazon.com>
The methods were made available in the pyi file
> Exposing PrefabOverridePublicInterface methods to script for automated testing

- AutomatedTesting/Gem/PythonTests/AWS/common/constants.py
- scripts/build/Platform/Linux/build_config.json
- scripts/build/Platform/Linux/deploy_cdk_applications.sh
- scripts/build/Platform/Linux/destroy_cdk_applications.sh
- scripts/build/Platform/Windows/build_config.json
- scripts/build/Platform/Windows/deploy_cdk_applications.cmd
- scripts/build/Platform/Windows/destroy_cdk_applications.cmd
Attempts to fix periodic build errors in the AWS python tests. Subsumes https://github.com/o3de/o3de/pull/13617
Deploys and tests pass for both Windows & Linux in forked [Jenkins job](https://jenkins-pipeline.agscollab.com/job/O3DE-Fork-dev_periodic-incremental-daily-internal/7/).
> Shorten AWSI python test project name formulation

- Tools/LyTestTools/ly_test_tools/o3de/asset_processor.py
A few AR runs have run into issues with parsing the AP logs, so this PR updates the code from splitting from (\r\n) to just splitlines() to normalize the log parsing.
Ran the AR successfully.
> {lyn17246} Update using splitlines() for assetprocessor tools

- Code/Tools/SceneAPI/SceneCore/Containers/SceneGraph.cpp
- Code/Tools/SceneAPI/SceneCore/Tests/Containers/SceneGraphTests.cpp
Updated the message for invalid characters in an import scene node name.
Added a test for empty node names.
> {ghi6670} Updated the assert to give some helpful instructions

- Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderOptionGroupLayout.cpp
Signed-off-by: Ethan Chen <ethanchen1227@gmail.com>
Fix #13625
Test on my PC
> Fix the shader option interger range issue

- scripts/build/Jenkins/Jenkinsfile
fix the first run
Signed-off-by: byrcolin <byrcolin@amazon.com>
> fix the first time this is run

- Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/Platform/Mac/Vulkan_Traits_Mac.h
Fixes Mac compile issues
Compiled ASV profile
> Fix Mac compile issues

- scripts/metrics/common/query_metrics.py
This allows metrics stored in .csv files in AWS S3 to be queried. You could also use this to query manually downloaded locally.
Setup dummy .csv files in S3 buckets and ran the script locally with four different scenarios.
> S3 Query Metrics

- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/ComputePassData.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/CopyPassData.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/DownsampleMipChainPassData.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/EnvironmentCubeMapPassData.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/FullscreenTrianglePassData.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/PassData.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/RasterPassData.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/RenderPassData.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/RenderToTexturePassData.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/SlowClearPassData.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/System/PipelineRenderSettings.h
- Gems/Atom/RPI/Code/Source/RPI.Reflect/Pass/PassData.cpp
- Gems/Atom/RPI/Code/Source/RPI.Reflect/System/PipelineRenderSettings.cpp
- Gems/Atom/RPI/Code/atom_rpi_reflect_files.cmake
Moved all Reflect() function implementations from h files to cpp files in RPI gem.
This is to improve compiling time. 
Build AutomatedTesting project and run Editor
> Moved all Reflect() function implementations from h files to cpp files in RPI gem.

- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BreadCrumbs.cpp
Signed-off-by: ShivAlley <shivvalley8@outlook.jp>
Correction of compile errors originating from warnings
I compiled only BreadCrumbs.cpp and confirmed no warnings.
> Suppress warnings generated by Breadcrumbs code

- AutomatedTesting/Gem/PythonTests/Prefab/CMakeLists.txt
This PR opts-in Prefab Python tests to TIAF Python.
This PR will be tested in AR.
> Opt-in Prefabs Python tests to TIAF Python.

- Gems/Atom/RHI/Metal/Code/Source/RHI/BindlessArgumentBuffer.cpp
Signed-off-by: Colin Byrne <byrcolin@amazon.com>
fix compile errors
> fix mac. static cast the 64->32

- scripts/build/Jenkins/Jenkinsfile
- Adds additional checks for null params (as with the case of Multistage pipelines) for non-emgine repo AR runs
- Changes a null pass with an OS compatible command
Tested in a sandbox branch with o3de and o3de-extras repos
> Add null param check and os safe nul pass

- Gems/PhysX/Code/Editor/Source/Components/Conversion/PrefabConversionUtils.cpp
Fixes a compile error in the latest code with the latest compiler.
Compiles and runs correctly.
> Fix for the latest compiler

- Gems/EMotionFX/Code/Source/Editor/Plugins/ColliderWidgets/JointPropertyWidget.cpp
Fixes https://github.com/o3de/o3de/issues/13732
Heavy tested in editor.
https://user-images.githubusercontent.com/69218254/217683949-be692296-bdfd-4740-8915-0b9fc5020396.mp4
> EMFX: Fixes a crash that caused by not hidden the widget when no actor instance is selected

- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentModes/CapsuleViewportEdit.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentModes/SphereViewportEdit.cpp
Fixes collision of constants in anonymous namespaces
Built project
> fix anonymous namespaces colliding in unity build

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/Resources/Icons.qrc
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/Resources/reset_icon.png
- Gems/LyShine/Code/Editor/PropertyHandlerDirectory.cpp
reset button is invalid for direcory handler.
> bugfix for directory handler.

- Gems/LyShine/Code/Editor/CoordinateSystemToolbarSection.cpp
Increase the width of the control.
> Increase the width of the control.

- Code/Framework/AzCore/AzCore/Asset/AssetDataStream.cpp
Using System Allocator to manage instances of `AssetDataStreamPrivate`.
Start `Editor` and open `Sponza`.
> Using System Allocator to manage instances of `AssetDataStreamPrivate`.

- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/EditorVertexSelection.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/Device.cpp
Fixes a couple compile errors that are occurring on Mac OS X.
fixes #14576 
Can build Editor target on Mac.
> Fixes compile errors on Mac

- Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.cpp
The project-path command line parameter s no longer converted into a --regset parameter, instead the FindProjectRoot function directly checks the `--project-path` command line parameter first.
If the --project-path command line parameter is not set, then the first ancestor path of the executable directory that contains a project.json file is used as the project path.
Finally if the previous 2 checks of the `--project-path` command line fails and scanning upwards for a projec.json fails, the `/Amazon/AzCore/Bootstrap/project_path` setting is read to find the project path.
> Update SettingsRegistry project path determination logic

- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentModes/CapsuleViewportEdit.cpp
Fixes #14622 
Followed repro steps and encountered crash without change, did not crash with change.
> fix crash in capsule manipulators

- Code/Editor/TrackView/SequenceBatchRenderDialog.ui
3. Click `Add Sequence`, name it as `1`.
4. Click `Add Director Node`, add two nodes at least.
5. Click Tools -> Render Output, and check options in comboxes.
> bugfix: Increase width of comboxes.

- Code/Framework/AzNetworking/AzNetworking/Serialization/StringifySerializer.cpp
- Code/Framework/AzNetworking/Tests/Serialization/StringifySerializerTests.cpp
- Gems/Multiplayer/Code/Tests/MultiplayerComponentTests.cpp
- Gems/Multiplayer/Code/Tests/NetworkEntityTests.cpp
- Gems/Multiplayer/Code/multiplayer_tests_files.cmake
Added unit tests to test the previously-submitted fixes to StringifySerializer and the serializer helpers to verify that they create unique entries and don't overwrite on serialization.
Also discovered from the unit test that the assert had a condition wrong, so I fixed that too.
Wrote and ran the unit tests.
> Added unit tests for the StringifySerializer and the serializer helpers.

- Code/Editor/TrackView/TrackViewNodes.cpp
I have two screens.
1. Open Editor, at 1st screen.
3. Move `Track View` to 2nd screen.
4. Create a sequence, and create a folder, as follows:
> add parent widget to StringDlg object.

- Code/Editor/TrackView/TrackViewDialog.cpp
3. Create a sequence, named as `1`.
5. Change sequence selection to none.
6. Click `Edit Sequence Properties` in the toolbar, the dialog shows up with properties of sequence `1`.
> fix sequence select/edit.

- Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/SceneManager/ActorPropertiesWindow.cpp
1. Click Tools -> Animation Editor.
2. Click File -> Open Actor.
3. Check `Actor name`, click the input text and select the value, but do not make any change.
4. Click else where.
5. Check `Actors`.
> bugfix: correct change status of "Actor name".

- Code/Editor/TrackView/SequenceBatchRenderDialog.cpp
5. Click Tools -> Render Output, and click Start.
6. Return to Editor, select/transit/rotate/scale a entity.
> Editor is not usable after Render Output is done.

- cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake
- cmake/3rdParty/Platform/Mac/BuiltInPackages_mac.cmake
- cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
This PR makes use of the new AZSLc 1.8.15
Validated all shaders are compiled successfully on Windows, Linux and MacOS.
> Using new AZSLc 1.8.15

- Gems/LmbrCentral/Code/Source/Shape/EditorBaseShapeComponent.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorCapsuleShapeComponent.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorCylinderShapeComponent.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorDiskShapeComponent.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorPolygonPrismShapeComponent.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorQuadShapeComponent.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorSphereShapeComponent.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorTubeShapeComponent.cpp
> bugfix for 3007

- Code/Editor/TrackView/SequenceBatchRenderDialog.cpp
- Code/Editor/TrackView/SequenceBatchRenderDialog.h
5. Click Tools -> Render Output, Add a batch.
6. Change some paramters, and check status of `Update`.
1. Change `Director`.
2. Change `Start frame`.
3. Change `End frame`.
4. Change `Resolution`.
5. Change `FPS`.
7. Change `Format`.
8. Change `File prefix`
> bugfix Update in Render Output dosen't take effect.

- Code/Editor/IEditorImpl.cpp
- Code/Editor/Plugins/FFMPEGPlugin/FFMPEGPlugin.cpp
- Code/Editor/TrackView/SequenceBatchRenderDialog.cpp
Currently, we cannot export videos with Track View.
5. Click Tools -> Render Output, Add a batch.
6. Click `Start`, and wait for its ending, then check the video file.
> bugfix Track View cannot export video.

- Code/Tools/TestImpactFramework/Frontend/Console/Common/Code/CMakeLists.txt
- Code/Tools/TestImpactFramework/Frontend/Console/Common/Code/Source/Platform/Common/Clang/testimpactframework_clang.cmake
- Code/Tools/TestImpactFramework/Frontend/Console/Common/Code/Source/Platform/Common/GCC/testimpactframework_gcc.cmake
- Code/Tools/TestImpactFramework/Frontend/Console/Common/Code/Source/Platform/Common/MSVC/testimpactframework_msvc.cmake
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Headers/TestImpactFramework/TestImpactRepoPath.h
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/Dependency/TestImpactTestSelectorAndPrioritizer.h
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/Process/JobRunner/TestImpactProcessJobRunner.h
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/TestEngine/Common/Job/TestImpactTestEngineJob.h
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Include/Static/TestEngine/Common/TestImpactTestEngine.h
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Source/Platform/Common/GCC/testimpactframework_gcc.cmake
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Source/TestImpactRepoPath.cpp
- Code/Tools/TestImpactFramework/Runtime/Common/Code/Source/TestRunner/Common/Run/TestImpactTestRunSerializer.cpp
- Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/Platform/Common/GCC/testimpactframework_gcc.cmake
- Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestEngine/Native/TestImpactNativeTestEngine.cpp
- Code/Tools/TestImpactFramework/Runtime/Native/Code/Source/TestEngine/Native/TestImpactNativeTestEngine.h
- Code/Tools/TestImpactFramework/Runtime/Python/Code/Source/Platform/Common/GCC/testimpactframework_gcc.cmake
Built TIAF using Windows clang 15.0.0
> Test Impact Analysis Framework clang build fixes

- Gems/AWSGameLift/Code/AWSGameLiftClient/CMakeLists.txt
> Fixed missing build dependency

- Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/DeviceLimits.h
- Gems/Atom/RHI/Code/Source/RHI/RHISystem.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/BufferView.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
- Fix Vulkan crash
- Add support to cache Vk device limits related data
Tested full test suite on Vulkan
> Fix Vulkan crash at boot and cache device limits related data

- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/FrameCaptureTestBus.h
- Gems/Atom/Utils/Code/Include/Atom/Utils/ImageComparison.h
> Fix wrong type info

- AutomatedTesting/Gem/PythonTests/assetpipeline/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/assetpipeline/ap_fixtures/bundler_batch_setup_fixture.py
- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/CMakeLists.txt
- AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/asset_bundler_batch_tests.py
Also added missing sub-directories cmake list for new tests.
Updates Asset Bundler tests to work on Linux.
Locally tested on Linux and Windows.
Additional Notes:
Disabled one of the tests based on issues found in: https://github.com/o3de/o3de/issues/14630
> Updated Asset Bundler tests to work with Linux.

- AutomatedTesting/Gem/PythonTests/editor/TestSuite_Main.py
Disables failing camera test while it is investigated
AR run
> Disable failing camera test

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineState.h
- Gems/Atom/RHI/Metal/Code/Source/RHI/Scope.h
- Gems/Atom/RHI/Metal/Code/Source/RHI/StreamingImagePoolResolver.h
Clean up code that fails to build on macOS.
Fixes a number of compile time errors encountered.
Ran:
```
cmake --build build/mac/. --target Editor --config profile
```
> Fix build for macOS

- engine.json
**This change will be merged AFTER the stabilization/2305 branch is created**
Increment the engine major version to prevent there being any engine version overlap between development and stabilization from this point on.
Related RFC https://github.com/o3de/sig-core/issues/44
n/a this does not change any functionality
> Increment engine major version post stabilization

- Gems/LmbrCentral/Code/include/LmbrCentral/Shape/ShapeComponentBus.h
Removes superfluous warning. Fixes #15141.
AR.
> Remove superfluous shape offset warning

- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/AuxGeom/AuxGeomFeatureProcessor.h
- Gems/Atom/Feature/Common/Code/Source/AuxGeom/AuxGeomFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/AuxGeom/DynamicPrimitiveProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/AuxGeom/DynamicPrimitiveProcessor.h
- Gems/Atom/Feature/Common/Code/Source/AuxGeom/FixedShapeProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/AuxGeom/FixedShapeProcessor.h
This is a possible fix for this random AR failure because of a crash happened when exit editor for a python test.
Tested in Editor with AutomatedTesting project. All aux geom rendering still functional
> random test crash

- Code/Framework/AzNetworking/AzNetworking/Framework/ICompressor.h
- Code/Framework/AzNetworking/AzNetworking/Framework/INetworking.h
- Code/Framework/AzQtComponents/AzQtComponents/AzQtComponentsAPI.h
Resolves broken links in the API Reference (see https://github.com/o3de/o3de.org/pull/2281, where the broken links were identified)
Did not test, as the changes were to a comment
> Fix broken link in the API Reference

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.h
Fixes https://github.com/o3de/o3de/issues/14691
Tested in editor
> Dpe component deletion fix

- scripts/build/Jenkins/Jenkinsfile
- scripts/build/Platform/Linux/build_config.json
- Add stabilization/2305 to the snapshot tags
- Fixes an issue with the snapshot flag being called during the mount action
> Add stabilization/2305 snapshot tag

- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/AuxGeom/AuxGeomFeatureProcessor.h
- Gems/Atom/Feature/Common/Code/Source/AuxGeom/AuxGeomFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/AuxGeom/DynamicPrimitiveProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/AuxGeom/DynamicPrimitiveProcessor.h
- Gems/Atom/Feature/Common/Code/Source/AuxGeom/FixedShapeProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/AuxGeom/FixedShapeProcessor.h
- Gems/Atom/Feature/Common/Code/Source/SpecularReflections/SpecularReflectionsFeatureProcessor.cpp
Cherry pick two AR fixed from stabilization to development
> cherry pick ar fixes from stabilization to development

- Code/Framework/AzCore/AzCore/Asset/AssetCommon.h
Updated comments on AssetLoadBehavior enum to make it more clear what each setting does
None, comment update
> Update asset load behavior comments

- scripts/build/Jenkins/Jenkinsfile
PlatformRm and PlatformRmDir would fail when files were written to workspace with sudo privilege.
> Run PlatformRm/PlatformRmDir with sudo

- Gems/ScriptCanvas/Code/CMakeLists.txt
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasNodeable.xsd
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/CreateSpawnTicketNodeable.ScriptCanvasNodeable.xml
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/DespawnNodeable.ScriptCanvasNodeable.xml
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/SpawnNodeable.ScriptCanvasNodeable.xml
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Time/DelayNodeable.ScriptCanvasNodeable.xml
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Time/DurationNodeable.ScriptCanvasNodeable.xml
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Time/HeartBeatNodeable.ScriptCanvasNodeable.xml
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Time/RepeaterNodeable.ScriptCanvasNodeable.xml
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Time/TimeDelayNodeable.ScriptCanvasNodeable.xml
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Time/TimerNodeable.ScriptCanvasNodeable.xml
- Templates/ScriptCanvasNode/Template/${Name}_files.cmake
- Templates/ScriptCanvasNode/Template/Source/${Name}.ScriptCanvasNodeable.xml
- Templates/ScriptCanvasNode/Template/Source/AutoGen/ScriptCanvasNodeable.xsd
- Templates/ScriptCanvasNode/template.json
Adding a Script Canvas nodeable schema to make Script Canvas node authoring easier and validated when using Visual Studio. 
Using Visual Studio to verify there is auto completion.
> Added schema for Script Canvas node authoring

- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/TableView.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/TableView.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTableModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTableModel.h
This PR adds drag/drop functionality equivalent to that implemented in the thumbnail view to the AssetBrowser tableview. 
> Add drag/drop functionality to the table view.

- Code/Editor/Util/Platform/Mac/FileUtil_Mac.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/Platform/Mac/Vulkan_Traits_Mac.h
Apply mac fixes to stab branch.
> Apply mac compile fixes to stab.  (#15205)

- Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.cpp
When a prefab group exists in the manifest but generation is skipped due to a registry setting, it leaves behind an empty prefab group which causes exporting to fail later on since the group still exists.  This fix causes the group to be removed before skipping the entry and adds an info message to notify users that a registry setting caused generation to be skipped.
Fixes https://github.com/o3de/o3de/issues/15361
Followed repro steps in linked bug and verified asset processes correctly after fix.
> Fix error when prefab generator skips generation

- Code/Framework/AzFramework/AzFramework/Asset/AssetProcessorMessages.cpp
- Code/Framework/AzFramework/AzFramework/Asset/AssetProcessorMessages.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserViewUtils.cpp
- Code/Tools/AssetProcessor/native/AssetManager/AssetRequestHandler.cpp
Fixes bugs #13111 and #15320.
Performed the tests specifies in the bug reports and all working.
> Fixes #13111 and #15320

- Code/Framework/AzFramework/AzFramework/Viewport/ViewportBus.h
Fixes https://github.com/o3de/o3de.org/issues/1028
Updates the API comment for `ViewportRequests`
N/A - comment only change
> Update ViewportRequest interface API comment

- Gems/CameraFramework/Code/Source/CameraRigComponent.cpp
Fixes https://github.com/o3de/o3de/issues/14578
Followed reproduction steps of bug in the Editor.
> Fix CameraRig and Camera dependency

- Tools/LyTestTools/ly_test_tools/o3de/multi_test_framework.py
Creates sub artifact folders for SingleTests. Also saves Game.log and Server.log if they exist.
Tested by running SingleTests locally and checking logs.
> Organizes SingleTests by test case name and saves game/server logs

- Code/Tools/AssetProcessor/assetprocessor_test_files.cmake
- Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
- Code/Tools/AssetProcessor/native/tests/ApplicationManagerTests.cpp
- Code/Tools/AssetProcessor/native/tests/BuilderManagerTests.cpp
- Code/Tools/AssetProcessor/native/tests/PathDependencyManagerTests.cpp
- Code/Tools/AssetProcessor/native/tests/assetmanager/InitialScanSkippingTests.cpp
Cherry pick the follow PRs from dev into stabilization:
https://github.com/o3de/o3de/pull/15385
https://github.com/o3de/o3de/pull/15371
None, this is just a cherry pick of already reviewed code.  There is a set of unit tests that will run on Jenkins to verify
> Asset Processor - Cherry Pick Scan Skipping Fix from Dev

- Code/Editor/splashscreen_background.png
Updates the Editor's splashscreen for the 23.05 release.
> Update Editor splashscreen

- Code/Framework/AzCore/Tests/AZStd/Parallel.cpp
Cherry picks the commits for PR to #15133 and #15276 which
fixes #14536
Built the Parallel.cpp successfully
> Cherry-Pick: Parallel thread test fix

- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/DynamicDraw/DynamicDrawContext.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
Fix transparency sample for ASV + misc cleanup.
Tested ASV
> Fix sort keys for transparent meshes

- Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
Fixes https://github.com/o3de/o3de/issues/15678
Fix invalid access via meshIndex when not all meshes have valid draw packets.
Tested in the Editor using the repro steps from the GHI.
> Fix for GHI-15678 MeshFeatureProcessor crashes with mesh component + invalid material

- Code/Tools/SceneAPI/SceneData/GraphData/MeshVertexUVData.cpp
- Code/Tools/SceneAPI/SceneData/GraphData/MeshVertexUVData.h
- Code/Tools/SceneAPI/SceneData/ManifestMetaInfoHandler.cpp
- Code/Tools/SceneAPI/SceneData/ReflectionRegistrar.cpp
- Code/Tools/SceneAPI/SceneData/Rules/UVsRule.cpp
- Code/Tools/SceneAPI/SceneData/Rules/UVsRule.h
- Code/Tools/SceneAPI/SceneData/SceneData_files.cmake
- Gems/SceneProcessing/Code/Source/Generation/Components/TangentGenerator/TangentPreExportComponent.cpp
- Gems/SceneProcessing/Code/Source/Generation/Components/TangentGenerator/TangentPreExportComponent.h
- Gems/SceneProcessing/Code/Source/Generation/Components/UVsGenerator/UVsGenerateComponent.cpp
- Gems/SceneProcessing/Code/Source/Generation/Components/UVsGenerator/UVsGenerateComponent.h
- Gems/SceneProcessing/Code/Source/Generation/Components/UVsGenerator/UVsGenerators/SphereMappingUVsGenerator.cpp
- Gems/SceneProcessing/Code/Source/Generation/Components/UVsGenerator/UVsGenerators/SphereMappingUVsGenerator.h
- Gems/SceneProcessing/Code/Source/Generation/Components/UVsGenerator/UVsPreExportComponent.cpp
- Gems/SceneProcessing/Code/Source/Generation/Components/UVsGenerator/UVsPreExportComponent.h
- Gems/SceneProcessing/Code/Source/SceneProcessingModule.cpp
- Gems/SceneProcessing/Code/sceneprocessing_editor_static_files.cmake
- Registry/sceneassetimporter.setreg
Note to reviewers, this PR is already in 'development branch' but this is a PR to get it into the Stabilization branch as an Exception.
I will be adding the exception checklist below.  Please see the original PR for a full brief including pictures of the difference it makes.
https://github.com/o3de/o3de/pull/15530 - solves https://github.com/o3de/o3de/issues/12795 issue.
Without this PR merged, the robotics stuff in o3de-extras will seem incomplete for the release as all models will appear as featureless gray shadeless objects.
The new modifier is implemented in the same UX as the existing modifiers.
https://user-images.githubusercontent.com/70027408/229643430-e28c85ae-4e56-4be2-872c-619650ca2220.png
This PR is a cherry-pick of that squash submission.
* Adds the ability to generate UVs …
> EXCEPTION REQUEST: Adds the ability to generate UVs automatically during mesh import

- Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArrayFeatureProcessor.cpp
**Exception request** -- This PR resolves a crash that occurs when updating a decal's material. As this is a common workflow with decals, I believe this is critical.
A separate [PR](https://github.com/o3de/o3de/pull/15719) for development created. 
Fix decal crash #15190
- Changed how the image asset is verified to correctly catch the missing image error. Previously a broken image was considered valid and failed to be caught. 
- Changed Assert to Error so console can report missing image to the user and Editor can continue safely.
Tested manually by doing the following steps: 
Setup: 
1. Created a new material with a base color texture
2. Added the Decal component to the default ShaderBall
3. Added the material to the Decal component
4. Deleted the base color texture
5. Saved and closed …
> Fix decal crash #15190 (Stabilization request)

- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingCommon.azsli
> Fix light accumulation in SSR raytraced fallback

- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/SimpleSpotLight.azsli
Fixes a typo.
Ran Automated testing
> Fix for a typo related to a previous PR

- scripts/build/bootstrap/incremental_build_util.py
Updates the incremental build script to use token based IMDSv2 endpoints for EC2 instance and EBS volume metadata. This uses an private function inside the botocore IMDSFetcher class
Tested in a sandbox instance
> Incremental build IMDSv2 update

- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracing.shader
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingClosestHit.shader
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingMiss.shader
- Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportScene.cpp
Fixed MaterialEditor support for NoMSAA
Added NoMSAA supervariants to the SSR RayTracing shaders
Tested MaterialEditor DX12/Vulkan
> Fix for MaterialEditor NoMSAA

- Code/Framework/AzCore/Platform/Common/Apple/AzCore/IO/SystemFile_Apple.cpp
- Code/Tools/AssetProcessor/native/AssetManager/SourceFileRelocator.cpp
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracing.shader
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingClosestHit.shader
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingMiss.shader
- Gems/Atom/Feature/Common/Code/Source/Platform/Mac/Atom_Feature_Traits_Mac.h
- Gems/Atom/RHI/Code/Source/RHI/RHIUtils.cpp
- Gems/DiffuseProbeGrid/Code/Source/Components/DiffuseProbeGridComponentController.cpp
- Compile fixes
- AP Shader failure fixes
- Crash fix related to Diffuse probe grid
- Other Mac fixes were merged to stab branch but will be integrated to development soon -  https://github.com/o3de/o3de/pull/15795
Tested AutomatedTesting Editor
> Misc mac fixes that didnt make the cut for the stab branch.

- Gems/Atom/RHI/DX12/Code/Source/RHI/Device.cpp
This fixes a random crash happened when exist MPS. This also fixes a random crash happened with ASV screenshot tests
(https://github.com/o3de/o3de/issues/15850)
MPS: start game launcher then press the Quit button
ASV: run full test suites
> Fixed a random crash related to d3d12ma

- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.cpp
- Fixes #15921 
- Fixes keyboard shortcuts not registering in the table view
- Fixes assets not prompting user for rename when newly created in the table view
Locally
> Fixes right click with multiple selected assets in the thumbnail view

- Code/Framework/AzFramework/Platform/Windows/AzFramework/Windowing/NativeWindow_Windows.cpp
Recent changes to make the windowed version of the Launcher run as a TOPMOST window were making it hard to debug on single-monitor systems. This changes the behavior so that if a debugger is attached, the window will run as NOTOPMOST instead of TOPMOST, so that when hitting breakpoints and crashes, the debugger window will be drawn on top.
Ran the MultiplayerSample Launcher in both windowed and fullscreen mode with and without a debugger attached. 
Switched back and forth between the two modes. 
Alt-tabbed to and from other applications.
All works as expected, except for if the launcher is switched to fullscreen mode and then alt-tabbed away to inactive, the first time this happens, the window can end up in an odd priority state where it might be behind other windows but still on top of …
> Don't make the window topmost with a debugger attached unless it's fullscreen

- Gems/Atom/RHI/DX12/Code/Source/RHI/BufferPool.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/BufferPoolResolver.cpp
This fixes intermittent crashes that could occur in `AZ::RPI::Buffer::UpdateData(const void * sourceData, unsigned __int64 sourceDataSize, unsigned __int64 bufferByteOffset)` from mysteriously invalid pointers.
The root problem was that BufferPool was expanding the size of the m_uploadPackets vector and grabbing a reference into it inside a lock, but then using it outside the lock to call Map(). If expanding the size caused m_uploadPackets to get reallocated, then any other threads that were outside the lock would have an invalid uploadRequest reference, leading to chaos and crashes.
The fix is to declare uploadRequest as a local variable, call Map() outside the lock, and then add uploadRequest into the vector inside the lock. By not holding references to the vector anywhere, the problem …
> Fix Atom buffer crashes due to invalid pointers

- Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridRayTracingPass.cpp
Fixes a crash related to RT PSO creation on machines where RT is not supported
Tested ASV, Editor
> Add support to check RT support before building RT PSOs

- scripts/o3de/o3de/project_manager_interface.py
Fixes detection of remote gem incompatiblities
fixes #15981
Ran Python debugger with use case to verify compatibility check worked correctly
> Fixes detection of remote gem incompatiblities

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.h
Fix Vulkan crash when resizing windows
Fixes #15947 
Run ASV Launcher and Editor while resizing the window
> Fix resize crash on Vulkan

- Gems/ScriptEvents/Code/Include/ScriptEvents/ScriptEventRegistration.cpp
Fixes #15693 .
When ScriptEvents get loaded, if the ScriptEvent asset is already ready by the time ScriptEventRegistration::Init() is called on an asset loading thread, it was possible to trigger an assert on the SystemTickBus when trying to connect because it doesn't have a mutex allowing it to be connected to from multiple threads.
This _could_ be solved by adding a mutex to SystemTickBus, but since most processing occurs within a tick process, the mutex would almost always be locked, so it's not a great solution.
Instead, since the only reason to connect to the bus was to call CompleteRegistration() after the asset is ready, and the only way the assert was triggered was if the asset was already ready and CompleteRegistration() had already been called, a better choice is to skip the …
> Fix ScriptEvent SystemTickBus assert

- Templates/RemoteRepo/Template/repo.json
- Templates/RemoteRepo/preview.png
- Templates/RemoteRepo/template.json
- engine.json
This PR creates a Remote Repo template for users interested in sharing their personal projects/gems online
We run the create-from-template function from CLI and added the relevant variables and made sure the correct information was produced in the generated repo.json file
command used: `./o3de.bat create-from-template -tn RemoteRepo -dp C:\o3de_Projects\create_pathtest_7`
> Added Remote Repository template

- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
Fixes #16066 
There were some cases where the DPE wasn't following the same logic for selecting a node's display label as the RPE. Part of this fix was consolidating the separate checks into a single location for easier readability of how a node's display label is chosen. I also re-worked it to follow a similar logic flow as the method the RPE uses (`AzToolsFramework::GetNodeDisplayName`).
This method will be expanded in further PRs as we handle some of the more complicated label name override cases (which the RPE handles in a different method by modifying the `m_name` in the metadata prior to reaching `GetNodeDisplayName`).
Two other changes made during this PR:
1. Changed the `EnumerateInstanceCallContext` to use the `ENUM_ACCESS_FOR_READ` instead of write. The RPE also uses the read …
> Fixed some node display label handling in DPE

- Code/Framework/AzFramework/Platform/Windows/AzFramework/Windowing/NativeWindow_Windows.cpp
- Gems/Atom/RHI/Code/Source/RHI/Device.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/CommandListBase.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/CommandQueueCommandBuffer.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/Scope.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/Scope.h
- Better gpu markers for metal backend
- Ability to switch to Renderdoc/pix in order to do a gpu capture
- Disable bindless related asserts for null rhi
Tested with ASV
> A few quality of life fixes

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
Fixes #15953 
This fix now makes it possible to write property value changes to the DOM for property types whose handler is for a sub-class (generic class info). The best use-case of this is being able to modify asset properties, which previous would cause a DOM error and throw many errors to the console.
The underlying issue is that for most properties, there is a handler for that exact type (e.g. primitives, AZ::Vector3, etc...) so we can infer the type from the value itself, for which we can just use `ValueFromType` when writing out the new value to the DOM. However, this fails for things like asset properties where there is a default handler for the underlying asset type `AZ::Data::Asset<AZ::Data::AssetData>`, but the actual type for the property is a derived class (e.g. …
> Fixed assigning asset properties in the DPE

- Gems/Atom/Feature/Common/Assets/Passes/PassTemplates.azasset
- Gems/Atom/Feature/Common/Assets/Passes/ReflectionScreenSpace.pass
- Gems/Atom/Feature/Common/Assets/Passes/ReflectionScreenSpaceBlur.pass
- Gems/Atom/Feature/Common/Assets/Passes/ReflectionScreenSpaceBlurHorizontal.pass
- Gems/Atom/Feature/Common/Assets/Passes/ReflectionScreenSpaceBlurVertical.pass
- Gems/Atom/Feature/Common/Assets/Passes/ReflectionScreenSpaceComposite.pass
- Gems/Atom/Feature/Common/Assets/Passes/ReflectionScreenSpaceDownsampleDepthLinear.pass
- Gems/Atom/Feature/Common/Assets/Passes/ReflectionScreenSpaceDownsampleDepthLinearChild.pass
- Gems/Atom/Feature/Common/Assets/Passes/ReflectionScreenSpaceTrace.pass
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceBlurCommon.azsli
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceBlurHorizontal.azsl
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceBlurVertical.azsl
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceComposite.azsl
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceDownsampleDepthLinear.azsl
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceDownsampleDepthLinear.shader
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceFilter.azsl
- Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceTrace.azsl
- Gems/Atom/Feature/Common/Code/Source/CommonSystemComponent.cpp
- Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceBlurChildPass.cpp
- Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceBlurChildPass.h
- Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceBlurPass.cpp
- Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceDownsampleDepthLinearChildPass.cpp
- Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceDownsampleDepthLinearChildPass.h
- Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceDownsampleDepthLinearPass.cpp
- Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceDownsampleDepthLinearPass.h
- Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceTracePass.cpp
- Gems/Atom/Feature/Common/Code/Source/SpecularReflections/SpecularReflectionsFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/atom_feature_common_files.cmake
Added Bilateral Filtering to the SSR roughness blur.
Added Downsampled Linear Depth passes.
> SSR Bilateral Filtering

- scripts/o3de/o3de/repo_properties.py
- scripts/o3de/tests/test_repo_properties.py
Add Unit test to make sure the sha256 and URL is being updated by using the existing function validate_downloaded_zip_sha256 in download.py file to validate.
Passed Unit test by calling the edit_repo_props function from repo_properties.py file and made sure release_archive_path function got called and correct release archive zip was formed by using the validate_downloaded_zip_sha256 in download.py file.
> Add Unit Test For Create Archive Path CLI Function

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/BindlessDescriptorPool.cpp
> Need a null check to address a crash Fix when exiting in Vulkan

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
Fixes #15904 
This fixes a large amount of cases where non-registered attributes weren't being passed on to the property handlers. The DPE logic assumed the attributes would all be registered, but we can't register all of the attributes explicitly because custom attributes can be introduced in gems or by external users. The logic in `LegacyReflectionBridge` does actually try to pass on non-registered attributes as well, but it assumed the `name` of the attribute would be the human-readable name of the attribute (e.g. "ChangeNotify"), but for non-registered attributes the `name` is already the hashed number (e.g. "2934982394").
We have an explicit issue that this resolves, but this actually will restore a lot of additional missing attributes as well. In the case of the `Script Canvas` …
> Fixed missing generic attributes in DPE

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
Fixes #16068 and #16078 
In my previous PR (https://github.com/o3de/o3de/pull/16244), I fixed an issue with generic attributes that aren't explicitly registered not being passed on to handlers properly. At the time, this only supported primitive data types for the attributes (e.g. int, bool, string, etc...). This fix extends the support to also handle opaque values and callbacks.
Here are some example components where this crops up:
BEFORE (Material component is missing custom widget for the material preview thumbnail, which is passed as a custom attribute, and on the Script Canvas component the button to open a script in the Script Canvas Editor doesn't work)
AFTER:
Tested the repro of the mentioned issues, as well as ad-hoc testing (e.g. tested other components with "Open in ... Editor" …
> Handled additional missing custom attributes

- Templates/ScriptCanvasNode/Template/README.md
Minor typo fix: Instanciate -> Instantiate
> Fixed typo in readme

- scripts/build/Jenkins/Jenkinsfile
Removes the Github url regex pattern to allow for usage with other Git services
Tested in sandbox Jenkins
> Use general regex to find repo url

- Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasNodeable.xsd
This PR updates the XML schema for Script Canvas Nodeables and adds documentation. Parts of this PR refer to changes that will be made to the documentation on o3de.org by this PR: https://github.com/o3de/o3de.org/pull/2449
Tested in the Visual Studio Schema Explorer
> Update nodeable XML documentation

- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/BasePBR.materialgraphtemplate
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/StandardPBR.materialgraphtemplate
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test1.materialgraph
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test2.materialgraph
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test3.materialgraph
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test5.materialgraph
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test9.materialgraph
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test_normalmaps.materialgraph
Resaving data with cleaner formatting and updated versioning
Loaded existing graphs
Created new graphs from templates
> material canvas: resaving template files and sample graphs with cleaner formatting

- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ExpanderSettings.cpp
pick DPE fix to stabilization
in Editor
> make sure all path levels get an entry

- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
tolerate null instance attributes, to allow for things like static methods
fixes #16510 
> Fix for instance pointer crash

- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
Minor compile fix for AR. It should fix https://github.com/o3de/o3de-atom-sampleviewer/issues/642
Tested ASV
> Fix release config compile error

- Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceFence.h
- Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceObject.h
- Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDevicePipelineLibrary.h
- Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDevicePipelineState.h
- Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceQuery.h
- Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceQueryPool.h
- Gems/Atom/RHI/Code/Source/RHI/MultiDeviceFence.cpp
- Gems/Atom/RHI/Code/Source/RHI/MultiDevicePipelineLibrary.cpp
- Gems/Atom/RHI/Code/Source/RHI/MultiDevicePipelineState.cpp
- Gems/Atom/RHI/Code/Source/RHI/MultiDeviceQuery.cpp
- Gems/Atom/RHI/Code/Source/RHI/MultiDeviceQueryPool.cpp
This is an alternative to https://github.com/o3de/o3de/pull/16606 using template methods instead of class templates.
Using the RHI tests including the already existing multi device tests.
> Moving the maps into MultiDeviceObject.

- Code/Framework/AzCore/AzCore/DOM/DomUtils.h
- Code/Framework/AzCore/AzCore/RTTI/TypeInfo.h
- fixes reference/pointer mismatches when dereferencing certain opaque values
- fixes #16719 
> fix for opaque wrapper types

- Gems/Atom/RHI/Vulkan/Code/Include/Atom/RHI.Reflect/Vulkan/XRVkDescriptors.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/XR/XRRenderingInterface.h
Remove unused function and class due to the last refactor of the XR interface. I couldn't submit then with the rest of the changes due to the AR system dependency problem.
Run on Quest2
> [OpenXR] Remove unused xr function and descriptor

- scripts/build/Jenkins/Jenkinsfile
Adds a condition for the enable gem step in AR to only trigger if the o3de_projects variable is set. Previously it ran automatedtesting, then looped into empty projects
Tested in a sandbox Jenkins
> Add check to enable gems if o3de_project is set

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp
While using material canvas or manually editing shaders, modifying existing assets, the root asset browser entry class consistently asserts about missing or already registered files and folders. I can only assume that this is going unnoticed either because of different behavior in the main editor, material canvas repeatedly saving over the same files, or because asserts were previously non fatal.
The issue has been reported here: 
https://github.com/o3de/o3de/issues/14772
https://github.com/o3de/o3de/issues/13967
https://github.com/o3de/o3de/issues/11744
https://github.com/o3de/o3de/issues/5407
Tested in main editor and material canvas. Asserts are now reported as warnings and no longer crash after files are modified, added, removed. Hmm
> Root Asset Browser Entry: Change asserts to warnings and cached ptrs

- Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialPipelineSourceData.h
Adding comment about Material pipeline object SRG to address feedback from previous PR
> Adding comment about Material pipeline object SRG to address feedback from previous PR

- Gems/ScriptCanvas/Code/Editor/View/Windows/mainwindow.ui
> Hid the ScriptCanvas commandline, it's experimental and incomplete

- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/AssetEditorToolbar/AssetEditorToolbar.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
- Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.h
Only enable alignment options when multiple nodes are selected
Closes #14577
> Only enable alignment options with multiple selection. 

- Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
Ensures save actions are enabled when a new script is created
Closes #16876
> Script Canvas: Fixed enable save actions on file new

- scripts/build/Platform/Android/gradle_windows.cmd
Cherry picking [fix ](https://github.com/o3de/o3de/commit/ac042819f9176eb87fa554a42a5c61372ba6caaf)for java detection to correct an issue introduced on the jenkins node with an updated windows AMI
> Fixing the gradle_windows.cmd script to set the JAVA_HOME env (#16942)

- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Specific/ImageAttachmentPreviewPass.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Specific/ImageAttachmentPreviewPass.cpp
Adding Image Array support for ImageAttachmentPreview
Tested on internal Meta ASV example.
> Adding Image Array support for ImageAttachmentPreview

- Gems/Atom/RHI/Code/Include/Atom/RHI/DrawItem.h
Will fix https://github.com/o3de/o3de/issues/17018
> Adding default value to enabled flag on DrawItem

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
This addresses a case where a user was setting property values during notifications for materials being created and updated. These notifications are sent after property values for the current tick are applied. Changes made within the notifications would not get applied until other work was queued at a later time.
Testing material editor, material component instance inspector, scripts and tests that change material properties.
> Keep material component connected to tick bus if additional work is queued during notifications

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
Fix validation error on Linux while running the ROSCon2023 demo
Run ROSCon2023 demo (https://github.com/RobotecAI/ROSCon2023Demo/)
> Fix validation error on Linux

- Code/Framework/AzCore/AzCore/DOM/DomComparison.cpp
- Code/Framework/AzCore/AzCore/DOM/DomComparison.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.cpp
Cherry pick of DOM fix from the development branch: https://github.com/o3de/o3de/pull/17041
> add lambda to reject replacement patches on nested rows (#17041)

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
- correctly uses overriden typeID when building the proxy class info for the DPE
- this fixes the m_genericClassInfo consumed by the asset picker when determining what filters/file locations to use for a particular asset type
- fixes #16922 
> fix for typeID in the DPE Inspector

- Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/Limits.h
Remove staging buffer budget limit for all platforms.
Fixes #17007
Run Editor with terrain
> Remove staging buffer budget limit

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
- fix for delayed refresh working on deleted adapters
- Fixes #17070
> fix for crash from delayed refresh on deleted adapters

- scripts/o3de/ExportScripts/export_source_built_project.py
- scripts/o3de/o3de/export_project.py
This PR provides minor corrections to the current PC export script when running it from an SDK installer build.
Testing was performed from a windows laptop using an SDK installer based on latest changes in development. A minimal sample project was used to calibrate the expected behavior of the final release executable.
> adding small fixes for installer sdk on windows

- Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
> Continue CloseAll operation after saving

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DirectionalLightComponentConfig.cpp
Fixes a bug introduced in 298cb5945b35fdc2d016501b5d16235536332292 and reported by Sergey on Discord in sig-build.
> Fixing a logic error.

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.cpp
Updated material component generate source materials with a progress dialog that waits for assets to be added to the catalog
Fixes https://github.com/o3de/o3de/issues/15444
Cleared all of the materials from the sponza entity material component.
Deleted all of the previously generated materials from the project.
Confirmed that generating all of the materials from scratch displays the progress dialog which only progresses after material assets are available and able to be assigned.
Confirmed that this also works for individual material slots.
Confirmed that warning messages in spam no longer appears in the console window or log.
> Fix material component generate source materials warnings/spam caused by assigning assets before they have been added to the catalog

- .gitignore
- Code/Tools/Android/ProjectBuilder/AndroidManifest.xml
- Code/Tools/Android/ProjectBuilder/build.gradle.in
- Code/Tools/Android/ProjectBuilder/gradle.properties.in
- cmake/Platform/Android/LYWrappers_android.cmake
- cmake/Platform/Android/StripDebugSymbols.cmake
- cmake/Tools/Platform/Android/android_post_build.py
- cmake/Tools/Platform/Android/android_support.py
- cmake/Tools/Platform/Android/unit_test_android_post_build.py
- scripts/o3de.py
- scripts/o3de/o3de/android.py
- scripts/o3de/o3de/android_support.py
- scripts/o3de/o3de/command_utils.py
- scripts/o3de/o3de/utils.py
- scripts/o3de/tests/test_android.py
- scripts/o3de/tests/test_android_support.py
- scripts/o3de/tests/test_command_utils.py
This cherry picks the updated android scripts into the point release branch (ref https://github.com/o3de/o3de/pull/17078 )
Unit tests passed
```
λ python\python.cmd -m pytest scripts\o3de
platform win32 -- Python 3.10.5, pytest-7.2.0, pluggy-0.13.1
rootdir: D:\github\o3de, configfile: pytest.ini
plugins: mock-3.8.2, timeout-2.1.0
timeout: 1200.0s
timeout method: thread
timeout func_only: False
collected 540 items
scripts\o3de\tests\test_android.py .x........................
[  4%] scripts\o3de\tests\test_android_support.py ...x......xxxxX....xxxXxxxx......x............
[ 13%] scripts\o3de\tests\test_cmake.py ...................
[ 16%] scripts\o3de\tests\test_command_utils.py ..................x....
[ 21%] scripts\o3de\tests\test_compatibility.py ...........................
[ 26%] …
```
> Cherry Pick Updates for Android scripts into the point release

- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
- properly inherit NameLabelOverride from showChildrenOnly nodes
- allow inherited attributes to overwrite existing empty attributes (needed for existing ScriptEditorComponent quirks)
- fixes #17173 
> fix nameLabelOverride not being inherited for showChildrenOnly nodes

- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
cherrypick the fix nameLabelOverride not being inherited for showChildrenOnly (#17199)
> cherrypick of scriptCanvas DPE fix

- Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentModes/CylinderComponentMode.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentModes/CylinderComponentMode.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentModes/CylinderViewportEdit.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ComponentModes/CylinderViewportEdit.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/CylinderManipulatorRequestBus.h
- Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
- Gems/LmbrCentral/Code/Source/Shape/EditorCylinderShapeComponent.cpp
- Gems/LmbrCentral/Code/Source/Shape/EditorCylinderShapeComponent.h
add edit mode to cylinder component in lmber central.
[Screencast from 2023-12-06 23-00-15.webm](https://github.com/o3de/o3de/assets/854359/7c1399ec-aab4-4257-b6f0-6da56ea77ec6)
ref: https://github.com/o3de/o3de/issues/16996
> feat: add edit mode to cylinder component (GHI-16996)

- Code/Framework/AzFramework/Platform/Android/AzFramework/Windowing/NativeWindow_Android.cpp
Fix render resolution upscale on Android when running in portrait mode
Run Android
> Fix android render resolution

- Gems/Atom/RHI/Code/Tests/MultiDeviceDrawPacketTests.cpp
Attempting to fix build failures on development branch
> Fix multi device draw packet tests failing development build

- Code/Framework/AzCore/AzCore/DOM/DomUtils.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
Cherry-picks approved fixes from development, mostly pertaining to DPE's handling of containers
> DPE fixes cherry-picked from development

- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/StandardPBR.materialgraphtemplate
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/Scene/time.materialgraphnode
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/View/viewworldposition.materialgraphnode
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/StyleSheet/materialcanvas_style.json
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test2.materialgraph
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test5.materialgraph
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test8.materialgraph
- Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test_view_position.materialgraph
Created node to read a view world position from material canvas node
Created test graph to demonstrate the node
> Material canvas view world position node and test graph

- Gems/MiniAudio/Code/Source/Clients/MiniAudioImplementation.cpp
Cherry picks a fix from the point release branch https://github.com/o3de/o3de/pull/17388
- see https://github.com/o3de/o3de/pull/17388 for testing details
> Cherry pick MiniAudio compile fix

- Gems/Atom/RHI/Metal/Code/Source/RHI.Builders/ShaderPlatformInterface.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/Device.cpp
- Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.cpp
- Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/GraphOutliner/GraphOutlinerTableModel.cpp
Fixes various Mac related compile fixes
Tested by compiling on Mac
> Mac compile fixes

- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
fixes adding of container elements for containers with dynamic element types
fixes #17365
minor formatting fixes from the auto formatter
> fix element add for containers with DynamicElementType

- Gems/AtomLyIntegration/AtomViewportDisplayInfo/Code/Source/AtomViewportDisplayInfoSystemComponent.cpp
Fixes a bug introduced in #17234.
> Fixing a string use after free memory bug.

- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/ColorPicker.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/ColorPicker/ColorController.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/ColorPicker/ColorController.h
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/ColorPicker/ColorGrid.cpp
- Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/ColorPicker/ColorGrid.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabOverrideLabelHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabOverrideLabelHandler.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/PropertyHandlerWidget.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/LabelHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/LabelHandler.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/MultiLineTextEditHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/MultiLineTextEditHandler.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyBoolRadioButtonsCtrl.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyBoolRadioButtonsCtrl.hxx
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyCheckBoxCtrl.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyCheckBoxCtrl.hxx
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyDoubleSpinCtrl.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyDoubleSpinCtrl.hxx
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
cherry picks several DPE fixes from development for the point release
> cherry pick DPE fixes from development

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/AssetPlatformComponentRemover.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
Fix small int conversion issues that generate warnings that could halt some builds.
> Fix int conversion warnings.

- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/ContainerActionButtonHandler.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/ContainerActionButtonHandler.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/GenericButtonHandler.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/GrowTextEdit.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/GrowTextEdit.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
Includes these changes:
- https://github.com/o3de/o3de/pull/17472
- https://github.com/o3de/o3de/pull/17482
- https://github.com/o3de/o3de/pull/17516
- https://github.com/o3de/o3de/pull/17530
> Cherry-pick DPE fixes to point-release 23.10.3

- Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceDispatchItem.h
- Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceFence.h
- Gems/Atom/RHI/Code/Source/RHI/MultiDeviceFence.cpp
Introduce minor fixes/updates to the MultiDevice RHI classes which are necessary to use them in the RPI.
`Gem::Atom_RHI.Tests.main`
`Gem::Atom_RPI.Tests.main`
> Multi device resources DispatchItem Fence fixes

- Gems/Atom/RHI/Code/Source/RHI/RHISystem.cpp
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Model/ModelLod.h
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Shader/ShaderResourceGroup.h
- Gems/AtomTressFX/Code/Rendering/HairCommon.h
- Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGrid.h
Reverts some formatting changes and a small compile fix for release builds with clang.
> Multi device minor fixes

- Code/Editor/Objects/EntityObject.cpp
this is entirely unused in the current implementation.
> feat: remove unused CUndoAttachEntity

- Code/Editor/Controls/SplineCtrlEx.cpp
- Code/Editor/Controls/TimelineCtrl.cpp
- Code/Editor/Controls/WndGridHelper.h
- Code/Editor/TrackView/TrackViewSplineCtrl.cpp
- Gems/LyShine/Code/Editor/Animation/Controls/UiSplineCtrlEx.cpp
- Gems/LyShine/Code/Editor/Animation/Controls/UiTimelineCtrl.cpp
- Gems/LyShine/Code/Editor/Animation/UiAnimViewSplineCtrl.cpp
This just replaces Vec2 with AZ::Vector for WndGridHelper.
> feat: migrate WndGridHelper from Vec2 to AZ::Vector

- Code/Framework/AzCore/AzCore/DOM/DomUtils.h
- Code/Framework/AzCore/AzCore/DOM/DomValue.cpp
- Code/Framework/AzCore/AzCore/DOM/DomValue.h
- Code/Framework/AzCore/AzCore/RTTI/ReflectContext.h
- Code/Framework/AzCore/AzCore/Serialization/EditContext.h
- Code/Framework/AzCore/Tests/AttributeDomInteropTests.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/AggregateAdapter.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyRowWidget.cpp
Fixes https://github.com/o3de/o3de/issues/17740
Original PR by @lemonade-dm : https://github.com/o3de/o3de/pull/17031
> [Cherry-pick] fix to ChangeValidate functions not triggering in Property Editors.

- AutomatedTesting/Gem/PythonTests/editor/TestSuite_Main.py
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabDetachPrefabAndRemoveContainerTests.cpp
The development branch is currently broken due to unreferenced arguments warnings as errors
Closes #17790
> Fixed unreferenced argument warnings

- Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/PassDescriptor.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
Cherry picks a fix for the editor crashing on a first time run on Linux from https://github.com/o3de/o3de/pull/17769
Same as https://github.com/o3de/o3de/pull/17769
> Cherry Pick fix linux editor first time crash

- scripts/build/Jenkins/Jenkinsfile
- Adds snapshot attributes for point-release and hotfix targets. 
- Adds additional string search based on target branch for PR or looks for branches that match the protected branches
Tested in sandbox Jenkins
> Jenkinsfile point-release snapshot attribute

- Code/Framework/AzToolsFramework/AzToolsFramework/ContainerEntity/ContainerEntitySystemComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorPickEntitySelection.cpp
Cherry-pick https://github.com/o3de/o3de/pull/17778 to `23.10.3`
> [Cherry-Pick] Viewport | Allow direct selection of entities inside prefabs in Entity Pick mode

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
Cherry-pick https://github.com/o3de/o3de/pull/17735 to `23.10.3`
> [Cherry-Pick] Prefabs | Select the container of a prefab after instantiation

- Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
- Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.h
- Code/Editor/ViewManager.cpp
- Code/Editor/ViewManager.h
- Code/Framework/AzToolsFramework/AzToolsFramework/API/ToolsApplicationAPI.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/EditorMenu.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/EditorMenu.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/MenuManager.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/MenuManager.h
- Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/MenuManagerInterface.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
Cherry-pick https://github.com/o3de/o3de/pull/17768 to `23.10.3`
> [Cherry-pick] Allow for Entity creation and Prefab instantiation in place via viewport interactions.

- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.h
Note that this ONLY fixes the crash, it does not include any of the prefab detach improvements due to risk.
> cherry-pick crashfix part of PR 17664 from dev into point-release/23103

- cmake/Platform/Common/Install_common.cmake
Add missing file from installer (#17594)
> cherry-pick from development to point-release/23103 PR #17594

- Code/Editor/CryEdit.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTreeToTableProxyModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTreeToTableProxyModel.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetEntryChangeset.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp
A few small improvements for the editor startup time
This is just a cherrypick of the already accepted PR 17697, from development to point-release branch.
> cherry-pick from dev to point-release, PR #17697

- Code/Framework/AzCore/AzCore/Component/Entity.cpp
It turns out that previewing a FBX or other scene
in the asset browser causes the scene to be loaded and compiled (ie, prefab processor runs) in an async thread. 
But that thread sets the name of the container Entity and causes the entity system to send entity name changes from that async thread, even though the entity is temporary and inactive (and will never be active).
This can fix flaky tests which are crashing due to the error 
```
Bus const char *__cdecl AZ::EBus<class AZ::EntitySystemEvents,class AZ::EntitySystemEvents>::GetName(void) has multiple threads in its callstack records. Configure MutexType on the bus, or don't send to it from multiple threads
```
* running AR locally.  but its a flaky test, so it doesn't prove much
* adding prefabs, clicking around fast in the Asset …
> PointRelease - Fixes a flaky test and possible actual crash - not a cherrypick

- engine.json
Updates the engine version to 2.2.2 for sync with the 23103 point release
Run in a Jenkins branch
> Update engine version to 2.2.2

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetEntryChangeset.cpp
Fixes https://github.com/o3de/o3de/issues/17824
This does not address the true root cause, but it addresses a change in behavior that introduced this problem. The introduction of a limit on the number of changes that the Asset Browser change set [s_BatchSize](https://github.com/o3de/o3de/blob/8c687c85c361115b625bdb391a0693c791cc1c86/Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetEntryChangeset.cpp#L27) was introduced in a [PR](https://github.com/o3de/o3de/pull/17697/files) to improve the editor startup time. Before this change, it would loop through all of the pending changes in the change set at every interval. However, in the case of the reported GHI, the following actions were happening:
* When a script canvas asset is changed and updated, a change event is …
> Fix pending change starvation causing Asset Browser not to recognize Script Canvas assets after an edit

- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetEntryChangeset.cpp
This cherry picks in a [fix](https://github.com/o3de/o3de/pull/17847) for script canvas and asset browser to go into the stabilization 2310.3 branch
Testing done on development
> Cherry Pick [#17847](https://github.com/o3de/o3de/pull/17847) into stabilization/2310.3

- Code/Framework/AzCore/AzCore/Math/Quaternion.cpp
- Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_QuaternionFunctions_CreateFromValues.names
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Math/Quaternion.ScriptCanvasFunction.xml
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Math/Quaternion.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Math/Quaternion.h
Closes #17843
Adds support for Quaternion CreateFromValues as requested, also added it to the BehaviorContext binding to ensure Lua has the same functionality
> ScriptCanvas support Quaternion CreateFromValues

- Code/Framework/AzCore/AzCore/Debug/Trace.cpp
- Code/Framework/AzCore/AzCore/Debug/Trace.h
- Code/Framework/AzCore/Platform/Linux/AzCore/Debug/Trace_Linux.cpp
- Code/Legacy/CrySystem/Log.cpp
Adds console logging back to Linux.  Without this, only some logs will print out to the stdout.  Code largely pulled from the iOS version of the same file.
Built and tested on an ubuntu 20.04 VM.
> Added Linux Console Logging

- README.md
Added links to both the website roadmap (easiest to understand quickly) and the github roadmap (tracks progress against roadmap items)
> Update README.md to add links to the roadmap

- Gems/EMotionFX/Code/Tests/EmotionFXMathLibTests.cpp
This just standardizes the math test cases for emotionFX. replace the test setup logic with existing utilities from AZ math.  
run emotionFX unit tests.
> feat: standardized math test cases for EmotionFX

- Code/Editor/TrackView/TrackViewAnimNode.cpp
- Code/Editor/TrackView/TrackViewTrack.cpp
- Code/Editor/TrackView/TrackViewTrack.h
- Code/Legacy/CryCommon/IMovieSystem.h
- Gems/LyShine/Code/Editor/Animation/UiAnimViewTrack.cpp
- Gems/LyShine/Code/Editor/Animation/UiAnimViewTrack.h
- Gems/LyShine/Code/Include/LyShine/Animation/IUiAnimation.h
- Gems/LyShine/Code/Source/Animation/AnimSplineTrack.h
- Gems/LyShine/Code/Source/Animation/AnimTrack.h
- Gems/LyShine/Code/Source/Animation/CompoundSplineTrack.cpp
- Gems/LyShine/Code/Source/Animation/CompoundSplineTrack.h
- Gems/Maestro/Code/Source/Cinematics/AnimSplineTrack.h
- Gems/Maestro/Code/Source/Cinematics/AnimTrack.h
- Gems/Maestro/Code/Source/Cinematics/CompoundSplineTrack.cpp
- Gems/Maestro/Code/Source/Cinematics/CompoundSplineTrack.h
This should be a straight conversion to AZ::Vector3 for OffsetKeyPosition
> feat: migrate OffsetKeyPosition for AZ::Vector3 for CTrackViewTrack

- Code/Framework/AzFramework/AzFramework/Entity/EntityDebugDisplayBus.h
@spham-amzn this addresses your comments from:  https://github.com/o3de/o3de/pull/17893 
Address the comments for the listed PR:
> feat: address comments for IRenderAuxGeom

- Code/Tools/AssetProcessor/native/AssetManager/AssetRequestHandler.cpp
- Code/Tools/AssetProcessor/native/AssetManager/FileStateCache.cpp
This is just cherry-picking some minor fixes that were made to PRs that themselves were cherrypicked into point release.
To make the flow more clear, this happened
* 2 different bugs were fixed in development, and passed AR and PR
* PR was performed, updated for stuff found in the reviews, finalized.
* submitted, development green
* the 2 PRs were then opened to cherry-pick the 2 bug fixes from development to point-release
* additional issues were found during the cherry-pick which found a const problem and a spelling mistake during pr in point-release of the already commited dev commits.
* These issues were then fixed in point release, and submitted.
* This PR has been created to bring those minor additional fixes back into development so that nothing is forgotten.
> Cherrypick pr fixes from pointrelease to development

- Code/Framework/AzCore/AzCore/Component/Entity.cpp
Cherry-pick of PR #17826 to development branch from point release commit 458541f
It turns out that previewing a FBX or other scene
in the asset browser causes the scene to be loaded and instantiated (ie, prefab processor runs) in an async thread.  But that thread sets the name of the container Entity and causes the entity system to send entity name changes from that async thread, even though the entity is temp and inactive.
Tested by running the tests, but also manually clicking thru lots of different FBXs in the AB that produce procprefabs while having the inspector open on the scene settings page at the same time.
> Fixes a flaky test and possible actual crash (cherrypick from point-release to dev)

- Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiPassTree.inl
This PR shows the device index if there are multiple devices available
Self tested on windows with one and two devices.
> Show pass execution device index if multi devices are available

- Gems/RemoteTools/Code/CMakeLists.txt
- Gems/RemoteTools/Code/Source/RemoteToolsSystemComponent.cpp
- Gems/RemoteTools/Code/Tests/RemoteToolsTest.cpp
Cherry pick [pr-1790](https://github.com/o3de/o3de/pull/17902/files) into stabilization. Fixes remote tools debug
> Cherry pick pr-17902 into stabilization

- Code/Framework/AzCore/AzCore/Component/Entity.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserBus.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserComponent.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserComponent.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.h
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTreeToTableProxyModel.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.h
- Code/Tools/AssetProcessor/native/AssetManager/AssetRequestHandler.cpp
- Code/Tools/AssetProcessor/native/AssetManager/FileStateCache.cpp
Cherry pick: 
PR https://github.com/o3de/o3de/pull/17839
PR https://github.com/o3de/o3de/pull/17838
PR https://github.com/o3de/o3de/pull/17874
* Crash fix for entity name change.
* Crash fix for AB thumbnail generator
* Slight Perf fix for AB startup time.
* Fix for editor crashing if you click AP full refresh button while its running.
into Stabilization.
these PRs were released in the Point Release, but never made it from the point release to Development before the Stabilization branch was cut.  They were merged into development, but only after that branch was cut.
> cherrypick some PRs that made it into pointrelease but didn't make it into dev in time

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/AsyncUploadQueue.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphCompiler.cpp
- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/AttachmentReadback.cpp
This PR cherry-picks #17969 from development to stabilization/2409
Tested with various atom sample viewer samples, and a simple test level in the editor
> Cherry-pick "Fix vulkan fence synchronization (#17969)" to stabilization/2409

- Docker/Dockerfile
- Docker/README.md
- Docker/build.sh
- Docker/entrypoint.sh
This PR adds Docker support for O3DE to run from a Docker container, using mapped volumes for persistence of data.
Followed the steps to create both a basic and ROS2 based Docker container, and created a new project (on Linux)
> O3DE Docker support

- Gems/Atom/RHI/Code/Source/RHI/FrameGraphCompiler.cpp
Hopefully fixes #18068.
As described in #18068.
> Bugfix for #18068: Device lost on Vulkan when switching levels on AutomatedTesting

- Gems/Atom/RHI/Code/Source/RHI/RayTracingAccelerationStructure.cpp
Fixes compilation of development.
Compiled.
> Compile fix for recent overlapping PR merges.

- Code/Tools/Android/ProjectGenerator/main.py
This fixes the alignment of the edit boxes in the Android Project Generator, and adds some additional organizations using Label Frames from tkinter.
The original Android Project Generator 
The updated aligned Android Project Generator
Generated an android project for existing O3DE Project using the tool from the Project Manager (o3de)
> Fix alignment issues in the Android Project Generator

- Code/Tools/Android/ProjectGenerator/main.py
This cherry picks the alignment fix for the Android Project generator (https://github.com/o3de/o3de/pull/18129)
Tested on Linux and Windows
> Fix alignment issues in the Android Project Generator (#18129)

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/AliasedHeap.cpp
> Cherry-picking #18148 from development

- Code/Framework/AzFramework/AzFramework/Visibility/OcclusionBus.cpp
- Code/Framework/AzFramework/AzFramework/Visibility/OcclusionBus.h
- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h
- Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
- Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Culling.h
- Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
Cherry picking occlusion request bus interface changes from development branch
Built and tested MPS on stabilization branch
> Cherry picking occlusion request bus updates from development branch

- Code/Tools/ProjectManager/Source/ProjectButtonWidget.cpp
- Code/Tools/ProjectManager/Source/ProjectExportWorker.cpp
- scripts/o3de/o3de/export_project.py
This is a small PR to address minor fixes brought up in the following PR: https://github.com/o3de/o3de.org/pull/2578
> Export Button Fixes

- Gems/PhysX/Core/Code/Source/ArticulationLinkComponent.cpp
This PR prevent crash when one tries to spawn PhysX5 articulation when no Physics scene is available. 
Articulation is created in non-operative state, but we prevent UB.
Added code to spawn prefab and execute it with console with no level loaded.
Fixes #18214
> Prevent crash when articulation is created without Physics Scene

- Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/Serialization/Locale_UnixLike.h
Cherry Picks https://github.com/o3de/o3de/pull/18301 
* Fix compile error for Mac
> Cherry Pick : Fix compile error for Mac

- Code/Legacy/CryCommon/Mocks/ICryPakMock.h
Removing use of auto() for creating mock_method fixes compiler error
Fixes #18324 
Build MaestroTest and see that it compiles and test pass
> Maestro Compiler Error Fix

- Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp
- Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.h
- Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.cpp
- Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.h
- Code/Framework/AzFramework/Platform/Linux/AzFramework/AzFramework_Traits_Linux.h
- Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp
Revert an unnecessary fix
This reverts commit 138d316321a554746623ec54508435e4ffadff5f.
Followed https://github.com/o3de/o3de/issues/18344 steps
> Revert "Fix hyper-sensitve camera rotation remote clients (#18354)"

- Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp
Temporary fix of #18111 and #18305
See #18111
> Porting #18334 for a temporary fix of #18111 and #18305.

- Code/Editor/IEditor.h
- Code/Editor/IEditorImpl.cpp
- Code/Editor/IEditorImpl.h
- Code/Editor/Lib/Tests/IEditorMock.h
- Code/Editor/Settings.h
- Code/Editor/Viewport.cpp
A lot of this functionality doesn't seem to be used anywhere in the editor. it should be safe to remove all this from IEditor.
> feat: remove unused code from IEditor

- Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp
The BRDFTexture so far only gets generated on device 0. This patch generates it on all available devices.
In a multi-device sample that uses the BRDFTexture.
> Multi-device support for the BRDF texture generation.

- Code/Editor/IEditor.h
- Code/Editor/IEditorImpl.cpp
- Code/Editor/IEditorImpl.h
- Code/Editor/Lib/Tests/IEditorMock.h
- Code/Editor/Viewport.cpp
- Code/Editor/Viewport.h
doesn't seem like SetReferenceCoordSys is ever called, something seems wrong with how this works with the viewport? wonder if something was broken or is this logic unused?
> feat: remove GetReferenceCoordSys

- Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
With multiple pipelines per scene or when the pipeline got rebuilt, adding the RTACPs didn't work properly.
In the editor of a test project using a ray-tracing debug component and having multiple pipelines (preview pipeline in addition).
> Fixing adding RTACPasses for multiple devices

- Code/Framework/AzCore/AzCore/Math/Quaternion.cpp
- Code/Framework/AzCore/AzCore/Math/Transform.cpp
Expose useful member functions to the behavior context.
Tested in a small LUA script.
> Expose math members to behavior context level

- Assets/Editor/Scripts/TrackView/example.py
Fixed the TrackView Python example script to use the correct API
Closes #6965 
Followed the steps in the provided video in #6965 and instead of an error the new output is:
```
PyTrackViewGetNumSequences called
(python_test) - Created new sequence Test Sequence 01
(python_test) -
PyTrackViewGetNumSequences called
(python_test) - Number of Sequences: 1
(python_test) -
PyTrackViewGetNumSequences called
(python_test) - Sequence: Test Sequence 01
(python_test) -
(python_test) - Time Range - Start: 0.0 End: 10.0
(python_test) -
```
> Fixed TrackView example Python script

- Gems/Atom/RPI/Code/Source/RPI.Public/Pass/CopyPass.cpp
The CopyPass gets optional device indices for the source device and destination device. These are `-1` by default. When `-1` is supplied the CopyPass should fall back to using the default device. The scope queries introduced in https://github.com/o3de/o3de/pull/18463 did not implement this fallback.
This PR adds a check and sets the device index to `DefaultDeviceIndex` if the value is `-1` .
Tested with a Gem that inserts a CopyPass without supplying device indices
> CopyPass: Fix device index for queries

- Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpSocket.cpp
- Code/Framework/AzNetworking/AzNetworking/Utilities/IpAddress.cpp
- Code/Framework/AzNetworking/AzNetworking/Utilities/IpAddress.h
- Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Multiplayer system checks for invalid IP address and rejects the connection if it's invalid
Fixes #18591
> Multiplayer Gracefully Handles Invalid IP Address

- Code/Framework/AtomCore/AtomCore/Instance/InstanceData.cpp
- Code/Framework/AtomCore/AtomCore/Instance/InstanceDatabase.h
Fixed two race conditions in InstanceDatabase.
These two race conditions were exposed by unit tests.
The fix was to move decrementing m_useCount inside InstanceDatabase::ReleaseInstance(), which locks
m_databaseMutex first.
```
------------  CASE 1 (Fixed) -----------------------
First race condition (Caused a crash):
Thread 1                                  Thread2
│                                         │
│                                         │
│                                         │
RefCount==1                                  │
RefCount--                                   │
RefCount==0                                  │
InstanceDatabase::ReleaseInstance            │
Thread Yields Just before LOCK MUTEX         │
LOCK MUTEX
FindsTheInstance
RefCount==0
RefCount++
RefCount==1 …
```
> Fixed two race conditions in InstanceDatabase.

- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
- Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
Fixed PreviewRenderer material update crash.
Fixes #18629
Fixes #18630
The crash was originated by `AtomToolsFramework::PreviewRenderer`. And the easiest way to reproduce was by making changes to an active material asset using the MaterialEditor. Order of events for the crash: The MaterialComponentController owned by AtomToolsFramework::PreviewRenderer, detects a change in the material asset and it enqueues MaterialComponentController::InitializeMaterialInstancePostTick in the TickBus which captures the `this` address. Then immediately `MaterialComponentController::Deactivate()` is called. Later, in the next TickBus event, `MaterialComponentController::InitializeMaterialInstancePostTick` is executed with the same `this` pointer that was destroyed in the previous frame.
Solution, added a …
> Fixed PreviewRenderer material update crash.

- Code/Legacy/CrySystem/DebugCallStack.cpp
- Code/Legacy/CrySystem/DebugCallStack.h
- Code/Legacy/CrySystem/IDebugCallStack.h
- Code/Legacy/CrySystem/SystemInit.cpp
Cherry pick https://github.com/o3de/o3de/pull/18608 from dev to point release branch
Local windows build, then used the "crash" command
> Cherry-pick : Built-in Crash Reporter : Fix and improve message box dialogs (#18608)

- Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp
- Code/Framework/AzCore/AzCore/DOM/DomPath.cpp
- Code/Framework/AzCore/AzCore/IO/Streamer/FileRequest.h
- Code/Framework/AzCore/AzCore/IO/Streamer/Statistics.cpp
- Code/Framework/AzCore/AzCore/IO/Streamer/Streamer.cpp
- Code/Framework/AzCore/AzCore/JSON/rapidjson.h
- Code/Framework/AzCore/AzCore/Memory/SystemAllocator.cpp
- Code/Framework/AzCore/AzCore/Memory/SystemAllocator.h
- Code/Framework/AzCore/AzCore/Metrics/EventLoggerReflectUtils.cpp
- Code/Framework/AzCore/AzCore/std/string/conversions.h
- Code/Framework/AzCore/AzCore/std/string/utf8/unchecked.h
- Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/IO/SystemFile_WinAPI.cpp
- Code/Framework/AzCore/Tests/AZTestShared/Math/MathTestHelpers.cpp
- Code/Framework/AzCore/Tests/Name/NameJsonSerializerTests.cpp
- Code/Framework/AzCore/Tests/Serialization/Json/StringSerializerTests.cpp
- Code/Framework/AzCore/Tests/Streamer/SchedulerTests.cpp
- Code/Framework/AzFramework/AzFramework/Entity/SliceEntityOwnershipService.cpp
- Code/Framework/AzFramework/AzFramework/Entity/SliceEntityOwnershipService.h
- Code/Framework/AzNetworking/AzNetworking/Serialization/DeltaSerializer.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.h
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
- Code/Framework/AzToolsFramework/Tests/ActionManager/HotKeyManagerTests.cpp
- Code/Framework/AzToolsFramework/Tests/ComponentAddRemove.cpp
- Code/Framework/AzToolsFramework/Tests/EntityOwnershipService/SliceEntityOwnershipTests.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabTestFixture.h
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUndoEditEntityTests.cpp
- Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUpdateTemplateTests.cpp
- Code/Tools/AssetProcessor/native/unittests/UtilitiesUnitTests.cpp
- Code/Tools/SceneAPI/SceneCore/Containers/GraphObjectProxy.cpp
- Gems/Atom/RHI/Code/Tests/ThreadTester.cpp
With these changes, I was able to run all of the tests in the following folders in debug, with Address Sanitizer enabled.
* Everything in Code/* - so framework, tools, AP, etc.
* Everything In Gems/Atom* - so all atom tests in there.
I plan to do the other miscelaneous gems later.
Note that you will not be able to reproduce this - the current version of GoogleMock has ASAN issues inside it.  I will be following this up with a fix to GoogleMock that upgrades it to the latest version, which has those ASAN issues fixed.  If you do want to test this PR locally WITH ASAN enabled you will have to change Code/Framework/AzTest/CMakeLists.txt to upgrade GoogleTest to the latest version AND disable deprecation warnings globally.
However, doing so requires mass renaming some macros, and thus the …
> Fixes many issues discovered by the Address Sanitizer

- Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.cpp
Fix for shadows not working after switching levels (#18652)
Tested on PC editor
> CherryPick - Fix for shadows not working after switching levels (#18652)

- engine.json
- scripts/build/Jenkins/Jenkinsfile
Updates the engine version to `2.3.2` and the Jenkinsfile to `point-release/24092`
Tested in sandbox
> Update engine.json and jenkinsfile updates for point-release 24092

- scripts/build/build_node/Platform/Windows/install-windows-android.ps1
Updates the Windows Android script for in workflow usage with Github Actions
Tested in a forked repo with a proposed Github Actions workflow
> Update Windows Android script for GHA

- scripts/build/Platform/Android/pipeline.json
Updates the Android platform for NDK 25
Tested in the point-release/24092 branch
> Update Android pipeline.json for NDK 25

- Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.cpp
Closes https://github.com/o3de/o3de/issues/10537
The `CAnimComponentNode::Animate(SAnimContext& ac)` method updated to check for enabled state of sub-tracks.
If there are no keys in a sub-track, or sub-track is disabled, method uses the previous (current) value of animated Entity property for that sub-track, thus essentially making a non-keyed or disabled sub-track a no-op.
Release and Profile Editors run, repro steps from the issue #10537 repeated, correct behavior noted.
https://github.com/user-attachments/assets/f5de8147-aded-47cc-b642-04a5088dc4e9
> [TrackView] Fix Disabling Sub-Tacks.

- Code/Editor/TrackView/TrackViewNode.cpp
Fixes typo made in PR #18766, leading to endless loop in some circumstances.
Sorry.
Profile and Release Editors run, bug fix  noted.
> [Track View] Fix typo made in PR #18766

- scripts/build/build_node/Platform/Linux/install-ubuntu-android-tools.sh
- scripts/build/build_node/Platform/Linux/install-ubuntu-build-tools.sh
- scripts/build/build_node/Platform/Linux/install-ubuntu.sh
Fixes the Linux Android install scripts, as they run into syntax errors during GHA AR runs
Tested in my AR branch. Test run in GHA AR here: https://github.com/amzn-changml/o3de/actions/runs/14160266382/job/39664749043
> Linux Android install script fixes

- scripts/build/Platform/Linux/build_config.json
- scripts/build/Platform/Windows/build_config.json
Disables failing tests for Github Actions AR as discussed in https://github.com/o3de/o3de/pull/18605#issuecomment-2770596417
Tested in my fork using Github Actions AR: https://github.com/amzn-changml/o3de/actions/runs/14211807408
> Disable failing tests for AR

- Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpConnection.cpp
fixes https://github.com/o3de/o3de/issues/14203 on TCP/IP connections.
Turns out when you connect to the lua editor, it sends a blob of data that contains the names and interfaces for all of the EBUS, classes, functions, etc.  This blob is about 3.5mb in size.
It first generates the blob (about 3.5mb) and after its in one big buffer, sends that blob all at once to the TCP/IP interface.  The interface splits it into ~10k packets, and fills a send ringbuffer up, the ringbuffer has a static storage of 1mb.
That ring buffer does attempt to send all awaiting data each time a packet is queued up in it, but even a localhost TCP/IP connection cannot handle 3mb of data sent to it at once (in the space of a few microseconds). The TCP/IP buffer (of the operating system itself) fills up, and …
> (Stabilization) BUGFIX - lua editor connectivty with ringbuffer error message

- Code/Framework/AzCore/AzCore/RTTI/BehaviorClassBuilder.cpp
- Code/Framework/AzCore/AzCore/RTTI/BehaviorClassBuilder.inl
- Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.cpp
- Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.h
- Code/Framework/AzCore/AzCore/RTTI/BehaviorEBusBuilder.cpp
- Code/Framework/AzCore/AzCore/RTTI/BehaviorEBusBuilder.inl
This is a continuation of #18772, which extracted some templated code into "concrete" functions, thus avoids being expanded per instantiation.
Debug build shows PDB files size reduced ~4.5%.
> More improvements to reduce binary sizes

- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
This is a cherry pick of PR 18732 from development
https://github.com/o3de/o3de/pull/18732
Tested by doing the same steps as in the original bug, but this time with ASAN and Debug enabled, to check for any further issues found.  No issues found.
> (Stabilization) cherry-pick from dev: DPE: Don't request a size update for every Dom change

- Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Core.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Core.h
> Cherry-pick: ScriptCanvas: Fix default file path when saving a new graph

- Gems/Atom/RHI/Code/Source/RHI/FrameGraphCompiler.cpp
Allows transient attachments to be on multiple devices.
This only fixes the validation that checks if attachments are activated more than once: It now checks if attachments are activated more than once per device.
The actual usage on different devices was already working before this PR.
Tested on Windows with the MainRenderPipeline and a custom pipeline that uses transient attachments on multiple devices
> Allow transient attachments to be on multiple devices

- Gems/Atom/RPI/Code/Source/RPI.Public/DynamicDraw/DynamicDrawContext.cpp
This should fix:
https://github.com/o3de/o3de/issues/18769
https://github.com/o3de/o3de/issues/18890
Don't have time to test so if someone working with the stabilization could take over with this change that would be great, thanks
> Fixing DrawLinear issue in DynamicDrawContext caused by GeometryView changes

- engine.json
Updates the engine version and copyright year for the 2505.0 release
Note: Do not merge this into the development branch. This is only for the release
Resolves https://github.com/o3de/o3de/issues/18925
Tested on my fork
> Bump engine.json version for the 2505.0 release and update copyright year

- Code/Framework/AzQtComponents/AzQtComponents/Utilities/ScreenGrabber_mac.mm
- Code/Legacy/CryCommon/Maestro/Bus/SequenceComponentBus.h
- Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineState.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/SystemComponent.cpp
- Gems/Maestro/Code/Source/Cinematics/AnimSplineTrack_Vec2Specialization.cpp
- Gems/Maestro/Code/Source/Cinematics/CaptureTrack.cpp
- Gems/Maestro/Code/Source/Cinematics/GotoTrack.cpp
- cmake/Platform/iOS/RuntimeDependencies_ios.cmake
Fixes compile errors on Mac and ios.
Tested running AutomatedTesting on Mac.
> Addresses compile errors for Mac/Ios

- Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphObjectFactory.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeFabrikNode.cpp
- Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeFabrikNode.h
- Gems/EMotionFX/Code/EMotionFX/emotionfx_files.cmake
This is a draft for [FABRIK](https://www.andreasaristidou.com/FABRIK.html) multi-link inverse kinematic solver. Most part of the code was copied from two-link IK node and there are still problems with the math. The node currently has only one end node, but it might be possible to be extended allow multiple end nodes.
Create the anim graph as the image below
> Add Fabrik blend tree node.

- Gems/Atom/RHI/Code/Include/Atom/RHI/DispatchRaysItem.h
Should fix the issue in #18950.
@kiotk can you please check if that solves the issue for you?
> Fix error appearing when GPU doesn't support ray tracing.

- Code/Editor/splashscreen_background.png
- Code/Framework/AzQtComponents/AzQtComponents/Utilities/ScreenGrabber_mac.mm
- Code/Legacy/CryCommon/Maestro/Bus/SequenceComponentBus.h
- Gems/Atom/Asset/Shader/Code/AZSL/Platform/Android/Vulkan/AzslcHeader.azsli
- Gems/Atom/Asset/Shader/Code/AZSL/Platform/iOS/Metal/AzslcHeader.azsli
- Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/DirectionalLightShadowCalculator.azsli
- Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/IndexableList.h
- Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArray.cpp
- Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArrayFeatureProcessor.cpp
- Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
- Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceSwapChain.h
- Gems/Atom/RHI/Code/Source/RHI/DeviceSwapChain.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI.Builders/ShaderPlatformInterface.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineState.cpp
- Gems/Atom/RHI/Metal/Code/Source/RHI/SystemComponent.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Instance.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.h
- Gems/LyShine/Assets/LyShine/Shaders/LyShineUI.azsl
- Gems/Maestro/Code/Source/Cinematics/AnimSplineTrack_Vec2Specialization.cpp
- Gems/Maestro/Code/Source/Cinematics/CaptureTrack.cpp
- Gems/Maestro/Code/Source/Cinematics/GotoTrack.cpp
- Gems/Terrain/Assets/Shaders/Terrain/TerrainDetailHelpers.azsli
- cmake/Platform/Windows/Packaging/BootstrapperTheme.wxl.in
- cmake/Platform/Windows/Packaging/PostInstallSetup.wxs
- cmake/Platform/iOS/RuntimeDependencies_ios.cmake
- engine.json
Cherry pick missing changes from 24.09.0 (#18396) (#18428) (#18425)
Cleanly merged from main. Test branch installer being created
> Cherry pick changes from 24.09.0 (#18396) (#18428) (#18425)

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
Should fix the issue in #18983
Checked on Windows 10 and Debian GNU/Linux
> fix-vulkan12Features-missassigments

- .github/workflows/android-build.yml
- .github/workflows/linux-build.yml
- .github/workflows/windows-build.yml
- Removes the retry action, as it will run into a max variable length issue
- Fixes the Windows workflow script, as it had Android dependencies that should be removed
- Tested in my fork AR: https://github.com/amzn-changml/o3de/actions/runs/15764916025/job/44439305918
> Remove AR retry action, Windows workflow fixes

- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/PhysicalDevice.cpp
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/PhysicalDevice.h
Fix misassignment, remove duplicate, and correct spelling
> fix-descriptorBindingPartiallyBound-misassignment

- Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
- Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabSaveLoadHandler.cpp
- Code/LauncherUnified/Platform/Android/Launcher_Android.cpp
- Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
- Code/Tools/AzTestRunner/Platform/Android/platform_android.cpp
- Gems/Atom/Feature/Common/Code/Source/CubeMapCapture/CubeMapRenderer.cpp
- Gems/Atom/RHI/Code/Include/Atom/RHI/DispatchRaysItem.h
- Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
- Gems/Camera/Code/Source/CameraComponent.cpp
- Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/AbstractCodeModel.cpp
- Templates/ScriptCanvasNode/Template/${Name}_files.cmake
- Templates/ScriptCanvasNode/Template/CMakeLists.txt
- Templates/ScriptCanvasNode/Template/Source/${Name}.cpp
- cmake/PAL.cmake
- python/python.cmd
- scripts/o3de.py
- scripts/o3de.sh
- scripts/o3de/o3de/android_support.py
- scripts/o3de/o3de/disable_gem.py
- scripts/o3de/o3de/download.py
- scripts/o3de/o3de/engine_template.py
- scripts/o3de/o3de/global_project.py
- scripts/o3de/o3de/register.py
- scripts/o3de/o3de/repo.py
- scripts/o3de/o3de/utils.py
Cherry-picks the below (approved) PRs with no changes.  
These are the ones that caused no merge conflicts or other special changes and needed no human interaction to merge.
Approvals re noted on https://github.com/orgs/o3de/projects/73/views/1
Note that this does not include compiler fixes for [[maybe_unused]] variables with the very latest VC143 compiler or clang20/19.  I will be doing those in a separate change.
* Running CI Build `test_profile_cpu` to PASS
* Manual quick smoke testing - running the editor, CTRL G mode on navigation sample, opening hermanubis_high, opening other samples, making sure no issues occur.
> Cherry pick approved PR's from dev to stabilization

- engine.json
Bumps the engine version for 2505.1
Will be built in AR
> Update engine version for 2505.1

- scripts/signer/Platform/Windows/signer.ps1
Cherry pick of https://github.com/o3de/o3de/pull/19133 to allow MS trusted signing for Windows installer codesigning
Tested in the development branch
> Refactor signer for MS trusted signing (#19133)
